### ISSUE TITLE
[1846] game id 2495 error on entry

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#1000]
Game data linked. Error message on entering game GameError: PRR has 442 and cannot spend 500

https://gist.github.com/KillerOrca/050984cd1600d9e97a6cae1313ba7cb0

**Comment by michaeljb** [comment]
At action 299 (https://www.18xx.games/hotseat/hs_lzykvppa_2495?action=299), the PRR lays a token on the C&WI spot. When you were actually playing the game, the PRR got the token for free, as they had previously bought in the C&WI.

With PR #947, the C&WI was changed such that the purchasing corporation must lay their free token right away, not some time later. So, now when your game is processed, the PRR spends $80 on that token so when they get to trying to buy a train, they're a few dollars short.

I don't know how much pinning @tobymao is doing, but looks like game 2495 could be pinned to fbb7fd02

**Comment by tobymao** [comment]
thanks for looking into this @michaeljb i'm going to just delete this game
