### ISSUE TITLE
18Mag + expansion doesn’t run train.

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10005]
Game 144021

I reported yesterday the bug, but Benjamin Scott has closed the issue without fixing it.

We are playing 18Mag with expansion. The supporter that I have (I am queroscia) allows to add +1 town to a route of one of my companies each OR. Company 5 hasn’t used the capability. I have select the supporter with company 11. So, my 2-train has become a 2+1-train. BUT, when I submit the route, appears a message and the program come back to the moment of choosing the route.
I cannot continue playing because I cannot run the 2+1-train of company 5.

Thanks,

queroscia.

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment]
Sorry about that misunderstanding on my end, reopened https://github.com/tobymao/18xx/issues/9996
