### ISSUE TITLE
[1822MX] Single Token Blocks Route After Upgrade Track from Two single stations to Double Station City 

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#10001]
https://18xx.games/game/142025

At the start of MC's turn in OR 6.2 the NdeM had a token in each of the stations in Guanajuanto Leon (L19).
![image](https://github.com/tobymao/18xx/assets/70117294/e6b73dc7-e965-4746-91f0-1cba265d8449)

The MC upgraded Guanajuanto Leon (L19) by laying tile #207.  The game correctly removed one of the NdeM tokens.
![image](https://github.com/tobymao/18xx/assets/70117294/b11db223-2b0c-46e1-9eb1-9a3ca8fce9cb)

However, the game would not allow the MC's 4 train to serve the route Mexico City - San Luis Potsi.  It seemed to consider Guanajuanto Leon (L19) as blocking the route even though the graphic clearly shows an open station spot.

**Comment by ollybh** [comment]
I'm not able to reproduce this, either in hotseat or by running the game in my development environment. I can't see any recent changes that would have fixed this since the bug was reported, so I'm not sure what was happening here.
