### ISSUE TITLE
[1844] Game hang on attempt to purchase 5 train

### ISSUE THREAD

**Issue by WeeMadAndo** [tobymao/18xx#10010]
https://18xx.games/game/137512

Have attempted to purchase a 5 train which is hanging game. Button goes black indicating a press and game hangs at this point. Unsure of why, but this leads to complex events (company closures and new company formations) in 1844 so could be any number of problems.

Attempted to troubleshoot:

- Purchase 5H instead - same outcome
- Clone game to test in hotseat - same outcome
- Attempted on Win10 PC in different browser (using OperaGX, Chrome, and Edge) - same outcomes
- Attempted on Android device - same outcome

**Comment by ollybh** [comment]
The game is getting caught in a loop with `Engine::Game::G1844::Step::Destination.auto_actions` being called repeatedly.
