### ISSUE TITLE
1825 bug, no action possible.

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#10013]
https://18xx.games/game/139377
Step: 1373

Player "castlerigg" want to make moves for the LNWR.
No action is possible (
pass Track, Comment >> Message
![grafik](https://github.com/tobymao/18xx/assets/80693707/60973223-30e4-450d-ab25-66989274e2f0)

undo, >> Message
![grafik](https://github.com/tobymao/18xx/assets/80693707/480b205f-a974-4d75-b599-f397de7e2236)
each time, there is an error and the game is refreshed.
In a hotseat-game there are no problems.

**Comment by roseundy** [comment]
This was broken with a change for 18ESP.
