### ISSUE TITLE
18AL - 50% train discount from NDY private not being applied after selection

### ISSUE THREAD

**Issue by saccenti** [tobymao/18xx#10023]
I'm stuck in an 18AL game: https://18xx.games/game/144868

Specifically at this point: https://18xx.games/game/144868?action=137

I'm not able to purchase a train with New Decatur Yards. If I understand the rules, I should at this moment be able to purchase the 4T for $150.

**Comment by saccenti** [comment]
See also here: https://github.com/tobymao/18xx/issues/9686

**Comment by saccenti** [comment]
Phil, why did you remove "needs triage" label, without any comment? This is probly a misunderstanding on my end(?) but I don't see how this issue has been addressed.

**Comment by dfannius** [comment]
"needs triage" means that the issue hasn't been classified yet. It has now been classified with the labels "18AL" and "abilities".
