### ISSUE TITLE
1825 bug, no action possible. please finish the game.

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#10029]
https://18xx.games/game/139377
Step: 1373

game is still broken after the last change (https://github.com/tobymao/18xx/issues/10013 and https://github.com/tobymao/18xx/issues/10014 )
Even "End game" isn't possible.

Please finish the game.
regards
Volker

**Comment by roseundy** [comment]
This fix hasn't been deployed yet.
