### ISSUE TITLE
1822 - Cannot sell shares in a company that has already operated

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#10026]
https://18xx.games/game/145168

Trying to sell shares in a company which has completed an operating round, in this case MR shares where I am e-buying a train for Minor 28 immediately following the 1st round MR operated, which should be legal according to Rule 4.4.1 "Shares cannot be sold in a company that has not completed an operating round."

No option for MR sale at this point.

**Comment by philcampeau** [comment]
I suspect this is because of my PR here https://github.com/tobymao/18xx/pull/9989

I'm going to have to look that over.

**Comment by DrPooter** [comment]
Thank you!!
