### ISSUE TITLE
[1846] Erie cannot token Erie

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#1003]
Erie just opened, issued 3 shares, and with the track already in place, should be able to token the reserved spot in Erie, but cannot.

[1846-erie-cannot-token-erie.txt](https://github.com/tobymao/18xx/files/4875530/1846-erie-cannot-token-erie.txt)

**Comment by StormCrow42** [comment]
I imported the game and was able to place the Erie token.

**Comment by tobymao** [comment]
i haven't verified but it looks like this cannot be reproduced, closing for now
