### ISSUE TITLE
[1850] - game #143563 - The game is rejecting a Western Land Grant tile lay on F9 with the message "Paths must be connected".  SOO is connected and it is allowing me to select the tile, then rejecting it incorrectly.

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#10033]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by Doc-Evil** [comment]
I experience the same (bug) several times with the Western Land Grant Corporation. In several places and several devices.
