### ISSUE TITLE
[1822Africa] - Playtest feedback on Train Rush Death Spirals caused by train exports.

### ISSUE THREAD

**Issue by TheTagoreler** [tobymao/18xx#10036]
See: https://18xx.games/game/145246

With the right combination of minors/privates, it is possible for there to be a train rush death spiral that occurs from SR3.  To date, 5 minors had been bought with 5 L/2s sold.  In our case, this occured with players out of money (3 had spent $300 on acquiring a minor/concession combo in SR1/2, and the last player had no concession and did not want to buy another minor).  This resulted in neither of the minors on offer in SR3.1 being bought.  This exported 3 L trains (1 each for M8 and M9 being unsold and 1 extra for M8 being in bid box 1).  In SR3.2, another 2L trains were exported (unsold M9 and M3)  and because M9 was now in bid box 1, it took a 3 train with it.

This resulted in a bunch of 3s being bought out in the OR set, leaving 5s on deck and imminently being exported at the end of this SR (4.1)

Suggest unsold minors in bidbox 1 do NOT remove a train (beyond regular L train) when being removed from the bid boxes for being unsold in the first of two SRs, or, alternatively, capping the "unsold minor in bid box 1" export to one train between the two SRs.

**Comment by scottredracecar** [comment]
See this post for advice about strategy.
https://boardgamegeek.com/thread/3131296/article/43182524#43182524

That thread is the proper place for such discussion.

**Comment by TheTagoreler** [comment]
Ta
