### ISSUE TITLE
[1849K2S] Unable to lay Reggio to Green

### ISSUE THREAD

**Issue by TheTagoreler** [tobymao/18xx#10047]
https://18xx.games/game/145637

SFCS is unable to upgrade Reggio from Yellow to green which has drastically affected its Revenue.

**Comment by scottredracecar** [comment]
Not a bug. It's not allowed to switch track type on a route.

**Comment by TheTagoreler** [comment]
Ah Okay, I see - You need to be able to trace a legal route to upgrade, and it's not a legal route because of the non-city gague switch (thought connectivity was enough).  I'll tell the guy who played the hex leading to Reggio in Narrow gague(not me!) not to do it again in the future.

**Comment by scottredracecar** [comment]
Yeah, my idea there was that you can either do the fast/expensive tile lay or the slow/longer/cheap one. Obviously laying the wrong type is both a waste of money and not very effective for running routes!
