### ISSUE TITLE
1830 - Missing optional 6 train

### ISSUE THREAD

**Issue by systo** [tobymao/18xx#10046]
Game ID: 146318 /https://18xx.games/game/146318

When playing asyc with two physical copies of the game board, the original AH rules allow for an optional 6 train. We played up to the point where the 3rd 6 or first Diesel needed to be bought, and not having that as an option created a cascade of events durastically altering the remainder of game play.

Could the option of adding a third six train be present in the original game, or as a toggle button option when setting up a new game? Also, is there a way to make it optional where you don’t need to buy it and you can go straight to buying a diesel? 

Filing as a bug because it doesn’t match the original rules, but I can understand if this needs to be filed as an enhancement instead.

**Comment by philcampeau** [comment]
Is this an actual variant in the rules? I don't see it in my copy.

**Comment by philcampeau** [comment]
Looks like they do. I'll handle this. 

![image](https://github.com/tobymao/18xx/assets/26125362/e4c66fcb-1942-4636-b18d-1b6fe314c0db)
