### ISSUE TITLE
[1841] The Buy a Token step sometimes locks up the client, requiring a refresh.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10052]
A javascript error sometimes gets thrown on the Buy a Token step, requiring a refresh.

Steps to Reproduce:
Clone the game from https://18xx.games/game/136576?action=1055
On the CTDA's Buy Token step, buy the token from ATFA on H12
Sell shares to EMR an 8 train to complete the CTDA's turn [not relevant]
On the ATFA's turn, skip laying track.
- This will cause the game to hang.
- A subsequent refresh will correct the issue, and bring us to the ATFA's Buy Token step.

The error appears to always occur if you buy a token from another company, and then proceed to that company's buy token step. This is the only consistent repro I have found, but it may not be the only one.

```
Uncaught re {
    "name": "hex",
    "message": "undefined method `hex' for nil",
    "cause": {
        "$$id": 4
    },
    "args": [],
    "backtrace": [
        "https://18xx.games/assets/deps.js:1:14686:in `re.p'",
        "https://18xx.games/assets/main.js:63:111191:in `re.<anonymous>'",
        "https://18xx.games/assets/deps.js:31:36399:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:64:239347:in `re.<anonymous>'",
        "https://18xx.games/assets/deps.js:31:36399:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:65:91542:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:65:93498:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:65:81183:in `re.<anonymous>'"
    ]
}
```

**Comment by roseundy** [comment]
Thanks for the report.

**Comment by roseundy** [comment]
Going from BuyToken to BuyToken w/o a refresh. Need to clear selected_token.
