### ISSUE TITLE
[1822PNW] game cannot proceed due to GameError

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#10065]
[Game](https://18xx.games/game/143212)

Error below:
We're sorry this game cannot be continued due to GameError: dfwinfinitejest (utc-8) still need to sell shares before a loan can be granted
Broken action: { "type": "buy_train", "entity": "20", "entity_type": "corporation", "id": 725, "created_at": 1702567450, "train": "3-0", "price": 200, "variant": "3" }

Trying to take actions results in a new error message: This game is broken and cannot accept any new actions. If this issue has not already been reported, please follow the instructions at the top of the page to report it.

**Comment by kodemaniak** [comment]
I have the same issue in an 1822MRS game:

https://18xx.games/game/145577?action=505

Should I open a separate issue for that one?

**Comment by KillerOrca** [comment]
They're probably related, but since they're different 1822 games I would open a separate one.

**Comment by vandamm** [comment]
Caused by #10059

**Comment by philcampeau** [comment]
@michaeljb ^

**Comment by michaeljb** [comment]
dup #10059
