### ISSUE TITLE
[1825] Game error state has frozen game

### ISSUE THREAD

**Issue by mdwatson** [tobymao/18xx#10085]
https://18xx.games/game/142258?action=506

Game has reverted several ORs and reached a game state from which it cannot progress. Unsure why this happened.

**Comment by roseundy** [comment]
This game was invalidated by this fix: #10016 

Ideally, your game should have been pinned, but it's too late now.

**Comment by roseundy** [comment]
I was leaving this open until the game is archived.

**Comment by mdwatson** [comment]
Just to make sure I understand -- the game cannot be completed, salvaged, or deleted -- correct?

**Comment by roseundy** [comment]
Sadly, correct. This fell between the cracks when the fix was deployed on the server.

**Comment by roseundy** [comment]
Actually, it can be archived (which basically means deleted).
