### ISSUE TITLE
1822 Game error when taking loan

### ISSUE THREAD

**Issue by MasonM42** [tobymao/18xx#10080]
**What's your Game ID?**
142948

We're sorry this game cannot be continued due to GameError: Guido65 still need to sell shares before a loan can be granted
Broken action: { "type": "buy_train", "entity": "7", "entity_type": "corporation", "id": 491, "created_at": 1703224232, "train": "3-5", "price": 200, "variant": "3" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822,%22needs%20triage%22) and include this link (https://18xx.games/game/142948?action=490)

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by vandamm** [comment]
Caused by #10059
