### ISSUE TITLE
[Shikoku 1889] aJogar (Game vanished)

### ISSUE THREAD

**Issue by tdbs** [tobymao/18xx#10092]
Our multiplayer Invite only game of Shikoku 1889 has vanished

Game ID: 147343
Link: https://18xx.games/game/147343

**How to Reproduce the Bug?**
I created the game, 6 people were on it, I started it, and some time after it just vanished.

**Comment by benjaminxscott** [comment]
This is due to one of the players deleting their account, which results in all their games being deleted (wiping their data)
