### ISSUE TITLE
It should be possible to update the description of any hotseat game

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1009]
When trying out different situations in games (for implementation of new features) using Clone is nice.
When I do clone the cloned game gets a description like "Cloned from game hs_tbsbbgrm_1594034348" or similar. 
It would be nice to be able to change the description in these clones to make them possible to more easily tag the games for what they are intended for. Could be via a tag, changing description or similar.

After suggestion by yzemaze I have updated the title to be more general; It would be nice to be able to update the description of any hotseat game.

**Comment by yzemaze** [comment]
I’d like to expand this to: an option to rename any hotseat game.

**Comment by perwestling** [comment]
Yes, renaming hotseat games would accomplish my use case, so I think that is fine.
