### ISSUE TITLE
[1822] market value endgame should take priority over bank breaking

### ISSUE THREAD

**Issue by Randy3535** [tobymao/18xx#10108]
1822 - Game #146150

In Operation Round 10.1, the LNWR concurrently triggered two end game conditions (i.e. its marker hit the top of the market track while concurrently "breaking the bank"). The way I read rule 1.3, the market hitting the top of the chart should be the determining end game trigger, which would end the game at the end of OR 10.1. However, the game is showing game completion at the end of 10.2. ???

Please correct error or provide rule clarification as appropriate.  Thanks

https://18xx.games/game/146150

-->

**Comment by benjaminxscott** [comment]
Thanks for the report of this edge case, this is due to the order in which we check for endgame status

I agree w/ your reading of `1.3` 

![image](https://github.com/tobymao/18xx/assets/1711810/d84f0ccc-a60d-4a51-a13d-986c7a05722d)

**Comment by michaeljb** [comment]
Quoting a few relevant rules from the 2020 edition (where 1.3.1 has been moved to 10.1.1):

> 5.12 Earnings Distribution
> ...
> 5.12.3 If dividends are paid, 10% is paid to the holder of each share. Payments for shares in the company treasury (including the half paid as dividends if the company pays half) go to the company, while payments for shares in the bank pool remain in the bank.
> ...
> 5.12.7 Next, the total dividend paid determines if and how the company’s share price moves.
> ...
> 5.12.10 For a major company, if the total dividend paid is equal to or greater than its share price, but less than twice its share price, its price token is moved one space to the right.
> 5.12.11 For a major company, if the total dividend paid is equal to or greater than twice its share price, the price token is moved two spaces to the right.

> 10 Game End
> 10.1.1 ...
> * If a company’s stock market token reaches the “game end” value on the market during an operating round, the game ends at the end of that operating round.
> ...
> * If the bank runs out of money during an operating round, the game ends after the current set of operating rounds. If 
the bank later becomes solvent the game still ends at that point. The bank continues to pay out per normal, even when 
broken; players should record these, or add money to the bank. Complete these operating rounds even if a company’s 
market value subsequently reaches the game end value.
> ...
>
> 10.1.2 Once the game end has been triggered, the game will end at the indicated time, even if another end condition is triggered after the first.

By 5.12.7, dividends are paid before the stock marker moves, so I'd argue the bank breaking is in fact the first endgame trigger, so the implemented behavior is correct.
