### ISSUE TITLE
[1822PNW] "undefined owner for nil" when minors are merging.

### ISSUE THREAD

**Issue by outsidePasser** [tobymao/18xx#10107]
https://18xx.games/game/147728?action=276

Most likely this is because 10 became the associated minor for NP (10 is the in the same location for the destination for NP).

**Comment by MrSkinny** [comment]
Verified. Looks like there's no implementation for the following section of PNW rules when Backroom Negotiations is used on M3 or M10:

> Exchange the associated minor’s home station (M3 or M10) with the major’s destination station token. Then exchange the unassociated minor’s home station with the major’s home station token. Unlike the normal merger process, both minor
station locations must contain a station token at the end of the merger and only one station token should be left in the available section of the major company’s charter.

During the Merge logic:

* Check if Associated Minor is identified as M3 or M10
  * If yes, bypass `G1822PNW::Step::Merge#process_select_token` method as player does not have choice
  * Set New Major's Home location = Unassociated Minor's home location
  * Set New Major's Destination location = Associated Minor's home location

**Comment by MrSkinny** [comment]
Per PR, turns out no new merge logic needed; it was an issue with the `ability` object.
