### ISSUE TITLE
Entities owned by the bank are not clearly owned by the bank

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1011]

**Comment by tobymao** [comment]
@yzemaze

**Comment by yzemaze** [comment]
@jenf Do you want a header (bar) or what’s the matter?

**Comment by jenf** [comment]
Header would be good, maybe with how much cash left in the bank as well

**Comment by jenf** [comment]
It's not intuitly obvious to me that the columns are player ownership

**Comment by dfannius** [comment]
We could have a bank card just like a corp card, with cash and discarded trains. Theoretically there could even be corp shares there (so every share in the game would be on a player card or the bank card), although maybe that's redundant to a silly extent.

**Comment by yzemaze** [comment]
Like this?
![image](https://user-images.githubusercontent.com/33390595/86628629-737b9780-bfca-11ea-9456-635547fdb4a0.png)
![image](https://user-images.githubusercontent.com/33390595/86628645-78d8e200-bfca-11ea-88e0-d24d4f20f84c.png)

@tobymao "The Bank" already blacklisted/registered? ;)

**Comment by jenf** [comment]
Looks good to me

**Comment by dfannius** [comment]
Yeah, I say let's start with that and tweak later as necessary.
