### ISSUE TITLE
1822CA - Error message/reverts action after making track lay with company

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#10117]
https://18xx.games/game/148122

Currently unable to make a track build with the active company. After pressing Done, the game produces an error message, states auto actions do not match, then reverts back to waiting for track builds to be done.

Bless you kind sir or madam.

**Comment by michaeljb** [comment]
The sample game was pinned for bug fixes, so the underlying issue was either already fixed, or some other unknown thing that cannot be debugged with that sample.
