### ISSUE TITLE
[1841 v1] The SFLi should not operate the turn it is formed.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10118]
In Version 1, the SFLi never operates in the OR in which it is formed.

Repro:
- Clone https://18xx.games/game/145925?action=207
- Buy 3 in the AFI and 3,4 in the CFCC. After resolving Phase 4 events, observe the the SFLi will operate, even though it should not.

The following clause was added in version 2. It is absent in Version 1.
> The SFLi will operate during the Operating Round in which it is formed if none of its components had already operated.

From 1841 Clarifications and Amendments:
> {4.6.9} The SFLi will not run in the round in which it is formed, even if its components have not. This is a side-effect of the standard merge rules. [See [Section 4](http://www.18xx.net/1841/1841f.htm#Section%204), below.]

**Comment by roseundy** [comment]
I will look at this. I never intended to implement the version 1 rules - only the components.

**Comment by roseundy** [comment]
However, this is a simple fix.

**Comment by physic** [comment]
You da man

**Comment by roseundy** [comment]
This will break some version 1 games.
