### ISSUE TITLE
1822CA P30 Remove Single Town Option not available on 2nd yellow lay

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10129]
https://18xx.games/game/148393

On Operating Round 5.1, GNWR acquired P30-RemoveSingleTown and played an initial broad curve north from Duluth.  Prior to the first lay the button to use P30's ability was present.  For the 2nd yellow lay the button disappeared.  

To move the game along I undid the acquisition and will use it on the first yellow lay next turn, but the issue should be fixed.

**Which Browser / Platform?**
- Browser Version:  Firefox 121.0

**Comment by WayneWWms** [comment]
Thanks so much for providing this game on the site.

**Comment by michaeljb** [comment]
Glad you're enjoying the game!

My initial reading of the rules text for P29/P30 was that they used up the Major's full track-laying step, but I can see an argument for it counting as just one yellow tile lay.

> This closes the company and counts as the company’s normal track laying step.

I've posted a question on BGG to follow-up on this and hopefully get an official response (I can email Bob if there's no post there soon) https://boardgamegeek.com/thread/3226011/can-town-removal-p29p30-be-used-turn-where-another

**Comment by michaeljb** [comment]
> Also they say on the private 29/30 can be used together and that doesn't work.

Fixed in 4d0cd8849

**Comment by michaeljb** [comment]
Confirmed via email with the designer that removing the town is a "downgrade" that functions like an "upgrade" using the full tile step, so the implementation is correct.

Thanks for alpha testing and reporting the question!

And @mkkohls thanks for pointing that out, the P29 and P30 descriptions will be updated in the next release.
