### ISSUE TITLE
[1841] Growing up a minor corporation, I should be allowed to buy up to three tokens for L.100 each.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10120]
https://gist.github.com/physic/95210f43d65ed55aaa26a9fa80c099df
?action=341

In the attached game, you can see that the CTS (the newly grown up SFV) has L.231 and two tokens, but is only offered the option to buy one token, rather than the two that it can afford. 

From 4.7.5 Transforming Minor Corporations [after buying a second token for L.50 if necessary]
> The President may buy, with Corporate money, any number of tokens to bring the total number of tokens up to the maximum allowed to a major Corporation (five) at L.100 each

This is a v1 game, but the rule is identical in both versions.

**Comment by roseundy** [comment]
Yep, messed up the calculation.
