### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#10123]
https://18xx.games/game/147861?action=1276 - [gist](https://gist.githubusercontent.com/michaeljb/58a5c07956642ff096be2568fc20af3d/raw/73b5b68c21d5d2c394c16bd333b1e3ee25340e24/147861_at_1276.json)

~Computing the graph~ Rendering the route selector here takes long enough for this message to be displayed in my browser:

![slowing](https://github.com/tobymao/18xx/assets/1045173/63d553e9-56ff-42f2-ae40-e10c887be7d1)

This particular game is 1822CA but this behavior has also been observed in other games, including at least 1822 and 18NewEngland.

**Comment by roseundy** [comment]
Pretty sure this won't be 1822CA-specific.

**Comment by roseundy** [comment]
And I was wrong.
