### ISSUE TITLE
Please close the broken game https://18xx.games/game/141861 of 1822

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#10138]
The game is broken and we are even not able to close it ourselves.

**How to Reproduce the Problem?**

What steps cause the unexpected behavior?

e.g.
- Trying to login with my username results in "Access Denied"

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by michaeljb** [comment]
dupe #10059 

I'm closing 141861, for debugging reference the game data has been copied to [this gist](https://gist.github.com/michaeljb/540e0016d9dbe8bc69f0e9de17bb9040)
