### ISSUE TITLE
[1822CA] undefined method `round' for nil

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10139]
**What's your Game ID?**

https://18xx.games/game/148647?action=1200

https://gist.github.com/benjaminxscott/4e3de5165e6b6180d9248a7acbd0355a

**How to Reproduce the Bug?**

Not my game, it looks like it's bailing  in a late game round `OR 8.1`, the last phase had just triggered (Phase 7)

**Comment by michaeljb** [comment]
Whoops, I think the sold-out companies fix broke this one--the game now crashes before OR 8.1 and the major that is up on the broken action is set to be later in the order
