### ISSUE TITLE
1866 - Game is currently inaccessible/doesn't load

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#10144]
https://18xx.games/game/147518

This 1866 game appears to be unable to load. I hope it has not fallen into a digital abyss.

Cheers. :)

**Comment by magnusstjarnhild** [comment]
Made a fix for this, but it wont fix this game since its now a pinned game.

**Comment by JaySixA** [comment]
Can it be moved from pinned status, or, if not, is there a way to just nike the game?

**Comment by benjaminxscott** [comment]
dupe #10141
