### ISSUE TITLE
[1822CA] Moncton (AO3) upgrade to brown not allowed

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10149]
1822CA
https://18xx.games/game/148932

 I'm trying to upgrade Moncton (AO3) to brown with the ICR but can't get it to stay upgraded in OR 7.2.  Tried on phone and PC (Firefox).  Another player tried to do this for me via MasterMode and it failed to hold too.

It does it briefly and sometimes it stays until I run a route and submit to pay.  Then it roughly says:
Blocking route action 1079 cannot process route 

And it resets to prior to the upgrade putting me back on the track action.

**Comment by WayneWWms** [comment]
I then tried building south with yellow track and a similar issue occurred.

**Comment by michaeljb** [comment]
The game in question has been pinned, and I was just able to successfully upgrade AO3 to brown in a hotseat game. Closing this, will dig into it if it reoccurs.
