### ISSUE TITLE
[1846] Bankrupt player who owns additional stock outside of closed company remains in the game.

### ISSUE THREAD

**Issue by ryanespin** [tobymao/18xx#1014]
In game 3428, I became bankrupt with PRR.  PRR closed, however I still had a president's share of B&O.  B&O's stock should have gone back to the market, but instead, it still remains in my control and I am still acting for B&O in the OR.

**Comment by michaeljb** [comment]
I wrote up more details on how bankruptcy is supposed to work in #1022, so I'll close this issue and track bankruptcy there. Thanks for reporting the bug!
