### ISSUE TITLE
[1866] undefined method `split' for nil when submitting routes

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#10141]
Game #147518.  I was running the OU.  And auto-route gave me a 20 run with the L train and a 60 with the 2 train.  I reset that, and changed it to a 30 run with the L train and 50 with the 2 train.  I submitted it, and the game gave me an error that was on the screen too quickly to see about not accepting the move, and then started to reset, and now it won't get past the "Game Loading" screen.

**Comment by benjaminxscott** [comment]
last working action:
https://18xx.games/game/147518?action=299

https://gist.github.com/benjaminxscott/aa4aab008ccf446feec7972172a51aa5

Couldn't repro on hotseat with the route changes mentioned above, could be a server-side Opal vs Ruby issue or a race condition got a bogus route inserted

![image](https://github.com/tobymao/18xx/assets/1711810/581c3558-5751-497a-823c-dc13f6b95074)

**Comment by magnusstjarnhild** [comment]
Made a fix for this, but it wont fix this game since its now a pinned game.
