### ISSUE TITLE
[1822CA] Tile lay after minor acquisition

### ISSUE THREAD

**Issue by cwebblax** [tobymao/18xx#10151]
Cannot do a bonus tile lay past location where token was removed despite having a connected route. Appears to conflict with rules 5.17.12 and 5.17.13. 

Thanks fellas!

**Comment by michaeljb** [comment]
Hi, could you share a link to a game where this has happened? That will help with fixing the issue. Thanks!

**Comment by cwebblax** [comment]
Hi Mike,

Here is the game link: https://18xx.games/game/149084

The time stamp for the issue was at 20:50.

Thanks again guys!
Cody

**Comment by michaeljb** [comment]
Thanks Cody, that's helpful!

https://18xx.games/game/149084?action=448 [gist](https://gist.githubusercontent.com/michaeljb/85a533eccf6a8215f3369fced8aad647/raw/42ad3c0f83c71dec5dcacfe70d47ce7e390a98df/149084_at_448.json)
