### ISSUE TITLE
[1822CA] Certificate count tracking

### ISSUE THREAD

**Issue by JEBrosius** [tobymao/18xx#10159]
I propose that the display of a player's cert count be modified to reflect the fact that "each item on which a player currently has the highest bid counts as a certificate against the certificate limit" (Rule 4.10.8.)  Currently, the count shown under "Certs" in a player's status block does not count items on which the player has the highest bid.

See for example https://18xx.games/game/148162?action=960.  Player jazzfish owns 13 stock certificates and 2 private company certificates, and has the highest bid on M15.  He is at 16 certificates out of the maximum of 20 in a 4-player game, and has room to buy 4 additional certificates.  However, his status block shows "Certs 15/20."

I propose that the display be modified to show "Certs 15(16)/20" or "Certs 15+1/20" or (less desirably) "Certs 16/20".  This will help players avoid errors that result from not accounting for items on which they have the highest bids in their evaluation of how the certificate limit applies to their position.  In the example given above, the player erred in estimating how many additional certificates he was able to buy (assuming that he was not overbid by an opponent.)

I searched the Github list for 1822CA and certificate and did not find any other items that address this topic.

**Comment by bubba0077** [comment]
This would apply to all 1822 titles, not just 1822CA
