### ISSUE TITLE
1822CA Private P16 (Montreal) Upgrade Not Functioning

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10150]
1822CA
https://18xx.games/game/148393

I acquired P16 ([15:17] GNWR acquires P16 (Free Montreal Upgrades) from WayneWilliams) and then tried to upgrade Montreal (poorly since I'm not there).  It didn't work.

I ignored the opportunity and we continued playing since I didn't really care, but this cloned game replicates it occurred:

https://18xx.games/hotseat/hs_govgijsy_148393

**Comment by michaeljb** [comment]
https://18xx.games/game/148393?action=1015

> and then tried to upgrade Montreal (poorly since I'm not there).

This is correct behavior. The ability text includes this:

> The company upgrading the city must be connected to it in order to exercise the private company.

So since GNWR is not connected to Montreal, they cannot use P16.

Thanks for alpha testing!

**Comment by WayneWWms** [comment]
Thanks for keeping me on track!

Wayne
