### ISSUE TITLE
1841 Restarted major shows 2 shares in market, causing stock drop.

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10158]
https://18xx.games/game/147439

"[11:41] AFI's share price moves down from L.340 to L.295"

AFI was a restart.  3 shares were bought, but the entities page shows -2 still in the market and 12 total shares.  As a result it dropped at the end of the stock round, when it should not have.

Thanks for your work on the game!

--Wayne Williams

**Comment by WayneWWms** [comment]
And then the owner of the presidency was able to sell it in a non-forced situation, recouping all the money.  ("[13:04] ATFA sells 3 shares of AFI and receives L.798")   But AFI still shows as a company he owns on the entities section.  The placard indicates 7 shares in the IPO, 1 in the market, and no explanation of the presidency that was sold.....

**Comment by roseundy** [comment]
Clearly the game state was corrupted before that point. There should never be "-2" shares anywhere.

**Comment by roseundy** [comment]
Action 427 leads to the first time there is a negative number of shares in the market for AFI.

**Comment by roseundy** [comment]
The original problem occurs on action 324 (the start of the Ferd. Secc.)

IRSFF has the president's cert of AFI plus an additional share, the president's cert should have transferred to SB (and the log says it did), but either the president's cert never transferred, or when gershwyn took over the presidency of AFI as a result of the transfer, the two 10% shares from gershwyn never made it to SB.

**Comment by roseundy** [comment]
Looks like another SharePool bug around transferring a presidency.
