### ISSUE TITLE
[cross-game] reserved token text overflow

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#1015]
Minor nitpick that text centered in the city spaces often overruns the space available 

In '89 this is workable since companies have two-letter codes, but other games often have longer codes

To make it fit a bit better, I'd propose: 
1 - Make the 'reserved token' text slightly smaller to fit Nord and three-letter codes a bit better
2 - Remove the ampersand in markers for B&O, C&O, C&WI, N&W
3 - Make Erie lowercase to fit a bit better

![Screenshot 2020-07-06 at 1 52 36 PM](https://user-images.githubusercontent.com/1711810/86641556-1367ff80-bf90-11ea-9296-f815cec2b808.png)
![Screenshot 2020-07-06 at 1 51 51 PM](https://user-images.githubusercontent.com/1711810/86641558-14009600-bf90-11ea-900e-a38a33afa134.png)
![image](https://user-images.githubusercontent.com/1711810/86643206-5aa2c000-bf91-11ea-8ee2-214b673c42da.png)

**Comment by tobymao** [comment]
we can easily make the text size dynamic based on symbol size. we should
not change the company symbols since that requires a migration

**Comment by benjaminxscott** [comment]
sounds good to me, I imagine that works better for responsive mobile/desktop as well
