### ISSUE TITLE
149489 - 1822CA Game Frozen

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#10161]
https://18xx.games/game/149489

This game of 1822CA is frozen, and I forgot my parka.

Many thanks for your attention and time.

**Comment by michaeljb** [comment]
I thought this freezing issue might be fixed by #10153, but unfortunately this game needed to be archived. Saved to a [gist](https://gist.github.com/michaeljb/9e5a5e891a46bd1fc200d702f0af4fec) in case it is useful for future debugging.
