### ISSUE TITLE
create at-message to player when their name is clicked during a game

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10166]
Currently one must transcribe or copy/paste a player's name to write an @-mention to them during a game, and clicking their name redirects to their profile page

I would propose that clicking a player's name auto-fills an @-mention to them in the game chat box, to make this usecase a bit smoother

**Comment by crericha** [comment]
I was the one who added the click to profile. I find that I use it all the time and would not want that functionality to change.

If I wanted to make @ mentions easier, I'd look into autocomplete.
