### ISSUE TITLE
1866 - Game 148823 - Undefined method entity for 'nil' error

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#10162]
https://18xx.games/game/148823

I get an Undefined method 'entity' for nil error message when trying to start a company in the ISR.

**Comment by benjaminxscott** [comment]
What are the specific actions taken to start a corp in ISR? It looks like on hotseat, if I have DrA win the auction it begins operations w/o an error

**Comment by DrPooter** [comment]
When I click on the appropriate par button under any of the companies I receive the error message.

I can successfully bid on the auction, however.
