### ISSUE TITLE
[1822CA] Quebec gets a "no implicit conversion of NilClass into integer" error when upgrading

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#10172]
[1822CA] Quebec gets an error when attempting to upgrade to gray.  Same game with the ICR destination token error.

It seems that Quebec has issues when attempting to upgrade the city when it is tokened out.

Hotseat, Firefox

https://gist.github.com/ScottDrone/3f7a39ac656f2da03cb93b5c589c5c81

**Comment by michaeljb** [comment]
probably similar to #10164 which affects Winnipeg

**Comment by michaeljb** [comment]
Unfortunately the sample game is broken by updates, probably due to #10192. I'm going to close this issue and track progress on big city upgrade issues in #10164
