### ISSUE TITLE
[1822CA]  ICR destination token

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#10171]
1822CA - ICR can not place their destination token in the eastern slot of Quebec.  I get an error message telling me to click on the hex where I want the token, but it will only allow in the western slot.  The lone Eastern slot is filled with a GT token, the 2 western slots are filled by QMOO and the slot reserved for 5.  

Hotseat game, Firefox.

https://gist.github.com/ScottDrone/1b09618f60b17649afa9dd4e4b287b93

**Comment by kepakiano** [comment]
Would you be able to provide a screenshot? That would make it easier to rule out a misunderstanding of the rules.

**Comment by ScottDrone** [comment]
It doesn't provide an error message.  When you click on the various city
slots, the only one that permits the destination token to be placed, are
the western slots.  Clicking on the eastern slot does nothing at all.

My reading of the rules is that the ICR should be allowed to place their
destination token in either the eastern or western city locations in
Quebec. If the slot is not available, it should create a new one until the
city upgrades enough to allow it to merge in.

Game was deleted prior to receiving this question.

**Comment by ScottDrone** [comment]
I was able to recreate the issue.

ICR's first operating turn
![image](https://github.com/tobymao/18xx/assets/105426708/372acbad-5fdb-4a4d-9f05-e18f5b3fbe58)

The state of the track laid so far allows ingress to both the east and west sections of Quebec

![image](https://github.com/tobymao/18xx/assets/105426708/4a552b47-f5a6-41d5-96fe-d9a63e028241)

In this game, clicking on either side of the city produces the error message, and you can not move forward.

![image](https://github.com/tobymao/18xx/assets/105426708/946fccea-895e-4a52-9c26-c62ca8e74304)


New gist enclosed

https://gist.github.com/ScottDrone/d190d2625bb49db6ed51086dfa44e7e0

**Comment by ScottDrone** [comment]
Game ID follows  Id: hs_favvcpny_1706031342
