### ISSUE TITLE
[1822CA] open sawmill token bonus not applied to minor

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#10176]
In this game: https://18xx.games/game/147823?action=310 if you proceed to acquire P13, put the open +$20 token on Peterborough (AD20) and then proceed to the turn of minor 10, it should be able to run for 70 from Peterborough to Toronto, but it only runs for 50. The bonus does work later for the GT.

https://gist.github.com/benjaminxscott/f4c08d15f558d71f818368e1d755aa20

**Comment by benjaminxscott** [comment]
The rules seem to allow for minors to get the bonus, am I reading that right @michaeljb ?

**Comment by benjaminxscott** [comment]
The bonus will apply retroactively after a fix is deployed, assuming other patches don't break the game in the interim (since it's alpha it's likely to do so)

**Comment by kepakiano** [comment]
awesome, thank you :)
