### ISSUE TITLE
1822 

### ISSUE THREAD

**Issue by Seraphin06** [tobymao/18xx#10181]
https://18xx.games/game/141719?action=743

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
Can you explain what the issue is so we don't have to guess?

**Comment by Seraphin06** [comment]
Sorry, it had allowed someone to take loans out without selling all of their shares...my bad.  That was the first time giving an bug report...I will be more through next time.  I really appreciate everything you guys have done, and will get back to giving monthly after I sell our house next month.  Two mortgages and no job, we are penny pinching right now.  I just wanted to say thank you.
________________________________

**Comment by benjaminxscott** [comment]
No worries man thanks for letting us know

-_Ben
