### ISSUE TITLE
21Moon Incorrect tile upgrades

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#10190]
The following incorrect tile upgrades are shown in the tiles tab.
- X2 should not be able to upgrade to X5 or X6. 
- X3 should not be able to upgrade to X4.

I did not verify if these choices are offered during gameplay.

**Comment by philcampeau** [comment]
It doesn't look like they're displayed as options on the map: 
![image](https://github.com/tobymao/18xx/assets/26125362/c8d7381b-4b7a-45dc-b2e7-963fc3eea937)

So the issue is only in the display on the Tiles tab.

**Comment by roseundy** [comment]
Really struggling to see in the code why X5 and X6 _aren't_ available as an option when laying track.

**Comment by roseundy** [comment]
OK, see it now. It's the difference between all_potential_upgrades in @game and upgradeable_tiles in tracker. The latter calls tracker::legal_tile_rotation, and the former doesn't.
