### ISSUE TITLE
[18SJ] rand not called correctly in setup, producing limited combinations of company removals

### ISSUE THREAD

**Issue by Doomvar** [tobymao/18xx#10202]
I found a few issues, choosing seeds for the game setup.
The current situation is (companies and corporations to remove):
seed  0:`	`**AEvR, NOJ, MV, GKB**`	`**TGOJ**` `[ **ÖKJ** ]
seed  1:`	`**NE, FRY, NOHAB, SB**`	`**ÖSJ**	
seed  2;`	`**AEvR, NOJ, MV, GKB**`	`**MYJ**`	`[ **ÖKJ** ]
seed  3:`	`**NE, FRY, NOHAB, SB**`	`**STJ**	
seed  4;`	`**AEvR, NOJ, MV, GKB**`	`**TGOJ**` `[ **BJ** ]
seed  5:`	`**NE, FRY, NOHAB, SB**`	`**ÖSJ**	
seed  6:`	`**AEvR, NOJ, MV, GKB**`	`**MYJ**`	`[ **BJ** ]
seed  7:`	`**NE, FRY, NOHAB, SB**`	`**STJ**	
seed  8:`	`**AEvR, NOJ, MV, GKB**`	`**TGOJ**` `[ **BJ** ]
seed  9:`	`**NE, FRY, NOHAB, SB**`	`**ÖSJ**	
`   `the corporation in square brackets are corporations with president's share which stuck with Nils Ericson

You can see the pattern:
- all even seeds are **AEvR, NOJ, MV, GKB** plus **TGOJ** or **MYJ**
- all odd seeds are **NE, FRY, NOHAB, SB** plus **ÖSJ** or **STJ**

Only corporations in square brackets have a random. 
By the way, you can never see **KFJ**, **UGJ**, **ÖSJ** corporations in the square brackets (100,000,000 seeds were checked)

**Comment by Doomvar** [comment]
The logic is:
any random number for the companies is **rand%2** (two companies in four blocks)
any random number for the corporation is **rand%4** (four corporations to choose)
any random number for the corporations added to Nils Ericson is **rand%10** (ten corporation to choose)

**Comment by Doomvar** [comment]
I modified the code a bit and I've got:
seed 0:` `**NE, NOJ, MV, GKB**`       `**ÖSJ**	
seed 1:` `**AEvR, FRY, NOHAB, GKB**` `**ÖSJ**`  `[ **ÖKJ** ]
seed 2:` `**NE, FRY, MV, SB**`         `**TGOJ**	
seed 3:` `**AEvR, NOJ, NOHAB, SB**`  `**STJ**`   `[ **SNJ** ]
seed 4:` `**NE, FRY, MV, SB**`         `**ÖSJ**	
seed 5:` `**AEvR, NOJ, NOHAB, SB**`  `**TGOJ**` `[ **ÖSJ** ]
seed 6:` `**AEvR, NOJ, NOHAB, SB**`  `**MYJ**`  `[ **BJ** ]
seed 7:` `**AEvR, FRY, MV, SB**`       `**STJ**`   `[ **BJ** ]
seed 8:` `**AEvR, FRY, NOHAB, GKB**` `**ÖSJ**`  `[ **STJ** ]
seed 9:` `**AEvR, FRY, MV, GKB**`     `**TGOJ**` `[ **STJ** ]

and etc

**Comment by Doomvar** [comment]
For the logic I used the same logic as above. I've just randomly picked the number **20** and added to the formulas.

For the companies:
**rand%20**
if (rand%20)<(rand%20)/2 then 0 else 1

For the corporation:
**rand%20**
if (rand%20)<((rand%20)/4`*`1) then 0 else
` `if (rand%20)<((rand%20)/4`*`2) then 1 else
`  `if (rand%20)<((rand%20)/4`*`3) then 2 else 3

For the corporation added to Nils Ericson:
**rand%20**
if (rand%20)<((rand%20)/10`*`1) then 0 else
` `if (rand%20)<((rand%20)/10`*`2) then 1 else
`  `if (rand%20)<((rand%20)/10`*`3) then 2 else
`   `if (rand%20)<((rand%20)/10`*`4) then 3 else
`    `if (rand%20)<((rand%20)/10`*`5) then 4 else
`     `if (rand%20)<((rand%20)/10`*`6) then 5 else
`      `if (rand%20)<((rand%20)/10`*`7) then 6 else
`       `if (rand%20)<((rand%20)/10`*`8) then 7 else
`        `if (rand%20)<((rand%20)/10`*`9) then 8 else 9

**Comment by benjaminxscott** [comment]
is there a bug? 

the logic for randomizing stuff in this game seems to be
https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_sj/game.rb#L353

**Comment by michaeljb** [comment]
+1 to Benjamin's question. What's the problem @Doomvar?

If no seed is entered, the one that is generated will be a large number, for instance I just made a hotseat game and it got `1706409280`. Here's the relevant setup log lines I got:

```
[19:42] Removed companies: Adolf Eugene von Rosen, Nässjö-Oskarshamns järnväg, Motala Verkstad, Göta kanalbolag
[19:42] Removed corporation: Trafikaktiebolaget Grängesberg-Oxelösunds järnvägar (TGOJ)
[19:42] Nils Ericson comes with the president's share of SNJ
```

My seed is even and doesn't include AEvR, so I think eventually you do get different behavior from what you're seeing?

Here's the full `rand` implementation we use:

https://github.com/tobymao/18xx/blob/f530449836135cebd33ed4375bed9481a5e59909/lib/engine/game/base.rb#L395-L398
https://github.com/tobymao/18xx/blob/f530449836135cebd33ed4375bed9481a5e59909/lib/engine/game/base.rb#L631-L638

**Comment by Doomvar** [comment]
> +1 to Benjamin's question. What's the problem @Doomvar?
> 
> If no seed is entered, the one that is generated will be a large number, for instance I just made a hotseat game and it got `1706409280`. Here's the relevant setup log lines I got:
> 
> ```
> [19:42] Removed companies: Adolf Eugene von Rosen, Nässjö-Oskarshamns järnväg, Motala Verkstad, Göta kanalbolag
> [19:42] Removed corporation: Trafikaktiebolaget Grängesberg-Oxelösunds järnvägar (TGOJ)
> [19:42] Nils Ericson comes with the president's share of SNJ
> ```
> 
> My seed is even and doesn't include AEvR, so I think eventually you do get different behavior from what you're seeing?
> 
> Here's the full `rand` implementation we use:
> 
> https://github.com/tobymao/18xx/blob/f530449836135cebd33ed4375bed9481a5e59909/lib/engine/game/base.rb#L395-L398
> 
> 
> https://github.com/tobymao/18xx/blob/f530449836135cebd33ed4375bed9481a5e59909/lib/engine/game/base.rb#L631-L638

This is exactly what I said.
1706409280 is even
 all even seeds are **AEvR**, **NOJ**, **MV**, **GKB** plus **TGOJ** or **MYJ**

in your case **AEvR**, **NOJ**, **MV**, **GKB** plus **TGOJ**

**Comment by Doomvar** [comment]
The rule sais:
Randomly remove from the game one private company from each
pair specified below:
• P1 Frykstabanan (**FRY**) and P2 Nässjö-Oskarshamns Järnväg (**NOJ**)
• P3 Göta Kanalbolag (**GKB**) and P4 Sveabolaget (**SB**)
• P6 Motala Verkstad (**MV**) and P7 Nydqvist och Holm AB (**NOHAB**)
• P9 Nils Ericson (**NE**) and P10 Adolf Eugène von Rosen (**AEvR**)

In current code you will not see the combinations like:
**NE**, **NOJ**, **MV**, **GKB** or
**AEvR**, **FRY**, **NOHAB**, **SB** or
**NE**, **NOJ**, **MV**, **SB**
and etc.

**Comment by michaeljb** [comment]
Ah ok, I didn't understand that the companies you listed were the ones removed, and since the log didn't abbreviate everything I didn't pick up how it matched the list you gave. 

So somewhere in setup we'll need to call `rand` more.

**Comment by Doomvar** [comment]
It will help you:
https://boardgamegeek.com/filepage/272763/18sj-seeds-generator

**Comment by Doomvar** [comment]
> Ah ok, I didn't understand that the companies you listed were the ones removed, and since the log didn't abbreviate everything I didn't pick up how it matched the list you gave.
> 
> So somewhere in setup we'll need to call `rand` more.

That's why I gave my suggestion to change the code (see above). But I do not know where and for whom I can send the message (for developers).

**Comment by Doomvar** [comment]
> is there a bug?
> 
> the logic for randomizing stuff in this game seems to be https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_sj/game.rb#L353

The current code gives you very limited randomizing

**Comment by michaeljb** [comment]
> But I do not know where and for whom I can send the message (for developers).

This is the right place 👍 

I think shuffling the collection when selecting the company to remove is the right solution. That will call `rand` once for each company in the collection, instead of just once for the whole collection, and sorting by the produced values also produces different results than modding the result. Local testing confirms a variety of combinations that you'd expect.

This ends up being a simple one-line change #10206

**Comment by Doomvar** [comment]
> > But I do not know where and for whom I can send the message (for developers).
> 
> This is the right place 👍
> 
> I think shuffling the collection when selecting the company to remove is the right solution. That will call `rand` once for each company in the collection, instead of just once for the whole collection, and sorting by the produced values also produces different results than modding the result. Local testing confirms a variety of combinations that you'd expect.
> 
> This ends up being a simple one-line change #10206

Could be
But if you accept my suggestion you don't need to change the code a lot.

**Comment by michaeljb** [comment]
The fix is live, all the legal combos should be possible now. For instance, seed `14` will remove the companies NE, NOJ, MV, SB

**Comment by michaeljb** [comment]
Thanks for reporting the issue, and clarifying after I didn’t get it at first! 🙂
