### ISSUE TITLE
1822CA ICR Destination Token (any Quebec) moved to other Quebec location when QMOO starts

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10201]
https://18xx.games/game/149918

1) ICR reached Quebec and destination token placed in east Quebec.
[19:52] ICR places its destination token on AH8

2) In OR7.1 NTR placed a token in east Quebec.
[16:23] NTR places a token on AH8 (Québec) for $100.

3) The next company, QMOO started and placed its home token in OR7.1 in east Quebec, displacing ICR destination token to west Quebec.
[16:23] WayneWilliams operates QMOO
[16:23] QMOO places a token on AH8

**Comment by WayneWWms** [comment]
Thanks again Michael for all your work on this great game.

**Comment by michaeljb** [comment]
Turned out to be an easy fix, I messed up something small in my other recent token fixes. Thanks for alpha testing and reporting, Wayne!
