### ISSUE TITLE
[21Moon] Route from Eastern to Terminal does not count Terminal as a "free stop"

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10211]
**What's your Game ID?**
hs_iooynzwn_1706317833

https://gist.github.com/jackpunt/707a25035640f3753514f76f49b976ba

**How to Reproduce the Bug?**

Train of size 3, route of length 4; is from Terminal to Research Facility (Eastern)
By rule, there is a bonus for such a route, and the final stop at the Terminal is not counted against route length.

11.4.1 Terminal Bonus
If a transport visits both the Terminal and
one of the Eastern off-board areas, the run
is worth an extra ₡30 and the stop does not
count against the transport's number. This
bonus can be collected by each transport a
corporation runs. The bonus is provided for
transporting tourists and research personnel
to the terminal attached to the Space Port.

<img width="1374" alt="Screenshot 2024-01-27 at 2 37 01 PM" src="https://github.com/tobymao/18xx/assets/455836/e891296c-42b9-4e14-9834-b5c9046faf4c">

.

Later, with 4-train, does not extend to 5th stop:
<img width="1349" alt="Screenshot 2024-01-28 at 8 34 39 AM" src="https://github.com/tobymao/18xx/assets/455836/46fe9343-2bfd-468a-9afa-2503a8cce65e">

**Which Browser / Platform?**
Chrome..
But it's a logic/rules problem not a presentation problem.

**Comment by roseundy** [comment]
This rule is news to me (obviously). It wasn't in the playtesting rules.

**Comment by roseundy** [comment]
Checked with Scott. This was a change made late in play testing.

The good news is that fixing it won't break existing games.

**Comment by jackpunt** [comment]
Ah! "late in play testing"...
That may explain why the current game, although lacking the free step, seems to allocate a $50 bonus, instead of the $30.
Likely both changes were intended to be somewhat offsetting.
(check my math, or check your code ;)

Glad you could find a fix;

**Comment by philcampeau** [comment]
@roseundy ^ assuming that's correct, sounds like the EW_BONUS should be 80 instead of 100 now. Figured I'd tag you so you didn't miss the message :)

**Comment by roseundy** [comment]
Please file a separate bug. This one has already been fixed in a PR.
