### ISSUE TITLE
[21Moon] Multi-sales from same corp in a SR seemingly at odds with rulebook

### ISSUE THREAD

**Issue by Adrianows** [tobymao/18xx#10218]
Game id:
https://18xx.games/game/150529

Violation as of https://18xx.games/game/150529?action=342
- LG has a stock price two spots above closing
- adrian sells one share of LG, moving the price down from 50 to 40, then sells another share of LG, moving from 40 to 0 and closing the company.

The rulebook implies that multiple sales of the same corp cannot be performed in a single SR turn in such a way as to lower the stock price by more than a single spot: 
<img width="316" alt="image" src="https://github.com/tobymao/18xx/assets/25406958/cd9423ee-891d-4342-b0ff-d7121cd109ec">

**How to Reproduce the Bug?**

During any stock round after which a company has already operated, own multiple shares of a single corporation and sell any number sequentially to lower the stock value that many places. The rulebook implies that all corporations shares get placed into the bank pool at the same time and thus you can only lower a stock price by one spot per stock turn.

**Which Browser / Platform?**

MacOSX / Firefox (not associated with site loading issues)

**Comment by roseundy** [comment]
The fix will potentially require pinning games.

**Comment by jackpunt** [comment]
Q: Will this apply to Stock Issuing during the Corp Round?

I rather like the ability to serially issue 1 IPO share at a time, driving $80 down to $60, [or $70 to $50]
(so the corp can run **after** the other corps build roads, and the 2-trains are sold; 
 and then get the 2-step bonus for running SP @ $120 [or 100])
 
 Big money *and* big trains!

**Comment by jackpunt** [comment]
Realated to multiple "sales" dropping the price:

9.1 at the end says: "However, if the corporation has not yet had
an operating turn its price does not drop."

Note: "has not operated" rather than "has not floated".
So the current practice where in the Corp Round, issuing single shares of the IPO cause the stock to drop is probably wrong.

(the bug has a value: a high priced IPO can lower its price so as to run later in the Oper Round, 
 but that's probably not intended to be allowed)

**Comment by roseundy** [comment]
If there is a second bug here, please file a different bug report. I've already submitted a PR to fix the original bug.

**Comment by roseundy** [comment]
Note that there are different rules for price drops when issuing shares vs. selling shares.

**Comment by jackpunt** [comment]
Ah, i see:
10.1.2: says:
"If the corporation was not floated at the time
shares were issued, the share price does
not change. If the corporation had already
been floated, its stock market token moves
down one space no matter how many shares
were issued. "

So it's not a but, and we can use it as a bona fide feature!

Thanks for keeping this up and running!
