### ISSUE TITLE
Rolling Stock [Stars] should not have a market share limit

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10215]
**What's your Game ID?**

**How to Reproduce the Bug?**

Sounds like RS and RSS don't have a market share limit

I don't play either so not sure if RS would also have this rule, the issue was mentioned in the context of RSS
https://18xxgames.slack.com/archives/C68J3MK2A/p1706464717304489

**Comment by roseundy** [comment]
After temporarily backing out of the fix, I can't reproduce the bug. There is a spurious "L" that appears next to the market shares, but that is only a UI issue. I can sell a 6th share to the market just fine.
