### ISSUE TITLE
[18EU] Purchase of 70% allowed - should not be

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#10222]
Game ID: 149843

Link to move: https://18xx.games/game/149843?action=486

Player was able to purchase 7th share of a not-yet-operated company. This should not be allowed. 

Per rule 3.1: "Players are normally limited to owning sixty percent (60%) of a Corporation's stock. However, a player may, through the exchange of Minor Companies for shares, find himself with more than 60% of a Corporation. If so, he must correct the situation by selling at his next legal opportunity. However, in no case may a player sell stock in a Corporation that has not yet operated. Thus, it is possible for a player to have more than 60% of a Corporation for an entire set of Operating Rounds."

Rules should allow exchange of a minor to get above 6, but not purchase.

Worth noting the Corp hasn't yet operated, so it's possible the implementation of the last two sentences of the above rule might be causing the issue...

**Comment by andrewzwicky** [comment]
Almost definitely because of https://github.com/tobymao/18xx/pull/10024. I'll look into this.
