### ISSUE TITLE
1846 bankruptcy

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1022]
Bankruptcy doesn't end the game now on 18xx.games, but there's so much more to it in the 1846 rules...

GMT rules:

> 7. BANKRUPTCY
>
> 7.11 After a player has gone bankrupt due to a forced train purchase
> (see 6.89), put the cash the player raised in the corporation’s
> treasury. Sell all remaining shares owned by this player to the
> Stock Market, even if this puts more than 50% of a corporation’s
> stock or a President certificate there. Add the money raised to the
> corporation’s treasury. This may result in a Presidency change in
> the corporation currently operating. If so, the new President must
> immediately purchase a train for it.
>
> 7.12 The certificate limit is unaffected by a bankruptcy.
>
> 7.13 If a corporation’s President certificate is in the Stock Market,
> modify the normal stock rules:
> • A player may not sell stock in this corporation.
> • If, after buying a share, a player owns 20% of this corporation
> then that player becomes President, swapping shares for the
> President certificate.
>
> _NOTE: A President certificate may not be directly bought from_
> _the Stock Market (as two shares). However, if only the President_
> _certificate is in the Stock Market, a player holding a 10% share_
> _in that corporation may purchase a virtual 10% share, swapping_
> _certificates appropriately._
>
> 7.14 A corporation with its President certificate in the Stock Market
> operates as follows in the Operating Round:
> • It does not issue or redeem shares, lay track, purchase tokens,
> or purchase Private Companies.
> • It will run routes with any train(s) it owns (for the most revenue
> possible) and retain its earnings (shifting its stock price one
> column left). If it does not own a train at this step, instead shift
> its stock price two columns left.
> • If it does not own a train and can afford to buy the cheapest
> available train from the bank, it will do so.

**Comment by tobymao** [comment]
haha yea i didn't do it because it seemed like a pain and rarely happens :)

**Comment by michaeljb** [comment]
Yep, but #996 broke the seal :laughing: 

Some of the parts about operating a corporation where the president certificate is in the bank pool may be relevant for 2p 18CZ with "Vaclav"--they both have a non-president player taking actions for a corporation.

**Comment by ryanespin** [comment]
> haha yea i didn't do it because it seemed like a pain and rarely happens :)

Thanks for making me feel good about my game of 1846 yesterday... lol

**Comment by Azuureth** [comment]
Game Id#3483 also had a bankrupcy. Player sold "remaining shares", but still held 4 of one company 5 of other, because the open market was full.

**Comment by jaysachs** [comment]
Since I "broke the seal", I'll take a crack at this one if no one else has started. Game states welcome (thanks Azuureth).

I'd expect to do this in phases, in particular, I'd skip "bank ownership" first.

**Comment by tobymao** [comment]
i think there are higher priority issues than this but if you want to do it go for it

**Comment by Azuureth** [comment]
Continuing from our game. Next OR Phoenix11 was still the president of those companies, but could not declare double bankrupcy and the game was halted. Error message was "0 is not valid amount to spend" when trying to declare backrypcy while already bankrupt.

https://gist.github.com/Azuureth/e6ad380bf694f81273e4003b79d28b95

**Comment by jaysachs** [comment]
@michaeljb I just noticed this is assigned to you so I'll assume you're working on it.

**Comment by michaeljb** [comment]
@jaysachs sorry, didn't see your comment before today. I do have some work in progress on this but I haven't pushed it yet. I could push what I have if you're interested.

**Comment by michaeljb** [comment]
Pushed up my branch and created a draft PR (#1079), and moved the checklist over there.

**Comment by michaeljb** [comment]
@jaysachs #1079 is ready to go for the bankruptcy stuff, but if you want to take a crack at the semi-related weird Emergency Money Raising rules of 1846, I opened #1087 and pasted in the GMT rules. :slightly_smiling_face:

**Comment by JEBrosius** [comment]
I'll point out that, weird though they may be, I've seen the Emergency Money Raising rules used in a number of different ways.  Just last week I saw someone issue a share at the start of the OR and then issue a second share in EMR in a very clever play to achieve what he wanted to achieve.
