### ISSUE TITLE
[21Moon] OLS should require a yellow tile lay on minerals

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10225]
**What's your Game ID?**

**How to Reproduce the Bug?**

According to the posted PDF rules (and text on the card in latest release):
"6.1.1 Old Landing Site (P1)
Face Value: ₡30, Revenue: ₡0
Sale price: ₡1
Upon purchasing this private company, the
player must immediately **place an appropriate yellow tile** on any mineral resource hex.
Then they must place the black “Old Landing
Site" (OLS) token in a depot token slot on
that tile."

This is a valuable benefit to the card, since it makes the resource available without an additional track placement.
.

PS: I played the [new release?] hardcopy last week and like the new market and SP/LB mechanics,
Came to the online site to explore it more, so noticing the differential between versions.

(I mentioned in #10211 a bit about the E-W bonus ($40 vs $50), I'll soonish make a new issue for that...)

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Another playtesting change that I'm just now hearing about.

**Comment by roseundy** [comment]
The fix will require all games to be pinned (meaning you won't see the fix on this game).

**Comment by roseundy** [comment]
I've also heard some rumblings that there are placement restrictions for the OLS that weren't in the play test rules.

**Comment by jackpunt** [comment]
In the discussion thread (on bgg) the resolution was to ignore the 3 hex limit, leaving it as a "house rule";
So players can choose whether to enforce the restriction (socially - no new code needed)

(one of the longish 'rules question'; i can re-search if you need citation/attribution; LMK)

**Comment by roseundy** [comment]
Yep. I'm well aware. Thanks.
