### ISSUE TITLE
[21Moon] EW_BONUS should be 80

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10229]
**What's your Game ID?**
 
per comments at the end of #10211  , the E-W bonus should be 80 for the connecting E-W.

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Another play test change that wasn't reflected in the play test rules.

**Comment by jackpunt** [comment]
If/when this is changed, the wiki page https://github.com/tobymao/18xx/wiki/21Moon should also be updated.

"E-W bonus adds **50** earnings to each off-board area. Additionally, the corporation receives bonus tokens for completing E-W runs that provide a further endgame bonus. Each bonus token adds 50 to the company's stock value at the end of the game. Each company may earn one token from each off-board area (there are only four tokens per area)"

**Comment by benjaminxscott** [comment]
@jackpunt Feel free to edit the wiki btw, any github account can do so

**Comment by jackpunt** [comment]
Ok, thanks. 
the emphasis was the bit about "if/when" to keep the doc sync'd with the code.

LMK when the change pushes to your server...
