### ISSUE TITLE
[1822CA] Unable to upgrade Toronto on a specific upgrade track

### ISSUE THREAD

**Issue by Tekopo** [tobymao/18xx#10226]
**What's your Game ID?**

https://18xx.games/game/147916

**How to Reproduce the Bug?**

When attempting to use my free build for Toronto, I am unable to upgrade Toronto to the two slot brown Toronto tile, with a bug message that says "no implicit conversion of NicClass into integer". The three-slot Toronto brown upgrade is selectable.

**Which Browser / Platform?**

Chrome

**Comment by michaeljb** [comment]
@Tekopo thanks for reporting, this ended up being trickier than I expected but the fix should be live now!
