### ISSUE TITLE
[18NY] NYC Formation Triggered Incorrectly

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#10223]
GameID: 150162

Turn link: https://18xx.games/game/150162?action=265

NYC formation is triggered, despite no Buffalo-Albany connection nor the 12H being purchased.

My guess is the bug is because both Buffalo and Albany are connected to the same red off-board area (Scranton) - however, Scranton is not pass through. I verified with Pierre (designer) that this should not trigger the formation.

**Comment by crericha** [comment]
@roseundy `graph.reachable_hexes()` is including hexes only reachable through an offboard. Is that expected behavior or a bug? Note: graph was constructed with `no_blocking = true` if that matters.

**Comment by benjaminxscott** [comment]
sry I must have misclicked on the self-assignment button
