### ISSUE TITLE
[21moon] corps should be allowed to run W-W or E-E

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#10237]
Currently, the 21moon implementation doesn't allow running from one East offboard to the other, or one West to the other. The rules don't discuss it, however. You just don't get an E-W bonus, or any bonus tokens.

Confirmed by the designer here: https://boardgamegeek.com/thread/3237742/article/43706638#43706638

**Comment by roseundy** [comment]
Is there a failing case?

**Comment by roseundy** [comment]
Most likely a consequence of how I determine whether a route hits a west or east offboard.

**Comment by philcampeau** [comment]
Here, i brought a hotseat game to that point:
https://gist.github.com/philcampeau/16cac66d3a8db127a26f82498a091ac9

![image](https://github.com/tobymao/18xx/assets/26125362/3a567943-ef8b-49c2-834b-c8a671dc89dd)

**Comment by roseundy** [comment]
Awesome, thank you!
