### ISSUE TITLE
[18SJ] The Oscarian Era -bankpool shares should pay to treasury

### ISSUE THREAD

**Issue by genericgituser1** [tobymao/18xx#10230]
18SJ: The Oscarian Era Game ID: Id: 148824

We were playing this game as a community group, and I noticed that the oscarian era earnings distribution was not programmed as the rule book indicate.

13.3.4 Earnings distribution indicates that "Shares in the bank pool pay dividends to the corporation's treasury". One company I was running had 1 share in the IPO and one share in the bank pool; however, when choosing "pay out", no money would go to the treasury. 

You can go and review the game and notice this issue fairly quickly, as many times there were companies with shares in the bank pool where the pay out dividend would not go to the corporation's treasury.

Thank you!

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
@perwestling I see you assigned this to yourself a couple of weeks ago, so I didn't want to submit a fix, but it looks like all you need to do is replace `@game.bank` with `@game.share_pool` on line 57 of the game's dividends.rb file: https://github.com/tobymao/18xx/blob/3794ce0ddcfbb174d74b1d3ef609e0a0ead633aa/lib/engine/game/g_18_sj/step/dividend.rb#L53C1-L61C14

I tested this locally and it fixed the issue.

**Comment by perwestling** [comment]
@philcampeau My intention was to look into this, but things got in the way. Please take it over, and fix it. Thanks.
