### ISSUE TITLE
[1822CA] error on dividend payout step "ArgumentError": "comparison of Number with NilClass failed"

### ISSUE THREAD

**Issue by ViennaTramways** [tobymao/18xx#10238]
Only a white screen with the massage "Loading game..."
https://18xx.games/game/147905

**Comment by benjaminxscott** [comment]
last working action https://18xx.games/game/147905?action=1701
(fairly late game)

taking any dividend payout action on the GTP results in an error

> "ArgumentError": "comparison of Number with NilClass failed"

https://gist.github.com/benjaminxscott/ec0dbb7da8439cd8539b656e7bcdbb89

**Comment by michaeljb** [comment]
@ViennaTramways thanks for reporting, this is fixed now, and you can resume your game.
