### ISSUE TITLE
[21Moon] Space Bridge private corp should close after first bridge is built

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10233]
**What's your Game ID?**
In the discussion in https://boardgamegeek.com/thread/3018725/article/42599063#42599063,
Scott confirms/clarifies  that Space Bridge corp closes after a bridge is built.
That is: the _first_ road across the rift is also the _last_ road across the rift.

Text from the card:

**Space Bridge**
Company
Value: 40
Revenue: 10
When sold to a corporation, the
owning corporation may build
and upgrade road tiles crossing
the rift during the game. The
owning corporation also
recieves a one time bonus of 60
credits when completing the
first road across the rift. **The \[Corp\]
Closes after the bonus is
collected** ."

(Sadly the new edition from AAG misspells  'recieves' and leaves out a word or two...)

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by roseundy** [comment]
It looks like this is another change from play testing.

**Comment by roseundy** [comment]
There is another change related to the SBC. I originally coded 21Moon such that you could lay tiles with track leading to the Rift, you just couldn't create a crossing w/o the SBC.

**Comment by jackpunt** [comment]
Yeah; the documented constraint (IIRC) is that a road cannot lead to the rift unless you have SBC.
Basically, for corps without the SBC, the rift is like the edge of the board.

(knowing the constraint, I never tried/tested it on 18xx, happily that is another quirk that the users can work around)

Again, thanks for getting this sync'd with the new release, i enjoy playing on the web site, so much less futzing that the hardcopy; esp with the log and undo/redo!

Kudos!
