### ISSUE TITLE
[21Moon] Allow E-E or W-W routes (but still no bonus)

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10241]
**What's your Game ID?**
https://boardgamegeek.com/thread/3237742/article/43706431#43706431

Jonas says: 
"Rechecking what we wrote in the rules I cannot see its forbidden to run W-W or E-E if players want to build such a route, via the Space Port or Home Base. It makes sense as its four separate areas however such a run do not qualify for a bonus token. Its unusal but not forbidden. Why it does not work in 18xx.games is probably the assumption that its not allowed as in many other 18xx games, but again I cannot find or remember that we wrote a rule that strictly forbids it.

To be clear. **Its ok to run between any two offboards just for basic income**."

**How to Reproduce the Bug?**

Problem provoked by: 

"[Cannot use group W more than once](https://github.com/tobymao/18xx/blob/683dfaae75b77ec6a2a1d7c0fc36694c2c594c81/lib/engine/route.rb#L324)"

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Dup of #10237
