### ISSUE TITLE
1844: Upgrade does not have to use new track

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#10240]
Running 1844 and an upgrade to green did not follow the rules:
https://18xx.games/game/147417?action=565

![image](https://github.com/tobymao/18xx/assets/2631151/529ed812-65e7-4226-86a4-377c7e44a679)

The rules seems to forbid the above upgrade:
![image](https://github.com/tobymao/18xx/assets/2631151/fd5275ef-f6c0-4fea-96c3-aca428fb2af1)

**Comment by philcampeau** [comment]
ViennaTramways is correct. This is implemented properly.
