### ISSUE TITLE
[1822CA] Sawmill private text inconsistent with game session

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#10242]
When applying Sawmill private to an open city, the game text indicates that it is for majors only, but minors operating in the city still get the bonus applied.  See screenshot.

https://gist.github.com/ScottDrone/cd0b7e5cc802d2ad8eeab71f8b67281e

Hotseat game, firefox

![image](https://github.com/tobymao/18xx/assets/105426708/0e8ba56a-fa9f-4b5d-b652-227669ef04f8)

**Comment by benjaminxscott** [comment]
Thanks I missed this when making https://github.com/tobymao/18xx/pull/10178
