### ISSUE TITLE
[1822CA] issue Couldn't acquire Minor #5 with QMOO after both companies had operated once.

### ISSUE THREAD

**Issue by Seraphin06** [tobymao/18xx#10245]
(https://18xx.games/game/149605)

[18:41] QMOO passes acquire private companies
[18:41] QMOO lays tile #8 with rotation 4 on AF8
[18:41] QMOO passes place the destination token
[18:41] QMOO skips place a token
[18:41] QMOO runs a 2 train for $40: AH8-AG9
[18:42] QMOO pays out $40 = $4 per share ($24 to QMOO, $16 to Seraphin)
[18:42] QMOO passes buy trains
[18:42] QMOO passes acquire a minor
[18:43] QMOO passes issue or redeem shares
[18:43] vexhawk operates GWR
[18:45] GWR passes acquire private companies
[18:45] GWR passes lay/upgrade track
[18:45] GWR passes place the destination token
[18:45] GWR skips place a token
[18:45] GWR runs a 2 train for $30: AB24-AB22
[18:45] GWR runs a 2 train for $50: AB24-AA25
[18:45] GWR pays out $80 = $8 per share ($48 to GWR, $32 to vexhawk)
[18:45] GWR's share price moves right from $50 to $60
[18:45] GWR passes buy trains

I was trying to acquire Minor #5 into QMOO at the end of phase 2 operation round 2...
It auto passed my acquire minors step.  I even backed up and to analyze the situation...I read briefly through the rules and there is nothing about needing 3 trains out prior to acquiring minors. I hope I am not missing something.

**Comment by michaeljb** [comment]
https://18xx.games/game/149605?action=440 - ([gist](https://gist.github.com/michaeljb/aec5b1de16584291fc30e1b9a279418f))

The minor acquisition step is skipped via auto_action, so the graph at that point is not detecting that QMOO and M5 are connected even though (or because?) they share a home city:

```
  {
      "type": "pass",
      "entity": "QMOO",
      "entity_type": "corporation",
      "id": 440,
      "created_at": 1706838171,
      "auto_actions": [
        {
          "type": "pass",
          "entity": "QMOO",
          "entity_type": "corporation",
          "created_at": 1706838171
        }
      ]
    }
```

**Comment by Seraphin06** [comment]
I assumed, Thank You!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Seraphin06** [comment]
Ok, now I was able to aquire M#5 but M#6 isn't showing up as available.  
![Screenshot_20240204_153013_Chrome](https://github.com/tobymao/18xx/assets/113114593/0612c3df-8045-4279-9807-6a717ff4950f)
![Screenshot_20240204_152952_Chrome](https://github.com/tobymao/18xx/assets/113114593/56054246-445b-4786-a504-5c792bf47284)

**Comment by michaeljb** [comment]
I spotted the problem, and it’s not actually a bug—in both cases, QMOO cannot afford to acquire the minor in question.

In OR 4.2 QMOO’s share price is $50, and it has $84 cash, so the most it could spend on an acquisition is $184, but the cost to acquire M5 is $200.

In OR 5.2 QMOO’s share price is $80, and it has $71 cash, so the most it could spend on an acquisition is $231, but the cost to acquire M6 is $240.

**Comment by Seraphin06** [comment]
I am so sorry to waist your time, but thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michaeljb** [comment]
Not a problem, and not a waste! It’s something to consider for adjusting the UI, we could make it more clear what’s going on.

Thanks for reporting!
