### ISSUE TITLE
[21Moon] Terminal should be placeable after private companies close.

### ISSUE THREAD

**Issue by lsanwick** [tobymao/18xx#10243]
**What's your Game ID?**

https://18xx.games/game/148239

**How to Reproduce the Bug?**

- Terminal private company was never sold to a corporation.
-  Terminal company closed after OR4.1
- Terminal tile should be placeable by any corporation after that point.

![IMG_2257](https://github.com/tobymao/18xx/assets/399536/398ef172-7ed6-4f29-9e50-188a5518479d)

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Yet another rule that was added after play testing.
