### ISSUE TITLE
[21Moon] How to make route with a tight loop through Space Port?

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10244]
**What's your Game ID?**

https://18xx.games/hotseat/hs_mkgkgfeh_1706680791

**How to Reproduce the Bug?**

As shown in screen shot, the route would be improved by looping from Space Port through the Terminal
(removing the side-track through D12)
I cannot find a gesture in the GUI to direct the route from SP to Terminal and back to SP,
the usual click just removes the previous segment going into the Terminal.

I've been looking for a 'shift-key' that lets me click on a road-tile (rather than the next node), 
a way to say: add this road-segment, and thereby "micro-manage" the routing for a case like this.

I suppose this is generic to all the 18xx.games; or maybe other 18xx don't have a routing hub like the SP ??
It is unusual to have a 'tile' with six arbitrarily connected edges...

Beyond the GUI, is there something that limits the auto-router from finding the loop?

**Which Browser / Platform?**

<img width="1289" alt="Screenshot 2024-02-01 at 5 17 16 PM" src="https://github.com/tobymao/18xx/assets/455836/1ba7910a-45bd-4ca4-bd4a-f64e8c59188d">

**Comment by roseundy** [comment]
FYI, your hotseat game is private to your browser - it's impossible for me to look at it. There are instructions for saving a gist when you file a bug.

**Comment by roseundy** [comment]
In any case, unless I'm misunderstanding what you are trying to do, a single route that loops from the SP to the Terminal back to the SP is not legal. You can't visit the SP twice.

**Comment by jackpunt** [comment]
Ah, of course: "You can't visit the SP twice"

... never mind...
