### ISSUE TITLE
1817 rename "after_ipo" option for SELL_AFTER

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#10255]
The "after_ipo" option for SELL_AFTER really should be named "after_float". Currently only affects 1817. Is expected to be used more for System18 microgames that use the incremental cap rules. This change will make it easier to understand how this rule works.

**Comment by crericha** [comment]
@roseundy and I discussed the naming on slack. We agreed upon :after_sr_floated since that's what the behavior really is.
