### ISSUE TITLE
implement a player-defined list of "blocked" users

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10253]
Users sometimes demonstrate behavior that other users don't want to interact with, whether that's ending games early, holding up live games, etc

The issue seems to be (currently) uncommon enough to not require the overhead of a "moderator" style feature, but common enough to degrade the experience of other users.

I would propose a user-defined list of users they "don't want to interact with", with an initial implementation that hides `New` games in which they are a member.

Using [RFC terms](https://www.ietf.org/rfc/rfc2119.txt):

- List MUST be stored server-side attached to the user account
- Adding/removing a user to the list SHOULD be possible from the target user's profile page
- Games which include any users on that list SHOULD be filtered out of the logged-in user's game view (client-side)
- This filtering MAY apply to `Active` games (ones that have already started)
- List MUST be visible / interactable to the logged-in user on their profile page
- List SHOULD allow removal (perhaps a red X next to each name)
- List SHOULD be limited in length (to mitigate issues in server storage)
- List MUST NOT be publicly accessible via the user's profile

**Comment by benjaminxscott** [comment]
Had an idea that perhaps blocked users couldn't join a game that you've created

**Comment by tobymao** [comment]
why don't users just not play with those users?

**Comment by benjaminxscott** [comment]
Hmm I would consider the case of "joining a game, then a blocked user joins and the host starts it" (i.e. the user doesn't have agency)

**Comment by tobymao** [comment]
seems complicated. someone could block someone and then join every game effectively blocking the blocked.
