### ISSUE TITLE
[21Moon] Tunnel Company gives discount on normal mineral resource.

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10256]
**What's your Game ID?**
https://gist.github.com/jackpunt/c83997fac2cc2b377fc9b83f343cdd16

"Tunnel Company
When owned by a corporation,
tiles only cost 10 credits to build
**in difficult terrain
(normally 40c).**
The owner may also take one
share available in the market for
free during SR 2, 3, or 4.
Taking a share closes the
private company"

Would expect tile on A9 to cost ₡20.

**How to Reproduce the Bug?**
[15:50] Player 1 operates SWP
[15:50] SWP receives a discount of ₡30 from Tunnel Company
[15:50] SWP spends ₡10 and lays tile #9 with rotation 1 on B8

<img width="705" alt="Screenshot 2024-02-02 at 4 10 36 PM" src="https://github.com/tobymao/18xx/assets/455836/94049775-4f9e-46a9-8232-33d86591bf4c">

[15:50] SWP receives a discount of ₡10 from Tunnel Company
[15:50] SWP spends ₡10 and lays tile #5M with rotation 3 on A9

<img width="709" alt="Screenshot 2024-02-02 at 4 11 29 PM" src="https://github.com/tobymao/18xx/assets/455836/d2c8e549-4901-4ce8-abcf-a6d6ee80bf97">

**Which Browser / Platform?**

**Comment by roseundy** [comment]
I need to mark the $10 terrain as "hill" instead of "mountain" in the map defintion.

**Comment by roseundy** [comment]
Only the $40 terrain should be marked at mounting, not the $10 terrain or the mineral hexes.
