### ISSUE TITLE
[21Moon] Can't swap share out of newly acquired corp

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10261]
**What's your Game ID?**
https://gist.github.com/jackpunt/120a98bc66fe61efaa7d8200f6f27ae8

**How to Reproduce the Bug?**
Player-1 becomes owner of SSF [a hostile takeover], then wants to swap out the share of ITC for SWP.

Player-1 (new owner of SSF) is not offered a chance to "Trade for share of ITC" out of SSF.
I expect it is because of being the **new** owner...

<img width="1114" alt="Screenshot 2024-02-03 at 10 14 56 AM" src="https://github.com/tobymao/18xx/assets/455836/1bec6d8b-9953-4e8f-a61f-9cf3d4c0b8df">

Note: in alternate playthrough, Player-4 (before losing presidency) is able to swap.

<img width="1117" alt="Screenshot 2024-02-03 at 10 07 08 AM" src="https://github.com/tobymao/18xx/assets/455836/10f4087b-ff8b-4eb6-8654-a6c4323d29d8">

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Player 1 was not offered the chance to swap with SSF because the only share SSF has in its treasury is a for a corporation Player 1 sold earlier that stock round (ITC). The "can't buy a share of a corporation you sold" rule applies to swaps in addition to purchases. See Section 2.1 of the rules.

**Comment by jackpunt** [comment]
Ah! ok. that's all good then.

Wasn't clear/obvious what was blocking the trade.
