### ISSUE TITLE
1858: Illegal route Madrid to Madrid

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#10275]
https://18xx.games/game/149262

ZPB running in OR4.1, placed a token in Madrid(NW) and then used the autorouter for its 4H train. This ran Madrid(NW) to Madrid(SW) for 120 - this is illegal.

"For cities which have two or more separate disconnected spaces, such as Madrid in yellow, a route may not include both spaces."

**Comment by benjaminxscott** [comment]
route step:
https://18xx.games/game/149262?action=506
