### ISSUE TITLE
Per-game webhook settings?

### ISSUE THREAD

**Issue by photogineer** [tobymao/18xx#10298]
**What's your idea?**

A bunch of my friends in a discord server are starting a game, we've set up the webhook to notify us, but each player has to set up the same webhook. Instead it would be ideal if we could set it per-game (like PYDT does) since for that game we're all using the same discord guild/channel to keep updated. Additionally I can't play in other games without spamming our server with the current setup.

**Comment by tobymao** [comment]
no plans to do this. if you’re interested you could make a pr.
