### ISSUE TITLE
[21Moon] Corp can't claim stock cert using Tunnel Company

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10296]
**What's your Game ID?**
https://gist.github.com/jackpunt/301aeb3a6f42faff45ffc9fb7bf28b76

**How to Reproduce the Bug?**
In Stock Round, the president is not offered a chance to activate the Tunnel Corp ability.
(even in following Corp Round, corp cannot activate the Tunnel Corp ability)
Presumably when the president activates it, the Tunnel Corp is closed and a share appears in corp treasury.

in [Questions about P2 and P6](https://boardgamegeek.com/thread/3234584/questions-about-p2-and-p6)  How/when can you activate Tunnel Corp?
Scott says: "Extra action player does anytime on their turn. In the case of a company doing the action, do it on the president's turn." 

<img width="1305" alt="Screenshot 2024-02-06 at 9 06 43 PM" src="https://github.com/tobymao/18xx/assets/455836/d8b09ce3-c812-4dea-8b35-3ea4112ed0e6">

**Which Browser / Platform?**

**Comment by roseundy** [comment]
I probably haven't coded it up to handle a president exercising it, only a player.

**Comment by jackpunt** [comment]
Ack.
IMHO, it would also suffice to allow the Corp to exercise it in the Corp Round...
(I originally exercise/close Tunnel Company in CR-4)

**Comment by roseundy** [comment]
Yeah, amazing no one found this before (or at least filed a bug - thank you for doing that!)

**Comment by jackpunt** [comment]
Eh... 50 years in the software business: must. file. bugs...

and thank you for fixing them!

**Comment by roseundy** [comment]
Fair warning: I won't likely get to this until Friday.

**Comment by philcampeau** [comment]
> Ack. IMHO, it would also suffice to allow the Corp to exercise it in the Corp Round... 

Not if there are a limited number of shares left in that corp and you want to scoop one up before someone else!

**Comment by jackpunt** [comment]
I was just going to add: or if you want to trade the share out of the corp...

**Comment by roseundy** [comment]
Apparently I originally coded this up thinking if a corporation owned the TC it would do the exchange during a Corporate Round. And apparently, I never tested it. I found the bug that kept that from happening and the fix will allow the exchange to happen during a SR.

**Comment by roseundy** [comment]
And it turns out that exchanging in the CR _did_ work, just not in this case because the owning corps turn was skipped over in the CR (which is another, non-21Moon specific, issue).
