### ISSUE TITLE
Paris pays 90F instead of 30F

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#1030]
By connecting Paris it adds 90 F instead of 30F to the run

https://www.18xx.games/game/2986

    {
      "type": "run_routes",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 498,
      "routes": [
        {
          "train": "5-1",
          "connections": [
            [
              "E11",
              "E9",
              "F8",
              "G7"
            ],
            [
              "H4",
              "G5",
              "G7"
            ],
            [
              "H4",
              "I3"
            ],
            [
              "J2",
              "I3"
            ]
          ]
        }
      ]
    },

**Comment by scottredracecar** [comment]
Lucky you are hitting three tokens. Check out the rules to see how to count
Paris.
