### ISSUE TITLE
[Shikoku 1889] Forced to pass ('has no valid action') despite being able and wanted swap Dougo for UR

### ISSUE THREAD

**Issue by peterjacobi** [tobymao/18xx#10306]
https://18xx.games/game/152130

End of first SR. I (pjacobi) was out of money but wanted to swap Dougo for 10% IR as last action in the SR.

This was not possible, which I only realized when I was notified for my next turn and it was already SR2. In the log I saw 'has no valid action'.

**Comment by tobymao** [comment]
this is a duplicate. no plans to fix this. you can just swap it on someone else’s turn.
