### ISSUE TITLE
[21Moon] tweak auto-route to consider unclaimed E-W Bonus tokens

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10304]
**What's your idea?**

Currently, the auto-path search takes the 'first' path with the highest value.
However, i've had several maps where there are equivalent 'value' routes,
but one goes to a corner that i've already claimed, and the other to the new corner.

The search finds/chooses NW before a similar route to SW:
<img width="942" alt="Screenshot 2024-02-08 at 8 15 32 PM" src="https://github.com/tobymao/18xx/assets/455836/95c3c170-5514-43db-a5e3-629a18068e17">

https://gist.github.com/jackpunt/5b91a506b1ada02b7e9f078868d5cd50

I'll forgive the harder problem of choosing a $330 path that does not gain new corner bonus
over a $280 path that includes the NE corner...

**Are there related ideas?**

Other contributors may be working on something similar, [check out the list of open feature requests](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to see if there's opportunity to collaborate.

**Did you join the Slack?**

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-27imtsj2u-vussFAqtecmACsycjdsIhg) and meet your fellow contributors!

**Comment by roseundy** [comment]
I'm not sure how likely it will be that this will be fixed.

**Comment by jackpunt** [comment]
Not the end of the game: it is just to account for does the Corp **currently** have the bonus for a given corner?
If a route can get the same score, but can get a new corner coupon/bonus/token, then prefer that route
over one that does not **gain** a corner bonus. (generally: not gaining from a corner because you already have that token)

**Comment by roseundy** [comment]
The way the autorouter works is to maximize route revenue. Since the bonus tokens do not affect revenue directly, it would have to be refactored. Since I haven't worked on the autorouter code, I don't have a feel for how likely this is.

**Comment by jackpunt** [comment]
Is the router subclass-able for 21Moon?
or point me at the code i'll take a look.

**Comment by roseundy** [comment]
The code was written by @tobymao 

I'd take it up with him.

**Comment by benjaminxscott** [comment]
Code:
https://github.com/tobymao/18xx/blame/master/lib/engine/auto_router.rb

**Comment by tobymao** [comment]
no it’s not. closing this fur now as i dont see it happening
