### ISSUE TITLE
[1847AE]  Tile upgrades for regular green cities to tile #63 is not allowed

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#10315]
1847AE, hotseat game.  Firefox.

https://gist.github.com/ScottDrone/58a758d059c91bd1c4af467c51ac7c8f

![image](https://github.com/tobymao/18xx/assets/105426708/4a427e12-ef52-456c-b8d7-9d78cbcc0598)

Tile manifest shows 4 available brown #63 cities.  These should be available to place on any legal city, but clicking on any regular city tile does not allow for this upgrade.  I did see a similar issue reported earlier that was closed last month but this appears to be unresolved, and I could not find any other issues tagged for this game.

Clicking on a yellow town shows upgrade pathing
![image](https://github.com/tobymao/18xx/assets/105426708/611d04d4-b39f-4b8e-95a5-3b7b8ee4c960)

Clicking on standard green track shows upgrade pathing
![image](https://github.com/tobymao/18xx/assets/105426708/66234a7e-6fb7-49c2-a5af-f48b5aeabd77)

Clicking on what should be a legal placement for brown #63 does not show a legal upgrade path
![image](https://github.com/tobymao/18xx/assets/105426708/b6c2a1c1-fce6-4a0d-856e-37a991cc663b)

Full board state at this time - all upgrade paths except #63 appear to be working as intended
![image](https://github.com/tobymao/18xx/assets/105426708/178cf77e-0233-4674-b08d-7f5b3ae86882)

**Comment by benjaminxscott** [comment]
possibly related: #9852

**Comment by BellmakerSA** [comment]
This is not a bug according to the game’s upgrade chart (not in the enclosed rules). Only the one station greens can be upgrade to brown.

**Comment by benjaminxscott** [comment]
It looks like the single-slot cities on C13 (a 206) and G19 (a 205) also aren't being allowed to upgrade to a brown 63, which appears to be a bug

![image](https://github.com/tobymao/18xx/assets/1711810/cc356bdc-5876-4d5d-8d90-efe1e95f08b7)

**Comment by BellmakerSA** [comment]
> It looks like the single-slot cities on C13 (a 206) and G19 (a 205) also aren't being allowed to upgrade to a brown 63, which appears to be this bug
> 
> ![image](https://private-user-images.githubusercontent.com/1711810/303960454-cc356bdc-5876-4d5d-8d90-efe1e95f08b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3ODAxODksIm5iZiI6MTcwNzc3OTg4OSwicGF0aCI6Ii8xNzExODEwLzMwMzk2MDQ1NC1jYzM1NmJkYy01ODc2LTRkNWQtOGQ5MC1lZmUxZTk1ZjA4YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjMxODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNiZWI3NDA2NmEyMzc1ZmRiYTEzZjNhOTM1NmE5ODc3Nzc3OGU5MDA3YmYyYTAxOWNhMGQwMTYwY2E2NTE1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QleQnZkmwPiH4uc_gROmmixswr4PaK90ZxbtjEju6TM)
> 
> clicking the hex in hotseat on the RNB's turn where it can reach the tile, no upgrades shown ![image](https://private-user-images.githubusercontent.com/1711810/303960478-a6609887-f524-4d73-9c21-9784e9e1881b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3ODAxODksIm5iZiI6MTcwNzc3OTg4OSwicGF0aCI6Ii8xNzExODEwLzMwMzk2MDQ3OC1hNjYwOTg4Ny1mNTI0LTRkNzMtOWMyMS05Nzg0ZTllMTg4MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjMxODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMwZmU0MDYyNzI5ZjcwYTVkZTI2Zjg1YjU1MDcxNDc2ZWQ3NDdmYzMyZDUzODQwYjIxNDE1NDFlNWM0Y2JlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ud3aW7B8tzIBkWEmfKZy9TebZC3_n7P47wi2JhUakCE)

#63 can't go on C13 because you can't point a spoke at the dead spot where B12 is. Upgrades are working correctly.
