### ISSUE TITLE
Bankruptcy in 1846 mishandled

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#1031]
https://gist.github.com/gchambers419/748abbef6d29fb50b4520665774ac423

Player 3 bankrupted, but still owns stock.

From the rules:

After a player has gone bankrupt due to a forced train purchase 
(see 6.89), put the cash the player raised in the corporation’s 
treasury. Sell all remaining shares owned by this player to the 
Stock Market, even if this puts more than 50% of a corporation’s 
stock or a President certificate there. Add the money raised to the 
corporation’s treasury. This may result in a Presidency change in 
the corporation currently operating. If so, the new President must 
immediately purchase a train for it.

7.12 The certificate limit is unaffected by a bankruptcy.

7.13 If a corporation’s President certificate is in the Stock Market, 
modify the normal stock rules:
• A player may not sell stock in this corporation.
• If, after buying a share, a player owns 20% of this corporation 
then that player becomes President, swapping shares for the 
President certificate.
NOTE: A President certificate may not be directly bought from 
the Stock Market (as two shares). However, if only the President 
certificate is in the Stock Market, a player holding a 10% share 
in that corporation may purchase a virtual 10% share, swapping 
certificates appropriately.

7.14 A corporation with its President certificate in the Stock Market 
operates as follows in the Operating Round:
• It does not issue or redeem shares, lay track, purchase tokens, 
or purchase Private Companies.
• It will run routes with any train(s) it owns (for the most revenue 
possible) and retain its earnings (shifting its stock price one 
column left). If it does not own a train at this step, instead shift 
its stock price two columns left.
If it does not own a train and can afford to buy the cheapest 
available train from the bank, it will do so.

**Comment by gchambers419** [comment]
Continued the game and got to the point where it was C&O's turn again.  At thee buy-train step, the only option is "declare bankruptcy" but clicking it gets a "zero is not valid to spend" message

https://gist.github.com/gchambers419/edf973eef7fa1eb4f767f83628cc7eba

**Comment by tobymao** [comment]
dup
