### ISSUE TITLE
1846 unable to lay Meat Packing Token, except for immediately after corp buy in

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1032]
Game 3578, unable to place token in Chicago.

**Comment by tobymao** [comment]
as soon as the company is bought in, click on it's description, it should highlight blue, then click on chicago

**Comment by ChrisTheCat** [comment]
That is incorrect. There is no requirement in the rules to place the token
immediately on purchase of the company.

**Comment by JEBrosius** [comment]
Right now I am trying to buy the Meat Packing Company in with the IC and place the token in St. Louis.  I am trying to follow the instructions without success.

**Comment by tobymao** [comment]
the instructions are out dated, there is a new ability bar at the top by the history

**Comment by JEBrosius** [comment]
Thank you.

Eric
