### ISSUE TITLE
[1822CA] Miscalleneous Bugs and Fixes - Sawmill etc.

### ISSUE THREAD

**Issue by TheTagoreler** [tobymao/18xx#10326]
1. The Info tab game state notes still references the in-game currency as "£", presumably as this was forked from Base 22
2. The Sawmill private allowed me to place the Sawmill in a Y city/Grey city -looking at the code, (https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1822_ca/step/assign_sawmill.rb), it doesn't seem to have a block defining legality beyond preventing it from being placed in a town previously bulldozed by P29/P30.

**Comment by michaeljb** [comment]
Thanks for reporting! The hexes where the sawmill may be assigned are explicitly allow-listed, but they Y-city hexes were still in the list.
