### ISSUE TITLE
[21Moon] OLS doesn't allow builds fewer than 3 hexes from SpacePort

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#10324]
In the physical version of the game, the OLS private was updated to not allow its use on hexes fewer than 3 hexes away from the Space Port. In practice, this prevents its use on D10 and E5.

![image](https://github.com/tobymao/18xx/assets/26125362/cc77592e-9052-40e6-b5d2-d5979bf859fa)

I've already prepared the fix.

**Comment by roseundy** [comment]
This was overruled by Scott and Jonas on BGG.
https://boardgamegeek.com/thread/3237716/regarding-p1-ols-placement
