### ISSUE TITLE
18xx.games HTTPS certificate... is expired?

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10338]
**What's your Game ID?**

<img width="411" alt="Screenshot 2024-02-15 at 7 20 43 PM" src="https://github.com/tobymao/18xx/assets/455836/30b4e170-eecb-4651-8814-e028497fddee">

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by bubba0077** [comment]
Same here. Need to generate a new cert for the website.
