### ISSUE TITLE
[1888-N] Incorrect tile cost for B14 hex (Quick fix needed)

### ISSUE THREAD

**Issue by pltnc** [tobymao/18xx#10339]
**What's your Game ID?**

**How to Reproduce the Bug?**
The hex B14 should have no cost instead of $20 tile cost for all games

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment]
Could you provide a reference? The (presumably) [latest rules](https://www.kickstarter.com/projects/1840vienna/1888-north-china/posts/3609599) have maps showing a 20 cost for B14

https://www.lonnygames.com/games/1888-n/

![image](https://github.com/tobymao/18xx/assets/1711810/f6ce442e-ca3c-4ab8-94a8-d1c5629cca07)

**Comment by pltnc** [comment]
> Could you provide a reference? The (presumably) [latest rules](https://www.kickstarter.com/projects/1840vienna/1888-north-china/posts/3609599) have maps showing a 20 cost for B14
> 
> https://www.lonnygames.com/games/1888-n/
> 
> ![image](https://private-user-images.githubusercontent.com/1711810/305612640-f6ce442e-ca3c-4ab8-94a8-d1c5629cca07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODI3NTYsIm5iZiI6MTcwODE4MjQ1NiwicGF0aCI6Ii8xNzExODEwLzMwNTYxMjY0MC1mNmNlNDQyZS1jYTNjLTRhYjgtOTRhOC1kMWM1NjI5Y2NhMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTUwNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZhODBlMWRkMzZlYTlkMzc5NDI2NGQwY2U4NWUwMWQ1OTVhMGQ2NjVmNzIwZGJhNWJiMDlmNDliODE4M2JiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F5zheTy6D16U6tmt-_pDVINhC1OiRQU-1_Xo2avNeCY)

Hi, please refer to the pictures for the rule book and box of the Simplified Chinese version of this game, maybe you could double confirm with Lonny? All Simplified Chinese version does not have the cost 
![WhatsApp Image 2024-02-17 at 23 07 23](https://github.com/tobymao/18xx/assets/76254078/f601fdff-80cf-40a5-9f62-4e99c5446a00)
![WhatsApp Image 2024-02-17 at 23 07 22](https://github.com/tobymao/18xx/assets/76254078/0e2fddab-3598-4469-9460-f9dd6200a7f0)

**Comment by benjaminxscott** [comment]
no worries it's very helpful to have ppl double-check things
