### ISSUE TITLE
[21Moon] Timing for when can buy/activate Terminal Company

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10336]
**What's your Game ID?**
https://gist.github.com/jackpunt/afc954fea739869ab457bca4d65ed27c

**How to Reproduce the Bug?**
Tried to buy & activate the Term Company after placing track.
Was able to buy, but there was no offer to activate.

Workaround: undo the tracks, buy & place terminal, THEN place other tracks.

**Which Browser / Platform?**

**Comment by roseundy** [comment]
One the corporation has laid it's tiles, the game moves on to the token step. The rules say the power only applies during the track laying step.

I don't really see a way to fix this without requiring the president of the corporation owning the private to always have to click "Skip" to end the track laying step even if they already laid two tracks. I feel this is a quality of play issue and fixing it would make thinks worse and less intuitive. Other games have this exact same issue.

**Comment by jackpunt** [comment]
Ack. it's not a blocker, easy enough to 'undo' back to beginning of track laying.
(near as I can tell, you can't buy&activate _between_ track1 and track2)

**Comment by jackpunt** [comment]
By the way:

Looks like the 18xx.games HTTPS certificate has expired... 
(in Chrome 'Advanced' you can load anyway) but it times out regularly...

**Comment by roseundy** [comment]
Nevermind, I think I can fix this easily without making the game play slower.

**Comment by roseundy** [comment]
And nope, my idea didn't work. Will probably just close this bug.

**Comment by benjaminxscott** [comment]
> unable to activate Terminal between normal track lays

fwiw I tested and this case does work
https://gist.github.com/benjaminxscott/5067ac8da83f5c8b20b119bd9d4d6f71
