### ISSUE TITLE
[21Moon] Share price order during CorpRound when stock price drops

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10335]
**What's your Game ID?**
https://gist.github.com/jackpunt/e4387a407250a151a0bbfd2119c51fa8

**How to Reproduce the Bug?**
During corp round LG (1st @ $80) sells a share of KR (2nd @ $70) which drops KR to $60
I expected that would put KR in 4th place (after the other Corps that are already at $60)

? Is the order of operation set and invariant at the beginning of the Corp Round?

"The round proceeds in descending share price order
(see 5.2), and each started corporation gets
exactly one turn."

<img width="1311" alt="Screenshot 2024-02-15 at 1 43 37 PM" src="https://github.com/tobymao/18xx/assets/455836/f34cfce7-2b34-4ef1-b850-743ee6bfaab6">

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Checking with Scott...

**Comment by roseundy** [comment]
And Scott indicates it needs fixing.

**Comment by roseundy** [comment]
Apparently I meant for this work to work the way it should, but I never called the method in the corporate round that I wrote way back when.
