### ISSUE TITLE
When I create a Multiplayer game, I don't get a Join or Enter button?

### ISSUE THREAD

**Issue by dmitton42** [tobymao/18xx#1034]
How am I supposed to be able to create a game and play it?

**Comment by tobymao** [comment]
it may be easier if you ask these questions in the in game chat

if you want to play by yourself, you can make a hot seat game. if you want to play with other people, join a multiplayer game or create your own.

**Comment by tobymao** [comment]
when you create a game, you're automatically in the game so you don't need to click join or enter

**Comment by dmitton42** [comment]
If I'm in the game, where is it?
When I push the create a game button I am back out to the main screen where the game is listed under Your Games.
With only a Delete button.

I can ask people in chat things, but no one seems to understand my problems.

**Comment by tobymao** [comment]
that's it, you wait for people to join your game, when you're ready, you
click start game

**Comment by dmitton42** [comment]
So, I cannot join my own game until someone else does?

**Comment by dmitton42** [comment]
Active Games needs a search box, and/or filters

**Comment by tobymao** [comment]
you've already joined your game automatically by being the creator

**Comment by dmitton42** [comment]
So until the other player's join... it's in limbo?  Do I get a notification?    I guess I could create alternate egos for testing...

**Comment by tobymao** [comment]
well you can't play a 1 player game. if you want to play by yourself with
fake players, create a hot seat game.

**Comment by dmitton42** [comment]
Yeah, did that,  remember it doesn't transport to my other system. 
I'm trying to make sure I understand this well enough to explain to some of my friends which will be the players.
I'm not ready yet (time wise ) to sit down with other real players.

**Comment by tobymao** [comment]
Just play around in hotseat mode. It is enough to learn how to use the
system.
