### ISSUE TITLE
[21Moon] Train from LB is not connected to LB

### ISSUE THREAD

**Issue by jackpunt** [tobymao/18xx#10363]
**What's your Game ID?**
https://gist.github.com/jackpunt/15e5c4f0b460395fafe2ee8bd4b9e544

Auto-router came up with this routing, but it looks wrong; I don't see how Pink T2 is connected to LB

<img width="980" alt="Screenshot 2024-02-18 at 4 13 33 PM" src="https://github.com/tobymao/18xx/assets/455836/bf8a815f-6b4b-4dc5-bf67-caa00176447c">

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by jackpunt** [comment]
Strangely, THIS "continuation" route is marked illegal.
<img width="854" alt="Screenshot 2024-02-18 at 4 47 14 PM" src="https://github.com/tobymao/18xx/assets/455836/4d29efc6-ff54-40c8-ac83-9758cf487e09">

**Comment by roseundy** [comment]
I don't see a problem

**Comment by jackpunt** [comment]
OH!?

So "intersect at a stop" can be a stop that is otherwise blocked to the train?

I didn't expect that... we thought the path back to the LB needed to be passable!


"If a base is running two transports, the first
must include that base’s token (Space Port or
local base) on its route. The second transport’s route must **intersect with the first route
at a stop**, and must include either the base’s
token or a depot token."
