### ISSUE TITLE
new warning when running rack rake

### ISSUE THREAD

**Issue by andrewzwicky** [tobymao/18xx#10381]
**How to Reproduce the Problem?**

`docker-compose exec rack rake` now has many warnings saying:

``warning: Backtick operator usage interpreted as intent to embed JavaScript; this code will break in Opal 2.0; add a magic comment: `# backtick_javascript: true` -- (file):``

**Which Browser / Platform?**
Github Codespaces

![image](https://github.com/tobymao/18xx/assets/5263073/b7892295-cac6-4467-b1e4-79f96d1c0f0d)

I'm assuming it's related to the new Opal version.  Doesn't seem like it actually hurt anything.

**Comment by michaeljb** [comment]
Got it down to just one anyway. Thanks!
