### ISSUE TITLE
[System18] odd separated hex on the NEUS map

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#10385]
https://18xx.games/game/153951

**How to Reproduce the Bug?**

It's the map as created. It's in the code, I'm guessing a mistype of some sort (but maybe I'm wrong!)

Please include screenshots (you can drag and drop or upload them into this issue)

![image](https://github.com/tobymao/18xx/assets/26125362/8d586f6d-ef16-40d2-a1ba-d7860615c844)

**Comment by roseundy** [comment]
This was a spurious hex in code that I created S18 with. I'm not sure why it never showed up before. @michaeljb did your UI change affect this?
