### ISSUE TITLE
[1841] First shares offered to the wrong player during Tuscan merge.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10389]
https://18xx.games/game/150150?action=434

***Relevant rules/game state:***
physicssquirrel has 3 shares. Hushed has 4 shares. We are each the president of a company at L.70 on different parts of the stock market, but Hushed's company is farther to the right. In the Tuscan merge the president of the company with the highest value executes the merge, and the tiebreak for highest value is the rightmost company, so Hushed should exchange shares first.
Exchanging pairs of shares happens before exchanging half shares.

***Repro***
Navigate to the link above. Notice that phtsicssquirrel is offered the opportunity to trade half shares \*before\* Hushed exchanges pairs of shares.

Expected: Hushed exchanges pairs (receiving the presidency) before I get the option to "special tradeup" to the presidency.

***Additional Thoughts***
I am not sure of the root cause. It is probably either
~~A. Internally, pairs of shares are being exchanged at the end instead of the beginning, so I am offered the trade up, because I happen to have the only half shares.~~
B. The rightmost company is not being given the tiebreak for highest value, and an arbitrary L.70 company is chosen instead (mine)
*[Edit: I tried declining the special trade up and it then exchanged pairs of shares and offered to let me buy up, so it appears the cause is B.]*

**Comment by roseundy** [comment]
Yes, I'm sure it's the tie-break. This calculation has been troublesome in the past.

**Comment by roseundy** [comment]
Can you point to the rule that says the tiebreaker is the rightmost corporation? My copy of the rules just say
`The merges are always performed by the President of the Corporation currently having the greater value.`

My code is picking arbitrarily, which I agree is not great, but has there been a clarification on this specific rule?

**Comment by roseundy** [comment]
Fixing this by using the operating turn order rules (Section 4 of the rules)
