### ISSUE TITLE
[System 18 - Map Twisting Tracks] iOS error?

### ISSUE THREAD

**Issue by ViennaTramways** [tobymao/18xx#10396]
Id: 153986
I play the game on different machines: PC, iphone, macbook. On iphone and macbook I get strange error codes, on the PC it works properly.

**Comment by roseundy** [comment]
What issues are you seeing? Can you attach a screenshot?

Unfortunately I don't have an iphone or mac to test it on. It seems fine on my android phone.

**Comment by ViennaTramways** [comment]
Hello Steve,

I apologize for the inconvenience - it seems to work now. I was waiting for
more error messages, but I believe the system is sometimes slow...

Lonny

Am Mo., 26. Feb. 2024 um 02:45 Uhr schrieb Steve ***@***.***>:
