### ISSUE TITLE
Improvements from XB_XB

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#104]
~~No Bank - there’s no bank showing anywhere so we dont know how much is in the bank or when it breaks.~~
~~Train Roster - be great to have a train roster showing what’s left/available and costs somewhere (maybe in the dead space right of the map).~~
~~Share Prices (Market and IPO) - We found it annoying to not be able to see IPO vs Market prices for shares - you didn’t get to see prices for both until trying to buy something when it would finally tell you what they were.~~
Private Sale Value error - during one of the ORs we discovered an error.  It is possible for a player to pay more than twice the Private’s face value; the player without realising it was not allowed selected the private to buy in, deleted the pre-set double-face value and typed in an amount.  (We obviously undid that action when we realised but we’re highlighting that it is able to be done.)
Port tile locations - a symbol on the map indicating clearly where the port tile can be laid would be nice.
Priority Marker - Be great to have something to indicate this player or that one has priority for the next SR.  Yes it announces it as part of the record log but some on-going flag/asterisk/mark on the name would be great as a visual aide without having to scroll back through the log to find the one line where it was mentioned.
~~Uno-Takamatsu - The private company is misspelt (missing the second T).~~
~~Tile 465 - the K tile for upgrade of the Kouchi F9 city should have 3 token locations not 2.  Also has a value of 60 not 40.~~
PASS button - we all thought the name was odd.  It took a few goes and false starts before we realised pass meant “I have finished with taking action blah blah”.  Ideally a button saying “Finished Lay Track action” or “Completed Action Blah” (or Done with or some other phrase/word which also included the phase that was now completed) would be much clearer.
UNDO button - seemed cool to be able to take action on behalf of other players and to undo those actions, but it was actually really easy to rewind/undo to well before the place you wanted.  The button location, color, and ease of use meant we were undoing then having to redo more than we realised.  Maybe it could be adjusted a touch.

**Comment by dfannius** [comment]
I've struck through items that have been done.

**Comment by tobymao** [comment]
i've done most of these issues, except some enhancements, will close for now
