### ISSUE TITLE
[System18] cannot lay track or post text in chat. Returning error 

### ISSUE THREAD

**Issue by tphon** [tobymao/18xx#10402]
In_ game https://18xx.games/game/154315
Laying track provides error at top of screen and does a reset.
I get the same issue when trying to add text to the in game chat.

**Comment by roseundy** [comment]
What is the error you are getting?

I can't reproduce this. It's possible you need to refresh your browser (shift-cntl-R on Chrome).

**Comment by tphon** [comment]
Thanks for checking. Wouldn't work on PC with Chrome but did work on my tablet. I'll keep an eye on PC performance. 

On 27 February 2024, at 01:08, Steve ***@***.***> wrote:

What is the error you are getting?

I can't reproduce this. It's possible you need to refresh your browser (shift-cntl-R on Chrome).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/tobymao/18xx/issues/10402#issuecomment-1965610534">https://github.com/tobymao/18xx/issues/10402#issuecomment-1965610534</a>", "url": "<a href="https://github.com/tobymao/18xx/issues/10402#issuecomment-1965610534">https://github.com/tobymao/18xx/issues/10402#issuecomment-1965610534</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
