### ISSUE TITLE
[1846] Unable to assign steamboat to a company during private income step prior to buy-in

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#1041]
First: I have read other issues related to this, including the following:
https://github.com/tobymao/18xx/issues/851
https://github.com/tobymao/18xx/issues/920
https://github.com/tobymao/18xx/pull/991

I believe this is either new or a separate, possibly overlooked issue.

Perhaps this is a UI issue (as in, I just can't figure out how to do it) but I'd appreciate if the devs can confirm with me (I promise to respond!) before closing the issue.

I have a hotseat test game (https://www.18xx.games/hotseat/hs_rskbdjmk_1594215514) where I have just reached the private income step and while I can click on the Steamboat Company and click on, say, Wheeling, I then click on steamboat again and see no way of clicking on the B&O to assign the power.  Am I missing how to do this?

(One note is that if the rules are being enforced to restrict the steamboat assignment per the rules to this specific step I'd recommend a prompt requiring a yes/no "do you want to assign/shift steamboat" prior to MS operating, but I'll file another issue recommending that enhancement.)

**Comment by benjaminxscott** [comment]
Can repro, assigning SBC to a hex works fine, but can't assign to a corp
[This loc](https://github.com/tobymao/18xx/blob/96c86d7d167b35e773d794c610861dc08a152868/lib/engine/round/special.rb#L100) should be implementing the corp assignment, it just doesn't seem to be firing as expected

(fwiw hotseat games are local-only, you can drag-n-drop a textfile or upload a gist if you want to include repro json)

**Comment by Spobster** [comment]
Concerning the steamboat, I think there is a second issue that may need to be fixed:

1. The player with the Steamboat Company can not assign it to a corporation in the private income step (see issue filed above). 
2. The player with the Steamboat Company can assign it to a hex during the turn of one of his/her corporations, even though it was not assigned to that corporation (it seems that the player can only to this once per game). This is not allowed according to the rules. Interestingly, there is no value assigned to the corporation's ride hitting the assigned hex, also not in the next OR.

Thus it seems impossible to use the Steamboat Company when possessed by a player.

**Comment by benjaminxscott** [comment]
Seems to be fixed by https://github.com/tobymao/18xx/pull/1080 
(first click private's card, then the hex, then the company)
[steamed_boats.json.txt](https://github.com/tobymao/18xx/files/4935490/steamed_boats.json.txt)

**Comment by benjaminxscott** [comment]
Notably this issue seems to have been resurfaced, possibly due to the refactored usage flow for private abiliites
