### ISSUE TITLE
System18 - Unlimited last rank of trains

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#10413]
Although the number of trains defined in System18 "base" is a constant 5 to be used as a reference for what components come in the base game, I think that generally maps will have unlimited copies of the last rank of trains (this is what I have printed on the physical maps). Should this be hardcoded in base?

Otherwise, all maps on the site should have unlimited last rank of trains (except Twisting Tracks).

For Twisting Tracks, there is a hard limit of 1 copy per rank of D-train. To make sure we don't run out of trains, I am changing the train limit on Twisting Tracks to 1 on Phase D (the gray one, and remains so for the remainder of the game).

**Comment by roseundy** [comment]
Given the train limit of 2 in the final phase (for all but Twisting Tracks), 20 D/8 trains should be sufficient.

**Comment by scottredracecar** [comment]
Indirectly noted here, but please also change the train limit on Phase D (gray) for Twisting Tracks to 1 too as part of this change.
