### ISSUE TITLE
[Shikoku 1889] No token step with Awa Railroad

### ISSUE THREAD

**Issue by Frenchwolfie** [tobymao/18xx#10422]
[Shikoku 1889 No Token step for Awa Railroad]

**What's your Game ID?**

https://github.com/Frenchwolfie/AwaRailroadBug/blob/main/game%20sample

**How to Reproduce the Bug?**

See game sample last actions.

**Which Browser / Platform?**

DuckDuckGo 0.68.0

**Comment by michaeljb** [comment]
In OR 6.3, Awa's token step is skipped because it has less than the cost of placing a token, ¥40, in its treasury. Working as intended.
