### ISSUE TITLE
[1880] Company's train purchase step skipped after SR ends

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#10429]
GameID: 154247

Link to move: https://18xx.games/game/154247?action=253

Issue:
Previous OR ended at NJR purchasing the last 3T. At the time, NJR lacked sufficient funds to purchase another train. During the SR, 5th share of NJR was purchased, giving NJR sufficient funds to purchase the first 3+3. However, at the end of the SR NJR's remaining train purchase action was skipped, moving to the next company to operate. NJR is not train-tight.

**Comment by crericha** [comment]
@djanyreason is this still an issue? Looking at https://18xx.games/game/154247?action=253, it shows NJR at the train buying step at the beginning of the OR.

**Comment by crericha** [comment]
Linked game working correctly as far as I can tell. Reopen if not the case.
