### ISSUE TITLE
[18Esp] strange error cannot continue game 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10426]
https://18xx.games/game/153929

![A8219155-60B9-441B-80B3-DBD4F06B4A8C](https://github.com/tobymao/18xx/assets/73144084/98be6e2a-cfdd-4edc-9f8d-29bfa1247148)

I have no idea what could cause this error.

**Comment by michaeljb** [comment]
What action was attempted when this error appeared?

**Comment by BellmakerSA** [comment]
> What action was attempted when this error appeared?

Attempted to pay out.

**Comment by l33twash0r** [comment]
https://18xx.games/game/153924
This game is also loading quite slow,y but it's stuck on company's turn after I tried to pay out and avoid buying any trains it just resets to choosing payout or withold.
