### ISSUE TITLE
[1846] Recommend prompt during private income step for steamboat assign/shift

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#1043]
Many people play loosely on when the steamboat token gets assigned in 46 - if it was obvious and they forgot to do it during the private income step they'll ask the table "oh I meant to have assigned the token to Wheeling (or some other location)" - since that is difficult to properly or fairly implement (especially since it's breaking the rules of the game), and considering it could mean undoing multiple corporation's entire turns to get back to the private income step - I'd recommend the following as a UI enhancement:

During the private income step a prompt requiring a yes/no "do you want to assign/shift steamboat" could be shown, prior to MS operating (perhaps with a checkbox somewhere else - possibly within the private - to enable or disable this prompt.

**Comment by tobymao** [comment]
dup

**Comment by eheiden** [comment]
Hey Toby - could you point me to which issue this is a dup of?
