### ISSUE TITLE
ArgumentError: wrong array length at 1 (expected 2, was 1)

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1044]
Trying to add a sticky icon to 18AL. In the example below I use an existing icon (meat) from 1846 just to show the problem.

In file lib/engine/config/game/g_18_al.rb I have the following configuration for 5 city hexes:
```
"city=revenue:0":[
   "J7",
  "K2",
  "L5",
  "G6",
  "H3"
],
```

And now I want an icon there, so I add an image:
```
"city=revenue:0;icon=image:1846/meat":[
   "J7",
  "K2",
  "L5",
  "G6",
  "H3"
],
```

When I refresh the map of an 18AL game I can see the meat icon appearing at these 5 hexes.

But I also want the icon to stay when I upgrade the hexes, so I add a sticky attribute:
```
"city=revenue:0;icon=image:1846/meat,sticky=1":[
   "J7",
  "K2",
  "L5",
  "G6",
  "H3"
],
```

When I refresh the game I now get an error message:
ArgumentError: wrong array length at 1 (expected 2, was 1)

If I remove the sticky attribute, the error disappear, but then the icon is removed when hex is upgraded.

**Comment by tobymao** [comment]
sticky: 1, you have written sticky=1

this is better for the slack channel as opposed to a github issue

**Comment by perwestling** [comment]
Ah... thanks.
