### ISSUE TITLE
[System18] Crash Report

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#10444]
We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action
Broken action: { "type": "buy_shares", "entity": 606, "entity_type": "player", "created_at": 1709581640, "shares": [ "PHX_4" ], "percent": 10 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3ASystem18,%22needs%20triage%22) and include this link (https://18xx.games/game/154677?action=9)

**Comment by michaeljb** [comment]
Archived for #10430
