### ISSUE TITLE
[1858] Additional M&A token slot after Madrid upgrade to Green tile.

### ISSUE THREAD

**Issue by GalaxyTrukker** [tobymao/18xx#10442]
https://18xx.games/game/155282?action=296

M&A had been exchanged for AVT in SR 3. 
In OR 3.1 RP ran before AVT, upgraded Madrid to green creating an additional token space in NE slot showing AVT / M&A. 
After AVT ran, M&A token space remained with no name. 

It was possible to token this space as well as trace route through Madrid. Reversed the token/run to follow the rules - and not risk breaking the game on brown upgrade.

**Comment by ollybh** [comment]
![image](https://github.com/tobymao/18xx/assets/11144854/b64d6389-554b-45c6-9515-0dfd5092ed6b)
Well, that's not right.

What's happened here is:

1. M&A is used to form AVT in stock round 3.
2. AVT places its home token in M&A's slot in the NE Madrid city.
3. In OR 3.1 RP operates before AVT.
4. RP upgrades Madrid to green.

At this point M&A hasn't yet closed and the code for moving tokens and reservations sees both AVT's token and M&A's reservation in the NE Madrid city, and helpfully creates a second slot to accommodate both of these.

The solution to this should be to clear M&A's reservation when AVT's home token is placed.
