### ISSUE TITLE
[18Carolinas] View error when entering 'track conversion mode'

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10458]
Error thrown:
> Uncaught TypeError: Cannot add property elm, object is not extensible

WNC attempts to enter 'track conversion mode' which throws error
https://18xx.games/game/150357?action=473
(this game is broken after that point)

https://gist.github.com/benjaminxscott/2204049136f453bb0ff076f402c760d0

Looks like an issue w/ the view rendering

**Comment by roseundy** [comment]
I looked at another (finished) game and it shows the same error if I go back in history to a track conversion step. I'm thinking some infrastructure change broke 18Carolinas. It must have occurred after Feb 15 2024.

**Comment by roseundy** [comment]
My guess is the Opal and Ruby updates on Feb 20.

**Comment by roseundy** [comment]
Root cause: missing .compact on the TrackConversion render method.
