### ISSUE TITLE
[21Moon] Several gray tiles are mislabeled compared to the published edition

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#10466]
[155627, action 512](https://18xx.games/game/155627?action=512)

**How to Reproduce the Bug?**

VH selects X26 which is correctly added but mislabeled in the log as X27

![18xxbug](https://github.com/tobymao/18xx/assets/757327/3b1f599f-bb21-4a18-850f-6ab4d7d248d2)

**Which Browser / Platform?**

Safari on iOS 17.4

**Comment by philcampeau** [comment]
Looks like more late changes. I compared [https://boardgamegeek.com/image/7992433/scottredracecar]Scott's updated tile list(URL) with what's on the site, here's what I found:

- Tiles labelled X22, X23, and X24 on Scotts list are X24, X25, and X26 on .games.
- Tile X25 from Scott's list is absent from .games
- Tiles labelled X26-X29 are all one higher on .games, X27-X30.
- The tiles on .games that are labelled X22 and X23 aren't actually tiles in the published version, just tokens.

**Comment by benjaminxscott** [comment]
In that case the rules link is also out of date, and idk where the canonical rules live

Currently we link to this file (which is the most visible on BGG)
https://boardgamegeek.com/filepage/263361/21moon-rules

I don't see a rules link on the game's AAG page
https://all-aboardgames.com/products/21moon?variant=39673600049236

or AAG's rules list
https://all-aboardgames.com/pages/rules

**Comment by philcampeau** [comment]
The link I included above is the most recent version, referenced in this comment from @scottredracecar https://boardgamegeek.com/thread/3213195/article/43681661#43681661

Though there's a more recent comment from someone saying there are still omissions.

**Comment by philcampeau** [comment]
Another tile difference reported, with a reply from Jonas: https://boardgamegeek.com/thread/3265911/terminal-tile

**Comment by benjaminxscott** [comment]
Ah OK, it sounds like an official updated PDF is incoming
