### ISSUE TITLE
[1848] Sydney and Adelaide falsely declared connected.

### ISSUE THREAD

**Issue by epigamic** [tobymao/18xx#10468]
Game ID: 155335

The bug manifests at this point in the game: https://18xx.games/game/155335?action=620

Description:
VR upgraded tile F13, causing a connection from Sydney to Adelaide, but it is a spurious one as far as I can tell.

The only way for a train to travel from Sydney to Adelaide is by re-using track on tile C16.

The rules state: "(5.3.2) Sydney to Adelaide Link: The company is launched and begins to operate once 60% of its shares have been bought and a notional train of infinite range could travel from Sydney to Adelaide. (Station tokens don’t act as blockers when applying the second part of this test.)"

Chrome version 22.0.6261.112 for me - other players are using other browsers.

**Comment by benjaminxscott** [comment]
possibly same issue as:
https://github.com/tobymao/18xx/issues/10223
where the connectivity check is spuriously using A18 offboard
