### ISSUE TITLE
[21moon] Terminal Tile

### ISSUE THREAD

**Issue by FelineWrangler** [tobymao/18xx#10477]
Terminal tile should have revenue 30yellow, 20green, 10brown

**Comment by benjaminxscott** [comment]
Currently the .games implementation and the printed game diverge and an updated official rules document seems to be in the works

Confirmed that the Passenger Terminal tile in Scott's updated tileset image reflects the 30/20/10 values

https://boardgamegeek.com/image/7992433/scottredracecar

**Comment by roseundy** [comment]
BTW, the tile is 30yellow, 20brown, 10gray
