### ISSUE TITLE
Game chat visible publicly (unintentionally?) under certain circumstances

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10478]
**What's your idea?**
There's been some discussion about how game chats are available if a user (who's not in a game) starts viewing a game and then stays on the page w/o manually reloading

I'm not sure this is expected behavior, given the prior PR that implemented the chat stripping feature

Patching that may be unpopular due to current usage, so perhaps we implement an opt-in "make chat public" on game creation?

https://github.com/tobymao/18xx/pull/8171/files#diff-8b1c776b20fe190442fcbb137476bcd56329cb1b568e0ee20c8d23f4b0b5af4e

LoC
https://github.com/tobymao/18xx/blob/master/lib/engine/game/base.rb#L713

**Are there related ideas?**
I didn't see this issue reported

**Comment by tobymao** [comment]
working as intended for now, we just don't keep any history
