### ISSUE TITLE
[18ESP] acquiring corp should be able to keep MZ token on map when MZA is removed during initial setup

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10476]
https://18xx.games/game/155560?action=379

The takeover company should be able to keep the MZ token in Madrid with MZA out of the game but is not able to do so.

**Comment by benjaminxscott** [comment]
Seems like the issue is that acquired minor's token cannot be 'kept on the map' and only put back on the charter

![image](https://github.com/tobymao/18xx/assets/1711810/cfbaca86-6596-4293-a476-35c2cfdedd28)
