### ISSUE TITLE
[1880] Broken game

### ISSUE THREAD

**Issue by Git-Yoda** [tobymao/18xx#10487]
https://18xx.games/game/150832

Async game. 

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "choose", "entity": 15185, "entity_type": "player", "id": 70, "created_at": 1707205476, "choice": "ABC" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1880,%22needs%20triage%22) and include this link (https://18xx.games/game/150832?action=69)

**Comment by ollybh** [comment]
Duplicate of #10484.
