### ISSUE TITLE
Multiple games broken with error `uninitialized constant Engine::SharePool::Set`

### ISSUE THREAD

**Issue by lavoieba** [tobymao/18xx#10484]
Below is the message seen at the top of the screen after entering the game. The game has also reset itself to the SR1 from MR4.1.

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 776, "entity_type": "player", "id": 121, "created_at": 1708890243 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A18USA,%22needs%20triage%22) and include this link (https://18xx.games/game/153253?action=120)

**Comment by richpri** [comment]
I have the same type of message for 2 of my games. 
https://18xx.games/game/156063?action=39
https://18xx.games/game/151868?action=21
Will these games have to be abandoned?

**Comment by ollybh** [comment]
> I have the same type of message for 2 of my games. https://18xx.games/game/156063?action=39 https://18xx.games/game/151868?action=21 Will these games have to be abandoned?

No, you just need to wait for a fix to be pushed to the server code. Everything should then start working again.
