### ISSUE TITLE
game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set

### ISSUE THREAD

**Issue by answard007** [tobymao/18xx#10498]
[1882] game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set

Broken action: { "type": "pass", "entity": 5475, "entity_type": "player", "id": 21, "created_at": 1710607897 }

**What's your Game ID?**
https://18xx.games/game/156686?action=20

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment]
Duplicate of #10484.
