### ISSUE TITLE
[Shikoku 1889] Broken game

### ISSUE THREAD

**Issue by Git-Yoda** [tobymao/18xx#10491]
https://18xx.games/game/153005

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 10727, "entity_type": "player", "id": 13, "created_at": 1708019870, "corporation": "IR", "share_price": "75,3,3" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1889,%22needs%20triage%22) and include this link (https://18xx.games/game/153005?action=12)

**Comment by ollybh** [comment]
Duplicate of #10484.
