### ISSUE TITLE
Legal connection for laying track, but tile is not accessible (gameid #75)

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#105]
Takamatsu wants to build track in C8 (current OR7.1), which is a legal spot, but is still gray and not possible. Probably because of the previous bugfix that one could still build track even though the spot was blocked by a station. However in this case there is an alternative route to C8, so the station doesn't need to be hit by a fictive dieseltrain.

**Comment by tobymao** [comment]
fixed

**Comment by Spobster** [comment]
Hi Toby, is this fixed in new games only? In the current game, I can still not upgrade the tile on C8. The tile is still "blurred", so there is no option for me even to click on the tile. Thanks for all your efforts! Spobster
