### ISSUE TITLE
[1828.games] Broken action

### ISSUE THREAD

**Issue by Aposky** [tobymao/18xx#10509]
[**What's your Game ID?**](https://18xx.games/game/156377?action=27)

Having following bug
```
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "bid", "entity": 10302, "entity_type": "player", "id": 28, "created_at": 1710448974, "company": "C&A", "price": 160 }
```

During Auction Round 1 - Bid on Companies, player AverageTrainFan buys Camden & Amboy Railroad for $160 and causes this error.

**Which Browser / Platform?**

Browser and platform: any, all players experienced that.

**Comment by ollybh** [comment]
https://18xx.games/game/155495?action=19
