### ISSUE TITLE
Bug with 1861

### ISSUE THREAD

**Issue by sereghk0** [tobymao/18xx#10500]
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 14458, "entity_type": "player", "id": 32, "created_at": 1710425104 }

https://18xx.games/game/156490?action=31
-->

**Which Browser / Platform?**

**Comment by ianwilson156** [comment]
1867 and 1840 are also affected, but not 1862 or 18GB.

**Comment by ollybh** [comment]
Duplicate of #10484.
