### ISSUE TITLE
1846

### ISSUE THREAD

**Issue by kcshaple** [tobymao/18xx#10511]
**What's your Game ID?**

**How to Reproduce the Bug?**
No idea
What steps cause the unexpected behavior?
Don’t know, I opened it up as notified my go and had reverted to company selection when we were in SDR3 !

Please include screenshots (you can drag and drop or upload them into this issue)
![image](https://github.com/tobymao/18xx/assets/163724905/e703ba7d-0ff6-49ef-813f-f530d2680280)

-->

On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform Mobile

**Comment by ollybh** [comment]
Duplicate of #10484.

**Comment by kcshaple** [comment]
Apols it was actually 155475. But I’ve never encountered error before and have no idea how to report it on GitHub. So Apols for any snafu.
Needless to say I can’t close the game on 18XX
