### ISSUE TITLE
[18MEX] Auto-routing gives an invalid route

### ISSUE THREAD

**Issue by branidal** [tobymao/18xx#10526]
**What's your Game ID?**

https://18xx.games/game/156331?action=243

**How to Reproduce the Bug?**

Click Auto
- Track on F5 (Copper Canyon) is re-used.

![image](https://github.com/tobymao/18xx/assets/14219087/4baec2e1-5c51-46df-b565-1d4794ff67d6)

**Which Browser / Platform?**
Firefox 123.0.1

**Comment by branidal** [comment]
I just realized this is a duplicate of #8571

**Comment by benjaminxscott** [comment]
no worries, that's a pretty old bug ha

I'd fix it but the autorouter code is black magic
