### ISSUE TITLE
[The Old Prince 1871] Incorrect exchange options

### ISSUE THREAD

**Issue by Galatolol** [tobymao/18xx#10537]
**What's your Game ID?**

https://18xx.games/game/156504?action=269

**How to Reproduce the Bug?**

Click on the Alberton charter. Only 2 first options from the following screenshot should be available. The next two should never be proposed.

![image](https://github.com/tobymao/18xx/assets/10097748/b893ef74-f59a-4662-b362-519dd58c5302)

**Which Browser / Platform?**

- Browser Version
Firefox 123.0.1

**Comment by ollybh** [comment]
I've also seen this in [game 153513](https://18xx.games/game/153513).
