### ISSUE TITLE
[1846] 3/5 train with EW + meatpacking incorrect payout

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#1053]
https://gist.github.com/adamranderson/7dc3e12622e97d21c73079ca38347238

In this game IC is running a 3/5 train from Chicago connections to Windsor. The meat packing token is assigned to the IC and is assigned to Chicago. The game calculates the best run as: Chicago connections (7) - Detroit (5) - Windsor (7) for 19 total.  With meatpacking the route should replace Detroit with Chicago (7) for 21 total.

**Comment by Spobster** [comment]
Please check whether the 3/5 run from IC in this one is fixed as well after fixing the bug. It does not involve the meatpacking company.

https://gist.github.com/Spobster/6bbecab69d3d2fc3d069e4f0debc0daa

(was posted as #1127)

**Comment by vantdog** [comment]
have another issue with a 3/5 and meat packing - involving PRR. 

Game 6005. First time I ran this train - it ran correctly. Paid out Windsor, Chicago (with Meat packing) and Chicago Connections for 210 (in Green phase - so Chicago upgraded to Green). 

Next OR - I tokened in Detroit - and ran the same route with the 3/5. Only paying out 190 that time. I think it paid Detroit instead of Chicago?

-Tim

**Comment by adamranderson** [comment]
Hit this again in a similar way to vantdog. Game data https://gist.github.com/adamranderson/150fcf54a0dbe5cbc6ed92fa2e372379

I suspect that the 3/5 train is picking Detroit ($50) over Chicago ($40) at face value and not seeing the +$30 meat packing token.

**Comment by adamranderson** [comment]
This is working as intended. The 3/5 will only pick up Chicago and the EW run if the company has a token in Chicago. One of the 3 stops must have a token.

From the rules: 
"N/M trains, such as a 3/5 (“three out of five”) train. These may
count any number of cities and off-board areas totaling up to
N towards its revenue (with at least one of them containing a
token belonging to the corporation), while visiting up to M
cities and off-board areas. An N/M train cannot visit more than
M locations."

**Comment by adamranderson** [comment]
Looks like the bug still exists if a token is Chicago. It was only working as intended if the company only has a token in Detroit.

https://gist.github.com/adamranderson/150fcf54a0dbe5cbc6ed92fa2e372379

**Comment by dfannius** [comment]
Fixed with https://github.com/tobymao/18xx/commit/d5437b0f1bef304dc58ecf44e850ce873a9ecdd7.
