### ISSUE TITLE
[18Mag] buy_share step autoskipped after selling down under cert limit on my turn

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10545]
Action https://18xx.games/game/153991?action=843 

https://gist.github.com/benjaminxscott/0caca5ff5380231b5b21540cfaf9fe61

> (I previously to report it, I asked directly to Lonny Orgler, author of the game)

In SR6  I had the `RABA` presidency and was at cert limit (14/14). 
Another player took the `RABA` presidency resulting in me being over cert limit (15/14) and I became obligated to sell down on my turn.

On my turn I sold two shares of `RABA`  resulting in cert count (13/14), but my "buy share" action was erroneously auto-skipped. Action order is "sell any then buy one"

**Comment by benjaminxscott** [comment]
Confirmed that the rules don't mention anything about not being able to buy shares after selling down

This likely applies to other games, thanks for noticing this!

What did Lonny say?

**Comment by queroscia** [comment]
I asked directly to Lonny before reporting you, and he confirmed it is a bug. And, actually, it could be an usual bug in other games.

Best regards,

Enrique.

Enviado desde mi iPad

El 23 mar 2024, a las 20:05, Benjamin Scott ***@***.***> escribió:

﻿

Confirmed that the rules don't mention anything about not being able to buy shares after selling down

This likely applies to other games, thanks for noticing this!

What did Lonny say?

**Comment by roseundy** [comment]
You were auto-skipped because you had enabled auto-pass for this stock round. There is no bug. In order to buy a share after selling down your RABA stock, you just need to disable auto-pass.
