### ISSUE TITLE
[21moon] Unable to use Terminal power during Track Lay step

### ISSUE THREAD

**Issue by mkkohls** [tobymao/18xx#10547]
https://18xx.games/game/157057?action=79

https://gist.github.com/benjaminxscott/5067ac8da83f5c8b20b119bd9d4d6f71

Unable to lay terminal tile after buying in private. The terminal highlights but nothing happens.

Chrome on android

**Comment by benjaminxscott** [comment]
Confirmed this occurs during the track lay step when the corp s.b. able to lay the tile

N.B. the live game has diverged from the bugged state (purchased Terminal at the end of SSB's turn), so the gist has a repro state

![image](https://github.com/tobymao/18xx/assets/1711810/e13724df-ce79-41d5-a581-b3aca74162c5)

![Screenshot 2024-03-24 11 03 17 AM](https://github.com/tobymao/18xx/assets/1711810/28779689-b31d-4e4e-b020-ee8867a0ddd4)

**Comment by Schutenko** [comment]
I have been unable to place the Terminal in my games too

**Comment by Schutenko** [comment]
Dear Steve
Many thanks for this.  The Terminal is now placing and the Game is able to move into Operating 4.1 Round.
Keep up the good work, and warm regards
Marcus Schutenko  ***@***.*** +64 27 319 5328 

    On Sunday, April 21, 2024 at 08:31:23 AM GMT+12, Steve ***@***.***> wrote:  
 
 


Closed #10547 as completed via #10562.
