### ISSUE TITLE
Cloning a game should open it in a new tab

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10542]
Users often use `Clone Game` to plan out moves or do auto-routing, so having it by-default open in a new tab seems like a useful change.

I looked into adding the typical `target=_blank` attribute, but it looks like the button is generated in a way that is eventually handled by Snabberb, so idk how to set attributes in that context

`Clone Game` button is defined here, with `app_route`  used to redirect the browser to the new hotseat game. My understanding (at best) ends here
https://github.com/tobymao/18xx/blob/master/assets/app/view/game/game_data.rb#L75

`app_route` is defined here to be used as  `request.path` when rendering occurs (?)
https://github.com/tobymao/18xx/blob/02f8ebe84a373e5768337512c2de0a45f1fede76/api.rb#L203

Which seems to be defined by Snabberb as a collection of hashes that are used for generating JS via Opal (?)
https://github.com/tobymao/snabberb/blob/ba27b81bd9de87c69ef5da16ee9de879a6a7aa0f/lib/snabberb.rb#L10

**Comment by tobymao** [comment]
just pass in props, props: { target: "_blank" }
