### ISSUE TITLE
[1822 family] Bid disappears when stock is purchased

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#10543]
Game ID is https://18xx.games/game/154863

In SR 5.1, on my 1st stock turn, I put in a A30 bid on the Permanent 2-Train.  On my 2nd stock turn, I purchased a share of CAR.  This caused my bid on the Permanent 2 Train to disappear.

**Comment by JaySixA** [comment]
Note, on Stock Turn 3, the bid was back, so I'm not sure what is going on.

**Comment by michaeljb** [comment]
https://18xx.games/game/154863?action=409

https://gist.github.com/michaeljb/16562b4a5872612792d090dd1a3f8e56

**Comment by michaeljb** [comment]
Some other games are not loading and are showing errors with rendering bids, I'm going to rollback the commit that fixed this

https://18xx.games/game/166295
