### ISSUE TITLE
[1836jr] Cannot run a route from a single city to a Red

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#1054]
The requirement to run to at least 2 other cities only applies to Paris/Ports. You should still be able to run a 2 from Arnhem to Dortmund for example. Attempted this here: https://www.18xx.games/game/3699?action=582, however if you lay #59 with rotation 2 on E11 and token the track from Dortmund to Arnhem, the game skips the run routes step as if there were no valid route to run, despite NBDS owning a 5 and having a route.

Relevant rule section:
Paris and the Channel Ports (Dover and Harwich)
A train that includes one of these three locations at one end of its run increases the total of its run by F20 per station
token (not City) on the route in the green phase, and F30 per station token (not City) in the brown phase. As with
Off-Map Locations, only one Paris/Port Location may be scored (either at the beginning or the end of the run). Such
a run must include at least two other scoring locations (e.g., a run from Lille to Paris is not legal) and thus requires at
least a 3 train. A train may include both an Off-Map Location and a Paris/Port Location in its run, one at each end.

**Comment by jenf** [comment]
Exact point
https://www.18xx.games/game/3699?action=577
Unclear why it's not treating the route correct but is a bug

**Comment by jenf** [comment]
Ahh, problem is due to the token move not sending to the run trains step.

Will likely be fixed in the OR rewrite (5a066e6)

**Comment by yraelrocks** [comment]
https://18xx.games/game/3168

This game similar issue - NBDS lays OO tile towards off board & tokens. Should be able to run a route between, but the game skips the turn (not letting the token be put down until the HSM’s operation.

**Comment by jenf** [comment]
Same issue

**Comment by jenf** [comment]
Considered a dup of #896
