### ISSUE TITLE
{"error":"TypeError: Cannot read property '$$is_a_module' of undefined"} since 77f14a

### ISSUE THREAD

**Issue by jaysachs** [tobymao/18xx#1055]
I rolled back and deleted all active games, still same thing. Are some other DB changes to make?

**Comment by jaysachs** [comment]
This is on the landing page (or any page).

I believe for a commit or two starting at 77f14a it was actually 

`{"error":"TypeError: Cannot read property '$$is_a_module' of undefined"} `

**Comment by tobymao** [comment]
delete public/deps.js
