### ISSUE TITLE
[21Moon] Token placement s.b. optional when using Terminal ability

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10552]
Currently after laying the Terminal tile we auto-skip and always place a token, when it should be player's choice (same logic as C&OC)

```
[Corp] may then place its cheapest remaining supply depot token on the tile. 

This is done during the corporation’s tile place￾ment step and is in addition to its normal tile and supply depot token placements. 

Placing the Passenger Terminal tile closes this 
corporation. 
```

https://18xx.games/game/157057?action=79

https://gist.github.com/benjaminxscott/5067ac8da83f5c8b20b119bd9d4d6f71

![image](https://github.com/tobymao/18xx/assets/1711810/85424700-0ec5-4999-9aa4-6c53369afa98)

![image](https://github.com/tobymao/18xx/assets/1711810/3e5ca773-9e50-4c9c-aff9-e79acb3be401)

**Comment by roseundy** [comment]
Good catch. This also solves the problem I thought of yesterday when the placing corp doesn't have any tokens left.
