### ISSUE TITLE
1858: starting a new company, offered to use an existing company

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#10563]
https://18xx.games/game/156971

In SR3, I'm trying to start W... I click on it, and I'm offered to use C&S (correct) but also there's a button for using RP (weird).

**Comment by ianwilson156** [comment]
I cloned the game and tried to start it with the RP, but just got an error message. So it's more of a spurious button than a true bug?

**Comment by ollybh** [comment]
This is probably related to #10537, which is giving spurious exchange buttons in 1871.
