### ISSUE TITLE
[18Neb] Cannot upgrade Chadron to Brown on starting NebKota

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#10570]
GameID: 158026

Move: Current (previous was action 352: https://18xx.games/game/158026?action=352)

I am trying to par the NebKota, however the game is stuck on upgrading Chadron. Per rule 4.4.1 on page 6 of the rules: "The home hex of each Local Railway Corporation is upgraded immediately to its brown version, if this has not already been done, to facilitate placement of the base token." The home station of NebKota, Chadron in C3, is currently yellow. The game wants to upgrade to green first, however there is not a legal green tile for this upgrade so I cannot proceed.

**Comment by crericha** [comment]
It works from white to brown. Weird that yellow to brown doesn't. I'll fix.
