### ISSUE TITLE
[21Moon] Error on Space Port upgrade

### ISSUE THREAD

**Issue by tphon** [tobymao/18xx#10579]
In Game 158089 corporate round 3, I need to pass with VH but the error
no implicit conversion of NilClass into Integer
Pops up in the banner and I cannot progress this game.
https://18xx.games/game/158089

**Which Browser / Platform?**
Chrome Version 123.0.6312.86 (Official Build) (64-bit)

**Comment by roseundy** [comment]
Another consequence of renaming tiles

**Comment by tphon** [comment]
Thanks Steve, is there anything I can do or is this game stuck

**Comment by roseundy** [comment]
If you don't touch it, it should be able to work after the latest deploy.

**Comment by metawidget-net** [comment]
Still seems to be not working after latest deploy? Affecting a game started Apr 1, 17: something EDT.

**Comment by roseundy** [comment]
The fix hasn't been deployed yet.

**Comment by jason-johnson** [comment]
We have the same issue with: https://18xx.games/game/158822

This is during the company action in the stock round.
