### ISSUE TITLE
[18NL] I can't skip place a token

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#10584]
https://18xx.games/game/157162

NCS cannot skip place a token due to illegal action

**Comment by benjaminxscott** [comment]
May be a transient issue, try hard refreshing? I couldn't repro in hotseat so if that doesn't fix it then it would likely be a server-side vs client-side code issue

**Comment by philcampeau** [comment]
Using hotseat mode often doesn't catch these types of errors, you really need to use the import_games.rb script on your local machine.

I'll need to investigate. This is the error they're getting: 
![image](https://github.com/tobymao/18xx/assets/26125362/770673ae-d730-4fd0-b91d-bd66bb5311ce)

**Comment by philcampeau** [comment]
I found the fix, will submit shortly.
