### ISSUE TITLE
18NY apparent server-side failure

### ISSUE THREAD

**Issue by MadFedor** [tobymao/18xx#10588]
Multiplayer, async.

I completed an auction turn by purchasing a private, from my Android mobile login, Chrome browser. A few seconds later the game was removed from the "My Games" list on my login, and attempts to open the game from my last "My Turn" email notification show the error "Game not found".

http://18xx.games/game/158344

Notification email timestamp: Mar 30, 2024, 1:15 AM (UTC -4). I regret I don't remember the timestamp of my game action.

**Comment by benjaminxscott** [comment]
Someone in the game must have deleted their account, which deletes any games they are in from the server DB
