### ISSUE TITLE
[18Neb] Valentine should be counted as a passthrough offboard instead of a town dit

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#10586]
https://18xx.games/game/158005?action=193

https://gist.github.com/benjaminxscott/61dcf583e54b62d9fd1b8718eab7192d

The 3+3 train runs to four cities and two towns, which is not allowed.

<img width="1385" alt="Screenshot 2024-03-30 at 10 28 40 PM" src="https://github.com/tobymao/18xx/assets/8732435/80ca7abd-45cd-4832-ad85-54002500cb76">

**Comment by benjaminxscott** [comment]
Looks like it's hitting 3 "cities" (omaha, lincoln, offboard) and 3 towns (seems like Valentine is a town vs. a city)

**Comment by ChrisTheCat** [comment]
Valentine is a city in the printed game.

**Comment by crericha** [comment]
Here is the relevant rule text

> Regular trains, labeled n+m, may count a total
of n+m stops, at most n of which may be Cities
or Off-Map Areas. No stops may be skipped.

**Comment by philcampeau** [comment]
Seems like the easy solution here would be to make Valentine an untokenable city like Malpeque Shipyard (G11) in 1871:

https://github.com/tobymao/18xx/blob/d6872960a21c6b99b614d9210b055f1e51f1a569/lib/engine/game/g_1871/game.rb#L151-L158

**Comment by ChrisTheCat** [comment]
18EU and several other titles do the same.
