### ISSUE TITLE
[21Moon] No Implicit Conversion of NilClass at end of corporate round

### ISSUE THREAD

**Issue by Schutenko** [tobymao/18xx#10598]
I've played a few games without signing up and keep having a problem at the end of Corporate Round 3, so I signed up, hoping that would fix it but it still occurs.  I am unable to do my last action in Corporate Round 3.  It is as though their is a bug preventing Operating Round 3 to commence.  The message says 'No Implicit Conversion of NilClass into Integer'.

**Comment by philcampeau** [comment]
We can't access your hotseat games. They only exist on your local machine. 

As indicated in the form you used to submit this report, if your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**Comment by Schutenko** [comment]
Suspect I'm not doing something right.  Copying the game data gave the above, not a https

**Comment by philcampeau** [comment]
You're not doing it right. Read my comment again.

**Comment by benjaminxscott** [comment]
Looks like when Player 1 attempts to take any actions, the error pops

Repro'd on current master so doesn't seem related to https://github.com/tobymao/18xx/pull/10352, and doesn't seem related to Terminal (hasn't been placed)

**Comment by metawidget-net** [comment]
Have it here as well… second game of mine it's happened, first time a Moon update dropped mid-game, aborted game and started this one fresh, found bug again: https://18xx.games/game/158673

**Comment by roseundy** [comment]
Dup of #10579

**Comment by Schutenko** [comment]
Tried another Hotseat game, but with five players, and same issue occurred.  Followed philcampeau's instructions about copying game data, but same issue as above.  Game id is: Id: hs_knaacvcw_1712287883
Many thanks

**Comment by roseundy** [comment]
The fix hasn't been deployed yet.
