### ISSUE TITLE
[18Neb] Game hangs on bankruptcy

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#10601]
https://18xx.games/game/158004?action=367

https://gist.github.com/benjaminxscott/43a156aa0e3fc3f7053dafb578cc4f8c

cdlietz is bankrupt, but has no option to declare.

<img width="356" alt="Screenshot 2024-04-03 at 3 44 31 PM" src="https://github.com/tobymao/18xx/assets/8732435/03fe2fac-5d6e-4fe3-880b-1180de144693">

**Comment by crericha** [comment]
Awesome. Some one already hit bankruptcy. This was hard to test without a real scenario.
