### ISSUE TITLE
18Chessapeake LHV unable to place Tile 1 on J2/Allentown/Home tile.

### ISSUE THREAD

**Issue by dvdavins** [tobymao/18xx#10608]
[18Chesapeake] LHV unable to place Tile 1 on J2/Allentown/Home tile
-->

Game ID: 158555
Link: https://18xx.games/game/158555

This is on LHV's initial tile lay. I will make a disadvantageous move to keep the game going. See LHV's tile lay in OR 1.1.

**How to Reproduce the Bug?**

Click on Allentown and only Tile 6 appears as available to place.

**Which Browser / Platform?**

Chrome 123.0.6312.58

**Comment by philcampeau** [comment]
Tile X1 is reserved for Washington (hex F8). That's why it has the DC label on it, like hex F8 does.
