### ISSUE TITLE
1848 - pay shareholders at par value

### ISSUE THREAD

**Issue by JohnPPP** [tobymao/18xx#10604]
Whenever a company goes into Receivership, company should pay shareholders (exept president) share at par value. If not possible, president pays.

**Comment by benjaminxscott** [comment]
It looks like we currently pay non-pres shareholders par price for each share https://github.com/tobymao/18xx/blob/19003a33f6497533d545c3b3ce7d2d251507c190/lib/engine/game/g_1848/game.rb#L760

It seems to be working correctly on the currently deployed code

![image](https://github.com/tobymao/18xx/assets/1711810/977925dd-f05e-4ef4-92e2-04559b6091f0)


![image](https://github.com/tobymao/18xx/assets/1711810/0a4a1e17-abd3-4c22-88e3-a605d4514990)


Is there a specific case in which this isn't working as expected?

**Comment by crericha** [comment]
@JohnPPP can you please provide a link to the game where you think this is implemented incorrectly? Thanks!

**Comment by JohnPPP** [comment]
Hi,

I think its happening here, on game 157133

12:52] BOE's share price moves right from £150 to £160
[12:52] -- Event: Permanent 8 train exports --
[12:52] WA closes
[12:52] -- Operating Round 5.2 (of 3) --

Thank you,
Joao

**Comment by benjaminxscott** [comment]
Ah so looks like in that case the WA president was the only owner of shares when WA went into receivership, so there was no payout

Thanks for reporting it's super valuable to have people testing things out!
