### ISSUE TITLE
1822CA

### ISSUE THREAD

**Issue by ChuckHanna1** [tobymao/18xx#10606]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ChuckHanna1** [comment]
Hit return too soon....
1822CA 156003.
P11 (Tax Haven) is not supposed to count against the certificate limit, but appears to do so.
I'm sure this is platform-independent, but I'm using Firefox on a Windows 11 laptop.

**Comment by crericha** [comment]
The CPR director share is a 10% share. So in total, you have 7 CPR certs + 2 CNoR certs + 1 other private cert, which adds up to 10 certs, the same as the game is calculating.

**Comment by ChuckHanna1** [comment]
Thanks. I automatically calculated a director's share as 20%.
