### ISSUE TITLE
[1848] "next" permanent s.b. exported on 2nd and 5th receivership

### ISSUE THREAD

**Issue by JohnPPP** [tobymao/18xx#10603]
When the first company goes into Receivership, the next available permanent train s.b. exported. Same should happen at the 5th company

https://gist.github.com/benjaminxscott/54f693cd4dee1cf373e91f361f49b120

**Comment by benjaminxscott** [comment]
It looks like in `5.4.4` when the 2nd and 5th corp are thrown into receivership, a permanent is exported
https://gmtwebsiteassets.s3.us-west-2.amazonaws.com/1848/1848-RULES-FINAL.pdf

Currently we incorrectly skip the export step if the next train isn't a permanent
https://github.com/tobymao/18xx/blob/19003a33f6497533d545c3b3ce7d2d251507c190/lib/engine/game/g_1848/depot.rb#L13
