### ISSUE TITLE
1825(beta)  #153183

### ISSUE THREAD

**Issue by beardurham** [tobymao/18xx#10619]
Taff Vale has floated, tile is in place but no station marker.
Game has moved on to next player, but TV still illuminated and cannot be played.

**Comment by roseundy** [comment]
When I look at the game, it seems to have progressed. Did you do anything to move it?

**Comment by roseundy** [comment]
So it looks like the problem is that TV needed to place a token, but the wrong player was on turn.

**Comment by beardurham** [comment]
Yes, that is how I saw it.  Something changed?

I was shown as "on" but unable to actually do anything.

As I understand it this game was set up to push the system as many people
and all the available expansions.

Thank you for your time and efforts in this case, and also the whole 18XX
set up.

Best wishes
 beardurham 🐻

**Comment by roseundy** [comment]
I'm not sure about this. I think the bug is that the wrong player was highlighted. It can be played, sure, but I think the bug is there.
