### ISSUE TITLE
[1840] Hexagons for bonus tile lays

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#10610]
Shouldn't the icons for the bonus tile lays along the Stadtbahn tracks be hexagons rather than pentagons? Is there a reason they are pentagons?

**Comment by philcampeau** [comment]
Does it make any functional difference?

**Comment by orome** [comment]
@philcampeau Depends on what you mean by "functional", I suppose. Mostly I'm just wondering why they're pentagons instead of hexagons.

**Comment by Zwergenpunk** [comment]
Because i thought they are pentagons ;)
