### ISSUE TITLE
[spreadsheet view] Change way certicate counts are displayed

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#1061]
Currently in spreadsheet view the Certs row counts only the certificates that count towards certificate limits (i.e. it ignores certificates from yellow or orange companies). But I find that towards the end of the game, knowing a player's *total* certificate count allows me to more easily gauge their earning potential. 

Can I suggest instead that we display the certificate information as follows:
1. **Certs** (this would be a total count of all certificates)
2. **of which count towards limit**  (can't think of anything less wordy at the moment!)

EDIT: 
I've updated my suggestion after reading Dan's reply. 

If you had 7 shares in just one company, which happened to be a yellow company, it would say: 
1. **Shares**: 7
2. **Certs**: 0/18

Having the "/18" makes it a little clearer that "certs" only includes those certificates which count towards the certificate limit. It's also a reminder of the certificate limit for that particular game or player count.

**Comment by dfannius** [comment]
I think the word for #2 is "shares". For example, I imagine you want the president's certificate to count as 2 for purposes of this stat.

(That said, I don't have a problem just summing the column in my head, but I can appreciate other people's desire for this number.)

**Comment by zurfarosa** [comment]
> I think the word for #2 is "shares". For example, I imagine you want the president's certificate to count as 2 for purposes of this stat.
> 
> (That said, I don't have a problem just summing the column in my head, but I can appreciate other people's desire for this number.)

Yes, that makes sense. So if you had 7 shares in just one company, which happened to be a yellow company, it would say: 
1. **Shares**: 7
2. **Certs**: 0/18

Having the "/18" makes it obvious that "certs" only includes those certificates which count towards the certificate limit. It's also a reminder of the certificate limit for that particular game or player count.
