### ISSUE TITLE
[1880] FI Player incorectly given token option

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#10611]
GameID: 158391

Action: https://18xx.games/game/158391?action=390

Issue:
Page 8 of the linked rules, in the "Merger of Foreign Investors with Companies" section states: "The Share company may replace the Investor‘s station marker with the least expensive marker from its own charter at no cost." This implies that in the situation where the president of the company and the player controlling the associated Foreign Investor are different, it is the president of the company who should have the option of replacing the token (this is consistent to how I have always played this situation F2F). However, in the above linked action the FI-controller is given the option, not the company president.

**Comment by philcampeau** [comment]
A part of me is inclined to check with the designers on BGG, but this seems pretty clear based on the rules.
