### ISSUE TITLE
[18Neb] P2 Morison Bridging Company not working properly when upgrading Omaha (K7)

### ISSUE THREAD

**Issue by scninmer08** [tobymao/18xx#10612]
https://18xx.games/game/159045

The game is in OR3.1 and phase 3.  UP owns Morison Bridging Company, but is unable to upgrade Omaha using the private's bridge token.  It is able to be upgraded without use of the private.  When the private is selected, it highlights both Lincoln (J8) and Omaha (K7), but clicking on either does nothing but create a black border around the respective hex (and I don't think Lincoln should be eligible for an upgrade since it's not a river anyway?).

**Comment by TheTagoreler** [comment]
Similar issue in this game: [https://18xx.games/game/159147]
