### ISSUE TITLE
[18NEB] Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shamblen** [tobymao/18xx#10623]
https://18xx.games/game/159061

https://gist.github.com/benjaminxscott/6d996972ee7347decd6c5ddf1e58c958

At the NK's first token step (in Phase 4D), the game refuses to accept input -- cannot play a token, cannot skip token, cannot post in chat.  Was able to Undo, then post in chat, but moving forward to token step re-causes the problem.

**Comment by OedipussyRex** [comment]
Same issue: https://18xx.games/game/159626
