### ISSUE TITLE
[1870] - Open Port token bonus not added to connection run

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#10620]
https://18xx.games/game/159106?action=403

Frisco made the connection to it's destination and made the connection it's connection run. The Open Port token (owned by Frisco) in Memphis was not added to the value of the run. The token was properly added to the normal operation.

**Comment by philcampeau** [comment]
In action 403, the connection run hasn't happened yet. 
I cloned the game and skipped trains to get to the connection run.
When I run E12-H17-M20-M22, it gives a value of $140, assuming I put the destination token on the map. By my math, that's correct. 

E12 - 30
H17 - 30 + 20 port token bonus
M20 - 20
M22 - 20 x 2 for destination bonus
Total = 140

Am I miscalculating something?

**Comment by OedipussyRex** [comment]
No. Nothing wrong with your calculations, but mine. I was using the wrong value for M22. And I triple-checked before posting. "I blame society. Society made me what I am." -Duke
