### ISSUE TITLE
[18Neb] - Illegal Tile Lay on C3

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#10629]
https://18xx.games/game/159031?action=302

I at one point upgraded hex C3 with the UP and only now realized that it's not a legal tile placement.

Reason I realize it now is because the Nebkota can't start now.

**Comment by crericha** [comment]
Thanks for letting us know. The bug was already fixed, but the way the game engine works, it doesn't detect if previously laid tiles are illegal. I went in and archived all those games too.
