### ISSUE TITLE
[18ESP] Capitalization bug

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10633]
Hello,

18ESP game has the capitalization linked to the achievement of three goals, BEFORE phase 5. When phase 5 enters, all major companies are launched with the 60% sold (not the 40% on phases 2-4) and they have the full capitalization (PAR x10). It is the rule. However, on game https://18xx.games/game/155533 the FdSB major company, that was launched AFTER phase 5, received the full capitalization, and ALSO the goals. So, it will receive more money on its treasury that it should. Every time FdSB reaches a goal (and it shouldn't have goals) it will receive PAR x1, PAR x2 or PAR x3. It is wrong, because the company was launched after phase 5 and it hasn't goals for this reason.

Thank you so much.

All the best,

Enrique Trigueros (queroscia): designer of 18ESP.

**Comment by kepakiano** [comment]
Additional context: The FdSB director was bought before phase 5, which is when the goals were added to its charter. Same happened in this game: https://18xx.games/game/159424
So, only adding the goals when the company floats could solve the issue.

**Comment by queroscia** [comment]
Also on game https://18xx.games/game/154646, already reported.

**Comment by kepakiano** [comment]
This issue seems to be fixed in master. When I download the data of 155533 and load it in hotseat mode in a local environment, FdSB does not have goals anymore:
![image](https://github.com/tobymao/18xx/assets/1355029/5185bb2c-5396-4480-9d12-11f58c8f23db)

**Comment by benjaminxscott** [comment]
fixed by #10587
