### ISSUE TITLE
[18NEB] - Game breaks when undoing actions in hotseat

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#10634]
https://gist.github.com/OedipussyRex/2f48f917b7cd329a8f8d6a57cdab0432

Happens in green or later regardless the type of action being undone. Have never had the game break while still in yellow.

**Comment by crericha** [comment]
The game is broken because it had an illegal move that has been fixed. That's why it isn't working. It maybe appeared to work for you because it was cached in your browser, but if you would have done a hard reload in your browser, it would have shown as broken.
