### ISSUE TITLE
Indicate mail contract bonus when running train and in log

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1063]
The mail contract should be indicated when setting the route and then later when payout or withhold in the log.

This run looks like it is calculated incorrectly, as a 3/5 should be 40 + 60 + 70 = 170. However, the mail contract bonus is 40.

Here, it should show as part of the on-screen text while selecting cities.

<img width="1458" alt="Screenshot 2020-07-10 06 10 05" src="https://user-images.githubusercontent.com/8732435/87158158-23bff900-c274-11ea-8aab-6a64d710e70f.png">

Here, it should appear in the log.

NYC spends $20 and lays tile #23 with rotation 4 on E15
NYC spends $20 and lays tile #8 with rotation 2 on E13
NYC passes
NYC runs a 3/5 train for $210 (D14, E17, G19, G21)
NYC pays out $210 = $21 x 10 shares
ChrisShaffer receives $105 = $21 x 5 shares
Halekio receives $21 = $21 x 1 shares
Akado receives $21 = $21 x 1 shares
NYC's share price changes from $80 to $100

**Comment by gchambers419** [comment]
Subset of the issues in #976, but with better examples of desired change.

**Comment by jenf** [comment]
#976 also asks for highlighting of which cities the payout is calculated from.
