### ISSUE TITLE
18ESP update P1 and P2 face values

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10639]
Hello,

According to the last version of the rules (available on bgg), the face value of privates #1 and #2 change. Face value of P#1 becomes 20, and face value of P#2 becomes 60. No changes on income.

Please, update it on 18xx.games when possible.

Thanks,

Enrique Trigueros (queroscia): 18ESP designer.

**Comment by benjaminxscott** [comment]
Ref:

https://boardgamegeek.com/file/download_redirect/fba63123700843b56a5492cda4bd3d7e3bf8d9973cfc5c87/18ESP_DRAFT+RULES_Enrique+revised_Ian+proofread_15-04-2024_BETA+2.5.pdf
