### ISSUE TITLE
18ESP PAR value

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10645]
Hello,

18ESP is a game that have the capitalization and the stations according to achieve some goals. While the companies have shares on the IPO we can see the PAR value (as IPO value). But, when the last IPO share is sold, the IPO row disappear from the charter.

It is similar coded as other games. What is then the problem? Each company has 3 goals. When they achieve the first goal, they receive the PAR (or IPO) value x1; With the second goal, PAR value x2; With the third, PAR value x3.
What happens if a company has not more IPO shares and the row disappear, and still has some goals to achieve? Easy, nobody know how many money will enter into the treasury when a goal is achieved, because the PAR value (= IPO) has been removed.

For making the code as easier as possible, I suggest: on the bottom of the charter the goals are listed, for knowing what goals are achieved and what left. I would add simply a little note: PAR = x (the PAR value that the director chosen when bought the director certificate). In this way, all player can in any moment check the potential money a company could reach in an OR. It is very important for deciding selling shares or not during a SR.

Thank you so much,

Enrique Trigueros (queroscia): designer of 18ESP.

**Comment by benjaminxscott** [comment]
Similar usecase here for showing par values: https://github.com/tobymao/18xx/issues/10406#issuecomment-

Currently we auto-remove par/IPO values once those shares are removed, to clean up the UI a bit

I'd propose to generically show pars on the corp sheet, perhaps optionally depending on it being useful in that particular game title

**Comment by queroscia** [comment]
I don’t know anything about programming, but I have thought that maybe it is easier and code cleaner if the par values are marked on the market tab. For this game it would be enough.

Thanks.

Enrique Trigueros.

**Comment by benjaminxscott** [comment]
I should clarify - the par values are currently listed on `Spreadsheet` tab but we could list them on `Entities` as well, which is what the above linked issue was about

**Comment by queroscia** [comment]
You are right. I didn't realized it was on the spreadsheet. For me it is enough and that issue can be closed. It is not necessary to include the PAR value in any other place. I asked for this issue to the programmer who has coded 18ESP, and he didn't tell me that PAR value was there. Surely because of a misunderstanding. But, as said, that issue can be closed.
