### ISSUE TITLE
[18USA] One 2T is missing from corporation SP

### ISSUE THREAD

**Issue by jave09** [tobymao/18xx#10659]
https://18xx.games/game/155693

SP bought two 2Ts in OR1.1: https://18xx.games/game/155693?action=204

Current turn in OR1.2 - one of the 2T is missing.

On mobile

On desktop Chrome 123.0.6312.124 (Official Build) (64-bit) (cohort: Control)

**Comment by philcampeau** [comment]
Whether deliberately or accidentally, SLSF bought one of them on [https://18xx.games/game/155693?action=229]action 229(url)
