### ISSUE TITLE
[18Chesapeake] Feature Request:  In Create New Game, the ability to set private Cornelius Vanderbilt to a specific Company

### ISSUE THREAD

**Issue by academicone** [tobymao/18xx#1065]
Feature Request:  In Create New Game, the ability to set private Cornelius Vanderbilt to a specific Company; the default would be "Random".  

Situation 1:  I don't want to repeat a random CV company I recently had.
Situation 2:  as a newbie learning/teaching the game, I'd like to use the online in parallel with the physical game to show what options the rules allow at a specific point in the game.  E.g., ability to buy trains from other companies may be forgotten when using only the physical game (as a newbie).  [current workaround is to start the online game first and use it's random CV]

Thank you.

**Comment by tobymao** [comment]
no plans to do this
