### ISSUE TITLE
(21moon) stuck in Sr 

### ISSUE THREAD

**Issue by rainmight** [tobymao/18xx#10657]
https://18xx.games/game/158232

**How to Reproduce the Bug?**

Trying to pass the SWP Corp round 3.

Can't because :

![image](https://github.com/tobymao/18xx/assets/73754571/f7234d35-c370-481a-af8d-b3d25be5f8bd)

Please include screenshots (you can drag and drop or upload them into this issue)

-->

**Which Browser / Platform?**

Safari 17.4.1

<
-->

**Comment by roseundy** [comment]
This is a dup of #10579 
I need to fix this today.
