### ISSUE TITLE
[1822PNW] Not all companies offered for merger

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#10662]
https://18xx.games/game/159496?action=528

18xx.games only offers the opportunity to merge on the turn of the associated minor company. The rules are clear that the merger can be initiated on the turn of the association or unassociated minor company.

_6.1.2 The merger round takes place in descending share price order, which means that the first eligible minor company with the highest stock value has the first opportunity to merge. If an eligible minor passes, it may still be merged with another minor further down in operating order when the lower valued minor company is given the option to merge._

_6.2.1 To be eligible to merge, the minor companies must meet all requirements listed below:
• Must be Phase 2 or later.
• Both minor companies must be owned by the same player.
• One minor company must be an associated Minor (M1, M5, M7, M8, M17, M18, M20).
• The other minor company must be an unassociated Minor (all other minor companies not named above).
• A regional railway may not be substituted for an unassociated minor company.
• The first minor company must be able to trace a route of any length from its home station token to the home station token of the other minor company_

In the game below, the operating order is: M6, M1, M9, M14, M21, M10, M8, M2, M17, M16, M18. The order of operations should be:

- Unassociated M6 should be skipped because it is not connected to an eligible associated minor
- Associated M1 should be skipped because it is not connected to an eligible unassociated minor
- Unassociated M9 is skipped because it is not connected to an eligible associated minor
- Unassociated M14 should be offered a merger with associated M8
- Unassociated M21 should be offered a merger with associated M17
- Unassociated M10 should be offered a merger with associated M16
- Associated M8 should be offered a merger with unassociated M14
- Unassociated M2 is skipped because it is not connected to an eligible associated minor
- Associated M17 should be offered a merger with unassociated M21
- Associated M16 should be offered a merger with unassociated M10
- Associated M18 should be skipped because it is not connected to an eligible unassociated minor

<img width="775" alt="Screenshot 2024-04-22 at 18 00 07" src="https://github.com/tobymao/18xx/assets/8732435/d0fefc83-ab41-4a71-9050-30ce5207bd12">

**Comment by outsidePasser** [comment]
This is technically correct - however, I don't think this is a very high priority issue.  All combinations can still be achieved, and if it was fixed, players would be asked multiple times in the same round if they want to combine the same two minors.

**Comment by outsidePasser** [comment]
Although it could change the timing of when the formed companies run.  So it's worth fixing.

**Comment by ChrisTheCat** [comment]
There are also times where I have a high and low priced combo, and I want
to see who else merges before I commit.

**Comment by michaeljb** [comment]
Deploying the update for this now. The majority of 1822PNW games will need to be migrated for this, and until then they will appear broken.
