### ISSUE TITLE
@everyone game chat notification feature

### ISSUE THREAD

**Issue by MatthewDeKoning** [tobymao/18xx#10674]
**What's your idea?**
Add @everyone or @game in a game chat to notifies all players. Would make asking to undo or for a rematch quicker. 

Thanks implemented or not, this site is amazing!

**Comment by benjaminxscott** [comment]
dupe of https://github.com/tobymao/18xx/issues/4917

I wouldn't close this issue just yet since idk the reason why the original ticket was closed

**Comment by scottredracecar** [comment]
Toby batch closes issues that go a long time without someone stepping up to
work on them.

**Comment by tobymao** [comment]
because no one works on issues, i don't want hundreds of issues around that no one is ever going to implement. if someone wants to pick it up we can discuss it.
