### ISSUE TITLE
[1846] Feature suggestion - display Market on the Game tab for 46 during ORs

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#1067]
The linear market contains a lot of information on operating order, whether you'll single/double/triple jump, etc during the ORs and since it takes up so little space I'd recommend displaying at the bottom (or top?) of the game tab during the ORs.

**Comment by benjaminxscott** [comment]
It looks like some of these may be covered by recent commits, if those are the usecases being described?

Operating order now shown on corp charters: https://github.com/tobymao/18xx/pull/1165
Payout UI now shows outcomes: https://github.com/tobymao/18xx/pull/1168
