### ISSUE TITLE
[1822CA] P11 RRSP Tax Haven Doesn't Count but programming not allowing bid by player at certificate limit.

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10678]
1822CA

[1822CA] RRSP P11 Tax Haven rules state:

"The RRSP cannot be acquired and does not count against the certificate limit." (p37, last line of P11 Special Property/Notes)   Despite this, the game programming is not allowing bids by players at the certificate limit.

Please note that the above 1822CA rule is very different from 1822, which states:  "Does not count against the certificate limit when owned by a player, but does count while in a bidding box. In other words, a player at certificate limit may NOT bid on P16."

So in 1822CA, the limiting language from 1822 "when owned by a player" is not present.  Nor is phrase "while in a bidding box", nor is the sentence regarding a player at certificate limit.

Please tweak the programming so we can go forward.  Thanks!

From the game dialogue:  
[19:42] ramanraj passes
[19:43] ramanraj: Bug? Game sees me as full and wont allow bid on tax haven. But th does not count against cert limit
[19:58] DrAwesome bids $35 for P11 (Tax Haven)
[19:59] DrAwesome: seems like a bug yes

**Comment by michaeljb** [comment]
The commit that fixed this is going to be reverted, the bidding cube is supposed to count against the limit:

From page 12:

> 4.10.8 A player may not place or move a bid on an item if they are at the certificate limit. Each item on which a player currently has the highest bid counts as a certificate against the certificate limit. (!is applies to P11 Registered Retirement Savings Plan as well.)
