### ISSUE TITLE
18Neb breaks on bankruptcy

### ISSUE THREAD

**Issue by tomhoward87** [tobymao/18xx#10686]
18Neb throws an error when the player tries to declare bankruptcy, our game is stuck: https://18xx.games/game/161183
![Screenshot_20240429-093632](https://github.com/tobymao/18xx/assets/1814143/29c4dd94-67fa-4116-b7b2-425c49ecce8f)

**Comment by benjaminxscott** [comment]
dupe https://github.com/tobymao/18xx/issues/10683
