### ISSUE TITLE
[18Hiawatha] Corps in Liquidation can decline to be sold

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#10689]
Game hasn't reached the bug yet, but it's on its way there: 
https://18xx.games/game/160858

Gist link to HotSeat copy, which is 160858 but played through until the moment of bug: 
https://gist.github.com/yoyoson/715cf347f8559d9e1a05ccc9fe98befd

If a corp is in liquidation, then when it comes up in the Acquisition Round, the options are "Offer for Sale" or "Pass (Offer for Sale)", and Passing works and turn order proceeds to the next company. 

I don't see any rule difference for 18Hiawatha w.r.t. liquidation, but I could be just tired and missed it multiple times.

Note also that in other 1817-family titles, the market's Liquidation space is colored Red and separated from the rest of the market, whereas here it's normal colored and connected.

**Comment by philcampeau** [comment]
Hey thanks for this report. It was a silly oversight, literally needed to add one character to the code to fix.

Unfortunately, there's a good chance this will break some games.

**Comment by yoyoson** [comment]
> Hey thanks for this report. It was a silly oversight, literally needed to add one character to the code to fix.
> 
> Unfortunately, there's a good chance this will break some games.

As to be expected, playing in Alpha. Thank you for implementing this!
