### ISSUE TITLE
[21Moon] Issuing IPO of a floated company before first operation decreases share price

### ISSUE THREAD

**Issue by Adrianows** [tobymao/18xx#10696]
## Game ID
https://18xx.games/game/161747?action=41
game : 161747
action 41

In this game the action was undone (HMQ did not issue in the end because of this bug), but you can replicate the bug by cloning the game and issuing HMQ IPO shares. The company has floated but not yet operated, so the share price shouldn't decrease.

## How to reproduce bug
Float a company fully prior to the corporate round, then issue IPO shares as a corporate action. The share price decreases for corporations that have floated prior to the CR, whereas it should only decrease if the corporation has already run.

**Comment by philcampeau** [comment]
The game rules, section **10.1.2 Issuing Stock**, say

> If the corporation was not floated at the time shares were issued, the share price does not change. If the corporation had already been floated, its stock market token moves down one space no matter how many shares were issued. 

This seems to be what happens in your game. If so, that's not a bug.

**Comment by Adrianows** [comment]
I take it back then, I had missed that paragraph continuation of 10.1.2 and interpreted sections 10.1.1 and 9.1, the latter of which describes

> However, if the corporation has not yet had
an operating turn its price does not drop.
