### ISSUE TITLE
[18RoyalGorge] error when trying to use Y3 Coal Creek private

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10698]
![D23A9644-138D-40C9-8776-9CB3E6CCCF79](https://github.com/tobymao/18xx/assets/73144084/cae402ed-fc7c-424d-b1a1-5cb0ed2598b5)

https://18xx.games/game/161776?action=224

Same game but this seems to be a separate issue from #10695 where buying in the coal creek private seems to automatically come with 12 cubes instead of getting one when coal creek is run to, which may be locking up the game in a different way.

**Comment by benjaminxscott** [comment]
fix is deployed if you'd like to try continuing
