### ISSUE TITLE
email notification not delivered for pinned game

### ISSUE THREAD

**Issue by Baconologist** [tobymao/18xx#10700]
I noticed that my async games of 18ESP have really slowed down, then I realized that I haven't gotten an e-mail indicating that it is my turn in maybe 4-5 days. (I only notice it is my turn when I return to the main 18xx.games home page and see that a box is orange.)

I know the game's in alpha, so I just assume this is part of the development maturation process. If not, just calling it out as an interface issue!

**Comment by benjaminxscott** [comment]
I tested that mail is working on my test accounts (and tailing `docker logs` on the prod server) and it seems to be working in general. 

Thanks for letting us know, I think what happened here is the game was "pinned" , which means its state has diverged from the canonical latest game code and it will no longer get email notifications

(basically it's deprecated and likely to be deleted on the next deploy)

https://github.com/tobymao/18xx/wiki/Notifications#email-notifications

Probably not related to this ticket, but also note 
- if the site is currently open in a browser where the user is logged, email is suppressed
- email addys hosted by MSFT don't accept our emails (they consider elasticEmail spammy, I guess) 
- emails are rate-limited to 1/min max

https://github.com/tobymao/18xx/blob/master/queue.rb#L113
