### ISSUE TITLE
18SJ:  fullcap corp not able to be selected by bot

### ISSUE THREAD

**Issue by cscottk** [tobymao/18xx#10709]
We are told to pick a corporation for the bot, and we have a single one left, and no matter who is in Master Mode, the game gives us an error:  All Shares must be from the same corporation.  This is the only single company left.

**What's your Game ID?**
[160962](https://18xx.games/game/160962)

https://gist.github.com/benjaminxscott/c04f0a58f3a641295e3fad5220f450ca

**How to Reproduce the Bug?**
The game is currently stuck in this state.

**What steps cause the unexpected behavior?**

2-player game with all corporations but one started.

**Which Browser / Platform?**
Chrome
124.0.6367.118

**Comment by benjaminxscott** [comment]
When the fix is rolled out the game s.b. continuable

**Comment by cscottk** [comment]
When is a roll-out expected, so I can verify fix?

**Comment by benjaminxscott** [comment]
deployed try it now

**Comment by cscottk** [comment]
Verified.
