### ISSUE TITLE
1841 EMR sweeping issue from owner shell (156013)

### ISSUE THREAD

**Issue by Kingsoby1** [tobymao/18xx#10715]
[156013](https://18xx.games/game/156013)

https://gist.github.com/benjaminxscott/459bddfed8efe1ecee0dede3f09ad9e7

I back pedalled because I wanted to continue the game. But basically what happened: 

ICsf is owned by ATFA 

IcSF moved all of its money to ATFa with token buy 

ICSF EMR to buy a train 

Implementation swept like $1000 from ATFa that it didn't have and didn't sell down atfas shares in icsf

**Comment by roseundy** [comment]
Something isn't right. If ICSF is owned by ATFA, it should have been illegal for ICSF to own shares in ATFA. I'll take a look in a bit.

**Comment by roseundy** [comment]
Not seeing a problem here.

1. ICSF buys a token from ATFA and transfers L.979 to ATFA
2. ICSF now has no train and no cash (8 train will cost L.1450)
3. It EMR issues it's stock and raises L.460. ICSF has no other stock to sell. ICSF is still L.990 short of the cash needed for the 8.
4. Now ICSF's Controlling Corporation is now on the hook. ICSF is controlled by ATFA.
5. ATFA has L.1142 in cash.
6. The remaining L.990 needed for the 8 train is paid out of ATFA's treasury ("swept"). No shares need to be sold.
7. ICSF buy the 8 train.

This is all following the rules in section 4.5.1.

What exactly were you expecting to happen?

**Comment by Kingsoby1** [comment]
Thanks, you're right. Must have just been tired.
