### ISSUE TITLE
18 Royal Gorge bug

### ISSUE THREAD

**Issue by ArcticOctopus** [tobymao/18xx#10716]
18 Royal Gorge breaks at the Treaty of Boston. It's happened in two games so far.  Got a 
"Server did not accept action due to unknown keyword ::closed_when_used_up"
-->

**What's your Game ID?**
161832
And
161819

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment]
dupe #10695

**Comment by benjaminxscott** [comment]
fix is deployed if you'd like to try continuing
