### ISSUE TITLE
[1848] 3T bought before last 2T is sold. 

### ISSUE THREAD

**Issue by coen4git** [tobymao/18xx#10714]
[1848] 3T bought before last 2T is sold. 

This happend in this game
https://18xx.games/game/160643

during this step.
https://18xx.games/game/160643?action=132

SAR bought a 3T while there was a 2T available. 

Game Id: 160643

**Comment by benjaminxscott** [comment]
dupe #9598, there's more context in that ticket but it's likely generic rare server request validity issue

**Comment by benjaminxscott** [comment]
fwiw I would undo to there since it's clearly not a valid action, very likely just some weird unavoidable issue vs. some deliberate thing
