### ISSUE TITLE
[1846] Differentiate the home station of the Erie and the reserved station in the City of Erie

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#1071]
Right now the two circles look identical on the map and it's not unreasonable for an unfamiliar player to assume that Erie starts in Erie.

**Comment by JEBrosius** [comment]
One approach would be to display the corporation name in the reserved space in gray, as compared with black for the home station.

**Comment by michaeljb** [comment]
@eheiden @JEBrosius what do you think of the screenshots I added on #1077?

**Comment by JEBrosius** [comment]
I left a note in #1077.  This is a clear improvement.  There are issues still to think about, but I don't know what recommendation to make (see my note.)
