### ISSUE TITLE
System18 Twisting Tracks Playtesting Changes

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#10725]
After TraXX playtesting:
Replacement 5-train and 6-trains both cost change to $450
D-trains all cost $600

Revise train counts:
2-train: 4
3-train: 3
4-train: 2

Revise starting cash to:
2p: 700
3p: 500
4p: 350
(Steve, I don't think I took a good note about this, please post if you took a note)

Steve, let me know if you recall any other changes. That is all I wrote down.

**Comment by roseundy** [comment]
I had this for the new starting cash:

2p: 1000
3p: 700
4P: 500

**Comment by scottredracecar** [comment]
Ok, go with yours.
