### ISSUE TITLE
[18RoyalGorge] Train buy doesn't work, game can't proceed

### ISSUE THREAD

**Issue by gloinul** [tobymao/18xx#10721]
When attempting to buy a 3+ train for SF which will trigger Treaty of Boston we get the error message:

The server did not accept this action due to: Illegal action: unknown keyword: :closed_when_used_up... refreshing.

**What's your Game ID?**

https://18xx.games/game/161782

**How to Reproduce the Bug?**

Don't really know:

![Skärmbild 2024-05-06 083232](https://github.com/tobymao/18xx/assets/11295323/8f184a5b-7641-466a-a430-11bff80559b3)

**Which Browser / Platform?**

Issue exist on both:
Firefox 124.0.2 
Edge  124.0.2478.80

**Comment by benjaminxscott** [comment]
dupe #10695

**Comment by benjaminxscott** [comment]
fix is deployed if you'd like to try continuing
