### ISSUE TITLE
[18RoyalGorge] Known Issues link does not pick up the issues due to misspelled github label

### ISSUE THREAD

**Issue by gloinul** [tobymao/18xx#10723]
So when in a game of 18 Royal Gorge the known issues link in it is: 
https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A18RoyalGorge

However, someone made a spelling misstake when creating the 18RoyalGorge label and spelled it "18RoyalGeorge" which results that no known issues are found when following the above link. I would recommend fixing the label and you might get fewer duplicates.

**Comment by benjaminxscott** [comment]
fixed
