### ISSUE TITLE
[18RoyalGorge] new error preventing proceeding

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10728]
![IMG_7596](https://github.com/tobymao/18xx/assets/73144084/7e6c0224-723d-4bd0-aef3-a2539f8c9b7d)

https://18xx.games/game/161776

no idea what this one means 🤷‍♂️

**Comment by michaeljb** [comment]
This is fixed by #10724, but that is not deployed yet. I’ll close this when it is deployed
