### ISSUE TITLE
18 Hiawatha: Phase 2 - Merger Round 1.1 (of 2) - Convert or Merge Corporation

### ISSUE THREAD

**Issue by DrLogistik** [tobymao/18xx#10730]
18 Hiawatha: Phase 2 - Merger Round 1.1 (of 2) - Convert or Merge Corporation

**What's your Game ID?**

https://18xx.games/game/160860?action=325

**How to Reproduce the Bug?**

 I believe it is because it is in alpha

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment]
Looks like it's due to a bugfix correctly causing the J corp to go into liquidation at this step, instead of pre-bug where it got to operate

https://github.com/tobymao/18xx/pull/10688

Since it's alpha this game can't be continued and will be auto-cleaned up eventually
