### ISSUE TITLE
[18Hiawatha] inherited 1817 logic for or_round_finished bails when upcoming train is nil

### ISSUE THREAD

**Issue by CzlDzl** [tobymao/18xx#10746]
18Hiawatha "Pass" Button Not Working 

[GameID 162717](https://18xx.games/game/162717)
"Pass" button isn't working.

Loans and other features already to still be working but the player can't end their turn. 

All platforms.

**Comment by benjaminxscott** [comment]
This occurs due to the inherited 1817 code handling train exports bails if there's no upcoming trains (which doesn't happen in '17 since it has infinite diesels)

https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1817/game.rb#L981

**Comment by CzlDzl** [comment]
Thank you! This game is awesome!

**Comment by philcampeau** [comment]
Thanks for the fix @benjaminxscott!
