### ISSUE TITLE
[18Hiawatha] Error in merge step

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#10744]
https://18xx.games/game/160922

game is broken, please kill this one

**Comment by ollybh** [comment]
> We're sorry this game cannot be continued due to GameError: Choose a corporation to merge with DL&W
> Broken action: { "type": "merge", "entity": "DL&W", "entity_type": "corporation", "id": 332, "created_at": 1714589101, "corporation": "GT" }
> Please raise a bug report and include this link (https://18xx.games/game/160922?action=331)

**Comment by ollybh** [comment]
The action is attempting to merge DL&W with GT, but GT is in the yellow section of the stock market.

**Comment by philcampeau** [comment]
Hmm I can see what happened in the game, but I can't figure out how it happened. When I try to roll back to that step, it doesn't give me GT as a merge candidate.

**Comment by benjaminxscott** [comment]
closing since game is pinned / likely difficult to repro

can reopen if desired
