### ISSUE TITLE
[18RoyalGorge] game will not load Id: 163064

### ISSUE THREAD

**Issue by DStickum** [tobymao/18xx#10745]
https://18xx.games/game/163064 will not load.  Appears to be either broken or frozen.   Please delete.  

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"
-->

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment]
The runtime error is:

> Uncaught RuntimeError: All shares must be from the same corporation

This comes from the ShareBundle code. Issue #10733 has the same error occurring in a 18RoyalGorge game, could these be related?

**Comment by philcampeau** [comment]
Looking at the console error, it's mentioning RoyalGorge: 
![image](https://github.com/tobymao/18xx/assets/26125362/da349fc6-c94d-476f-9381-2c765a782463)

Are we sure this wasn't a game of 18RoyalGorge? There's no reason why 18Hiawatha should be calling anything from 18RG.

**Comment by DStickum** [comment]
My apologies.  It is a game of RoyalGorge



Sent from my T-Mobile 4G LTE Device



-------- Original message --------
From: philcampeau ***@***.***>
Date: 5/12/24 10:30 PM (GMT-05:00)
To: tobymao/18xx ***@***.***>
Cc: DStickum ***@***.***>, Author ***@***.***>
Subject: Re: [tobymao/18xx] 18Hiawatha game will not load Id: 163064 (Issue #10745)


Looking at the console error, it's mentioning RoyalGorge:
image.png (view on web)<https://github.com/tobymao/18xx/assets/26125362/da349fc6-c94d-476f-9381-2c765a782463>

Are we sure this wasn't a game of 18RoyalGorge? There's no reason why 18Hiawatha should be calling anything from 18RG.
