### ISSUE TITLE
[1889 Shikoku] - I was able to buy more than 19 maximal certificates in a 3 player game

### ISSUE THREAD

**Issue by WoAiJiqiXuexi** [tobymao/18xx#10759]
[1889 Shikoku] - I was able to buy more than 19 maximal certificates in a 3 player game

Game ID: **163131**

The game is online multiplayer
https://18xx.games/game/163131

**How to Reproduce the Bug?**

In Stock Round 7 I was able to purchase moren than the 19 certificates, that should be the maximum in de 3 player game. I now have 21/19 certificates. In the stock round itself the counter for bought stock was off. I think, I it was stuck at 14/19 the whole time and I already wondered. It actually just updated, when we entered the Operation Round.

I have added a screen shot.
![Shikoku 1889 on 18xx games - bugreport - too many certs](https://github.com/tobymao/18xx/assets/56035203/e28a7cc1-fa7f-490e-851b-c60daf322886)

In the rules it says: "A player may not purchase a share if they are already at the Certificate Limit (7.6), even if doing so
would cause an exchange of a President’s Certificate that would bring them back into compliance" So that shouldn't have been possible!?

At least the certificate number is shown in red, so the program has detected, there is something off.

**Which Browser / Platform?**

Browser Version:
Firefox:  	125.0.3

**Comment by vandamm** [comment]
@WoAiJiqiXuexi if you take a look at the situation from this point https://18xx.games/game/163131?action=336, you can see that during SR only 16 of your certs were counting because KU was in yellow zone.
When SR7 ended, "KU's share price moves up from ¥50 to ¥55", getting it out of yellow zone so its certificates now count.
You will have to sell down to the limit as a first action in next SR unless KU gets into yellow zone again

**Comment by WoAiJiqiXuexi** [comment]
Oh thank you very much. I didn't notice that the KU company was in the yellow zone. That explains it.
This is the second time, I played a 18xx game and the first I play on 18xx.games. 
I was accused of playing wrong by my players or having superior hacking skills. Now I can claim, that I understand the game better than they do.

Jokes aside, thank you very much for clarify that so quickly.
