### ISSUE TITLE
[1822PNW] non-owning corp able to use P18 Boomtown

### ISSUE THREAD

**Issue by OrcaWilly** [tobymao/18xx#10758]
Placed Boomtown in Phase 7/E in 1822PNW - however I don't own the private as CPA.

https://18xx.games/game/160513

-->

**Comment by benjaminxscott** [comment]
Did you encounter that at this step, where CPR has begun operation?
https://18xx.games/game/160513?action=1572

I only see P11 and P8 shown which the CPR owns, and GNR owns the P18 (which doesn't show up)

![image](https://github.com/tobymao/18xx/assets/1711810/69c544a8-eaab-456c-ac4d-84efff76bed0)

It doesn't look like P18 has been used yet in your game, I presume that you refrained from using P18 when you encountered this bug

**Comment by OrcaWilly** [comment]
I undid the game when I realized my error of placing the boomtown tile - but this should not be happening in phase 7.  Bug?

This was selecting the tile and it shows the boomtown tile as available (not when pressing the private button)

**Comment by benjaminxscott** [comment]
I looked at a couple corp turns in OR 7 and 8 and couldn't repro the boomtown tile showing up as an option for different yellow track / hexes, was there a hex location / tile that it showed as available?

**Comment by OrcaWilly** [comment]
It was CPR turn at E20 dit town (upgrading from Brown to Gray)

**Comment by OrcaWilly** [comment]
![image](https://github.com/tobymao/18xx/assets/67157672/22fc391c-2f45-40c8-8eaf-27721d8ab0ea)

I cloned the game to OR8.2 and CPR turn to lay tile.

**Comment by OrcaWilly** [comment]
Also I tried different companies - when you upgrade it from brown dit to grey dit the option becomes available.

**Comment by benjaminxscott** [comment]
ah probably something in this LoC https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1822_pnw/game.rb#L949
