### ISSUE TITLE
[1846] - N/M trains only take into account the base value of a city (not bonuses) when calculating the best stops to keep

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#10760]
https://gist.github.com/OedipussyRex/2a8952ccd59bce1a038b972baf1910ad

GTR owns Meatpacking and has a token in the C&WI spot. Two trains run to/through Chicago, but only the train that runs to GTR's token receives the Meatpacking bonus, not the train that runs through the northeast spot.

**Comment by philcampeau** [comment]
The 3/5 train isn't counting Chicago as a stop, so it doesn't collect the bonus. But of course, if the bonus is counted, Chicago is worth more than Detroit and should be the stop chosen.

This likely has more to do with the Auto-routing code than 1846.

Interesting find!

**Comment by scottredracecar** [comment]
I think this is being counted correctly. Feel free to reopen if you disagree. I think the best route for the 3/5 includes the E/W and one more tokened city, which isn't Chicago since there is no Chicago token on the 3/5 route.

**Comment by philcampeau** [comment]
Ha yep, you're completely right. I almost closed it when I saw that Chicago was skipped, but then I got distracted by the values and forgot all about tokens.
