### ISSUE TITLE
[18RoyalGorge] wrong player listed as having Pdeal

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10772]
![IMG_7624](https://github.com/tobymao/18xx/assets/73144084/ebd726aa-3e0e-445a-96b2-6c0f7cc2106f)

https://18xx.games/game/164060?action=35

**Comment by benjaminxscott** [comment]
I think this is a logging bug, Frank gets priority as expected since they have the most cash after the auction

![image](https://github.com/tobymao/18xx/assets/1711810/54b1c246-4fd1-44b6-aee3-8ae7f0c54353)
