### ISSUE TITLE
[18ESP] can't finish the game

### ISSUE THREAD

**Issue by hachi-18xx** [tobymao/18xx#10805]
Game ID: 156000

**How to Reproduce the Bug?**
The following message appears and the operation cannot be performed.
"End Game" is also not accepted.

----
We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 931
Broken action: { "type": "pass", "entity": "TBF", "entity_type": "corporation", "id": 931, "created_at": 1711431731 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A18ESP,%22needs%20triage%22) and include this link (https://18xx.games/game/156000?action=930)
----

**Which Browser / Platform?**
Chrome (125.0.6422.78 (Official Build))

**Comment by benjaminxscott** [comment]
Ah it's an alpha game so the code got updated and is no longer playable or supported for debugging - it'll get deleted

**Comment by hachi-18xx** [comment]
I don't want this game to continue.
I'm wondering when it will be removed, as it has been giving me a turn for the last 2 months without me being able to do anything.
