### ISSUE TITLE
[1822PNW] P20-Backroom Negotiations closes without acquiring the last associate minor in a bid box.

### ISSUE THREAD

**Issue by stateless** [tobymao/18xx#10804]
**What's your Game ID?**

Table [162156](https://18xx.games/game/162156)

Non-associated  Minor 6 acquired P20 and associated Minor 20 is in Bid Box 2.  The exchange for Minor 20 was not offered; and P20 was just closed.

![image](https://github.com/tobymao/18xx/assets/12046/defe4a98-65ab-468e-953d-dd2edc03d4ea)
![image](https://github.com/tobymao/18xx/assets/12046/76163a15-524c-4e4e-89e8-3038dddae98d)
![image](https://github.com/tobymao/18xx/assets/12046/cd0d2af8-23d3-41b6-8886-b233dae57692)

**Which Browser / Platform?**
Brave on Linux:  1.66.113 Chromium: 125.0.6422.76 (Official Build) unknown (64-bit)

**Comment by outsidePasser** [comment]
Could you clarify what you think the issue is?

From the rulebook:  "When this private company is acquired by a non-associated minor company, choose an associated minor company that is currently not operational or in an bid box"...

I do not believe that you should have been able to exchange it for Minor 20, which is in a bid box.

**Comment by outsidePasser** [comment]
@stateless

**Comment by stateless** [comment]
Yeah. I not 100% clear to me if that (not operational) or (in a bid box) OR if that not (operational or in a bid box).  If it's the later, why not just say the draw stack?

**Comment by stateless** [comment]
Posted a question about it. https://boardgamegeek.com/thread/3309116/p20-backroom-negotiations-does-it-associated-minor

**Comment by stateless** [comment]
Yeah the later is correct - not (operational or in a bid box).  So not a bug.
