### ISSUE TITLE
[1847 AE] Error message when attempting to purchase a share of Rhein-Nahe-Bahn in phase 5 SR 8 Transinvestite's turn. This is similar to my earlier report.

### ISSUE THREAD

**Issue by Trainsinvestite** [tobymao/18xx#10814]
**What's your Game ID?**

https://18xx.games/game/164438 

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by Trainsinvestite** [comment]
I think I know what this relates to. In both cases this has happened to me the player after me had preprogrammed to auto buy the share that the game wasn't allowing me to purchase. This happened in both cases that the following player immediately purchased the share that I couldn't purchase in 2 different async games. When trying to purchase an error message referring to values popped up and then the page would restart to before I purchased the share in question. Thank you!!!

**Comment by Galatolol** [comment]
@Trainsinvestite In what game exactly that error occured? https://18xx.games/game/164438 doesn't have you among the players.

**Comment by Trainsinvestite** [comment]
It's probably because I changed my handle to TexasRocket some time after
that report. Sorry for being confusing.

**Comment by Galatolol** [comment]
Ah, ok. I didn't realize.

You mean the first double share (i.e. the second certificate)? I cloned the game and didn't get the error:
![image](https://github.com/tobymao/18xx/assets/10097748/43991446-35e0-4384-8cda-7f8b41799762)

**Comment by Trainsinvestite** [comment]
It hasn't happened since but it seemed like it wasn't letting me buy a
share that another player had set to automatically buy. In both cases it
gave me an error message and if I took any other available action I would
then see the following player auto-buy the share in question.

**Comment by Galatolol** [comment]
Ah, okay. So it's something related to autobuying. Honestly I have no idea how to fix that. Maybe autobuying should be disabled for this game.

**Comment by bsnqrk** [comment]
I can reproduce this issue in a local development environment.
At the beginning or SR8, player cash crisis needs to buy the first president certificate and then enable Auto Buy Shares for RNB with e.g. Until float.
The next player, or in particular this case TexasRocket is not able to buy a share anymore.
The command send to the server is a 
`POST http://localhost:9292/api/game/164438/action` 
with this body
`{"type":"buy_shares","entity":16224,"entity_type":"player","id":679,"created_at":1718918277,"auto_actions":[{"type":"program_disable","entity":7428,"entity_type":"player","created_at":1718918277,"reason":"TexasRocket has bought, shares exist that could allow them to gain presidency"}],"shares":["RNB_2"],"percent":20,"_client_id":"4187855155d044189bead63c78f78757"}`
The response is a 500 with `{"error":"Illegal action: wrong number of arguments (given 1, expected 0)"}`

Does this help further to investigate? Currently, I have no idea where exactly take a look into the code.

**Comment by bsnqrk** [comment]
The backend logs following message, which might help to further understand the issue, or get an idea where to fix it: 

> rack-1   | D, [2024-06-20T22:07:43.074101 #24] DEBUG -- : Caught exception #<ArgumentError: wrong number of arguments (given 1, expected 0)>, backtrace: [/18xx/lib/engine/step/buy_sell_par_shares.rb:413:in max'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:413:in action_is_shenanigan?'
> rack-1   | /18xx/lib/engine/game/g_1847_ae/step/buy_sell_par_shares.rb:110:in action_is_shenanigan?'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:444:in block (3 levels) in should_stop_applying_program'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:440:in each'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:440:in block (2 levels) in should_stop_applying_program'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:439:in each'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:439:in block in should_stop_applying_program'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:436:in each'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:436:in should_stop_applying_program'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:506:in activate_program_buy_shares'
> rack-1   | /18xx/lib/engine/step/programmer.rb:16:in block in programmed_auto_actions'
> rack-1   | /18xx/lib/engine/step/programmer.rb:12:in each'
> rack-1   | /18xx/lib/engine/step/programmer.rb:12:in programmed_auto_actions'
> rack-1   | /18xx/lib/engine/step/buy_sell_par_shares.rb:362:in auto_actions'
> rack-1   | /18xx/lib/engine/round/base.rb:146:in auto_actions'
> rack-1   | /18xx/lib/engine/game/base.rb:791:in process_action'
> rack-1   | /18xx/routes/game.rb:103:in block (6 levels) in <class:Api>'

It think, it might be possible to override `step/should_stop_applying_program` as in e.g. 1849, and stop auto buy if double shares are handled.
