### ISSUE TITLE
[1858] Cannot trade in private for share

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#10813]
https://18xx.games/game/163331

SR3: I have started AVT (with V&J) in Valencia. I then auctioned a green private (S&C) and won that. Everyone else having passed, I tried to absorb M&C into AVT but the only action available for AVT is to grow to 10-share. I only have 2 shares in AVT.

**Comment by ollybh** [comment]
Also https://18xx.games/game/160946?action=552. I'm not able to trade O&V for an RP share. There is a broad gauge connection from RP's tokens to B5, RP has treasury shares available, and I own less than 60% of RP so it should be possible to make this exchange.
![image](https://github.com/tobymao/18xx/assets/11144854/0bbdc60c-99c8-4aa3-8007-d5da6212b2fc)
![image](https://github.com/tobymao/18xx/assets/11144854/d22bf050-97d5-4f26-a1c5-7f810fffc397)

**Comment by ianwilson156** [comment]
This used to work - looks like a bug has been introduced somehow.

**Comment by ollybh** [comment]
It looks like this has been broken by some other change made in the last couple of weeks. I just need to work out which change it was...

**Comment by ollybh** [comment]
This has been broken by commit 67572e89c1.
@crericha The new function `player_owned_ability?` isn't working if the owning entity is a minor. What problem were you fixing with this change? Could the test be changed from `ability.owner&.company?` to `!ability.owner&.corporation?`?

**Comment by ianwilson156** [comment]
This bug has not been fixed!

**Comment by roseundy** [comment]
The fix still needs to be deployed. The bug closes when the code is updated, not when it goes "live".
