### ISSUE TITLE
Bug: not allowing to pass twice in same tile but different cities 

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#1081]
In 1836Jr30, specifically in NY tile, is not possible to make a route passing twice at the same tile, but in different stations

![IMG-20200711-WA0027](https://user-images.githubusercontent.com/4177168/87239735-ec268d80-c3e8-11ea-95fd-3213ef03b2c3.jpg)

**Comment by Djeefther** [comment]
In 1836Jr30, specifically in NY tile, is not possible to make a route passing twice at the same tile, but in different stations

**Comment by jenf** [comment]
Please provide sample game showing the issue

**Comment by jenf** [comment]
Bug also applies to 18Chesapeake

**Comment by jenf** [comment]
1836Jr30 behaves correctly
`	3	F150	D6 E7 D6
HSM runs a 5 train for F150 (D6, E7, D6)
`
