### ISSUE TITLE
[1844] Selling shares one at a time should not drop the price multiple times.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10824]
https://18xx.games/game/165067?action=612
[20:35] Hushed sells a 10% share of RhB and receives 80 SFR
[20:35] RhB's share price moves down from 90 SFR to 80 SFR
[20:35] Hushed sells a 10% share of RhB and receives 70 SFR
[20:35] RhB's share price moves down from 80 SFR to 70 SFR

Expected: Even if Hushed sell the shares one at a time, as part of a single stock action, the he should receive money based on the share's original price and the price should only drop once.
Observed: By selling one share, and then one more share, the share price dropped a second time, and Hushed received less money for the second share.

**Selling Shares**
> A player may sell any number of shares. Certificates may not be sold.
> Shares sold by the player go into the bank pool and can be bought by other players
> during the Stock Round.
> If the company has already operated the seller receives the current market price,
> after which the price is moved down by exactly one space.
> If the company has never operated the price is moved down first, and then the
> seller gets the new market price.

**Comment by philcampeau** [comment]
I'm not sure how you're coming to this conclusion. As per the rules, a share (or any number of shares) of an unoperated corp is sold, the seller receives the new market price, and the price is moved down by exactly one space to that new market price. If they now sell a second share (or a second bundle of shares), you start back at the top of the sequence of events: sell, receive the new market price (now one market row lower than before), and the price drops exactly one space.

**Comment by physic** [comment]
Phil. Where are you getting the idea that you can do this as many times as you want?

According to the rules you may, on your turn:

1. Sell any number of shares.
2. Buy one share.

They then clarify how share prices move after shares are sold. I see no reasonable way to infer that I can sell as many packets of shares as I want, and have the price move in between each sale. I get ONE sale, wherein I may sell any number of shares, per step 1 of 2 above.

**Comment by physic** [comment]
Phil, in your interpretation, what then is the point of saying "When you sell more than one share of the same type of stock, the share value only drops down one space." if that rule can be trivially circumvented? Why should I be allowed to repeat step 1 as many times as I like, and insert the stock movement rules in between each one? May I also repeat step 2 and buy one share as many times as I like in one action?

**Comment by philcampeau** [comment]
The rule is not being circumvented. The selling player is losing money with
each sale by selling the shares separately rather than all together.

I would ask you, where are you getting the idea that all of your sales must
be done as a single action? The rule says "sell any number of shares". It
doesn't give an indication one way or the other as to whether you have to
sell them all at once.

If you'd like, raise the question on BGG. Helmut Ohley is still semi-active
there, under the user name O_Games.

**Comment by crericha** [comment]
@philcampeau, I believe @physic's interpretation is correct. Its the same rule as 49 has. There is code to already only move the share price down one on sale, but it doesn't account for a player doing it twice during their sell action. 49's code does and I need to add that.

**Comment by philcampeau** [comment]
It's definitely possible. The rules are ambiguous, in my opinion. I posted a thread on bgg asking the question: https://boardgamegeek.com/thread/3308703/can-players-sell-multiple-shares-in-a-company-one

**Comment by crericha** [comment]
German rule text. Clearer than the English.

> A player may sell any number of shares in public companies. Certificates
cannot be sold.
The player places the corresponding shares in the bank pool and receives per
sold share the current market value from the bank.
The price markers of the corresponding companies are then displayed on the
Stock market pushed down one space, regardless of how many
shares he sold.
If a player sells shares in a company that has not yet traded, he receives
only the price value after the price change!

**Comment by philcampeau** [comment]
All in all, I don't have any dog in this race. But the German text you quoted doesn't clarify the ruling on this subject any more than the English text, in my opinion.

**Comment by scottredracecar** [comment]
I think this is very much a 50/50 case and it just depends on the designer's attitude toward such sales. Since the rules don't go into detail about grouping sales in to blocks, my RAW reading is more like Phil's, but it's totally possible that's not the case or that this situation wasn't even considered when writing the rules.

**Comment by physic** [comment]
Scott, if you cannot group sales into blocks, the only interpretation is that you sell them all at once, in which case (truly in any case) the clause "Move the price down once no matter how many shares were sold" must then apply to the entire sell shares action, and not to each block, since there is no such concept.

The rules describe a procedure to follow to execute the "Sell Shares" action. Let's consider the translated rules crericha posted above. This procedure is as follows:
1. Sell any number of shares.
2. Receive the value of the shares, and place the shares in the bank pool.
3. Move the price of each company down once, regardless of how many shares were sold.

There is nothing left to the imagination here, except that the order of share sales is unspecified.

**Comment by scottredracecar** [comment]
I think we all know the arguments for or against.

1849 has a lot of wording that gets specific about how this works for the "selling all as a block" vs individual blocks of sales. So that is a good counter example for how to write these rules to make it work the way you are advocating for.

Ultimately, no point in arguing about this because no matter what the rules say, it's just going to come down to whatever Helmut Ohley says which I put at a 50/50 either way.

**Comment by philcampeau** [comment]
For the record, I geekmailed Helmut about this, but he hasn't logged in to bgg since may 27, so no reply yet.

**Comment by philcampeau** [comment]
Alright, finally got a reply. He agrees with physic's  interpretation here. (Second answer in geekmail):

![Screenshot_20240623_083234_Chrome](https://github.com/tobymao/18xx/assets/26125362/5b10d3ab-6f97-4365-8d18-02c71a1b6056)
