### ISSUE TITLE
Feature suggestion: It should be possible to select variants of 18xx when creating a game

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1082]
Some 18xx has variants/optional rules that is of interest to try. 
Example:
- 18AL: Use "hard-rust" instead of "obsoleteness" when buying 7T
- 18MEX: Allow corporations to lay 3 yellow tiles instead of 2 during its first OR

It would be nice if when creating the game it would be possible to select which optional rules (if any) that should be used for the game. The selection could be shown in the description for the game.
It should be possible to select multiple optional rules (each game should check if a combination is invalid).

I see no use case for changing optional rules.

**Comment by perwestling** [comment]
If this is seen as a good idea, I could try to implement something as part of my work with 18AL. I do not know if any of the existing supported 18xx has a need for this feature.

**Comment by perwestling** [comment]
Thought this would be straight forward but was not able to modify create_game.rb. 

I added a constant GAME_OPTIONAL_RULES
Eg 
```
GAME_OPTIONAL_RULES = {
  hard_rust: 'Rust 4T when 7T bought',
}.freeze
```

Then my intention was to add a multi-line select filled with the GAME_OPTIONAL_RULES values for the game selected in Game Title. 
The select optional rules should then be a list of values that could be checked for in the game.

But I did not get this to work, in create_game.rb, so I will pause this.

If anyone with better knowledge about how to create views like to try this, please go ahead.

**Comment by perwestling** [comment]
Have worked a bit more on this and now have something that does seem to work. It has been tried in 18AL.
The implementation draft can be found in branch: https://github.com/perwestling/18xx/tree/feature/optional_rules/first_attempt_18AL

Will put this on pause until a user request to actually have support for optional rules appear.

**Comment by michaeljb** [comment]
> Will put this on pause until a user request to actually have support for optional rules appear.

#1868 has such a request for 1817

I was also thinking this would also be useful for each of the optional private companies in 18 Los Angeles
