### ISSUE TITLE
[18Neb] DRG and NK tokens not rendering 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10826]
https://18xx.games/game/164369#entities

**Comment by philcampeau** [comment]
They render on my end. Could you give more information about where it's not displaying properly for you?

![image](https://github.com/tobymao/18xx/assets/26125362/f145bc9d-4d24-4358-bd5d-880330c6edc4)

**Comment by BellmakerSA** [comment]
![IMG_7640](https://github.com/tobymao/18xx/assets/73144084/2bcfbf31-0bb6-4e78-911a-20c071a125b3)
![IMG_7641](https://github.com/tobymao/18xx/assets/73144084/6545adcd-3d66-41c9-84f6-a50a9b8efd82)

I am using Safari if that matters

**Comment by scottredracecar** [comment]
These also do not show up for me on Safari, but do show up on Chrome.

Same issue with viewing the svg directly. Probably something is just weird
about those svgs.
https://github.com/tobymao/18xx/blob/master/public/logos/18_neb/DRG.svg
https://github.com/tobymao/18xx/blob/master/public/logos/18_neb/NK.svg

**Comment by crericha** [comment]
I'm enabling simple logos for now. Will look at the SVGs on a mac later.
