### ISSUE TITLE
[1871 The Old Prince] - game hanging after split attempt

### ISSUE THREAD

**Issue by TheOldWhitehorse** [tobymao/18xx#10825]
https://18xx.games/game/162898

I click 'split' for MR... and everything hung. It now seems impossible to enter the game :/

Firefox 126.0, but folks in chat had the same issue so I doubt it is my end.

-->

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
This seems to be caused by my update here #10796

I'll see if I can resolve it, worst case we revert it back. I tested on my end and reverting the code back does fix the issue.

**Comment by dtschirmer** [comment]
This happened to me too, also trying to split MR on game # 164589. 
I'm using Firefox 126.0 on a mac.
I also can't enter the game.

**Comment by michaeljb** [comment]
Reverting and deploying

**Comment by philcampeau** [comment]
yep, both games load now. I'll keep working on my patch, and test it a bit more thoroughly before submitting again!
