### ISSUE TITLE
[1841-Version1] Add optional rule for Version 1 to allow SFLi to run the same as the Version 2 rules

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#10832]
https://18xx.games/game/164879

Thanks for making this game available!  I appreciate it.  We've run into a bug.

SFLi formed when the first company operating (CTDA) bought a 4.  None of the SFLi component companies (SFMA, SSFL, SFLP) had operated.  But the programming failed to let the SFLi run saying:  

[12:00] SSFL closes
[12:00] SFLi will not run this OR

But this is not accurate:

From page 14, under Tuscan Merge:  "The SFLi will operate during the Operating Round in which it is formed if none of its components have already operated."  This was true in the original 1839 version as well.

**Comment by roseundy** [comment]
https://18xx.games/game/164879?action=291

**Comment by roseundy** [comment]
Crap. This logic is mostly missing.

**Comment by WayneWWms** [comment]
I’m surprised it’s never come up before in the testing….

Although I know a lot of times the companies don’t start down there.

Thanks for your work!

Wayne

**Comment by roseundy** [comment]
It is odd that it's never been found before. I have a fix ready.

**Comment by roseundy** [comment]
I take it all back. I _did_ try to implement this correctly. The issue is that you are running with version 1 rules, and in version 1, the rules are silent as to whether the SFLi runs or not. I chose to never run it in the OR it forms. I'll look to see if there is any official ruling on this.

**Comment by roseundy** [comment]
http://www.18xx.net/1841/1841f.htm indicates that I am correct.

**Comment by WayneWWms** [comment]
Thanks.  I guess my group in the old days always played with the variant.

 

Since you have it programmed, any chance to add that variant?  Otherwise the south is pretty useless.

 

Thanks again.

Wayne

**Comment by roseundy** [comment]
We can turn this into an enhancement request.

**Comment by roseundy** [comment]
I hacked your game to retroactively add the new optional rule I'm implementing. When the fix deploys (not sure when), you game will work as desired.

**Comment by WayneWWms** [comment]
THANKS!

 

Wayne

 

Wayne W. Williams

Designated Election Official

3472 Research Parkway, Ste. 104-200

Colorado Springs, CO 80920

(719) 439-1870

**Comment by WayneWWms** [comment]
Thanks!Wayne WilliamsSent from my iPhoneOn Jun 11, 2024, at 5:40 PM, Steve ***@***.***> wrote:﻿
Closed #10832 as completed via #10906.
