### ISSUE TITLE
[1894] Station Antwerpen Centraal is not allowing me a choice of brown upgrade.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10831]
https://18xx.games/game/165039?action=237

When I go to use the Antwerp teleport, it only gives me the option to lay #X19, when #X20 and #X21 should also be available options.

**Comment by philcampeau** [comment]
@Galatolol I'm looking at the rules for your game. In the rules, both the Station Antwerpen Centraal and the Gare de Liège-Guillemins's descriptions say "The owning public company may place a yellow track tile or **upgrade a yellow track tile**" in their respective cities, while the description on 18xx.games simply says "may lay or upgrade a tile" in their respective cities. 

Is the intention that you should only be able to use this ability for yellow and green tiles, or can it also be used to upgrade to brown?

**Comment by physic** [comment]
Oh, good catch, Phil. Maybe I shouldn't have been able to use its ability at all.

**Comment by Galatolol** [comment]
You should be able to upgrade to brown. There are incorrect tile ids in the private’s power’s code and the rulebook has to be updated. I'll do it tomorrow.

**Comment by Galatolol** [comment]
Actually not, too many edge cases with stations. Let it be "may lay or upgrade a yellow tile", like it was written in the rulebook.
