### ISSUE TITLE
1846 "It is not ERIE's turn"

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#1086]
I get a "It is not ERIE's turn" error message after I lay my first tile with Eerie.
Whilst the interface clearly shows that it is Eeries turn.

Game id 3419

**Comment by Spobster** [comment]
This one must be related to the fact that IC moved one down on the market and ERIE moved one spot up. I don't even know which of the two had priority for that 150 spot. But in the main overview it is Mario's turn, while in the game it seems to be Moshi's turn. The algorithm is confused by the moves :)

**Comment by tobymao** [comment]
i just tried it and i see no problems

spobster: If it is not fixed soon, we could already start a new game with the four of us if all of you agree.
ERIE spends $20 and lays tile #9 with rotation 0 on B14
ERIE spends $20 and lays tile #28 with rotation 5 on C13
ERIE passes

**Comment by tobymao** [comment]
fixed
