### ISSUE TITLE
[1822Africa] P12 (Saharan Fast Tile Lay) not working as expected

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#10886]
https://18xx.games/game/165906

We can’t figure out why P12 isn’t laying numerous tiles.

apologies if this is a duplication, but if it is, please link that thread.

**Comment by michaeljb** [comment]
https://18xx.games/game/165906?action=227

gist backup - https://gist.github.com/michaeljb/cf04460b868f72be5e49be9c72dd68ad

**Comment by benjaminxscott** [comment]
Looking at this, I don't think P12 is working properly. Working off the assumption that using the private replaces the normal track laying step with the ability to teleport place yellow tiles on desert hexes (paying terrain costs)

https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1822_africa/entities.rb#L219

1 We are in a Track step and it wants to fire in a specialtrack step, which has been skipped. Maybe we need logic in that step to block if P12 is owned? Or maybe I'm misunderstanding how specialtrack is triggered
 (Then presumably the "consume tile lay" flag will correctly skip it's normal Track step)

2 my reading of the private description is that the hexes dont need to be "reachable"

**Comment by scottredracecar** [comment]
Tiles need to be reachable.

The wording could be adjusted to "...any amount of yellow tiles following the other tile laying rules..." to make that less ambiguous.
