### ISSUE TITLE
[21Moon+] Certificate Limit changes after closing corporations

### ISSUE THREAD

**Issue by davidlaughlin** [tobymao/18xx#10882]
**What's your Game ID?**
163960

https://18xx.games/game/163960

**How to Reproduce the Bug?**

Certificate limit at the start of the game for a 5 person game was 10.  2 players went bankrupt and the cert limit is now 12.  Rulebook states that the cert limit for a 3 person game should be 15.  I can't find any other rules stating how cert limit would be changed to 12.  Confirmed that starting a hotseat 3p game of 21Moon, the cert limit is 15.

**Which Browser / Platform?**

Firefox 126.0.1 (64-bit)

**Comment by roseundy** [comment]
I believe this is caused by the code that closes a corporation.
