### ISSUE TITLE
Game 3772

### ISSUE THREAD

**Issue by randomgeekdom** [tobymao/18xx#1088]
{
  "id": 3772,
  "description": "SNB1846 private",
  "user": {
    "id": 2840,
    "name": "I_hate_nicks_characters"
  },
  "players": [
    {
      "id": 2751,
      "name": "randomgeekdom"
    },
    {
      "id": 2755,
      "name": "twoscoopsofpig"
    },
    {
      "id": 2840,
      "name": "I_hate_nicks_characters"
    }
  ],
  "max_players": 4,
  "title": "1846",
  "settings": {
    "pin": "eba344e",
    "seed": 5.598918607968225e+37
  },
  "status": "active",
  "turn": 1,
  "round": "Draft Round",
  "acting": [
    2752
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 60,
      "entity": "twoscoopsofpig",
      "company": "MS",
      "entity_type": "player"
    }
  ],
  "loaded": true,
  "created_at": 1594408767,
  "updated_at": 1594577496
}

**Comment by tobymao** [comment]
pinned game deleting
