### ISSUE TITLE
[1846] GameError: Not a buyable train: 2-7

### ISSUE THREAD

**Issue by neanias** [tobymao/18xx#10905]
**What's your Game ID?**

https://18xx.games/game/164036?action=81

[Game data](https://gist.github.com/neanias/64b07b2ea834bca4f623162e33c0b195)

**How to Reproduce the Bug?**

**Which Browser / Platform?**

This looks like a back-end issue, so not sure it's applicable?

**Comment by michaeljb** [comment]
This needs to be pinned due to #10889

**Comment by michaeljb** [comment]
The game has been pinned and you can finish playing. Thanks for reporting the problem!

**Comment by neanias** [comment]
Thanks for sorting!
