### ISSUE TITLE
[18GA] Better graphic for Jacksonville

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#10915]
Jacksonville should be two dead-end arrows. The current implementation implies that ACL could run a train through Jacksonville.

https://18xx.games/map/18GA

<img width="431" alt="Screenshot 2024-06-12 at 20 40 24" src="https://github.com/tobymao/18xx/assets/8732435/d2982340-35a2-4236-9e7a-a1d6bf489f9e">

Original map image:

<img width="597" alt="Screenshot 2024-06-12 at 20 37 33" src="https://github.com/tobymao/18xx/assets/8732435/d6b0ee61-896f-4cf5-a6ca-302ef040a34e">

**Comment by philcampeau** [comment]
The rules say that ACL can run routes through Jacksonville, so actually the way it's rendered on 18GA is actually clearer than the original map art. 

![image](https://github.com/tobymao/18xx/assets/26125362/a822ef75-f5b6-4e1c-ab6d-6e8bb201be01)
