### ISSUE TITLE
Bug 1836Jr30: HSM was allowed to place a station in the home station of the NBDS. 

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#1091]
After when NBDS floats the company has no action.

![image](https://user-images.githubusercontent.com/4177168/87355970-aaf0c380-c537-11ea-8ba7-475194cc18a7.png)

**Comment by Djeefther** [comment]
Status here: https://gist.github.com/Djeefther/32bb7c738a5387186b40d474d1db71d4

**Comment by jenf** [comment]
Yep another NBDS token bug, dup of #896
