### ISSUE TITLE
1850 Mesabi token unavailable

### ISSUE THREAD

**Issue by barattie** [tobymao/18xx#10921]
**What's your Game ID?**
165314

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
![image](https://github.com/tobymao/18xx/assets/26125362/4e46d8d6-0ee9-4903-810e-7a7c4b00a4fb)
![image](https://github.com/tobymao/18xx/assets/26125362/f2f15ab2-61c9-4358-83ee-506aa02ff4f5)

**Comment by barattie** [comment]
Thanks a lot!
