### ISSUE TITLE
If OR1 happens before all private companies are sold, then export a train

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#1092]
I am not proud to submit this bug, but in the interest of having a perfect implementation of 18Chesapeake rules, here it is.

If all the players pass during the initial stock round after a private company has been purchased, we run an OR. After this OR, a train should be exported. So this screenshot is correct, but also there should be an export which doesn't happen currently.
![image](https://user-images.githubusercontent.com/29106780/87428900-9f89b080-c5a8-11ea-95b6-5dde6cb760bf.png)

**Comment by jenf** [comment]
Still and issue post or step rewrite

**Comment by tobymao** [comment]
lol 50 games hit this issue

**Comment by jenf** [comment]
@scottredracecar this could be improved in the rulebook if there's ever a update
