### ISSUE TITLE
1861: RSR buys 3T from the Pool

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#10932]
https://18xx.games/game/167429

When RSR ran first time (end of OR4.1), there was a 3T in the Pool, which it bought - not a 5T from the Stack of new trains.
2nd edition rules say:
"The RSR always buys the cheapest _new_ train(s) from the Bank..."
(3rd edition is ambiguous)

**Comment by ollybh** [comment]
@ianwilson156  The RSR has just started operating in OR 4.1 so it does not have a train. The last paragraph of section 10.10 of the AAG rules says:

> If the Russian State Railway has no train, it will buy the cheapest train from the Bank or Bank Pool, taking out loans if it has insufficient money in its treasury.

So the purchase of the 3-train from the pool is following these rules.

**Comment by ianwilson156** [comment]
Ah ok, I'm forgetting my own rules, must be getting old! It normally only buys a new train, but if trainless it will also buy from the Pool. (1st edition is the same.)
Sorry for the confusion.
