### ISSUE TITLE
Max Players is not capped by game limit

### ISSUE THREAD

**Issue by ry-dgel** [tobymao/18xx#10937]
**How to Reproduce the Problem?**
* Create a new game
* Select a title
* Set the max players to whatever number you want, in excess of the game limit
* Get cozy with all the friendly players on the site (optional)
![image](https://github.com/tobymao/18xx/assets/14968322/e74ff3a5-5696-4a4a-9f75-6b2211792a32)

**Which Browser / Platform?**
N/A

**Comment by benjaminxscott** [comment]
related? 
https://github.com/tobymao/18xx/pull/9250

**Comment by benjaminxscott** [comment]
fwiw the game will still correctly not allow you to start it if current_players > max_supported_players

it is pretty funny tho
