### ISSUE TITLE
[1822pnw] Backroom Negotations did not let me choose a company that had been removed from the game.

### ISSUE THREAD

**Issue by merlinofchaos** [tobymao/18xx#10938]
https://18xx.games/game/167707

During Operating Round 6.1, M3 used Backroom Negotiations. 20 had fallen through bid box 1 and was removed; that company should have been eligible to be replaced, but the game only offered 8 and 18.

**Comment by michaeljb** [comment]
https://18xx.games/game/167707?action=589

https://gist.github.com/michaeljb/4146b43711aca40ad7da51581f6811b3
