### ISSUE TITLE
[18RoyalGorge] undefined method name for nil is back

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10959]
https://18xx.games/game/167919

![IMG_7687](https://github.com/tobymao/18xx/assets/73144084/193b0e37-9107-426e-aefd-82ab118b182b)

I think it’s because there’s no train to export but not 100% sure, not an issue in recent other games 🤷‍♂️

**Comment by michaeljb** [comment]
> I think it’s because there’s no train to export but not 100% sure

Yep, this was it! The fix will be in soon.

Thanks for reporting the issue!
