### ISSUE TITLE
[18Hiawatha] Game ID 165302

### ISSUE THREAD

**Issue by CzlDzl** [tobymao/18xx#10977]
*Game froze during final SR/SR 4.
*I was just buying a share in DL&W that was formed that round. 
*Game advised to open a ticket and include the following:

We're sorry this game cannot be continued due to GameError: Blocking step Buy or Sell Shares cannot process action
Broken action: { "type": "pass", "entity": 17440, "entity_type": "player", "created_at": 1719373802 }

https://18xx.games/game/165302?action=1163

**Comment by CzlDzl** [comment]
I can't kill the game either. Just tell Jason I won and kill it. Please and thank you.

**Comment by michaeljb** [comment]
Archived
