### ISSUE TITLE
Usability: Show Status for each hotseat game in the Welcome page

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1097]
It would be nice to see the status of the games in the main page.
It could e.g. be a line
  **Status:** Private auction
  **Status:** Game over
  **Status:** SR1
  **Status:** OR7.3
  **Status:** Not started  ((or something similar for games that have not yet been started. Maybe different for games that wait for players to join, and games that wait for game creator to start the game))

A potential further improvement could be to show which player is the current one.

A feature like this would
- Help to separate hotspot games when you create several ones during testing
- Help to select games when playing several
- Simplify for "audience" to find games of interest

**Comment by yzemaze** [comment]
Streamlining and more details wouldn’t hurt, but most of these are already there: e. g. Round: Auction/Draft 1, header color of game cards, underlining of current player. The majority just isn’t implemented for hotseat games.

**Comment by jenf** [comment]
We should improve it for hotseat games.

I'd also suggest we add a default description of hotseat games if none is supplied (the date it was created), i'm constantly getting confused which one is which.
