### ISSUE TITLE
[1822PNW Short Variant] Minor Combo Malfunction

### ISSUE THREAD

**Issue by KenKuhn** [tobymao/18xx#10983]
**What's your Game ID?**
https://18xx.games/game/168492

**How to Reproduce the Bug?**
When the combo in Bid box one is won, both minors, the associated and the unassociated, are supposed to start. The bug is that they are not. At least in our game M6 didn’t start.

**Which Browser / Platform?**
Chrome

**Comment by michaeljb** [comment]
Thanks for reporting this Ken, the fix should be live now. I woefully under tested this and the Southern Regional Scenario when initially adding them, hopefully they’re good now 😅

**Comment by KenKuhn** [comment]
Michael, no worries. I’m here to help and do some bug hunting!

I’m just really thankful that you added these variants, so thank you 🙏
