### ISSUE TITLE
Wingding on info page

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1099]
The Upgrade Discount section has a wingding. I think it used to be an arrow.

4, 5, 6 ⮕ $200

<img width="671" alt="Screenshot 2020-07-15 09 32 22" src="https://user-images.githubusercontent.com/8732435/87570943-307e8b80-c67e-11ea-888d-f6b4d120c1b7.png">

**Comment by yzemaze** [comment]
It still **is** an arrow. Which OS & browser (versions) do you use?

**Comment by ChrisTheCat** [comment]
I'm running OS X 10.14.6. The above screenshot is on Firefox 78.0.2 (64-bit). The below screenshot is from Safari 13.1.1 on the same computer.

<img width="176" alt="Screenshot 2020-07-16 22 21 45" src="https://user-images.githubusercontent.com/8732435/87751548-15616800-c7b3-11ea-8b40-170826811131.png">

**Comment by ChrisTheCat** [comment]
and this is Chrome 84.0.4147.89 (Official Build) (64-bit)

<img width="512" alt="Screenshot 2020-07-16 22 27 00" src="https://user-images.githubusercontent.com/8732435/87751719-8e60bf80-c7b3-11ea-8eef-b8ebaa6a4ff9.png">
