### ISSUE TITLE
[1870] Bill Dixon's original 70 rules

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#11006]
There are several rules changed from Dixon's original rules to Mayfair.  I see Phil is already implementing the price protection changes.

1. Game supports up to 7 players 5.4.1 https://web.archive.org/web/20110409211332/http://www3.telus.net/wrdixon/1870html/1870dif.html
2. Reissuing shares limited to $200 5.11 https://web.archive.org/web/20110409171034/http://www3.telus.net/wrdixon/1870html/1870sec05.html
3. Tile list much more limited https://web.archive.org/web/20110409211343/http://www3.telus.net/wrdixon/1870html/1870sec02.html

Additional information can be found here:
https://web.archive.org/web/20110409211332/http://www3.telus.net/wrdixon/1870html/1870dif.html
https://groups.io/g/18xx/topic/106908720#msg51531
https://web.archive.org/web/20201111210240/http://www3.telus.net/wrdixon/1870html/1870toc.html

**Comment by philcampeau** [comment]
Working on the price protection. I can look at these too. This should be easier actually.
