### ISSUE TITLE
[1822CA] Tax Haven value is double counted

### ISSUE THREAD

**Issue by David-Tinman** [tobymao/18xx#11007]
Just before the last company is to run at the end of the game the NTR), I notice that I (TINMAN-D} should be winning but the player in second place (Daroj) has a value more than mine. When I check his details I see that the contents of the Tax Haven are included twice in his total value. This may have been happening all through but I don't think so, as yo can see from the earlier spreadsheet values. Is this enough for you?

**What's your Game ID?**

**How to Reproduce the Bug?**

![Screenshot (8)](https://github.com/tobymao/18xx/assets/82830761/63851f97-9ac4-4b00-9da1-5f9ff4b0f91c)

**Which Browser / Platform?**

**Comment by michaeljb** [comment]
Thanks for reporting this.

Looks like the fix for #5200 was incorrect
