### ISSUE TITLE
1822MX - Cannot place 2-dit tile in M22 from a track to the east of the hex.

### ISSUE THREAD

**Issue by gargoyleking** [tobymao/18xx#11015]
168850

https://18xx.games/game/168850

**How to Reproduce the Bug?**

16 Ferrocarril Atlamaxac builds from east to west One tile is provided as an option, but even that, in this game, is already laid and cannot be returned do to upgrading.  MC isn't started and can't build any tiles.

-During OR 4.1 (of 2), 16 attempts to build a railroad on hex M22.  
  -One build cube is on the space, company has the money to pay the other $20 of the cost.
  -Two options are visibly available.  1) Add a build cube to the space.  2) Place Tile #2 in the space.  Tile #2 is unavailable, as there is only one and it has already been placed elsewhere on the board.

**Which Browser / Platform?**

Attempted on Android google chrome, and also on PC Firefox. (127.0.2 (64-bit)

![1822MX_M22_tileerror](https://github.com/tobymao/18xx/assets/23289732/41780764-b60a-44a8-aab7-cf8bf5ea68be)

**Comment by michaeljb** [comment]
Per rule 6.9.2, tile 2 is the only one that would be legal here. Since MC has no owner, the track that connects to Mexico City has to connect to pre-existing track

**Comment by gargoyleking** [comment]
That....  is stupid.

**Comment by michaeljb** [comment]
@scottredracecar is my interpretation correct? Or would it be ok to allow one of the other double-dit tiles to be placed on M22, as long MC has a connection to *some* track?

**Comment by scottredracecar** [comment]
Correct
