### ISSUE TITLE
[18MEX] Game allows to purchase and sell the same share in a single turn

### ISSUE THREAD

**Issue by jesberpen** [tobymao/18xx#11014]
**What's your Game ID?**
[166930](https://18xx.games/game/166930)

**How to Reproduce the Bug?**
The game menu let's you purchase and sell a share on the same turn, see the 3 times it has been done by the same player in stock round 5 (previous 3 links). This is not allowed per the game rules.

During Stock round 5 a player has been able to purchase and sell immediately the same share in 3 different companies (3 different actions, but same stock round). This is not allowed per the game rules.

**Which Browser / Platform?**
I've seen it in Chrome, I don't know the browser used by the player that has done the actions.

**Comment by michaeljb** [comment]
This actually is allowed by the 18MEX rules.

> 3.2 Regular Stock Turn
> 
> Once all of the private and minor companies have been purchased from the bank, each player may do any, all, or none of the following on his turn:
>
> (a) Sell any stock certificate(s) of a major company ...
>
> ...
>
> (c) Buy one certificate ...
> 
> You may not sell one or more certificates, buy a certificate, and then sell it on the same turn. That is, your one purchase (if any) must either precede or follow, all sales (if any) you make on the same turn. You may do any of these things, except (c), more than once on a turn.

That last paragraph prohibits "sell-buy-sell" but allows "buy-sell" OR "sell-buy". spatten's actions (e.g., https://18xx.games/game/166930?action=360) fit within the "buy-sell" rule.
