### ISSUE TITLE
18C2C

### ISSUE THREAD

**Issue by AntonioDG71** [tobymao/18xx#11018]
**What's your idea?**

What about for having 18C2C game in library ?

**Are there related ideas?**

I'm able for playtesting the start version

**Did you join the Slack?**
Not yet

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-27imtsj2u-vussFAqtecmACsycjdsIhg) and meet your fellow contributors!

**Comment by ollybh** [comment]
We do not have permission to add 18C2C to the site. There's a spreadsheet which shows which games were are allowed to implement: https://docs.google.com/spreadsheets/d/1ndWr805MZ8pIzSgh94bb6C3zr3Noh4Xpc3Gl2FN_-6g/edit#gid=0.
