### ISSUE TITLE
[18USA] Suggestion: minor tile inventory edits

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#11026]
This could be 1 (one) NY tile and 4 (four) B tiles.

<img width="260" alt="Screenshot 2024-07-09 at 00 40 34" src="https://github.com/tobymao/18xx/assets/8732435/25c25158-2a2f-4ccf-b07d-e851b6fcf01d">

**Comment by benjaminxscott** [comment]
I don't think we need to explicitly limit the metropolis (B) or NY tiles since the logic only allows those to be placed as appropriate. We could show a limit, it's just a no-op

Technically all tiles are unlimited
