### ISSUE TITLE
[1822] Game incorrectly requests player consent to upgrade a London-adjacent tile

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#11031]
https://18xx.games/game/166759

I tried to upgrade L37 from green to brown, and I got the popup asking me to confirm that the owner of the 16 consented to the upgrade.  The rules do not require any consent for upgrading London-adjacent tiles.  The only limitation is on laying yellow tile in hexes adjacent to London.

"6.1.5 The six unbuilt hexes around London are reserved for the adjoining companies and cannot have a yellow tile placed on them
without the agreement of the director or concession holder of the respective company. If the company that controls such a hex has
no director or concession holder, then a tile may only be laid if it connects the associated London station to existing track. **There
is no restriction on upgrading these tiles once placed**."

**Comment by ddaybell** [comment]
This happened at time 13:29 (Pacific time), 7/14/-2024

**Comment by michaeljb** [comment]
Nice catch, thanks for reporting this!

**Comment by ddaybell** [comment]
Happy to help!
