### ISSUE TITLE
[18GB] Better text for LB

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#11039]
> The owner of the LB has priority for starting the LNWR. No other player may buy the Director's Certificate of the LNWR, and the owner of the London & Birmingham may not buy shares in any other corporation until they have purchased the LNWR Director's Certificate.

This should also say that the private blocks hex F21 (Birmingham) while open.

**Comment by ChrisTheCat** [comment]
GN blocks I18
SD blocks I12
LM blocks F15
AF blocks K2
LS blocks H21

**Comment by slapphappyjazz** [comment]
As the designer, I agree with this suggested enhancement of the online implementation.
