### ISSUE TITLE
[1822] Value of Tax Haven subtracted from different player in Entities view

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#11040]
1822

https://18xx.games/game/166816#entities
vs
https://18xx.games/game/166816#spreadsheet

Matt C's total is different in these two views, and appears to be reduced by the Tax Haven (which is owned by a different player.

**Comment by philcampeau** [comment]
Issue also reported in these bug reports with additional detail

#11107

> There seems to be a weird bug related to the Tax Haven, depending on the order of screens viewed. I think something got broken after the recent bug fixes in this area.
> 
> See this current game:
> (https://18xx.games/game/167967?action=1318) and go to the Spreadsheet tab.
> 
> Note the total player values, L to R:
> 3926, 5712, 1123, 4680, 4955. These are correct. NY_NAFO owns the tax haven (value $604).
> 
> Now click to the Entities tab, and then click back to the Spreadsheet tab.
> The player values (other than the TH owner) have changed - and the difference is the value of the Tax Haven!!
> 3322 (-604), 5108 (-604), 519 (-604), 4076 (-604), 4955 (OK - he owns it).
> 
> The only way to recover the correct values seems to be to refresh the page in the browser.

#11158

1822 CA
Gid 166232

> The Tax Haven Private is subtracting its value from all other players that are not its owner. It adds it value correctly to its owner. I just noticed this as one of the players has a negative total value (he had a bit of an issue with trains and loans) after paying off his loan, having some cash in hand and owning 5 shares.
> He did have a loan carry over some one SR in to the next set of ORs, paying the interest.
> I can't say for certain when this crept in or if it always had this and went unnoticed.

**Comment by waaayback** [comment]
Is this bug ever going to be fixed? I’ve been playing several games of 1822CA lately and this issue is very annoying. It’s still broken, for example see current game #179414.

**Comment by ChrisTheCat** [comment]
Writing to confirm we see the same problem in our game of 1822NRS.

<img width="1275" alt="Screenshot 2024-10-10 at 16 02 07" src="https://github.com/user-attachments/assets/a4bd93a9-0834-4a6d-8583-56056d25290c">
<img width="1249" alt="Screenshot 2024-10-10 at 16 01 48" src="https://github.com/user-attachments/assets/9bb2715b-4c5f-4446-91d0-554863cb3965">

**Comment by michaeljb** [comment]
> Is this bug ever going to be fixed? I’ve been playing several games of 1822CA lately and this issue is very annoying. It’s still broken, for example see current game #179414.

Yes.
