### ISSUE TITLE
Default auto-routing to "on".

### ISSUE THREAD

**Issue by branidal** [tobymao/18xx#11045]
It would be nice to set auto-routing to "on" by default.

I think that most people actually prefer this, as it speeds up the game significantly, and can anyway be done in the cloned games, even if it's not on for the actual game. However, I think many players forget to click it and then cannot change it once they realize and the game has started. This especially applies to newer players, who often benefit the most from the feature.
It should ofc still be possible to leave it off it that is preferred.

**Comment by benjaminxscott** [comment]
It's a contentious issue

https://github.com/tobymao/18xx/issues/8241

**Comment by fanman80** [comment]
I'd prefer such an enhancement to be player specific.  So a player could "opt-in" as a preference on the player's profile rather than a default for everyone.  I prefer to not use auto-routing, and I would find having to turn it off every time I created a game annoying.

**Comment by scottredracecar** [comment]
User-specific option to opt-in to default autorouting on setup seems
reasonable.

**Comment by michaeljb** [comment]
Opt-in in player settings was added in #11890, I forgot to link this issue when I made that PR.
