### ISSUE TITLE
[1856] Upgrade or Downgrade of Towns not available in Phase 5 (only 6)

### ISSUE THREAD

**Issue by rjaey** [tobymao/18xx#11043]
https://18xx.games/game/170343

For example, in Phase 5 WR should have been able to downgrade M18 but it's not possible.

According to the rules, "In phases five and six, single and double small city tiles may be upgraded or downgraded."

The upgrade was possible in phase 6, however.

**Comment by philcampeau** [comment]
Where you're likely getting confused is that the rules for 1856 refer to phase 1 as the 2 trains, phase 2 as the 3 trains, and so on. Phase 5 in the rules is when the first 6 train is sold.

**Comment by rjaey** [comment]
Thanks for the explanation, i was not aware of that. But then the chart in the info tab is wrong, it states phase 5 as when the first 5 train is bought onwards and i was going by looking at the chart.

<img width="668" alt="image" src="https://github.com/user-attachments/assets/be800ed4-c39a-4090-a5d6-5cc0c43fca12">

**Comment by philcampeau** [comment]
The site aligns the phase names with the trains, the rule book doesn't.
