### ISSUE TITLE
[1822PNW] Combining private abilities not working: e.g. Dit Crusher and Coal Tile

### ISSUE THREAD

**Issue by BrianBankler** [tobymao/18xx#11049]
Game ID -- hs_niuekuaw_1721570195 (Hotseat)

In the game, I acquired and used Dit Crusher and the coal company in the same OR by the same company. (CPMS). I used the coal company, then realized I had meant to also use ditcrusher. I undid, acquired both, crushed the dit, but then the coal company would not place (red error bar, "cannot place coal company" or some such text). I undid the dit crushing, then the coal company worked but when I tried to crush the dit it failed. After some trial and error, I just undid everything and simply acquired the dit crusher (planning on doing the coal company the next OR). I apologize that I didn't grab the game state at this time but only thought of submitting a bug a bit later. So the gist link is a bit later on in the game.

https://gist.github.com/BrianBankler/785c33c14b76675bbbc7b90ef966e87d

**How to Reproduce the Bug?**

1. Acquire Coal Company and Dit Crusher in same OR by same company (May also work with other multiple acquisitions, don't know).
2. Crush dit (should work)
3. Add coal company (fails)
4. Undo crushing dit, add coal company (works)
5. Crush dit fails

**Comment by fanman80** [comment]
Maybe I'm misunderstanding what you mean by "the coal company," but to me it means Private 19 the Rockport Coal Mine.  If you are referring to the Rockport Coal Mine, then you may be misunderstanding its use.  The special abilities for this private clearly states "No other private company bonus can combine with this one" (see Private Companies table, page 33.  So the game not letting you combine the coal mine with the dit crusher is a correct enforcement of the rules.

Moreover, I don't see how these two could combine even if allowed by the rules in that I don't see any dits in the hexes on which the coal mine could be placed.  The special abilities text for the coal mine on page 33 says "Use this private company to place the Rockport Coal special city tile (PNW4) in any mountain hex."  I see six dits which are adjacent to mountain hexes on which the coal mine may be placed, but non actually on a mountain hex.  So I don't see any reason to try to combine these abilities even if allowed by the rules.

**Comment by fanman80** [comment]
Also, the special abilities for the Rockport Coal Mine state "This tile lay replaces a company's normal build actions for the turn."  This means a company may not make any other build action on the turn it places the special tile.  Using the dit crusher happens with a build action, either laying a yellow tile or upgrading a tile.  So, per the rules, a company may not place the coal mine tile on the same turn as using the dit crusher.

Again it seems that the rules are being enforced correctly.

**Comment by BrianBankler** [comment]
Ah, then I misunderstood. I think we played it wrong during a F2F game. I apologize for the inconvenience.
