### ISSUE TITLE
Db container problem on CentOS

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1105]
Did try to get 18xx.games developer site started on a CentOS installation.

When trying to do "make dev_up_b" the 18xxgames_db_1 container fail to start.
(Gets a chown error for /var/lib/postgres/db)

@jenf trouble shooted this one and found out that there is a different default user ID on CentOS.

So by changing line 12 in db/Dockerfile to use the actual user id of the user instead of the default 1000, removing the containers and then retry it worked.

So it would be good to use the actual userid of the user starting the container instead of a hardcoded one.

**Comment by benjaminxscott** [comment]
Is this still an issue?

**Comment by tobymao** [comment]
let’s close it won’t get fixed

**Comment by perwestling** [comment]
Yes it is still an issue. I have a local commit that I apply to the branches I use on CentOS, and I will continue to use.

My reason for having this issue was two fold:
- Maybe it would be fixed someday?
- Anyone that encounter this problem could find the issue, and then also the solution
