### ISSUE TITLE
[18 India] Can't lay home token on OO hexes

### ISSUE THREAD

**Issue by bennettn404** [tobymao/18xx#11058]
https://18xx.games/game/171575?action=215

When EBR first operates, it lays its home OO tile on P17. Once the tile is laid, a prompt to select the home city from the 2 OO options comes up. When attempting to click on either city, the page gives an error and force refreshes and rolls back the action. Both myself and the owner in master mode had the same behavior. 

126.0.6478.128 (Official Build) (64-bit)

**Comment by JaySixA** [comment]
The same problem in game 171572 with the EIR (same starting hex as EBR).

**Comment by philcampeau** [comment]
Looks like this affects all corps starting on OO hexes. Presumably any starting on hexes with more than one individual city. 

I did a quick test, this doesn't happen in hotseat mode, so @EdPovi, make sure you're testing on a real game.

**Comment by waaayback** [comment]
Thanks for fixing this quickly.  Can we get this pushed to the website?  I think this is holding up every game of 18 India LOL

**Comment by philcampeau** [comment]
It's not fixed, I was just identifying where the problem seems to be.

**Comment by ZakisanGithub** [comment]
> Looks like this affects all corps starting on OO hexes. Presumably any starting on hexes with more than one individual city.

In our game, did not come up for OO/Mumbai cities where only one Company was located, but it did occur when two companies in the placed OO tile were in the game.

https://18xx.games/game/171615

**Comment by charliewilsonstaindrop** [comment]
For completeness (?) we have the same issue in game #171527 where both SPD and NWR are railway companies in the game.

**Comment by Adac27** [comment]
It make it a bit easier to reproduce: Of the 2 OO hexes, in our game (#171481), Delhi had only 1 company starting on it, but Kolkata had 2. The company starting on Delhi was able to place fine. It was only when a company starting in Kolkata tried to place did we run into this bug.

**Comment by MatthewDeKoning** [comment]
But caught in the act in game 171671
Cloning the game works fine. 
master mode / normal moves in the live game fail when choosing home station.

**Comment by waaayback** [comment]
Will the 18 India bugs be assigned soon (especially this one)?  The game isn't really playable yet.

**Comment by EdPovi** [comment]
I have a fix going up *soon* (tm)

**Comment by waaayback** [comment]
cool,thanks!

**Comment by fanman80** [comment]
I'm in [https://18xx.games/game/171946](url) which is just starting SR 2, both Dehli companies (NWR and SPD) are not only in play but also ran in OR 1.1 & 1.2.  Dehli now has a brown tile.
