### ISSUE TITLE
[18 India] - label does not appear in the label list

### ISSUE THREAD

**Issue by charliewilsonstaindrop** [tobymao/18xx#11067]
- Browser Version
  - Edge
- Platform (Mobile, Tablet, Desktop)
 - Desktop

-->

**Comment by benjaminxscott** [comment]
Could you clarify? A label on Github? on the site?

**Comment by charliewilsonstaindrop** [comment]
Hi
 
Sorry for not being clearer.  In the labels shewing which game or general 
function the report appears some have used [18India] and others [18 India].
In the pop-up list (for searching) only [18India] exists so there is no way to 
see reports that have been labelled [18 India].
 
Hope that makes sense.
 
All the best
Charlie Wilson
"From the Sea, Freedom."

 

----- Original Message -----
From: Benjamin Scott ***@***.***>
Reply-To: tobymao/18xx 
***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author 
***@***.***>
Sent: 26/07/2024 21:34:29
Subject: Re: [tobymao/18xx] [18 India] - label does not appear in the label 
list (Issue #11067)



Could you clarify? A label on Github? on the site?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by charliewilsonstaindrop** [comment]
Sorry even then I forgot to say on GitHub. <duh>
 
All the best
Charlie Wilson
"From the Sea, Freedom."

 

----- Original Message -----
From: Benjamin Scott ***@***.***>
Reply-To: tobymao/18xx 
***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author 
***@***.***>
Sent: 26/07/2024 21:34:29
Subject: Re: [tobymao/18xx] [18 India] - label does not appear in the label 
list (Issue #11067)



Could you clarify? A label on Github? on the site?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by benjaminxscott** [comment]
Ah so those labels in the title are user-supplied, we put the official GH labels on issues once they're triaged. It's volunteer driven so there's no SLA on that :D

You can filter on a given tag btw

https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3A18India

If it hasn't gotten a GH label yet it will show up as `needs-triage`
https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3A%22needs+triage%22
