### ISSUE TITLE
Unable to import hotseat game

### ISSUE THREAD

**Issue by ollybh** [tobymao/18xx#11064]
It is no longer possible to import a JSON game file. Attempting to do this gives an error:
```Uncaught title: undefined method `title' for nil```

The error is occurring here:
https://github.com/tobymao/18xx/blob/edc5f9e1b9ad202232e4e7d896fcbd74cc7d0050/assets/app/view/create_game.rb#L411

Reverting commit a0ced7ac74 makes it possible to import hotseat games again.

[CC @benjaminxscott]

**Comment by benjaminxscott** [comment]
Ah does that need a safe navigation operator?

-_Ben

**Comment by ollybh** [comment]
That might be it. I just reverted the whole commit to get the game import working again, I didn't try looking for a proper fix.

**Comment by benjaminxscott** [comment]
I tested a patch locally that reverts the guard clause to the same one as before, and getting an error that the submit function isn't defined, so that's weird
