### ISSUE TITLE
18CZ B9 Hex preventing none ATE token placement

### ISSUE THREAD

**Issue by BasiBoyX** [tobymao/18xx#11088]
[18CZ]]  preventing none ATE token from being placed on B9 - despite a token space being available

Game ID 171153

https://18xx.games/game/171153

Operating SZ I had upgraded B9 to brown sold a company to make sure I had at least 100 in the company - but I was unable to place a token on B9 - being told 'SX cannot lay token - remaining token slots are reserved on B9'

I did have a simllar issue on a previous round when B9 was a green tile - though I just assumed at the time a speciifc station ws reserved for ATE

I will probably roll the sale of the company back that I did to make sure I had the money for the token - so that the game can continue

Browser - Fire fox on both Android (v14 X200XXS3DXD5/X200OXM3DXB3)  and PC (Windows 10)

**Comment by philcampeau** [comment]
I suspect this is the same issue that affected 1880 in issue #8871 . The hex is reserved for ATE, because before brown, ATE should have the choice between which of the two cities it will occupy. Once the city is brown though, they're merged and it's irrelevant. 

I'll submit a fix soon.
