### ISSUE TITLE
[18Neb] Bankrupt player dropped as entity

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#11089]
A player bankrupted in our game.  Username disappeared from the entities and was excluded from the results.

https://18xx.games/game/172287

**Comment by benjaminxscott** [comment]
I think this is working as intended, when a player goes bankrupt it sets the `bankrupt` flag and they no longer show up as 'active' in any of the places in the UI that would be relevant. We could change that UI logic, but I'm not super sure that would add enough value to justify potentially causing other bugs by making that change
(i.e. oops we show a bankrupt player in a UI dialogue so now another bug is possible)

https://github.com/tobymao/18xx/blob/master/lib/engine/game/base.rb#L682C45-L682C53
