### ISSUE TITLE
[1841] Can par IRSFF at 216 in SR1

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#11098]
The 216 par value shouldn't be available until greens. https://18xx.games/game/166750?action=73

**Comment by roseundy** [comment]
Where are you seeing this in the rules? Major corps can always be parred at 68, 100, 144, 216 and 340.

**Comment by crericha** [comment]
I based it off of the stock market space being green. In the 49 implementation (Vellani's other game), the space color matches the phase the par is allowed in, so made the assumption that's how 41 worked. Checked the rules based on your comment and you are correct, that rule did not carry over to 41. Closing the issue. I do recommend changing the color used for the `major only` par prices, so they aren't confused with phase.
