### ISSUE TITLE
[18Mag] Game does not load

### ISSUE THREAD

**Issue by amartinsola** [tobymao/18xx#11099]
**What's your Game ID?**

https://18xx.games/game/167816

**How to Reproduce the Bug?**

I chose to use Itsvan during OR of company 4. Then the game does not load at all. 

**Which Browser / Platform?**
The same with PC/Firefox and iOS/Safari

**Comment by amartinsola** [comment]
Related to issue #10980

**Comment by benjaminxscott** [comment]
dupe https://github.com/tobymao/18xx/issues/10980

seems to be the same issue where call stack is exceeded
