### ISSUE TITLE
There is no visible scroll thumb on the game log frame.

### ISSUE THREAD

**Issue by dmitton42** [tobymao/18xx#11093]
[**What's your Game ID?**]
https://18xx.games/game/172066
https://18xx.games/game/171368

**How to Reproduce the Bug?**
Open an game and look

**Which Browser / Platform?**

Chrome Version 127.0.6533.89 (Official Build) (64-bit)
PC Windows 10

**Comment by benjaminxscott** [comment]
This seems to be a limitation in chrome, as they've implemented 'overlay scrollbars' which only show up on hover and are tiny (see vid). For clarity, this behavior is entirely client-side

The workaround I see is to *disable* this flag in chrome, which brings back the wider ones that are always visible

chrome://flags#overlay-scrollbars

[Screen recording 2024-08-03 9.54.45 PM.webm](https://github.com/user-attachments/assets/0efe0a3c-6bc9-47a7-866c-f7ad0a5c06d1)
