### ISSUE TITLE
Issue #105 closed but not fixed in the ongoing game (#75)

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#111]
Hi Toby, don't know whether my other message will reach you as you closed the issue. But I put a new comment in the closed #105 issue on laying track. Thanks for your help.

**Comment by tobymao** [comment]
i got the original message. thanks so much for your efforts!

**Comment by tobymao** [comment]
please don’t touch this game i will look at it soon. you have some complex track!

**Comment by Spobster** [comment]
Great, it works. Nice fix, thanks!
