### ISSUE TITLE
[18USA] Allowed to bid higher than my bid power

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#11100]
https://18xx.games/game/170012?action=261

TheCat has bid power 105 (a private worth 90 and 15 cash) but is allowed to bid 111 on this company.

<img width="1318" alt="Screenshot 2024-08-03 at 15 42 17" src="https://github.com/user-attachments/assets/dbdfe4e6-b028-4964-87f8-2e24ee14c82e">

**Comment by crericha** [comment]
You can bid higher because of the $30 subsidy on the starting hex.
