### ISSUE TITLE
18India - token in OO city issue

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#11109]
**What's your Game ID?** https://18xx.games/game/172738

**How to Reproduce the Bug?**

OR1.1 SPD has placed the OO tile in Delhi. Now trying to place it's home token. When I do this I get a "The server did not accept this due to []...refreshing" red bar and the page refreshes.  This happens on both my Macbook (running Firefox) and Phone (using Safari).

Shots from game:
![Screen Shot 2024-08-09 at 9 06 10 am](https://github.com/user-attachments/assets/f7674bb7-72b9-4f67-b042-e89a56c0f804)
![Screen Shot 2024-08-09 at 9 06 29 am](https://github.com/user-attachments/assets/bed8b037-5399-492f-b233-79f315767371)

Shot of error message
![Screen Shot 2024-08-09 at 9 06 42 am](https://github.com/user-attachments/assets/98462279-667b-400a-afb6-c9b46d72648c)

Firefox version:
![Screen Shot 2024-08-09 at 9 07 11 am](https://github.com/user-attachments/assets/a346e317-62d2-4b12-bcfb-c89950da40c6)

Thank you :)

**Comment by fanman80** [comment]
This looks like: [https://github.com/tobymao/18xx/issues/11058](url)

**Comment by philcampeau** [comment]
yeah, looks like the code hasn't been deployed to the site since July 22. This issue was been fixed on the back end.

**Comment by philcampeau** [comment]
But yes, this has been resolved by #11058 and will be fixed when the code is deployed. Closing this report as fixed.

**Comment by Chrisozwa** [comment]
Thank you
