### ISSUE TITLE
[1849] Electric dream variant should require other variants to be in play

### ISSUE THREAD

**Issue by Adrianows** [tobymao/18xx#11116]
Example game:
https://18xx.games/game/173634

Running with only E-train variant but no bond or token purchase.

Section 14.3 of the AAGames rulebook states

> This variant, which can be used only with the other variant rules, allows you to explore the possibility of an earlier electrification of the Sicilian railway network.

This implies that the other variant rules should also be in play if Electric Dreams is selected.

It's possible to choose to play with all the variants as suggested by the rules or to select only Electric Dreams, which is not recommended by the designer.

**Comment by philcampeau** [comment]
Ha, missed that. 

I'll post the fix soon.
