### ISSUE TITLE
[18Neb] Initial OR was weird

### ISSUE THREAD

**Issue by jtamplin** [tobymao/18xx#11126]
**What's your Game ID?**

https://18xx.games/game/173873?action=34

**How to Reproduce the Bug?**

The first OR is supposed to run in reverse stock price order.  However, it shows UP as the first to operate.  Trying to place a tile resulted in a pink box (went away too quick to copy, but something about action blocked).  Then it went to CBQ's turn (the one that should have been operating), except the player operating it was getting a similar error.  Mark was able to master-mode the CBQ actions, and then everything seemed to operate properly.

If you back up into the stock round from there and go forward, you should see the problem.

**Which Browser / Platform?**

Chrome 127.0.6533.89, laptop

**Comment by crericha** [comment]
I implemented the operating order a different way. That may fix this.
