### ISSUE TITLE
Broken links to non-existent profile pages for non-player entities

### ISSUE THREAD

**Issue by MarcusBatty** [tobymao/18xx#11124]
https://18xx.games/game/172805#info

MarcusBatty

**Comment by ollybh** [comment]
This applies to other games with dummy players, such as Vaclav in the two-player 18CZ, and the robot player in the (under development) 1858 Switzerland two-player variant.

In all of these the dummy player is created with an ID value of -1, and the player card on the entities page includes a link to https://18xx.games/profile/-1. This link should be omitted for non-human players.
