### ISSUE TITLE
[18Neb] Local Railways should be limited to one train

### ISSUE THREAD

**Issue by jtamplin** [tobymao/18xx#11125]
**What's your Game ID?**

https://18xx.games/game/173873

**How to Reproduce the Bug?**

Try and buy trains with OLB or NK.  The game will let you buy a second, but you should only ever be able to own more than one.  You can discard a train to buy a new one if it is a different type and the company has the cash, so it should let you buy a train of higher type but discard the first one.

I'll need to add a clarification to the rules since it doesn't specifically say it there, but the components clearly show they may own 1 rusted train.

**Which Browser / Platform?**

Chrome 127.0.6533.89, laptop

**Comment by m4rt1n2d** [comment]
Here is a picture of a charter for a Neb minor.  It does say "may only own one rusted train"

https://boardgamegeek.com/image/744773/18neb
