### ISSUE TITLE
[18NY] Trains ending up in the bank pool from voluntary giving up of a train 

### ISSUE THREAD

**Issue by g18xxperson** [tobymao/18xx#11133]
**What's your Game ID?**
https://18xx.games/game/17166

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
As per the rules:

![image](https://github.com/user-attachments/assets/b33a080c-f2cb-430d-94d6-235dbf2aae4e)
