### ISSUE TITLE
[1822MX] FCM can access Acapulco (P23) and lay track there without a connection

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#11149]
In https://18xx.games/game/171948?action=507 FCM is able to upgrade O22 and P23 and then lay a token even though it has no route to these tiles. Interestingly, the rules for M24 are enforced correctly.

![image](https://github.com/user-attachments/assets/074798c6-0113-40a0-8fc2-2433f600d01b)

**Comment by philcampeau** [comment]
duplicate of #11148
