### ISSUE TITLE
[Steam Over Holland] Unable to enter game 174384

### ISSUE THREAD

**Issue by Enderwiggin3rd** [tobymao/18xx#11157]
Game 174384 will not load. Last action unable to be retrieved; screen stuck on “game loading” screen.

**What's your Game ID?**

(https://18xx.games/game/174384)

-->

**How to Reproduce the Bug?**

uncertain: game stopped loading on another person’s turn.

edit: wrong game number

**Comment by stateless** [comment]
Same issue. Right after trying to do a token that raised an error. Crashed immediately after the error when trying another UI action. 

https://18xx.games/game/174566

**Comment by dragonboyyyy** [comment]
Same issue in this game: https://18xx.games/game/174346

**Comment by lbleicher** [comment]
> Same issue in this game: https://18xx.games/game/174346

I am having the same problem with a game of SoH:
https://18xx.games/game/174358

And also a game of 18Uruguay
https://18xx.games/game/170573

**Comment by philcampeau** [comment]
@lbleicher I'd recommend creating a separate report for the 18Uruguay game.

**Comment by Aposky** [comment]
Same here https://18xx.games/game/175093

**Comment by philcampeau** [comment]
Because the new code hasn't been deployed yet. You can check on the About link to see when the last deploy was: https://18xx.games/about

**Comment by Enderwiggin3rd** [comment]
Oh thank you! I missed that!

**Comment by philcampeau** [comment]
Looks like all these games are loading now that the code has been deployed.

**Comment by stateless** [comment]
Yes. Working for me now.
