### ISSUE TITLE
Steam Over Holland - Unable to enter game

### ISSUE THREAD

**Issue by TallyAlex** [tobymao/18xx#11150]
**What's your Game ID?** https://18xx.games/game/174379

**How to Reproduce the Bug?**

**Which Browser / Platform?** desktop and mobile.  Android and Win 11 MSEdge

**Comment by philcampeau** [comment]
I don't have a solution yet, but I was able to load the game into my local server and see the error that's preventing it from loading at least: 

![image](https://github.com/user-attachments/assets/06cc3681-293a-4208-b828-37dee5f3a5b1)

I'll investigate this later tonight and this weekend. Thanks for the report!

**Comment by TallyAlex** [comment]
Add game 174384 - same symptom, cannot enter game
