### ISSUE TITLE
1822 CA tax haven value being subtracted from non-owners

### ISSUE THREAD

**Issue by akoewler** [tobymao/18xx#11158]
1822 CA
Gid 166232

The Tax Haven Private is subtracting its value from all other players that are not its owner.   It adds it value correctly to its owner.  I just noticed this as one of the players has a negative total value (he had a bit of an issue with trains and loans) after paying off his loan, having some cash in hand and owning 5 shares.
He did have a loan carry over some one SR in to the next set of ORs, paying the interest.
 I can't say for certain when this crept in or if it always had this and went unnoticed.

**Comment by philcampeau** [comment]
duplicate of #11040
