### ISSUE TITLE
[Steam over Holland] company can not run a route over the ferry while owing p3

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#11164]
https://18xx.games/game/174408

This is a similar bug to the one with being unable to run to Vlissengen while owning p4

**Comment by philcampeau** [comment]
So strange. All this stuff worked when I was playtesting locally. I'm working on the reports. Thanks for testing everything!

**Comment by darkotuskan** [comment]
As an added bug that I think is associated, in game https://18xx.games/game/174493, I was unable to buy Private P3 in to my company while having a route connected to the ferry (that also caused the game to hang)

**Comment by philcampeau** [comment]
I suspect that https://github.com/tobymao/18xx/pull/11166 will fix that issue as well, and possibly the other hung game reports as well.
