### ISSUE TITLE
3562 - game cannot be continued due to GameError: Step Lay Track cannot process

### ISSUE THREAD

**Issue by bootydharma** [tobymao/18xx#1116]
Reporting this error. Game data given below:

GameError: Step Lay Track cannot process {"type"=>"run_routes", "entity"=>"N&W", "entity_type"=>"corporation", "id"=>538, "routes"=>[{"train"=>"6-1", "connections"=>[["D12", "C11", "C9", "B8", "A7"], ["D12", "C13"], ["B14", "C13"]]}]}

**Comment by tobymao** [comment]
fixed
