### ISSUE TITLE
Play with full game in window (remove tabs/all tabs open)

### ISSUE THREAD

**Issue by jlunders** [tobymao/18xx#11174]
One nice feature could be to have the full game on screen at once in one window. Tabs are definitely useful on a small laptop, but for those with screen resolutions that can support it or who prefer scrolling over mouse-clicks or hotkeys, it would be really nice to see all tabs expanded together. 

I didn't see any other requests or related submissions. Apologies if I missed any, I imagine this isn't the first time it's come up.  Thanks! I love the site.

**Comment by tobymao** [comment]
sorry no plans to do this
