### ISSUE TITLE
18Uruguay - Not given the option of trading in a 4 for a D train

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#11173]
https://18xx.games/game/170955?action=756

In the above game, the WER has a 4 train, the 4D/D is up, the WER has over $750, but the WER is not even given the option of trading its 4 in for a D.

Rule 8.2.6 provides:

Additionally, it is possible for a company to exchange one
of their own trains for a D-train. The price is then
$750 instead of $950.

**Comment by philcampeau** [comment]
I [posted a question](https://boardgamegeek.com/thread/3357437/is-there-a-discount-on-4d-trains) on the BGG forums just to verify if the discount also applies to the 4D trains, which are available at the same time, or only to the Diesel trains. May as well get this information before submitting a fix.
