### ISSUE TITLE
1846 -- C&WI power not usable in an OR after it has been bought in.

### ISSUE THREAD

**Issue by JEBrosius** [tobymao/18xx#1117]
In a currently ongoing game (#4046), a player bought the C&WI into his corporation but did not try to exercise the power until a later OR.  At that point he was unable to exercise it, despite clicking on the text.  Another player used Master mode to try to help him and was also unable to do it.

I know that quite a few C&WI issues have been reported, but I don't see an open issue about this behavior.

**Comment by tobymao** [comment]
I'm not sure I see the issue

tsuk: All games of 1846 are the same...
IC buys Chicago and Western Indiana from JohnRDelaney for $60
Chicago and Western Indiana places token in D6 for IC

IC used C&I right there, so if you try to do it again obviously it won't work.

**Comment by JEBrosius** [comment]
We had to undo all the way back to the OR in which the IC bought the C&WI, buy it in right then, and then play from there.  Before we undid it, we had this problem.

**Comment by tobymao** [comment]
I just tried it with your game, undoing the lay, skipping an operating round.

GT passes buy trains
GT passes buy companies
JohnRDelaney operates IC
IC passes issue or redeem shares
Chicago and Western Indiana places token in D6 for IC

You expand the company, click on it, it should highlight, then click the token spot.
