### ISSUE TITLE
Site crashing frequently with 502 Bad Gateway

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#11193]
I am seeing a lot of 502 server errors. Everyone I've talked to is seeing them too. I'm used to these happen once in a blue moon, but today it's been as bad as every few minutes.
```
502 Bad Gateway
nginx/1.21.6
```

Repro: Unknown. I've seen it while:
-loading the main page.
-inputting a move
-submitting a message in game chat

**Comment by tobymao** [comment]
on what game do you see this?

**Comment by tobymao** [comment]
one of the web servers was down so the site was running at half capacity, i've brought it back up, please dm me if you see it again

**Comment by physic** [comment]
I personally was seeing it on the homepage and 1817. Others in the main chat reported seeing issues as well. Don't know which games.
