### ISSUE TITLE
[1846] Mark half-pays on the spreadsheet 

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#1119]
Currently full-pays and withholds are are marked on the spreadsheet, but half-pays are not.  Potential easy implementation suggestion--mark some of the numbers in the bright font?

**Comment by yzemaze** [comment]
How about underlining (wavy, dotted, dashed, solid?) and maybe reduced opacity? (same as withhold or somewhere in the middle?)
Just dashed:
![image](https://user-images.githubusercontent.com/33390595/87885018-d29dcb00-ca12-11ea-94f5-a4883f68b60b.png)

**Comment by TheExcalabur** [comment]
Somewhere in the middle would probably be best if three different levels are clear enough.

**Comment by yzemaze** [comment]
Just reduced opacity won’t work (light bg, visual impairments, row highlighting). There needs to be a more visually distinctive cue. Italic/bold would highlight too much, light font-weight doesn’t work either. Font or bg color could be one way, but an underline is way easier and should work independently of user defined color/bg.

**Comment by benjaminxscott** [comment]
@tobymao this change seems to have been reverted , which I presume is unintentional

**Comment by tobymao** [comment]
yep probably

**Comment by tobymao** [comment]
i can reopen the issue

**Comment by yzemaze** [comment]
> @tobymao this change seems to have been reverted (in a new game on the currently deployed app), which I presume is unintentional

There was no change to the code and It still works as it should:
![image](https://user-images.githubusercontent.com/33390595/91653087-90e65280-ea9d-11ea-94ec-e0323d741084.png)

Game id? OS, browser (incl. version)?

**Comment by benjaminxscott** [comment]
Sry I should have added those, only have access to mobile

Looks like on desktop chrome it works as expected but mobile Safari it doesn't

Game 7686
NYC half paid 12 total
![7F07A312-F56D-4F8C-97C6-D11C85818703](https://user-images.githubusercontent.com/1711810/91663376-39e07d80-ea9d-11ea-922f-aaff2442bffc.jpeg)


Safari:
Mozilla/5.0 (iPhone; CPU iPhone OS 13_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1
