### ISSUE TITLE
[18Uruguay] Game doesn't open

### ISSUE THREAD

**Issue by lbleicher** [tobymao/18xx#11194]
**What's your Game ID?**

The game https://18xx.games/game/170573 only shows a blank page when opened

Happens on any platform (Firefox on windows and linux, Chrome on an Android phone)

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by ollybh** [comment]
This game has already been pinned, so unfortunately this won't be fixable. This game will need to be archived.

**Comment by lbleicher** [comment]
Is there a way to do it outside of the game?
