### ISSUE TITLE
Cannot upgrade T4 to Diesel when company already has 2 trains (GameID #75)

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#112]
In OR 7.2, Takamatsu wants to upgrade the 4-train to a Diesel train. The corporation has enough cash after trains have ran, but the turn is immediately passed to the next corporation, probably because Takamatsu already has two trains (T4 and T6).

**Comment by Spobster** [comment]
Hi Toby, the fix almost works :) I can buy the Diesel train, but a notification in a red bar appears stating "It is not KO's turn". I can then finish my turn (or not), but as soon as I refresh the page (F5), then I the game is back at the point where I can buy the train. Can you check this as well please? Thanks!

**Comment by Spobster** [comment]
Actually, also if I don't buy the Diesel train and just pass, the game cannot continue. So we are stuck at this point in the game :)

**Comment by tobymao** [comment]
this one was tricky, client worked but server didn't fixed, try now

**Comment by Spobster** [comment]
Yes it works, great! Thanks :)
