### ISSUE TITLE
[18Ardennes] stuck at declaring bankruptcy

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#11203]
**What's your Game ID?**
https://18xx.games/game/176238

Game seems to be stuck as I have two corporations I started and I don't have money to start them both. When I press declare bankruptcy I get error: "Wrong number of arguments given"

[gist](https://gist.github.com/l33twash0r/85c268eabc6b5e7d16bb1757582b6ba7).

**Comment by l33twash0r** [comment]
Still getting the same error on the same game.

**Comment by ollybh** [comment]
> E: now its fixed. Site was updated just now I guess.

Yep. The timing of the issues being closed can be a bit confusing. The issue is closed when the fix is added to the main code base, but this code might not be deployed to the 18xx.games server for a few days.
