### ISSUE TITLE
Can't lay new tiles in game 2274

### ISSUE THREAD

**Issue by jftaylor21** [tobymao/18xx#1121]
KU has 86 yen and want to lay a straight tile on H11 which costs 80 yen. However, the game is not showing any tile options when I click on it. The game will let me upgrade other tiles. The problem seems limited to laying new tiles.

See game 2274.

**Comment by jftaylor21** [comment]
I am able to lay a new tile with NBDS in 3834 so this doesn't affect all games.

**Comment by yzemaze** [comment]
Just refresh your browser. @jenf has already fixed this issue and layting a tile on H11 works over here.

**Comment by jftaylor21** [comment]
Thanks, I confirmed that it works now.
