### ISSUE TITLE
Feature request - Allow expanding market or include operating order information on charters

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#1122]
Sometimes enough company tokens can end up on a space on the market to obscure them. Operating order can be important to know during the stock round. If the space on the market could be expanded or the current operating order included on the charters would clear things up.

![image](https://user-images.githubusercontent.com/67166181/87886880-3f927000-c9d5-11ea-9a5d-8fec959f39b2.png)

**Comment by yzemaze** [comment]
Like these?
![image](https://user-images.githubusercontent.com/33390595/87978345-8d3fd300-cad0-11ea-8cf7-7f8ab833a92c.png) ![image](https://user-images.githubusercontent.com/33390595/87978504-caa46080-cad0-11ea-882e-93598fd727d8.png)
… or sth. else? (mock-ups preferred)

**Comment by jenf** [comment]
This looks resolved.
#883 covers the stock market
