### ISSUE TITLE
[18Ardennes] Unable to issue shares after in second operating round and beyond

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#11221]
6.2 Issuing Treasury Stock
Except in its very first turn of operations, a Public Com-
pany may issue one or more Treasury shares to the Open
Market and receive their  Current Market Value from the
Bank. Each time a Company issues Treasury stock in this
step, its Current  Market  Value moves one space down in
value for each share sold. A Company that has Treasury
stock may issue it to the Open Market  in any Operating
Round.

This doesn't seem to be implemented at all from what I can see?

**Comment by ollybh** [comment]
Ugh. I'd completely missed that rule. My excuse is that I don't recall ever seeing shares issued in F2F games.

**Comment by BellmakerSA** [comment]
I didn’t notice until another person pointed it out so no worries!

**Comment by WayneWWms** [comment]
Same issue in 183663.  When no one else buys your stock it's the only way to buy a 2nd permanent train.....
