### ISSUE TITLE
18ESP - game id 177789 will not load

### ISSUE THREAD

**Issue by SharpDressedDan** [tobymao/18xx#11222]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by SharpDressedDan** [comment]
Game ID is 177789.  Game will not load.   When I try to enter the game, the loading screen comes up, but the game never actually loads.

**Comment by philcampeau** [comment]
Here's the error in the browser console, for whoever ends up working on this bug:
![image](https://github.com/user-attachments/assets/777ffe7e-29f4-47c8-972f-7e7d2c85e6ef)

**Comment by philcampeau** [comment]
Actually, I just ran a test. This bug is fixed by https://github.com/tobymao/18xx/pull/11189, which is already merged into the master. As soon as the code is updated on the site, this will be resolved.
