### ISSUE TITLE
1858 Swiss with Robot: buying SBB shares

### ISSUE THREAD

**Issue by Dave4B** [tobymao/18xx#11228]
1858 Switzerland 2-player with Robot player.
After permanent trains have come out, a human player can buy 50% of the stock in SBB and become the Director.
Then the company appears to be over train limit and must discard all of its trains!

**Comment by ollybh** [comment]
@Dave4B when you find bugs in stuff I've got in development on my super-secret server, can you please raise issues on my Github repository? It's likely to confuse things over here.
This has been fixed by commit ollybh@10887d301

**Comment by Dave4B** [comment]
@ollybh I'm pretty sure this was raised from your s-s server, which seems to down at the moment, so the "report" link from there may be pointing to the wrong part of Github.
