### ISSUE TITLE
[18ESP] "undefined method `hex_by_id' for nil" when attempting to lay down track

### ISSUE THREAD

**Issue by RedNick** [tobymao/18xx#11237]
**What's your Game ID?**
https://18xx.games/game/176521

**How to Reproduce the Bug?**
1st operating round of the game
Trying to lay track for a minor company: get error "undefined method `hex_by_id' for nil" when confirming the track lay

![image](https://github.com/user-attachments/assets/9efa2136-ce5b-4816-8d85-3cd211f6ff5e)

**Which Browser / Platform?**
Not browser bug, but using Firefox on Windows

**Comment by ViennaTramways** [comment]
The same here:
https://18xx.games/game/179395
