### ISSUE TITLE
1858 not allowing  7E on dual gauge track 

### ISSUE THREAD

**Issue by romulin6** [tobymao/18xx#11239]
**What's your Game ID?**

178936

**How to Reproduce the Bug?**

I trying for over 24 hours to run a 7E train in company A I hit Auto it does nothing then I get message this page is slowing down Firefox to speed up your browser stop this page.

**Which Browser / Platform?**
Firefox

**Comment by philcampeau** [comment]
Game 178936 is a game of 1856. Could you double check your game id?

**Comment by romulin6** [comment]
should be 177538




Regards, Brian A. RobinsonE-Mail ***@***.*** MOPAR OR NO CAR

 

    On Tuesday, September 24, 2024 at 02:21:51 PM EDT, philcampeau ***@***.***> wrote:  
 
 


Game 178936 is a game of 1856. Could you double check your game id?

**Comment by philcampeau** [comment]
So the issue here is just that the auto routing failed? I looked at the game and I was able to select a route manually.

**Comment by romulin6** [comment]
I tried selecting manually it won't let me. 




Regards, Brian A. RobinsonE-Mail ***@***.*** MOPAR OR NO CAR

 

    On Wednesday, September 25, 2024 at 09:50:22 AM EDT, philcampeau ***@***.***> wrote:  
 
 


So the issue here is just that the auto routing failed? I looked at the game and I was able to select a route manually.

**Comment by ollybh** [comment]
When did you have this problem – what operating round was it, and which company were you trying to select the route for?

And what was the route that you were trying to select but unable to do so?

As the wiki describes (https://github.com/tobymao/18xx/wiki/Auto-Routing#performance) you are likely to get poor performance with auto-routing when maps like this get lots of track on them and there are huge numbers of possible routes for trains. But there are no known problems with manually routing trains in 1858, so we will need more information from you so we can reproduce this problem.

**Comment by romulin6** [comment]
Operating round 7.1 (of 2) company A the OR before A had a 5E and 7E the % used 5 but the 7 only used 2 MZA bought the 5 fem A. A placed some brown tiles with dual track. then it hung up and got message page is slowing down Firefox  and i had to hit stop before I could do anything after being unable to get it pick route I hit submit with 0 just to keep the game going.




Regards, Brian A. RobinsonE-Mail ***@***.*** MOPAR OR NO CAR

 

    On Thursday, September 26, 2024 at 04:28:56 PM EDT, Oliver Burnett-Hall ***@***.***> wrote:  
 
 


When did you have this problem – what operating round was it, and which company were you trying to select the route for?

And what was the route that you were trying to select but unable to do so?

As the wiki describes (https://github.com/tobymao/18xx/wiki/Auto-Routing#performance) you are likely to get poor performance with auto-routing when maps like this get lots of track on them and there are huge numbers of possible routes for trains. But there are no known problems with manually routing trains in 1858, so we will need more information from you so we can reproduce this problem.

**Comment by ollybh** [comment]
I don't have any problems manually routing the 7E train, so I'm closing this issue. I suspect that the autorouter was still running when you were trying to select the route, and blocking the interface.

This does appear to be a case where the auto-router performance is pathologically bad. The auto-router *should* timeout if it's taking too long (by default after 30 seconds), but this is performing so badly that it doesn't get to the timeout check for a long, long time.
