### ISSUE TITLE
[18 India] Game will not proceed

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#11230]
https://18xx.games/game/179114. We cannot get the game to proceed.  Any action that is attempted results in the error shown [below.]
![Screenshot_20240920_165538](https://github.com/user-attachments/assets/935d9877-362b-45c4-aff2-7254fb1ee7b5)

**Comment by philcampeau** [comment]
Duplicate of https://github.com/tobymao/18xx/issues/11097
