### ISSUE TITLE
[1862] System allows company to keep four trains in phase G and H after a late merge.

### ISSUE THREAD

**Issue by Quedak** [tobymao/18xx#11232]
**What's your Game ID?**

https://18xx.games/game/176127

This is the step when companies L&D and N&E merge. They each have two trains, and the merged company should only be allowed to keep 3 of the trains:
https://18xx.games/game/176127?action=667

But as can be seen in this action L&D has kept all 4 trains and is runni ng them.
https://18xx.games/game/176127?action=717

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by BellmakerSA** [comment]
Train limit is only for buying new trains in 62, you are never require to discard down due to a merger.
