### ISSUE TITLE
18Ardennes - Error when declaring Bankruptcy - Game ID 178882

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#11247]
Under the Declare Bankruptcy button, the text is
JoMa needs at least 280 F to start Königlich Bayerische Staats-Eisenbahn but can only raise 125 F.

When the Declare Bankruptcy button is pressed, the error message at the top of the screen says:
Illegal Action:  Wrong number of arguments (given 2, expected 1)... refreshing

The link to the game is  https://18xx.games/game/178882

-->

**Comment by ollybh** [comment]
Duplicate of #11203.
