### ISSUE TITLE
[1861-2p variant] - Limit of 60% when starting company from President's cert

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#11246]
https://gist.github.com/OedipussyRex/12f275387a952a6373a4c057968ecbaf

When starting a Major Company from the President's certificate, not from converting or merging minors, the game limits the player to only 60% ownership instead of the 70% allowed in the 2-player variant. In subsequent stock rounds a seventh share is allowed, but not in the stock round when the Major is parred.

**Comment by ollybh** [comment]
This only occurs when a major company has been nationalised and then is restarted. It is defaulting to a maximum 60% player ownership, not the 70% that is allowed in two-player games.
