### ISSUE TITLE
[18ESP] I cannot lay a track tile - undefined method 'hex_by_id'

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#11248]
Game 179389.

MH company has its turn. When you lay a track tile on its home base the following message arose: "undefined method 'hex_by_id' for nil". The program doesn't allow to lay this tile. I cannot know if the bug is only in that hex or will continue with the following laying track actions.
The game is stopped for several days, waiting for continuing. 
I reported the bug to the original programmer and he fixed it, but he told me it was necessary an update on 18xx.games server, and that he wasn't able to do it because the server is not his server.
Could any of you update the code with the fixed code asap, please? 
Thank you so much,

Enrique (designer of 18ESP).

**Comment by philcampeau** [comment]
This was fixed with #11244
Will be implemented with the next site update.
