### ISSUE TITLE
1844 allows less revenue to activate mountain railroad which is not correct

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#11251]
Please fill out the bug report title with the game name and description
Allows less revenue to activate mountain railroad
1844 - For people who can usually make multiple moves during Chicago evenings

What's your Game ID? 180281
https://18xx.games/game/180281

I bought the mountain railroad for the hex near Zurich and the GB has a route to it with a 2H train.  We are still in the yellow phase so the value of the mt rr is only 10.  I wasn't sure if trains need to run for maximum revenue so I selected the route being Goldau-MtRR for 30 instead of Goldau-Aldorf for 40, and it was allowed.  The text then said the MtRR was activated.  I had double thoughts that this shouldn't be allowed, so I checked the rules, and indeed it is not allowed.  So I made correct routes.  Specifically on page 13 of the rules: "The revenue claimed must be the highest total revenue that any player can show. You may not claim less revenue in order to activate a Mountain Railway or tunnel."

**Comment by philcampeau** [comment]
Unfortunately, this one might not be fixable. While running for the highest total revenue is a fairly common rule in 18xx, the only way to enforce it would be to require users to always use Auto-Run.

**Comment by ollybh** [comment]
Enforcing running for maximum revenue is not technically possible, this has to be enforced by the players.

**Comment by pzieske** [comment]
Yes, I see that problem.  Of course, when Ohley created 1844 he wasn't
figuring in that it would be running on computers in the future!
Paul
