### ISSUE TITLE
1848 info tab incorrect description of game end condition

### ISSUE THREAD

**Issue by MarcusBatty** [tobymao/18xx#11255]
Info tab states game ends at completion of next complete set, but that is only true if the bank breaks during SR.  If the bank breaks during OR, the current set is completed and the game ends.  This is implemented correctly.

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by MarcusBatty** [comment]
I guess the use of the word complete threw me.  Am I the only one getting
tripped up by this phrasing?

**Comment by philcampeau** [comment]
This phrasing was set about 3 years ago, has been used throughout the site, and this is the first report about it. So I guess so.
