### ISSUE TITLE
[steam over Holland] Werkspoor private power 

### ISSUE THREAD

**Issue by cw67q** [tobymao/18xx#11262]
https://18xx.games/game/180045

**What's your

https://18xx.games/game/180045

https://18xx.games/game/180045?action=314

This is a relatively minor bug that has to start at this point. The Werkspoor private provides a 10% discount on train purchases. The currently available train is a 5T costing 400 (360 with discount).

If I do not issue any shares run and payout the company has 384 in treasury ie enough for a train. But there is no option to buy.

OTOH if I issue 1 share and run as above I have 499 in treasury and I am offered the chance to buy the 5T for 360.

I should be able to buy the train without having the full price of 400. But the game doesn't seem to recognise that I have enough cash in the first scenario. The game applies the discount *but only if I have the full cost available at the point of buying*

We have just gone ahead with the game, it's not a huge deal for this play. But I think this might be a minor bug in the implementation.

I am using Chrome on a Google Pixel 4a. 

Cheers, Chris

**Comment by cw67q** [comment]
My apologies, one of the other players in our game just told me this issue had already been noted.

https://github.com/tobymao/18xx/issues/11163

**Comment by philcampeau** [comment]
duplicate
