### ISSUE TITLE
[1846] 3/5 train incorrect payout

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#1127]
The run of the 3/5 train of IC gets a fawlty payout when running over Port Huron (which somehow gets prioritized over Toledo).
I made a gist with the following number. 

gist:6bbecab69d3d2fc3d069e4f0debc0daa

Is this enough info?

**Comment by tobymao** [comment]
i believe this is a dup

**Comment by Spobster** [comment]
It may be yes, although in the other post, it was probably related to the meatpacking company. So maybe this is not the same issue.
