### ISSUE TITLE
[System18: Britain] Cannot upgrade Glasgow to green

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#11273]
Hotseat game:

KKN wants to upgrade Glasgow to green #53 tile, but cannot. May be something to do with the bit of track running NW off the map?

https://gist.github.com/ianwilson156/21374e1fd2adca28aa0c414e90969396

**Comment by ianwilson156** [comment]
OK. I was hoping to avoid having to renumber all the hexes, to add in another row at the top, but unfortunately it looks like we'll have to do that.

**Comment by roseundy** [comment]
Is that strictly necessary? It seems to me that the purpose of hex numbering is:

1. for reference in the log
2. for reference in play-by-mail/email games

In neither case is a reference to the stub required.

**Comment by scottredracecar** [comment]
It's okay for Steve (18xx.games) and me (future physical edition) to not
renumber this. Ian may need to renumber for his 18xx-maker file though. I
don't know if the workarounds for "negative" numbering are as robust for
18xx-maker.

**Comment by ianwilson156** [comment]
The problem is that it is a lettered row, not a numbered column, so there isn't a letter before "A".

**Comment by scottredracecar** [comment]
18xx.games has a way to deal with negative letters and I can just leave it
off.

**Comment by roseundy** [comment]
![S18_Britain_Spike](https://github.com/user-attachments/assets/8607974b-bee5-4b8b-92c5-1ea31b4e9cd4)
