### ISSUE TITLE
[System18 Britain] Wrong price for 2nd token

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#11274]
For those companies which start with one token on the map (KKN, GFN, SPX & PGS), the 2nd token is shown as costing 100 but it should be only 40, as per standard System18 rules.

**Comment by roseundy** [comment]
I broke this when I originally coded it up with tokens starting on the map. Easy fix.

Also, I'm changing the "cost" for the 2nd tokens of DGN and PHX to zero, to make it clear that the corp doesn't pay for the second token that gets placed automatically on their first OR.
