### ISSUE TITLE
1822CA Eastern Scenario Tax Haven bug

### ISSUE THREAD

**Issue by woodfeld** [tobymao/18xx#11278]
I came across this in my game today - it allowed me to buy 2 shares with the Tax Haven private. Unless I’m mistaken, this shouldn’t be possible.

18xx.games/game/176517

Tax Haven has 1 share of GT and 1 share of QMOO

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by woodfeld** [comment]
Looks like this can happen in the Western Scenario too 

18xx.games/game/176518

**Comment by michaeljb** [comment]
In 1822CA the Tax Haven is allowed to buy one share per SR, and only own one share per company. This is also available as an official variant for 1822 Great Britain's Tax Haven.

See the P11 row of the table on page 37 of the 1822CA rules, and rule 11.1.2 on page 28 of the 1822 Great Britain rules.

**Comment by woodfeld** [comment]
Except I was able to buy a 2nd share with it
