### ISSUE TITLE
Express trains - bypassing small cities ?

### ISSUE THREAD

**Issue by Morris-X** [tobymao/18xx#11283]
Playing in game 182071.  It says in rules "The permanent trains ... they may optionally skip small cities" (Page 8, column 1, paragraph 6, lines 1 and 3.)  How do you get that to work ?  Spent several minutes hitting 'Undo' and 'Clear Train', no joy.

Using Waterfox G6.0.20

https://18xx.games/game/182071

**Comment by philcampeau** [comment]
By small cities, it means towns. The site will automatically include towns in your route until you include enough cities that it needs to start skipping towns. There is no reason to skip towns unless you aren't hitting the full number of cities.
