### ISSUE TITLE
[18Carolinas] Bankrupt companies restart with power already available.

### ISSUE THREAD

**Issue by Hawke** [tobymao/18xx#11292]
Rule not respected: “The company’s shares, tokens, par price, and other markers are reset to be as they were at the beginning of the game and this company is available to be restarted during the next stock round.”

**What's your Game ID?**

https://18xx.games/game/183146

When CAR is restarted, it starts with the train power it had previously.

**Comment by rmroc451** [comment]
Car reflects @ 21:53

**Comment by roseundy** [comment]
Timestamps aren't useful.
Action numbers are:
https://18xx.games/game/183146?action=372

**Comment by rmroc451** [comment]
> Timestamps aren't useful. Action numbers are: https://18xx.games/game/183146?action=372

Didn't know that was a thing, thanks for pointing that out.
