### ISSUE TITLE
18EU - 180050 Final Exchange Round

### ISSUE THREAD

**Issue by 18xxPlayer** [tobymao/18xx#11299]
I have #12 and am connected to my company in Berlin via Hamburg but it will not give me that option.
How do I achieve that? I left a message asking the other players but no answer.

18xxPlayer

**Comment by philcampeau** [comment]
If you click on the Charter for GSR, do you not see a button saying **Exchange 12 for Treasury Share**?

![image](https://github.com/user-attachments/assets/2aa0fef8-c2e8-49de-aed9-2489a88a591c)

**Comment by 18xxPlayer** [comment]
Thank you - solved.I am a newbie to this site
18xxPlayer    On Wednesday, October 23, 2024 at 06:55:22 PM GMT+1, philcampeau ***@***.***> wrote:   

 


If you click on the Charter for GSR, do you not see a button saying Exchange 12 for Treasury Share?

image.png (view on web)
