### ISSUE TITLE
Lake Shore Line can upgrade to green tile before Phase 2

### ISSUE THREAD

**Issue by JacCCMF** [tobymao/18xx#1130]
{
  "id": 4428,
  "description": "Live 46: in 2 hours or less Monty/Akado/Jac one open spot? ",
  "user": {
    "id": 24,
    "name": "Jac"
  },
  "players": [
    {
      "id": 523,
      "name": "MontyBrewster71"
    },
    {
      "id": 24,
      "name": "Jac"
    },
    {
      "id": 529,
      "name": "Akado"
    },
    {
      "id": 648,
      "name": "starchitect"
    }
  ],
  "max_players": 5,
  "title": "1846",
  "settings": {
    "seed": 1.620502458385741e+38
  },
  "status": "active",
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    529
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 1,
      "company": "MS",
      "price": 60
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 2,
      "message": "glhf"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 3,
      "message": "ditto"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 4,
      "message": "hi everyone! we have a great group here "
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 5,
      "message": "good luck, have fun!"
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 6,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 7,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 8,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 9,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 10,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 11,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 12,
      "company": "TBC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 13,
      "company": "Pass (2)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 14,
      "company": "Pass (4)",
      "price": 0
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 15,
      "message": "this will be interesting =)"
    },
    {
      "type": "bid",
      "entity": "Jac",
      "entity_type": "player",
      "id": 16,
      "company": "MC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "pass",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 19,
      "message": "forced a 3rd private 😢"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 20,
      "message": "ouch"
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "bid",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 23,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 24,
      "message": "Let's play a game of \"Whose company will have two owners by OR1\".  I love this game!"
    },
    {
      "type": "par",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 25,
      "corporation": "NYC",
      "share_price": "80,0,8"
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 26,
      "message": "I almost bought both MS and Big4. had the chance.... decided that was a bad idea."
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "par",
      "entity": "Akado",
      "entity_type": "player",
      "id": 28,
      "corporation": "IC",
      "share_price": "100,0,10"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 29,
      "message": "i wanted the Ick but akado could steal it "
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 30,
      "message": "i’m so broke "
    },
    {
      "type": "par",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 31,
      "corporation": "PRR",
      "share_price": "100,0,10"
    },
    {
      "type": "buy_shares",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "NYC_1"
      ]
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 33,
      "message": "I'd have loved to have the NYC, but I don't want to get cut off by PRR again heh"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 34,
      "message": "decided to take the IC and starve Jac/star =/"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 35,
      "message": "Well, I appreciate it ;)"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 36,
      "message": "IC is also great for not needing as many shares bought...."
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 37,
      "message": "yep. you going to start a second?"
    },
    {
      "type": "par",
      "entity": "Jac",
      "entity_type": "player",
      "id": 38,
      "corporation": "GT",
      "share_price": "100,0,10"
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 39,
      "message": "I know you love the C&O"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 40,
      "message": "i love ICK and PRR personally "
    },
    {
      "type": "buy_shares",
      "entity": "Akado",
      "entity_type": "player",
      "id": 41,
      "shares": [
        "PRR_1"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "buy_shares",
      "entity": "Akado",
      "entity_type": "player",
      "id": 43,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "pass",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 45,
      "message": "$300 for everyone!"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 46,
      "message": "except monty"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 47,
      "message": "there's no East Coast Bias here"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 48,
      "message": "That's ok"
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 49,
      "hex": "C13",
      "tile": "7-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 50,
      "hex": "D14",
      "tile": "5-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 51,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "C13",
              "D14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 52,
      "hex": "G9",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 53,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 54,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "sell_shares",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 55,
      "shares": [
        "NYC_2",
        "NYC_3",
        "NYC_4"
      ],
      "percent": 30,
      "share_price": 70
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 56,
      "hex": "D18",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 57,
      "hex": "E17",
      "tile": "292-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 59,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 60,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 61,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 62
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 63,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 64,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "lay_tile",
      "entity": "LSL",
      "entity_type": "company",
      "id": 65,
      "hex": "E17",
      "tile": "294-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 67,
      "message": "Can you upgrade that already?"
    },
    {
      "id": 68,
      "type": "sell_shares",
      "entity": "IC",
      "shares": [
        "IC_1"
      ],
      "percent": 10,
      "entity_type": "corporation",
      "share_price": 90
    },
    {
      "id": 69,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 70
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 71,
      "message": "I think its not enforced that we need to be in green"
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 72,
      "hex": "J4",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 73,
      "hex": "H6",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 74
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 75,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 76,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 78
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 79
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 80,
      "message": "wait "
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 81,
      "message": "did someone buy a 3"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 82,
      "message": "is that a bug"
    },
    {
      "type": "message",
      "entity": "starchitect",
      "entity_type": "player",
      "id": 83,
      "message": "I think so. LSL currently doesnt enforce the tile restriction"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 84,
      "message": "ohhhh, yeah that's a bug"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 85,
      "message": "who want to report it "
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 86,
      "message": "lol"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 87,
      "message": "someone whose turn it isn't"
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 88,
      "message": "You know, I didn't event think about that."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 89,
      "message": "we willing to go back and not do it this OR?"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 90,
      "message": "or jus play on"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 91,
      "message": "go back it’s not been long "
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 92,
      "message": "and green isn’t out "
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 93,
      "message": "okay, monty want to undo back to just before you used LSL?"
    },
    {
      "type": "message",
      "entity": "Jac",
      "entity_type": "player",
      "id": 94,
      "message": "let me copy data "
    },
    {
      "type": "message",
      "entity": "MontyBrewster71",
      "entity_type": "player",
      "id": 95,
      "message": "I'm willing to go back"
    }
  ],
  "loaded": true,
  "created_at": 1595273514,
  "updated_at": 1595274807
}

**Comment by jenf** [comment]
Looks related to a special, we probably don't enforce upgrades on the specials properly.
Lake Shore Line lays tile #294 with rotation 0 on E17

https://www.18xx.games/game/4428?action=65

**Comment by PedroRCSequeira** [comment]
half related, i noticed you can upgrade the cleveland Z to a regular green. didnt test if it works the other way around

**Comment by pstone1** [comment]
Had the same problem here: https://www.18xx.games/game/4667?action=337 Played a bit forward and then realized what had happened and needed to revert, once upgraded to a regular green Cleveland cant be upgraded again to a Z brown.

**Comment by michaeljb** [comment]
This was fixed once, maybe there's a clue here in how to re-fix it - https://github.com/tobymao/18xx/pull/990

**Comment by tobymao** [comment]
@perwestling touched this piece i think

**Comment by perwestling** [comment]
Yes, I think my change caused this problem. I will have a look at it.

**Comment by perwestling** [comment]
@tobymao: The change I made, was to add a 
`return true if special_lay`
at line 208 in lib/engine/tile.rb

This makes it possible for a company to upgrade a tile even though all checks BUT COLOR is skipped in `upgrades_to?`.
On line 205 a check that the new tile is in the right upgrade color (in this case green, to the city yellow tile).

So it must be something else.

But I think there might be other problems with my change. Now it is possible to put down a tile (allowed by the ability) on a hex which does not honor pre-existing track.
So I think line 221 (that check paths_are_subset_of? should be moved up before line 208.

I can try to look into the bug of this issue - but as I have very little knowledge about 1846 I might struggle a bit.

Can you assign this ticket to me, @tobymao ?

**Comment by perwestling** [comment]
The remaining checks (label, towns count, city count) still needs to be there, as these should be possible to override.

**Comment by perwestling** [comment]
Have verified fix on latest master. Can be closed.
