### ISSUE TITLE
18ESP too many tokens (opened again because it was closed without fixing)

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#11300]
Hello,

Yesterday I received this mail from ollybh: Closed https://github.com/tobymao/18xx/issues/11271 as completed via https://github.com/tobymao/18xx/pull/11282.
However, the bug still persists. 

In all 18ESP games, all major companies (Northern and Southern) have two available station tokens and four locked station tokens. Rules states THREE locked station tokens. Each unlocked station token is available when the company achieve any goal they have, and there are only three goals.
So three goals = three locked/unlocked tokens, in addition to the two available station tokens that there are at the beginning, for a total of five station tokens, instead of six.
So one locked station token must be removed.
Thanks and regards,

Enrique (designer of 18ESP).

**Comment by philcampeau** [comment]
The code has been merged into the master, but the master hasn't been deployed to the website yet. The issue should be resolved the next time the code is deployed. 

You can verify the latest deployment date here: https://18xx.games/about
