### ISSUE TITLE
[System18] Game stuck

### ISSUE THREAD

**Issue by Aposky** [tobymao/18xx#11306]
We played async System18 Great Britain scenario. Game is stuck on "Loading game..." and cannot be open in any browser.

https://18xx.games/game/181999

**Comment by ollybh** [comment]
This game had a previously discarded train being bought. That should not have been allowed (discarded trains should be removed from the game), and was broken when this behaviour was changed by #11275.

This game (and others similarly affected) was supposed to be archived when that code was deployed, but I messed this up at the time. It has now been archived.
