### ISSUE TITLE
[1822CA: Eastern Regional Scenario] Tiles T14

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#11329]
Tile T14 is wrong
on 18xx.games
![image](https://github.com/user-attachments/assets/572df403-dacc-407e-a089-3c55e57c2958)
Winniepeg must be an end point

But on physical copy
![image](https://github.com/user-attachments/assets/564852c6-c565-48d4-9f59-9c04dd892780)
Sorry for unclear photo
Winniepeg is not an end, you can enter Winniepeg from SE and leave at NE and enter Vanconver.

**Comment by philcampeau** [comment]
@scottredracecar can you confirm?

**Comment by scottredracecar** [comment]
Comment seems correct. I think the idea is that you can still run through Winnipeg to get to Vancouver.
