### ISSUE TITLE
Spreadsheet tab could track the phase of each OR

### ISSUE THREAD

**Issue by DatBrute** [tobymao/18xx#11328]
**What's your idea?**

Add a row to this spreadsheet 
![image](https://github.com/user-attachments/assets/6e02e7d1-40b3-42d3-ad49-d171cbe948c7)
or a column to this spreadsheet
![image](https://github.com/user-attachments/assets/dedc8e5d-2d5a-4fbf-b89a-b600c655f3a6)

which states the last phase achieved during that OR/SR. This would help players get a feel for how long the 2 trains were in play.

(I am a programmer with limited relevant experience, let me know if you would like me to give a shot at implementing this)

**Comment by philcampeau** [comment]
@DatBrute go ahead and give it a try!

**Comment by DatBrute** [comment]
Well, like most open source, I'm afraid I don't know how to build the project. So I could take a while guess, but couldn't confirm it did anything.

This was all I could find. https://github.com/tobymao/18xx/wiki/Developing-for-18xx.games

**Comment by roseundy** [comment]
Are you on the 18xx.games Slack? That's the best place to get advice on starting a dev environment.
