### ISSUE TITLE
18Ardennes not allowing buying of more expensive train with mandatory train buying (6.8.3).

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#11330]
https://18xx.games/game/183663

 6.8.3: Note that unlike in other games a Company in a mandatory train buying situation is never required to buy a less expensive train in lieu of a more expensive train, even if the Company would have sufficient funds to buy the less expensive train without performing an Emergency Money Raising.

BE has no train but is not being given the option of buying a 4D.

**Comment by WayneWWms** [comment]
https://18xx.games/game/183663

 6.8.3: Note that unlike in other games a Company in a mandatory train buying situation is never required to buy a less expensive train in lieu of a more expensive train, even if the Company would have sufficient funds to buy the less expensive train without performing an Emergency Money Raising.

**Comment by ollybh** [comment]
BE is a 5-share company. Only 10-share companies are allowed to buy 4D trains.
