### ISSUE TITLE
1822 PNW uses £ instead of $ in description of ability

### ISSUE THREAD

**Issue by tduchow** [tobymao/18xx#11339]
**What's your Game ID?**
https://18xx.games/game/184672

**How to Reproduce the Bug?**
Go to the info page and scroll down to the "Acquire a minor from bidbox" description.

**Which Browser / Platform?**
Chrome 130

**Comment by philcampeau** [comment]
There were actually a couple of instances where it showed up. I submitted the fix.

![image](https://github.com/user-attachments/assets/e524bc04-e157-4bbf-9f0b-4836dc56a571)

**Comment by tduchow** [comment]
Thanks! Felt nitpicky but nice to see the consistency.
