### ISSUE TITLE
Corporation charter crowded in entities view

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#1133]
Hello.

We had this situation where PRR (already having 1 extra token) had bunch of trains which caused the elements to overflow.

Perhaps it might be worth considering to have trains be displayed in 2 rows after certain amount of characters is met.

![image](https://user-images.githubusercontent.com/64785010/88036394-295af000-cb4c-11ea-917c-8ca4fc7dded2.png)

**Comment by michaeljb** [comment]
This will also apply to games where corporations can end up with many tokens, like 1817 and 18CZ. Maybe a separate row for tokens?
