### ISSUE TITLE
[18RoyalGorge] Gold Miner private also works as 2 ghost shares for CF&I, this should’t

### ISSUE THREAD

**Issue by jantref** [tobymao/18xx#11355]
https://18xx.games/game/186486

This private should only pay dividend for VGC for two ‘ghost shares’ but it does also for CF&I. According to the rules it shouldn’t and now it gives the owner too much advantage.

**Comment by michaeljb** [comment]
Thanks for reporting this! I've got the fix in, and your linked game and other impacted games have been pinned.
