### ISSUE TITLE
[18Texas] Map

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#11351]
serveral map tiles is different from physical copy

H19: Lafayette only get 2 exit
![WhatsApp 圖片2024-11-1600 02 51_96f4f3a5](https://github.com/user-attachments/assets/13a73824-797e-42cb-b6ae-a4821ede6d65)
![image](https://github.com/user-attachments/assets/b58a967d-70de-4f87-9506-a733849cb3ce)

M8: Corpus Christi is 30/50, not 20/40
![WhatsApp 圖片2024-11-1600 03 05_3950362b](https://github.com/user-attachments/assets/720e9878-8acb-426a-aed5-3237d47941b6)
![image](https://github.com/user-attachments/assets/ac920a49-dba4-4c03-a34e-00f414fefe1e)

H5: West of Austin get no terrain fee 
![WhatsApp 圖片2024-11-1600 02 59_3ec507bf](https://github.com/user-attachments/assets/460e9ed5-f917-42f2-95a5-06783d8f816b)
![image](https://github.com/user-attachments/assets/93177cf9-0458-4b8e-9775-e79ad09ae6d9)

**Comment by philcampeau** [comment]
@scottredracecar presumably these changes are official at this point?

**Comment by scottredracecar** [comment]
The printed map is final.
