### ISSUE TITLE
Allow users to change their user name

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1135]
At the moment one user has their email address as their user name. They might want to be changing it, but the software won't allow it.

**Comment by tobymao** [comment]
this is difficult because user names are used as keys in actions

**Comment by jenf** [comment]
I think when a user changes names we add an alias into every game.
Bob changes to Bob2, then we update each of the games with Bob2 in so that Bob2 aliases to Bob.
This could also be used to replace players in a game, as I think a few people are finding a lot of dropouts

**Comment by jenf** [comment]
{"seed": 5, "aliases": {"Bob2": ["Bob"]}}

game would take the list of aliases so any reference to Bob it treats as an action by Bob2

**Comment by jenf** [comment]
After we've migrated players to use ids, we'll need to add functionality to allow players to change names.

I'd was thinking of adding a setting stating the last time they changed their name, and disallow changes for 60 days (or unless they bug an admin). I'd rather discourage changing names too often as it might cause confusion to other users.
