### ISSUE TITLE
1817 Volatility (184503) - Station subsidy not giving to company $50 when converted from 2 to 5 share

### ISSUE THREAD

**Issue by akoewler** [tobymao/18xx#11378]
When converting from a 2 share to a 5 share company in Merger/Conversion 1.1, the company owning the Station Subsidy does not receive $50.  When passed through to the start of the next OR it still has not received the $50.

**Comment by ollybh** [comment]
When A&S converts from 2-share to 5-share it must buy an additional token for $50. The station subsidy private has paid for this token: at [action 307](https://18xx.games/game/184503?action=307#entities) A&S has one token, two loans and $10. After converting at [action 308](https://18xx.games/game/184503?action=308#entities) A&S has two tokens, two loans and $10. It would have had to take a loan to pay for the token if it did not own the station subsidy private.
