### ISSUE TITLE
value miscalculation

### ISSUE THREAD

**Issue by ChrisBa59** [tobymao/18xx#11384]
re Id: 185265 1822+

the moment one player (here ramanraj) buys the last CR share the value of my portfolio (Chrisba) and also that of rr1 decreases exactly in the amount of CR share price (245) whereas the other player`s values remain unchanged. 

I checked my value and indeed there are now 245 missing..

Any idea why?
Thanks, Chris

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by michaeljb** [comment]
Opselo owns the tax haven which has a share of CR, so this is another occurrence of #11040. Closing this as a duplicate issue.
