### ISSUE TITLE
[1822Africa] Auto router doesn't know E train can re-use track

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#11381]
The auto router runs both trains on separate track.

![Screenshot 2024-11-26 at 2 17 53 PM](https://github.com/user-attachments/assets/e5ce8a65-cf29-4b74-978d-ea54383093ad)
![Screenshot 2024-11-26 at 2 20 08 PM](https://github.com/user-attachments/assets/e743808e-7fe8-4c65-a175-6b30558c1dbd)

**Comment by vandamm** [comment]
Okay so I think I've addressed it in my PR. Will be fixed after it's merged
