### ISSUE TITLE
1858 quick start variants not working?

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#11399]
**How to Reproduce the Problem?**

When creating a new game of 1858, the Quick start variants are displayed but can't be selected. 

**Which Browser / Platform?**
115.18.0esr (64-bit) on a Mac Book

Thank you :)

**Comment by ollybh** [comment]
This is a slight quirk with the 18xx.gsmes game creation page. Both of the quick start variants are only valid for a player count of three to six players, but when creating a new game the default player range is two to six players. If you increase the minimum number of players you will be able to choose these variants.

**Comment by Chrisozwa** [comment]
Thank you Oliver. And thank you again for programming 1858
