### ISSUE TITLE
Implementing 1835 on 18xx.games

### ISSUE THREAD

**Issue by MadFedor** [tobymao/18xx#11398]
A suggestion that might help make coding move.

Bill Stoll ran an 1835 PBEM for a long time, and has a code base for running the game, including code for train routes. Firefox deems this linked site as a security risk. Bill has several links there which might help you.. https://web.oocities.org/timessquare/arena/Arena/5276/depot/1835p.htm

Bill's code base: https://web.oocities.org/timessquare/arena/Arena/5276/depot/1835mpg.htm
It worked very well for the several PBEM games I played with Bill as host.

As I recall from 25 years ago downloading his code, it is written in C.

**Comment by philcampeau** [comment]
Getting 1835 onto the site is less a coding question and more of an interest question. The permission was granted 4 years ago, but the dev(s) who was working on the game [abandoned](https://github.com/tobymao/18xx/issues/3059) the project some time ago. 

Either way, the coding done in C won't really help to implement the game on a site coded in Ruby that has an entire framework already constructed under it.
