### ISSUE TITLE
1858: ongoing issue with "action not accepted, refeshing"

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#11407]
**How to Reproduce the Problem?**

It's not always happening, but sometimes I've been getting the problem. It's been occurring at random intervals through the game.  It does stop, but not sure why...I try refeshing the screen, reloading etc. Sometimes works, sometimes not. Game ID is 186045. Screenshot of the most recent example of the error message is attached.

**Which Browser / Platform?**
Safari on an iPhone 11 running IOS 18.1.1

- Platform (Mobile, Tablet, Desktop)
Mobile, not tried on desktop.

![image_123655411](https://github.com/user-attachments/assets/7ecf681a-1900-4970-90ae-0d59b598a783)

**Comment by philcampeau** [comment]
This is a duplicate issue, first reported here: #11372
