### ISSUE TITLE
[1840] tram not getting Prater bonus

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#11404]
https://18xx.games/game/189049

Tram should be running for $160 not $140

![IMG_8044](https://github.com/user-attachments/assets/ad9188e4-3991-43a7-9912-98f3e0219aa3)
![IMG_8045](https://github.com/user-attachments/assets/76fc3914-1177-4a49-a340-9c1d645c21f8)

**Comment by philcampeau** [comment]
Looking at the history, Prater was still owned by you, and not your tram company. According to the rules, you only get the bonus if your tram company owns the private: 

![image](https://github.com/user-attachments/assets/942eaab8-86ee-461b-9578-3b7a221c4d6e)

Buying in the private fixes the revenue: 

![image](https://github.com/user-attachments/assets/ea0c7049-7856-4e93-ae20-d8b919f15e43)
