### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by chiahsuan-tsai** [tobymao/18xx#1144]
One of our players accidentally clicked "leave game" and that ended up corrupting our game data.

Here's the game ID: 4517

![image](https://user-images.githubusercontent.com/37878383/88123266-8a101a00-cb98-11ea-8c04-6f3196279ba4.png)

**Comment by chiahsuan-tsai** [comment]
Here's the game data.

[4517.txt](https://github.com/tobymao/18xx/files/4957305/4517.txt)

**Comment by jenf** [comment]
Dup of #1102
