### ISSUE TITLE
Game 4348: We're sorry this game cannot be continued due to GameError: Not a buyable train

### ISSUE THREAD

**Issue by wademoore** [tobymao/18xx#1152]
Game showing:

`We're sorry this game cannot be continued due to GameError: Not a buyable train
Please raise a bug report and include the game id (4348) and the following JSON data`

I've attached the json for the game.

[4348.txt](https://github.com/tobymao/18xx/files/4967298/4348.txt)

**Comment by wademoore** [comment]
Update..

After a few minutes it just has this in the chat log, but the game appears to work:

`----
Your game was unable to be upgraded to the latest version of 18xx.games.
It is pinned to version c3bdb617, if any bugs are raised please include this version number.
----`

**Comment by jenf** [comment]
Refresh, your game is now pinned. See  #1092 for why.

**Comment by wademoore** [comment]
> Refresh, your game is now pinned. See #1092 for why.

Yup - looks good.  Fairly new so the first time I ran into this - thank you for following up!
