### ISSUE TITLE
Hide other players private companies by default

### ISSUE THREAD

**Issue by Bobsson** [tobymao/18xx#1153]
The "buying from another player" issue from #293 was fixed for trains, but is still the case for private companies.  Currently available ones are just listed under the map, with no clear distinction between yours and someone else's.  They should probably either be hidden (like trains) or just have a "confirm" checkbox on other players' companies which you can't click the "Buy" button until you check.  Either way, it should be able to just be a UI change.

**Comment by jenf** [comment]
@tobymao I was thinking we should add confirm as a step and actions now for trains, companies and when we get to it mergers.
