### ISSUE TITLE
Can't run routs to/from/through Chicago

### ISSUE THREAD

**Issue by Nate-Mg** [tobymao/18xx#1159]
Playing B&O in Id: 4324.

I've tried placing a new token there, various track upgrades. It's not working for some reason.

**Comment by jenf** [comment]
Looks like, maybe due to the tile reservation?

https://18xx.games/game/4324?action=205

**Comment by Nate-Mg** [comment]
Tile reservation? Is this something I can fix on my end?

**Comment by dfannius** [comment]
Note that you have to be careful to click right on the station in Chicago that you are running to, not elsewhere on the hex.

**Comment by Nate-Mg** [comment]
dfannius, I guess that was the issue. Thx.
