### ISSUE TITLE
1846: Priority Deal display during draft

### ISSUE THREAD

**Issue by cheesinglee** [tobymao/18xx#1162]
During the privates draft, the priority display indicator in the Entities tab as well as the turn notification email doesn't make sense to me. In this game, seating order is: 

`zabergau->cheesinglee->autumnweave->Arne->KennyB (forward order)`

On my (cheesinglee) turn in the draft, it shows that PD is on Arne. I figured OK, autumnweave did the last action, so I guess the PD is just being determined in forward order as if we were in a regular stock round. Then, after I complete my draft selection and check again, it shows that KennyB has PD, so something else is happening here. 

To me, what would make the most sense would be to just keep PD on the player who will act first in SR1 (zabergau in this case). 

Here is the game data exported after I made my first draft selection.

```{
  "id": 4583,
  "description": "private",
  "user": {
    "id": 611,
    "name": "cheesinglee"
  },
  "players": [
    {
      "id": 619,
      "name": "zabergau"
    },
    {
      "id": 611,
      "name": "cheesinglee"
    },
    {
      "id": 3209,
      "name": "autumnweave"
    },
    {
      "id": 612,
      "name": "Arne"
    },
    {
      "id": 277,
      "name": "KennyB"
    }
  ],
  "max_players": 5,
  "title": "1846",
  "settings": {
    "seed": 1.7366584916396344e+37
  },
  "status": "active",
  "turn": 1,
  "round": "Draft Round",
  "acting": [
    619
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "KennyB",
      "entity_type": "player",
      "id": 1,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Arne",
      "entity_type": "player",
      "id": 2,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "autumnweave",
      "entity_type": "player",
      "id": 3,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "cheesinglee",
      "entity_type": "player",
      "id": 4,
      "company": "C&WI",
      "price": 60
    }
  ],
  "loaded": true,
  "created_at": 1595447697,
  "updated_at": 1595617317
}```

**Comment by dfannius** [comment]
In 1846, player order for SR1 is determined randomly. Then player order for the private draft is the reverse of that. So KennyB was always going to go first in SR1.

The bug here is that we shouldn't move the priority deal label during the private draft since it's misleading.

**Comment by cheesinglee** [comment]
I may not have stated it explicitly enough, but the private draft began with KennyB, so PD for SR1 will be on zabergau.
