### ISSUE TITLE
[1846] Cannot payout if at top of Market

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#1163]
When clicking the pay out button, nothing happens because IC is already at the max stock price and so price cannot change. It should be able to pay out but not increase in price. Game continues as normal if IC witholds, so it seems to be the top of market issue. https://www.18xx.games/game/4737

**Comment by jenf** [comment]
Your probably the first to hit the top of the market :)

https://www.18xx.games/game/4737?action=697
