### ISSUE TITLE
{"error":"TypeError: Cannot read property '$freeze' of undefined"}

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#1166]
mini_racer.rb:209:in `eval_unsafe'
> rack_1   | JavaScript at Object.Opal.load (<anonymous>:2311:7)
> rack_1   | JavaScript at Opal.modules.view/home (<anonymous>:61152:8)
> rack_1   | JavaScript at constructor.Opal.require (<anonymous>:2339:17)
> rack_1   | JavaScript at Object.Opal.load (<anonymous>:2311:7)
> rack_1   | JavaScript at Opal.modules.view/chat (<anonymous>:61047:8)
> rack_1   | JavaScript at constructor.Opal.require (<anonymous>:2339:17)
> rack_1   | JavaScript at Object.Opal.load (<anonymous>:2311:7)
> rack_1   | JavaScript at Opal.modules.lib/settings (<anonymous>:62142:5)
> rack_1   | JavaScript at <anonymous>:62141:7
> rack_1   | JavaScript at <anonymous>:62108:103
> rack_1   | MiniRacer::SnapshotError: TypeError: Cannot read property '$freeze' of undefined

**Comment by tobymao** [comment]
delete your build files
