### ISSUE TITLE
Tapping towns on mobile makes them disappear

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#117]
iOS 13.3.1
Safari browser

I’m trying to pick my routes, and whenever I tap on a tile with a town, the dit disappears from the hex. Interestingly, it doesn’t do this with my 2T, only the 3T. It does it both on a yellow tile and on the grey town above UR’s home.

**Comment by tobymao** [comment]
cannot replicate this

**Comment by tobymao** [comment]
please reopoen if you can give me a reproducible xample
