### ISSUE TITLE
1846: MC and O&I allowing illegal tile lays

### ISSUE THREAD

**Issue by Qaimaqam** [tobymao/18xx#1173]
When purchased by a corporation, the MC and O&I allow you to build two free bonus tiles at any time in marked hexes. According to the game rules, if you lay both tiles using this power, they must connect to one another. 

In game 4811, the MC owner was able to lay two disconnected tiles in the MC hexes (two sharp curves, not connected to each other). We had them undo it, but this is against the game rules. You may lay one or both tiles in the hexes, but if you lay both, they must connect (also, if you choose to only lay one, I believe you don't get to choose to lay the other one for free on a subsequent operating round; it must connect and you must pay at that point). 

I tested this in a hotseat game and both MC and O&I were allowing disconnected tile-lays after the private was bought in. I believe in all instances I observed this behavior, it happened after the Buy Companies step (which is legal; you can have a corporation buy in a private and then exercise its power as the last part of an operating turn in 1846).

**Comment by michaeljb** [comment]
Relates to #885
