### ISSUE TITLE
allow/force player to sell stock in forc...WITHDRAWN

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#118]
In OR 5.2, an earlier D purchase has rusted the 4Ts. Player has no train, so is forced to buy a D. Error message says "<playername> has 639 and cannot spend 885" - shouldn't the player then be forced to sell shares (the minimum necessary) to get to 885 and their new D train?

**Comment by tobymao** [comment]
can you add a game i’d?

**Comment by tobymao** [comment]
did you try clicking on the corporation to sell shares?

**Comment by jchipr** [comment]
that works.
