### ISSUE TITLE
Game 3709

### ISSUE THREAD

**Issue by coryke** [tobymao/18xx#1180]
I believe DonaldTrumpDeclaresBankruptcy mentioned this in the chat on 18xx games. But I never saw a resolution to this.

This game (3709) will not load and has been hung up for about two weeks. Is there a way to resume the game or cancel it? I have no idea why it has hung up. I wish I could be more helpful on this.

Thanks.

**Comment by tobymao** [comment]
it's a pinned game

**Comment by coryke** [comment]
I don't know what that means in this context. Nevertheless, it has disappeared from my home screen. cheers!!

as a side note, what you've created with this is truly remarkable.

**Comment by tobymao** [comment]
thanks, i hope you're enjoying it.

In order to move forward and allow players to finish games, we've created a
pinning system. If new updates break existing games, they get 'pinned' to
an old version. These old versions are not maintained and are best effort.
