### ISSUE TITLE
Neutral Token Laying Issues

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#1188]
I was not offered the opportunity to place the free neutral token here (only have $36 so maybe that is why it skipped?--neutral are of course free to place)
https://www.18xx.games/game/4875?action=511

Also later in the game hit an error trying to lay a neutral token in J12 (although it let me do it in hotseat when I tried this just now)
https://www.18xx.games/game/4875?action=534

**Comment by jenf** [comment]
2 is fixed, 1 i'll sort later.
