### ISSUE TITLE
wonky cert # display WITHDRAWN

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#119]
The cert limit and display of number of certificates is mostly correct--and I found a place where it's a bit wonky...  In this scenario, the Iyo is down in yellow, so its certificates do not count toward the cert limit. This is handled correctly in most of the players, but not in one of them:
P1 AR* 60% TR 10% IR 10% ; display shows 6/11 correctly
P2 IR* 60% AR 20% KO 10%; display shows 3/11 correctly
P4 SR* 50% KU* 50%; display shows 8/11 correctly
P5 KO* 50% UR* 40% SR20% KU10% IR10%; display shows 10/11 correctly
P6 TR*50 UR20 SR20 KU/KO/IR/AR all 10; displays 11/11 correctly

P3 UR40 KU30 KO20 SR10 IR10 AR10; display wrongly shows 12/11

maybe because P3 does not own any presidencies?

**Comment by tobymao** [comment]
do you have a game i’d?

**Comment by jchipr** [comment]
game ID 120 has wonky cert numbers - two of the four companies are calculated/displayed correctly, and the other two are each incorrect (one appears to count a presidency as two shares; the other may have done that for one company but not the other??). Honestly, the numbers may have been wrong for a while; I wasn't paying much attention to them.

**Comment by jchipr** [comment]
MY APOLOGIES. I wasn't counting the private companies ... the app is correct.

**Comment by dfannius** [comment]
Glad to hear it! I was confused about what could be causing this.
