### ISSUE TITLE
1846: Lake Shore Line Extra upgrade not working

### ISSUE THREAD

**Issue by qwerlancer** [tobymao/18xx#1195]
I have found private company Lake Shore Line having following issue :

Current situation: When it has been purchased by a public company, it gives that company a 0 cost upgrade on Toledo or Cleveland BUT not an extra upgrade. It still counts as a tile-laying action.

Expected situation: When it has been purchased by a public company, it gives that company an extra 0 cost upgrade on Toledo or Cleveland.

Tested in both multiplayer and hot-seat environment.

**Comment by jenf** [comment]
Do you have a game id showing the issue?

**Comment by qwerlancer** [comment]
I believe it has been fixed. It works in my new game.
