### ISSUE TITLE
1882 first token is 40, rest are 100

### ISSUE THREAD

**Issue by mattroy** [tobymao/18xx#1198]
It looks like all the tokens are being priced at 40 instead of 40 for first 100 for rest.

**Comment by jenf** [comment]
@scottredracecar could you confirm?

**Comment by mattroy** [comment]
bottom of page 8 https://docs.google.com/document/d/1ERTlNSDpvj4Wd5Pbt21_j46hcH7xtS0_gOBGooBwIXs/edit#
