### ISSUE TITLE
82 - NWR event causes problems with previous route selector

### ISSUE THREAD

**Issue by WeeMadAndo** [tobymao/18xx#1199]
In game hs_gpynwduo_1595819106 (error'd out, can no longer access), post NWR runs on newly laid tiles in NWR spaces would generate a route but with a gap on that tile. Testing options showed that pressing on the destination space again would "reroute" (similar to in other circumstances) and fill the gap. This needed to be done with each subsequent run involving a re-laid tile as the gap in the route would return each time.

**Comment by jenf** [comment]
https://www.18xx.games/game/4891?action=132

**Comment by jenf** [comment]
New variant of this issue
18xx.games/game/4964
caused by having more than one possibility on the connections
