### ISSUE TITLE
Rule 8.1d route incorrectly paid through tokened hex

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#120]
In OR 3.1, TR traveling north into IR territory. App shows this payout: 
F9 F7 F5 F3 E2 F1 $110  //please excuse dollar sign for Yen sign
However, E2 hadn't yet been upgraded; had only one circle, which was tokened by IR. The route should not have been allowed

**Comment by jenf** [comment]
Fixed by #403 (Route is not connected)
