### ISSUE TITLE
Show button not obvious - might need improvement

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1201]
Created an 1846 multi player game to try to trigger issue 1130.
When doing that, I let PRR buy Lake Shore Line.
When I do Lake Shore Line appear as an aibility in the game.

But when I click on Show for that ability Steamboat Company appear....

I would have guessed that it should show the Lake Shore Line ability there...

{
  "id": 23,
  "description": "1130 take 2",
  "user": {
    "id": 5,
    "name": "a"
  },
  "players": [
    {
      "id": 5,
      "name": "a"
    },
    {
      "id": 9,
      "name": "a1@a.a"
    },
    {
      "id": 6,
      "name": "b"
    },
    {
      "id": 10,
      "name": "b1"
    },
    {
      "id": 7,
      "name": "c"
    }
  ],
  "max_players": 5,
  "title": "1846",
  "settings": {
    "seed": 2.3038643112949798e+38
  },
  "status": "active",
  "turn": 1,
  "round": "Draft Round",
  "acting": [
    7
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "c",
      "entity_type": "player",
      "id": 1,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "b1",
      "entity_type": "player",
      "id": 2,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "b",
      "entity_type": "player",
      "id": 3,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 4,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "a",
      "entity_type": "player",
      "id": 5,
      "company": "TBC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "c",
      "entity_type": "player",
      "id": 6,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "b1",
      "entity_type": "player",
      "id": 7,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "b",
      "entity_type": "player",
      "id": 8,
      "company": "SC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 9,
      "company": "MC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "a",
      "entity_type": "player",
      "id": 10,
      "company": "MS",
      "price": 60
    },
    {
      "type": "par",
      "entity": "a",
      "entity_type": "player",
      "id": 11,
      "corporation": "PRR",
      "share_price": "40,0,4"
    },
    {
      "type": "par",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 12,
      "corporation": "NYC",
      "share_price": "40,0,4"
    },
    {
      "type": "par",
      "entity": "b",
      "entity_type": "player",
      "id": 13,
      "corporation": "B&O",
      "share_price": "40,0,4"
    },
    {
      "type": "par",
      "entity": "b1",
      "entity_type": "player",
      "id": 14,
      "corporation": "C&O",
      "share_price": "40,0,4"
    },
    {
      "type": "par",
      "entity": "c",
      "entity_type": "player",
      "id": 15,
      "corporation": "ERIE",
      "share_price": "40,0,4"
    },
    {
      "type": "pass",
      "entity": "a",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "pass",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "pass",
      "entity": "b",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "b1",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "c",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "undo",
      "entity": "MS",
      "entity_type": "minor",
      "id": 21
    },
    {
      "type": "undo",
      "entity": "c",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "undo",
      "entity": "b1",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "undo",
      "entity": "b",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "undo",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "buy_shares",
      "entity": "a",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "PRR_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "NYC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "b",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "B&O_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "b1",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "C&O_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "c",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "ERIE_1"
      ]
    },
    {
      "type": "undo",
      "entity": "a",
      "entity_type": "player",
      "id": 31
    },
    {
      "type": "undo",
      "entity": "c",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "undo",
      "entity": "b1",
      "entity_type": "player",
      "id": 33
    },
    {
      "type": "undo",
      "entity": "b",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "undo",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "undo",
      "entity": "a",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "undo",
      "entity": "c",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "undo",
      "entity": "b1",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "undo",
      "entity": "b",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "undo",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "par",
      "entity": "a",
      "entity_type": "player",
      "id": 41,
      "corporation": "PRR",
      "share_price": "60,0,6"
    },
    {
      "type": "par",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 42,
      "corporation": "NYC",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "b",
      "entity_type": "player",
      "id": 43,
      "corporation": "B&O",
      "share_price": "90,0,9"
    },
    {
      "type": "par",
      "entity": "b1",
      "entity_type": "player",
      "id": 44,
      "corporation": "C&O",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "c",
      "entity_type": "player",
      "id": 45,
      "corporation": "ERIE",
      "share_price": "100,0,10"
    },
    {
      "type": "buy_shares",
      "entity": "a",
      "entity_type": "player",
      "id": 46,
      "shares": [
        "PRR_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 47,
      "shares": [
        "NYC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "b",
      "entity_type": "player",
      "id": 48,
      "shares": [
        "B&O_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "b1",
      "entity_type": "player",
      "id": 49,
      "shares": [
        "C&O_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "c",
      "entity_type": "player",
      "id": 50,
      "shares": [
        "ERIE_1"
      ]
    },
    {
      "type": "pass",
      "entity": "a",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "pass",
      "entity": "a1@a.a",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "pass",
      "entity": "b",
      "entity_type": "player",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "b1",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "pass",
      "entity": "c",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 56,
      "hex": "C13",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 57,
      "hex": "D12",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 58,
      "hex": "G9",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 59,
      "hex": "G7",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 60,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 62,
      "hex": "E19",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 63,
      "hex": "E17",
      "tile": "293-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 64
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 65,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 68
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 70,
      "hex": "D18",
      "tile": "8-2",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 72,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 73
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 74
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 75
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 76
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "buy_company",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 78,
      "company": "LSL",
      "price": 20
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 79
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 80
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 81
    },
    {
      "type": "buy_company",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 82,
      "company": "LSL",
      "price": 20
    },
    {
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 83,
      "city": "293-0-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 84
    }
  ],
  "loaded": true,
  "created_at": 1595848447,
  "updated_at": 1595848579
}

**Comment by michaeljb** [comment]
To see the Lake Shore Line's ability, you need to click on "Lake Shore Line". 

The "Show" button shows abilities from companies owned by other players. The Steamboat Company can be assigned to one railroad (be it a minor or a corporation) per OR; in RAW that happens during the private company income step. On 18xx.games I think it's allowed any time during the OR so that the game flow isn't interrupted.

**Comment by michaeljb** [comment]
Probably would improve UX to change wording on "Show" to "Show other companies" or something like that, and make the company names look like buttons or mini-cards.

**Comment by perwestling** [comment]
@michaeljb You were right, clicking on Lake Shore Line did show the ability.
Not clear to me why only Steamboat Company was shown? 

But changing the text of Show might be enough. In the same way as it is more than Show when it comes to buying trains from other players' corporations.

BTW, the Steamboat Company talkes about "by the owning (or assigned) company" - should it be corporation?

**Comment by perwestling** [comment]
I would say that it is pretty obscure to show Abilities: Lake Shore Line (PRR)   SHOW, and then expect the user to click on Lake Shore Line.... Maybe showing the line from the start to indicate that it is a clickable link would help?
