### ISSUE TITLE
Priority deal marker is incorrect during SRs

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#1207]
During an SR, the priority deal marker should be on the player who would have PD if everyone passed, starting now (and this used to be the case).

Here is a simple example demonstrating that this is now broken: Start 18Ch, buy all the privates for face value, Player 1 buys a share (PD marker correctly moves from Player 1 to Player 2), Player 2 passes (PD marker incorrectly moves from Player 2 to Player 3).

**Comment by o0dano0o** [comment]
I agree that the behavior is confusing, but I'm pretty sure the correct player has PD at the end of the SR. At least all the tests I've tried seem to work ok. Note this is in regards to 1889. I'm not sure if PD does weird things in other games...

**Comment by dfannius** [comment]
Agreed, it updates correctly once the SR is over, but it used to update correctly during the SR as well. I'd rather have it just be absent while an SR is in progress than have it be incorrect/confusing. (Of course, actually fixing it would be best.)

**Comment by dfannius** [comment]
This functionality broke in commit 806cded2c2911c6f6421fe63e540919427042397 (the round rewrite). I don't know if the old solution matches the current architecture, but that's where to look for reference; it was explicitly keeping track of the last player to make a non-pass action with the variable `last_to_act`.
