### ISSUE TITLE
show most recent payout?

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#121]
It would be nice to see the last amount paid to each company. One can go back and read through the log, but seeing it displayed at a glance would be appreciated.

**Comment by sparr** [comment]
Would you want this all in one place on some sort of grid, or as information on the company box, or elsewhere?

**Comment by jenf** [comment]
Should be covered by #215

**Comment by jcoveney** [comment]
I actually have a PR for this read once https://github.com/tobymao/18xx/pull/210 is in :)
