### ISSUE TITLE
Email address issue

### ISSUE THREAD

**Issue by o0dano0o** [tobymao/18xx#1214]
When I signed up for the site I think I had a typo in my email address. I don't remember exactly what the issue was, only that it was wrong. Also I don't ever get emails from the site, so it must be wrong?

I do not see a way of updating the email address. It would make sense to me to add something to see/update your email from the profile page.

**Comment by tobymao** [comment]
what's your user name on the site?

**Comment by o0dano0o** [comment]
It's o0dano0o. Thanks!

-- 
Dan Squires
dsquires@gmail.com
http://fotodano.com
http://danmakesmugs.com

**Comment by tobymao** [comment]
i've changed your email
