### ISSUE TITLE
1846: Private Company bug

### ISSUE THREAD

**Issue by qwerlancer** [tobymao/18xx#1222]
I found there is a bug of the latest update which adding "Abilities" attribute. 

In my turn, the "Abilities" field showing other players private company that has been bought by public companies. And I am allowed to use its ability by clicking it even that company does not owned by my company. Other players in their turn could do so.

Game ID: 4963 (Ongoing game)

**Comment by tobymao** [comment]
yes you can use threes abilities at any time

**Comment by qwerlancer** [comment]
I mean, I can use private company abilities which doesn't belong to my corporation.
We just undo it for not being ass and want a fair game.

**Comment by tobymao** [comment]
yep, and you can also steal their trains, but this is cheating so don't do it!
