### ISSUE TITLE
[1846] C&WI private allows incorrect station laying

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#1228]
In 1846 the C&WI private allows laying of an incorrect station in all Chicago, not just in the reserved spot.

**Comment by tobymao** [comment]
can you provide game data to reproduce this?

**Comment by Ticketautomat1** [comment]
Game ID: 5112
I spawned in Chicago using my C&WI and placed a token there (not in the reserved spot)

**Comment by tobymao** [comment]
action id?

**Comment by Ticketautomat1** [comment]
{
      "id": 72,
      "city": "D6-0-2",
      "slot": 0,
      "type": "place_token",
      "entity": "C&WI",
      "entity_type": "company"
    },

**Comment by vantdog** [comment]
Just encountered the same issue in Game 5715.

PRR bought the CWI and the token went into the wrong spot in Chicago.

**Comment by vantdog** [comment]
Relevant game data - 

  "id": 275,
      "city": "298-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "C&WI",
      "entity_type": "company"
    },
    {
      "id": 276,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation"
    },
    {
      "id": 277,
      "city": "298-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "C&WI",
      "entity_type": "company"

**Comment by vantdog** [comment]
We ended up hitting "undo" and went back to the point it happenned. We caught it a couple of turns after the fact. Back on track with the game now.
