### ISSUE TITLE
need not buy train without a route?

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#123]
I may have this wrong--but must a player purchase a train if they have no route? Player two floated the TR (Tosa Electric) and built north (F7). There is no route, but the app still requires a train purchase (or "undo"). I know that *some* 18xx games do not require a train purchase if there isn't a route; I am unsure about 1889.

**Comment by tobymao** [comment]
they don’t need a route , vacancy you give me a game id  in this state?

**Comment by jchipr** [comment]
I don't know how to determine game id...it's the one I'm currently playing. Description is "JCRhot3p200421a"  I am playing at http://159.203.254.109:9292/game

**Comment by jchipr** [comment]
just dropped it. I can recreate the state, but still don't know how to determine the game ID

**Comment by Spobster** [comment]
I believe that as soon as you have a station placed on a tile, then you need a train. But I may be wrong. Rules can be found here: https://www.tckroleplaying.com/bg/1889/1889-Rules.pdf, so check yourself :)

**Comment by dfannius** [comment]
The consensus is that you need an actual train-route with a second city/town before a train is required. The rules are a little unclear because they have a fuzzy definition of "route" that seems to imply that they can have only one city/town, but every discussion that I have seen goes with the "you don't need a train if you don't have a train-route" interpretation.

**Comment by jchipr** [comment]
Toby was right; you do not need a train without a route. Rules 10.1 say "an operating company with a legal route of any length must own a train...a company that does not have a valid run is not required to purchase a train."

**Comment by Spobster** [comment]
Perfect, Toby previously fixed the no tile - no train bug for us, but has to go back to also fix this issue then :)

**Comment by jchipr** [comment]
game ID 109 is currently in this state
