### ISSUE TITLE
issue with Lake Shore Line

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#1230]
game ID: #5112

Lake Shore Line allows placing of any town upgrade tile in Cleveland, although it's a "Z" town, we had could place a normal city tile.

 {
      "id": 283,
      "hex": "E17",
      "tile": "619-1",
      "type": "lay_tile",
      "entity": "LSL",
      "rotation": 1,
      "entity_type": "company"
    },

**Comment by tobymao** [comment]
duplicate
