### ISSUE TITLE
1846 - when a train is bought, its variant should be locked

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1241]
[This game data](https://gist.github.com/michaeljb/258fc4d2ac0d145b8b0fa2673913a135) (originally from #1233) has B&O buy train 4-2 as a 3/5, it is later discarded, and then bought by IC as 4. After B&O buys it as a 4-2 it should be locked in as a 3/5.

**Comment by benjaminxscott** [comment]
The rules seem to specify that it can be bought as a different train

### 6.83 Train Limit:
Returned train certificates may be purchased again (as either type)

**Comment by michaeljb** [comment]
Whoops, that's what I get for relying on my memory of the rules. Thanks for the correction @benjaminxscott
