### ISSUE TITLE
1882 river cost

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#1244]
In the game https://www.18xx.games/game/4971 we crossed the river 3 times, but only one of them was paid.

**Comment by jenf** [comment]
Confirmed, while most of the time the border disappears on I11 -> K11 it isn't working
K3 -> L4 also doesn't look to be working

**Comment by jenf** [comment]
B2, B12, 
D6
J2
K11
L4

Are missing the borders

**Comment by jenf** [comment]
Need to also confirm if the NWR happens the borders get reestablished

**Comment by tgtschetter** [comment]
The game tried to charge my company 60 on a 40 crossing.

**Comment by jenf** [comment]
@tgtschetter do you have a game id?
Was it from laying a second tile on your turn?

**Comment by tgtschetter** [comment]
> @tgtschetter do you have a game id?
> Was it from laying a second tile on your turn?

Yes, that was it. My mistake, thank you!
