### ISSUE TITLE
Usability: Add the possibility to show implementation details for the game on the info page

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1251]
On the info page today is shown designer, a link to the rules, and some more.

But I would like to see a section where one could write implementation details. E.g. that optional rules not supported, differences from the rule book based on differences in the digital implementation, and mayne other things. It could be enough with a simple text.

**Comment by ChrisTheCat** [comment]
As discussed on Slack, we could add a link to the wiki on the game Info tab, and then put implementation details / rules clarifications in the wiki where it's easier for non-programmers to edit/test

**Comment by jenf** [comment]
Wiki is the appropriate place, closing
