### ISSUE TITLE
[1846] Unable to assign steamboat to a company to minor (independent) railroad

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#1254]
This commit: https://github.com/tobymao/18xx/commit/dadfe3493605648d821ce69381ad3c26bb4235d7 fixed issue #1041 However, it still does not allow the user to assign the steamboats to a minor (MS or Big 4) only a major corporation. 

@tobymao I was actually working on this when you pushed the other fix. I have a few ideas for a solution, but am not sure which you would prefer. In lib/engine/step/assign we could change the check on target.is_a(Corporation) to also check if it is a minor. Or add a "assign_minor" ability that we also check for. Or have minor extend type corporation so the check will pass. Or plenty of other option. I also don't know enough other 18xx games to know how much minors vs corporations should be distinguished for private abilities. 

I have reached the point where I think this isn't a great first issue, since unless I am missing something it involves a non-trivial change. But I am happy to keep working on it if you have guidance. Or once I have something working I can put out a PR to give you a starting point.

**Comment by curlett** [comment]
Proposed labels: 1846, bug. Since I cannot add them myself.

**Comment by tobymao** [comment]
i think it's trivial to change target to include minor. 

another way you could do it is change to target.operator? to check both

**Comment by tobymao** [comment]
i've pinged you on slack if you want to chat more in detail
