### ISSUE TITLE
Providing an API could make 18xx.games even more awesome

### ISSUE THREAD

**Issue by Petesuchos** [tobymao/18xx#1255]
18xx.games is awesome but providing an API for external applications to consume could make it even more awesome.
An API would make things so much easier for developers to build around this project.

The API could provide interface to data like:
* Game chatlog
* Players
* Game data

We can always use scrappers to get that kind of data but an API is so much better

**Comment by tobymao** [comment]
we already have an api, please visit us in slack to discuss.

https://www.18xx.games/api/game/5213

btw, i saw your very cool app https://convert-18xx-to-routes.herokuapp.com/

this is super interesting, we should chat more!
