### ISSUE TITLE
Chat / Game Log Separation, Stamping, Etc.

### ISSUE THREAD

**Issue by Qualm64** [tobymao/18xx#1263]
The current log contains both game events and chat messages, and extends the width of the browser window even though most messages are much shorter.  Since most games are async, it can be difficult to take in all that has happened since your last turn, who has asked for autopassing, and generally to interact socially during the game.

Proposal:  Separate Game Events and Chat Messages into two windows, and pre-pend the current SR/OR to each message.

Pre-pending the SR/OR would be particularly important in the Chat Window, since "Qualm: Autopass me please" might be old and refer to a previous stock round in game without much chat, where "[SR3] Qualm: Autopass me please" is  unambiguous.

**Comment by jenf** [comment]
This is done.
