### ISSUE TITLE
Feature Request:  "Date Ended" timestamp for Completed Games

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#1264]
The "Completed Games" section in your profile is currently sorted by Game ID, with no indication of when a game ended.  Some async games may end when a user is sleeping or not available, and it would disappear from their "Your Games" section on the main page and appear somewhere in the "Completed Games" section with no great way to search for it or identify it as having ended recently.

Being able to sort by Game ID and Last Move or Date Updated or Date Ended would be awesome, but even just putting the Date Ended there would be great.

**Comment by yzemaze** [comment]
Really timestamp (= date & time) or same style like the other dates? (< 22 hrs => time, else date)

**Comment by yzemaze** [comment]
full date is available as title (on hover/tap) anyway
