### ISSUE TITLE
1882 Bug: NWR Private doesn't allow tile LAY, only tile UPGRADE

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#1266]
When using the NWR Private, it says that a token can be teleported and then an extra Tile Lay or Tile Upgrade may be done.  However, when trying to teleport my token into a recently-revolutioned Spiritwood, the game would not allow me to lay a yellow city tile.  I am fairly sure (but not positive) that there were yellow city tiles left, and I was able to teleport into that OO battlefield and upgrade it to green.

**Comment by jenf** [comment]
Do you have a game id?

**Comment by Akado05** [comment]
Not anymore, I undid the move and placed it in the battlefield.  Will a hotseat game ID work?  I can reproduce it there after the next smiting.

**Comment by jenf** [comment]
If you provide us the JSON (Tools -> Copy Game Data) I can probably reproduce it much quicker

**Comment by Akado05** [comment]
Interesting, in a hotseat game, Player 2 was able to teleport a home token + lay a yellow tile in Spiritwood immediately after the NW Rebellion.  I'll try again to see if it can be done before NWR.

**Comment by Akado05** [comment]
Nope, that worked as well (before NWR blows up tiles).  I guess this is no longer a bug, and the game ID was 5236.
[5236_nwr_bug.txt](https://github.com/tobymao/18xx/files/5002532/5236_nwr_bug.txt)
