### ISSUE TITLE
1882: train limit did not enforce at the turn of phase 4 / 4T

### ISSUE THREAD

**Issue by lychenus** [tobymao/18xx#1277]
https://www.18xx.games/game/5340

user was not prompted to dump train when 3T 3T 3T 4T is bought.

 {
      "type": "buy_train",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 110,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_train",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 111,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_train",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 112,
      "train": "3-3",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_train",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 113,
      "train": "4-0",
      "price": 300,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 114
    },
    {
      "id": 115,
      "hex": "K3",
      "tile": "57-3",
      "type": "lay_tile",
      "entity": "CPR",
      "rotation": 1,
      "entity_type": "corporation"
    },

**Comment by jenf** [comment]
Exact spot
https://www.18xx.games/game/5340?action=189

looks like i forgot to put the discard train code into the OR.

**Comment by jenf** [comment]
That was the only game that hit it. fixed in 0635f25
