### ISSUE TITLE
On map view show potential upgrades even if it's not your turn

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1279]
I'd like to see if a company can upgrade a tile during a stock round.

It'd be nice to be able to click on random tiles in the map view to see potential upgrades ignoring any adjacency restrictions without needing to work it out in my head :)

**Comment by yzemaze** [comment]
#865 is related

**Comment by jenf** [comment]
It's probably the right way to implement #865

**Comment by jenf** [comment]
Actually both would be a good approach, since you might be in yellow and wanting to see which brown you can end up with.

**Comment by orome** [comment]
In [a bit more detail](https://github.com/tobymao/18xx/issues/2259#issue-739334328), some possible features that would be nice to have (in presumed order of complexity):
- the ability to click on any hex where a tile can be placed by any player and see what placements are possible, regardless of who plays (i.e. no player restrictions imposed);
- imposition of player restrictions (i.e. don't show tiles that no one could possibly place);
- indication, for placeable tiles, of which players could place them (e.g., with the company icons tagging each tile);
- the ability to "impersonate" a specific player and see what tiles they could place.

**Comment by scottredracecar** [comment]
No one has stepped up to work on this. Closing for now.
