### ISSUE TITLE
game 110 "Game out of sync"

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#128]
OR 3.1  AR passes to TR - error message "Game out of sync"
game ID 110

I had been working toward setting up a different scenario, but this error showed up - is this something you want me to report, or is it not that big a deal?
Can I continue to work on reproducing the "forcing a player to sell stock" issue in this game, or is the "out of sync" error enough to abandon this one and begin a new experiment?

**Comment by tobymao** [comment]
no, this is a known issue, your game had a bug in it, the passing multiple times, so i had to delete it
