### ISSUE TITLE
[18Chesapeake]: C-P Private usable out of operating order

### ISSUE THREAD

**Issue by yeknom02** [tobymao/18xx#1284]
Playing a hotseat game of 18Chesapeake. I need to double-check the rules but this seems strange:
The B&O owns The Columbia-Philadelphia private which blocks H2 and I3, and gives you a free pair of tile lays. B&O is first in operating order and chooses to pass on this ability, settling on a single normal tile lay.
The C&A is second in operating order, and during the tile lay stage, it can show the Ability of the C-P private and lay its two track tiles, despite the person in the hotseat not being president of the B&O and the B&O already having completed its operations.

I will try cloning this game and leaving the current game as is:
https://18xx.games/hotseat/hs_ekhchryd_1596206429

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "B&OR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "C&OC",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "B&OR",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "C-P",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "B&S",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "CV",
      "price": 205
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "company": "B&S",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "company": "C-P",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "company": "C&OC",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "company": "D&R",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "company": "C-P",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "company": "C-P",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14,
      "company": "B&S",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "company": "B&S",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16,
      "company": "B&S",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "company": "B&S",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19,
      "company": "C&OC",
      "price": 95
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21,
      "company": "B&OR",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22,
      "company": "B&OR",
      "price": 120
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23,
      "company": "B&OR",
      "price": 125
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 24,
      "company": "B&OR",
      "price": 130
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25,
      "company": "B&OR",
      "price": 135
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 26,
      "company": "B&OR",
      "price": 140
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 27,
      "company": "B&OR",
      "price": 145
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "company": "B&OR",
      "price": 150
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 30,
      "corporation": "SRR",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 31,
      "corporation": "B&O",
      "share_price": "95,2,4"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "SRR_1"
      ]
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 33,
      "corporation": "C&A",
      "share_price": "95,2,4"
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 34,
      "shares": [
        "B&O_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "SRR_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "C&A_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 37,
      "shares": [
        "B&O_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 38,
      "shares": [
        "SRR_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 39,
      "shares": [
        "C&A_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 40,
      "shares": [
        "B&O_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 41,
      "shares": [
        "SRR_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 42,
      "shares": [
        "C&A_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 43,
      "shares": [
        "SRR_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 44,
      "shares": [
        "B&O_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 45,
      "shares": [
        "C&A_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 46,
      "shares": [
        "B&O_6"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 47,
      "shares": [
        "B&O_7"
      ]
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 48,
      "hex": "G7",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 49,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 50,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 51
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 52,
      "hex": "J6",
      "tile": "57-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 53
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 54,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 55,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 56
    },
    {
      "type": "lay_tile",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 57,
      "hex": "H4",
      "tile": "57-1",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 58,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 59,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 60,
      "train": "2-6",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 62
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 63,
      "shares": [
        "C&A_5"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 64
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 65
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 66
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 67,
      "hex": "F8",
      "tile": "X1-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 68,
      "city": "X1-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 69,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H6",
              "G7",
              "F8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 70,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 71,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 72,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 73,
      "company": "C-P",
      "price": 80
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 74,
      "company": "C&OC",
      "price": 160
    },
    {
      "type": "lay_tile",
      "entity": "C-P",
      "entity_type": "company",
      "id": 75,
      "hex": "I3",
      "tile": "9-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "C-P",
      "entity_type": "company",
      "id": 76,
      "hex": "H2",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "undo",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 78
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 79
    },
    {
      "type": "undo",
      "entity": "C-P",
      "entity_type": "company",
      "id": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 81
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 82,
      "hex": "J4",
      "tile": "X5-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "C-P",
      "entity_type": "company",
      "id": 83,
      "hex": "I3",
      "tile": "9-1",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "C-P",
      "entity_type": "company",
      "id": 84
    }
  ],
  "id": "hs_ekhchryd_1596206429",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18Chesapeake",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-07-31",
  "loaded": true,
  "result": {}
}

**Comment by Clacker76** [comment]
I have had the same issue with Chesapeake, C-P private purchased by B&O company, I CANNOT use the special ability! Game ID: 7734, player Clacker (other players include Phasmtis, Kampi and turn0
