### ISSUE TITLE
Lake Shore Line Upgrades Cleveland to wrong type of Tile

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#1285]
When using the Lake Shore Line's ability, it upgrades Cleveland to a non Z tile, which means it is undervalued.

**Comment by JEBrosius** [comment]
Hmm.  In our game (#4980), it upgraded properly.  I wonder what's causing the difference in behavior.

**Comment by tobymao** [comment]
i haven't validated this but i assume the reported is saying that it allows upgrading cleveland to non z, if you can confirm that this is not true, i can close this issue

**Comment by Blobbley** [comment]
Thanks. The game ID with the bug is 5169. Cleveland definitely is a non Z green tile there

**Comment by dfannius** [comment]
It's action 105.

**Comment by dfannius** [comment]
and if I go to hotseat from that point, it lets me upgrade to both Z and unlettered green tiles.

**Comment by JEBrosius** [comment]
Hmmm.  I guess one *can* upgrade to a Z tile (which is what we did) but that is not the same as saying it *requires* one to upgrade Cleveland to a Z tile (which is the desired behavior.)

**Comment by andrewbucholtz** [comment]
A similar thing happened in game #5698; the LSL was able to upgrade non-Z city Toledo to a Z tile. We fixed it, and it looks like it's fine if people are paying attention and know the rules, but it would be nice to have that upgrade restricted to only the tiles you can legally place in Cleveland or Toledo.
