### ISSUE TITLE
18Chesapeake - Wrong private showing up in abilities after purchase by company

### ISSUE THREAD

**Issue by pottsie** [tobymao/18xx#1286]
After N&W purchased the C&O private, the B&S private showed up under the abilities tab. Game ID is 5144, and it happened in operating round 4.1.

![image](https://user-images.githubusercontent.com/4276768/89056748-82840a00-d32a-11ea-96c0-13591cd4cf34.png)

**Comment by tobymao** [comment]
nothings wrong here, just a confusing ui. the B&O is under a toggle hide or show, which indicates that it's owned by another corporation / player.

**Comment by pottsie** [comment]
Maybe a separate issue then, but why isn't hex D2 available for the N&W to lay a tile?


Thanks!

On July 31, 2020 at 12:43 PM, Toby Mao <notifications@github.com> wrote:






nothings wrong here, just a confusing ui. the B&O is under a toggle hide or show, which indicates that it's owned by another corporation / player.

**Comment by tobymao** [comment]
looks available to me when i go to your game

https://www.18xx.games/game/5144?action=103

**Comment by pottsie** [comment]
Hmmm, it definitely is. I wonder why my screen capture attached to the original issue doesn't show it as available.


Thanks for your time in answering my questions.


Mike

On July 31, 2020 at 1:05 PM, Toby Mao <notifications@github.com> wrote:






looks available to me when i go to your game

https://www.18xx.games/game/5144?action=103
