### ISSUE TITLE
18AL Memphis & Charleston Railroad

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1288]
The text on the Memphis & Charleston Railroad company needs to be updated to reflect the fact that each bonus may only be scored by one train (both bonuses can be scored by a single train, but neither bonus may be scored by more than one train).

**Comment by tobymao** [comment]
you can fix this one yourself 

https://github.com/tobymao/18xx/blob/master/lib/engine/config/game/g_18_al.rb#L252
