### ISSUE TITLE
18AL Mobile city rendering

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1290]
The name of the city of Mobile (Q2) overlaps the values.

**Comment by ChrisTheCat** [comment]
Nashvill (A4) has the same problem.

**Comment by perwestling** [comment]
Preferably the Nashville and Mobile hexes should be apparent that they are one-way; you cannot pass the city, just start or end there.

**Comment by perwestling** [comment]
There is also a similar offboard city hex in 18MEX, where UdY starts, in the south east corner.

**Comment by roseundy** [comment]
Should this be broken into two issues: one for the overlapping city/values and one for tapered track to off-board cities?

**Comment by roseundy** [comment]
I think the fix for the first issue (city names on top of the revenue values) is to use non-unity (>1) weights for the revenue to bias the city name elsewhere. This is why there isn't a problem with Meridian.

**Comment by roseundy** [comment]
After more study, the problem with city names and revenue values colliding is that the revenue value box is not rendering in the correct location. The code is biasing (correctly) the revenue value to the top row of the grid, but that is not where it is being drawn.

**Comment by jenf** [comment]
1817 also shares the same problem.
