### ISSUE TITLE
18AL historical objectives on the map

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1292]
It would be nice if the historical objectives were indicated on the map.

**Comment by perwestling** [comment]
I have not seen this in any physical copies of the game. Having it on the corporation charter makes it pretty visible, and avoiding cluttering up the map.
@ChrisTheCat: Would it be a good idea to adding three destination markers to the already crowded Birmingham hex?

**Comment by tobymao** [comment]
if it's not present in physical and and it's shown on the charter, doesn't seem like we need it  wont fix for now
