### ISSUE TITLE
[18AL] Coal Token?

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#1293]
The coal token deploys correctly and gets added in correctly, but an icon to show where it is would be helpful.

The same is true for the swamp hexes, which has been addressed.

Likewise, it would be helpful if the named train bonus was named in the routes which use them. They are being added in correctly, but some notation to show which routes triggered the bonuses would be helpful.

**Comment by perwestling** [comment]
About coal token, the 5 locations where it can be put is shown from the start, and at deploy they are removed. @SmithInMN, do you think a solution of leaving the coal icon be in the selected hex, and just remove the non-selected ones, would be an OK solution?

About the bonuses, I have it as a known problem on this page: https://github.com/tobymao/18xx/wiki/18AL

**Comment by TheExcalabur** [comment]
Leaving the icon in the selected hex would work fine.

**Comment by perwestling** [comment]
Have pushed an improvement for the coal token for review.

For the bonus issue I have created a new issue, #1302

**Comment by perwestling** [comment]
@SmithInMN  - the coal hex fix has now been deployed.
I suggest this issue is closed as the bonus thing has been moved to another issue.
