### ISSUE TITLE
3/5 Miscalculating

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#1294]
In game ID 5169 GT is trying to run a 3/5 from Chicago connections to Sarnia. It is calculating this as 190 but it should be 230 (C4 - 40; D6 - 70; B18 - 50 + 70 for the EW)

**Comment by Blobbley** [comment]
(Specifically in OR 4.1)

**Comment by tobymao** [comment]
you need to include a token

**Comment by Blobbley** [comment]
Even if the token had been counted instead of another city, it should have been 220, not 190

**Comment by tobymao** [comment]
how? 9 + 3 + 7 is 19

**Comment by Blobbley** [comment]
30 + 70 + 50 + 70

(B16 - 30; D6 - 70; B18 - 50; EW 70) (not counted C5 and C9)

**Comment by Blobbley** [comment]
Sorry if I’ve totally missed something fundamental and thank you for the quick response

**Comment by Blobbley** [comment]
Sorry. I now see you have to include both E and West locations to get the bonus, so I don’t include the Chicago tile. Thank you for your time and sorry!

**Comment by tobymao** [comment]
no problem have fun
