### ISSUE TITLE
Enhancement:  Add Par Pop Up to Various Games

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#1297]
Boston Rob has produced very nice quick reference sheets to show you the various pars.

This would be a very nice addition to the particular games.  You would select Par Chart, and the chart for the particular game would pop up.  Also a good reminder to people that 1889 is a five par game and not six!

See this thread:  [https://boardgamegeek.com/filepage/205972/par-chart-player-aid-small-and-simple-18ches](url)

**Comment by tobymao** [comment]
it's on each company charter
