### ISSUE TITLE
1882: NWR Private usage broke gameID 5266 in so many ways

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#1299]
QLL had $160 left in treasury after running, and wanted to buy the NWR private, use it, and teleport to safety.

In the company-buying stage, if the QLL paid $160 for NWR the game auto-forwarded to the next company's turn due to the QLL not having any money in treasury.  So, I undid, bought NWR during the payout-withhold stage, teleported to the Battlefield OO, upgraded it to green OO, and tried placing my token again in the spot where I wanted it to be.  That didn't work at all, and in my infinite wisdom I clicked a whole bunch of places thinking it might have been a hitbox issue.  Nope, so I went back to refresh, and now the game won't load on computer or phone.

I'm counting this as a victory, as I caused the game to end right after paying myself a hefty ransom.  If you want to see the game right before it broke, use `https://www.18xx.games/game/5266?action=123`, as action=124 is where it no longer loads.

I've attached the game data from action=123, but that might not include the part where I tried re-placing the token after the OO upgraded.
[5266_nwr_bug.txt](https://github.com/tobymao/18xx/files/5011061/5266_nwr_bug.txt)

I cloned the game at action=123, right before QLL needed to re-place the token, and the crash/bug/freeze/IWIN still happens if I try to select a spot in the OO.

**Comment by Akado05** [comment]
Just for weirdness' sake, once I went to action=123 and copied game data, it seems that the game went to "latest action#tools", and I was able to go to the Maps tab, which showed the QLL's new token spot.  However, going to the Game tab still causes the game to not load.

**Comment by jenf** [comment]
I think i have to disable NWR between selecting routes and payouts, otherwise the route you've run becomes invalid.

**Comment by jenf** [comment]
Two bugs
1) Using NWR private at the dividend step causes it to crash
2) Buying a private leaving you 0 money advances to next player rather than allowing you to use the private.

**Comment by jenf** [comment]
Actually 2 is unnecessary since you can use the ability out of turn anyway.
