### ISSUE TITLE
Operating round : Placed a second tile instead of buying train

### ISSUE THREAD

**Issue by McDood** [tobymao/18xx#13]
First Operating Round : Awa is floated in Stock round 1
I placed a yellow tile on home tile, then placed a second tile next to it.
Train buying step was passed by doing this

(Log is inverted)
-- Stock Round 2 --
Awa Railroadspends $80 and lays tile 7 with rotation 0 on K6
Awa Railroad's share price changes from $65 to $60
Awa Railroad does not run
Awa Railroad lays tile 5 with rotation 3 on K8

**Comment by tobymao** [comment]
thanks for reporting these! i'm aware of this one
