### ISSUE TITLE
18AL: Rendering of icon in Birmingham tile collides with revenue

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1300]
In 18AL a mining icon is used to show where the Warrior Coal Field token can be assigned, or has been assigned. This is rendered on a bad place on the Birgmingham tile, at 3 o'clock, which means it collides with the revenue for that tile. 

I think one possibility would be to make it possible to specify where the icon should be placed. In the case of Birmingham, putting the icon at 1 o'clock (North East) should be good enough.

Here is how Birmingham would look in green with mining icon still there:
![Birmingham_mining](https://user-images.githubusercontent.com/2631151/89110790-8d37bf80-d44e-11ea-8413-86bf732750ba.PNG)
From the beginning Birmingham also has a mountain icon:
![Empty_Birmingham](https://user-images.githubusercontent.com/2631151/89110812-d982ff80-d44e-11ea-8fa7-af0e90065b8b.PNG)

Birmingham has the B tiles, special in each color. Note! The mining icon will be removed no later than the 6T is bought, so it will never appear on the gray tile.
![Tiles](https://user-images.githubusercontent.com/2631151/89110847-29fa5d00-d44f-11ea-85b0-57c07189ec96.PNG)

**Comment by tobymao** [comment]
you should just use the weights system

**Comment by tobymao** [comment]
https://github.com/tobymao/18xx/blob/master/TILES.md
