### ISSUE TITLE
18AL: Bonus not aparent

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1302]
In #1293 @SmithInMN wrote:

"Likewise, it would be helpful if the named train bonus was named in the routes which use them. They are being added in correctly, but some notation to show which routes triggered the bonuses would be helpful."

In 18AL there are two types of bonuses:

1. Warrior Coal Field token, giving $10 each time a route contains a specific hex
2. Robert E Lee (och Pan American) giving a $20 (and/or $40) bonus for a run if any route contains two specific hexes

The Warrior Coal Field token bonus is added to the route revenue, but it is not apparent that a bonus has been received.

The Robert E Lee (and Pan American) is added to the revenue as a whole. 
Example:
- Route 1 is from Birmingham to Atlanta and gives $70
- Route 2 is from Birmingham to Atlanta (another path) and gives $80
In this case the total revenue is shown as $170, not $150, as it includes a one time bonus of Robert E Lee.

It would be nice if it somehow were more obvious that a bonus has been triggered.

**Comment by perwestling** [comment]
Similar request can be found for other 18xx in #976 and #1063 

An attempt that might solve this has been done via #1085 but it is still not clear if it would solve the run bonus; possibly a separate line with extra bonus(es) might need to be added.

**Comment by perwestling** [comment]
This might also apply to the Civil War event in 18TN, where when running the next runs, one of the trains are excluded from giving any revenue (which is implemented as the minimum one are just removed from total revenue). So it can be seen as a negative bonus. It has the same problem of not being apparent.

**Comment by ryandriskel** [comment]
18CO and 1882 have examples of showing a bonus in the run log. Its not terribly pretty though.

**Comment by perwestling** [comment]
18MS also has the Atlanta bonus that could use this, see issue 2000.

One lack I noticed when I used this in another game was that the bonus information did not appear until the log (besides the increased value). But anyway it is an improvement.
In case of Mobile-Nashville: Wonder how to best present it? M/N? 
Also, in case of two trains were managed to hit these bonus-routes - does it show on just one (if I recall it correctly you cannot get this bonus for more than one run).

**Comment by ryandriskel** [comment]
Also, in case of two trains were managed to hit these bonus-routes - does it show on just one (if I recall it correctly you cannot get this bonus for more than one run).

Yessir!

<img width="577" alt="Screen Shot 2020-12-15 at 8 12 08 PM" src="https://user-images.githubusercontent.com/15675400/102418778-a6837780-3fbb-11eb-89f5-bdac960ce67e.png">

**Comment by ryandriskel** [comment]
Err, I guess that's not the case you asked about :D

I'll need to verify that one, but the code I've written is based off your work and stores the route together with the bonus, so it shouldn't.

**Comment by perwestling** [comment]
It was twice Atlanta-Birmingham that I were asking about.
I think it is OK with A-B + M-N if that would ever happen. (Have played 10+ games of 18AL and never seen the M-N bonus....)

**Comment by perwestling** [comment]
In the physical game there is one token per bonus type that you assign to specific trains. So that means only one train can get a specific bonus. Now this was hard to implement in 18xx.games so we choose this automatic bonus instead (which caused other problems...)

**Comment by ryandriskel** [comment]
> It was twice Atlanta-Birmingham that I were asking about.

Yeah right after I posted I realized what you meant. Will be easy enough to verify when I get back to working on it.
