### ISSUE TITLE
Game ID 83: Player not forced to sell down certs in excess of cert limit

### ISSUE THREAD

**Issue by jaeisma08** [tobymao/18xx#131]
EisVrouw81 has 23/19 certs in the first round of SR8. The game is letting EisVrow81 pass instead of selling shares down to the cert limit. At the end of SR7, IR was in the yellow, so the player's 4 IR shares did not count against their cert limit. During OR7, IR left the yellow.

**Comment by dfannius** [comment]
`Round::Stock::must_sell?` is defined but nothing seems to call it.
