### ISSUE TITLE
Usability: Make it possible to filter games shown in Welcome page

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1311]
The number of games shown in the Welcome page starts to get very large, so it would be nice to have some way of showing a subset.

One idea could be to add a select box for "New games", "Active games", "Finished games" where you can select a game title and only show games for that game title. 

It would probably be simple to make a filter for all sections, alternatively there could be one filter per section.

**Comment by jenf** [comment]
i think this is a dup of #782
