### ISSUE TITLE
Easier placing of bonus tokens

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1317]
Here's the current workflow for a player-owner to place then 1846 Steamboat token:

- Click Show to show the abilities.
- Click the Steamboat Company.
- Click the MS charter.
- Click the Steamboat Company.
- Click the appropriate tile (Toledo).

Here's a workflow that requires fewer clicks:

- Click on steamboat symbol on map
- Get presented with a list of corporations and select one

and if a corporation owns it, the steps would be:

- Click on a steamboat symbol on map

This would, of course, apply to many bonus tokens, like the 1846 Meat Packing Token, the 18AL Warrior Coal Field, the 1830 Port, etc.

**Comment by jenf** [comment]
@ChrisTheCat is this still an issue?

**Comment by ChrisTheCat** [comment]
Nope, the new workflow is fine.
