### ISSUE TITLE
[1846]: All players in Draft Round can see which companies the current player can choose from.

### ISSUE THREAD

**Issue by OzLocutus** [tobymao/18xx#1318]
https://www.18xx.games/game/5578

In Draft 1, all players can click on the Show Company Button, and view the companies that the current player can choose from. Pretty sure this wasn't happening in the Alpha game I played, and pretty sure players shouldn't be able to see what the current player can choose from.

**Comment by tobymao** [comment]
@jenf looks like this was broken when you consolidated the draft round

**Comment by jenf** [comment]
yeah, fixed on master.
