### ISSUE TITLE
Automatically resubmit actions if the desyncing action is a chat message

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1322]
**Describe the bug**
If people are talking the game can go out of sync. We should know if it's a message and that we can just resubmit it anyway.

**Comment by jenf** [comment]
Problem is this still causes problems to the player submitting the action.

If action == chat
 change the id
else
 ensure that all actions between id and the current id are chat
end

We'd have to modify the subscription on the UI to detect if orders are incorrect and update the local view, This could probably be done with exactly the same algorithm to just fake it coming in later.

**Comment by daniel-sousa-me** [comment]
I have also been thinking about this and was going to open an issue x)

Could the messages have "different id's"? I was thinking that they could just reference a parent message or action.

A different question, but related. Maybe we should just separate the chat from the log and have them side by side (or one above the other on mobile). Lots of times the messages get lost in the middle of a bunch of log text, especially in the ORs. This way we can just have to separate arrays. The messages might still reference a parent action and there could be a visual indication in the log as a kinda of notification that there's a new message.
