### ISSUE TITLE
[1846] 3/5 Trains not Calculating Properly

### ISSUE THREAD

**Issue by TIE53** [tobymao/18xx#1326]
In a game of 1846 earlier today, we noticed that 3/5 trains were not computing properly, and not selecting the best cities on the route. I believe the current scripting will always select the end points as one of the stops. In the test JSON below, if IC runs a 3/5 from Chicago Connections -> Chicago -> Detroit, it calculates the run correctly as $100.  However, if you include Port Huron on the end, instead of counting the run as $110 (skip/40/40/30) it counts the run as $90. This issue appears to not occur if both end points should in fact be counted (e.g. on an E-W)

JSON to Hotseat test (not a real game): https://gist.github.com/TIE53/6f6d4046d20de0b503d771205cb70379

**Comment by tobymao** [comment]
dup of #1053
