### ISSUE TITLE
Separate count in spreadsheet for neutral tokens

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#1332]
Please describe your idea and why we should consider it.
For 1882, spreadsheet showing separate counts for regular and neutral tokens.  Either a new column or some other way to see it at a glance.

**Comment by KenKuhn** [comment]
I'll give this one a whirl

**Comment by KenKuhn** [comment]
I think this issue is a bit too advanced for me. I'm releasing it back into the ether ;)
