### ISSUE TITLE
Player finance columns do not line up with player columns above 

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#1333]
**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.

**Please provide details about your system**
 - OS [e.g. iOS13, Win10] & Device [e.g. iPhone XS]
 - Browser & Version [e.g. Chrome 83]

Chrome browser.  Win10.  Player finance columns in 1882 do not line up with the player columns above; they are evenly spaced while the above columns have different spacing, resulting in offset.

**Comment by jenf** [comment]
Not 1882 specific
