### ISSUE TITLE
The map doesn't show the routes that president chose as indicated in the log file.

### ISSUE THREAD

**Issue by o0dano0o** [tobymao/18xx#1338]
I was playing a live game of 1889 with friends last night. We noticed that the routes that the president were choosing were not appearing on everyone else's screens correctly.

Example: https://www.18xx.games/game/3998?action=299

The view in the history also seems incorrect and different from what we saw live.

During the live game we saw this:
![1889_2](https://user-images.githubusercontent.com/5915535/89361220-922f8580-d67f-11ea-853b-8e45c409ac1a.JPG)
![1889_1](https://user-images.githubusercontent.com/5915535/89361221-92c81c00-d67f-11ea-9830-42b2d9165be6.JPG)

In the history now I see this:
![1889_4](https://user-images.githubusercontent.com/5915535/89361303-d589f400-d67f-11ea-8dda-fd30a23ea436.JPG)
![1889_3](https://user-images.githubusercontent.com/5915535/89361298-d458c700-d67f-11ea-8deb-70d00cafd8d4.JPG)

Neither of the maps match what the president actually did per the log messages.

**Comment by o0dano0o** [comment]
To be clear, the rail between Marugame and Kotohira should be blue

**Comment by jenf** [comment]
While the president is choosing routes you don't get a live view of their route choice.

Effectively a dup of #563
