### ISSUE TITLE
Can get stuck if over cert limit and undersell stock

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#134]
There is existing code that only lets you sell stock from a given corporation once per stock round, since the 1889 rules say that stock can only be sold as a block (I don't think 1830 has this restriction, but that's neither here nor there).

Now that #133 doesn't let you move on until you have sold stock down to the cert limit, it's possible to get in a situation where

- you're over the cert limit by a few shares, so you can't pass
- you sell one or more shares of the companies you have stock in, but not enough to get under the cert limit
- now you can't pass because you're still over the cert limit, but you can't sell any more shares because you've been locked out from making a second sale in any corporation.

In reality you can always undo at this point (hooray for undo), and maybe that's actually ultimately the correct solution (anything else would be kind of a nightmare), but we should probably at least call out what's going on so it doesn't look like a bug.

**Comment by tobymao** [comment]
i think the correct solution is to undo, the game is broken and this is what you would do in real life
