### ISSUE TITLE
Buttons are getting cut off on the pay/withhold step

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#1341]
**Describe the bug**
The buttons are getting cut off on the pay/withhold step, hotseat game below, but I think this happens globally.
![image](https://user-images.githubusercontent.com/29106780/89368982-7db0b480-d6a2-11ea-832d-625250d0ccc1.png)

[hotseat.txt](https://github.com/tobymao/18xx/files/5025964/hotseat.txt)

**Please provide details about your system**
macOS Chrome

**Comment by perwestling** [comment]
It is not OS related as I have had that for a while on Chrome, on both Linux and Windows.

**Comment by yzemaze** [comment]
It’s not. It was an oversight by me. I even noticed it a few days ago, but didn’t put it on my to-do list instantly …and forgot about it … It’s already fixed and waiting for a merge.
