### ISSUE TITLE
[1846] Trying to assign routes for 5 trains fails

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#1343]
Multiplayer: https://www.18xx.games/game/5738?action=274
Gist: https://gist.github.com/wcraigtrader/33a13ad1b312fd6cc09f7de3cee1103a

I had a game of 1846 where the IC had a pair of `2` trains and a `4`. In OR3.2 the IC bought two (2) `4/6` trains, which phased out its `2` trains. On the next OR (4.1), the IC tried to run all 5 trains. It could assign all of the `2`s, the `4`, and one of the` 4/6` trains, but not the other one, no matter what order the routes were assigned. 

Since running both 4/6 trains was pretty critical, we called the game on account of bug.

**How To Reproduce:**

1. Click `Done` button to complete building track.
2. Try to assign routes for all 5 trains.

**Comment by Akado05** [comment]
Any issue solved by "use french violet and outrageous orange" is awesome.  Just saying.
