### ISSUE TITLE
The Takamatsu Private doesn't list that it blocks K4 upgrade

### ISSUE THREAD

**Issue by DNAmers** [tobymao/18xx#135]
As the per the heading; not critical to those that know the game, but helpful to those learning. Worth adding this to the Private cert?

**Comment by zurfarosa** [comment]
Yes, as a noob I'd find that very helpful.

**Comment by sparr** [comment]
The iconography on the board is relatively consistent with other 18xx games, but I agree that it's sometimes hard to notice or keep track of for a new player.
What about ER blocking upgrade of C4, too?

**Comment by jenf** [comment]
Text added.
Lack of blocking the action is a dup of #243
