### ISSUE TITLE
[1882] Attempting to activate SC ability and I am required to have 20% of personal cash even though 10% is required

### ISSUE THREAD

**Issue by BackdoorMP** [tobymao/18xx#1351]
Link to the game with action number: https://www.18xx.games/game/5002

In game 5002, I am attempting to activate the SC ability to par SC at $100.  $100 is unavailable to me as an option (neither is $90 for that matter) $100 and $90 become available only when I sell an additional company share bringing my personal cash to >$200 or par value x 2 (at least 20% in available funds).  SC requires only 10% to activate. It appears that the game is requiring me to have 20% even though 10% will be removed from my personal funds. When parred at $82, only $82 is removed from my personal funds.

**Comment by jenf** [comment]
Probably a regression caused by the par changes. I tested this possibility originally
