### ISSUE TITLE
1846 - Bankruptcy

### ISSUE THREAD

**Issue by vantdog** [tobymao/18xx#1352]
Game 5715 - 1846, 4 player

player brootal went bankrupt - was president of 2 companies at the time it happened (NYC and PRR). Both went into receivership as per the rules - as in both cases there was only 1 stock held by another player. Both were operated by "Sharepool" according to the game history. PRR followed the rules - ran its train and withheld revenue. NYC didn't do that though - it doesn't appear that it ran its train, nor did it withhold. 

Not likely to happen a whole lot - but thought I'd let you know. 
-Tim

**Comment by michaeljb** [comment]
Weeeeeiird at https://www.18xx.games/game/5715?action=642 the NYC is up to act, according to the rules it should be running any trains it has for max and then withholding (I've written #1380 to make that a little more obvious). The chat message being the next action caused the end of NYC's turn to be skipped, but that didn't happen on PRR's turn. Strange.
