### ISSUE TITLE
[1889] Train could run illegal route

### ISSUE THREAD

**Issue by augustoribeiro** [tobymao/18xx#1353]
SR company could run a train on an apparently illegal path where the track section on the D9-E8 hex-side was used twice
![Screenshot 2020-08-05 at 12 52 25](https://user-images.githubusercontent.com/2705049/89450921-aa74d280-d75b-11ea-96c5-307b19e35423.png)

![Screenshot 2020-08-05 at 10 28 01](https://user-images.githubusercontent.com/2705049/89450822-79949d80-d75b-11ea-9f9a-cdb0269905aa.png)

https://www.18xx.games/game/5033?action=713

Please request if you need any extra info. Best regards.

**Comment by jenf** [comment]
I don't think this will be specifically 1889.

**Comment by cmaggard** [comment]
I've been taking a look into this- definitely not specific to 1889.

**Comment by timbovelander** [comment]
We ran into the same bug, but with multiple trains in 18chesapeake.

![IMG-20200913-WA0001](https://user-images.githubusercontent.com/2109937/93016404-37b01000-f5c1-11ea-9e0e-45f1ec2c7144.jpg)
