### ISSUE TITLE
1846: Cannot Emergency Buy brown train from another company in grey phase

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#1355]
**Please provide**

Game link: https://www.18xx.games/game/5779?action=1211
Not exact action, but pretty shortly afterwards.

**Describe the bug**
In OR 4.2, grey trains broke and the B&O had only a 3/5 train.  It was slated to buy a permanent train, and had $474 in treasury.  It wanted to buy over a 5T from the PRR (owned by same player), but the game said "Not a buyable train".  Tried with master mode enabled, same error.

Perhaps because there is something saying "You can only buy current-phase trains", despite the 5T being a permanent train and thus not phased out?

**Comment by Bobsson** [comment]
It might be a little broader of a problem.  
Game: https://www.18xx.games/game/5636?action=579

B&O is trying to buy a 7/8 from IC, so this is a current-phase permanent train, but I'm getting the same "Not a buyable train" error.
