### ISSUE TITLE
[1846] SBC token can be moved to a new location too many times

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1359]
As of #1358, the Steamboat company may be re-assigned too many times. While owned by a player, it should be assignable once per OR (before any corporations operate to be _strictly_ accurate); while owned by a corporation, it should be assignable once.

**Comment by PedroRCSequeira** [comment]
I've tried without success to change the location of the token

Tried in another OR
Tried after buying
Tried after buying with another company (it switches the assigned company, but still won't change the location
