### ISSUE TITLE
1846: reload on possible route builds when a private company is bought in

### ISSUE THREAD

**Issue by lychenus** [tobymao/18xx#1361]
https://www.18xx.games/game/5329?action=137

when michigan south is bought in, the new possible routes wont be highlighted or allowed to put. users need to manually reload to see the new possibilities. good if it reloads for the user.

**Comment by tobymao** [comment]
just tested and it works fine for me

action 137, buy MS, token swaps, toledo and others are highlighted, allowing me to lay track.
