### ISSUE TITLE
make notes popup when you open the game

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#1365]
In BGA if you have notes written, they will popup everytime you open that game.
In async, specially with multiple games, it's likely that you may have notes in some, and not in others, and you may not remember which ones.. this would make it a bit harder to forget about the notes you have written

It also has a quick *close* and *close and delete* button to make it even more practical

**Comment by tobymao** [comment]
it's just one click to get to the tab

**Comment by PedroRCSequeira** [comment]
+1 click to go back after you find an empty notepad.

so you are lost, without a helping hand because you forgot to leave a note..
and you just wated 2 clicks. #regrets

**Comment by yzemaze** [comment]
@PedroRCSequeira Just use https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/ or sth. similar.
