### ISSUE TITLE
Feature: "Run till end" button

### ISSUE THREAD

**Issue by erperreault** [tobymao/18xx#1366]
Once everyone agrees to run out the game (no more tile/token/etc, just run and pay out), a button could auto-run all corporations until the bank breaks or the next SR. Nest it with the Master mode button so it stays out of the way. This will save time and hassle when players want to get a final net worth rather than just stopping and would normally "spreadsheet" the last several ORs.

**Comment by michaeljb** [comment]
Even if not everyone agrees to this for all their corporations, it could probably be done on a per-corporation basis.

**Comment by tobymao** [comment]
it should be pretty easy to just click through to the end?
