### ISSUE TITLE
1846 allows you to run a legal route with two of Chicago’s stations

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#1369]
![C248AD50-7A80-4B75-A5E0-3565A618A737](https://user-images.githubusercontent.com/69050942/89560932-b326e080-d80f-11ea-96f4-a346378e3751.png)

**Comment by benjaminxscott** [comment]
Ah this is probably b/c those stops are "towns" in the code, and in other games like Ches it's legal to hit both towns in a single hex (e.g. b'more)

**Comment by jenf** [comment]
A train’s route may not visit a given location more than once or pass
through any blocked cities

**Comment by michaeljb** [comment]
I think the tile upgrades (tiles 298, 299, 300) just need `groups:Chicago` added; the definition for the preprinted yellow tile has `groups:Chicago` for all four cities, but that's not passed on when the tile is upgraded.
