### ISSUE TITLE
Kouchi (F9) upgrade

### ISSUE THREAD

**Issue by webbtraverse08** [tobymao/18xx#137]
The tile for upgrading Kouchi (#465) should have three token spaces and be worth $60.

**Comment by michaeljb** [comment]
Just fixing the tile breaks some tests. Added a revert commit and started a branch for a proper fix

**Comment by lukesonnet** [comment]
While you're here, it looks like it costs 80 to upgrade, but upgrading Kochi is free.

**Comment by michaeljb** [comment]
@lukesonnet the DTG board has an ¥80 upgrade cost - https://boardgamegeek.com/image/555394/1889-history-shikoku-railways

**Comment by lukesonnet** [comment]
Oh yep, sorry, looks right. I was incorrectly inferring something from the tile roster and couldn't remember ever paying to upgrade.
