### ISSUE TITLE
Make it possible to add/show a longer description to a corporation ability

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1374]
For companies owned by a corporation you can click on it to get a more extensive explanation what it does.

But for abilities in corporation there is no such extensive description available. In some cases a more full text can be helpful so you do not have to lookup the rules. 
Of course some abilities is more or less self explanatory so abilities without extra description should just ignore clicks.

**Comment by perwestling** [comment]
Example of abilities there this can be helpful:
- 18AL, the historical objective. The text could describe that the corporation receives $100 when its historical objective is tokened.
- 18TN, civil war. Hard to give a short description what a Civil War means in this case.

**Comment by yzemaze** [comment]
@perwestling 
I’m not really keen on adding the company solution here. Simplest solution would be to just allow linewrap for abilities. Would this work?
![image](https://user-images.githubusercontent.com/33390595/108185407-8f245000-710c-11eb-9832-0283a15eaf8d.png)
(dummy text)

**Comment by perwestling** [comment]
@yzemaze What is the problem to use a similar behavior for company, corporation, minor? Adding an always present longer text wouldn't it clutter down the GUI?

It could also be noted that I have started to use abilities for corporation (and minors) more and more.... I do believe this is good UX as the players have this information handy without having to look through the rules, or lookup the wiki page.

**Comment by yzemaze** [comment]
It was just a question. If 2 or 3 lines aren’t sufficient (or if there are multiple abilites with longer texts), that option is dead.
Just point me to examples of these longer texts and I’ll think about it.
