### ISSUE TITLE
Support other presidency percentage than 20

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1376]
20% is very common for presidency shares. But there are a bunch that has other numbers.

One of these are 18TN which has a 30% presidency share.

It would be good if it was possible to configure per game.

**Comment by michaeljb** [comment]
18Chesapeake 2p is broken; dumping a corp magically adds 10% to the new President's total - https://www.18xx.games/game/5976

**Comment by perwestling** [comment]
I tried adding this functionality in 18TN, creating a 30% share for IC.
Now I had the situation:
- Player 3 40%
- Player 1 20%
- Player 2 10%
And 30% in IPO

If Player 3 want to sell the options are now:
Sell 10%, Sell 30%, Sell 40% (the two last invalid)

If selling 30% or 40% Player 1's holding is now changed to 30%.

**Comment by michaeljb** [comment]
This is probably the code that needs to be generalized:

https://github.com/tobymao/18xx/blob/master/lib/engine/share_pool.rb#L143-L153

**Comment by perwestling** [comment]
Also tried 18Chesapeake.
Here I had a situation where
- Player 1 50%
- Player 2 30%
- Bank 10%

If Player 1 want to sell Player 1 can choose between 10%, 20% and 40%. But not 30%?

Hot set game https://18xx.games/hotseat/hs_lljthykc_1596808338
