### ISSUE TITLE
Reachability of the website 

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#138]
Hi Toby, we cannot reach the website anymore for the last 30h or so. First I expected it to be a general downtime, but because new issues were posted here, I assume it may have a different cause. I have tried my android phone, and use firefox webbrowser from the Netherlands. And my friends also have trouble to access.
Thanks again for your help. Spobster

**Comment by tobymao** [comment]
please join us on the #18xx slack for updates. the website is now at https://www.18xx.games/
