### ISSUE TITLE
18MS: Crashes when attempting to configure off board hexes

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1385]
There are two errors in the 18MS map. Included maps below is from the physical game.

1. Atlanta on the east should be a group of D12, E13, F12, with track out on the board. When I try to add a hex E13, with a path, it crashes with: undefined method 'edge?' for nil. 
![Atlanta](https://user-images.githubusercontent.com/2631151/89687393-74248800-d900-11ea-9c2b-5ffee646b6dc.PNG)
2. I3 on the map is a workaround to solve the city + town hex of I1. If I try to add a track on I3 to connect to I1 I get uncaught exception: Type Error, NilClass can't be coerced into Numeric. Stack trace for this include reservation.rb:3, town_rect.rb:64, base.rb etc
![NewOrleans](https://user-images.githubusercontent.com/2631151/89687395-7686e200-d900-11ea-9891-52c492df0f93.PNG)

**Comment by perwestling** [comment]
I have a local commit where I have managed to add E13, and make D12+E13+F12 into one big off board hex with one revenue. Think it looks fine.

But I3 is still a problem; cannot put track on that hex.

**Comment by perwestling** [comment]
I made I3 into a town with one track out at 1, and one track out at 4. It seems to work acceptable.

Maybe the rendering does not support a town with only one track?

**Comment by roseundy** [comment]
After a tiny bit of debug, I think the exception is coming from assests/app/view/game/part/town_rect.rb and the definition of the TownRect Class. It was written assuming there are at least two edges in play. We need TownDot in this case and not TownRect.

**Comment by michaeljb** [comment]
Reopening; #1425 only fixes one of the two problems here.

**Comment by perwestling** [comment]
@michaeljb The current hex configuration seems to work fine, so I think it might be good enough. Have not gotten any feedback from Designer or Players about this off board.

Do you think we still need to consider this change for 18MS, or should we close this and open a new one for any future title (if any) that has this problem?

**Comment by michaeljb** [comment]
The current config is probably good enough, we could revisit this if/when relevant for a future title.
