### ISSUE TITLE
Need more obvious logging for automatic actions

### ISSUE THREAD

**Issue by dagopher** [tobymao/18xx#1392]
My turn came around and the game log said I had already taken actions when I hadn't. I eventually figured out that the game had auto-skipped actions I couldn't do because I didn't have enough stocks to issue shares) or enough money to lay track. But the game log just said:

> dagopher operates GT
> GT skips issue or redeem shares
> GT skips place a token or lay track

This made me think that I did those actions (when I knew I hadn't) or the game glitched. It took me a few minutes to figure out what had actually happened. I would recommend that when an action is auto-skipped or automatically played that the log should reflect that. 

For example I would have found this much more helpful:

> dagopher operates GT
> GT automatically skips issue or redeem shares (Reason: no shares left)
> GT automatically skips place a token or lay track (Reason: not enough funds in treasury)

Logging that A) this was an automatic action and B) WHY it was an automatic action would greatly avoid confusion for some players (me!).

**Comment by tobymao** [comment]
anything tagged as skip is automatic

**Comment by tobymao** [comment]
i think it's sufficient for now

**Comment by wcraigtrader** [comment]
This enhancement is less about using "automatically skips" instead of "skips" and more about logging *why* that action was skipped (no shares in the treasury or market, or no cash in the company).
