### ISSUE TITLE
1836Jr30, Share Price Did Not Move Up At End of SR When Corp Was Sold Out

### ISSUE THREAD

**Issue by MontyBrewster71** [tobymao/18xx#1394]
Game number 6108 of 1836Jr30, at the end of SR 9, Corporation B was sold out, but the stock price (which was $670 did not move up.

https://18xx.games/game/6108?action=763

**Comment by michaeljb** [comment]
While the share price was unchanged, the token did correctly move up in the market. The share price is only logged when the price changes; sometimes the token can move without a price change.

Screenshot at [762](https://18xx.games/game/6108?action=762):

![Screenshot from 2020-08-08 23-54-57](https://user-images.githubusercontent.com/1045173/89725960-ae5e5a00-d9d2-11ea-9b86-e7eb7736767c.png)

Screenshot at [763](https://18xx.games/game/6108?action=763):
![Screenshot from 2020-08-08 23-55-22](https://user-images.githubusercontent.com/1045173/89725972-c7ffa180-d9d2-11ea-9925-1fecc6e3aad5.png)

**Comment by MontyBrewster71** [comment]
Sorry, I missed that it was in the area where the price stays the same.
Thank you for looking into this.
