### ISSUE TITLE
[1846] - Steamboat Company can be assigned any time in OR instead of during private income step, allowing multiple Corporations to benefit in a single OR

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1397]
**Describe the bug**

When the Steamboat Company is owned by a player, it should only be assignable during the "private income step", or before any corporations operate.

Without this implemented, it will be possible for the Steamboat to be assigned to one corp, get it the bonus, and then be assigned to another corp so both get the bonus in one OR.

**Steps to reproduce:**

1. Start an 1846 game with Steamboat Company not removed from the game
2. Have the owner of the Steamboat Company assign it when it is their turn to operate a corporation

sample game JSON: https://gist.github.com/michaeljb/d170e9aa2a8820593f1064c9b8bf7813

Thanks @wcraigtrader for originally pointing out this timing issue in https://github.com/tobymao/18xx/issues/1316; for #1396 it was easier to solve the "multiple times in an OR" part of the issue, and put off the "private income step" part for later.

**Comment by michaeljb** [comment]
Without this implemented, it will be possible for the Steamboat to be assigned to one corp, get it the bonus, and then be assigned to another corp so both get the bonus.

**Comment by KillerOrca** [comment]
Here is Tom Lehmann's response for the intricacies of the Steamboat private.

https://boardgamegeek.com/thread/2015186/article/31693575#31693575

**Comment by eheiden** [comment]
We're in a game (https://www.18xx.games/game/6958) where IC in OR2.2 wants to move the steamboat to Toledo, but it doesn't look like I have the ability to shift the token as I should (even though IC bought the steamboat in a previous OR).  From Tom L in the linked thread above: "In phases I & II after being bought by a corporation the port token can be shifted during each OR before the corporation runs its routes."  Not sure if this is the same issue or a different one.

**Comment by michaeljb** [comment]
@eheiden Once I finish up #1443 (should be this weekend unless something unexpected happens IRL), you should be able to shift the steamboat correctly.
