### ISSUE TITLE
Sharp curve missing from available tile

### ISSUE THREAD

**Issue by McDood** [tobymao/18xx#14]
Sharp curve existing on Matsuyama (E2) between Imabari (F1) and Saijou (F3).
I select Saijou (F3)
Can only select a straight or a gentle curve. I believe a legit sharp curve could be build to link Matsuyama (E2) and E4

**Comment by tobymao** [comment]
![Screen Shot 2020-04-11 at 9 16 04 PM](https://user-images.githubusercontent.com/8205034/79060432-b3381a80-7c39-11ea-9ff7-38ffa75884cd.png)

not sure i could reproduce this but i was able to lay one after a small fix
