### ISSUE TITLE
1846- All players alerted as active player when a company in receivership

### ISSUE THREAD

**Issue by Shaz87** [tobymao/18xx#1408]
It would be useful if all players are alerted as if it is their turn when a company in receivership needs trains to be run. I have had a few async games go without moves being made for days as we all have been waiting for orange bars to trigger us to make a move.

**Comment by eheiden** [comment]
Just curious - this has the 1846 label, but there's no rules for receivership in 1846... was this label applied incorrectly?

**Comment by dfannius** [comment]
It's not called "receivership" in the rules, but this is referring to rule 7.14, where a corporation has no president due to a bankruptcy.

**Comment by tobymao** [comment]
receivership is the general terminology 18xx.games will use when a
corporation has no president
