### ISSUE TITLE
5546 Game Corruption

### ISSUE THREAD

**Issue by HazelrahBL** [tobymao/18xx#1413]
Trying to enter 5546 prints this message

> We're sorry this game cannot be continued due to GameError: Step Sell then Buy Shares cannot process {"type"=>"assign", "entity"=>"SC", "entity_type"=>"company", "id"=>203, "target"=>"GT", "target_type"=>"corporation"}
> View the last valid action (202)
> Please raise a bug report and include the game id (5546) and the following JSON data

**Comment by tobymao** [comment]
was a pinned game, deleting
