### ISSUE TITLE
Increase history navigation granularity (skip between companies)

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#1415]
Currently when browsing the game history, there are 6 controls:

* First Action (`|<`)
* Previous SR/OR (`<<`)
* Previous Action (`<`)
* Next Action (`>`)
* Next SR/OR (`>>`)
* Last Action (`>|`)

I would like to propose the addition of two more controls that would be available within ORs:

* Previous company
* Next company

This would mean adding new text buttons, and renaming some of the existing ones. I have two suggestions for how to implement these controls. The simplest, but more confusing, would be to just increase the number of chevrons:

* First Action (`|<`)
* Previous SR/OR (`<<<`)
* Previous company (`<<`)
* Previous Action (`<`)
* Next Action (`>`)
* Next company (`>>`)
* Next SR/OR (`>>>`)
* Last Action (`>|`)

Perhaps less confusing would be this:

* First Action (`|<`)
* Previous SR/OR (`R<`)
* Previous company (`C<`)
* Previous Action (`<`)
* Next Action (`>`)
* Next company (`>C`)
* Next SR/OR (`>R`)
* Last Action (`>|`)

This has the advantage that when you aren't in an OR, you can just drop the `C<` and `>C` options without confusing matters.

**Comment by ryandriskel** [comment]
While we did not implement this suggestion as proposed, a user now has the ability to Review from / Undo to any action in the log history, allowing the same result.
