### ISSUE TITLE
Some UI tweaks

### ISSUE THREAD

**Issue by justinkwaugh** [tobymao/18xx#1416]
Trying to make things more readable, just toying around with some mockups
<img width="1165" alt="Screen Shot 2020-08-11 at 11 56 20 AM" src="https://user-images.githubusercontent.com/1012189/89936849-45e5c780-dbe2-11ea-9692-4f594293e260.png">
<img width="294" alt="Screen Shot 2020-08-11 at 2 46 06 PM" src="https://user-images.githubusercontent.com/1012189/89936862-4c743f00-dbe2-11ea-82a3-1add7a6fbe3d.png">

This one is from my app:
<img width="185" alt="Screen Shot 2020-08-11 at 3 18 20 PM" src="https://user-images.githubusercontent.com/1012189/89941226-b7c10f80-dbe8-11ea-97c2-ad0f97e1c202.png">

source here:https://github.com/justinkwaugh/18www/blob/7610fcb6cb0dec3ec039f3c71d0cc3db305ba3ca/web/views/cell.html#L31

**Comment by tobymao** [comment]
i think we should keep the or history connected and have the corporation logos on the right hand side
