### ISSUE TITLE
Home/YourGames Menu

### ISSUE THREAD

**Issue by richardtempura** [tobymao/18xx#1418]
Just a quick request and let me know if its valid or not.

In a game, on the top menu (Game - Entities - Map -etc...) to the left of the Game option, it'd be nice to have a "Home - You Games" option. 
On iOs, we always need to back up to the 18xx.games logo to go back.

It's not much but it would be faster.

thanks guys, you rock!

**Comment by tobymao** [comment]
on ios you can tap the top of safari to jump to the top and click the logo
