### ISSUE TITLE
18TN - Privates do not block hexes

### ISSUE THREAD

**Issue by Bearcat89** [tobymao/18xx#1419]
I don’t know if this is just a text error or an actual bug, but Private companies do not block access to hexes in 18TN.

**Comment by perwestling** [comment]
Right, the implementation seems to be incorrect.

**Comment by perwestling** [comment]
@Bearcat89 - this has now been fixed, and will be available the next time a new version is deployed.

**Comment by perwestling** [comment]
It has been deployed so I will close this issue now.
