### ISSUE TITLE
18TN -Louisville Hex

### ISSUE THREAD

**Issue by Bearcat89** [tobymao/18xx#1424]
There should be a track segment in the Louisville hex that allows a route to bypass the L&N station there (both for purposes of train runs and track placement).  This should be similar to how the Altoona hex (PRR home hex) in 1830 is handled.

**Comment by perwestling** [comment]
![image](https://user-images.githubusercontent.com/2631151/89955521-802b8500-dc33-11ea-9859-c2046ba93825.png)

**Comment by perwestling** [comment]
Has been corrected and deployed.

![Louisville](https://user-images.githubusercontent.com/2631151/90681931-7b368900-e264-11ea-8521-d007de4ee9e3.PNG)
