### ISSUE TITLE
1846 Issue/redeem Streamlining

### ISSUE THREAD

**Issue by yraelrocks** [tobymao/18xx#1433]
Currently it’s a pain point having people use multiple undos to get back to the start. I know it’s not technically allowed but the rules suggest allowing due to the pain of
Undoing multiple times for a company because you're short or have spare cash at the end of the OR.

Either have a return to start of company turn button or have a button to allow issue/redeem Through out - obviously modifying payouts and cash auto.

**Comment by Mark894xx** [comment]
I would **much** prefer the **UNDO** button to only allow you to back up one step period. Too much abuse of the undo trying to get the "perfect" turn is feels wrong.  Part of 18xx is living with your mistakes

**Comment by Akado05** [comment]
There are many new players, to the site and to 18xx and 1846, and being able to undo fatal mistakes is very helpful and allows games to be more forgiving for new players.  Much better experiences if they don't have to sit through a multipelle-hour game knowing they lost simply because they forgot to issue shares before laying two tiles.

**Comment by Mark894xx** [comment]
Fair enough, But I have seen players do then redo the same turn from start to finish like three or four times.
That not fair to others waiting to take thier turn in a LIVE game

________________________________

**Comment by yraelrocks** [comment]
So I get the desire to shut down undos, but on a format like this where you have to flick between screens (at least on mobile devices) you might miss something important. I’d suggest playing with people who use it to a minimum unless by common agreement which is how I usually manage things.

If the undo button remains as is then it’s currently painful Especially for 46. The rules for 46 suggest you allow issue/redeem mid turn so reduce the amount of rewinding required. As it’s typically touted as a teaching title then newer players are going to head towards that among others and so likely be an on going issue.

**Comment by Mark894xx** [comment]
That all seems very reasonable to me...

**Comment by justinkwaugh** [comment]
Yes Issue / redeem should only be disallowed once trains are run as I recall
