### ISSUE TITLE
1882: Request abbreviation changes

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#1434]
In 1882 the assigned abbreviations are confusing as they stand.  

With both the Canadian National and the Canadian Northern in the game, that's an understandable problem.  However, the chosen on-site abbreviations don't match the usage in other games, some historical sources, or the spreadsheets/some paper copies.  

I would recommend:
CNR (or CN) -- Canadian National Railway
CNoR (or CNo) -- Canadian Northern Railway.  

Minor fix, but I think it'd help.

**Comment by dfannius** [comment]
In (the latest revision of) the AAG rules for 1882, the Canadian National Railway is CN and the Canadian Northern Railway is CNoR.

**Comment by tobymao** [comment]
matches closely to aag, closing

**Comment by TheExcalabur** [comment]
That "o" is _really_ important.  Please?  You effectively currently have the 'CN' and the 'CN Railway' in the game.
