### ISSUE TITLE
1846 cannot see chosen cards during draft

### ISSUE THREAD

**Issue by galfridus** [tobymao/18xx#1439]
When conducting a multiplayer draft in 1846, there is no way (outside master mode presumably) to see what cards I have already chosen. In a F2F game I would have the cards in hand, so this seems like reasonable information to make available.

**Comment by Akado05** [comment]
For awhile, if you scrolled down past the cards shown, you could see your own player card that had a list of what privates you'd previously drafted.  Did that go away?
![image](https://user-images.githubusercontent.com/68389380/90155075-82cfcc80-dd50-11ea-8d21-592e5a922dbc.png)

**Comment by tobymao** [comment]
nope, still works

**Comment by galfridus** [comment]
Did not see that during our draft.

**Comment by myNameIsFourteen** [comment]
This is an enhancement request to make this information available during the other player's turns. Not a bug report about the feature that exposes this information only during the current player's turn - which does still work.

The screenshot is of Player 3's turn and shows what Player 3 has picked thus far. At this point in the game, Player 1 can't review what they have. Making that information accessible is what is being requested.
