### ISSUE TITLE
Got “undefined method `price' for nil” when trying to buy the last 4D train on 18AL pinned to version d43f9f0c

### ISSUE THREAD

**Issue by ozgurbulbul** [tobymao/18xx#1446]
This happened when I was trying to buy last 4D on 18AL pinned to version d43f9f0c https://www.18xx.games/game/5459?action=549

When I try to buy the last train for WRA, I get the error “ undefined method `price' for nil” I tried to search for a similar problem that was fixed, but could not find anything.

**Comment by perwestling** [comment]
I reproduced this in a hot seat game.

**Comment by perwestling** [comment]
This bug has been fix and merged.
