### ISSUE TITLE
[1846] wrong cost for the B&O token teleport in Cincinnati

### ISSUE THREAD

**Issue by AlexandrePiquet** [tobymao/18xx#1449]
In a game of 1846 (ID: 6528), during the B&O OR, while the RR had only $90 and was not connected to Cincinnati (H12), I clicked on the hex to place a tile, and then on the city to place a token and the log showed a price of $20.
According to the rules (in GMT rulebook: 6.52), the price should be $20 for the tile and $100 for the token.

**Comment by michaeljb** [comment]
The token looks like it cost the right amount at https://www.18xx.games/game/6528?action=112

Was your game a different game ID?

**Comment by michaeljb** [comment]
Based on the B&O's cash total, I think you're talking about the tile lay in OR 2.2 https://www.18xx.games/game/6528?action=300

The B&O's token was laid long before, in OR 1.1 when ionicbox was the president, at https://www.18xx.games/game/6528?action=112

Note that in 2.2, the log doesn't mention the token being placed, and when a city slot is reserved, it just has the company's "sym", not their logo.
