### ISSUE TITLE
[1846] LSL private cannot be used during tile lay action

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#1453]
https://www.18xx.games/game/6699?action=108

When upgrading Cleveland using the LSL, you cannot do it during the tile lay action. If you do, it counts as one of your tile lays. You must advance past tile laying in order to use the LSL upgrade. While this works, it is very unintuitive and easy to miss.

**Comment by michaeljb** [comment]
If you click "Lake Shore Line" in the "Abilities" row, you can do the upgrade without it counting against the tile lay, during the normal tile lay action.

I cloned your game, backed up one tile lay, and then was able to use the LSL and then do the other tile lay - https://www.dropbox.com/s/oc5l2avcj8t3qg8/lsl.mp4?dl=0
