### ISSUE TITLE
1882: Unable to Purchase Exchanged Train from the Marketplace

### ISSUE THREAD

**Issue by iansc-18xx** [tobymao/18xx#1458]
Game 5446

At the end of the previous OR, a 5-Train was traded for a diesel by HBR.

It should be possible to purchase this 5-Train from the Marketplace, but it isn't, only new trains are available.

**Comment by dfannius** [comment]
In the AAG rulebook for 1882, the last paragraph of section 11.7 says:

> 5-trains and 6-trains that are traded in [for diesels] are removed from the game.
