### ISSUE TITLE
Spelling of Company at 235  18xx/lib/engine/game/g_1889.rb 

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#146]
https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1889.rb#L235

(Not sure if you want us doing PRs or if we're even allowed.)

**Comment by tobymao** [comment]
prs are welcomed and encourages!

**Comment by dfannius** [comment]
I already PRed a fix to this one, sorry @rheretic! (There were a couple of other tweaks I had been meaning to make.)
