### ISSUE TITLE
1846: illegal upgrade tile

### ISSUE THREAD

**Issue by mugnaio** [tobymao/18xx#1461]
https://18xx.games/game/6760?action=77 

in this action GT place a tile in D8 that is not legal.
According to rules "6.47 Connection: Some of the newly placed track of a non-city tile
must connect to a token of the corporation placing it. "

![D8](https://user-images.githubusercontent.com/6367880/90343622-a32eae00-e012-11ea-8e69-f31e1becc6f7.PNG)

**Comment by mugnaio** [comment]
in this tile the new track is the curve in the green tile (the straight track was already present) and it is not connected to a GT token.

**Comment by cheesinglee** [comment]
It appears the permissive upgrades can be done by independents, but not corporations.
