### ISSUE TITLE
18TN: We're sorry this game cannot be continued due to GameError: F11 is not upgradeable to TN2

### ISSUE THREAD

**Issue by ozgurbulbul** [tobymao/18xx#1463]
This happened on game 6361.  The exact error is: We're sorry this game cannot be continued due to GameError: F11 is not upgradeable to TN2. 

{
  "id": 6361,
  "description": "Open- few moves a day",
  "user": {
    "id": 307,
    "name": "Shaz"
  },
  "players": [
    {
      "id": 2359,
      "name": "oz"
    },
    {
      "id": 307,
      "name": "Shaz"
    },
    {
      "id": 2022,
      "name": "jsterphone"
    },
    {
      "id": 797,
      "name": "nigelsandwich"
    }
  ],
  "max_players": 4,
  "title": "18TN",
  "settings": {
    "seed": 1.3600054527849892e+38
  },
  "user_settings": null,
  "status": "active",
  "turn": 5,
  "round": "Stock Round",
  "acting": [
    2359
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 105,
      "entity": "oz",
      "company": "OWR",
      "entity_type": "player"
    },
    {
      "id": 2,
      "type": "bid",
      "price": 75,
      "entity": "Shaz",
      "company": "MCR",
      "entity_type": "player"
    },
    {
      "id": 3,
      "type": "bid",
      "price": 180,
      "entity": "jsterphone",
      "company": "LNR",
      "entity_type": "player"
    },
    {
      "id": 4,
      "type": "bid",
      "price": 45,
      "entity": "nigelsandwich",
      "company": "ETWCR",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "bid",
      "price": 50,
      "entity": "oz",
      "company": "ETWCR",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "bid",
      "price": 20,
      "entity": "Shaz",
      "company": "TCC",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "bid",
      "price": 55,
      "entity": "nigelsandwich",
      "company": "ETWCR",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "bid",
      "price": 60,
      "entity": "oz",
      "company": "ETWCR",
      "entity_type": "player"
    },
    {
      "id": 9,
      "type": "bid",
      "price": 65,
      "entity": "nigelsandwich",
      "company": "ETWCR",
      "entity_type": "player"
    },
    {
      "id": 10,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 11,
      "type": "par",
      "entity": "jsterphone",
      "corporation": "L&N",
      "entity_type": "player",
      "share_price": "90,1,4"
    },
    {
      "id": 12,
      "type": "buy_shares",
      "entity": "jsterphone",
      "shares": [
        "L&N_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "par",
      "entity": "nigelsandwich",
      "corporation": "SR",
      "entity_type": "player",
      "share_price": "65,3,3"
    },
    {
      "id": 14,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 15,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "L&N_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "buy_shares",
      "entity": "jsterphone",
      "shares": [
        "L&N_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "SR_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "buy_shares",
      "entity": "oz",
      "shares": [
        "L&N_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 19,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "L&N_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 20,
      "type": "buy_shares",
      "entity": "jsterphone",
      "shares": [
        "L&N_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 21,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "SR_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "buy_shares",
      "entity": "oz",
      "shares": [
        "L&N_7"
      ],
      "entity_type": "player"
    },
    {
      "id": 23,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "L&N_8"
      ],
      "entity_type": "player"
    },
    {
      "id": 24,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "SR_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 25,
      "type": "buy_shares",
      "entity": "oz",
      "shares": [
        "SR_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 26,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "SR_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 27,
      "type": "buy_shares",
      "entity": "oz",
      "shares": [
        "SR_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 28,
      "hex": "B15",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 29,
      "hex": "E10",
      "tile": "58-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 30,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 31,
      "hex": "E10",
      "tile": "4-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 32,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "L&N",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 33,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 34,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 35,
      "type": "undo",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 36,
      "hex": "B15",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 37,
      "hex": "B17",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 38,
      "city": "5-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 39,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "L&N",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 40,
      "hex": "F17",
      "tile": "57-0",
      "type": "lay_tile",
      "entity": "SR",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 41,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 42,
      "hex": "F17",
      "tile": "6-0",
      "type": "lay_tile",
      "entity": "SR",
      "rotation": 4,
      "entity_type": "corporation"
    },
    {
      "id": 43,
      "hex": "G16",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "SR",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 44,
      "type": "buy_train",
      "price": 80,
      "train": "2-1",
      "entity": "SR",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 45,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 46,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 47,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 48,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 49,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 50,
      "hex": "E10",
      "tile": "3-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 51,
      "hex": "E12",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 52,
      "type": "run_routes",
      "entity": "L&N",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B17"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 53,
      "kind": "payout",
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 54,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "L&N",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 55,
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 56,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 57,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 58,
      "type": "sell_shares",
      "entity": "Shaz",
      "shares": [
        "L&N_2",
        "L&N_5",
        "L&N_8"
      ],
      "percent": 30,
      "entity_type": "player"
    },
    {
      "id": 59,
      "type": "sell_shares",
      "entity": "Shaz",
      "shares": [
        "SR_5"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 60,
      "type": "par",
      "entity": "Shaz",
      "corporation": "GMO",
      "entity_type": "player",
      "share_price": "70,2,3"
    },
    {
      "id": 61,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 62,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "L&N_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 63,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 64,
      "type": "buy_shares",
      "entity": "oz",
      "shares": [
        "GMO_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 65,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 66,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "GMO_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 67,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 68,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 69,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 70,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 71,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "GMO_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 72,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 73,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 74,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 75,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 76,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "GMO_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 77,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 78,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 79,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 80,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 81,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "GMO_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 82,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 83,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 84,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 85,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 86,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 87,
      "hex": "F13",
      "tile": "58-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 88,
      "hex": "G12",
      "tile": "5-1",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 89,
      "city": "5-1-0",
      "slot": 0,
      "type": "place_token",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 90,
      "type": "run_routes",
      "entity": "L&N",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B17"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "B13",
              "B15",
              "B17"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 91,
      "kind": "payout",
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 92,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "L&N",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 93,
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 94,
      "hex": "H7",
      "tile": "6-1",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 95,
      "hex": "I6",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 96,
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 97,
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 98,
      "hex": "F7",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 4,
      "entity_type": "corporation"
    },
    {
      "id": 99,
      "hex": "F9",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 100,
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 101,
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 102,
      "hex": "H7",
      "tile": "6-1",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 103,
      "hex": "I6",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 104,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 105,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "GMO",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 106,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 107,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 108,
      "type": "buy_train",
      "price": 180,
      "train": "3-0",
      "entity": "SR",
      "variant": "3",
      "entity_type": "corporation"
    },
    {
      "id": 109,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 110,
      "type": "buy_company",
      "price": 60,
      "entity": "SR",
      "company": "ETWCR",
      "entity_type": "corporation"
    },
    {
      "id": 111,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 112,
      "type": "buy_shares",
      "entity": "jsterphone",
      "shares": [
        "SR_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 113,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 114,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "GMO_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 115,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 116,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 117,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 118,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 119,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 120,
      "hex": "F11",
      "tile": "TN2-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 121,
      "city": "TN2-0-0",
      "slot": 1,
      "type": "place_token",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 122,
      "type": "run_routes",
      "entity": "L&N",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B17"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "B13",
              "B15",
              "B17"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "G12",
              "F11"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 123,
      "kind": "payout",
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 124,
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 125,
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 126,
      "hex": "F7",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 4,
      "entity_type": "corporation"
    },
    {
      "id": 127,
      "hex": "F9",
      "tile": "9-3",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 128,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 129,
      "type": "run_routes",
      "entity": "GMO",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "F11",
              "F9",
              "F7",
              "G6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 130,
      "kind": "payout",
      "type": "dividend",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 131,
      "type": "buy_train",
      "price": 180,
      "train": "3-1",
      "entity": "GMO",
      "variant": "3",
      "entity_type": "corporation"
    },
    {
      "id": 132,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 133,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 134,
      "hex": "H15",
      "tile": "TN1-0",
      "type": "lay_tile",
      "entity": "SR",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 135,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 136,
      "type": "run_routes",
      "entity": "SR",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "F17",
              "G16",
              "H15"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 137,
      "kind": "payout",
      "type": "dividend",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 138,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 139,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 140,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 141,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 142,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 143,
      "hex": "F19",
      "tile": "9-4",
      "type": "lay_tile",
      "entity": "ETWCR",
      "rotation": 1,
      "entity_type": "company"
    },
    {
      "id": 144,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 145,
      "type": "undo",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 146,
      "hex": "F19",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "ETWCR",
      "rotation": 1,
      "entity_type": "company"
    },
    {
      "id": 147,
      "hex": "E20",
      "tile": "8-3",
      "type": "lay_tile",
      "entity": "SR",
      "rotation": 4,
      "entity_type": "corporation"
    },
    {
      "id": 148,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 149,
      "type": "run_routes",
      "entity": "SR",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "F17",
              "F19",
              "E20",
              "E22"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 150,
      "kind": "payout",
      "type": "dividend",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 151,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 152,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 153,
      "hex": "B17",
      "tile": "15-0",
      "type": "lay_tile",
      "entity": "L&N",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 154,
      "type": "run_routes",
      "entity": "L&N",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A16",
              "B17"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "F11",
              "F9",
              "F7",
              "G6"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "G12",
              "F11"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 155,
      "kind": "payout",
      "type": "dividend",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 156,
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 157,
      "type": "pass",
      "entity": "L&N",
      "entity_type": "corporation"
    },
    {
      "id": 158,
      "hex": "H7",
      "tile": "15-1",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 159,
      "type": "undo",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 160,
      "hex": "G6",
      "tile": "14-0",
      "type": "lay_tile",
      "entity": "GMO",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 161,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 162,
      "type": "run_routes",
      "entity": "GMO",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "F11",
              "F9",
              "F7",
              "G6"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "H7",
              "I6",
              "J5"
            ],
            [
              "H7",
              "G6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 163,
      "kind": "payout",
      "type": "dividend",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 164,
      "type": "buy_train",
      "price": 180,
      "train": "3-2",
      "entity": "GMO",
      "variant": "3",
      "entity_type": "corporation"
    },
    {
      "id": 165,
      "type": "buy_company",
      "price": 105,
      "entity": "GMO",
      "company": "MCR",
      "entity_type": "corporation"
    },
    {
      "id": 166,
      "type": "buy_company",
      "price": 30,
      "entity": "GMO",
      "company": "TCC",
      "entity_type": "corporation"
    },
    {
      "id": 167,
      "type": "pass",
      "entity": "GMO",
      "entity_type": "corporation"
    },
    {
      "id": 168,
      "hex": "H15",
      "tile": "TN1-0",
      "type": "lay_tile",
      "entity": "SR",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 169,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 170,
      "type": "run_routes",
      "entity": "SR",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "F17",
              "F19",
              "E20",
              "E22"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "F17",
              "G16",
              "H15"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 171,
      "kind": "payout",
      "type": "dividend",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 172,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 173,
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation"
    },
    {
      "id": 174,
      "type": "sell_shares",
      "entity": "oz",
      "shares": [
        "L&N_4",
        "L&N_7"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 175,
      "type": "sell_shares",
      "entity": "oz",
      "shares": [
        "GMO_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 176,
      "type": "sell_shares",
      "entity": "oz",
      "shares": [
        "SR_4",
        "SR_6"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 177,
      "type": "par",
      "entity": "oz",
      "corporation": "TC",
      "entity_type": "player",
      "share_price": "70,2,3"
    },
    {
      "id": 178,
      "type": "undo",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 179,
      "type": "par",
      "entity": "oz",
      "corporation": "IC",
      "entity_type": "player",
      "share_price": "70,2,3"
    },
    {
      "id": 180,
      "type": "sell_shares",
      "entity": "Shaz",
      "shares": [
        "GMO_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 181,
      "type": "par",
      "entity": "Shaz",
      "corporation": "TC",
      "entity_type": "player",
      "share_price": "65,3,3"
    },
    {
      "id": 182,
      "type": "buy_shares",
      "entity": "jsterphone",
      "shares": [
        "GMO_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 183,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 184,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "L&N_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 185,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    },
    {
      "id": 186,
      "type": "buy_shares",
      "entity": "oz",
      "shares": [
        "IC_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 187,
      "type": "pass",
      "entity": "oz",
      "entity_type": "player"
    },
    {
      "id": 188,
      "type": "buy_shares",
      "entity": "Shaz",
      "shares": [
        "TC_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 189,
      "type": "pass",
      "entity": "Shaz",
      "entity_type": "player"
    },
    {
      "id": 190,
      "type": "buy_shares",
      "entity": "jsterphone",
      "shares": [
        "L&N_8"
      ],
      "entity_type": "player"
    },
    {
      "id": 191,
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player"
    },
    {
      "id": 192,
      "type": "buy_shares",
      "entity": "nigelsandwich",
      "shares": [
        "SR_7"
      ],
      "entity_type": "player"
    },
    {
      "id": 193,
      "type": "pass",
      "entity": "nigelsandwich",
      "entity_type": "player"
    }
  ],
  "loaded": true,
  "created_at": 1597182777,
  "updated_at": 1597613154
}

**Comment by tobymao** [comment]
mid pin, works now
