### ISSUE TITLE
1846 emergency train buying

### ISSUE THREAD

**Issue by g18xxperson** [tobymao/18xx#1465]
When one player entered emergency train buying for the NYC, a bunch of strange things happened. There was 5 shares of the NYC in the pool at the time. The person was doing the emergency train buying had 5 IC and nobody else had any shares of that company. For some reason, they were allowed to sell everything they had. The IC was able to have no director because of this as well as the transfer of the NYC. All of their money got sent into the NYC. The game id is 6822 for a reference.

**Comment by perwestling** [comment]
[6822.txt](https://github.com/tobymao/18xx/files/5082273/6822.txt)

**Comment by michaeljb** [comment]
What's the problem? All these strange things are straight from the rules :wink:

See pages 10 and 11 - https://s3-us-west-2.amazonaws.com/gmtwebsiteassets/1846/1846-RULES-GMT.pdf

If you find something specific that the site did wrong, let me know, but it looks to me like this case was handled correctly.
