### ISSUE TITLE
1846 - buying President's share from market disappears a share from the game

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1469]
https://www.18xx.games/game/6822?action=658 (copied to a [gist here](https://gist.github.com/michaeljb/7ac19622f73dfc9fb76af817151360ef))

DrAwesome buys a second share from the market, becoming the president of the IC, which had been in receivership. There should be one share left in the market, but that share has apparently disappeared; the game reports 4 in the treasury, 2 held by DrAwesome, and 1 each held by 18xxperson, Mark894, and adam, for a total of 9 shares.

On the IC's turn, they were presented the option to redeem a share, but could not actually redeem it, and could not skip that step without hitting a GameError

**Comment by crericha** [comment]
Okay, so the game lets DrAwesome buy the president share outright, paying 2x the market price; however, it only shows him owning 20% of the company, when it should be 30%. His cert count of 8, confirms the game recognizes him as the owner of the IC. So my guess is the game tried to exchange his 10% share with the 20% in the market, but instead the 10% share got lost someplace.

I think I see two issues here:
1. The 20% share should not be purchasable outright from the market. DrAwesome should only be paying for a single share, not a double share.
2. The logic to exchange the the single share for the double share has a bug where the 10% share doesn't end up in the market.

**Comment by crericha** [comment]
The share class knows which share is the president share, so my thinking is there should be logic around dealing with purchasing the president share from the market.

1. If you own no shares of the corporation, then you should not be able to buy the presidents share.
2. If you own 1 share less than the amount it takes to own the corporation (assuming logic to change presidency is correct), then you should pay 1x market price and exchange you additional shares for the presidents share. I'm being intentionally generic here as games like 1880 have 30 or 40 percent presidents shares.
