### ISSUE TITLE
18AL not allowing lay of tile #6

### ISSUE THREAD

**Issue by dragon12** [tobymao/18xx#1473]
I'm not sure when in this game this started, but if you click on West Point (J7) to lay track you don't get tile #6 as an option even though the manifest says there are three available:
https://www.18xx.games/game/6602?action=437

**Comment by tobymao** [comment]
tile 6 had a label put onto it at some point and it was never removed, so it cannot be upgraded, we need to make sure the temporary labels are removed when upgraded
