### ISSUE TITLE
Broken transaction recovery

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#148]
Hotseat three player game.  Player 2 IPO's KO at 70 in one round, tries to buy an additional share in a subsequent round but is short of cash.  Gets an error, but the "game" page now shows KO as having 10 shares in IPO and no stock price.  The player 2 display still showed the correct balances, as did the player and corporation tabs.
Playing several rounds eventually got the board back in sync

Clone this game to play around in hotseat mode
Clone Game
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Mitsubishi Ferry",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Sumitomo Mines Railway",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "Mitsubishi Ferry",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "Ehime Railway",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Sumitomo Mines Railway",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "Dougo Railway",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "company": "Mitsubishi Ferry",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "company": "South Iyo Railway",
      "price": 80
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "corporation": "AR",
      "share_price": "75,3,3"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "corporation": "IR",
      "share_price": "80,2,3"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "corporation": "KU",
      "share_price": "80,2,3"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "corporation": "TR",
      "share_price": "75,3,3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "share": "IR_1"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 20,
      "corporation": "SR",
      "share_price": "70,4,3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 23,
      "corporation": "KO",
      "share_price": "70,4,3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 26,
      "share": "KU_1"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 29
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 31,
      "share": "AR_1"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 38
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1889",
  "description": "glenntest",
  "max_players": "3",
  "id": "hs_1587848937",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-04-25"
}

**Comment by tobymao** [comment]
this can be fixed by doing a clean refresh of the game state when an error is received
