### ISSUE TITLE
18TN - Incorrect Reporting of Civil War in OR1

### ISSUE THREAD

**Issue by Bearcat89** [tobymao/18xx#1487]
- Operating Round 1.1 (of 1) --
Bearcat89 collects $5 from Tennessee Copper Co.
JaxHammerHex collects $10 from East Tennessee & Western Carolina Railroad
sadknight collects $15 from Memphis & Charleston Railroad
MontyBrewster71 collects $20 from Oneida & Western Railroad
L&N places a token on B13
Bearcat89 operates L&N
L&N spends $60 and lays tile #9 with rotation 1 on B15
L&N lays tile #5 with rotation 1 on B17
L&N places a token on B17 (Lexington) for $40
L&N skips run routes
L&N does not run
**L&N's run is ignored due to Civil War**
L&N's share price changes from $100 to $90
L&N buys a 2 train for $80 from The Depot
L&N skips buy companies
SR places a token on F17
JaxHammerHex operates SR
SR spends $40 and lays tile #57 with rotation 0 on F17
SR lays tile #8 with rotation 4 on E18
SR skips place a token
SR skips run routes
SR does not run
**SR's run is ignored due to Civil War**
SR's share price changes from $65 to $55
SR buys a 2 train for $80 from The Depot
SR passes buy trains
SR skips buy companies

This may just be a reporting issue and have no issue on actual game play, but it DID catch my eye.

**Comment by perwestling** [comment]
This has been fixed and deployed so now it should be ok.
