### ISSUE TITLE
Automatically pass my turn within the current stock round

### ISSUE THREAD

**Issue by janhartigan** [tobymao/18xx#1489]
In many of the games I play, we frequently have one or two people who don't have a lot of options left in the stock round and just want to pass all subsequent turns for the remainder of that stock round, while other players are performing other actions.

I imagine this could be in the form of a checkbox that says something like "pass my turn for the rest of this stock round".

**Comment by dfannius** [comment]
Indeed! This is in the system as #209, which is more complicated, but people usually mean "automatically pass unless something interesting happens", not "automatically pass now matter what".
