### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#149]
Nearly had an issue today where I thought I had lost my password, but luckily it actually was in my password manager, just saved under the IP for the old server rather than "18xx.games".

But, sooner or later this will happen to a user who won't be able to recover their password, so we'll want to be able to automatically email them with a short-lived, one-time link to set a new password.

**Comment by tobymao** [comment]
i have code to do this in rollingstock, haven't implemented it yet

**Comment by cfreeman1305** [comment]
Implementing it would be great, because I am one of those schmucks who mistyped their password the first time and I need to reset it.

**Comment by mkarbowiak** [comment]
> Implementing it would be great, because I am one of those schmucks who mistyped their password the first time and I need to reset it.

I second that
