### ISSUE TITLE
Enhanced endgame experience - stats on the game progression

### ISSUE THREAD

**Issue by jenspoder** [tobymao/18xx#1490]
One of the exciting things in 18XX is speculating about why a game ended the way it ended and discussing it in the game group. 

Who was ahead?
What companies dominated?

In classic civilization there is this amazing chart showing the development of power through the game. Something similar would be amazing. 

To get a chart with

- Value of companies round for round
- value of players round for round
- accumulated dividends per company round for round

It could be added in the email from the game. Or as a screen online.

**Comment by rally5** [comment]
Yeah I like this idea.  Would also like something that encouraged more endgame discussion with the game log.

**Comment by tom-blight** [comment]
I really like this idea - graphs showing player & company value over each round would be a great tool. Some 'dreamsheets' used by board18 have a similar feature.

**Comment by bridger15** [comment]
I was just thinking about this and came to post the suggestion.  A simple set of line graphs visible at the end (or even during, I guess?) would be a really cool feature.

**Comment by jenspoder** [comment]
My friend Nicolai did a graph of individuel player net value based on the spreadsheet data in the end of a game we played

![Skærmbillede 2021-01-31 kl  09 51 54](https://user-images.githubusercontent.com/345719/106379105-f79fcd00-63a9-11eb-8413-77a74459aa93.png)

This is of course very basic, but It gave a sense of the actual performance through the whole game. See if you can spot the D-train rush.

**Comment by scottredracecar** [comment]
There have been several ideas for endgame graphs and such, but no one has stepped up to work on one that Toby has gone for, closing for now.

**Comment by pbrinkmeier** [comment]
Hi, I would like to work on this. I see two ways to approach this:

* Use any established charts library such as D3, Chart.js, etc. and do the rendering using that. This approach would probably require weighing the options and choosing a library that's not too overkill (we only need a simple line chart).
* Render the chart manually using the canvas API or, imo preferably, inline SVG. Inline SVG is [pretty well suported](https://caniuse.com/svg-html5). This would require more code but has the advantage of being very lightweight and customizable.

In addition to that we would need to figure out when to render the graph. I'd suggest a toggle button similar to the "show delta values" one that's turned off by default and can be turned on whenever people want in the spreadsheet tab.

**Comment by pbrinkmeier** [comment]
Tagging @tobymao for comments (not sure if notifications show up for closed issues).

**Comment by tobymao** [comment]
the bar for getting something like this in would be very high.

**Comment by pbrinkmeier** [comment]
I'm willing to put the work in. I currently use a bookmarklet i developed for this purpose but everybody i share it with asks whether it could be integrated into the page instead.
Which of the things above would you favor? Personally I believe the graph could be simple enough for just a manually generated SVG.

**Comment by tobymao** [comment]
a small open source javascript library

**Comment by pbrinkmeier** [comment]
So a cursory google search doesnt yield any libraries that only do line charts. So I guess this is a question about how "small" is qualified. There are lots of open source charting libraries, but all are at least 20kb (minified + gzipped). What would be the mode of deployment? Adding it to `assets/vendor`? Many libraries also assume some sort of contrived frontend build process, so they come with a large initial bundle size that they assume to be cut down by the compiler. Not sure if Opal is compatible with this.

We also need to consider the compatibility of Snabbdom and the chosen library. I assume its quite possible to just add some content to the DOM manually but not sure how that fits in the general rendering model.

So the next set of questions:

- What size would you consider ok for a third-party library?
- What's the preferred deployment, e.g. third-party `script` tag or rather adding it to `assets/vendor`?
- What would you think of a small implementation that does only one job (line charts) in Opal using snabbdom?

Btw thanks for taking the time to talk this through, if you consider this too much work for small gain I'm happy to continue using my bookmarklet. But if I can contribute something I'd like to.
