### ISSUE TITLE
18TN: Map upgrade breaks down if Tile manifest shown inbetween

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1494]
Consider the below game.

This bug can be reproduced by doing the following:

1. Select "Tiles" and click on any tile
2. Select "Game" and click on any tile

The expected upgrade choices do not appear but instead the text "Undefined".

Repeating this in a local installation does how the exception:
![image](https://user-images.githubusercontent.com/2631151/90951905-7d186c00-e45f-11ea-91cd-3bfd607a7a5f.png)

Tried to repeat this with 18AL, WRA but did not get the same error. The difference between 18AL and 18TN is how the latter still adds the N label. But problem did occur for me even if removing the track.rb and track adding code in 18TN, so it must be something else.

Game data: https://gist.githubusercontent.com/michaeljb/781782d0aecd3b342411dd9cc4136986/raw/90dc4bb5cb914556289f05e1ce3f6fdb1e62ffcf/1494.json

**Comment by jenf** [comment]
Still reproducible.

**Comment by ryandriskel** [comment]
I have been able to trigger this in 18AL and 18CO as well. I don't think it is 18TN specific.

**Comment by ryandriskel** [comment]
Interestingly, I got this error when cloning an active 18TN game and trying it, as opposed to the insertBefore error.

<img width="387" alt="Screen Shot 2020-10-26 at 2 52 00 PM" src="https://user-images.githubusercontent.com/15675400/97227261-d754e680-179a-11eb-8876-4aeb8d90e42e.png">

**Comment by michaeljb** [comment]
Before #2410, I was able to reproduce this in multiple titles. In one case, the tile selector did appear correctly when clicking on the map, but before then there was still an "undefined" string that rendered on the map.
