### ISSUE TITLE
1846 forced train purchase didn't allow buy of a 7/8

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#1497]
During OR4.1 of game 7051 BO had to force buy a train, but after selling the minimum shares required for the 6T (800$) it wouldn't allow the sale of more shares to buy the 7/8 (900$), namely the NYC share that should have been possible, of even up to 2*BOs since that wouldn't change the presidency

**Comment by michaeljb** [comment]
hmm I think we might need a new constant in`Game::Base` for this one, something like a `true`/`false` `EBUY_MUST_BUY_CHEAPEST`, or maybe `EBUY_CAN_BUY_WHAT` that could have values of `:cheapest`, `:any`, or whatever other options are out there.
