### ISSUE TITLE
Ohzu not upgradeable after purchasing Ehime Railway

### ISSUE THREAD

**Issue by AndrewChenUoA** [tobymao/18xx#150]
Hello! Firstly, thank you so much for making this - it is awesome to have a new platform to play 18xx games on and we are very excited down here in New Zealand. 

I've checked #72 and #48 and this seems to be slightly different. In game 102 (https://www.18xx.games/game/102), the TR buys in the Ehime Railway in OR2.2. It has no track near Ohzu, and so Ohzu doesn't highlight, and clicking on Ohzu doesn't show any options to lay track. I've checked the full rules and it says that the selling Player may place the tile, so I don't think there is a restriction that the company has to be connected to Ohzu. 

I tried this buying the Ehime Railway as the last action before the end of the turn, and also clicking Undo and doing it at the very beginning during track laying, but wasn't able to upgrade Ohzu in either case. Not a huge deal in this game and we are happy to play on but might be worth checking. Browser is Chrome.

**Comment by tobymao** [comment]
i just cloned your game and tried. you have to do it 'immediately' so as soon as you buy it, the next action must be to click on the company and then place the tile.

**Comment by AndrewChenUoA** [comment]
It's not doing it for me - I tried this on both mobile and desktop, and it's just not highlighting the tile and clicking on Ohzu is doing nothing.

![image](https://user-images.githubusercontent.com/4627037/80292211-ea193f00-87a8-11ea-9cd7-4267ac3951c8.png)

**Comment by tobymao** [comment]
You need to click Ehime first in the companies tab. Then the tile will be highlighted. I need to make this more intuitive, I have an issue already for that.

**Comment by AndrewChenUoA** [comment]
Ah, I see - I don't think I saw that explained anywhere... Thanks for clarifying that.

**Comment by tobymao** [comment]
It's not explained :D
