### ISSUE TITLE
Skip of buying companies in log even though all companies have been closed.

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1511]
Observed this in an 18 MS test. Might be worth checking out if it is a general thing.
The issue is a minor one: Should not have to see the skip of buying companies in the log after companies have been closed.

![image](https://user-images.githubusercontent.com/2631151/91034230-f4d3cb80-e604-11ea-96b2-86d5d55a50fb.png)

(In 18 MS it is the 6 train buy that closes the companies, not the 5 train.)

**Comment by jenf** [comment]
Don't think we'll ever change this behaviour.
