### ISSUE TITLE
[1846] Big 4 discount to less than 0. 

### ISSUE THREAD

**Issue by mkkohls** [tobymao/18xx#1519]
Game number 7582
https://gist.github.com/mkkohls/5e10fc3529d04dc95e8d0cad366f4b52
**Describe the bug**

During the private company draft the last company available was the big four. Its cost is $40 + $60 debt. It shows as $100 initially as that is what the player would pay. The debt is paid after it's bought not as part of the price. 

When players pass the $10 discount applies. Since the price is $40 not $100 once players have passed 4 times the price would now be 0. There is no discount on the debt.

 Per section 3.22 and  3.23 of the 1846 rules.
_3.22 A player must take it 
for free if its price is reduced to $0. 
3.23 After distributing the Private Companies, all players reveal 
and pay for them. Remove the player cards. Give the Michigan Southern and Big 4 Independent Railroads each its initial treasury, equal to its list price (without debt), even if its actual price was reduced below this, train, and token. Then, begin the first Stock Round._

It lets players keep passing after the price has gone to 0, $60 in your implementation. It should force the player to buy it.

**Comment by mkkohls** [comment]
The rule is clarifies in this bgg thread.

**Comment by tobymao** [comment]
aa35f42f3
