### ISSUE TITLE
18Chesapeake: Teleport is not according to the rule book

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1520]
As was observed in 18GA, if a corporation that owns the token teleport company puts down a regular token (one that is connected normally) the game will do this for free as if the ability was used. There might be reasons for the player to want to pay for the token (especially in the general case where the private is closed) and therefor it should be an explicit choice.

Here is a hotseat game where PRR just have put down a token in D2, after buying Chesapeake & Ohio Channel company.
As can be noted, PRR does not pay anything for the token, and it was not put down using an explicit token.
It is also presented as PRR puts a token - if explicit maybe it should be the private putting down the token?

It is a bit more complicated in Chessy as the ability is actually to teleport the tile and thereafter optionally put down the token. So maybe the teleport token implicit should only be used if there is no connection to another token for the company?
And the user should then have the option to click on the ability to put down a token for through if s/he wants.

Trying it further I can see that the tile laying in Chessy does appear as a choice, The token choice is not obvious (in case of other corporation owning the private) but clicking on D2 puts a token there even though it is not high lighted. 

At least the teleport of the token can only be done in the same OR that the tile was layd. If a corporation does put down the token in a future OR it does have to pay for it, so it is a difference from the GA bug.

Another problem I discovered. If the token lay activity is started, and then buying the private, Berlin (D2) is not highlighted. Doing refresh and it does appear.

https://gist.github.com/michaeljb/78b62b37411735d21b7e4d6b5fb4dc77

**Comment by perwestling** [comment]
There are 3 problems here:
1. Activation of ability differ a bit from newer titles on 18xx.games
2. Implicit free token if tokening in Berlin without teleport
3. The hex not highlighted unless you refresh

1. This seems to be acceptable.

2. Can be seen as a feature. The corner case where you actually want to spend for this is not very common. 

3. Might be something to fix. Do not know if it is browser relates.

So we should consider if we should close this? Anyway, it is low prio.
2 - I will use when implementing the token abilty of 18GA.

**Comment by tobymao** [comment]
There is a bug with the teleport ability. It is applied implicitly based on the hex and tile but it should also check that the company is the entity laying the tile. Currently the corporation lays the tile because it is seen as a normal tile lay.

To fix, we'd need the step/tracker.rb to allow the company to lay in place of the corporation if it has the teleport ability.

**Comment by michaeljb** [comment]
Found another issue, if the owning corporation can still teleport after the company closes even if it hasn't done so by the time the 5T is bought. See action 238 in this game - https://gist.githubusercontent.com/michaeljb/56bb46d7eb6cfde46c66ffc89e50a692/raw/31f0ce9f74822240004105fe966ab522a82a0359/teleport_persist_through_closure.json
