### ISSUE TITLE
LV cant run between Allentown - Philadelphia, nor to NY.

### ISSUE THREAD

**Issue by akvik** [tobymao/18xx#1521]
In game 7052 I try to run two 3-trains for LV. See image:
https://www.dropbox.com/s/winc1hb9bszlpzu/Screenshot%202020-08-25%20at%2009.30.18.png?dl=0
From this, I can't neither run a train between allentown and philly, nor Allentown - T&A - New York. PRR has tokens in Allentown and Philly but that shouldn't prevent me from running TO Philadelphia. Not to NY either. 

Also, I can go to Easton but not further to T&A with my 3T.

Is this a bug or have I completely misinterpreted the rules?

**Comment by jenf** [comment]
Cloned game and can run it fine between those locations.

LV runs a 3 train for $100 (L2, K3, J2)
LV runs a 3 train for $100 (J4, J2, K1)

**Comment by akvik** [comment]
I must be doing something wrong - I'm on Firefox on Mac and I cannot mark off those locations no matter what. But it's good to know that it works for you - I will try with a different browser next time around.

Thank you for you swift reply!

**Comment by dfannius** [comment]
Note that when a hex has multiple revenue locations (like Philadelphia and Trenton & Amboy), you have to click right on the revenue location to go there, not just click on the hex. That's usually the first thing to check in these cases, although it sounds like you were trying pretty hard.

**Comment by dfannius** [comment]
(I confirmed that I am able to run those routes with a clone of your game on Firefox 79.0 on macos 10.4.6.)

**Comment by akvik** [comment]
Thanks, didn’t try right click!
