### ISSUE TITLE
18Chesapeake map/tile rendering

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#153]
There are a few board/tile features that Chessie has that 1889 does not. I'll keep track of them here.

- [ ] OO tiles
- [ ] offboard locations spanning more than one hex (Pittsburgh and W Virginia Coal)
- [ ] companies that block more than one hex (B&S, C-P)
- [ ] multiple towns in one hex -- rendering the yellow tiles for this somewhat works, need to get "white" tiles (i.e., starting hexes on the map) working

**Comment by tobymao** [comment]
i don't know  that we should complicate the system to support offboard locations spanning more than one hex... we'll see

**Comment by sparr** [comment]
Would it suffice to have a way to flag two offboard locations as being linked? So they might render as a bunch of adjacent red hexes, but the route planner would know they couldn't both be on the same route?

PS: Can't wait til we get to this thing... http://www.diogenes.sacramento.ca.us/18xx_net/tiles/485.gif

**Comment by kelsin** [comment]
Double dits on the map and on track should be good now. Need to abstract that logic for OO's and will be doing that ASAP.

**Comment by michaeljb** [comment]
Closing this, it's covered by other issues now:

* OO tiles - #388 and #389
* offboards - #391 
* multi-hex blockers are done; enlarged in #387 but we're sticking with rendering the blocker graphic twice instead of having one graphic cover both hexes
* as kelsin's comment indicates, are basically working (there is still some work, to do, see #264 )
