### ISSUE TITLE
Improve readability of log/history

### ISSUE THREAD

**Issue by justinkwaugh** [tobymao/18xx#1531]
Currently when returning to the game, parsing the game log to see what happened is difficult because it's just a bunched together, indistinguishable blob of info.  My suggestions are to:

1.  Remove extraneous info.  It is not necessary to say that a company skipped buying companies for instance.
2. Group and emphasize actions like operation of a company.  I've attached a mockup.

<img width="1020" alt="Screen Shot 2020-08-27 at 9 24 26 AM" src="https://user-images.githubusercontent.com/1012189/91452532-ad3f8080-e84c-11ea-8efe-0d46e5a57647.png">

Chat messages obviously can interrupt the operation of a company.  Personally I would prefer they just be placed outside the grouping.  A toggle could also be provided to switch between a flat mode and a grouped mode.

**Comment by jenf** [comment]
The skip log can be useful for a "Yes, we know you can't do anything"

**Comment by justinkwaugh** [comment]
it's a lot of noise for the non current player though... as a comparison here is the actual log for the above mockup

<img width="1003" alt="Screen Shot 2020-08-27 at 9 28 42 AM" src="https://user-images.githubusercontent.com/1012189/91453459-be3cc180-e84d-11ea-837d-5a4332af8d8e.png">

**Comment by justinkwaugh** [comment]
You could further reduce it by just saying "TR pays out ¥82/share" instead of "TR pays out ¥820 = ¥82 x 10 shares"

**Comment by jenf** [comment]
Useful to know if it's a 2, 5 or 10 share company.

**Comment by justinkwaugh** [comment]
I don't see why if the payout is calculated for you for each person

**Comment by jenf** [comment]
Splitting into two, one for grouping one for reducing verbosity (but not content of the log)

**Comment by jenf** [comment]
Suggestion of how to implement

At the start of an entity operating open a group, when it finishes pop the group.
Same with stock rounds.
This log grouping would need to be done in the rounds.

Group all of that text within the group.
Migration log messages to the end of the group.

**Comment by tobymao** [comment]
some people want to know each item that was skipped which is why it's implemented.

**Comment by justinkwaugh** [comment]
Interesting.  Seems like a really low signal to noise ratio for most
people.  Unless you are talking about the current player during their turn,
which I understand.  From a historical sense though for other players it
just seems like clutter.

**Comment by khamsoul** [comment]
As a first time player I can confirm that the verbosity was very helpful for learning the game, though I can see say having a button to toggle verbosity as a desirable feature.

**Comment by perwestling** [comment]
Is it helpful to show that an action is skipped if it cannot ever be performed?
I am thinking of 
"Fr skips buy companies" when all companies have been closed?

**Comment by giovandc** [comment]
I think that the log could be improved by:
- Adding timestamp to the moves, useful for async games
- Not skipping anything from the log: if I don't run trains, it should be clear in the log that I didn't run any train, and that I paid 0 dividends, and that the company value on the stock market decreased. It's makes it extremely easier for players in async games to understand what happened between one move and another.
