### ISSUE TITLE
Reduce verbosity of the log at certain points

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1532]
Split from #1532 

The skip log can be useful for a "Yes, we know you can't do anything"
But merging them would be useful

Stock price payouts can be condensed
"N&W skips place a token, run routes"

TR pays out ¥820 = ¥82 x 10 shares
LenaC receives ¥82 = ¥82 x 1 shares
Jen Freeman receives ¥492 = ¥82 x 6 shares
Bjorsa receives ¥82 = ¥82 x 1 shares
kiwijohn receives ¥164 = ¥82 x 2 shares

Could be
TR pays out ¥820 = ¥82 x 10 shares (LenaC receives ¥82, Jen Freeman receives ¥492, Bjorsa receives ¥82, kiwijohn receives ¥164)

**Comment by tobymao** [comment]
no need to to compress skipping of steps. dividends should be easy though

**Comment by dfannius** [comment]
Even briefer: TR pays out ¥820 = ¥82 × 10 shares (¥82 to LenaC, ¥492 to Jen Freeman, ¥82 to Bjorsa, ¥164 to kiwijohn)

Also, if we're not listing the number of shares each player has, I would drop the "× 10 shares" part. It's not like the payout is calculated by multiplying ¥82 by 10.

**Comment by jenf** [comment]
#1511 would reduce the skip a bit.
