### ISSUE TITLE
18GA problem running train

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1536]
In game 7260 I am running the CoG 2 train. I get the error “cannot run another corporation’s train, refresh.” Toby says "there's a bug, probably can't find the train you're trying to run." I suspect it is related to the free 2 train that was granted by the Ocilla Southern RR company.

**Comment by perwestling** [comment]
I reproduced the error. It seems the train was mixed up so that another 2 train (W&A) is chosen for the run.

**Comment by ChrisTheCat** [comment]
W&A bought one of the CoG's two 2 trains, one of which (I don't know which one) is the free one from the Ocilla Southern RR

**Comment by perwestling** [comment]
Bug fixed. I think the fix wont break any games when it is deployed.
