### ISSUE TITLE
View Train Roster / Depot in more useful places

### ISSUE THREAD

**Issue by justinkwaugh** [tobymao/18xx#1539]
Knowing the remaining train roster, at minimum the current type of trains remaining and upcoming is critical for many decisions throughout 18xx games.  Right now it's only in the "Info" tab.  I'd like to see it in the entities and spreadsheet view, but with only the type and remaining columns (and possibly rusting).  I think there is not a need for the full set of columns (that does belong more in the info tab).  There is too much tab switching involved to keep checking the remaining amounts.

**Comment by jenf** [comment]
Adding an Entity known as 'The Depot' might be a way to do this.

**Comment by jenf** [comment]
This is done.
