### ISSUE TITLE
unable to route 2 train b/t Uwajima and Yawa

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#154]
Chrome `83.0.4103.21 (Official Build) beta (64-bit)` (chromebook)

I wasn't able to route one of my two 2 train from Uwajima to Yawa (dit city) as the Uwajima company

The company has two 2 trains, and a token in Uwajima and the a token in Ohzu

The first one of the 2 trains is able to successfully route from Ohzu to the Yawa dit, but the second one consistently doesn't result in a colored line being created (trying in either order)

Am choosing the route(s) by clicking the Uwajima hex and then the Yawa hex

[json file here](https://gist.github.com/benjaminxscott/91106632eec13342b045206fb6f76048)

**Comment by tobymao** [comment]
you need to click every hex, will improve this later

**Comment by benjaminxscott** [comment]
thanks! pebcak on my side

Appreciate your work on the game implementation, its very nice
