### ISSUE TITLE
Request for a time-series plot of Value vs Time on the Entities tab

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#1549]
Thank you for creating 18xx.games, I had a great first game. I would really enjoy being able to see the Value of each player vs time on a graph. This could go somewhere in the Entities tab. I attached a rough mock-up. 
![mock_chart](https://user-images.githubusercontent.com/5924761/91652265-45568900-ea4a-11ea-81db-499d41c31bcc.png)

**Comment by Bearcat89** [comment]
I did something similar to this when I created Excel spreadsheets for tracking teaching games that I ran in the forums over on BGG and it is actually quite helpful.

![image](https://user-images.githubusercontent.com/69537256/92239322-c5d11b80-ee88-11ea-9f07-aeb042597086.png)

**Comment by khamsoul** [comment]
Yes that's exactly what I was thinking of! Maybe having it on the spreadsheets tab makes more sense

**Comment by tobymao** [comment]
dup of #1490
