### ISSUE TITLE
Clicking on someone's username while queueing for a game kicks them out of the game

### ISSUE THREAD

**Issue by jftaylor21** [tobymao/18xx#155]
I started a new game and noticed that someone joined it. I saw a box around the username and was curious about what happened when I clicked on it. It looks like it kicked them out of my game which was unintentional.

It would be nice if there was an X on the username box or some other UI element that indicates that this will kick the person.

**Comment by daniel-sousa-me** [comment]
I made a PR to try to improve this. This is my first (of hopefully many) contributions. I hope everything is ok.
