### ISSUE TITLE
[1889] Buying trains from other players

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#1557]
* Multiplayer? Yes
https://www.18xx.games/game/7696
Possible every OR.

**Describe the bug**
Players can "buy" other players trains without the owner consent for the price set by buyer (1Y works just fine). In other words I can take from someone all trains and he/she can do nothing about it other than taking them back next round...

Possibly it also works for the private companies (didn't check yet)

**Comment by dfannius** [comment]
Yes, this is by design to make both the code and the interface simpler. Maybe there could be a notice saying that buying trains from other players may only be done with their permission, but in general we assume that players know the rules of the game.

**Comment by tobymao** [comment]
by design. you can also steal people's trains in real life, but it's not very nice!
