### ISSUE TITLE
[1889] port tile illegal placement

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#1558]
**Please provide**
* Multiplayer? Yes
https://www.18xx.games/game/7696?action=91

**Describe the bug**
TR (owner KrzysP) was able to place port tile in G10 while Mitsubishi Ferry was hold by another player (Sir_Yaro).

**Comment by tobymao** [comment]
@michaeljb is this fixed?

**Comment by michaeljb** [comment]
No the Mitsubishi Ferry is still on `any` time. To follow the rules completely, we'll need to add some more times that can be checked, like "between OR turns".
