### ISSUE TITLE
18MS: Map broken after recent update

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1562]
If I create a hotseat game of 18MS on 18xx.games, and then try to show the map, it crashes when trying to render the map.
![image](https://user-images.githubusercontent.com/2631151/91825614-c9706280-ec3c-11ea-99f6-34452f63db60.png)

**Comment by perwestling** [comment]
@roseundy It seems there is some problem with rendering after the latest changes.

**Comment by perwestling** [comment]
I think it is just to change CENTER to Base::Center at line 145. When I did that, I could now show the map of 18MS.

**Comment by tobymao** [comment]
can you push that change?
