### ISSUE TITLE
1846 C&WI token placement

### ISSUE THREAD

**Issue by cfreeman1305** [tobymao/18xx#1565]
In game 7893, a game of 1846, B&O purchased the private company C&WI, then placed the token in Chicago. However, they placed it in a spot other than the reserved C&WI slot. As far as I can tell, the token MUST be placed in the reserved spot. The C&WI card reads ""Reserves a token slot in Chicago (D6), in which the owning corporation may place an extra token at no cost." 

I do not see anywhere in the rules that this allows for placement of the token anywhere other than this reserved spot. Am I wrong, or is this just a mistake/oversight? 

https://www.18xx.games/game/7893?action=54

![Annotation 2020-09-01 102458](https://user-images.githubusercontent.com/64927350/91885944-6d5a0e00-ec3d-11ea-9bc6-495a60df5585.png)

**Comment by StormCrow42** [comment]
https://www.18xx.games/game/7480?action=159

**Comment by michaeljb** [comment]
Found a rules-breaking edge case--the reservation should disappear when the C&WI is bought in, and other connected corporations should be allowed to token in that spot if the owning corporation has not yet tokened. Will fix that as well.
