### ISSUE TITLE
Have you Considered Changing the Name to 18rr.Games instead?

### ISSUE THREAD

**Issue by Clacker76** [tobymao/18xx#1566]
Hello, Folks!

I'm writing as the letter x has such a negative connotation, especially online.  Have you considered registering 18rr.games as well as 18xx.games?

I think the games are great!  I also think the re-branding to 18rr reflects that these are railroad games, and would remove some of the stigma associated with the letter x and online.

Just a thought.  Thanks for the great work you've all done.  Since being introduced to 18xx, I have become a BIG fan.  I have anywhere from 1-6 games on the go in my spare time.

Thanks again!

Clacker76
aka Curtis

**Comment by tobymao** [comment]
heh thanks for the suggestion, but nope, not considering it.
