### ISSUE TITLE
[1889] Trading in Dougo Railway is not recognized as a valid action, ending stock round early

### ISSUE THREAD

**Issue by spenczar** [tobymao/18xx#1567]
The Dougo Railway private corporation can be traded for a share of Iyo Railway in 1889. If a player doesn't have enough money to buy any shares, and they cannot sell any shares (perhaps because it's the first stock round) but they _do_ have this corporation (and Iyo's par price has been set), then that player incorrectly gets auto-skipped during the stock round.

Game data example here: https://gist.github.com/spenczar/9fe2f6b3ac1f5ccb2707c911e58d31b

**Comment by tobymao** [comment]
this is behaving correctly, you can do it at any time, even on other people's turns

**Comment by spenczar** [comment]
In my particular case, the other two players also had spent all their money, so the stock round ended entirely. The first OR started, and Iyo had not been floated; as a result, a different railroad (UR, in my case) got to go first. I expected to be able to float IR at a higher par value and go first in the OR. Was that an incorrect expectation?

**Comment by tobymao** [comment]
it's a tricky issue. in that case, simply roll back right before the OR,
execute your action and continue.

**Comment by ckarlof** [comment]
> it's a tricky issue. in that case, simply roll back right before the OR, execute your action and continue.

This suggested workaround does not work particularly well in async games. If the president of the IR was intending to use the Dougo private to acquire their 6th share and SR1 automatically ended in the manner described here, the president of the IR might not discover this has happened until they are notified of their next turn during SR2. It would be pretty disruptive to the game to unwind the entire OR1.1 of the other companies to exchange the Dougo private, float the IR, and then replay all of OR1.1.
