### ISSUE TITLE
Spectating games list for easy access

### ISSUE THREAD

**Issue by myNameIsFourteen** [tobymao/18xx#1569]
It's easy to spectate a game on the site as long as I hang onto a link to the right game ID, but the site could make this a bunch easier.

I would like to be able to identify a game that I'm not playing in as one I'm interested in specatating, so that when I log into the site it appears in the list similar to active games that I am playing in.

**Comment by tobymao** [comment]
although it is not the exact feature you're looking for, we're planning to implement search in the future which would help with this. i don't think this exact request will make it through though, so closing for now
