### ISSUE TITLE
Tab title should be updated with game name (at very least)

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#157]
When you enter a game, the tab doesn't change. So if I'm in 5 games in 5 tabs, they will all just say "18xx.games." It'd be ideal if it said the game name and potentially the SR/OR and current player.

Thanks for the great work!

**Comment by sparr** [comment]
I tried to dive into this request tonight and got a bit stuck.

Here's what I figured out, I think...

https://github.com/tobymao/18xx/blob/master/assets/js/index.rb#L56 is where the current page title is rendered.

https://github.com/tobymao/18xx/blob/master/api.rb#L145 unfortunately seems to render the game state out to components before it gets handed over to Index

I couldn't suss out any way to get access to the game description from Index. It wouldn't be too hard to get the number out of app_route, but that would be hacky and mixing some logic where it doesn't belong.

Hopefully some fresh eyes, mine or another's, will make more progress on this.
