### ISSUE TITLE
Allow inspection of a title without playing it

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#1570]
When I am learning the rules of a new game that is implemented on 18xx.games, I find a game in progress, rewind to the beginning, and look at the privates, market, phase info, etc. It would be nice if there were a way to view all of that information in a read-only manner without finding an actual live (or dead) game to snoop on.

**Comment by dfannius** [comment]
Thanks, that's more convenient than rewinding the history. It would still be nice not to have to first find an active game of the title you're interested in.

**Comment by ChrisTheCat** [comment]
You can also just create a new hotseat (local) game yourself and play with
it.

**Comment by jenf** [comment]
Maybe "preview/1889" should give you that option
