### ISSUE TITLE
1836jr30 - CdFdN is not getting to do a run

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#1571]
It's the Operating Turn for CdFdN, and it's got a route and a train, but the system is skipping the run trains and going straight to buy trains.

https://gist.github.com/rheretic/0ddafd1359906d96e27b72fbf73635f1

**Comment by rheretic** [comment]
(Game is two or three days old if this is something that may have been fixed very recently.)

**Comment by jenf** [comment]
Correct behaviour, there is no legal run. Paris cannot be the only other stop.

"They count against the length of the train, but the train must touch at least two additional revenue locations."
