### ISSUE TITLE
Limited Tileset for #9 - #8 - #7

### ISSUE THREAD

**Issue by Panzerlied7** [tobymao/18xx#1577]
We are playing 1882 and the tile set seems to have limited tiles (straights, curve, sharp curves). My understanding is that these tiles are generally considered unlimited. 

We see no way to consider them unlimited in the game. 

JimA

**Comment by dfannius** [comment]
The site is correct. 1882 has 5 #7 tiles, 10 #8 tiles, and 10 #9 tiles. The tile manifest is on the last page of the rulebook. 1882 is extremely tile-limited by design.

**Comment by Panzerlied7** [comment]
Hi, the general understanding in the 18xx world is that those specific tiles are considered unlimited. That is how it should work in the implementation you have. Regardless of what the tile manifest says.

**Comment by dfannius** [comment]
Marc Voyer designed 1882 to have a limited tile set available to the players, and the site implements his design and his rules. If you want to play with more tiles, you may wish to open another issue with a general feature request for a variant that allows an unlimited amount of #7, #8 and #9 tiles (in any title).
