### ISSUE TITLE
Chesapeake - No Bids Round Decrease Auction Price

### ISSUE THREAD

**Issue by Clacker76** [tobymao/18xx#1579]
Hi, 

I've run into multiple Chesapeake private auctions where NO ONE wanted to spend $200 on a less desirable Co. From the board game, I thought an auction round with no bids would trigger a decrease in price of each remaining item, as well as an export of a 2 train. $5 or $10 decrease, I can't remember. Round by round, a lower price might entice bids. 

Although, maybe that's not a development issue but by design. 

I would be in favour of it as an enhancement. 

Thank you!
Clacker76
aka Curtis

**Comment by dfannius** [comment]
The site implements the game as designed. See section 9 of the rules. The one scenario in which prices can decrease is if everyone passes at the very start of the game without ever bidding at all, in which case the Delaware and Raritan Canal is reduced by $5.
