### ISSUE TITLE
Call out end of game

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#158]
It would be helpful to list why the game ended (broke the bank, etc.)

**Comment by tobymao** [comment]
doesn't the log say the bank broke?

**Comment by gchambers419** [comment]
Yes, but it wasn't highlighted enough and got buried in the transaction text.
The "action prompt" text still said "Lay track" - maybe changing it to "Game over" and why would be better?  
Or make the log message noisier.

Meta:  I've been putting in a lot of issues, it seems, but overall I'm very impressed with the quality of the site.

**Comment by tobymao** [comment]
I appreciate your feedback! I'm glad you're enjoying it.

**Comment by gchambers419** [comment]
I'm a software developer, so I understand exactly how much work this all was,
