### ISSUE TITLE
18GA - Make Open City spaces white with text instead of black

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#1580]
In 18GA, Open City locations cannot be tokened. In the current design, these spaces are black with white text. I propose that they should be white with black text for two reasons: 

1- Open city spaces are normally white, so this flows more naturally.
2- ACL's tokens are black with white text, which can lead players to either mistakenly think that the Open City is an ACL token, or to think that ACL's home space in the bottom right is an Open City.

**Comment by perwestling** [comment]
@philcampeau: Check out the picture in #1589 

Is it good enough?
