### ISSUE TITLE
Add more options when creating the games

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1581]
It is good to know the expectations when joining a new game. Today the expectations is shown on many games, in the description, but it is easy to forget to add this, which seems to cause some friction during startup of games. One problem is that it is hard to communicate between the players before the game is started. This sometimes lead to games being quickly aborted, which is a bit of a waste.

There seem to be kind of a standard that has developed where one uses some keywords in the game description, but not all use these. So maybe we could add some options to select when creating a multi-player game to make it more standard?

I suggest the following, and they can probably be "radio buttions" or possible a check box:

- If it is public / private: public means anyone can join, private means you are only expected to join if you are invited
- If it is asynch / live: live games are expected to be played the same day, while asynch are expected to take days, weeks, months... 

I suppose public and asynch could be the defaults.
For asynch one could consider if one should add a speed field? 

For existing games these values are not set, so I suppose there should be a "not defined" as well. 

I suggest showing public/private and asynch/live on the game when shown in the view of all games.
If adding filtering it would be nice to filter out on these, e.g. show me all public asynch new games.

Of course, the above is just suggestions.

**Comment by tobymao** [comment]
regarding public and private, that doesn't make much sense, you should just have actual private games with passwords. i think with live async, all of this is handled by the description bar. overall i don't think having these being toggles will change much. if you want faster pacing, i think the chess clock feature is the right way to go, closing this issue for now.
