### ISSUE TITLE
List bank balance during operating rounds?

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#159]
I was surprised when my game ended and couldn't figure out why util I looked at the market tab and saw a negative bank balance.  Displaying the bank's balance when in a operating round would help.

**Comment by sparr** [comment]
Where would you want to see it? Where would it fit, in the current UI?

**Comment by gchambers419** [comment]
In a different issue, I proposed a "Game phase" status line near the top of the page.  This could go in that line as well.

In the current UI, I think it could go on the right-hand side of the page in the same "row" as the action choice area.  (That's on tablets and desktop - I have no experience with the UI on phones.

**Comment by jenf** [comment]
Thinking about this, I don't think adding this to the main page is that useful. Otherwise you could argue everything should be on the main page.

With patch going in it'll say that the bank has broken more clearly which should reduce the problem.
