### ISSUE TITLE
[1846] GameError: Step Assign Steamboat Company cannot process when clicking on the Steamboat Company card

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#1595]
Final game action: https://www.18xx.games/game/8768?action=26

OR 1.2, MS ran, then before the IC could run the game blew up.

**Comment by wcraigtrader** [comment]
A new game (https://www.18xx.games/game/8771)

In the middle of another 1846 game, with more Steamboat Company problems. This time there was a JS error in OR1.1:
assigned?: undefined method `assigned?' for <Engine::Company: SC>
main.js:9     at a.$method_missing (https://www.18xx.games/assets/main.js:2:20031)
main.js:9     at a.n (https://www.18xx.games/assets/main.js:1:11652)
main.js:9     at a.$process_assign (https://www.18xx.games/assets/main.js:134:14906)
main.js:9     at I.send (https://www.18xx.games/assets/main.js:1:15202)
main.js:9     at a.$process_assign (https://www.18xx.games/assets/main.js:133:21570)
main.js:9     at a.$__send__ (https://www.18xx.games/assets/main.js:2:14965)
main.js:9     at Object.I.send (https://www.18xx.games/assets/main.js:1:15202)
main.js:9     at a.$send (https://www.18xx.games/assets/main.js:1:17338)
main.js:9     at a.$process_action (https://www.18xx.games/assets/main.js:122:9639)
main.js:9     at a.$process_action (https://www.18xx.games/assets/main.js:124:6364)
main.js:9     at a.$process_action (https://www.18xx.games/assets/main.js:158:27900)
main.js:9     at a.$select_company (https://www.18xx.games/assets/main.js:154:24445)
main.js:9     at Object.t (https://www.18xx.games/assets/main.js:154:26024)
main.js:9     at r (https://www.18xx.games/assets/main.js:68:4818)

**Comment by michaeljb** [comment]
Little deployment snafu, I think it's all good now

**Comment by michaeljb** [comment]
Ok I think I see the problem, in the new Steamboat assign step, you don't need to click on the steamboat card first, you can just click on the hex or railroad you want to assign it to. It would be better if clicking on the card didn't raise an error.
