### ISSUE TITLE
Confusing UI around whose turn it is

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#160]
So a game showed up orange, which I thought meant it was my turn? Probably worth clarifying that with a legend on the main site, or some text on the the games.

So I click, and the game log does not make it clear whose turn it is. Should also clarify that.

Then, because master mode is on by default, I was able to take a turn...for someone else. Which I immediately undid. But then on the main page, it still says that it is my turn.

Game ID 129 if it helps!

**Comment by tobymao** [comment]
orange should mean it's your turn

**Comment by tobymao** [comment]
i think this was a one time issue, but let me know if this shows up again
