### ISSUE TITLE
[18MS] New Orleans Route Calculation Error

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#1600]
JSON: https://gist.github.com/roseundy/0663d81a5dfda8303583999e99101934

Routes that include New Orleans and the town south of it is calculating a revenue $10 too high. This only appears to happen when New Orleans has been tokened - as if the $10 bonus is being applied twice.

**Comment by perwestling** [comment]
Ah, yeah, the code was written for only one stop in New Orleans....  Your suggested fix is fine and I will implement it.
