### ISSUE TITLE
[1846] Wrong players getting control of corporation

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#1608]
We're playing a four-player game of 1846 and we're had several instances where the wrong player is given control of a company, e.g. the right owner is not able to select track or to select routes.  The person who is able to select these isn't then able to submit them.  Refreshing the browser helped sometimes.

Could this be a problem arising with one person using Edge ?  He's now logged in with Chrome, we'll see if that works better.

**Comment by yzemaze** [comment]
**Please provide**
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...
It really helps us having a sample game to reproduce the issue.

**Comment by slapphappyjazz** [comment]
I think this was the first occasion that this occured:  https://www.18xx.games/game/8808?action=28 This is certainly the right game.  If I remember rightly, player rannoch couldn't lay a tile with the Big4 but I (daveb) could.  Then he refreshed his browser tab and it seemed to work OK. There were some similar occasions later in the game, including to do with picking routes), but I don't remember exactly which actions (sorry).
Rannoch seemed to have a better experience after he switched from Edge to Chrome.

**Comment by tobymao** [comment]
can't really reproduce this and edge isn't really supported, closing this for now
