### ISSUE TITLE
For implemented games, should have a link to version of the rules you are based off of

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#161]
This is more of a nice to have, but for example I haven't played 18chesapeake, and I'd want to make sure I study the version of the rules you used!

**Comment by jenf** [comment]
@scottredracecar is the Dropbox the correct source of rules for 18chesapeake? Can we put a link to the draft '82 rules in as well?

**Comment by scottredracecar** [comment]
Yes the dropbox link is good. I’d prefer to link here for the time being for 1882.
https://boardgamegeek.com/thread/2389239/prerelease-rules-review-mass-production-news
