### ISSUE TITLE
Seeing other company's routes

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#1611]
A general request from our group would be to update the game map for all players with the routes a company has selected.  Currently, only the acting director/president gets to see the routes selected.  Other players would like to see this too, once the director has submitted the routes.

**Comment by dfannius** [comment]
I think this is covered by #563 and #1250.

**Comment by slapphappyjazz** [comment]
#563 and #1250 seem a bit more general: they seem to be asking for the abilty to view a company's runs at any time.  I'm just suggesting that they runs are shown to other players during the active company's turn, from the point where the runs are submitted until the end of the turn.
The more general feature would be useful as well, but would be for when the player goes looking for that information between turns.  Showing the routes during the turn would be equivalent to the f-t-f explanation of the route being run during the turn.   I also assume it would be easier to implement, as it would only be a matter of showing other players the same view of the map as the active player.
This suggestion only makes sense for live play.  During asynchronous play it wouldn't make any differenc.e.

**Comment by dfannius** [comment]
OK, let's keep them all open for now.

**Comment by jenf** [comment]
Eilert Fleetjer  11:53
Hi, I don't have a github account but I would like to encourage a new feature:
- I would like to see visually which routes the trains of the other companies took the last run
- This would be really helpful in async games
- You could show an icon of each company in the map tab and upon selection it would show the lines where the trains went in the last run

**Comment by jenf** [comment]
The new map enhancements give me a way to approach this.
