### ISSUE TITLE
Tokens are rended in other orientation for "pointy" hexes

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1617]
Here is how it looks like if New Orleans is tokened in 18MS. I guess this is a general issue.
Now this is a minor thing but it might be worth considering to change so that all tokens have the same orientation.

![image](https://user-images.githubusercontent.com/2631151/92373968-692b6600-f0ff-11ea-9fd7-5e7e87620981.png)

**Comment by roseundy** [comment]
Hmmm. Curious that this isn't a problem for 1846.

**Comment by roseundy** [comment]
Found the bug. We are passing the number of cities+towns to the CitySlot object, when it should just be the number of cities.

Line 281 in assets/app/view/game/part/city.rb
