### ISSUE TITLE
Call out in UI when actions require another player's permission

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#1619]
By design, nothing prevents players from taking actions that require another player's permission (such as buying one of their privates, or one of their corporation's trains). And actions accidentally (or intentionally) taken can always be undone.

But it would be nice to call out those actions before they are taken, so that players are aware beforehand of which actions require permission, especially if they're new.

The lightest-weight solution (at least from the user's side) is probably to have a confirmation button somewhere for these actions. I'm not too concerned that it will add much of a speedbump to the UI, since there are very few actions that require other players' permission, and for the ones that do, you presumably already spent some time obtaining their permission, so what's one more button-press?

**Comment by renaudgermain** [comment]
+1 for the button, UI should "teach" the rules IMO and avoid unintentional cheating when possible.
