### ISSUE TITLE
18AL: Should not be able to build through Mobile

### ISSUE THREAD

**Issue by Bobsson** [tobymao/18xx#1626]
It looks like the game engine offers players who have connected to one side of Mobile the ability to lay track _from_ it as well.  See 
 https://18xx.games/game/8960?action=190:
![image](https://user-images.githubusercontent.com/2022339/92426497-0f0abf00-f158-11ea-9040-73ca1c407809.png)

Since this is a red off-board area, it should not be possible for a route to connect through it, and thus not be able to build through it either.  (4.2.1j)

**Comment by roseundy** [comment]
Would be cool if the "terminal" flag for a path would take care of it automatically.

**Comment by roseundy** [comment]
I'm going to take a crack at it
