### ISSUE TITLE
Display train routes during Payout phase

### ISSUE THREAD

**Issue by Bobsson** [tobymao/18xx#1627]
Currently, there is no good way to *see* what route(s) a company ran until their next train operation phase.  The log lists the tiles, so it's possible to examine it, but it's not as useful as actually seeing the routes.

Since the next phase after running trains is the payout/withhold phase, it would be reasonable to show the routes that were actually run on the map during that phase, even without the train list/color key.

**Comment by tobymao** [comment]
duplicate #1250

**Comment by Bobsson** [comment]
@tobymao I'm not sure this is strictly a duplicate of #1250.  That seems to be asking for a way to arbitrarily pull up the last run of a given company, while I'm only suggesting having it for the phase immediately following.  Theoretically (and I have no idea how possible this is), this suggestion could be accomplished by simply not removing the train lines between those two phases.  I'm sure it'd be more complicated than that, but it's not a whole extra set of UI options.

That said, they are very similar in goal, so if you want to roll this into that ticket, then I'll just patiently wait for that one to be developed.

**Comment by tobymao** [comment]
They'd be solved in the same way, so when 1250 is implemented, this will
come for free
