### ISSUE TITLE
18TN - 3p game with uncounted cert. 

### ISSUE THREAD

**Issue by Jon-Ger** [tobymao/18xx#1628]
Game 8738; each player owns 2 companies, so 2 president certificates, but one of the three players was able to fill to 19 shares (instead of 18).

**Comment by dfannius** [comment]
Everything looks good to me as of OR7.2. The presidency of IC is a certificate with 30% shares.

**Comment by dfannius** [comment]
I've created the feature request #1630 to try to make cases like this easier to understand.
