### ISSUE TITLE
Way to see what the certificates in a collection are

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#1630]
18TN has a 30% president's certificate for one company, but this isn't called out anywhere and has to be known by the players. This can lead to issues like #1628, where it's not obvious why one player seems to have more shares than they should. It's also important information for cases like dumping a company.

There should be some way to see what the actual certificates that make up a player's (or corp's, or pool's) holding are. This will be even more important when we implement games like 1849 that have non-president double certificates, in which case the current system would drop necessary information that isn't deducible from the rules.

**Comment by dfannius** [comment]
A pretty cheap solution would be to have more symbols to represent any unusual certificates in a holding, e.g., in addition to `*` for presidency, have `+` for a 30% presidency, `d` for a double share, etc. But that's pretty ugly (even the `*` is kind of ugly!), requires some sort of glossary, and doesn't really scale with the number of titles.

**Comment by perwestling** [comment]
It should also be noted the 5% NdM shares in 18MEX, which are a bit special. 
2 5% shares is not the same as 1 10% share.

**Comment by perwestling** [comment]
About 18TN the fact about the 30% share is noted on the Wiki side. But yes, it should be more obvious in the game.

In a game of 1880 this would be even more important as the players choose presidency paper size, 20%, 30% or 40%.

**Comment by benjaminxscott** [comment]
not sure if merged PR closes this issue? 
https://github.com/tobymao/18xx/pull/3637

**Comment by perwestling** [comment]
> not sure if merged PR closes this issue?
> #3637

E.g. 18MEX has not yet been solved, as the 5% shares are not shown. But maybe #3601 covers that case? Are there any other title that needs to be fixed?

**Comment by scottredracecar** [comment]
I think this suggestion is mostly solved. Someone should make a new issue specific to 18MEX if that is still needed. This is unlikely to get fixed under this current issue I think.
