### ISSUE TITLE
Smart sound if a player is „on turn“

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#1638]
When I have an opened main view in my browser, I recognize from time to time the colour switching to orange telling me „it is your turn“.
Would it be possible to play a smart sound in the browser window while switching the colour? Configurable in the profile view?

**Comment by edfactor29** [comment]
Would be nice to make it a train whistle.

**Comment by Illotus** [comment]
This would be great improvement.

**Comment by zurfarosa** [comment]
I came here to make this request myself :)

**Comment by scottredracecar** [comment]
We have webhook notifications now and those can be configured to make a sound. Please use that type of solution.
