### ISSUE TITLE
https://www.18xx.games/game/9115; 3/5 train not calculating route $$ correctly

### ISSUE THREAD

**Issue by twotwotrainer** [tobymao/18xx#1641]
**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by twotwotrainer** [comment]
oops. nvmd. my bad

**Comment by dfannius** [comment]
Does your better route possibly have no tokens?

**Comment by dfannius** [comment]
OK, if there's no issue, I'll close this.

**Comment by twotwotrainer** [comment]
close it. apologies
