### ISSUE TITLE
[Feature Request] Options for bigger screens

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#1644]
Under the user profile an option to turn on for users on larger screens would allow for taking advantage of screen real estate. This could be turned on or off at any time by the user. I have two specific scenarios in mind. Please excuse the terrible paint mock-ups.

During the initial auction(A) or draft place the map(M) beneath the auction -
![auction](https://user-images.githubusercontent.com/67166181/92801181-3d5fe880-f36a-11ea-99a2-8f9383f5ccb2.png)

During the operating rounds place the tile sheet(t) next to the map(M) - 
![or](https://user-images.githubusercontent.com/67166181/92801203-4355c980-f36a-11ea-9d76-e55280b7b88a.png)

**Comment by dfannius** [comment]
If you have the capability to put two browser windows side by side, that's what I do. It also has the advantage that I can choose exactly what set of two tabs to look at.

**Comment by tobymao** [comment]
there are no plans to have configurable options like this, it's too much to maintain and would only be used by a fraction of users. 

there is a plan to have a spreadsheet driven view, which would allow a more efficient use of space. 

i will close this ticket for now. but if you feel strongly that the tiles should be on the same page as the map (which is a reasonable request) please feel free to open up a new ticket with a solution that will work universally for mobile and desktops.
