### ISSUE TITLE
Handle borders meant to hide an edge differently from others

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#1649]
All borders are drawn after all other tile elements are drawn. This should be changed so that borders that trying to hide the edge of the tile (type == nil) are drawn first. This would allow off-board with track to be rendered properly.

Without this change, if we try to hide edges we get:
![BorderIssue](https://user-images.githubusercontent.com/8494213/92953218-938e6380-f41e-11ea-8010-0992ec36921b.png)

So, we are forced to not use "border" at all, and we get the hex edges:
![Offboard_lines](https://user-images.githubusercontent.com/8494213/92953268-aef96e80-f41e-11ea-8a39-e230044d8c5c.png)

**Comment by roseundy** [comment]
A bonus would be to have edge hiding border respect the transparency property when a map was drawn.

**Comment by roseundy** [comment]
Looked into the transparency (opacity) problem. It's caused by the fact that the border extends into the neighboring hex. This has implications for the primary bug fix since drawing wide borders will take out neighboring track.

**Comment by michaeljb** [comment]
Closed via #2551 (but I'm happy to re-open if you think that's warranted @roseundy)
