### ISSUE TITLE
Not receiving game turn notifications

### ISSUE THREAD

**Issue by Phildnarud** [tobymao/18xx#1657]
Hi, we are at least two new players not receiving any turn notification, After checking my account, Phildurand, all is right, my e-mail adress is valid and notifications are activated. For me it is something about my e-mail provider @free.fr blocking emails from 18XX.games, not even in spam, junk or so on. I wish to change my e-mail adress, but there is no way doing so on my 18XX  account, it seems I have to request that here.
Many thanks 
Philippe

**Comment by tobymao** [comment]
your email provider is blocking us. please send me your new email on slack dm

**Comment by Phildnarud** [comment]
Ok, I will tell my friends to use a gmail email. Merci beaucoup.
