### ISSUE TITLE
Train limit visible?

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#166]
Is it possible to add train limit somewhere in the UI?

**Comment by tobymao** [comment]
right now it's only in the log, need to find a place to put the phase info

**Comment by gchambers419** [comment]
I was thinking you could put the log at the top, put the phase/limits text under that, and the round/action prompt under that.  (Or in other words, swap the prompt and the log and put the phase/limits text between them.  That would also be a good place for the bank balance.)

**Comment by tobymao** [comment]
i’m not following

**Comment by gchambers419** [comment]
I'm talking about rearranging the top UI elements on the main tab.

**Comment by jenf** [comment]
Train limits now visible on 'Trains' tab

Fixed by #278
