### ISSUE TITLE
Player value (score) tracking graph

### ISSUE THREAD

**Issue by rsbelcher** [tobymao/18xx#1667]
Please describe your idea and why we should consider it.
Hi there! AWESOME stuff! Really enjoying the site and games. 

I'm a visual person, and thought it would be helpful, interesting or handy to have a running graph of player values through the game, maybe on the Entities page? It, along with reading back through the game log, would be helpful for seeing and understanding certain game impacts on scores. Just an idea, and thank you!

**Comment by dfannius** [comment]
Thanks for the suggestion; I think this is covered by by #1549 so I'm going to close this as a duplicate.

**Comment by rsbelcher** [comment]
Yes - thanks --- I'm new to all of this (including and especially Github)
and saw that one after I had posted mine.

Thanks for the hard work! Such an impressive site!
