### ISSUE TITLE
[1889] cant sell IR shares

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#1669]
https://www.18xx.games/game/9244?action=409

After selling one share (had six of them) last 5 IR shares can't be sold. I looks like game treats them as they were presidency shares.

**Comment by dfannius** [comment]
The market can't contain more than 5 shares.

**Comment by jenf** [comment]
You can sell KO shares, but IR is at limit.

**Comment by SirYaro** [comment]
Oh my.... It so obvious and I did not see that. Appologies...
