### ISSUE TITLE
Liquidity value can be misleading in operating round.

### ISSUE THREAD

**Issue by yoyot1** [tobymao/18xx#1672]
See game 8352 for example.

N&W was forced to buy a D train ($900), but only had $220 cash on hand.  Spreadsheet for president (jeki187) shows liquidity of $691, however the "actual" liquidity at that point was only $631 because the owner could only sell 4 shares of N&W, instead of 5 (otherwise presidency would change, which is disallowed in this case).

So the game operated correctly, but would be nice to have some indicator of that situation - asterisk/tooltip on liquidity to display "correct" amount?  Better message in the log?

**Comment by jenf** [comment]
For some games 'Emergency' liquidity != Liquidity. It'd be confusing to randomly change between them. Maybe we need Emergency Liquidity as a separate field.

**Comment by jenf** [comment]
The 'Emergency' liquidity changes depending on what corporation is operating.
I'm proposing we wouldn't do this, as it might cause more confusion.
