### ISSUE TITLE
1882: Cannot use NWR in run routes step

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1674]
https://www.18xx.games/game/9253?action=277

Looks like the token ability gets removed as the user lays a token in the NWR area

`{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 1,
      "company": "NWR",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 2,
      "company": "TB",
      "price": 145
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 3,
      "company": "SC",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 4,
      "company": "SC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 5,
      "company": "TB",
      "price": 150
    },
    {
      "type": "bid",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 6,
      "company": "CP",
      "price": 185
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 7,
      "company": "NWR",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 8,
      "company": "HB",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 9,
      "company": "SC",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 10,
      "company": "SC",
      "price": 70
    },
    {
      "id": 11,
      "type": "bid",
      "price": 75,
      "entity": "svenfu",
      "company": "SC",
      "entity_type": "player"
    },
    {
      "id": 12,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "bid",
      "price": 85,
      "entity": "svenfu",
      "company": "SC",
      "entity_type": "player"
    },
    {
      "id": 14,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 15,
      "type": "bid",
      "price": 80,
      "entity": "svenfu",
      "company": "SC",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "bid",
      "price": 85,
      "entity": "svenfu",
      "company": "SC",
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 19,
      "company": "SC",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 20,
      "company": "SC",
      "price": 90
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 22,
      "company": "NWR",
      "price": 95
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 23,
      "company": "NWR",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 24,
      "company": "NWR",
      "price": 115
    },
    {
      "id": 25,
      "type": "bid",
      "price": 125,
      "entity": "svenfu",
      "company": "NWR",
      "entity_type": "player"
    },
    {
      "id": 26,
      "type": "undo",
      "entity": "Bastian",
      "entity_type": "player"
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 27,
      "company": "NWR",
      "price": 125
    },
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 28,
      "company": "NWR",
      "price": 130
    },
    {
      "type": "bid",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 29,
      "company": "NWR",
      "price": 135
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "bid",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 31,
      "company": "TB",
      "price": 160
    },
    {
      "id": 32,
      "type": "bid",
      "price": 165,
      "entity": "Bastian",
      "company": "TB",
      "entity_type": "player"
    },
    {
      "id": 33,
      "type": "undo",
      "entity": "Ratherdone",
      "entity_type": "player"
    },
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 34,
      "company": "TB",
      "price": 170
    },
    {
      "type": "bid",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 35,
      "company": "TB",
      "price": 175
    },
    {
      "type": "bid",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 36,
      "company": "TB",
      "price": 180
    },
    {
      "type": "bid",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 37,
      "company": "TB",
      "price": 185
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "par",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 39,
      "corporation": "CPR",
      "share_price": "100,0,3"
    },
    {
      "type": "buy_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 40,
      "shares": [
        "CPR_2"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 41,
      "corporation": "CNR",
      "share_price": "76,3,3"
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 42,
      "shares": [
        "CNR_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 43,
      "shares": [
        "CPR_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 44,
      "shares": [
        "CNR_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 45,
      "shares": [
        "CNR_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 46,
      "shares": [
        "CNR_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 47,
      "shares": [
        "CPR_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 48,
      "shares": [
        "CNR_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 49,
      "shares": [
        "CNR_6"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 50,
      "shares": [
        "CPR_5"
      ],
      "percent": 10
    },
    {
      "id": 51,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 52,
      "type": "undo",
      "entity": "Bastian",
      "entity_type": "player"
    },
    {
      "id": 53,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 54,
      "type": "redo",
      "entity": "svenfu",
      "entity_type": "player"
    },
    {
      "id": 55,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 56,
      "type": "redo",
      "entity": "svenfu",
      "entity_type": "player"
    },
    {
      "id": 57,
      "type": "redo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "id": 58,
      "type": "redo",
      "entity": "Bastian",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 59,
      "shares": [
        "CNR_7"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 60,
      "hex": "I5",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 61,
      "hex": "J4",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 62,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 63,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 64
    },
    {
      "id": 65,
      "hex": "E7",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "CNR",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 66,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 67,
      "hex": "E7",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "CNR",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 68,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 69,
      "hex": "E7",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 70,
      "hex": "F6",
      "tile": "7-0",
      "rotation": 3
    },
    {
      "type": "buy_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 71,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 72,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 73
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "sell_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 75,
      "shares": [
        "CNR_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 76,
      "shares": [
        "CPR_6"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 77
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 78
    },
    {
      "type": "sell_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 79,
      "shares": [
        "CNR_1",
        "CNR_4",
        "CNR_6"
      ],
      "percent": 30
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 80,
      "shares": [
        "CPR_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 83
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 85,
      "shares": [
        "CPR_8"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 90
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 91,
      "hex": "K3",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "id": 92,
      "hex": "H6",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "CPR",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 93,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 94,
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 95,
      "city": "57-1-0",
      "slot": 0,
      "type": "place_token",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 96,
      "type": "run_routes",
      "entity": "CPR",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 97,
      "kind": "payout",
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 98,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 99,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 100,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 101,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 102,
      "hex": "H6",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 103,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 104,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 105,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 106,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 107
    },
    {
      "type": "lay_tile",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 108,
      "hex": "D6",
      "tile": "57-2",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 109,
      "hex": "F8",
      "tile": "69-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "run_routes",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 111,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "B6",
              "D6"
            ],
            [
              "D8",
              "E7",
              "F6",
              "D6"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "D8",
              "F8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 112,
      "kind": "payout"
    },
    {
      "id": 113,
      "type": "buy_train",
      "price": 80,
      "train": "2-5",
      "entity": "CNR",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 114,
      "type": "buy_train",
      "price": 180,
      "train": "3-0",
      "entity": "CNR",
      "variant": "3",
      "entity_type": "corporation"
    },
    {
      "id": 115,
      "type": "buy_company",
      "price": 160,
      "entity": "CNR",
      "company": "NWR",
      "entity_type": "corporation"
    },
    {
      "id": 116,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 117,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 118,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "type": "buy_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 119,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 120,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_company",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 121,
      "company": "NWR",
      "price": 160
    },
    {
      "type": "pass",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 122
    },
    {
      "type": "buy_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 123,
      "shares": [
        "CNR_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 124
    },
    {
      "type": "sell_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 125,
      "shares": [
        "CPR_1",
        "CPR_2",
        "CPR_3",
        "CPR_6"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 126,
      "corporation": "QLL",
      "share_price": "82,2,3"
    },
    {
      "type": "buy_shares",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 127,
      "shares": [
        "CPR_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 128
    },
    {
      "id": 129,
      "type": "buy_shares",
      "entity": "Fredric",
      "shares": [
        "CPR_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 130,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 131,
      "shares": [
        "CNR_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 132
    },
    {
      "type": "sell_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 133,
      "shares": [
        "CNR_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 134,
      "shares": [
        "CPR_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 135
    },
    {
      "type": "buy_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 136,
      "shares": [
        "QLL_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 137
    },
    {
      "id": 138,
      "type": "buy_shares",
      "entity": "svenfu",
      "shares": [
        "CNR_8"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 139,
      "type": "undo",
      "entity": "svenfu",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 140,
      "shares": [
        "CNR_8"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 141
    },
    {
      "id": 142,
      "type": "sell_shares",
      "entity": "Fredric",
      "shares": [
        "CPR_7",
        "CPR_8"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 143,
      "type": "undo",
      "entity": "Fredric",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 144
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 145
    },
    {
      "type": "buy_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 146,
      "shares": [
        "QLL_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 147
    },
    {
      "type": "buy_shares",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 148,
      "shares": [
        "CPR_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 151
    },
    {
      "type": "buy_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 152,
      "shares": [
        "QLL_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 153
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 154
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 155
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 156
    },
    {
      "type": "buy_shares",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 157,
      "shares": [
        "QLL_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 158
    },
    {
      "type": "pass",
      "entity": "svenfu",
      "entity_type": "player",
      "id": 159
    },
    {
      "type": "pass",
      "entity": "Fredric",
      "entity_type": "player",
      "id": 160
    },
    {
      "type": "pass",
      "entity": "Bastian",
      "entity_type": "player",
      "id": 161
    },
    {
      "type": "pass",
      "entity": "Ratherdone",
      "entity_type": "player",
      "id": 162
    },
    {
      "id": 163,
      "city": "J10-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "QLL",
      "entity_type": "corporation"
    },
    {
      "id": 164,
      "type": "undo",
      "entity": "QLL",
      "entity_type": "corporation"
    },
    {
      "type": "place_token",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 165,
      "city": "J10-0-0",
      "slot": 0
    },
    {
      "id": 166,
      "hex": "J10",
      "tile": "R1-0",
      "type": "lay_tile",
      "entity": "QLL",
      "rotation": 4,
      "entity_type": "corporation"
    },
    {
      "id": 167,
      "type": "buy_train",
      "price": 180,
      "train": "3-1",
      "entity": "QLL",
      "variant": "3",
      "entity_type": "corporation"
    },
    {
      "id": 168,
      "type": "undo",
      "entity": "QLL",
      "entity_type": "corporation"
    },
    {
      "id": 169,
      "type": "undo",
      "entity": "QLL",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 170,
      "hex": "K9",
      "tile": "1-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 171,
      "hex": "J8",
      "tile": "57-3",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 172,
      "city": "57-3-0",
      "slot": 0,
      "token_type": "neutral"
    },
    {
      "type": "buy_train",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 173,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_train",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 174,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 175
    },
    {
      "type": "pass",
      "entity": "QLL",
      "entity_type": "corporation",
      "id": 176
    },
    {
      "id": 177,
      "hex": "K3",
      "tile": "14-0",
      "type": "lay_tile",
      "entity": "CPR",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 178,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "id": 179,
      "hex": "K3",
      "tile": "15-0",
      "type": "lay_tile",
      "entity": "CPR",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 180,
      "type": "undo",
      "entity": "CPR",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 181,
      "hex": "K3",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 182
    },
    {
      "type": "run_routes",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 183,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "L2",
              "K3"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 184,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 185
    },
    {
      "type": "pass",
      "entity": "CPR",
      "entity_type": "corporation",
      "id": 186
    },
    {
      "id": 187,
      "city": "D8-0-0",
      "slot": 0,
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 188,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "type": "lay_tile",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 189,
      "hex": "D6",
      "tile": "15-0",
      "rotation": 0
    },
    {
      "id": 190,
      "city": "15-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 191,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 192,
      "city": "15-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 193,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 194,
      "city": "D8-0-0",
      "slot": 0,
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 195,
      "city": "C3-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 196,
      "hex": "C3",
      "tile": "57-1",
      "type": "lay_tile",
      "entity": "NWR",
      "rotation": 2,
      "entity_type": "company"
    },
    {
      "id": 197,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 198,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 199,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 200,
      "city": "15-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 201,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 202,
      "city": "D8-0-0",
      "slot": 0,
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 203,
      "city": "C3-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 204,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 205,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 206,
      "city": "15-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 207,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 208,
      "city": "D8-0-0",
      "slot": 0,
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 209,
      "city": "C3-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 210,
      "hex": "C3",
      "tile": "57-1",
      "type": "lay_tile",
      "entity": "NWR",
      "rotation": 2,
      "entity_type": "company"
    },
    {
      "id": 211,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 212,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 213,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 214,
      "city": "D8-0-0",
      "slot": 0,
      "type": "remove_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 215,
      "city": "C3-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 216,
      "hex": "C3",
      "tile": "57-1",
      "type": "lay_tile",
      "entity": "NWR",
      "rotation": 2,
      "entity_type": "company"
    },
    {
      "id": 217,
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation"
    },
    {
      "id": 218,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "id": 219,
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company"
    },
    {
      "type": "place_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 220,
      "city": "15-0-0",
      "slot": 1
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 221
    },
    {
      "type": "redo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 222
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 223
    },
    {
      "type": "redo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 224
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 225
    },
    {
      "type": "redo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 226
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 227
    },
    {
      "type": "place_token",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 228,
      "city": "15-0-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 229
    },
    {
      "type": "redo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 230
    },
    {
      "type": "undo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 231
    },
    {
      "type": "redo",
      "entity": "CNR",
      "entity_type": "corporation",
      "id": 232
    }
  ],
  "id": "hs_fqpxkafi_9253",
  "players": [
    {
      "id": 1258,
      "name": "Bastian"
    },
    {
      "id": 1250,
      "name": "Ratherdone"
    },
    {
      "id": 1251,
      "name": "svenfu"
    },
    {
      "id": 1277,
      "name": "Fredric"
    }
  ],
  "title": "1882",
  "description": "Cloned from game 9253",
  "max_players": 4,
  "user": {
    "id": 0,
    "name": "You"
  },
  "settings": {
    "seed": 9.434868030141968e+37
  },
  "user_settings": null,
  "turn": 3,
  "round": "Operating Round",
  "acting": [
    1251
  ],
  "result": {},
  "loaded": true,
  "created_at": "2020-09-16",
  "updated_at": 1600243052,
  "mode": "hotseat"
}`

**Comment by daniel-sousa-me** [comment]
This has been fixed, right? I just did this yesterday with no problem

**Comment by jenf** [comment]
Nope, if you lay a token in the NWR area it reproduces

**Comment by daniel-sousa-me** [comment]
https://www.18xx.games/game/11645?action=260

**Comment by jenf** [comment]
I can't seem to reproduce this now. Closing
