### ISSUE TITLE
[18MS] Display progress chart on info tab and update OR names

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#1675]
Game https://www.18xx.games/game/9795

https://all-aboardgames.com/products/international-18ms-the-railroads-come-to-mississippi

As found on the third image the round of play tracker should be added to the info tab.

The OR description also went from OR 1.1 to OR 1.2 instead of OR 1 to OR 2.

**Comment by perwestling** [comment]
There will always be differenes between the looks of physical games and how it is presented online.
Now the game is run for 10 ORs, 5 OR sets, and I took the design decision to use the existing presentation of OR1.1, OR1.2, OR2.1, OR2.2, that is first OR of first OR set, second OR of first OR set etc.
This was also described in the wiki page: https://github.com/tobymao/18xx/wiki/18MS#rules-highlights

It is of course possible to change this to using OR 1, OR 2, OR 3, ... and I might give it a new try. But I thought it most important to test it in alpha to see the reactions.

When it comes to play tracker this is something that would require a lot of specialized implementation. And as far as I know it would only be used in 18MS and 18CZ. Question is if is worth the effort; how useful would it be?

Mark Derrick had another suggestion, and that was to show the last OR more clearly in the log.
That might be a good improvement which do not require much implementation.

I did have an idea how to add a time line, but that was mostly to show the events that occur during the ORs. Now this is far from how it appear in the physical game, and I do not know if it will be clear enough for the players?  Here is a link to my suggestion: https://github.com/tobymao/18xx/issues/1507

Any more thoughts on this subject, @KillerOrca ?

**Comment by TIE53** [comment]
I think it needs some sort of timeline/round marker.  As far as I can tell, there is nothing in the current implementation that displays the train rusting schedule, the length of the game, when phase 3 begins, etc. This is not a problem for experienced players, but when I was teaching a new player yesterday, I had to write all of this information in the chat, which was mildly burdensome. 

I don't think it necessarily needs a moving round marker, but an image/display analagous to the round marker on the physical board would be very helpful.

**Comment by KillerOrca** [comment]
@perwestling My thinking was a static image of the play tracker then players could match the current round to see how for along they are to the game end. This might not be everyone's preferred version but I think as a quick reference it would work well.

Speaking of 18CZ since it also has the static rounds I think renaming to match the OR structure, in this instance for 18MS, will make it clearer for players. When it goes from OR1.1 to OR1.2 new players may think they have more time left in the game than they really do.

**Comment by perwestling** [comment]
It is not that further to go to find the information about operation rounds. Just click on "More info" in the Info page, and you get the Wiki page that describes these parts. It could be possible to add some more graphical things there, maybe? E.g. that timeline could be shown there.

Anyway, I have some ideas on how to improve things.

**Comment by TIE53** [comment]
> It is not that further to go to find the information about operation rounds. Just click on "More info" in the Info page, and you get the Wiki page that describes these parts. It could be possible to add some more graphical things there, maybe? E.g. that timeline could be shown there.

Sure, but train rust and phase information is included on the info tabs of all the other games, so it seems out of place not to include it in this one.  IMO, a player shouldn't need to reference a wiki for critical game information (salvage prices, train rusting, etc.).

**Comment by perwestling** [comment]
Have now merged in the changes I have done (in 1693 linked above). It does improve the presentation quite a bit and might be good enough.

**Comment by perwestling** [comment]
@TIE53 @KillerOrca 

If you scroll through the bold lines in the log of game https://www.18xx.games/game/9795 you can see the changes made, which is now deployed. There is also a "Timeline" section added to the "Info" page.

What do you think of this? Is it good enough?

**Comment by TIE53** [comment]
> @TIE53 @KillerOrca
> 
> If you scroll through the bold lines in the log of game https://www.18xx.games/game/9795 you can see the changes made, which is now deployed. There is also a "Timeline" section added to the "Info" page.
> 
> What do you think of this? Is it good enough?

I think it's good enough. It conveys the necessary information without making players leave the game tab.

**Comment by KillerOrca** [comment]
> 
> 
> @TIE53 @KillerOrca
> 
> If you scroll through the bold lines in the log of game https://www.18xx.games/game/9795 you can see the changes made, which is now deployed. There is also a "Timeline" section added to the "Info" page.
> 
> What do you think of this? Is it good enough?

Looks great to me, thank you.

**Comment by perwestling** [comment]
Thanks for the feedback!
