### ISSUE TITLE
[18MS] Birmingham Southern Railroad Private confuses OR steps

### ISSUE THREAD

**Issue by shazzner** [tobymao/18xx#1677]
https://www.18xx.games/game/9800

In the screenshot below you can see FR was operating and wanted to buy in the private, lay tracks down to New Orleans including its two tracks in the first OR.
![Screenshot from 2020-09-16 12-49-40](https://user-images.githubusercontent.com/691304/93378698-7264b300-f822-11ea-8d0d-1a91f73d6c6f.png)

Unfortunately either way I laid track, then buy in the private and laid them, or vice versa, I wasn't able to token NO. Additionally if I bought in first, laid the tiles then tried to do my normal track operation I got a message saying i couldn't. Tried to undo a few times but wasn't able to get it to work.

```
Fr spends $20 and lays tile #9 with rotation 2 on F2
Fr lays tile #58 with rotation 0 on G3
Fr skips place a token
Fr skips run routes
Fr does not run
Fr's share price changes from $70 to $65
Fr buys Birmingham Southern Railroad from shazzner for $40
Fr lays tile #9 with rotation 0 on H2
Fr lays tile #9 with rotation 1 on E3
```

**Comment by tobymao** [comment]
you need to click on the abilities to activate them

**Comment by shazzner** [comment]
I did and this issue is actually fairly easy to reproduce, for example:
![Screenshot from 2020-09-16 15-50-59](https://user-images.githubusercontent.com/691304/93391290-8b765f80-f834-11ea-9d37-b3b6154c7be4.png)
![Screenshot from 2020-09-16 15-50-31](https://user-images.githubusercontent.com/691304/93391306-90d3aa00-f834-11ea-8e74-23b3cad49495.png)

Buying in the private, laying two tracks, then attempting to lay their two track tiles causes an error.
Laying two then buying in the private doesn't allow for a token.

**Comment by shazzner** [comment]
To those that didn't full grok the answer, you have to click on the private and lay a single tile twice.
