### ISSUE TITLE
Illegal track lay allowed

### ISSUE THREAD

**Issue by MichaelDyrud** [tobymao/18xx#168]
In a 2p multiplayer game, track in our game is incorrectly upgrading. In this case, an 8 going from F7 to G4 was upgraded into a 25 that connects F7 to E4. Several other green tiles were also allowed to be placed in an illegal upgrade. I cloned the game and attached the log here.

[F5 Track upgrade bug.txt](https://github.com/tobymao/18xx/files/4535804/F5.Track.upgrade.bug.txt)

**Comment by philcampeau** [comment]
I’ve experienced this as well in game Id 88, the game allowed me to upgrade hex C8 to a #20 tile even though the operating company couldn’t access the new track. 

It seems to allow permissive tile laying when 1889 is semi-restrictive.

**Comment by tobymao** [comment]
i need to rewrite the routing code to be more efficient but will get to this

**Comment by rheretic** [comment]
OP:  I would retry this to see if it's still present.  Quite a bit of code change since you opened this.
