### ISSUE TITLE
[1846] GT token put on Chicago city 2 (east side of tile) rather than city 1 (south-east side of tile) when buying in the C & WI

### ISSUE THREAD

**Issue by grumpydaddy845** [tobymao/18xx#1680]
multiplayer game ID: 9175

In OR2.1, Grand Trunk buys in the C&WI private. The free GT token was placed in the wrong location initially or more likely, it has moved during a code update as none of the players noticed the error at the time and it's current location could only have been the result of an illegal move. The game was started on 9/9/2020. 

![2020-09-17 00_25_31-1846 - hs_opumancl_9175 - 18xx Games](https://user-images.githubusercontent.com/71422389/93420362-b8e6fb80-f87c-11ea-8dee-d500fde9c737.png)
prior to the buy in
![2020-09-17 00_27_52-1846 - hs_opumancl_9175 - 18xx Games](https://user-images.githubusercontent.com/71422389/93420406-d1efac80-f87c-11ea-9a4a-c77df96176d9.png)
immediately following the buy in
![2020-09-17 00_28_20-1846 - hs_opumancl_9175 - 18xx Games](https://user-images.githubusercontent.com/71422389/93420443-e338b900-f87c-11ea-8f29-28594be528aa.png)
immediately after placing the token.

A link to the moves in question:
https://www.18xx.games/game/9175?action=234

I doubt that someone would not have noticed this during live play, most especially the GT player. Is there any way to move the token over to the correct spot?

Thanks in advance,
Mike Ward

**Comment by michaeljb** [comment]
I've pinned game 9175 to the previous release. Note that pinned games do not emit email notifications. It is currently grumpydaddy's turn, operating the B&O. Sorry for the inconvenience!
