### ISSUE TITLE
1846, gm 9893, IC runs 3 trains OR 1.2, after runnng one of them w B4 in OR 1.2

### ISSUE THREAD

**Issue by twotwotrainer** [tobymao/18xx#1682]
Game: 1846
Owner: DrAwesome
Review
Id: 9893
Description: Live - Open
seasons operates IC
IC places a token on G7 (Terre Haute) for $80
IC runs a 2 train for $100 (G7, I1)
IC runs a 2 train for $100 (K3, I1)
IC runs a 2 train for $40 (G7, G9)

**Comment by dfannius** [comment]
The bug is that in OR2.1, Big 4 ran its 2T, then IC bought Big 4 on its turn and ran the 2T again.
