### ISSUE TITLE
Restrict access to game

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#169]
It would be nice if we could create a game that only specific invited players may join.

**Comment by jrebs** [comment]
A very simple early implementation would be to just designate a password when creating a game and then pass that out to your invitees.

**Comment by michaeljb** [comment]
@ChrisTheCat would you say the "private" game implementation is good enough to close this?

**Comment by tobymao** [comment]
i think we can close this for now

**Comment by ChrisTheCat** [comment]
Yes, it does, though I will probably ask for enhancements :)
