### ISSUE TITLE
[18MS] WRA did not receive $50 bonus for connecting Chattanooga

### ISSUE THREAD

**Issue by jftaylor21** [tobymao/18xx#1698]
WRA is the first corporation to connect to Chattanooga but did not receive the $50 bonus. The connection was made with the Birmingham Southern Railroad ability.

See game https://www.18xx.games/game/9984

**Comment by roseundy** [comment]
Poking around in this shows that SpecialTrack (special_track) calls lay_tile
While 18MS defines it's own lay_tile, in this case, it is not overridden by that method, instead calling Tracker#lay_tile directly.

**Comment by perwestling** [comment]
Nice analysis @roseundy 
Have a fix up for review.
