### ISSUE TITLE
[1846] Draft is visible to users that aren't logged in.

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#1703]
Multiplayer game: https://www.18xx.games/game/10354

If you open up a separate browser window that is not logged into 18xx,games and then browse to a game during the auction, you will be presented with the player's view and you can click on the **Show Player** button to see the companies they are currently drafting from.

![18xx-games-1846-draft-bug](https://user-images.githubusercontent.com/972263/93834065-92dca500-fc48-11ea-827a-a310b4ba7109.png)

**Comment by tobymao** [comment]
working as intended

**Comment by wcraigtrader** [comment]
Why is that intended? In RL the privates that are drafted in the auction are hidden until after the auction. While I realize that someone who wants to cheat can do so by looking at the log, why make it easy?

**Comment by tobymao** [comment]
for visitors who want to look at your game

it's already very easy, just turn on master mode
