### ISSUE TITLE
Investigate if companies abilities are correct according to the rules

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1704]
It has been noted that there are some problems with the abilities of corporations:
- Abilities appear as an option in incorrect phases
- Abilities appear in stock round
- Abilities appear for corporations that does not own the company
- Abilities are used automatically when it should be a choice

E.g. in 18GA an ability was available in a corporation when in reality it was owned by the another corporation owned by the president.  

Also in 18GA the extra tile lay ability was possible to lay outside the tile laying phase.

Eg. in 18TN abilities appear in Stock Round. 

1. This issue is to check if there is any problems with the abilities
1. And to check if there exist an issue for it.
1. If not write a new.
1. Link the issue to this issue. 

Titles to investgate:
- [x] 1836Jr
- [x] 1846
- [x] 1882
- [x] 1889
- [x] 18AL
- [ ] 18Chesapeake
- [x] 18GA
- [x] 18MS
- [x] 18TN
- [x] 1817

Titles completed:
- [x] 1836Jr
- [ ] 1846
- [x] 1882
- [x] 1889
- [x] 18AL
- [ ] 18Chesapeake
- [x] 18GA
- [x] 18MS
- [x] 18TN
- [x] 1817

**Comment by perwestling** [comment]
Looking in 18GA: #1697

**Comment by perwestling** [comment]
@CaptainObi is doing 1889.

**Comment by CaptainObi** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/69726608/94058861-820f6900-fdd9-11ea-93cd-f1ea239db606.png)
This is issue one. The tile lay for this is under IR but it should actually be the player who is selling it in. 
The other one is #1558 adjacent where the Misitibushi ferry cannot be layed in a OR turn where the coorperation is not owned by the private company owner. The actual issue in #1558 will fix by itself if this is fixed.

**Comment by perwestling** [comment]
18MS had one problem: Abilities appeared during stock round. (Fixed by removing track laying as a possible action during stock rounds)
Should be fixed by #1713

**Comment by perwestling** [comment]
I'll look into 18TN, and CaptainObi in 1836Jr.

**Comment by CaptainObi** [comment]
1836jr, the CdH private does not work the round it is bought in and must be used in the next turn for some reason. game JSON, https://pastebin.com/wh5GwiZ9

**Comment by perwestling** [comment]
18GA has been fixed recently and I do not know of any remaining issues.

18AL has the problems described here: https://github.com/tobymao/18xx/wiki/18AL#known-problems

18AL and 18TN has the bonus issue reported as https://github.com/tobymao/18xx/issues/1302

**Comment by perwestling** [comment]
#1583 is relevant for 18Chesapeake and 1846.

**Comment by perwestling** [comment]
#1520 is relevant for 18Chesapeake

**Comment by michaeljb** [comment]
In 1846, none of the abilities should ever render in Stock Rounds, and in Operating Rounds should only appear when it is the owning corporation's turn. This impacts Steamboat Company, Chicago & Western Indiana, Lake Shore Line, Michigan Central, and Ohio & Indiana.

In regard to #1583, the tile lays of Michigan Central, Lake Shore Line, and Ohio & Indiana may occur any time during the owning corporation's operating turn. This is currently behaving correctly on 18xx.games, though in the game config those abilities all have `"when":"track"`, so something there is perhaps not behaving as intended. When the config is changed, we need to be sure not to break those abilities.

**Comment by michaeljb** [comment]
Created #1794 for handling 1846 company abilities

**Comment by michaeljb** [comment]
>  This is issue one. The tile lay for this is under IR but it should actually be the player who is selling it in.

@CaptainObi - I opened #1796 for this, only the logging was wrong in this case

**Comment by ccxvii** [comment]
18Chesapeake still lets both the CP and BS privates lay their extra tiles during a non-owning public company's turn if the same player is president of both the private-owning and currently operating public companies.

**Comment by perwestling** [comment]
@ccxvii I recommend writing an issue for the 18Chesapeake thing.

**Comment by jenf** [comment]
Seperated 1882 to a separate issue which i'll sort sometime soon

**Comment by perwestling** [comment]
This is a bit unfocused issue. And there has been work done with timing. So we should open issues per title when we encounter problems. (Also, the number of titles has grown and will grow further so it is not feasible to check every title.)
