### ISSUE TITLE
[1846] Issuing should be a blocking step when other pre-route steps would be skipped due to lack of cash

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1709]
If a corporation has no cash for buying privates or for laying track, its turn will skip to running routes; if it has no train, it will skip to buying a train. If a corporation has no cash but has issuable shares, it should be able to issue shares to raise funds for laying track, etc., but the site does not currently allow this.

* https://www.18xx.games/game/10481
* [10481.json](https://gist.github.com/michaeljb/a535e655ddb448e1724aeb4634c277b5)

In this game, the B&O in OR 1.2 should be able to issue shares and then place a token and/or lay track, but is unable to do so.

**Comment by PatrickoftheIsles** [comment]
We abandoned a game today after experiencing this bug because it happened at a crucial moment.

https://18xx.games/game/10486
