### ISSUE TITLE
1889: Cannot use Mitsubishi Ferry ability if not president of any corporation

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1725]
Example game: https://18xx.games/game/10498/action=57

A player owning Mitsubishi Ferry, and not being president of any corporation cannot ever lay the tile.
During SR the ability does not appear for the player owning the Ferry private.
During OR the ability is possible to display by clicking the other button, but the player cannot use the ability as the player is never the current acting player. 
It is possible, by using Master mode, to lay the tile during the OR when another player is acting, and it will show up as if the owning player had acted, but without Master mode it cannot be done.

The rules have this wording:
"Player owner may place the port tile on a coastal town without a tile on it already, outside of the operating rounds of company controlled by another player.  The player need not control a company or have connectivity to the places tile from one of their companies.  This does not close the company."

As there are no step in between ORs in 18xx.games this is not trivial.

Adding such a step is possible but it would break all existing games AND slow down future games a bit.

Making it possible to use the ability "out of turn" might be a smaller effect and should not break any game.

This is related to #1558 although that is a report on another issue.

**Comment by KenKuhn** [comment]
I just tried this in a locally hosted hotseat game and it was possible. So I'm assuming this has already been fixed.

**Comment by perwestling** [comment]
> I just tried this in a locally hosted hotseat game and it was possible. So I'm assuming this has already been fixed.

@KenKuhn In a hot seat game you control all players, so therefor it is not a problem at all in a hot seat game. Anyway I closed my attempted fix as it would have caused problems in existing games.
