### ISSUE TITLE
Can't run routes through tiles with crossings

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#1746]
at least in some cases. This particular case was reported in 18xx.games chat and I could reproduce it. https://www.18xx.games/game/10395?action=370

<img width="608" alt="10395" src="https://user-images.githubusercontent.com/1295244/94430399-d8760200-0161-11eb-8e9d-c11c6d1a3d37.png">

As IC, I'm not able to run routes through tiles B8 or D8 (e.g., if I click on Birmingham first, I can run to Tuscaloosa, Selma, or Chattanooga, but not to Memphis or Meridian).

Chat on 18xx.games indicates that this is a general issue.

**Comment by dfannius** [comment]
I can reproduce the issue on 18xx.games itself but not in my own local copy of the code (as of 66866598d69fa2d90608fa174793c17c344d912b).

**Comment by roseundy** [comment]
I can't reproduce this on 18xx.games
