### ISSUE TITLE
BoardGameGeek logging

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1750]
It would be nice to have a button to log completed games at BoardGameGeek.

**Comment by jenf** [comment]
I'm not sure how viable this will be reading the comments on https://boardgamegeek.com/thread/1531606/log-play-api

**Comment by ChrisTheCat** [comment]
As a stopgap, would it be possible to add a URL to the BGG entry for each game in the "game ended" email? That way, when someone gets the game ended email, they could just click the link and quickly log the play.

**Comment by scottredracecar** [comment]
People seem to be doing the logging manually and no one has stepped up on this request.
