### ISSUE TITLE
1846 remove free tiles from IC charter after laid

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1752]
The IC charter has "Ability Free tile lay: E5, F6, G5, H6, J4." It would be nice if the list only included hexes still available for free tile lays, i.e. dynamically remove the ones that have been placed.

**Comment by waaayback** [comment]
Even better -  leave all hexes in the list, but put a line (strikethrough) through the ones that have been used.

**Comment by scottredracecar** [comment]
Closing, I don't find this necessary to understand the game and no one is stepping up to enhance 1846 currently.
