### ISSUE TITLE
1846 2p Variant - pair of ORs during draft need to be full ORs, not just privates paying

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1757]
Current behavior is just for privates to pay, but it should be two full ORs, which includes Steamboat assignment and MS/BIG4 operating.

**Comment by michaeljb** [comment]
In the fix, hs_rbefffgr_1600814502 should be changed so that Player 2 makes some money with Big4 in the beginning but Player 1 should not make any money with Michigan Southern--thanks to emergency issuing dropping share value, Player 1 is *just* able to afford a third share of PRR at action 145, so Player 1 shouldn't get any more money.

**Comment by twotwotrainer** [comment]
https://www.18xx.games/game/11322; same as above...we didn't get two full or's. just payouts
