### ISSUE TITLE
Consider desktop notifications for the webapp

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#176]
Such a slick notification! While I normally dislike it when sites ask to notify me, this is actually an example where it would be perfect! Could have a notification for chat updates (with the chat), a notification for moves (ideally with the move just taken), and if you click the notification it opens up a tab with the game.

**Comment by tobymao** [comment]
i hate notifications, but i can make the title flash

**Comment by jcoveney** [comment]
If it's opt in only (say in a configuration somewhere that people have to find), wouldn't it be a win/win? People who dislike them under no pressure to get them, people who like them get them, and it could hook directly into the same code path that sets up email notifications.

Of course it's ultimately your call, as you're doing all the work :) But I think that for a game like this, a notification like "so and so said so and so in chat" is quite actionable and nice. I hate notifications 99% of the time, but this is a natural application of them.

**Comment by jcoveney** [comment]
I should add that given the app is responsive enough to play "live" over the internet, not having some form of notification would mean players would have to focus a lot more on the game. I guess I could make the email notifications more prominent, but the downside to that is that notifications are inherently transient (which is perfect for this case). With email notifications, if one is in a lot of games, when you wake up there may be hundreds of messages if people have been chatting.

**Comment by jcoveney** [comment]
If I implement it like I mentioned above (opt-in via settings), would you be open to this as a contribution, or is it something you don't want in the app? I'm willing to roll up my sleeves and learn the code :)

**Comment by tobymao** [comment]
yes, only if you do it :D

**Comment by jcoveney** [comment]
Two questions for @tobymao  (happy to discuss in slack)

1. how is the client updated? that is to say, if the game is open, how do notifications come?
2. is there a model for embedding/running javascript functions? I know the purpose of your ruby wrapper is to avoid writing javascript (+1!!!), but for notifications it seems unavoidable?

Thank you!

**Comment by sparr** [comment]
Standard desktop notifications from web apps are fully under the user's control. You can decline when the site asks. Or you can accept and tell your browser how to expose them to the OS. And then you can tell the OS what to do with them.

@jcoveney I don't know the "right" way to do this, but you can embed javascript directly into the event handler with
```
 `javascript.function(#{rubycode})`
```

**Comment by tobymao** [comment]
solved for now by changing the title
