### ISSUE TITLE
1846 route finder error

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#1764]
In this game - https://18xx.games/game/11142?action=719 - the system insists on creating the route between Dayton and Springfield by using track that loops north of Fort Wayne (g13-f14-e13-d12-d10-d8-e7-e5-f4-g3). It will not use track that goes south of Fort Wayne (g13-f11-f10-f8-e7-e5-f4-g3).

**Comment by dfannius** [comment]
Confirmed locally.

**Comment by dfannius** [comment]
And confirmed that it's not the overlap code (I commented it out entirely and the problem persists).

It understands both ways of getting from Dayton to the SW Chicago city (where the NYC token is), though.

**Comment by dfannius** [comment]
In the same OR, as C&O I can run from Springfield to Terre Haute but not from Springfield to Indianapolis or Toledo.

(That's it for my triaging; someone who knows the route code should take it from here.)

**Comment by dfannius** [comment]
I did do a little more research. When the green tile is laid on G3, only one of the connections from G3 to G13 is created (there should be two). I don't know whether it's found and then discarded or never found.
