### ISSUE TITLE
1846 game 10135 log OR misnumbered

### ISSUE THREAD

**Issue by cw67q** [tobymao/18xx#1765]

**Comment by cw67q** [comment]
ORs are misnumbered in the log. All OR are numbered X.1 ie sequence runs 1.1, 1.1, 2.1, 2.1, etc

**Comment by perwestling** [comment]
@cw67q I checked a random game (https://www.18xx.games/game/11369) and it looked OK to me. Do you have a game number where this occurs?

**Comment by cw67q** [comment]
Hi Per the game in question is 10135 (the one in the header)

Thanks, chris

**Comment by cw67q** [comment]
By “gaming log” I mean the scrolling commentary that is visible on game (in case I am using the wrong term)

**Comment by michaeljb** [comment]
This was fixed in 44740e5c, but 10135 is pinned to an older version (63dbae2c). Unfortunately this means it cannot be fixed for 10135.
