### ISSUE TITLE
1846 C&WI spot no longer reserved after purchase

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#1774]
https://www.18xx.games/game/10906?action=200

After purchase the reserved spot mark disappears and anyone can build there (even before the browns arrive)

as far as I know you can use the ability in another OR, the teleport works and only for the reserved spot.

**Comment by dfannius** [comment]
I believe this was an intentional change: https://github.com/tobymao/18xx/pull/1653

**Comment by dfannius** [comment]
See https://boardgamegeek.com/thread/1203571/article/35362506#35362506 for a clarification from the designer that this is the correct behavior (point 4).

**Comment by dfannius** [comment]
I'm going to mark this as resolved, but feel free to reopen if something isn't clear or you think I'm wrong and there is a bug.

**Comment by PedroRCSequeira** [comment]
Ok I got it, my bad, just to clarify, the ability can still be used in later rounds, right?

**Comment by dfannius** [comment]
It looks like that is the rule, so if it is not implemented that way, it is a bug.
