### ISSUE TITLE
While running trains, a 1-city route was allowed

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#179]
However according to rule 8.2 from t[he deepthought rules](http://www.deepthoughtgames.com/games/1889/Rules.pdf), 

> A train may not run on a route shorter than length two, therefore a 2-train must run routes of exactly length two.

For instance, a yellow straight was laid WNW out of the KO home tile, but no tile yet in Marugame (I2)

I was allowed to run K4 to J3, and it paid 30 for having the KO home tile in there.

The JSON for the game lists it as a route including from K4 to J3. 
```

{
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 62,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "K4",
            "J3"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "K4",
            "K6",
            "L7"
          ]
        }
      ]
    }

```

Full blob here: 

[SingleCityRouteAllowed.txt](https://github.com/tobymao/18xx/files/4537616/SingleCityRouteAllowed.txt)
This was in a hotseat game.

**Comment by jenf** [comment]
Should be resolved
