### ISSUE TITLE
1860 Special Rules Summary

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#1791]
Rules: [https://boardgamegeek.com/filepage/79633/second-edition-rules](https://boardgamegeek.com/filepage/79633/second-edition-rules)

### Money

- [x] Corporation money (Company Credits "(cc)") is distinct from player money and the Bank.

### Tiles

- [x] Cowes has two dits/halts and a city. This will have multiple intra-tile paths as this upgrades. This will break the ability to restore routes unless Connection::id is modified, possibly in a way that will break all games unless a migration path is built.
- [x] Implement halts. Subclass of towns?
- [x] Newport, Merstone and Ryde upgrades have fixed rotations

### Initial Auction

- [x] New auction type. Players bid on the chance to buy one of four privates or one of two presidencies. Winner chooses which of the remain items to buy (not optional). Pays bid value plus face value of item.
- [x] If no bids, first to pass (first bidder) wins.
- [x] Player to left of winner is first bidder in next auction.
- [x] Priority Deal goes to player with most cash after initial auction completes. If there is a tie, across all players: player with lowest total face value of private companies and owning at least one private company wins Priority Deal.

### Market

- [x] New market type. Essentially linear, but displayed as two rows.
- [x] Per corporation par values. Par values change between initial offering and after liquidation (bankruptcy)
- [x] Red areas that ignore first share sold for movement
- [x] Bankruptcy at left
- [x] Game end at right
- [x] 1, 2, 3, 4x jumps when paying out

### Private Companies

- [x] There are four private companies that are available in initial auction, each associated with a specific corporation.
- [x] As a free action during the SR, the starting privates can be exchanged for one share of their associated corporation if that corporation's director's certificate has been bought and a par price set. Until that exchange occurs or the private is closed, one share of the associated corporation is reserved in the IPO and cannot be purchased.
- [x] Fifth private company is Fishbourne Ferry Company. Not available until first 6+2 train is bought, whereupon it is placed in the bank and is available for purchase. When Fishbourne is bought, all other private companies immediately close.
- [x] After SR1: Privates can be sold to the bank for face value minus 30 during the SR
- [x] Privates in the bank can be bought during the SR for face value.

### SR

- [x] Corporations are offered in tranches or layers. Can't buy stock from a corporation in the next layer until either:
a. At least one corporation in the current layer has operated, or
b. All shares in at least one corporation in the current layer has had all of its shares sold from the IPO. Note that for four of the corporations, that will not be possible if the corresponding private company is still open and unredeemed.
- [x] Home token is laid upon flotation (50%).
- [x] Upon flotation, if the starting hex for that corporation does not have a tile, the president gets an immediate and free tile lay.
- [x] There is no upper limit to the number of shares a player may own in one corporation
- [x] There is no upper limit to the number of shares a corporation may have in the stock pool.
- [x] Can sell director's certificate to bank (if no other player has at least two shares). The corporation will go into Receivership.
- [x] When selling only one share of director's certificate, there must be one share in stock pool in order to exchange it. Selling both shares of a director's certificate is always OK.
- [x] When buying a share of a corporation in Receivership, if the player has no shares for that corporation, there must either be at least one available single share (i.e. not a Director's certificate) in the stock pool or IPO. Otherwise, if the player already owns one share, it will be swapped for the Director's certificate in the stock pool.
- [x] Shares for a trainless corporation are sold at half price, rounding down
- [x] Stock rounds can be restarted due to Bankruptcy (see below).
- [x] Share price will not change when selling corporations that have not operated
- [x] After the 8+4 train is bought, the certificate limit is ignored and share sales do not affect prices

### Bankruptcy, Receivership, Insolvency

- [x] If a corporation's share price reaches the left side of the market (share price == 0), it enters Bankruptcy. The following then occurs:
a. All shares are returned to IPO w/o compensation
b. The corporations tokens are "flipped over", but remain on the board. These flipped over tokens block for the purposes of track development, but not for running routes.
c. Priority deal is given to the player with the fewest shares (not fewest certificates). Ties go to closest to current priority deal.
d. If this happens in a SR, a new SR begins (now can buy shares sold previous to bankruptcy).
e. A new set of par prices apply to the bankrupted corporation: between 40 and upper end of original par range for that corporation.
f. As soon as bankrupted corporation floats, it's tokens are flipped back over.
g. The bankrupted corporation retains any trains, cash, tokens (and insolvency status) it may have had.
- [x] If the president certificate for a corporation is in the bank, it is in Receivership. The following then applies:
a. The corporation can't lay track or tokens, nor buy a train if it already owns one.
b. It runs trains for maximum revenue (determined by players), but must withhold
c. If it has no train at the start of it's turn and has a valid route, it enters Insolvency immediately. Note that this is different from corporations outside of Receivership.
d. It exits Receivership as soon as a player owns a second share in the corporation.
- [x] A corporation that ends its turn without a train and has a valid route enters Insolvency at the end of its operating turn. The following then applies to that corporation:
a. They cannot lay track that would incur a cost.
b. They cannot place tokens
c. They run their routes with a "leased" train. It leases the smallest train available from the bank or IPO. Normal route rules apply, but receives a leasing revenue of 40cc + 20cc per city/town/halt. For this purpose ignore the the number after the "+" for that train. They must withhold revenue
d. Insolvent corporation shares are sold at half market price
e. They must buy a train as soon as it is able to
f. They exit Insolvency as soon as they have funds to buy a train from the bank or IPO. Note that in rare cases this can happen before the running routes step.

### Operating Rounds, Trains and Running Routes

- [x] Can either lay two yellow tiles without cities, one yellow tile with a city, or upgrade one tile
- [x] Can't upgrade without a train
- [x] Can only upgrade tiles reachable with one of the owned trains from a tokened station
- [x] Upgraded tiles must either contain additional track reachable from the company, or increased revenue on a halt, town, or city reachable from the company
- [x] If running multiple trains, the individual routes must have a city, town or halt in common
- [x] Routes can start and end in cities or towns, but not halts
- [x] At least one route must contain the "home" token
- [x] Once a train leaves a hex, it may not re-enter that hex
- [x] A single train may pass through one single tokened-out city
- [x] Trains can bypass halts and small stations, but not cities
- [x] Halts pays 10cc directly to the corporation treasury
- [x] The first number on a train is the maximum number of cities the train can visit. If the train runs to fewer than that number, it may stop at one additional town or halt for each unused allowance. The second number is the maximum number of towns and halts it can visit in addition to the those covered by the first number.
- [x] Shares in IPO or bank do not earn dividends

### Buying Trains

- [x] When buying trains across corporations, it must be a minimum of 10cc and multiple of 10cc
- [x] Cannot buy the last train from a corporation unless the buying corporation has no trains.

### End of Game

- [x] Ends if any corporation hits 340 on the market. Game ends at the end of the current OR
- [x] Bank runs out of money prior to Nationalization. If in OR, finish the current OR. If in SR, finish the next OR.
- [x] End of game is triggered after the sale of the first 9+5 train (formation of the Southern Railway). The railways are nationalized into the Southern Railway
- [x] Value of shares of corporation w/o trains is half normal value (rounded down)

### Formation of the Southern Railway

- [x] When first 9+5 train is bought, starting with next OR after the next SR no track or tokens can be laid and halts are ignored (even for leased trains).
- [x] At end of each SR and OR, check to see if railways are Nationalized: are all corporations that have a president solvent (i.e. have a train)

### Nationalization

- [x] No more SRs
- [x] Game cannot end due to bank breaking
- [x] If Nationalization was triggered at the end of an OR (as opposed to a SR), track and tokens can still be laid.
- [x] Number after train "+" is ignored
- [x] Corporations in Receivership pay nothing to shareholders
- [x] Corporations cannot withhold
- [x] Companies may buy additional trains if they can afford to, but any trains must be bought from the bank, and not other companies
- [x] At end of each OR, the two corporations that paid the lowest dividends cease to operate (may be more than two if tied)
- [x] Game ends when all have ceased (or a corporation hit 340 in market)

**Comment by roseundy** [comment]
Of all the changes required to implement 1860 the following are going to require the most work:

1. Dealing with the Cowes tile and it's multiple intra-tile paths. This is going to break restoring a route from JSON.
2. The need to select which towns and halts to count in a route.
3. The need to select and then to deal with routing through a tokened-out city.

**Comment by Kalnoch** [comment]
Bypassing towns and allowing for the X+Y is already supported I believe, I have a similar setup going on my test game that uses a derivation of 18OE mechanics

**Comment by roseundy** [comment]
I'm not sure how the UI would allow splitting town/halt visits, since the the split offers different benefits between shareholders and the corporatin

**Comment by Kalnoch** [comment]
True, likely have to implement new stop type? Any other games use halts?
