### ISSUE TITLE
Don't show the "upgrade discount" column when the game has no discounts

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#1792]
On the info page, the upcoming trains table has an "upgrade discount" column that is always displayed, even if the game does not have any train discounts. The column shouldn't appear for these games.

**Comment by CaptainObi** [comment]
I will attempt to fix this, this looks similar to another bug I fixed a while back.

**Comment by CaptainObi** [comment]
I actually will not be able to, my development environment is acting up.
