### ISSUE TITLE
1846 - company abilities should only be available during the owning corporation's OR turn

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1794]
See #1704

In 1846, none of the abilities should ever render in Stock Rounds, and in Operating Rounds should only appear when it is the owning corporation's turn. This impacts Steamboat Company, Chicago & Western Indiana, Lake Shore Line, Michigan Central, and Ohio & Indiana.

In regard to #1583, the tile lays of Michigan Central, Lake Shore Line, and Ohio & Indiana may occur any time during the owning corporation's operating turn. This is currently behaving correctly on 18xx.games, though in the game config those abilities all have "when":"track", so something there is perhaps not behaving as intended. When the config is changed, we need to be sure not to break those abilities.

The Steamboat Company is a sort of exception to this; while owned by a player, there is a special blocking Assign step at the beginning of the OR; that step can remain unchanged.

**Comment by arcee1986** [comment]
Note that at present, if the purchasing corp has to buy after they get money from running routes, and either has no money left or has bought the last company, they cannot use the ability on their own turn as the game will skip to the next turn.  So using on the next corp's turn is a workaround.
