### ISSUE TITLE
On tools page, please add a "save as" button to download the JSON

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#180]
I believe this will make it easier to debug rules/logic issues in the future, by making it easier for people to post the game state at the time of the bug. 

Next level beyond that would be to link directly to the "new issue" github form, with the JSON blob pasted in

**Comment by chrispday** [comment]
Also a copy to clipboard for easy pasting into issues would be good too.

**Comment by yoyoson** [comment]
> Also a copy to clipboard for easy pasting into issues would be good too.

I think this is the best idea

**Comment by tobymao** [comment]
i added the copy button
