### ISSUE TITLE
OR view stopped redrawing properly during Lay Track 

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#181]
1. I have a game where the IR president created a tiny triangle with F1, E2, and F3. They cannot upgrade out of this until green phase starts. 
2. During the track lay portion of IR, click on E2. It gets a bold outline. 
3. Now click on Imabari (F1) (nothing visible happens) 
4. Now click on "Pass"
5. Now the game is in a wonky state, where it's still changing state invisibly or behind the scenes, but the screen doesn't redraw. 
6. You can press pass multiple times (less than dozen) and it will eventually pass through the whole OR to the next SR. At that point it will redraw the screen, and the log will update showing all the passed OR actions. 
7. You can also press "Undo" to go back to previous SR.  But the OR screen will not redraw anymore.

You can get out of this state by refreshing the page in the browser. 

Possibly related to #28 
I'm using Windows 10 Chrome Version 81.0.4044.113 (Official Build) (64-bit)

Here is the game file 
[ORNotRedrawing.txt](https://github.com/tobymao/18xx/files/4537713/ORNotRedrawing.txt)

**Comment by tobymao** [comment]
yes, it is related to #28 thanks
