### ISSUE TITLE
18MS: Bank does not have to be visible

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1810]
18MS has an unlimited bank, and is therefor not visible, except in the Entities tab.
![image](https://user-images.githubusercontent.com/2631151/95665226-a778d280-0b4e-11eb-87f8-8583a9f6931c.png)

I think it should be hidden from view when it has not function.

**Comment by doleksy** [comment]
Hello all, I am Dave. I am new around here and I think this would be a good first issue for me to work on.
