### ISSUE TITLE
Publishing Permissions from Mr. Bill Dixon

### ISSUE THREAD

**Issue by Mark894xx** [tobymao/18xx#1811]
Subject: Re:1870 Publishing rights
MarkH894 wrote:
Mr. Dixon,

First, let me say that 1870 is my favorite and most played 18xx game. Sadly, due to a lack of folks that will play 18xx games in my area I have not been able to play any 18xx games for 20+ years.
That is until I recently discovered a wonderful new platform over at 18xx.games
Toby has created a very special place for lovers of 18xx games.
I am writing to you to see if you might be open to allowing Toby to add 1870 to the 18xx.games library.
It may even lead to an opportunity to see 1870 back in print for many new players to discover and enjoy.

Thanks in advance for you time

Mark Hoover

![Capture](https://user-images.githubusercontent.com/69325888/95665234-69fb5180-0b1c-11eb-816f-d6eed90aa4f2.PNG)

Hi Mark

I have been playing on 18xx.games and enjoying new games that I have never played before.
Not a full replacement to the one or two FTF 18xx games a month I was getting in, but still fun.

I see no problem with Toby adding the game to the web site.
Please let him know that he has my permission to add any of my games to his site.

Regards
Bill Dixon

**Comment by tobymao** [comment]
whoa thanks.
