### ISSUE TITLE
Make the doubling feature of diesels a configurable thing

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1814]
Right now there are diesels in some title that double revenue from stops but with slightly smaller difference

- 4D of 18MEX/18AL/18CO is a 4+ train that double cities and off-boards, but can run an unlimited number of towns
- 5D of 18CO is a similar 5+ train
- 2D/4D/5D of 18MS is a standard 2/4/5 train that double any stops

The "4+D" functionality used in 18MEX/18AL(/18CO) is a module you can include in the game code. It could be refactored to work for any number, in which case it would cover 5D of 18CO as well.

The 2D/4D/5D functionality of 18MS is handled in the 18MS game code.

My suggestion is to enhance the game configuration for trains to support doubling of certain stops.

Here is how the configuration on an "4+D" train is done in 18CO. (Similar in 18AL/18MEX)
```
		{
			"name": "4D",
			"distance": [
				{
					"nodes": [
						"city",
						"offboard"
					],
					"pay": 4,
					"visit": 4
				},
				{
					"nodes": [
						"town"
					],
					"pay": 0,
					"visit": 99
				}
			],
			"available_on": "5",
			"price": 650,
			"num": 3
		},
```
My suggestion is to add a "doubling" which would specify which stops that should be doubled.
It could look like this for the "4+D" train type:
```
		{
			"name": "4D",
			"doubling": [
				{
					"nodes": [
						"city",
						"offboard"
					]
				},
```
Or add as a field in the distance structure:
```
			"distance": [
				{
					"nodes": [
						"city",
						"offboard"
					]
                                        "double":true,
					"pay": 4,
					"visit": 4
				},
				{
					"nodes": [
						"town"
					],
					"pay": 0,
					"visit": 99
				}
			],
```
In all cases if not double specified, it should pay normal.

A question is this should be generalized further? E.g. if the double attribute in the last case should be some general attribute that take ["double"] as value? E.g. "modifier":["double"],

That last comment is this could be used for handling E trains. In 1822 the E trains double all stations with the corporation token in (if I remember correctly) so how should that be expressed?

**Comment by ryandriskel** [comment]
Note: The 4D/5D in 18CO _do not pay towns at all_, unlike 18AL.

I have a slightly different suggestion, a multiplier attribute, assumed 1.

`"distance": [
				{
					"nodes": [
						"city",
						"offboard"
					]
                                        "multiplier":2,
					"pay": 4,
					"visit": 4
				},
				{
					"nodes": [
						"town"
					],
					"pay": 0,
					"visit": 99
				}
			],`

**Comment by ryandriskel** [comment]
@perwestling I believe this can be closed. I didn't have the automated issue linking done at the time the pr was merged.

**Comment by perwestling** [comment]
Thanks @ryandriskel
