### ISSUE TITLE
1846 - Issuing shares/undo during run trains step messes up train pathing/calculation

### ISSUE THREAD

**Issue by yoyot1** [tobymao/18xx#1816]
See attached screen recording.  Ultimately the game prevents the invalid action, but can be confusing. 

On my turn, I laid track, and did not token.  On the run trains step, the prior path was filled in from prior turn, with $210 payout.  I issued 2 shares, and then clicked undo.  The issue shares was undone, and the path was cleared out, but the submit button still shows $210.  I re-selected the same path, but it now shows the path value as $170, and the submit button shows $380.  Clicked submit and get the error message "Cannot run another corporation's train, refresh".  The route resets to the correct value, and then submit works.
[Screen Recording 2020-10-11 at 3.29.53 PM.zip](https://github.com/tobymao/18xx/files/5361851/Screen.Recording.2020-10-11.at.3.29.53.PM.zip)

**Comment by tobymao** [comment]
can you link the game and relevant action?

**Comment by yoyot1** [comment]
https://www.18xx.games/game/10839?action=350 is the start of the turn.

I think there is a related issue where the Undo button stops working when you've done some "out-of-order" share issuance in 1846, but I've not been able to reproduce reliably yet.

**Comment by yoyot1** [comment]
I'm sorry, https://www.18xx.games/game/10839?action=286 is the *actual* start of the turn - I did a bunch of undoing-redoing to figure out how to reproduce.
