### ISSUE TITLE
Action buttons placement

### ISSUE THREAD

**Issue by massayoshi** [tobymao/18xx#183]
It would be better if the buttons showed up right after the div we are clicking on, like on the screenshot below. Instead of being added to the end of the list.

![Screenshot 2020-04-27 at 18 32 33](https://user-images.githubusercontent.com/609562/80402212-82044f00-88b5-11ea-8a20-f8f3109ef698.png)

This also happens when bidding for the private companies at the beginning.

**Comment by tobymao** [comment]
this change will happen with 

https://github.com/tobymao/18xx/pull/151

**Comment by massayoshi** [comment]
Should've looked through the commits. I'm sorry!

Thank you!

**Comment by tobymao** [comment]
it's not fixed yet, it's a PR
