### ISSUE TITLE
1817 cosmetic improvement to stock market

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1831]
Values 50, 70, and 120 should have an underscore, or some way to indicate that they are the values needed for a 2,5,10 share company to float, take maximum loans, and not enter acquisition.

Values 50-200 should have an indication of valid par values.

**Comment by joshyboy20k** [comment]
Additionally, is there a way to remove the "40" value from the Acquisition area? A price implies that shares can be bought or sold.

**Comment by ChrisTheCat** [comment]
Or perhaps put it in parentheses? It does indicate how much need to be paid
to move up on the stock market, or to double jump.

**Comment by joshyboy20k** [comment]
> Or perhaps put it in parentheses? It does indicate how much need to be paid to move up on the stock market, or to double jump.
Hmm. Yeah that's a good suggestion. Perhaps better than how it's currently represented in the physical game even.

**Comment by bubba0077** [comment]
The first highlighted number should be 55, not 50.
