### ISSUE TITLE
1817 Floating company stopped too early / wrong par price (game breaking)

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1833]
<img width="1316" alt="Screen Shot 2020-10-12 at 10 47 16 AM" src="https://user-images.githubusercontent.com/8732435/95777777-b14c2400-0c7b-11eb-80b5-9c97bb5d1508.png">

In this hotseat game, Player 2 won the auction for A&S with a bid of 140. Adding the Pittsburgh Steel Mill at 40 leaves 100 to contribute. Adding the Coal Mine at 60 leaves 40 to contribute. The game should allow Player 2 to also contribute the Mountain Engineers at 40 (even if this would be a strategic mistake), but instead it skips back to the auction and contributes 40 cash.

<img width="508" alt="Screen Shot 2020-10-12 at 11 13 38 AM" src="https://user-images.githubusercontent.com/8732435/95777972-025c1800-0c7c-11eb-9976-2329f2036b7a.png">

Note that the par price was incorrectly set at 65 rather than 70 - however, the total contributions of privates (60+40) and cash (40) = 140 as bid.

**Comment by ChrisTheCat** [comment]
I also just noticed that the log incorrectly set the par price at 65, instead of 70.

**Comment by jenf** [comment]
Do you have a json for this?

**Comment by ChrisTheCat** [comment]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "MINC",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "company": "PSM",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "company": "CM",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "company": "CM",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "company": "OBC",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14,
      "company": "ME",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 17,
      "company": "MINM",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "company": "TS",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 23,
      "company": "UBC",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 26,
      "company": "MAIL",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "company": "MAJC",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "company": "MAJC",
      "price": 70
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "company": "MAJM",
      "price": 95
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 36,
      "corporation": "A&S",
      "price": 120
    },
    {
      "type": "place_token",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 37,
      "city": "F13-5-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 41,
      "corporation": "A&S",
      "price": 140
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "assign",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 43,
      "target": "PSM",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 44,
      "target": "CM",
      "target_type": "company"
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "assign",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 46,
      "target": "CM",
      "target_type": "company"
    }
  ],
  "id": "hs_rosmrgey_1602523185",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1817",
  "description": "testtest",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-12",
  "loaded": true,
  "result": {}
}
