### ISSUE TITLE
[1817] Adjust language from "20% to float" to "2 shares to start"

### ISSUE THREAD

**Issue by joshyboy20k** [tobymao/18xx#1834]
Only 2 shares are needed for a company to become operational in 1817. These 2 shares might be from a 2, 5, or 10 share company (100%, 40%, or 20% respectively). 

![1817 companies](https://user-images.githubusercontent.com/46472947/95780562-f7f04d00-0c80-11eb-8987-4abef61ee95f.png)

I'd suggest changing the language from "20% to float" to "2 shares to start". "Float" usually references full cap games which 1817 is not.

**Comment by bubba0077** [comment]
With companies floating immediately, it might be even better if the message was changed to the starting size(s) available given the current phase.
