### ISSUE TITLE
1817 Corporation ordering improvement during SRs

### ISSUE THREAD

**Issue by KenKuhn** [tobymao/18xx#1838]
The amount of corporations at play makes seeing what's going on and which corporation belong to visually overwhelming.

Would be nice:

- The corporations that belong to you were outlined
- There were two columns: one column of started companies and one for unstarted companies.
         -my thinking here is you'd be able to buy stock on the left and start a new company on the right.
         -Also, maybe during SR1 the companies could be displayed in reverse. Unstarted at top/left, started on bottom/righ

**Comment by giovandc** [comment]
I'd argue that this suggestion could be implemented for the private auction too.
The private which is being auctioned should be displayed as first, even better if separated from the others. This is even more needed in mobile view.
