### ISSUE TITLE
1817 Hotseat Crash During Take Loan Phase

### ISSUE THREAD

**Issue by nigelsandwich** [tobymao/18xx#1839]
I was just clicking around and it locked up during the Take Loan Phase of OR 1

https://gist.github.com/nigelsandwich/b7343388b974a2d842101d7bcd53e111

**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by tobymao** [comment]
looking
