### ISSUE TITLE
[1817] Player order breaking during private company auction

### ISSUE THREAD

**Issue by joshyboy20k** [tobymao/18xx#1840]
- Player 1 bids on a private company
- Player 2 outbids
- Player 3 passes
- Action goes to Player 2 instead of Player 4

https://gist.github.com/joshyboy20k/d35795b9e6d5812776f084dfa9336637

**Comment by joshyboy20k** [comment]
NB: This happened after I had some history in the game and hit "Undo" back to the start of the game. When I spin up a fresh Hotseat game, I don't see this behavior.

**Comment by KenKuhn** [comment]
This was fixed by @jenf earlier today not sure if it made it into this version?

**Comment by tobymao** [comment]
can't repro
