### ISSUE TITLE
[1817] Incorrect minimum bids for private companies

### ISSUE THREAD

**Issue by d-choo** [tobymao/18xx#1841]
In the private company auction, some of the companies seem to have set values for the minimum bids. For example, Pittsburgh Steel Mill has a min bid value of $5 while the Train Station has a min bid value of $45. They should all start at $0.

**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by jenf** [comment]
No JSON provided. Yesterday I started Pittsburgh at zero so only way I can imagine this occuring is if the seed money ran out.

**Comment by jenf** [comment]
Cannot reproduce
