### ISSUE TITLE
[1817] Loan information

### ISSUE THREAD

**Issue by ArielAyanna** [tobymao/18xx#1844]
Number of loans taken/remaining grouped in sets of fives and current interest rate should be shown under "info" and "spreadsheet." Would also be useful to know current interest rate on game tab. Useful on both OR turns and SR turns.

**Comment by jenf** [comment]
Information is already on the entity pag

**Comment by daniel-sousa-me** [comment]
It used to be, but it disappeared

**Comment by jenf** [comment]
Caused by #1810

**Comment by ArielAyanna** [comment]
Entities is not a useful tab for this info,  since it doesn't relate to entities.  If nowhere else,  it should be under information tab.  Also could include current loan rate in text box at start of every OR, since that is set for whole OR.

**Comment by dfannius** [comment]
The bank is an entity and is typically where we show that sort of information. (Which is not to say it couldn't also be displayed elsewhere if it's information that people always want in front of them.)

**Comment by ArielAyanna** [comment]
I'm not sure i agree the bank is an entity in this game,  since it cannot be owned. It is more akin to pure game state information,  aka information tab.

**Comment by dfannius** [comment]
No one owns the bank in any of the other (implemented) titles either! We put bank-related information there like the amount of money left in the bank and discarded trains. Of course that information can be displayed elsewhere as well (like the amount of money remaining currently is).

**Comment by ArielAyanna** [comment]
Well, I think amount of money left in bank and discarded trains should also be under information tab :)
