### ISSUE TITLE
[1817] private companies appear to count towards certificate limit. they should not.

### ISSUE THREAD

**Issue by tom-blight** [tobymao/18xx#1845]
in hotseat game test 
![image](https://user-images.githubusercontent.com/48089193/95832624-d489d880-0d3a-11eb-8cd7-742066e04ab7.png)

**Comment by jenf** [comment]
Where in the rules does it say they should not?

**Comment by tom-blight** [comment]
I’m looking at version 1.0 of the original rules, apologies if this has
changed in more recent revisions... but quite an important rule since
private companies never close.

Page 6
