### ISSUE TITLE
Suggestion: in-game chat either bold/different colour then in-game log

### ISSUE THREAD

**Issue by rthomp9595** [tobymao/18xx#185]
Finding the in-game chat quite handy and useful. If possible it would be nice to have it different font/typeface than the in-game log text.

Just a nice to have/suggestion - definitely not a complaint! This site is coming along so nicely, great work!
Rob Thompson

**Comment by dfannius** [comment]
Enthusiastically seconded. Also it would be nice if you could toggle the display of chat and the log text independently, so you could see one or the other or both interleaved (as now).

**Comment by webbtraverse08** [comment]
Thirded. Does undo also remove chat entries as it does on rollingstock.net? Because that's also awkward and confusing, if you're trying to negotiate how much to undo. So if there's a way to separate them entirely, into parallel text boxes, that would be great, too.

**Comment by jenf** [comment]
Bold will be fixed in #272 
But not removing the messages on undo will take a bit more effort and a more specific bug is available for it #263
