### ISSUE TITLE
[1817] Game not loading; hex error of some variety

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#1855]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 1,
      "company": "MAJM",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 2,
      "company": "MAJM",
      "price": 95
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 3,
      "company": "MAJM",
      "price": 100
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 4
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 5
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 6,
      "company": "MAJM",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 7,
      "company": "MAJM",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 8,
      "company": "MAJM",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 9,
      "company": "MAJM",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 10,
      "company": "MAJM",
      "price": 120
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 16,
      "company": "ME",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 17,
      "company": "ME",
      "price": 5
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 18,
      "company": "ME",
      "price": 10
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 19,
      "company": "ME",
      "price": 15
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 20,
      "company": "ME",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 21,
      "company": "ME",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 22,
      "company": "ME",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 25,
      "company": "MAJC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 26,
      "company": "MAJC",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 27,
      "company": "MAJC",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 28,
      "company": "MAJC",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 29
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 31,
      "company": "MINC",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 32,
      "company": "MINC",
      "price": 5
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 33,
      "company": "MINC",
      "price": 10
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 34,
      "company": "MINC",
      "price": 15
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 36,
      "company": "MINC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 37,
      "company": "MINC",
      "price": 25
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 39,
      "company": "OBC",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 40,
      "company": "OBC",
      "price": 5
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 41,
      "company": "OBC",
      "price": 10
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 42,
      "company": "OBC",
      "price": 15
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 43,
      "company": "OBC",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 46,
      "company": "OBC",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 47,
      "company": "OBC",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 49
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 50,
      "company": "TS",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 53,
      "company": "PSM",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 54,
      "company": "PSM",
      "price": 5
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 55,
      "company": "PSM",
      "price": 10
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 56,
      "company": "PSM",
      "price": 15
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 57,
      "company": "PSM",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 58,
      "company": "PSM",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 59,
      "company": "PSM",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 60,
      "company": "PSM",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 61,
      "company": "PSM",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 62,
      "company": "PSM",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 64
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 65,
      "company": "MAIL",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 66,
      "company": "MAIL",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 67,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 68,
      "company": "MAIL",
      "price": 85
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 69
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 70
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 74,
      "corporation": "UR",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 75,
      "city": "I12-1-0",
      "slot": 0
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 76,
      "corporation": "UR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 77,
      "corporation": "UR",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 78,
      "corporation": "UR",
      "price": 115
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 81,
      "target": "MAJC",
      "target_type": "company"
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 83,
      "target": "MAJC",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 84,
      "corporation": "PLE",
      "price": 120
    },
    {
      "type": "place_token",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 85,
      "city": "F13-5-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "assign",
      "entity": "North",
      "entity_type": "player",
      "id": 88,
      "target": "PSM",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "North",
      "entity_type": "player",
      "id": 89,
      "target": "MINC",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 90,
      "corporation": "A&S",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 91,
      "city": "H3-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "assign",
      "entity": "East",
      "entity_type": "player",
      "id": 94,
      "target": "OBC",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "East",
      "entity_type": "player",
      "id": 95,
      "target": "MAIL",
      "target_type": "company"
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 97
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 98
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 99
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 100
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 101
    },
    {
      "type": "take_loan",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 102,
      "loan": 0
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 103
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 104
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 105
    },
    {
      "type": "lay_tile",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 106,
      "hex": "H3",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 107,
      "hex": "H5",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "take_loan",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 108,
      "loan": 0
    },
    {
      "type": "buy_train",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 109,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "take_loan",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 110,
      "loan": 1
    },
    {
      "type": "buy_train",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 111,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 112
    },
    {
      "type": "redo",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "lay_tile",
      "entity": "PSM",
      "entity_type": "company",
      "id": 114,
      "hex": "F13",
      "tile": "X00-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "MINC",
      "entity_type": "company",
      "id": 115,
      "hex": "G12",
      "tile": "8-1",
      "rotation": 1
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "PSM",
      "entity_type": "company",
      "id": 118,
      "hex": "F13",
      "tile": "X00-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 119,
      "hex": "F15",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 120
    },
    {
      "type": "lay_tile",
      "entity": "MINC",
      "entity_type": "company",
      "id": 121,
      "hex": "F15",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "take_loan",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 122,
      "loan": 2
    },
    {
      "type": "buy_train",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 123,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 124
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 125
    },
    {
      "type": "lay_tile",
      "entity": "MAJC",
      "entity_type": "company",
      "id": 126,
      "hex": "H11",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "take_loan",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 127,
      "loan": 3
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 128,
      "hex": "I12",
      "tile": "6-0",
      "rotation": 2
    },
    {
      "type": "take_loan",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 129,
      "loan": 4
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 130,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "convert",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 132
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 133
    },
    {
      "type": "convert",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 134
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 135
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 136
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 137
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 138
    },
    {
      "type": "lay_tile",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 139,
      "hex": "I6",
      "tile": "9-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 140
    },
    {
      "type": "run_routes",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 141,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H3",
              "H1"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "H3",
              "H5",
              "I6",
              "J7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 142,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 143
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 144,
      "hex": "F17",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 145,
      "hex": "F19",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 146,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F19",
              "F17",
              "F15",
              "F13"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 147,
      "kind": "payout"
    },
    {
      "type": "take_loan",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 148,
      "loan": 5
    },
    {
      "type": "buy_train",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 149,
      "train": "2+-0",
      "price": 100,
      "variant": "2+"
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 150
    },
    {
      "type": "undo",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 151
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 152
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 153
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 154
    },
    {
      "type": "dividend",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 155,
      "kind": "half"
    },
    {
      "type": "take_loan",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 156,
      "loan": 5
    },
    {
      "type": "buy_train",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 157,
      "train": "2+-0",
      "price": 100,
      "variant": "2+"
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 158
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 159,
      "hex": "H9",
      "tile": "6-1",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 160,
      "hex": "I14",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 161,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "H9",
              "H11",
              "I12"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 162,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 163
    },
    {
      "type": "merge",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 164,
      "corporation": "UR"
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 165
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 166
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 167
    },
    {
      "type": "undo",
      "entity": "South",
      "entity_type": "player",
      "id": 168
    },
    {
      "type": "undo",
      "entity": "East",
      "entity_type": "player",
      "id": 169
    },
    {
      "type": "convert",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 170
    },
    {
      "type": "buy_shares",
      "entity": "East",
      "entity_type": "player",
      "id": 171,
      "shares": [
        "A&S_1"
      ],
      "percent": 20
    },
    {
      "type": "buy_shares",
      "entity": "East",
      "entity_type": "player",
      "id": 172,
      "shares": [
        "A&S_2"
      ],
      "percent": 20
    },
    {
      "type": "buy_shares",
      "entity": "East",
      "entity_type": "player",
      "id": 173,
      "shares": [
        "A&S_3"
      ],
      "percent": 20
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 174
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 175
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 176
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 177
    },
    {
      "type": "convert",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "buy_shares",
      "entity": "North",
      "entity_type": "player",
      "id": 179,
      "shares": [
        "PLE_1"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 180
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 181
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 182
    },
    {
      "type": "convert",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 183
    },
    {
      "type": "buy_shares",
      "entity": "South",
      "entity_type": "player",
      "id": 184,
      "shares": [
        "UR_1"
      ],
      "percent": 20
    },
    {
      "type": "buy_shares",
      "entity": "South",
      "entity_type": "player",
      "id": 185,
      "shares": [
        "UR_2"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 186
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 187
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 188
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 189,
      "target": "UR",
      "target_type": "corporation"
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 190
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 191
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 192
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 193
    },
    {
      "type": "buy_shares",
      "entity": "South",
      "entity_type": "player",
      "id": 194,
      "shares": [
        "PLE_2"
      ],
      "percent": 20
    },
    {
      "type": "undo",
      "entity": "South",
      "entity_type": "player",
      "id": 195
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 196,
      "corporation": "SR",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 197,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 198,
      "corporation": "SR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 199,
      "corporation": "SR",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 200,
      "corporation": "SR",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 201,
      "corporation": "SR",
      "price": 120
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 202,
      "corporation": "SR",
      "price": 125
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 203,
      "corporation": "SR",
      "price": 130
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 204,
      "corporation": "SR",
      "price": 135
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 205,
      "corporation": "SR",
      "price": 140
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 206,
      "corporation": "SR",
      "price": 145
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 207
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 208
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 209,
      "target": "TS",
      "target_type": "company"
    }
  ],
  "id": "hs_pnkzhnnt_1602609952",
  "players": [
    {
      "name": "North"
    },
    {
      "name": "East"
    },
    {
      "name": "South"
    }
  ],
  "title": "1817",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-13",
  "loaded": true,
  "result": {}
}

**Comment by roseundy** [comment]
Couldn't repro on latest code, fails on deployed, but only when reading JSON. If I load up to right before the error and then take the action it works. The action that fails is 197 - placing a token in F19 (tile 57-1-0).

**Comment by roseundy** [comment]
This was likely fixed by PR #1852
