### ISSUE TITLE
[1817] President is able to buy more than 60% of his company

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#1858]
In our game of 1817 the President was able to buy more than 60% of his company.

Game ID 12444

  {
      "type": "buy_shares",
      "entity": "Tillmann",
      "entity_type": "player",
      "id": 542,
      "shares": [
        "A&A_3"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "Tillmann",
      "entity_type": "player",
      "id": 543
    },

**Comment by tobymao** [comment]
dup #1850
