### ISSUE TITLE
[1817] Once a company has been sold short, President is unable to take any actions with that company

### ISSUE THREAD

**Issue by TIE53** [tobymao/18xx#1860]
Here, player 2 has short-sold a share of the Rutland Railroad. Player 3, the company president, is unable to take any actions involving this company (buying shares, selling shares, or taking any actions on behalf of the company).  Other players are still allowed to buy/sell shares in this company, though. I'm not exactly sure what has caused this bug, but it seems problematic (and common). 

https://gist.github.com/TIE53/044321ff79bca225c4c5b75af4b93389

**Comment by jenf** [comment]
Exception is "All shares must be owned by the same owner"
