### ISSUE TITLE
[1817] Tried to start a 5-share company from scratch, but wasn't able to buy the additional token

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#1861]
I tried to start a 5-share company from scratch, but wasn't able to buy the additional token for 50 $. Got an error message every time, followed by "game out of sync" message. Company was automatically sent to liquidation after our SR.

error message:
uninitialized constant Engine::Action::BuyTokens Did you mean? Engine::Token

Enhancement would be, to pay token fee automatically after the stock round, and took a loan, if necessary (like I'm used to from rr18xx)

game: 12444

https://www.18xx.games/game/12444

**Comment by jenf** [comment]
Must've forgotten an import

**Comment by jenf** [comment]
Dup #1853
