### ISSUE TITLE
[1817] - Select which variants to use when creating the game and show them in the game card

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#1868]
While there are clearly some variants that are more broadly used, you should be able to freely choose whatever combination of the 4 official variants when creating the game, and that combination should also be displayed on the game card when browsing the new games section, so that you can figure out which variants are in play in that specific game.

**Comment by tobymao** [comment]
i believe there's already any issue for variants so closing as a dup

**Comment by michaeljb** [comment]
#1082 is the one
