### ISSUE TITLE
[1846] Show list of privates in current game

### ISSUE THREAD

**Issue by ohgeetee** [tobymao/18xx#1869]
I think in 1846 and possibly other games, seeing the full list of privates, with privates removed greyed out would be a great QoL improvement.

For new players, having an understanding of what is available currently vs what has yet to be seen during the private draft is important information.

**Comment by waaayback** [comment]
I also think this would be a good feature.

**Comment by benjaminxscott** [comment]
Where would this live, under `Info` tab?

(When I play 46, this info seems mostly useful in initial draft and OR1)
