### ISSUE TITLE
Buying 2 privates at end of turn prompts to run trains again

### ISSUE THREAD

**Issue by cheesinglee** [tobymao/18xx#187]
This was observed in game ID 300. On TR's first operating turn, it bought 3 2Ts and 1 3T to trigger the phase transition. I tried buying my 2 private companies (South Iyo and Ferry) and after pressing pass, I was returned to the run trains state. I did an undo and bought only South Iyo and then the turn finished correctly after I hit pass. I didn't test with buying only the Ferry unfortunately.

**Comment by cheesinglee** [comment]
I tried buying the Ferry in a later OR and encountered this issue again, so it is definitely and issue with the Ferry private. To provide further information, I had already laid the port tile before buying the in private in both cases.

**Comment by tobymao** [comment]
is the game still in this state?

**Comment by tojaelemele** [comment]
Same in game ID 140. Player kaminski.2710 in his first OR was operating SR (with 650 in the treasury). He bought 4T for 300, then he bought 2 private companies for remaining 350.
Then system forced him to once again lay the track etc.
If he would sold only one company, then everything works good.

**Comment by cheesinglee** [comment]
No, I worked around by undoing back when I really ran trains, and bought it in then.

**Comment by tobymao** [comment]
it would help in these situations if you cloned the game and then sent me the json so i can recreate it

**Comment by tojaelemele** [comment]
> it would help in these situations if you cloned the game and then sent me the json so i can recreate it

In which state game should be? Before passing after selling privates, or when it forced to lay tracks once again?

**Comment by cheesinglee** [comment]
> it would help in these situations if you cloned the game and then sent me the json so i can recreate it

OK, I will do that if further issues arise

**Comment by tobymao** [comment]
doesn't matter too much as long as i can recreate the situation easily, i'm attempting this now

**Comment by tobymao** [comment]
hm i can't recreate it

**Comment by tojaelemele** [comment]
> hm i can't recreate it

maybe because I'm clicking on it right now? :)

**Comment by tobymao** [comment]
nope, i'm doing it locally on my own machine in hot seat mode

**Comment by tojaelemele** [comment]
> hm i can't recreate it

so there is no chance to continue as player wants?

**Comment by tobymao** [comment]
if you can paste me the json, i can fix this issue

**Comment by tojaelemele** [comment]
> if you can paste me the json, i can fix this issue

just tell me how :) and where should I send it?

**Comment by tobymao** [comment]
recreate the game state with hot seat mode go to tools, the data is there. paste it in here. thank you!

**Comment by tojaelemele** [comment]
`{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 1,
      "company": "Sumitomo Mines Railway",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 2,
      "company": "Mitsubishi Ferry",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 3,
      "company": "Ehime Railway",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "piton",
      "entity_type": "player",
      "id": 4,
      "company": "Sumitomo Mines Railway",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 5,
      "company": "Ehime Railway",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 6,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 7,
      "company": "Ehime Railway",
      "price": 55
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 9,
      "company": "Sumitomo Mines Railway",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "bid",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 11,
      "company": "Dougo Railway",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "piton",
      "entity_type": "player",
      "id": 12,
      "company": "South Iyo Railway",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 13,
      "company": "Uno-Takamatsu Ferry",
      "price": 150
    },
    {
      "type": "message",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 14,
      "message": "o"
    },
    {
      "type": "par",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 15,
      "corporation": "TR",
      "share_price": "70,4,3"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "par",
      "entity": "piton",
      "entity_type": "player",
      "id": 17,
      "corporation": "IR",
      "share_price": "65,5,3"
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 18,
      "share": "IR_1"
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 19,
      "share": "TR_1"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 21,
      "share": "IR_2"
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 22,
      "share": "IR_3"
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 23,
      "share": "TR_2"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 25,
      "share": "IR_4"
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 26,
      "share": "TR_3"
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 27,
      "share": "IR_5"
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 28,
      "share": "IR_6"
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 29,
      "share": "IR_7"
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 30,
      "share": "IR_8"
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 31,
      "share": "TR_4"
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 32,
      "hex": "G10",
      "tile": "437-0",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 33,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 35
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 36,
      "hex": "E2",
      "tile": "5-0",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 38,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 39
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 41,
      "share": "TR_5"
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 43
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "sell_shares",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 46,
      "shares": [
        "IR_1",
        "IR_3"
      ],
      "percent": 20
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 47,
      "share": "TR_6"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 49
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 50
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 52,
      "hex": "G12",
      "tile": "57-0",
      "rotation": 3
    },
    {
      "type": "place_token",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 53,
      "city": "57-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 54,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G10"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "G12",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 55,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 56
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 57,
      "hex": "F3",
      "tile": "5-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 59,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "F1",
            "E2"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "E2",
            "F3"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 60,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 62,
      "share": "TR_7"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "sell_shares",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 64,
      "shares": [
        "IR_5",
        "IR_7",
        "IR_8"
      ],
      "percent": 30
    },
    {
      "type": "sell_shares",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 65,
      "shares": [
        "TR_4"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 66,
      "corporation": "UR",
      "share_price": "75,3,3"
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 67,
      "share": "IR_1"
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 68
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 69,
      "share": "TR_4"
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 70
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 72,
      "share": "UR_1"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 75,
      "share": "TR_8"
    },
    {
      "type": "sell_shares",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 76,
      "shares": [
        "TR_5",
        "TR_6",
        "TR_4",
        "TR_8"
      ],
      "percent": 40
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 77
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 78,
      "share": "UR_2"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "par",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 81,
      "corporation": "SR",
      "share_price": "65,5,3"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 83,
      "share": "UR_3"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 85
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 86,
      "share": "SR_1"
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 90
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 91,
      "share": "IR_3"
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 97,
      "hex": "B5",
      "tile": "9-0",
      "rotation": 3
    },
    {
      "type": "place_token",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 98,
      "city": "C4-0-0",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 99,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 100,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 101,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 102
    },
    {
      "type": "buy_company",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 103,
      "company": "Ehime Railway",
      "price": 80
    },
    {
      "type": "lay_tile",
      "entity": "Ehime Railway",
      "entity_type": "company",
      "id": 104,
      "hex": "C4",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "buy_company",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 105,
      "company": "Dougo Railway",
      "price": 120
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 107,
      "hex": "F3",
      "tile": "205-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 108,
      "city": "205-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 109,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "F1",
            "E2"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "F1",
            "F3"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 110,
      "kind": "payout"
    },
    {
      "type": "buy_company",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 111,
      "company": "South Iyo Railway",
      "price": 160
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 112,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 114
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 115,
      "hex": "G8",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 116,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G10"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "G12",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 117,
      "kind": "payout"
    },
    {
      "type": "buy_company",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 118,
      "company": "Takamatsu E-Railroad",
      "price": 40
    },
    {
      "type": "buy_company",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 119,
      "company": "Mitsubishi Ferry",
      "price": 60
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 120,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 121,
      "train": "3-3",
      "price": 180
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 122,
      "share": "UR_4"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 123
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 124,
      "share": "TR_5"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 125
    },
    {
      "type": "sell_shares",
      "entity": "piton",
      "entity_type": "player",
      "id": 126,
      "shares": [
        "IR_2",
        "IR_4"
      ],
      "percent": 20
    },
    {
      "type": "par",
      "entity": "piton",
      "entity_type": "player",
      "id": 127,
      "corporation": "KO",
      "share_price": "80,2,3"
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 128,
      "share": "SR_2"
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 129
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 130,
      "share": "IR_5"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 131
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 132,
      "share": "IR_7"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 133
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 134,
      "share": "KO_1"
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 135
    },
    {
      "type": "sell_shares",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 136,
      "shares": [
        "IR_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_share",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 137,
      "share": "SR_3"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 138
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 139,
      "share": "UR_5"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 140
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 141,
      "share": "KO_2"
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 142
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 143
    },
    {
      "type": "buy_share",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 144,
      "share": "KO_3"
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 145
    },
    {
      "type": "buy_share",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 146,
      "share": "TR_6"
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 147
    },
    {
      "type": "buy_share",
      "entity": "piton",
      "entity_type": "player",
      "id": 148,
      "share": "UR_6"
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "kaminski.2710",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "pass",
      "entity": "Elemele",
      "entity_type": "player",
      "id": 151
    },
    {
      "type": "pass",
      "entity": "Adam Badura",
      "entity_type": "player",
      "id": 152
    },
    {
      "type": "pass",
      "entity": "piton",
      "entity_type": "player",
      "id": 153
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 154,
      "hex": "J3",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 155,
      "train": "3-4",
      "price": 180
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 156,
      "train": "4-0",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 157
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 158
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 159,
      "hex": "C8",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 160,
      "routes": [
        {
          "train": "3-0",
          "hexes": [
            "B7",
            "B5",
            "B3",
            "C4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 161,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 162
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 163
    },
    {
      "type": "lay_tile",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 164,
      "hex": "I2",
      "tile": "6-0",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 165,
      "train": "4-1",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 166
    },
    {
      "type": "buy_company",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 167,
      "company": "Sumitomo Mines Railway",
      "price": 50
    },
    {
      "type": "buy_company",
      "entity": "SR",
      "entity_type": "corporation",
      "id": 168,
      "company": "Uno-Takamatsu Ferry",
      "price": 300
    }
  ],
  "id": "hs_1588033796",
  "description": "Cloned from game 140",
  "user": {
    "id": 0,
    "name": "You"
  },
  "players": [
    {
      "id": 201,
      "name": "kaminski.2710"
    },
    {
      "id": 208,
      "name": "Elemele"
    },
    {
      "id": 206,
      "name": "Adam Badura"
    },
    {
      "id": 217,
      "name": "piton"
    }
  ],
  "max_players": 4,
  "title": "1889",
  "settings": {
    "seed": 2.9199838394971408e+38
  },
  "turn": 4,
  "round": "Operating Round",
  "acting": [
    201
  ],
  "result": {},
  "created_at": "2020-04-28",
  "updated_at": "2020-04-27",
  "mode": "hotseat"
}`

**Comment by tobymao** [comment]
thank you, will fix this after i put the kids to bed

**Comment by tojaelemele** [comment]
no problem, it's 2.40 CEST in Poland now, so I need to go to sleep too ;)
