### ISSUE TITLE
Desktop notifications via the Notification API

### ISSUE THREAD

**Issue by pablonen** [tobymao/18xx#1870]
I have the game tab open amongst a bunch of other tabs, and I rarely peek at it to see if it is my turn. In order to play quicker I'd like to add support to desktop notifications via the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification), so that whenever it is my turn I would get a desktop notification about my turn.

**Comment by tobymao** [comment]
dup

**Comment by dfannius** [comment]
The duplicate issue seems to be #956.

**Comment by pablonen** [comment]
Sorry, I tried searching the tracker, but couldn't find it. The duplicate seems to be #386 , I'll take a look there and see if there is anything I can do.
