### ISSUE TITLE
[1817] 2+ trains don't seem to rust after being used once (after 2s rust)

### ISSUE THREAD

**Issue by ggohierroy** [tobymao/18xx#1871]
Game:
https://18xx.games/hotseat/hs_tazjuqsy_1602556628

Data:
https://gist.github.com/ggohierroy/4bbd2172283d6c99922c0d2a57e7747a

I'm currently in a phase 5 and the 2+ trains are still running

**Comment by jenf** [comment]
Completely missed that rule.
