### ISSUE TITLE
18TN - Civil War did not impact triggering company

### ISSUE THREAD

**Issue by TBarchet** [tobymao/18xx#1873]
A company (GMO) with no train bought the 3' train as it's first.  It had a valid route (and train, via the purchase) when the Civil War was triggered, but it was able to run for revenue in the next OR.

Civil War Trigger captured here:
https://www.18xx.games/game/11452?action=185

**Comment by ryandriskel** [comment]
Confirmed issue. Review of the game log shows GMO did not have the Civil War ability applied.
