### ISSUE TITLE
[1817]  Merge then convert in same M&A round allowed.

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#1876]
Section 7.1 of the rules says that a company should not be allowed to merge or convert more than once in the same M&A round.  In this game, companies are allowed to do just that.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 1,
      "company": "MAJM",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 2
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 4
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 5,
      "company": "MAJC",
      "price": 70
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 6
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 7
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 9,
      "company": "MAIL",
      "price": 70
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "bid",
      "entity": "West",
      "entity_type": "player",
      "id": 13,
      "company": "UBC",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 17,
      "company": "PSM",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 21,
      "company": "OBC",
      "price": 20
    },
    {
      "type": "undo",
      "entity": "South",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 23,
      "company": "CM",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 27,
      "company": "MINM",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 29
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "bid",
      "entity": "West",
      "entity_type": "player",
      "id": 31,
      "company": "TS",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 33
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 36,
      "company": "OBC",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 40,
      "company": "ME",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 43
    },
    {
      "type": "bid",
      "entity": "West",
      "entity_type": "player",
      "id": 44,
      "company": "MINC",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 47
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 48,
      "corporation": "PLE",
      "price": 140
    },
    {
      "type": "place_token",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 49,
      "city": "F13-5-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 50
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "assign",
      "entity": "North",
      "entity_type": "player",
      "id": 53,
      "target": "PSM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 54,
      "corporation": "A&S",
      "price": 200
    },
    {
      "type": "place_token",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 55,
      "city": "I12-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 57
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 58
    },
    {
      "type": "assign",
      "entity": "East",
      "entity_type": "player",
      "id": 59,
      "target": "MAJC",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "East",
      "entity_type": "player",
      "id": 60,
      "target": "OBC",
      "target_type": "company"
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 62,
      "corporation": "B&A",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 63,
      "city": "C26-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 64
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 65
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 66,
      "target": "ME",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 67,
      "target": "MAIL",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "West",
      "entity_type": "player",
      "id": 68,
      "corporation": "UR",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 69,
      "city": "G6-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 70
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "assign",
      "entity": "West",
      "entity_type": "player",
      "id": 72,
      "target": "UBC",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "West",
      "entity_type": "player",
      "id": 73,
      "target": "TS",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "North",
      "entity_type": "player",
      "id": 74,
      "corporation": "PSNR",
      "price": 210
    },
    {
      "type": "place_token",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 75,
      "city": "F19-6-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "redo",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "assign",
      "entity": "North",
      "entity_type": "player",
      "id": 78,
      "target": "MAJM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "East",
      "entity_type": "player",
      "id": 79,
      "corporation": "WT",
      "price": 160
    },
    {
      "type": "place_token",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 80,
      "city": "H9-2-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "assign",
      "entity": "East",
      "entity_type": "player",
      "id": 83,
      "target": "CM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "South",
      "entity_type": "player",
      "id": 84,
      "corporation": "DL&W",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 85,
      "city": "C22-3-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "assign",
      "entity": "South",
      "entity_type": "player",
      "id": 87,
      "target": "MINM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "West",
      "entity_type": "player",
      "id": 88,
      "corporation": "H",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "H",
      "entity_type": "corporation",
      "id": 89,
      "city": "F3-4-0",
      "slot": 0
    },
    {
      "type": "assign",
      "entity": "West",
      "entity_type": "player",
      "id": 90,
      "target": "MINC",
      "target_type": "company"
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 91
    },
    {
      "type": "pass",
      "entity": "East",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "pass",
      "entity": "West",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "lay_tile",
      "entity": "MAJC",
      "entity_type": "company",
      "id": 95,
      "hex": "H11",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 96,
      "hex": "I12",
      "tile": "5-0",
      "rotation": 2
    },
    {
      "type": "take_loan",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 97,
      "loan": 0
    },
    {
      "type": "buy_train",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 98,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "lay_tile",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 101,
      "hex": "F19",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 102,
      "hex": "F17",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "take_loan",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 103,
      "loan": 1
    },
    {
      "type": "buy_train",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 104,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "lay_tile",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 107,
      "hex": "B27",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 108
    },
    {
      "type": "take_loan",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 109,
      "loan": 2
    },
    {
      "type": "buy_train",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 110,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 111
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 112
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 113,
      "hex": "G6",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "assign",
      "entity": "UBC",
      "entity_type": "company",
      "id": 114,
      "target": "G6",
      "target_type": "hex"
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 115,
      "hex": "F5",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "take_loan",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 116,
      "loan": 3
    },
    {
      "type": "take_loan",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 117,
      "loan": 4
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 118,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 119
    },
    {
      "type": "lay_tile",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 120,
      "hex": "C22",
      "tile": "5-1",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 121,
      "hex": "D23",
      "tile": "8-2",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 122,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 123
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 124
    },
    {
      "type": "lay_tile",
      "entity": "H",
      "entity_type": "corporation",
      "id": 125,
      "hex": "F3",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "H",
      "entity_type": "corporation",
      "id": 126,
      "hex": "E2",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "H",
      "entity_type": "corporation",
      "id": 127,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "take_loan",
      "entity": "H",
      "entity_type": "corporation",
      "id": 128,
      "loan": 5
    },
    {
      "type": "buy_train",
      "entity": "H",
      "entity_type": "corporation",
      "id": 129,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "H",
      "entity_type": "corporation",
      "id": 130
    },
    {
      "type": "pass",
      "entity": "H",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "lay_tile",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 132,
      "hex": "H9",
      "tile": "6-2",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 133,
      "hex": "I8",
      "tile": "9-3",
      "rotation": 0
    },
    {
      "type": "undo",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 134
    },
    {
      "type": "lay_tile",
      "entity": "CM",
      "entity_type": "company",
      "id": 135,
      "hex": "I8",
      "tile": "9-3",
      "rotation": 0
    },
    {
      "type": "take_loan",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 136,
      "loan": 6
    },
    {
      "type": "buy_train",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 137,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 138
    },
    {
      "type": "pass",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 139
    },
    {
      "type": "lay_tile",
      "entity": "PSM",
      "entity_type": "company",
      "id": 140,
      "hex": "F13",
      "tile": "X00-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 141,
      "hex": "E12",
      "tile": "8-3",
      "rotation": 5
    },
    {
      "type": "take_loan",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 142,
      "loan": 7
    },
    {
      "type": "buy_train",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 143,
      "train": "2-8",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 144
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 145
    },
    {
      "type": "merge",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 146,
      "corporation": "WT"
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 147
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 148
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "H",
      "entity_type": "corporation",
      "id": 150
    },
    {
      "type": "merge",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 151,
      "corporation": "H"
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 152
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 153
    },
    {
      "type": "pass",
      "entity": "South",
      "entity_type": "player",
      "id": 154
    },
    {
      "type": "pass",
      "entity": "North",
      "entity_type": "player",
      "id": 155
    },
    {
      "type": "lay_tile",
      "entity": "MAJC",
      "entity_type": "company",
      "id": 156,
      "hex": "H13",
      "tile": "8-4",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MAJC",
      "entity_type": "company",
      "id": 157,
      "hex": "H15",
      "tile": "8-5",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 158,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H9",
              "H11",
              "I12"
            ]
          ]
        },
        {
          "train": "2-7",
          "connections": [
            [
              "J7",
              "I8",
              "H9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 159,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 160
    },
    {
      "type": "payoff_loan",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 161,
      "loan": 0
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 162
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 163,
      "hex": "H5",
      "tile": "8-6",
      "rotation": 1
    },
    {
      "type": "assign",
      "entity": "UBC",
      "entity_type": "company",
      "id": 164,
      "target": "H3",
      "target_type": "hex"
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 165,
      "hex": "H3",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 166
    },
    {
      "type": "run_routes",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 167,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "D1",
              "E2",
              "F3"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "F3",
              "F5",
              "G6"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "H3",
              "H5",
              "G6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 168,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 169
    },
    {
      "type": "payoff_loan",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 170,
      "loan": 3
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 172,
      "hex": "F21",
      "tile": "8-7",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 173
    },
    {
      "type": "run_routes",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 174,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "F19",
              "F21",
              "E22"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 175,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 176
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 177
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "run_routes",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 179,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "E22",
              "D23",
              "C22"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 180,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 181
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 182
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 183
    },
    {
      "type": "run_routes",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 184,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "C26",
              "B27",
              "A28"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 185,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 186
    },
    {
      "type": "pass",
      "entity": "B&A",
      "entity_type": "corporation",
      "id": 187
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 188,
      "hex": "F15",
      "tile": "9-4",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 189,
      "hex": "E10",
      "tile": "8-8",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 190,
      "routes": [
        {
          "train": "2-8",
          "connections": [
            [
              "D9",
              "E10",
              "E12",
              "F13"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 191,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 192
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 193
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 194
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 195
    },
    {
      "type": "pass",
      "entity": "PSNR",
      "entity_type": "corporation",
      "id": 196
    },
    {
      "type": "merge",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 197,
      "corporation": "B&A"
    },
    {
      "type": "merge",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 198,
      "corporation": "PSNR"
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 199
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 200
    },
    {
      "type": "convert",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 201
    },
    {
      "type": "undo",
      "entity": "South",
      "entity_type": "player",
      "id": 202
    },
    {
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 203
    },
    {
      "type": "undo",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 204
    },
    {
      "type": "undo",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 205
    },
    {
      "type": "convert",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 206
    },
    {
      "type": "undo",
      "entity": "North",
      "entity_type": "player",
      "id": 207
    },
    {
      "type": "merge",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 208,
      "corporation": "PSNR"
    },
    {
      "type": "pass",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 209
    },
    {
      "type": "pass",
      "entity": "DL&W",
      "entity_type": "corporation",
      "id": 210
    }
  ],
  "id": "hs_uqemgyzg_1602715949",
  "players": [
    {
      "name": "North"
    },
    {
      "name": "East"
    },
    {
      "name": "South"
    },
    {
      "name": "West"
    }
  ],
  "title": "1817",
  "description": "",
  "max_players": "4",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-14",
  "loaded": true,
  "result": {}
}

**Comment by jenf** [comment]
Bug is more problematic, it skips companies
