### ISSUE TITLE
[1817]  Mail Contract(s) not paying.

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#1881]
This might be a duplicate, since it seems like something someone would have noticed by now, but the mail contract(s) don't seem to be paying the companies.

**Comment by mtsay** [comment]
I'm seeing this issue as well, and I'm supplying some data so whoever working on this can hopefully track it down.

I've created a hot seat game with 3 players each starting a company with a mail contract. I took a screenshot of company spreadsheet at the end of SR2 and at the start of OR2.1; note that the company cash has not changed despite these companies having trains and mail contracts.

- This is a copy of game data from that game.
[game_data.txt](https://github.com/tobymao/18xx/files/5388980/game_data.txt)

- This is the text log from the same game.
[game_log.txt](https://github.com/tobymao/18xx/files/5388981/game_log.txt)

- Screenshot of company spreadsheet at the end of SR 2.
<img width="1392" alt="SR2" src="https://user-images.githubusercontent.com/72957217/96209060-a74c4e80-0f23-11eb-91d2-4db979297c74.png">

- Screenshot of company spreadsheet at the start of OR 2.1 when PLE operates.
- Note that this looks identical to the previous screenshot. Sorry that I'm unable to prove that this is taken at the start of OR 2.1; you will just have to take my words for it.
<img width="1392" alt="OR2 1" src="https://user-images.githubusercontent.com/72957217/96209058-a4515e00-0f23-11eb-932d-5fdd8b074ab0.png">

**Comment by SmithInMN** [comment]
It appears neither in the game log nor do I see a change in the company treasury, so that's got me convinced!

Strangely enough, it looks like it shows income to be $0 while the company has no train, so that appears to be working correctly.
