### ISSUE TITLE
[1882] Buying shares from company in brown area in SR

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#1885]
Game: 12685

Player was able to buy several shares from market (that's correct) and an additional share from IPO (should be either from market or from IPO, I think)

 {
      "type": "buy_shares",
      "entity": "Tillmann",
      "entity_type": "player",
      "id": 171,
      "shares": [
        "QLL_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Tillmann",
      "entity_type": "player",
      "id": 172,
      "shares": [
        "QLL_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Tillmann",
      "entity_type": "player",
      "id": 173,
      "shares": [
        "QLL_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Tillmann",
      "entity_type": "player",
      "id": 174,
      "shares": [
        "QLL_8"
      ],
      "percent": 10
    },

**Comment by tobymao** [comment]
it's in brown
