### ISSUE TITLE
[18LA] lists titles of SRs and ORs wrong

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#1893]
https://www.18xx.games/game/12602

In this game, the first SR was listed as **Stock Round**, and the 2 subsequent ORs were called **Operating Round 1 (of 2)** and **Operating Round 2 (of 2)**. The subsequent stock round was called *Stock Round 1**, followed by **Operating Round 1.1 (of 2)** and **Operating Round 1.2 (of 2)** and then **Stock Round 2** etc.

It really helps us having a sample game to reproduce the issue.

It seems that they're all off by one round.

**Comment by michaeljb** [comment]
Interesting...the bug causing this is also breaking operating order for the first 2 OR sets in 2-player 18 Los Angeles games.
