### ISSUE TITLE
Suggestion : Priority deal

### ISSUE THREAD

**Issue by McDood** [tobymao/18xx#19]
Add a visual cue to show which player has priority deal for next Stock round.
Add an event in the log  at the end of the stock round to say "priority deal awarded to player X"

**Comment by dfannius** [comment]
I agree that it would be nice to call it out on the player card, but for the moment, note that during an operating round, the players are always displayed in the order that they will act in the next stock round, so the leftmost player displayed has priority deal.

**Comment by Talbatross** [comment]
I'll take a look.

**Comment by Talbatross** [comment]
I put up a PR that adds the player order to the player cards.  It's interesting because it points out that the ordering is always in order on mobile, so it feels a bit redundant.  On computer, since the ordering is 2D (left-> right, top-> bottom) it feels better there as it clarifies that ordering.
