### ISSUE TITLE
When you enter a game, an indication of what the current move is

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#190]
I've had it happen multiple times where I know it's my turn, but it's unclear what I need to be doing. Specifically, during the auction, I went, and it turned out that someone had bought a private, there were some cascading buys, and then it was time to bid with another player. Since I'm fairly experienced at 18xx I was able to figure that out quickly, but I still feel like when you join the game it should call out what is actually currently happening

**Comment by dfannius** [comment]
This particular scenario will be clearer as of fa86e54, but there is still room for more narration in general in the log.

**Comment by dfannius** [comment]
I think we're a lot better about making the current state of the game clear than a week ago when this issue was filed. At this point if there are still improvements to be made it might be best to create specific issues for them.

**Comment by dfannius** [comment]
@jcoveney I'm going to close this now unless there are some specific scenarios that you think haven't been addressed; otherwise we can act on individual ones as they come up.
