### ISSUE TITLE
18Ches tokens not showing up on older ipad

### ISSUE THREAD

**Issue by Schwazzy** [tobymao/18xx#1900]
See attached image.  It's an older ipad.  18Ches, game [#12702]
![IMG_0039](https://user-images.githubusercontent.com/73030787/96346791-b3432800-106b-11eb-96a4-4330ecd592d9.jpg)

**Comment by tobymao** [comment]
this is an issue with your ipad not being able to process svgs

**Comment by Schwazzy** [comment]
Thanks, I told him not to be such a luddite and get some tech from within
the last decade.  :)
