### ISSUE TITLE
[18Mex][1846][18LA][1817][Others?] Spreadsheet and Entities tab don't show closed / merged companies

### ISSUE THREAD

**Issue by CaptainObi** [tobymao/18xx#1913]
The spreadsheet tab and entities tab doesn't show closed/merged companies. If a company operated for a few ORs and then closed in 1846 it would not show that company in the SS.

**Comment by jenf** [comment]
Would also suggest that non-IPOed companies shouldn't show up on spreadsheet especially with 1817 due to the verbosity.
