### ISSUE TITLE
[18MEX] Show UdeY and NdM treasuries before they've floated

### ISSUE THREAD

**Issue by TIE53** [tobymao/18xx#1916]
When Minors A-C close, they give their treasuries to the NdM and UdeY. This information should be shown on the charters starting once the minors close, not only when the majors float.  It's helpful to know how much money these companies will have before players start buying shares in them.

**Comment by perwestling** [comment]
@TIE53 My suggestion is to change presentation so that it looks like this:

![image](https://user-images.githubusercontent.com/2631151/96377833-95b7b080-1188-11eb-9d99-e41702787568.png)
