### ISSUE TITLE
There should be a log of game deletion

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#192]
I think the ideal would be an email if a game you're in is deleted (ideally with an optional reason why). I've noticed a bunch of games have disappeared and I assume it's because they've been deleted, but it's weird to not know

a centralized log of game state changes (creation, deletion, etc) would also be very helpful!

**Comment by tobymao** [comment]
i think perhaps just an email would suffice, i want to actually delete the data so that the user can control their data

**Comment by jcoveney** [comment]
Yeah that seems reasonable. I've just had a number of games disappear and don't know why, just want a place to surface that :)

**Comment by jenf** [comment]
dup of #615
