### ISSUE TITLE
[18MEX] Two copper canyon notes

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#1923]
It would be helpful to mark the CC hex on the main map. I believe it is marked on the board IRL.

And this is very minor, but “canyon” is spelled “canyan” in the private description.

**Comment by perwestling** [comment]
Spell error will be fixed.

The helpful mark I am not sure how to make it work. Putting CC label on the hex might be a possible solution but it might be confusing for other reasons.

**Comment by perwestling** [comment]
@SmithInMN It was suggested to add a mining icon (like in 18AL) on the hex, and so I have done. I think it might be a good enough solution. When the platform support putting a name on the hex we might revisit this.

**Comment by SmithInMN** [comment]
I think that icon should be plenty. Just something to remind players which hex so they either build or don’t build there as their strategy dictates!

And I know it says in the private which hex, but it’s an easy thing to forget, especially if new to the title.
