### ISSUE TITLE
1846 - full payout option incorrectly stated that the token will not move. After actual payout, the share price moves accordingly. 

### ISSUE THREAD

**Issue by shamusj** [tobymao/18xx#1928]
Game Id 11905
Operating around 6.1

NYC paid out correctly, but when given the option of whether to full pay / half pay / retain the token movement shows incorrectly. The actual token movement after choosing the option seemed correct though.

**Comment by slapphappyjazz** [comment]
I also observed this.  A double jump was shown as "0 right" and a triple jump as "1 right". 
<img width="177" alt="Screenshot 2020-10-18 182223" src="https://user-images.githubusercontent.com/36824573/96414736-6be0a700-11e5-11eb-9bdf-31d4d15c89ae.png">

**Comment by jenf** [comment]
fixed
