### ISSUE TITLE
Spreadsheet view

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#193]
This has come up in slack. I'm actually planning to give it a try (despite my non-existent front-end skills), and figure there should be an issue to track the feature (slack is fairly ephemeral).

**Comment by gchambers419** [comment]
Agree about tracking the feature request here vs the "chat room"
I suggest logging design intent as well, so everyone knows what's coming.
My theory was that there would be a player listing as one axis, with columns for name, privates owned, money and net worth, then a set of columns, one per corporation, with names/symbols across the top, and rows at the bottom for cash on hand, trains owned, and privates owned.
As always the "working rule" applies: The person doing the work makes the rules.

**Comment by jcoveney** [comment]
Yes, that was more or less my intent. If you want to give it a stab, feel free of course, though I will probably try at some point soon. I've already spent a bit of time with the code and toby graciously provided a lot of guidance. My original thought was to have a switch which turned on a spreadsheet view in the main tab, but for now I'm actually thinking of adding a spreadsheet tab. The reason is the view code right now is quite clean in how it renders everything...adding a switch based on that setting that then renders things in one of two ways is kind of messy. If it is in its own tab, then it can be completely separate and I think will be less ugly as a maintenance burden. Plus it's easier to implement initially and we can see how it looks. If we want, we can integrate it with the summary easily.

Something I would like as a nice to have would be for the spreadsheet to expend out and have the companies' income during each OR. But I'm not sure if that information is currently available in the client.

**Comment by gchambers419** [comment]
Given my lack in the following areas, you are much more likely to get to it than I:
1. Ruby programming.  It's just another language, but it **is** a new language
1. Anything beyond the most rudimentary knowledge of CSS or modern web coding in general
1. Time
1. Attention span

I prefer a separate tab as well.

**Comment by dfannius** [comment]
One more vote for a separate tab.

**Comment by jcoveney** [comment]
Initial PR is up. Feel free to discuss specifics there. Would love for anyone good at CSS to help out...
