### ISSUE TITLE
[1817] Game crashes during a stock round while shorting shares

### ISSUE THREAD

**Issue by mrpoodlepants** [tobymao/18xx#1935]
**Please provide**
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/mrpoodlepants/d1b5d6a9bd54c03d06de2e7609587222

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
I believe the game crashed when trying to short a share, but it may have been when trying to undo the action.

**Comment by jenf** [comment]
Looks very similar to #1872, resolving as dup
