### ISSUE TITLE
18MEX tile laying step should be skipped if no money and only tile has cost

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1944]
This might be a more global request. In 1846, tile laying is skipped if the corporation has no money. It would be nice if the same thing happened in 18MEX when the only tile a corporation can lay has a cost the corporation cannot afford. An easy example of this is the Minor Corporations in the first operating round.

**Comment by tobymao** [comment]
i'd classify it as a bug

**Comment by perwestling** [comment]
And I would classify it as enhancement ;-)

In general this can be tough as the game has to check all possible tile lays for the corporation, and these can be quite a few. 

Now a question is if implementing this should we take the next step? For 18MEX the first orders of minors A, B, C are automatic (no track as not enough money to lay yellow in start hex, automatic choice of run [20+10], done) for first OR, and I suppose for second OR as well (same as first). So should we use auto pilot for minors during two first ORs?

That said, it would be possible to add a check in general code for a special case:*

- If it is the first OR for the corporation
- and the home hex for the corporation is "white"
- and the home hex has terrain cost
- and corporation has less money than terrain cost
THEN skip lay track.

Making it more advanced than that I think would be hard.

-

**Comment by tobymao** [comment]
sorry, thinking about it again, you're right

**Comment by perwestling** [comment]
Plan now is to do this for 18MEX, and as described above. Will probably only affect minors.
This will break all alphas so we will try to do this just before going to beta.
