### ISSUE TITLE
18MEX unable to upgrade city that does not change value

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1945]
The code gives an error "Must use new track or change city value." This is incorrect. The rules say "Each tile laid must contain either some newly added track that is connected to an existing station of the company, or a city which is connected to an existing station of the company." There is no requirement to increase the value of said city.

In the JSON below. UdY is unable to place a city in the Minor C home hex.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "MCAR",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "KCMO",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "A",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "B",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "C",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "MIR",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "company": "MNR",
      "price": 140
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "corporation": "NdM",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "corporation": "CHI",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "CHI_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "CHI_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "CHI_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "CHI_5"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "redo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21,
      "corporation": "MC",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22,
      "corporation": "CHI",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23,
      "corporation": "MEX",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24,
      "shares": [
        "MC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 25,
      "shares": [
        "CHI_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "MEX_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "MC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "CHI_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "MEX_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "MC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "CHI_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "MEX_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "MC_4"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 34,
      "corporation": "TM",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "MEX_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "TM_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 39,
      "shares": [
        "TM_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 43
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 44,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "minor",
      "id": 45
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 46,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "C",
      "entity_type": "minor",
      "id": 47
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 48,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 49,
      "hex": "I8",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 50,
      "hex": "K8",
      "tile": "58-0",
      "rotation": 3
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 51,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 52,
      "hex": "G6",
      "tile": "8-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 53,
      "hex": "H7",
      "tile": "9-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 54,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 55
    },
    {
      "type": "lay_tile",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 56,
      "hex": "P13",
      "tile": "473-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 57,
      "hex": "Q12",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 58,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 59
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 60,
      "shares": [
        "TM_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 62,
      "shares": [
        "TM_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 64,
      "shares": [
        "TM_5"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 65,
      "shares": [
        "TM_1",
        "TM_2",
        "TM_5"
      ],
      "percent": 30
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 66
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 67,
      "shares": [
        "CHI_1",
        "CHI_2",
        "CHI_3",
        "CHI_4"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 68,
      "corporation": "PAC",
      "share_price": "60,2,2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 69,
      "shares": [
        "MEX_1",
        "MEX_2",
        "MEX_3",
        "MEX_4"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 70,
      "corporation": "SPM",
      "share_price": "60,2,2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 71,
      "shares": [
        "MC_1",
        "MC_2",
        "MC_3",
        "MC_4"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 72,
      "corporation": "UdY",
      "share_price": "60,2,2"
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 74,
      "corporation": "UdY",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 75,
      "shares": [
        "SPM_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 77,
      "shares": [
        "SPM_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 78
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 79,
      "shares": [
        "SPM_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 81,
      "shares": [
        "SPM_4"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 83,
      "shares": [
        "PAC_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 85,
      "shares": [
        "PAC_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 87,
      "shares": [
        "PAC_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 89,
      "shares": [
        "PAC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 90,
      "shares": [
        "UdY_1"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 91,
      "shares": [
        "SPM_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 92,
      "shares": [
        "UdY_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 93,
      "shares": [
        "UdY_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 97
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 98
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 99,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "minor",
      "id": 100
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 101,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "C",
      "entity_type": "minor",
      "id": 102
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 103,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    }
  ],
  "id": "hs_rdiijwhx_1603149128",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18MEX",
  "description": "test",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-19",
  "loaded": true,
  "result": {}
}

**Comment by roseundy** [comment]
But the city is tokened and you cannot trace a route to the new track.

**Comment by ChrisTheCat** [comment]
The rules clearly say you only need to meet one of two conditions.

EITHER reach new track

OR lay a city tile

**Comment by roseundy** [comment]
My bad. I didn't realize that 18MEX has permissive tile lays if the tile has a city on it. Interesting. There is no support for this in the code for this at all.
