### ISSUE TITLE
18MEX unable to upgrade Mexico City

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1947]
UdY gets an error "Must use new track or increase value of city" when trying to upgrade Mexico City to brown.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "MCAR",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "KCMO",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "A",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "B",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "C",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "MIR",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "company": "MNR",
      "price": 140
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "corporation": "NdM",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "corporation": "CHI",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "CHI_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "CHI_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "CHI_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "CHI_5"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "redo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21,
      "corporation": "MC",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22,
      "corporation": "CHI",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23,
      "corporation": "MEX",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24,
      "shares": [
        "MC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 25,
      "shares": [
        "CHI_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "MEX_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "MC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "CHI_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "MEX_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "MC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "CHI_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "MEX_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "MC_4"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 34,
      "corporation": "TM",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "MEX_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "TM_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 39,
      "shares": [
        "TM_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 43
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 44,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "minor",
      "id": 45
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 46,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "C",
      "entity_type": "minor",
      "id": 47
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 48,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 49,
      "hex": "I8",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 50,
      "hex": "K8",
      "tile": "58-0",
      "rotation": 3
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 51,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 52,
      "hex": "G6",
      "tile": "8-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 53,
      "hex": "H7",
      "tile": "9-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 54,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 55
    },
    {
      "type": "lay_tile",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 56,
      "hex": "P13",
      "tile": "473-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 57,
      "hex": "Q12",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 58,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 59
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 60,
      "shares": [
        "TM_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 62,
      "shares": [
        "TM_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 64,
      "shares": [
        "TM_5"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 65,
      "shares": [
        "TM_1",
        "TM_2",
        "TM_5"
      ],
      "percent": 30
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 66
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 67,
      "shares": [
        "CHI_1",
        "CHI_2",
        "CHI_3",
        "CHI_4"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 68,
      "corporation": "PAC",
      "share_price": "60,2,2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 69,
      "shares": [
        "MEX_1",
        "MEX_2",
        "MEX_3",
        "MEX_4"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 70,
      "corporation": "SPM",
      "share_price": "60,2,2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 71,
      "shares": [
        "MC_1",
        "MC_2",
        "MC_3",
        "MC_4"
      ],
      "percent": 40
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 72,
      "corporation": "UdY",
      "share_price": "60,2,2"
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 74,
      "corporation": "UdY",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 75,
      "shares": [
        "SPM_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 77,
      "shares": [
        "SPM_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 78
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 79,
      "shares": [
        "SPM_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 81,
      "shares": [
        "SPM_4"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 83,
      "shares": [
        "PAC_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 85,
      "shares": [
        "PAC_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 87,
      "shares": [
        "PAC_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 89,
      "shares": [
        "PAC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 90,
      "shares": [
        "UdY_1"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 91,
      "shares": [
        "SPM_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 92,
      "shares": [
        "UdY_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 93,
      "shares": [
        "UdY_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 97
    },
    {
      "type": "pass",
      "entity": "A",
      "entity_type": "minor",
      "id": 98
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 99,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "minor",
      "id": 100
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 101,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "C",
      "entity_type": "minor",
      "id": 102
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 103,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 104
    },
    {
      "type": "buy_train",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 105,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 107
    },
    {
      "type": "undo",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 108
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 109,
      "hex": "D3",
      "tile": "57-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 110,
      "hex": "F3",
      "tile": "8-2",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 111
    },
    {
      "type": "buy_train",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 112,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "lay_tile",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 114,
      "hex": "O8",
      "tile": "6-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 115,
      "hex": "M8",
      "tile": "8-3",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 116,
      "train": "2-8",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 118,
      "hex": "K12",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 119,
      "hex": "M12",
      "tile": "472-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 120,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 121
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 122
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 123,
      "hex": "I8",
      "tile": "14-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 124
    },
    {
      "type": "run_routes",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 125,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "I8",
              "H7",
              "G6",
              "E6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 126,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 127,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 128
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 129
    },
    {
      "type": "lay_tile",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 130,
      "hex": "O10",
      "tile": "479MC-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "run_routes",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 132,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "P13"
            ],
            [
              "P11",
              "Q12",
              "P13"
            ],
            [
              "P11",
              "O10"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 133,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 134,
      "train": "3-2",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 136
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 137,
      "hex": "L9",
      "tile": "4-0",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 138,
      "hex": "M10",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 139
    },
    {
      "type": "run_routes",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 140,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "M10",
              "L9"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "I8",
              "K8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 141,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 142,
      "train": "3-3",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 143
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 144
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 145
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 146
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 147
    },
    {
      "type": "lay_tile",
      "entity": "A",
      "entity_type": "minor",
      "id": 148,
      "hex": "M12",
      "tile": "477-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "A",
      "entity_type": "minor",
      "id": 149,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ],
            [
              "M12",
              "K12",
              "I12"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "B",
      "entity_type": "minor",
      "id": 150,
      "hex": "K6",
      "tile": "471-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "minor",
      "id": 151,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "C",
      "entity_type": "minor",
      "id": 152,
      "hex": "S12",
      "tile": "5-0",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "C",
      "entity_type": "minor",
      "id": 153,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 154,
      "hex": "P13",
      "tile": "478-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 155
    },
    {
      "type": "run_routes",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 156,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "P13"
            ],
            [
              "P13",
              "Q14"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 157,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 158,
      "train": "3'-0",
      "price": 180,
      "variant": "3'"
    },
    {
      "type": "pass",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 159
    },
    {
      "type": "pass",
      "entity": "UdY",
      "entity_type": "corporation",
      "id": 160
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 161,
      "hex": "C2",
      "tile": "8-4",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 162,
      "hex": "G4",
      "tile": "8-5",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 163
    },
    {
      "type": "run_routes",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 164,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "B1",
              "C2",
              "B3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 165,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 166,
      "train": "3'-1",
      "price": 180,
      "variant": "3'"
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 167
    },
    {
      "type": "pass",
      "entity": "PAC",
      "entity_type": "corporation",
      "id": 168
    },
    {
      "type": "lay_tile",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 169,
      "hex": "L9",
      "tile": "474-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 170
    },
    {
      "type": "run_routes",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 171,
      "routes": [
        {
          "train": "2-8",
          "connections": [
            [
              "I8",
              "K8"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "L9",
              "M8",
              "O8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 172,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 173,
      "train": "4-0",
      "price": 300,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 174
    },
    {
      "type": "pass",
      "entity": "SPM",
      "entity_type": "corporation",
      "id": 175
    },
    {
      "type": "lay_tile",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 176,
      "hex": "E6",
      "tile": "14-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 177
    },
    {
      "type": "run_routes",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 178,
      "routes": [
        {
          "train": "3-1",
          "connections": [
            [
              "L9",
              "M10"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "I8",
              "K8"
            ],
            [
              "E6",
              "G6",
              "H7",
              "I8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 179,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 180,
      "train": "4-1",
      "price": 300,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation",
      "id": 181
    },
    {
      "type": "lay_tile",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 182,
      "hex": "M10",
      "tile": "14-2",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 183
    },
    {
      "type": "run_routes",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 184,
      "routes": [
        {
          "train": "3-2",
          "connections": [
            [
              "L9",
              "K8"
            ],
            [
              "M10",
              "L9"
            ],
            [
              "M10",
              "O10"
            ],
            [
              "P11",
              "O10"
            ],
            [
              "P13",
              "Q12",
              "P11"
            ],
            [
              "P13"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 185,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 186,
      "train": "4-2",
      "price": 300,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation",
      "id": 187
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 188,
      "hex": "N11",
      "tile": "8-6",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 189
    },
    {
      "type": "undo",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 190
    },
    {
      "type": "lay_tile",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 191,
      "hex": "H11",
      "tile": "8-7",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 192
    },
    {
      "type": "run_routes",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 193,
      "routes": [
        {
          "train": "3-0",
          "connections": [
            [
              "L9",
              "K8"
            ],
            [
              "M10",
              "L9"
            ],
            [
              "M10",
              "N11",
              "M12"
            ],
            [
              "M12",
              "K12",
              "I12"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 194,
      "kind": "withhold"
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 195
    },
    {
      "type": "pass",
      "entity": "TM",
      "entity_type": "corporation",
      "id": 196
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 197,
      "hex": "O8",
      "tile": "15-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 198
    },
    {
      "type": "run_routes",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 199,
      "routes": [
        {
          "train": "3-3",
          "connections": [
            [
              "P11",
              "O10"
            ],
            [
              "M10",
              "O10"
            ],
            [
              "M10",
              "L9"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "I8",
              "K8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 200,
      "kind": "withhold"
    },
    {
      "type": "buy_train",
      "entity": "MC",
      "entity_type": "corporation",
      "id": 201,
      "train": "5-0",
      "price": 450,
      "variant": "5"
    }
  ],
  "id": "hs_rdiijwhx_1603149128",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18MEX",
  "description": "test",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-19",
  "loaded": true,
  "result": {}
}

**Comment by roseundy** [comment]
This looks like a bug that I thought was already fixed.

**Comment by roseundy** [comment]
I wonder if the problem is that we are checking this condition in between the two individual tile lays. If we are, when MC is upgraded while P is not, there is no path from P to MC (due to the difference in lane widths). Again, I thought this has been tested and fixed.

**Comment by roseundy** [comment]
Now I'm pretty sure this got re-broken during all the Lawson tile work. One fix: allow tracing a path across a lane width change. Another fix: lay the Puebla tile first while overriding to permissive track lays, then the Mexico City tile.

**Comment by perwestling** [comment]
@roseundy Sounds like laying Puebla first might be the easiest one, and possibly the best. Although it might get strange error messages in case the tile lay is invalid (if not enough money to upgrade Puebla).

**Comment by roseundy** [comment]
Actually, if we are going to be temporarily overriding TRACK_RESTRICTION for Puebla, we should just do it for both and call it a day. After all, this is the only upgrade for that location and we know it is legal.
