### ISSUE TITLE
Usability Improvement Suggestions

### ISSUE THREAD

**Issue by Corvus-IRL** [tobymao/18xx#196]
As posted on BGG. It would be great to see the following implemented. 

- a revenue tracker (without having to scroll back through the history)
- an indication on the player information as to who has priority deal
- ability to turn on/off master mode
- ability to program future actions in a Stock Round
- Train rusting chart # #

**Comment by tobymao** [comment]
hello @Corvus-IRL i appreciate this, but but all of these are already filed in github. so i'm going to close out this issue as it's a duplicate

**Comment by Corvus-IRL** [comment]
Hi Tony,

No problem. I didn't see them listed, sorry for the duplication. Apologies
also if my posts on BGG were impolite in any way. I certainly didn't mean
it to come across like that.

Great work on the site. Its great!

Jim

**Comment by tobymao** [comment]
Hey Jim, 

I did not get that impression. Hope you enjoy the site! And keep giving me feedback.
