### ISSUE TITLE
[18LA] SP teleport token should cost $60 if not connected, not $100

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#1960]
As stated, The teleport token for SP should be $60, not $100, as indicated in the rulebook.

[Screenshot from 2020-10-20 17-39-23](https://user-images.githubusercontent.com/26125362/96647362-77be8d00-12fb-11eb-950d-a03e32b199b1.png)

https://www.18xx.games/game/13257

**Comment by michaeljb** [comment]
There currently seems to be a discrepancy between the rulebook and the SP charter (which indicates a $100 cost), I have reached out for clarification.

**Comment by michaeljb** [comment]
Tony has confirmed that $100 is correct
