### ISSUE TITLE
Undo fails undoing routes

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1961]
Undo sometimes fails at the step of undoing routes.

In this JSON hotseat game, clicking undo the fourth time fails.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 1,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 3,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 4,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "company": "MC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9,
      "corporation": "NYC",
      "share_price": "50,0,5"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 10,
      "corporation": "PRR",
      "share_price": "70,0,7"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 11,
      "corporation": "GT",
      "share_price": "100,0,10"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "NYC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "PRR_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "GT_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "NYC_2"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "redo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 21,
      "hex": "C13",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 22,
      "hex": "B16",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 23,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "B16",
              "C15"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 24,
      "hex": "G9",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 25,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 26,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G7",
              "G9"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 27,
      "hex": "D18",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 28,
      "hex": "E17",
      "tile": "292-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 29
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 30,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 31,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 32
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 33
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 34
    },
    {
      "type": "sell_shares",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 35,
      "shares": [
        "NYC_3",
        "NYC_4",
        "NYC_5",
        "NYC_6"
      ],
      "percent": 40,
      "share_price": 40
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 38,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 39,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 40
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 41
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 42,
      "hex": "E19",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "sell_shares",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 43,
      "shares": [
        "PRR_2",
        "PRR_3",
        "PRR_4"
      ],
      "percent": 30,
      "share_price": 60
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 44
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 45,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 46,
      "train": "2-6",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 47,
      "train": "4-0",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 48
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 49
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 50,
      "hex": "C11",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 51,
      "hex": "C9",
      "tile": "6-2",
      "rotation": 4
    },
    {
      "type": "sell_shares",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 52,
      "shares": [
        "GT_2",
        "GT_3",
        "GT_4"
      ],
      "percent": 30,
      "share_price": 90
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 53
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 54,
      "train": "4-1",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 55,
      "train": "4-2",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 56
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 57
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 58,
      "hex": "D8",
      "tile": "8-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 59,
      "hex": "D6",
      "tile": "298-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 60,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "B16",
              "C15"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 61,
      "hex": "F6",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 62,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G7",
              "G9"
            ]
          ]
        }
      ]
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 63,
      "company": "MC",
      "price": 40
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 64,
      "hex": "B14",
      "tile": "8-3",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "company",
      "id": 65,
      "hex": "B12",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 66,
      "hex": "B10",
      "tile": "9-4",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 67,
      "city": "C15-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 68,
      "routes": [
        {
          "train": "4-1",
          "connections": [
            [
              "B8",
              "B10",
              "B12",
              "B14",
              "A15",
              "B16"
            ],
            [
              "B16",
              "C15"
            ]
          ]
        },
        {
          "train": "4-2",
          "connections": [
            [
              "D6",
              "D8",
              "C9"
            ],
            [
              "C9",
              "C11",
              "C13",
              "C15"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 69,
      "kind": "payout"
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 70
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "redo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 72
    },
    {
      "type": "redo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 73
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 74
    }
  ],
  "id": "hs_jxhwlrdq_1603242496",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1846",
  "description": "test",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-10-20",
  "loaded": true,
  "result": {}
}

**Comment by tobymao** [comment]
not sure why this is happening yet. basically when you convert a route to_h when you clone it, it calls revenue which is empty

**Comment by tobymao** [comment]
fixed

**Comment by tobymao** [comment]
with 1e544 because the previous runroute action got cached
