### ISSUE TITLE
[18MEX] UdY can run a train through Mérida (off-board hex Q14)

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#1967]
in 18MEX, UdY was allowed to run a 3-train route through its home station in Mérida (Q14), despite it being an off-board location.  (P13-Q14-S12)

The move has been undone, but here is the preceding action:
https://www.18xx.games/game/12968?action=206

**Comment by perwestling** [comment]
Here is a gist showing the problem, and which UdY just made that illegal run:
[18MEX hotseat 3 player game](https://gist.github.com/perwestling/eaa74d5b90bdb7b1e2d245055b0d9322)

**Comment by roseundy** [comment]
This bug applies to all games with "terminal" paths, not just 18MEX.

**Comment by perwestling** [comment]
Has been reproduced in 18AL, so yes, it seems to be a general issue, and it is something that has broken since 18AL was set in production stage.

**Comment by roseundy** [comment]
@perwestling I know you assigned yourself to this, but I have a fix.
