### ISSUE TITLE
Revenue display

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#197]
I know that you can go back and find the revenue from the game log and an entire revenue track might be overkill, but having “last revenue” available somewhere would be nice.

I know not everyone considers that, especially in a shorter game like 1889 where trains can rush quickly and revenue will fluctuate, but it can still be useful.

Apologies ahead of time if this is already present and I’m just not seeing it or if it has been asked and answered.

**Comment by tobymao** [comment]
dup https://github.com/tobymao/18xx/issues/121
