### ISSUE TITLE
Ehime Railway does not trigger when sold to corporation

### ISSUE THREAD

**Issue by pedrostruck** [tobymao/18xx#198]
When sold to a corporation the Ehime Railway is not triggering the "free" green tile that the selling player is allowed to place in Ohzu.

If I try to set the green tile in Ohzu, it count's as the corporation tile laying of the Operating Round, and not the selling player tile laying (which is what occurs).

**Comment by tobymao** [comment]
as soon as it's sold, you need to click on the company in the companies tab. then you can lay the tile for free
