### ISSUE TITLE
18Mex Merge Issue

### ISSUE THREAD

**Issue by jazhuit** [tobymao/18xx#1980]
NDM Merge 

game - 
https://www.18xx.games/game/13258

![image](https://user-images.githubusercontent.com/28173770/97027838-eb8daf00-1520-11eb-9287-5137f41d7658.png)

**Comment by perwestling** [comment]
@jazhuit Can you add a bit more information? If I check the game all corporations declined the merge so there were no merge. Do you know at which action this problem occured?

**Comment by jazhuit** [comment]
We declined because we couldn't merge due the error. The only option was to
move the game forward, was to decline.

I captured the error posting and then we continued on

**Comment by perwestling** [comment]
@jazhuit Ok, but can you remember which corporation(s) who tried to do merge, and fail?

**Comment by jazhuit** [comment]
Mexican Central

(And thanks for all the awesome work)

(Oh, small plug for adding 1836....it's a rare Winsome 18xx that is
starting to gain popularity... And it's really good)
