### ISSUE TITLE
[1817] Token buying when converting not working as expected

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#1984]
When a company converts, the tokens are being bought before players get the chance to buy/sell shares. It should be after.

If the company doesn't have enough money, the token simply does not get bought. It should require the player to take loans to buy the token (or liquidate if they don't buy them)

An example when this happened: https://www.18xx.games/game/13537?action=523

**Comment by jenf** [comment]
Confirmed, first instance I think is https://18xx.games/game/13537?action=323

**Comment by jenf** [comment]
I think the loan + token step need to be separated into alternative step which is done after the post conversion step

**Comment by daniel-sousa-me** [comment]
That's how the rules have it written. There's a buy token/take loans step after the post conversion step.

For mergers and friendly sales there is also a take loans step after post conversion, which maybe is also not implemented (and if it is, you can make use of that code)
