### ISSUE TITLE
[1817] During the SR a company should be able to take loans and then redeem shares

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#1986]
The rules allow a player, when acting as a company, to take loans and then redeem shares in the same action, but the website only allows one of them at a time

**Comment by jenf** [comment]
note the order is important, must be loans first. if they redeem shares they cannot take loans.

**Comment by GAFBlizzard** [comment]
Is it possible to reopen this issue?  In the current hotseat game hs_ygkmjbth_13649, a company was sold short by 2 shares.  The company's owner then clicked the Loan button once, which enabled the Redeem button.  Clicking the Redeem button resulted in a pause, then an error that the owner cannot buy shares.

Are we missing something?

**Comment by jenf** [comment]
Please create a new issue redeem worked last night when I was fixing this so it must be something more subtle

**Comment by daniel-sousa-me** [comment]
And copy-paste the game data. The hotseat games are stored locally on your computer

**Comment by GAFBlizzard** [comment]
@jenf @daniel-sousa-me thanks so much!  I created https://github.com/tobymao/18xx/issues/2004
