### ISSUE TITLE
[1817] Player can buy a specific company locally, but not on the server

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#1989]
In the game: https://www.18xx.games/game/13537?action=823
Ariel can buy J, but when the action is sent to the server, it giver an error

**Comment by jenf** [comment]
ruby
823 ["beginetienne 218", "daniel.sousa.me 43", "Ariel 163", "mtsay 143"]
javascript
823 beginetienne 219,daniel.sousa.me 43,Ariel 165,mtsay 145

hunting for the variance.
