### ISSUE TITLE
Tile Rendering

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#2]
required for a playable 1889:

- [x] private companies that block building
- [x] upgrade cost
- [x] icons (mountain, river)
- [x] definitions for 1889 preprinted tiles
- [x] offboard / red tiles
- [x] render reserved spaces (start with text, eventually corporation's logo)

required for playable 1830, 1846, and 1861:

- [x] add definitions for 1830
- [x] add definitions for 1846
- [ ] add definitions for 1861
- [ ] render multiple cities (e.g., OO, NY, Chi)
- [x] multiple revenue centers: render just one revenue circle, or render two separately (currently 2 rendered, right on top of each other)
- [ ] more icons (e.g., meat packing, port)
- [ ] E/W label and bonus
- [ ] render 1830's preprinted tile for PRR's home

other (mainly aesthetic features):

- [ ] three-digit revenues need to render without bleeding over the circle
- [x] elements should not render outside bounds of hex (e.g., Uwajima)
- [x] make location names part of the hexes instead of tiles
- [x] smart positioning for circles showing the revenue
- [x] "white background" / box for 4+ city slots (implemented for 2-3)
- [ ] clearly show crossing track (white outline)
- [x] fix rendering gentle curve on top of other curves (see tile 16)
- [x] center tile name when rendering just the tile name due to error?
- [x] 1889 preprinted gray town names should be rendered (Yawatahama, Muroto)

**Comment by michaeljb** [comment]
svg code that was used for white outline for straight track:

```
          h(:path, attrs: { d: 'm -4 86 L -4 -86', stroke: 'white', 'stroke-width' => 2 }),
          h(:path, attrs: { d: 'm 4 86 L 4 -86', stroke: 'white', 'stroke-width' => 2 }),
```

**Comment by michaeljb** [comment]
Location names should probably be moved to the hexes, and be assigned in a game's init_map

**Comment by tobymao** [comment]
jcl suggests boxing grouped city circles

**Comment by sparr** [comment]
Tile definitions for additional games are coming as @kelsin implements automatic export from 18xx-maker.

**Comment by kelsin** [comment]
I implemented the boxes for cities of size 4-6, that's live.

**Comment by kelsin** [comment]
Double city rendering is like... 1/2 done. They show up but stupid right now. Going to abstract the code I wrote for double dits, and get that into cities as well. It's in my plan for this weekend unless someone else wants it of course.

**Comment by kelsin** [comment]
A lot of exporting work on 18xx-maker done this weekend but not in a form that's presentable here. Finalizing my templates and should have something asap. Fixed the town bug, and making sure tile rotations are good. Don't want to break live games with rotation changes, so we're figuring that out and thinking about it now. Have most of the tiles from 18xx-maker exporting properly now. Will be checking 30/46/61/41/49 etc tiles.

**Comment by michaeljb** [comment]
Closing this as 1830 and 1861 aren't at the top of the queue for titles to implement. I think @thebamaman has some work done on white outlines for track, to help clearly show track crossing? The other checklist items relevant to 1846 can go into other issues.
