### ISSUE TITLE
Suggestion : Shares in the Bank vs Shares in IPO

### ISSUE THREAD

**Issue by McDood** [tobymao/18xx#20]
Add a way to know how many share of a company are in the bank pool vs the quantity in the IPO

When there is share both in the IPO and the bank pool, have a way to select from where to buy the share

**Comment by tobymao** [comment]
i've added a way to select bank shares but haven't done the UI for info yet

**Comment by Talbatross** [comment]
This should be visible now.  Let me know if the latest works for you.
