### ISSUE TITLE
Improve the route bonus presentation in 18AL and 18MS

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2000]
18AL has two privates that gives route bonus and run bonus respectively.
18MS has New Orleans bonus.

Consider using similar method as #1981

**Comment by BellmakerSA** [comment]
Could this or something similar be used for the mail contract in 1846/18LA as well?

**Comment by perwestling** [comment]
Would solve #1302

**Comment by scottredracecar** [comment]
@perwestling do you think you will solve these? I know you are maintaining some of the games you have implemented so I don't want to close your issues if you think you will get to them in time. It's also okay to close issues, not everything needs a perfect implementation. I don't think someone else will step up to fix issues like this.

**Comment by perwestling** [comment]
I play to fix it for 18AL and 18MS as I think it is a good enhancement. But it has been low priority.

**Comment by perwestling** [comment]
Seems to already be implemented in 18AL:
![image](https://user-images.githubusercontent.com/2631151/152655154-1eca3d4b-64cf-4325-862f-791ca9db2a85.png)

![image](https://user-images.githubusercontent.com/2631151/152655127-44c8a6cd-9096-4d43-9422-1ec75aaf1ea7.png)

**Comment by perwestling** [comment]
18MS were lacking such a bonus presentation for the New Orleans bonus. So I will make a commit that adds this. Here is how it will look in the GUI.

It would look like this in the route dialog:
![image](https://user-images.githubusercontent.com/2631151/152656067-c3ad95ab-cc92-4ed3-9a2c-5d4b1a9113db.png)

And in the game log:
![image](https://user-images.githubusercontent.com/2631151/152656093-9f1a0fd0-0368-476e-843f-e0fe1e662598.png)
