### ISSUE TITLE
18Mex Force Buy Issue

### ISSUE THREAD

**Issue by jazhuit** [tobymao/18xx#2006]
I had to force buy...but it says I don't have the money and now game is 'out of synce'

![image](https://user-images.githubusercontent.com/28173770/97087096-20673800-15ed-11eb-9843-b22620f8cda6.png)

https://www.18xx.games/game/13258

**Comment by jazhuit** [comment]
![image](https://user-images.githubusercontent.com/28173770/97087127-50164000-15ed-11eb-8477-4b37e18573be.png)

**Comment by perwestling** [comment]
This is an issue with the 5% NdM share, and a correction is on its way with issue #2001.
