### ISSUE TITLE
Operator + applied to nil

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#201]
Hotseat two player game.  Start of stock round, clicked over to companies tab & selected Dougo Railwa, owned by current player.  Clicked on game tab and clicked the Exchange button and got the above error.
Game data in next comment

**Comment by gchambers419** [comment]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Mitsubishi Ferry",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Ehime Railway",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 3,
      "company": "Sumitomo Mines Railway",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "company": "Dougo Railway",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 5,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "corporation": "TR",
      "share_price": "80,2,3"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "corporation": "UR",
      "share_price": "90,1,3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "share": "TR_1"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9,
      "corporation": "IR",
      "share_price": "65,5,3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 10,
      "share": "IR_1"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "share": "IR_2"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 17,
      "share": "TR_2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "TR_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 23,
      "share": "TR_3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 27,
      "hex": "G10",
      "tile": "58-0",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 28,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 29,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 30
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 31
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 33,
      "hex": "G8",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 34,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 35,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 37,
      "share": "IR_3"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 39,
      "share": "TR_4"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 40,
      "shares": [
        "TR_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 43
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 44,
      "hex": "H7",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 45
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 46,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G8",
            "H7"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 47,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 48
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 49,
      "hex": "E2",
      "tile": "57-0",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 50,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 51,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 52
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 53
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 54,
      "share": "TR_5"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 55,
      "shares": [
        "TR_3"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 57
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 58
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 59,
      "hex": "G12",
      "tile": "57-1",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 60
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 61,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G8",
            "H7"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 62,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 63
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 64,
      "hex": "D3",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 65,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "E2",
            "F1"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 66,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 68,
      "share": "UR_1"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 69
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 70,
      "share": "TR_6"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 73,
      "share": "TR_7"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 75
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 77,
      "hex": "H5",
      "tile": "8-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 78
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 79,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G8",
            "H7"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 80,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 81
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 82
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 83,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "E2"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 84,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 85
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 87,
      "share": "IR_4"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 90
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 91,
      "hex": "I4",
      "tile": "438-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 92,
      "city": "438-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 93,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "I4",
            "H5",
            "H7"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 94,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 97,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-3",
          "hexes": []
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 98,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 100,
      "share": "IR_5"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 101
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 102,
      "share": "IR_6"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 103,
      "shares": [
        "IR_1",
        "IR_4",
        "IR_6"
      ],
      "percent": 30
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 104
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 105
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 106,
      "corporation": "AR",
      "share_price": "80,2,3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 107
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 108
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 109,
      "share": "AR_1"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 110
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 111
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 112,
      "share": "AR_2"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 113
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 114
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 115
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 116,
      "hex": "I2",
      "tile": "6-1",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 118,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "I4",
            "I2"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 119,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 120
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 121
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 122,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "E2",
            "F1"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 123,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 124
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 125,
      "share": "IR_7"
    },
    {
      "type": "sell_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 126,
      "shares": [
        "IR_2",
        "IR_3"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 127
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 128,
      "share": "AR_3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 129
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 130,
      "corporation": "KO",
      "share_price": "80,2,3"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 131
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 132
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 133
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 134,
      "hex": "F7",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 136,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "I4",
            "I2"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 137,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 138
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 139,
      "hex": "K8",
      "tile": "5-0",
      "rotation": 3
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 140,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 141,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 142,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 143
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 144
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 145,
      "hex": "C4",
      "tile": "13-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 146
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 147,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "E2",
            "D3",
            "C4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 148,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 149,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 150
    },
    {
      "type": "lay_tile",
      "entity": "Mitsubishi Ferry",
      "entity_type": "company",
      "id": 151,
      "hex": "B11",
      "tile": "437-0",
      "rotation": 2
    },
    {
      "type": "buy_company",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 152,
      "company": "Mitsubishi Ferry",
      "price": 60
    },
    {
      "type": "buy_company",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 153,
      "company": "Sumitomo Mines Railway",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 154
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 155,
      "share": "AR_4"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 156
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 157,
      "share": "KO_1"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 158
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 159
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 160,
      "share": "KO_2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 161,
      "shares": [
        "KO_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 162
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 163
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 164
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 165,
      "hex": "I4",
      "tile": "439-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 166
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 167,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "I4",
            "I2"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F9",
            "G8",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 168,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 169,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 170,
      "train": "3-3",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 172,
      "hex": "B5",
      "tile": "9-2",
      "rotation": 3
    },
    {
      "type": "place_token",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 173,
      "city": "B7-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 174,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "3-1",
          "hexes": [
            "C4",
            "B3",
            "B5",
            "B7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 175,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 176,
      "train": "3-4",
      "price": 180
    },
    {
      "type": "buy_company",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 177,
      "company": "Takamatsu E-Railroad",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 179,
      "hex": "K8",
      "tile": "12-0",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 180,
      "routes": [
        {
          "train": "2-4",
          "hexes": [
            "K8",
            "L7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 181,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 182,
      "train": "4-0",
      "price": 300
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 183
    },
    {
      "type": "buy_company",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 184,
      "company": "Ehime Railway",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 185
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 186,
      "hex": "J5",
      "tile": "58-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 187
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 188,
      "routes": [
        {
          "train": "3-2",
          "hexes": [
            "I4",
            "I2",
            "J1"
          ]
        },
        {
          "train": "3-3",
          "hexes": [
            "I4",
            "H5",
            "H7",
            "G8",
            "F9"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 189,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 190
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 191
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 192,
      "hex": "A8",
      "tile": "8-2",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 193,
      "routes": [
        {
          "train": "3-1",
          "hexes": [
            "C4",
            "D3",
            "E2",
            "F1"
          ]
        },
        {
          "train": "3-4",
          "hexes": [
            "B7",
            "B5",
            "B3",
            "C4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 194,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 195
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 196
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 197,
      "hex": "K6",
      "tile": "9-3",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 198,
      "routes": [
        {
          "train": "3-0",
          "hexes": []
        },
        {
          "train": "4-0",
          "hexes": [
            "K8",
            "K6",
            "K4",
            "J5",
            "I4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 199,
      "kind": "withhold"
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 200
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 201
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    }
  ],
  "title": "1889",
  "description": "",
  "max_players": "6",
  "id": "hs_1588070999",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-04-28"
}

**Comment by jenf** [comment]
Seems to work on the latest master

**Comment by tobymao** [comment]
i’ll take @jenf word for it
