### ISSUE TITLE
[18Mex] SPM token appears on market after merger

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#2017]
NdM merged with unstarted SPM correctly, in game 12968, but SPM token appeared on market afterwards for no reason.

![4CC8B517-BA26-4C99-915D-49F2F3711067](https://user-images.githubusercontent.com/73144084/97111215-f167c980-16b3-11eb-9dad-ff5e664bdbcc.png)

**Comment by perwestling** [comment]
I think this has been fixed, and should be corrected with next deploy, but I will check on it.

**Comment by perwestling** [comment]
Is now fixed in the deployed code.
