### ISSUE TITLE
Token reservations removed at Phase IV - 18 Los Angeles and 1846

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2021]
Token reservations go away at the beginning of phase IV, though the discount on placement remains. This should be reflected on the Info page, in the Events. The word "reserved" should be removed from company charters at the beginning of phase IV.

**Comment by michaeljb** [comment]
What do you think of these charters @ChrisTheCat? (Also note the tile-laying change on the IC charter, it's not quite a fix for #1752 but it does clarify that the free tile lay can't be used to upgrade any of those hexes)

![Screenshot from 2020-10-25 14-07-40](https://user-images.githubusercontent.com/1045173/97117792-aa85ce00-16cb-11eb-8f66-8774311e92f3.png)

**Comment by ChrisTheCat** [comment]
Looks good. Will the 'reserved' line disappear when phase IV starts?

**Comment by michaeljb** [comment]
Yep. I haven't fixed up the phase/train tables yet, I may get to that later this week and then this issue can be closed.

**Comment by benjaminxscott** [comment]
Do the above PRs resolve this issue?

**Comment by ChrisTheCat** [comment]
Probably? I don't know how to read a PR (I'm not a programmer).
