### ISSUE TITLE
[18Chesapeake] Chesapeake & Ohio Canal missing from map

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#2025]
The Chesapeake & Ohio Canal is not indicated (as are the other private companies) on the map

<img src="https://user-images.githubusercontent.com/757327/97119034-f2b0ea80-16e3-11eb-94f4-2a4397a1608a.jpeg" width=200><&nbsp;><img src="https://user-images.githubusercontent.com/757327/97119049-11af7c80-16e4-11eb-8478-85dbe9f13e53.jpeg" width=200>

**Comment by michaeljb** [comment]
It is indicated at https://www.18xx.games/map/18Chesapeake

Can you provide a game ID where you are encountering this?

**Comment by doleksy** [comment]
I just looked in one of my games:
https://18xx.games/game/12122#map

And it is not showing. It shows before a corporation buys the company.

**Comment by michaeljb** [comment]
Thanks for the tip @doleksy! I think I see the cause of the problem now
