### ISSUE TITLE
Illegal tile upgrade allowed

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#203]
Step one placed this tile:

    {
      "type": "lay_tile",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 387,
      "hex": "D7",
      "tile": "7-1",
      "rotation": 0
    },

I later placed this tile:

    {
      "type": "lay_tile",
      "entity": "KU",
      "entity_type": "corporation",
      "id": 408,
      "hex": "D7",
      "tile": "28-0",
      "rotation": 0
    }

This placement seems legal.  However, the game also allowed the rotation where the south edge and the SSE edge were no longer linked to each other.  I don't think that would be a legal placement.

**Comment by rheretic** [comment]
OP:  I would retry this to see if it's still present.  Quite a bit of code change since you opened this.

**Comment by tobymao** [comment]
no none of these laying bugs were fixed
