### ISSUE TITLE
[1817] OR1.1 company did not pay interest on loan taken.

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2030]
In OR 1.1 the (only) company bought a 2T then took a loan, then passed, and it started OR 1.2 with $100.

The expected behavior is that $5 interest for the loan is deducted at the end of the companies' operating turn.

I have reproduced the issue in a hotseat game and here is the JSON
https://gist.github.com/ventusignis/560fe490ef42d029f7ea0b9703955a6f

**Comment by jenf** [comment]
Correct behavior

You are taking the loan after paying back the 0 loans taken (which has no log). This is explicitly stated as the behavior in the rules in section 6.9

If you take the loan at the buy trains step

`A&S takes a loan and receives $100
A&S's share price changes from $45 to $40
A&S passes buy trains
A&S pays $5 interest for 1 loans
`

**Comment by ventusignis** [comment]
Thanks @jenf I never noticed that detail in the rules
