### ISSUE TITLE
[1846] buying in a private shouldn't force end turn

### ISSUE THREAD

**Issue by th3tick** [tobymao/18xx#2032]
1846
When buying in the meat packing plant at the end of my company's turn, it instantly ended that company's turn.  So I sat there clicking and trying to get the token placed for that private, but didn't realize it had moved on.  The brown phase was started shortly thereafter and I was left with the option to beg for my company's turn back to place the token.

The company turns should never auto-end, especially on something as innocuous as buying a private.  There are a number of other things I could still have done, all taken away with not a whit of notification.

**Comment by michaeljb** [comment]
sample game reproducing this issue - https://gist.github.com/michaeljb/8e63a7442f4bcb0fafa4d6478a597d52
