### ISSUE TITLE
[18Los Angeles] [Game: 13645] Can't lay available Z tile on B13, game reports "Tile Already in Use"

### ISSUE THREAD

**Issue by lfbprod** [tobymao/18xx#2033]
https://www.18xx.games/game/13645

It really helps us having a sample game to reproduce the issue.

In OR 1.1, Operating the UP, Cannot lay down either Tile number 291 or 292 on B13, getting an error that "Tile is already in use." 

Only tile 293 has been used, the other two Z tiles should be available.

**Comment by jenf** [comment]
fixed by toby
