### ISSUE TITLE
Error: Tile already in use

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2034]
**Describe the bug**
When I try to place a tile, I'm getting "Tile already in use." This happens no matter the tile I try to lay (yellow or otherwise), no matter the orientation. For reference, I'm seeing it in game IDs 13544 (MS) and 13050 (AL).

**Please provide details about your system**
 - OS: Chrome OS
 - Browser: Chrome 85.0.4183.133

**Comment by tobymao** [comment]
@jenf

**Comment by Craig1830** [comment]
Adding to this issue...

I had the same problem occur in 18 Los Angeles.  Tried multiple tiles in the two available locations. 
Message: “Tile is already used”
https://www.18xx.games/game/13615?action=48

One action later, I could place a tile:
https://www.18xx.games/game/13615?action=49

Screenshots:
![A4DAE40B-110F-4469-9BD3-C604BFD2F399](https://user-images.githubusercontent.com/73244775/97128652-d9c62a80-171f-11eb-855b-c8be8bdd2c8b.png)

![174A99E7-4CA3-46F6-889F-E25513ABC0D4](https://user-images.githubusercontent.com/73244775/97128648-d763d080-171f-11eb-9c45-85c0dcf6c666.png)

**Comment by jenf** [comment]
Toby fixed
