### ISSUE TITLE
[1817] A 2-share company converted to a 5-share company will erroneously report that it "floated" again when redeeming shares.

### ISSUE THREAD

**Issue by GAFBlizzard** [tobymao/18xx#2035]
![1817_float_bug](https://user-images.githubusercontent.com/539467/97128747-83eb8580-1713-11eb-92b3-efc2039605fd.png)

A 2-share company was floated.
It was converted to a 5-share company.
Someone sold 2 shares short of the 5-share company.
The CEO took loans and redeemed the 2 short shares, resulting in the "floats" message in the screenshot.

**Comment by michaeljb** [comment]
https://www.18xx.games/game/13649?action=372 :detective:
