### ISSUE TITLE
1889: Support "Beginner's game" rules as an Optional Rule

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2039]
1889 does not have any optional rule as such. But the rules cover a Beginner Game Difference (without auction, and more tiles) that could be useful to have as an even more beginner friendly game. 

I suggest that this is added as an optional rule to the existing 1889 version.

Would be nice to have them as two options:
- [ ] Beginner game: Distribute privates rather than bid
- [ ] Beginner game: Extra tiles

**Comment by jenf** [comment]
the rules for GTG edition 1889 beginner privates may be different than the deep thought, i'm checking

**Comment by jenf** [comment]
fixed by #5892
