### ISSUE TITLE
1817: Support optional rules

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2040]
There are several optional rules in the 1817 rule book, that could be add as Optional Rules.

Consider having 5 shorts for 10 share corporation as an optional rule.

* [ ] 5 short option
* [x] 8-12 player
* [ ] Short squeeze
* [ ] Modern trains (7 & 8 gain 20 bonus from tokens)

**Comment by jenf** [comment]
When it gets to production :)

**Comment by SmithInMN** [comment]
I just noticed that 18MEX now has optional rules as well.

I agree that the 10-short variant should be looked at as well as the modern train variant and short squeeze variant.  The 8-12 player variant would be easy to implement, but who knows if it would ever get used.

**Comment by perwestling** [comment]
The idea behind optional rules in 18MEX is that there was a big request for "hard rust", and as 18MEX was in alpha it was a good opportunity to try the concept of optional rules in a title that is still under testing.  There are still a couple of problems (hard rust does not work, importing games looses optional rules) so before those problems are fixed I wont add more optional rules.
