### ISSUE TITLE
[1817] Company placing a Coal Mine and Mountain Engineers doesn't receive the 20$

### ISSUE THREAD

**Issue by ggohierroy** [tobymao/18xx#2045]
https://www.18xx.games/game/13538

There is a company that has both a Coal Mine and Mountain Engineers.

On my second lay, I want to put a coal mine on the board.

1. Select Coal Mine ability
2. Click on the mountain hex to place the coal mine and yellow tile

Expected results:

- 0$ fee to place the tile on the mountain hex because of coal mine ability
- 20$ fee because 2nd lay
- +20$ in treasury because mountain engineers

Net result: no change in treasury

Actual results:

- The company doesn't receive the 20$ from mountain engineers

**Comment by jenf** [comment]
18xx.games/game/13538?action=239
