### ISSUE TITLE
[1817] Pass button in SR should warn players they have tokens outstanding on 5/10 share corps

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#2054]
A 5- or 10-share company that floats, has to buy a token before the next OR starts. What about if this action would happen automatically (We forgot it several times and this company is instantly in red market area)

**Comment by jenf** [comment]
The rules specifically state it's optional, I suspect there is some strategic reasons you may want it to occur.

If so, we should change it so the pass button says "Pass (May liquidate corporations)"

**Comment by Ticketautomat1** [comment]
Have 1817 just played on rr18xx and there your company pays its token automatically. So I was wondering, why my companys was starting in the red liquidation area without any action. I can't estimate if there is any strategic reason, but there should be at least a warning before one passes without buying for tokens.

**Comment by jenf** [comment]
Best strategic way we can think of is to allow you to get a station marker without really running a company.

I think "Pass (May liquidate corporation)" is the best approach while sticking strictly to the rules.

**Comment by Ticketautomat1** [comment]
Thanks Jen, that's a good solution for this.

**Comment by tobymao** [comment]
the pass liquidate button is the same approach we use when growing up
