### ISSUE TITLE
Coal Mine ability not working

### ISSUE THREAD

**Issue by manthedan101** [tobymao/18xx#2057]
UR is unable to use coal mine ability (see the last turn from the game data)

Step to reproduce: 

Select ability, lay track, get this error message:
![image](https://user-images.githubusercontent.com/73503333/97246619-22d7b680-17d4-11eb-8f78-875bb649c1cb.png)

{
  "id": 13953,
  "description": "Sparmigiano 1",
  "user": {
    "id": 2461,
    "name": "ggohierroy"
  },
  "players": [
    {
      "id": 2461,
      "name": "ggohierroy"
    },
    {
      "id": 2468,
      "name": "Orange_Julec"
    },
    {
      "id": 2462,
      "name": "ManTheDan"
    }
  ],
  "max_players": 3,
  "title": "1817",
  "settings": {
    "seed": 60260439,
    "unlisted": true,
    "optional_rules_selected": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    2462
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 1,
      "company": "ME",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 2,
      "company": "ME",
      "price": 5
    },
    {
      "type": "message",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 3,
      "message": "Ok ready dès que je trouve mes écouteurs"
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 4,
      "company": "ME",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 5,
      "company": "ME",
      "price": 25
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 6
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 7
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 8,
      "company": "PSM",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 9,
      "company": "PSM",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 10,
      "company": "PSM",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 13,
      "company": "TS",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 14,
      "company": "TS",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 15,
      "company": "TS",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 16,
      "company": "TS",
      "price": 55
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 18,
      "company": "TS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 19,
      "company": "TS",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 21,
      "company": "MAJC",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 22,
      "company": "MAJC",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 23,
      "company": "MAJC",
      "price": 55
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 26,
      "company": "MAJM",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 29,
      "company": "MAIL",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 31,
      "company": "MAIL",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 32,
      "company": "MAIL",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 33,
      "company": "MAIL",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 35,
      "company": "CM",
      "price": 35
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 37,
      "company": "CM",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 39,
      "company": "MINM",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 41,
      "company": "MINM",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 42,
      "company": "MINM",
      "price": 35
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 43
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 44,
      "company": "OBC",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 45,
      "company": "OBC",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 47
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 49
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 50
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 51,
      "corporation": "A&S",
      "price": 110
    },
    {
      "type": "place_token",
      "entity": "A&S",
      "entity_type": "corporation",
      "id": 52,
      "user": "ggohierroy",
      "city": "H9-2-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "assign",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 55,
      "target": "ME",
      "target_type": "company"
    },
    {
      "type": "assign",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 56,
      "target": "OBC",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 57,
      "corporation": "GT",
      "price": 110
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 58,
      "user": "Orange_Julec",
      "city": "B17-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 59
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 60
    },
    {
      "type": "assign",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 61,
      "target": "MAIL",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 62,
      "corporation": "H",
      "price": 120
    },
    {
      "type": "place_token",
      "entity": "H",
      "entity_type": "corporation",
      "id": 63,
      "user": "ManTheDan",
      "city": "F3-4-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 64
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 65
    },
    {
      "type": "assign",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 66,
      "target": "TS",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 67,
      "corporation": "A&A",
      "price": 130
    },
    {
      "type": "place_token",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 68,
      "user": "ggohierroy",
      "city": "D9-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 69
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 70
    },
    {
      "type": "assign",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 71,
      "target": "PSM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 72,
      "corporation": "WT",
      "price": 110
    },
    {
      "type": "place_token",
      "entity": "WT",
      "entity_type": "corporation",
      "id": 73,
      "user": "Orange_Julec",
      "city": "G18-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 75
    },
    {
      "type": "assign",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 76,
      "target": "MINM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 77,
      "corporation": "UR",
      "price": 135
    },
    {
      "type": "place_token",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 78,
      "user": "ManTheDan",
      "city": "C22-3-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "assign",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 81,
      "target": "MAJC",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 82,
      "corporation": "Belt",
      "price": 200
    },
    {
      "type": "place_token",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 83,
      "user": "ggohierroy",
      "city": "D9-0-0",
      "slot": 1
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 85
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 86,
      "corporation": "WC",
      "price": 140
    },
    {
      "type": "place_token",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 87,
      "user": "Orange_Julec",
      "city": "C8-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "assign",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 89,
      "target": "MAJM",
      "target_type": "company"
    },
    {
      "type": "bid",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 90,
      "corporation": "R",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "R",
      "entity_type": "corporation",
      "id": 91,
      "user": "ManTheDan",
      "city": "F19-6-0",
      "slot": 0
    },
    {
      "type": "assign",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 92,
      "target": "CM",
      "target_type": "company"
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "bid",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 94,
      "corporation": "PW",
      "price": 150
    },
    {
      "type": "place_token",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 95,
      "city": "H3-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "ManTheDan",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "ggohierroy",
      "entity_type": "player",
      "id": 97
    },
    {
      "type": "pass",
      "entity": "Orange_Julec",
      "entity_type": "player",
      "id": 98
    },
    {
      "type": "lay_tile",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 99,
      "hex": "E8",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 100,
      "hex": "E6",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 101,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "take_loan",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 102,
      "loan": 0
    },
    {
      "type": "buy_train",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 103,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 104
    },
    {
      "type": "pass",
      "entity": "Belt",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "id": 106,
      "hex": "F19",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "R",
      "rotation": 4,
      "entity_type": "corporation"
    },
    {
      "id": 107,
      "hex": "G20",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "R",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 108,
      "loan": 1,
      "type": "take_loan",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 109,
      "loan": 2,
      "type": "take_loan",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 110,
      "type": "buy_train",
      "price": 100,
      "train": "2-2",
      "entity": "R",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 111,
      "type": "buy_train",
      "price": 100,
      "train": "2-3",
      "entity": "R",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 112,
      "type": "undo",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 113,
      "type": "undo",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 114,
      "type": "undo",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 115,
      "type": "undo",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 116,
      "type": "undo",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "id": 117,
      "type": "undo",
      "entity": "R",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "R",
      "entity_type": "corporation",
      "id": 118,
      "hex": "F19",
      "tile": "57-0",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "R",
      "entity_type": "corporation",
      "id": 119,
      "hex": "G20",
      "tile": "7-0",
      "rotation": 1
    },
    {
      "type": "take_loan",
      "entity": "R",
      "entity_type": "corporation",
      "id": 120,
      "loan": 1
    },
    {
      "type": "buy_train",
      "entity": "R",
      "entity_type": "corporation",
      "id": 121,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "R",
      "entity_type": "corporation",
      "id": 122
    },
    {
      "type": "pass",
      "entity": "R",
      "entity_type": "corporation",
      "id": 123
    },
    {
      "id": 124,
      "hex": "D7",
      "tile": "6-0",
      "type": "lay_tile",
      "entity": "WC",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 125,
      "loan": 2,
      "type": "take_loan",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 126,
      "loan": 3,
      "type": "take_loan",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 127,
      "type": "pass",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 128,
      "type": "buy_train",
      "price": 100,
      "train": "2-3",
      "entity": "WC",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 129,
      "type": "buy_train",
      "price": 100,
      "train": "2-4",
      "entity": "WC",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 130,
      "type": "undo",
      "entity": "Orange_Julec",
      "entity_type": "player"
    },
    {
      "id": 131,
      "type": "undo",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 132,
      "type": "undo",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 133,
      "type": "undo",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 134,
      "type": "undo",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "id": 135,
      "type": "undo",
      "entity": "WC",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 136,
      "hex": "D7",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 137
    },
    {
      "type": "take_loan",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 138,
      "loan": 2
    },
    {
      "type": "take_loan",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 139,
      "loan": 3
    },
    {
      "type": "buy_train",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 140,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "WC",
      "entity_type": "corporation",
      "id": 141
    },
    {
      "type": "lay_tile",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 142,
      "hex": "H3",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 143,
      "hex": "H5",
      "tile": "8-1",
      "rotation": 1
    },
    {
      "type": "take_loan",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 144,
      "loan": 4
    },
    {
      "type": "buy_train",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 145,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 146,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 147
    },
    {
      "type": "pass",
      "entity": "PW",
      "entity_type": "corporation",
      "id": 148
    },
    {
      "type": "lay_tile",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 149,
      "hex": "E4",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "id": 150,
      "hex": "E2",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "A&A",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 151,
      "loan": 5,
      "type": "take_loan",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 152,
      "loan": 6,
      "type": "take_loan",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 153,
      "type": "buy_train",
      "price": 100,
      "train": "2-6",
      "entity": "A&A",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 154,
      "type": "buy_train",
      "price": 100,
      "train": "2-7",
      "entity": "A&A",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 155,
      "type": "pass",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 156,
      "type": "undo",
      "user": "ggohierroy",
      "entity": "UR",
      "entity_type": "corporation"
    },
    {
      "id": 157,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 158,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 159,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 160,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 161,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 162,
      "hex": "E2",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "A&A",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 163,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "id": 164,
      "hex": "F13",
      "tile": "X00-0",
      "type": "lay_tile",
      "entity": "PSM",
      "rotation": 1,
      "entity_type": "company"
    },
    {
      "id": 165,
      "type": "undo",
      "entity": "A&A",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 166,
      "hex": "E2",
      "tile": "8-2",
      "rotation": 2
    },
    {
      "type": "take_loan",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 167,
      "loan": 5
    },
    {
      "type": "take_loan",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 168,
      "loan": 6
    },
    {
      "type": "buy_train",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 169,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 170,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "A&A",
      "entity_type": "corporation",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 172,
      "hex": "C22",
      "tile": "6-1",
      "rotation": 5
    },
    {
      "type": "undo",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 173
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 174,
      "hex": "C22",
      "tile": "57-2",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 175,
      "hex": "B21",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 176
    },
    {
      "type": "take_loan",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 177,
      "loan": 7
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 179,
      "train": "2-8",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 180
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 181
    },

**Comment by steve-yu** [comment]
also happening in this game: https://www.18xx.games/game/13593

**Comment by jenf** [comment]
Perma https://www.18xx.games/game/13593?action=317
