### ISSUE TITLE
1889 game (ID: 13048) not able to complete OR, get "unknown keyword: : settings" error at the top

### ISSUE THREAD

**Issue by pratman99** [tobymao/18xx#2059]
https://www.18xx.games/game/13048?action=392

**Describe the bug**
In  OR, trying to complete, and it seems to complete,  but when I exit, my full OR hasn't been completed. Get a "unknown keyword: : settings" error across the top in pink.

Regards,
Pratik

**Comment by tobymao** [comment]
temp issue
