### ISSUE TITLE
1817: Companies falling into acquisition during M&A should not be acquirable

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2061]
https://www.18xx.games/game/13593 is the game and EJE is the company that went into acquisition.

It fell into acquisition during the M&A round so it shoudl not be offered for acquisition.  I imagine liquidations might also be affected by this.

**Comment by jenf** [comment]
From rules

If a company moves into the gray acquisition area of the
stock market due to loans taken during an acquisition or
conversion, the company is not put up for acquisition
during this M&A round, and may not participate in further activity during this M&A round.

**Comment by jenf** [comment]
Action https://www.18xx.games/game/13593?action=256
