### ISSUE TITLE
18LA - drafting LA Title is broken in multiplayer games

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#2062]
reproduced locally in a multiplayer game, but it seems to work as expected in hotseat, but here's the hotseat JSON anyway - https://gist.github.com/michaeljb/a56ee4a96c26964a182b17f36b117076

**Comment by michaeljb** [comment]
another sample game - https://www.18xx.games/game/13864

**Comment by philcplaygames** [comment]
Experiencing the same issue in game id:13959 when I attempt to draft my tile I get the following error message:
"undefined method 'name' for nil:NilClass'
