### ISSUE TITLE
joined game but didn't end up in game

### ISSUE THREAD

**Issue by th3tick** [tobymao/18xx#2075]
https://www.18xx.games/game/14012

I joined this game earlier today but once others joined later, I didn't end up in the actual game once it started.

**Comment by perwestling** [comment]
Are you sure you wasn't just kicked out of the game by the one that had created the game?

**Comment by th3tick** [comment]
Well, they said they didn't.  They instead abandoned that game and had to start a new one that I could again join.

**Comment by jenf** [comment]
I doubt we'll be able to action this ticket without it reproducing locally.
