### ISSUE TITLE
1817 show future interest

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2083]
Current interest is shown on The Bank entity card. It would be nice if future interest was shown as well.

e.g. at the beginning of OR2.2, the interest rate was $15; since then 7 loans have been taken and the new interest rate can be projected to be $25. Both current interest ($15) and future interest ($25) should be shown on The Bank entity card.

**Comment by joshyboy20k** [comment]
The interest rate is very important to see at all times. Perhaps it should have its own card that is shown on the Game tab.

**Comment by SmithInMN** [comment]
A very small part of me wants a separate graphic or tab showing the loan board from the physical game.

The larger and more pragmatic part of me would be happy to just the projected, as the current number of loans would determine it, interest rate just as a parenthetical figure after the current interest rate.  That's a much quicker and easier implementation that an entire new graphic.
