### ISSUE TITLE
18MS: Cannot place token if having token ability

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2086]
Below is the critical situation for game 12680.
GMO is doing OR3. At start of OR3 GMO is connected to New Orleans.
GMO has just placed a tile in H8 but when trying to put a token in New Orleans an error message of 
  GMO cannot lay token on I1-0-0.
Refresh does not help.

But if GMO selects the Meridian and Memphis Railway ability it can now lay the token in New Orleans.

![image](https://user-images.githubusercontent.com/2631151/97457282-e625cf80-1939-11eb-8491-960e49d60460.png)

https://gist.github.com/benjaminxscott/d70f5bc11cd4e9fcbfd90d6dc1791b45

**Comment by perwestling** [comment]
The reason for the error is that GMO only have $35 left, and the token cost $40. If using the ability the tokening is cheaper and then GMO can afford it.

So I think the error message can be improved.

**Comment by bentziaxl** [comment]
no longer an issue, when a company doesn't have enough for a token, it skips token placement
