### ISSUE TITLE
Allow programmed moved for stock rounds/merger rounds

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#209]
rr18xx has a nice stock round automation which would be useful to improve upon especially when playing async games. It'd be nice to be able to fill in your request at any time during the stock round.

I think a lot of the different conditions can be merged into a 'Stop' condition whereby it'll stop if it thinks that the player might want to consider their move more. This would be better than getting users to choose their stop conditions as it may make them regret their decision.

- Buy to Float
- Buy to Float with Stop
- Buy n from Bank with Stop
- Buy n from IPO with Stop
- Pass once
- Pass until OR with Stop

AutoStop for both pass and buy stops when
- Someone sells something in a company i'm invested in
- I can now buy a share, I couldn't previously
- Someone is close to buying a company out from under me.

Buy would also stop when:
- Any company has changed price (I may value company B over company A)
- A new company has floated
- Someone has bought shares in the company I am buying
- 
Implementation plan for Programmed moves
### 'Auto' actions
- [x] Underlying support for adding extra actions

### Underlying support
- [x] Add actions to add programmed move to be added/removed/modified
- [x] Move logging to individual player view (why program deactivated)
- [x] Determine how best to de-arm the programmed moves when moving to next round

### Future
- [x] UI work
- [x] Buy to float (only on first round)
- [x] Merger/float auto-pass on convert, merge, for sale for 1817/1867/1861 etc
- [x] Disable Merger option in stock round
- [x] Add asset tests
- [x] Rename to 'Auto' rather than Async
- [x] Add fixture tests for auto actions
- [x] Make it clearer that Programmed actions are active for a player
- [x] Buy till float unless shenanigan
- [x] Pass unless shenanigan
- [x] SR for 1822
- [x] SR for 1817/1861/1867
- [ ] Buy till custom

**Comment by jcoveney** [comment]
So I've thought about this a bit. I agree that there are reasonable defaults... I feel like the dream would be a little sublanguage that lets you query basic game state and build a "should I stop or not" based off of that. Then we can do whatever we want. That said, not sure if toby is interested in maintaining something like that :) And it may be overkill when there are probably some sane defaults that cover most use cases (eg what is in the OP!)

**Comment by benjaminxscott** [comment]
FWIW rr18xx [has something like this](http://www.rr18xx.com/cgi-bin/cmd_auto_order.cgi?gname=JJJS_1) as reference for the options

(Personally I'm fairly neutral on the feature, agree it's useful but seems fiddly)

**Comment by jcoveney** [comment]
There is definitely an 80/20 here. I find that "auto float" and "pass unless someone sells" get you like 90% of the way there, and are massive wins for keeping games moving. After that, things in the OP would be really nice...stuff like "if anything happens with this company I care about, wake me up." Lack of that often keeps me from autopassing on rr18xx. But auto float, autopass, and pass unless someone sells are really great.

**Comment by ChrisTheCat** [comment]
For some games, PUO (pass unless overbid) would also be a great option to have.

**Comment by toastmastergeneral** [comment]
I want to support a basic level implementation like jcoveney mentioned. "buy until float" and "pass until sale" for the SR alone will make async stock rounds significantly faster.

**Comment by jenf** [comment]
This is kind of dependant on #684

**Comment by jenf** [comment]
Will likely implement this in three phases as I'm worried it'll go wrong implementing it all in one.
* Buy to float on first round
* Pass unless shenanigan
* Buy unless shenanigan

**Comment by yraelrocks** [comment]
Another option which might suit is having a way to set oneself to a specific state, purely so others can act on ones behalf. Currently you Can type a message in chat but that relies on the other players remembering what each other are currently set at. Having a way to see quickly what someone is set at (ie auto pass/auto float) would be helpful in the short term

**Comment by tom-blight** [comment]
I logged on to make this request, but in addition for the M&A rounds in 1817. This could have some real impact on the length of games! 

Again, rr18xx has some good tools here, could be used as a template. I don't have any games running there currently so can't check options. 
- (for each company player controls) skip/skip unless another merger or conversion/convert
- (for each company player controls) skip/skip unless another friendly sale/initiate friendly sale

**Comment by jenf** [comment]
Initial version is now deployed with support for buy to float

**Comment by jenf** [comment]
Per suggests a 'Just run routes' async option

**Comment by jenf** [comment]
Shenanigan protection is in review, just the custom buys to close this off:

Buy till custom needs a few options

Number of shares and to float
Share preference

- IPO only
- Market only
- IPO preferred
- Market preferred
- Cheapest
- Biggest?
