### ISSUE TITLE
[18LA] cannot use Pacific Maritime's power in E8

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#2093]
[game id (note this this game is not stopped on the exact action)](https://www.18xx.games/game/12891)

[repro json stopped at the specific action](https://github.com/tobymao/18xx/files/5454717/LA.json.txt)

When buying in the Pacific Maritime, its reserved token in E8 goes away, which means it can never be placed by the owning company

**Comment by michaeljb** [comment]
Even though the reservation goes away, the Pacific Maritime can still be used to put a token there, it's just that other corporations can also place a token there, if they can reach the spot and it's still open for them to do so.

Regardless of the reservation, to use the Pacific Maritime, you have to click on "Pacific Maritime (ELA)" next to "Abilities", then while the text is expanded you can click on the Long Beach spot and ELA will get the free, extra token there.

**Comment by benjaminxscott** [comment]
Huh earlier I could swear it didn't let me put the token down when I use the private power as described above

Seems to work now though
