### ISSUE TITLE
[18MEX] Cannot buy 10% NdM with the both 5% in market

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2097]
Game link: https://www.18xx.games/game/14188?action=611

Both 5% shares of NdM are in the market, along with a 10% share. I (auzzy) want to buy the 10% share. I only have 12 certs out of the 15 cert limit, so I have space. I also have plenty of money, so I can afford it. However, when I click on NdM, I am only presented with a single button labeled "Buy Market Share". When I buy the share, it purchases a 5% share (as noted in the log at the link above).

**Comment by jerryyeti** [comment]
https://www.18xx.games/game/13895?action=911

I have the opposite problem.  When I buy I can *only* buy the 10% and do not have the option to get the 5%.

**Comment by perwestling** [comment]
Have now made an attempt to fix both these problems.

Before correction (2nd problem):
![image](https://user-images.githubusercontent.com/2631151/97777696-3edfad00-1b72-11eb-868f-6641a60f24d0.png)

After correction it is now possible to buy 5% or 10%:
![image](https://user-images.githubusercontent.com/2631151/97778494-de536e80-1b77-11eb-9674-1bcfd5e22042.png)

In case the buyer owns 5.5 shares of NdM the correction now makes it possible to buy the 5% share:
![image](https://user-images.githubusercontent.com/2631151/97778651-e19b2a00-1b78-11eb-8765-0907f1353e35.png)

And when there is just one type of percentage in the market, the percentage is not shown on the buy button:
![image](https://user-images.githubusercontent.com/2631151/97778721-66864380-1b79-11eb-9639-81725c080a52.png)

**Comment by perwestling** [comment]
The correction was reverted and I have problems with my development environment so I have not been able to fix the problem.
