### ISSUE TITLE
18MEX NdM trade in shares shown twice on charter

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2103]
<img width="339" alt="Screen Shot 2020-10-29 at 8 25 15 AM" src="https://user-images.githubusercontent.com/8732435/97594951-6f7fe500-19c0-11eb-914c-136b518bb0fe.png">

Trade in shares are displayed twice. I suggest removing the lower (second) instance: "Trade-in shares: 10%"

**Comment by perwestling** [comment]
@ChrisTheCat So how do you know, as a player, that it is a 10% that is trade in, and not two 5%?
By removing the upper Trade-in line that wont be a problem.

**Comment by ChrisTheCat** [comment]
That problem affects more than this use case, as currently if Spaul owned both 5% shares there is no way for players to know that either. And if there are 20% trade in shares, how do players know that's 1x10% + 2x5%. Display of unusual percentages is in this issue https://github.com/tobymao/18xx/issues/1630.

Having "Trade-in 2.0" and "Trade-in shares: 20%" on the charter doesn't solve the problem of issue 1630. It's duplicate information in either case.

**Comment by perwestling** [comment]
@ChrisTheCat: In case of 18MEX the players knows that the 20% trade-in is 1x10% + 2x5% as that is specified on the charter. Here is how the NdM charter look from the beginning:

![image](https://user-images.githubusercontent.com/2631151/97645088-4c027c00-1a4c-11eb-9fbb-dde5ef67b1c6.png)

Removing the upper part will decrease the information.

If the problem of issue 1630 is solved it will be a different situation.
