### ISSUE TITLE
18MS: Tile laying private ability skips token lay.

### ISSUE THREAD

**Issue by JLamkin** [tobymao/18xx#2105]
In 18MS with the two privates that give you either 1 or 2 extra tile lays. I found a bug with order of operations.

If in the first OR you lay both of your tiles, than buy in the private and lay the extra 1 or 2 tiles it skips the tokening step.
However, if you buy in the private than lay both of your tiles, than lay the extra 1 or 2 tiles it gives you the option to lay the token.

Not a huge bug but thought I would point it out.

**Comment by crericha** [comment]
May be fixed by the special_track/tracker rework done for teleport. Needs to be tested.

**Comment by michaeljb** [comment]
I think that for this to work, we need the track step to block not only for abilities the active corporation currently has, but also if the active corporation could possibly buy a company that has a tile lay ability with `when: 'track'`.
