### ISSUE TITLE
1817: SR Order should enforce Sell/Short and then Buy

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2108]
During an SR, players must first sell any shares and then short any shares, and then buy.  Currently, the game allows buy, then sell/short.

https://www.18xx.games/game/13593 example game

**Comment by ChrisTheCat** [comment]
Note that it's actually short "one" share, not "any shares."

Also, there's no particular reason to require sales before shorts, as neither changes the price of the corporation. The main thing is to prevent someone from selling or shorting a share they just purchased in the same action.

**Comment by jenf** [comment]
"If acting for himself, he may perform any or all of the
following actions in this order:"
