### ISSUE TITLE
18MEX overlapping icons and names

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2113]
The yellow Veracruz tile has the word "Veracruz" overlapping the symbol "V." Similarly Mexico City overlaps MC, Mazatlan overlaps M, etc. Some of the revenue values overlap the city names as well, as shown here:

<img width="194" alt="Screen Shot 2020-10-29 at 9 10 16 PM" src="https://user-images.githubusercontent.com/8732435/97659065-36308f00-1a2b-11eb-97f6-2dd4d934ac75.png">

**Comment by perwestling** [comment]
@ChrisTheCat - is the improvement enough? If so I think this can be closed.

**Comment by ChrisTheCat** [comment]
Works for now.
