### ISSUE TITLE
[1817] - Player bidding on new companies an amount s/he cannot pay

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2117]
It happened in this game https://www.18xx.games/game/13922

The player Merlo Piccante has 0 cash and two privates, one with face value 120, one with 30, and he was able to bid 135, winning the auction, but now he's stuck, because his bid power is either 120 or 150, no inbetween.
He souldn't have been allowed to bid anything else but 120 and 150.

**Comment by jenf** [comment]
Relevant action
https://www.18xx.games/game/13922?action=122

**Comment by jenf** [comment]
In addition, if there is only one valid selection of companies to fold in it should be automatic.
