### ISSUE TITLE
[18Mex] incorrect number of town tiles

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#2118]
E: error see below

**Comment by BellmakerSA** [comment]
Correction that was legal upgrades, should be 2 of each town (still only 1 474)

**Comment by BellmakerSA** [comment]
![CD6E47D3-9506-469C-AF3B-0F254C66D8D4](https://user-images.githubusercontent.com/73144084/97714454-8fcea300-1a97-11eb-8776-c5e6166c1290.png)

**Comment by perwestling** [comment]
Well spotted. When checking the remaining tiles it turn out that the green "chicken feet" also has the same error (1 instead of 2).
