### ISSUE TITLE
[1817] 5-share company start token purchase should be automatic

### ISSUE THREAD

**Issue by KenKuhn** [tobymao/18xx#2119]
In Game 13568, two 5-share companies were started in SR2 and their tokens weren't automatically purchased. We were allowed to leave the stock round without buying the tokens, which is against the rules.

**Comment by jenf** [comment]
Nope it's not, it's technically a player choice. The UI warns you that it will may cause liquidation on the pass button.

'Payment for these station markers must be made prior to
the end of the stock round. Paying for these station markers is not an action. Companies may take loans to pay for
the initial station markers. Taking loans must be a company action. If the stock round ends without the
company purchasing the required station markers, the company is placed in liquidation.'
