### ISSUE TITLE
1817 abilities shown during M&A round

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2122]
<img width="567" alt="Screen Shot 2020-10-30 at 1 57 42 PM" src="https://user-images.githubusercontent.com/8732435/97756488-2f9c2900-1ab8-11eb-8d7f-8c92c50c1d49.png">

These abilities should not be shown during the M&A round.

**Comment by PedroRCSequeira** [comment]
They should also not be shown outside that company turn, right? for instance coals from another of your companies

**Comment by ChrisTheCat** [comment]
Correct
