### ISSUE TITLE
sort new games so that „joinables“ come first

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#2129]
Actual I see all non-private new games that are not started. Some of them are already complete and I cannot join them. As I search for „joinable“ games they should come on the first pages.

**Comment by perwestling** [comment]
I think #782 could fix that. 'Joinable' could be yet another filtering possibility.

**Comment by perwestling** [comment]
Actually, that was one of the suggestions in the comment part of #782.

So I will close this suggestion as it is a duplicate. But yes, it is a good suggestion.

**Comment by Herbert62** [comment]
Thank you - I did not recognize #782
