### ISSUE TITLE
Error message when buying train

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2131]
<img width="719" alt="Screen Shot 2020-10-31 at 7 30 18 AM" src="https://user-images.githubusercontent.com/8732435/97781814-11cbd400-1b4b-11eb-9160-fa9dfb6454aa.png">

MC gets this error when trying to buy the 5 train.

https://www.18xx.games/game/13766

**Comment by perwestling** [comment]
I think this is same as #2096. That one has been fixed, and merged, but not deployed yet.

**Comment by perwestling** [comment]
Code has been updated. And MC has bought a 5 train in the game.
So it seems the fix helped.

Thanks for the issue.
