### ISSUE TITLE
Reset turn (better undo)

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2135]
Sometimes, when undoing, you end up in previous player turns: how about adding a "Reset turn" that would avoid you clicking many times undo if you want to just reset your turn?

**Comment by tobymao** [comment]
dup of #2611

**Comment by ChrisTheCat** [comment]
LOL, you closed the earlier (lower number 2135, dated Oct 31) because it is a duplicate of 2611 dated Dec 10...

**Comment by tobymao** [comment]
yea because the other one is a better idea

**Comment by ChrisTheCat** [comment]
I disagree. The other suggestion requires a player to click "undo" over and over and over until they get to the point where they want to "reset to here." My suggestion avoids needing multiple undo clicks. And in games like 1817, each undo can be 3-4 seconds of waiting!

**Comment by ChrisTheCat** [comment]
and even if it isn't "undo" over and over, it's "back one step" over and over - and each "back one" in the history can be 2-3 seconds or more per click.

**Comment by tobymao** [comment]
no, the plan would be to click on a line in the log, and then click undo until here, two clicks to go back in time anywhere

**Comment by ChrisTheCat** [comment]
The other suggestion says nothing about "clicking on a line in the log" - it talks about using the history buttons.

**Comment by tobymao** [comment]
sometimes i read things in my mind and then infer what i'm gonna do with it, you're right it aint optimal!
