### ISSUE TITLE
Game 212 stuck, wrong player

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#214]
In game 212, Bruce is the first player. He placed a bid. Now the 18xx.games home page correctly shows that it is Pete's turn. However, when any of us enter the game, it shows that it is still Bruce's turn and there's no indication he placed a bid.

**Comment by tobymao** [comment]
i don't see an issue, it's daroj's turn

ChrisShaffer bids ¥35 for Mitsubishi Ferry
PeteC66 bids ¥65 for Dougo Railway
beardbru bids ¥45 for Ehime Railway
-- Phase 2 (Operating Rounds: 1, Train Limit: 4, Available Tiles: Yellow ) --

**Comment by ChrisTheCat** [comment]
Thanks. It unstuck itself somehow. I wish I had taken screenshots.
