### ISSUE TITLE
[1817] During corporation auction show on log when a player is skipped because they don't have money

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2140]
https://www.18xx.games/game/14513?action=88

It would be nice to get a message on the log that the players automatically passes because they don't have money

**Comment by jenf** [comment]
This is a generic kind of problem with how the auctions are done.

**Comment by jenf** [comment]
```
Player 2 bids $400 for A&A
Player 3 passes on A&A
Player 1 passes on A&A
Player 2 wins bid on A&A for $400
```

It does so
