### ISSUE TITLE
[1817] Show company list instead of player list during the acquisition round

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2147]
During the acquisition round we see the list of players with the highlight jumping around. I think it would look better if we saw the list of corporations in ascending market value, as is the order of play

**Comment by jenf** [comment]
I think both need displaying

**Comment by jenf** [comment]
In general there's a need for a second level to provide more context to the user, especially in merges.

One which is the active entity (player in this case)
One which is the 'context' entities (so active_context_entity and context_entities)

This would be displayed

Corp 1 | **Corp 2** | Corp 3
Player 1 | Player 2 | **Player 3** | Player 4

**Comment by daniel-sousa-me** [comment]
But it could show "Corp 2 (Player 3)" like in the OR. Then if we are in the middle of a bid, it switches to players, like the merger does in the buying/selling step.

**Comment by jenf** [comment]
Problem is you are always in the middle of a bid. It'd also be useful to know what corps are coming up

**Comment by daniel-sousa-me** [comment]
Well, I wrote acquisitions because it's the name of the round, but I was actually thinking about friendly sales.

For liquidations and acquisitions having both lines would be very good, but just having the players is also ok
