### ISSUE TITLE
1817 Stock market should indicate par prices (ie max 200)

### ISSUE THREAD

**Issue by yraelrocks** [tobymao/18xx#2155]
1817 Stock market - par prices indicated (ie max 200).

**Comment by perwestling** [comment]
Can you write some more, describe what the problem is?

**Comment by yraelrocks** [comment]
So there’s a range of prices which you can par a company at, but that’s not indicated on the stock market.

**Comment by yraelrocks** [comment]
50 being the lowest & 200
Being the highest par price
