### ISSUE TITLE
[18 Los Angeles] Can’t return to Info tab

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#2156]
After navigating away from the Info tab in 18 Los Angeles, I cannot return to the Info tab again.
 (e.g., attempt to select Map -> Info -> Tiles -> Info)

I can reproduce the issue in all of my current 18 Los Angeles games.  I have not seen it occur in other titles.

Observed in Safari on IPad.  Have not yet tried other browsers or devices.

**Comment by Craig1830** [comment]
Reloading the page allows the Info tab to be displayed again, but then the problem recurs after navigating away.

**Comment by ChrisTheCat** [comment]
Replicated in several games. To reproduce:

Open game, click Spreadsheet, click Info (works), click Spreadsheet, click Info (fails). Continues to fail until a browser refresh.

**Comment by tobymao** [comment]
@michaeljb this was due to map!
