### ISSUE TITLE
[18mex] Misspelling of Treasury in log

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#2158]
The log misspells Treasury as "treasurey" during the minor company merge. 

eg: https://www.18xx.games/game/14139

![Screenshot from 2020-11-01 10-19-06](https://user-images.githubusercontent.com/26125362/97807628-df47d700-1c2f-11eb-9dde-5c846dfabe6e.png)

**Comment by perwestling** [comment]
Thanks
