### ISSUE TITLE
Indicate which player has Priority Deal

### ISSUE THREAD

**Issue by PilotBob** [tobymao/18xx#216]
Some indicator in the player section of which player has priority deal. Currently, you have to look through the log to find that information.

**Comment by tobymao** [comment]
the player order indicates that

**Comment by tobymao** [comment]
this is duplicate

**Comment by PilotBob** [comment]
When we are on the Game tab, in and OR it doesn't show player order, it shows corp order. Where are you talking about? Is the player page in Priority order?

**Comment by dfannius** [comment]
Yes, the player page is in priority order.
