### ISSUE TITLE
Make it more obvious when you are in hotseat mode

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2167]
Sometimes people clone the game and forget they are in a hotseat clone and don't understand why the game isn't updating.

Maybe we could make something a different color or add some header or something so that the user notices that something is different when they are not in a "real" game

**Comment by ventusignis** [comment]
I have a prototype for something, would this be acceptable?
![image](https://user-images.githubusercontent.com/2993555/102656949-c5604600-4142-11eb-9d7f-8c0cbbac3960.png)

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/102692824-02c8e000-41e4-11eb-8377-115465d56903.png)

**Comment by daniel-sousa-me** [comment]
That's very nice ^^
