### ISSUE TITLE
18MEX merger round should show players, not corporations

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2171]
In the screenshot below, the NdM just purchased the 5 train, triggering the merger. Priority order is thedaber (NdM + PAC) -> hobie (MC + UdY) -> Chris (MEX + TM) -> winn1098 (Chi). The merger order is hobie (MC or UdY) -> Chris (MEX) -> winn1098 (Chi). The game is asking in the right order, but the row (under history, above undo/decline buttons) is corporations in operating order. That row really should show the players, as I've described them here, and not the corporations.

<img width="1333" alt="Screen Shot 2020-11-02 at 11 18 21 AM" src="https://user-images.githubusercontent.com/8732435/97909511-336cbd00-1cfd-11eb-8db7-7115fbfad829.png">

**Comment by perwestling** [comment]
Player order is thedaber, Hobie (controlling UdY & MC), ChrisShaffer (MEX), win1098(CHI), and SPM not floated
Merge should there for be UdY or MC, followed by MEX, followed by CHI, followed by SPM
Game log shows:
  Merge candidates: UdY,MC,MEX,CHI,SPM
In turn it shows UdY, MC, MEX, CHI as the active entity (underlined) and ask the controlling player if they want to merge or not.
If all decline SPM is automatically chosen.

The operation order is displayd as we are in operating round.

If we change the order, how would you tell what the operating order is? Is this not important for your decision?

**Comment by perwestling** [comment]
Would it be better if the logged line would be:

Merge decision: Hobie (UdY,MC),ChrisShaffer (MEX), win1098 (CHI), auto/thedaber (SPM)

**Comment by ChrisTheCat** [comment]
Operating order is not really relevant at all.

**Comment by ChrisTheCat** [comment]
yes, that would be great.

**Comment by ChrisTheCat** [comment]
Except that SPM isn't eligible, because thedaber owns NdM

**Comment by perwestling** [comment]
If showing players, which player should be shown for SPM? (None I suppose as it is merged automatically)

If so the NdM player would only be shown if there is a choice among non-floated.

Would the players understand that SPM will be automatically merged?

**Comment by ChrisTheCat** [comment]
Perhaps this would be best:

Merge decision: Hobie (UdY,MC), ChrisShaffer (MEX), win1098 (CHI), automatic (SPM)

**Comment by ChrisTheCat** [comment]
If there were two corporations unfloated (hard to imagine that happening, but it's possible), then:

Merge decision: Hobie (UdY), ChrisShaffer (MEX), win1098 (CHI), automatic (SPM or MC thedaber decides)

**Comment by perwestling** [comment]
As can be seen, this is not a Merger round (as in 1817) but part of the Operating round.
This would possibly mean a larger redesign to incorporate the possibility of introducing a subround of another round.
Have not looked into that.

So the question is if it is worth the effort?

Anyway, have now pushed up an improvement of the log message which I think might be good enough at the moment, but the issue can remain as a candidate for anyone who want to give it a go with handling subrounds.

**Comment by jenf** [comment]
Adding a mechanism to override turn order, it now looks like
![Screenshot from 2020-11-13 18-12-45](https://user-images.githubusercontent.com/71923/99106360-07deb200-25dc-11eb-9e81-e3e4506647cf.png)

**Comment by ChrisTheCat** [comment]
Looks great.
