### ISSUE TITLE
[1817] Increase cert limit after bankruptcy

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2174]
I'm sorry this is not on the main website. When we started playing the mines were broken, so we played in an old commit in a improvised server. To import the game to your machine, you should check out commit 45f89361

http://daniel.sousa.me:9292/game/10

A player went bankrupt, but the cert limit stayed in 13.

**Comment by jenf** [comment]
7.4 ' The certificate limit
is increased to the number allowed based on the current
number of players remaining in the game.'
