### ISSUE TITLE
[1817] Problems with the 10th short of a company

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2175]
I'm sorry this is not on the main website. When we started playing the mines were broken, so we played in an old commit in a improvised server. To import the game to your machine, you should check out commit 45f8936

http://daniel.sousa.me:9292/game/10?action=1502

WT here has only 9 shorts, but I couldn't do the 10th short

**Comment by jenf** [comment]
Technically there are 10 shorts in existence.
 [<Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>, <Share: WT -10%>]

**Comment by jenf** [comment]
Side effect of bankrupcy bugs
Manu sells -1 share WT and receives $-200

**Comment by jenf** [comment]
covered by #2176
