### ISSUE TITLE
[1817] Short in the market via bankruptcy

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2176]
I'm sorry this is not on the main website. When we started playing the mines were broken, so we played in an old commit in a improvised server. To import the game to your machine, you should checkout commit 45f8936

http://daniel.sousa.me:9292/game/10?action=1099

A player who help shorts for PLE went bankrupt and that short was placed in the market. At the beginning of the SR the bank should have bought a share from the treasury to settle the short.

The player could also buy a share from the market, leaving the market with 2 shorts

**Comment by jenf** [comment]
Two bugs
1) Shorts don't cancel when getting sold
2) Bank doesn't try to clear the shorts at start of stock round

**Comment by jenf** [comment]
Bankruptcy occured at daniel.sousa.me:9292/game/10?action=983
