### ISSUE TITLE
1817 entering liquidation during M&A round

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2179]
The rules are clear that corporations that move into the grey acquisition area during an M&A round are not auctioned during that same round. They are silent about what happens to corporations that move into the red liquidation area during an M&A round (which can happen if a liquidation drives someone bankrupt).

Craig Bartell, the designer, has stated several times that his intent was that the M&A round auction order is set at the beginning of the M&A round, and that companies that enter liquidation during an M&A round are not auctioned until the next M&A round (i.e. they sit in limbo for the current M&A round).

As I noted, the rules do not address this topic, so I think it is fine for 18xx.games developers to agree on which interpretation they would like to use. However, we should document that choice in the implementation notes in the wiki. And it should be an actual choice by the developers, and not something that happened because we copied the rr18xx model, or simply just did it that way.

According to reports (which I have not yet verified) 18xx.games currently implements the "auction them this round" version.

**Comment by jenf** [comment]
I'd probably agree with Craig Bartell, please provide a link to him stating his interpretation.

**Comment by ChrisTheCat** [comment]
Here's a link to a post Craig made on the dtg-proto email list in 2011. I don't think any of his messages are on a public web site. I also have a couple of private emails from him on this topic.

https://groups.google.com/g/dtg-proto/c/wmNYzGWNyhY/m/6ggNOx-xTjYJ

It says:

> If a player goes bankrupt during an M&A round, thus dumping some
> companies in liquidation, they are liquidated the following M&A round. 
> The intent of liquidation and acquisition is they must start the M&A
> round in liquidation or acquisition.  This also means those companies
> newly placed in liquidation will not run during the next Operating round.
> 
> Companies should be placed in liquidation in operating order.  They are
> then liquidated in reverse of the order they are placed in liquidation.

Also, in the slack someone said they think rr18xx delays the liquidation to the following M&A round. I don't use that site so can't check how they actually implemented it.

**Comment by jenf** [comment]
It fits in line with other rules, we don't implement it properly.
Will update faq when done.
