### ISSUE TITLE
No training wheels variant

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2180]
We have been putting more and more nice information on the page to help players make decisions. Maybe it would be interesting to have the option to disable all these at the game level and show to everyone "only" the information that would be available in the board on a f2f game.

This will be even more relevant if we ever have auto routing, because it is clear that some people prefer that players have to figure the routes out themselves.

**Comment by tobymao** [comment]
i don't think this is a good idea
