### ISSUE TITLE
1817 5-share companies floating when not sold out and tokens not bought automatcally.

### ISSUE THREAD

**Issue by Antivamp** [tobymao/18xx#2181]
The 5 share companies we started floated at the end of the stock round with 60% sold. The tokens had to be bought and should be bought automatically.

**Comment by daniel-sousa-me** [comment]
In 1817 the companies always float when they are pared, regardless of the amount sold

**Comment by jenf** [comment]
Nope, it is a player option to buy tokens. See the wiki https://github.com/tobymao/18xx/wiki/1817

**Comment by Antivamp** [comment]
I don’t mean float as is start. I mean float as in they start at $200 and move to $220 with only 60% sold.


Sent from my iPhone

On Nov 3, 2020, at 7:59 AM, Daniel Sousa <notifications@github.com> wrote:

﻿

In 1817 the companies always float when they are pared, regardless of the amount sold

**Comment by daniel-sousa-me** [comment]
Oh, I've also seen that happening, but I think Jen already fixed it.

Can you post a link to a game where that happened?
