### ISSUE TITLE
[1817] It's possible to end up with negative cash after choosing subsidiaries

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2182]
This can happen if the player has 2 privates where one of them is enough to pay for the bid, but other isn't and the 2 of them together is too much. If the player chooses the one that is not enough, the game sees that the company can't use the other and automatically passes leaving the player with negative cash.

https://www.18xx.games/game/14650?action=98

**Comment by jenf** [comment]
Woo, bad bug :(

Looks like I need to add another check in
