### ISSUE TITLE
1870 Special Rule Summary

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2185]
### Stock market
- [x]  Ledge

### Privates
- [x]  Blocked river
- [x]  Cattle token
- [x]  Port token
- [x]  Weird river discounts

### Map
- [x] Mark hexes with special tiles

### Stock Round
- [x] Price protection
- [x] Redeem share
- [x] Reissue shares
- [x] Certificate limit depending on the number of companies
- [x] Buy privates from other players

### Operational round
- [x] Connection runs

**Comment by ventusignis** [comment]
Does adding a way to represent the destinations on the map need to be added to this? 1856 needs that ability too

**Comment by daniel-sousa-me** [comment]
Yes

I think I'll just use tokens. Every corporation has a token on the map and a reserved station on the charter. When they reach the destination the token disappears and can be replaced by the station

**Comment by ventusignis** [comment]
I'm curious how having tokens outside of a city will work in the 18xx.games framework

**Comment by daniel-sousa-me** [comment]
Normal tokens are usually like that. Stations outside the reserved spots is already implemented for the 18LA variant. I haven't checked the code, but I see no reason why it could be a problem.

**Comment by ventusignis** [comment]
Ah, the 18LA variant must be new, I just toyed with that. I imagine you still want a small icon or something similar on the hex to indicate this is a destination for one of the corporations and also a way to indicate that the destination token is a doubler

**Comment by daniel-sousa-me** [comment]
Yeah, it's a new variant. I only played with it once, I actually got the private. But didn't really have a use for it, so I don't know what it looks like.

Ah, didn't think about that because on the board they are indistinguishable. But a simple border (maybe thicker, maybe a different color) does the trick

**Comment by daniel-sousa-me** [comment]
The small icon can be the same as the tokens for coal/bridges/ports/..

**Comment by perwestling** [comment]
In 18AL the Destination is represented as an ability on the corporation charter. It is called Historical Objective in that title.
It is not shown on the map. 

Using an icon for it would be possible but it would be a bit crowded in Birmingham as there are terrain, label, mining icon, city name. Adding three destination icons to that hex might therefor be a bad idea ;-)

But maybe a general, small, destination icon, that just signals that someone has this as destination? And keep the details on the chater.

That could work in 18AL, 1822, 1856, 1870, ...

**Comment by ventusignis** [comment]
The destinations aren't printed on the map in any of the forms of 18AL I can find, so in that game's case of Birmingham, omitting it from the map should be fine

As far as "small destination icon" is the way 18xx-maker does it good?
![image](https://user-images.githubusercontent.com/2993555/100238474-3e7ecb80-2efe-11eb-8479-71f9b82d1d10.png)

I don't have a picture available at the moment, but the games 1891 & 18NK uses stacked wide rectangles to represent destinations and it allows to compactly have multiple destinations on one hex

**Comment by daniel-sousa-me** [comment]
Thank you very much! I had no idea this was already implemented and was going to do duplicate work

Yeah, I was thinking about something like that

**Comment by daniel-sousa-me** [comment]
I've finished implementing everything. There are no PRs because I have already too many pending PRs and now I'll need the time to break it down (and do some more testing).

The current version is here: https://github.com/daniel-sousa-me/18xx/tree/1870
