### ISSUE TITLE
1817 Liquidation & debt visuals

### ISSUE THREAD

**Issue by yraelrocks** [tobymao/18xx#2186]
Currently it’s not very clear if a company is in liquidation (apart from in the market tab).

Could it be possible to highlight a company in liquidation? May change the colour graphics to red or something on the game tab? Especially if a player is about to pay out when they could withhold and stop the liquidation. Saves big rewinds. I know it’s an unforgiving game but obvious blunders like that can be avoided. 

Also I’d suggest making the interest red if the company doesn’t have the funds so it’s more apparent.

On rr18xx it also includes a value called Debt margin, which shows how much the company would have if you took max loans less interest for all loans. Which gives you an idea of how close to the line you’re driving.

debt margin = company cash + 100*(loans remaining) - (size * loan fee)

**Comment by jenf** [comment]
Yeah, I was thinking about this last night. Will address some if not all after bugs are fixed

**Comment by jenf** [comment]
Colour now changes if in liquidation or acquisition

To do:
* Set interest to red if corp money < interest owed
* Add Buying Power (how we refer to 'debt margin')
