### ISSUE TITLE
Make it clearer when an ability is activated

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2190]
Many privates bring abilities into the game, which can be activated during the company operation turn. I think it should be clearer which abilities are activated and which aren't, because the first times I thought clicking on the name just had the effect of showing the description. I think that it should be showed much more clearly which ability is activated and which isn't, even a simple visual cue that doesn't go away when clicking on another abilites (if it's possible to activate more abilites simultaneously), like a toggleable button or something. I'd also consider removing the effect of showing the description when you activate the abilit, since you are forced to activate the ability just to see the description, that often you can find somewhere else.

**Comment by benjaminxscott** [comment]
Does the current implementation cover this? 
(i.e. abilities are buttons now after this PR https://github.com/tobymao/18xx/pull/2534 was merged in)

**Comment by jenf** [comment]
Yep.
