### ISSUE TITLE
Make the UI more mobile friendly when browsing from mobile, make map zoomable

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2191]
While the UI automatically adapts to the type of browser and size of the screen, using the site from mobile is still extremely painful, since it shows only one "card" per row. When there are multiple company charters piled up, like in 1817, it could be useful to make the company cards smaller, so that four of them can fit where now there's just one. This could mean developing a new way to render cards when they are in "small" view, but I think that some changes need to be done to make the site more usable from mobile.
Also, it's not possibile to zoom in and out on the map, and this is clearly an issue for players browsing the site from mobile, forced to just view a small portion of the map at a time

**Comment by daniel-sousa-me** [comment]
Zoomable map is implemented. #2498
