### ISSUE TITLE
1817 Change place of loan interest info, remove bank size info

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2192]
While it is appropriate to have the total number of loans issued, the actual and the future interest rate displayed in the bank card in the entities tabs, it also makes it much difficult for players playing from mobile to find them, since they are forced to scroll through many other cards.
I think that it would make it easier to move or also display these informations in the info tab, which is much less hoarded and clearer, and would it make it much easier to parse these information.

The bank size info should be removed or just hidden, since the game has a infinite bank, so it's actually incorrect to show a very big bank size.

**Comment by tom-blight** [comment]
I second this. To add a request - a loan table would be a great visual aid to see how many loans until the interest rate changes up or down. Perhaps a cropped version of the one present on the game board, to the current row +1 & -1 row. See below. 
![image](https://user-images.githubusercontent.com/48089193/98121347-779fbf00-1eaf-11eb-9921-3346356c9abe.png)

**Comment by jenf** [comment]
It's probably better to add the 'Bank' UI onto the 'Market' pane, and add the following:

Repay 3 loans $10
Take 2 loans $20

**Comment by jenf** [comment]
Interest if 3 more loans repaid
Interest if 2 more loans taken
