### ISSUE TITLE
[1817] Create a separation between Liquidation and Acquisition

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2194]
With the stock market as is, it gives the impression to new players that it is possible to fall from acquisition into liquidation just by moving a step down.

It would be nice to have some space between than or a thicker line.

Another option could be putting the liquidation spot on the right of 600. I believe no one will think that you can go up from 600 into liquidation xD

**Comment by ChrisTheCat** [comment]
I definitely would not put it on the right.
