### ISSUE TITLE
[1817] Companies in acquisition are worth $0

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2195]
Companies in acquisition count as $40 for jumping purposes, but their value is $0 (they can't be bought sold during an SR, but for the M&A and the end game they count as $0)

**Comment by jenf** [comment]
Can you point me to the rulebook which says their value is $0

**Comment by daniel-sousa-me** [comment]
I don't think it explicitly states that anywhere, but doesn't assign them a value, either. It only says that it "is considered $40 for calculating stock movement when paying a dividend", which implies it's not $40 elsewhere.

**Comment by jenf** [comment]
I think this is the rule.

The company can be in liquidation, in acquisition, or valued from $40 to $600 per share. Shares of a company
in the liquidation or acquisition section of the stock market are considered illiquid and cannot be bought or sold.

**Comment by SmithInMN** [comment]
It seems really confusing to talk about something as having two dollar values.  It still has an assigned intrinsic value, even if the rules prevent it from being sold or from being scored at the end.  This is more about having a logical value assignment to prevent, but not devalue, a company's actions.

If I try to sell my car, it still has value, even if nobody wants to buy it.

**Comment by daniel-sousa-me** [comment]
I agree, but that intrinsic value is $0, because that's what you get at the end of the game. The $40 figure is not supposed to be how much it's worth, just how much dividend is required for it to go up.

**Comment by giovandc** [comment]
To be fair, the rulebook states: «The gray acquisition area is considered $40 for calculating stock movement when paying a dividend». This doesn't mean that companies in acquisition have a stock value of $ 40. Interpreting _a contrario_, companies whose value is in the acquisition area, outside of the scope of paying dividends, **don't** have a stock value of $ 40.
Arguing from a mere gameplay point of view, it's misleading to see companies in acquisition having a stock value of 40, and forces you to check if it's _actually_ $ 40, or just in acquisition.

**Comment by daniel-sousa-me** [comment]
> it's misleading to see companies in acquisition having a stock value of 40, and forces you to check if it's actually $ 40, or just in acquisition

Yeah, this is the point that lead me to taking notice of this. I didn't check, but this also probably means that the value in the end of the game is being incorrectly calculated, which isn't exactly irrelevant x)
