### ISSUE TITLE
[1817] Add warning if running with unused bridge

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2196]
We could show a message if the company has a bridge token to place and it is running to a hex without the bridge.

This could also be helpful for other games with similar tokens like the meat packing in 1846. Maybe the token code could be generalised a bit more. Iirc, the meat packing in 1846, the bridge in 1817 and the cattle in 1870 all work precisely the same way (for the token part), but the code is customised.

**Comment by jenf** [comment]
I'm not sure how the UI would flow for this

**Comment by jenf** [comment]
I believe @michaeljb is looking at this for #1520, and probably best placed for it.

**Comment by michaeljb** [comment]
Not directly what I'm looking at for #1520, but certainly related, under the umbrella of company abilities.

**Comment by jenf** [comment]
@daniel-sousa-me can you describe more how you think this should work as i'm a bit unclear.

**Comment by daniel-sousa-me** [comment]
During the route or the dividend step, if a corp is running through a city without a bridge and that corp has the option to place a bridge, I'd put some text pointing attention to this fact. Maybe making use of `train_help` or something like that.
