### ISSUE TITLE
Error message "undefined method" upon starting a new game

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#2199]
I received an "undefined method" error message immediately upon starting game 14822.

![18xx-14822-error-message](https://user-images.githubusercontent.com/73244775/98122979-dc492280-1e8b-11eb-9e97-e58de9a84ad5.png)

There is a player in this game whose username contains non-Latin characters.  Unknown if this is related.

The player list shown in the message appears to be from a _different_ game, 14798.

**Comment by michaeljb** [comment]
@Craig1830 it looks like you managed to get game [14822](https://www.18xx.games/game/14822) started, did refreshing or something fix it? I haven't been able to reproduce the issue locally.
