### ISSUE TITLE
Map tab - Mouseover company token

### ISSUE THREAD

**Issue by akh911007** [tobymao/18xx#2200]
I thought it could be cool if station tokens on the map had a mouse-over effect to show some information on which company / president controls the station. Maybe show the company charter card when you mouse over the token?

I had the thought while playing 1817 and a company went up for liquidation. I had the map up trying to determine who would want to buy the company's tokens and I kept switching back and forth between tabs. 

I don't know if it's worth it or not, but seems like it could be a cool idea.

**Comment by jenf** [comment]
I don't think this is needed now we have the colour border on tokens
