### ISSUE TITLE
Provide table of player and company history

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#2201]
Currently there is a table of revenue for each public company by round in the "OR History" on the "Spreadsheet" tab. This is a great feature for tracking the progress of the game (e.g. for making plots or performing an analysis), but it would be even greater if a similar "history" was provided for other player and company information:

- Player:
    - Cash
    - Value
    - Liquidity
    - Shares
    - Certs
- Company:
    - Market Price
    - Number of each kind of train
   - Player held shares

Currently the only way to get at this information is to run the game and copy out this information after each OR (or whatever), but it would be great to have this as part of the "Spreadsheet", suitable for simply copying and pasting into a Goole Sheet or Excel, for use in analysis or creating plots.

**Comment by orome** [comment]
Partially addresses [this](https://18xxgames.slack.com/archives/CV3R3HPUZ/p1616511361363300) by adding a table of "Value" history (only)

**Comment by daniel-sousa-me** [comment]
https://18xx.tools/stats/game/27063
