### ISSUE TITLE
[18Mex] cannot lay a tile in game #14865 and #15340

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#2202]
https://18xx.games/game/14865?action=36

want to lay a tile -> error message. wrong number of arguments (given 0, expected 1)

we started the game with two opt rules: Extra yellow + Early buy of KCM&O

**Comment by perwestling** [comment]
@Herbert62 - do you remember which corporation (TM I suppose?), and what tile + orientation, it was that you tried? 
I cloned the game and tried some TM lays but did not get any error.

**Comment by Herbert62** [comment]
TM spends $20 and lays tile #8 with rotation 3 on H11 -> error
TM spends $20 and lays tile #9 with rotation 1 on J11 -> same error

**Comment by perwestling** [comment]
I get no errors when I try a clone of 14865.
TM spends $20 and lays tile #8 with rotation 3 on H11
TM spends $20 and lays tile #9 with rotation 1 on J11

**Comment by Herbert62** [comment]
I can lay the tile - I always get the error
when I quit the error and want to continue, the game is out of sync
whein I refresh ny browser the tile has disappeared
I just undoed some move we did in enabled master mode and we replayed it - same problem - no way
even if I say skip laying tiles (which is of course no option in the first turn of a company) he says "wrong number of arguments (given 0, expected 1)"
no idea how to give him an argument :-(

**Comment by Herbert62** [comment]
new game - same error
https://18xx.games/game/15340?action=46

**Comment by perwestling** [comment]
After yesterday's corrections, are this still a problem?

**Comment by jenf** [comment]
hotseat games won't see this.
You could add the extra action, save the json and run it through validate.rb:validate_json

**Comment by Herbert62** [comment]
This morning I tried again and ended the second game after that.
I still got the error

**Comment by iGuitar93** [comment]
We are having the same issue in game 15367. Early buy of KCM&O private is an optional rule. We are in operating round 1 and the CHI cannot lay track. No matter who tries to do the action it doesn't work. Is the optional rule causing this bug?

**Comment by perwestling** [comment]
Bug located and I have pushed a fix. Thanks @jenf
