### ISSUE TITLE
1817 - Make it easier to see who owns what

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#2207]
both could be optional based on user preferences:

1) show company name (S/ME/A&A) instead of the logos on the map

2) circle logo/name with a color for each players. see image.
each player could go to preferences to activate this, set a color for himself, constant in all games, and a color for 2nd players, 3rd, etc, which would be assigned to the remaining players during setup. It could also be used to highlight each players holdings on the entities/game/sheet tabs, and also in the log so it's easier to see who is making what decisions

![image](https://user-images.githubusercontent.com/30501602/98238435-4631fc80-1f5e-11eb-93cf-b02dafe1f7dd.png)

ps: I wrote it as 1817 specific but it could be useful for other games I guess, this is just the first i'm having a hard time figuring out who owns what since there are so many companies

**Comment by akh911007** [comment]
I had a similar thought and suggested the idea for mouse-over text:  https://github.com/tobymao/18xx/issues/2200

The color border idea is interesting too, since that would be useful on mobile.

**Comment by PedroRCSequeira** [comment]
I actually mentioned the mouse-over option to a friend just a few days ago, and yesterday he showed me your idea, I guess I should write there too, it sounds really cool, and both would help, you can see who owns what and then easily get the info instead of swaping back and forth on the tabs

**Comment by daniel-sousa-me** [comment]
That sounds like a very nice friend x)

**Comment by jenf** [comment]
@tobymao what's your opinion of assigning each player a color and changing the border of the tokens to that corps owner color?

**Comment by PedroRCSequeira** [comment]
One extra thing that would help is, players could pick their colors, and also the color of the player to his left, and the next, etc

So when looking at the map, he always knows the *blue* player is just after him in the SR for instance. The one on his right would change depending on player count, but if they play mostly 4p games then that would also give an extra helpful hint

**Comment by tobymao** [comment]
i guess that would be an enhancement over on the table play. if it's trivial to do, i'm ok with it, but i don't think it's that necessary so i wouldn't spend much time on it

**Comment by giovandc** [comment]
Suggestions no. 2 starts from the assumption that all games a fixed stock round order, and this might not be the case as more titles get implemented.
A keyboard shortcut or on-screen button on the map tab to show/hide companies acronym could be useful

**Comment by benjaminxscott** [comment]
Generically I like the idea of a "legend" for tokens / company names

Perhaps in the legend, it could also show which player is President and be alphasorted by player name? 

(So companies I run are listed next to each other and it's more available "at a glance")

Personally the color borders seem difficult to tell apart and manage since some tokens will have conflicting color schemes (red on red)

**Comment by PedroRCSequeira** [comment]
Using the new toggle system one thing we could have is, a "normal mode" and a mode where logos are replaced with the names (A&A, ME, etc) and the colored border according to each player. That way the possibility of red on red and so on is gone.

**Comment by jenf** [comment]
I might think about actually implementing this soon.

@roseundy playing my first 18Mag game this looks very useful for that :)
Although in 18Mag's case maybe changing the entire color would be useful.

**Comment by jenf** [comment]
Following SVG would do it
<g><circle r="30" fill="red" stroke-width="0"></circle><image href="/logos/18_mag/3.svg" x="-25" y="-25" height="50" width="50"></image></g>

**Comment by giovandc** [comment]
Will it be enforced or the players can choose whether to show these circles
or not?

Il giorno gio 21 gen 2021 alle ore 09:46 Jennifer Freeman <
notifications@github.com> ha scritto:

**Comment by jenf** [comment]
Player choice I think is best

**Comment by PedroRCSequeira** [comment]
it could be the same as the hex coordinates on the map, off by default, but
anyone can turn them on :D

**Comment by jenf** [comment]
Prototype 18Mag & 1817NA
![Screenshot from 2021-01-21 21-39-54](https://user-images.githubusercontent.com/71923/105415957-5f7b4880-5c31-11eb-96f5-05c559f147c3.png)
![Screenshot from 2021-01-21 21-40-53](https://user-images.githubusercontent.com/71923/105415968-61450c00-5c31-11eb-8ab6-e9584fb77297.png)

**Comment by jenf** [comment]
Extra things to be done

Extend 'track' colors to add up to the 12 players for 1817
(I've checked it doesn't crash at present)
Improve text on 'track' colors to refer to players as well as track
Add player colors onto Player cards and maybe the entity bar
Allow the user to override their own color

**Comment by PedroRCSequeira** [comment]
This is great for 1817! :D

Now 2 small requests

1) Let us change player colors, or at least specify our own

2) have a per game toggle, or to make it simples something like "games with
10+ corps" and games with less
alternatively associate the map toggle option with just that game (this
could also be useful for the other toggles, for instance someone not
wanting to see the silly city games of 1817WO ^^

**Comment by tobymao** [comment]
you can already change the color. it’s tied to the routes
