### ISSUE TITLE
[1817] Crash during SR when trying to buy shares

### ISSUE THREAD

**Issue by ggohierroy** [tobymao/18xx#2208]
Game: https://18xx.games/game/13953

This was a pinned version, so the bug might already be fixed

A player was trying to close their short position by buying a share from the market, and it crashed.

![image](https://user-images.githubusercontent.com/1578363/98246350-31467080-1f40-11eb-9190-4f246c059eb8.png)

Data: https://gist.github.com/ggohierroy/f8d449436e972b8053012ff35a08d0ad

**Comment by jenf** [comment]
Probably, i fixed quite a few bugs relating to shorting so maybe
