### ISSUE TITLE
[1817] Warn about liquidation for missing loan payment

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2209]
There is a warning if the company will go into liquidation for lack of train, but there isn't if it's because missing the loan payment.

Since we're on it, I think the warning should be more visible. I suggesting putting the information on the "pass" button like we have now on the SR if you don't buy a token

**Comment by jenf** [comment]
Where would you put it? Dividends?

**Comment by daniel-sousa-me** [comment]
Yes, I think that makes sense. And also in the last loan phase.

I'd change the "Pass (loans)" button to something like "Send company into liquidation". Same for the no train case, so it's obvious that's the last chance to avoid liquidation.
