### ISSUE TITLE
18 Los Angeles / 1846 better EMR options

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2219]
In 18 Los Angeles and 1846, you can issue shares prior to dividend distribution, and also during emergency money raising. The interface for doing this is sometimes confusing to new (and even experienced) players.

As an example, in this game: https://www.18xx.games/game/14071?action=491

The SF has $420 and the next trains on offer are a 4/6 for $450 and a 5 for $500.

First, it would be nice if the "Done token/track" button had a warning "Issue shares now or you will enter emergency money raising."

Second, if the player does enter EMR, the system then offers them two buttons - one to issue one share (resulting in $480, enough to buy a 4/6 train) and the second to issue two shares (resulting in $540, enough to buy a 5 train). If the player issues two shares, they are unable to buy the 4/6 train but aren't told why they can't buy it. It would be nice if the interface offered two buttons: "issue one share, buy 4/6 train" and "issue two shares, buy 5 train."

**Comment by crericha** [comment]
There is certainly enhanced logic that help guide the player. It can also be a slippery slope when trying to strike a balance between too much hand holding and not enough. Perhaps something in between would be to distinguish between emergency issuing and regular issuing in the UI by changing the wording to "Emergency Issue" instead of just "Issue". That would help clarify to the player that there is a difference.

**Comment by ChrisTheCat** [comment]
Even if you don't want to 'hand hold' and warn people that they could issue before revenue distribution, there's still a good argument that when the only options are "issue one share and buy the cheap train OR issue two shares and buy the expensive train" the system shouldn't ask that question this way:

- How many shares do you want to issue, 1 or 2?
- You just issued two shares, would you like to buy the cheap train or the expensive train? 
- You chose the cheap train, that wasn't a real option, here's an unhelpful error message.

**Comment by crericha** [comment]
To me, its less a question of 'hand holding' or not and more of the cost of adding logical complexity. Historically, Toby has come down strongly on the side of its not worth it. I guess that wasn't clear in my first comment.

Why is the cheap train not an option? Maybe that's what I'm missing. I don't see that called out in the rules. Also, I can't ever remember someone wanting to issue more than needed for the train type they want. The only reason I could think to do that is if it closed the company.

**Comment by ChrisTheCat** [comment]
The cheap train is only an option if you issue ONE and ONLY ONE share. You are only allowed to issue exactly as many shares as are necessary to buy the selected train.

> I can't ever remember someone wanting to issue more than needed for the train type
> they want. The only reason I could think to do that is if it closed the company.

The reason you can't remember it happening is because it is illegal. You can't issue extra shares. And that's the crux of the interface problem. In face to face play, you pick the train, then issue as many shares as are needed to buy it. The 18xx interface obfuscates that decision by reversing it, forcing you to issue the shares before you pick the train.

**Comment by scottredracecar** [comment]
The game @ChrisTheCat linked to is broken. So many games of 1846 have now been played. Is this still an issue?

Closing for now, please reopen if this case appears again and propose a solution if necessary.
