### ISSUE TITLE
[18Mex] Sale of a half share displays in the log as sale of a full share

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#2220]
When selling a half share in 18Mex, the game log shows 1 share being sold instead of 0.5 shares (though the cash amount appears to be correct for a half share):

**{username} sells 1 share NdM and receives $45**

https://www.18xx.games/game/12986?action=215

May be related to issue #2218

**Comment by perwestling** [comment]
It does show the correct amount of money so I think it is just a minor.
