### ISSUE TITLE
[18LA] - LA Citrus token removed before Phase IV

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#2221]
Title about sums it up.  The LA Citrus token I placed in Riverside was removed (I think) at the start of Phase III with the private companies. Per 1846 rules the tokens remain until Phase IV, which we're not in yet.   In fact, the LA Steamship token is *correctly* still in Long Beach at the moment.

https://www.18xx.games/game/14433

**Comment by michaeljb** [comment]
LA Citrus does close when the first brown train is purchased at https://www.18xx.games/game/14433?action=505 but there's no bug there; it was still owned by a player.

I see the LA Citrus was bought by UP and had the token placed at https://www.18xx.games/game/14433?action=325, but then a bunch of undo actions happened and it was ultimately left with the player owning LA Citrus--and thus its token not placed on the board--at https://www.18xx.games/game/14433?action=333
