### ISSUE TITLE
[1817]  "Face value limit" private rule

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#2222]
I know that most people play with the variant that privates can sell over face value, especially given the importance of the Pittsburgh Steel Mill private and tile...  but are there any plans to make the original rule that privates can NOT sell over face value an option?  I feel like since it is in the rules, at least some acknowledgement should be shown to that rule.

**Comment by tobymao** [comment]
I don't think there's much point to it, as long as the info is in the wiki, if you don't want to play with that variant, you can by simply agreeing not to bid over max.

**Comment by SmithInMN** [comment]
You might be overestimating (1) how many people read the wiki, (2) how many people know the rules of 1817 and (3) how much awareness people always have while playing these games, but that’s your call. 

It would not be a hard fix, and at least to make it an option down the road would be deferential to Craig and Tim’s work.
