### ISSUE TITLE
[1817] In MA round plays can purchase shares of company in aquisition

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#2226]
In 1817 if a company converts and moves into acquisition players are able to buy shares at 0. They should not be able to buy shares of a company in acquisition

https://www.18xx.games/game/15415?action=220

**Comment by curlett** [comment]
https://github.com/tobymao/18xx/issues/2227 should fix this particular example, but you should not be able to purchase acquisition shares in any case, and I am sure other edge cases will come up as well.

**Comment by jenf** [comment]
dup of #2227
