### ISSUE TITLE
[1817] when a company is liquidated the president is responsible for loans not purchasing company

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#2228]
https://www.18xx.games/game/15415?action=345

1817 - In the MA round a company with 2 loans was liquidated. After the liquidation sale the president is responsible for paying off the loans. Instead the loans were given to the company, as if it were an acquisition or friendly sale.

**Comment by jenf** [comment]
AndyMesa bids $240 for UR
ME has $51 and 4 loans
ME afterwards has $11 and 6 loans.

This looks like correct behavior, to pay for the bid ME needs to take 2 loans.

**Comment by jenf** [comment]
UR settles with shareholders $240 = $120 ($240 to AndyMesa)
That should be $40
