### ISSUE TITLE
1817: Responsibility for mistaken assignment to acquisition status

### ISSUE THREAD

**Issue by DerekLong101** [tobymao/18xx#2237]
https://github.com/tobymao/18xx/blob/c91f8643fce15fbadd87b229f631e2bece3fd8b8/lib/engine/step/g_1817/acquire.rb#L436

This line and next fails because the special par prices (55, 70, 120) are all considered a different price type to the normal track. The consequence is that any company that enters (or leaves, I think) these prices during mergers will now be considered to have entered acquisition. The fix needs to do either confirm that the company price is actually an acquisition price, rather than assume it is because it is not a liquidation price.

Fixing this will fix #2225 and (prematurely closed) #2224.

**Comment by DerekLong101** [comment]
I suggest line 436 becomes:

if corporation.share_price.type != @game.stock_prices_start_merger[corporation].type  && (corporation.share_price.acquisition?  || corporatiob.share_price.liquidation?)

Not maybe the prettiest code, but it would do the job.

**Comment by perwestling** [comment]
Yes, that is pretty ugly code. A slight improvement would be to introduce a private method that is used here instead.

**Comment by jenf** [comment]
dup of #2237
