### ISSUE TITLE
18MEX Run Routes cannot process

### ISSUE THREAD

**Issue by RockCartel** [tobymao/18xx#2249]
game id (13012) stopped after buying last 2 train
{
  "id": 13012,
  "description": "MEX NZ (private)",
  "user": {
    "id": 684,
    "name": "NickCartel"
  },
  "players": [
    {
      "id": 5008,
      "name": "actionmahon"
    },
    {
      "id": 112,
      "name": "cdhunter"
    },
    {
      "id": 684,
      "name": "NickCartel"
    },
    {
      "id": 115,
      "name": "spielfool"
    }
  ],
  "max_players": 4,
  "title": "18Mex",
  "settings": {
    "seed": 2.7444176118773387e+38
  },
  "user_settings": null,
  "status": "active",
  "turn": 4,
  "round": "Operating Round",
  "acting": [
    684
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 105,
      "entity": "actionmahon",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 2,
      "type": "bid",
      "price": 55,
      "entity": "cdhunter",
      "company": "B",
      "entity_type": "player"
    },
    {
      "id": 3,
      "type": "bid",
      "price": 45,
      "entity": "NickCartel",
      "company": "KCMO",
      "entity_type": "player"
    },
    {
      "id": 4,
      "type": "bid",
      "price": 55,
      "entity": "spielfool",
      "company": "C",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "bid",
      "price": 50,
      "entity": "actionmahon",
      "company": "KCMO",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "bid",
      "price": 55,
      "entity": "cdhunter",
      "company": "A",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "bid",
      "price": 110,
      "entity": "NickCartel",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "bid",
      "price": 60,
      "entity": "spielfool",
      "company": "A",
      "entity_type": "player"
    },
    {
      "id": 9,
      "type": "bid",
      "price": 115,
      "entity": "actionmahon",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 10,
      "type": "bid",
      "price": 20,
      "entity": "cdhunter",
      "company": "MCAR",
      "entity_type": "player"
    },
    {
      "id": 11,
      "type": "bid",
      "price": 55,
      "entity": "NickCartel",
      "company": "KCMO",
      "entity_type": "player"
    },
    {
      "id": 12,
      "type": "bid",
      "price": 60,
      "entity": "actionmahon",
      "company": "KCMO",
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "bid",
      "price": 65,
      "entity": "NickCartel",
      "company": "KCMO",
      "entity_type": "player"
    },
    {
      "id": 14,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 15,
      "type": "bid",
      "price": 65,
      "entity": "cdhunter",
      "company": "A",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "bid",
      "price": 70,
      "entity": "spielfool",
      "company": "A",
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "bid",
      "price": 75,
      "entity": "cdhunter",
      "company": "A",
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "bid",
      "price": 85,
      "entity": "spielfool",
      "company": "A",
      "entity_type": "player"
    },
    {
      "id": 19,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 20,
      "type": "bid",
      "price": 120,
      "entity": "NickCartel",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 21,
      "type": "bid",
      "price": 125,
      "entity": "actionmahon",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "bid",
      "price": 130,
      "entity": "NickCartel",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 23,
      "type": "bid",
      "price": 135,
      "entity": "actionmahon",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 24,
      "type": "bid",
      "price": 140,
      "entity": "NickCartel",
      "company": "MIR",
      "entity_type": "player"
    },
    {
      "id": 25,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 26,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 27,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 28,
      "type": "bid",
      "price": 140,
      "entity": "actionmahon",
      "company": "MNR",
      "entity_type": "player"
    },
    {
      "id": 29,
      "type": "par",
      "entity": "actionmahon",
      "corporation": "NdM",
      "entity_type": "player",
      "share_price": "90,0,5"
    },
    {
      "id": 30,
      "type": "par",
      "entity": "cdhunter",
      "corporation": "CHI",
      "entity_type": "player",
      "share_price": "90,0,5"
    },
    {
      "id": 31,
      "type": "undo",
      "user": "cdhunter",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 32,
      "type": "par",
      "entity": "cdhunter",
      "corporation": "PAC",
      "entity_type": "player",
      "share_price": "80,0,4"
    },
    {
      "id": 33,
      "type": "undo",
      "user": "cdhunter",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 34,
      "type": "par",
      "entity": "cdhunter",
      "corporation": "CHI",
      "entity_type": "player",
      "share_price": "60,2,2"
    },
    {
      "id": 35,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 36,
      "type": "par",
      "entity": "spielfool",
      "corporation": "MC",
      "entity_type": "player",
      "share_price": "70,1,3"
    },
    {
      "id": 37,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "CHI_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 38,
      "type": "buy_shares",
      "entity": "cdhunter",
      "shares": [
        "CHI_3"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 39,
      "type": "buy_shares",
      "entity": "NickCartel",
      "shares": [
        "MC_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 40,
      "type": "buy_shares",
      "entity": "spielfool",
      "shares": [
        "MC_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 41,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "CHI_4"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 42,
      "type": "buy_shares",
      "entity": "cdhunter",
      "shares": [
        "CHI_5"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 43,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 44,
      "type": "buy_shares",
      "entity": "spielfool",
      "shares": [
        "MC_3"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 45,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "MC_4"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 46,
      "type": "buy_shares",
      "entity": "cdhunter",
      "shares": [
        "CHI_6"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 47,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 48,
      "type": "buy_shares",
      "entity": "spielfool",
      "shares": [
        "MC_5"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 49,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "MC_6"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 50,
      "type": "buy_shares",
      "entity": "cdhunter",
      "shares": [
        "CHI_7"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 51,
      "type": "buy_shares",
      "entity": "NickCartel",
      "shares": [
        "CHI_8"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 52,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 53,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "MC_7"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 54,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 55,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 56,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 57,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 58,
      "type": "pass",
      "entity": "A",
      "entity_type": "minor"
    },
    {
      "id": 59,
      "type": "run_routes",
      "entity": "A",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 60,
      "type": "pass",
      "entity": "B",
      "entity_type": "minor"
    },
    {
      "id": 61,
      "type": "run_routes",
      "entity": "B",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 62,
      "type": "pass",
      "entity": "C",
      "entity_type": "minor"
    },
    {
      "id": 63,
      "type": "run_routes",
      "entity": "C",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 64,
      "hex": "I8",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 65,
      "hex": "K8",
      "tile": "58-0",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 66,
      "type": "buy_train",
      "price": 100,
      "train": "2-3",
      "entity": "MC",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 67,
      "hex": "G6",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "CHI",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 68,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 69,
      "type": "buy_train",
      "price": 100,
      "train": "2-4",
      "entity": "CHI",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 70,
      "type": "undo",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 71,
      "type": "undo",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 72,
      "type": "undo",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 73,
      "hex": "C6",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "CHI",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 74,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 75,
      "type": "buy_train",
      "price": 100,
      "train": "2-4",
      "entity": "CHI",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 76,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 77,
      "type": "buy_shares",
      "entity": "cdhunter",
      "shares": [
        "MC_8"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 78,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 79,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 80,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 81,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 82,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 83,
      "type": "pass",
      "entity": "A",
      "entity_type": "minor"
    },
    {
      "id": 84,
      "type": "run_routes",
      "entity": "A",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 85,
      "type": "pass",
      "entity": "B",
      "entity_type": "minor"
    },
    {
      "id": 86,
      "type": "run_routes",
      "entity": "B",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 87,
      "type": "pass",
      "entity": "C",
      "entity_type": "minor"
    },
    {
      "id": 88,
      "type": "run_routes",
      "entity": "C",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 89,
      "hex": "L9",
      "tile": "4-0",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 90,
      "hex": "M10",
      "tile": "6-0",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 91,
      "city": "6-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 92,
      "type": "run_routes",
      "entity": "MC",
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "M10",
              "L9"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "K8",
              "I8"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 93,
      "kind": "payout",
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 94,
      "type": "buy_train",
      "price": 100,
      "train": "2-5",
      "entity": "MC",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 95,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 96,
      "hex": "G6",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "CHI",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 97,
      "hex": "H7",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "CHI",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 98,
      "type": "run_routes",
      "entity": "CHI",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 99,
      "kind": "payout",
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 100,
      "type": "buy_train",
      "price": 100,
      "train": "2-6",
      "entity": "CHI",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 101,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 102,
      "type": "sell_shares",
      "entity": "NickCartel",
      "shares": [
        "MC_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 103,
      "type": "sell_shares",
      "entity": "NickCartel",
      "shares": [
        "CHI_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 104,
      "type": "par",
      "entity": "NickCartel",
      "corporation": "MEX",
      "entity_type": "player",
      "share_price": "75,1,4"
    },
    {
      "id": 105,
      "type": "buy_shares",
      "entity": "spielfool",
      "shares": [
        "MC_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 106,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 107,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "MEX_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 108,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 109,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 110,
      "type": "buy_shares",
      "entity": "NickCartel",
      "shares": [
        "MEX_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 111,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 112,
      "type": "message",
      "entity": "NickCartel",
      "message": "If you can buy a share of MEX for me on my turn",
      "entity_type": "player"
    },
    {
      "id": 113,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 114,
      "type": "message",
      "entity": "spielfool",
      "message": "Auto pass for me",
      "entity_type": "player"
    },
    {
      "id": 115,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 116,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 117,
      "type": "buy_shares",
      "user": "cdhunter",
      "entity": "NickCartel",
      "shares": [
        "MEX_3"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 118,
      "type": "pass",
      "user": "cdhunter",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 119,
      "type": "pass",
      "user": "cdhunter",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 120,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 121,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 122,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 123,
      "type": "pass",
      "entity": "A",
      "entity_type": "minor"
    },
    {
      "id": 124,
      "type": "run_routes",
      "entity": "A",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 125,
      "hex": "K6",
      "tile": "471-0",
      "type": "lay_tile",
      "entity": "B",
      "rotation": 2,
      "entity_type": "minor"
    },
    {
      "id": 126,
      "type": "run_routes",
      "entity": "B",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 127,
      "hex": "S12",
      "tile": "6-1",
      "type": "lay_tile",
      "entity": "C",
      "rotation": 4,
      "entity_type": "minor"
    },
    {
      "id": 128,
      "type": "run_routes",
      "entity": "C",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "S12",
              "R13",
              "Q14"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 129,
      "hex": "P13",
      "tile": "473-0",
      "type": "lay_tile",
      "entity": "MEX",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 130,
      "hex": "Q12",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "MEX",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 131,
      "type": "buy_train",
      "price": 100,
      "train": "2-7",
      "entity": "MEX",
      "variant": "2",
      "entity_type": "corporation"
    },
    {
      "id": 132,
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation"
    },
    {
      "id": 133,
      "hex": "J7",
      "tile": "58-1",
      "type": "lay_tile",
      "entity": "MC",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 134,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 135,
      "type": "run_routes",
      "entity": "MC",
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "M10",
              "L9"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "K8",
              "I8"
            ],
            [
              "J7",
              "I8"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "P11",
              "O10"
            ],
            [
              "M10",
              "O10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 136,
      "kind": "payout",
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 137,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 138,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 139,
      "type": "run_routes",
      "entity": "CHI",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 140,
      "kind": "payout",
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 141,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 142,
      "type": "buy_shares",
      "entity": "spielfool",
      "shares": [
        "CHI_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 143,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 144,
      "type": "undo",
      "user": "spielfool",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 145,
      "type": "undo",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 146,
      "type": "buy_shares",
      "entity": "spielfool",
      "shares": [
        "CHI_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 147,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 148,
      "type": "buy_shares",
      "entity": "actionmahon",
      "shares": [
        "MEX_4"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 149,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 150,
      "type": "buy_shares",
      "entity": "cdhunter",
      "shares": [
        "MEX_5"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 151,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 152,
      "type": "buy_shares",
      "entity": "NickCartel",
      "shares": [
        "MEX_6"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 153,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 154,
      "type": "pass",
      "entity": "spielfool",
      "entity_type": "player"
    },
    {
      "id": 155,
      "type": "pass",
      "entity": "actionmahon",
      "entity_type": "player"
    },
    {
      "id": 156,
      "type": "pass",
      "entity": "cdhunter",
      "entity_type": "player"
    },
    {
      "id": 157,
      "type": "pass",
      "entity": "NickCartel",
      "entity_type": "player"
    },
    {
      "id": 158,
      "hex": "M12",
      "tile": "472-0",
      "type": "lay_tile",
      "entity": "A",
      "rotation": 1,
      "entity_type": "minor"
    },
    {
      "id": 159,
      "type": "run_routes",
      "entity": "A",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "M12"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 160,
      "hex": "J5",
      "tile": "4-1",
      "type": "lay_tile",
      "entity": "B",
      "rotation": 2,
      "entity_type": "minor"
    },
    {
      "id": 161,
      "type": "run_routes",
      "entity": "B",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "K6"
            ],
            [
              "J5",
              "K6"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 162,
      "hex": "T13",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "C",
      "rotation": 5,
      "entity_type": "minor"
    },
    {
      "id": 163,
      "type": "run_routes",
      "entity": "C",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "U14",
              "T13",
              "U12",
              "S12"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 164,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 165,
      "type": "run_routes",
      "entity": "MC",
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "M10",
              "L9"
            ],
            [
              "L9",
              "K8"
            ],
            [
              "K8",
              "I8"
            ],
            [
              "J7",
              "I8"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "P11",
              "O10"
            ],
            [
              "M10",
              "O10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 166,
      "kind": "payout",
      "type": "dividend",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 167,
      "type": "pass",
      "entity": "MC",
      "entity_type": "corporation"
    },
    {
      "id": 168,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 169,
      "type": "run_routes",
      "entity": "CHI",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "E6",
              "C6",
              "A6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 170,
      "kind": "payout",
      "type": "dividend",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 171,
      "type": "pass",
      "entity": "CHI",
      "entity_type": "corporation"
    },
    {
      "id": 172,
      "type": "pass",
      "entity": "MEX",
      "entity_type": "corporation"
    },
    {
      "id": 173,
      "type": "run_routes",
      "entity": "MEX",
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "P13"
            ],
            [
              "P11",
              "Q12",
              "P13"
            ],
            [
              "P11",
              "O10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 174,
      "kind": "payout",
      "type": "dividend",
      "entity": "MEX",
      "entity_type": "corporation"
    }
  ],
  "loaded": true,
  "created_at": 1603046556,
  "updated_at": 1604878059
}

**Comment by jenf** [comment]
games are being migrated, please wait they'll be back
