### ISSUE TITLE
[1817] Cannot buy shares after converting company

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2252]
**Please provide**
[1817] Cannot buy shares after converting my second 2-share company in a row. I may only take loans or liquidate the company.

Live game where this was encountered
https://www.18xx.games/game/14604

Here is a hotseat game gist
https://gist.github.com/ventusignis/db8e3324406a92db4e7f224d25cb396c

For the hotseat I created 2 2-share companies, paid out so that the president had money, and when I tried to convert to 5-share corporations, buying shares was not given as an option.

**Comment by biddu6566** [comment]
Sam issue with gameID 13594

https://www.18xx.games/game/13594

**Comment by jenf** [comment]
Confirmed, likely a regression
