### ISSUE TITLE
[1817] Red warning about interest after paying interest

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2254]
https://www.18xx.games/game/14114?action=526

A company pays the interest, it is pretty common and non-problematic that the company doesn't have enough cash to pay the interest next OR, but right now the interest shows in red because it is less than the cash the company has.

**Comment by jenf** [comment]
I'm not sure what the solution is for this. When is it valid to warn players that a corporation doesn't have enough cash to pay it's interest?

**Comment by daniel-sousa-me** [comment]
I'd say only during the OR, before the company has to pay it.

I also think the most important warning is when the company can't pay the interest even if taking more loans.

**Comment by jenf** [comment]
Yeah at the least it should be changed to buying power rather than cash.

Maybe 'red' if buying power + last route doesn't cover interest
'yellow' if buying power doesn't cover interest

**Comment by daniel-sousa-me** [comment]
I really like that!

That probably should be different between running and paying dividends (that' might be the buy trains step only). There it should be just "red" if buying power doesn't cover interest.

Don't forget that the "buying power doesn't cover interest" also has to include the interest of the new loans.
In rr18xx the buying power automatically subtracts that, but it becomes awkward outside of the OR, because sometimes what you care about is how much money you can use right now (and sometimes you can actually avoid paying it altogether!).
I am realising that it's not clear when each should be shown and that both are useful, but having one more line may get too cluttered. I thought maybe the "interest due" line could also include the amount of interest you have to pay if taking all loans (and then you just subtract on your mind). Like "Interest due: $40/$100" (for a 5 share company with 2/5 loans).

**Comment by jenf** [comment]
I'm only going to do the yellow mode, as I think the red could be confusing since it might mean that there's no way to pay the bill when you could improve the route, but that's for the players to work out.
