### ISSUE TITLE
Tile placement preview for full map

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#2259]
Currently there's an excellent tile placement preview (in the form of clear indication of available tiles) available for the active player on the Game tab. It would be great if the ability to preview potential (and unavailable) tile placements was available everywhere, regardless of who the current player is (e.g. on the Map tab).

In order of (assumed) complexity it would be nice to have:
- the ability to click on any hex where a tile can be placed by any player and see what placements are possible, regardless of who plays (i.e. no player restrictions imposed);
- imposition of player restrictions (i.e. don't show tiles that no one could possibly place);
- indication, for placeable tiles, of which players could place them (e.g., with the company icons tagging each tile);
- the ability to "impersonate" a specific player and see what tiles they could place.

**Comment by jenf** [comment]
dup of #1279
