### ISSUE TITLE
Game Card Error

### ISSUE THREAD

**Issue by chrisdavis103** [tobymao/18xx#2262]
Linux.  Firefox 82.02 64bit.

I see this on the main page:

Error rendering game card... clear your local storage: {"id"=>13093, "description"=>"exploring game, open, +2move per day", "user"=>{"id"=>2999, "name"=>"HansEllinas"}, "players"=>[{"id"=>1967, "name"=>"kyoysc"}, {"id"=>3811, "name"=>"Gersen"}, {"id"=>3544, "name"=>"Djuel"}, {"id"=>1452, "name"=>"chrisdavis103"}, {"id"=>2999, "name"=>"HansEllinas"}], "max_players"=>5, "title"=>"18Mex", "settings"=>{"pin"=>"c91f8643", "seed"=>3.4575951505126706e+37}, "user_settings"=>nil, "status"=>"active", "turn"=>6, "round"=>"Stock Round", "acting"=>[1967], "result"=>{}, "actions"=>[], "loaded"=>false, "created_at"=>1603095189, "updated_at"=>1604879920}

**Comment by tobymao** [comment]
dup, known issue, you can still go to the game directly
