### ISSUE TITLE
[1817] Following conversion, president restricted to only single share purchase

### ISSUE THREAD

**Issue by DerekLong101** [tobymao/18xx#2266]
The rules indicate that the president may buy *any number* of shares following conversion, up to certificate and holding limits. Then other players may buy a single share. Currently, the implementation only offers single share purchase opportunity to president (and all other players).

**Comment by jenf** [comment]
Do you have a game that shows this bug?

**Comment by jenf** [comment]
The code as implemented should do this.

**Comment by DerekLong101** [comment]
Just reran the game to confirm and realise that the president in question only had enough cash for one share. Sorry to have raised a false alarm!

**Comment by jenf** [comment]
no probs, i thought that'd be the issue. Please add a game next time as it makes it easier to diagnose
