### ISSUE TITLE
"Your games" game sorting should prioritize active games

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#227]
IMO, the order should be: active games, then started games, then games that have not started yet.

**Comment by jcoveney** [comment]
Is this uninteresting to you? It's still an "issue" as far as I can tell
(quotes bc it's not some major bug). Not huge, but annoying. If you have a
lot of games, always having to click "next" to check for new ones seems
like there's no reason for it to be necessary. If one ever had 3 pages of
games it's be quite annoying, as each page swap can take a couple of
seconds on my connection.

**Comment by tobymao** [comment]
fix is merged

**Comment by dfannius** [comment]
This was implemented in PR #351, which was merged 4 hours ago as I write this. It may not have gone live yet.

**Comment by jcoveney** [comment]
Ah ok I was on my phone. Nice work as always :)

**Comment by tobymao** [comment]
ger contributed this one

**Comment by dragon12** [comment]
@jcoveney ah I should have posted here :) I note your follow-up https://github.com/tobymao/18xx/issues/356 , and I've also just opened https://github.com/tobymao/18xx/issues/375 because the new Finished Games addition aren't sorted now.
