### ISSUE TITLE
[18MEX] "wrong number of arguments" when attempting to lay yellow veracruz tile

### ISSUE THREAD

**Issue by drewsheldon** [tobymao/18xx#2270]
GameID=15466: https://www.18xx.games/game/15466?action=56

We get "wrong number of arguments" error when attempting to lay yellow veracruz tile

**Comment by perwestling** [comment]
@drewsheldon Does the problem remain? Tried to recreate it but could not.

**Comment by drewsheldon** [comment]
Problem remains. The full text of the error is “wrong number of arguments (given 0, expected 1)”

**Comment by CaptainObi** [comment]
https://www.18xx.games/game/15619, has the same issue with TM, this is has happened to me in two games and happened both times with TM.

**Comment by drewsheldon** [comment]
It works now! Not sure what all happened but at least one thing tried was another player attempted to mastermode it and got the same error. They then commented about this in the chat. Then when I attempted to go back and try again it allowed me to place the tile and all is well now. Not sure what happened but the bug in that game is resolved! Thank you!

**Comment by CaptainObi** [comment]
Same here!

**Comment by perwestling** [comment]
I am not sure what happened here but I will close this one. Thanks for reporting.
