### ISSUE TITLE
1817 - Suggestion to make token purchase default (option to not buy tokens)

### ISSUE THREAD

**Issue by jehayward** [tobymao/18xx#2271]
In a number of games I've played, we've found some confusion/frustration in the need to purchase the tokens. Players have missed this numerous times and we've gotten well into the next OR before realizing the mistake.

I do recognize that this is a step in the rules, and that there are reasons why you would not wish to purchase the tokens, but in most cases the token purchase occurs.

In some discussion, we thought it was worth suggesting that the token buy process in this implementation be reversed, in which the companies would automatically purchase their tokens when started, but an option would be available to the player to select the company and "Un-buy" the tokens.

**Comment by tobymao** [comment]
that'd be too complicated to implement, i don't think there will be plans to do this.
