### ISSUE TITLE
[1882] NWR event isn't random.  Always happens on 3 train.

### ISSUE THREAD

**Issue by Kyrkitao** [tobymao/18xx#2272]
`nwr_train = trains[rand % trains.size]` at https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1882.rb#L111 should be
`nwr_train = trains[rand trains.size]`

The NWR event should happen on a randomly selected train of the 3, 4, 5, or 6, but in three games it had only chosen 3. 

Applicable rules text:

> The “additional trains” are a 3, 4, 5, and 6 train.  Shuffle the 3, 4, 5, and 6 train and randomly select one of them. Place the NWR indicator card in the train stack under the first train of the type matching the randomly selected train.Set aside the additional 3, 4, 5, and 6 train.

**Comment by michaeljb** [comment]
One of the fixture games we have in the repo has the rebellion happen on the 4, one on the 5. You can check out those JSONs (and import them as a hotseat game) here - https://github.com/tobymao/18xx/tree/master/spec/fixtures/1882

I think your sample size of three games is just a little bit too small ;)
