### ISSUE TITLE
allow plays in entities tab

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#2273]
Just how you can lay track in either the game or the map tab, I would like to be able to buy/sell/short in the entities tab.

I use it a lot because I like to see companies sorted by president instead of market price,
so what happens is, I look at entities to make my decision, then go to game tab, search for the company i wanted to buy/sell/short and then do it. it takes longer and it is more prone to error, specially in 17 where there are sooooo many companies and so much to do (short 1, sell 2 or 3, and buy another, that's a bunch of back and forth eheh

**Comment by tobymao** [comment]
i don't think we will do this, a more concise approach would be the spreadsheet mode
