### ISSUE TITLE
1817 Bug: game stuck on bankruptcy

### ISSUE THREAD

**Issue by wheresvic** [tobymao/18xx#2276]
Hi, 

In a M&A round, a player bankrupted due to a company liquidating with loans. The sales did not generate enough cash and president bankrupted on loan repayments. The game froze thereafter and does not load anymore : https://18xx.games/game/15714. 

Console error:

```
{
  "name": "owner",
  "message": "undefined method `owner' for #<Engine::SharePool:0x1fce>",
  "args": []
}
```

**Comment by michaeljb** [comment]
Last action that still loads - https://18xx.games/game/15714?action=1306

Copied game data at that point to gist - https://gist.github.com/michaeljb/21a90fee45ce17a12ea9809f2d5f06af

**Comment by michaeljb** [comment]
![7148DC6B-638B-46BD-8F47-CC690FC0DCD6](https://user-images.githubusercontent.com/1045173/98955598-52690d00-24bc-11eb-9797-cfda96b9d795.jpeg)

**Comment by jenf** [comment]
Problem is it really doesn't know who should be acting for the market since the corp is owned by the market at that point.

**Comment by jenf** [comment]
Ahh, R is offered for sale while the same time the owner goes bankrupt.
