### ISSUE TITLE
Option to buy trains from another company lists the same company twice for the same train #

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#228]
Train 2 - ¥80
Train 2 - from AR
Train 2 - from AR

It should just list skip the second 'Train 2 - from AR'

**Comment by sparr** [comment]
This happens when AR has two 2-trains?

**Comment by jenf** [comment]
`{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Mitsubishi Ferry",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 3,
      "company": "Ehime Railway",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "company": "Sumitomo Mines Railway",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 5,
      "company": "Dougo Railway",
      "price": 60
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "corporation": "AR",
      "share_price": "65,5,3"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "corporation": "IR",
      "share_price": "65,5,3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "share": "AR_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9,
      "share": "IR_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 10,
      "share": "AR_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "share": "IR_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "share": "AR_3"
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 13,
      "hex": "K8",
      "tile": "6-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 14,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 15,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 16,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 17
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 18,
      "share": "IR_3"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 22,
      "hex": "E2",
      "tile": "5-0",
      "rotation": 4
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    }
  ],
  "title": "1889",
  "description": "",
  "max_players": "6",
  "id": "hs_1588232337",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-04-30"
}`

**Comment by jenf** [comment]
Above shows it three times, since AR owns 3 2 trains.
