### ISSUE TITLE
1817 Bug - President only allowed to buy one share when converting.

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#2285]
https://gist.github.com/joeyd4329/6c653ba8c15d51db686045df8ac2f4e2

Player One converted Belt Railway of Chicago to a 5 share company. When prompted to buy a treasury share, only one share was allowed to be bought even after the president had $105 while the share price was $70. In 7.1.4 a president should be able to buy as many shares as desired.

**Comment by akh911007** [comment]
President can only hold up to 60% of a 5-share company, so 1 additional share is all the president can buy

**Comment by joeyd4329** [comment]
Doh, that went right over my head, I will go ahead and close this issue.
