### ISSUE TITLE
[18MEX] Wrong number of IPO shares in NdM in Spreadsheet

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2289]
https://www.18xx.games/game/14777?action=344#spreadsheet

**Comment by perwestling** [comment]
Well... the 10th share is reserved, and appear as trade-in share on the charter. But it is an IPO share that cannot be bought.

So the question is if we should add a column just to show reserved shares?

**Comment by daniel-sousa-me** [comment]
The question is that I don't know what I'm doing and missed that :|

It's fine as it is
