### ISSUE TITLE
1817 - game is stuck in MA round and cannot be moved forward or backwards

### ISSUE THREAD

**Issue by emknell** [tobymao/18xx#2292]
Our game of 1817 is stuck and none of the buttons seem to work.  I'm trying to Pass for ME, although neither the Convert or Undo buttons seem to have an effect either.  I tried it on both my phone and browser, and others in the game have tried in Master mode.

https://www.18xx.games/game/15728

Thanks,
Eric

**Comment by jenf** [comment]
dup of #2281, checked fix works for this game as well
