### ISSUE TITLE
1817: Incorrect Stock Price movement at the end of SR

### ISSUE THREAD

**Issue by biddu6566** [tobymao/18xx#2294]
In 1817 games newly floated 5 share companies with only president owning 60% of shares (rest in treasury) moved right in stock price at the end of SR. The rules say "If 100% or more of a 5 share or 10 share company's stock is held by players, the stock price moves one space to the right, unless the value of the stock is already at $600."

Game is https://www.18xx.games/game/13593

**Excerpt from game log** 
_SR's share price changes from $200 to $220
DL&W's share price changes from $180 to $200
H's share price changes from $180 to $200
R's share price changes from $180 to $200_

**Comment by jenf** [comment]
Game was pinned, but I recall no changes to that area
https://www.18xx.games/game/13593?action=1171

**Comment by jenf** [comment]
Ahh, that's a really old pin, it doesn't include the fix for #2138
