### ISSUE TITLE
1817 - Show 0 tokens left when the private runs out of tokens

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2298]
When the private companies exaust their reserve of tokens (like the coal mine in 1817), it should show (0/3) in the token counter, while it just shows the name of the private, so you don't know if the private actually has tokens left or not.

**Comment by jenf** [comment]
This is a bit of a limitation, as soon as you have used the ability it no longer exists

**Comment by giovandc** [comment]
You mean that the ability actually disappears when operating the company?
DIdn't notice that, but still, 0/3 would be a very useful and simple visual cure to check, from the entity tab, what companies have still tokens left.
