### ISSUE TITLE
1817 - Incorrect value for "Interest if 0 more loans repaid"

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2300]
Game link: https://www.18xx.games/game/13546?action=304

The Bank currently shows the Interest per Loan as $10, but also shows that if 0 more loans are repaid, the new interest will be $5. I'm new to 1817, so I could be mistaken, but I was under the impression the interest only decreases when loans are repaid. 
![1817-bank](https://user-images.githubusercontent.com/332270/99081083-3a62bd80-2590-11eb-8512-e84fa7df63d6.png)

**Comment by jenf** [comment]
another off by one... my dodgy coding it should be 5 more loans repaid.
