### ISSUE TITLE
[1817]  Pittsburgh Steel Mill not available to buy in

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#2301]
I just won the auction -- which another player started -- for a company in Pittsburgh.  Pitt Steel Mill is not available to buy in to the company.  Other privates are and I do own PSM.

{
  "id": 15812,
  "description": "TC18XX Bug hunting and Learning game",
  "user": {
    "id": 606,
    "name": "SmithInMN"
  },
  "players": [
    {
      "id": 529,
      "name": "Akado"
    },
    {
      "id": 2336,
      "name": "jerryyeti"
    },
    {
      "id": 2843,
      "name": "joeD"
    },
    {
      "id": 606,
      "name": "SmithInMN"
    }
  ],
  "max_players": 5,
  "title": "1817",
  "settings": {
    "seed": 1581348753,
    "unlisted": true,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Stock Round",
  "acting": [
    606
  ],
  "result": {},
  "actions": [
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 1,
      "message": "all right...gonna try something out in hotseat, see what happens when seed money runs out"
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 2,
      "message": "unlesss bug, if there's no more seed money. ya gotta cover the entire cost for what ever the bid is"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 3,
      "message": "yeah, was just seeing edge cases"
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 4,
      "message": "gotcha"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 5,
      "message": "if you run out of money because you're dumb, you can still try to start opening bids, you just get lots of errors"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 6,
      "message": "but no game crash"
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 7,
      "company": "TS",
      "price": 25
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 8,
      "message": "Private auction is pretty automated...  if you run out of cash/have insufficient cash, it will just skip right over you."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 9,
      "message": "yep, just making sure that it worked for weird cases in 1817"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 10,
      "message": "in case they broke it specifically for here"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 11,
      "message": "This is the one part that has always, for the most part, worked.  I've played through a number of stupid things in this auction.  Past this, any number of things might go wrong, including a full and complete crash, but this has always worked!"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 12,
      "message": "cool"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 13,
      "message": "I don't know how much anyone knows about 1817, so I won't over-explain anything, but if you're not sure about something, say something and we'll get it sorted."
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 14,
      "message": "I'm foggy in some areas, but I think I have a good general idea"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 15,
      "message": "I know what can be done, I have no idea how any of it helps me win"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 16,
      "message": "or why I shouldn't have done -that- action right -then-"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 17,
      "company": "TS",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 18,
      "company": "TS",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 19,
      "company": "TS",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 20,
      "company": "TS",
      "price": 60
    },
    {
      "type": "message",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 21,
      "message": "I’ve only watched the bankruptcy club video... so if I go bankrupt that’s why"
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 22,
      "message": "heh"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 23,
      "company": "TS",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 25,
      "message": "i have a feeling 3 of us will be vying for that \"first to bankrupt\" trophy"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 26,
      "message": "and chris will just be laughing his butt off"
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 27,
      "company": "TS",
      "price": 70
    },
    {
      "type": "message",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 28,
      "message": "Thanks for waiting."
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 29,
      "company": "TS",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 31
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 32,
      "message": "Hell no...  That's a serious over-estimation of me and we all know it!"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 33,
      "company": "PSM",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 34,
      "company": "PSM",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 35,
      "company": "PSM",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 36,
      "company": "PSM",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 37,
      "company": "PSM",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 38,
      "company": "PSM",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 39,
      "company": "PSM",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 43,
      "company": "UBC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 44,
      "company": "UBC",
      "price": 25
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 45,
      "company": "UBC",
      "price": 55
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 46,
      "message": "Damn!"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 47,
      "message": "...  and I'll raise you $30!"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 48,
      "company": "UBC",
      "price": 60
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 49,
      "message": "I like to move it, move it"
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 50,
      "company": "UBC",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 51
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 52,
      "company": "UBC",
      "price": 70
    },
    {
      "type": "message",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 53,
      "message": "Are the two bridge cos essentially the same?"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 54,
      "message": "Yep except for number of tokens."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 55,
      "message": "one \"+$10\" token vs two"
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 57,
      "company": "UBC",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 58
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 59,
      "company": "MAJM",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 60,
      "company": "MAJM",
      "price": 95
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 61,
      "message": "I did notice the tooltips + error message if you try to bid  $96"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 62,
      "company": "MAJM",
      "price": 100
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 63,
      "message": "err, i mean...who would try such a thing?!"
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 64,
      "company": "MAJM",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 65,
      "company": "MAJM",
      "price": 110
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 66
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 67,
      "message": "An a**hole, that's who.  :)"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 68,
      "company": "MAJM",
      "price": 115
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 69
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 70,
      "company": "MAJM",
      "price": 120
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 71,
      "message": "clearly"
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 73,
      "company": "CM",
      "price": 35
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 74,
      "message": "What has two thumbs and is overpaying?  :)"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 75,
      "company": "CM",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 76,
      "company": "CM",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 77
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 78,
      "message": "two half-completed robots?"
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 79,
      "company": "CM",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 80,
      "company": "CM",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 82
    },
    {
      "type": "message",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 83,
      "message": "I thought these were supposed to go for 80%ish of their face value. :-)"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 84,
      "message": "Oh, they are!  "
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 85,
      "company": "MAIL",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 86,
      "company": "MAIL",
      "price": 75
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 87,
      "message": "I'm totally overbidding...  No idea why.  :)"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 88,
      "message": "eh"
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 89,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 90,
      "message": "from what i hear, the small ones go for face+, whereas the big ones can go for 80-100%"
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 91,
      "company": "MAIL",
      "price": 85
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 92,
      "message": "paying face = free power for a company, so it's not a bad thing"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 93,
      "message": "its' just not free money (if the bank chips in)"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 94,
      "company": "MAIL",
      "price": 90
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 97
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 98,
      "company": "MINM",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 99,
      "company": "MINM",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 100,
      "company": "MINM",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 101
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 102,
      "company": "MINM",
      "price": 55
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 103
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 104,
      "company": "MINM",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 105,
      "company": "MINM",
      "price": 65
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 106
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 107,
      "company": "MINC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 108,
      "company": "MINC",
      "price": 25
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 109
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 110,
      "company": "MINC",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 111
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 112
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 113,
      "message": "I could not imagine doing this auction async with people making 2-3 moves a day.  It would take forever."
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 114,
      "company": "OBC",
      "price": 30
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 115,
      "message": "especially when you throw in time zone differences"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 116,
      "message": "Oof."
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 117,
      "company": "OBC",
      "price": 35
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 118
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 119
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 120,
      "company": "OBC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 121
    },
    {
      "type": "message",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 122,
      "message": "Two left!"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 123,
      "company": "ME",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "joeD",
      "entity_type": "player",
      "id": 124,
      "company": "ME",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 125
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 126
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 127
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 128
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 129,
      "company": "MAJC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 130,
      "company": "MAJC",
      "price": 70
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 131
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 132
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 133,
      "company": "MAJC",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 134,
      "company": "MAJC",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 135,
      "company": "MAJC",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 136,
      "company": "MAJC",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 137,
      "company": "MAJC",
      "price": 95
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 138,
      "message": "bahhhh.  If y'all had just let me get $10 more in seed money, I could have floated three companies for $110 each"
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 139
    },
    {
      "type": "bid",
      "entity": "Akado",
      "entity_type": "player",
      "id": 140,
      "corporation": "H",
      "price": 110
    },
    {
      "type": "place_token",
      "entity": "H",
      "entity_type": "corporation",
      "id": 141,
      "city": "H9-2-0",
      "slot": 0
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 142,
      "message": "\"You like auctions?  Cause this game has them!\""
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 143,
      "message": "yuuuup"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 144,
      "message": "I see you like auctions, so I put auctions in your auctions"
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 145
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 146,
      "message": "I always read that as Miskatonic and expect Cthulhu to appear on your railroad."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 147,
      "message": "^"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 148,
      "message": "Auztrailia, yo"
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "message",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 151,
      "message": "am I expected to start one or two companies?"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 152,
      "message": "i vote for two"
    },
    {
      "type": "assign",
      "entity": "Akado",
      "entity_type": "player",
      "id": 153,
      "target": "OBC",
      "target_type": "company"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 154,
      "message": "first companies are 2-share companies, so you get 100% (unless you halfpay)"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 155,
      "message": "I would say at least two."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 156,
      "message": "i don't think anyone can start 3?"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 157,
      "message": "ohhh, right, $100 companies"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 158,
      "message": "* Generally at least two."
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 159,
      "message": "My approach is to generally start a number of companies between two and two."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 160,
      "message": "haha"
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 161,
      "corporation": "Bess",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "Bess",
      "entity_type": "corporation",
      "id": 162,
      "city": "F13-5-0",
      "slot": 0
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 163,
      "message": "if you can start 3, i think that's really good, but i don't know how to not die in a horrible rusty fire later with 3 companies"
    },
    {
      "type": "pass",
      "entity": "joeD",
      "entity_type": "player",
      "id": 164
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 165,
      "corporation": "Bess",
      "price": 105
    },
    {
      "type": "pass",
      "entity": "Akado",
      "entity_type": "player",
      "id": 166
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 167,
      "corporation": "Bess",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 168,
      "corporation": "Bess",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 169,
      "corporation": "Bess",
      "price": 120
    },
    {
      "type": "bid",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 170,
      "corporation": "Bess",
      "price": 125
    },
    {
      "type": "pass",
      "entity": "jerryyeti",
      "entity_type": "player",
      "id": 171
    },
    {
      "id": 172,
      "type": "assign",
      "entity": "SmithInMN",
      "target": "MAJC",
      "entity_type": "player",
      "target_type": "company"
    },
    {
      "id": 173,
      "type": "undo",
      "user": "SmithInMN",
      "entity": "joeD",
      "entity_type": "player"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 174,
      "message": "Wait...  that's weird...  Why can't I buy in the Pittsburgh Steel Mill??  That was the whole purpose of bidding on that!"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 175,
      "message": "that is..."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 176,
      "message": "i swore i saw you buy it in"
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 177,
      "message": "yeah it's there"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 178,
      "message": "refresh"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 179,
      "message": "I did refresh...  It's not there."
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 180,
      "message": "Damn, that's weird!"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 181,
      "message": "Hang on..."
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 182,
      "message": "think it's a bug, that you didn't start the bid on Bess or something?"
    },
    {
      "type": "message",
      "entity": "joeD",
      "entity_type": "player",
      "id": 183,
      "message": "I mean it's there under your player box. I don't see it to buy in though"
    },
    {
      "type": "message",
      "entity": "SmithInMN",
      "entity_type": "player",
      "id": 184,
      "message": "I just closed the tab and reopened it...  Well, first bug found!  Gimme a second to report it!"
    },
    {
      "type": "message",
      "entity": "Akado",
      "entity_type": "player",
      "id": 185,
      "message": "cool"
    }
  ],
  "loaded": true,
  "created_at": 1605123983,
  "updated_at": 1605280278
}

**Comment by jenf** [comment]
Cash | $15
-- | --
Value | $295
Liquidity | $15
Bid Power | $175
Certs | 1/16

Pittsburgh Steel Mill $40
Major Mail Contract $120
Major Coal Mine (3/3) $90

Bid was won at $125, so privates + cash options give you
=15+40 < 125
= 0+90+40 >130
= 0+120+40 > 160

There's no legal way at a bid of 125 that cash + privates can be made including the 40 for Pittsburgh

Not showing Pittsburgh is correct behavior Correct behavior

**Comment by SmithInMN** [comment]
Fair point.  Embarrassingly, never even considered that.  Thanks.

**Comment by jenf** [comment]
We never considered it when first implementing it leading to problems :)
