### ISSUE TITLE
Waterfall Auction - Allows buying of private with money committed to other privates.

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#2302]
In our 1836Jr30 game, someone with $230 committed on the final private was allowed to buy the previous private without a bid at face value, giving them negative available money.

Attached is the JSON and an image.

![Negative available](https://user-images.githubusercontent.com/11392314/99088283-7a767000-2591-11eb-8ad8-849d493da033.jpg)
[1836jr30.json.txt](https://github.com/tobymao/18xx/files/5537706/1836jr30.json.txt)

**Comment by jenf** [comment]
we needed to revert, reopening. ensure testing on 1846 since the auction is done differently.

**Comment by michaeljb** [comment]
Also ensure that hegeton is able to raise their bid on UTF here - https://18xx.games/game/16575?action=41 ([gist backup](https://gist.github.com/michaeljb/67205b174fe834a258037ef74a3ec306))
