### ISSUE TITLE
[18MEX] "0 is not valid to spend" error

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2304]
I can't get past NdM's turn. I get an error saying "0 is not valid to spend"

https://www.18xx.games/game/14777

**Comment by perwestling** [comment]
Actually the problem is SPM. It owns trains but has no tile laid in the home location. A case I never considered...
Have a fix on that that I will push.

**Comment by daniel-sousa-me** [comment]
I had also just submitted a PR x)

But it seems Rubocop failed (I always forget to check...), so I'll delete mine
