### ISSUE TITLE
Show private company track lay specials as possible options when laying track

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#231]
It seems the private company track lay specials has a confusing UX:

Mitsubishi Ferry when owned by a player
Ehime Railway when owned by a company

Add these as possible laying track options when it's valid for them to lay track. If they lay it then can then lay company track.
(This assumes that the user does it before their normal track lay, but they can use the other way to do it if they lay normal track first)

**Comment by masontylerjames** [comment]
This would be really helpful, as my current game is stalled because we can't figure out how to use the Ehime Railway ability.

**Comment by jenf** [comment]
Companies -> Select Companies go to map then you should be able to lay

**Comment by jenf** [comment]
I think the new UI makes this more obvious, and the rest is covered by #940
