### ISSUE TITLE
OR history in spread sheet needs improvement for showing payment

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2312]
Here is an example from 1846:
![image](https://user-images.githubusercontent.com/2631151/99148483-33b77180-2688-11eb-942f-15513957fef7.png)

This is the code used:
![image](https://user-images.githubusercontent.com/2631151/99148450-f9e66b00-2687-11eb-8257-bd55290ebb86.png)

The use of 50%, 75% or 100% opacity - is that clear enough?

Using dotted line and underscore at the same time - is that intentional?

Should really the 100% amount be shown when it is half pay? Alternative is to show 50% of full payment.
((I had a memory that rr18xx did show half amount, but that was incorrect. It shows 100% as well, but use |x| to show half dividend.))

We also need to consider how to show Destination Runs in 1870. I am not sure the current solution would cater for one more way of showing OR history.

FInally, consider adding a Legend to explain the different way of showing dividend.

**Comment by dfannius** [comment]
I feel strongly that the total amount that the trains run for should be what is displayed, whether that amount is withheld, half-paid, or paid out in full.

**Comment by yzemaze** [comment]
>Using dotted line and underscore at the same time - is that intentional?

Yes. https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration


>I think "50% or 100% opacity" are visually distinct, but 75% is too subtle if that's the only distinction between payout types

That’s exactly why they are underline dotted. Cf. discussion in #1119 and PR https://github.com/tobymao/18xx/pull/1129
A better way would be welcome. So yeah, feel free to
>perhaps try out a few options and survey slack?

or just brainstorm here.

>We also need to consider how to show Destination Runs in 1870. I am not sure the current solution would cater for one more way of showing OR history.

There are always colors, frames, pre-/suffixes etc.

**Comment by yzemaze** [comment]
Better visual distinction by #3827. I’ll add a legend immediately.
