### ISSUE TITLE
1846: Bankruptcy issues.  Second of two Market-owned companies did not run

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#2315]
https://www.18xx.games/game/16134?action=355

Player owning both B&O and C&O went bankrupt.  C&O operated first, ran its train (via other players deciding), withheld.  B&O operated immediately afterwards, and did not even get a chance to operate its train and withhold.  

((The second issue reported here was split into #2316 ))

**Comment by perwestling** [comment]
The 2nd issue was causes by a recent change to cater for 5% shares in 18MEX. I think that is a separate issue, so this issue should be split into two.

**Comment by perwestling** [comment]
The 20% button problem has been fixed in #2316.
