### ISSUE TITLE
【1817】cities cannot upgrade to brown

### ISSUE THREAD

**Issue by sadknight1989** [tobymao/18xx#2322]
cities like buffalo, toledo, Blackburn, can not upgrade from green to brown. Which means tile #611 and #448 can not be use.

**Comment by jenf** [comment]
please provide a game id showing an example

Also be aware of the following rule 'When upgrading normal cities to brown, players must
use tiles with as many exits as will fit.'

**Comment by michaeljb** [comment]
Sample game posted by @crericha for #2324 - https://gist.github.com/michaeljb/075f803267b6ed91e7cf0f9d2f203eb3

**Comment by jenf** [comment]
ahh, potential tiles restricts to early, it should be done in upgradeable_tiles
