### ISSUE TITLE
1817: Corporation share sell buttons inconsistent (UI)

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#2325]
The first sell button says "Sell a 20% ($60)" and the second "Sell 2 ($120)". In my opinion, the buttons should be consistent. Either "Sell 1" and "Sell 2" or "Sell 1 20%" and "Sell 2 20%".

![image](https://user-images.githubusercontent.com/67359577/99193143-04b30580-2745-11eb-8dbf-ea80631ebb1a.png)

[sell share inconsistency.data.txt](https://github.com/tobymao/18xx/files/5542877/sell.share.inconsistency.data.txt)

**Comment by jenf** [comment]
@perwestling ?

**Comment by jenf** [comment]
resolved I think
