### ISSUE TITLE
1817 - Allow company to immediately buy station when floated

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2327]
99% of time when you open a new company you want to immediately buy the needed station tokens. Make it so that, after opening the company, you can immediately buy them (if you can), instead of having to wait until your next turn to perform this non-action

**Comment by tobymao** [comment]
wouldn't this change priority / big against the rules?

**Comment by jenf** [comment]
Paying for the stations is not technically an action as per the rules.

The problem comes from if the corporation doesn't have the cash to buy the tokens, then there's one way if you do have money, another if you do not.

**Comment by jenf** [comment]
On a strict interpretation of the rules you'd only be able to buy stations if you initiated the bidding.

In person games i'd suspect everyone would just allow you to buy the tokens, but we need to implement the rules as written.
