### ISSUE TITLE
Expand spreadsheet view to include per-player financial history

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#233]
This builds off of the work in this issue https://github.com/tobymao/18xx/issues/193
As well as the work in this issue https://github.com/tobymao/18xx/issues/215

Where the second issue provides operating round history for companies, this issue seeks to add financial history for players. It will likely be very similar to the solution to issue 215, but it's good to separate stuff out :)

**Comment by jcoveney** [comment]
I have a PR ready for this once #210 lands

**Comment by Apreche** [comment]
@jcoveney I came to post a feature request asking for the spreadsheet to include how much total income each player got in each OR. Does your PR include that information?

**Comment by jcoveney** [comment]
Yes, I implemented that. But was told it cluttered the spreadsheet. If
people are open to it now I can def revive the PR -- I want the info!

**Comment by Apreche** [comment]
I also think it would clutter the sheet to show the player income from every single OR. But the most recent ORs are really the ones you care about most, and showing just one or two would only take a column or two. That doesn't sound like clutter to me. 

If we want to see the income from every single OR, then I think it should go in a separate sheet below the big one.

**Comment by jcoveney** [comment]
I suppose I'd just want toby to weigh in on what he would be ok with before I spend time on it. I personally would want all ORs, but yeah we could just do the last set of ORs. Or have a second spreadsheet below, though I think toby will be resistant to that. Another option would be a separate graph (a la what is in rolling stock) of player value over the game, perhaps in the tools dropdown.

**Comment by Apreche** [comment]
I think have to consider the use case. Why do we want this information, and what will we use it for? 

Personally, I find the information most useful when the game is close to ending, and when it's close. I want to be able to predict, assuming nothing big happens, which player will be ahead at the end of the ORs. For that, I need to see about how much revenue each player is probably going to get each OR. For that, I only need the most recent OR, and that shouldn't make too much clutter.

After the game is over, I see no reason not to show a detailed summary of everything.

**Comment by jenf** [comment]
Personally i'd like a graph of the bank state at certain points, and players value over the game, it'd be interesting to see "did that tactic actually work" after a game.

**Comment by jcoveney** [comment]
I think the info at the end of the game is easy to agree on.

Before that, I think the information is useful to evaluate "how am I doing relative to everyone else right now." This can influence the decision to buy trains, start new companies, etc.

**Comment by wheresvic** [comment]
Can you post a link to the PR, I would be very interested to see what it might look like!

**Comment by jenf** [comment]
I believe this is now done.
