### ISSUE TITLE
1817: Company that already has 8 tokens can not convert without entering liquidation

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2335]
A company that has 8 tokens even if it is a 2 or 5 share company is not allowed the option of buying additional tokens during a conversion in an M&A round.  It will immediately then enter liquidation.  It should instead just proceed without needing to purchase any tokens.
  
link to the game:
https://18xx.games/game/16174 

Relevant Rule: The company
must now purchase additional station markers. When a
2-share company converts to a 5-share it must buy one
station marker for $50 provided the company currently
has fewer than eight station markers. When a 5-share
company converts to a 10-share company, it must buy
two station markers for $100 provided the company has
six or fewer station markers. If it has exactly seven station
markers, it must buy one station marker for $50.

**Comment by jenf** [comment]
Relevant action
https://18xx.games/game/16174?action=2091
