### ISSUE TITLE
1817: On bankruptcy, ownership of a corporation should not transfer to the next player with highest share count

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2336]
When a player bankrupts, the companies that player owns should go into liquidation immediately regardless of the number of shares held by other players.

link to game:
https://18xx.games/game/16174

Relevant rule: 
If the player
has sold all the shares possible, and still cant make payment,
he is bankrupt and removed from the game. The
game continues without the player.
...
Place all the players stock shares, short shares, and private
companies in the open market. If the presidents
certificate for any company is now in the open market,
place that companys stock marker in the liquidation
space.

**Comment by mtsay** [comment]
Note that the president of a company may not sell shares as to cause a transfer of presidency outside of a stock round per rule 7.4:

"Shares may not be sold that cause a president’s certificate from any company to change hands" 
and [this discussion on BGG](https://boardgamegeek.com/thread/2083383/article/32304235#32304235)

In the extreme case, a non-president player holds 6 shares of a company will prevent the president (who also holds 6 shares) from selling any share during a cash crisis.

**Comment by mtsay** [comment]
Also note that this affects liquidity calculation during ORs & M&A rounds. The current number suggests that if a non-president player holds more than 1 share of a company, then all shares of that company held by the president are liquid when they are not.

**Comment by jenf** [comment]
https://18xx.games/game/16174?action=2156

Two bugs
* Ownership change
* Check to make sure no president change in EMR
