### ISSUE TITLE
1817: Shares in companies should not be instantly closed on a bankruptcy - only in the next stock round

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2337]
During a bankruptcy all of a player's shares and shorts should be placed in the open market.  Any short shares and actual shares will immediately cancel each other out in the open market.  However, shares in companies should not be redeemed by the bank until the following Stock Round.  It is currently immediately redeeming all the shares.

link to game:
https://18xx.games/game/16174

Relevant Rule:
Place all the players stock shares, short shares, and private
companies in the open market.
...
At any time, if there is a share and a matching short
share in the open market, they are removed from the
open market and placed in the NYSE Open Short Interest
section. At the start of every stock round, the bank closes
any short positions in the open market by purchasing
stock from the company treasury, if there is any available.
The bank will continue to do this until all short
shares are cleared from the open market.

**Comment by jenf** [comment]
It closes shorts which have an equivalent in the market, but it doesn't buy shorts from the treasury until the stock round.

Or am I missing something?

Please provide an example action where it's incorrect

**Comment by steve-yu** [comment]
I'm sorry in reviewing the log again, I see that the action is working correctly.  I misread what when the redemption of company shares happened.

**Comment by jenf** [comment]
no problems :) will try and fix the other two today
