### ISSUE TITLE
1817: priority should transfer when a president acted on behalf of a company during a stock round.

### ISSUE THREAD

**Issue by mtsay** [tobymao/18xx#2338]
During a stock round, when a player takes loans and/or redeems shares (but excluding buying required stations) with one of the companies they control, the priority should transfer to the next player. Currently priority does not transfer.

link to game:
[https://18xx.games/game/16174](https://18xx.games/game/16174)

Relevant rule:
5.7: "The stock round ends when all players pass consecutively. Give the priority deal marker to the player to the left of the last player to take an action, for himself **or one of his companies in the stock round**. Advance the roundel marker...

**Comment by jenf** [comment]
Relevant action:
https://18xx.games/game/16174?action=1094
