### ISSUE TITLE
[18Chesapeake] Hinder player from buying other player's trains without their consent

### ISSUE THREAD

**Issue by Lloyden** [tobymao/18xx#2339]
According to the rules a player can buy another player's train to an agreed upon price. On the site, that can easily be overriden, thus creating unnecessary friction between players.
I didn't know about this rule, figuring that was a special rule for 18Chesapeake, and rudeness ensued, quite unnecessarily. If a dialogue box query enables the other player to accept or decline the bid, this mistake could easily be avoided

**Comment by jenf** [comment]
The game is already asking for confirmation by making you show other players trains.

**Comment by Lloyden** [comment]
I mean the _other_ player obviously. Apparently this is a problem that has occurred several times, and since this leads to toxicity and ruined games it really should be pertinent to address

**Comment by jenf** [comment]
@tobymao

**Comment by tobymao** [comment]
you mean someone stole your trains? if so that's a player issue and not software. if people are maliciously stealing your trains, you shouldn't play with them.

**Comment by Lloyden** [comment]
Actually it was me that unknowingly "stole" other player's trains due to lack of knowledge about the rules. 
The "player issue" was that I was rudely chastised. You may not mind that, but I do. 
It is unfortunate that new players are met with disdain instead of enthusiasm - I will not play with strangers on this site again: who knows which other "well known" but unsupported rules I might break

**Comment by tobymao** [comment]
Sorry you had that experience. The players who were rude to you were in the wrong because you are a new player. There are many friendly players who I'm sure will provide a more cordial experience.

**Comment by Lloyden** [comment]
Thank you so much for your kind reply :) And thank you for a great site which gives me the opportunity to play these great games!
