### ISSUE TITLE
1817 - Tweak buying power counter

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2340]
The buying power counter is an unofficial counter created to make it easier for the players to plan their moves.
This counter, though, only displays the "raw" buying power, which doesn't take in consideration the interest the companies need to pay.
The actual, useful buying power should then be "Raw buying power" - "actual interest rate". Otherwise, every player is forced to do such math in their minds, and it's just a waste of time.

**Comment by jenf** [comment]
The Raw Buying Power changes depending exactly where in the OR you are, if you are before dividends then the meaning can be different.
I don't think we should vary this depending what step of the OR you are in.
