### ISSUE TITLE
1817: Auction home city not requested until after auction with no other bidders

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#2341]
https://18xx.games/game/15799?action=352

This is admittedly a minor point.

At this point I auctioned the GT.  I picked a bid amount. On the next screen, where the home city is normally specified, I noticed in the game log that I had already won the auction. Granted, no one else had enough cash so I was automatically the winner, but technically it should have (1) asked me for the home city FIRST, and then (2) recorded in the game log "Player 2: not enough cash to bid / Player 3: not enough cash to bid ....", etc, and THEN declared me the president of the GT.

**Comment by jenf** [comment]
It's an architectual  issue that's not easy to resolve i'm afraid. Won't fix
