### ISSUE TITLE
1817 - First bid in liquidation display bug

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2349]
https://18xx.games/game/15349?action=1381
The guy is the first to bid for the liquidation auction. The text box that allows that bid shows 10, and you can raise it up to 20. Even though you cannot bid 20 (it gives you an error), you shouldn't be able _at all_ to select 20, and only 10 should be displayed.

**Comment by jenf** [comment]
i'm afraid the action id is no longer valid, after a while of trying to find the action you mention i failed. Could you provide an example where this is the case?
