### ISSUE TITLE
Expand Spreadsheet view to show when are in the yellow/brown

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#235]
Currently it shows grey if they are not floated it'd be nice to add yellow and brown for when they're in that area on the stack market.

**Comment by jcoveney** [comment]
I went ahead and put a PR together which does this once https://github.com/tobymao/18xx/pull/210 lands. I could put it there, but I want to get that in, since it is the basis of multiple other PRs I have, and will be useful etc etc
