### ISSUE TITLE
1817 - Company logos in different size in the order section of the main view

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2350]
Recently it's been implemented a feature the displays different company token sizes in the market, depending on the size of the company (2/5/10). This effect should be limited to the market, and not to the operation order section in the main view too
![image](https://user-images.githubusercontent.com/72523908/99410621-fc003200-28f2-11eb-99c6-027bf99a344b.png)

**Comment by jenf** [comment]
Why? Another user requested it

**Comment by daniel-sousa-me** [comment]
I didn't even realise it was related to company size. I think it looks weird in both places

**Comment by jenf** [comment]
Yeah, this is a case of 'can't please everyone'

I can be persuaded to remove it from the bar, but the market i think probably has value.

**Comment by PedroRCSequeira** [comment]
I really like it in both places, just extra info is nice!!

**Comment by giovandc** [comment]
I honestly thought that this was a bug since they look so weird skewed and out of place in the operation round order bar.
I don't really care about the market, even though I personally find it superfluous, but sure as hell isn't needed in the operation order bar, which was, before this change, neat and clean, as it should be.

**Comment by jenf** [comment]
Vote up this comment if you want it removed, vote down this comment if you want it retained.

**Comment by daniel-sousa-me** [comment]
I suggest that while the icons get smaller, their container stays the same size. That should improve the look

**Comment by daniel-sousa-me** [comment]
I figured out what is my problem with the logos. You made the big corps bigger instead of making the small corps smaller. I think that if you reduce the size of all of them it will look a lot better.

This applies doubly to the size in the bar. If the biggest logos are of the size of the text (and the others are centred vertically), I think it will look good. Even if the logos are not legible, you still get some info with the color.

I may try to play around with this later and send some screenshots.

**Comment by daniel-sousa-me** [comment]
I've done the new version, you can find the source at: https://github.com/daniel-sousa-me/18xx/tree/logo_sizes
I'll do a PR if you all think this is an improvement.

Here are the new versions:

![image](https://user-images.githubusercontent.com/3337865/99918490-285ee880-2d0f-11eb-996d-c043e55114be.png)

![image](https://user-images.githubusercontent.com/3337865/99918493-344aaa80-2d0f-11eb-80ae-122582dd0cf4.png)

**Comment by daniel-sousa-me** [comment]
The thing I still don't like is the bold and especially the underline, but I don't have an alternative that's consistent with the rest of the site

**Comment by giovandc** [comment]
I still think that it just looks messy on the market, but that's just my opinion. The info on the company size is actually relevant only with other info (like cash, shortability, amount of trains and stations), so the spreadsheet is the place to look for company size, not the market.

**Comment by jenf** [comment]
Given there is no consensus, i'm closing this issue as won't fix.
