### ISSUE TITLE
Bug: [UNDO] does not revert Priority Deal

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#2351]
https://18xx.games/game/14792?action=363

Player C does an action, so Player D has Priority Deal.  Player D does something (Player A now has Priority Deal), regrets it immediately (much like most of their life), clicks [Undo], and passes.  However, Player A still has priority deal, adding to the list of things that Player D regrets.

Let's remove one of those things from that list, because Player D has enough baggage already.

**Comment by Akado05** [comment]
Speaking of regrets, the "*Priority Deal*" indicator does indeed show incorrectly after an Undo, but upon everyone passing for the round, the PD was correctly given to Player D.  Who still has regrets about their life.

**Comment by benjaminxscott** [comment]
Besides the display bug, I think there's a mechanical bug as well

Using your [game's json to repro](https://github.com/tobymao/18xx/files/5556211/repro.json.txt), if I undo back to `triode`'s turn (at this point, they are the last one to take an action, so `dennislaumen` should have priority), and pass through everyone else's turn from `dennislaumen` on, the player that gets priority is `Akado` - which is incorrect

If I'm interpreting correctly, the undo feature is not "decrementing" the priority deal marker back to the player who should have it, if an action is taken and then undo'd

**Comment by jenf** [comment]
The game engine does not actually see the undo's, they are processed before the game engine actually sees any actions.

**Comment by daniel-sousa-me** [comment]
This is 100% unrelated to undo. 18LA doesn't have priority based on pass order. Any priority info that is shown after the end of the SR is incorrect, because it should only be attributed at the end of the OR
