### ISSUE TITLE
18MEX bankruptcy didn't sell all shares

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2355]
https://18xx.games/game/16377

```
MEX does not run
MEX's share price changes from $65 to $60
-- ChrisShaffer goes bankrupt and sells remaining shares --
ChrisShaffer sells 3 shares NdM and receives $240
NdM's share price changes from $80 to $65
-- Game over: claudio ($961), 18xxperson ($943), Hanigan ($546), ChrisShaffer ($463) --
```

ChrisShaffer should have also sold 3 shares of MEX and 0.5 shares of NdM automatically as part of the bankruptcy.

**Comment by perwestling** [comment]
The bug was that NdM was handled incorrectly. Shouldn't have been a bankruptcy, although would have crippled your position.
