### ISSUE TITLE
Better error message on duplicate username

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2357]
If I try to change my username to one that exists, I get the error "PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "users_lower(name)_index" DETAIL: Key (lower(name))=(...) already exists."

**Comment by jenf** [comment]
It also occurs when you create a duplicate name when creating an account

**Comment by yzemaze** [comment]
cf. https://github.com/tobymao/18xx/pull/716
