### ISSUE TITLE
Zoom option for map - feature request

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#236]
Low priority feature request: add ability to zoom just the map portion. On high resolution (4k+) monitor, it is very small. Can zoom entire browser, but other components grow too large/distorted. 

Thanks!

**Comment by justinkwaugh** [comment]
transform-origin: 0px 0px;
transform: scale(<some value>)

triggered by buttons which look like: 
<img width="93" alt="Screen Shot 2020-08-11 at 3 29 11 PM" src="https://user-images.githubusercontent.com/1012189/89940735-faceb300-dbe7-11ea-8993-ca525af6bfce.png">

which has html like (I used bootstrap and : 
`<div class="btn-group" role="group">                                    
<button type="button" class="btn btn-sm btn-outline-light font-weight-bold " style="height:35px;"><span class="oi oi-zoom-out"></span></button>
<button type="button" class="btn btn-sm btn-outline-light font-weight-bold" style="height:35px;"><span class="oi oi-zoom-in"></span>
</button>
</div>`

**Comment by jenf** [comment]
This is now implemented
