### ISSUE TITLE
1817: Bankruptcy is not working correctly

### ISSUE THREAD

**Issue by jftaylor21** [tobymao/18xx#2361]
See https://18xx.games/game/13546

shermath5 and auzzy went bankrupt, but they were not removed from the game and they still have cash and can take turns. However, the certificate limit did go up as expected.

**Comment by jenf** [comment]
First and second bankruptcy
https://18xx.games/game/13546?action=402
https://18xx.games/game/13546?action=404

**Comment by jenf** [comment]
Players should be cleared of cash after bankruptcy
