### ISSUE TITLE
Cert Limit didn’t change 

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#2363]
In game ID 15115, SR5 I closed a Corp in the SR to decrease the share limit but this didn’t actually happen after the corporation closed - the limit stayed at 12 instead of decreasing to 10.

**Comment by daniel-sousa-me** [comment]
I'm sorry. This is my fault. I changed how this is handled a few days ago and somehow a line of code got lost in the way

**Comment by daniel-sousa-me** [comment]
The code was divided in 2 PRs, but one of them didn't get merged yet
