### ISSUE TITLE
1817 - In friendly sale some companies are skipped even though there are companies that could bid on them 

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2365]
https://18xx.games/game/15349?action=1864
PLE was automatically skipped in the friendly sale.
It had 40 stock value, 7 shares in the treasury, 25 cash and 9 loans. The starting bid was 400, but subtracting 280 from the shares and 25 cash, anyone who could pay at least 95 in cash, even by taking loans, and absorb 9 loans, could bid on that.
There were 3 companies that satisfied these conditions.
1. WC. Had 1/10 loans, 105 in cash. Could easily pay 95 and just max its loan slots.
2. GT. 0/10 loans. 55 in cash. It could have taken all the 9 loans + another one to pay the 95 bid.
3. UR. Same as GT.

This doesn't apply to all biddable companies.

**Comment by jenf** [comment]
Could you do me a favor and calculate the right outcomes for each of the three corporations if they did acquire at the starting bid.
I'd like to verify the calculations are correct

**Comment by giovandc** [comment]
PLE was automatically skipped in the friendly sale.
It had 40 stock value, 7 shares in the treasury, 25 cash and 9 loans. The starting bid was 400, but subtracting 280 from the shares and 25 cash, anyone who could pay at least 95 in cash, even by taking loans, and absorb 9 loans, could bid on that.
There were 3 companies that satisfied these conditions.
1. WC. Had 1/10 loans, 105 in cash. Could easily pay 95 and just max its loan slots.
2. GT. 0/10 loans. 55 in cash. It could have taken all the 9 loans + another one to pay the 95 bid.
3. UR. Same as GT.
Now, if PLE could be put up in auction, these would have been the scenarios:
1. If WC bid on PW the minimum bid (400, nominally), it would end up with **10/10 loans** (1+9) and **$10 cash** (105-95). The company stock value would drop from 100 to 40.
2. If GT bid on PLE the minimum bid (400), it would end up with **10/10 loans** (9 absorbed, 1 taken to pay 95) and **$56 cash** (51 +100 (extra loan) -95). The company stock value would drop from 180 to 65.
3. If UR bid on PLE the minimum bid (400), it would end up with **10/10 loans** (9 absorbed, 1 taken to pay 95) and **$6 cash** (1 +100 (extra loan) -95). The company stock value would drop from 135 to 50.

**Comment by jenf** [comment]
The code believes the following max bids
bid WC PLE 130
bid GT PLE 176
bid UR PW 10

**Comment by jenf** [comment]
Found the issue, wasn't calculating treasury shares correctly

WC max bid: 410
GT max bid: 456
UR max bid: 406

**Comment by jenf** [comment]
GT acquires PLE receiving $305, companies (Pittsburgh Steel Mill, Coal Mine, Major Mail Contract), loans (9), trains (3,4), and tokens (5: hexes F13,H9,C26,C8)
GT takes a loan and receives $100
GT's share price changes from $180 to $165
GT's share price changes from $165 to $65
PLE settles with shareholders $400 = $40 ($80 to DrDome, $-40 to gdc, $-360 to BoB94)
