### ISSUE TITLE
1817 - Force declaration of bankruptcy if, even by selling all the marketable shares, he can't afford the amount due

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2366]
https://18xx.games/game/15349?action=1877
The player is in cash crisis and can't pay the needed amount, so he must declare bankruptcy.
Since he's forced anyway to declare bankruptcy, this could be done automatically.

**Comment by jenf** [comment]
We don't do this in any other game. While we can do it automatically I think it's important that a player knows they are out.
