### ISSUE TITLE
1817 - "Declare Bankruptcy" button does't work, and a "undefined method `[]' for nil" error message is displayed.

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2367]
https://18xx.games/game/15349?action=1877
Just as the title says. Clicking on the button does nothing, and the error message is displayed.

**Comment by jenf** [comment]
Last log messages are
["UR cannot be bought at $1350, skipping", "NYOW moved into liquidation during M&A and so is skipped", "GT cannot be bought at $650, skipping", "Bess moved into liquidation during M&A and so is skipped"]

**Comment by jenf** [comment]
From the game log it should be in the transition between an Acquitiion and an OR

**Comment by giovandc** [comment]
Actually this is what I see:
-- Merger and Conversion Round 4.1 (of 2) --
Bess passes convert or merge corporation
GT converts from 5 to 10 shares
BoB94 passes buy/sell shares post conversion
• Action(pass) via Master Mode by BoB94:
DrDome passes buy/sell shares post conversion
GT passes taking loans
GT pays $100 for 2 tokens
• Action(pass) via Master Mode by BoB94:
NYOW passes convert or merge corporation
• Action(pass) via Master Mode by DrDome:
B&A passes convert or merge corporation
UR merges with B&A at share price $135 receiving trains (4), and tokens (2: hexes D19)
• Action(pass) via Master Mode by gdc:
DrDome passes buy/sell shares post conversion
BoB94 passes buy/sell shares post conversion
UR passes taking loans
• Action(convert) via Master Mode by BoB94:
WC converts from 5 to 10 shares
• Action(buy_shares) via Master Mode by BoB94:
DrDome buys a 10% share of WC from the Treasury for $100
• Action(buy_shares) via Master Mode by BoB94:
DrDome buys a 10% share of WC from the Treasury for $100
BoB94 passes buy/sell shares post conversion
• Action(pass) via Master Mode by BoB94:
gdc passes buy/sell shares post conversion
• Action(pass) via Master Mode by BoB94:
WC passes taking loans
WC pays $100 for 2 tokens
NYSW skips convert or merge corporation
ME skips convert or merge corporation
WT passes convert or merge corporation
PW skips convert or merge corporation
PLE skips convert or merge corporation
-- Acquisition Round 4.1 (of 2) --
PLE cannot be bought at $400, skipping
PW cannot be bought at $400, skipping
WT may be offered for sale for $280
BoB94 declines to put WT up for sale
ME may be offered for sale for $700
ME is offered at auction, buying corporation will receive $980 for treasury shares
• Action(pass) via Master Mode by DrDome:
gdc passes on ME
DrDome bids $1000 for ME
BoB94 bids $1010 for ME
DrDome passes on ME
BoB94 wins the auction of ME for $1010
GT acquires ME receiving $995, companies (Mail Contract, Minor Mail Contract, Minor Coal Mine, Major Coal Mine, Union Bridge Company), loans (10), trains (3,4,4), and tokens (8: hexes D9,C22,D7,H9,C8)
GT's share price changes from $180 to $65
ME settles with shareholders $1010 = $101 ($606 to BoB94, $-1010 to DrDome)
NYSW cannot be bought at $800, skipping
WC may be offered for sale for $1000
DrDome enters Cash Crisis and owes the bank $1007
• Action(sell_shares) via Master Mode by BoB94:
DrDome sells 3 shares PW and receives $120
• Action(sell_shares) via Master Mode by BoB94:
DrDome sells 2 shares WC and receives $200

**Comment by giovandc** [comment]
The only thing that's left to do is to declare bankruptcy, but obviously clicking the button won't work
