### ISSUE TITLE
[18Chesapeake] Route selection on OO tile in Baltimore only worked by clicking city circle, not the tile.

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#2376]
Hi,

I'm pretty new to this so I'm not sure if this is even an issue (I did try to search to see if this was an issue) but I was trying to run a route into Baltimore on the #X5 green OO tile.  Clicking the tile did not work for route selection, I had to specifically click on the connected city  (white circle) on the tile for the route selection to work.  

Game 16397, move 140 I think.

Thanks,
Vince

**Comment by roseundy** [comment]
I'm pretty sure that's normal behavior, especially with an O-O tile.
