### ISSUE TITLE
1846 game 14951 GameError: Step Buy/Use Companies cannot process

### ISSUE THREAD

**Issue by asherdiamant** [tobymao/18xx#2378]
Getting the following error:

We're sorry this game cannot be continued due to GameError: Step Buy/Use Companies cannot process {"type"=>"pass", "entity"=>"SC", "entity_type"=>"company", "id"=>108}
View the last valid action (107)
Please raise a bug report and include the game id (14951) and the following JSON data

Going to the last valid action (107) brings me to OR 1.1 which is odd as the game is in SR 4 (as you can see in the games card on the main page). 

JSON data is attached

[Game 14951.json.txt](https://github.com/tobymao/18xx/files/5571762/Game.14951.json.txt)

**Comment by asherdiamant** [comment]
And of course going to the game one more time (I tried at least 4 times above) after I open the bug and it's fine...

**Comment by michaeljb** [comment]
No worries, had to run a DB migration so some games were broken for a few minutes.
