### ISSUE TITLE
Linear market doesn't have enough vertical space for companies

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2382]
As you can see here
![image](https://user-images.githubusercontent.com/72523908/99802502-19720d80-2b38-11eb-9dfd-52d122395065.png)
The linear market does't have enough space to accomodate all the company tokens.
Having the height of the market dinamically change to accomodate all tokens could be a solution.

**Comment by jenf** [comment]
Please provide a game id to help debug

**Comment by dfannius** [comment]
When I wrote the linear market code, I automatically stretched the market vertically enough to fit all tokens, but that was when all tokens had a known constant size. You'll probably need to compute how much space each box needs by actually adding up the heights of the tokens in it (plus margins).

**Comment by dfannius** [comment]
Here's the relevant code:
```
        max_num_corps = @game.stock_market.market.first.map { |p| p.corporations.size }.push(MIN_NUM_TOKENS).max
        box_height = max_num_corps * (TOKEN_SIZE + VERTICAL_TOKEN_PAD) + VERTICAL_TOKEN_PAD + PRICE_HEIGHT + 2 * PAD
```

**Comment by giovandc** [comment]
https://18xx.games/game/15349?action=1155#market

Il giorno ven 20 nov 2020 alle ore 15:15 Jennifer Freeman <
notifications@github.com> ha scritto:
