### ISSUE TITLE
1817: 2+ trains are not being counted against the train limit in phase 4

### ISSUE THREAD

**Issue by emknell** [tobymao/18xx#2385]
In 1817, it appears that 2+ trains are not being counted against the train limit in phase 4.  In the game referenced below, GT acquires J and now has 4 trains, so should be forced to discard one of them.

https://18xx.games/game/15718?action=675

**Comment by michaeljb** [comment]
This could probably be fixed with a new config constant like `OBSOLETE_COUNTS` that defaults to `false`, 1817 can set it to `true`.
