### ISSUE TITLE
1817: Cash crisis for multiple players selects the wrong player as the next player 

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2388]
When there are multiple players who encounter a cash crisis due to holding a short share, it seems to try to resolve the cash crisis in player order which is correct, but the turn indicator for who's turn it is goes to another player who is also in cash crisis and gives them the option of selling the stocks of the first player.

Game example here: https://18xx.games/game/16569
NYOW operation created a cash crisis for Stephen_Yu and Avemo3.  It correctly showed Avemo3 as having to sell shares first, but listed Stephen as current player needing to take an aciton.

**Comment by jenf** [comment]
https://18xx.games/game/16569?action=870

**Comment by jenf** [comment]
The ui was showing Avemo3 at that point as the active player. Unsure what the bug is.

**Comment by steve-yu** [comment]
The Main https://18xx.games/ site listing the set of active games and "Your games" shows the game as orange for me, meaning that it is my action.  It may not be a game UI bug but a homepage bug?

**Comment by jenf** [comment]
Odd, I did fix a similar bug recently, maybe a different variant of it.

**Comment by jenf** [comment]
Confirmed, investigating
