### ISSUE TITLE
Game not listed after undoing "Declare Bankruptcy"

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#239]
During e-buy I pressed the "Declare Bankruptcy" button. Once I saw that it ended the game I pressed Undo. The game is still playable however it is no longer listed under Your Games, New Games, Active Games, or Finished Games. I can still access the game through the URL.

https://18xx.games/game/262

[g262_state.txt](https://github.com/tobymao/18xx/files/4561808/g262_state.txt)

**Comment by jenf** [comment]
Not fixed by #342, but should be easy afterwards
