### ISSUE TITLE
1817: Remove companies not in game from Spreadsheet view during ORs

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#2390]
Title is self-explanatory.  Currently ALL companies are shown during an OR on the Spreadsheet tab, and it's a lot of clutter to see the companies that are not currently in the game.  During the SR it makes sense to show these, but not in an OR.

**Comment by jenf** [comment]
Also 1817 corporations that close are no longer have their round info listed

**Comment by yzemaze** [comment]
@waaayback is this covered by hiding not floated corps (#4055)?

**Comment by waaayback** [comment]
yes, precisely.
