### ISSUE TITLE
1817 twenty 2 trains isn't enough

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2395]
The physical game comes with twenty 2 trains and instructions to "use a substitute if you run out." This of course doesn't work on 18xx.games. Here's a player report (copied from Slack):

_In the player counts where 12 companies often start 20 2Ts is causing non 2Ts to export and 2+ trains to be offered for sale in OR1.1_

**Comment by TIE53** [comment]
It's physically impossible for more than 40 2Ts to be purchased.  Would it cause problems to include 40 2Ts (even though in practice, 40 will never be sold)?

**Comment by tobymao** [comment]
no it's not a problem
