### ISSUE TITLE
Not all games listed on the main page

### ISSUE THREAD

**Issue by lbleicher** [tobymao/18xx#240]
I was invited to join a 1889 game (#449), but I simply could not find it on the main page. So the guy who created the game made a new one (#457), which I could find on the main page and click on join, but then the other players couldn't find it after I joined. Are we doing something wrong?

**Comment by tobymao** [comment]
Did the owner delete the game?

**Comment by lbleicher** [comment]
No (the owner was Caedrus)

**Comment by tobymao** [comment]
i'm not sure i can reproduce this. let me know if it happens again, and don't delete the games because they are deleted now
