### ISSUE TITLE
18MEX: KM&O Private should close when used

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#2400]
The Kansas City, Mexico and Orient Private Railroad should close when its ability is used to lay the Copper Canyon tile, but it currently does not.

Note that this is discrepancy between the rule book and the card in the printed game, Card is correct and the rule book is not as per the errata:
https://www.boardgamegeek.com/filepage/206976/18mex-errata

Also as indicated by the designer in this thread:
https://www.boardgamegeek.com/thread/535347/error-kcmo-private-company

The text of for the Private should probably also be updated to indicate that this will happen.

**Comment by perwestling** [comment]
I have updated the wiki page for 18MEX and will implement a correction.

**Comment by perwestling** [comment]
Fixed in #2401.
