### ISSUE TITLE
Display starting tiles more subtly

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2402]
There was a recent change to the map that colors starting tiles as just a border instead of the whole tile (e.g. Chihuahua in 18Mex). This is very confusing, as it minimizes the important feature (their color) in favor of whether it started on the map. Whether or not it was a starting tile is nice to know, but not crucial, so it should be marked more subtly, if at all.

Additionally, this style is not consistent, as built-in gray tiles are still displayed as solid gray. This is even more confusing, since gray tiles being built-in can matter; in many games, you can't direct track into the side of a built-in gray tile.

Finally, the community seems to be in agreement. On the morning of Sunday, Nov 22, in the chat, there was discussion of this feature, and 5 people other than myself expressed a desire to turn off or otherwise mute the effect of this feature.

Please either remove this UI feature outright, or at least allow us to turn it off.

**Comment by dfannius** [comment]
The original discussion that led to the current design is at #2087.

**Comment by tobymao** [comment]
@michaeljb either delete this feature completely or keep it and close the ticket, do not make it a toggle option.

**Comment by tobymao** [comment]
i think because because of the ability to view the starting map, it's not necessary to have this feature
