### ISSUE TITLE
[1817] Error that disappeared after re-entering game

### ISSUE THREAD

**Issue by RosieLeaman** [tobymao/18xx#2408]
I received an error in a multiplayer game (ID 14127), which claimed that the game could not be continued but then it could be. After taking my move (OR 5.1, NYOW attempted to pass its second tile lay) the game produced an error message:

"We're sorry this game cannot be continued due to GameError: Step Buy/Sell Shares Post Conversion cannot process {"type"=>"pass", "entity"=>"Belt", "entity_type"=>"corporation", "id"=>1323}
View the last valid action (1322)
Please raise a bug report and include the game id (14127) and the following JSON data"

After the error appeared the game refused to continue when I refreshed the page, but after going back to the 18xx homepage (in a new tab) and entering the game again, I was able to continue and complete the rest of my turn.

The last valid action linked in the error message was: https://18xx.games/game/14127?action=1322
However, we had taken many actions since then (I think we were on action 1892, game data here: https://gist.github.com/RosieLeaman/df8114880ed83db3eb825bbaed57a2fd).

Not sure if it's worth reporting, as the error did go away...

**Comment by michaeljb** [comment]
This looks like a case where a code change was made that broke your game, but then the DB migration was able to repair the game. Thanks for reporting, always good to be alerted when something looks wrong 🙂
