### ISSUE TITLE
Feature - Stock Round actions from Spreadsheet View

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#241]
> Was just thinking that it would be amazing if you could have this spreadsheet view during a stock round and have buy/sell buttons in the sheet. So with the screenshot at the top, on local4's turn, there would be a "-" or "sell" button in the "AR"/"local4" cell, and a "buy" or "+" button next to the "AR"/"IPO" cell (or it could be next to the par price cell).
> 
> When clicking the sell button, a small popup would let you choose how many to cell, and could even give you the numbers of how much you would get, maybe even the new share price after selling.
> 
> For unfloated companies, instead of "buy"/"+" next to the IPO share count it could say "par", and clicking on that pops up the par price options.

- copied from https://github.com/tobymao/18xx/pull/210#issuecomment-621599837

**Comment by jcoveney** [comment]
This would be pretty cool!! I don't think I'll take on the primary work myself, but would be happy to help out (since I have 4 spreadsheet related PRs I'm hoping to get in eventually)
