### ISSUE TITLE
Error messages should fade or have a close / X button

### ISSUE THREAD

**Issue by mtwomey** [tobymao/18xx#2416]
**Describe the bug**
This error here:
![image](https://user-images.githubusercontent.com/7715262/99985954-3561f300-2d74-11eb-8286-052fda806e72.png)

**Please provide details about your system**
 - OS [e.g. iOS13, Win10] & Device [e.g. iPhone XS]
 - Browser & Version [e.g. Chrome 83]

**Comment by dfannius** [comment]
I've been meaning to suggest this myself. The error bar could really use an X (even if clicking there does exactly the same thing as clicking anywhere else) to indicate that it's closeable.

**Comment by daniel-sousa-me** [comment]
For some reason I find the idea of just putting an X somewhere that doesn't do anything new really funny

**Comment by tobymao** [comment]
dup of #247
