### ISSUE TITLE
[1846] Page freezes if last corporation closes

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2418]
I wanted to see if I could engineer a scenario where no player has cash, privates, or shares. This is possible to do by collusion between players and extremely poor play.

When I did this in a hotseat game the page freezes once it gets to the action where the last corporation (in this example IC) closes.

Here is a gist for the game data for the hotseat game

https://gist.github.com/ventusignis/8b01d54cbea466b6f9f3cb078fcace06

**Comment by michaeljb** [comment]
Hah! I've known for quite a while that this situation wasn't handled but since it'll never happen in a "real" game I figured there was no rush to handle it before a user reported it :wink:

**Comment by ventusignis** [comment]
From my reading of the rules, the game does not end in this case, despite no players having any legal actions to take
I propose that if 1846 gets stalemated this way, the game ends immediately with a message "Game ends in stalemate. Everyone loses" :)

**Comment by michaeljb** [comment]
I figure if any players still own a private company that pays each OR, the game can run till the bank breaks, otherwise just show the normal game end screen. Though shaming the players for their silliness does sound fun :joy:

**Comment by tobymao** [comment]
seems unnecessary to handle
