### ISSUE TITLE
Enforcing Private's A power

### ISSUE THREAD

**Issue by richardtempura** [tobymao/18xx#243]
A way to block K4, until it's sold....

**Comment by jenf** [comment]
Yep, added to the bucket of rules we don't enforce fulyl.

**Comment by jenf** [comment]
Rule is 15.1. A and C block laying on tiles until owned by corporations

**Comment by jenf** [comment]
Following games break when enforcing this
# gameid, move, reason
253,117,C4 is blocked by Ehime Railway
* Active
361,129,K4 is blocked by Takamatsu E-Railroad
Dead
475,60,C4 is blocked by Ehime Railway
Complete
529,92,C4 is blocked by Ehime Railway
* Active
506,106,K4 is blocked by Takamatsu E-Railroad
* Active
521,69,C4 is blocked by Ehime Railway
Complete
625,187,K4 is blocked by Takamatsu E-Railroad
Complete

**Comment by jenf** [comment]
reopening due to rollback
