### ISSUE TITLE
[1817] On the take loans step after liquidation, the game should show the card of the acquiring corp

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2430]
https://18xx.games/game/16711?action=1536

Now it is showing the card of the liquidated corp. I think this step should be taken after the assets are transferred.

I understand that this happen because of acquisitions and friendly sales. I would implement that on the different way: the defunct corp always returns all its loans, possibly ending up with negative cash, then all the assets are transferred. After the old corp is removed, the new one get the chance to take new loans. If the cash is negative, some of those loans are not optional.
This is similar to what happens in SR1 when you're paying for the bid.

**Comment by daniel-sousa-me** [comment]
Just a clarification: I see what I wrote in the title as a (very minor) bug, but everything else is just a suggestion of how to tackle it

**Comment by jenf** [comment]
Original tried this but it caused problems in games
`
diff --git a/lib/engine/step/g_1817/acquire.rb b/lib/engine/step/g_1817/acquire.rb
index d3c817b5..3b0635a4 100644
--- a/lib/engine/step/g_1817/acquire.rb
+++ b/lib/engine/step/g_1817/acquire.rb
@@ -444,7 +444,7 @@ module Engine
         end
 
         def auctioning_corporation
-          @buyer || @offer || @auctioning || @winner&.corporation
+          @offer || @auctioning || @winner&.corporation
         end
 
         def setup
`
