### ISSUE TITLE
Semantic tagging of Info, Entities, and Spreadsheet pages suitable for scraping

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#2433]
It would be great to be able to do some post game analysis by scraping (e.g. using something line [Scrapy](https://scrapy.org)) information from the Info, Entities, and Spreadsheet pages, but currently the elements on those pages are not tagged or structured in way that facilitates this. This could be addressed by adding informative `id` tags to elements on those pages.

**Comment by tobymao** [comment]
won't do this, the json api is available

**Comment by orome** [comment]
> the json api is available

Excellent — much better! [Is it documented?](https://18xxgames.slack.com/archives/C012K0CNY5C/p1624454675372000)

**Comment by tobymao** [comment]
no, only in the code
