### ISSUE TITLE
Can't take presidency in a company when at cert limit

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#244]
jcl mentioned this might be a bug, and I confirmed it is.

Player B is president of Company 1
Player A is at cert limit and has equal shares to Player B in Company 1

Player A should be able to buy a cert for Company 1

Rspec to reproduce
`
      it 'can buy when at cert limit when doing so would gain you the presidency' do

        player_0.cash = 10_000
        player_1.cash = 10_000
        market.set_par(corp_0, market.market[2][4])
        market.set_par(corp_1, market.market[2][4])
        market.set_par(corp_2, market.market[2][4])
        market.set_par(corp_3, market.market[6][0])

        # Make player 1 president
        3.times { game.share_pool.buy_share(player_1, corp_0.shares[0]) }

        # Get player 0 to the same quantity and to cert limit
        4.times { game.share_pool.buy_share(player_0, corp_0.shares[0]) }
        4.times { game.share_pool.buy_share(player_0, corp_1.shares[0]) }
        3.times { game.share_pool.buy_share(player_0, corp_2.shares[0]) }# at 6-player cert limit

        # Double check it's player 0 to operate
        expect(subject.current_entity).to eq(player_0)
        # Check player 1 is actually the president
        expect(corp_0.president?(player_1)).to eq(true)

        expect(subject.can_buy?(corp_0.shares[0])).to eq(true)
      end
`

**Comment by sparr** [comment]
Can you elaborate on how you confirmed that this is a bug? This behavior matches my reading of the English rules.

**Comment by jenf** [comment]
Actually I think your right, JCL mentioned it might be an issue but then said the rules disallowed it, I should've read the rules fully first :)

**Comment by tobymao** [comment]
this is a good spec can we merge that?

**Comment by jenf** [comment]
You mean flipping the expect to false as it was failing, i can put it on my current PR.

**Comment by tobymao** [comment]
cool, so just to clarify, duogo exchange respects the current share buying and ownership right?

**Comment by jenf** [comment]
PR #246 only shows it,  however the old interface i think allows you to transfer the shares even if your not at limit. I'll add the check into PR #246

**Comment by jenf** [comment]
Yeah, you can go over the limit in the current implementation.
