### ISSUE TITLE
18MEX Copper Canyon value marker partially off-hex

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2442]
The 20 value for the Copper Canyon is partially out of the hex.

<img width="214" alt="Screen Shot 2020-11-24 at 8 57 06 PM" src="https://user-images.githubusercontent.com/8732435/100186684-4fe2bc00-2e9b-11eb-9317-6740fba50f06.png">
<img width="222" alt="Screen Shot 2020-11-24 at 9 22 40 PM" src="https://user-images.githubusercontent.com/8732435/100186687-52451600-2e9b-11eb-9514-8c072c8b0089.png">

**Comment by benjaminxscott** [comment]
Looks like this is fixed now
ref: https://18xx.games/game/33135?finished=4

![Screen Shot 2021-03-19 at 12 11 10 PM](https://user-images.githubusercontent.com/1711810/111831160-33d0b380-88ac-11eb-9601-365eb2b6e750.png)

**Comment by benjaminxscott** [comment]
nevermind it's still messed up in some of the other orientation

**Comment by scottredracecar** [comment]
new link to specific action
https://18xx.games/game/33135?action=168#map

This could be fixed with added collision detection
