### ISSUE TITLE
[1817] Disallow buying shares of corporation in acquisition area

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2444]
https://18xx.games/game/16711?action=1652

5.6

> If a player decides to act on behalf of a company instead of taking action himself, he must perform one or both of the following actions in this order for any one company for which he is president and whose share price is not in the red liquidation or gray acquisition areas of the stock market

**Comment by jenf** [comment]
Don't think i've fixed anything in the share round, so still valid even if it's a pinned game.
