### ISSUE TITLE
Cannot end/remove games 14289 and 14395

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#2455]
I have two games with bugs that I can’t end/remove. I’m sure this is somewhere and I read the wiki and cannot find it. 
They are (14289) and 14395
Thanks!
Jen

**Comment by perwestling** [comment]
I went to https://18xx.games/game/14289#tools and https://18xx.games/game/14395?action=1490#tools
"End game" appear on both.

So what happens when you click on End game?

**Comment by Eludyan** [comment]
So the game was not appearing at all before. Only the error screen. I’ll end the one now. The other still has the error:

We're sorry this game cannot be continued due to GameError: Invalid bid, valid bids are 0 + cash 272
View the last valid action (1490)
Please raise a bug report and include the game id (14395) and the following JSON data

Thanks!

**Comment by jenf** [comment]
i can delete the last action which caused the problem on 14395.

**Comment by jenf** [comment]
resolved.
