### ISSUE TITLE
18Mex stuck on trains buying 

### ISSUE THREAD

**Issue by shingoi9** [tobymao/18xx#2457]
**Please provide**
* 18Mex (Id: 15756)

**Describe the bug**
When pressing Skip (Trains) nothing happens and game is stuck on train buying phase of UdY

**Comment by perwestling** [comment]
This was a bug when using the Optional Rule of Delay minor close. It works to delay the minor close until the SR (in the game in question, SR 6), but for some reason the game tried to do minor close also when SR 7 were to start.

Have added the missing one liner which fixes the games using this optional rule, and will push a correction.
