### ISSUE TITLE
[18MEX] Put towns with cost=0 so that they don't show up in the stop count when running trains

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2461]
As it is right now when the train runs through a town it increases the stop count shown for the train and then we need to "manually" count the actual stops.

**Comment by daniel-sousa-me** [comment]
Or maybe improve the stop count to show separately things with different limits

**Comment by roseundy** [comment]
I doing the latter for 1860

**Comment by perwestling** [comment]
This is not an 18MEX specific thing.

**Comment by daniel-sousa-me** [comment]
I know there are a few more games with the same thing, but Mex is the one I've been playing. This cost option is something that already exists. You can just add it to the config file.
This would not work for 18MS, because it is a configuration of the revenue centre and not the train, but Steve's thing would be great in both. I don't know anything about 18AL.

**Comment by perwestling** [comment]
18AL works in the same way as 18MEX.

**Comment by ryandriskel** [comment]
This was accomplished with `require_relative '../cities_plus_towns_route_distance_str'`
