### ISSUE TITLE
1817 half pay 2 share company value shown incorrectly

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2464]
In this scenario when half paying, the 2 shares will each pay 42.5, for a total of 85. Displaying 42/share implies that the president will receive 84.

<img width="354" alt="Screen Shot 2020-11-27 at 1 40 47 PM" src="https://user-images.githubusercontent.com/8732435/100485828-6ca70b80-30b6-11eb-84df-2ab8e940aae1.png">

**Comment by jenf** [comment]
Please provide a game id that shows this.

**Comment by ChrisTheCat** [comment]
https://18xx.games/game/16764?action=393
