### ISSUE TITLE
Test for liquidation shown slightly wrongly.

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#2468]
Minor issue with 1817 - We had a company looking like this.  It had exactly enough money to avoid liquidation but was shown as being at risk. Game is still going on - game is https://18xx.games/game/17117
![image](https://user-images.githubusercontent.com/11814681/100491168-79108000-3119-11eb-913c-c39837ba767e.png)

**Comment by jenf** [comment]
https://18xx.games/game/17117?action=369
