### ISSUE TITLE
Login error message does not clear

### ISSUE THREAD

**Issue by pottsie** [tobymao/18xx#247]
When I try and log in to the site, and use the wrong username, I get an error "Could not find user". When I correct my username, and log in successfully, the error persists at the top of the page. See image below.
![image](https://user-images.githubusercontent.com/4276768/80804032-ed824100-8b81-11ea-8ac6-cf2d481dcad3.png)

**Comment by jenf** [comment]
This is more generalized, error messages do not clear automatically.

**Comment by jcoveney** [comment]
Yeah per jenf, if you click it it will go away, but it not clear that that is the way to get rid of it.

**Comment by mtwomey** [comment]
Yeah, it's not clear. I even opened a duplicate issue to this one, because it's not clear. I'd prefer an auto-fade on these personally.
