### ISSUE TITLE
18LosAngeles

### ISSUE THREAD

**Issue by Panzerlied7** [tobymao/18xx#2473]
Not sure if this is an issue but our recent game of 18LA (#17137) did not send out a Game Results email and does not show up in the Finished Games list. It does appear in my account. 

Additionally, game 11561 (18MS), for which I have an email is now missing from my Account - although 11551 (18TN) played on the same day is still there - although the date 2020-11-16 is incorrect. The date for 7778 (also 18TN) also seems to have been changed to 2020-11-16. Very odd. 

JimA

**Comment by tobymao** [comment]
games sometimes get deleted. dates are last move dates

**Comment by Panzerlied7** [comment]
Are you still sending out Game Results email? As I did not receive one for our  most recent game (17137).

Are you saying that the system randomly deletes game entries? All of my games are played live and the games mentioned were completed on October 3rd not 16 Nov.

**Comment by tobymao** [comment]
End game emails should still be sent out. I delete games occasionally, it's not random. It's based on age and if the game is broken etc.
