### ISSUE TITLE
Turn not showing on Home Screen

### ISSUE THREAD

**Issue by yraelrocks** [tobymao/18xx#2474]
18Mex game - my turn but it’s not showing on the Home Screen, pinned version (63cf94ea)

![717A56D2-6D6C-4403-A574-BAD5BA67EF29](https://user-images.githubusercontent.com/64525475/100522600-3f378c00-31a2-11eb-825f-820d777bdcf8.png)

![EAF07CAC-B77F-4CAA-B085-43E3B811B1DE](https://user-images.githubusercontent.com/64525475/100522605-4363a980-31a2-11eb-9e66-daba311ad425.png)

**Comment by jenf** [comment]
should be resolved now
