### ISSUE TITLE
Undoing after run routes presents apparent option to submit for double the money

### ISSUE THREAD

**Issue by MalkD** [tobymao/18xx#2476]
Issue arose in game of 1846
https://18xx.games/game/15252?action=432

Steps:
In OR 6.1  B&O submitted routes for 610
Next player accidentally pressed Undo.
I realised I could get 620, so pressed Undo once to clear previous submit
Trains appeared blank, so filled then in.
Submit button said "Submit for 1230"  being 610+620
I decided not to press this.
Cleared all trains and redid submission.
The link is copied from the spreadsheet after this happened.

Trains for the 610 were the same as the previous run
B&O runs a 4/6 train for $270: I1-(I5)-E11-E17-(G19)-G21 + E/W
B&O runs a 5 train for $320: C5-D6-C15-C17 + E/W
But with improved cities

Trains for the 620
B&O runs a 4/6 train for $250: D6-E11-E17-(G19)-G21
B&O runs a 5 train for $370: C17-C15-E11-D6-C5 + E/W

I didn't take a screenshot of the button.

**Comment by michaeljb** [comment]
Cloning at action 430 and hitting "undo" gets me this screen, with apparently no routes selected, but "Submit $610" visible:

![Screenshot from 2020-11-28 17-21-44](https://user-images.githubusercontent.com/1045173/100528843-6b510e00-319e-11eb-9076-580e6187deaf.png)

I can enter in a route for a train, and it shows the combined total of the previous run and the new route I've entered:

![Screenshot from 2020-11-28 17-24-03](https://user-images.githubusercontent.com/1045173/100528870-abb08c00-319e-11eb-8fbf-3f479cc0fb4b.png)

Attempting to submit that invalid amount throws an error and resets the trains correctly:

![Screenshot from 2020-11-28 17-24-28](https://user-images.githubusercontent.com/1045173/100528875-bc610200-319e-11eb-8762-4147ce86fecd.png)

So the good news is that it won't allow entering the double-counted routes, but it is still a UI bug.

**Comment by michaeljb** [comment]
saving a copy of the game JSON; to reproduce the issue, create a new game with it and then hit "undo" - https://gist.github.com/michaeljb/c24bc5f412c4d26925d5e4eee94ca34a

**Comment by michaeljb** [comment]
I was able to reproduce this in 18Chesapeake, using one of the games saved as a test fixture - https://18xx.games/game/1277?action=204

It seems this is repeatable by undoing immediately after running routes (ie, clicking on undo at the dividend screen), if the corporation ran two trains. With a single train (ie https://18xx.games/game/1277?action=198), it still shows no route while showing the amount to submit, but you cannot start entering a route for another train and have it add to the total

**Comment by tobymao** [comment]
can't repro
