### ISSUE TITLE
[18MEX] Game 17170 locked up...

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#2480]
It just says “Loading game...”

I can get into other games and my hotseat game, but this one does not want to load.

Is there anything that can be done? Or is it just crashed?

**Comment by SmithInMN** [comment]
I just talked with my group and the player last to act had just bought in the Copper Canyon private early when she said the game crashed...

And yes, we had that option enabled, so it should have been a legal move.

**Comment by perwestling** [comment]
OK found it. It was caused by a recent change that closes KCM&O when ability is used.
Have a fix that I will merge, so hopefully the game will be back tomorrow.

**Comment by SmithInMN** [comment]
Thanks for the great work getting this up and running again!  We really appreciate it.  Quality work!
