### ISSUE TITLE
Unable to use generated passwords on Password Reset page

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#2491]
The password reset screen does not play nicely with iOS generated strong passwords.

The generated password is automatically entered in both the Temporary Password and New Password fields.

Attempting to paste the temporary password from the reset email into the Temporary Password field causes the New Password field to be cleared. 

iOS appears to treat the fields as new/confirm fields and expects them to be the same. 

Manually entering values in each field works fine. 

Could there be an issue with how the fields are named or tagged in HTML? 

Using Safari for iOS13, on IPhone 8

**Comment by jenf** [comment]
can't seem to reproduce but I don't have an iPhone tried with browserstack. We are following the standard correctly and Chrome and Chrome Android seem fine

**Comment by tobymao** [comment]
closed for now
