### ISSUE TITLE
18MEX game stuck, can't buy NdM

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2495]
It's ChrisShaffer's turn. I can click every charter to get a list of options (buy IPO, buy market, sell) except NdM. Clicking the NdM charter results in... nothing. No error, no option to buy or sell, it's just not clickable.

**Comment by perwestling** [comment]
Have you checked the console? 

Which game is it? Is it still a problem after the latest bug fix?

**Comment by ChrisTheCat** [comment]
Oh, sorry, I thought I linked to it. Here it is: https://18xx.games/game/15284

I'm pretty sure the problem was related to the fact that cdlietz just sold the 5% NdM share.

I checked several times last night and it wasn't working for the entire evening, but now in the morning the problem seems to have disappeared.

**Comment by ChrisTheCat** [comment]
p.s. I have no idea what "the console" is or how it would be checked.

**Comment by perwestling** [comment]
Sorry, the console thing is a developer thing. It is sometimes possible to see why a game behaves badly that way.

So, should I close this issue if it is no longer a problem? Probably fixed by one of the corrections yesterday.

**Comment by ChrisTheCat** [comment]
RIght
