### ISSUE TITLE
[1889] Denied option to use Dougo Railway share exchange in SR1 after running out of money

### ISSUE THREAD

**Issue by ckarlof** [tobymao/18xx#2496]
In [SR1 of this 1889 game](https://18xx.games/game/17098?action=26), I was out of money, but had the Dougo Railway private, which I believe entitles me to exchange it for a share of the IR anytime during a SR. 

Expected behavior: Even though I was out of money in SR1, I would still be given the option to exchange the Dougo Railway for a share of the IR when it was my turn.
Actual behavior: When I ran out of money in SR1, the game skipped my turn automatically without giving me this option. 

I thought I would need this action to float the IR in SR1, because I only had money to buy 4 shares. Luckily another player floated it for me, so I was happy to keep the private to buy-in, but I wanted to report this issue.

**Comment by benjaminxscott** [comment]
Propose as dupe of #1567, in that issue a workaround of "Undo and trade in the private on any players turn" was mentioned, if that works for your particularly game?

**Comment by ckarlof** [comment]
I agree this is a dup of #1567. I'll post my thoughts on the suggested workaround in that issue.
