### ISSUE TITLE
Solo mode local storage

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#25]
Right now solo mode has no storage, so a refresh will kill the game.

When playing solo mode, we should 

1. generate an ID to save the game
2. save the game in local storage by the id, you can use Lib::Storage
3. Add someway from the homepage to get access to these local games
4. The API should simply route to the local action
5. import and export these actions

**Comment by tobymao** [comment]
@lkingsford

**Comment by lkingsford** [comment]
Sorry - wanted to help, but I think open it up again. Need to work on Ruby/Opal fundamentals a little more before being able to deliver this in a timely manner.
