### ISSUE TITLE
1817 - Cash Crisis resolved slightly late

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2501]
Game link: https://18xx.games/game/15729?action=919

gatesman entered Cash Crisis while settling UR's debts, but the game triggered it at the start of Belt's liquidation.

**Comment by jenf** [comment]
really it's just a logging artifact, it'll be a bit complex to resolve this.

**Comment by Auzzy** [comment]
Makes sense. Figured I'd report anyways, in case there was something deeper going on.

**Comment by jenf** [comment]
It'd take a massive effort to fix it
