### ISSUE TITLE
[18MEX] nothing rusts 2s in info

### ISSUE THREAD

**Issue by arcee1986** [tobymao/18xx#2508]
In the info tab, the 4 trains are not described as rusting the 2s.

4 | $300 | 3 | None | None

Variants on: Extra yellow, delay minor close
ID: 17097

**Comment by TIE53** [comment]
This bug only seems to occur when the "delay minor close" variant is selected.

**Comment by perwestling** [comment]
Have located the bug and fix them.
You can continue to play - the trains will rust when 4 train is bought. It is just the Info table that is wrong.

**Comment by perwestling** [comment]
The fix caused problems in other games so we need to fix this in another way.
