### ISSUE TITLE
L when choosing par price doesn't take into account already-bought shares

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#2511]
When you set the par price and get buttons like "$67 (6 L)" and "$71 (5)", the number in parentheses shows how many shares you can afford to buy at that price and the L shows whether that number is sufficient to float the corporation. But the L calculation doesn't take into account shares that have already been moved out of the IPO (probably due to privates like 1830's C&A).

Here's an example from 1836Jr:

<img width="300" alt="Screen Shot 2020-12-01 at 10 39 49" src="https://user-images.githubusercontent.com/1295244/100762603-2ad1da00-33c2-11eb-879f-36a91f3c72ac.png">

The last two buttons should be "(5 L)" rather than "(5)", as only 5 additional shares need to be purchased to float the corporation.

**Comment by michaeljb** [comment]
I thought the L indicated you would be at the limit of how much you can hold of one corporation, not that the corporation can float. For instance, in 2p 18 Los Angeles, corporations float at 20% and players can hold up to 70%; the par price selection looks like this:

![Screenshot from 2020-12-02 18-02-26](https://user-images.githubusercontent.com/1045173/100949991-9dc57880-34c8-11eb-892b-357cc5e59dcd.png)

To see if you can afford to float a corporation on your own, you just need to look at the "50% to float" and compare with the number of shares you can afford. Do you want some other indication on the par price button that you are able to float the corp yourself?

**Comment by dfannius** [comment]
I guess that explains why it's an L and not an F! I think the amount needed to float is clear enough from the "N% to float" text. I'll close this.
