### ISSUE TITLE
[1889] trains didn't rust

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#2513]
**Describe the bug**
Please take a look at info tab at 199th game step:
https://18xx.games/game/16683?action=199#info
6-train will rust 3-train, right?
take one step further:
https://18xx.games/game/16683?action=200#info
and now it says 6-train rust no trains.
How cool is that?

And now, we are at step 431. Info tab says no trains will rust. Ever....
https://18xx.games/game/16683?action=431#info

Somehow we manage to rust 2-trains...

**Please provide details about your system**
 - Ubuntu 18.04.5 LTS
 - Firefox 83.0

**Comment by tobymao** [comment]
@perwestling i believe this is due to your change

**Comment by perwestling** [comment]
The trains will rust, even though the Info does not state this.

Will revert the fix I made as it only solved a minor problem in 18MEX.
