### ISSUE TITLE
1817NA info tab missing train rusting information

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2520]
https://18xx.games/game/17578?action=222

Doesn't say that 2 and 2+ rust on 4

<img width="718" alt="Screen Shot 2020-12-01 at 7 37 49 PM" src="https://user-images.githubusercontent.com/8732435/100825405-cee07300-340c-11eb-8a54-85cc5bde69f8.png">

**Comment by ventusignis** [comment]
I found a possible cause for this - it looks like the Obsoleted by column is removed when the last 2+ is sold
https://18xx.games/game/17578?action=178#info
![image](https://user-images.githubusercontent.com/2993555/100827069-d7937200-3429-11eb-947d-bbf795814d09.png)

https://18xx.games/game/17578?action=179#info
![image](https://user-images.githubusercontent.com/2993555/100826962-900ce600-3429-11eb-8fab-9c2a9bd067a8.png)

**Comment by ChrisTheCat** [comment]
Your first image shows the correct phases out information, but still shows "none" for rusts on 4

**Comment by tobymao** [comment]
dup and fixed
