### ISSUE TITLE
[1882] Info tab showing no trains rust on 6, D

### ISSUE THREAD

**Issue by McCoy9000** [tobymao/18xx#2524]
Hi, great job with the game. Thank you!
On O.R 6 of game 17074 on Android I notice that my info tab says no train will rust on 6 or D trains. My fellow players info tabs show the correct info. Not a great deal since I could undo my play. Leaving and reentering the game resets it to normal.
![Screenshot_20201202-171124__01](https://user-images.githubusercontent.com/17376365/100900155-d3676300-34c2-11eb-8d37-d65f3ccf6888.jpg)

**Comment by tobymao** [comment]
refresh your browser
