### ISSUE TITLE
Theming option: Fancy tiles and map

### ISSUE THREAD

**Issue by AndreSteenbergen** [tobymao/18xx#2530]
I like 18xx.games in all functionality. I personally would like to see theming. I would personally like a more fancy tile. I already made some SVG files for 18MEX. I kept zoomability in mind so tiles would also look nice on smart-phones. Would you consider a pull request (in the long run) with a theming option and have the tiles and map rendered differently.

I attached the pdf's generated using the SVG's I already made.

[tile-manifest.pdf](https://github.com/tobymao/18xx/files/5634423/tile-manifest.pdf)
[tile-manifest-no-sharp-edges.pdf](https://github.com/tobymao/18xx/files/5634424/tile-manifest-no-sharp-edges.pdf)

**Comment by roseundy** [comment]
This would take a large amount of effort. The tiles are generated programmatically. The Mexico City tiles, in particular, can never be rendered in the way you suggest.

**Comment by AndreSteenbergen** [comment]
I understand, I did say in the long run ;) 9/10 tiles aren't that hard to generate, most of them are 4-6 lines of svg. For example:

```
 <svg 
    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 230.940107676 200">
    <link xmlns="http://www.w3.org/1999/xhtml" rel="stylesheet" href="svg.css" type="text/css"/>

    <g>
        <use xlink:href="defs.svg#green" />
        <use xlink:href="defs.svg#hexcorners" />

        
        <use xlink:href="defs.svg#straight" />   
        <use xlink:href="defs.svg#tight-left" />

        <text class="tilenr">27</text>    
    </g>
</svg> 
```

**Comment by AndreSteenbergen** [comment]
Only parts that are nearly impossible to render are the company home towns.

**Comment by tobymao** [comment]
probably not, it adds too much complexity
