### ISSUE TITLE
Market boxes do not grow properly in certain circumstances

### ISSUE THREAD

**Issue by myNameIsFourteen** [tobymao/18xx#2531]
1817
Game ID 15799
Pinned to Version: 5f8239fb

If 5 or more corps have the same stock price, icons for the corps after the 4th hang off the bottom of the market graphic. Could the market boxes be dynamically made taller if there are extras on the same price?
![image](https://user-images.githubusercontent.com/3456680/101057746-64d5e400-355a-11eb-9a74-492802a08ecd.png)

**Comment by dfannius** [comment]
The code is attempting to do this, so there is a bug.

**Comment by michaeljb** [comment]
5f8239f is a couple weeks old, I just tried out a hotseat game and the market resized correctly:

![Screenshot from 2020-12-04 19-32-35](https://user-images.githubusercontent.com/1045173/101231305-8f619300-3667-11eb-91c4-404328d856a0.png)
