### ISSUE TITLE
Very laggy interface on mobile devices

### ISSUE THREAD

**Issue by yraelrocks** [tobymao/18xx#2533]
Turns get out of sync easily, refresh very slow & over multiple users. Particularly 1817 game: 14388

yrael - iOS 14.2 iPhone 11 Safari

**Comment by yraelrocks** [comment]
Sunnd: Chrome on MacBook (work)plus windows (home) and iOS 14 (mobile) are the 3 platforms I use.

**Comment by yraelrocks** [comment]
Phil: Windows on an Acer laptop and whatever OS samsung currently has on an S7

**Comment by jenf** [comment]
yeah, 1817 seems to really stress the code out, we probably need to see if any performance improvements can be made especially with tile laying (which seem to take the majority of cpu time)

**Comment by jenf** [comment]
One potential improvement. Skip rebuilding the graph if a tile has no revenue centers and doesn't connect to another tile.

**Comment by jenf** [comment]
To fix this the connections code needs a rewrite. We should not generate connections while processing previous moves (similar to how the graph is mostly done). Then only calculate when needed.

**Comment by tobymao** [comment]
this has been fixed. 26 seconds -> 4 seconds for game 18300
