### ISSUE TITLE
1817 asked to buy share on conversion even though not enough money

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2536]
https://18xx.games/game/17767?action=540

DrAwesome has a short in the converted company, but doesn't have enough money to close it. And, of course, he can't sell it.

**Comment by ventusignis** [comment]
Is the expected behavior that DrAwesome is skipped automatically due to being unable to do anything but pass?

**Comment by ventusignis** [comment]
I was able to replicate this in base 1817.
https://gist.github.com/ventusignis/b1fb8f2a89bf0efceae7fbaaed25e86d

**Comment by ChrisTheCat** [comment]
Yes, he should have been skipped. He had no legal actions other than passing.

**Comment by jenf** [comment]
It's probably getting confused due to the short.

**Comment by jenf** [comment]
yeah, the short.
