### ISSUE TITLE
Add 'finished game' state, for better archiving and game stats

### ISSUE THREAD

**Issue by tom-blight** [tobymao/18xx#2540]
I like to refer to past games on the 'your finished games' section in the player profile. 

Usually I will go there to add game results to my play tracker, and sometimes I'll go back and review a particular game. 
Often though I find the finished games to be sorted in a different order, since the 'Ended:' field is actually just displaying the date of the last activity, which could be a continuing conversation in the message box or someone hitting undo-redo after the game is finished.

I love the idea suggested here: https://github.com/tobymao/18xx/issues/1490 for end-game stats, and I wonder if this could be an opportunity for each player to press a button to confirm moving the game into 'game-end' state. Then a true game-end timestamp can be recorded and used to sort finished games. This timestamp would then ignore further player activity such as chat, and perhaps lock in the state of the game (no undos after all players confirmed game end).

**Comment by tobymao** [comment]
no i don't think so, if anything it should change you can just make the sort order different
