### ISSUE TITLE
Add Train roster to Entities and Spreadsheet tabs

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#2541]
The site UI can be improved. To do that, you should take in consideration two user types. The desktop user and the mobile user.
Every change in UI, unless they are separated (they aren't right now, and I guess it would be a pain to do so), should take in consideration both environments.
One of the shortcomings of the actual UI is that the informations are too scattered around and should be regrouped and organized on a functional criterion.
The "Game", "Entities", "Market" and "Tools" tabs are fine as they are, right now.
The "Map" and "Tiles" tabs can be merged together to avoid jumping between the two to check the tile roster and then decide where to expand your routes. Which is literally the way rr18xx handles this. The tile roster can be placed horizontally under the map, or vertically at the left of it. Right now I guess the tiles tab isn't used much since the UI actually suggests you what tile can be placed if you click on a hex, but for games with complex tile roster you should always be able to look at the map and the tile roster simultaneously. And we all know that having two separate tabs opened in a browser, one set on the map tab and one on the tiles map can be really taxing on the resources of the device you are using.

The info and spreadsheet tabs literally have, taken together, all the information needed to decide your action during a stock round. When you act, you want to know in which phase you are right now, how many trains are left, how many trains the company has etc. Qualititatively, they are all part of a single block of information needed to act tipically during a stock round., so it's only natural to group them in a single tab, similarly to this concept.

![image](https://user-images.githubusercontent.com/72523908/101161654-70480e80-3631-11eb-8ac6-511a5077633e.png)

As a matter of fact, the inexperienced player will always go look at the info tab to keep track of the progress of the game and of the trains; the expert player will too, but way less, probably only to check the trains.
Any change should take in consideration every kind of user, both newcomers and veterans, right now having the info and spreadsheet information separated is more of an issue for the noobies than for the experienced players. In 1817 it might take me just a glance at the info tab , after that I can focus only on the spreadsheet, since I've played it many times and memorized the train roster and phases.
A newcomer might forget it really easily. Then, when analyzing the situation on the spreadsheet, he'll have to switch between spreadsheet and info tabs way more than an experienced player. And that is annoying, because it's fixable extremely easily, given that the spreadsheet and info tabs are mostly empty.
As shown in the concept I posted previously, rearranging the elements on the info tab on the "top" of it while leaving space for the spreadsheet under that will make the info tab actually complete, with all the needed info in one single place, without any need to annoyingly switch between tabs.
All the arguments against this proposal don't sound convincing.

- It will make the experience better not only for the experienced player, but (expecially) for the newcomers too, so it caters to everyone.
- The scrolling argument is not convincing. 1920x1080 fits the concept perfectly, 1366x768, the most common resolution after that, fits it with only a little bit of scrolling needed to see the cut off 10% portion of the spreadsheet. But, at that resolution, every other tab will need scrolling, so why is it an issue only for the info/spreadsheet one? Same for mobile, this change wouldn't change practically the amount of scrolling needed to use the site. It won't require a higher resolution from desktop too. It basically doesn't require anything, resolution wise. Here's the difference between height of the concept and the actual info tab
![image](https://user-images.githubusercontent.com/72523908/101161834-bc934e80-3631-11eb-879a-6d592097b748.png)
- It's a _tested_ and _working_ concept, since it's basically a lighter version of rr18xx main view.
- One could also argue that a player might not be interested in using the spreadsheet. That's not a problem! You can simply not look at it. All the "old" info is regrouped on the higher half of the tab, with a nice natural division made by the first line of the spreadsheet. Hence, visually, it isn't a hindrance for those who don't use the spreadsheet.

**Comment by daniel-sousa-me** [comment]
As I've written in Slack, I strongly oppose this change because it forces me to scroll every time I open the spreadsheet tab. This is really inconvenient since I spend most of my game switching between the "Game", "Spreadsheet" and "Map" tabs.

The "scrolling argument" is not an argument. Is me telling you how this change affects the way I play.

This is not the same as in rr18xx, because there the spreadsheet show before the info.

**Comment by giovandc** [comment]
As newcomers have commented on slack, your argument is that you don't use the info tab since you know it by memory, while they don't, since they are not such expert players.
The site should be optimized for everyone.

**Comment by daniel-sousa-me** [comment]
Please stop telling me what I said. That is not what I said.

**Comment by jenf** [comment]
Seems like the main pinch point is that the train roster is not where it needs to be namely Entities and Spreadsheet.

So I'm proposing to resolve this:
* We add a simplified Train card under the Bank on entity/right on spreadsheet for the train roster that shows the upcoming trains
* It only has very limited information and so doesn't fully replace the Info tab, but will mean that it's needed much less
* I'd like to hide the unstarted corporations on the 'Bank' part of entities for games where they are effectively undistinguised (e.g. (1817,67)) and just replace them with a numerical number of how many is left.
* Some people would like the number of loans shown even when they're zero so they can see the corp size (this would remove the corporation size field)
* Long term, maybe think about allowing the entities view to be seen on the game tab during stock round.

**Comment by daniel-sousa-me** [comment]
> Some people would like the number of loans shown even when they're zero so they can see the corp size (this would remove the corporation size field)

#2412 adds the size of the corporation to the card

> Long term, maybe think about allowing the entities view to be seen on the game tab during stock round.

I like the idea of having a toggle (that can be stored in LocalStorage) between the 2 views. Actually a lot of these things could be customisable in this way, but I'm guessing Toby won't be a huge fan of that.

**Comment by bridger15** [comment]
Ooo, i really like these suggestions.  +1 for combining info and spreadsheet.  I'd much rather scroll than bounce between two tabs.
