### ISSUE TITLE
1817 lockup when receivership company tries to operate

### ISSUE THREAD

**Issue by myNameIsFourteen** [tobymao/18xx#2543]
GAMEID: 15799
Pinned to Version: 5f8239f

Player 3 went bankrupt during OR 4.1, placing several companies (B&A, J) that had not yet operated entirely into the bank pool.
When B&A's turn in the operating order, it was not skipped, instead the game prompted the last player who acted to select the best possible routes for B&A's trains, although the prompt did not match the trains that B&A actually had at the time. The player was unable to actually enter a route OR click submit $0.

After this point, any attempt to enter the game from the dotGames home screen has led to a blank page. The game appears to be stuck.

Screenshot of the strange prompt attached.
![image](https://user-images.githubusercontent.com/3456680/101202145-dc794100-3636-11eb-95b0-a285edb25ae6.png)

**Comment by jenf** [comment]
Yeah, your on a pinned version. I can only delete the game.

**Comment by myNameIsFourteen** [comment]
If you could please delete the game, that would be nice to clear off our dashboards.
