### ISSUE TITLE
1817: Shorts held by bank pool after bankruptcy are invisible

### ISSUE THREAD

**Issue by myNameIsFourteen** [tobymao/18xx#2544]
GAMEID: 15799
Pinned to Version: 5f8239f

After a player went bankrupt during OR 4.1, any shorts held by that player are in the bank pool until the start of the next stock round - but they are not visible on the bank pool card or on the company card as shorts held by the bank pool. This would be good information for the players to be able to see.

**Comment by jenf** [comment]
There's significant bugs in the version your using, I think the shorts are now shown properly.
