### ISSUE TITLE
[18Mex] 'wrong number of arguments' error when declaring bankruptcy

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#2547]
https://18xx.games/game/17849?action=404
When attempting to declare bankruptcy, the player received an error re: wrong number of arguments. Also experienced by other players using Master Mode.

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/101225626-f24f2c00-365f-11eb-9d76-c07980ddaa86.png)
