### ISSUE TITLE
[1848] Rules Implementation

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#2548]
[rules pdf ](http://ohley.de/english/1848/1848-rules.pdf)

[My latest dev branch](https://github.com/benjaminxscott/18xx/tree/1848) (likely unstable)

### Capital
- Supports 3 - 6 players, receiving {840, 630, 510, 430} 
- Bank starts with 10,000 dollarydoos

### Auction
- [x] Dutch auction with rules:

- On a player's turn, they have two actions: buy a private or reduce the price a private
- Once a player owns a private, they have an additional action: passing
- If all privates have been reduced to their minimum price and nobody has bought a private yet, the currently active player must buy one
- If any privates are left and all players have passed in a row, an "OR" happens where privates pay and the auction continues

### Stock Rounds
- Sell any number of shares, then buy up to one share, or pass
- Priority order works as normal (left of the last player to take an action in SR)

#### Certificate Limits
- [ ] In 3p game, can hold 70% of corp, else 60%
- [x] Privates do not count against cert limit
- [ ] After a company goes into receivership, the cert limit for all players goes down 

| Players | 0 Receiverships | 1 | 2 | 3 | 4 | 5+ |
|---|---|---|---|---|---|---|
| 3      | 20 |  18 |16 |14 |12 |10|
| 4      | 17 |15 |13 |11 |10 |9|
| 5      | 14 |13 |12 |10 |9 |8 |
| 6      | 12 |11 |10 |9 |8 |7 |

#### Launching Corporations
- 60% to float, full-cap
- May be parred at {60,70,80,90,100}
- [x] CAR is always parred at 100 (Presidency is granted by P6)

- [x] COM receives two free home tokens, in Sydney and Adelaide
- [x] COM is parred by whomever buys its Presidency, and may only operate once 60% of its shares have been bought and Sydney is connected to to Adelaide (e.g. if a D train ignoring tokens could connect the two cities)
- [ ] From Phase 6 on, COM can operate without the above requirement
- [ ] If all the conditions for the launch of the COM are fulfilled before it would be the COM's turn to operate in the relevant OR (according to share price order), it starts to operate in the same OR. If the second condition (the Sydney-Adelaide link or the purchase of the first 6/6+ train) is fulfilled for the first time by a company with a lower share price, the COM will operate for the first time in the next OR.
- [ ] If in one or both of the cities there is no place for the COM's home station for that city, the marker is laid on the edge of the tile or undeveloped hex (can use `cheater` token)
- [ ] A station marker of the COM lying at the edge of a tile has the same properties as a "normally" placed station marker
- [ ] If as a result of the development/upgrade of the hex/tile a free place becomes available, the marker is immediately moved from the edge of the hex/tile to this place.

#### Share Transactions
- Shares may not be sold in the first Share Round (handled by `SELL_AFTER = :first`)
- Shares may only be sold if after the sale no more than 50% of the company's shares are in the Bank Pool
- Has IPO / market shares with different prices
- For each sale of any number of a company's shares, the company's share price marker is moved down one space on the share price chart, and does not move further if it's already on the bottom row (handled by `SELL_MOVEMENT = :down_block`)
- [ ] Shares of BoE can be bought/sold without restriction (can theoretically buy/sell forever)

#### End of Stock Round Movement
- Each company with shares that are 100% in player hands moves its share price up one row, but does not move if already at the top row
- Share price does not move if shares are in the market or IPO

### Operating Rounds
- Privates Pay
- [ ] BoE Pays
- Corps operate in share price order (normal tie-breakers for "furthest right" and "token on top")

#### Taking Loans (At Any Time)
- [ ] from phase 3 on, each corp may take 1 "voluntary" loan of $100 per OR at any time
- [ ] this moves the corp's share price two spaces to the left and BoE's share price goes up one space
- [ ] Corps may have 5 "voluntary" loans total
- [ ] When a second company goes into receivership, the cheapest permanent train (5/5+, 6/6+,8/D) on sale from the Bank is removed from the game. [English rules say when second company takes loan, corrected in FAQ]
- [ ] When a fifth company goes into receivership, the cheapest permanent train (5/5+, 6/6+, 8/D) on sale from the Bank is removed from the game. [English rules say when fifth company takes loan, corrected in FAQ]
- [ ] Trains removed from the game are regarded as having been sold and can bring about a phase
change.

#### Laying Track
- [ ] In phase 2, can only build one yellow hex at a time, from phase 3 on, can build up to two yellow hexes OR perform a single upgrade (may need custom `TILE_LAYS`)
- [x] "K" tiles are placed in their respective hexes in Green/Brown/Gray (these hexes are normal cities in Yellow)
- [x] No track may be placed connecting to either reserved Tasmania space, until/unless its tile exists in that space (the reserved spaces count as an red offboard until it's placed)

#### Placing Tokens
- If a city contains the home base of a company that is not yet in operation, other companies may only build stations there if they leave at least one free place on the tile for the not yet operating company to place its station marker. (This rule does not apply to the home stations of the COM)

#### Running Trains / Dividends
- [x] All trains count as "plus trains" (can count arbitrary number of dits)
- [x] Some "small harbour" offboards at {B21, F3} count as dits
- [ ] Ghan (2E) train must have one of its stops be the off board Alice Springs location, and the stop must be a city with the corp's station
- [ ] Gauge changes count against a train's run
- [ ] Plus + trains get a free gauge change
- [x] K tiles in yellow and green upgrades
- [ ] Bonuses for running two or more K tiles in a single run
- Director can either choose to with-hold or full-pay
- [ ] Shares in bank pool / IPO do *not* pay dividends to anyone
- Share price moves right once if dividend is paid, and moves left once if dividend is withheld
- Share price "crawls up" if it hit the right side of the market

#### Purchasing Trains
- [x] Trains of type 2..6 have a "Plus+ train" `variant` that is slightly more expensive 
- [x] Ghan (2E) is available in Phase 5 (purchase of 5 or 5+)
- [x] Each company may only have one Ghan (2E) total
- [x] Ghan (2E) does *not* count against train limit
- [x] Ghan (2E) does *not* count as a train for the purposes of compulsory train ownership

- Multiple trains can be bought per OR
- Train from another company which has the same Director may be bought for $1 to $infinity 
- [ ] If a company buys a train from another company which has a different Director, the price paid must be the train's face value
- [ ] Trains cannot be bought from other companies until Phase 3
- [ ] After a phase change, trains in excess of the limit are discarded from the game without compensation
- [ ] During emergency money raising (EMR), the Director may *not* contribute private capital towards the purchase of a train
- [ ] During EMR, companies may take more than one loan per OR (as well as more than 5 total loans) if the compulsory train is being purchased from the Bank
- [ ] The second and each subsequent loan results in corp's share price moving 3 to the left
- [ ] If the corp's share price falls into the receivership zone after taking a loan, it goes into receivership *even if* it would have enough money after taking that loan to buy a train
- [ ] If a corp is unable to take out further loans because there are already 20 loans outstanding, it is placed in receivership even if its share price has not fallen into the receivership area of the Share Price Chart

#### Receivership
- [x] If a corp's share price moves left into the receivership zone, company is immediately placed in receivership
- [x] The corp's treasury is returned to the bank and trains are discarded
- [ ] Corp's tokens are converted to BoE tokens in the same cities (could be handled by a custom `close_corporation()` and `super`
- [ ] Corp pays compensation of par price to any other players who own shares in the defunct corp (IPO and market shares get nothing) [English rules say current stock price, corrected in FAQ]. If corp's assets are insufficient to pay everyone, its director must contribute. Remaining money in the corp goes back to the bank.
- [ ] Shares sold as the result of insolvency (the result of paying compensation to other shareholders in a company that has gone into receivership) may not trigger a change of Director
- [ ] If the owner cannot raise enough money via legal stock sales in order to pay out his fellow shareholders, she must overdraw his account by the appropriate amount (interest free). As soon as she receives future income (from dividends or the sale of shares) she must immediately pay back the borrowed money to the Bank
- [ ] In a 3 or 4 player game the share limit for the former Director is reduced by an additional 2 certs. In a 5 or 6 player game the share limit for the former Director is reduced by an additional 1.

#### Private Companies
- {P1, P2, P3, P4} can be bought in for up to face value
- Privates may be bought in starting in Green phase (Phase 3)
- Privates close in Brown phase (Phase 5)
- Privates *cannot* be bought across players

#### Private Abilities
- [x] Private powers cannot be used until Phase 3 (can use `on_phase`)
- [ ] P2 lays a cactus tile for free
- [ ] P3 places Tasmania tile in one of two reserved hexes (it counts as a regular off-board stop)
- [x] Add Tasmania tile (should have `blocks_lay`)
```
"241": {
      "count": 1,
      "color": "water",
      "code": "path=a:3,b:_0;path=a:4,b:_0",
    },
```
- [ ] P4 gets $100 off a Ghan (2E) as a one-time discount
- [x] P5 gets a free share of the QR
- [x] P6 gets the presidency of the CAR (at 100 par)

- [x] P2 and P4 powers stick around after they close
- [ ] P2 and P4 powers can be used by a player on behalf of a corp they are running during the corp's turn
- [ ] P3 owner/owning corp is compelled to place Tasmania when Brown hits

### Bank of England
- [ ] Doesn't have a float amount / treasury, but does have 10 shares and a stock price and pays dividends
- [ ] share price only moves if corps take out loans, not from paying dividends or share buys/sells
- [ ] each OR BoE pays a base dividend based on phase {0, 100, 200, 300}
- [ ] its base dividend is increased by an amount equal to revenue from each city that has a BoE token
- [ ] If BoE has more than one station marker in a city, it counts the value of the city for each of them

### [Game End Triggers](https://github.com/tobymao/18xx/blob/master/lib/engine/game/base.rb#L1493)
- after trigger, game ends after current set of ORs
- If bank breaks
- [ ] If 16 loans total are taken 
- [ ] If any company gets to 450 price
- [ ] 5 or more companies are in receivership

**Comment by BellmakerSA** [comment]
Didn’t see it above, but the 2E (Ghan) train must have one of its stops be the off board Alice Springs location, and the other be a city with a station in it.

**Comment by dfannius** [comment]
I updated a couple of rules above that are incorrect in the current English manual but have been corrected in the FAQ (search for "FAQ" to see what they are).

**Comment by benjaminxscott** [comment]
Just realized that the `halt` concept can implement the "gauge change" thing pretty cleanly

**Comment by lkingsford** [comment]
A few updates (can't edit this issue myself). The following has been implemented
- K yellow tile (and upgrades correctly to green).
- COM free home tokens.
- COM doesn't start until both floated and Syd/Melb connected. The phase 6 exception to this hasn't been implemented yet.

**Comment by benjaminxscott** [comment]
ok updated
