### ISSUE TITLE
[1817] having only one corp in a MA round breaks things

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2549]
I'm not sure how relevant this is, but I was doing random stuff in hotseat mode and I managed to break the implementation. 100% sure that this exact situation won't happen in a real game, but I don't know if this is a symptom of something more relevant.

The json: https://gist.github.com/daniel-sousa-me/a4f1259df35427f2cc1ff8d22280ba51

**Comment by ventusignis** [comment]
@daniel-sousa-me Just to confirm; the way the game broke is that an error is printed to the console if you try to take a loan when you import the game right?

**Comment by daniel-sousa-me** [comment]
Or if I try to pass. And the game doesn't move forward.
