### ISSUE TITLE
[18Mex] Missing Half shares in the NdM

### ISSUE THREAD

**Issue by CaptainObi** [tobymao/18xx#2553]
https://www.18xx.games/game/17886?action=365

After the minors closed, one of the half shares disappeared. Not too sure what happened exactly. 

![Screenshot (125)](https://user-images.githubusercontent.com/69726608/101246869-c38f8f00-370d-11eb-9d1a-98ce5be7af75.png)
![Screenshot (123)](https://user-images.githubusercontent.com/69726608/101246871-c4282580-370d-11eb-89ad-fb336247d151.png)

In the second screenshot if you buy the half share the market shares will become a negative -0.5 value.

**Comment by perwestling** [comment]
It seems t be swap that is broken, action 312
