### ISSUE TITLE
[1817] Unused tokens have a "0" underneath it on the corporation card

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#2585]
Is the "0" underneath unused tokens on purpose or a bug? A blank seems to make more sense.

![image](https://user-images.githubusercontent.com/67359577/101306949-3f73ff00-3814-11eb-9e57-9592deb3310b.png)

**Comment by perwestling** [comment]
That is the cost, what you need to pay to place it. It is already paid for so therefor 0.
So it is intentional.

Why do you think it is a bug?

**Comment by crericha** [comment]
Okay, I understand. Thanks for explaining.

 In my opinion, the value is misleading without the currency sign. Also, should we consider leaving blank when the token is free?

**Comment by perwestling** [comment]
It says for example 40, 60, 100 so I do not see 0 as that misleading. Put currency on these values would of course be possible but it would be a bit crowded with $100, and even more so for titles that do not have a currency sign, but two or more letters as currency.

In 1882 this has been from the start:
![image](https://user-images.githubusercontent.com/2631151/101319366-272ad100-3862-11eb-99be-61566371ebed.png)

Anyway, your suggestion has been noted. I have put the Enhancement label on it, and not 1817, as it is a general thing.

**Comment by jenf** [comment]
Yeah, I believe we never did it because of the overcrowding the occurs at £100

**Comment by crericha** [comment]
I think the confusion lies in using that location on the card is use for both the token's placed coordinates and its unplaced cost. In my above picture, its hard to know the "0" is currency.

For what it's worth, this made for a 10 minute discussion during my game to figure out what the "0" meant. Some thought it was an "O" for open and others thought it was a bug or bad visual. No one thought it represented cost since 1817 doesn't have token placement costs. Just one observation. :-)

I looked through the physical version of a few games. It's pretty split between using "£0", "Free", and nothing. The games where you prepay for tokens either used "Free" (1849) or nothing (1817 and 1862).

**Comment by crericha** [comment]
My suggestion is if the game has you prepay for tokens, don't show a cost.

**Comment by jenf** [comment]
I'd argue against that, since people switch between games very often having the '0' or 'Free' would remind them that they don't need to pay.

**Comment by tobymao** [comment]
closin for now, seems fine as is
