### ISSUE TITLE
Game in broken state

### ISSUE THREAD

**Issue by cnejustin** [tobymao/18xx#259]
Game #263 is in a broken state after a player:
1. bought a share
2. used undo 
3. bought a different share. 

We were not playing real-time but it's possible another player tried to take an action between those steps which caused the corrupt game state.

Crashing with the exception "uncaught exception: GameError: It is not Juztyn's turn"

**Comment by tobymao** [comment]
this has been manually fixed. the long term fix is to put undo and process in advisory locks

https://github.com/chanks/sequel-advisory-locking/blob/master/lib/sequel/extensions/advisory_locking.rb

https://github.com/yuryroot/sequel-pg_advisory_lock
