### ISSUE TITLE
End Turn Button

### ISSUE THREAD

**Issue by galfridus** [tobymao/18xx#2590]
When one company takes the last choice in their OR, the site goes immediately to the next company. It is possible that the player running the first company might wish to undo after looking at the results. Before they do, the next player may begin operating. While it's possible to undo, it can create tension (and it's possible that the next player's actions reveal intentions or otherwise "spoil" the previous player's choices).

A final "end OR" button would make clear that the previous player is done, and avoid this situation.

**Comment by tobymao** [comment]
I don't think it's necessary. Just explain in chat that you made a mistake and want to undo. The same thing will happen if you press end OR accidentally, or more comonly, you will forget to press end and there will be tension because it's still your turn.
