### ISSUE TITLE
Button to delete temporary, cloned "Hotseat" games?

### ISSUE THREAD

**Issue by triode-dev** [tobymao/18xx#2593]
Assuming there is no "commit my move" button, ie the site is always "live" - then players often will use Clone Game, to figure out their move, without disturbing the main game.  

When used like this (eg, sometimes almost every move), the hotseat games accumulate quickly.   It would be nice to have a button to delete them all, as a batch.

**Comment by benjaminxscott** [comment]
Hotseat games are stored in client-side cookies, so you could clear cookies to accomplish this

**Comment by tobymao** [comment]
won't implement for now as you can pretty easily delete them all by clicking
