### ISSUE TITLE
[18Chesapeake] C&OC does not work the turn a company purchases it

### ISSUE THREAD

**Issue by Bobsson** [tobymao/18xx#2594]
When a company buys the C&OC in 18Chesapeake, they are unable to build track there on that turn, even if it's purchased before the company lays track.  This opens up the possibility for someone else to build there, blocking its use altogether.

A game just before Player 2 buys C&OC: https://gist.github.com/Bobsson/78d824deaa72a93ac9963e76231eb4d5
Same game, one OR after Player 2 buys C&OC: https://gist.github.com/Bobsson/2a16f7fa7550b280c831d13e5441cb60

**Comment by michaeljb** [comment]
This is something that needs to be fixed, but there is a possible workaround--after buying in C&OC, refresh the page and then its hex will be highlighted

**Comment by michaeljb** [comment]
Actually this was noted in #1520, so I'll close this issue as a duplicate.
