### ISSUE TITLE
Master mode showing player took actions when they didn't

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#2597]
![Screenshot from 2020-12-08 17-57-44](https://user-images.githubusercontent.com/1045173/101559714-ed032180-397e-11eb-9d40-7383a14ad05d.png)

In https://18xx.games/game/14927#tools, the browser find tells me there are 633 instances of `"user"` on in the game JSON, with 632 of them being `"user": 136`; the on other being `"user": {` at the top of the JSON, so the system reports that 632 of the 904 actions were taken by user 136 (Stephen_Yu).

**Comment by michaeljb** [comment]
May be caused by migrations - https://github.com/tobymao/18xx/blob/master/migrate_game.rb#L314

**Comment by michaeljb** [comment]
I think that needs to be changed to `action.user` or something, and we could do a sweep for games where the owner is marked as the user on the action an unusually high amount of times and remove those so it doesn't look like they master moded through the whole game.

**Comment by tobymao** [comment]
this is not a bug in the engine, this is a bug in the migration script

**Comment by tobymao** [comment]
is this fixed?

**Comment by michaeljb** [comment]
Yeah, fixed in https://github.com/tobymao/18xx/commit/160d2ec478944576e865711e32f1ce1a1aa8967e#diff-ec939cb63abf76c70afca5bcb759020a2e3dfe6149f1f8b2e3a113801c2966cdR331 and https://github.com/tobymao/18xx/commit/07219f62af13d407ceb0124faa16309075e6ca6c#diff-ec939cb63abf76c70afca5bcb759020a2e3dfe6149f1f8b2e3a113801c2966cd

Note that any future migrations that create new actions also need to appropriately set `user` on that action
