### ISSUE TITLE
clicking city toggles illegal routes and misses the legal way

### ISSUE THREAD

**Issue by arcee1986** [tobymao/18xx#2599]
In an 18MEX game, I had trouble making a train take the route I wanted.  I would click various cities and it would toggle on and off, or sometimes toggle illegal routes, but there was a different legal route entirely to that city.  I tried a few times clearing the route and adding them in different orders, and eventually was able to find a way.

Sample game: 18mex, #18208.  NdM's final turn (7.3, actions 757-759 should cover it), a token had been placed in Tampico cutting its route for a 5-train.  I took the Queretaro-Guadalajara segment out of the other 5, and was trying to make Tampico-Mexico-town-Guadalajara-Queretaro.  The illegal Tampico-Queretaro segment liked to reappear, and also sometimes Mexico City (SE) - Queretaro rather than Guadalajara-Queretaro (when clicking Queretaro)

(yes, forgot to put another stop in that other 5.  between the slow speed of lategame and the trouble with this route, whoops)

Not sure if 18MEX specific, but it might be, because of the MC double-track.

**Comment by benjaminxscott** [comment]
Is this valid teal route the one you were attempting [at that game state](https://18xx.games/game/18208?action=758)?
(having removed the red train connection between G and Q cities) 

![Screenshot 2020-12-16 at 9 13 42 PM](https://user-images.githubusercontent.com/1711810/102447861-b9ab3d00-3fe5-11eb-94d6-9b36759ea05e.png)

Possibly a repro of this issue - after selecting the above route, if I click Mexico City or Tampico (which removes the valid MC to Tampico route), and then click Tampico again it will connect an invalid route to Tampico from Q 
(the valid route from MC to Tampico is not suggested upon clicking multiple times)

![Screenshot 2020-12-16 at 9 26 11 PM](https://user-images.githubusercontent.com/1711810/102447806-a39d7c80-3fe5-11eb-90ed-d8933764d91c.png)

**Comment by benjaminxscott** [comment]
Notably I can also generate this invalid route for NdM which is treated as valid

![Screenshot 2020-12-16 at 9 34 15 PM](https://user-images.githubusercontent.com/1711810/102448204-7d2c1100-3fe6-11eb-8b7b-803d74921d4a.png)

**Comment by arcee1986** [comment]
Yeah both of those were what I was running into.  Didn't notice it was considering the 2nd route as valid, but it definitely appeared.

**Comment by physic** [comment]
Here's another delightful instance of this bug. Forcing a route extension to trace through a red off board area, and then telling me my route is disconnected. You don't say!
![image](https://user-images.githubusercontent.com/5408282/126085358-d48ccde1-637e-4455-8b4a-6a802adc1037.png)

https://gist.github.com/physic/60ec6dd5d6094f7cbb720d1257396441

**Comment by dfannius** [comment]
Just chiming in to reiterate that this continues to make extending routes annoying in practice. I have acquired a set of tricks to use to avoid it, which is kind of a red flag. It's linked above but I'll note again that there's more info in #3915.

**Comment by scottredracecar** [comment]
The 18MEX linked game no longer reaches action 757

The gist provided by @physic works, but I don't understand what to try to reproduce to cause a problem. Yes it shouldn't allow routing through an offboard, but I am not sure if that is worth fixing, players shouldn't be attempting to route through offboards.

What "normal" mode of operation do I need to do to reproduce?

**Comment by dfannius** [comment]
One of this or #3915 should continue to exist. There are a bunch of bugs referencing the same basic issue; I think this is the last one left alive but #3915 actually has more information, although it was silently closed a couple of months ago.

**Comment by scottredracecar** [comment]
let's close this one and focus on #3915 which is easy to reproduce now
