### ISSUE TITLE
Add hyperlinking and/or hover info for players, corporations, companies

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#260]
I would like to see a lot more informative contextual interaction in the interface. I think this would greatly reduce the friction in dealing with so many tabs, which has come up recently in proposals to merge some of the tabs. I'm willing to try to implement some of this, but I don't want to waste time if @tobymao doesn't like the ideas.

Anywhere I see a player's name (game tab player order, corporation card president, spreadsheet headings, chat), I want to click the player's name to go to the player tab with them highlighted, and/or have [a subset of] their player card show up in a hover/tooltip.

Anywhere a corporation name/icon/token is displayed without the corporation's card (map token, player card share list, stock market token, spreadsheet rows, chat), I want to click to go to the corp tab with them highlighted, and/or have [a subset of] their corp card show up in a hover/tooltip.

Ditto privates/companies.

Maybe some of the behaviors are also context-dependent. Of all the combinations described above, the one where clicking on a map token takes you to the corporation tab is probably the "worst" UX, so it should probably be omitted, but I would still want the corp card tooltip/hover there.

**Comment by dfannius** [comment]
The one of these I want the most right now is to see a private's special ability by hovering over it in a player or corporation card.

**Comment by tobymao** [comment]
I think hyper linking and hover info are all good ideas if done well. happy to discuss further in slack.

**Comment by zurfarosa** [comment]
> The one of these I want the most right now is to see a private's special ability by hovering over it in a player or corporation card.

The clickable privates info on the new Entities tabs makes hover-over less essential, but it would still be really useful in the Spreadsheet tab.

**Comment by yzemaze** [comment]
> The clickable privates info on the new Entities tabs makes hover-over less essential, but it would still be really useful in the Spreadsheet tab.

Why? Afaik only Liquidity and Priority Deal are missing from Spreadsheet (both would be an easy fix). Everything else from player/corp cards should already be there – because that’s exactly what the Spreadsheet was designed for.

**Comment by Beemser** [comment]
I'm also strongly behind this suggestion.  Where I notice it most is while planning my moves in the Game tab.  I might want to know if the next company in turn order has a token left, or how much money they have, etc.  I'd want to simply hover over their icon in the turn order strip to see that pop up.
