### ISSUE TITLE
1817 better interest warning

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2600]
https://18xx.games/game/15339?action=471

In this example, it would be nice if the button warned you that you would need to take an additional loan to cover interest.

**Comment by jenf** [comment]
Which button?

**Comment by ChrisTheCat** [comment]
Done (Trains)

**Comment by ChrisTheCat** [comment]
I would have it say "Done (Trains) - will take 1 loan to pay interest" or something like that

**Comment by bridger15** [comment]
Yes, and a similar warning if you couldn't cover interest (and are going to head into acquisition).

**Comment by jenf** [comment]
@ChrisTheCat apologies, the actions on this have been renumbered, could you point me to which action you mean

**Comment by ChrisTheCat** [comment]
Sorry, I'm not sure which company it was - this game was a month ago.

**Comment by jenf** [comment]
Yeah, apologies I should've added more detail at the time

**Comment by ChrisTheCat** [comment]
That said, I can explain the issue as I currently understand it.

When selecting pay/half/hold dividends, there is a warning if paying full
(or even half) dividends will send a corporation to liquidation.

It would be nice if that warning also indicated if paying full (or half)
dividends would automatically result in taking sufficient loans to pay
interest to send the corporation to acquisition.

Similarly, when buying trains or companies after paying dividends but prior
to paying interest, if the selected action will automatically cause the
corporation to go into liquidation, or force the corporation to take loans
to pay interest that would send the corporation into acquisition, a warning
would be useful.

**Comment by jenf** [comment]
#3340 https://18xx.games/game/21973?action=210.

**Comment by ChrisTheCat** [comment]
Here is a specific example.

https://18xx.games/game/16208?action=486

Clicking the "Done (trains)" button sends the NYOW to liquidation with no warning whatsoever. I didn't notice it had happened until much later in the game, when it was too late to undo, and thus my entire game turned into a completely avoidable and accidental bankruptcy.
