### ISSUE TITLE
1817NA: Miami is wrong

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2603]
The values of Miami in 1817NA are wrong; they should be 20/30/50/60

See PR https://github.com/tobymao/18xx/pull/2601

**Comment by perwestling** [comment]
This ticket is 3 hours old, and the PR was merged 3 hours ago. Merged does not mean deployed - that it it has probably not been applied to the production instance yet.

**Comment by tobymao** [comment]
deployed
