### ISSUE TITLE
Showing available tokens

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#2604]
In a game like 1817 where you can have 8 or more tokens you get a misleading display.  When a company has 8 tokens, only 7 of them are shown in the Game or Entity tab.  You can see all 8 on the info tab.  In the game I am playing, the company has 7 tokens on the board and one token available but you have to do a lot of digging to see that is the case.

As more games are added, this could become a major issue.  Ideally, the game and entity tabs need to show clearly how many tokens a company has.

In 1817 game 17117 J bought NYSW 

![image](https://user-images.githubusercontent.com/11814681/101734936-fabcc200-3ab8-11eb-9a22-58563d540572.png)

and the result looks like

![image](https://user-images.githubusercontent.com/11814681/101734994-13c57300-3ab9-11eb-84a1-ae2cbb0de2e1.png)

**Comment by slapphappyjazz** [comment]
Also, in this same transaction, the log displayed:
"J acquires NYSW receiving and tokens (4: hexes F19,C26)" 
There is nothing between "receiving" and "and" (presumably because NYSW had no trains and no privates.  Also, although the NYSW owned 4 tokens, J could only acquire 3, so should there have been a note about discarding one?

Also: I was confused because the message said 4 tokens but only listed 2 hexes - this was correct because the other two were on the charter but the message could be clearer, e.g. "and 4 tokens (hexes F19, C26; 2 on the charter)".

**Comment by yzemaze** [comment]
Yep, Toby and I knew we’d run into this problem later on (with 1817 especially) back when the corporation cards were redesigned. We decided to just let the overflow of tokens be scrollable until a better solution "comes along".

@rclyne On which browser and system did you take the screenshots? (Chrome and FF over here display the scroll bar.) Which solution would you prefer? Display all tokens? (How?) Display x/y tokens used? (Where?) Something else?

**Comment by rclyne** [comment]
Perhaps the graphic needs to have all unused tokens shown, then used tokens and then a +X showing how many used tokens are not shown.  The hexes that used tokens are in is probably not that important as most users will look at the map for that information

**Comment by rclyne** [comment]
Screenshots are Safari on OSX

**Comment by rclyne** [comment]
Also, prepare for issues if you ever implement 1873 or 1831.  Both have lots of tokens in one or more companies. 1831 has a maximum of 38 tokens per company!!!

**Comment by yzemaze** [comment]
@rclyne Tokens are ordered with available ones first. This should alleviate the problem. If you still run into trouble, please just post here. [This was just a quick and easy fix, it’s not perfect and might not even work well for titles with loads of tokens like the ones you mentioned.]

**Comment by ChrisTheCat** [comment]
Note that the hidden scrollbar is an OS X feature, for all browsers. The scrollbar setting is a system preference:

<img width="428" alt="Screen Shot 2021-02-07 at 4 49 16 PM" src="https://user-images.githubusercontent.com/8732435/107164550-72e21f80-6964-11eb-84d8-16765eedeada.png">

**Comment by yzemaze** [comment]
Closing for now. Feel free to request re-opening this issue if the status quo doesn’t work for you.
