### ISSUE TITLE
[1846] Player forced to buy Big 4 / MS for more than $0 in private draft

### ISSUE THREAD

**Issue by mbolohan** [tobymao/18xx#2610]
Hotseat JSON:
https://gist.github.com/mbolohan/267fd65fc857c9112f1a9b8aac87a166

In 1846, when Big 4 or MS is the last company in the private draft, a player is forced to buy it after its price is reduced to $60 for Big 4 and $80 for MS, instead of $0. Rules state that "A player must take it for free if its price is reduced to $0." It seems that the private's value is being used to determine when to force a player to purchase, instead of its price.

In the gist above, Player 3 is forced to buy Big 4 at $60 instead of being allowed to pass:

Big 4 price decreases from $100 to $90
Big 4 price decreases from $90 to $80
Big 4 price decreases from $80 to $70
Big 4 price decreases from $70 to $60
Player 3 chooses Big 4

**Comment by dfannius** [comment]
My understanding is that this behavior is correct. The Big 4 has a price of $40 (see the card in the physical game) and also comes with $60 of debt that must be paid off immediately. When the price is reduced from $40 to $0, the next player must buy it for $0, and then pay off the $60 debt.

**Comment by dfannius** [comment]
I found a comment by the designer agreeing with this: https://boardgamegeek.com/thread/1880571/article/27393557#27393557
