### ISSUE TITLE
Undo To Here in history view

### ISSUE THREAD

**Issue by emknell** [tobymao/18xx#2611]
It can be fairly onerous if you need to do a lot of undos (such as restarting a long stock round).  An "Undo to Here" button that worked when you are flipping through the History would be super helpful.

**Comment by ChrisTheCat** [comment]
Per Toby's comment on the linked issue, apparently the idea is not about "flipping through the history" but instead would be implemented as: find a spot in the log, click on it, and then click "undo to here"

**Comment by emknell** [comment]
Yeah - that sounds like a great way to do it!
