### ISSUE TITLE
Make the bank cash visible on more pages

### ISSUE THREAD

**Issue by glomzig** [tobymao/18xx#262]
Some comments/suggestions:
1. I think it would be helpful to include the bank on the spreadsheet view
2. Is it possible to include the phase of the game with current train limit, number of ORs on each screen?

**Comment by Anvil-X** [comment]
Bank should be on each screen too.

**Comment by SirLinkan** [comment]
I like the 2nd point. In rr18xx, there is an Train/Phase Table which is very useful. Something similair would be appreciated!

**Comment by jenf** [comment]
#258 covers the train/phase table

So this ticket is just relation to adding the bank on more pages

**Comment by 8bg** [comment]
Issues 158, 159, and 262 are essentially the same issue if can consolidate.

**Comment by yraelrocks** [comment]
Also can the broken bank have some kind of flag? It’s in the log but could be missed by players if a train is bought just after the bank breaks, giving a false indication.

Or simply stop adding purchases back into the bank after it’s been broken?

**Comment by scottredracecar** [comment]
I suggest to add the bank cash in two places:
- Above the market on the Game tab (mirrors the layout of the Market tab)
- Above the spreadsheet on the Spreadsheet tab

**Comment by andypymont** [comment]
Pull request  #915 implements the bank appearing in the two additional places suggested by Scott above.
