### ISSUE TITLE
1817 wrong player order on liquidation auction

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2627]
https://18xx.games/game/18546?action=1051

Colby -> Hushed -> Colby -> Skanadron is the wrong order of operations.

WT is being liquidated, bank offers $0, corporation had $50 and 2 loans
ChrisShaffer bids $10 for WT
Aolivei8 bids $100 for WT
Colby bids $200 for WT
Hushed bids $300 for WT
Colby passes on WT
Skanadron bids $310 for WT
ChrisShaffer passes on WT
Aolivei8 bids $350 for WT

**Comment by jenf** [comment]
Just a logging issue

**Comment by jenf** [comment]
The log should be modified to "Colby cannot raise bid to $300 and passes"
