### ISSUE TITLE
1817 corporations in wrong order in M&A round

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2629]
https://18xx.games/game/18546?action=1077

The "B&A moved into acquisition" line should have appeared before Skanadron was asked to put the SR up for friendly sale.

SR may be offered for sale for $250
Skanadron declines to put SR up for sale
B&A moved into acquisition during M&A and so is skipped
A&A cannot be bought at $550, skipping

**Comment by jenf** [comment]
This is the correct order, B&A should've been after SR, unless i'm missing something.

**Comment by ChrisTheCat** [comment]
In the M&A round, for liquidation/acquisition/friendly sales, it goes from left to right. B&A is farther left, so should happen before SR. In the list below, it should be in this order:

B&A, SR, A&A, Belt, J, HOU, UR

<img width="568" alt="Screen Shot 2020-12-13 at 1 45 13 PM" src="https://user-images.githubusercontent.com/8732435/102024956-c3b10f80-3d49-11eb-9a11-5170987c9518.png">

**Comment by jenf** [comment]
The rules are ambiguous on this point. It says in operating order and doesn't really clarify what happens if taking loans changes the order they come up in m&a. I'm not sure it really changes the outcome.

**Comment by jenf** [comment]
This seems to indiciate that the fixed order is the correct interpretation:
https://boardgamegeek.com/thread/2432961/order-friendly-sales

**Comment by jenf** [comment]
Reopen if you still disagree
