### ISSUE TITLE
"entities" view doesn't render during initial auction

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#2631]
It looks like the 'entities' tab is not accessible during the initial private auction round

(e.g. clicking `Entities` doesn't render the view )

screenshot where I was on the "Market" tab, and clicked "Entities"
![Screenshot 2020-12-13 at 9 48 45 AM](https://user-images.githubusercontent.com/1711810/102019445-7c665700-3d28-11eb-8c6e-217dcc8a245e.png)

This appears reproducible across games (I tested 18mex and 1846)

**Please provide details about your system**
Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by jenf** [comment]
fixed c2cc9d4c
