### ISSUE TITLE
Visual rendering of route should take into account town location

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#264]
This is a super minor issue, but still, I figure we can log these and prioritize accordingly (eg not high, but a nice little wart to remove)

<img width="171" alt="Screen Shot 2020-05-03 at 12 29 04" src="https://user-images.githubusercontent.com/830087/80898774-10efec00-8d3a-11ea-80f4-bb5b8b519d52.png">

**Comment by kelsin** [comment]
I'll take a peek at this when I abstract out the town/city location stuff. Right now I don't think the track has any way of knowing where the town ended up being laid. @tobymao does that sound accurate? I think track gets rendered first and right now doesn't know enough about the town's location to divide properly. I'll keep thinking about it as I learn more about the code base. We'll find an answer I'm sure 👍

**Comment by rheretic** [comment]
OP:  I would retry this to see if it's still present.  Quite a bit of code change since you opened this.

**Comment by tobymao** [comment]
no this was not fixed

**Comment by roseundy** [comment]
This should have been fixed with PR #1535
