### ISSUE TITLE
1817NA game 17785 crashed after multiple undos near end game

### ISSUE THREAD

**Issue by tom-blight** [tobymao/18xx#2643]
https://18xx.games/game/17785

I took a load of loans without thinking, so attempted to ‘undo’ a few times in a row. Next thing I know the game was broken. 

It’s in the final ORs and so a pretty large JSON now.

**Comment by jenf** [comment]
It's a pinned game, the server doesn't check the state as much. I can delete the last few actions for you.

**Comment by tom-blight** [comment]
Wonderful, thanks.
