### ISSUE TITLE
18LA - map tab not working

### ISSUE THREAD

**Issue by vantdog** [tobymao/18xx#2660]
Game 19009 - none of us can use the map tab . . . 

https://18xx.games/game/19009?action=4

**Comment by jenf** [comment]
Uncaught 
a {name: "track", message: "undefined method `track' for <Engine::Part::Stub: hex: D9>", args: Array(0), stack: "track: undefined method `track' for <Engine::Part:…a.$h (https://18xx.games/assets/main.js:68:13843)"}
args: []
message: "undefined method `track' for <Engine::Part::Stub: hex: D9>"
name: "track"
stack: "track: undefined method `track' for <Engine::Part::Stub: hex: D9>↵    at a.$method_missing (https://18xx.games/assets/main.js:2:20031)↵    at a.n (https://18xx.games/assets/main.js:1:11652)↵    at s (https://18xx.games/assets/main.js:132:4064)↵    at Object.I.yield1 (https://18xx.games/assets/main.js:1:13246)↵    at Array.$collect (https://18xx.games/assets/main.js:5:27210)↵    at Object.I.send (https://18xx.games/assets/main.js:1:15202)↵    at Array.$map (https://18xx.games/assets/main.js:1:17338)↵    at I.send (https://18xx.games/assets/main.js:1:15202)↵    at a.$render (https://18xx.games/assets/main.js:132:3845)↵    at a.$h (https://18xx.games/assets/main.js:68:13843)"
__proto__: a

**Comment by jenf** [comment]
should be fixed now

**Comment by vantdog** [comment]
> should be fixed now

Thanks! It is
