### ISSUE TITLE
[1817] Ohio Bridge Company allows to place two bridge tokens

### ISSUE THREAD

**Issue by Xirivia86** [tobymao/18xx#2664]
[https://18xx.games/game/14443?action=1017](url)

I was able to place a second bridge token. The first one was placed at the 1st OR at Charleston. If you see the action on the link, I have just placed the second token at Cincinnati. I should not be able to place more than one.

I don't know if I can use the Ohio Bridge Company while operating a different company than the owner. This could be a second issue with the rules, but I am not sure of this one.

**Comment by ventusignis** [comment]
I noticed this in 1817WO as well

**Comment by benjaminxscott** [comment]
This seems to be a trivial fix, I can make a PR

**Comment by benjaminxscott** [comment]
> I don't know if I can use the Ohio Bridge Company while operating a different company than the owner. This could be a second issue with the rules, but I am not sure of this one.

Looks like those privates should only be usable on the owning company turn
> The owning company may place one or both bridge tokens at any time during its operating turn.

This should fix that:
https://github.com/tobymao/18xx/pull/2667/commits/dfdb286fa2a7fae3de0baa2cf76529ba97509573
