### ISSUE TITLE
1817 cannot cross-player merge 5share corporations with bare presidencies

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2665]
It looks like in the effort to prevent presidentless corporations being created from mergers (IE: shorts) the implementation of 1817 prohibits mergers where the new president will have only the bare presidency.

It looks like the `>` should be `>=` here in `lib/engine/step/g_1817/conversion.rb`
`            (target.total_shares != 5 || merged_max_share_holder(corporation, target) > 40) &&`

**Comment by jenf** [comment]
Resolved by #2666
