### ISSUE TITLE
Player name can throw off formatting in players tab

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#267]
Likely due to the use of a fixed width

I guess it either needs to be a variable width (the longest applied to all), or scrollable (though scrolling on desktop is annoying if you don't have a touchpad)
<img width="1035" alt="Screen Shot 2020-05-03 at 20 29 15" src="https://user-images.githubusercontent.com/830087/80914273-1a4e7800-8d7d-11ea-968c-3aecf00a251d.png">

**Comment by M-Kristof** [comment]
Formatting in Players tab seems to be fine now, but there are still issues in Corporations and Spreadsheet tabs. Easiest fix would be to cut the names when they exceed a maximum length, I guess (extremelylongusername -> extremely...).

Players tab:
![image](https://user-images.githubusercontent.com/19674341/81832425-c68f1c00-953e-11ea-9a81-f3f7adbf5b60.png)

Corporations tab:
![image](https://user-images.githubusercontent.com/19674341/81831603-d65a3080-953d-11ea-854d-26cc82ad2041.png)

Spreadsheet tab:
![image](https://user-images.githubusercontent.com/19674341/81831811-1b7e6280-953e-11ea-8f83-b524c2ca27a1.png)

**Comment by tobymao** [comment]
we should just truncate the names in these views
