### ISSUE TITLE
Stock round indicator on corporations with no action

### ISSUE THREAD

**Issue by ryandriskel** [tobymao/18xx#2672]
During the stock round, all corporations are shown. This is good to have a general sense of relative positioning. However, many of the corporations will have no actions a player can take once they are selected. It would help reduce mental processing if there was a quick indication of whether there are actions available for that corporation.

A few potential (but not exhaustive) implementation ideas:
- reduced transparency
- colored border
- icon

**Comment by benjaminxscott** [comment]
I like the idea of lighter transparency for corp cards for which the active player has no valid actions

**Comment by roseundy** [comment]
Perhaps a dashed line for their borders?

**Comment by ryandriskel** [comment]
This as at 60% opacity. I'm not sure it is distinguishable enough, but I want to still be able to read the corp card.

<img width="1351" alt="Screen Shot 2020-12-21 at 5 56 49 PM" src="https://user-images.githubusercontent.com/15675400/102897991-16fc1f80-4426-11eb-9d36-ad86251474b4.png">

<img width="1363" alt="Screen Shot 2020-12-21 at 5 57 21 PM" src="https://user-images.githubusercontent.com/15675400/102897995-182d4c80-4426-11eb-9cb7-bd57a7c1f57e.png">

**Comment by benjaminxscott** [comment]
imo it's not very distinguishable, perhaps some sort of [striped gradiant](https://css-tricks.com/stripes-css/) for the background of cards?

**Comment by ryandriskel** [comment]
Here with are with a very light grey background on corps with no actions. Thoughts?

<img width="1357" alt="Screen Shot 2020-12-29 at 11 29 40 AM" src="https://user-images.githubusercontent.com/15675400/103305791-4a602080-49c9-11eb-852a-b2a9acb10305.png">

**Comment by benjaminxscott** [comment]
Hmm it seems not that distinguishable, but I'm not the only opinion fwiw (just I get email notifs for this thread)

Perhaps  the [disabled](https://www.w3schools.com/tags/att_button_disabled.asp) attribute could be combined to make it obvious that it's unclickable when hovered?

**Comment by ryandriskel** [comment]
The stripes work and are noticable, but I feel like they make the text difficult to read

<img width="1321" alt="Screen Shot 2020-12-29 at 12 45 28 PM" src="https://user-images.githubusercontent.com/15675400/103309981-c495a280-49d3-11eb-90d2-8fe7d1d569ea.png">

**Comment by crericha** [comment]
My eye parses the light gray option the best. The stripes are very distracting to me. The 60% opacity makes the charters look out of focus to me when glancing through them. Perhaps 100% opacity on the charter header and 60% could make that option work. Hard to tell without seeing.

**Comment by daniel-sousa-me** [comment]
I'm sorry I'm a bit late for the discussion, but I was mostly afk until now.

I have a wildly different suggestion. Why not just show all the available actions at all times without requiring clicks?

I find the extra clicking pretty annoying (although this is a big improvement) and pointless. The cards already occupy 10-20 lines, I don't think the 1-3 lines of actions is a big deal. If we're concerned about space, there's plenty other less useful information that could be hidden behind clicks.

**Comment by roseundy** [comment]
For 1860, that would be sub-optimal, since bankrupt corporations have a _lot_ of possible par prcies.

**Comment by daniel-sousa-me** [comment]
There could be a "Show par prices" button only for that case
