### ISSUE TITLE
[1860] Counting halts over train limit

### ISSUE THREAD

**Issue by yeknom02** [tobymao/18xx#2673]
I have a company running one of two 4+2 trains, and I am allowed to select £30 of kept revenue, which I am assuming means I am able to choose 3 halts. (Unless I am missing something in the rules, this should be over the limit.) I have cloned the game at the point of the issue. Game Id: hs_kcgpixmw_1608128593

Game information below:

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 1,
      "price": 5
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 2,
      "price": 10
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "par",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 4,
      "corporation": "IOW",
      "share_price": "90,0,24"
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 5
    },
    {
      "type": "undo",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 6
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 7,
      "price": 5
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 9,
      "company": "CMH",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 10,
      "price": 5
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 11,
      "price": 10
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 12,
      "price": 15
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 14,
      "company": "RPSC",
      "price": 130
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 15,
      "price": 5
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 16,
      "price": 10
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 17,
      "price": 15
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "par",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 19,
      "corporation": "C&N",
      "share_price": "100,0,26"
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 20,
      "price": 5
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 21,
      "price": 10
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 22,
      "price": 15
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "bid",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 24,
      "company": "BHC",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 25,
      "price": 5
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "bid",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 27,
      "company": "YHC",
      "price": 50
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "IOW_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "C&N_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "IOW_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "C&N_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "IOW_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "C&N_3"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 34,
      "hex": "F2",
      "tile": "787-0",
      "rotation": 0
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "C&N_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "IOW_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 37,
      "shares": [
        "C&N_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 38,
      "shares": [
        "IOW_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 39,
      "shares": [
        "C&N_6"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 40,
      "shares": [
        "IOW_6"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "RPSC",
      "entity_type": "company",
      "id": 41,
      "shares": [
        "IOW_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "buy_shares",
      "entity": "CMH",
      "entity_type": "company",
      "id": 43,
      "shares": [
        "C&N_7"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "undo",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "undo",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 47
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 49,
      "hex": "F4",
      "tile": "742-0",
      "rotation": 3
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 50,
      "hex": "G3",
      "tile": "741-0",
      "rotation": 5
    },
    {
      "type": "place_token",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 51,
      "city": "G5-0-0",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 52,
      "train": "2+1-0",
      "price": 250,
      "variant": "2+1"
    },
    {
      "type": "buy_train",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 53,
      "train": "2+1-1",
      "price": 250,
      "variant": "2+1"
    },
    {
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "lay_tile",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 55,
      "hex": "J4",
      "tile": "5-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 56,
      "city": "5-0-0",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 57,
      "train": "2+1-2",
      "price": 250,
      "variant": "2+1"
    },
    {
      "type": "buy_train",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 58,
      "train": "2+1-3",
      "price": 250,
      "variant": "2+1"
    },
    {
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 59
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 60
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 62,
      "hex": "H4",
      "tile": "744-0",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 63,
      "hex": "I5",
      "tile": "742-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 64,
      "routes": [
        {
          "train": "2+1-0",
          "halts": 1,
          "connections": [
            [
              "F4",
              "G5"
            ],
            [
              "F4",
              "F2"
            ],
            [
              "F2 1.2"
            ],
            [
              "F2 0.1"
            ]
          ]
        },
        {
          "train": "2+1-1",
          "halts": 1,
          "connections": [
            [
              "I5",
              "J4"
            ],
            [
              "I5",
              "H4"
            ],
            [
              "H4"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "G3",
              "G5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 65,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 66,
      "train": "2+1-4",
      "price": 250,
      "variant": "2+1"
    },
    {
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 68
    },
    {
      "type": "run_routes",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 69,
      "routes": [
        {
          "train": "2+1-2",
          "halts": 1,
          "connections": [
            [
              "G3",
              "G5"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "H4"
            ],
            [
              "I5",
              "H4"
            ],
            [
              "I5",
              "J4"
            ]
          ]
        },
        {
          "train": "2+1-3",
          "connections": [
            [
              "J4",
              "I3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 70,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 71,
      "train": "3+2-0",
      "price": 300,
      "variant": "3+2"
    },
    {
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 72
    },
    {
      "type": "sell_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 73,
      "shares": [
        "C&N_4",
        "C&N_5",
        "C&N_6"
      ],
      "percent": 30
    },
    {
      "type": "par",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 74,
      "corporation": "IWNJ",
      "share_price": "82,0,22"
    },
    {
      "type": "sell_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 75,
      "shares": [
        "IOW_4",
        "IOW_5",
        "IOW_6"
      ],
      "percent": 30
    },
    {
      "type": "par",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 76,
      "corporation": "FYN",
      "share_price": "82,0,22"
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 77,
      "shares": [
        "IWNJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "YHC",
      "entity_type": "company",
      "id": 78,
      "shares": [
        "FYN_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 79,
      "shares": [
        "IWNJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 80,
      "shares": [
        "FYN_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 81,
      "shares": [
        "IWNJ_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 82,
      "shares": [
        "FYN_3"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 83,
      "hex": "B4",
      "tile": "5-1",
      "rotation": 5
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 84,
      "shares": [
        "IWNJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 85,
      "shares": [
        "FYN_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "buy_shares",
      "entity": "RPSC",
      "entity_type": "company",
      "id": 87,
      "shares": [
        "IOW_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 89,
      "hex": "J4",
      "tile": "12-0",
      "rotation": 0
    },
    {
      "type": "undo",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 90
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 91,
      "hex": "G5",
      "tile": "763-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 92,
      "routes": [
        {
          "train": "2+1-0",
          "halts": 1,
          "connections": [
            [
              "G5",
              "F4"
            ],
            [
              "F4",
              "F2"
            ],
            [
              "F2 1.2"
            ],
            [
              "F2 0.1"
            ]
          ]
        },
        {
          "train": "2+1-1",
          "halts": 1,
          "connections": [
            [
              "I5",
              "J4"
            ],
            [
              "I5",
              "H4"
            ],
            [
              "H4"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "G5",
              "G3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 93,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 94
    },
    {
      "type": "lay_tile",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 95,
      "hex": "H8",
      "tile": "743-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "buy_train",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 97,
      "train": "3+2-1",
      "price": 300,
      "variant": "3+2"
    },
    {
      "type": "buy_train",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 98,
      "train": "3+2-2",
      "price": 300,
      "variant": "3+2"
    },
    {
      "type": "buy_train",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 99,
      "train": "2+1-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "lay_tile",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 101,
      "hex": "B6",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 102
    },
    {
      "type": "buy_train",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 103,
      "train": "3+2-3",
      "price": 300,
      "variant": "3+2"
    },
    {
      "type": "buy_train",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 104,
      "train": "4+2-0",
      "price": 350,
      "variant": "4+2"
    },
    {
      "type": "pass",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "type": "lay_tile",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 106,
      "hex": "I3",
      "tile": "758-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 107,
      "routes": [
        {
          "train": "3+2-0",
          "halts": 1,
          "connections": [
            [
              "G5",
              "G3"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "H4"
            ],
            [
              "I5",
              "H4"
            ],
            [
              "I5",
              "J4"
            ],
            [
              "I3",
              "J4"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 108,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 109
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 110,
      "hex": "F6",
      "tile": "742-2",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 111,
      "hex": "E5",
      "tile": "742-3",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 112,
      "train": "3+2-3",
      "price": 240
    },
    {
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "lay_tile",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 114,
      "hex": "J4",
      "tile": "12-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 115,
      "routes": [
        {
          "train": "3+2-0",
          "halts": 1,
          "connections": [
            [
              "G5",
              "G3"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "H4"
            ],
            [
              "I5",
              "H4"
            ],
            [
              "J4",
              "I5"
            ],
            [
              "J4",
              "I3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 116,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 118,
      "hex": "I9",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 119,
      "city": "6-1-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 120
    },
    {
      "type": "undo",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 121
    },
    {
      "type": "lay_tile",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 122,
      "hex": "G7",
      "tile": "761-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 123,
      "city": "763-0-1",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 124,
      "routes": [
        {
          "train": "3+2-1",
          "halts": 1,
          "connections": [
            [
              "G7"
            ],
            [
              "G7",
              "G5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IWNJ",
      "entity_type": "corporation",
      "id": 125,
      "kind": "payout"
    },
    {
      "type": "lay_tile",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 126,
      "hex": "C5",
      "tile": "743-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 127,
      "hex": "D6",
      "tile": "742-4",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 128
    },
    {
      "type": "run_routes",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 129,
      "routes": [
        {
          "train": "4+2-0",
          "halts": 3,
          "connections": [
            [
              "F6",
              "G5"
            ],
            [
              "E5",
              "F6"
            ],
            [
              "D6",
              "E5"
            ],
            [
              "D6",
              "C5"
            ],
            [
              "C5",
              "B4"
            ],
            [
              "B6",
              "B4"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 130,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 131,
      "train": "4+2-1",
      "price": 350,
      "variant": "4+2"
    },
    {
      "type": "pass",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 132
    },
    {
      "type": "sell_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 133,
      "shares": [
        "C&N_1",
        "C&N_2",
        "C&N_3",
        "C&N_0"
      ],
      "percent": 50
    },
    {
      "type": "undo",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 134
    },
    {
      "type": "buy_shares",
      "entity": "CMH",
      "entity_type": "company",
      "id": 135,
      "shares": [
        "C&N_7"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 136,
      "shares": [
        "C&N_1",
        "C&N_2",
        "C&N_3",
        "C&N_7",
        "C&N_0"
      ],
      "percent": 60
    },
    {
      "type": "par",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 137,
      "corporation": "BHI&R",
      "share_price": "68,0,18"
    },
    {
      "type": "buy_shares",
      "entity": "BHC",
      "entity_type": "company",
      "id": 138,
      "shares": [
        "BHI&R_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 139,
      "shares": [
        "IOW_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 140,
      "shares": [
        "BHI&R_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 141,
      "shares": [
        "IOW_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 142,
      "shares": [
        "BHI&R_3"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "BHI&R",
      "entity_type": "corporation",
      "id": 143,
      "hex": "L6",
      "tile": "5-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 144
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 145,
      "shares": [
        "IOW_6"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 146
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 147,
      "shares": [
        "BHI&R_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 148
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 149,
      "shares": [
        "BHI&R_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 151,
      "shares": [
        "BHI&R_6"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 152
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 153,
      "shares": [
        "BHI&R_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 154
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 155,
      "shares": [
        "BHI&R_8"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 156
    },
    {
      "type": "undo",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 157
    },
    {
      "type": "undo",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 158
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 159,
      "shares": [
        "IWNJ_5"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 160,
      "shares": [
        "IWNJ_1",
        "IWNJ_2",
        "IWNJ_3"
      ],
      "percent": 30
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 161,
      "shares": [
        "IOW_6"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 162,
      "shares": [
        "BHI&R_7"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 163,
      "shares": [
        "IOW_8"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 164,
      "shares": [
        "BHI&R_8"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Dan2",
      "entity_type": "player",
      "id": 165
    },
    {
      "type": "pass",
      "entity": "Dan1",
      "entity_type": "player",
      "id": 166
    },
    {
      "type": "lay_tile",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 167,
      "hex": "J6",
      "tile": "746-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 168,
      "city": "746-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 169,
      "routes": [
        {
          "train": "3+2-0",
          "halts": 2,
          "connections": [
            [
              "G5",
              "G3"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "H4"
            ],
            [
              "I5",
              "H4"
            ],
            [
              "J4",
              "I5"
            ],
            [
              "J4",
              "I3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 170,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 172,
      "hex": "A7",
      "tile": "115-0",
      "rotation": 4
    },
    {
      "type": "undo",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 173
    },
    {
      "type": "lay_tile",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 174,
      "hex": "B4",
      "tile": "756-0",
      "rotation": 5
    },
    {
      "type": "place_token",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 175,
      "city": "6-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "FYN",
      "entity_type": "corporation",
      "id": 176,
      "routes": [
        {
          "train": "4+2-0",
          "halts": 3,
          "connections": [
            [
              "F6",
              "G5"
            ],
            [
              "E5",
              "F6"
            ],
            [
              "D6",
              "E5"
            ],
            [
              "D6",
              "C5"
            ],
            [
              "B4",
              "C5"
            ],
            [
              "B4",
              "B6"
            ]
          ]
        }
      ]
    }
  ],
  "id": "hs_kcgpixmw_1608128593",
  "players": [
    {
      "name": "Dan1"
    },
    {
      "name": "Dan2"
    }
  ],
  "title": "1860",
  "description": "Cloned from game hs_ialvcggt_1608128593",
  "max_players": "2",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-12-16",
  "loaded": true,
  "result": {}
}

**Comment by roseundy** [comment]
Yes, you are missing something. Since your route is only hitting 3 cities, not 4, the unused "city" allowance may be used for towns and halts.
