### ISSUE TITLE
1889 laying Ohzu does not work as noted in Wiki

### ISSUE THREAD

**Issue by coleman07** [tobymao/18xx#2676]
coleman07 owns the Ehime Railroad. UR buys private company. Coleman07 runs UR.  I go into the Entities tab and hit the Ehime Railroad so all text is shown. When I go to the game tab, now Ehime Railway appears as a separate operable company owned by the player UR. The Ohzu hex is yellow. When I try to lay my tile, it says it is not my turn. I can't lay the tile nor pass.

The solution for this game was, buy the private company, go into master mode to lay the tile. The log shows a different player (ER) laying the tile, not me, the owner of both the private and president of the company who bought the private. I then was able to proceed with my turn. I cloned it so maybe you can see what is happening.  hs_yzyqhgks_18573
<img width="689" alt="Screen Shot 2020-12-16 at 1 20 15 PM" src="https://user-images.githubusercontent.com/5997819/102402669-5f3cbd00-3fa2-11eb-9447-a917831319ba.png">

**Comment by ryandriskel** [comment]
Hi Sean. The hotseat games are local to your computer, so we can't access the one you reference. If this was a live game, can you link the game with the action in the history ( use the << and < links next to History ) where this wasn't working?

**Comment by coleman07** [comment]
The link where this picture was taken is https://18xx.games/game/18573?action=246

**Comment by michaeljb** [comment]
@coleman07 the wiki entry was actually outdated, so I've removed that, but you definitely should have been the active player; I've fixed that bug in #2684. Sorry for the inconvenience!
