### ISSUE TITLE
1860: Don't highlight market values of running corporations as gray

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2680]
When a corporation in 1860 has its market price in the gray zone (potential IPO values for bankrupted corporations) the market value is highlighted gray. The suggestion here is to not highlight the market values in this case

![image](https://user-images.githubusercontent.com/2993555/102405672-82259c00-3fb7-11eb-9b9d-cf8939aca32f.png)

**Comment by jenf** [comment]
Add to the NON_HIGHLIGHT_TYPES
