### ISSUE TITLE
18Chesapeake: Cannot sell shares to emergency fund raise trains from other corporations

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2688]
Gist here : https://gist.github.com/ventusignis/df267b063c5aa5bd18d51cf9cce0b970
Expected behavior:
Can emergency fund raise trains from other corporations for up to face value.
Actual behavior:
Trainless corporations may only buy trains from other corporations with cash available between player and corporation
![image](https://user-images.githubusercontent.com/2993555/102500403-4b4c9600-404a-11eb-902b-b0937c4d47e3.png)

**Comment by ryandriskel** [comment]
I'll check this one out

**Comment by ryandriskel** [comment]
I'm a little bit confused. The total player (10) + corporation (321) cash is only $331. That's not $500. This appears to be working correctly except for the display line that indicates the player must raise $569, which is based on the depot price.

In my cloned game, I sold shares to cover the $500 and was able to purchase the train.
<img width="384" alt="Screen Shot 2020-12-17 at 7 54 56 AM" src="https://user-images.githubusercontent.com/15675400/102503681-33bae080-403d-11eb-9cf7-dcbd1ae6f6db.png">

**Comment by ventusignis** [comment]
Thanks Ryan, I see what you mean I'll close this now
