### ISSUE TITLE
[18 Los Angeles] Variant, Using 1846 Priority Deal Rules

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#2691]
I would suggest a variant to 18 Los Angeles that uses the 1846 Priority Deal assignment rules (first to the left of the last player who acted in the previous SR), same as implemented in 1846.  I asked the designer for permission in the following BGG thread  https://boardgamegeek.com/thread/2560897/why-choice-change-priority-token-assignment.  I have no programming skills or I would contribute.  This would be a "toggle" option, a "house rule" variant, the basic would stay as designed by Tony Fryer.

**Comment by tobymao** [comment]
it's not an official variant so i'm closing this for now
