### ISSUE TITLE
1860 error message when submitting 0£ with insolvent company

### ISSUE THREAD

**Issue by daniwelt** [tobymao/18xx#2696]
https://gist.github.com/daniwelt/6c9a3ee81ca82b16b3725697fe2c8a1a.js

Company NGStL is insolvent and needs to run a leased train. If you click "Submit £0" an error text appears: "Step Buy Trains cannot process {"type"=>"dividend", "entity"=>"NGStL","entity_type"=>"corporation","kind"=>"withold"}.

I'm not that much into the rules yet, to explain what options there are with insolvent companies.

![IMG_0785](https://user-images.githubusercontent.com/76153009/102539851-808acf80-40ae-11eb-887a-aff71d3183b4.PNG)

**Comment by roseundy** [comment]
It is illegal to not run a route if a corp has a train and a legal route - which is always true for an insolvent corp. I will add a better error message. There is one case where it is OK: receivership corps during Nationalization.
