### ISSUE TITLE
[18Mex] - Prompt for NdM to remove an extra token.

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2706]
Link: https://18xx.games/game/19294?action=342

CHI has merged into NdM, and NdM needs to remove a token, but nothing prompts the user to do so. A message in the game log would be enough.

**Comment by perwestling** [comment]
It does appear a text at the top: "18MEX: Operating Round 5.1 (of 2) - NdM Select Token to Convert"

But I have now added a help text in the view that describes the choice a bit. Is that good enough, @Auzzy ?
![image](https://user-images.githubusercontent.com/2631151/102997315-172f1480-4525-11eb-8d3b-18adf79d8f70.png)

**Comment by perwestling** [comment]
I changed the 2nd line to
  Remaining CHI token(s) will be removed.

**Comment by Auzzy** [comment]
Wow, you're right, there it is at the top. Turns out we all looked right past it. Yeah, those lines you added look good. Thanks!
