### ISSUE TITLE
1817 wording of redemption

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2710]
SR (ChrisShaffer) takes a loan and receives $100
SR's share price changes from $165 to $150
SR (ChrisShaffer) takes a loan and receives $100
SR's share price changes from $150 to $135
SR buys a 20% share of SR from the market for $270'

That should probably be "SR buys two 10% shares of SR..."

Another example:

A&A buys a 90% share of A&A from the market for $900

should be "A&A buys 9 shares of A&A..."

**Comment by jenf** [comment]
Please provide a game id

**Comment by ChrisTheCat** [comment]
This was five days ago. I have no idea which game it is from now.

**Comment by ChrisTheCat** [comment]
You can see it in any game where someone redeems more than 10% - it always says "buys a 40% share of ..." even if it is 4x10% or 2x20%

**Comment by jenf** [comment]
https://18xx.games/game/19468?action=1256

**Comment by ChrisTheCat** [comment]
Great example
