### ISSUE TITLE
1860 - selling shares doesn’t cause bankruptcy 

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#2713]
https://gist.github.com/Blobbley/43f76441c02baffb6a79f91674387eb5

I sold 3 shares of a company which should have caused the share price to drop 2 spaces as it was in the green. As the share price was 7 this should have caused bankruptcy but didn’t.

**Comment by roseundy** [comment]
This is not a bug. The 8+4 has been purchased at the point. The prevents share prices from dropping on sales.
