### ISSUE TITLE
1860: Selling Green across multiple turns 

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#2714]
https://gist.github.com/Blobbley/eaf4aaf411fa92843eaa53d9c9fa8dbd

From the rules: 
“ When a player sells more than one share in a single company on a single turn, these shares are always counted as being sold at the same time in a single transaction. In this way, Bill may not sell his three shares as three separate sales and so avoid causing the share price to drop.”

In the cloned game attached I sold 3 shares of IOW separately and they did not drop on the second and third occasion.

EDIT: went back to check and if I sold them all at once, price still did not drop.

**Comment by roseundy** [comment]
This is not a bug. The 8+4 has been purchased. Selling no longer reduces share prices.

**Comment by Blobbley** [comment]
This still happened in games pre the 8+ being bought.

**Comment by roseundy** [comment]
Can you please indicate a game? I can't debug without one.

**Comment by Blobbley** [comment]
gist:b042fd627b60f0b7dc817e5082858db9

**Comment by roseundy** [comment]
If you sell more than one share in the green zone it drops. I don't see a bug.

**Comment by Blobbley** [comment]
I think I’m misinterpreting the rule
