### ISSUE TITLE
Outdated game stuck on the main page

### ISSUE THREAD

**Issue by pltnc** [tobymao/18xx#2729]
I think my game 19190 is outdated and we cannot play it anymore? I got stuck in this page and cannot play, delete or remove it. It just stuck on my page. Not so sure what is going to be done about it.

![untitled](https://user-images.githubusercontent.com/76254078/102707479-41d75e00-42d6-11eb-913c-dcb156f57a90.png)

{
  "id": 19190,
  "description": "(Asia timezone) Open Async - several moves a day - let's try a new game",
  "user": {
    "id": 4704,
    "name": "plt&c (hk, utc+8)"
  },
  "players": [
    {
      "id": 1452,
      "name": "chrisdavis103"
    },
    {
      "id": 2886,
      "name": "hyrumli"
    },
    {
      "id": 4704,
      "name": "plt&c (hk, utc+8)"
    }
  ],
  "max_players": 3,
  "title": "1860",
  "settings": {
    "pin": "274d8cf8",
    "seed": 1644764928,
    "unlisted": false,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 3,
  "round": "Stock Round",
  "acting": [
    2886
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "message",
      "entity": 4704,
      "message": "my first 1860, glhf!",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608176210
    },
    {
      "id": 2,
      "type": "message",
      "entity": 2886,
      "message": "@chrisdavis103 Your move",
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608200604
    },
    {
      "id": 3,
      "type": "bid",
      "price": 50,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608201106
    },
    {
      "id": 4,
      "type": "bid",
      "price": 55,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608201694
    },
    {
      "id": 5,
      "type": "bid",
      "price": 60,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608201744
    },
    {
      "id": 6,
      "type": "bid",
      "price": 90,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608202514
    },
    {
      "id": 7,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608202871
    },
    {
      "id": 8,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608202957
    },
    {
      "id": 9,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608203659
    },
    {
      "id": 10,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608203683
    },
    {
      "id": 11,
      "type": "bid",
      "price": 30,
      "entity": 1452,
      "company": "BHC",
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608203704
    },
    {
      "id": 12,
      "type": "bid",
      "price": 30,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608206026
    },
    {
      "id": 13,
      "type": "bid",
      "price": 35,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608207373
    },
    {
      "id": 14,
      "type": "message",
      "entity": 4704,
      "message": "i am not so sure...you can choose which private to buy not the leftest one?",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608209651
    },
    {
      "id": 15,
      "type": "message",
      "entity": 2886,
      "message": "yup, you can choose any privates to buy",
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608209842
    },
    {
      "id": 16,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608212052
    },
    {
      "id": 17,
      "type": "bid",
      "price": 40,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608212447
    },
    {
      "id": 18,
      "type": "bid",
      "price": 45,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608212575
    },
    {
      "id": 19,
      "type": "bid",
      "price": 60,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608212703
    },
    {
      "id": 20,
      "type": "bid",
      "price": 65,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608212715
    },
    {
      "id": 21,
      "type": "bid",
      "price": 70,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608212790
    },
    {
      "id": 22,
      "type": "bid",
      "price": 75,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608212848
    },
    {
      "id": 23,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608212873
    },
    {
      "id": 24,
      "type": "par",
      "entity": 4704,
      "corporation": "C&N",
      "entity_type": "player",
      "share_price": "90,0,24",
      "user": 4704,
      "created_at": 1608212945
    },
    {
      "id": 25,
      "type": "message",
      "entity": 4704,
      "message": "not so sure how much i should pr",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608213060
    },
    {
      "id": 26,
      "type": "message",
      "entity": 4704,
      "message": "*par",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608213064
    },
    {
      "id": 27,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608213068
    },
    {
      "id": 28,
      "type": "message",
      "entity": 4704,
      "message": "is there a 60% limit of shareholding?",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608213150
    },
    {
      "id": 29,
      "type": "par",
      "entity": 4704,
      "corporation": "C&N",
      "entity_type": "player",
      "share_price": "74,0,20",
      "user": 4704,
      "created_at": 1608213165
    },
    {
      "id": 30,
      "type": "message",
      "entity": 2886,
      "message": "nope, you can buy all 100% of your shares in this game",
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608213497
    },
    {
      "id": 31,
      "type": "bid",
      "price": 5,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608213822
    },
    {
      "id": 32,
      "type": "bid",
      "price": 30,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608214265
    },
    {
      "id": 33,
      "type": "bid",
      "price": 35,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608214364
    },
    {
      "id": 34,
      "type": "bid",
      "price": 40,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608220933
    },
    {
      "id": 35,
      "type": "undo",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608220937
    },
    {
      "id": 36,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608220966
    },
    {
      "id": 37,
      "type": "undo",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608220971
    },
    {
      "id": 38,
      "type": "bid",
      "price": 40,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608220993
    },
    {
      "id": 39,
      "type": "bid",
      "price": 50,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608254088
    },
    {
      "id": 40,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608254209
    },
    {
      "id": 41,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608273554
    },
    {
      "id": 42,
      "type": "undo",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608273559
    },
    {
      "id": 43,
      "type": "bid",
      "price": 55,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608273567
    },
    {
      "id": 44,
      "type": "bid",
      "price": 60,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608275155
    },
    {
      "id": 45,
      "type": "bid",
      "price": 65,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608275244
    },
    {
      "id": 46,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608275267
    },
    {
      "id": 47,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608275271
    },
    {
      "id": 48,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608275278
    },
    {
      "id": 49,
      "type": "bid",
      "price": 50,
      "entity": 1452,
      "company": "YHC",
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608275314
    },
    {
      "id": 50,
      "type": "bid",
      "price": 30,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608275353
    },
    {
      "id": 51,
      "type": "bid",
      "price": 35,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608280483
    },
    {
      "id": 52,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608280915
    },
    {
      "id": 53,
      "type": "bid",
      "price": 40,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608283539
    },
    {
      "id": 54,
      "type": "bid",
      "price": 45,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608283865
    },
    {
      "id": 55,
      "type": "bid",
      "price": 50,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608283903
    },
    {
      "id": 56,
      "type": "bid",
      "price": 55,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608283907
    },
    {
      "id": 57,
      "type": "bid",
      "price": 60,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608283921
    },
    {
      "id": 58,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608283932
    },
    {
      "id": 59,
      "type": "bid",
      "price": 130,
      "entity": 2886,
      "company": "RPSC",
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608283954
    },
    {
      "id": 60,
      "type": "bid",
      "price": 35,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608283966
    },
    {
      "id": 61,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608284598
    },
    {
      "id": 62,
      "type": "bid",
      "price": 40,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608290891
    },
    {
      "id": 63,
      "type": "bid",
      "price": 45,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608291063
    },
    {
      "id": 64,
      "type": "bid",
      "price": 50,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608291192
    },
    {
      "id": 65,
      "type": "bid",
      "price": 55,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608293055
    },
    {
      "id": 66,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608295092
    },
    {
      "id": 67,
      "type": "bid",
      "price": 90,
      "entity": 4704,
      "company": "CMH",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608296766
    },
    {
      "id": 68,
      "type": "bid",
      "price": 5,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608297690
    },
    {
      "id": 69,
      "type": "bid",
      "price": 20,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608299395
    },
    {
      "id": 70,
      "type": "bid",
      "price": 25,
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608299447
    },
    {
      "id": 71,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608299458
    },
    {
      "id": 72,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608299459
    },
    {
      "id": 73,
      "type": "bid",
      "price": 25,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608299987
    },
    {
      "id": 74,
      "type": "bid",
      "price": 30,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608301793
    },
    {
      "id": 75,
      "type": "bid",
      "price": 35,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608303924
    },
    {
      "id": 76,
      "type": "bid",
      "price": 40,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608305291
    },
    {
      "id": 77,
      "type": "bid",
      "price": 45,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608305340
    },
    {
      "id": 78,
      "type": "bid",
      "price": 50,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608305827
    },
    {
      "id": 79,
      "type": "bid",
      "price": 55,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608305880
    },
    {
      "id": 80,
      "type": "bid",
      "price": 60,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608305972
    },
    {
      "id": 81,
      "type": "bid",
      "price": 65,
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608306001
    },
    {
      "id": 82,
      "type": "bid",
      "price": 70,
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608306018
    },
    {
      "id": 83,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608306028
    },
    {
      "id": 84,
      "type": "par",
      "entity": 2886,
      "corporation": "IOW",
      "entity_type": "player",
      "share_price": "82,0,22",
      "user": 2886,
      "created_at": 1608306035
    },
    {
      "id": 85,
      "type": "buy_shares",
      "entity": 4704,
      "shares": [
        "C&N_1"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608306281
    },
    {
      "id": 86,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608306398
    },
    {
      "id": 87,
      "type": "undo",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608306461
    },
    {
      "id": 88,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "IOW_1"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608306489
    },
    {
      "id": 89,
      "type": "buy_shares",
      "entity": 2886,
      "shares": [
        "IOW_2"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608306608
    },
    {
      "id": 90,
      "type": "buy_shares",
      "entity": 4704,
      "shares": [
        "C&N_2"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608307228
    },
    {
      "id": 91,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "C&N_3"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608307309
    },
    {
      "id": 92,
      "type": "undo",
      "entity": "C&N",
      "entity_type": "corporation",
      "user": 1452,
      "created_at": 1608307325
    },
    {
      "id": 93,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "IOW_3"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608307353
    },
    {
      "id": 94,
      "type": "buy_shares",
      "entity": 2886,
      "shares": [
        "IOW_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608308183
    },
    {
      "id": 95,
      "type": "buy_shares",
      "entity": 4704,
      "shares": [
        "C&N_3"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608308238
    },
    {
      "id": 96,
      "hex": "F2",
      "tile": "787-0",
      "type": "lay_tile",
      "entity": "C&N",
      "rotation": 0,
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608308245
    },
    {
      "id": 97,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "IOW_5"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608337354
    },
    {
      "id": 98,
      "type": "undo",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608337362
    },
    {
      "id": 99,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "C&N_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608337409
    },
    {
      "id": 100,
      "type": "buy_shares",
      "entity": 2886,
      "shares": [
        "IOW_5"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608337548
    },
    {
      "id": 101,
      "type": "buy_shares",
      "entity": 4704,
      "shares": [
        "C&N_5"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608339688
    },
    {
      "id": 102,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "IOW_6"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608339829
    },
    {
      "id": 103,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608340682
    },
    {
      "id": 104,
      "type": "message",
      "entity": 2886,
      "message": "Autopass for me thanks",
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608340710
    },
    {
      "id": 105,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608340972
    },
    {
      "id": 106,
      "type": "message",
      "entity": 4704,
      "message": "chris do what u want and pass for me using master mode also",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608341001
    },
    {
      "id": 107,
      "type": "message",
      "entity": 4704,
      "message": "thx",
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608341005
    },
    {
      "id": 108,
      "type": "message",
      "entity": 1452,
      "message": "ok",
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608342342
    },
    {
      "id": 109,
      "type": "buy_shares",
      "entity": 1452,
      "shares": [
        "IOW_7"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608342354
    },
    {
      "id": 110,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608342391
    },
    {
      "id": 111,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608342396
    },
    {
      "id": 112,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608342413
    },
    {
      "id": 113,
      "hex": "J4",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "IOW",
      "rotation": 1,
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608342464
    },
    {
      "id": 114,
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608342472
    },
    {
      "id": 115,
      "type": "buy_train",
      "price": 250,
      "train": "2+1-0",
      "entity": "IOW",
      "variant": "2+1",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608342473
    },
    {
      "id": 116,
      "type": "buy_train",
      "price": 250,
      "train": "2+1-1",
      "entity": "IOW",
      "variant": "2+1",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608342474
    },
    {
      "id": 117,
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608342480
    },
    {
      "id": 118,
      "hex": "F4",
      "tile": "742-0",
      "type": "lay_tile",
      "entity": "C&N",
      "rotation": 3,
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608343591
    },
    {
      "id": 119,
      "hex": "G3",
      "tile": "741-0",
      "type": "lay_tile",
      "entity": "C&N",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608343594
    },
    {
      "id": 120,
      "city": "G5-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "C&N",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608343600
    },
    {
      "id": 121,
      "type": "buy_train",
      "price": 250,
      "train": "2+1-2",
      "entity": "C&N",
      "variant": "2+1",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608343606
    },
    {
      "id": 122,
      "type": "buy_train",
      "price": 250,
      "train": "2+1-3",
      "entity": "C&N",
      "variant": "2+1",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608343631
    },
    {
      "id": 123,
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608343633
    },
    {
      "id": 124,
      "type": "pass",
      "entity": 2886,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608344194
    },
    {
      "id": 125,
      "type": "pass",
      "entity": 4704,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608344747
    },
    {
      "id": 126,
      "type": "sell_shares",
      "entity": 1452,
      "shares": [
        "C&N_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608365250
    },
    {
      "id": 127,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608365260
    },
    {
      "id": 128,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608365295
    },
    {
      "id": 129,
      "hex": "I5",
      "tile": "742-1",
      "type": "lay_tile",
      "entity": "IOW",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608370055
    },
    {
      "id": 130,
      "hex": "H4",
      "tile": "744-0",
      "type": "lay_tile",
      "entity": "IOW",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608370060
    },
    {
      "id": 131,
      "city": "5-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "IOW",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608370061
    },
    {
      "id": 132,
      "type": "run_routes",
      "entity": "IOW",
      "routes": [
        {
          "train": "2+1-0",
          "connections": [
            [
              "J4",
              "I3"
            ]
          ]
        },
        {
          "halts": 1,
          "train": "2+1-1",
          "connections": [
            [
              "G3",
              "G5"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "H4"
            ],
            [
              "H4",
              "I5"
            ],
            [
              "I5",
              "J4"
            ]
          ]
        }
      ],
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608370105
    },
    {
      "id": 133,
      "kind": "payout",
      "type": "dividend",
      "entity": "IOW",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608370109
    },
    {
      "id": 134,
      "type": "pass",
      "entity": "IOW",
      "entity_type": "corporation",
      "user": 2886,
      "created_at": 1608370142
    },
    {
      "id": 135,
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608370264
    },
    {
      "id": 136,
      "type": "run_routes",
      "entity": "C&N",
      "routes": [
        {
          "halts": 0,
          "train": "2+1-2",
          "connections": [
            [
              "F4",
              "G5"
            ],
            [
              "F4",
              "F2"
            ],
            [
              "F2 1.2"
            ],
            [
              "F2 0.1"
            ]
          ]
        },
        {
          "halts": 1,
          "train": "2+1-3",
          "connections": [
            [
              "I5",
              "J4"
            ],
            [
              "H4",
              "I5"
            ],
            [
              "H4"
            ],
            [
              "H4",
              "G3"
            ],
            [
              "G3",
              "G5"
            ]
          ]
        }
      ],
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608370319
    },
    {
      "id": 137,
      "kind": "payout",
      "type": "dividend",
      "entity": "C&N",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608370321
    },
    {
      "id": 138,
      "type": "pass",
      "entity": "C&N",
      "entity_type": "corporation",
      "user": 4704,
      "created_at": 1608370341
    },
    {
      "id": 139,
      "type": "buy_shares",
      "entity": 2886,
      "shares": [
        "C&N_6"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 2886,
      "created_at": 1608370822
    },
    {
      "id": 140,
      "type": "buy_shares",
      "entity": 4704,
      "shares": [
        "C&N_7"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 4704,
      "created_at": 1608371065
    },
    {
      "id": 141,
      "type": "sell_shares",
      "entity": 1452,
      "shares": [
        "IOW_1",
        "IOW_3",
        "IOW_6",
        "IOW_7"
      ],
      "percent": 40,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376082
    },
    {
      "id": 142,
      "type": "par",
      "entity": 1452,
      "corporation": "IWNJ",
      "entity_type": "player",
      "share_price": "82,0,22",
      "user": 1452,
      "created_at": 1608376173
    },
    {
      "id": 143,
      "type": "undo",
      "entity": 2886,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376228
    },
    {
      "id": 144,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376230
    },
    {
      "id": 145,
      "type": "sell_shares",
      "entity": 1452,
      "shares": [
        "IOW_1",
        "IOW_3",
        "IOW_6"
      ],
      "percent": 30,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376281
    },
    {
      "id": 146,
      "type": "undo",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376297
    },
    {
      "id": 147,
      "type": "sell_shares",
      "entity": 1452,
      "shares": [
        "IOW_1",
        "IOW_3",
        "IOW_6",
        "IOW_7"
      ],
      "percent": 40,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376302
    },
    {
      "id": 148,
      "type": "par",
      "entity": 1452,
      "corporation": "FYN",
      "entity_type": "player",
      "share_price": "82,0,22",
      "user": 1452,
      "created_at": 1608376371
    },
    {
      "id": 149,
      "type": "pass",
      "entity": 1452,
      "entity_type": "player",
      "user": 1452,
      "created_at": 1608376491
    }
  ],
  "loaded": true,
  "created_at": 1608173274,
  "updated_at": 1608376491
}

**Comment by roseundy** [comment]
This can be fixed by deleting the last "pass" from the json. I have no idea how it got into this state.

**Comment by pltnc** [comment]
How to delete that? I dont know how to use json but this shows up:
We're sorry this game cannot be continued due to GameError: Step Sell then Buy Certificates cannot process {"type"=>"pass", "entity"=>1452, "entity_type"=>"player", "id"=>149}

Version 274d8cf8

> This can be fixed by deleting the last "pass" from the json. I have no idea how it got into this state.

**Comment by roseundy** [comment]
It's been fixed. Try it now.

**Comment by roseundy** [comment]
Closing, as I believe the issue has been resolved.
