### ISSUE TITLE
#58 Small town rendering off the track

### ISSUE THREAD

**Issue by jrebs** [tobymao/18xx#273]
The same 58 tile placed elsewhere in our game renders fine but the one placed at J9 has the small town floating in the wrong location based on the track orientation. Image attached.

![image](https://user-images.githubusercontent.com/4203789/80922912-18f95d00-8d35-11ea-8fdd-f978f0e0cc39.png)

https://18xx.games/game/263#map

**Comment by tobymao** [comment]
@kelsin

**Comment by gchambers419** [comment]
Same failure if the Port tile (437) is placed there

**Comment by kelsin** [comment]
Yep, I'll be checking this out when abstracting the positioning code later. Thanks!

**Comment by kelsin** [comment]
This is fixed now.

**Comment by jrebs** [comment]
Looks good. Thanks.
