### ISSUE TITLE
1860 - tile orientation on tile lay limited

### ISSUE THREAD

**Issue by vantdog** [tobymao/18xx#2734]
Tried to lay home tile for NGStL - would not allow me to choose the tile orientation - only let me lay it one way. 

https://18xx.games/game/19485?action=155

**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by vantdog** [comment]
happened again - this time with a different company - in both cases it was the yellow B tile - 

https://18xx.games/game/19485?action=231

**Comment by roseundy** [comment]
Yeah, I biffed the fix for the game locking up when no tiles are available for the home tile lay. My fix tests to see if any tiles exist by calling upgradeable_tiles. Unfortunately this has side-effects and causes problems when called by Step::home_track multiple times.

**Comment by vantdog** [comment]
> Yeah, I biffed the fix for the game locking up when no tiles are available for the home tile lay. My fix tests to see if any tiles exist by calling upgradeable_tiles. Unfortunately this has side-effects and causes problems when called by Step::home_track multiple times.
> 
> The net result is that you can't change the rotation of the tile being layed for the home hex.

did notice that it happened one more time - (for SC) - and wasn't a yellow B - just fyi

Thanks for all your work on this one - love that 1860 is on the site now

**Comment by roseundy** [comment]
Thanks. The bug should occur for any home tile lay, not just B-tiles.
