### ISSUE TITLE
Newly cloned hotseat games receive updates from server as long as the actions are the same as the server game

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#2736]
Expected behavior: once a game is cloned, that new hotseat game is completely independent from its source multiplayer game

Actual behavior:
- if the new clone is left untouched, when actions are performed on the server, they propagate to the clone
- even if an action is done in the clone before being done on the server, if the same action is done on the server, then the next action on the server will propagate to the clone
- an action must be executed in the clone that is different from an action on the server in order for the clone to become independent

In this video, in tab 1 I'm on the server as michaeljb, tab 2 is michaeljb2, and tab 3 is not logged in and is where the game is cloned. https://drive.google.com/open?id=1xGbVe1RNkjsEnagNlLrgxI-JYhNS9WYW

**Comment by PedroRCSequeira** [comment]
i've noticed this before too, one thing i believe solves this (and i just managed to replicate) is:

close a game
watch it keep getting updates
open a net tab, go to the main page and open the clone

you will have 2 tabs with the cloned game, the first one will keep getting updates, the second (new) won't

it's weird :D and just a bit annoying if you have a bunch of hotseat games, else it's just a small delay
