### ISSUE TITLE
1846 2-Player Variant Does Not Reduce Certificate Limit When Company Closes

### ISSUE THREAD

**Issue by PatrickoftheIsles** [tobymao/18xx#2737]
According to the 2-player variant rules linked to by 18xx.games: 

"The certificate limit is 19. If one or more corporations close, the limit becomes 16."

In our recent game, a company closed at the end of OR 1.2, but the certificate limit remained at 19 all game rather than reducing to 16.

https://18xx.games/game/19507

**Comment by michaeljb** [comment]
Thanks for reporting this @PatrickoftheIsles!
