### ISSUE TITLE
1817: Bids allowed to be made even though all 70 loans are already taken

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#2738]
When all 70 loans are taken in a game, bids for liquidation and acquisition can only be made for the cash available in the companies since no additional loans may be taken.  Implementation allows illegal bids to be made up to the loan limit of the company making the bid despite no loans being available to fulfill the bid obligation.

See example here: https://18xx.games/game/19468

**Comment by jenf** [comment]
Was fixed by #2768
