### ISSUE TITLE
Rule 8.1e: Trains can reverse at junctions and run to exits on a tile that are not valid

### ISSUE THREAD

**Issue by altorio** [tobymao/18xx#274]
<img width="926" alt="Captura de pantalla 2020-05-03 a las 19 06 11" src="https://user-images.githubusercontent.com/64750181/80923340-613f6c00-8d83-11ea-8b53-2f0bb12e38e3.png">
Hi, first of all thanks a lot for such a great page. I think we have detected 2 errors.
1) It shouldn't allow 2 trains from c10 to c8.
2) It shouldn't allow the route from c10 to the east.

Hope it helps,

Regars, Alejandro

**Comment by jenf** [comment]
Rephrasing and splitting into two bugs
1) KU is running two trains over the same piece of track (C10 and C8) split to #303
2) C10, C8, D9 the C8 to D9 is not possible due to the shape of the track as the only valid exits are B7 and C6

**Comment by jenf** [comment]
1889 Rule 8.1e
