### ISSUE TITLE
Teleport doesn't work if no track has been laid during the game

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#2745]
I've noticed this while working on 1856 and was able to reproduce it in 18Chesapeake. 'teleport' company abilities are not usable unless a corporation has laid track somewhere. In my test, the CA, which bought in the teleport private, was not able to teleport until a corporation has laid any track, either the CA (on a previous turn because one track action per turn) or the BBG needed to lay track before the teleport would work

**Comment by michaeljb** [comment]
I noticed this while looking at #1520, but apparently didn't note it on that issue. I'm currently working towards a solution on this and some other ability timing issues.
