### ISSUE TITLE
Game ID / Description should be obvious while in the game

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#276]
One player I'm playing with has reported difficulty in keeping track of multiple async games, especially since he has a common opponent in those games. I think adding the game ID and description to the main game tab, or maybe even everywhere, would help with that.

**Comment by michaeljb** [comment]
This somewhat relates to #157

**Comment by Azuureth** [comment]
Further suggestion. It would be nice to know at least when it's your turn to act just by looking at the tab. Full info or just an (1) at the end of the 18xx.games
