### ISSUE TITLE
Allow "sandbox" tile lays when in MAP view.  

### ISSUE THREAD

**Issue by Tin-Whisker** [tobymao/18xx#2778]
Please describe your idea and why we should consider it.
When on Map tab, allow clicking on any hex and seeing and even placing tiles and then seeing the possible upgrades from there.  This would only be temporary while on that tab.  

This helps with route planning for future lays and even when deciding on a company launch during SR.  There are also a lot of people who cannot visualize well without seeing the tile on the board.  

Thanks for considering

**Comment by jenf** [comment]
dup of #1279
