### ISSUE TITLE
Ability to clean out old finished games or sort by game

### ISSUE THREAD

**Issue by coleman07** [tobymao/18xx#2790]
Please describe your idea and why we should consider it.
It would be nice to sort your previous games by the title to know how many of what you played or be able to clean up your space, removing old games played. Not sure if it is possible since there are multiple players but wouldn't one of the database tables have a "pointer" to game data by player name?

**Comment by yzemaze** [comment]
It’s more or less a dup of #782 (also of note: #1311, #2129). We are working on finally fixing this issue, but it will take some time.
