### ISSUE TITLE
[1817WO] - Should be sent into cash crisis during liquidation

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2797]
Game link: https://18xx.games/game/19931?action=981

Both auzzy and bendow had shorts in a company which was bought during liquidation. The purchase is enough to send both into cash crisis - they both show negative cash amounts. But neither is prompted to resolve it until the next OR, after the first railroad lays its first track (https://18xx.games/game/19931?action=983).

**Comment by ventusignis** [comment]
https://18xx.games/game/19931?action=763#entities

**Comment by ventusignis** [comment]
I was able to reproduce this in 1817 with an convoluted demonstration
https://gist.github.com/ventusignis/276d71d15ef431cdda35add8c743aa22

**Comment by cfcurtis** [comment]
Same issue here in 1817NA, the president of NYOW wasn't prompted to pay off the 10 loans when it liquidated. I should have bankrupted yet am still in the game and the loans seem to have just vanished.
https://18xx.games/game/21935?action=1398

**Comment by jenf** [comment]
Problem is cash crisis caused when corporation was owned by the market
