### ISSUE TITLE
Unplaced tiles remain when switch from Map to Game view

### ISSUE THREAD

**Issue by andybeta** [tobymao/18xx#28]
During tile placement, switch to Map view, click on a valid location to bring up the available tile selections, then switch back to the Game view. The tiles remain, overlaying the text.
![tiles_overlayed](https://user-images.githubusercontent.com/4150843/79153140-494c7c00-7dc5-11ea-9c7d-2cf3d5e25089.png)

**Comment by rheretic** [comment]
OP:  I would retry this to see if it's still present.  Quite a bit of code change since you opened this.

**Comment by jenf** [comment]
Still present, will have a look as part of the 1882 token selector changes
