### ISSUE TITLE
[18CZ] Rule Implementation

### ISSUE THREAD

**Issue by Zwergenpunk** [tobymao/18xx#2803]
Impelementation is found [Here](https://github.com/Zwergenpunk/18xx/tree/feat/18cz-map) 

**Configuration and map**

- [x]  Basic configuration
- [x] Event info
- [x] No Limit Bank
- [x]  Cash per Player
- [x] Game end: Private Company Marker runs to end of track
- [x]  Corporations configuration
- [x] Private configuration
- [x] Trains configuration
- [x]  Cert limit

**Map**

 - [x]  Add base map
 - [x] Add special starting tiles for large corporations
 - [x] Add purple borderd tiles

**Trains**
- [x] Add Rusting of trains
- [x]  Some corporations may buy only small trains
- [x]  Plus Trains
- [x]  E Trains

**Corporations**
- [x] Logos
- [x] Different Par values for corporations
- [x] Differenz Share amount
- [x] full cap (>=50% float)

**Private Companies**
- [x] Buyable in in phase 2 for up to current private value
- [x] Sellable from corporation to bank for current private value
- [x]  Special Bonus 
    - [x]  Place purple tile or
    - [x]  Ignore Hex costs depending on size of company

**Stock Market**
- [x] Player order for first SR is ordered by least money left
- [x] 2 Line Stock Market
- [x]  No Market - Just IPO
- [x] Different sizeed corporations are available at different phases
- [x] No sell Limit, but president share cannot never be sold to bank. only changed with other player
- [x] ATE may choose in which city the starting token is placed
- [x] Tile may also be placed in home city when there is not tile yet
- [x] When Sold out at the end of SR moves 1right up or 1 right down
- [x] When selling share it moves 1 left up or 1 left down
- [x]  Player may not buy shares until his dept is payed off
- [x]  Player order for next SR is ordered by most money left

**Operation rounds**
- [x] Income of prives
- [x] Player order - market value descending
- [x] Track building: 1 or (first turn after float) 2 yellow tiles or upgrade placed tile it upgrade printed tile (praha)
- [x]  Large corporations may build red special tile + token in first OR
- [x] B9 may only be tokened after ATE tokened there first
- [x] Running of different trains
    - [x]  normal Trains
    - [x]  plus Trains
    - [x]  E -Trains
- [x] Placing a track near Praha has to be connected to Praha (rendered but not restricted)
- [x] Payout moves 1 (2 for large corporations) to right
- [x] withhold always 1 left 
- [x] Merging of corporations
- [x]  Emergency Train Buy 
    - [x] Player may not sell shares to gain money for emergency buy
    - [x] Player has to take loan and this adds -100%  of the loan to his values  (penalty interest)
- [x] Export of trains

**Comment by OedipussyRex** [comment]
Two issues I see, 1) Full cap >=50% to float, not >=60%; and 2) In the __Stock Market__ section, "When Sold out at the end of SR moves 1right up and 1 ~~left~~ right down."

There should probably also be a check for share limit in a company of 75% for small companies (3 shares, 2 certs) and 60% for medium (3 shares, 2 certs) and large (6 shares, 5 certs).

**Comment by benjaminxscott** [comment]
Some of these are handled by default, I'd suggest changing those to a regular bullet to denote that they are already handled (e.g. `-` instead of `- [ ]`)

I don't see a bullet for the player reordering, which is 

```
SR1: The player with the *least* money takes the lowest-numbered Playing Order Card (gets priority deal) . The player with the second least money left takes the next higher-numbered Playing Order Card and so on. Resolve any ties so that the player who was earlier in the old order is also earlier in the new order. 
```

```
Future SRs: The player with the *most* money left at the end of the Stock Round takes the lowest-numbered Playing Order Card (gets priority deal). The player with the second most money left takes the next higher-numbered Playing Order Card and so on. Resolve any ties so that the player who was earlier in the old order is also earlier in the new order. 
```

**Comment by Zwergenpunk** [comment]
> Some of these are handled by default, I'd suggest changing those to a regular bullet to denote that they are already handled (e.g. `-` instead of `- [ ]`)
> 
> I don't see a bullet for the player priority reordering, which is determined at the end of the initial auction and then at the end of each SR
> 
> ```
> after initial auction: The player with the *least* money takes the lowest-numbered Playing Order Card (gets priority deal) . The player with the second least money left takes the next higher-numbered Playing Order Card and so on. Resolve any ties so that the player who was earlier in the old order is also earlier in the new order. 
> ```
> 
> ```
> at the end of future SRs: The player with the *most* money left at the end of the Stock Round takes the lowest-numbered Playing Order Card (gets priority deal). The player with the second most money left takes the next higher-numbered Playing Order Card and so on. Resolve any ties so that the player who was earlier in the old order is also earlier in the new order. 
> ```

Included. Thanks

**Comment by OedipussyRex** [comment]
No other company may place a token in Usti nad Labem/Aussig or Teplice/Teplitz (ATE's home hex) until the ATE has chosen its home city. This rule holds even if the tile has been upgraded to brown and the two cities have merged.

**Comment by OedipussyRex** [comment]
Question: "Track may not 'enter' border of special places marked for red tiles of corporations." By this do you mean that you cannot lay a track tile in a red-bordered hex or that you cannot lay a tile in a hex next to a red border such that the track leads to the red border? Because the latter most certainly is allowed.

**Comment by OedipussyRex** [comment]
Home station (home tile for large companies) is not placed until the start of the company's first operation.

Yellow track in hexes northeast and southeast of Praha (D12 and F12) must be laid to connect to Praha.

**Comment by Zwergenpunk** [comment]
> No other company may place a token in Usti nad Labem/Aussig or Teplice/Teplitz (ATE's home hex) until the ATE has chosen its home city. This rule holds even if the tile has been upgraded to brown and the two cities have merged.

Added the rule


> Question: "Track may not 'enter' border of special places marked for red tiles of corporations." By this do you mean that you cannot lay a track tile in a red-bordered hex or that you cannot lay a tile in a hex next to a red border such that the track leads to the red border? Because the latter most certainly is allowed.

Oh wow. I totally misread that rule. Thanks ;)

> Home station (home tile for large companies) is not placed until the start of the company's first operation.

Yeah thats what I had in mind
 
> Yellow track in hexes northeast and southeast of Praha (D12 and F12) must be laid to connect to Praha.

All of these mini rules are hard to catch all ;)


 Thanks

**Comment by benjaminxscott** [comment]
> Yellow track in hexes northeast and southeast of Praha (D12 and F12) must be laid to connect to Praha.
I'd propose to set a `stub` for those hex edges, to implement this (essentially pre-printed track)

**Comment by benjaminxscott** [comment]
Looks like this is ready for alpha imo

**Comment by Zwergenpunk** [comment]
Yeah nearly. I want to double check how the stock market behaves when selling etc., because I never did ;) 

But if thats alright I think its ready
