### ISSUE TITLE
1882 instructions needed on how to close Saskatchewan Central

### ISSUE THREAD

**Issue by coleman07** [tobymao/18xx#2808]
I would like to use my SC power but their is no button available to convert it to 10% of SC - need instructions or something;
https://18xx.games/game/19269?action=359

https://gist.github.com/coleman07/a11e43544871a2cf0dcb2134d9e6a4bc

**Comment by Maxwell-Frank** [comment]
You can only close the private to convert to the presidency of the SC on your turn in a stock round.

**Comment by coleman07** [comment]
I figured out that I just buy SC and I get my 10% - just not clear
