### ISSUE TITLE
18CO -- UI Shares to Float is Deceptive, since it can Change

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#2811]
This is a temporary suggestion for 18CO.  Because the number of shares needed to float a company changes based on the par price, but the UI does not take that into account and shows the number of shares needed to float a company based on the company's class, I would suggest to temporarily remove the number of shares needed to float the company from the UI pending a real implementation (which would show the different amounts for different par prices).  This will eliminate a source of confusion for new players.

**Comment by luigicoolGH** [comment]
I would like to further clarify what the current issue is with the UI in my opinion.  Say for example that you are a new player, and you want to par your first Class III company (e.g., KPAC), and are looking at the UI to choose the par price that will allow you to float it based on your finances.  You would see (1) that you only need 40% to float the company (KPAC is  Class II and the UI shows you the flotation requirements for a Class III) and (2) the number of shares you can buy at different par prices (simple math) based on your finances regardless of Class type.  The problem is that if you choose to par this Class III company at a price in the Class II or Class I category the UI is giving you the wrong information (telling you you only need 40%), since you would need a greater number of shares to float (e.g., 50% at Class II).  Since I cannot think of a way to have the UI give float requirements based on par price in real time, it might be better to remove the UI float information.  Alternatively, the par action would have to be in two steps, with confirmation, but that might be too much trouble for too little gain.

**Comment by ryandriskel** [comment]
I understand what you are saying luigi. I think having the par group listed will help significantly, however I will reopen this request and think on it.

**Comment by pstone1** [comment]
Just saw another group have this same issue, even with it now being displayed in the log in chat: https://18xx.games/game/19870?action=325 

Perhaps you could have it display each par price, the number you can afford, and the number required, for example taking the above action to buy a DSL share at $80 would show: 
$80 (4/5)
where /# is the number needed to float at that price. So it would be more obvious that likely the better play would be to buy at $75 since that would say:
$75 (4/4)
