### ISSUE TITLE
18CO- Green Denver Tile is Missing Revenue Value

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#2814]
In 18CO, the manifest (and IIRC, the actual tile) does not display the revenue provided by the Denver (D) tile. 

https://18xx.games/game/20105#tiles

**Comment by ryandriskel** [comment]
For any other devs, I've had a devil of a time trying to get the revenue to fit on the tile. Feel free to help me out :D

**Comment by ryandriskel** [comment]
Referenced on https://github.com/tobymao/18xx/issues/2671

**Comment by roseundy** [comment]
Sigh. Another "pointy" map issue. Pretty sure it would render fine for the "flat" orientation (see 18Mex).
