### ISSUE TITLE
Improve Card Notation for Variable Certificate Sizes

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#2816]
The player card should display the number of certificates next to the percentage share owned as a general language for cases where there are share certificates available for shares other than 10%.

A player in 1817 with 2 shares of a 5 share company and 4 shares of a 10 would display:

PLE 40% (2)
DLSW 40% (4)

This is also useful for titles like 18Mex and CO for companies with special shares:

NdM 30%* (1) -Player owns the presidency and two 5% shares which do not count to cert limit
DSNG 40% (3) -Player owns the 20% share of DSNG and two 10% shares, but not the presidency
DSNG 50%* (4) -Player owns the presidency and three 10% shares of DSNG

The (#) on a player card next to all companies should always add up to that players cert count, and will serve as a useful breakdown of where your cert count is coming from. This seems preferable to some sort of notation that indicates each individual type of share, such as (d) for double shares and (h) for half because it is universal to all games, and the count of certificates is the most relevant piece of information for gameplay.

**Comment by tobymao** [comment]
this is a dup #1630
