### ISSUE TITLE
1817 log timing issue

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2822]
https://18xx.games/game/20116?action=1208

<img width="1266" alt="Screen Shot 2020-12-26 at 6 05 19 PM" src="https://user-images.githubusercontent.com/8732435/103162403-11476680-47a5-11eb-8d06-8d4fd400195a.png">

The log already says the J is being liquidated, but the actual action that is relevant is the B&A completing the WC acquisition by selecting which token to retain in New York City.

**Comment by ChrisTheCat** [comment]
Another example of a log ordering issue. A&S settled with shareholders, causing a cash crisis for chanmancan and ChrisShaffer. However, the line "GT may be offered for sale" appears first.

https://18xx.games/game/14420?action=1351

<img width="910" alt="Screen Shot 2021-01-05 at 5 43 16 PM" src="https://user-images.githubusercontent.com/8732435/103719333-a56fb580-4f7d-11eb-93ed-3f0f73e6f09d.png">

**Comment by jenf** [comment]
Won't fix, would require a complete rewrite.
