### ISSUE TITLE
1817 - Two corps liquidating in a row: Out of order status description

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#2823]
https://18xx.games/game/20116?action=1208

At this action the B&A has purchased the WC in a Liquidation Sale.  After the sale, the B&A has two tokens in NYC (one in north (former WC) and one in South NY.  The B&A player now must choose which token in NYC to keep, before the next Liquidation sale.

However, confusingly, during this choice (at action 1208, where the B&A player is choosing which station in NYC to keep), the status message being shown in the chat is: 

_"J is being liquidated, bank offers $0, corporation had $24 and 4 loans"_

Followed by:
_"B&A removes token from E22"_

These are simply being displayed out of order.  The "J is being liquidated" shouldn't be shown until after the tokens have been settled on the previous liquidation.

**Comment by jenf** [comment]
Not gonna fix
