### ISSUE TITLE
Add option to run same route again

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#283]
Could be nice addition for times where you have the route already done so you could just press one button to do it again or option to save routes.

**Comment by scottredracecar** [comment]
Alternatively, there could be a "Total Earnings" manual entry field that is pre-populated with the previous rounds earnings and a confirmation button. Entering the earnings here would bypass the "trace train routes" step.

Possible issue with this might be if users think that the system is autocalculating earnings, but in general would be a flexible solution to solve this problem and be a nice workaround if there are bugs with the earnings calculations.

![image](https://user-images.githubusercontent.com/29106780/81008582-ca24f380-8e18-11ea-9c13-daddb303177e.png)

**Comment by jenf** [comment]
I'd be very wary of making this change until we fix a lot of the permissive route bugs that are open.

**Comment by jenf** [comment]
Lots of the permissive route bugs are now fixed, picking up.

**Comment by jenf** [comment]
fixed
