### ISSUE TITLE
1817NA Bug - Coal on mountain hex next to klondike

### ISSUE THREAD

**Issue by wheresvic** [tobymao/18xx#2846]
In game **https://18xx.games/game/18827**, PSNR is not able to lay a coal on track heading into klondike from A3. Is Klondike not a revenue center?

**Comment by Maxwell-Frank** [comment]
The 1817 rules do specify that the coal mine must be placed adjacent to a "city or red off-board location," but there are no mountain hexes adjecent to Toronto, so we have no way to know whether that distinction was intentional, or simply written that way for clarity.

**Comment by wheresvic** [comment]
Yes but isn't Toronto also a "city"? It is just a fixed city that does not upgrade but in that regard it is similar to the original Cleveland (with the difference being that Cleveland has spots for tokens).

**Comment by Maxwell-Frank** [comment]
Oh...that does sound familiar. I would say that you should be able to lay coal there then, but I am not an authority on this.

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/103253508-8a82bd00-494f-11eb-9585-2a85c873b984.png)
This is the area in question - should it be possible to lay coal to connect the track to Anchorage?

**Comment by wheresvic** [comment]
> ![image](https://user-images.githubusercontent.com/2993555/103253508-8a82bd00-494f-11eb-9585-2a85c873b984.png)
> This is the area in question - should it be possible to lay coal to connect the track to Anchorage?

I think you mean Klondike because that is where the connection fails. Anyhow, I found the fix in the code - klondike is marked as a town (probably for visual purposes) and the code only includes cities and offboard locations. Will submit a fix for this.
