### ISSUE TITLE
Log on separate tab

### ISSUE THREAD

**Issue by leisenstein** [tobymao/18xx#2851]
A convenient feature would be the ability to have your log on a separate tab.

- This would allow you to be able to see more of the log and easily scroll through It. 
- You can keep the log open on a separate tab or even on a mobile device while you're playing.
- this could also make adding features to the logging tab easier such as filters for verbosity levels or changes in last 24hrs/since last move...

**Comment by perwestling** [comment]
Maybe a duplicate to #1263?
