### ISSUE TITLE
[1860]P https://18xx.games/game/20388

### ISSUE THREAD

**Issue by PaulKT** [tobymao/18xx#2871]
So we think this is a bug after 9 train had been purchased Southern Rail had been formed and companies started being nationalised it was our understanding that track could not be laid or upgraded (whilst we obeyed the rule and did not do this, so cannot send you to exactly what happened) it was definitely available right up to the last OR of the game (9.4 in our case). Just to let you know.

Hope this helps, it didn't damage our game in any way as we self policed and maybe we got the rule wrong?

Cheers,
Paul

**Comment by roseundy** [comment]
You got the rule wrong - although that's pretty understandable considering the designer didn't even realize the implications of how he wrote the rules.

If there is no stock round between buying the 9T and Nationalization starting, then you can still lay track and tokens.  See this thread on BGG: https://boardgamegeek.com/thread/1043393/southern-formationbritish-rails-nationalization-qu#

I've also documented this in the FAQ.
