### ISSUE TITLE
Abilities not supported for minors

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2875]
If adding abilities to minor corporations they are not shown in the gui.

When running config_spec.rb test, these abilities fail. If printing the read abilities it looks like ["type" .... instead of {type: ....

By having abilities on minors it is possible to have different behaviors for minors, e.g. may buy train, may not buy. Also the difference from corporations could be expressed as abilities.

**Comment by michaeljb** [comment]
I think the `minors` block here just needs the same `company[:abilities]&.each { |ability| ability.transform_keys!(&:to_sym) }` line that companies and corporations get:

https://github.com/tobymao/18xx/blob/0dfff13591e5a5d1bce74428f0c186789267ca0d/lib/engine/game/base.rb#L367-L386

**Comment by roseundy** [comment]
I believe I've fixed the issues with ability strings needing to be mapped to symbols. I'm not closing this, though, since it worked fine in hotseat and blew up running multiplayer. It never had the symptom that you describe.
I think the problem you are seeing is that the GUI only shows abilities for privates, not minors. That's a separate fix.

**Comment by jenf** [comment]
Is this actually needed for any actively developed titles?

**Comment by perwestling** [comment]
@jenf Sort of. 1824 is an example, where the Coal Corporations and Pre-Staatsbahn are minors. They could have use for abilities. As it is now some information presented use the minor/corporation status string. But I could add base ability to put in more info.

The train limit has been handled in another way. 
No buy train is pretty common (in 18SJ, 18MEX) and could be handled as an ability.

So I think this is a worthwile enhancement.

**Comment by tobymao** [comment]
do we still need this?

**Comment by scottredracecar** [comment]
closing, if this gets implemented via 1824, that will be great, but there is no real demand
