### ISSUE TITLE
Extensive description in abilities

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2876]
The restrictions to only have one ability per type, and only show a short description, makes it hard to show game information in the minor/corporation. 

This could be enhanced by doing for example:

- Show a description, which has a long description connected to it, that shows when clicked on description
- Make it possible to have a multi line description (e.g. a list of strings) and show all

**Comment by ryandriskel** [comment]
Similar to https://github.com/tobymao/18xx/issues/1374

**Comment by yzemaze** [comment]
Dup
