### ISSUE TITLE
Undo and player names overlap

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#288]
Seen in game id 521

![image](https://user-images.githubusercontent.com/71923/80971511-cd1de500-8e14-11ea-9ff0-f8fa24ce007f.png)

**Comment by dfannius** [comment]
Hmm, I wonder if #277 has issues on mobile. I know Toby wantd to put the whole thing in a single scrollable row anyway, which would fix this as a side effect.

**Comment by jenf** [comment]
yeah i'd suspect it is #277
