### ISSUE TITLE
[1867] Bidding for minors capped

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2886]
Bidding for minors is capped at $270, double the maximum starting value for minors of $135, instead of allowing the bid to go higher but the final value being the limit. Don't know if this is a bug or a design feature of the boardgame but we've always played that you can bid as much as you can afford. And the relevant passage from the 1861 rules from All-Aboard Games that I have mentions that the bids must be at least R100, and that the stock value is limited to between R50 and R135.

**Comment by ianwilson156** [comment]
In addition, you cannot overbid a bid of $270.
