### ISSUE TITLE
1867: Granby

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#2887]
You can lay a tile in Granby (M13) in Phase 2. This should not be allowed (as per the lock & 3 symbol).

**Comment by jenf** [comment]
It worked when I originally wrote it, I think it got broken in the ability rewrite :(
Fixing now.

**Comment by ianwilson156** [comment]
Great! We had an unusual game where a player started a minor in 
Sherbrooke in SR1, and I spotted when he tried to build Granby.

------ Original Message ------
