### ISSUE TITLE
1867: Privates should be purchasable between paying dividends and repaying loans

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#2888]
When a company operates after Phase 2, it should be able to buy in a private at any instant during its turn. But in the current implementation, it isn't given the opportunity to buy in a private before repaying a loan.

**Comment by jenf** [comment]
We'd probably have to move the blocking BuyCompany from after the the train buying step to before and run a migration.

I'd rather not have two blocking BuyCompany steps

**Comment by ianwilson156** [comment]
Sorry to be a pain but...
The rules say you can buy in a private at _any_ point in a company's operating turn.
It doesn't make any difference when you're laying track/placing tokens.
But it might after running trains. In principle, you could buy in a private with all its cash and be nationalised because it can't afford the loan interest. More usually, it pays interest and buys a private before paying off a loan. Or, of course, you could pay off the loan(s) and buy in the private with what's left. A bit complicated, I know - might involve a lot of clicking through a company's turn.

**Comment by jenf** [comment]
there's two forms, the anytime one, and the blocking one (which on most games is at the end)

having the blocking after Buy train isn't necessary if it's earlier since if it skips buy train it'll still have blocked.
