### ISSUE TITLE
1867: laying track with no assets

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#2889]
When a minor company comes to operate and it has no cash and two loans, it cannot lay even one piece of (free) track.

**Comment by jenf** [comment]
do you have a game with this in? if it's a hotseat can you paste the game data?

**Comment by ianwilson156** [comment]
Game ID is #20462, but I can't remember exactly when it happened, sorry.


------ Original Message ------

**Comment by jenf** [comment]
Found, game id is usually enough for us to work it out https://18xx.games/game/20462?action=176

**Comment by jenf** [comment]
Odd, buying power shouldn't be negative.
