### ISSUE TITLE
1867: multiple CN tokens

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#2891]
The implementation has multiple CN tokens in the same hex. This is not allowed. If a company is nationalised and the CN already has a token there e.g. in Toronto, the CN doesn't get the extra token.

**Comment by jenf** [comment]
do you have a game showing this?

**Comment by OedipussyRex** [comment]
https://18xx.games/game/20424

This issue seems to be a generalized form of the issue I posted for Toronto

**Comment by ianwilson156** [comment]
#20462 - in both Toronto and Hamilton

------ Original Message ------

**Comment by jenf** [comment]
Two different edge conditions, first is for when a tile upgrades and merges cities, the other is for the CN putting tokens when it already exists.

**Comment by ianwilson156** [comment]
No - a common misunderstanding of the rules. The rule is that a company 
may not have more than one token per hex (not per city). So merging 
cities with a tile upgrade is irrelevant.
The trickiest bit happens when two companies get nationalised with 
tokens in the same hex. In this case, they are absorbed in operating 
turn order, so the CN gets the token of the first company and not the 
second.


------ Original Message ------

**Comment by jenf** [comment]
Thanks, so the merging wouldn't apply just the nationalisation.

**Comment by ianwilson156** [comment]
Mmm, the rule applies to merging too. So, if two minors merge with tokens in the same hex (e.g. Montreal), the new president has to choose which token to keep.
This is the exception to the rule that means a major formed by merger starts with two tokens. 
The 'lost' token can still be placed in the normal manner.
