### ISSUE TITLE
1867: nationalised companies

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#2893]
When a minor company is nationalised, the owner gets his cash recompense and the CN gets the token correctly, but the minor doesn't disappear from the turn order and still gets a run (before disappearing).
When a major company is nationalised (president chooses), the owner doesn't get his cash, the company doesn't disappear, and the game crashes (looses sync) when it comes to operate.

**Comment by jenf** [comment]
please provide game data.

**Comment by ianwilson156** [comment]
#20462 again - in the middle of OR3.1 the CA bought the first 4-train, 
thus rusting all the 2's. Various companies were nationalised as a 
consequence, including the TN (for example) and their owners received 
their cash. But then some of them (including the TN) were asked to 
operate later in the round.


------ Original Message ------

**Comment by jenf** [comment]
Point of issue
https://18xx.games/game/20462?action=275
