### ISSUE TITLE
1867: buying shares on merge

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#2896]
When a minor(s) converts/merges, the other players should only be offered to buy one share but they are being offered shares more than once.

**Comment by jenf** [comment]
It was intended they should only be able to buy one. Please provide a sample game

**Comment by ianwilson156** [comment]
#20462: at the conversion of BBG to CNR in MR3.1, the other two players 
were offered to buy a share twice.


------ Original Message ------

**Comment by jenf** [comment]
Action:
http://localhost:9292/hotseat/hs_zarqamts_20462?action=291
(note that I've deployed a bunch of fixes which mean you game was deleted)

**Comment by ianwilson156** [comment]
Hi Jennifer,

Please let me know when you've done all the fixes, then I'll have a go 
in hot-seat mode...

Cheers,
Ian D


------ Original Message ------

**Comment by jenf** [comment]
All the closed bugs are deployed, the others will take a few more days
