### ISSUE TITLE
[18CO] Rule 6.1.1 (removing tokens of acquired company in hex where acquiring company is already present) not enforced

### ISSUE THREAD

**Issue by otdewiljes** [tobymao/18xx#2903]
In the rulebookof 18CO (dated 12-27; https://drive.google.com/drive/folders/0B3lRHMrbLMG_eEp4elBZZ0toYnM) it states in rule 6.1.1, regarding acquisition (i.e. when a company becomes 'president' of another): "Remove any owned Station Tokens in hexes containing the owning Corporation’s Station tokens." 
We had a case (https://18xx.games/game/20509) where the DSL acquired the DPAC and ended up with two tokens in separate sub-parts of Colorado (a thing, incidentally, which is legal in Toronto and Montreal in 1867):
![18CO_bug_1](https://user-images.githubusercontent.com/4226724/103322308-f5aabd00-4a3d-11eb-9b3c-96bf458bcd06.PNG)

This should not be possible; the acquired token should disappear. This propagated even when Colorado grew together (a thing which should not be legal in 1867 either)--by then the DSL had been acquired by the UP:
![18CO_bug_3](https://user-images.githubusercontent.com/4226724/103322363-1246f500-4a3e-11eb-9394-9e9fa6d74048.PNG)

(I do not know how to access the history to get the exact action. Sorry.)

**Comment by ryandriskel** [comment]
Thanks for the report!

**Comment by otdewiljes** [comment]
Thanks for doing the implementation!

**Comment by ryandriskel** [comment]
I've got the fix in review but want to warn you, when it is deployed it will cause this particular game to explode.

**Comment by otdewiljes** [comment]
That's fine, we were done with it.
Thanks for the quick fix!
