### ISSUE TITLE
[1867] Nationalization of Private Companies not Paying Out

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2905]
When Private Companies are nationalized with the sale/export of the first 6-Train, the owners of the Privates (player or RR) are not being paid the face value of the Privates.

**Comment by jenf** [comment]
I can see this in the old AAG rules but not the new rules @ianwilson156, was there a decision to change the rules?

**Comment by ianwilson156** [comment]
There _should_ be no rule differences. Unfortunately, this one has been missed (like the train upgrade).
I'll raise this with Josh to get it corrected.
