### ISSUE TITLE
Spreadsheet - sort corps by Market value

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#291]
To allow for quickly identifying corp OR turn order. Or possibly offer different sort option by clicking column headers.

**Comment by lbrande** [comment]
I really think this would reduce the usability of the spreadsheet view, it can be very confusing if companies move around.

**Comment by 8bg** [comment]
I find the current view frustrating after years of rr18xx use where the default sort is by operating order/market value. The header sort option I mentioned would accommodate different preferences.

**Comment by lbrande** [comment]
As long as it's an option it should be fine. As a Board18 player i would find it very frustrating if companies moved around.

**Comment by ptrinidad** [comment]
I'd also feel more comfortable if companies are sorted in operating order. However I understand other that prefer keeping a fixed order from the beginning of the game. Since this is an opinionated feature, I think that offering both options is the best choice.

**Comment by sparr** [comment]
"Obviously" the one true sort order for corporations is (alphabetical|par order|float order|stock value|operating order|...)

+1 for just making the table sortable by any column, like a spreadsheet.

**Comment by michaeljb** [comment]
> +1 for just making the table sortable by any column, like a spreadsheet.

My friend just echoed this request. His exact words:

> Would be cool if you could sort the spreadsheet by varying factors. High low values in different columns etc

**Comment by Tin-Whisker** [comment]
I highly encourage the idea of sorting by not just market value but operating order.  Having one place where  you can see corp, money, and trains makes it easier to predict what trains are going to be bought by whom.  

So if you are to allow sorting on a column please add a column for operating order.   Thanks.

**Comment by wheresvic** [comment]
I can try and tackle this one :)
