### ISSUE TITLE
18 MEX Retain Obsolete Train Cost for Nat'l RR

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#2910]
In the Info tab train costs are currently displayed only for trains that are available and those that may become available (upcoming trains), but not for trains that are no longer available for purchase.  In some (maybe all) games with national railroads, such as 18MEX, any used trains bought by the nat'l RR or bought from the nat'l RR must be bought at list (original) price or some fraction of list price.  When considering such a transaction it would be very helpful to be able to go to the info tab and see how much used trains originally cost.

I'm suggesting keeping the information for all trains and using some visual indication for trains no longer available from the bank instead of just not showing them.  Maybe add a section for trains no longer available from the bank.  Another idea is to keep the full Upcoming Trains table renamed to something like "Trains in the Bank", show "0" for sold out train types, and highlight the row or rows of types currently available for purchase from the bank.

**Comment by slapphappyjazz** [comment]
+1 we noticed this in our game today.

**Comment by perwestling** [comment]
Information about active trains, their face value, when they rust or becomes obsolete - this information should probably be visible for all titles.

**Active Trains
Type              Price                 Rusts on**
2                    100                    4
3                     180                   6

This could be put to the right of Upcoming Trains - when playing with a big screen there is a lot of space to the right, and on small screen you can scroll.

Putting it to the right would not disturb existing view.

**Comment by jenf** [comment]
fixed
