### ISSUE TITLE
Surface who has sold what stock in a given SR

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#292]
While this information is in the log, it can be tough to scroll up and make sense of things, and there's no reason we can't surface this.

That said, I'm not sure what the right UX here is

**Comment by dfannius** [comment]
Same as #265. I've been thinking about this but I'm happy to give @lbrande first crack at it.

**Comment by lbrande** [comment]
Now I've set up the development environment and started to work on this. Could someone assign me?

**Comment by dfannius** [comment]
Note that there's a redesign of the player card incoming with #307, so if you want to display this information there, you should probably wait for that to get merged in.

**Comment by lbrande** [comment]
You can unassign me from this issue now. @dfannius will fix the rest of this issue.

**Comment by dfannius** [comment]
I'll unassign you when the PR is merged.

**Comment by lbrande** [comment]
Unassigned my self as it now works in spreadsheet view.

**Comment by dfannius** [comment]
Putting this info on the corp card is implemented with c9451e1 (share amounts are written in red). I think that's sufficient.
