### ISSUE TITLE
[1860] Not able to buy Fishborne Ferry Company

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#2920]
https://18xx.games/game/20252?action=252

It really helps us having a sample game to reproduce the issue.

Fishborne Ferry Company is for sale (200£), I have 201£, but when I choose buy I get the error message: >>undefined method `name' for nil<<

**Comment by Maxwell-Frank** [comment]
You can't buy the Fishburne Ferry until after a 6+3 train has been purchased.  That said, the error message could be clarified to remind players of that.

**Comment by roseundy** [comment]
An unrelated change to the 18xx code base caused the Ferry to be displayed when it shouldn't have been.
