### ISSUE TITLE
[1846] GameError: Route must contain token

### ISSUE THREAD

**Issue by rrokkam** [tobymao/18xx#2923]
This occurred on a hotseat game: https://18xx.games/hotseat/hs_uzaeytth_18756

Following that first link to the hotseat game immediately brings up the error screen. Text of the error is as follows: 
"We're sorry this game cannot be continued due to GameError: Route must contain token"

I uploaded a gist as requested: https://gist.github.com/rrokkam/9d6e8cb248b55dad2ec144cc78aae55f

**Comment by michaeljb** [comment]
Hmm what routes were you trying to run? The broken action in the error output is this:

```
Broken action: { "type": "run_routes", "entity": "B&O", "entity_type": "corporation", "id": 617, "routes": [ { "train": "5-2", "connections": [ [ "I5", "I3", "I1" ], [ "H12", "H10", "I9", "I7", "I5" ], [ "G13", "H12" ], [ "G19", "F18", "F16", "F14", "G13" ], [ "G21", "G19" ] ] } ] }
```

` [ "G19", "F18", "F16", "F14", "G13" ]` this part looks like it's a route from Wheeling to Dayton via F18, but there's no tile on F18, so I'm not sure how that could have happened.

If you press `<` in the little history controls section you can back up an action, clone the game there (under Tools) and hopefully carry on.

**Comment by rrokkam** [comment]
This happened after I undid laying the token and redid the runs. I'm fine with closing this, since the gist doesn't seem to have been that helpful -- I don't have a repro on a fresh game and I don't intend to spend the time coming up with one.
