### ISSUE TITLE
[1860]P - Privates re-appearing after all being exchanged in Stockround ten

### ISSUE THREAD

**Issue by PaulKT** [tobymao/18xx#2928]
https://18xx.games/game/20624?action=574 just after this all 4 exchanged privates reappeared to be purchased again although the buy was in brackets? In any case upon purchasing it would produce an error (I think it was null pointer, it wasn't on my screen sorry).

We also believe the way it was calculating the insolvent trains may be incorrect or it may be a rules error by us again. Halts/Towns are not meant to count but they were counting as stops just to let you know. But the above issue I think is definitely a bug.

**Comment by tobymao** [comment]
@michaeljb is this due to 22f1333ed

**Comment by roseundy** [comment]
No, this is due to d025f57c5

**Comment by roseundy** [comment]
Also, why do you say that "Halts/Towns are not meant to count" on loaner trains? The rules are pretty clear that they count as stops. Even when halts are ignored (at times during Nationalization), towns still are counted.
