### ISSUE TITLE
Make it clearer when someone is purchasing trains from another player

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#293]
During Wheel Tapping's playthrough one of the players bought a train from another without the other player realizing causing confusion.

https://youtu.be/AiPhNX5a-bA?t=1710

If it's from another player (or maybe generally another company) there should be a confirmation step.

**Comment by jenf** [comment]
Should probably occur when buying a private of another player

**Comment by SmithInMN** [comment]
> During Wheel Tapping's playthrough one of the players bought a train from another without the other player realizing causing confusion.
> 
> https://youtu.be/AiPhNX5a-bA?t=1710
> 
> If it's from another player (or maybe generally another company) there should be a confirmation step.

We just had that happen in our game as well. New player, didn’t mean to do it, but it has caused a bit of a problem.

**Comment by benjaminxscott** [comment]
Suggest hiding the privates/trains owned by other players during the respective steps, and having a button to "view other players privates/trains"
(vs having a click-thru box, IMO this interface's UI is cleaner by virtue of not having click-thrus anywhere in its flow already)

**Comment by tobymao** [comment]
i like this suggestion the best of hiding the trains by default

**Comment by jenf** [comment]
Yeah and avoids another migration
