### ISSUE TITLE
1846: LSL ability consumed by yellow tile lay in Cleveland

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#2948]
Steps to reproduce:
1. Buy in LSL
2. Click on LSL ability
3. Select Cleveland
4. Click on LSL ability
5. Lay yellow in Cleveland

Log:
NYC buys Lake Shore Line from Player 2 for $40
NYC (LSL) spends $20 and lays tile #291 with rotation 3 on E17

**Comment by crericha** [comment]
JSON to reproduce:

[LSL.json.txt](https://github.com/tobymao/18xx/files/5758681/LSL.json.txt)

**Comment by benjaminxscott** [comment]
![image](https://user-images.githubusercontent.com/1711810/103467597-836bfe00-4d05-11eb-9c25-126a21e1aa12.png)

Unable to repro from the step in the game json (clicking the private ability and then cleveland doesn't give any options to build a yellow tile, in the screenshot)

If I hit 'redo' from that game json, it does repro the behavior you noticed, so I'm not entirely sure how it got into that state

**Comment by crericha** [comment]
You need to select lsl, select cleveland hex, unselect lsl, and then you
will see tile options.

**Comment by benjaminxscott** [comment]
Ah yes I can repro with those steps, I was missing the 'deselect lsl power' step

Presumably this is because the hex is still 'selected' and for some reason the power is still selected, so the `tile_build` power gets consumed

**Comment by crericha** [comment]
It's a bit odder still because a yellow tile lay is not valid for lsl and
the company is also charged $20. I think it is using the regular tile lay
step, but somehow pulling in the lsl too.
