### ISSUE TITLE
[1860] GameError game id (19190)

### ISSUE THREAD

**Issue by mrwrenlyh** [tobymao/18xx#2949]
Game could not be continued due to GameError: Step Buy Trains cannot process {"type"=>"pass", "entity"=>"BHI&R", "entity_type"=>"corporation", "id"=>801}

Last valid action was (800).

https://18xx.games/game/19190

**Comment by roseundy** [comment]
I'm sorry, but since this was on a pinned game I can't easily debug the problem. In addition, there is no way to release a fix for pinned games.

**Comment by tobymao** [comment]
@roseundy close issues about pinned games
