### ISSUE TITLE
Improve player name display

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#295]
I registered today, and then joined my first game. 

Here are some minor issues I discovered:
- You can use space in signums (which is fine)
- You cannot change your signum
- When you join a game, your signum is shown in the same line as the other players, like AAA BBB CCC. But if a player uses spaces if will be AAA BB BB CCC, which is very hard to read. Suggest adding comma in that presentatin
- The names shown, and description just cuts words in half when wrapped over several lines. Try to keep the words together.
- The dates are shown as 2020-05-4 and so on. Make the date show as 2020-05-04 instead. That is, two digits for both month and day of month.

**Comment by jenf** [comment]
Dates are fixed

**Comment by Djeefther** [comment]
I suggest some formation to emphasis that this is a user name in the log the user name, like bold, italic or some color. The same could be used to Corporation and Company names or acronyms.
