### ISSUE TITLE
[1867] Wrong player's turn after an auction is won

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2950]
Often, when an auction for a Minor Company is won, the next player given a turn is not the next person "clock-wise" from the auction winner, but either the next person clock-wise from the player who made the opening bid in the auction or the next person clock-wise from the last player to pass in the auction.

I haven't noticed this behavior in a Private Company auction. Doesn't mean it hasn't happened.

**Comment by jenf** [comment]
Confirmed
