### ISSUE TITLE
[1867] undefined method 'loan' for <engine::Corporation:QLS>

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2951]
Hot-seating a game of 1867. A Minor Company went to purchase the first 4-train. The above error was given and the purchase did not happen, but play could continue without purchasing the train.

QLS was another minor with no train, one loan, and enough money in the company to cover the loan to avoid the double drop in stock price when nationalizing.

I do not have the json for the game as it later froze and would not reload.

**Comment by jenf** [comment]
dup of #2951
