### ISSUE TITLE
Minor Companies receiving starting stock value exceeding $135

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2952]
As the title reads, winning bids of $300 or more are resulting in a Minor Company's initial stock value equal to half the bid, rounded down to the nearest available stock value, including a winning bid of $440 giving a stock value of $220, far exceeding the maximum value for minors of $165.

**Comment by jenf** [comment]
dup of #2953

**Comment by ianwilson156** [comment]
Maximum stock price of a minor starting is $135, not £165.
