### ISSUE TITLE
[1867] Minor Companies capping at stock value of $200

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2953]
The maximum stock value a Minor Company can achieve is $165. The system is setting the cap at $200, which is the maximum stock value a Major can start at when two (or more) Minors merge.

**Comment by jenf** [comment]
Please provide a game id where I can easily reproduce this

**Comment by Maxwell-Frank** [comment]
Here's a hotseat game where I started a company with $420 and it parred at $200 instead of $135. 

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 7
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9,
      "company": "MB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "company": "QB",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16,
      "corporation": "PM",
      "price": 420
    },
    {
      "type": "place_token",
      "entity": "PM",
      "entity_type": "corporation",
      "id": 17,
      "city": "F16-0-1",
      "slot": 0
    }
  ],
  "id": "hs_vmkgabjv_1609523436",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-01",
  "loaded": true,
  "result": {},
  "turn": 1,
  "round": "Stock Round",
  "acting": [
    "Player 3"
  ],
  "updated_at": 1609523458
}
