### ISSUE TITLE
[1867] Dashed line in the Stock Market to match that used on the physical board

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2954]
That is, assuming that the GTR edition kept it. The AAG version of the stock market has a dashed line between $165 and $180 to mark the maximum value a Minor Company can achieve. Probably wouldn't hurt to add it to this implementation.

**Comment by jenf** [comment]
There's a solid purple line already implemented for this

**Comment by OedipussyRex** [comment]
There is a solid purple at 200 for the max starting value of a Major, not a
dashed line at 165 for the max value for a Minor.

**Comment by jenf** [comment]
that's a bug...
