### ISSUE TITLE
[1846] broken F16 blocked by Ohio and Indiana

### ISSUE THREAD

**Issue by deaconbluz** [tobymao/18xx#2964]
https://18xx.games/game/20804?action=89

{
  "id": 20804,
  "description": "3 J Gaming",
  "user": {
    "id": 5456,
    "name": "e1v15"
  },
  "players": [
    {
      "id": 5469,
      "name": "jtlowell"
    },
    {
      "id": 5456,
      "name": "e1v15"
    },
    {
      "id": 5470,
      "name": "jrjacob"
    },
    {
      "id": 5467,
      "name": "deaconbluz"
    }
  ],
  "max_players": 5,
  "title": "1846",
  "settings": {
    "seed": 1560244778,
    "unlisted": true,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    5467
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 80,
      "entity": 5467,
      "company": "MAIL",
      "entity_type": "player",
      "user": 5467,
      "created_at": 1609515251
    },
    {
      "id": 2,
      "type": "bid",
      "price": 60,
      "entity": 5470,
      "company": "MS",
      "entity_type": "player",
      "user": 5470,
      "created_at": 1609515361
    },
    {
      "id": 3,
      "type": "bid",
      "price": 40,
      "entity": 5456,
      "company": "BIG4",
      "entity_type": "player",
      "user": 5456,
      "created_at": 1609515586
    },
    {
      "id": 4,
      "type": "bid",
      "price": 40,
      "entity": 5469,
      "company": "SC",
      "entity_type": "player",
      "user": 5469,
      "created_at": 1609516190
    },
    {
      "id": 5,
      "type": "bid",
      "price": 40,
      "entity": 5467,
      "company": "O&I",
      "entity_type": "player",
      "user": 5467,
      "created_at": 1609516475
    },
    {
      "id": 6,
      "type": "bid",
      "price": 60,
      "entity": 5470,
      "company": "MPC",
      "entity_type": "player",
      "user": 5470,
      "created_at": 1609518517
    },
    {
      "id": 7,
      "type": "bid",
      "price": 60,
      "entity": 5456,
      "company": "C&WI",
      "entity_type": "player",
      "user": 5456,
      "created_at": 1609518947
    },
    {
      "id": 8,
      "type": "bid",
      "price": 0,
      "entity": 5469,
      "company": "Pass (1)",
      "entity_type": "player",
      "user": 5469,
      "created_at": 1609519103
    },
    {
      "id": 9,
      "type": "bid",
      "price": 0,
      "entity": 5467,
      "company": "Pass (4)",
      "entity_type": "player",
      "user": 5467,
      "created_at": 1609519906
    },
    {
      "id": 10,
      "type": "bid",
      "price": 0,
      "entity": 5470,
      "company": "Pass (2)",
      "entity_type": "player",
      "user": 5470,
      "created_at": 1609520145
    },
    {
      "id": 11,
      "type": "bid",
      "price": 0,
      "entity": 5456,
      "company": "Pass (3)",
      "entity_type": "player",
      "user": 5456,
      "created_at": 1609520219
    },
    {
      "id": 12,
      "type": "pass",
      "entity": 5469,
      "entity_type": "player",
      "user": 5469,
      "created_at": 1609520244
    },
    {
      "id": 13,
      "type": "bid",
      "price": 40,
      "entity": 5467,
      "company": "MC",
      "entity_type": "player",
      "user": 5467,
      "created_at": 1609520314
    },
    {
      "id": 14,
      "type": "par",
      "entity": 5469,
      "corporation": "IC",
      "entity_type": "player",
      "share_price": "150,0,14",
      "user": 5469,
      "created_at": 1609520404
    },
    {
      "id": 15,
      "type": "par",
      "entity": 5456,
      "corporation": "PRR",
      "entity_type": "player",
      "share_price": "112,0,11",
      "user": 5456,
      "created_at": 1609520738
    },
    {
      "id": 16,
      "type": "undo",
      "entity": 5470,
      "entity_type": "player",
      "user": 5456,
      "created_at": 1609520762
    },
    {
      "id": 17,
      "type": "par",
      "entity": 5456,
      "corporation": "PRR",
      "entity_type": "player",
      "share_price": "112,0,11",
      "user": 5456,
      "created_at": 1609520789
    },
    {
      "id": 18,
      "type": "par",
      "entity": 5470,
      "corporation": "GT",
      "entity_type": "player",
      "share_price": "100,0,10",
      "user": 5470,
      "created_at": 1609520870
    },
    {
      "id": 19,
      "type": "par",
      "entity": 5467,
      "corporation": "NYC",
      "entity_type": "player",
      "share_price": "124,0,12",
      "user": 5467,
      "created_at": 1609520942
    },
    {
      "id": 20,
      "type": "assign",
      "entity": "SC",
      "target": "I1",
      "entity_type": "company",
      "target_type": "hex",
      "user": 5469,
      "created_at": 1609521071
    },
    {
      "id": 21,
      "type": "assign",
      "entity": "SC",
      "target": "IC",
      "entity_type": "company",
      "target_type": "corporation",
      "user": 5469,
      "created_at": 1609521078
    },
    {
      "id": 22,
      "hex": "B16",
      "tile": "6-0",
      "type": "lay_tile",
      "entity": "MS",
      "rotation": 4,
      "entity_type": "minor",
      "user": 5470,
      "created_at": 1609521265
    },
    {
      "id": 23,
      "type": "run_routes",
      "entity": "MS",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ],
      "entity_type": "minor",
      "user": 5470,
      "created_at": 1609521277
    },
    {
      "id": 24,
      "hex": "G9",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 2,
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609521322
    },
    {
      "id": 25,
      "hex": "F8",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 2,
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609521329
    },
    {
      "id": 26,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521341
    },
    {
      "id": 27,
      "type": "undo",
      "entity": "BIG4",
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609521374
    },
    {
      "id": 28,
      "hex": "G9",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 1,
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609521423
    },
    {
      "id": 29,
      "hex": "G7",
      "tile": "5-1",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 4,
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609521561
    },
    {
      "id": 30,
      "type": "run_routes",
      "entity": "BIG4",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ],
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609521568
    },
    {
      "id": 31,
      "hex": "C13",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 4,
      "entity_type": "corporation",
      "user": 5470,
      "created_at": 1609521719
    },
    {
      "id": 32,
      "hex": "D14",
      "tile": "5-2",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 1,
      "entity_type": "corporation",
      "user": 5470,
      "created_at": 1609521726
    },
    {
      "id": 33,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "user": 5470,
      "created_at": 1609521750
    },
    {
      "id": 34,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "GT",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5470,
      "created_at": 1609521754
    },
    {
      "id": 35,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "user": 5470,
      "created_at": 1609521801
    },
    {
      "id": 36,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "user": 5470,
      "created_at": 1609521821
    },
    {
      "id": 37,
      "city": "E11-1-0",
      "slot": 0,
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521839
    },
    {
      "id": 38,
      "hex": "E11",
      "tile": "57-0",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521872
    },
    {
      "id": 39,
      "hex": "D10",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521894
    },
    {
      "id": 40,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "PRR",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521898
    },
    {
      "id": 41,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521920
    },
    {
      "id": 42,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521926
    },
    {
      "id": 43,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521929
    },
    {
      "id": 44,
      "hex": "E11",
      "tile": "6-1",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521935
    },
    {
      "id": 45,
      "hex": "D10",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521944
    },
    {
      "id": 46,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "PRR",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521946
    },
    {
      "id": 47,
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521955
    },
    {
      "id": 48,
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609521962
    },
    {
      "id": 49,
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522040
    },
    {
      "id": 50,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522042
    },
    {
      "id": 51,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522044
    },
    {
      "id": 52,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522045
    },
    {
      "id": 53,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522056
    },
    {
      "id": 54,
      "hex": "E19",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522070
    },
    {
      "id": 55,
      "hex": "E17",
      "tile": "293-0",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 1,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522089
    },
    {
      "id": 56,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "PRR",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522091
    },
    {
      "id": 57,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522101
    },
    {
      "id": 58,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522102
    },
    {
      "id": 59,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522104
    },
    {
      "id": 60,
      "hex": "E11",
      "tile": "6-1",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522111
    },
    {
      "id": 61,
      "hex": "D10",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "PRR",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522115
    },
    {
      "id": 62,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "PRR",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522119
    },
    {
      "id": 63,
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522124
    },
    {
      "id": 64,
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "user": 5456,
      "created_at": 1609522144
    },
    {
      "id": 65,
      "hex": "D18",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "NYC",
      "rotation": 4,
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609522174
    },
    {
      "id": 66,
      "hex": "E17",
      "tile": "293-0",
      "type": "lay_tile",
      "entity": "NYC",
      "rotation": 0,
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609522180
    },
    {
      "id": 67,
      "city": "293-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "NYC",
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609522202
    },
    {
      "id": 68,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "NYC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609522207
    },
    {
      "id": 69,
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609522232
    },
    {
      "id": 70,
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609522236
    },
    {
      "id": 71,
      "hex": "J4",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 0,
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523130
    },
    {
      "id": 72,
      "hex": "I3",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 1,
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523148
    },
    {
      "id": 73,
      "city": "I5-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523149
    },
    {
      "id": 74,
      "type": "buy_train",
      "price": 80,
      "train": "2-5",
      "entity": "IC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523162
    },
    {
      "id": 75,
      "type": "buy_train",
      "price": 80,
      "train": "2-6",
      "entity": "IC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523165
    },
    {
      "id": 76,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523188
    },
    {
      "id": 77,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609523195
    },
    {
      "id": 78,
      "type": "pass",
      "entity": "SC",
      "entity_type": "company",
      "user": 5469,
      "created_at": 1609523208
    },
    {
      "id": 79,
      "hex": "D12",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "MS",
      "rotation": 2,
      "entity_type": "minor",
      "user": 5470,
      "created_at": 1609524416
    },
    {
      "id": 80,
      "type": "run_routes",
      "entity": "MS",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ],
      "entity_type": "minor",
      "user": 5470,
      "created_at": 1609524449
    },
    {
      "id": 81,
      "hex": "F8",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 2,
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609526381
    },
    {
      "id": 82,
      "type": "run_routes",
      "entity": "BIG4",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ],
      "entity_type": "minor",
      "user": 5456,
      "created_at": 1609526388
    },
    {
      "id": 83,
      "hex": "H6",
      "tile": "7-1",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 0,
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609526560
    },
    {
      "id": 84,
      "hex": "H4",
      "tile": "9-3",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 1,
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609526567
    },
    {
      "id": 85,
      "type": "run_routes",
      "entity": "IC",
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "K3",
              "J4",
              "I5"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "I1",
              "I3",
              "I5"
            ]
          ]
        }
      ],
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609526591
    },
    {
      "id": 86,
      "kind": "payout",
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609526604
    },
    {
      "id": 87,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609526612
    },
    {
      "id": 88,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "user": 5469,
      "created_at": 1609526651
    },
    {
      "id": 89,
      "hex": "F16",
      "tile": "8-3",
      "type": "lay_tile",
      "entity": "NYC",
      "rotation": 1,
      "entity_type": "corporation",
      "user": 5467,
      "created_at": 1609526790
    }
  ],
  "loaded": true,
  "created_at": 1609477925,
  "updated_at": 1609526790
}

**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by michaeljb** [comment]
@deaconbluz I've manually deleted the broken action, your game should be good to continue now

**Comment by deaconbluz** [comment]
thanks! but it is still saying broken...

**Comment by deaconbluz** [comment]
sry. got it back now. Thanks!
