### ISSUE TITLE
1817 Friendly sales shows wrong corporation for loans.

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#2965]
When you put a company up for sale, the final screen is wrong.  In this case, the Housatonic was put up for sale and bought by the WC.  WC is offered the chance to take loans at the end of the process but the display gives the impression that the Housatonic is doing so even though it no longer exists at this stage fo the process.  It should be showing the WC corporate details

![image](https://user-images.githubusercontent.com/11814681/103444812-69c6aa00-4c64-11eb-98e7-5ecba8f5f9fd.png)

**Comment by jenf** [comment]
Please could you provide a game id and approximately when it occured

**Comment by rclyne** [comment]
It was game 20827 Acquisition Round 3.2. The same thing happened on previous friendly sales although I cannot remember exactly when. 

What I think is happening is that thesis-lay logic is saying that it is the H being sold so it is displaying the corporate data for it after the company ceases to exist.  The take loans at the end of the acquisition step refers to the purchasing company so the display is confusing.  As the take loans at this stage is raely used, I suspect a lot of people are just clicking straight through.

**Comment by jenf** [comment]
https://18xx.games/game/20827?action=835
