### ISSUE TITLE
18 CO bug

### ISSUE THREAD

**Issue by Foxrik** [tobymao/18xx#2966]
Our game died, with this message:

We're sorry this game cannot be continued due to GameError: Route must contain token
Broken action: { "id": 268, "type": "run_routes", "entity": "KPAC", "routes": [ { "train": "2-0", "connections": [ [ "D24", "C25", "B24", "B26" ], [ "E27", "F26", "E25", "D24" ] ] }, { "train": "2-5", "connections": [ [ "F24", "G23", "G21", "G19", "F18", "E17", "E15" ], [ "G27", "F26", "F24" ] ] } ], "_client_id": "35509932c1e049e7a1cb97bf29a1c7b4", "entity_type": "corporation", "user": 2275, "created_at": 1609527889 }
Please raise a bug report and include this link (https://18xx.games/game/20859?action=268) and the following JSON data

**Comment by michaeljb** [comment]
@Foxrik I've manually deleted the broken action, you should be good to continue
