### ISSUE TITLE
https://18xx.games/game/18844?action=590 18GA game is broken

### ISSUE THREAD

**Issue by cameroon77** [tobymao/18xx#2973]
**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by tobymao** [comment]
looks like this is fixed

**Comment by cameroon77** [comment]
Game is still showing broken for me.

**Comment by cameroon77** [comment]
Player Bought 6 train not having enough money and it broke the game

**Comment by tobymao** [comment]
the game is over and it looks fine to me?

**Comment by cameroon77** [comment]
The game wasn’t over. Player tried to buy a train that they did not have enough money for and then the game sent a broken message. My screen is still showing broken message. Did the host end the game? If so why is it still showing on my screen as a broken active game

**Comment by tobymao** [comment]
Probably cached on your browser. Do a hard restart
