### ISSUE TITLE
Color selection boxes on profile page are black on iOS

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#2975]
On the profile page, all of the color selection boxes are black instead of the corresponding UI color.

Observed on:
iPad (5th gen) iOS 12.4.1
iPhone 8 iOS 14.2

![99538F2B-1DA2-402A-BFEF-A1810745536A](https://user-images.githubusercontent.com/73244775/103447693-363a4e80-4c69-11eb-8f17-e9095564d80d.png)

**Comment by yzemaze** [comment]
Yep, known bug. When I implemtend this feature last year I couldn’t for the life of me figure out why this doesn’t work with Safari (or other browsers on iOS) on the live site, but works fine when it’s a [static site](https://yzemaze.de/temp/color_inputs.html).
I’ll investigate again. If someone has any pointers please come forward :)
