### ISSUE TITLE
[1867] undefined method `buying_power' for <Engine::Corporation: CV>

### ISSUE THREAD

**Issue by kodemaniak** [tobymao/18xx#2984]
Multiplayer game 20217, https://18xx.games/game/20217, OR4

On first turn of CV I was unable to finish "Track Laying" after first tile lay. Now the game does not load and fails with the following error in the Console:

```JavaScript
{ name: "buying_power", message: "undefined method `buying_power' for <Engine::Corporation: CV>", args: [], stack: "" }
```

**Comment by jenf** [comment]
Something relating to EMR
