### ISSUE TITLE
[18CO] improve green Denver tile

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#2986]
The Denver tile is fine in yellow and brown, but moving the three station part in green to add a small spoke to the southeast would help readability. It is not immediately obvious that you can build out of there.

![CB4F223B-5C17-4FC4-A4AC-A52E4F605308](https://user-images.githubusercontent.com/73144084/103459783-79370900-4cdf-11eb-9b27-630f00db553c.png)

**Comment by benjaminxscott** [comment]
probably could roll into https://github.com/tobymao/18xx/issues/2814

**Comment by ryandriskel** [comment]
Yeah, the spoke is actually there, we're just having some trouble with the volume of information on the tile.
