### ISSUE TITLE
[18Mex] Buying of closed private during SR.

### ISSUE THREAD

**Issue by CaptainObi** [tobymao/18xx#2989]
https://18xx.games/game/19660?action=173

OR1.1 FCP buys in the KCMO private and lays the CC tile, KCMO closes.  (Early buy variant). 

SR3, Billy is offered the chance to buy KCMO from the bank at face value. 

![image](https://user-images.githubusercontent.com/69726608/103463754-a529ad00-4d26-11eb-9c07-1609f28dbc91.png)

Playing with all the variants enabled.

**Comment by perwestling** [comment]
Should be fixed due to #3001
