### ISSUE TITLE
Mitsubishi Ferry unable to lay special port tile

### ISSUE THREAD

**Issue by Darkvorrt** [tobymao/18xx#30]
Bought the Mitsubishi Ferry in 1889, and I have attempted to lay the tile.  System does not seem to allow for that.

**Comment by tobymao** [comment]
did you click on the company? what's the game id?

**Comment by Darkvorrt** [comment]
Game ID 29

How do you click on the private companies?  I see it listed under my name (Vorrt) as a Private I own, but it does not appear interactive

**Comment by tobymao** [comment]
this is fixed, i've added a new private company tab

**Comment by lbleicher** [comment]
It would also be nice to have the hexes where the special tile can be laid be marked on the map

**Comment by tobymao** [comment]
> It would also be nice to have the hexes where the special tile can be laid be marked on the map

this should work. if you click on the private and then the map. let me know if it doesn’t for you.
