### ISSUE TITLE
[1867] Game Crashing when winning the auction of the final private

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3004]
Hotseat. When auction of the St. Clair Tunnel private is complete the game crashes. When leaving and trying to re-enter, receive a "not found" error. Following is a game-state just prior to the final pass for the auction.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "company": "MB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "company": "QB",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14
    }
  ],
  "id": "hs_pwnqwgxq_1609643498",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-02",
  "loaded": true,
  "result": {},
  "turn": 1,
  "round": "Auction Round",
  "acting": [
    "Player 1"
  ],
  "updated_at": 1609643520
}

**Comment by jenf** [comment]
a {name: "type", message: "undefined method `type' for nil", args: Array(0), stack: "type: undefined method `type' for nil↵    at a.$me….$map (https://18xx.games/assets/main.js:1:17338)"}

**Comment by tobymao** [comment]
656c9879d5d
