### ISSUE TITLE
1817 short squeeze variant is wrong

### ISSUE THREAD

**Issue by tysen** [tobymao/18xx#3012]
Corporation stock values should move right a second time at the end of a stock round only if player ownership of that corporation exceeds 100%, not if it equals 100%.

**Comment by jenf** [comment]
Please provide a game id where this is the case

**Comment by tysen** [comment]
https://github.com/tobymao/18xx/blob/master/lib/engine/round/g_1817/stock.rb#L27-L30

```
def sold_out_stock_movement(corp)
  @game.stock_market.move_up(corp)
  @game.stock_market.move_up(corp) if @game.option_short_squeeze?          <-------------------- this is wrong
end
```

**Comment by jenf** [comment]
Yes, please provide a game for validation.

**Comment by tysen** [comment]
I don't know if it's happened yet. The logic here doesn't correspond to the game's manual. You don't need a game to validate this.
