### ISSUE TITLE
Don't say stock will move right/left if it's at the end/start of the market

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#3013]
A company will never exceed $600 in value; do not say a company at $600 can move right
https://18xx.games/game/18114?action=1420

**Comment by curlett** [comment]
Game was 17NA, but I am pretty sure it applies to all 3 17 titles.

**Comment by jenf** [comment]
It's in all 18xx titles

**Comment by bentziaxl** [comment]
no longer an issue. Log doesn't say moves right from 600

**Comment by dfannius** [comment]
It's not an issue with the log, but with the UI.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/1295244/180663553-09590320-5bc9-4b11-9667-ec6cf33602bd.png">
