### ISSUE TITLE
18Mex: Closed privates showing as available for purchase in Stock Rounds

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#3017]
This was a multiplayer game we played today.  I  attach two screenshots that show the issue.
[
![18Mex issue 1](https://user-images.githubusercontent.com/36824573/103488962-b4812700-4e08-11eb-8b12-6ae5b01e3a97.png)
![18Mex issue 2](https://user-images.githubusercontent.com/36824573/103488977-c82c8d80-4e08-11eb-9937-3a0cdb5a82b2.png)](url)

In the first screenshot, the Copper Canyon private has been used during the first OR and is now being displayed as available for purchase in the second SR.   In the second screenshot, the minor companies A-C have been closed and their certificates are displayed as available to purchase.

The game is here: https://18xx.games/game/21072?action=59 but the issue isn't appearing in the replay.  (I didn't save the link when the issue occurred; we just ignored it and I'm submitting the bug report after the game ended).

If it's relevant, we were playing with the optional rule that allowed the Copper Canyon private to be bought in early (but non of the other optional rules).

**Comment by tobymao** [comment]
was fixed
