### ISSUE TITLE
Spreadsheet: add a row in the history for the final OR

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#3018]
In the spreadsheet tab, the history table - i.e. the rows at the bottom that show player values or deltas at the end of each SR and OR for the whole game - doesn't include the final OR when the game ends.  This means players can't see the deltas for the final OR when viewing the history as deltas.  Of course, you can work it out by hand but that defeats the point of having a delta view in the first place.

**Comment by jenf** [comment]
dup of #2753
