### ISSUE TITLE
UI: Add a close symbol (e.g. "X") to the warning banners

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#3020]
IMO the warning banner would be friendlier and more intutive if it included a close symbol - most likely an "X", or the word "OK", or just "click to close".  I've had to tell several people that they can make the banner go away by clicking on it, and I didn't realise this myself the first time I used the site, so I have a fair bit of anecdotal evidence that the current behaviour is not obvious.

**Comment by tobymao** [comment]
dup 

close in favor for #247
