### ISSUE TITLE
UI: Train purchase shows player must contribute negative cash.

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#3021]
When a corporation is in the train buying stage and the game tab shows the available trains, it includes the amount that the player must contribute out of hand to buy the train.  It displays this paragraph even if the amount is negative, i.e. when the corporation has enough money to buy the available train.  
See the attached screenshot, in the text below the list of available trains.
![18Mex issue 3](https://user-images.githubusercontent.com/36824573/103489392-29099500-4e0c-11eb-9f4f-b97aed163d7c.png)
I assume this is generic bug and not specific to 18Mex or our particular game.  For reference, we saw it here: https://18xx.games/game/21072?action=44

**Comment by ChrisTheCat** [comment]
The same thing happened in another 18MEX game.

https://18xx.games/game/21143?action=270

**Comment by ChrisTheCat** [comment]
p.s. action 44 in the original report is clearly wrong, it's much later in that game.

**Comment by slapphappyjazz** [comment]
Action 44 is the first time this text appears in the game, when the first company to act buys its first train.  The screenshot is indeed from much later in the game, when the other players asked me to report the bug: https://18xx.games/game/21072?action=244
