### ISSUE TITLE
1817: Text when acquiring tokens.

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#3024]
In 1817 game 17117 J bought NYSW,  The text displayed in the log was as follows:
`J acquires NYSW receiving and tokens (4: hexes F19,C26)`
There is no text between "receiving" and "and" (presumably because NYSW had no trains and no privates). Also, although the NYSW owned 4 tokens, J could only acquire 3, so should there have been a note about discarding one?

Also, I was confused because the message said 4 tokens but only listed 2 hexes - this was correct because the other two were on the charter but the message could be clearer, e.g. "and 4 tokens (hexes F19, C26; 2 on the charter)".  

The game and action in question is https://18xx.games/game/17117?action=1395   

I previously reported this in my comment to issue #2604 but I neglected to raise a separate issue when requested.  I apologise for not creating this issue before now.

**Comment by jenf** [comment]
Since the old game was deleted, https://18xx.games/game/19350?action=924 works
