### ISSUE TITLE
Crash when buying D train

### ISSUE THREAD

**Issue by fabianpk** [tobymao/18xx#3025]
**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

Here's the link to the game:
https://18xx.games/game/21140?action=415

I didn't have enough money to buy the D train but it didn't let me sell shares or anything to do it. 
It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by jenf** [comment]
Could you refresh, cloning as a hotseat I can see that you can't afford to sell all the shares.

**Comment by fabianpk** [comment]
Yeah that solves it, it was just that clicking on Buy gave me a screen that said the game was broken and couldn’t accept more inputs. Maybe it’s not a bug?

**Comment by jenf** [comment]
You might've hit an issue earlier in the day that was fixed
