### ISSUE TITLE
Tiles tab: fade tiles that can no longer be played

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#3026]
The tiles tab has a very helpful UI that fades out tiles and flags them as unavailable when all tiles of that type are in play.

It would be nice if this were also done for location-specific tiles that have been upgraded and that can no longer be played.  For example, in 18MEX, the yellow tiles for Tampico, Veracruz and Mazatlan cannot be played anywhere else, so when they are upgraded they are effectively out of the game.  If the display showed them faded out, it would help users (or me, at least) focus on the tiles which are still available.

The principle applies to other titles as well as 18Mex.  Presumably this would require an additional attribute in the tile descriptor to indicate that when upgraded it can't be re-used, and some code that flags the tile as used when it is upgraded.  The attribute would only be needed for the relevant tiles; for all other tiles the absence of the attribute would be taken as meaning the tile can be reused. If the code were added for one game, the feature could then be rolled out gradually to other titles by updating the tile descriptors when convenient to do so.

18Mex has an additional twist in that there are two options in brown for Mexico City, so when one of them is played, the other should be faded as unavailable.  If there is a general provision for marking a tile as out of play, perhaps the code in 18Mex for handling the Mexico City tile could also mark the unchosen choice as out of play.

![18Mex issue 4](https://user-images.githubusercontent.com/36824573/103489818-03ca5600-4e0f-11eb-8d19-8ac375d3fa1b.png)

**Comment by jenf** [comment]
Likely this would be computationally expensive

**Comment by slapphappyjazz** [comment]
I don't know the code but in principle I don't see why this would be computationally expensive.  At the point a tile is upgraded, there must be some code at the moment that increments the number of avilable tiles of the tile being replaced.  So this code could test the attribute on the tile being replaced and either increment the number of available tiles (the default behaviour) or set a flag showing that the tile is unavailable.  (If i were writing this in C, I'd be tempted to use a -1 value to indicate this).  
The tiles tab must have some code to check whether to fade out each tile type, which is currently done if the number available is zero.  This test could be changed to check whether the unavailable flag has been set.  (If using the -1 hack as above, the test could simply check for <= 0 instead of =0, but there may be nicer ways to implement this).

**Comment by tobymao** [comment]
i don't think we will implement this since we'd have to do a full scan. closing for now

**Comment by slapphappyjazz** [comment]
OK, but I'd like to understand why you'd need to do a full scan and why the approach I outlined above wouldn't work.

**Comment by tobymao** [comment]
we can’t assume a tile can be laid in only one hex, you’d have to check every single hex to check that a tile can’t be laid

**Comment by neutronc** [comment]
i do understand your point of view Toby. in Rails-18xx we handle that with a field per hex that keeps the possible updates/upgrades and you do a lookup if that particular tile is still valid for an upgrade in the map. 
Of course you have to define possible upgrades after a tile lay, removing old upgrades etc...

**Comment by tobymao** [comment]
it is possible, i don’t think it’s worth adding the coding complexity and computational complexity for this though

**Comment by neutronc** [comment]
beg to differ Toby, i saw lots of scenarios already where it is really helpful to see which hex is upgradable still. 
And yes i do have to check how you currently present the upgrade paths in the gui and find out possible upgrades in the engine, havent made it that far yet :)
It all about checks and validation, but i would be more than glad to help out if i can.

**Comment by tobymao** [comment]
game#upgrades_to? will tell you this

**Comment by slapphappyjazz** [comment]
What I had in mind was the special case where a tile can only be placed in a single hex and where this is known in advance, when writing the specificaiton for the tile.  Examples include NY in 1830 & 1817, Moscow in 1861 (& the equivalent hex in 1867), Tampico, Veracruz and Mazatlan in 18Mex, and so forth.  In all these examples, there is no way that a tile for those locations can re-enter play once it has been upgraded, as they can only be placed in a single specific hex.

I do see that this a specialisation of a more general solution. For example, if all the Y hexes in 1867 or all the B hexes in 1817 were upgraded to green, the corresponding yellow tiles would be unavailable.  I was assuming that the specific case would be useful enough without having to implement the more general solution.  It's possible though that people would see the tiles being faded out in the special case and then wonder why that wasn't happening in the more general case - i.e. there might be a usability downside to implementing only the special case.

**Comment by tobymao** [comment]
we try to avoid special cases as it increases the complexity of the code
