### ISSUE TITLE
18USA Changes

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#3028]
https://github.com/ventusignis/18xx/tree/18USA-map has map, companies, and stock market for a starting base

- [x] P1
- [x] P2
- [x] P3
- [x] P4
- [x] P5
- [x] P6
- [x] P7
- [x] P8
- [x] P9
- [x] P10
- [x] P11
- [x] P12
- [x] P13
- [x] P14
- [x] P15
- [x] P16
- [x] P17
- [x] P18
- [x] P19
- [x] P20
- [x] P21
- [x] P22
- [x] P23
- [x] P24
- [x] P25
- [x] P26
- [x] P27
- [x] P28
- [x] P29
- [x] P30
- [x] Free Station subsidy
- [x] Resource subsidy
- [x] Randomization of starting privates
- [x] Icons for the subsidies (SR1 then OR1+)
- [x] Subsidy Randomization
- [x] Metropolis Randomization
- [x] Offboard Randomization
- [x] New Tiles
- [x] Pullmans
- [x] 5+ player count trains
- [x] 5+ player count loan market
- [x] Blank -> Green city tile upgrades are mandatory in phase 5+
- [x] Home -> Brown tile upgrade for companies first OR in phase 5+
- [x] Ability to skip levels when upgrading tiles for a fee in phase 5+
- [x] Alternate stock market behavior
- [x] New Export Rules
- [x] At most 2 trains to Mexico when running trains
- [x] bid increments of $1

**Comment by CaptainObi** [comment]
- [ ]  P1
- [ ] P2
- [ ] P3
- [ ] P4
- [ ] P5
- [ ] P6
- [ ] P7
- [ ] P8
- [ ] P9
- [ ] P10
- [ ] P11
- [ ] P12
- [ ] P13
- [ ] P14
- [ ] P15
- [ ] P16
- [ ] P17
- [ ] P18
- [ ] P19
- [ ] P20
- [ ] P21
- [ ] P22
- [ ] P23
- [ ] P24
- [ ] P25
- [ ] P26
- [ ] P27
- [ ] P28
- [ ] P29
- [ ] P30
- [ ] Randomization of starting privates
- [ ] Icons for the subsidies (SR1 then OR1+)
- [ ] Subsidy Randomization
- [ ] Metropolis Randomization
- [ ] New Tiles
- [ ] Pullmans
- [ ] 5+ player count trains
- [ ] 5+ player count loan market
- [ ] Blank -> Green plain tile upgrades are mandatory in phase 5+
- [ ] Home -> Brown tile upgrade for companies first OR in phase 5+
- [ ] Ability to skip levels when upgrading tiles for a fee in phase 5+
- [ ] Alternate stock market behavior
- [ ] At most 2 trains to Mexico when running trains
- [ ] Off-board Randomization

**Comment by crericha** [comment]
There are two lists in this issue. Should the checked boxes in each be merged?

**Comment by CaptainObi** [comment]
I'm not sure what's going on @ventusignis It looks like they picked up the game after I left it and implemented some features, but some features that I had implemented such as offboard randomization and metropolis randomization haven't been ticked. Orginally I created my own checklist as I couldn't edit @ventusignis 's but looks like he has picked up the game again?

**Comment by crericha** [comment]
I merged the two lists. @CaptainObi, if you decide to do more, let me know what you did and I can mark it as complete.

I'd like to see this one get wrapped up. I'm going to start working on the remaining privates.

**Comment by CaptainObi** [comment]
I'm game for doing private randomisation. I'll look into it.

**Comment by crericha** [comment]
@ventusignis, are the 5+ trains & loan market referring to the optional extended game?

**Comment by CaptainObi** [comment]
@ventusignis Nice PR!, If yall don't mind, could people just note what they are working on so that I don't accidentally end up duplicating code? Thanks
