### ISSUE TITLE
1817 - Game repeats log about no longer eligable

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#3039]
During the game one player went bankrupt and their companies went into liquidation. WT acquired the company. After this J should have been sold from liquidation, but the UI showed WT as if it was being offered and the chat log has an infinite scroll of 

WT is no longer eligible to be auctioned
J is being liquidated, bank offers $0, corporation had $0 and 0 loans

https://18xx.games/game/21129

![image](https://user-images.githubusercontent.com/11777262/103491907-3870ea00-4ddc-11eb-85c6-5308ac94f38b.png)

**Comment by jenf** [comment]
Looks like you've got past the issue, can you still reproduce?

**Comment by jenf** [comment]
Oh the logging still exists

**Comment by curlett** [comment]
The game was completely broken. I didn't include an action, since we were leaving it there, but then it somehow fixed itself and we continued. 

I can't repro the completely broken game state, so now it appears to just be a logging bug as you said.
