### ISSUE TITLE
Pressing Undo when partially selecting routes causes an exception when trying to relay track

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#304]
Seen in the following game

Steps to reproduce

Select first Train but do not select routes
Press Undo
Attempt to upgrade I3 again

'uncaught exception: GameError: Cannot use I2 in route because it is not connected'
Looks like the map thinks its still in routing mode

`{
  "status": "active",
  "actions": [
    {
      "type": "message",
      "entity": "timox",
      "entity_type": "player",
      "id": 1,
      "message": "hi"
    },
    {
      "type": "message",
      "entity": "oniony",
      "entity_type": "player",
      "id": 2,
      "message": "yo"
    },
    {
      "type": "bid",
      "entity": "oniony",
      "entity_type": "player",
      "id": 3,
      "company": "Sumitomo Mines Railway",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "timox",
      "entity_type": "player",
      "id": 4,
      "company": "Mitsubishi Ferry",
      "price": 35
    },
    {
      "type": "message",
      "entity": "oniony",
      "entity_type": "player",
      "id": 5,
      "message": "@HighEagle you there dude?"
    },
    {
      "type": "bid",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 6,
      "company": "Ehime Railway",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "oniony",
      "entity_type": "player",
      "id": 7,
      "company": "South Iyo Railway",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "timox",
      "entity_type": "player",
      "id": 8,
      "company": "South Iyo Railway",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 9,
      "company": "Dougo Railway",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "oniony",
      "entity_type": "player",
      "id": 10,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "par",
      "entity": "oniony",
      "entity_type": "player",
      "id": 14,
      "corporation": "KO",
      "share_price": "65,5,3"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "par",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 16,
      "corporation": "IR",
      "share_price": "75,3,3"
    },
    {
      "type": "buy_share",
      "entity": "oniony",
      "entity_type": "player",
      "id": 17,
      "share": "KO_1"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "buy_share",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 19,
      "share": "IR_1"
    },
    {
      "type": "buy_share",
      "entity": "oniony",
      "entity_type": "player",
      "id": 20,
      "share": "KO_2"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "buy_share",
      "entity": "Dougo Railway",
      "entity_type": "company",
      "id": 22,
      "share": "IR_2"
    },
    {
      "type": "buy_share",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 23,
      "share": "IR_3"
    },
    {
      "type": "buy_share",
      "entity": "oniony",
      "entity_type": "player",
      "id": 24,
      "share": "KO_3"
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 25,
      "share": "IR_4"
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 26,
      "share": "IR_5"
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 27,
      "share": "KO_4"
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 28,
      "share": "KO_5"
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 29,
      "hex": "E2",
      "tile": "5-0",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 30,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 31,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 32
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 33,
      "hex": "K6",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 35,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 40,
      "hex": "F3",
      "tile": "57-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 41
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 42,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "F3",
            "E2"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 43,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 44,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 45
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 46,
      "hex": "J5",
      "tile": "58-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 47,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "K4",
            "K6",
            "L7"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "K4",
            "J5"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 48,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 49,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 50
    },
    {
      "type": "buy_share",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 51,
      "share": "KO_6"
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "buy_share",
      "entity": "oniony",
      "entity_type": "player",
      "id": 53,
      "share": "KO_7"
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 57
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 58,
      "hex": "G4",
      "tile": "6-0",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 59,
      "city": "6-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 60,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "E2",
            "F3"
          ]
        },
        {
          "train": "2-4",
          "hexes": [
            "G4",
            "F3"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 61,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 62,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "buy_company",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 63,
      "company": "Ehime Railway",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 64
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 65,
      "hex": "J3",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 66,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "K4",
            "K6",
            "L7"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "K4",
            "J3",
            "J1"
          ]
        },
        {
          "train": "2-5",
          "hexes": [
            "K4",
            "J5"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 67,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 68,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "sell_shares",
      "entity": "timox",
      "entity_type": "player",
      "id": 70,
      "shares": [
        "IR_4",
        "IR_5"
      ],
      "percent": 20
    },
    {
      "type": "sell_shares",
      "entity": "timox",
      "entity_type": "player",
      "id": 71,
      "shares": [
        "KO_4",
        "KO_5"
      ],
      "percent": 20
    },
    {
      "type": "par",
      "entity": "timox",
      "entity_type": "player",
      "id": 72,
      "corporation": "TR",
      "share_price": "80,2,3"
    },
    {
      "type": "buy_share",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 73,
      "share": "IR_6"
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "buy_share",
      "entity": "oniony",
      "entity_type": "player",
      "id": 75,
      "share": "IR_7"
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 77,
      "share": "TR_1"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 78
    },
    {
      "type": "buy_share",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 79,
      "share": "KO_4"
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 80
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 82,
      "share": "TR_2"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 83
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 85
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 86,
      "share": "TR_3"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "buy_share",
      "entity": "timox",
      "entity_type": "player",
      "id": 90,
      "share": "TR_4"
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 91
    },
    {
      "type": "pass",
      "entity": "HighEagle",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "oniony",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "pass",
      "entity": "timox",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "lay_tile",
      "entity": "Mitsubishi Ferry",
      "entity_type": "company",
      "id": 95,
      "hex": "G10",
      "tile": "437-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 96,
      "hex": "G8",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 97,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 98
    },
    {
      "type": "buy_company",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 99,
      "company": "Mitsubishi Ferry",
      "price": 60
    },
    {
      "type": "buy_company",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 100,
      "company": "South Iyo Railway",
      "price": 160
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 101
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 102,
      "hex": "F3",
      "tile": "205-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 103,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "E2",
            "F3"
          ]
        },
        {
          "train": "2-4",
          "hexes": [
            "F3",
            "F1"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "F3",
            "G4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 104,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 106,
      "hex": "I4",
      "tile": "438-0",
      "rotation": 3
    },
    {
      "type": "place_token",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 107,
      "city": "438-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 108,
      "routes": [
        {
          "train": "3-1",
          "hexes": [
            "K4",
            "J5",
            "I4"
          ]
        },
        {
          "train": "2-2",
          "hexes": [
            "J1",
            "J3",
            "K4"
          ]
        },
        {
          "train": "2-3",
          "hexes": [
            "L7",
            "K6",
            "K4"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 109,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "lay_tile",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 111,
      "hex": "G4",
      "tile": "13-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 112,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "E2",
            "F1"
          ]
        },
        {
          "train": "2-1",
          "hexes": [
            "E2",
            "F3"
          ]
        },
        {
          "train": "3-0",
          "hexes": [
            "G4",
            "F3",
            "F1"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 113,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IR",
      "entity_type": "corporation",
      "id": 114
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 115,
      "hex": "H7",
      "tile": "6-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 117,
      "routes": [
        {
          "train": "3-2",
          "hexes": [
            "G10",
            "F9",
            "G8",
            "H7"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 118,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 119,
      "train": "3-3",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 120
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 121
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 122,
      "hex": "I2",
      "tile": "6-0",
      "rotation": 4
    }
  ],
  "players": [
    {
      "id": 569,
      "name": "oniony"
    },
    {
      "id": 399,
      "name": "timox"
    },
    {
      "id": 378,
      "name": "HighEagle"
    }
  ],
  "title": "1889",
  "description": "Open fast/live game",
  "max_players": 3,
  "id": "hs_1588764744",
  "user": {
    "id": 0,
    "name": "You"
  },
  "settings": {
    "seed": 2.045571273851731e+38
  },
  "turn": 4,
  "round": "Operating Round",
  "acting": [
    569
  ],
  "result": {},
  "created_at": "2020-05-6",
  "updated_at": "2020-05-6",
  "mode": "hotseat"
}`

**Comment by oniony** [comment]
To add a little more detail, I was able to reselect I2 but only had one of the two track options available: the piece I had placed last time was not an option.

However, I later realised it was being rendered almost entirely off screen (mobile phone) but I was able to tap the right corner of the hex in order to place it again.
