### ISSUE TITLE
1846 route calculator using Mail Contract on 2 trains

### ISSUE THREAD

**Issue by jacobb11** [tobymao/18xx#3044]
https://18xx.games/hotseat/hs_rqvmfyip_21160

**Comment by dfannius** [comment]
That's a hotseat game, so we don't have access to it; you'll have to post the JSON here (Tools / Copy Game Data).

Also, please tell us what you think the bug is. What behavior did you expect and what happened instead?

**Comment by PatrickoftheIsles** [comment]
This game that is currently live:

https://18xx.games/game/21160

Saw in OR 1.2 and in OR 2.2 the Grand Trunk company overpay route value by $20 and $30 respectively because the Mail Contract private company bonus was applied to two separate train routes instead of the one that is legally allowed.

**Comment by dfannius** [comment]
https://18xx.games/game/21160?action=111
https://18xx.games/game/21160?action=244

**Comment by dfannius** [comment]
When I run the game locally, it works okay in old versions of the code and has the buggy behavior starting with 578a07a97da70f91d6798adc6076ec850145f1dc.
