### ISSUE TITLE
[1846 2p] purchase of unaffordable train permitted, breaks game

### ISSUE THREAD

**Issue by thepackrat** [tobymao/18xx#3049]
1846, 2p variant
https://18xx.games/game/21173?action=107

I unthinkingly clicked on 'buy a train' wiht a company (C&O) which had trains, but not enough money and the game moved my share price down, then broken because presumalby this was an illegal buy.

**Comment by thepackrat** [comment]
We managed to refresh and undo out of this. The message we go initiall said game was irrecoverably broken. This was at the action above, the C&O purchasing a 3/5 it couldn't afford rather than passing (which the game will show post undo)

**Comment by michaeljb** [comment]
I managed to reproduce this locally
