### ISSUE TITLE
OR History columns should be in reverse order (most recent first)

### ISSUE THREAD

**Issue by Anvil-X** [tobymao/18xx#305]
The most important thing about the OR revenue history on the spreadsheet view is what was earned recently, and it's easiest to see that if the columns are arranged so the the most recent OR is  in the first column rather than the last

**Comment by dfannius** [comment]
Hmm. Left-to-right is more natural, and also matches what people are used to from rr18xx if anyone is coming from there. The most recent run is also on the corporation cards so it's pretty easily available.

So I cast a mild vote for the status quo (although I am biased by playing with a desktop browser that is reasonably wide).

**Comment by Anvil-X** [comment]
Actually, my suggestion was entirely motivated by the fact that I read left-to-right and have no use for who ran for zero in the first OR.  Pertinent data first.  Also, bad design on another site is no justification for repeating it here

**Comment by jcoveney** [comment]
I prefer the current left to right design. If you just want last OR that is already on the company cards you see on the main page. I personally find seeing the OR history very useful in evaluating game state.

**Comment by Anvil-X** [comment]
@jcoveney First of all, I never asked to see just the last OR info on the spreadsheet, just reverse it. 

How does this prevent you from understanding the OR history?

![operating](https://user-images.githubusercontent.com/64378525/81316885-c4662280-9051-11ea-8ca0-24f9befb6484.JPG)

**Comment by jcoveney** [comment]
Because this is not how financial data is ever presented in any context. In 99% of contexts where spreadsheets are used to present financial data, it's left to right.

Toby can make the call on how much fine grained configuration of this stuff he wants to allow. We could absolutely have a toggle in tools that allows people to flip the order.

**Comment by sparr** [comment]
I agree that the benefits of reversing the order outweigh the breaking of convention.

**Comment by Anvil-X** [comment]
@tobymao Can we address this?  Current implementation is bad

**Comment by wheresvic** [comment]
I can try to tackle this as a user preference

**Comment by Anvil-X** [comment]
@tobymao  closed and not implemented?
