### ISSUE TITLE
Display city names and coordinates for tile lays

### ISSUE THREAD

**Issue by thepackrat** [tobymao/18xx#3052]
The game notification that notes when a city tile is laid could be more descriptive if it included the city name as well as the coordinate. We appear to know those from the map, for e.g. 

e.g. from '46. 

"NYC spends $20 and lays tile #611 with rotation 5 on D14"
could be
"NYC spends $20 and lays tile #611 with rotation 5 on D14 (Toledo)"

this would also be interesting to annotate non-city track that was immediately adjacent to a named city (SE of Toledo), but I could see this being contentious.

**Comment by benjaminxscott** [comment]
I have a patch for this, 1m
