### ISSUE TITLE
Game breaking bug - 1867 corporation offered opportunity to merge with itself

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3053]
https://18xx.games/game/20289?action=249

I'm pretty sure the PM can't merge with itself.

<img width="336" alt="Screen Shot 2021-01-03 at 8 46 06 PM" src="https://user-images.githubusercontent.com/8732435/103502044-e1333f80-4e04-11eb-9a6d-3753f8e5f9c3.png">

**Comment by ChrisTheCat** [comment]
And if I accept the offer to merge with myself, I get told this:

<img width="483" alt="Screen Shot 2021-01-03 at 8 48 58 PM" src="https://user-images.githubusercontent.com/8732435/103502164-3707e780-4e05-11eb-87b2-35e77f415991.png">

**Comment by ChrisTheCat** [comment]
And if I choose not to merge, it asks me to complete the CS,CA merger - and I should not be offered that choice.

**Comment by jenf** [comment]
Your still in the bad merge state, i'm going to delete the actions that cause it when I deploy

**Comment by jenf** [comment]
I've deleted the actions and now you can't press the convert button, reopen if you get it back into that state
