### ISSUE TITLE
fixture directory already watched

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#3057]
@michaeljb 
rack_1   |         ** ERROR: directory is already being watched! **
rack_1   | 
rack_1   |         Directory: /18xx/public/fixtures
rack_1   | 
rack_1   |         is already being watched through: /18xx/spec/fixtures
rack_1   | 
rack_1   |         MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors

**Comment by michaeljb** [comment]
Caused by the symlink `public/fixtures -> ../spec/fixtures/`. Moving the fixtures out of `spec/` and into `public/` would eliminate this error, but it feels more natural to keep them in `spec/`. I'll see if I can find anything in the `listen` config.

**Comment by michaeljb** [comment]
Apparently this is a long-lived issue in `listen`. Even adding ignoring `spec/fixtures` and `public/fixtures` in the rerun command triggers this duplicate directory issue.

**Comment by jenf** [comment]
Let's not fix then
