### ISSUE TITLE
Tile tab - leave tiles visible even when exhausted

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#306]
Currently tiles disappear when there are none remaining. Personally I'd prefer for them to remain (perhaps grayed out) with an x0 indicator. Perhaps I'm in the minority there--just used to the rr18xx display style.

**Comment by jenf** [comment]
I'd agree with this change, seeing that you can't use something (which may later be available as a tile gets upgraded) is useful.

**Comment by scottredracecar** [comment]
I think even the radial tile picker should show exhausted tiles, perhaps grayed out.

I ran into cases where I was trying to upgrade a tile and nothing happened and I thought it was a bug since nothing happened when I clicked the hex.

**Comment by jenf** [comment]
yeah, that'd be a good improvement as well
