### ISSUE TITLE
[1867] "The game is broken and cannot accept any new actions" error incorrectly displayed

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3069]
https://18xx.games/game/21268?action=1115

At this point in the game during the place token phase, I clicked on a city that already had one of my tokens and received the above error instead of one for already having a token in that city. Apparently the same error had popped up for another player several times, but I cannot say for what actions. While the game would not let me skip placing the token at the time, a refresh of the  page did and the game continued.

**Comment by tobymao** [comment]
hard refresh your brower
