### ISSUE TITLE
[18CO] - Illegal action Blocking step Buy Shares cannot process action 873

### ISSUE THREAD

**Issue by wheresvic** [tobymao/18xx#3073]
The 6 train and the E train were bought in the same set of ORs

In the subsequent SR we had the President's choice round followed by the Stock round. In the SR we could not buy any shares due to the above error.

Game json: https://gist.github.com/wheresvic/2b427b182e6e6cfe98bd1f27bfbc3679

**Comment by wheresvic** [comment]
Could be related to #3066

**Comment by ryandriskel** [comment]
From https://18xx.games/game/21298

**Comment by ryandriskel** [comment]
I don't have a solution on this yet but found the problem. The browser thought it was Viz's turn while the server thinks its wheresvic's turn.

**Comment by wheresvic** [comment]
Looks like @ryandriskel is right - we got it again https://18xx.games/game/21415?action=854 and here you can see that on the home page it shows Aavar's turn but when you jump into the game it is showing DrAwesome to make a move.
