### ISSUE TITLE
[18Mex] Cannot "trade up" 5% to 10%.

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#3074]
https://gist.github.com/Auzzy/cf55c2f005840d4cf3b5ebbc61c02451

thomb should be able to trade their 5% share for the 10% share in the market, but no button appears to do so.

**Comment by daniel-sousa-me** [comment]
The behaviour is correct. Thomb is at cert limit and the 5% share doesn't count towards the cert limit

**Comment by Auzzy** [comment]
@daniel-sousa-me Please load up the gist before making assertions about it. =) This is a clone of the game discussed in chat, in which I've sold a different 10% share, so thomb is below cert limit. However, the option to trade up still does not appear. This was also noted in the chat right before I filed this bug.

**Comment by daniel-sousa-me** [comment]
I'm sorry. I understood you sold the 5%.
