### ISSUE TITLE
1867 National Railway token should be on starting map

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3080]
When the "show starting map" button is clicked, the national railway token should remain on the map.

**Comment by jenf** [comment]
Not 1867 specific

**Comment by bentziaxl** [comment]
fixed, no longer an issue

**Comment by dfannius** [comment]
The maple leaf token? I don't see it when "Show Starting Map" is enabled.

**Comment by bentziaxl** [comment]
saw it on a clean starting game. I though that was the original issue

**Comment by dfannius** [comment]
"Show Starting Map" is a toggle on the map display that you can use any time in the game to show what the original map looked like before the game started.

**Comment by bentziaxl** [comment]
created a pr to fix
