### ISSUE TITLE
[1860] Game stuck on the bug page

### ISSUE THREAD

**Issue by pltnc** [tobymao/18xx#3083]
Whenever I enter game 19190, I got stuck on a page that says:

"We're sorry this game cannot be continued due to GameError: Step Buy Trains cannot process {"type"=>"pass", "entity"=>"BHI&R", "entity_type"=>"corporation", "id"=>801}
View the last valid action (800)
Please raise a bug report and include the game id (19190) and the following JSON data
Show Game DataCopy Game Data"

and the game was stuck on my main page.
Version number:274d8cf8
Please help deleting the game or undoing the action, thank you.

**Comment by tobymao** [comment]
pinned game
