### ISSUE TITLE
1867 game stuck, THB can't lay track

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3088]
https://18xx.games/game/20289?action=282 or https://18xx.games/game/20289

THB can select a hex and tile, but then the green check and red x buttons don't respond and the game goes out of sync.

**Comment by jenf** [comment]
Ahh, THB can't afford a train.

**Comment by ChrisTheCat** [comment]
Why would that have any impact on laying track?

**Comment by jenf** [comment]
Because you skip dividends you go into interest the game tried to nationalize you causing the crash.

**Comment by ChrisTheCat** [comment]
How do you skip dividends before the track laying step completes?

**Comment by ChrisTheCat** [comment]
Actually, I see you linked a PR to fix it, no need to actually explain the intricacies to me.
