### ISSUE TITLE
18CO

### ISSUE THREAD

**Issue by elkrajico** [tobymao/18xx#3093]
Game 18CO
Link: https://18xx.games/game/20628
On SR when anybody pass, it shows:
"Illegal action Blocking step Buy Shares cannot process action 814"
Refresh site is worthless.
So, we END the game.

IMHO. When I clone the game, i was able to pass without any error and normal finish the game.

**Comment by jenf** [comment]
Probably impacted during the migration, loads fine now

**Comment by elkrajico** [comment]
Still sam problem. 
"Illegal action Blocking step Buy Shares cannot process action 830"

**Comment by jenf** [comment]
we have a fix in review, will probably need them to wake up 
#3089

dup of #3094
