### ISSUE TITLE
18Co- We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 854

### ISSUE THREAD

**Issue by Aavar77** [tobymao/18xx#3094]
We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 854
Broken action: { "type": "pass", "entity": 1739, "entity_type": "player", "id": 854, "user": 5518 }
Please raise a bug report and include this link (https://18xx.games/game/21415?action=854) and the following JSON data

**Comment by wheresvic** [comment]
Duplicates #3073
