### ISSUE TITLE
Add "prepainted" line to show where the main line goes

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#3095]
It would be nice if the main lines (Stockholm to Malmö / Göteborg / Luleå) was shown as a line on the board instead of using icons.
It should be a special track that cannot be used by train routes, and do not affect track upgrades.
Adding it just to the initial hexes and not shown after upgrade (if main line has not been completed in the hex) would be sufficient I think.

**Comment by jenf** [comment]
This should be doable using the parts approach

**Comment by roseundy** [comment]
Once this is implemented, Harzbahn 1873 will use it too.

**Comment by jenf** [comment]
It's already available and used on 18LA and 1867

**Comment by roseundy** [comment]
No. I think this is something different. A thin track on the map where tiles need to be laid to follow the concession route.

**Comment by perwestling** [comment]
Put into a collective issue to keep track for the future.

This issue is closed for now.
