### ISSUE TITLE
18SJ didn't let my select par, now won't load

### ISSUE THREAD

**Issue by SwanofTrumpeter** [tobymao/18xx#3098]
https://18xx.games/game/21452 can't list the last action because the page is just stuck on a loading screen,, but we were on phase 1 buying privates. I had just bought the 225kr private and was going to decide the par value for the company attached to it. I repeatedly selected the par I wanted but nothing happened, when I tried to reload the page it got stuck on a screen just saying: Loading game..., where it has remained since. 

Any tips to resolve the issue?

**Comment by ventusignis** [comment]
I tried loading the game and saw this error in the browser console
​```
message: "undefined method `can_sell?' for #<Engine::Step::G18SJ::ChoosePriority:0x513a>"
name: "can_sell?"
```

**Comment by perwestling** [comment]
I will have a look - seems to be related to the priority deal choice private.
