### ISSUE TITLE
18SJ - unable to load stuck in loading game - we were doing the privates auction

### ISSUE THREAD

**Issue by Aavar77** [tobymao/18xx#3099]
18SJ - unable to load stuck in loading game - we were in the middle of the auction

https://18xx.games/game/21455

**Describe the bug**
During starting privates auction 
the game sorta froze was not my turn to bid 
exiting browser, was not able to load the screen stalled on loading game

**Comment by perwestling** [comment]
I'll have a look.

**Comment by perwestling** [comment]
Are you sure it was game 21455? I checked it and that game is in OR 4.1, and load fine for me.

**Comment by Aavar77** [comment]
its 21452
  
   ---------- Original Message ----------
   From: Per Westling <notifications@github.com>
   Date: January 6, 2021 at 2:29 PM
   
   
    
   Are you sure it was game 21455? I checked it and that game is in OR 4.1, and load fine for me.

**Comment by perwestling** [comment]
Ok, that was reported in #3098 as well, and that bug I have located. So I will close this issue as it is a duplicate. 
Thanks for reporting the issue.
