### ISSUE TITLE
18SJ - Göta kanalbolag private ability not working

### ISSUE THREAD

**Issue by Aavar77** [tobymao/18xx#3102]
https://18xx.games/game/21455
When Raymong bought the private into MOJ company, Ability didnt show up until the next OR started.
then clicking the Buy GKR Bonus ability button gave error and reset the game back position as if button wasn't pressed.
thre was a different error but it went by too fast to catch

![image](https://user-images.githubusercontent.com/76664105/103806654-5b410f80-5023-11eb-9f12-39fb0b6c84e1.png)

**Comment by perwestling** [comment]
I'll have a look.

**Comment by perwestling** [comment]
The bonus might be correct, as both trains get 50kr for Norrköping, and then 1 train gets 50kr for Jönköping.
But I check with designer. If game is correct maybe the GUI might show this better, and description might need update.

It seems refresh might be needed to show up the effects correcly. I will see if I can improve that part a bit.

**Comment by perwestling** [comment]
Checked with designer - 150kr is correct bonus. 
But I need to improve description and/or presentation for the bonus.
And the activation bugs still need to be looked into.

**Comment by perwestling** [comment]
Suggestion is to use the following presentation for the 3 train:
E8 - C8 + GKBx2

**Comment by perwestling** [comment]
I have now:

- Improved description of GKB
- Improved revenue presentation for multiple bonuses on one train
- Make Buy button appear when private bought

Still, the bonus does not appear directly when bought, if a route is shown.
Instead you need to do Refresh, or in some way do something with the route (e.g. click on a revenue center) and the route will be updated and include the bonus.

Now, this is not optimal and need to be improved, but it should be an enough workaround.

**Comment by Aavar77** [comment]
Great thank you
  
   ---------- Original Message ----------
   From: Per Westling <notifications@github.com>
   Date: January 6, 2021 at 5:21 PM
   
   
    
   I have now:
   
    Improved description of GKB
    Improved revenue presentation for multiple bonuses on one train
    Make Buy button appear when private bought
   
   Still, the bonus does not appear directly when bought, if a route is shown. Instead you need to do Refresh, or in some way do something with the route (e.g. click on a revenue center) and the route will be updated and include the bonus.
   Now, this is not optimal and need to be improved, but it should be an enough workaround.
