### ISSUE TITLE
Change browser tab to indicate pending turn

### ISSUE THREAD

**Issue by chrispday** [tobymao/18xx#3107]
If you have multiple tabs open in a browser there is no visual cue there is a pending turn if you are on another tab.

Creating a new favicon with a pending turn overylay, eg. an orange dot over the hex
or, Add a dot (U+2022) at the start of the title, eg. • 18xx.games

**Comment by benjaminxscott** [comment]
It looks like there was [some work on implementing notifs and tab title changes](https://github.com/tobymao/18xx/pull/386), if that seems related

**Comment by chrispday** [comment]
Appears to be already implemented, favicon goes dark red and asterisk is in title.
