### ISSUE TITLE
Home page chat box option?

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#3119]
The chat input box asks for the discussion to stay strictly to 18XX.

I come on tonight/this morning to find political commentary. Whether I agree with it or not is secondary to the fact that it should not be there and doing so is explicitly discouraged.

I get that policing that chat isn’t something anyone wants to do, so is there any way to give the user the option to close it? I understand that a lot of people use it to find games and that’s useful for them, but for those of us who (1) don’t use it for that and (2) don’t want to have to read off-topic commentary, the option to close it would be helpful.

**Comment by jenf** [comment]
I'm a bit wary of this since we use the chat to warn people of outages.

**Comment by SmithInMN** [comment]
I can only speak for myself, but that’s a chance I am willing to take. I try to avoid the chat anyway because of things like the above incident.

i don’t know if there are filter/block features inherent to that feature, but that could be a compromise.

**Comment by beginetienne** [comment]
There was very little political commentary the past 12 hours which was quickly self moderated by the users there.  I would prefer we keep the box visible at all times.

**Comment by tobymao** [comment]
you can use uBlock origin to hide the element from your screen
