### ISSUE TITLE
[18SJ] Add legend with bonus values on map

### ISSUE THREAD

**Issue by Nisse75** [tobymao/18xx#3120]
Add a legend to the map with value of bonus routes and other map features.

**Comment by perwestling** [comment]
Might be hard to fit in the legend so instead I am considering to add this to the route page in 18SJ. Not sure if it would work for 1824 or 1867?

![image](https://user-images.githubusercontent.com/2631151/108590951-7dd68000-7366-11eb-9dcf-bd777b2557db.png)

**Comment by perwestling** [comment]
Alternative look:
![image](https://user-images.githubusercontent.com/2631151/108590977-9b0b4e80-7366-11eb-90d5-8012009ef92d.png)

**Comment by perwestling** [comment]
I suppose a third alternative could be to use the 2nd suggestion, and add a Comment column that show Lapplandspilen etc

**Comment by perwestling** [comment]
No, the third suggestion do not work as only two columns are supported at the moment.

**Comment by Nisse75** [comment]
Rhe first option lloms good and has some thematic flavour

**Comment by jenf** [comment]
This would work for 1867/1861

**Comment by perwestling** [comment]
> This would work for 1867/1861

You mean the tabular form?

I am thinking if this should be hidden by default, and then click to show the bonuses? But that would be more work.

**Comment by perwestling** [comment]
@jenf If a similar thing should be done for 1861/67, maybe a new issue should be created?

**Comment by perwestling** [comment]
I will get back with 1824 when I take up work on that title again.
