### ISSUE TITLE
[1846] Restart Turn Bug

### ISSUE THREAD

**Issue by mkkohls** [tobymao/18xx#3129]
**Please provide**
[1846] used restart turn feature

**Describe the bug**
Please raise a bug report and include this link (https://18xx.games/game/21612?action=54) and the following JSON data

{
  "id": 21612,
  "description": "Mfb",
  "user": {
    "id": 1001,
    "name": "Frank"
  },
  "players": [
    {
      "id": 1972,
      "name": "mkkohls"
    },
    {
      "id": 1001,
      "name": "Frank"
    },
    {
      "id": 3258,
      "name": "Korval"
    }
  ],
  "max_players": 3,
  "title": "1846",
  "settings": {
    "seed": 865558168,
    "unlisted": true,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    1001
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 60,
      "entity": 3258,
      "company": "C&WI",
      "created_at": 1610067483,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 2,
      "type": "bid",
      "price": 60,
      "entity": 1001,
      "company": "MPC",
      "created_at": 1610067493,
      "entity_type": "player",
      "user": 1001
    },
    {
      "id": 3,
      "type": "bid",
      "price": 0,
      "entity": 1972,
      "company": "Pass (1)",
      "created_at": 1610067499,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 4,
      "type": "bid",
      "price": 40,
      "entity": 3258,
      "company": "O&I",
      "created_at": 1610067513,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 5,
      "type": "bid",
      "price": 40,
      "entity": 1001,
      "company": "BIG4",
      "created_at": 1610067523,
      "entity_type": "player",
      "user": 1001
    },
    {
      "id": 6,
      "type": "bid",
      "price": 0,
      "entity": 1972,
      "company": "Pass (2)",
      "created_at": 1610067530,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 7,
      "type": "bid",
      "price": 80,
      "entity": 3258,
      "company": "MAIL",
      "created_at": 1610067577,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 8,
      "type": "bid",
      "price": 0,
      "entity": 1001,
      "company": "Pass (3)",
      "created_at": 1610067587,
      "entity_type": "player",
      "user": 1001
    },
    {
      "id": 9,
      "type": "pass",
      "entity": 1972,
      "created_at": 1610067618,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 10,
      "type": "pass",
      "entity": 3258,
      "created_at": 1610067654,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 11,
      "type": "pass",
      "entity": 1001,
      "created_at": 1610067689,
      "entity_type": "player",
      "user": 1001
    },
    {
      "id": 12,
      "type": "pass",
      "entity": 1972,
      "created_at": 1610067693,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 13,
      "type": "bid",
      "price": 60,
      "entity": 3258,
      "company": "MS",
      "created_at": 1610067747,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 14,
      "type": "par",
      "entity": 1972,
      "created_at": 1610067787,
      "corporation": "NYC",
      "entity_type": "player",
      "share_price": "60,0,6",
      "user": 1972
    },
    {
      "id": 15,
      "type": "par",
      "entity": 1001,
      "created_at": 1610067829,
      "corporation": "IC",
      "entity_type": "player",
      "share_price": "100,0,10",
      "user": 1001
    },
    {
      "id": 16,
      "type": "pass",
      "entity": 3258,
      "created_at": 1610067837,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 17,
      "type": "buy_shares",
      "entity": 1972,
      "shares": [
        "NYC_1"
      ],
      "percent": 10,
      "created_at": 1610067858,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 18,
      "type": "pass",
      "entity": 3258,
      "created_at": 1610067868,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 19,
      "type": "buy_shares",
      "entity": 1972,
      "shares": [
        "NYC_2"
      ],
      "percent": 10,
      "created_at": 1610067874,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 20,
      "type": "pass",
      "entity": 3258,
      "created_at": 1610067884,
      "entity_type": "player",
      "user": 3258
    },
    {
      "id": 21,
      "type": "buy_shares",
      "entity": 1972,
      "shares": [
        "NYC_3"
      ],
      "percent": 10,
      "created_at": 1610067897,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 22,
      "type": "par",
      "entity": 3258,
      "created_at": 1610067932,
      "corporation": "GT",
      "entity_type": "player",
      "share_price": "60,0,6",
      "user": 3258
    },
    {
      "id": 23,
      "type": "buy_shares",
      "entity": 1972,
      "shares": [
        "IC_1"
      ],
      "percent": 10,
      "created_at": 1610067945,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 24,
      "type": "pass",
      "entity": 1972,
      "created_at": 1610067954,
      "entity_type": "player",
      "user": 1972
    },
    {
      "id": 25,
      "hex": "B16",
      "tile": "6-0",
      "type": "lay_tile",
      "entity": "MS",
      "rotation": 0,
      "created_at": 1610067963,
      "entity_type": "minor",
      "user": 3258
    },
    {
      "id": 26,
      "hex": "C13",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "MS",
      "rotation": 1,
      "created_at": 1610067967,
      "entity_type": "minor",
      "user": 3258
    },
    {
      "id": 27,
      "type": "run_routes",
      "entity": "MS",
      "routes": [
        {
          "hexes": [
            "B16",
            "C15"
          ],
          "train": "2-0",
          "revenue": 60,
          "connections": [
            [
              "C15",
              "B16"
            ]
          ],
          "revenue_str": "B16-C15"
        }
      ],
      "created_at": 1610067974,
      "entity_type": "minor",
      "user": 3258
    },
    {
      "id": 28,
      "hex": "G9",
      "tile": "5-0",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 1,
      "created_at": 1610067982,
      "entity_type": "minor",
      "user": 1001
    },
    {
      "id": 29,
      "hex": "G7",
      "tile": "6-1",
      "type": "lay_tile",
      "entity": "BIG4",
      "rotation": 2,
      "created_at": 1610067987,
      "entity_type": "minor",
      "user": 1001
    },
    {
      "id": 30,
      "type": "run_routes",
      "entity": "BIG4",
      "routes": [
        {
          "hexes": [
            "G7",
            "G9"
          ],
          "train": "2-1",
          "revenue": 40,
          "connections": [
            [
              "G9",
              "G7"
            ]
          ],
          "revenue_str": "G7-G9"
        }
      ],
      "created_at": 1610067996,
      "entity_type": "minor",
      "user": 1001
    },
    {
      "id": 31,
      "hex": "D18",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "NYC",
      "rotation": 4,
      "created_at": 1610068005,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 32,
      "hex": "E17",
      "tile": "291-0",
      "type": "lay_tile",
      "entity": "NYC",
      "rotation": 3,
      "created_at": 1610068008,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 33,
      "type": "sell_shares",
      "entity": "NYC",
      "shares": [
        "NYC_4",
        "NYC_5",
        "NYC_6"
      ],
      "percent": 30,
      "created_at": 1610068107,
      "entity_type": "corporation",
      "share_price": 50,
      "user": 1972
    },
    {
      "id": 34,
      "type": "pass",
      "entity": "NYC",
      "created_at": 1610068111,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 35,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "NYC",
      "variant": "2",
      "created_at": 1610068114,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 36,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "NYC",
      "variant": "2",
      "created_at": 1610068114,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 37,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "NYC",
      "variant": "2",
      "created_at": 1610068115,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 38,
      "type": "pass",
      "entity": "NYC",
      "created_at": 1610068117,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 39,
      "type": "pass",
      "entity": "NYC",
      "created_at": 1610068119,
      "entity_type": "corporation",
      "user": 1972
    },
    {
      "id": 40,
      "type": "sell_shares",
      "entity": "GT",
      "shares": [
        "GT_1",
        "GT_2"
      ],
      "percent": 20,
      "created_at": 1610068124,
      "entity_type": "corporation",
      "share_price": 50,
      "user": 3258
    },
    {
      "id": 41,
      "hex": "C11",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 4,
      "created_at": 1610068131,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 42,
      "hex": "D10",
      "tile": "8-2",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 1,
      "created_at": 1610068133,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 43,
      "type": "pass",
      "entity": "GT",
      "created_at": 1610068137,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 44,
      "type": "buy_train",
      "price": 80,
      "train": "2-5",
      "entity": "GT",
      "variant": "2",
      "created_at": 1610068138,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 45,
      "type": "buy_train",
      "price": 80,
      "train": "2-6",
      "entity": "GT",
      "variant": "2",
      "created_at": 1610068139,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 46,
      "type": "pass",
      "entity": "GT",
      "created_at": 1610068156,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 47,
      "type": "undo",
      "entity": "GT",
      "created_at": 1610068170,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 48,
      "type": "undo",
      "entity": "GT",
      "action_id": 39,
      "created_at": 1610068172,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 49,
      "type": "undo",
      "entity": "GT",
      "action_id": 39,
      "created_at": 1610068267,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 50,
      "type": "undo",
      "entity": "GT",
      "action_id": 39,
      "created_at": 1610068380,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 51,
      "type": "pass",
      "entity": "GT",
      "created_at": 1610068415,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 52,
      "type": "buy_train",
      "price": 80,
      "train": "2-5",
      "entity": "GT",
      "variant": "2",
      "created_at": 1610068419,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 53,
      "type": "message",
      "entity": 1001,
      "message": "Keep digging",
      "created_at": 1610068523,
      "entity_type": "player",
      "user": 1001
    },
    {
      "id": 54,
      "type": "undo",
      "entity": "GT",
      "action_id": 39,
      "created_at": 1610068556,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 55,
      "type": "buy_train",
      "price": 80,
      "train": "2-5",
      "entity": "GT",
      "variant": "2",
      "created_at": 1610068725,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 56,
      "type": "pass",
      "entity": "GT",
      "created_at": 1610068752,
      "entity_type": "corporation",
      "user": 3258
    },
    {
      "id": 57,
      "type": "pass",
      "entity": "GT",
      "created_at": 1610068758,
      "entity_type": "corporation",
      "user": 3258
    }
  ],
  "loaded": true,
  "created_at": 1610067394,
  "updated_at": 1610068758
}

**Comment by rrokkam** [comment]
Also experiencing this issue at https://18xx.games/game/18756.

Gist: https://gist.github.com/rrokkam/f4f421a0f0b41dee512e5c38f0dacda2
