### ISSUE TITLE
Restart Turn skips back to previous company’s turn

### ISSUE THREAD

**Issue by Craig1830** [tobymao/18xx#3130]
In an 18 Los Angeles game, selecting **Restart Turn** anytime during the current company’s turn (LAIR) skips back past that company’s turn and to the start of the _previous_ company’s turn (UP).

Start of LAIR’s turn:
https://18xx.games/game/19689?action=280

(iPad 5th gen, iOS 12.4.1)

**Comment by crericha** [comment]
I am able to reproduce. I think the next_turn logic needs to know more about the rounds to cover some edge cases.

**Comment by crericha** [comment]
Restart turn was removed and will be reimplemented in a different manner.
