### ISSUE TITLE
Allow user preferences for route colours to improve use for color blind users

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#314]
Suggest adding 'stroke-dasharray="4,3"' to the svg for track with non-black coloring.
This means that it also looks like a train track which is nice :)

**Comment by gchambers419** [comment]
May want to see how that interacts with how narrow gauge and dual gauge in the upcoming games.  see https://www.18xx-maker.com/tiles tile 71 thru 79 and tile thru 10u7

**Comment by gchambers419** [comment]
see https://github.com/tobymao/18xx/pull/229

**Comment by jenf** [comment]
Given we now have user preference, it should be extended to route colour selection

@yzemaze is probably best placed for this :)
