### ISSUE TITLE
[1817] Game is stuck due to GameError: Cannot lay an upgrade now

### ISSUE THREAD

**Issue by emknell** [tobymao/18xx#3140]
Note that it was reporting a different error before, but then we tried fiddling with some undos and stuff.  Doesn't seem to matter what we do.

We're sorry this game cannot be continued due to GameError: Cannot lay an upgrade now
Broken action: { "type": "lay_tile", "entity": "A&S", "entity_type": "corporation", "id": 1624, "created_at": 1610120535, "hex": "C14", "tile": "611-1", "rotation": 2 }
Please raise a bug report and include this link (https://18xx.games/game/19358?action=1624) and the following JSON data

I tried including the Game Data in this bug report, but it is too large and GitHub rejects the issue.

**Comment by tobymao** [comment]
I went to the game and it loads fine. What’s the problem?

**Comment by emknell** [comment]
Every time we try to do anything, it does this:

![image](https://user-images.githubusercontent.com/5177520/104036054-8e58df80-5198-11eb-906b-940592798480.png)

**Comment by jenf** [comment]
What are you trying to do? You can't upgrade a tile

**Comment by tobymao** [comment]
there's a nuanced issue, i'm looking at it now

**Comment by emknell** [comment]
The upgrade was legal at the time I tried it.  It upgraded the tile and then gave the error.  But even if I undo and skip the tile lay entirely, it just bombs on the next thing I try to do.

**Comment by tobymao** [comment]
fixed with ac7c6b5072f83909a38e442617ac1464b1670771
