### ISSUE TITLE
18SJ bug in the text when referring to company bonus tile lay.

### ISSUE THREAD

**Issue by willbeplayin** [tobymao/18xx#3143]
Hi,

Just had a weird bug happen in https://18xx.games/game/21671 where I laid track with my SNJ. It keeps referring to KHJ, that it's that company that gets the bonus tile lay. Or am I understanding the rules wrong here?

[00:10]SNJ lays tile #9 with rotation 2 on F25
[00:10]KHJ gets extra tile lay/upgrade as main line improvement.
[00:11]SNJ lays tile #8 with rotation 5 on E24
[00:11]SNJ skips place a token
[00:11]SNJ skips buy trains
[00:11]SNJ skips run routes
[00:11]SNJ does not run
[00:11]SNJ's share price changes from 82kr to 76kr
[00:11]KHJ gets extra tile lay/upgrade as main line improvement.

----

{
  "id": 21671,
  "description": "open async, 4+ moves a day, please",
  "user": {
    "id": 3582,
    "name": "bellynice"
  },
  "players": [
    {
      "id": 3582,
      "name": "bellynice"
    },
    {
      "id": 797,
      "name": "nigelsandwich"
    },
    {
      "id": 949,
      "name": "willbeplayin"
    },
    {
      "id": 5116,
      "name": "TimN76"
    }
  ],
  "max_players": 4,
  "title": "18SJ",
  "settings": {
    "seed": 1309183757,
    "unlisted": false,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    797
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": 3582,
      "entity_type": "player",
      "id": 1,
      "created_at": 1610118599,
      "company": "GKB",
      "price": 45
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 2,
      "created_at": 1610118616,
      "message": "gl hf"
    },
    {
      "type": "bid",
      "entity": 797,
      "entity_type": "player",
      "id": 3,
      "created_at": 1610118718,
      "company": "KHJ",
      "price": 145
    },
    {
      "type": "bid",
      "entity": 949,
      "entity_type": "player",
      "id": 4,
      "created_at": 1610118904,
      "company": "GC",
      "price": 75
    },
    {
      "type": "bid",
      "entity": 5116,
      "entity_type": "player",
      "id": 5,
      "created_at": 1610119036,
      "company": "MV",
      "price": 95
    },
    {
      "id": 6,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 5116,
      "created_at": 1610119066
    },
    {
      "id": 7,
      "type": "redo",
      "entity": 5116,
      "entity_type": "player",
      "user": 5116,
      "created_at": 1610119091
    },
    {
      "type": "bid",
      "entity": 3582,
      "entity_type": "player",
      "id": 8,
      "created_at": 1610120401,
      "company": "AEvR",
      "price": 225
    },
    {
      "type": "bid",
      "entity": 797,
      "entity_type": "player",
      "id": 9,
      "created_at": 1610121391,
      "company": "GKB",
      "price": 50
    },
    {
      "type": "bid",
      "entity": 949,
      "entity_type": "player",
      "id": 10,
      "created_at": 1610123968,
      "company": "MV",
      "price": 100
    },
    {
      "type": "bid",
      "entity": 5116,
      "entity_type": "player",
      "id": 11,
      "created_at": 1610124303,
      "company": "NOJ",
      "price": 20
    },
    {
      "type": "bid",
      "entity": 3582,
      "entity_type": "player",
      "id": 12,
      "created_at": 1610125311,
      "company": "GKB",
      "price": 55
    },
    {
      "type": "pass",
      "entity": 797,
      "entity_type": "player",
      "id": 13,
      "created_at": 1610127154
    },
    {
      "type": "bid",
      "entity": 5116,
      "entity_type": "player",
      "id": 14,
      "created_at": 1610127410,
      "company": "MV",
      "price": 120
    },
    {
      "type": "pass",
      "entity": 949,
      "entity_type": "player",
      "id": 15,
      "created_at": 1610130049
    },
    {
      "type": "par",
      "entity": 3582,
      "entity_type": "player",
      "id": 16,
      "created_at": 1610130158,
      "corporation": "ÖKJ",
      "share_price": "76,3,6"
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 17,
      "created_at": 1610130175
    },
    {
      "type": "par",
      "entity": 797,
      "entity_type": "player",
      "id": 18,
      "created_at": 1610131051,
      "corporation": "UGJ",
      "share_price": "71,4,6"
    },
    {
      "type": "par",
      "entity": 949,
      "entity_type": "player",
      "id": 19,
      "created_at": 1610132301,
      "corporation": "SNJ",
      "share_price": "82,2,6"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 20,
      "created_at": 1610132310,
      "message": "SNJ for me on my turns, thanks."
    },
    {
      "id": 21,
      "type": "par",
      "entity": 5116,
      "corporation": "KFJ",
      "entity_type": "player",
      "share_price": "71,4,6",
      "user": 5116,
      "created_at": 1610132484
    },
    {
      "id": 22,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 5116,
      "created_at": 1610132510
    },
    {
      "type": "par",
      "entity": 5116,
      "entity_type": "player",
      "id": 23,
      "created_at": 1610132513,
      "corporation": "KFJ",
      "share_price": "71,4,6"
    },
    {
      "type": "message",
      "entity": 5116,
      "entity_type": "player",
      "id": 24,
      "created_at": 1610132523,
      "message": "Autofloat kfj "
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 25,
      "created_at": 1610132841,
      "shares": [
        "ÖKJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 26,
      "created_at": 1610134037,
      "shares": [
        "UGJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 27,
      "user": 797,
      "created_at": 1610134054,
      "shares": [
        "SNJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 28,
      "user": 797,
      "created_at": 1610134058,
      "shares": [
        "KFJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 29,
      "created_at": 1610134898,
      "shares": [
        "ÖKJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 30,
      "created_at": 1610134912,
      "shares": [
        "UGJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 31,
      "user": 797,
      "created_at": 1610134916,
      "shares": [
        "SNJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 32,
      "user": 797,
      "created_at": 1610134918,
      "shares": [
        "KFJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 33,
      "created_at": 1610134952,
      "shares": [
        "ÖKJ_3"
      ],
      "percent": 10
    },
    {
      "type": "message",
      "entity": 797,
      "entity_type": "player",
      "id": 34,
      "created_at": 1610134953,
      "message": "float me ugj. thank you"
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 35,
      "created_at": 1610135193,
      "shares": [
        "UGJ_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 36,
      "user": 797,
      "created_at": 1610135196,
      "shares": [
        "SNJ_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 37,
      "user": 797,
      "created_at": 1610135200,
      "shares": [
        "KFJ_3"
      ],
      "percent": 10
    },
    {
      "id": 38,
      "type": "buy_shares",
      "entity": 3582,
      "shares": [
        "ÖKJ_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136199
    },
    {
      "id": 39,
      "type": "undo",
      "entity": 797,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136219
    },
    {
      "id": 40,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136224
    },
    {
      "id": 41,
      "type": "redo",
      "entity": 5116,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136243
    },
    {
      "id": 42,
      "type": "buy_shares",
      "entity": 3582,
      "shares": [
        "SNJ_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136272
    },
    {
      "id": 43,
      "type": "undo",
      "entity": 797,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136282
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 44,
      "created_at": 1610136286
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 45,
      "created_at": 1610137175,
      "shares": [
        "UGJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 46,
      "user": 797,
      "created_at": 1610137178,
      "shares": [
        "SNJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 47,
      "user": 797,
      "created_at": 1610137183,
      "shares": [
        "KFJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 48,
      "created_at": 1610137301,
      "shares": [
        "SNJ_5"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 49,
      "created_at": 1610137459,
      "hex": "D13",
      "tile": "7-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 50,
      "created_at": 1610137462,
      "hex": "E14",
      "tile": "8-0",
      "rotation": 0
    },
    {
      "id": 51,
      "hex": "F25",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "SNJ",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143247
    },
    {
      "id": 52,
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143258
    },
    {
      "id": 53,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143335
    },
    {
      "id": 54,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143361
    },
    {
      "id": 55,
      "hex": "F25",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "SNJ",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143383
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 56,
      "created_at": 1610143414,
      "message": "but why does KHJ get it, and not me my SNJ?"
    },
    {
      "id": 57,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143577
    },
    {
      "id": 58,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143603
    },
    {
      "id": 59,
      "type": "redo",
      "entity": "KHJ",
      "entity_type": "minor",
      "user": 949,
      "created_at": 1610143608
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 60,
      "created_at": 1610143677,
      "message": "sorry game is bugging"
    },
    {
      "type": "lay_tile",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1610143841,
      "hex": "F25",
      "tile": "9-0",
      "rotation": 2
    },
    {
      "id": 62,
      "hex": "E24",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "SNJ",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143881
    },
    {
      "id": 63,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143888
    },
    {
      "type": "lay_tile",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1610143901,
      "hex": "E24",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 65,
      "created_at": 1610143951,
      "message": "oh ok it bugs out the company name there"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 66,
      "created_at": 1610143963,
      "message": "but I did get to lay a second, when it's part of the main line"
    },
    {
      "type": "buy_train",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1610144020,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "id": 68,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "SNJ",
      "variant": "2",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144035
    },
    {
      "id": 69,
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144036
    },
    {
      "id": 70,
      "type": "undo",
      "entity": "UGJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144046
    },
    {
      "id": 71,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144047
    },
    {
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1610144048
    }
  ],
  "loaded": true,
  "created_at": 1610113248,
  "updated_at": 1610144048
}

**Comment by perwestling** [comment]
I can see that the 2nd tile lay of KHJ was illegal - the first OR tile lays for KHJ did not improve main line.
So it seems this check is buggy. I will try to correct this but it will probably delete this game.
And I will try to correct log message.
![image](https://user-images.githubusercontent.com/2631151/104089387-de09da80-526e-11eb-8c0e-7d86cba6c77d.png)

**Comment by perwestling** [comment]
This should now be fixed. But the bug that was fixed probably break the game where incorrect tile laying was done.
Will be deployed soon.
