### ISSUE TITLE
[1867] Game is charging loan interest on loans taken to lay track or pay interest in the OR they were taken.

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3145]
The game is charging interest when paying off a loan taken to build track in the same round. edit 2: or pay interest.
GTG rule: 
__8.10. Loan__
__Paying loan interest:__ $5 interest must be paid for each
loan taken on a _previous_ operating turn.
(emphasis mine)

A-A Games (1861 rules, as I have the expansion, not the full game):
A Company or the Russian State Railway which started
its operating turn with one or more loans must pay R5
interest on each one. Loans acquired during the turn have
already had their interest paid.

Here's the json of a quick game with garbage moves to demonstrate.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1610146059,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1610146061
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1610146062
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "created_at": 1610146063,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5,
      "created_at": 1610146064
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "created_at": 1610146064
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1610146065,
      "company": "MB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "created_at": 1610146066
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "created_at": 1610146066
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "created_at": 1610146067,
      "company": "QB",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "created_at": 1610146068
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "created_at": 1610146069
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "created_at": 1610146070,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14,
      "created_at": 1610146071
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "created_at": 1610146071
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "created_at": 1610146085,
      "corporation": "BO",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 17,
      "created_at": 1610146091,
      "city": "F8-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 18,
      "created_at": 1610146095
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19,
      "created_at": 1610146095
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "created_at": 1610146098,
      "corporation": "CS",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 21,
      "created_at": 1610146100,
      "city": "D8-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 22,
      "created_at": 1610146103
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 23,
      "created_at": 1610146104
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24,
      "created_at": 1610146107,
      "corporation": "CV",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 25,
      "created_at": 1610146110,
      "city": "E13-2-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 26,
      "created_at": 1610146116
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 27,
      "created_at": 1610146117
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "created_at": 1610146121
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "created_at": 1610146121
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30,
      "created_at": 1610146121
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 31,
      "created_at": 1610146128,
      "hex": "F8",
      "tile": "57-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 32,
      "created_at": 1610146132,
      "hex": "F6",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 33,
      "created_at": 1610146137,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 34,
      "created_at": 1610146147,
      "hex": "D8",
      "tile": "57-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1610146152,
      "hex": "E9",
      "tile": "9-1",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 36,
      "created_at": 1610146155,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 37,
      "created_at": 1610146159
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 38,
      "created_at": 1610146171,
      "hex": "E13",
      "tile": "6-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1610146176,
      "hex": "E15",
      "tile": "6-1",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 40,
      "created_at": 1610146181,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 41,
      "created_at": 1610146185
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 42,
      "created_at": 1610146200,
      "hex": "F4",
      "tile": "7-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1610146210,
      "hex": "E5",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1610146246,
      "hex": "F10",
      "tile": "9-3",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1610146248,
      "hex": "G11",
      "tile": "9-4",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1610146257,
      "hex": "D16",
      "tile": "621-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1610146263
    },
    {
      "type": "run_routes",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 48,
      "created_at": 1610146271,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E13",
              "E15"
            ]
          ],
          "hexes": [
            "E15",
            "E13"
          ],
          "revenue": 40,
          "revenue_str": "E15-E13"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1610146279
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 50,
      "created_at": 1610146282
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 51,
      "created_at": 1610146282
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 52,
      "created_at": 1610146283
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1610146313,
      "hex": "F12",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1610146316,
      "hex": "G13",
      "tile": "8-1",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1610146320,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E13",
              "E15"
            ]
          ],
          "hexes": [
            "E13",
            "E15"
          ],
          "revenue": 40,
          "revenue_str": "E13-E15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 56,
      "created_at": 1610146345
    },
    {
      "type": "lay_tile",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 57,
      "created_at": 1610146356,
      "hex": "D6",
      "tile": "9-5",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1610146360
    }
  ],
  "id": "hs_htksvxgg_1610146056",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-08",
  "loaded": true,
  "result": {},
  "turn": 2,
  "round": "Operating Round",
  "acting": [
    "Player 3"
  ],
  "updated_at": 1610146360
}

**Comment by jenf** [comment]
sigh, what a complication :(
