### ISSUE TITLE
1867: 8 train exported, trainless major not asked immediately about nationalisation

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#3152]
An 8-train was exported at the end of OR5.1, a minor was nationalised and 4-trains rusted. IC (a major) was trainless, but wasn't asked about nationalisation until it ran in the next OR.
In this case it didn't matter, since it ran first in OR5.2, but if there is a SR next - and the answer is yes - it would affect the players cash going into the SR.

https://18xx.games/game/21737?action=557

**Comment by jenf** [comment]
No, it is immediate, but sometimes the logging goes a bit funky due to the interrupts.
