### ISSUE TITLE
18SJ game ID 21671?action=145 broken, anything that can be done or do we just end it?

### ISSUE THREAD

**Issue by willbeplayin** [tobymao/18xx#3170]
"We're sorry this game cannot be continued due to GameError: Blocking step Buy Companies cannot process action 145
Broken action: { "type": "pass", "entity": "KFJ", "entity_type": "corporation", "id": 145, "created_at": 1610215437 }
Please raise a bug report and include this link (https://18xx.games/game/21671?action=145) and the following JSON data"

18SJ: Operating Round 2.1 (of 1) - Buy Companies - Pinned to Version: 91073a45

{
  "id": 21671,
  "description": "open async, 4+ moves a day, please",
  "user": {
    "id": 3582,
    "name": "bellynice"
  },
  "players": [
    {
      "id": 3582,
      "name": "bellynice"
    },
    {
      "id": 797,
      "name": "nigelsandwich"
    },
    {
      "id": 949,
      "name": "willbeplayin"
    },
    {
      "id": 5116,
      "name": "TimN76"
    }
  ],
  "max_players": 4,
  "title": "18SJ",
  "settings": {
    "pin": "91073a45",
    "seed": 1309183757,
    "unlisted": false,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 3,
  "round": "Stock Round",
  "acting": [
    797
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": 3582,
      "entity_type": "player",
      "id": 1,
      "created_at": 1610118599,
      "company": "GKB",
      "price": 45
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 2,
      "created_at": 1610118616,
      "message": "gl hf"
    },
    {
      "type": "bid",
      "entity": 797,
      "entity_type": "player",
      "id": 3,
      "created_at": 1610118718,
      "company": "KHJ",
      "price": 145
    },
    {
      "type": "bid",
      "entity": 949,
      "entity_type": "player",
      "id": 4,
      "created_at": 1610118904,
      "company": "GC",
      "price": 75
    },
    {
      "type": "bid",
      "entity": 5116,
      "entity_type": "player",
      "id": 5,
      "created_at": 1610119036,
      "company": "MV",
      "price": 95
    },
    {
      "id": 6,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 5116,
      "created_at": 1610119066
    },
    {
      "id": 7,
      "type": "redo",
      "entity": 5116,
      "entity_type": "player",
      "user": 5116,
      "created_at": 1610119091
    },
    {
      "type": "bid",
      "entity": 3582,
      "entity_type": "player",
      "id": 8,
      "created_at": 1610120401,
      "company": "AEvR",
      "price": 225
    },
    {
      "type": "bid",
      "entity": 797,
      "entity_type": "player",
      "id": 9,
      "created_at": 1610121391,
      "company": "GKB",
      "price": 50
    },
    {
      "type": "bid",
      "entity": 949,
      "entity_type": "player",
      "id": 10,
      "created_at": 1610123968,
      "company": "MV",
      "price": 100
    },
    {
      "type": "bid",
      "entity": 5116,
      "entity_type": "player",
      "id": 11,
      "created_at": 1610124303,
      "company": "NOJ",
      "price": 20
    },
    {
      "type": "bid",
      "entity": 3582,
      "entity_type": "player",
      "id": 12,
      "created_at": 1610125311,
      "company": "GKB",
      "price": 55
    },
    {
      "type": "pass",
      "entity": 797,
      "entity_type": "player",
      "id": 13,
      "created_at": 1610127154
    },
    {
      "type": "bid",
      "entity": 5116,
      "entity_type": "player",
      "id": 14,
      "created_at": 1610127410,
      "company": "MV",
      "price": 120
    },
    {
      "type": "pass",
      "entity": 949,
      "entity_type": "player",
      "id": 15,
      "created_at": 1610130049
    },
    {
      "type": "par",
      "entity": 3582,
      "entity_type": "player",
      "id": 16,
      "created_at": 1610130158,
      "corporation": "ÖKJ",
      "share_price": "76,3,6"
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 17,
      "created_at": 1610130175
    },
    {
      "type": "par",
      "entity": 797,
      "entity_type": "player",
      "id": 18,
      "created_at": 1610131051,
      "corporation": "UGJ",
      "share_price": "71,4,6"
    },
    {
      "type": "par",
      "entity": 949,
      "entity_type": "player",
      "id": 19,
      "created_at": 1610132301,
      "corporation": "SNJ",
      "share_price": "82,2,6"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 20,
      "created_at": 1610132310,
      "message": "SNJ for me on my turns, thanks."
    },
    {
      "id": 21,
      "type": "par",
      "entity": 5116,
      "corporation": "KFJ",
      "entity_type": "player",
      "share_price": "71,4,6",
      "user": 5116,
      "created_at": 1610132484
    },
    {
      "id": 22,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 5116,
      "created_at": 1610132510
    },
    {
      "type": "par",
      "entity": 5116,
      "entity_type": "player",
      "id": 23,
      "created_at": 1610132513,
      "corporation": "KFJ",
      "share_price": "71,4,6"
    },
    {
      "type": "message",
      "entity": 5116,
      "entity_type": "player",
      "id": 24,
      "created_at": 1610132523,
      "message": "Autofloat kfj "
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 25,
      "created_at": 1610132841,
      "shares": [
        "ÖKJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 26,
      "created_at": 1610134037,
      "shares": [
        "UGJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 27,
      "user": 797,
      "created_at": 1610134054,
      "shares": [
        "SNJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 28,
      "user": 797,
      "created_at": 1610134058,
      "shares": [
        "KFJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 29,
      "created_at": 1610134898,
      "shares": [
        "ÖKJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 30,
      "created_at": 1610134912,
      "shares": [
        "UGJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 31,
      "user": 797,
      "created_at": 1610134916,
      "shares": [
        "SNJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 32,
      "user": 797,
      "created_at": 1610134918,
      "shares": [
        "KFJ_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 33,
      "created_at": 1610134952,
      "shares": [
        "ÖKJ_3"
      ],
      "percent": 10
    },
    {
      "type": "message",
      "entity": 797,
      "entity_type": "player",
      "id": 34,
      "created_at": 1610134953,
      "message": "float me ugj. thank you"
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 35,
      "created_at": 1610135193,
      "shares": [
        "UGJ_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 36,
      "user": 797,
      "created_at": 1610135196,
      "shares": [
        "SNJ_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 37,
      "user": 797,
      "created_at": 1610135200,
      "shares": [
        "KFJ_3"
      ],
      "percent": 10
    },
    {
      "id": 38,
      "type": "buy_shares",
      "entity": 3582,
      "shares": [
        "ÖKJ_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136199
    },
    {
      "id": 39,
      "type": "undo",
      "entity": 797,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136219
    },
    {
      "id": 40,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136224
    },
    {
      "id": 41,
      "type": "redo",
      "entity": 5116,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136243
    },
    {
      "id": 42,
      "type": "buy_shares",
      "entity": 3582,
      "shares": [
        "SNJ_4"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136272
    },
    {
      "id": 43,
      "type": "undo",
      "entity": 797,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610136282
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 44,
      "created_at": 1610136286
    },
    {
      "type": "buy_shares",
      "entity": 797,
      "entity_type": "player",
      "id": 45,
      "created_at": 1610137175,
      "shares": [
        "UGJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 46,
      "user": 797,
      "created_at": 1610137178,
      "shares": [
        "SNJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 5116,
      "entity_type": "player",
      "id": 47,
      "user": 797,
      "created_at": 1610137183,
      "shares": [
        "KFJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 48,
      "created_at": 1610137301,
      "shares": [
        "SNJ_5"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 49,
      "created_at": 1610137459,
      "hex": "D13",
      "tile": "7-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 50,
      "created_at": 1610137462,
      "hex": "E14",
      "tile": "8-0",
      "rotation": 0
    },
    {
      "id": 51,
      "hex": "F25",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "SNJ",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143247
    },
    {
      "id": 52,
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143258
    },
    {
      "id": 53,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143335
    },
    {
      "id": 54,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143361
    },
    {
      "id": 55,
      "hex": "F25",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "SNJ",
      "rotation": 2,
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143383
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 56,
      "created_at": 1610143414,
      "message": "but why does KHJ get it, and not me my SNJ?"
    },
    {
      "id": 57,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143577
    },
    {
      "id": 58,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143603
    },
    {
      "id": 59,
      "type": "redo",
      "entity": "KHJ",
      "entity_type": "minor",
      "user": 949,
      "created_at": 1610143608
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 60,
      "created_at": 1610143677,
      "message": "sorry game is bugging"
    },
    {
      "type": "lay_tile",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1610143841,
      "hex": "F25",
      "tile": "9-0",
      "rotation": 2
    },
    {
      "id": 62,
      "hex": "E24",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "SNJ",
      "rotation": 5,
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143881
    },
    {
      "id": 63,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610143888
    },
    {
      "type": "lay_tile",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1610143901,
      "hex": "E24",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 65,
      "created_at": 1610143951,
      "message": "oh ok it bugs out the company name there"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 66,
      "created_at": 1610143963,
      "message": "but I did get to lay a second, when it's part of the main line"
    },
    {
      "type": "buy_train",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1610144020,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "id": 68,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "SNJ",
      "variant": "2",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144035
    },
    {
      "id": 69,
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144036
    },
    {
      "id": 70,
      "type": "undo",
      "entity": "UGJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144046
    },
    {
      "id": 71,
      "type": "undo",
      "entity": "SNJ",
      "entity_type": "corporation",
      "user": 949,
      "created_at": 1610144047
    },
    {
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1610144048
    },
    {
      "type": "lay_tile",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 73,
      "created_at": 1610144333,
      "hex": "F13",
      "tile": "57-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1610144336,
      "hex": "G12",
      "tile": "8-2",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 75,
      "created_at": 1610144346,
      "city": "G10-0-3",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 76,
      "created_at": 1610144364,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 77,
      "created_at": 1610144370,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 78,
      "created_at": 1610144372
    },
    {
      "type": "lay_tile",
      "entity": "KFJ",
      "entity_type": "corporation",
      "id": 79,
      "created_at": 1610144531,
      "hex": "C16",
      "tile": "5-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "KFJ",
      "entity_type": "corporation",
      "id": 80,
      "created_at": 1610144569
    },
    {
      "type": "pass",
      "entity": "KFJ",
      "entity_type": "corporation",
      "id": 81,
      "created_at": 1610144573
    },
    {
      "type": "message",
      "entity": 5116,
      "entity_type": "player",
      "id": 82,
      "created_at": 1610144587,
      "message": "Autopass"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 83,
      "created_at": 1610144631,
      "message": "pass for me thanks"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 84,
      "created_at": 1610145140,
      "message": "actually no, dont"
    },
    {
      "type": "pass",
      "entity": 797,
      "entity_type": "player",
      "id": 85,
      "created_at": 1610145216
    },
    {
      "type": "sell_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 86,
      "created_at": 1610145299,
      "shares": [
        "SNJ_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 87,
      "created_at": 1610145302,
      "shares": [
        "ÖKJ_4"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": 949,
      "entity_type": "player",
      "id": 88,
      "created_at": 1610145312
    },
    {
      "type": "pass",
      "entity": 5116,
      "entity_type": "player",
      "id": 89,
      "user": 949,
      "created_at": 1610145383
    },
    {
      "type": "sell_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 90,
      "created_at": 1610145538,
      "shares": [
        "ÖKJ_1"
      ],
      "percent": 10
    },
    {
      "id": 91,
      "type": "buy_shares",
      "entity": 3582,
      "shares": [
        "UGJ_5"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610145544
    },
    {
      "id": 92,
      "type": "sell_shares",
      "entity": 3582,
      "shares": [
        "SNJ_5"
      ],
      "percent": 10,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610145636
    },
    {
      "id": 93,
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610145781
    },
    {
      "id": 94,
      "type": "undo",
      "entity": 797,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610145846
    },
    {
      "id": 95,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610145940
    },
    {
      "id": 96,
      "type": "undo",
      "entity": 3582,
      "entity_type": "player",
      "user": 3582,
      "created_at": 1610145949
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 97,
      "created_at": 1610145957,
      "shares": [
        "KFJ_5"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 98,
      "created_at": 1610145962,
      "shares": [
        "KFJ_5"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 99,
      "created_at": 1610145973,
      "shares": [
        "SNJ_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 100,
      "created_at": 1610146029
    },
    {
      "type": "pass",
      "entity": 797,
      "entity_type": "player",
      "id": 101,
      "created_at": 1610147031
    },
    {
      "type": "sell_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 102,
      "created_at": 1610147655,
      "shares": [
        "ÖKJ_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 949,
      "entity_type": "player",
      "id": 103,
      "created_at": 1610147664,
      "shares": [
        "UGJ_5"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": 949,
      "entity_type": "player",
      "id": 104,
      "created_at": 1610147666
    },
    {
      "type": "pass",
      "entity": 5116,
      "entity_type": "player",
      "id": 105,
      "created_at": 1610148098
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 106,
      "created_at": 1610148364,
      "shares": [
        "UGJ_6"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 107,
      "created_at": 1610148388
    },
    {
      "type": "pass",
      "entity": 797,
      "entity_type": "player",
      "id": 108,
      "created_at": 1610148567
    },
    {
      "type": "pass",
      "entity": 949,
      "entity_type": "player",
      "id": 109,
      "created_at": 1610149477
    },
    {
      "type": "pass",
      "entity": 5116,
      "entity_type": "player",
      "id": 110,
      "created_at": 1610151187
    },
    {
      "type": "buy_shares",
      "entity": 3582,
      "entity_type": "player",
      "id": 111,
      "created_at": 1610164097,
      "shares": [
        "UGJ_7"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 112,
      "created_at": 1610164110
    },
    {
      "type": "pass",
      "entity": 797,
      "entity_type": "player",
      "id": 113,
      "created_at": 1610164169
    },
    {
      "type": "pass",
      "entity": 949,
      "entity_type": "player",
      "id": 114,
      "created_at": 1610164678
    },
    {
      "type": "pass",
      "entity": 5116,
      "entity_type": "player",
      "id": 115,
      "created_at": 1610174315
    },
    {
      "type": "pass",
      "entity": 3582,
      "entity_type": "player",
      "id": 116,
      "created_at": 1610188051
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 117,
      "created_at": 1610199357,
      "message": "O-ou. \"I can see that the 2nd tile lay of KHJ was illegal - the first OR tile lays for KHJ did not improve main line. So it seems this check is buggy. I will try to correct this but it will probably delete this game. And I will try to correct log message.\""
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 118,
      "created_at": 1610199384,
      "message": "so maybe revert back to original KFJ turn? :D"
    },
    {
      "type": "message",
      "entity": 949,
      "entity_type": "player",
      "id": 119,
      "created_at": 1610199390,
      "message": "or start a new one I dont know"
    },
    {
      "type": "message",
      "entity": 797,
      "entity_type": "player",
      "id": 120,
      "created_at": 1610210928,
      "message": "It doesn’t matter either way to me. If it’s just going to be deleted we can just play til that happens. I’m still pretty clueless on how this one works"
    },
    {
      "type": "lay_tile",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 121,
      "created_at": 1610210950,
      "hex": "E16",
      "tile": "8-3",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 122,
      "created_at": 1610210956
    },
    {
      "type": "run_routes",
      "entity": "KHJ",
      "entity_type": "minor",
      "id": 123,
      "created_at": 1610210962,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "D15",
              "D13",
              "E14",
              "F13"
            ]
          ],
          "hexes": [
            "F13",
            "D15"
          ],
          "revenue": 40,
          "revenue_str": "F13-D15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "ÖKJ",
      "entity_type": "corporation",
      "id": 124,
      "created_at": 1610212361
    },
    {
      "type": "lay_tile",
      "entity": "ÖKJ",
      "entity_type": "corporation",
      "id": 125,
      "created_at": 1610212375,
      "hex": "C12",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "ÖKJ",
      "entity_type": "corporation",
      "id": 126,
      "created_at": 1610212393
    },
    {
      "type": "buy_train",
      "entity": "ÖKJ",
      "entity_type": "corporation",
      "id": 127,
      "created_at": 1610212397,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "ÖKJ",
      "entity_type": "corporation",
      "id": 128,
      "created_at": 1610212400
    },
    {
      "type": "pass",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 129,
      "created_at": 1610212429
    },
    {
      "type": "run_routes",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 130,
      "created_at": 1610212439,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F13",
              "E14",
              "D13",
              "D15"
            ]
          ],
          "hexes": [
            "D15",
            "F13"
          ],
          "revenue": 40,
          "revenue_str": "D15-F13"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "F13",
              "G12",
              "G10"
            ]
          ],
          "hexes": [
            "G10",
            "F13"
          ],
          "revenue": 40,
          "revenue_str": "G10-F13"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 131,
      "created_at": 1610212440,
      "kind": "payout"
    },
    {
      "id": 132,
      "type": "buy_train",
      "price": 80,
      "train": "2-5",
      "entity": "UGJ",
      "variant": "2",
      "entity_type": "corporation",
      "user": 797,
      "created_at": 1610212458
    },
    {
      "id": 133,
      "type": "undo",
      "entity": "UGJ",
      "entity_type": "corporation",
      "user": 797,
      "created_at": 1610212460
    },
    {
      "type": "pass",
      "entity": "UGJ",
      "entity_type": "corporation",
      "id": 134,
      "created_at": 1610212461
    },
    {
      "type": "pass",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 135,
      "created_at": 1610214235
    },
    {
      "type": "lay_tile",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 136,
      "created_at": 1610214238,
      "hex": "E22",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 137,
      "created_at": 1610214244,
      "hex": "E20",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "place_token",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 138,
      "created_at": 1610214245,
      "city": "6-1-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 139,
      "created_at": 1610214255,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G26",
              "F25",
              "E24",
              "E22",
              "E20"
            ]
          ],
          "hexes": [
            "E20",
            "G26"
          ],
          "revenue": 40,
          "revenue_str": "E20-G26"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 140,
      "created_at": 1610214259,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 141,
      "created_at": 1610214324,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 142,
      "created_at": 1610214324,
      "train": "2-6",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 143,
      "created_at": 1610214325,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_company",
      "entity": "SNJ",
      "entity_type": "corporation",
      "id": 144,
      "created_at": 1610214342,
      "company": "GC",
      "price": 125
    }
  ],
  "loaded": true,
  "created_at": 1610113248,
  "updated_at": 1610222332
}

**Comment by perwestling** [comment]
I think it is not salvagable. I can delete it if you want, but otherwise I suggest ending it if possible,

**Comment by willbeplayin** [comment]
I can't end it even with master controls, it won't allow any new actions so could you delete it, thanks! :)

**Comment by perwestling** [comment]
@willbeplayin It seems that the owner (creator) of the game is the one that can delete the game. Can you check with the owner?

**Comment by willbeplayin** [comment]
Yes, they said that they can't delete it either. :D
