### ISSUE TITLE
1849 Error When AFG is the RSA Company

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#3175]
Error when it tries to par.

**Comment by Maxwell-Frank** [comment]
This also ocurred in a hot seat game I just created: 

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1610242093,
      "company": "SCE",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1610242094,
      "company": "SIGI",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1610242095,
      "company": "CNM",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "created_at": 1610242097,
      "company": "SMS",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "created_at": 1610242098,
      "company": "RSA",
      "price": 150
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "created_at": 1610242123
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 7,
      "created_at": 1610242128,
      "company": "RSA",
      "price": 150
    }
  ],
  "id": "hs_uraeogbk_1610242091",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1849",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-09",
  "loaded": true,
  "result": {},
  "turn": 1,
  "round": "Auction Round",
  "acting": [
    "Player 2"
  ],
  "updated_at": 1610242128
}

**Comment by tysen** [comment]
This one's tricky. Working on it.
