### ISSUE TITLE
[1849] Shares Must be Sold in Stock Price Order

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3176]
Rule 9.2.3: 
> When stock in more than one corporation is sold, the banker moves the stock market token of the corporations whose stock
has been sold in current market value order. This means that if three shares are being sold (in corporations A, B, and C) and they are all on currently the same price (with A on top and C at the bottom of the stack), after the sale the order of the stack remains unchanged.

The current implementation does not seem to enforce this.  

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1610242207,
      "company": "SCE",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1610242208,
      "company": "SIGI",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1610242209,
      "company": "CNM",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "created_at": 1610242211,
      "company": "SMS",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "created_at": 1610242213,
      "company": "RSA",
      "price": 150
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "created_at": 1610242214,
      "corporation": "ATA",
      "share_price": "100,3,5"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1610242219,
      "shares": [
        "ATA_1"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "created_at": 1610242223
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "created_at": 1610242228,
      "corporation": "AFG",
      "share_price": "68,4,2"
    },
    {
      "type": "place_token",
      "entity": "AFG",
      "entity_type": "corporation",
      "id": 10,
      "created_at": 1610242231,
      "city": "B14-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 11,
      "created_at": 1610242243
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "created_at": 1610242251,
      "corporation": "SFA",
      "share_price": "68,4,2"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13,
      "created_at": 1610242253
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14,
      "created_at": 1610242261,
      "shares": [
        "ATA_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15,
      "created_at": 1610242262
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 16,
      "created_at": 1610242265
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 17,
      "created_at": 1610242266
    },
    {
      "type": "lay_tile",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 18,
      "created_at": 1610242271,
      "hex": "L12",
      "tile": "78-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 19,
      "created_at": 1610242273
    },
    {
      "type": "buy_train",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 20,
      "created_at": 1610242274,
      "train": "4H-0",
      "price": 100,
      "variant": "4H"
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 21,
      "created_at": 1610242276
    },
    {
      "type": "lay_tile",
      "entity": "AFG",
      "entity_type": "corporation",
      "id": 22,
      "created_at": 1610242280,
      "hex": "D14",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "AFG",
      "entity_type": "corporation",
      "id": 23,
      "created_at": 1610242282,
      "train": "4H-1",
      "price": 100,
      "variant": "4H"
    },
    {
      "type": "pass",
      "entity": "SFA",
      "entity_type": "corporation",
      "id": 24,
      "created_at": 1610242283
    },
    {
      "type": "undo",
      "entity": "SFA",
      "entity_type": "corporation",
      "id": 25,
      "created_at": 1610242286
    },
    {
      "type": "lay_tile",
      "entity": "SFA",
      "entity_type": "corporation",
      "id": 26,
      "created_at": 1610242296,
      "hex": "J6",
      "tile": "657-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "SFA",
      "entity_type": "corporation",
      "id": 27,
      "created_at": 1610242302
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "created_at": 1610242314,
      "shares": [
        "SFA_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "created_at": 1610242315
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30,
      "created_at": 1610242315
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "created_at": 1610242317,
      "shares": [
        "AFG_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32,
      "created_at": 1610242319
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "created_at": 1610242320
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 34,
      "created_at": 1610242326,
      "shares": [
        "SFA_1"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 35,
      "created_at": 1610242329,
      "shares": [
        "AFG_1"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 36,
      "created_at": 1610242338
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37,
      "created_at": 1610242339
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 38,
      "created_at": 1610242346,
      "shares": [
        "SFA_1"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 39,
      "created_at": 1610242348,
      "shares": [
        "AFG_1"
      ],
      "percent": 10
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 40,
      "created_at": 1610242420
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 41,
      "created_at": 1610242421
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 42,
      "created_at": 1610242427,
      "shares": [
        "SFA_1"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 43,
      "created_at": 1610242428,
      "shares": [
        "AFG_1"
      ],
      "percent": 10
    }
  ],
  "id": "hs_ingryotb_1610242204",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1849",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-09",
  "loaded": true,
  "result": {},
  "turn": 2,
  "round": "Stock Round",
  "acting": [
    "Player 3"
  ],
  "updated_at": 1610242428
}

**Comment by tysen** [comment]
The only effect of this is that shares that end up in the same spot on the stock market after a set of sales have to maintain their relative ordering prior to the sales. That's enforced. It would be onerous to implement it as the rules described.

**Comment by Maxwell-Frank** [comment]
This is only enforced when a player passes and finishes their stock turn.  I missed that in the above example.
