### ISSUE TITLE
[1849] Error Message When trying to buy a share

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3177]
https://18xx.games/game/21925?action=53

Mark Derrick tries to by a share of RCS and we receive an error message the size of the Gutenberg bible in a giant pink window. 

Something is wrong...

**Comment by tysen** [comment]
What's the error? I cloned that game and bought an RCS share just fine.

**Comment by Maxwell-Frank** [comment]
It happened again here: https://18xx.games/game/21930?action=38

**Comment by Maxwell-Frank** [comment]
Couldn't snag a copy-paste before it cleared, but here's a screenshot: 
![Error Message](https://user-images.githubusercontent.com/75334833/104113926-33240b80-52c4-11eb-85d1-fdf848d57626.png)

**Comment by tysen** [comment]
Thanks @Maxwell-Frank, that's helpful. Will submit a fix soon.
