### ISSUE TITLE
1849: Train miscalculation 

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#3180]
![864B278C-829B-46ED-B20A-987C643C5A28](https://user-images.githubusercontent.com/69050942/104114994-65545e00-5302-11eb-9b4a-2514bf477d3a.png)
![BEDDE316-4D52-4D51-8038-5D475396CDBE](https://user-images.githubusercontent.com/69050942/104114995-684f4e80-5302-11eb-9397-e43f827d387d.jpeg)

Can include JSON data as well if required. 6H train showing error - can’t run across 8 hex edges but is only running over 5

**Comment by tysen** [comment]
What's the game ID?

**Comment by Blobbley** [comment]
Track was small gauge. Sorry
