### ISSUE TITLE
[1817x] Add loan schedule

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#3186]
Add to the info tab a way to visualise the loan tokens.

This is more or less straight forward in 1817, but in 1817NA and 1817WO it's messier. It becomes hard to calculate the interest rate when there is a corp with 10 loans in liquidation in 1817WO

**Comment by jenf** [comment]
I'm a little confused about what this request is. Could you elaborate

**Comment by jenf** [comment]
Externally discussed but this means showing something more concreate to allow it to be easier to calculate how many loans until a further amount like the original loans board.
![image](https://user-images.githubusercontent.com/71923/105093619-f366dc00-5a9a-11eb-98b5-b4fc8f7e704f.png)

This would probably be shown, but stored in an expandable area

**Comment by daniel-sousa-me** [comment]
I'm sorry, I forgot to write that here.

For reference, this is how rr18xx shows it: 
![image](https://user-images.githubusercontent.com/3337865/105846694-7379ce00-5fd4-11eb-863d-a5fffca18d36.png)
