### ISSUE TITLE
[18MS] Can't buy any D train even though first 6-train is bought

### ISSUE THREAD

**Issue by whytestone** [tobymao/18xx#3192]
In game https://18xx.games/game/21084
L&N has $810 but it only get a buy button for the last 6 train (1 left out of 2). The rules says:
 "after the first 6-train has been purchased, all of the remaining trains (the other 6-train, the 4D/2D-trains, and the 5D-train) become available immediately. A company with sufficient funds could therefore purchase the first 6-train, and then the 5D-train."

They only cost $550, $500 and $750 and the company only has three trains so that is not the problem (train limit is 3 and since it can buy a 6-train).

**Comment by whytestone** [comment]
Something isn't right. Out in the menue of all games available it says Operating 3. But we are in operating round 6 and this is what the heading says when you open the game.
If I go to Spreadsheet I only see (the bottom left) stats for operating rounds 1-3 with 1.1, 1.2, 2.1, 2.2 etch but these are in fact 1, 2, 3, 4, 5 as it says in the upper right stats. I don't know if that has anything to do with it.

**Comment by perwestling** [comment]
I believe the presentation error in the spreadsheet is a separate issue, and not connected to the D problem.
So I have created a new issue for that, #3194

**Comment by perwestling** [comment]
Created an issue for front page as well, #3200

**Comment by perwestling** [comment]
This is a problem with the phase change on 18MS. Still need to figure out how to fix it.
