### ISSUE TITLE
1817NA: Running to Blue Offboard requires 100T

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#3193]
On second thought, let's not go to the beach.  'Tis a silly place.

https://18xx.games/game/19811?action=775

Running from Mexico City to Guadalajara: 2 stops.
Running from Mexico City to Guadalajara to The Sea: 101 stops.

I don't think math works like that.

![image](https://user-images.githubusercontent.com/68389380/104129904-dfe9a180-5333-11eb-85d5-84d9f2d01591.png)

**Comment by scottredracecar** [comment]
Yeah, probably don't go to the beach.

**Comment by jenf** [comment]
The bug seems to be 'The wrong error message' appears

**Comment by jenf** [comment]
Don't go to the sea, won't fix
