### ISSUE TITLE
1849: Cannot buy IPO share

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#3197]
Hot seat game of 1849: https://gofile.io/d/urYnX8

Player 3 cannot buy any shares despite being below share limit.

If player 3 passes, player "Me" buy, player 2 passes, now player 3 can buy shares.

So there seem to be some kind of bug here.

**Comment by tysen** [comment]
Is this still broken? I don't think I fixed it but it appears to be working now.

**Comment by perwestling** [comment]
@tysen I just now imported the game from the link above on the production site
Then Player 3 clicks on IFT, AFT, ATA it only has Sell options.
It looks like the game still think it is Player 2's turn, as Player 2 is stock locked.

**Comment by tysen** [comment]
This is fixed now. Can close.
