### ISSUE TITLE
1860 - run trains - halts/minors does not seem to be handled correctly

### ISSUE THREAD

**Issue by dagibbs** [tobymao/18xx#3199]
The rules seem to allow for selecting any combination of whistle-stops or halts when running a training (as long as the route does not end at a halt), including, "IMPORTANT NOTE: The company director is not duty bound to run trains to generate the highest possible dividend! Indeed, the director may choose to generate a less than maximum dividend and instead generate more company revenue by visiting more halts."

But, the in-game interface seems to force one to pick the first whistle-stops/halts one encounters, rather than giving the flexibility that the rules allow.  (We saw this in https://18xx.games/game/21177 )

We also a run with a 3+2 train where it traversed many halts -- but the game only calculated/added +10 to the company treasure rather than +20.

**Comment by roseundy** [comment]
Hmmm. You should be able to cycle through the number of halts used (and therefore towns ignored) by clicking on the button showing the halt subsidy for each train. Was that not working?

**Comment by roseundy** [comment]
In your game, I was able to select 2 halts on your 3+2 train, by clicking that button:
![Subsidy](https://user-images.githubusercontent.com/8494213/104132037-ff82c900-5337-11eb-8665-85005e4b1ee1.PNG)

**Comment by dagibbs** [comment]
I'll try that... it didn't seem obvious.

**Comment by roseundy** [comment]
It's right there in the help text under "Select Routes"

**Comment by dagibbs** [comment]
Verified, is fine.  ID10T/PEBKAC issue.
