### ISSUE TITLE
1860 sort corporations owned by the bank in layer order

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3205]
subject says it all

**Comment by roseundy** [comment]
What view?

**Comment by ChrisTheCat** [comment]
Entities

**Comment by ChrisTheCat** [comment]
and it would be nice to have the layer be a sortable column in the spreadsheet. There's a similar request for corporation size to be a sortable column in the spreadsheet for 1817 and 1861/67 games.
