### ISSUE TITLE
1860 default for halts

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3208]
https://18xx.games/game/22068?action=240

The FYN runs for 90 revenue plus up to 2 halts. The system defaults to L90 + L10. It should most definitely default to L90 + L20. There's almost no circumstance where it would make sense to run for L90 + L0 or L90 + L10 in this situation.

Also, the interface doesn't entirely make clear what is going on here. The L10 button and the +L10 indicator in the Submit button don't show that those values will be paid to treasury. It would be nice if there was more information to show that this money is headed to the treasury and won't be part of the dividend.

<img width="372" alt="Screen Shot 2021-01-10 at 2 17 21 PM" src="https://user-images.githubusercontent.com/8732435/104137094-3adcc200-534f-11eb-914a-724c266b93e2.png">

**Comment by ChrisTheCat** [comment]
Also, at this step, there's no indication how much subsidy will go to the company:

<img width="995" alt="Screen Shot 2021-01-10 at 2 34 11 PM" src="https://user-images.githubusercontent.com/8732435/104137371-fb16da00-5350-11eb-9db9-a91b6b319e82.png">

**Comment by ChrisTheCat** [comment]
At this step, it makes it more clear that L20 will go to the treasury, which is the subsidy.

<img width="995" alt="Screen Shot 2021-01-10 at 2 34 11 PM" src="https://user-images.githubusercontent.com/8732435/104137407-35807700-5351-11eb-980c-321f1ff5eec3.png">

**Comment by roseundy** [comment]
First suggestion: The code is already pretty complex for selecting between halts/towns. Unless I can find an easy way to default correctly as a route is constructed this will be difficult to address.

Second suggestion: I'll think about how to update the help text. Changing the format of the buttons is difficult given the limited room allocated for the route selector.

Third suggestion: I'll look at this.

**Comment by ChrisTheCat** [comment]
I would think that defaulting to either "highest run + least subsidy" or "lowest run + highest subsidy" would be best.

**Comment by roseundy** [comment]
Yes, I understand what you want. Making the change is not anywhere close to easy.

**Comment by roseundy** [comment]
The intent was to maximize subsidy without reducing revenue. It breaks down, unfortunately, as stops are added.

**Comment by roseundy** [comment]
I have a thought on how to do this, though.

**Comment by roseundy** [comment]
OK, I'm making the following change:
- whenever a route is created or changed, the code will now maximize revenue first, and subsidies (halts) second.
