### ISSUE TITLE
1860 multi bump payouts suggestions

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3213]
At this screen, it would be nice if there was a tip box (perhaps to the right of the Select Routes tool, perhaps on the corporation charter) that indicated the amount needed to single/double/triple/quad jump on the stock market.

https://18xx.games/game/22068?action=469

<img width="427" alt="Screen Shot 2021-01-10 at 3 38 49 PM" src="https://user-images.githubusercontent.com/8732435/104138631-1803db00-535a-11eb-9b47-c4e0a888723b.png">

**Comment by ryanespin** [comment]
Maybe as helper text under the submit button?
![image](https://user-images.githubusercontent.com/3648402/106233936-a636e880-61c5-11eb-8432-0d8dc4fa991b.png)

**Comment by ChrisTheCat** [comment]
That works, though I'd prefer something that mimics the multiplication tables adjacent to the stock market in the print game.

**Comment by ryanespin** [comment]
Might've overdone it, lol

![image](https://user-images.githubusercontent.com/3648402/106235730-44787d80-61c9-11eb-83c6-a54cf285e592.png)

**Comment by roseundy** [comment]
No.

**Comment by roseundy** [comment]
The single line is better.

**Comment by roseundy** [comment]
I could put in a table at the top, similar to 18Mag.

**Comment by ryanespin** [comment]
@roseundy, so something like this?

![image](https://user-images.githubusercontent.com/3648402/106302775-61dc3480-6227-11eb-9ec6-cfb98ec95eaf.png)

**Comment by roseundy** [comment]
No, this:
![1860_chart](https://user-images.githubusercontent.com/8494213/106308160-86331380-621d-11eb-8ea5-045047a000b4.png)

If you don't mind, I would prefer putting this in myself.

**Comment by ryanespin** [comment]
I like it! Feel free to handle it. I'm happy to contribute anyway I am able to, even if it just means conversation. :)
