### ISSUE TITLE
Toggle tile coordinates

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#322]
A minor feature request that would help when reviewing others' routes or when describing routes verbally during synch games: overlay tile coordinates with an on/off toggle. Similar to the Map Ops-> Toggle coordinates in rr18xx:

![Screenshot from 2020-05-07 15-06-02](https://user-images.githubusercontent.com/33561233/81334768-8b8b7500-9074-11ea-857a-b5b412cbf335.png)

**Comment by sparr** [comment]
How persistent would you want this to be? Could it be a button on the page, which reverts any time you change tabs or reload? If so, it can exist purely in client side javascript and not require any game/player configuration state.

**Comment by 8bg** [comment]
Client-side/ephemeral would be fine imho

**Comment by NickHeiner** [comment]
Another way to do this: when the player hovers on a tile, highlight the axis labels that correspond to it. (e.g. if I hover on `H8`, then the `H` and `8` would be highlighted along the edges of the board.)
