### ISSUE TITLE
Make it possible to end/delete broken games

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#3230]
Take https://18xx.games/game/21671?action=145#tools as an example.
There is no way for a player to get rid of the game.  If trying to end the game the GUI complains that no new actions can be added.

So I would suggest that we add the possibility to end or delete a broken game. If it were to be possible as game owner maybe we can add information about this in the error message.

**Comment by tobymao** [comment]
the game owner can delete the game, feel free to close this issue or change it

**Comment by jenf** [comment]
we should probably have a way of double checking dead games so we can fix problems, maybe just mark them deleted and then we can sweep them after a while.

**Comment by perwestling** [comment]
According to #3170 the owner of that game cannot delete it.
