### ISSUE TITLE
1849:  When AFG is the RSA company, the player with priority is asked to select its home (the president should be asked instead)

### ISSUE THREAD

**Issue by triode-dev** [tobymao/18xx#3232]
There was an earlier 1849 bug that we couldn't par AFG when it's the RSA company (#3175), now I can par the company.  However the company needs to select its home - and that choice is being given to the player with priority, rather than the player with the AFG presidency.

Here's an example game - https://18xx.games/game/22011.  After AFG pars, the president (triode) was not asked to select its home.  Instead, this choice is given the player with priority after the ISR (FrankG).

**Comment by chrispday** [comment]
+1 https://18xx.games/hotseat/hs_wvmmgjcx_22069
Teena floats AFG, ChrisD is asked to place home token

**Comment by jenf** [comment]
Should be an easy migration

**Comment by jazhuit** [comment]
Happened in our game as well

https://18xx.games/game/22309
