### ISSUE TITLE
18SJ -- Gellivare Company Discount not working

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#3233]
https://18xx.games/game/21785

Timestamp 2021-01-10 14:15
Gellivare Company discount not received for C30

Also, on a different 18SJ hotseat, Gellivare Company discount not received for C30 and not allowed to lay track since the treasury had less than 75Kr (that's how I first accidentally discovered issue).

**Comment by perwestling** [comment]
When SNJ put tile in Malmfälten:
  [19:05]SNJ receives a discount of 50kr from The Gellivare Company
  [19:05]SNJ spends 25kr and lays tile #57 with rotation 0 on D29 (Malmfälten)
  
When SNJ put tile in C30:
  [23:15]SNJ receives a discount of 100kr from The Gellivare Company
  [23:15]SNJ receives a discount of 50kr from The Gellivare Company
  [23:15]SNJ spends 75kr and lays tile #9 with rotation 0 on C30
  
  A corporation that builds C30, connecting to Narvik, normally pays 75kr for the central mountain and 2*75kr for border mountains = 225kr.
   GC reduces 50kr per mountain, which means 150kr discount (it is a double mountain on the boarder in the physical game). That means the cost is 225kr - 150kr = 75kr.
   
 The description of the private says:
 "Reduce terrain cost in D29 and C30 to 25 kr for mountains and 50 kr for the Narvik border."
 
 And if owner of GC has less than 75kr in treasurey it cannot remove all three mountains.
   
 So it seems correct to me.  The text might be improved but note that if C30 is built without connecting to Narvik the cost is "only" 25kr.

**Comment by luigicoolGH** [comment]
Per, you are absolutely correct, I don't know how I missed that by placing the #9 tile in C30 you pay both the tile placement and the connection to Narvik at once!  It's all clear now.  Great job and thanks for bringing us this hidden gem.
