### ISSUE TITLE
18Mex: KC,M&O Private 

### ISSUE THREAD

**Issue by 100pcBlade** [tobymao/18xx#3235]
KC,M&O Private - My version of the rules says that the private stays open when the copper canyon tile is laid but the implementation on here closes it. I'm assuming this is an error in it's implementation

**Comment by Maxwell-Frank** [comment]
This rule was changed after the printing of the new edition: 

https://boardgamegeek.com/thread/535347/error-kcmo-private-company

**Comment by 100pcBlade** [comment]
Ah. Ok. Thanks. Sorry to bother you
