### ISSUE TITLE
Highlight turn in browser tab name

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#324]
I've started leaving 18xx.games open in a Pinned tab in Firefox. This is really convenient for sites I visit frequently, like my email and Yucata. However, it means I don't get any email notifications, since I always have the site open in a tab.

It would be nice if there were more choices for email - no mail | mail only if inactive | all mail. It would also be nice if I could override the setting on a per game basis - so I can play a realtime game and get no mail, but also at the same time be in an asynchronous game with all email.

**Comment by tobymao** [comment]
what if you got a desktop notification intsead?

**Comment by ChrisTheCat** [comment]
It would depend on what kind of notification. If it's in-browser, e.g. change tab color, prefix tab name with an asterisk, etc. then sure. If it's a pop up, then that wouldn't work. I use my computer to make work presentations and have nearly all destop popup notifications disabled.

**Comment by tobymao** [comment]
gotcha, i prefer the tab name asterix flash, but someone else wanted the
full shebang

**Comment by sparr** [comment]
@ChrisTheCat your browser and OS should give you control over if / when / how desktop notifications are presented.

**Comment by ChrisTheCat** [comment]
@sparr Thanks, that's how I disabled them all :-) Having all desktop notifications disabled is why I'd rather get email or in-browser notifications.
