### ISSUE TITLE
1817NA, company on yellow gets shorts closed by the market for 0$

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#3240]
To check it:
https://18xx.games/game/19350?action=1043

Make UR take 5 loans, therefore going to yellow. Then during the SR you'll get something like:

[15:57]-- Stock Round 4 --
[15:57]Market buys a 20% share of UR from the Treasury for $0
[15:57]Market buys a 20% share of UR from the Treasury for $0
[15:57]Market closes 2 shorts for UR

**Comment by jenf** [comment]
It's not explicit in the rules, but technically the shares have no value so it logically follows

**Comment by PedroRCSequeira** [comment]
yeah, i just found this:

At the start of every stock round, the bank closes
any short positions in the open market by purchasing
stock from the company treasury, if there is any avail-
able. The bank will continue to do this until all short
shares are cleared from the open market.
