### ISSUE TITLE
1849 First OR - no share issue message

### ISSUE THREAD

**Issue by yraelrocks** [tobymao/18xx#3245]
Can there be a note in hold or something to say why the issue share is skipped? Maybe in the Info page & in the history when that is skipped.

**Comment by tysen** [comment]
Is there something about that in particular that you think is especially confusing compared to other skipped steps? For example, a stock round turn might be skipped because a player holds only shares of corporations that have not yet operated and hasn't enough money to buy anything.

**Comment by yraelrocks** [comment]
The message for that says player has no further actions so skipped or so such.

It’s only a thought - even if it was ‘issue shares step skipped (first OR)’ just for clarity

**Comment by tysen** [comment]
Got it. I'll see about this once I resolve the outstanding bugs.

**Comment by BellmakerSA** [comment]
A note like “company cannot issue shares in its first operating round” would be nice
