### ISSUE TITLE
1849 - Can't refloat bankrupted corporation

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#3246]
https://18xx.games/game/22163

ATA was closed by going to $0 on the stock market. Is grey in the SR, showing no valid actions - inc no option to refloat it

**Comment by jenf** [comment]
Is the game id correct? It seems to show a game in SR 1

**Comment by Blobbley** [comment]
Clearly not - sorry Jen. https://18xx.games/game/21888

**Comment by Landshrk83** [comment]
Same issue in game 21855 https://18xx.games/game/21855
