### ISSUE TITLE
No way to submit chat message on mobile

### ISSUE THREAD

**Issue by mkkohls** [tobymao/18xx#3247]
**Describe the bug**.
I tried to send a message in the in game chat and the enter button on my mobile keyboard just adds a new line. It sometimes submitts and sometimes adds a new line. Until recently it never added a new line. There is no separate submit button so I cannot use that either.

**Please provide details about your system**
 - OS Android 10 Device OnePlus 6
 - Chrome 87.0 
 - Keyboard Gboard 10.0.02

**Comment by jenf** [comment]
I've seen this on Android as well, before the latest change.

**Comment by yzemaze** [comment]
I can’t reproduce this behavior (Chrome 87.0.4280.141).
Have you noticed the same problem on the main chat? Can you quantify "sometimes"? Does a page refresh change something? Have you tried a different keyboard or browser?

**Comment by TBarchet** [comment]
I'm using the standard keyboard that comes on Pixel 4a (Gboard?).  Typing a message in game log or main screen reproducibly does new line instead of submitting the message when pressing Enter.  Double tapping Enter submits the message.

**Comment by tobymao** [comment]
couple things to try, fiddle with the html to make it a form,

change keyup to keydown, use code instead of keyCode

https://stackoverflow.com/questions/14251676/detect-enter-key-pressed-using-javascript

**Comment by orome** [comment]
FWIW: No issues on iOS (14.3) Safari. Hitting return works as expected.
