### ISSUE TITLE
1860 - Skipped player turn during auction.

### ISSUE THREAD

**Issue by hopkinsryan** [tobymao/18xx#3248]
https://18xx.games/game/21891?action=61

During the private auction, player Hopkins passed, maquinista won the bid for 80, starting a new auction for the next private.  Maquinista then passed, and instead of going to Hopkins for the next bid, it just said that the third player pampy won the auction for 0.  

Hope this description is sufficient.  Many thanks!

**Comment by roseundy** [comment]
Maquinista won the auction at 80, but passed instead of doing the required buy. So that was an illegal play. There is a bug, in that maquinista should never have been offered to opportunity to pass.

**Comment by hopkinsryan** [comment]
Oh right, he never chose a cert.  Thanks, Steve!

**Comment by roseundy** [comment]
You can recover by "undoing" until action=58 and replaying from there.

**Comment by hopkinsryan** [comment]
Thanks!
