### ISSUE TITLE
Game log reports token placement upon floating

### ISSUE THREAD

**Issue by joshyboy20k** [tobymao/18xx#325]
<img width="277" alt="Screen Shot 2020-05-07 at 4 26 56 PM" src="https://user-images.githubusercontent.com/46472947/81354256-ff7f4a80-907f-11ea-8b6f-3b6600c22418.png">

Game log incorrectly reports that token is placed when corporation floats when token is not placed until beginning of operating round

**Comment by michaeljb** [comment]
Technically the log is accurately capturing what is happening; the problem is that we place the token when the company floats instead of at the start of the OR.

**Comment by michaeljb** [comment]
Naturally, different games have different rules for this...

* 1889 - beginning of OR
* 18Chesapeake - beginning of corporation's first operating turn
* 1846 - when corporation floats
