### ISSUE TITLE
[18SJ] "Parred" should have two Rs

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3260]
https://18xx.games/game/22371?action=259

In phase 5, a message appears on the log to indicate that companies move to full capitalization: "TGOJ becomes full capitalization corporation as it has not been pared"

_Parred_ should have two Rs, not one. 

[obviously, this is not a critical issue, but should be trivial to fix]

**Comment by perwestling** [comment]
Corrected at next deploy.
