### ISSUE TITLE
Differentiate messages for private auction, direct purchase vs uncontested bid vs won auction

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#327]
"PLAYER wins the auction for COMPANY with a bid of PRICE"

This same message is used for buying the cheapest private at face value, for buying a private on which you had an uncontested bid, and for actually winning a closed auction. I would like to see three different messages here. Perhaps:

"PLAYER buys COMPANY for face value, PRICE"

"PLAYER buys COMPANY for their initial bid, PRICE"

"PLAYER wins the auction for COMPANY with the high bid of PRICE"

**Comment by dfannius** [comment]
Yes, there is actually code that is supposed be differentiating these cases now, but it has a bug. To be fixed shortly.
