### ISSUE TITLE
18Chesapeake: Off the Rails - stock round ends early because there are "no valid actions" when I have enough money to buy another share

### ISSUE THREAD

**Issue by jftaylor21** [tobymao/18xx#3278]
I am playing https://18xx.games/game/22160.

The game claims that jftaylor21 has no valid actions and must pass during the stock phase. However, I still have enough to buy a stock and am below the cert limit.

Am I missing something or is this a bug?

**Comment by tobymao** [comment]
https://18xx.games/game/22160?action=30

you only have $175, the cheapest shares are $90, so no you don't have enough money.

**Comment by dfannius** [comment]
@jftaylor21 You may have misread the log (like I did); the purchase was successful, and then the game immediately autopassed all four players, which is why you saw the "no valid actions" message.
