### ISSUE TITLE
Keyboard shortcuts, especially for history navigation

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#328]
First and foremost, I request home/left/right/end as keyboard shortcuts for << < > >> in the History navigation.

In addition to that, it would be nice to be able to switch tabs from keyboard shortcuts.

**Comment by tobymao** [comment]
before you start this let's do a quick sync to make sure you do this a proper way

**Comment by jenf** [comment]
Essentially a dup of #495 keeping the later one since it's more detailed
