### ISSUE TITLE
[18CO] Same player two bids on the same private

### ISSUE THREAD

**Issue by coleman07** [tobymao/18xx#3292]
I bid on DPR for $115 than was outbid. I moved a bid to up my bid to $125 on DPR. Now my available money is tied up twice for the same private. Shouldn't the private only have one bid per player?

https://18xx.games/game/21752

**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

**Comment by ryandriskel** [comment]
This is working correctly.

In the physical game, once you place a stack of money on the table, that money is committed. You can increase the size of the stack (place bid) or move it (move bid), but moving one bid onto a private with a previous bid does not "free up" your previous bid.
