### ISSUE TITLE
History messages about financial events should use = or — instead of -

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#330]
"Player 1 (Teacher) receives ¥30 - ¥10 x 3"

I think this would make more sense with "=", possibly also rearranging the order of the numbers.

"TR pays out ¥110 - ¥11 per share"

This should be — or comma, not hyphen/dash.

**Comment by HQ063** [comment]
Using `—` gives almost no visible difference (see screenshot, it's a `—`). I'd use use `|` or wrap the `¥11 per share` with parentheses

<img width="272" alt="imagen" src="https://user-images.githubusercontent.com/663312/81356613-fc985000-90a7-11ea-9816-5deac8e0e21e.png">

**Comment by sparr** [comment]
`AR pays out Y40 = Y4 x 10 shares` would match the formatting of later lines, but otherwise feel a bit weird.

**Comment by HQ063** [comment]
Agree that feels weird, but actually, considering future games may not necessary have 10 shares per company (1817) it may be useful to also include the total number of shares and match the format of later lines.

**Comment by dfannius** [comment]
Yes, I would like to redo these messages too; I'm glad to hear that it's not just my own pedantic nature. (For one thing, I'd like to use an actual times sign `×` rather than the letter `x`.)
