### ISSUE TITLE
[1849]- Route not calculating income properly

### ISSUE THREAD

**Issue by BGarmon80** [tobymao/18xx#3307]
In our game of 1849 located at https://18xx.games/game/22309, during OR 4.1, the AFG's 6H train running north out of Terranova during the green phase is only calculating Terranova as a value 20 stop instead of 30. The 4H trains running through the same city at the same time are calculating it properly at 30. https://18xx.games/game/22309?action=148

**Comment by tysen** [comment]
Green incomes don't start paying until the 8H phase. This is listed on the Info tab but many people find it confusing. I'm working on changing the UI.
