### ISSUE TITLE
[1867] Change the "O" in Ottawa hex to "Y/O"

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#3309]
The rule about upgrading the Ottawa hex is: **_Ottawa (J12) upgrades as a Y city until it can be upgraded into its gray tile (O)._**

When first pursuing the 1867 map I became thoroughly confused because I found the Y cities, M, cities, and T cities in the tile mix, but couldn't find any "O" cities until I finally spotted the 1 Grey "O" city, which eventually led me to ctrl+F the rules for "ottawa" to find the above rule.

Just having the single "O" in the hex implies that only O tiles can upgrade this hex, which is where the confusion came from.  I'd suggest some other way to add a reminder about the rule for the ottawa hex.  Perhaps something as simple as "Y/O."

**Comment by jenf** [comment]
dup of #2885
