### ISSUE TITLE
Different message verbs for different stock price movements

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#331]
"TR's share price changes from ¥60 to ¥65"
"UR's share price changes from ¥65 to ¥50"

How about different words for "changes" depending on direction? "increases" / "decreases" for dividends, "rises" / "falls" for sellouts and sales, "bumps up" / "bumps down" or similar for hitting the right or left wall, etc?

**Comment by tobymao** [comment]
i'm not convinced of this and would make the code messy

**Comment by sparr** [comment]
What about just "increases" and "decreases", without consideration of actual movement direction? That could be calculated directly in the output string formatting, based on the old and new price values alone.
