### ISSUE TITLE
[1849] Game wont load after Earthquake closes AFG

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#3317]
https://18xx.games/game/22927. 

Game stuck loading after a 12T was bought, triggering the Earthquake and closing AFG with its only token in Messina

**Comment by pstone1** [comment]
Similar issue here: https://18xx.games/game/22597

**Comment by ArielAyanna** [comment]
This is not fixed.  Game does not work.

**Comment by tobymao** [comment]
What's wrong with it?

**Comment by tobymao** [comment]
The game now loads. If you're seeing something else wrong, it's a different issue cc @tysen

**Comment by ArielAyanna** [comment]
AFG should be closed,  but shows as active and does not let me take any actions.
