### ISSUE TITLE
Change order of history messages for train purchase and phase change

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#332]
"-- Phase 3 (Operating Rounds: 2, Train Limit: 4, Available Tiles: Yellow, Green ) --"
"KO buys a 3 train for ¥180 from The Depot"

I think these messages should be in the opposite order. The phase changes immediately *after* the train is bought, not before.

**Comment by sparr** [comment]
I'm having trouble tracking down the code path that leads to operating.rb::_process_action() happening after phase.rb::process_action()

**Comment by dfannius** [comment]
`Game::process_action` (in `game/base.rb`) calls `@phase.process_action` and then `@round.process_action`, where `@round` is an `OperatingRound`.

**Comment by dfannius** [comment]
(and then the generic `process_action` in `Round` calls `OperatingRound::_process_action`)
