### ISSUE TITLE
[ALL] Suggestion: Limit Amount to Money in Treasury When Buying Cross-Company.

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3324]
During the auction, the spinner(?) thingy limits the input to the money the player has. During the train buying step, how about limiting the the spinner thingy to the company's treasury when using it to input how much you're paying for a train from another company?

**Comment by Maxwell-Frank** [comment]
Make sure this doesn't break games like 18Chesapeake in which you can emergency buy a train across for more than the company's current treasury.

**Comment by OedipussyRex** [comment]
> Make sure this doesn't break games like 18Chesapeake in which you can emergency buy a train across for more than the company's current treasury.

I assume this is the 1830 compulsory train purchase rule. So let's amend the suggestion to "limiting the the spinner thingy to the maximum allowed to purchase a train from another company; for instance, the money in the company's treasury for most games and situations, or treasury plus president cash, up to face value of the train, during CTP in 1830-like games."

**Comment by ryandriskel** [comment]
As an aside, I'm working on a similar update for when a corporation tries to buy in a private.
