### ISSUE TITLE
Current operating company marker not advancing properly

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#334]
Note in the pictures that the next company is operating but the previous is still underlined
![B02FBE45-0F81-4789-820C-F772DA3CE099](https://user-images.githubusercontent.com/830087/81361300-94318900-9110-11ea-8b49-35f7f7c0168f.png)
![19BF6050-ECC4-4238-AD7D-7ADF9519D985](https://user-images.githubusercontent.com/830087/81361306-97c51000-9110-11ea-91bc-2baf943e9446.png)

**Comment by tobymao** [comment]
can this be reproduced?

**Comment by dfannius** [comment]
I vote to close this unless it shows up again.

**Comment by jcoveney** [comment]
I'd be fine with that. If it happens again, I'll reopen.
