### ISSUE TITLE
[1817x] Add acquisition warning

### ISSUE THREAD

**Issue by tom-blight** [tobymao/18xx#3340]
At the payout/withhold step there is already a warning if any of the options lead to liquidation. 

Id like to propose adding a warning about moving into the acquisition zone too. 

Perhaps also/instead the stock market could be previewed at this point, as a reminder where the company is and might end up after this step. 

regards,
An inattentive user

**Comment by jenf** [comment]
Please provide a game where this is shown (really helps investigating)

**Comment by tom-blight** [comment]
This is a general suggestion, for no game in particular.

**Comment by jenf** [comment]
Without a game easily showing the issue it'll be less of a priority to fix

**Comment by tom-blight** [comment]
I feel like there’s a misunderstanding here - perhaps I could have been
more clear. This is a Feature Request, not a big report.

At the revenue distribution step I would like a warning added against
actions that would drop stock into Acquisition, in a similar way that there
is a warning of an action would mean Liquidation.

**Comment by jenf** [comment]
I understand it's a feature request, but many of the feature requests point an example action where they want things improved which makes it easier for the developers to quickly improve the code base.

**Comment by tom-blight** [comment]
Ah ok, got you.

I’ve just looked for an example and it seems to have now been added! See
for example OR1.2 payout step for company SR in this game:
https://18xx.games/game/21973?action=219#spreadsheet

Now it states withholding would move the company to aquisition.

Thanks. Can close.

**Comment by jenf** [comment]
Ahh, it hasn't been added since you raised the bug report so will close

**Comment by tom-blight** [comment]
So - I realised it’s the ‘Take Loan’ button that is missing the Acquisition warning. See https://18xx.games/game/21973?action=210. Should I create a new issue for this feature request? Would fit under this same title...

**Comment by jenf** [comment]
That's being tracked on #2600
