### ISSUE TITLE
[1867] CN not placing token in Montreal when company is nationalized.

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3349]
When a company based in Montreal is nationalized no CN token is being placed in Montreal (L12) even though a CN token is not already there.

**Comment by OedipussyRex** [comment]
CN, NC, what's letter order amongst friends.

**Comment by OedipussyRex** [comment]
Forgot to add json
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1610844573,
      "company": "C&SL",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1610844574
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1610844574
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "created_at": 1610844575
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5,
      "created_at": 1610844579
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "created_at": 1610844585,
      "company": "NFB",
      "price": 45
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1610844586
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "created_at": 1610844586
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "created_at": 1610844594,
      "company": "MB",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "created_at": 1610844596
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "created_at": 1610844596
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "created_at": 1610844604,
      "company": "QB",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "created_at": 1610844605
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14,
      "created_at": 1610844606
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "created_at": 1610844612,
      "company": "SCT",
      "price": 90
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "created_at": 1610844614
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "created_at": 1610844615
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 18,
      "created_at": 1610844677,
      "corporation": "BO",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 19,
      "created_at": 1610844680,
      "city": "L12-0-1",
      "slot": 0
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "created_at": 1610844693,
      "corporation": "BO",
      "price": 115
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21,
      "created_at": 1610844695
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22,
      "created_at": 1610844729,
      "corporation": "BO",
      "price": 120
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23,
      "created_at": 1610844736
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 24,
      "created_at": 1610844759
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25,
      "created_at": 1610844760
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 26,
      "created_at": 1610844764
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 27,
      "created_at": 1610844766
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 28,
      "created_at": 1610844767
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 29,
      "created_at": 1610844770
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 30,
      "created_at": 1610844776,
      "corporation": "BO",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 31,
      "created_at": 1610844778,
      "city": "L12-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32,
      "created_at": 1610844781
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "created_at": 1610844800
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 34,
      "created_at": 1610844805,
      "corporation": "CS",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1610844808,
      "city": "L12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 36,
      "created_at": 1610844816
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37,
      "created_at": 1610844817
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 38,
      "created_at": 1610844829,
      "corporation": "CV",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1610844831,
      "city": "M9-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 40,
      "created_at": 1610844833
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 41,
      "created_at": 1610844833
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 42,
      "created_at": 1610844837,
      "corporation": "KP",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1610844841,
      "city": "J12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 44,
      "created_at": 1610844843
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 45,
      "created_at": 1610844844
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 46,
      "created_at": 1610844854,
      "corporation": "OP",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1610844860,
      "city": "G15-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 48,
      "created_at": 1610844866
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 49,
      "created_at": 1610844867
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 50,
      "created_at": 1610844879,
      "corporation": "TN",
      "price": 105
    },
    {
      "type": "place_token",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1610844882,
      "city": "F16-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 52,
      "created_at": 1610844886
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 53,
      "created_at": 1610844887
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 54,
      "created_at": 1610844895,
      "corporation": "AE",
      "price": 105
    },
    {
      "type": "place_token",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1610844903,
      "city": "E17-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 56,
      "created_at": 1610844907
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 57,
      "created_at": 1610844909
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1610844917
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 59,
      "created_at": 1610844926,
      "corporation": "CA",
      "price": 105
    },
    {
      "type": "place_token",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 60,
      "created_at": 1610844929,
      "city": "D16-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1610844932
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 62,
      "created_at": 1610844936,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 63,
      "created_at": 1610844940
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1610844942,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 65,
      "created_at": 1610844945
    },
    {
      "type": "buy_train",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 66,
      "created_at": 1610844946,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1610844953
    },
    {
      "type": "buy_train",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 68,
      "created_at": 1610844957,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 69,
      "created_at": 1610844965
    },
    {
      "type": "buy_train",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 70,
      "created_at": 1610844967,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 71,
      "created_at": 1610844970
    },
    {
      "type": "buy_train",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1610844975,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 73,
      "created_at": 1610844987
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1610844990
    },
    {
      "type": "buy_train",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 75,
      "created_at": 1610844993,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 76,
      "created_at": 1610844994,
      "train": "2-0",
      "price": 1
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 77,
      "created_at": 1610844996
    },
    {
      "type": "buy_train",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 78,
      "created_at": 1610844998,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 79,
      "created_at": 1610845001,
      "train": "2-1",
      "price": 1
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 80,
      "created_at": 1610845004
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 81,
      "created_at": 1610845006
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 82,
      "created_at": 1610845500
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 83,
      "created_at": 1610845503
    }
  ],
  "id": "hs_gipclvrj_1610844564",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-16",
  "loaded": true,
  "result": {},
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    "Player 2"
  ],
  "updated_at": 1610845503
}

**Comment by OedipussyRex** [comment]
I don't have a json for you, sorry, but I just played a hotseat that worked as expected with a company in Montreal being trainless with the purchase of the 4T and being nationalized, so it may be an issue with a company in Montreal being nationalized because it cannot afford a train.

**Comment by OedipussyRex** [comment]
Just confirmed that the error also occurs in Montreal when the company cannot pay the interest due.

This time I remembered to copy the json.
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1610889402,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1610889403
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1610889404
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "created_at": 1610889406,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5,
      "created_at": 1610889407
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "created_at": 1610889407
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1610889408,
      "company": "MB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "created_at": 1610889409
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "created_at": 1610889409
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "created_at": 1610889410,
      "company": "QB",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "created_at": 1610889411
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "created_at": 1610889411
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "created_at": 1610889412,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14,
      "created_at": 1610889413
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "created_at": 1610889414
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "created_at": 1610889416,
      "corporation": "BO",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 17,
      "created_at": 1610889420,
      "city": "J12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 18,
      "created_at": 1610889424
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19,
      "created_at": 1610889425
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "created_at": 1610889428,
      "corporation": "CS",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 21,
      "created_at": 1610889434,
      "city": "M9-0-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 22,
      "created_at": 1610889438
    },
    {
      "type": "undo",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 23,
      "created_at": 1610889438
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 24,
      "created_at": 1610889443
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 25,
      "created_at": 1610889444
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 26,
      "created_at": 1610889445
    },
    {
      "type": "undo",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 27,
      "created_at": 1610889448
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "created_at": 1610889453,
      "corporation": "BO",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 29,
      "created_at": 1610889456,
      "city": "L12-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 30,
      "created_at": 1610889482
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 31,
      "created_at": 1610889487
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32,
      "created_at": 1610889490
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "created_at": 1610889492
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 34,
      "created_at": 1610889495,
      "corporation": "CS",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1610889497,
      "city": "L12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 36,
      "created_at": 1610889500
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 37,
      "created_at": 1610889501
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 38,
      "created_at": 1610889504,
      "corporation": "CV",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1610889506,
      "city": "M9-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 40,
      "created_at": 1610889510
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 41,
      "created_at": 1610889511
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 42,
      "created_at": 1610889526,
      "corporation": "KP",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1610889536,
      "city": "O7-2-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 44,
      "created_at": 1610889541
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 45,
      "created_at": 1610889541
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 46,
      "created_at": 1610889552
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 47,
      "created_at": 1610889554
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 48,
      "created_at": 1610889554
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1610889560
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 50,
      "created_at": 1610889562,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1610889565
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1610889567,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1610889569
    },
    {
      "type": "buy_train",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1610889571,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1610889573
    },
    {
      "type": "buy_train",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 56,
      "created_at": 1610889582,
      "train": "2-0",
      "price": 10
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 57,
      "created_at": 1610889584
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1610889592
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 59,
      "created_at": 1610889594,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 60,
      "created_at": 1610889609
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1610889611
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 62,
      "created_at": 1610889614
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 63,
      "created_at": 1610889627
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 64,
      "created_at": 1610889633
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 65,
      "created_at": 1610889633
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 66,
      "created_at": 1610889634
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1610889640
    }
  ],
  "id": "hs_tqdoytah_1610889398",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-17",
  "loaded": true,
  "result": {},
  "turn": 2,
  "round": "Operating Round",
  "acting": [
    "Player 1"
  ],
  "updated_at": 1610889641
}

**Comment by jenf** [comment]
The 'green' token is from the engines POV owned by CN which is causing the issue.
