### ISSUE TITLE
[1828.games] Auto-pass Players with No Legal Actions During Initial Auction

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3361]
https://18xx.games/game/23277?action=50

In this game, after the initial trigger pull, TIE53 has no further legal actions during the auctions of the B&O privates.  They should be auto-passed.

**Comment by tysen** [comment]
Players can increase existing bids. 6.1 in the rules.

**Comment by crericha** [comment]
I don't believe any of the waterfall auction games currently support auto-pass. This would be a chance to the engine.
