### ISSUE TITLE
1860: Bank Broke after Southern Formed, perhaps misleading

### ISSUE THREAD

**Issue by PaulKT** [tobymao/18xx#3374]
https://18xx.games/game/20624

I get that in 1860 Southern can form and British Rail not form thus end game via nationalisation may not actually happen. Even if that end game trigger does form the market can still end the game straight out. But if BR forms the bank is unlimited. However, Southern can form and the bank break as per our game. I just wanted to note that it may be confusing.

[20:57]Southern Railway Forms; End of game triggered (via Nationalization). I think it should say "End Game possible via Nationalisation" maybe?

Then when BR forms it should then be "End of game triggered (via Nationalization)."

As some of our players thought "[20:57]Southern Railway Forms; End of game triggered (via Nationalization)." mean the bank was unlimited.

The game was fine, just maybe a bit misleading?

**Comment by roseundy** [comment]
This should have been linked to the PR with the change.
