### ISSUE TITLE
[1867] Company takes loans despite no EMR

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#3380]
https://18xx.games/game/22444

In this game, the C&O was able to buy a 6 despite not having the cash on hand to do so and already having 2 trains. It doesn’t actually state that the company takes loans but I’m assuming they are immediately paid off by the nationalisation of the private companies 

I undid and acted legally to continue the game but should show in game data and in hotseat. OR4.2

**Comment by jenf** [comment]
Confirmed
18xx.games/game/22444?action=540

**Comment by jenf** [comment]
Ahh, that causes the rust of the 6s and the privates payout which actually gives you enough to buy which is the cause of the bug
