### ISSUE TITLE
[1849] variant: IFT not in the first 3 companies. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#3384]
A common (though not universal) variant for 1849 is to not include IFT as one of the early opening companies. Since IFT can effectively be walled in until the green phase, and even longer if no one buys in P1.

it would be useful to have an option to ensure that it’s not one of the 3 first companies. Regardless of player count, ensuring it’s no earlier than 4th gives all players some options to work around it.

**Comment by dfannius** [comment]
Since there is sometimes some reluctance to add variants that aren't officially blessed, it's worth noting that this variant is explicitly recommended for new players in the rulebook (the boxed paragraph in section 2.2 in the AAG edition).

**Comment by philcampeau** [comment]
Yes! Thank you for mentioning that, I had meant to and forgot.

**Comment by dfannius** [comment]
Implemented with #3815.
