### ISSUE TITLE
Consider adding a 'preferred pronoun' to user account settings

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#3386]
Seeing a few people add `(pronouns)` to their username, it seems like a good thing to have available as an official feature

- Perhaps add a dropdown / freetext field in the account menu to have [suggested options plus ability to define custom ones](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) (default `nil`)

- Perhaps render after the user's name if non-`nil` 
`dstar (they/them)`

- Presumably would require db migration to add this field

**Comment by tobymao** [comment]
since it can easily be done by changing your username, i'd prefer that than adding a migration

**Comment by benjaminxscott** [comment]
I think I'd like to revisit this in the context of chat @-mentions, as the current implementation of changing username means it's quite tricky to @-mention someone with a long / special character username
e.g. `dstar [he/they]`
