### ISSUE TITLE
Attempting to load game data that leads to an invalid state should jump to the last valid move in the history

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#339]
Currently if you try to load invalid game data, the hotseat game will refuse to load/render, with a console error that the game constructor has failed. It would be nice if it would load at the correct action index to render the last valid game state, so that the error can be produced by clicking forward one step in the history, and the game state can be inspected.

**Comment by jenf** [comment]
I was thinking about this as well, we could then add a button to undo back to the last valid point. (When the new undo code is ready)

We need some text to explain to the user what went wrong due to the upgrade.
