### ISSUE TITLE
[1828.games] "May Lay 2nd tile..." Text Appears Twice on System

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3394]
https://18xx.games/game/23459?action=898

In this game, the B&M merged with the NKP. It should only have the ability to lay a second tile for $40 once, but it is listed twice on the charter. 

I have not tested whether the company is actually _given_ the ability to lay an extra tile twice, or if it is just listed twice.

**Comment by crericha** [comment]
Should be a visual only bug. Let me know if you find out otherwise.
