### ISSUE TITLE
[1828.games] Player allowed to sell shares during EMR, but then not actually buy a train

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3395]
https://18xx.games/game/23459?action=940

Somehow, G3 is able to sell shares as president of PRR to force-buy a train in their empty shell, but not required to actually buy the train. 

Can we somehow enforce that a player purchase a train once they begin the share-selling process [and subsequently, require that they purchase a train for a price that required the sale of those shares]?

**Comment by crericha** [comment]
Yeah, I caught this one too. The PR is up for review.
