### ISSUE TITLE
[18CO] Token private wording is inconsistent with implementation

### ISSUE THREAD

**Issue by rrokkam** [tobymao/18xx#3396]
The description of the Denver, Northwestern, and Pacific private claims that "an owning Corporation may return a station token to its charter to gain the token cost".

The implementation gives the value of the rightmost empty token if there is one (and the cost of the highest token if there is none).

Some unexpected behaviors from the wording "the token cost":

1) The reimbursement amount for a token changes depend on what other tokens the company has placed.
2) The reimbursement amount might not be the same cost paid for the token.
3) The home token can be reimbursed for money despite the token being free.

If the implementation behavior is intended, the phrase "the token cost" in the private description could be replaced with "the cost listed under the most expensive empty token slot on the company's charter", or something similar with fewer words.

**Comment by ryandriskel** [comment]
_(and the cost of the highest token if there is none)._

I am curious about this. I double checked and the implementation doesn't allow the corporation to remove its last token, so could you clarify what you meant?

**Comment by rrokkam** [comment]
Ignore that -- that was just a mistake.
