### ISSUE TITLE
Route highlighting

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#340]
<img width="322" alt="Screenshot 2020-05-07 22 16 49" src="https://user-images.githubusercontent.com/8732435/81377504-79ccc080-90ba-11ea-9a87-96559c8078cf.png">

It would be nice if Muki wasn't highlighted.

**Comment by tobymao** [comment]
this is technically a layable hex because it can be reached, there just exist no tiles to upgarde it in 1889,

**Comment by tobymao** [comment]
i doubt i will get around to fixing this

**Comment by ChrisTheCat** [comment]
Now that I understand it, I'm not sure it needs a fix. I would just add something to the documentation that says "all hexes that can be reached are highlighted, even if an eligible tile is not available."

**Comment by sparr** [comment]
What is the desired state if the game includes a valid upgrade, but none are currently available?

**Comment by ChrisTheCat** [comment]
> What is the desired state if the game includes a valid upgrade, but none are currently available?

I think the idea is to highlight only hexes where a tile may legally be played. In addition, JCL suggested that when you select a tile, the map should highlight to show you where it may legally be played. It would be great if those layers could both be visible at the same time.
