### ISSUE TITLE
1860: Incorrect stock movement prediction on payout

### ISSUE THREAD

**Issue by Jasonbartfast** [tobymao/18xx#3407]
edit: it just looks like a bug, I'm assuming that the market movements are displayed as such to handle the zig-zagging nature of movement. still probably going to confuse people, for the purposes of this display you could (if it is programmatically possible) just divide the number of steps by two, although naturally that doesn't work for sales.

1860, Windows 10, Firefox, game ID 22045. 

When selecting to payout or withhold the interface says a payout of 240, stock value 90, will result in 4 steps to the right.

Upon selecting "payout" the stock value only moved two steps to the right, the correct amount. Dividends and halt income were paid correctly. 

Similarly, the "withhold" movement prediction is wrong, but functions correctly when withholding.

![1860 bug - 22045](https://user-images.githubusercontent.com/77690606/105072398-c3e0b100-5a53-11eb-9ff5-217be23be834.PNG)

**Comment by roseundy** [comment]
Dup of #3214 

Despite the appearance of the zig-zag stock market, it is essentially a linear market. The message, while confusing, is accurate.
