### ISSUE TITLE
18xx.games filtered by google safesearch

### ISSUE THREAD

**Issue by brad-haynes** [tobymao/18xx#3411]
Using Google Nest WiFi, if safesearch is enabled, 18xx.games website is blocked as an adult website--I assume from the xx in the url. Not sure how you would go about removing it from their list of blocked websites but I thought your web site had gone down for the longest time until I opened it in Chrome and saw:

![image](https://user-images.githubusercontent.com/4133212/105098116-390daf80-5a6f-11eb-8bab-46033e998d4b.png)

**Comment by benjaminxscott** [comment]
goog may have fixed this?
https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2F18xx.games

**Comment by brad-haynes** [comment]
Indeed. Looks like they updated it today.

Closing as resolved.
