### ISSUE TITLE
[1828.games] Display Cost for Share Trade-up in Merger Process

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3417]
https://18xx.games/game/23572?action=539

Here TIE53 is asked if they want to trade-up for a full-share in the merged company, or sell their share, but the price for neither option is displayed. It would be helpful to see the cost/sale price for the trade-in/sale.

**Comment by crericha** [comment]
@Maxwell-Frank, how does this look? Is it clear that you are spending money for exchange and gaining money for the sell?
![image](https://user-images.githubusercontent.com/67359577/105120060-89046a80-5a9f-11eb-814e-c8820abecf93.png)

**Comment by Maxwell-Frank** [comment]
@crericha This looks good to me. I think most players will understand that exchanging involves paying money and selling involves receiving money, anyway.  I think it will make players' decisions easier to see the numbers right there on the buttons.
