### ISSUE TITLE
[18Mag] Display Share Company Stock Movement Chart on Info Tab

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3419]
It would be helpful during the ORs to see the share company stock movement chart to help players decide which companies to pay their money to, etc.  I assume it appears during the share company step, but it could be helpful to display in the ORs as well.

**Comment by roseundy** [comment]
Actually, it doesn't show even for the share companies during the pay dividends step. The current code makes this very difficult, but I understand the desire for it.

**Comment by Maxwell-Frank** [comment]
It should be simple to add to the info tab, though, right? At least if it's there it can be referenced during the pay dividends step.
