### ISSUE TITLE
[1849] Terrain cost appears on floating preview tile before placing

### ISSUE THREAD

**Issue by erperreault** [tobymao/18xx#3422]
OR 5.2, IFT tries to lay gentle curve dit on G13. The floating preview tile has a terrain cost on it - I don't think this is intended? I went back and master moded it again, then tried in hotseat and it happened consistently.

Game ID: 23602
https://18xx.games/game/23602

**Comment by erperreault** [comment]
I haven't been able to reproduce this bug locally, but in hotseat I have found some more info.

On IFT's turn in OR 4.1, there are zero unplaced remaining #58 tiles (the one in question). One is replaced on the map at G9, where there is an $80 terrain cost. 

Somehow that terrain cost is still attached to the #58 tile rather than the location going forward. The very next turn, CTL in 4.1, can lay a #58 at H4. It displays the terrain cost on the preview #58 tile but not the other possible tiles.

**Comment by tysen** [comment]
Thanks for the report @erperreault. I think I know what causes this and will submit a fix soon.
