### ISSUE TITLE
1817: Cannot buy shares in same SR after closing short position(s)

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#3423]
https://18xx.games/hotseat/hs_kpcqehmt_21676?action=1644

A 5-share UR started with 3 shares owned by President, and 6 shares in market due to 2 shorts from previous SR, each owned by two players (total: 9 shares).  One player closed their short position by buying two market shares.  This player was unable to buy the remaining 4 shares from market and take over the company, in fact, they were unable to buy any shares.

But, after closing their short positions (aka buying market shares), the only option they were offered was to short the company.

**Comment by jenf** [comment]
Can you provide hotseat data as we do not have access to it.

**Comment by Akado05** [comment]
Sure thing, boss!
[1817shorts.txt](https://github.com/tobymao/18xx/files/5843741/1817shorts.txt)

**Comment by jenf** [comment]
G3 & Akado are at cert limit and so cannot buy.
Shorts don't count to your cert limit so you can cancel those

**Comment by Akado05** [comment]
I have so many regrets.  Sorry!
