### ISSUE TITLE
[18Mag]  Suggestions for graphics re: first round

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#3434]
I'm finding a lot of flipping between the tabs in the first round:  The Entities Tab to see who own what, the Map tab to see where minors are and the Game tab in order to act.

Would it be possible to put unclaimed minors as grey/shaded markers on the map and then have them go to black once they are claimed?  Also, listing minors in the game tab player cards would help keep track of who has claimed what.  

(On a certain level, I want the minors to be color-coded to players, maybe even only as an option like coordinates, but I also feel like that goes against the design aesthetics, so while it might be helpful, it's probably not a great idea.)

**Comment by roseundy** [comment]
Adding minors to the player cards during the draft and stock rounds is very doable.

I'll have to think about changing the token shading. There is no easy support for this at the moment.

**Comment by SmithInMN** [comment]
Thanks for the quick response.

Not having the tokens on the map would make things more confusing, so something needs to be there, but I can see how there would never have been anything conditional built into that element of the tokens.  Either it's there or it isn't.

Especially late in the round, it's hard to remember what has been taken and what hasn't...  and what is in a region that's important and what isn't.  Putting the player cards with the minors listed on the map tab will make it too cluttered, so that doesn't work.

I feel like there has to be a good solution, but I'm struggling to figure out exactly what that is.

**Comment by roseundy** [comment]
I'm adding minor tokens to player cards.
I'm also changing the starting map to use reservations rather than placing tokens initially.
