### ISSUE TITLE
[1828.games] Company not Allowed to use D&H on First Operating Turn

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3436]
https://18xx.games/game/23759?action=232

If the CPR purchases the D&H on their turn, they seem to not be able to use the teleport power, even if purchased before their track laying step. This may be a bug related to the fact that the game thinks placing the home token is placing a station that turn?

**Comment by crericha** [comment]
I cloned the game and I was able to teleport and lay the token. I had to refresh the browser for the hex to appear available for tile lay. I believe that piece is a general bug that needs verification in other games with a teleport. Also, after the tile was laid, the hex again appeared to not be available; however, it still allowed me to place a token.

@Maxwell-Frank, did you try refreshing the page? I want to verify if we are seeing the same behavior or different.

**Comment by Maxwell-Frank** [comment]
@crericha The private wasn't even showing up on the list of abilities, so we didn't think to refresh. Maybe that was the correct solution, but we forgot :(

**Comment by crericha** [comment]
I would call it a workaround at best. :-) Either way, I'll take a look when I get an opportunity.

**Comment by ventusignis** [comment]
When I made a hotseat game, I had the N&W, a corp which had operated in prior rounds, buy the private and it couldn't use the ability, even with a refresh
https://gist.github.com/ventusignis/5a2a75e50acb7e2eff65b93e276cbc57

**Comment by Maxwell-Frank** [comment]
It looks like the confusion has arisen from the way the D&H is implemented.  Instead of being used as an ability (like the teleport privates are in 1846 and other games), Scranton is just shown as a track lay option for the owning company.  I would suggest that this be implemented in a way consistent with the other games on the 18xx.games.

**Comment by Maxwell-Frank** [comment]
https://gist.github.com/Maxwell-Frank/b5a9e143cca167946cc4e9cda977b259

I cloned the game in question.  NW is allowed to spend the $120 to lay a track in Scranton as its normal track lay (since it has the D&H power). However, during the token laying step, Scranton is greyed out, like a city in which a company is not allowed to token.  You can click on the greyed out city to token there, but it's very confusing. 

Additionally, the current implementation allows the company to place a free token **anywhere** on the turn it utilizes the D&H power.   The NW is allowed to token Washington for free on the turn the D&H power is utilized.  It should only be able to token Scranton for free.

**Comment by crericha** [comment]
1828 does used the standard ability. To clarify, on 18xx.games, there is a teleport ability and a token ability. The teleport ability allows you to place a tile and station without connectivity. This was implemented for 18Chesapeake and is also used by 1828, 1835, 1836jr, and 1856. The token ability allows you to place a station only. This was implemented for 1846 and also used in 18LA, 18GA, 18MS, and 1882.

There are known bugs with the base teleport ability: https://github.com/tobymao/18xx/issues/1520, https://github.com/tobymao/18xx/issues/2745. These are on @michaeljb's todo list.

Also, our goal is to move away from having to click on an ability to use it. Ideally, the game should prompt you if you are in a situation to use it. We are moving steadily towards this, but there is a ways to go.

**Comment by Maxwell-Frank** [comment]
Thanks. I do wish it was clearer, but I understand the intent.  Is this something we could add to the implementation notes in the wiki just for confirmation?

**Comment by crericha** [comment]
I agree the interface for the ability is not straightforward and we need to make it clearer. I may work on it once 1828.Games is in beta if Michael doesn't have an opportunity to.

The wiki is open to anyone to update. Feel free to add. Being that you've logged more 1828.Games plays than I have to this point, I expect you could make some good contributions there. Also, thank you for all the bug reports. It has been very helpful!
