### ISSUE TITLE
[18SJ] -- Nationalization Delayed

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#3437]
https://18xx.games/game/22906

Nationalization does not occur at the beginning of Phase 4, it happens after the subsequent corporation runs.  See timestamp for Phase 4.  This issue only happens with one scenario in that game, where the dividends were paid out and the private for 1/2 price train was used.  It did not happen if the dividends were withheld and the private was not used.

**Comment by jenf** [comment]
https://18xx.games/game/22906?action=435

**Comment by perwestling** [comment]
If phase 4 begins with a normal train buy STJ becomes nationalized directly: https://18xx.games/game/22906?action=415
But, as reported noticed, there is a bug in case the ability is used to buy the train via half price.
Good catch. I will fix it.
