### ISSUE TITLE
"Show Last Route For" feature does not show routes from trains being phased out

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#3449]
https://18xx.games/game/22827#map

PRR ran for $590 with two 2 trains, a 3/5 train, and a 5 train:
https://18xx.games/game/22827?action=404

However the "Show Last Route For" feature does not show the routes for the 2 trains which have rusted:
<img width="838" alt="Screen Shot 2021-01-21 at 9 12 58 PM" src="https://user-images.githubusercontent.com/5924761/105449938-3311fd00-5c2e-11eb-93de-968685567928.png">

**How to Reproduce the Bug?**
- Run a route with a train that is being phased out
- Go to the Map tab and select the company that ran a train being phased out
- Observe that the route for the phased out train does not display

Safari desktop: Version 14.0.2 (16610.3.7.1.9)

**Comment by dmitton42** [comment]
I've seen this in a game where all my trains phased out, and I bought a new one, but the Show Last Route for:  button did not even appear in the next OR.   I couldn't look at other corps either.

**Comment by bentziaxl** [comment]
Show Last Route is no longer an ability as far as i can tell. can close

**Comment by dfannius** [comment]
It's now called Show Last Route and Tile but it is still a feature(and I just confirmed that this bug still exists).

**Comment by bentziaxl** [comment]
sorry my bad
