### ISSUE TITLE
Suggestion: daily digest option for turn emails

### ISSUE THREAD

**Issue by BGarmon80** [tobymao/18xx#3451]
Is it possible to create an email option that fires off at midnight telling you in one email which games is your turn at? Essentially a daily reminder rather than the multiple emails I get per day every time it's my turn. I'm extremely active on the site but still get a flood of these.

**Comment by tobymao** [comment]
Yea that's a good idea. A temporary option is for you to turn off email notifications in your profile (because you're very active).

**Comment by tobymao** [comment]
close in favor of webhook notifications
