### ISSUE TITLE
1867/1882 Neutral tokens aren't displayed correctly in simple tokens mode

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#3452]
https://18xx.games/game/22140
Enabling simple tokens shows 'CN' instead of 'N'

**Comment by scottredracecar** [comment]
Can we just turn off simple tokens for 1882? I think the current tokens are better presented in all respects than the simple token implementation anyway.

Possibly in the future, simple tokens will have some kind of extra advantage like color blindness accommodations, but it doesn't do that right now as far as I know.

**Comment by jenf** [comment]
there aren't simplified tokens for 82, it's just a bug which caused the wrong token to be used.
