### ISSUE TITLE
All titles:  show game log window on Spreadsheet and Map tabs 

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#3453]
Currently, the game log is only displayed on the "Game" tab of each title.

I would like the game log to *also* be displayed on the "Spreadsheet" and "Map" tabs.

The use case is: when it it my turn, and I am reviewing the moves made since my last turn, it is very helpful to be able to see the map and/or the spreadsheet view on the *same screen* as I scroll through the log.  ATM you have to toggle back and forth between screens.  This, in itself, is currently frustrating because when you switch back to the Game tab, the game log window has reset to the latest move - it's not even displaying where you may have last scrolled to (but that's a separate issue; see my other recently submitted feature request).

I understand 'all titles' is a lot of work, so my top request would be 1846.

**Comment by benjaminxscott** [comment]
I see what you're saying, although adding the game history to Map/Spreadsheet seems like it would lose valuable real-estate for mobile users

**Comment by waaayback** [comment]
I think mobile users (including me) can scroll down a little more :)  Every screen already requires a fair amount of scrolling on mobile!

As I said above, if you can fix the game log window so it persists the scroll location when you tab away and come back, that might be a good enough solution.  But I still think this feature would be useful.

**Comment by tobymao** [comment]
no plans
