### ISSUE TITLE
1849: Add wiki page

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#3455]
https://github.com/tobymao/18xx/wiki contains wikis for the titles available at 18xx.games.

1849 does not seem to have any yet. We should add one.

**Comment by scottredracecar** [comment]
I started a stub for this.
https://github.com/tobymao/18xx/wiki/1849

**Comment by Maxwell-Frank** [comment]
I can put this together later this weekend unless someone wants to beat me to it.

**Comment by scottredracecar** [comment]
Somehow I doubt that will happen. 😀

**Comment by Maxwell-Frank** [comment]
The 1849 wiki is no longer a stub: https://github.com/tobymao/18xx/wiki/1849
