### ISSUE TITLE
[18Mag] Unable to place #6 tile on Kolozsvar (F23)

### ISSUE THREAD

**Issue by ikelly** [tobymao/18xx#3462]
**What's your Game ID?**

https://18xx.games/game/23603
(pinned to version e9ae9a4e)

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

I clicked on Kolozsvar (F23) during minor company #5's track-laying turn.
I expected to be able to place a #5, #6, or #57 tile (all are available), but only the #5 and #57 appear as options.

Please include screenshots (you can drag and drop or upload them into this issue)

![Screenshot 2021-01-22 141641](https://user-images.githubusercontent.com/1767452/105548240-9f3b4200-5cbc-11eb-9125-14625a43d50e.png)

**Which Browser / Platform?**
Google Chrome 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)
Desktop

**Comment by roseundy** [comment]
I'll have to dig into this.

**Comment by ikelly** [comment]
I also can't seem to upgrade to a #88 (green X with a small city) at G22.

![Screenshot 2021-01-22 155059](https://user-images.githubusercontent.com/1767452/105557516-ae74bc80-5cc9-11eb-9853-5b6aba99b338.png)

**Comment by ikelly** [comment]
Actually, I got confused and the #88 is expected, my track doesn't go into the city that way. It doesn't explain the issue with the #6 though

**Comment by roseundy** [comment]
I root caused this to not properly clearing the temporary "K" label off the yellow tiles placed on the K hexes when they are upgraded to green. Basically the 6-tile you wanted got corrupted because it was used and then came off one of the K hexes.
