### ISSUE TITLE
Add button to copy human readable transcript text

### ISSUE THREAD

**Issue by thepackrat** [tobymao/18xx#3469]
It would be great to have a button to copy the human readable transcript text from the history box (including chat message) into the clipboard so that it could be pasted somewhere as a record. 

This would appear next to undo/redo or in the a corner of the transcript box and could be an icon rather than text to save space.

**Comment by Maxwell-Frank** [comment]
Maybe "copy transcript" could be added on the Tools tab with the "copy game data" buttons.
