### ISSUE TITLE
Chat: local messages' timestamps don't match

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#347]
All messages' timestamps appear to be UTC, but when I enter a message it is displayed with a timestamp in my local time zone (UTC-4). If I refresh the page, the timestamp for my previous messages changes back to UTC.

**Comment by tobymao** [comment]
this is because when you enter the chat yourself, you render it immediately before it hits the server as opposed to when you receive messages you get them from the server

**Comment by sparr** [comment]
Can we instead render all the timestamps in localtime?

**Comment by dfannius** [comment]
Looks like this was closed because it was fixed.
