### ISSUE TITLE
[1828.games] Unsellable Privates do not close when associated company is merged into a system prior to buying a train

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3470]
https://18xx.games/game/24023?action=466

In this game Aavar merged the OS&H and NYH before either company had operated.  When this shell company purchased a train, the OS&H private should have closed, but it did not.

**Comment by crericha** [comment]
Is it specifically the shell or if the system buys a train? Do you know?

**Comment by Maxwell-Frank** [comment]
The player moved a train into the specific shell the next OR after we noticed the error and that still did not close the private.

**Comment by crericha** [comment]
I found the rule. 

"At the start of red phase or when the matching share company or a system including that share company as a constituent has acquired a train."

So it looks like if either shell purchases, the private closes.

**Comment by crericha** [comment]
All fixed, but it breaks your current game. I'll commit the fix once your game ends.

**Comment by Maxwell-Frank** [comment]
Thanks. Another bug may have irreparably broken our game, so we might be done sooner rather than later.

**Comment by tobymao** [comment]
Why? That's what pinning is for.

**Comment by crericha** [comment]
I thought we didn't pin alphas and they are almost done.

**Comment by tobymao** [comment]
That's more of a choice rather than a rule.
