### ISSUE TITLE
Make the token rings that denote corp owner optional

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#3471]
I totally dig the idea, but in practice I find it too busy, plus the same ring color can look quite different depending on what color token it's around so it's actually still hard (for me) to see which corps have a common owner anyway. In any case, it would be nice if this feature were user-toggleable like the simplified tokens are.

**Comment by scottredracecar** [comment]
It's a toggle on the map screen "Hide Player Colors".

**Comment by dfannius** [comment]
Thanks! I assumed the place to look was the same place as the simplified tokens toggle.
