### ISSUE TITLE
General Setting to "show player colors" that adds player colors everywhere, also to border of player's entity table and spreadsheet table

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#3478]
The "show player colors" is a very useful feature for games such as 18Mag, thank you for the existing implementation.  It would be nice to have the option to add the same colored border around the player's entity tables (the grey summaries of holdings under entities, etc.) and the header of the player's columns in the spreadsheet table.  This could be a settings toggle that would turn it on/off for the whole game so that players are identified by color throughout.

**Comment by tobymao** [comment]
seems a bit excessive

**Comment by jenf** [comment]
Dup of #2207
