### ISSUE TITLE
Smaller fonts for simplified logos

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3488]
It would be nice if NYSW, NYOW, D&LW text fit in the circles as well as Belt does, instead of being cropped at the edges.

<img width="523" alt="Screen Shot 2021-01-23 at 6 33 30 PM" src="https://user-images.githubusercontent.com/8732435/105619641-a0966880-5da9-11eb-9d2d-543809eb1ffb.png">

**Comment by dfannius** [comment]
Even better, I'd like the size of the font to be dynamic, so that R could be in a bigger font than UR, which would be bigger than A&A, etc.

**Comment by yzemaze** [comment]
prod vs. testing
![image](https://user-images.githubusercontent.com/33390595/110221030-fcd0ca00-7ec9-11eb-9b5b-3b45656f728e.png)
![image](https://user-images.githubusercontent.com/33390595/110221032-ff332400-7ec9-11eb-8538-976c568bce14.png)

Would this work for you?

**Comment by ChrisTheCat** [comment]
I dunno, having variable font sizes seems weirder somehow

**Comment by scottredracecar** [comment]
I don’t like the testing one at all. I don’t think anything should be vertically stretched, only horizontally shrunk. In the example, prod is fine for everything except NYOW.

Perhaps the single character R could be a little bigger as well, but I am also fine with it as is.

**Comment by yzemaze** [comment]
4+ syms have a font-size of 87.5%, everything else has the same font-size (height).
There’s nothing vertically stretched. Only the length/width of the text and the width of the glyphs are adjusted so they fit the circle.

**Comment by dfannius** [comment]
Is it easy to try a system in which the height/width ratio of the letters doesn't change, just their size? I don't like the condensed look of NYOW in the "testing" examples above. I'd like to see what varying font-size, but nothing else, would look like. (I'd even like to increase the font-size for shorter strings, so the "logo" always uses as much of the disc as it reasonably can.)

**Comment by yzemaze** [comment]
R not as wide, 4+ font-size 75%
![image](https://user-images.githubusercontent.com/33390595/110221478-c9dc0580-7ecc-11eb-9917-577c0344a5f0.png)

**Comment by scottredracecar** [comment]
NYOW, R, and GT look good. The rest should go back to their prod versions IMO.

**Comment by dfannius** [comment]
That all looks good to me (except for Belt looking a little squashed, but I think that's due to the resolution of the screenshot).

**Comment by scottredracecar** [comment]
Belt and Bess both look vertically squashed to me. A&A and A&S both look vertically stretched or horizontally squashed.

**Comment by scottredracecar** [comment]
For me the priorities are:

- If the letters fits in prod, then any manipulation should retain the proportions.
- If the letters are too wide in prod, then horizontally shrinking a little to make it fit is good (don't vertically stretch).
- It's okay to not take up the entire token--a single letter will be easy to differentiate from two letters from three letters.

**Comment by dfannius** [comment]
While my (incompatible) priorities are

- Letters should fit on the token
- Never change the proportions of the font (to condense or expand). If you have to shrink horizontally, shrink the same vertically.
- Increasing the font size as the symbols get shorter (even for 1- or 2-character symbols) will make simplified logos even more distinct from each other, and this is a good thing

But I'm certainly not going to throw a tantrum if I don't get my way, I'm just expressing my opinions. (And of course I reserve the right to change my mind after seeing the results.)

To be honest I think I need to see higher-res samples than these to really judge them.

**Comment by scottredracecar** [comment]
The reason that I am not 100% in favor of increasing the size of the 1/2 letter ones is that we have information that is a higher level of importance at that size, like revenues and terrain costs. So keeping the text small prevents "information overload" of text to consider at that size. I can focus on the relevant stuff rather than that getting drowned out by bigger text of companies.

However, I do see the good side of making the short companies bigger--namely ease of reading without squinting.

**Comment by scottredracecar** [comment]
I notice that H and WT are still small in 1817 and friends.

**Comment by yzemaze** [comment]
@scottredracecar 
Link?
![image](https://user-images.githubusercontent.com/33390595/110339405-7088e900-8028-11eb-81dd-617bd2c5f518.png)
https://18xx.games/game/31471?active=9#map
Ensure simple_logos is checked in profile (for now).

**Comment by scottredracecar** [comment]
Yes, simple logos are on of course because I don't see the graphical image.

Strangely, I see different behavior in various os/browser configurations I use.

In macOS chrome, I see the old unchanged small text logos.
![image](https://user-images.githubusercontent.com/29106780/110340745-34856200-7fef-11eb-89f6-b3863c01ab00.png)

In macOS safari and iOS Chrome, I see the expected new logos
![image](https://user-images.githubusercontent.com/29106780/110340805-46670500-7fef-11eb-9ddd-77997aa83ae1.png)

In iOS safari, I see the mixed version. (screenshot in next post).

**Comment by scottredracecar** [comment]
![image](https://user-images.githubusercontent.com/29106780/110341088-980f8f80-7fef-11eb-9755-7a28e7ff6cfb.png)

**Comment by scottredracecar** [comment]
Okay, probably it was a caching issue I am guessing.

**Comment by scottredracecar** [comment]
I still see inconsistent behavior among various browser configurations, but I assume this will clear itself up in time. Even after clearing the site data, I still see small logos in macOS Chrome, but I am satisfied this will be self-rectify eventually.

**Comment by scottredracecar** [comment]
Okay, my caching issue seems to be resolved now. They look as I expected they would with the intended change.

PLE looks a little horizontally stretched more than it should. The others look proportional or intentionally horizontally shrunk.
![A3FFE43E-EB5C-4A2A-BF3F-E284104D6B41](https://user-images.githubusercontent.com/29106780/110357934-715a5480-8001-11eb-9bc7-95e101f823eb.png)
