### ISSUE TITLE
1828.games: C&P minor company skips "running train step"

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#3498]
In 1828.games the C&P minor company skips his running train step without using his 2 train and earns nothing.

game ID 23033

  {
      "id": 280,
      "type": "undo",
      "entity": "NKP",
      "entity_type": "corporation",
      "user": 4301,
      "created_at": 1611496349
    },
    {
      "type": "pass",
      "entity": "NKP",
      "entity_type": "corporation",
      "id": 281,
      "created_at": 1611496358
    },
    {
      "type": "lay_tile",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 282,
      "created_at": 1611496459,
      "hex": "B20",
      "tile": "57-5",
      "rotation": 0
    },
    {
      "type": "undo",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 283,
      "created_at": 1611496478
    },
    {
      "type": "pass",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 284,
      "created_at": 1611496484
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 285,
      "created_at": 1611496489
    },
    {
      "type": "pass",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 286,
      "created_at": 1611496499
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 287,
      "created_at": 1611496503
    },
    {
      "type": "pass",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 288,
      "created_at": 1611496513
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 289,
      "created_at": 1611496521
    },
    {
      "type": "undo",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 290,
      "created_at": 1611496524
    },
    {
      "type": "redo",
      "entity": "NKP",
      "entity_type": "corporation",
      "id": 291,
      "created_at": 1611496528
    },
    {
      "type": "pass",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 292,
      "created_at": 1611496537
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 293,
      "created_at": 1611496542
    },
    {
      "type": "pass",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 294,
      "created_at": 1611496705
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 295,
      "created_at": 1611496711
    },
    {
      "type": "pass",
      "entity": "C&P",
      "entity_type": "minor",
      "id": 296,
      "created_at": 1611496857
    }
  ],
  "loaded": true,
  "created_at": 1610742445,
  "updated_at": 1611496358
}

**Comment by Aavar77** [comment]
Its cause C&P skip laying track.

**Comment by crericha** [comment]
Correct, Aavar. It is a private company, not a minor. Here is the pertinent rule from section 13.2.25.

>  If the player does not place or upgrade a track tile or there is
only one revenue center on the route from the placed track
tile, then the COBOURG & PETERBOROUGH RAILWAY
does not pay any revenue.
