### ISSUE TITLE
1849, unable to use SMS with RCS in Catania

### ISSUE THREAD

**Issue by fabianpk** [tobymao/18xx#3499]
In game https://18xx.games/game/23954 we tried to use SMS private to teleport a token into Catania, but we are unable to upgrade the tile to green and set the token there. It is possible to put the token in Messina however. So seems to be a bug.

**Comment by scottredracecar** [comment]
I think we hit the same issue in 49K2S. Player wants to close SMS to upgrade and token in P2 and is unable.
[sms.txt](https://github.com/tobymao/18xx/files/5863049/sms.txt)
