### ISSUE TITLE
Game ID 48: SR ends after sale of a stock

### ISSUE THREAD

**Issue by jaeisma08** [tobymao/18xx#35]
EisVrouw81 floated UR and then sold a share of UR. The other two players both passed. The game moved to an OR, not giving EisVrouw81 the option to pass or buy a share of another company. EisVrouw81 had sufficient funds to purchase a share of a different company.

We backed it up, and tried again. EisVrouw floated UR. The other two players both passed. The game gave EisVrouw the option to sell a share or pass. EisVrouw sold a share of UR, and the game moved immediately to an OR without giving EisVrouw the option to purchase a share.

**Comment by tobymao** [comment]
will look tonight

**Comment by tobymao** [comment]
can you possibly give me a bit more detail so i can try to recreate this?

**Comment by jaeisma08** [comment]
In the midst of typing out the specifics, I realized the issue. EisVrouw81 had $70 and wanted to buy a share of either IR or TER. At the time, both were at a market price of $70, but there were no shares in the market. The par price of both companies was $75.

**Comment by tobymao** [comment]
sweet, thanks for validating!
