### ISSUE TITLE
[1849] Losing the double share after a change in presidencies

### ISSUE THREAD

**Issue by basselhak** [tobymao/18xx#3502]
In game https://18xx.games/game/23968, stock round 3, ATA is dumped by Lior on Basselhak. 

Basselhak holds 40%, two 10% shares, one 20% share. 

As Lior dumps presidency and his two 10% shares, Basselhak's double share is converted to the presidency, and he is left with presidency and two 10% shares. He should have had the option to keep the double share and exchange the two 10% shares for the presidency.

**Comment by tysen** [comment]
That's not what the rules say:

>When changing control of a president’s certificate, if the incoming president has the “last certificate,” the outgoing president may choose whether to exchange the president’s certificate for the “last certificate,” or for two single shares owned by the incoming president.

The outgoing president has the choice, not the incoming.

**Comment by tysen** [comment]
The actual bug is that Lior should have been given the option. In practice you probably very rarely want to permit your opponent to retain the double cert, but it could happen.

**Comment by basselhak** [comment]
Ah, sorry, we missed that bit in the rules. But regardless, neither Basselhak nor Lior were given a choice.
