### ISSUE TITLE
Filter log based on type of event/step of the turn

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#3510]
Currently the log is one big long list of events, and is quite verbose.   This makes finding events of interest difficult, and given that the log is also tightly bound to the game state presumably reducing verbosity is challenging. 

**Potential solution**
Add controls to filter the log based on the type of action: track lays, tokens, train purchases and train routes are potential filters, though whatever's easiest to implement based on how the log is implement is a good starting point.

**Comment by jenf** [comment]
This would be very complicated to implement and other tickets would go a long way to improving this
