### ISSUE TITLE
[1846] A newly laid yellow not being allowed to be upgraded

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3511]
6.43 Limit: Each Operating Round, a corporation may lay one
yellow tile in an empty tan hex and it may either lay a second
yellow tile or upgrade one tile. All tile lays and upgrades cost
money (see below) and are optional. A corporation laying two
tiles or a tile and an upgrade does so sequentially in any order.
NOTES: If desired, _a given tile may be laid and then upgraded._

emphasis mine

Here's a json if you want to take a look. Moe just placed a yellow in Cincinnati (h12), and cannot upgrade it.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Moe",
      "entity_type": "player",
      "id": 1,
      "created_at": 1611518785,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Larry",
      "entity_type": "player",
      "id": 2,
      "created_at": 1611518789,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Curly",
      "entity_type": "player",
      "id": 3,
      "created_at": 1611518794,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Moe",
      "entity_type": "player",
      "id": 4,
      "created_at": 1611518798,
      "company": "Pass (2)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Larry",
      "entity_type": "player",
      "id": 5,
      "created_at": 1611518800,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Curly",
      "entity_type": "player",
      "id": 6,
      "created_at": 1611518804,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Moe",
      "entity_type": "player",
      "id": 7,
      "created_at": 1611518808,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "Larry",
      "entity_type": "player",
      "id": 8,
      "created_at": 1611518813,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "pass",
      "entity": "Curly",
      "entity_type": "player",
      "id": 9,
      "created_at": 1611518837
    },
    {
      "type": "pass",
      "entity": "Moe",
      "entity_type": "player",
      "id": 10,
      "created_at": 1611518848
    },
    {
      "type": "bid",
      "entity": "Larry",
      "entity_type": "player",
      "id": 11,
      "created_at": 1611518921,
      "company": "MS",
      "price": 60
    },
    {
      "type": "par",
      "entity": "Curly",
      "entity_type": "player",
      "id": 12,
      "created_at": 1611518968,
      "corporation": "NYC",
      "share_price": "70,0,7"
    },
    {
      "type": "par",
      "entity": "Larry",
      "entity_type": "player",
      "id": 13,
      "created_at": 1611519084,
      "corporation": "GT",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "Moe",
      "entity_type": "player",
      "id": 14,
      "created_at": 1611519113,
      "corporation": "B&O",
      "share_price": "70,0,7"
    },
    {
      "type": "buy_shares",
      "entity": "Curly",
      "entity_type": "player",
      "id": 15,
      "created_at": 1611519118,
      "shares": [
        "NYC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Larry",
      "entity_type": "player",
      "id": 16,
      "created_at": 1611519122,
      "shares": [
        "GT_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Moe",
      "entity_type": "player",
      "id": 17,
      "created_at": 1611519126,
      "shares": [
        "B&O_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Curly",
      "entity_type": "player",
      "id": 18,
      "created_at": 1611519131,
      "shares": [
        "NYC_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Larry",
      "entity_type": "player",
      "id": 19,
      "created_at": 1611519137
    },
    {
      "type": "pass",
      "entity": "Moe",
      "entity_type": "player",
      "id": 20,
      "created_at": 1611519138
    },
    {
      "type": "pass",
      "entity": "Curly",
      "entity_type": "player",
      "id": 21,
      "created_at": 1611519139
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 22,
      "created_at": 1611519148,
      "hex": "B16",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 23,
      "created_at": 1611519151,
      "hex": "C13",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 24,
      "created_at": 1611519155,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ],
          "hexes": [
            "B16",
            "C15"
          ],
          "revenue": 60,
          "revenue_str": "B16-C15"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 25,
      "created_at": 1611519163,
      "hex": "G9",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 26,
      "created_at": 1611519167,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 27,
      "created_at": 1611519170,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ],
          "hexes": [
            "G7",
            "G9"
          ],
          "revenue": 40,
          "revenue_str": "G7-G9"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 28,
      "created_at": 1611519187,
      "hex": "E19",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 29,
      "created_at": 1611519195,
      "hex": "E17",
      "tile": "291-0",
      "rotation": 3
    },
    {
      "type": "place_token",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 30,
      "created_at": 1611519197,
      "city": "291-0-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 31,
      "created_at": 1611519200
    },
    {
      "type": "sell_shares",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 32,
      "created_at": 1611519204,
      "shares": [
        "NYC_3",
        "NYC_4",
        "NYC_5",
        "NYC_6"
      ],
      "percent": 40,
      "share_price": 60
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 33,
      "created_at": 1611519216
    },
    {
      "type": "undo",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 34,
      "created_at": 1611519220
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1611519226,
      "hex": "E17",
      "tile": "293-0",
      "rotation": 1
    },
    {
      "type": "sell_shares",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 36,
      "created_at": 1611519232,
      "shares": [
        "NYC_3",
        "NYC_4",
        "NYC_5",
        "NYC_6"
      ],
      "percent": 40,
      "share_price": 60
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 37,
      "created_at": 1611519235
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 38,
      "created_at": 1611519238,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1611519238,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 40,
      "created_at": 1611519240,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 41,
      "created_at": 1611519295
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 42,
      "created_at": 1611519301
    },
    {
      "type": "sell_shares",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1611519346,
      "shares": [
        "B&O_2",
        "B&O_3",
        "B&O_4"
      ],
      "percent": 30,
      "share_price": 60
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1611519357
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1611519361,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1611519368,
      "train": "2-6",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1611519377
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 48,
      "created_at": 1611519380
    },
    {
      "type": "sell_shares",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1611519389,
      "shares": [
        "GT_2",
        "GT_3",
        "GT_4"
      ],
      "percent": 30,
      "share_price": 70
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 50,
      "created_at": 1611519408,
      "hex": "C11",
      "tile": "8-1",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1611519410,
      "hex": "D10",
      "tile": "8-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1611519416
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1611519426,
      "train": "4-0",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1611519451
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1611519456
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 56,
      "created_at": 1611519461,
      "hex": "D8",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 57,
      "created_at": 1611519466,
      "hex": "D6",
      "tile": "298-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 58,
      "created_at": 1611519471,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ]
          ],
          "hexes": [
            "D6",
            "C15"
          ],
          "revenue": 80,
          "revenue_str": "D6-C15"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 59,
      "created_at": 1611519477,
      "hex": "G11",
      "tile": "8-3",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 60,
      "created_at": 1611519481,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ],
          "hexes": [
            "G9",
            "G7"
          ],
          "revenue": 40,
          "revenue_str": "G9-G7"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1611519488,
      "hex": "C15",
      "tile": "294-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 62,
      "created_at": 1611519496
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 63,
      "created_at": 1611519505,
      "company": "MS",
      "price": 60
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1611519513
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 65,
      "created_at": 1611519515
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 66,
      "created_at": 1611519523,
      "company": "MS",
      "price": 60
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1611519525,
      "city": "298-0-2",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 68,
      "created_at": 1611519534
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 69,
      "created_at": 1611519540,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "D6",
              "C5"
            ],
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ],
            [
              "C17",
              "C15"
            ]
          ],
          "hexes": [
            "C5",
            "D6",
            "C15",
            "C17"
          ],
          "revenue": 230,
          "revenue_str": "C5-D6-C15-C17 + E/W"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 70,
      "created_at": 1611519543,
      "kind": "payout"
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 71,
      "created_at": 1611519552,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1611519566
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 73,
      "created_at": 1611519569
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1611519584,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "place_token",
      "entity": "C&WI",
      "entity_type": "company",
      "id": 75,
      "created_at": 1611519591,
      "city": "298-0-3",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 76,
      "created_at": 1611519596,
      "hex": "E7",
      "tile": "7-0",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 77,
      "created_at": 1611519600,
      "hex": "D8",
      "tile": "24-0",
      "rotation": 4
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 78,
      "created_at": 1611519609,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "place_token",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 79,
      "created_at": 1611519613,
      "city": "294-0-0",
      "slot": 1
    },
    {
      "type": "assign",
      "entity": "MPC",
      "entity_type": "company",
      "id": 80,
      "created_at": 1611519620,
      "target": "D6",
      "target_type": "hex"
    },
    {
      "type": "run_routes",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 81,
      "created_at": 1611519646,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "D6",
              "C5"
            ]
          ],
          "hexes": [
            "C5",
            "D6"
          ],
          "revenue": 90,
          "revenue_str": "C5-D6 + Meat-Packing"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "D6",
              "E7",
              "D8",
              "D10",
              "C11",
              "C13",
              "C15"
            ]
          ],
          "hexes": [
            "C15",
            "D6"
          ],
          "revenue": 120,
          "revenue_str": "C15-D6 + Meat-Packing"
        },
        {
          "train": "2-4",
          "connections": [
            [
              "C15",
              "C17"
            ]
          ],
          "hexes": [
            "C17",
            "C15"
          ],
          "revenue": 90,
          "revenue_str": "C17-C15"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 82,
      "created_at": 1611519653,
      "kind": "half"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 83,
      "created_at": 1611519662,
      "train": "4-1",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 84,
      "created_at": 1611519673,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "place_token",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 85,
      "created_at": 1611519699,
      "city": "H12-0-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 86,
      "created_at": 1611519703
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 87,
      "created_at": 1611519709,
      "hex": "H12",
      "tile": "291-0",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 88,
      "created_at": 1611519880
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 89,
      "created_at": 1611519885,
      "hex": "F6",
      "tile": "9-2",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 90,
      "created_at": 1611519889
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 91,
      "created_at": 1611520033,
      "hex": "H12",
      "tile": "291-0",
      "rotation": 2
    }
  ],
  "id": "hs_kcuncutl_1611518764",
  "players": [
    {
      "name": "Curly"
    },
    {
      "name": "Larry"
    },
    {
      "name": "Moe"
    }
  ],
  "title": "1846",
  "description": "Cloned from game hs_hgjubpyr_1611518764",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-01-24",
  "loaded": true,
  "result": {},
  "turn": 1,
  "round": "Operating Round",
  "acting": [
    "Moe"
  ],
  "updated_at": 1611520033
}

**Comment by ryandriskel** [comment]
@jenf Seems this might be related to the new flag on upgrades?

**Comment by tobymao** [comment]
@ryandriskel this hasn't been changed in a 

TILE_LAYS = [{ lay: true, upgrade: true }, { lay: true, upgrade: :not_if_upgraded }].freeze

is the second not_if_upgraded wrong? if so can you apply the fix?

**Comment by jenf** [comment]
My bad
