### ISSUE TITLE
18Mag hide IPO

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3518]
There is no functional reason to display the IPO, which will never be used and will never have shares.

<img width="332" alt="Screen Shot 2021-01-24 at 3 19 32 PM" src="https://user-images.githubusercontent.com/8732435/105649263-6047f080-5e64-11eb-891d-5caafc8ec6e7.png">

If possible, it would be nice if the IPO were hidden in other games after it becomes irrelevant (e.g. most full cap games where you can't reissue shares or refinance).

**Comment by benjaminxscott** [comment]
Presumably there could be a game flag for this, which is checked [in the view](https://github.com/tobymao/18xx/blob/master/assets/app/view/game/corporation.rb#L369) to decide whether to render that row

**Comment by roseundy** [comment]
I was going to make this a game method with the default behavior that can be overridden
