### ISSUE TITLE
1849/Hex Trains - Live counter for edges traversed

### ISSUE THREAD

**Issue by LupoLoopy** [tobymao/18xx#3523]
For games which feature hex trains, it would be great to get a hex-side counter visualisation when defining routes, rather than a stop count. Although the 'too many sides' error serves this purpose, it's kind of jarring vs seeing a ticker go up and leads me to sometimes blindly brute force my routes a bit.

**Comment by jenf** [comment]
Yeah I've been hit by this as well, In general it'd be good to have a count of how many stops count for payout for other games

**Comment by LupoLoopy** [comment]
Yes. Agreed - having both on view would be better if an option!

**Comment by dfannius** [comment]
Implemented with #4066.
