### ISSUE TITLE
[18Chesapeake] Indicate unlimited tiles

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#3525]
In some games (18Chesapeake at least) tiles (e.g. 7, 8, 9) that are available in unlimited quantity are not indicated as such. For example, in 18Chesapeake, the numbers of thee times indicated are limited to those provided in the (AA) game box.

Wouldn't it be more accurate and helpful to indicate which tiles are unlimited on the tile manifest?

**Comment by benjaminxscott** [comment]
We could increase the number of tiles available if this is happening in practice?

For rendering, the engine could have some special value (like `99`) that gets rendered as an infinity symbol

I wouldn't personally prioritize it given that 20 tiles is effectively infinite, but seems like an easy patch if you/someone wants to implement it

**Comment by orome** [comment]
Yes: this is just about rendering. An issue of having too few tiles for play hasn't arisin.

**Comment by jenf** [comment]
This is already implemented in 1817, just needs the config to update to "unlimited"

**Comment by benjaminxscott** [comment]
Ah sweet, I added it for the only two games I understand, 1846 and 18chesapeake
