### ISSUE TITLE
[18MS] possible bug with extra tile lay in company's first OR?

### ISSUE THREAD

**Issue by DookTibs** [tobymao/18xx#3527]
See https://18xx.games/game/23704?action=76

![first_or](https://user-images.githubusercontent.com/6773412/105759098-a4df9480-5f15-11eb-9dab-ff7d3f26c66a.png)

I was president of L&N with board state as shown in that link and the above screenshot. My understanding of the rules is that in a public company's first OR, they get a free extra yellow tile lay.

In this game the interface would allow me to place two yellows, for instance:

![twoyellows](https://user-images.githubusercontent.com/6773412/105758691-271b8900-5f15-11eb-89e8-7d007f27df43.png)

But if I first upgraded a hex, for instance Selma, then it would not give me an option to do the free yellow tile lay:

![onegreen](https://user-images.githubusercontent.com/6773412/105758755-3dc1e000-5f15-11eb-8a8d-dd22dfd88ac1.png)

I may well have misunderstood this rule; maybe you can't combine an upgrade with the free tile lay; if that's the case then there's no bug at all.

This was on Google Chrome 88.0.4324.96 (Official Build) (x86_64), OSX 10.13.6.

**Comment by Maxwell-Frank** [comment]
You should definitely be allowed to upgrade and then lay a yellow. I swear this used to work. Maybe one of the recently added games broke it?

**Comment by tobymao** [comment]
@jenf

**Comment by jenf** [comment]
Probably not me, the code is quite explicit
[{ lay: true, upgrade: true }, { lay: :not_if_upgraded, upgrade: false }]

**Comment by jenf** [comment]
The rule is within
11.4.2 LAYING YELLOW TILES
so it looks like it's only allowed if you lay a yellow tile.

@perwestling could you confirm?

**Comment by Maxwell-Frank** [comment]
11.3.: 2. [companies may] Lay or upgrade one track tile, as described in 11.4. On its first operating turn only, a major company may lay an extra yellow tile before or after its normal tile lay. (Optional)

**Comment by ikelly** [comment]
I'm running into the reverse issue in https://18xx.games/hotseat/hs_entxotne_41281 where L&N has just laid its initial yellow tile at C9 and now wishes to upgrade into D10 but isn't allowed. Since 11.3.2 says the extra yellow tile is "before or after its normal tile lay" I thought that this would be allowed.

**Comment by ikelly** [comment]
For posterity from the game referenced above:

![image](https://user-images.githubusercontent.com/1767452/119302577-94b89700-bc21-11eb-867b-3732a690371f.png)

**Comment by ikelly** [comment]
Also see Mark Derrick's response in https://boardgamegeek.com/thread/2588190/extra-yellow-tile-can-it-be-combined-upgrade which is still not very clear about the possibility of placing an upgrade and a yellow tile but seems to be saying that the intention was that the tiles could be placed in any order.

**Comment by perwestling** [comment]
@ikelly Can you supply a gist for the hotseat game above?

From ticket instructions:
"If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`."

**Comment by ikelly** [comment]
@perwestling https://gist.github.com/ikelly/7572f0b346579761de9b0c690cffc464

**Comment by orome** [comment]
Though the rules are a bit garbled on this point,[ the charters are clear](https://boardgamegeek.com/thread/2705767/article/38502694#38502694):
> May lay one tile (two on first turn of operation), at most one of which may be an upgrade

**Comment by scottredracecar** [comment]
I tried to change it to this in the game @ikelly provided, but have thus far been unsuccessful.
          [{ lay: true, upgrade: true }, { lay: true, upgrade: :not_if_upgraded }]

**Comment by scottredracecar** [comment]
I added an errata for this on the errata page on the AAG site.

11.4.2 states “ On its first turn only, a major company may lay a subsequent yellow tile.” Change the word subsequent to “extra” to agree with the charters and 11.3.

**Comment by thepackrat** [comment]
@scottredracecar Could you also  amend 11.3 (2) "On its first operating turn only, a major company may lay an extra yellow tile before or after its normal tile lay **or upgrade**" to account for the rules making a distinction between upgrade and lay.

I would also. suggest codifying the ability to lay yellow and then upgrade it, elsewise it'll stay ambiguous.

**Comment by scottredracecar** [comment]
I know what you are getting at, but I would prefer to leave it for now with the colloquial "lay" meaning lay or upgrade. I understand this makes it harder to read very strictly, but I am trying to balance against having a lot of errata.
