### ISSUE TITLE
18Mag problem running plus train

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3531]
https://18xx.games/game/24062?action=250

Minor 4 should be able to run to two revenue locations using the 2 train and an additional two towns using the Plus upgrade.

<img width="734" alt="Screen Shot 2021-01-25 at 3 45 56 PM" src="https://user-images.githubusercontent.com/8732435/105780150-b67c6880-5f24-11eb-94d3-b6d2eb52e12a.png">

**Comment by roseundy** [comment]
Interesting. That's not how I interpreted the rule, but I can't think of a reason why you are wrong.

**Comment by ChrisTheCat** [comment]
Every (or almost every) game with plus trains allows the "large number" to be used for towns if there aren't enough cities to count. Otherwise, a 2 train running from a city to a town wouldn't be a legal route.
