### ISSUE TITLE
Won't let me run train through B7

### ISSUE THREAD

**Issue by AndrewChenUoA** [tobymao/18xx#354]
Game ID 404, tested on Chrome on Windows and Android.
Tosa Electric (TR) places a token on B7 Uwajima.
Then tries to run trains through or to B7 - B7 comes up as the route, but then no subsequent clicks add onto the run (and the "(Route must have at least 2 stops)" error is shown). Other runs on the network are still okay, and doesn't matter if it's a 2T or 3T.
Have tried also without the token, it presents the same issue.

**Comment by AndrewChenUoA** [comment]
Possibly related... in the same game, the previous company (KO) ran 2T, 2T, 3T like this:

KO pays out ¥290 = ¥29 x 10 shares
KO runs a 3 train for ¥50 (I4, J5)
KO runs a 2 train for ¥40 (K4, J5)
KO runs a 2 train for ¥50 (K4, K6, L7)
KO runs a 2 train for ¥50 (K4, J3, J1)
KO runs a 2 train for ¥50 (K4, K6, L7)
KO runs a 2 train for ¥50 (K4, J3, J1)
KO places a token on I4 for ¥40

**Comment by jenf** [comment]
I seem to be able to select a route fine for you on B7, B5, B3

Are you clicking on each hex?

**Comment by AndrewChenUoA** [comment]
Yes, clicking on each hex. Other routes are fine, it's just routes that
rely on B7. It's not working for the other players who have tried this on
my behalf either. I just tried again, it's not letting me go through B7.

**Comment by jenf** [comment]
Please note, that KO has managed to hit a bug (#279) they shouldn't have been able to, they should undo and redo their trains otherwise when we fix the bug the game will be invalidated.

**Comment by jenf** [comment]
@AndrewChenUoA if you could chat to me on the main page, maybe I can see whats going on

**Comment by AndrewChenUoA** [comment]
Sorry, missed each other due to time zone differences (we are in New Zealand). We were preserving game state, but we will rewind now. That will probably fix it.

**Comment by AndrewChenUoA** [comment]
We have redone the KO and gotten to the same point as before, and still can't run routes through B7. 
![image](https://user-images.githubusercontent.com/4627037/81510726-02bc5400-9368-11ea-8fce-6e88de3d045a.png)
In this state, clicking on other hexes does nothing.

![image](https://user-images.githubusercontent.com/4627037/81510733-15368d80-9368-11ea-9217-bed19ddb2221.png)
In this state, clicking on B7 does nothing.

**Comment by jenf** [comment]
Click on B5 after B7, at present each hex must be clicked on

**Comment by AndrewChenUoA** [comment]
Ah, I understand what you mean now - the intermediary hexes have to be clicked on, not just the revenue centers. Was that always the case or did I miss that somewhere? I'll mark this as closed for now.

**Comment by jenf** [comment]
No, Toby is presently working on an improvement to allow just cities to be clicked
