### ISSUE TITLE
[1817]Coal mine tracks options are missing

### ISSUE THREAD

**Issue by qwerlancer** [tobymao/18xx#3544]
These are track options during a normal laying track phrase on hex H15
![BUG02](https://user-images.githubusercontent.com/32906266/105846633-cc228880-601f-11eb-9187-5e39fdbdc37f.png)

There is only sharp turn track for me when I clicked coal mine to lay tracks on hex H15. There should be straight and gentle turn too.
![BUG01](https://user-images.githubusercontent.com/32906266/105846180-240cbf80-601f-11eb-830b-036db7520e32.png)

Game data: https://gist.github.com/qwerlancer/ea17f860d6619a3b9c21095505e5eb1e

**Comment by edfactor29** [comment]
This is not a bug, in 1817 a coalmine must be placed pointing at a city. A sharp curve is the only legal tile the A&A could place there with a coal.

**Comment by jenf** [comment]
not a bug
