### ISSUE TITLE
18CO Selling shares allows optional price movement

### ISSUE THREAD

**Issue by kstastny** [tobymao/18xx#3559]
https://18xx.games/game/23799

- when selling shares, it is possible to sell shares one by one which does not decrease the price. Selling multiple shares at once correctly moves price down

Is this intended behaviour? It seems strange to me and more like a bug, I think that the price should move down.

See action 824 https://18xx.games/game/23799?action=824

**Comment by benjaminxscott** [comment]
This seems to be [rules correct](https://drive.google.com/file/d/14zHNRpMGO2Re-FRVkvvF_DZ8iTMhL5ol/view)
(I believe this mechanic is called "price protection" generally )

Note that the president of a company is not price protected, if they sell any number of shares it drops by that many rows

This is [implemented here](https://github.com/benjaminxscott/18xx/blob/master/lib/engine/game/g_18_co.rb#L510)

**Comment by kstastny** [comment]
ok, thank you for the information. I read the rules and to me it's not that clear from the way it's writte, I was hoping that this could be confirmed by Ryan Driskel (I thought I saw him communicating here). Anyway, I will leave it and trust you in this issue :)
