### ISSUE TITLE
[1828.games] Cannot Lay tile and place token in tile laying step with DH

### ISSUE THREAD

**Issue by xorbot135** [tobymao/18xx#3565]
*23019*

https://18xx.games/game/23019

https://18xx.games/game/23019?action=590

**How to Reproduce the Bug?**

I would like to place a tile and token with the DH private and then from there lay a tile into NY with a system (two yellow lays in one OR).  This does not currently seem possible as the free token can only be placed after the track laying step (not the intended design).

**Which Browser / Platform?**

Google Chrome | 88.0.4324.104
-- | --

**Comment by Maxwell-Frank** [comment]
Using the D&H counts as your track lay for the turn.

**Comment by xorbot135** [comment]
Should have included this is with a system which is why the intended use is DH into Scranton with a token and then build into new york.

**Comment by crericha** [comment]
I will take a look tomorrow. The teleport ability needs to be rebuilt from the ground up, but I'll see if I can't patch it in the meantime.

**Comment by crericha** [comment]
I couldn't find a quick fix. I'll put in a full fix this weekend.
