### ISSUE TITLE
Optional tweaks for faster games or fewer players 

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#3568]
It wold be great to have the ability to optionally apply, for _any_ game, some of the tweaks that have been used in various specific games to shorten play time or improve play for smaller number of payers. I'm sure there would be a lot of strong opinions about what works and what doesn't, but for me these are some that I like:

- Train export (as in 18Chesapeake) 
- Move all un-purchased shares to bank pool when company floats
- Remove a share from the game when non-president buys a bank pool share (as in 18Chesapeake) 
- Reduce amount of money in bank
- Shift 10% additional into president's share

I'm sure there are others.

**Comment by tobymao** [comment]
sorry, but I'm not interested in adding this. we're currently implementing games and their variants in their RAW forms
