### ISSUE TITLE
Password manager did not notice login fields 

### ISSUE THREAD

**Issue by snoonan-wp** [tobymao/18xx#3572]
**How to Reproduce the Problem?**
Login to the site, notice login manager (BitWarden) did not notice the screen or queue up id/password

What steps cause the unexpected behavior?
- Log in: password manager does not notice it is a login screen

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
- Firefox LTS (76) Desktop
- Bitwarden plugin

**Comment by benjaminxscott** [comment]
Hmm, the site uses a standard [password form field](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) and doesn't define an [`autocomplete off`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values) attribute

Beyond the above, the autocomplete logic is on the client side so there's not much else the site can do

You may want to report this to the [password manager itself](https://github.com/bitwarden/browser/issues) so they can update their parsing logic

**Comment by yzemaze** [comment]
We do provide guidance on what’s expected `<input id="password" type="password" autocomplete="current-password" […]>`, so I chalk this up to BitWarden, too.
