### ISSUE TITLE
[1860] Receivership company didn't run

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#3576]
https://18xx.games/game/22294

S&C has no train, no routes and is in receivership and I think this combination has caused the game to ignore it completely. I believe it should have done no actions, and then the stock price would have dropped, causing it to go into bankruptcy.

**Comment by roseundy** [comment]
Well, that's a new one.

**Comment by roseundy** [comment]
I don't think I should call @round.clear_cache on a bankruptcy unless it was a stock round.
This bug occurs whenever a corp that isn't the last to run in an OR goes bankrupt.

For reference, https://18xx.games/game/22294?action=616 is the action before NGStL goes bankrupt.
