### ISSUE TITLE
Variant games should be called out in Create Game dropdown

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#3577]
A friend who hadn't played 1849 yet started up a new game and chose the Two Sicilies variant by mistake. It's pretty easy to glance at the dropdown list, see "1849" somewhere, and choose that by accident. 18Chesapeake: Off the Rails could probably also stand to be listed more clearly as a variant.

**Comment by scottredracecar** [comment]
I approve of this approach.

**Comment by scottredracecar** [comment]
This has been implemented for all those games except 1849:K2S and we can do that (or open this back up) when it leaves prototype stage.
