### ISSUE TITLE
[1849] Two Siciles: possible run calculation error

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#3579]
It’s possible this is due to an update, but our game was pinned so it shouldn’t have been affected. 

Game: https://18xx.games/game/24068?action=732

On this action, IFT ran a 12H from  A7-A9-B14-D14-E11-C5 and calculated a total run of 410. The stops were 60-90-40-20-40-120, which adds up to 370.

**Comment by tobymao** [comment]
pinned game

**Comment by philcampeau** [comment]
In the end, the issue is in the code. While the map shows Rome as 60/90/120, the code for C5 shows 80/120/160
