### ISSUE TITLE
1860 unable to choose halts

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3581]
https://18xx.games/game/23350?action=259

The 4+2 train should have the option to choose to use halts instead of towns. The only optional rule enabled in the game is the 2/3 player map.

<img width="773" alt="Screen Shot 2021-01-28 at 12 29 39 PM" src="https://user-images.githubusercontent.com/8732435/106195205-afdc3400-6164-11eb-8b95-06363cf0bd05.png">

**Comment by roseundy** [comment]
Related to the previous change to halt behavior. If there any more of these I'm going to revert to the original behavior with halts.
