### ISSUE TITLE
1849: Cosmetic change for SFA

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#3587]
When I played my first online game of 1849 I could not understand why SFA looked disabled?
![image](https://user-images.githubusercontent.com/2631151/106249665-f4260d80-6212-11eb-9254-3b420f6a9c59.png)

I think the Società Ferroviaria Akragas should be black text instead of white.

You can consider if Compagnia Trasporti Lilibeo should have black text as well, but that is not as clearcut.
The remaining I think can be kept as white texts.

**Comment by tobymao** [comment]
@tysen should be a one word change

**Comment by dfannius** [comment]
This is often handled by programmatically choosing a foreground color (black or white) based on the brightness of the background color (V when translated into HSV).

**Comment by scottredracecar** [comment]
This was fixed
