### ISSUE TITLE
1860 Private bid and committed value calculation

### ISSUE THREAD

**Issue by broggles** [tobymao/18xx#3588]
When bidding in the ISR of 1860 the commited value shows as the bid + first available private value. e.g if I bid $5 my commited value is $35.

https://18xx.games/game/25001

**Comment by roseundy** [comment]
And?

**Comment by broggles** [comment]
My commited value at that point is only $5. I havent chosen which private/major to buy.

**Comment by roseundy** [comment]
If everyone passes, you have to pay that amount. You are committed.

**Comment by broggles** [comment]
Fair enough, makes sense from that angle.
