### ISSUE TITLE
Interface colors in settings all appear as black (on iOS)

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#3589]
In Safari on an iPhone, the colors for preferences (at least once they've been changed) all show as black:

![IMG_2447](https://user-images.githubusercontent.com/757327/106307305-2e040d80-622d-11eb-9a84-9888d6a8645c.jpeg)

**Which Browser / Platform?**
- Safari on iOS 14.3

**Comment by tobymao** [comment]
duplicate

**Comment by orome** [comment]
Ah, missed #2975
