### ISSUE TITLE
[1882] Simplified Logos show CN token instead of Neutral token after using NWR private. 

### ISSUE THREAD

**Issue by akh911007** [tobymao/18xx#3592]
The GT player used the NWR power to move his home station from L8 to E5, which resulted in a Neutral Token at L8 (as expected). When I view the map with simplified tokens turned on, I see a CN logo on the token. With simplified logos turned off, I see the Neutral token as expected.

https://18xx.games/game/24714

**Comment by jenf** [comment]
I missed that one :(
