### ISSUE TITLE
Homepage: Sort finished games by date of last action rather than game ID

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#3595]
Currently, when scanning the homepage for what games have finished recently, the items are sorted in descending order by game ID. This prioritizes live games that were started more recently.

I think it would be better if this list was sorted descending by the date of last action instead (don't consider comments, just game actions).

This has two advantages:
1. Async games would get more equal homepage exposure in this list
2. The games shown on the list would cycle more because every game would be listed on the homepage upon completion and for a duration afterwards. Currently, old game ids may never show up on the first view of the homepage.

Similarly, the active games may be preferable to sort by "updated" date/time (rather than ID).

**Comment by ChrisTheCat** [comment]
This would also be useful when viewing games on your profile. I sometimes go to look at a game that finished in the last day and can't find it.

**Comment by yzemaze** [comment]
> This would also be useful when viewing games on your profile. I sometimes go to look at a game that finished in the last day and can't find it.

Your Games on home page as well as finished games in profile are (should be?) sorted by last update (desc) since August (#1280).

Other games will be sorted the same way once Toby finds some time to peruse my search branch.

**Comment by scottredracecar** [comment]
Also would be nice to prune finished games from the list with less than some minimum number of actions, maybe something (like 50(?) to account for games with pregame chatting, but never started).
