### ISSUE TITLE
18SJ: Required second lay action even when such is not possible

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#3596]
When I lay a tile, I am prompted to lay a second tile even if it is not possible to lay a tile on the mainline paths. I think it would be better to skip this.

It is not a very big deal if this is a challenging problem.

**Comment by perwestling** [comment]
It might not be a big challenge to skip the 2nd lay when all mainlines are completed.
It is more of a challenge if skipping when a corporation/minor cannot make a 2nd lay according to the rules.

Maybe implementing #3560 will solve this?

**Comment by jenf** [comment]
Maybe we should do a generalised 'no lays are possible' and so auto_action skip.

**Comment by perwestling** [comment]
Put into a collective issue to keep track for the future.

This issue is closed for now.
