### ISSUE TITLE
1846 2p Variant as Optional Rule on 1846 instead of separate game

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#3598]
How this should work:

* if max players is set to 2, the "2p Variant" optional rule must be selected for the game to be created
* if max players is 3-5, "2p Variant" cannot be enabled
* once the game is created and players may join, the game should not be startable with only 2 players if max players was 3+

This will require a migration, all "1846 2p Variant" games will need to become "1846" games with the "2p Variant" optional rule selected.

**Comment by perwestling** [comment]
I made a different approach in 1824. If 2 players is selected then it will implicitly regard Cislethania option to be selected. And if 4-5 players then Cislethania option is disregarded.
This have the effect that the automatic testing of min and max players will test the Cislethania setup, and has found a couple of bugs that way.

But, as the games anyway need to be migrated I think setting the optional rule in migration is good. Just that it might simplify user interface if not having verification if optional rule selection is consistent.

**Comment by benjaminxscott** [comment]
I'd agree w/ this, but did something change with [the designer's preference](https://github.com/tobymao/18xx/pull/1710) ?
> add "1846 2p Variant" as a separate title (per Tom's request),

**Comment by michaeljb** [comment]
Yeah I emailed Tom and asked about implementing it the way I describe in the issue, he approved. We didn't have any optional rules yet when I first added the 2p Variant so it wasn't really an option to do it that way.

**Comment by michaeljb** [comment]
> I made a different approach in 1824. If 2 players is selected then it will implicitly regard Cislethania option to be selected. And if 4-5 players then Cislethania option is disregarded.

Tom doesn't want it to be implicit; I expect 1846 2p will forever be an outlier with how it's presented on 18xx.games.

Here's a related quote from [his BGG post on the GMT 2nd edition printing](https://boardgamegeek.com/thread/2589981/1846-gmt-reprint-2nd-edition-now-printer):

>  While I am gratified that some players enjoy the 2-player 1846 rules, I do not believe the 2-player game is at the same level of polish as the 3-5 player game and I don't want to mislead consumers. GMT will put a nicely formatted set of 2-player rules on its website for players to download and we did add a brief new section 12 in the rules mentioning that they exist and directing players to the GMT website.
