### ISSUE TITLE
Issues with Iyo/Dougo in SR 2 and OR 2.1

### ISSUE THREAD

**Issue by Groganite** [tobymao/18xx#36]
Game ID# 56
In SR 2 Groganite purchased president's share of Iyo parring at $65 then converted Dougo Railway.  During this SR the converted share vanished and the private came back.  We were able to undo this and get the shares to work out, but Dougo stilled payed out in OR2.1:

Groganite buys a 10% share of Iyo Railway for $65
Groganite exchanges Dougo Railway for a share of Iyo Railway
Groganite passes
tesh84 passes
Groganite passes
tesh84 collects $5 from Takamatsu E-Railroad
Groganite collects $5 from Mitsubishi Ferry
Groganite collects $10 from Ehime Railway
Groganite collects $15 from Sumitomo Mines Railway
Groganite collects $15 from Dougo Railway

Also had to pass an extra time in the SR.

In OR 2.1, Iyo's treasury disappeared.  It generated $100 revenue with no train.  Groganite withheld the phantom $100, bought one 2-train, then was able to buy another 2-train with $60 personal contribution:

Iyo Railway withholds $100
Iyo Railway's share price changes from $65 to $60
Iyo Railway buys a 2 train for $80 from The Depot
Groganite contributes $60
Iyo Railway buys a 2 train for $80 from The Depot

We probably made the issues worse with too many undo actions.

**Comment by tobymao** [comment]
lol wat. 

the extra pass is due to this being a sell / buy or buy / sell game. i can explore this tonight

**Comment by tobymao** [comment]
fixed the company closing, i can't repro the other one. if you can manager to do that again, don't undo it and let me debug it thanks!
