### ISSUE TITLE
[1889] 4T purchased with 3T still available in the bank/depot

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3604]
Not my game, but 18xx.games/game/24236 saw the purchase of a 4T while there was still a 3T in the bank. When I cloned the game and went back to the purchase, it operated correctly.

**Comment by jenf** [comment]
Can you be more specific about which corp?

**Comment by OedipussyRex** [comment]
It was SR at this point: https://18xx.games/game/24236?action=253
Sorry, should have linked to this move the first time.

**Comment by tobymao** [comment]
i don't see the issue. sr doesn't use president money to buy the 4T. closing for now

**Comment by jenf** [comment]
There's still a 3 in the depot, it's odd the UI doesn't show it

**Comment by jenf** [comment]
This could potentially be reproduced by buying a train, another player doing an undo then buying the second train

**Comment by crericha** [comment]
The train being purchased is not being validated by the engine. In theory, a player can cheat and put any train they want into the request to the server.

**Comment by scottredracecar** [comment]
Is this an actual bug that needs to be fixed, or just some one off weird thing that happened in this game?
