### ISSUE TITLE
[1860: Isle of Wight, but 18xx generally] Allow easily swapping routes between trains

### ISSUE THREAD

**Issue by DerekLong101** [tobymao/18xx#3614]
In playing 1860, it can often happen that a company gets a better train and wants to swap the route from an older train to the new train, so that it can be extended, while choosing a new route for the old train. So, it would be really handy to be able to reassign routes between trains - perhaps swap the routes of two trains, or reassign a route to a different train and just reset the one losing the route. This is not something that I have noticed as much in other games, but 1860 has a rapid train rush, so it is more obvious.

**Comment by ryanespin** [comment]
Would any of these approaches work?

The first being a Swap Routes button that just changes routes based on what trains are present.  This would be easy enough for cases where there are two trains to swap routes, but will lead to a lot more clicking when there's more than 2 trains.  Though, I'd imagine not many users would be doing that for this.  Logic could be in place to only allow it if the train is a different value.

![image](https://user-images.githubusercontent.com/3648402/106688136-89baf780-659b-11eb-80a9-eae276dc94fc.png)

Another approach could be up/down buttons on each row, but I think this would be overkill.

![image](https://user-images.githubusercontent.com/3648402/106688552-52991600-659c-11eb-967f-d7dc11c00335.png)

If both were combined, Swap Routes could enable a mode to show the arrows, and then the user can move manually, and click the same button to confirm?

**Comment by DerekLong101** [comment]
@ryanespin: Thanks for looking at this. I agree that the key issue here is how to make this functionality available without overloading the interface. I like the idea of swapping the routes on the highlighted train and the one below it, cycling back to the top if the bottom train is highlighted, because that is relatively lightweight for interface. In order to make it flexible enough to swap any pair of trains (with a few swaps if necessary) I think the swap should be allowed even if the trains are the same value. In this case, you don't need to confirm, because it can be reversed simply by swapping again. Swapping might (temporarily or not) make one of the train routes invalid, so that check would still have to be applied after swapping, to update status of route allocations. I

I agree that up/down buttons is a lot of extra interface logic and clutter for a relatively specialised function.

**Comment by scottredracecar** [comment]
I like this idea, but it doesn't seem to be necessary and no one has stepped up to solve.
