### ISSUE TITLE
1867 - New company without train doesnt get opportunity to buy train

### ISSUE THREAD

**Issue by chrispday** [tobymao/18xx#3625]
Original game is https://18xx.games/game/23040
Copied game to hotseat is https://18xx.games/hotseat/hs_uwbvphic_23040

GWR operated by packrat, skips the train purchase phase (eg. would buy a train over from packrat's C&O).

Nothing in the rules indicate that this is what should occur and that GWR should be able to purchase another company's train.

**Comment by chrispday** [comment]
From another player 
_"I also used hot seat mode and backed up to NYC, redoing it to include purchasing a 3 train from CS. then went on with GWR and was able to purchase two 3 trains from C&O for $2."_

**Comment by jenf** [comment]
Yeah clearly a bug, not auto actions causing it

**Comment by jenf** [comment]
NYC was nationalized leading to a bug whereby the pass on the train step gets applied to GWR
