### ISSUE TITLE
1877 (maybe 1817 general) Unowned token has half of a transparent ring

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#3642]
At the end of this game, A&S is unowned and it has an artifact with the player color ring where it only shows half of a transparent ring. I'm not sure what the intended behaviour is, but I would have guessed it should not have any ring.
https://18xx.games/game/25649

![image](https://user-images.githubusercontent.com/29106780/106545566-41ce9e80-64cf-11eb-8fb9-e7d228f0459d.png)

**Comment by roseundy** [comment]
This bug occurs whenever a corporation is in receivership (i.e. owned by a non-player).
