### ISSUE TITLE
1867 Merger of two minors leaves both tokens in Montreal

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#3643]
If you merge two minors, both with a token in Montreal, both tokens are left. This is not allowed. One must be removed and should be players choice.

Not sure what happens with the token removal logic when more than two minors are merged and two (or three) have tokens in Montreal, but probably a good idea to verify those scenarios too.

**Comment by jenf** [comment]
Please provide a game id which shows this

**Comment by Jay-Davis** [comment]
Sorry, wasn't in a real game, I noticed it when I was messing around with a game in hotseat mode. So I've specifically created the situation in hotseat mode, ending with the merger that leaves both tokens in Montreal. The game data is below:

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1612297064,
      "company": "C&SL",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1612297066
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1612297067
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 4,
      "created_at": 1612297076,
      "company": "NFB",
      "price": 30
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5,
      "created_at": 1612297077
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "created_at": 1612297077
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1612297079,
      "company": "MB",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "created_at": 1612297080
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "created_at": 1612297080
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "created_at": 1612297082,
      "company": "QB",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "created_at": 1612297082
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "created_at": 1612297083
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "created_at": 1612297084,
      "company": "SCT",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14,
      "created_at": 1612297085
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "created_at": 1612297085
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "created_at": 1612297160,
      "corporation": "OP",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 17,
      "created_at": 1612297164,
      "city": "L12-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 18,
      "created_at": 1612297165
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19,
      "created_at": 1612297166
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "created_at": 1612297208,
      "corporation": "TN",
      "price": 200
    },
    {
      "type": "place_token",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 21,
      "created_at": 1612297210,
      "city": "E17-0-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 22,
      "created_at": 1612297211
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 23,
      "created_at": 1612297212
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24,
      "created_at": 1612297236,
      "corporation": "CS",
      "price": 330
    },
    {
      "type": "place_token",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 25,
      "created_at": 1612297242,
      "city": "G15-0-0",
      "slot": 0
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 26,
      "created_at": 1612297257,
      "corporation": "CA",
      "price": 100
    },
    {
      "type": "place_token",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 27,
      "created_at": 1612297259,
      "city": "L12-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 28,
      "created_at": 1612297263
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "created_at": 1612297301,
      "corporation": "KP",
      "price": 150
    },
    {
      "type": "place_token",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 30,
      "created_at": 1612297306,
      "city": "D16-1-0",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "created_at": 1612297317
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 32,
      "created_at": 1612297331,
      "corporation": "AE",
      "price": 180
    },
    {
      "type": "place_token",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 33,
      "created_at": 1612297334,
      "city": "O7-2-0",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 34,
      "created_at": 1612297340,
      "hex": "G15",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1612297343
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 36,
      "created_at": 1612297344,
      "train": "2-0",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 37,
      "created_at": 1612297345,
      "train": "2-1",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 38,
      "created_at": 1612297354,
      "hex": "E17",
      "tile": "202-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1612297356
    },
    {
      "type": "buy_train",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 40,
      "created_at": 1612297357,
      "train": "2-2",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 41,
      "created_at": 1612297358,
      "train": "2-3",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 42,
      "created_at": 1612297367,
      "hex": "O7",
      "tile": "202-1",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1612297368
    },
    {
      "type": "buy_train",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1612297369,
      "train": "2-4",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1612297370
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1612297378,
      "hex": "D16",
      "tile": "202-2",
      "rotation": 3
    },
    {
      "type": "undo",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1612297381
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 48,
      "created_at": 1612297387,
      "hex": "D16",
      "tile": "201-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1612297389
    },
    {
      "type": "buy_train",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 50,
      "created_at": 1612297390,
      "train": "2-5",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1612297392
    },
    {
      "type": "lay_tile",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1612297400,
      "hex": "K13",
      "tile": "58-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1612297404
    },
    {
      "type": "buy_train",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1612297405,
      "train": "2-6",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1612297411,
      "hex": "L10",
      "tile": "3-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 56,
      "created_at": 1612297417
    },
    {
      "type": "buy_train",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 57,
      "created_at": 1612297418,
      "train": "2-7",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1612297438,
      "hex": "H14",
      "tile": "58-1",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 59,
      "created_at": 1612297440
    },
    {
      "type": "run_routes",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 60,
      "created_at": 1612297447,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "G15",
              "F16"
            ]
          ],
          "hexes": [
            "F16",
            "G15"
          ],
          "revenue": 50,
          "revenue_str": "F16-G15"
        },
        {
          "train": "2-1",
          "connections": [
            [
              "G15",
              "H14"
            ]
          ],
          "hexes": [
            "H14",
            "G15"
          ],
          "revenue": 30,
          "revenue_str": "H14-G15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1612297451
    },
    {
      "type": "run_routes",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 62,
      "created_at": 1612297457,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E17",
              "F16"
            ]
          ],
          "hexes": [
            "F16",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "F16-E17"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E17",
              "D16"
            ]
          ],
          "hexes": [
            "D16",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "D16-E17"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 63,
      "created_at": 1612297470,
      "hex": "N8",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1612297471
    },
    {
      "type": "run_routes",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 65,
      "created_at": 1612297475,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "O7",
              "P8"
            ]
          ],
          "hexes": [
            "P8",
            "O7"
          ],
          "revenue": 60,
          "revenue_str": "P8-O7"
        }
      ]
    },
    {
      "type": "buy_train",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 66,
      "created_at": 1612297477,
      "train": "2-8",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1612297491,
      "hex": "E15",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 68,
      "created_at": 1612297492
    },
    {
      "type": "run_routes",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 69,
      "created_at": 1612297496,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "D16",
              "E17"
            ]
          ],
          "hexes": [
            "E17",
            "D16"
          ],
          "revenue": 60,
          "revenue_str": "E17-D16"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 70,
      "created_at": 1612297498
    },
    {
      "type": "lay_tile",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 71,
      "created_at": 1612297505,
      "hex": "J12",
      "tile": "201-1",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1612297507
    },
    {
      "type": "run_routes",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 73,
      "created_at": 1612297511,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "K13",
              "J12"
            ],
            [
              "L12",
              "K13"
            ]
          ],
          "hexes": [
            "J12",
            "K13",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-K13-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1612297514
    },
    {
      "type": "lay_tile",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 75,
      "created_at": 1612297518,
      "hex": "K11",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 76,
      "created_at": 1612297519
    },
    {
      "type": "run_routes",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 77,
      "created_at": 1612297525,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "L10",
              "K11",
              "J12"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "J12",
            "L10",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 78,
      "created_at": 1612297533
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 79,
      "created_at": 1612297560,
      "corporation": "CV",
      "price": 160
    },
    {
      "type": "place_token",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 80,
      "created_at": 1612297576,
      "city": "57-1-0",
      "slot": 0
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 81,
      "created_at": 1612297622,
      "corporation": "BO",
      "price": 130
    },
    {
      "type": "place_token",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 82,
      "created_at": 1612297632,
      "city": "F16-0-1",
      "slot": 0
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 83,
      "created_at": 1612297635
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 84,
      "created_at": 1612297637
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 85,
      "created_at": 1612297650,
      "hex": "I15",
      "tile": "6-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 86,
      "created_at": 1612297652
    },
    {
      "type": "run_routes",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 87,
      "created_at": 1612297657,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "G15",
              "F16"
            ]
          ],
          "hexes": [
            "G15",
            "F16"
          ],
          "revenue": 50,
          "revenue_str": "G15-F16"
        },
        {
          "train": "2-1",
          "connections": [
            [
              "G15",
              "H14"
            ],
            [
              "H14",
              "I15"
            ]
          ],
          "hexes": [
            "G15",
            "H14",
            "I15"
          ],
          "revenue": 40,
          "revenue_str": "G15-H14-I15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 88,
      "created_at": 1612297666
    },
    {
      "type": "run_routes",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 89,
      "created_at": 1612297668,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E17",
              "F16"
            ]
          ],
          "hexes": [
            "E17",
            "F16"
          ],
          "revenue": 60,
          "revenue_str": "E17-F16"
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E17",
              "D16"
            ]
          ],
          "hexes": [
            "E17",
            "D16"
          ],
          "revenue": 60,
          "revenue_str": "E17-D16"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 90,
      "created_at": 1612297674,
      "hex": "M9",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 91,
      "created_at": 1612297675
    },
    {
      "type": "run_routes",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 92,
      "created_at": 1612297679,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "O7",
              "P8"
            ]
          ],
          "hexes": [
            "O7",
            "P8"
          ],
          "revenue": 60,
          "revenue_str": "O7-P8"
        },
        {
          "train": "2-8",
          "connections": [
            [
              "O7",
              "N8",
              "M9"
            ]
          ],
          "hexes": [
            "M9",
            "O7"
          ],
          "revenue": 50,
          "revenue_str": "M9-O7"
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 93,
      "created_at": 1612297699,
      "hex": "F14",
      "tile": "7-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 94,
      "created_at": 1612297701
    },
    {
      "type": "buy_train",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 95,
      "created_at": 1612297706,
      "train": "2-2",
      "price": 160
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 96,
      "created_at": 1612297721
    },
    {
      "type": "run_routes",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 97,
      "created_at": 1612297723,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "D16",
              "E17"
            ]
          ],
          "hexes": [
            "D16",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "D16-E17"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 98,
      "created_at": 1612297725
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 99,
      "created_at": 1612297742
    },
    {
      "type": "buy_train",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 100,
      "created_at": 1612297743,
      "train": "2-9",
      "price": 100,
      "variant": "2"
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 101,
      "created_at": 1612297746
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 102,
      "created_at": 1612297749
    },
    {
      "type": "run_routes",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 103,
      "created_at": 1612297751,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "K13",
              "J12"
            ],
            [
              "L12",
              "K13"
            ]
          ],
          "hexes": [
            "J12",
            "K13",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-K13-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 104,
      "created_at": 1612297753
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 105,
      "created_at": 1612297755
    },
    {
      "type": "run_routes",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 106,
      "created_at": 1612297757,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "L10",
              "K11",
              "J12"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "J12",
            "L10",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 107,
      "created_at": 1612297759
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 108,
      "created_at": 1612297770
    },
    {
      "type": "run_routes",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 109,
      "created_at": 1612297773,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "G15",
              "F16"
            ]
          ],
          "hexes": [
            "G15",
            "F16"
          ],
          "revenue": 50,
          "revenue_str": "G15-F16"
        },
        {
          "train": "2-1",
          "connections": [
            [
              "G15",
              "H14"
            ],
            [
              "H14",
              "I15"
            ]
          ],
          "hexes": [
            "G15",
            "H14",
            "I15"
          ],
          "revenue": 40,
          "revenue_str": "G15-H14-I15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 110,
      "created_at": 1612297778
    },
    {
      "type": "run_routes",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 111,
      "created_at": 1612297782,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "E17",
              "F16"
            ]
          ],
          "hexes": [
            "F16",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "F16-E17"
        }
      ]
    },
    {
      "type": "buy_train",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 112,
      "created_at": 1612297785,
      "train": "3-0",
      "price": 225,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 113,
      "created_at": 1612297788
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 114,
      "created_at": 1612297791
    },
    {
      "type": "run_routes",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 115,
      "created_at": 1612297793,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "O7",
              "P8"
            ]
          ],
          "hexes": [
            "O7",
            "P8"
          ],
          "revenue": 60,
          "revenue_str": "O7-P8"
        },
        {
          "train": "2-8",
          "connections": [
            [
              "O7",
              "N8",
              "M9"
            ]
          ],
          "hexes": [
            "O7",
            "M9"
          ],
          "revenue": 50,
          "revenue_str": "O7-M9"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 116,
      "created_at": 1612297796
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 117,
      "created_at": 1612297797
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 118,
      "created_at": 1612297803
    },
    {
      "type": "run_routes",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 119,
      "created_at": 1612297807,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "D16",
              "E17"
            ]
          ],
          "hexes": [
            "D16",
            "E17"
          ],
          "revenue": 60,
          "revenue_str": "D16-E17"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 120,
      "created_at": 1612297812
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 121,
      "created_at": 1612297821
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 122,
      "created_at": 1612297823
    },
    {
      "type": "lay_tile",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 123,
      "created_at": 1612297828,
      "hex": "E13",
      "tile": "5-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 124,
      "created_at": 1612297829
    },
    {
      "type": "run_routes",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 125,
      "created_at": 1612297833,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E15",
              "D16"
            ]
          ],
          "hexes": [
            "D16",
            "E15"
          ],
          "revenue": 50,
          "revenue_str": "D16-E15"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 126,
      "created_at": 1612297834
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 127,
      "created_at": 1612297836
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 128,
      "created_at": 1612297843
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 129,
      "created_at": 1612297847
    },
    {
      "type": "run_routes",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 130,
      "created_at": 1612297851,
      "routes": [
        {
          "train": "2-9",
          "connections": [
            [
              "F16",
              "G15"
            ]
          ],
          "hexes": [
            "G15",
            "F16"
          ],
          "revenue": 50,
          "revenue_str": "G15-F16"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 131,
      "created_at": 1612297853
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 132,
      "created_at": 1612297854
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 133,
      "created_at": 1612297856
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 134,
      "created_at": 1612297859
    },
    {
      "type": "run_routes",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 135,
      "created_at": 1612297861,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "K13",
              "J12"
            ],
            [
              "L12",
              "K13"
            ]
          ],
          "hexes": [
            "J12",
            "K13",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-K13-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 136,
      "created_at": 1612297863
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 137,
      "created_at": 1612297865
    },
    {
      "type": "pass",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 138,
      "created_at": 1612297867
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 139,
      "created_at": 1612297868
    },
    {
      "type": "run_routes",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 140,
      "created_at": 1612297869,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "L10",
              "K11",
              "J12"
            ],
            [
              "L12",
              "L10"
            ]
          ],
          "hexes": [
            "J12",
            "L10",
            "L12"
          ],
          "revenue": 70,
          "revenue_str": "J12-L10-L12"
        }
      ]
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 141,
      "created_at": 1612297870
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 142,
      "created_at": 1612297871
    },
    {
      "type": "pass",
      "entity": "CA",
      "entity_type": "corporation",
      "id": 143,
      "created_at": 1612297873
    },
    {
      "type": "pass",
      "entity": "CS",
      "entity_type": "corporation",
      "id": 144,
      "created_at": 1612297882
    },
    {
      "type": "pass",
      "entity": "TN",
      "entity_type": "corporation",
      "id": 145,
      "created_at": 1612297884
    },
    {
      "type": "pass",
      "entity": "AE",
      "entity_type": "corporation",
      "id": 146,
      "created_at": 1612297886
    },
    {
      "type": "pass",
      "entity": "KP",
      "entity_type": "corporation",
      "id": 147,
      "created_at": 1612297888
    },
    {
      "type": "pass",
      "entity": "CV",
      "entity_type": "corporation",
      "id": 148,
      "created_at": 1612297889
    },
    {
      "type": "pass",
      "entity": "BO",
      "entity_type": "corporation",
      "id": 149,
      "created_at": 1612297892
    },
    {
      "type": "merge",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 150,
      "created_at": 1612297895,
      "corporation": "CA"
    },
    {
      "type": "merge",
      "entity": "OP",
      "entity_type": "corporation",
      "id": 151,
      "created_at": 1612297907,
      "corporation": "NTR"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 152,
      "created_at": 1612297910
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 153,
      "created_at": 1612297911
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 154,
      "created_at": 1612297911
    }
  ],
  "id": "hs_lkdidulo_1612297061",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1867",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-02-02",
  "loaded": true,
  "result": {},
  "turn": 3,
  "round": "Stock Round",
  "acting": [
    "Player 3"
  ],
  "updated_at": 1612297911
}

**Comment by jenf** [comment]
Thanks, it is supposed to remove it, maybe it's due to the multiple cities

**Comment by Jay-Davis** [comment]
The complicated part is that you have to let the person choose which to remove because it matters when it upgrades to green and brown.

The other scenario is that when you merge more than two companies, now it lets you choose which tokens to remove to get down to two, but if two or more tokens are in Montreal it has to force you two remove all but one in Montreal, even if it means the company only has one token left on the map and two still available.
