### ISSUE TITLE
[1877] Notepad not saving

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#3664]
Game link: https://18xx.games/game/25348

Saving my private notepad doesn't seem to work in the above game of 1877. Same for my two other games of 77. I enter some text, click save, give it a moment, then navigate away from the page. And when I come back, the notepad is blank again.

I can't check if it's due to the game being pinned, as all my 77 games are pinned, and the only pinned games I'm in are 77.

**Comment by jenf** [comment]
It works on non-pinned games
