### ISSUE TITLE
[Multiple Games] Stuck in Loading Screen

### ISSUE THREAD

**Issue by KerubinHo** [tobymao/18xx#3682]
https://18xx.games/game/26031
https://18xx.games/game/26032
https://18xx.games/game/25332

Are all examples of '46 and '49 games stuck in the loading screen.

**Comment by tobymao** [comment]
@perwestling

**Comment by perwestling** [comment]
@tobymao I checked all three games above and the new PR (#3690) does not cause this problem; they load OK.
