### ISSUE TITLE
[1889] Unable to exchange Dougo for IR share in SR1

### ISSUE THREAD

**Issue by beginetienne** [tobymao/18xx#3683]
https://18xx.games/game/25997?action=29

In SR1, IR Player bought an IR share, leaving the player with a 5$ balance.  The player was autopassed the following turn, as the game assumed the only possible action is buy.  However, the player owns private Dougo Railway and should have been given the opportunity to exchange it for an IR share.  This was easily mitigated by undoing and having the IR player buy the share and exchange the private in the same turn.

**Comment by benjaminxscott** [comment]
This is a known issue due to the "no more actions" logic, as you described https://github.com/tobymao/18xx/wiki/1889#implementation-notes
