### ISSUE TITLE
[1860] Insolvent company didn't go bankrupt during OR

### ISSUE THREAD

**Issue by jave09** [tobymao/18xx#3685]
[1860] Insolvent company didn't go bankrupt during OR

Game ID 25562

https://18xx.games/game/31337?action=710

- During Operating Round 8.3, it was S&C's turn to operate.
- S&C was Insolvent, market share price was £7 and thus, went bankrupt.
- Operating Round should have continued until it is completed.
- Next company that was supposed to operate was FYN.
- FYN was also Insolvent, market share price was also £7 and should have gone bankrupt also.
- However, operation of FYN was skipped and game went directly into Stock Round 9.

Played on mobile.
OS Android 10 (Huawei CLT-L04)
Chrome 88.0.4324.141 (32-bit)

![screenshot game 25562](https://user-images.githubusercontent.com/78547973/106906871-d8ab7e80-66ba-11eb-9833-8ecd6b413003.jpg)

**Comment by roseundy** [comment]
This is the problem:
