### ISSUE TITLE
[18Mag] Game stuck:  GameError: Blocking step Lay/Upgrade Track cannot process action 23

### ISSUE THREAD

**Issue by emknell** [tobymao/18xx#3688]
Our 18Mag game is stuck with the following error:

We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action 23
Broken action: { "type": "place_token", "entity": "2", "entity_type": "minor", "id": 23, "created_at": 1611851356, "city": "L32-0-0", "slot": 0 }
Please raise a bug report and include this link (https://18xx.games/game/23877?action=24) and the following JSON data

**Comment by roseundy** [comment]
@tobymao this needs to be pinned.

**Comment by tobymao** [comment]
just going to delete it since it's alpha

**Comment by roseundy** [comment]
Just to explain to the bug filer, this is due to a change in the 18Mag implementation that no longer requires manually placing the minor token on OO yellow tiles (because of a clarification from Lonny, the designer). Any game that had manual placement ought to have been pinned to the old version.
