### ISSUE TITLE
[1861/1867] Automatically skip "Buy Companies" Step before Train Buying if Company Has no Loans

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3689]
To facilitate the ability to buy in privates before paying loan interest, 1861/1867 adds a "buy companies" step before interest payment and train buying. Would it be possible to automatically skip this step if the operating company has no loans?  

There is no need to make this a specific phase when a player could buy in a company pre-train buying anyway without a bespoke action step unless the company currently has loans.

**Comment by jenf** [comment]
dup of #3070, will eventually fix it
