### ISSUE TITLE
[1828] suggest renaming Treasury to System Share.

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#3691]
“Treasury” feels like an inaccurate name for the system share, since it’s not possible to redeem additional shares into the treasury, nor is it possible to buy that share from the treasury. 

I think calling it “System Share” is clear and concise, and avoids misreads (thinking an additional share is available for purchase, etc).

**Comment by crericha** [comment]
I'm of two minds here. Treasury share is the proper term, but can be misleading as you can buy treasury shares in incremental cap games. I tried early on calling it "Treasury Reserved" or some shortened version of that, but it didn't look good. My new ideas is "Treasury            R 1" or simply "Reserved" if I can't make some version of Treasury work. Feedback and additional ideas welcomed.
