### ISSUE TITLE
1860 - incorrect revenue route Yarmouth to Chale

### ISSUE THREAD

**Issue by Hepworthnot** [tobymao/18xx#3699]
Game ID 24542
https://18xx.games/game/24542

https://18xx.games/game/24542?action=535

During OR 7.2 the VYSC leased a train with original insolvency rules. I understand it should earn half of 40cc plus 20cc for each station plus the subsidy. The subsidy was correctly calculated at 2x10cc for 20cc.
The leased train hit 4 stations including the home station so should earn (40 + (4x20) ) / 2 = 60
In the game it earned 35

![SharedScreenshot](https://user-images.githubusercontent.com/43420560/107001618-d9f3ae80-6781-11eb-9b08-fc86a26ab3a5.jpg)

**Which Browser / Platform?**
Edge on a Microsoft Surface Pro

**Comment by benjaminxscott** [comment]
Looks like E9 is only worth 10, does that change the expected revenue?
(calculating 70 for total run , divided by 2 is 35)

**Comment by Hepworthnot** [comment]
Hi Benjamin,

you're right. I misunderstood. I see in the original insolvency rules you calculate income as normal and halve it - you don't use the 40 plus 20 per station method.

It is not a bug!

Hope I haven't wasted your time and thanks for the incredible work you guys have done on this site.

Phil

**Comment by benjaminxscott** [comment]
No worries better to report than not, thanks for linking to the game action since it makes reallocate easy to "clone as hotseat" to test

**Comment by roseundy** [comment]
Agreed. I'd much rather people over-report issues than under-report them.
