### ISSUE TITLE
[18Mag] ő in corporation names not displayed correctly

### ISSUE THREAD

**Issue by yzemaze** [tobymao/18xx#3700]
[More or less a note to future me.]

![image](https://user-images.githubusercontent.com/33390595/107033288-5e135980-67b5-11eb-9c73-6c7492363497.png)
[Lato](https://www.latofonts.com/de/lato-free-fonts/) does support extended Latin characters like ő (in Győr and Építőipari), but Google has botched it up: https://github.com/google/fonts/issues/1564

**Comment by roseundy** [comment]
Thanks for catching this. I noticed this when I first implemented 18Mag then promptly forgot about it.

**Comment by bentziaxl** [comment]
fixed, working now

**Comment by dfannius** [comment]
The ő still looks overly bold to me, like the picture above. Compare to the o in Károly.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/1295244/180663870-85e0a58f-60f8-4c0a-8b3b-1d7cf1906d4f.png">
