### ISSUE TITLE
1849 - Support for all 1849 optional rules

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#3704]
Seems like nobody is working on them, but it actually would be very nice to have all the official optional rule available.

**Comment by dfannius** [comment]
#3384 would be subsumed by this.

**Comment by bentziaxl** [comment]
implemented

**Comment by dfannius** [comment]
I don't think that any of the variants in section 14 of the AAG rules (Acquiring Station Tokens, Bonds, and Electric Dreams) are implemented.

**Comment by glleu** [comment]
This shouldn't be closed as completed, since all the offical variants of 1849 (14.1 Acquiring Station Tokens; 14.2 Bonds; 14.3 Electric Dreams) have not been implemented.

**Comment by tobymao** [comment]
they aren’t closed as completed, they are closed as not planned
