### ISSUE TITLE
1860 bug - shares in market should not count toward floating a corporation

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3705]
Confirmed by Mike Hutton:

https://boardgamegeek.com/thread/988779/when-does-company-float

I don't have an 18xx.games online play example, but I was able to confirm the bug in a hotseat game. I can provide a JSON if needed.

**Comment by roseundy** [comment]
Totally wasn't expecting that outcome.

Hopefully this won't invalidate too many games. I suspect it won't.

**Comment by roseundy** [comment]
I also need clarification about whether this applies to re-floating a bankrupt corp.
