### ISSUE TITLE
1877, market tip and company logos

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#3709]
I'm hoping one thing can be copied from 1817, the simplified company logos. I guess there aren't as many corps but it is still helpful (specially now that I deleted from my memory what all those logos actually look like for 1817

And another thing to be changed from 1817, which is removing the 55 market value tip (since it doesnt apply) and either changing the 5share company tip from 70 to 60 (since the company should be going up?) or removing it since there is no "auto-withhold on the first OR

and there can be shorts.. maybe just remove the tip since nothing is truly safe from acquisition I guess :D

**Comment by tobymao** [comment]
the 1877 logos are already simplified

**Comment by PedroRCSequeira** [comment]
oopsy, i'm on 2 games but they are the first version i guess :D
