### ISSUE TITLE
[18CO] Inter-corporation train purchase allowed during Emergency Fundraising

### ISSUE THREAD

**Issue by skizelo** [tobymao/18xx#3710]
From the rulebook: "5:10:6:1 If a Corporation cannot afford a train to satisfy a mandatory purchase, it must buy the cheapest available train in **the Bank or Market**, raising only as much money as necessary through the following means...". I understand this to mean that once you start Emergency fundraising, you can no longer buy trains across from another company.
In game id 24155, DSL couldn't afford to buy the latest from the market, and was given the option to buy across from another company, or go into Emergency Fundraising by selling shares ahead of the "Issuing Shares" step. After selling those shares, I could still buy a train across, at a price I could not have afford otherwise. 
After I persisted and contributed funds from the president, I could buy trains from another company, though just the one purchased 4D (a train from the latest stack) and not any of the 4T or 5Ts that were available before.
![bug1](https://user-images.githubusercontent.com/77389765/107068821-fbcc5000-67d8-11eb-94f4-d0f7f7beb8df.png)
![bug2](https://user-images.githubusercontent.com/77389765/107068824-fc64e680-67d8-11eb-809e-bbabe413dfde.png)

**Comment by ryandriskel** [comment]
In the future, please use the history arrows to generate a link to the point in the game where this is occurring. It will look similar to https://18xx.games/game/21073?action=905 . This allows the developers to have a test case where they can start debugging. Thanks for the report!

**Comment by ryandriskel** [comment]
Also, thank you for not doing the illegal action, as it would have made fixing this break your game! :D
