### ISSUE TITLE
NdM merger with unfloated company

### ISSUE THREAD

**Issue by ZetaZeta6** [tobymao/18xx#3715]
in game 26264 we have to merger NdM, but we get an error both if we click on "decline" and also if we click on "merge" for all the companies proposed. Because of this it's not possible to proceed with the game. Maybe there is a bug in the implementation?

**Comment by perwestling** [comment]
There is some kind of bug when the game tries to merge SPM. Have to look into why.

**Comment by perwestling** [comment]
This was fixed and merged. After the bug fix the game has finished.
