### ISSUE TITLE
18Mag: Support solo mode

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#3717]
18Mag had a solo stretch goal in the KS campaign, which was reached. So even though BGG page state 2-6 players it should be possible to play it solo.

Solo mode is something that is lacking in the existing titles at 18xx.games and as an avid solo gamer I think I would enjoy to have it. Also that would give me the opportunity to plug 18xx.games in the solo community.

Now I suppose I could do this myself, but I am working on three other titles at the moment so I will wait with that. But this is a potential future candidate for my work.

**Comment by roseundy** [comment]
Lonny sent me the assets needed for the solo game. I was thinking about implementing this, but I may be working on a much bigger project in the meantime: Harzbahn 1873.

Whoever works on this, let me know and I can send you the files.
