### ISSUE TITLE
Add version system for rule implementation

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#373]
Migrating older games when rules are broken is turning out to be problematic

Add a version field into the database
(Maybe add a git commit hash as well)
Add the version field into the game constructor

When we strengthen a rule that breaks existing games we put it behind a if version>x

Depending on the version (alpha, beta, production) of the rules we should display a different message to the users when creating games

Alpha:
"18Cheasepeake is currently considered 'alpha', the rules implementation is likely to not be complete and as we improve our implementation of the rules, games that are breaking the rules will be deleted. We suggest that any alpha quality game is concluded within 7 days"

Beta:
"1889 is currently considered 'beta', the rules implementation is not robust yet and can allow illegal moves, we are working to improve the quality of the rules implementation, games that are breaking the rules will be given 7 days to complete before being deleted. Because of this it may not be suitable playing games that may take months to complete"

**Comment by tobymao** [comment]
instead of version, i think it should have the word pin in it because only games that are broken will be pinned back

**Comment by jenf** [comment]
yeah, although i think it might be worth prototyping the opal idea first, if that's easier then maybe it'll be more suitable than worrying with version numbers.

**Comment by jenf** [comment]
we'd need to think about hotseat games
