### ISSUE TITLE
[18Mag] Major tokens should show +10 or increased city value

### ISSUE THREAD

**Issue by ikelly** [tobymao/18xx#3732]
The tokens of the major companies should show either a +10 on the tile, or else update the value on the tile to show the increased value. This would make it easier to see and remember the increased value.

**Comment by roseundy** [comment]
Does this physical game do this?

**Comment by ikelly** [comment]
No, I don't think there are components for this. I just think it would be a useful UI feature.

**Comment by ChrisTheCat** [comment]
Note that the +10 would not be on the tile, but rather the city. On tiles with multiple cities (O-O) only the city containing the token gets the bonus.
