### ISSUE TITLE
[General] Tab on home page for list of games with game rule links

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#3738]
I know it exists in a tab in an active game, but a quick link to the rules on the home page would be nice.

I heard talk on slack of making a game choosing tool using box covers rather than a drop down menu. Maybe here have a link underneath saying "Create new game" and below that "game rules?"

I know a simple BGG/internet search can yield these results, but if I'm spending time on 18xx.games it would be a nice little feature. 

Thanks for considering!

**Comment by Maxwell-Frank** [comment]
@HerbyMcGee There's already a link to the wiki on the home page which contains the rulebooks (as well as other information) for every game on the site.
