### ISSUE TITLE
Option to suppress currency symbols

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3739]
I would prefer if $ and ₽ and Ft symbols weren't displayed. They add visual clutter and make it harder for me to parse numbers at a glance. It would be nice if there was a profile checkbox to toggle them on and off.

**Comment by bridger15** [comment]
I think I agree.  Our current game of 18Mag looks like this: https://i.imgur.com/0Bq7P8i.png

It's got the extra line for ONLY the 'Ft' and if that was disabled then it would look much more clean.

**Comment by dfannius** [comment]
Currency format strings should use non-breaking spaces to avoid the sort of issue in that picture. (Though I'm not sure what it would look like afterwards given that the layout thinks it needs a linebreak.)

**Comment by yzemaze** [comment]
> Though I'm not sure what it would look like afterwards given that the layout thinks it needs a linebreak.

It’s fine. Mock-up with @Zwergenpunk ’s nbsp included and 320px width:
![image](https://user-images.githubusercontent.com/33390595/110209386-9d07fe00-7e8c-11eb-8b28-3e1d7eccfa93.png)

**Comment by Zwergenpunk** [comment]
So for now we have a &nbsp; between the number and the Symbol. Every new game has to remeber that a unicode has to be copied in and no white space. 

An other solution for that would be to adjust the currency_format function to replace a space with a nbsp but thr code for that would look really confusing 😀

The best solution would be to have an own component that uses css nowrap to display the currency, but that would require alot of work. But with that solution it would be possible to give the user settings to disable the currency symbol.
