### ISSUE TITLE
Can't undo after bankruptcy action

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#374]
Game Id #595. 
OR 7.1 Buy trains phase for UR. 

After bankruptcy pressing [undo] button leads to out of sync error.

Doesn't matter who or how often [undo] is clicked

**Comment by jenf** [comment]
Can you try it now?

**Comment by MoshiMaro** [comment]
Nope, still out of sync error

**Comment by jenf** [comment]
Ahh, yes I see the problem undos have a null id in this case. Apologies, we'll fix it but it might be a few days.

**Comment by jenf** [comment]
Similar route cause as #372
