### ISSUE TITLE
1830/18Chesapeake: Buying teleport corporation at track lay step doesn't immediately update the hexs available

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#3749]
Buy DH, F16 doesn't show up as immediately teleportable

Refreshing shows it

I'm assuming chesapeake has the same bug but i've not tried.

`{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1612807519,
      "company": "SV",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1612807520,
      "company": "CS",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1612807521,
      "company": "DH",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "created_at": 1612807522,
      "company": "MH",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "created_at": 1612807524,
      "company": "CA",
      "price": 160
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "created_at": 1612807528,
      "company": "BO",
      "price": 220
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1612807530,
      "corporation": "B&O",
      "share_price": "100,0,6"
    },
    {
      "type": "buy_shares",
      "entity": "MH",
      "entity_type": "company",
      "id": 8,
      "created_at": 1612807534,
      "shares": [
        "NYC_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9,
      "created_at": 1612807537,
      "shares": [
        "B&O_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 10,
      "created_at": 1612807538,
      "shares": [
        "B&O_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 11,
      "created_at": 1612807540,
      "shares": [
        "B&O_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "created_at": 1612807541,
      "shares": [
        "B&O_4"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "created_at": 1612811017,
      "corporation": "PRR",
      "share_price": "100,0,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 14,
      "created_at": 1612811019,
      "shares": [
        "PRR_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 15,
      "created_at": 1612811020,
      "shares": [
        "PRR_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16,
      "created_at": 1612811021,
      "shares": [
        "PRR_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 17,
      "created_at": 1612811022,
      "shares": [
        "PRR_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 18,
      "created_at": 1612811023,
      "shares": [
        "PRR_6"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 19,
      "created_at": 1612811031,
      "corporation": "NYC",
      "share_price": "100,0,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 20,
      "created_at": 1612811033,
      "shares": [
        "NYC_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21,
      "created_at": 1612811034,
      "shares": [
        "NYC_3"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22,
      "created_at": 1612811035,
      "shares": [
        "NYC_4"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23,
      "created_at": 1612811037,
      "shares": [
        "NYC_5"
      ],
      "percent": 10
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 24,
      "created_at": 1612811209,
      "hex": "I17",
      "tile": "7-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 25,
      "created_at": 1612811212
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 26,
      "created_at": 1612811219,
      "hex": "H10",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 27,
      "created_at": 1612811220
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 28,
      "created_at": 1612811222,
      "train": "2-0",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 29,
      "created_at": 1612811224,
      "train": "2-1",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 30,
      "created_at": 1612811225,
      "train": "2-2",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 31,
      "created_at": 1612811226,
      "train": "2-3",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 32,
      "created_at": 1612811237,
      "hex": "E19",
      "tile": "57-1",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 33,
      "created_at": 1612811241,
      "train": "2-4",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 34,
      "created_at": 1612811242,
      "train": "2-5",
      "price": 80,
      "variant": "2"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 35,
      "created_at": 1612811243,
      "train": "3-0",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 36,
      "created_at": 1612811243,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 37,
      "created_at": 1612811247
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 38,
      "created_at": 1612811247
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 39,
      "created_at": 1612811248
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 40,
      "created_at": 1612811294
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 41,
      "created_at": 1612811295
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 42,
      "created_at": 1612811296
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 43,
      "created_at": 1612811297
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1612811418,
      "company": "SV",
      "price": 40
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1612811456,
      "company": "CA",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1612811464
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1612811465
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 48,
      "created_at": 1612811466
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 49,
      "created_at": 1612811467
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 50,
      "created_at": 1612811467
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1612811484,
      "hex": "H16",
      "tile": "57-2",
      "rotation": 2
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1612811505,
      "company": "CS",
      "price": 80
    },
    {
      "type": "lay_tile",
      "entity": "CS",
      "entity_type": "company",
      "id": 53,
      "created_at": 1612811609,
      "hex": "B20",
      "tile": "58-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1612811678
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1612811681,
      "train": "3-1",
      "price": 180,
      "variant": "3"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 56,
      "created_at": 1612811683
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 57,
      "created_at": 1612811780
    },
    {
      "type": "buy_company",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 58,
      "created_at": 1612811791,
      "company": "DH",
      "price": 140
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 59,
      "created_at": 1612811885
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 60,
      "created_at": 1612811887
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 61,
      "created_at": 1612811893
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 62,
      "created_at": 1612811894
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 63,
      "created_at": 1612811987
    },
    {
      "type": "buy_company",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 64,
      "created_at": 1612811996,
      "company": "DH",
      "price": 140
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 65,
      "created_at": 1612812000
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 66,
      "created_at": 1612812002
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 67,
      "created_at": 1612812009,
      "hex": "F16",
      "tile": "57-3",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 68,
      "created_at": 1612812013,
      "city": "57-3-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 69,
      "created_at": 1612812016
    },
    {
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 70,
      "created_at": 1612812018,
      "city": "57-3-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 71,
      "created_at": 1612812065
    },
    {
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 72,
      "created_at": 1612812069,
      "city": "57-3-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 73,
      "created_at": 1612812150
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 74,
      "created_at": 1612812154
    },
    {
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 75,
      "created_at": 1612812161
    }
  ],
  "id": "hs_numdyyxn_1612803387",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1830",
  "description": "",
  "max_players": "3",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-02-08",
  "loaded": true,
  "result": {},
  "turn": 2,
  "round": "Operating Round",
  "acting": [
    "Player 2"
  ],
  "updated_at": 1612812161
}`

**Comment by Maxwell-Frank** [comment]
@jenf Chesapeake and 1828 (and probably 36jr) also have this bug.  There might already be an existing report for it?

**Comment by tobymao** [comment]
@crericha is rewriting how teleport works
