### ISSUE TITLE
[1860] Refloated Corporation Doesn't Remain Insolvent

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#3752]
When an insolvent company is sold down to a share price of 0, and is refloated, it says that it remains insolvent on the company card but during the OR it skips the train running step. In this case the company should be able to hire a train from the bank before it has to buy one of its own.

I believe that this does not happen when a company becomes insolvent during an OR - I don't have a Game ID as an example but from recollection it works fine in this case (I'm only about 80% sure of this)

**Comment by Blobbley** [comment]
https://gist.github.com/Blobbley/0846924b30870ab90226264d84c6a622

**Comment by roseundy** [comment]
If the refloated company has enough cash to buy a train (any train on offer) it becomes solvent immediately before running trains. This was clarified by Mike Hutton on BGG. I don't have the link at hand.

**Comment by roseundy** [comment]
From the rules:
`If an insolvent company has insufficient funds to buy a train from the bank, the company must lease a train...`
The implication being that if it _does_ have sufficient funds, it stops being insolvent and doesn't lease a train.

**Comment by Blobbley** [comment]
https://boardgamegeek.com/thread/1287358/bankrupt-and-insolvency

In this thread Mike suggests that it should not retain its insolvency marker in any circumstances upon refloating

**Comment by roseundy** [comment]
Ummm, in that thread Mike says this:

`The rules as written imply that the insolvency marker should be retained by he bankrupt company, and from that POV this should be the official interpretation.`

It certainly doesn't help that he said the opposite in an earlier thread.
