### ISSUE TITLE
[1860] IWNJ Unable to upgrade H8 from Yellow to Green

### ISSUE THREAD

**Issue by kensinn** [tobymao/18xx#3765]
IWNJ During Lay Track, unable to upgrade H8 tile. 

Unsure if this is due to 1860 Tile-Laying rules being different from a few other 18xx games. "In order to upgrade a tile, the company must be able to trace a route, with one of the trains it currently owns, from any of its bases on the board to the tile in question" -- IWNJ can reach the tile, but just can't reach any part of the existing track pre-upgrade. Other 18xx seem to allow this behaviour, as long as the post-ugprade tile can be reached

https://18xx.games/hotseat/hs_slrbyjso_22184

**Comment by kensinn** [comment]
Subsequent turn, as shown in https://18xx.games/hotseat/hs_ukgswldw_22184, even when connected to an existing track, IWNJ still unable to upgrade any tracks.

**Comment by kensinn** [comment]
Under almost identical situations, FYN is able to upgrade F4. https://18xx.games/hotseat/hs_hyaftxec_22184

**Comment by kensinn** [comment]
Edit: apparently hotseat tables aren't persisted, had no idea.
Game link is https://18xx.games/game/22184, turn 7.1 for IWNJ is where it happens.

**Comment by roseundy** [comment]
Not a bug. In 1860 companies cannot upgrade tiles unless they own a train.
