### ISSUE TITLE
GameID #735: wrong player underlined

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#377]
Hi Toby, in this game it is JaxHammerHex his turn (and is properly underlined), but in the overview of my active games at the homepage it is my name that is underlined. This may be confusing. JaxHammerHex is not playing his turn maybe because he thinks it is not his turn based on the homepage game overview.
Thanks for your help. Still love the game and the site!

**Comment by tobymao** [comment]
if you type a chat message it should fix it

**Comment by Spobster** [comment]
Yes, nice workaround thanks!

**Comment by tobymao** [comment]
i believe the underlying issue was fixed yesterday. Also if you want to email him, you have to do @name in the chat
