### ISSUE TITLE
[1836jr30] Overlapping data on hex E11

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#3771]
Hi, 

I am in a game currently (27039) and hex E11 has overlapping data that is hard to read. 
The construction cost, and the NBDS name overlap making it hard to read.

**Comment by roseundy** [comment]
You can always turn off location names.

**Comment by HerbyMcGee** [comment]
It's not the location name, it's the NDBS company name and the build cost.

**Comment by jenf** [comment]
https://18xx.games/game/27039?action=307

**Comment by andypymont** [comment]
Whilst this is crowded (unsurprising as the hex has a lot going on), the information isn't overlapping now so I believe rendering has changed in the meantime and this issue can now be closed?
![image](https://user-images.githubusercontent.com/8403378/174190407-ae10df67-da3b-49a3-b53e-5e2fe012981a.png)
