### ISSUE TITLE
Add option to show tiles as an upgrade chart (similar to rulebooks)

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#3772]
Hi, 

I don't know the coding logistics of this request, but I was playing an 1889 game recently, and I made a tactical error based on my perception of the tile manifest. 

I often play out my turns on my iPhone, and I did not see all the possible options for tiles when I was pre-planning my OR moves during the SR. My error was that I did not see all the green single city upgrades, and then got blocked out of a critical route. Some of the single city green tiles were separated from the others in numerical tile order. Scrolling on my iPhone made this difficult to parse. 

The current layout for the tile manifest is by tile #. When I play in person, we lay out the tiles in a more functional manner- all tiles of a similar type near one another- so all towns, all cities, all plain track, etc. 

So, for an alternate layout, is it possible to group tiles in such a way? Or to have it as some rule books do- showing the tile, and all possible upgrades next to it?

Thanks for considering.

**Comment by Zwergenpunk** [comment]
You can click on a tile at the tile page to see all possible upgrades. 

Still, another view as a "tree" would be nice.

**Comment by jenf** [comment]
Yeah the 'table' often in the back of the rulebook would be useful.

**Comment by HerbyMcGee** [comment]
@Zwergenpunk - I didn't realize clicking the tiles in the manifest shows options. Thanks for the tip.

@jenf Yes, that sort of table is kind of what I had in mind.
The iOS web interface is mostly really great. My biggest issue is that tile page- scrolling through the tiles 2 by 2 makes it hard to see the big picture. Thanks for considering.

I also don't think the numerical ordering is useful in most situations. It's good as a reference point, but it doesn't have much functional practicality. I'd like a view option to order things like:
Yellow- Plain track, town, city
Green- Plain track, town, city [single city, double city]
Brown- plain track, town, city
etc. 
Rather than 1, 2, 3.... 47, 49... 312, 313, etc
