### ISSUE TITLE
Forced Purchase not working correctly in 18CO

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#3776]
18CO

CBQ had 4 shares and 0 credit.
There was a 4T in market.  As it is in the market it should be available at half price.  Issuing two shares would give it enough money but the game would not allow that.  Once three shares were issued, the 4T could be bought but the CBQ was charged $140 which is the correct half price.
It was able to buy a 5T or a train from another company when 18CO rules say that it should not be able to

https://18xx.games/game/26651?action=560
![image](https://user-images.githubusercontent.com/11814681/107479609-46e8b900-6b73-11eb-85b5-f4e05a6717b0.png)

**Comment by ryandriskel** [comment]
Gah! I wonder what happened here, as I just fixed this bug on Sunday! Argh. Thanks for the report.

**Comment by rclyne** [comment]
The game was on Friday so before your fix!

**Comment by ryandriskel** [comment]
Ah yes, this game is pinned! I believe this issue is fixed in the current version.
