### ISSUE TITLE
General display issue showing routes - 1861 example but all titles

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#3777]
When someone else's company is running the display is shown wrongly.  The game state is correct.   This has occurred in all titles but the example is from 1861.

In this case, the N is running for 260 and chosen to payout but the display shows the previous run of 190
![image](https://user-images.githubusercontent.com/11814681/107479975-c2e30100-6b73-11eb-8a92-30c85ff24301.png)

https://18xx.games/game/26223?action=486

**Comment by jenf** [comment]
Loading it doesn't show the old route.

I'm guessing you had the previous route selected while another player was submitting routes? Is that correct?

**Comment by rclyne** [comment]
I wasn't using the show routes feature.  It was not just my display that was affected.  All players other than the director saw this mismatch between the shown routes and the revenue as in the screen print

**Comment by roseundy** [comment]
You are aware that as the director interactively changes the route, none of it shows up until the "submit" button is clicked, right? Just making sure.

**Comment by jenf** [comment]
@rclyne Does @roseundy comments match what you were seeing? I'm unsure what the bug is that's been reported

**Comment by jenf** [comment]
Cannot reproduce
