### ISSUE TITLE
Highlight tiles played this action

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#3778]
The only way to see what another company has laid/upgraded is to look at the logs.  Would it be possible to have a show map changes by company in a similar way to the show routes for company works?

**Comment by jenf** [comment]
I thought I'd already had a ticket for this but nope.

My idea was that there'd be a button to turn all tiles laid since last turn a certain color (or maybe just the edges)

**Comment by rclyne** [comment]
That would probably work well as well

**Comment by crericha** [comment]
I vote for edges.

The round already knows which hexes had tiles laid, so this may not be that bad to do.

**Comment by roseundy** [comment]
I'll have to update 1873 for this to work. It had to override a _lot_ of the base Track step.
