### ISSUE TITLE
Display number of ORs (like OR 6.2 (2/3)

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#378]
I know it's something basic, but while playing a few async games at the same time it could help

Not sure about the design, maybe it could be

OR6 1/3
OR6 2/3
OR6 3/3

**Comment by Herbert62** [comment]
This is related to #364 (show game phase (yellow, green, brown))

**Comment by scottredracecar** [comment]
I think the following syntax would be good.
`OR6.1 (1 of 3)`

If there is only one round, then don't use the parenthetical.
`OR2`

**Comment by sparr** [comment]
`OR6.1 (1 of 3)` is a bit redundant. How about `OR6.1 (of 3)` or even without the parentheses?

**Comment by scottredracecar** [comment]
I prefer the syntax I proposed. It is short enough already.

I think this change would appear on the game tab and in the log only currently. If it added to other places in the future, it would be good to show up there too. 

The OR name is also shown in the spreadsheet and we wouldn’t want to change it there of course.

**Comment by wheresvic** [comment]
@dfannius I just had a quick look into this issue and it is actually not that straightforward. Basically the engine contains the `round_num` field but it is not populated into the db. So this issue will likely require adding a column to the `game` table, saving this info and then displaying it, etc. At least for the main page we would need to store it into the db if I understood Toby correctly.

Anyways long story short I would remove the `good first issue` label on this one :p

**Comment by dfannius** [comment]
I refuse to believe that it is really that complicated! (I am probably wrong, of course.) I'll take a look.

**Comment by tobymao** [comment]
it’s not complicated but it requires a db migration

**Comment by sparr** [comment]
It seems like some people here are discussing putting this info on the game card on the front page (hard(ish)), while other people are discussing putting it on the game page (easy?).

**Comment by scottredracecar** [comment]
No, just game page is best. Too much info for the homepage game card.

**Comment by tobymao** [comment]
it’s already on the game page

**Comment by tobymao** [comment]
ah i misunderstood, this is just to add the total rounds

**Comment by jenf** [comment]
resolved by #614
