### ISSUE TITLE
Automatic Playback for Reviewing Games

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#3782]
**What's your idea?**

Reviewing games is a cool feature. Clicking the "next button" a thousand times is not so cool.
I would like to see an auto-playback feature that advances the game state every 2-3 seconds (or maybe have speed options with pause and rewind buttons). 
This way you can watch a game unfold without clicking again, and again, and again.

**Comment by HerbyMcGee** [comment]
Not sure if this should be a separate enhancement issue, but maybe during the reviews, there can be a "master view" tab that has the map, and a summary/ condensed version of the entities (with cash, treasury, share value, etc).

**Comment by benjaminxscott** [comment]
I don't feel strongly about this idea, but check out [this extension](https://chrome.google.com/webstore/detail/url-incrementer/hjgllnccfndbjbedlecgdedlikohgbko/related?hl=en) as a stopgap 
(its auto incrementer seemed to work)

**Comment by yzemaze** [comment]
There are [hotkeys](https://github.com/tobymao/18xx/wiki/Power-User-Features) now, so you can just hold the right arrow key down to "scroll" through a game.
You could use a tool like [AutoHotkey](https://www.autohotkey.com/) or [AutoKey](https://github.com/autokey/autokey) to automate this and delay each key press by 3 seconds e.g. This should be good enough for now.
