### ISSUE TITLE
[1830] Allowing President of owning corporation to lay the C&StL private tile during the stock round 

### ISSUE THREAD

**Issue by hopkinsryan** [tobymao/18xx#3783]
https://18xx.games/game/26856

We are in SR4 and the game is presenting the President of the NYC with the option to lay the C&StL tile.  The tile would have to be laid in the NYCs turn in an OR.  Not sure when it appeared, but it is there now, as well.  Just noticed it this SR.

**Comment by dfannius** [comment]
I'm removing the "bug" label because that's reserved for issues that prevent the game from being played correctly (as opposed to issues that don't stop the players from performing some illegal actions, like this one).

**Comment by tomdeakin** [comment]
Looks like there is similar behaviour for the D&H private too: https://18xx.games/game/26857
<img width="526" alt="Screenshot 2021-02-12 at 17 46 04" src="https://user-images.githubusercontent.com/1379598/107803197-3181b380-6d5a-11eb-8ee2-18606778759f.png">
