### ISSUE TITLE
1830 - Private Auction - Priority Deal Moved without Purchase of Private

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#3797]
Just fooling around with the Private Auction and I noticed that Priority Deal moved from Player 1 to Player 2.  The only time during the Private Auction that the PD should move is after the sale of a Private at Face (IIRC), and maybe if there is a pass around, but I'm not sure on that - I don't remember offhand.

Note:  In the below Player 1 increases his bid on the C&A which I believe is technically allowed, but might be disallowed for convenience.

JSON:

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1613077784,
      "company": "CA",
      "price": 165
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1613077792,
      "company": "MH",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1613077797,
      "company": "CA",
      "price": 170
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 4,
      "created_at": 1613077801
    },
    {
      "type": "pass",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 5,
      "created_at": 1613077802
    },
    {
      "type": "pass",
      "entity": "Player 6",
      "entity_type": "player",
      "id": 6,
      "created_at": 1613077803
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "created_at": 1613077807,
      "company": "CA",
      "price": 175
    }
  ],
  "id": "hs_ooodlwcc_1613077716",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    },
    {
      "name": "Player 4"
    },
    {
      "name": "Player 5"
    },
    {
      "name": "Player 6"
    }
  ],
  "title": "1830",
  "description": "",
  "max_players": "6",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-02-11",
  "loaded": true,
  "result": {},
  "turn": 1,
  "round": "Auction Round",
  "acting": [
    "Player 2"
  ],
  "updated_at": 1613077807
}

**Comment by dfannius** [comment]
I believe that this is a cosmetic issue and does not prevent the game from being played correctly, since the priority deal marker will be correct as soon as someone buys C&StL. If that is the case, we should remove the "bug" label, since that should be reserved for game-breaking behavior.

**Comment by rheretic** [comment]
I just checked this and there seems to be a genuine bug.  If you continue my game and have everyone pass, the Schyulkill is decreasing AFTER Player 1 (the player that should have the PD).  The price should be decreasing in front of Player 1.  (Player 1 is correctly forced to autobuy it but the wrong player is getting the first choice after the discount.)

**Comment by dfannius** [comment]
This looks correct to me:
```
[16:09] Player 1 bids $165 for Camden & Amboy
[16:09] Player 2 bids $115 for Mohawk & Hudson
[16:09] Player 3 bids $170 for Camden & Amboy
[16:10] Player 4 passes bidding
[16:10] Player 5 passes bidding
[16:10] Player 6 passes bidding
[16:10] Player 1 bids $175 for Camden & Amboy
[16:53] Player 2 passes bidding
[16:53] Player 3 passes bidding
[16:53] Player 4 passes bidding
[16:53] Player 5 passes bidding
[16:53] Player 6 passes bidding
[16:53] Player 1 passes bidding
[16:53] Schuylkill Valley minimum bid decreases from $20 to $15
[16:55] Player 2 passes bidding
```
Do you think that Player 1 should have the first chance to buy SV at $15?

**Comment by rheretic** [comment]
(I need to dig out the rules.  I treat the Private auction bids as a series of rounds starting with the PD and going around.  This may just be oversight on my part - admittedly the Private auction is not really that big a deal. - Unless there is an issue like the who-gets-the discount?)

**Comment by dfannius** [comment]
The Lookout rules say (1.2.3)

> If all of the players pass consecutively during the buy-bid-turn sequence and the SV is unsold, the price to buy the SV is reduced by $5 and the buy-bid-turn sequence resumes.

It isn't explicit about who it resumes with, but I think the most reasonable interpretation is that it's the next player after the one who just passed.

The Avalon Hill rules say:

> If a complete Stock Round fails to sell the Schuylkill Valley Navigation and Railroad Company, then another Stock Round is commenced immediately.

and they don't even hand out the Priority Deal card at all until all the privates are bought, so I think it can't be relevant to the resumption order.

**Comment by dfannius** [comment]
So I'm going to take the "bug" label off. We can always add it back if convincing arguments crop up.

**Comment by rheretic** [comment]
I'll post to Rules Help and we'll see what JCL says.

After rereading the rules (from AH, as the Mayfield / Lookout are not considered authoritative), I think a very reasonable interpretation is:

If a complete Stock Round fails to sell the Schuylkill Valley Navigation and Railroad Company, then another Stock Round is commenced immediately (starting with the First Player).

**Comment by rheretic** [comment]
JCL confirms the above as correct (as shown in log).  I concur with Minor for the PD marker.

As I said in Rules Help, the minor weirdness to me is that the Player 1 autobuys at zero even if as in this case that Player 2 is given first choice at the discount.

**Comment by rheretic** [comment]
Note:  my previous post is no longer valid as the responses have been clarified to Player 2 would have to buy it for free which makes this implementation much more consistent.

**Comment by tobymao** [comment]
Who says Lookout is not authoritative? 

Should this issue be closed or is it still valid?

**Comment by rheretic** [comment]
> Who says Lookout is not authoritative?
> 

Ask JCL.

> Should this issue be closed or is it still valid?

It's a cosmetic issue in that the PD really shouldn't be anywhere yet.

**Comment by dfannius** [comment]
The original issue still stands (the Priority Deal marker moves when people take actions other than buying the lowest private for face value), but has no effect on gameplay. Everything else is fine.

**Comment by tobymao** [comment]
> > Who says Lookout is not authoritative?
> 
> Ask JCL.

JCL doesn't define the definition of 1830.

**Comment by rheretic** [comment]
(There was a bug here after all - just not the one I originally saw!  Opened 3803 on it.)
