### ISSUE TITLE
18Mag missing link in spreadsheet when no president

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3798]
When a corporation has no president, the link from the spreadsheet to that point in the game is missing. See for example https://18xx.games/game/26627?finished=13#spreadsheet where in OR1.1 2.1 3.1 and 3.2 the G&C and SIK are missing the underline on their payout, which would link to that point in the game. It would be nice if no-president corporation payouts also linked to the relevant spot in the game, as is done for corporations that have a president.

<img width="236" alt="Screen Shot 2021-02-11 at 2 05 12 PM" src="https://user-images.githubusercontent.com/8732435/107704490-2f442a00-6c72-11eb-898a-a93afbb9e69c.png">

**Comment by yzemaze** [comment]
@daniel-sousa-me

**Comment by daniel-sousa-me** [comment]
Same thing as #3848. Both are fixed by #3943, but 1860 is causing problems

**Comment by daniel-sousa-me** [comment]
Actually my PR doesn't fix 18Mag, because it's not calling `super` :(
