### ISSUE TITLE
18Mag sort by player doesn't sort by minor

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3799]
https://18xx.games/game/26627?finished=13#spreadsheet

When I sort the spreadsheet by player, the minor corporations are not sorted. It would be nice if the * marking ownership of a minor was included in the sorting, so that all the minors owned by (in this example) Excalabur appeared in a group.

<img width="441" alt="Screen Shot 2021-02-11 at 2 06 50 PM" src="https://user-images.githubusercontent.com/8732435/107704608-66b2d680-6c72-11eb-949d-9052383d23c6.png">

**Comment by yzemaze** [comment]
Choose a or b.

![image](https://user-images.githubusercontent.com/33390595/110912440-3c594500-8314-11eb-81b9-4ed64c3e617f.png)

![image](https://user-images.githubusercontent.com/33390595/110912469-45e2ad00-8314-11eb-8683-f9d5fbca2c38.png)

**Comment by ChrisTheCat** [comment]
If you're talking about sorting Excalabur, I prefer the first one, where RABA is at the bottom.
