### ISSUE TITLE
1860: Game allows insolvent company to lay track with terrain costs

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#3802]
See the title.

Per the 1860 rules, p. 13, "An insolvent company must retain revenue, may not place base tokens, **and may not upgrade track or build track that would incur a cost**. "

https://18xx.games/game/26419?action=241

I just was able to lay a terrain track as the IOW (currently insolvent), just to try it.   I "did the right thing" in the game and did NOT lay it, but hopefully you can find the bug.   Here's a screenshot just in case:

![image](https://user-images.githubusercontent.com/66023744/107715179-b4dccf80-6c9c-11eb-9e35-aff78c841edd.png)

**Comment by roseundy** [comment]
Any change you can provide a link to a game that exhibits this behavior? It takes time to get the game into this state to test a fix.

**Comment by roseundy** [comment]
I suspect I broke this when cleaning up code prior to beta.

**Comment by roseundy** [comment]
Yep. I accidentally deleted this from lay_tile_action:

```
if @game.insolvent?(spender) && cost.positive?
  raise GameError, "#{spender.id} cannot pay for a tile when insolvent"
end
```
