### ISSUE TITLE
[1860] Sales within a single turn should only be in blocks

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#3804]
A player may sell a single share, then in the same turn sell a second single share of the same company to avoid impacting share price if the company is in the green zone of the market. This should not be possible

pg 8 of the rules: "When a player sells more than one share in a single company on a single turn, these shares are always counted as being sold at the same time in a single transaction. In this way, Bill may not sell his three shares as three separate sales and so avoid causing the share price to drop"

To fix, once a sale of a stock is made in a turn, the option to make additional sales of that stock should disappear for that turn, forcing all sales to be made as blocks as intended. Additional shares can be sold not impacting the price later in the stock round, but not within the same turn.

**Comment by roseundy** [comment]
You are confusing turn with round.

**Comment by roseundy** [comment]
This was working correctly at one point, but not now. My apologies.
