### ISSUE TITLE
1860: Company displays should say "INSOLVENT", "NO DIRECTOR", etc.  like the physical game cards do

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#3805]
See the title.  I'm now playing in the 1860 tournament; it's my first plays of 1860 on 18xx.games.   My IOW was recently insolvent and I almost couldn't tell, since the "**Inslvnt**" text is in _teeny tiny font_ at the bottom of the company box. 

The physical game has "INSOLVENT", "NO DIRECTOR", and "BANKRUPT" cards to place on company charters while so indicated.  These are **very** easy to spot even from across the table:

![image](https://user-images.githubusercontent.com/66023744/107720269-076fb900-6ca8-11eb-9465-6a1d0dfb7cf1.png)

My suggestion is that you should display a similar banner on the company boxes, like this, instead of the teeny tiny font:
(*behind* the text, obviously... apologies for the quick & dirty graphics)

![image](https://user-images.githubusercontent.com/66023744/107720810-1f940800-6ca9-11eb-9e70-9bfbc0a7ea22.png)

**Comment by roseundy** [comment]
@yzemaze, care to take a crack at this? I'm not up to speed on the CSS needed to make this work.

**Comment by yzemaze** [comment]
I wouldn’t, because it looks ugly. You could more or less copy & paste the code from the div right above it:
![image](https://user-images.githubusercontent.com/33390595/107807264-2a61a200-6d68-11eb-9b28-0327fa26b10a.png)

**Comment by waaayback** [comment]
that works for me. Just so they are obvious.
