### ISSUE TITLE
Remove "with rotation X" from the game log

### ISSUE THREAD

**Issue by Anvil-X** [tobymao/18xx#381]
Line should just read something like: SR lays tile 440 on K4

**Comment by tobymao** [comment]
I disagree with this as the rotation is important information.

**Comment by Anvil-X** [comment]
No it is not. There is no user on this site that parsed that info in the
log

**Comment by tobymao** [comment]
i believe you should be able to fully replay a game from the textual log

**Comment by Anvil-X** [comment]
If you insist on including this, can you help me to understand how it is used. Rotation number is not a concept in any physical 18xx game that I've seen, and it's not explained anywhere on this site. 

This remains a suboptimal approach. Better is to create a compact behind the scenes notation that is stored in a separate file that can be replayed in a manner similar to PGN format for chess.

**Comment by Anvil-X** [comment]
@tobymao Still waiting to learn how to use this useless rotation information.  Also, any input on doing proper game replay rather than stepping through a text log manually?
