### ISSUE TITLE
Add button to map menu which allows you to 'preview' tile upgrades

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#3812]
It would be nice if we could click a button at the bottom of the map (on the map tab specifically) which would let us use the same 'place and upgrade tile' interface we get during track building, but allow it for every hex and through all the phases.  

The reason this would be useful is that there are many hexes which have specific tiles that are needed to upgrade and it's often a bit hard to visualize the various ways those tiles are allowed to be placed.  In some cases, going back and forth from map screen to tile screen is required to fully visualize all the options.

And in other games certain tiles have to be placed in a specific orientation.  Being able to 'preview/plan' with a 'copy' of the current map screen would be a valuable feature.  It would also help one to realize that the tile they want has already run out.

The way I envision this working is thus: When you click the 'preview/plan' button, it copies the current map and enables track laying/upgrading interface with all hexes and phases allowed.  There should be a border around the map to help indicate that you are in the 'preview' mode and not viewing the actual game map (to avoid confusion).  

When players are done, they can click the 'preview/plan' button again to go back to the main map view.  Pressing it a third time would create a NEW copy of the NEW current map (if any changes had been made since the last time).

The main value of this would be speeding up of players turns who are unfamiliar with the peculiarities of the specific title being played.  We've had a number of live games grind to a halt when someone starts their turn and goes "oh, why can't I place this tile like this?  Oh, hmmm, I see, I'll need to re-think my turn, one moment."

**Comment by roocell** [comment]
also be able to rotate that tile in the preview.
rotating on the tiles tab would be nice too.

**Comment by bridger15** [comment]
Yes, my thought would be that the interface would work exactly the same as during normal track build (click, see upgrades, place, rotate), except if you click green checkmark, it doesn't construct anything on the 'real' map, it only updates this 'temporary preview map'.  You could 'reset' your personal preview map at any time with a different button press, and click back to the main map whenever you wanted.

**Comment by yzemaze** [comment]
sounds like #1279 on steroids
