### ISSUE TITLE
1861 - Shows train exchanges wrongly 

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#3818]
In 1867 there are exchange purchases.  In 1861 they don't exist.  The 1861 game displays the exchange costs on the info tab.  This applies to all games of 1861
Sample game https://18xx.games/game/27544 any action
![image](https://user-images.githubusercontent.com/11814681/107814658-2afb3800-6d6a-11eb-9488-3e370d14f891.png)

**Comment by jenf** [comment]
Already fixed
