### ISSUE TITLE
1861: RSR buys wrong train

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#3832]
RSR bought a 4 from the pool when it should have bought a new 7.

https://18xx.games/game/27578?action=471

From the AAG rules: "The RSR always buys the cheapest _new_ train(s) from the Bank..."
(The GTG rules are ambiguous.)

**Comment by OedipussyRex** [comment]
The problem is that the GTG rules state that the RSR purchases as many "available trains as it can afford (8.13)," "available" meaning from the bank or the market. A lot of issues arise from the discrepancies between the two rulebooks.

**Comment by Maxwell-Frank** [comment]
We encountered this problem in a recent game we played. I too thought it should always buy a new train, but were unable to confirm in the new rules, so we just let it go.

**Comment by ianwilson156** [comment]
Sigh. Another mitsake in the new rules. The whole <point> of the National Railway is to push the trains - so buying a train from the Pool is just wrong.

**Comment by jenf** [comment]
@ianwilson156 is Josh aware of this one?

**Comment by ianwilson156** [comment]
TBD...


------ Original Message ------

**Comment by ianwilson156** [comment]
Reviewing this with Josh, it's actually a bit more complicated. The AAG rules say:
"The Russian State Railway always buys the cheapest new train(s) from the Bank if it has sufficient money in its
treasury." and "If the Russian State Railway has no train, it will buy the cheapest train from the Bank or Bank Pool". 
So it all depends on whether it already has a train. In the case in point, it should have bought the new 7 (since it already owned a 4).
But one could imagine a scenario where it first comes to run and there's a 3 in the pool...

**Comment by jenf** [comment]
That sounds confusing, at present the implementation is such that it never buys from the pool... Let me know if this is incorrect. I want to move 1861 to production soon.

**Comment by ianwilson156** [comment]
The current implementation is incorrect. If trainless, the RSR will buy the cheapest train; if there's one in the Pool, that's likely to be the cheapest.
If it has a train, the implementation is correct i.e. not from the Pool.

**Comment by jenf** [comment]
Will amend the implementation

**Comment by jenf** [comment]
Thankfully my current game actually hit the condition... unfortunately I have to pin my own game :(
