### ISSUE TITLE
1861: name of company

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#3833]
Having both MK and MKR is confusing. I suggest changing the Moscow, Kiev and Voronezh from MKR to MKV.

**Comment by jenf** [comment]
@ianwilson156 Just to double check

So MKR should be MKV. All the other corps keep their existing names?

**Comment by ianwilson156** [comment]
The Grand Russian is usually called the GRR - I don't know why - but 
there's no possible confusion, so no real need to change.

------ Original Message ------

**Comment by jenf** [comment]
Ok, I'll change GR -> GRR and MKR -> MKV
