### ISSUE TITLE
Enhancement - (1830, other Stock Trash Games) - Show Sold Shares on player entity

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#3836]
Stock Trashing (without being an actual Short Position) is very common in 1830 and its ilk.  As a Player I would like to be able to look at my player information and know which shares I'm Long and which I'm Short (short in 1830 terms meaning that I have sold them this SR).

This information is available by scanning the different companies but it would be easier to plan and digest if it was indicated in my player information.

**Comment by rheretic** [comment]
In the games that support actual Shorting, is this shown as part of the Player Information?  Is so then it's not to far a leap to treat the stock sale as an actual short and show it as such.  (This may or may not work right out of the box because in 1830 you will often end up both Long and "Short" at the same time.)

**Comment by dfannius** [comment]
In games with short shares, they are displayed along with regular shares (as a negative number).

Personally, I think that merely having sold stock is very different from actually owning short shares (which carry a liability), and if the former is displayed on the player card I'd want to ensure that it can't be confused with the latter.

**Comment by rheretic** [comment]
I don't disagree.  (I haven't tried any of the games with actual shorts so I don't know how it was implemented.  That part was an idea for how it might be really easy to have with little work.)

**Comment by Maxwell-Frank** [comment]
Sales are already indicated in red on the spreadsheet.

**Comment by rheretic** [comment]
Can you play the game on the Spreadsheet tab?  

Wherever I am "running the game" I need to be able to look at my  player information and see which stocks I own and which stocks that I have sold this Stock Round.

**Comment by scottredracecar** [comment]
This works as requested now
