### ISSUE TITLE
[1828.Game] Unable to pass through Virginia Coaldfields

### ISSUE THREAD

**Issue by Ogrius** [tobymao/18xx#3843]
GameID: 27727

https://18xx.games/game/27727

C&O has two 3+D trains and a coal marker.

It should be able to run:
- Richmond -> Virginia Tunnel (Skipping town) -> Virignia Coalfields -> Nashville
- Richmond -> Norfolk

But the Richmond to Nashville run fails to allow to run through the Coal Fields.

The Coal marker was just acquired this Operating turn.

**Comment by Maxwell-Frank** [comment]
It works for me.  Maybe you just needed to refresh the browser after gaining the coal token?  It's definitely a bug, but I think it's a common issue in many games.

**Comment by crericha** [comment]
I am able to reproduce in a hotseat game from action 480 of the game above. The graph is not being reloaded. 

Until a fix is made, a workaround is to refresh the page.
