### ISSUE TITLE
Spreadsheet OR-history: withholds aren’t linked

### ISSUE THREAD

**Issue by yzemaze** [tobymao/18xx#3848]
If there’s no run, maybe the share price change log entry should be linked instead. (Original PR #2426)

Example: https://18xx.games/game/23120#spreadsheet
![image](https://user-images.githubusercontent.com/33390595/107869973-7873c400-6e94-11eb-956b-c80fdd320889.png)

**Comment by ventusignis** [comment]
In my test game of 1846, the first trainless OR withhold of 0 isn't linked, but a later withhold is linked

**Comment by yzemaze** [comment]
> In my test game of 1846, the first trainless OR withhold of 0 isn't linked, but a later withhold is linked

I added an example. Please link your test game if it’s live or paste the json on gist and link here.

**Comment by yzemaze** [comment]
@daniel-sousa-me Care to look at it? (You should know this code better than me ;-) )

**Comment by daniel-sousa-me** [comment]
Yeah, it's not about withholding. I can fix this.
