### ISSUE TITLE
Reorganize game code so that each game has its own JS bundle

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#3849]
See #3679, which does this for 1889. Once that is merged, I will quickly have PRs open for 18Chesapeake (and Off the Rails), 18MEX, and 1846 (and its 2p Variant, and 18 Los Angeles), as I already have the work done locally for those titles.

#3679 provides a new rake task, `rake move_game`. It moves files around and fixes import paths and does its best to fix imported constants used, but manual work is still needed to be sure rubocop is happy, the unit tests pass, and all DB games of that title are validated.

Once #3679 is merged, I'll be happy to work through this list (probably starting with titles in production), and if anyone else wants to pitch in, let me know and I'll try to keep this checklist up to date, only checking items off once they are in master. For games in active development, it would be most helpful if whoever is working on the game could take care of moving it--I think this would be the best way to avoid merge conflicts.

Games which are implemented as subclasses of others are moved by the rake task when their parent class is moved, i.e., `rake move_game[g_1846]` will move the code for 1846, 1846 2p Variant, and 18 Los Angeles. 
## Michael B:

- [x] `g_1846`
    * `g_1846_two_player_variant`
    * `g_18_los_angeles`
- [x] `g_1889`
- [x] `g_18_chesapeake`
    * `g_18_chesapeake_off_the_rails`
- [x] `g_18_mex`
- [x] `g_1817`
    * `g_1817_na`
    * `g_1817_wo`
    * `g_1877`
    * `g_18_usa`
- [x] `g_1849`
    * `g_1849_boot`
- [x] `g_1867`
    * `g_1861`

## Ryan Driskel
- [x] `g_18_co`
- [x] `g_18_eu`
- [x] `g_18_al`
- [x] `g_18_ga`
- [x] `g_18_tn`

## Steve Undy
- [x] `g_1860`
- [x] `g_1873`
- [x] `g_18_mag`

## Jen

- [x] `g_1830`
- [x] `g_1836_jr30`
- [x] `g_1882`
- [x] `g_1848`
- [x] `g_18_zoo`
- [x] `g_1835`
- [x] `g_1870`

## Matthew

- [x] `g_1856`
- [x] `g_18_fl`

## Chris R

- [x] `g_1828`

## Per W:
- [x] `g_1824`
- [x] `g_1893`
- [x] `g_18_ms`
- [x] `g_18_sj`

## Magnus

- [x] `g_1822`

### Alpha

- [x] `g_18_cz`

**Comment by michaeljb** [comment]
copying from Slack:

Short guide for moving a game's files to the new structure:
* comment on or update my top post in https://github.com/tobymao/18xx/issues/3849 to show you’re working on moving a particular game
* run the rake task, eg, rake move_game[g_1889] (can't run on the container, it also creates a git commit)
* Make manual changes to get rubocop and unit tests passing and to make the constants in game.rb that used to be in the config JSON more readable (eg I updated MARKET on 1889); you’ll probably need to verify that constants imported from other files are referenced correctly, my script fixes some but not all such references
* do some manual testing for the title in the browser
* Verify games in db
* Don’t count on anything being a 100% straight shot :grimacing:, feel free to ping me if something seems wonky after you’ve run the rake task

**Comment by daniel-sousa-me** [comment]
I'll take care of 1870 (hopefully soon)

**Comment by Zwergenpunk** [comment]
I will take care of 18CZ when the PRs of @benjaminxscott  are merged

**Comment by jenf** [comment]
All games moved over, closing!
