### ISSUE TITLE
[1860] Incorrect revenue for FYN 7+4 Train in Nationalization

### ISSUE THREAD

**Issue by joolsian** [tobymao/18xx#3857]
https://18xx.games/game/23637
https://18xx.games/game/23637?action=661

Nationalization has begun, FYN has a 7+4 train, and they are going to run 7 stops for 280p, but when submit is clicked, the revenue is recorded as 300p. Pre-submit screenshot:
![image](https://user-images.githubusercontent.com/79059869/107887630-42e2d100-6ebc-11eb-93f5-7a240002055e.png)

Post-submit:
![image](https://user-images.githubusercontent.com/79059869/107887657-758cc980-6ebc-11eb-831f-d9e8552a6a2c.png)

I'm running Chrome on my laptop, version 88.0.4324.150

**Comment by roseundy** [comment]
I can't reproduce this.

**Comment by roseundy** [comment]
There are a bunch of undo's and redo's around this point. That may have something to do with it, but I don't have a smoking gun.

**Comment by roseundy** [comment]
Are you positive you didn't hit "redo" instead of "submit"?

**Comment by joolsian** [comment]
Gotcha, that could be! I'm fairly positive that I clicked submit when it said 280, but then ran for 300, but it seems to be all sorted out now. You're probably right that I was messing with it. Thanks!
