### ISSUE TITLE
Hotkeys to change tabs: Provide option for Left Handed Hotkeys Only

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#3868]
I just noticed that there are now hotkeys to switch from one tab to another.  This is great!...except that they require me to either remove my hand from the mouse or look down at my keyboard.  Specifically, my left hand does not intuitively know where/how to hit the I, K, and M keys.  

This means that, for all intents and purposes, these hotkeys are useless to me.  The whole point of the hotkeys is to allow me to work the interface quickly without taking my eyes off the screen, and if I have to remove my hand from the mouse, or look down at the keyboard, they defeat their own purpose.

I propose an alternate suite of keyboard shortcuts (available as an option in player profile preferences) designed to only use keys easily accessible by the left hand:

TAB (or tilde (~)) = Game
Q = Entities
W = Map
E = Market
R = Info
T = Tiles
Y = Spreadsheet
G = Tools

These keys aren't as easy to memorize because they are not intrinsically linked with the name of the thing they are activating, but they *are* linked specially, as they follow the exact tabs order across the top of the screen. 

I would also suggest working in Undo and Redo as Ctrl+Z and Ctrl+Y, as those are the universal "undo" and "redo" keys in most productivity applications (word, photoshop, etc.)

**Comment by OedipussyRex** [comment]
And how does this help those who don't use the god-awful qwerty keyboard?

**Comment by dfannius** [comment]
I imagine it wouldn't.

**Comment by bridger15** [comment]
> And how does this help those who don't use the god-awful qwerty keyboard?

Yes, sorry, of course.  Why didn't I consider those 3 people when I made this suggestion? :P

**Comment by tobymao** [comment]
i don't use qwerty. aoensuthao

**Comment by yzemaze** [comment]
In addition to Dvorak and other non-qwerty keyboard layouts:
As of now there are [19 hotkeys](https://github.com/tobymao/18xx/wiki/Power-User-Features#hotkeys) already and there’ll likely be more down the road (undo/redo, maybe some of home/your games, profile, help & next game etc). So you’ll be running out of keys known to your left-hand pretty soon. I thought about number keys in addition to letters for tabs. This would be easy to implement and at least a tad more intuitive than qwerty etc., but also not exactly left-hand-friendly. User definitions would work, but bloat the code base and profile/settings page if done in a proper manner. **If** toby would approve of more code for a nice to have feature I don’t mind adding this, but I’m pretty sure he’s not a fan ;-)

I usually enjoy more config options, but I know I’m in the minority – most of the time. My conclusion: In addition to keyboard macros I use 3rd party tools to style and enhance sites if admins don’t comply with my rather special suggestions …

**Comment by tobymao** [comment]
closing for now unless there's a lot more demand
