### ISSUE TITLE
18CZ game says company has less money then it shows on the interface

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#3870]
https://18xx.games/game/27945?action=303

I placed a token
company ran and paid out
it said i had 121 and i tried to buy a 3train for 120 and the game gave me an error message that said i only had 119.

I just didnt buy the token and we went on

**Comment by benjaminxscott** [comment]
I wasn't able to repro [using that game](https://gist.github.com/benjaminxscott/3c06da8824232d83217adbb2e6cc52e2)
On the OFE:
- Tokened the OO city for 40K (presumably it doesn't matter where the token lands)
- Ran for 70K from Y to OO
- Paid out
- OFE has 121K
- OFE buys 3d for 120K
- OFE has 1K left

**Comment by tobymao** [comment]
did you try to repro it on the server? it won’t show up in hot seat

**Comment by jenf** [comment]
It'll likely be a rounding issue on a payout step

**Comment by benjaminxscott** [comment]
I see, using the instructions in slack for how to test using server-compiled JS [1](https://18xxgames.slack.com/archives/C012K0CNY5C/p1613331142465400?thread_ts=1613327758.460000&cid=C012K0CNY5C) [2](https://18xxgames.slack.com/archives/C012K0CNY5C/p1609986667346700)

Using [this branch](https://github.com/benjaminxscott/18xx/tree/18cz_payout_rounding) to add a fixture for [this json](https://gist.github.com/benjaminxscott/3c06da8824232d83217adbb2e6cc52e2)

> docker-compose exec rack rspec spec/ -e 18CZ

```
Failures:

  1) 18CZ payout_rounding matches result exactly
     Failure/Error: raise GameError, "#{name} has #{@cash} and cannot spend #{amount}" if (@cash - amount).negative?
     
     Engine::GameError:
       OFE has 119 and cannot spend 120
```

**Comment by Zwergenpunk** [comment]
For now it always rounds down, so the game can run consistent.
