### ISSUE TITLE
[18CZ] After acquiring a company, the acquired company's treasury doesn't get added to the acquiring company's treasury

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#3872]
https://18xx.games/game/27945?action=389

**How to Reproduce the Bug?**

After BN acquired BCB which had 91K in it's treasury, the 91K was not added to BN's treasury. BN had 295K after acquiring BCB instead of 295+91=386K. I expect the 91K to be available immediately after acquiring so that it can be used to upgrade trains.

**Comment by benjaminxscott** [comment]
fixed by https://github.com/tobymao/18xx/pull/3898
