### ISSUE TITLE
[18CZ] Could not upgrade tile F21 from #2 (yellow double town) to #887p (green purple-edged single town)

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#3874]
https://18xx.games/game/27945?action=231

**How to Reproduce the Bug?**
At this point in the game, BCB tried to use the private ability to upgrade tile F21 from #2 to #887p. This should should be permitted as per the tile upgrade chart:
<img width="519" alt="Screen Shot 2021-02-14 at 6 02 26 PM" src="https://user-images.githubusercontent.com/5924761/107902899-9d9c1d00-6efc-11eb-99b6-cd7d4333ebee.png">

However no tiles upgrade options were available after selecting the private company and then clicking on tile F21.

![Screen Shot 2021-02-14 at 7 42 17 PM](https://user-images.githubusercontent.com/5924761/107902952-c1f7f980-6efc-11eb-9c51-128cc9e4e577.png)

**Comment by Zwergenpunk** [comment]
oh wow. Thats an interesting upgrade. I totally missed that.
