### ISSUE TITLE
[18CZ] Selling shares should return to the bank not the market

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3876]
VII.6 Sale of Shares
* Sold Shares are returned to the Bank (there is no Bank Pool)

When shares are sold they should go back to the IPO, not into a non-existent market

**Comment by Zwergenpunk** [comment]
yeah there is a market right now, but the price is always the same

**Comment by benjaminxscott** [comment]
afaik this is working correctly from a mechanical POV, and is a cosmetic issue

**Comment by ChrisTheCat** [comment]
While cosmetic, the use of the term "IPO" implies that the shares there will be sold at the original par price, which is misleading. I would actually argue for eliminating the IPO from 18CZ entirely, and treating all shares as held by the Market (aka bank).

**Comment by Zwergenpunk** [comment]
Yeah you are right and we should fix it. But the priority here is pretty low.
