### ISSUE TITLE
[18CZ] Companies receiving dividends when paying out

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3877]
__VIII.8 Calculating Income__
--Paying Out Dividends (page 16)
* When a company pays a dividend, players receive the share of the revenue corresponding to the shares they own. _Shares in the Bank pay out to the bank._
(emphasis mine)

When a company pays out, shares that are in the Market (that shouldn't exist) are paying out to the company. 

Taking care of the Market issue should fix this issue.

**Comment by Zwergenpunk** [comment]
I should read all issues ;) That make it a bigger issue.
Thanks for finding all those small bugs

**Comment by Zwergenpunk** [comment]
Fixed. Always pays 0 to corporation
