### ISSUE TITLE
[18CZ] The train rusting schedule on the info tab does not indicate when medium and large trains rust

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#3878]
Here is the train rusting schedule from the rules:

<img width="416" alt="Screen Shot 2021-02-14 at 6 03 38 PM" src="https://user-images.githubusercontent.com/5924761/107904433-a131a300-6f00-11eb-8880-609de44128d6.png">

However the train rusting schedule on the info tab does not indicate when the following trains rust:
2+2
3+3
3E
4E

![Screen Shot 2021-02-14 at 8 08 20 PM](https://user-images.githubusercontent.com/5924761/107904469-bd354480-6f00-11eb-8a03-a5dc2fac7fc1.png)

**Comment by Zwergenpunk** [comment]
Yeah I worked a little on that, but it is implemented correct in the game, but I'm not sure how to display it "nice"

**Comment by khamsoul** [comment]
I think something like having the "Rusts" column on the "4+4f, 4Ef, 4f" row say "2+2 (on 4+4" instead of "None" would do, and so on.

**Comment by benjaminxscott** [comment]
It's tricky since the base code only implements "buying X train rusts Y train" (which is defined by the game config)

So any changes require custom views or refactor of base code
(We have custom code for the rusting, which Zwegenpunk wrote)

**Comment by Zwergenpunk** [comment]
It is actually not so custom. It still works with the rusts_on prop. 
But the info Page only shows rust_on from the main train and not from the variants. 

There is a prototype for this in https://github.com/Zwergenpunk/18xx/tree/feat/game-info-rusting

**Comment by Zwergenpunk** [comment]
Fixed and can be closed
