### ISSUE TITLE
Blocking step Lay/Upgrade Track cannot process action 848

### ISSUE THREAD

**Issue by grandi72** [tobymao/18xx#3884]
Our game is
https://18xx.games/game/27210

Broken action: { "type": "run_routes", "entity": "RCS", "entity_type": "corporation", "id": 848, "created_at": 1613385407, "routes": [ { "train": "12H-0", "connections": [ [ "E7", "C7", "D8", "C9" ], [ "C5", "D6", "E7" ], [ "D4", "C5" ], [ "C3", "D4" ], [ "C3", "D2", "C1" ] ], "hexes": [ "C9", "E7", "C5", "D4", "C3", "C1" ], "revenue": 230, "revenue_str": "C9-E7-C5-D4-C3-C1" } ] }

my Game ID: Grandi72

![Error 848](https://user-images.githubusercontent.com/79090297/107946251-0f25ab00-6f91-11eb-8e94-cbb9e34356fb.png)
**Which Browser / Platform?** ANY browser. I try in Chrome, IE, EDGE, FF
- Platform (Mobile, Tablet, Desktop): Windows

**Comment by dfannius** [comment]
Note that this game is pinned to c9d7a903a4168ad78deb2d7d81afe624bcf7fee7 from February 13.
