### ISSUE TITLE
[18CZ] Game bypassing Token opportunity when current treasury is insufficient

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3886]
Which makes sense. Except that Locals can be sold to the bank to gain sufficient funds. In the example below, BCB used a Local to ignore terrain cost and the game went immediately to running trains, not allowing the opportunity to sell the used Local and place a token.

https://gist.github.com/benjaminxscott/89f36742da322f1a95ec79370d0b9238

**Comment by benjaminxscott** [comment]
Probably we need to define a custom `issuable_shares` for CZ that checks how much money could be raised by trading in privates

This would then work the same way that 46 does, where it checks whether a company could issue shares to raise enough money, and then blocks on the step if so

https://github.com/tobymao/18xx/blob/master/lib/engine/game/base.rb#L1411

**Comment by michaeljb** [comment]
Here's another instance - https://18xx.games/game/34045?action=387

Desired outcome:

* regular tile lay
* use large company to place a purple-framed tile
* sell large company for cash
* place token

Actual:

* regular tile lay
* use large company to place a purple-framed tile
* token step skipped
