### ISSUE TITLE
1849: show in market when par prices activate

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#3890]
At the beginning of the game, the only pars available are L.68 and L.100. When the green phase is reached, the L.144 box becomes available, and when the brown phase is reached, the L.216 box becomes available. It would be nice to call these out in the market by shading them differently. The par boxes are already yellow, so we could make the L.144 one light green and L.216 a light brown. ([They're shaded in the physical game.](https://boardgamegeek.com/image/5984052/1849-game-sicilian-railways))

I don't know what other titles, if any, have this sort of mechanism; it would be useful to have a list of them to ensure that if this feature is implemented it's done in a way useful for other titles.

**Comment by crericha** [comment]
1828.Games has this functionality. It's straightforward to do using the par groups.

**Comment by dfannius** [comment]
Great, I'll do it myself with that as a model.

**Comment by dfannius** [comment]
Implemented with #3900.
