### ISSUE TITLE
Arrows should max out at available cash when buying across

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3892]
https://18xx.games/game/26721?action=288

SV has 5 but for some reason when you mash the up arrow, it maxes out at 7. Expected behavior would be to max at 5, just like the down arrow has a minimum of 1.

<img width="393" alt="Screen Shot 2021-02-15 at 8 43 20 AM" src="https://user-images.githubusercontent.com/8732435/107973251-dfaf7800-6f69-11eb-9b66-d65ddba7285d.png">

**Comment by yzemaze** [comment]
Looks to me like `+ entity.owner.cash` in https://github.com/tobymao/18xx/blob/master/lib/engine/step/train.rb#L187 is just wrong, but I’m not sure. @jenf

**Comment by jenf** [comment]
It shouldn't be going into that branch at all if it's another players train. Although there's some games where there is a limit on the price between players.

**Comment by yzemaze** [comment]
Yep, only `if @game.class::EBUY_OTHER_VALUE && (buying_power(entity) < train.price)`.
But the path via price_range leads there. I couldn’t find another def spend_minmax and the calculation is correct (5+2=7).

**Comment by ChrisTheCat** [comment]
Not sure if this is relevant, but in the example given I'm buying a train from my own corporation, so it's not another player's train.
