### ISSUE TITLE
1849: Stock movement rule on sales not enforced

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#3894]
In the 1849 rule book it has a this rule when selling shares (rule 9.2.3):
"The banker moves the stock market token(s) of the corporation(s)
whose stock has been sold one row down for each share sold.
When stock in more than one corporation is sold, the banker
moves the stock market token of the corporations whose stock
has been sold in current market value order. This means that if
three shares are being sold (in corporations A, B, and C) and they
are all on currently the same price (with A on top and C at the
bottom of the stack), after the sale the order of the stack remains
unchanged."

What is different than most 18xx games is that the resulting stock order is not based on the order sold, but should maintain the order in which they started. This is currently not enforced. I've attached a short hotseat game with the scenario where the last action was to sell 3 stocks showing that the order changes.

I realize this is probably a real pain to implement, but it can have a significant game impact. I didn't check, but I would assume this also applies to the 1849: Kingdom of the two Sicilies game too.

Here is the hotseat game:
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1613409028,
      "company": "RSA",
      "price": 155
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1613409035,
      "company": "SCE",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1613409038,
      "company": "SIGI",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 4,
      "created_at": 1613409041,
      "company": "CNM",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 5,
      "created_at": 1613409046
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "created_at": 1613409052,
      "company": "SMS",
      "price": 110
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "created_at": 1613409054,
      "corporation": "ATA",
      "share_price": "100,3,5"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 8,
      "created_at": 1613409066,
      "corporation": "CTL",
      "share_price": "100,3,5"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "created_at": 1613409069,
      "shares": [
        "CTL_1"
      ],
      "percent": 10
    },
    {
      "type": "par",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 10,
      "created_at": 1613409073,
      "corporation": "RCS",
      "share_price": "100,3,5"
    },
    {
      "type": "buy_shares",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 11,
      "created_at": 1613409075,
      "shares": [
        "RCS_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "created_at": 1613409092,
      "shares": [
        "ATA_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 13,
      "created_at": 1613409116
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "created_at": 1613409121
    },
    {
      "type": "lay_tile",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 15,
      "created_at": 1613409127,
      "hex": "L12",
      "tile": "78-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 16,
      "created_at": 1613409130
    },
    {
      "type": "buy_train",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 17,
      "created_at": 1613409131,
      "train": "4H-0",
      "price": 100,
      "variant": "4H"
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 18,
      "created_at": 1613409137
    },
    {
      "type": "lay_tile",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 19,
      "created_at": 1613409144,
      "hex": "D2",
      "tile": "79-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 20,
      "created_at": 1613409145
    },
    {
      "type": "buy_train",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 21,
      "created_at": 1613409147,
      "train": "4H-1",
      "price": 100,
      "variant": "4H"
    },
    {
      "type": "pass",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 22,
      "created_at": 1613409149
    },
    {
      "type": "lay_tile",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 23,
      "created_at": 1613409153,
      "hex": "D6",
      "tile": "9-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 24,
      "created_at": 1613409154,
      "train": "4H-2",
      "price": 100,
      "variant": "4H"
    },
    {
      "type": "pass",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 25,
      "created_at": 1613409155
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 26,
      "created_at": 1613409162,
      "shares": [
        "ATA_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 27,
      "created_at": 1613409163
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 28,
      "created_at": 1613409163
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "created_at": 1613409164
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30,
      "created_at": 1613409167,
      "shares": [
        "CTL_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "created_at": 1613409168
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 32,
      "created_at": 1613409169
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 33,
      "created_at": 1613409169
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 34,
      "created_at": 1613409174,
      "shares": [
        "RCS_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 35,
      "created_at": 1613409175
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 36,
      "created_at": 1613409176
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 37,
      "created_at": 1613409176
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 38,
      "created_at": 1613409177
    },
    {
      "type": "lay_tile",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 39,
      "created_at": 1613409188,
      "hex": "N10",
      "tile": "58-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 40,
      "created_at": 1613409191
    },
    {
      "type": "run_routes",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 41,
      "created_at": 1613409197,
      "routes": [
        {
          "train": "4H-0",
          "connections": [
            [
              "M13",
              "L12",
              "M11"
            ]
          ],
          "hexes": [
            "M11",
            "M13"
          ],
          "revenue": 30,
          "revenue_str": "M11-M13"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 42,
      "created_at": 1613409198,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 43,
      "created_at": 1613409200
    },
    {
      "type": "pass",
      "entity": "ATA",
      "entity_type": "corporation",
      "id": 44,
      "created_at": 1613409203
    },
    {
      "type": "lay_tile",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 45,
      "created_at": 1613409209,
      "hex": "C3",
      "tile": "73-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 46,
      "created_at": 1613409211
    },
    {
      "type": "run_routes",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 47,
      "created_at": 1613409215,
      "routes": [
        {
          "train": "4H-1",
          "connections": [
            [
              "C1",
              "E1"
            ]
          ],
          "hexes": [
            "E1",
            "C1"
          ],
          "revenue": 40,
          "revenue_str": "E1-C1"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 48,
      "created_at": 1613409216,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 49,
      "created_at": 1613409217
    },
    {
      "type": "pass",
      "entity": "CTL",
      "entity_type": "corporation",
      "id": 50,
      "created_at": 1613409219
    },
    {
      "type": "lay_tile",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 51,
      "created_at": 1613409224,
      "hex": "E7",
      "tile": "4-0",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 52,
      "created_at": 1613409229,
      "routes": [
        {
          "train": "4H-2",
          "connections": [
            [
              "C5",
              "D6",
              "E7"
            ],
            [
              "A5",
              "C5"
            ]
          ],
          "hexes": [
            "E7",
            "C5",
            "A5"
          ],
          "revenue": 70,
          "revenue_str": "E7-C5-A5"
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 53,
      "created_at": 1613409230,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 54,
      "created_at": 1613409231
    },
    {
      "type": "pass",
      "entity": "RCS",
      "entity_type": "corporation",
      "id": 55,
      "created_at": 1613409232
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 56,
      "created_at": 1613409236
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 57,
      "created_at": 1613409237
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 58,
      "created_at": 1613409237
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 59,
      "created_at": 1613409455,
      "shares": [
        "RCS_2"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 60,
      "created_at": 1613409458,
      "shares": [
        "CTL_2"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 61,
      "created_at": 1613409461,
      "shares": [
        "ATA_2"
      ],
      "percent": 10
    }
  ],
  "id": "hs_zaxzzdie_1613408982",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    },
    {
      "name": "Player 4"
    }
  ],
  "title": "1849",
  "description": "",
  "max_players": "4",
  "settings": {
    "optional_rules": [
      "delay_ift"
    ]
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-02-15",
  "loaded": true,
  "result": {},
  "turn": 3,
  "round": "Stock Round",
  "acting": [
    "Player 2"
  ],
  "updated_at": 1613409461
}

**Comment by tysen** [comment]
The order is fixed as soon as you finish the stock turn. Click "Done".
