### ISSUE TITLE
Make map hexes non transparent when it's not laying track phase

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#39]
make sure to handle tile laying privates

**Comment by Tin-Whisker** [comment]
Overall the map is much too transparent for my tastes.

**Comment by Anvil-X** [comment]
I cannot see any value to having the map visibility reduced ever

**Comment by tobymao** [comment]
@Anvil-X it helps tremendously when figuring out where you can lay your track. This is especially useful for new players.

**Comment by Anvil-X** [comment]
I get that you can use technology to make a game easier to learn or play but this is not an example of that.  If you honestly think that players need help identifying the big fat black lines at the edges of tiles, then make some kind of highlighting there.  Making the map unreadable is not helpful.

**Comment by Bastwood** [comment]
As a newcomer to 1889 and playing my very first game of it with this system, my absolutely biggest gripe was the "dimmed" map board. I'd never taken a close look at the game board, and initially finding just about anything on the board was an exercise in frustration and eye-squinting. I don't really care where I can lay my track if I'm having a hard time seeing the board in the first place. I'm very much in the camp that'd prefer the map to have zero transparency at all times.
