### ISSUE TITLE
Suggested edits so tile page will render for 1846

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#390]
https://github.com/tobymao/18xx/blob/a2f23f6e3e0e98e225fb7973f0dde92d4bf83964/lib/engine/game/g_1846.rb#L247

Replace the string with the number 60, and add a new element named debt with value 80.  Do the same a few lines down at 257, value 40, debt 60, and change 60 to 40 in the description text.

I haven't attempted to determine where the edit to make "debt" part of the cost-to-buy needs to be made.

**Comment by gchambers419** [comment]
https://github.com/tobymao/18xx/blob/a2f23f6e3e0e98e225fb7973f0dde92d4bf83964/lib/engine/game/g_1846.rb#L257

https://github.com/tobymao/18xx/blob/a2f23f6e3e0e98e225fb7973f0dde92d4bf83964/lib/engine/game/g_1846.rb#L260 
are the other two edit sites

**Comment by gchambers419** [comment]
I  did find the "run an auction" code, but an edit there to support "debt" would be semi-moot because 1846 uses a different sort of auction. for privates.

**Comment by kelsin** [comment]
Yeah going to split those into value and debt in 18xx-maker and make the exported output like that as well. Implementation can come later.

**Comment by kelsin** [comment]
The debt change made in my latest PR: #393

**Comment by gchambers419** [comment]
Verified that tile and map pages now render.  Descriptive text for Big 4 is still wrong.

**Comment by kelsin** [comment]
Yeah, don't know how @tobymao wants to represent extra trains that come with a private. My assumption is that we'll remove them from the 18xx-maker export so they aren't in the normal train roster and are given with the private powers etc.

**Comment by gchambers419** [comment]
I was referring to the part about it starting with $60 instead of $40.

I was thinking among the lines of having a "2MS" and "2B4" train type, with zero initially available, but with a "starting_train" property on the minor.

**Comment by michaeljb** [comment]
https://www.18xx.games/map/1846 and https://www.18xx.games/tiles/1846?r=all both render now, so I'm closing this out
