### ISSUE TITLE
[1849:K2S] Company Associated with RSA does not Correspond to the First Company in Order

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3903]
Something has broken with the randomization of company order and association with the RSA Private in Kingdom of Two Sicilies. 

In two games linked below, the company associated with the RSA private is not the first in line and is thus unavailable to be parred. 

https://gist.github.com/Maxwell-Frank/2a861778386491526aee52c51a4c1838

https://gist.github.com/Maxwell-Frank/05b31465b0a2eca78671ebc0634a2a03

**Comment by tobymao** [comment]
@dfannius

**Comment by dfannius** [comment]
Fixed with #3910.
