### ISSUE TITLE
[1867] Unable to place tile #801 in Berlin

### ISSUE THREAD

**Issue by Ogrius** [tobymao/18xx#3906]
Game Link: https://18xx.games/game/28105

https://18xx.games/game/28105?action=570

- During GTR build track, the city Berlin is currently tile #207.
- When clicking in it to upgrade only tile #623 is offered as an upgrade option.
- Tile #801 should be offered as an option as well.
- As per the tiles listing there is a 801 tile left.

Tried refreshing browser and no change.
Using Chrome.

**Comment by jenf** [comment]
Correct behavior see #2999
