### ISSUE TITLE
[18CZ] Show SR/OR Sequence and (more importantly) Private Company Prices

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#3909]
While the info tab does show how many ORs are in the current set and the current price of private companies, it is important to be able to see this information multiple ORs out.  Sometimes you will want to plan for a train purchase or company acquisition and need to know how much your private will be worth next OR or 2 ORs down the line.  I understand that this is an difficult to implement (as it was in MS), but it is critical to game play.

**Comment by benjaminxscott** [comment]
(For context, I implemented the current approach)

Agree that we should have something more similar to the "market / OR" track in the physical game, it wasn't entirely clear where to put that so the current `Info` is a stopgap

Would you expect it to be on the market tab?

**Comment by Maxwell-Frank** [comment]
A visual representation of the OR track from the physical board would be ideal, but that would require significant modification to the current interface.  Maybe something similar to the "Timeline" on the info tab of 18MS would be a good stopgap? 

All I, personally, want is a way to get an overview of the game and see what privates will be worth at any future point in the game, etc. It doesn't need to be pretty, but it'd be nice if it were there.

**Comment by Maxwell-Frank** [comment]
Even a text-based outline might work: 

-SR1
---OR1.1 ($40)
-SR2
---OR2.1 ($45)
