### ISSUE TITLE
1877 - GameError: Blocking step Buy or Sell Shares cannot process action 12 Broken action

### ISSUE THREAD

**Issue by LaytimeDemurrage** [tobymao/18xx#3914]
**27266**

I think it broke when I clicked Buy share, when I couldn't buy anymore shares.

 https://18xx.games/game/27266?action=13

{
  "id": 27266,
  "description": "Learning game- open watch out for the tile set",
  "user": {
    "id": 112,
    "name": "cdhunter"
  },
  "players": [
    {
      "id": 993,
      "name": "kosberg"
    },
    {
      "id": 2181,
      "name": "shermath5"
    },
    {
      "id": 112,
      "name": "cdhunter"
    }
  ],
  "max_players": 3,
  "title": "1877",
  "settings": {
    "seed": 1545299607,
    "unlisted": false,
    "optional_rules": [
      "cross_train"
    ]
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Stock Round",
  "acting": [
    112
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 120,
      "entity": 993,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613013214
    },
    {
      "id": 2,
      "city": "F1-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "Cap",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613013223
    },
    {
      "id": 3,
      "type": "message",
      "entity": 993,
      "message": "Hfgl",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613013248
    },
    {
      "id": 4,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613050998
    },
    {
      "id": 5,
      "type": "bid",
      "price": 125,
      "entity": 112,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613080694
    },
    {
      "id": 6,
      "type": "bid",
      "price": 130,
      "entity": 993,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613094500
    },
    {
      "id": 7,
      "type": "bid",
      "price": 135,
      "entity": 112,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613094821
    },
    {
      "id": 8,
      "type": "bid",
      "price": 140,
      "entity": 993,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613095302
    },
    {
      "id": 9,
      "type": "bid",
      "price": 145,
      "entity": 112,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613095350
    },
    {
      "id": 10,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613095427
    },
    {
      "id": 11,
      "type": "buy_shares",
      "entity": 112,
      "shares": [
        "Cap_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613095628
    },
    {
      "id": 12,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613095644
    },
    {
      "id": 13,
      "type": "bid",
      "price": 130,
      "entity": 993,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613095964
    },
    {
      "id": 14,
      "type": "undo",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613096031
    },
    {
      "id": 15,
      "type": "bid",
      "price": 130,
      "entity": 993,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613096039
    },
    {
      "id": 16,
      "city": "E2-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613096057
    },
    {
      "id": 17,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613096093
    },
    {
      "id": 18,
      "city": "B1-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613096128
    },
    {
      "id": 19,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613135593
    },
    {
      "id": 20,
      "type": "buy_tokens",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141787
    },
    {
      "id": 21,
      "loan": 0,
      "type": "take_loan",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141819
    },
    {
      "id": 22,
      "type": "buy_train",
      "price": 100,
      "train": "2-0",
      "entity": "BPC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141828
    },
    {
      "id": 23,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613141833
    },
    {
      "id": 24,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613141851
    },
    {
      "id": 25,
      "type": "buy_shares",
      "entity": "BPC",
      "shares": [
        "BPC_1"
      ],
      "percent": 20,
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141858
    },
    {
      "id": 26,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613141876
    },
    {
      "id": 27,
      "type": "undo",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613141880
    },
    {
      "id": 28,
      "loan": 1,
      "type": "take_loan",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141887
    },
    {
      "id": 29,
      "type": "buy_shares",
      "entity": "BPC",
      "shares": [
        "BPC_1",
        "BPC_2"
      ],
      "percent": 40,
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141893
    },
    {
      "id": 30,
      "type": "buy_train",
      "price": 100,
      "train": "2-0",
      "entity": "BPC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613141908
    },
    {
      "id": 31,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613141958
    },
    {
      "id": 32,
      "type": "bid",
      "price": 160,
      "entity": 2181,
      "corporation": "PCB",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613142125
    },
    {
      "id": 33,
      "city": "F1-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613142126
    },
    {
      "id": 34,
      "type": "bid",
      "price": 165,
      "entity": 993,
      "corporation": "PCB",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613142215
    },
    {
      "id": 35,
      "type": "bid",
      "price": 170,
      "entity": 2181,
      "corporation": "PCB",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613142237
    },
    {
      "id": 36,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613142555
    },
    {
      "id": 37,
      "type": "buy_tokens",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613142864
    },
    {
      "id": 38,
      "type": "short",
      "entity": 2181,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613142911
    },
    {
      "id": 39,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613142953
    },
    {
      "id": 40,
      "loan": 2,
      "type": "take_loan",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143430
    },
    {
      "id": 41,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613143433
    },
    {
      "id": 42,
      "loan": 2,
      "type": "take_loan",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143458
    },
    {
      "id": 43,
      "loan": 3,
      "type": "take_loan",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143464
    },
    {
      "id": 44,
      "loan": 4,
      "type": "take_loan",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143466
    },
    {
      "id": 45,
      "loan": 5,
      "type": "take_loan",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143470
    },
    {
      "id": 46,
      "loan": 6,
      "type": "take_loan",
      "entity": "PCB",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143478
    },
    {
      "id": 47,
      "type": "buy_shares",
      "entity": "PCB",
      "shares": [
        "PCB_1",
        "PCB_2",
        "PCB_3"
      ],
      "percent": 60,
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613143510
    },
    {
      "id": 48,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613143523
    },
    {
      "id": 49,
      "type": "buy_tokens",
      "entity": "Cap",
      "entity_type": "corporation",
      "user": 112,
      "created_at": 1613151140
    },
    {
      "id": 50,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613151168
    },
    {
      "id": 51,
      "type": "short",
      "entity": 993,
      "corporation": "PCB",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613158822
    },
    {
      "id": 52,
      "type": "bid",
      "price": 130,
      "entity": 993,
      "corporation": "BSC",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613158831
    },
    {
      "id": 53,
      "city": "G4-5-0",
      "slot": 0,
      "type": "place_token",
      "entity": "BSC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613158890
    },
    {
      "id": 54,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613159487
    },
    {
      "id": 55,
      "type": "buy_tokens",
      "entity": "BSC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613162237
    },
    {
      "id": 56,
      "type": "buy_train",
      "price": 100,
      "train": "2-1",
      "entity": "BSC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613162431
    },
    {
      "id": 57,
      "type": "undo",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613162435
    },
    {
      "id": 58,
      "type": "buy_shares",
      "entity": 993,
      "shares": [
        "BSC_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613163057
    },
    {
      "id": 59,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613163061
    },
    {
      "id": 60,
      "loan": 7,
      "type": "take_loan",
      "entity": "BSC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613163631
    },
    {
      "id": 61,
      "loan": 8,
      "type": "take_loan",
      "entity": "BSC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613163642
    },
    {
      "id": 62,
      "type": "buy_shares",
      "entity": "BSC",
      "shares": [
        "BSC_1",
        "BSC_2"
      ],
      "percent": 40,
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613163651
    },
    {
      "id": 63,
      "type": "buy_train",
      "price": 100,
      "train": "2-1",
      "entity": "BSC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613163654
    },
    {
      "id": 64,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613163657
    },
    {
      "id": 65,
      "type": "short",
      "entity": 2181,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613165654
    },
    {
      "id": 66,
      "type": "buy_shares",
      "entity": 2181,
      "shares": [
        "PCB_10"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613165838
    },
    {
      "id": 67,
      "type": "buy_train",
      "price": 100,
      "train": "2-2",
      "entity": "Cap",
      "variant": "2",
      "entity_type": "corporation",
      "user": 112,
      "created_at": 1613175714
    },
    {
      "id": 68,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613175731
    },
    {
      "id": 69,
      "loan": 9,
      "type": "take_loan",
      "entity": "BPC",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613177555
    },
    {
      "id": 70,
      "type": "buy_train",
      "price": 100,
      "train": "2-3",
      "entity": "BPC",
      "variant": "2",
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613177569
    },
    {
      "id": 71,
      "type": "buy_shares",
      "entity": "BPC",
      "shares": [
        "BPC_3"
      ],
      "percent": 20,
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613177592
    },
    {
      "id": 72,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613177599
    },
    {
      "id": 73,
      "type": "short",
      "entity": 2181,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613186682
    },
    {
      "id": 74,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613186743
    },
    {
      "id": 75,
      "type": "buy_shares",
      "entity": 112,
      "shares": [
        "BPC_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613193029
    },
    {
      "id": 76,
      "type": "buy_shares",
      "entity": 993,
      "shares": [
        "BSC_3"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613193723
    },
    {
      "id": 77,
      "type": "short",
      "entity": 2181,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613226096
    },
    {
      "id": 78,
      "type": "buy_shares",
      "entity": 2181,
      "shares": [
        "BSC_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613226131
    },
    {
      "id": 79,
      "type": "buy_shares",
      "entity": 112,
      "shares": [
        "BPC_2"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613255881
    },
    {
      "id": 80,
      "type": "buy_shares",
      "entity": 993,
      "shares": [
        "BPC_3"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613255924
    },
    {
      "id": 81,
      "type": "short",
      "entity": 2181,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613257710
    },
    {
      "id": 82,
      "type": "buy_shares",
      "entity": 2181,
      "shares": [
        "BSC_2"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613258002
    },
    {
      "id": 83,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613289121
    },
    {
      "id": 84,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613314102
    },
    {
      "id": 85,
      "type": "short",
      "entity": 2181,
      "corporation": "Cap",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613323289
    },
    {
      "id": 86,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613328701
    },
    {
      "id": 87,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613333065
    },
    {
      "id": 88,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613334870
    },
    {
      "id": 89,
      "type": "short",
      "entity": 2181,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613341710
    },
    {
      "id": 90,
      "type": "bid",
      "price": 180,
      "entity": 2181,
      "corporation": "CLG",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613341854
    },
    {
      "id": 91,
      "city": "C4-1-0",
      "slot": 0,
      "type": "place_token",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341881
    },
    {
      "id": 92,
      "type": "buy_shares",
      "entity": 2181,
      "shares": [
        "CLG_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613341890
    },
    {
      "id": 93,
      "type": "buy_tokens",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341893
    },
    {
      "id": 94,
      "type": "undo",
      "entity": 112,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613341897
    },
    {
      "id": 95,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613341902
    },
    {
      "id": 96,
      "loan": 10,
      "type": "take_loan",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341907
    },
    {
      "id": 97,
      "loan": 11,
      "type": "take_loan",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341909
    },
    {
      "id": 98,
      "loan": 12,
      "type": "take_loan",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341912
    },
    {
      "id": 99,
      "loan": 13,
      "type": "take_loan",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341915
    },
    {
      "id": 100,
      "loan": 14,
      "type": "take_loan",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341917
    },
    {
      "id": 101,
      "type": "buy_tokens",
      "entity": "CLG",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341935
    },
    {
      "id": 102,
      "type": "buy_shares",
      "entity": "CLG",
      "shares": [
        "CLG_1",
        "CLG_2",
        "CLG_3"
      ],
      "percent": 60,
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613341955
    },
    {
      "id": 103,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613341978
    },
    {
      "id": 104,
      "type": "sell_shares",
      "entity": 112,
      "shares": [
        "BPC_1",
        "BPC_2"
      ],
      "percent": 40,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348732
    },
    {
      "id": 105,
      "type": "short",
      "entity": 112,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348740
    },
    {
      "id": 106,
      "type": "undo",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348758
    },
    {
      "id": 107,
      "type": "undo",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348759
    },
    {
      "id": 108,
      "type": "sell_shares",
      "entity": 112,
      "shares": [
        "BPC_1",
        "BPC_2"
      ],
      "percent": 40,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348769
    },
    {
      "id": 109,
      "type": "short",
      "entity": 112,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348771
    },
    {
      "id": 110,
      "type": "buy_shares",
      "entity": 112,
      "shares": [
        "PCB_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348805
    },
    {
      "id": 111,
      "type": "undo",
      "entity": 993,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348813
    },
    {
      "id": 112,
      "type": "buy_shares",
      "entity": 112,
      "shares": [
        "CLG_1"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348846
    },
    {
      "id": 113,
      "type": "undo",
      "entity": 993,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348860
    },
    {
      "id": 114,
      "type": "bid",
      "price": 150,
      "entity": 112,
      "corporation": "M&M",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348895
    },
    {
      "id": 115,
      "city": "F3-4-0",
      "slot": 0,
      "type": "place_token",
      "entity": "M&M",
      "entity_type": "corporation",
      "user": 112,
      "created_at": 1613348919
    },
    {
      "id": 116,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348926
    },
    {
      "id": 117,
      "type": "undo",
      "entity": "M&M",
      "entity_type": "corporation",
      "user": 112,
      "created_at": 1613348930
    },
    {
      "id": 118,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613348939
    },
    {
      "id": 119,
      "type": "short",
      "entity": 993,
      "corporation": "CLG",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613349496
    },
    {
      "id": 120,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613349503
    },
    {
      "id": 121,
      "type": "short",
      "entity": 2181,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613350504
    },
    {
      "id": 122,
      "type": "buy_shares",
      "entity": 2181,
      "shares": [
        "CLG_10"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613350507
    },
    {
      "id": 123,
      "type": "short",
      "entity": 112,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613350773
    },
    {
      "id": 124,
      "type": "bid",
      "price": 200,
      "entity": 112,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 112,
      "created_at": 1613350784
    },
    {
      "id": 125,
      "city": "F3-4-0",
      "slot": 0,
      "type": "place_token",
      "entity": "TCM",
      "entity_type": "corporation",
      "user": 112,
      "created_at": 1613350810
    },
    {
      "id": 126,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613350843
    },
    {
      "id": 127,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613353202
    },
    {
      "id": 128,
      "type": "short",
      "entity": 2181,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613353613
    },
    {
      "id": 129,
      "type": "undo",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613353651
    },
    {
      "id": 130,
      "type": "short",
      "entity": 2181,
      "corporation": "BPC",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613353654
    },
    {
      "id": 131,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613353704
    },
    {
      "id": 132,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613358145
    },
    {
      "id": 133,
      "type": "short",
      "entity": 993,
      "corporation": "CLG",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613358447
    },
    {
      "id": 134,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613358453
    },
    {
      "id": 135,
      "type": "short",
      "entity": 2181,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613358871
    },
    {
      "id": 136,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613358899
    },
    {
      "id": 137,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613359594
    },
    {
      "id": 138,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613360396
    },
    {
      "id": 139,
      "type": "short",
      "entity": 2181,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613393470
    },
    {
      "id": 140,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613393557
    },
    {
      "id": 141,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613408476
    },
    {
      "id": 142,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613408771
    },
    {
      "id": 143,
      "type": "short",
      "entity": 2181,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613408877
    },
    {
      "id": 144,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613408879
    },
    {
      "id": 145,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613408966
    },
    {
      "id": 146,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613408998
    },
    {
      "id": 147,
      "type": "short",
      "entity": 2181,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613409313
    },
    {
      "id": 148,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613409317
    },
    {
      "id": 149,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613409627
    },
    {
      "id": 150,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613410332
    },
    {
      "id": 151,
      "type": "short",
      "entity": 2181,
      "corporation": "TCM",
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613410355
    },
    {
      "id": 152,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613410391
    },
    {
      "id": 153,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613422006
    },
    {
      "id": 154,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613422943
    },
    {
      "id": 155,
      "type": "sell_shares",
      "entity": 2181,
      "shares": [
        "BSC_1",
        "BSC_2"
      ],
      "percent": 40,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613423477
    },
    {
      "id": 156,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613423506
    },
    {
      "id": 157,
      "type": "undo",
      "entity": 112,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613423537
    },
    {
      "id": 158,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613423547
    },
    {
      "id": 159,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613424919
    },
    {
      "id": 160,
      "type": "buy_shares",
      "entity": "BPC",
      "shares": [
        "BPC_10",
        "BPC_1"
      ],
      "percent": 40,
      "entity_type": "corporation",
      "user": 993,
      "created_at": 1613424996
    },
    {
      "id": 161,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613425011
    },
    {
      "id": 162,
      "type": "buy_shares",
      "entity": "CLG",
      "shares": [
        "CLG_12"
      ],
      "percent": 20,
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613425137
    },
    {
      "id": 163,
      "type": "buy_train",
      "price": 100,
      "train": "2-4",
      "entity": "CLG",
      "variant": "2",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613425145
    },
    {
      "id": 164,
      "type": "buy_train",
      "price": 100,
      "train": "2-5",
      "entity": "CLG",
      "variant": "2",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613425249
    },
    {
      "id": 165,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613425296
    },
    {
      "id": 166,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613425923
    },
    {
      "id": 167,
      "type": "short",
      "entity": 993,
      "corporation": "CLG",
      "entity_type": "player",
      "user": 993,
      "created_at": 1613426157
    },
    {
      "id": 168,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613426163
    },
    {
      "id": 169,
      "type": "buy_train",
      "price": 100,
      "train": "2-6",
      "entity": "PCB",
      "variant": "2",
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613426255
    },
    {
      "id": 170,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613426291
    },
    {
      "id": 171,
      "type": "pass",
      "entity": 112,
      "entity_type": "player",
      "user": 112,
      "created_at": 1613441372
    },
    {
      "id": 172,
      "type": "pass",
      "entity": 993,
      "entity_type": "player",
      "user": 993,
      "created_at": 1613442667
    },
    {
      "id": 173,
      "type": "buy_shares",
      "entity": "CLG",
      "shares": [
        "CLG_14"
      ],
      "percent": 20,
      "entity_type": "corporation",
      "user": 2181,
      "created_at": 1613445462
    },
    {
      "id": 174,
      "type": "pass",
      "entity": 2181,
      "entity_type": "player",
      "user": 2181,
      "created_at": 1613445475
    }
  ],
  "loaded": true,
  "created_at": 1612992636,
  "updated_at": 1613445475
}

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by tobymao** [comment]
migrating
