### ISSUE TITLE
[18CZ] Acquired company shares are still showing on player "charters"

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3916]
OFE and MW were acquired and closed in the previous set of ORs, but are still showing up --and counting against cert limit-- in the player info box during the subsequent Stock Round.

https://gist.github.com/OedipussyRex/0be8eb16eca8f1f412cbe152f4317635

Edit: Companies still showing up in later ORs, too.

Edit 2: It may or may not be relevant that the two companies acquired were trainless at the time. Other companies in the game had trains when acquired and closed properly.

**Comment by Zwergenpunk** [comment]
I don't see it. When I import the state everything looks good =(

**Comment by benjaminxscott** [comment]
I'm able to repro via hotseat on the live site

![Screenshot 2021-02-16 at 1 32 49 PM](https://user-images.githubusercontent.com/1711810/108124243-d4d51000-705b-11eb-836c-d8f863bacb9a.png)

**Comment by pstone1** [comment]
They also still appear to count towards the cert limit. https://18xx.games/game/27929 I should have a current cert count of 10, but 3 acquired shares are still counting against my tally (OFE and MW have closed)

![image](https://user-images.githubusercontent.com/13589848/108160838-7a659f00-70af-11eb-9da7-f33073a29682.png)

**Comment by benjaminxscott** [comment]
That's fixed in the PR, it's not merged yet
