### ISSUE TITLE
[18CZ] Display player debt in player info boxes

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3917]
As far as I could see, the only time that information is displayed is during the player's turn in the Stock Round as a button below the "Pass (Share)" button, reading "Payoff all debt (K__)" 

Also, "payoff" is a bribe (The inspector needed his payoff before approving the electrical work) or a return of some kind of investment (Randy Andy had a good payoff in the fifth at the track).

To "pay off" is to pay in full or make the final payment.

**Comment by ventusignis** [comment]
I recommend the UI be expanded to something like this
![image](https://user-images.githubusercontent.com/2993555/108633085-5a800380-7440-11eb-9430-060e6db54032.png)


This can be done in a general way so that 1822, 1849, and 1824 (1844/1854 someday?) could use it
