### ISSUE TITLE
[18CZ] Large Companies not allowed to place token in first operation

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3918]
Placing the home token is counting against large companies' token placement. Happened with both large companies in the linked game (json).

https://gist.github.com/OedipussyRex/aec1ba0deb40f5fe647074d24069bb85

**Comment by benjaminxscott** [comment]
My dev setup is broken but I think this is fixable by adding `extra: true` to `place_token()` in our custom home_tile step

https://github.com/tobymao/18xx/blob/master/lib/engine/step/g_18_cz/home_track.rb#L64

**Comment by Zwergenpunk** [comment]
yep i make a PR

**Comment by benjaminxscott** [comment]
oh i was about to

**Comment by Zwergenpunk** [comment]
;) alright ;P
