### ISSUE TITLE
[1830] Click on "Buy a train" button changes a phase even if a player doesn't have enough money

### ISSUE THREAD

**Issue by anovosad** [tobymao/18xx#3922]
Happened to me when I had a 4-train and a D-train was available. I didn't had enough money to buy the D-train but I accidentaly clicked on "Buy". A message popped that told me I don't have enough money. But at a same time my 4-train disappeared and phase changed to D.

**Comment by jenf** [comment]
The game should refresh after the error message to not show.

**Comment by anovosad** [comment]
You are right, I tried to undo the game to the exact point, and I think for some reason it did not refresh by itself. Now it refreshs automatically, but it takes a few seconds on my mobile phone to do so.

**Comment by jenf** [comment]
yeah, behaving as intended
