### ISSUE TITLE
Extend hotkey navigation to lobby

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#3932]
**What's your idea?**

Current hotkeys are only for a game. There currently are no hotkeys for the lobby.
Suggestion to use 'L' as hotkey to go back to the lobby, or alternative 'D' for Dashboard.

* Chat shortcut could be the same there.
* Use numbers 1-9 to enter active games (number would have to be added as label)

**Did you join the Slack?**

yes, active as "Jeroen"

**Comment by yzemaze** [comment]
It’s on my todo list, but will need to wait.
Feel free to add more suggestions.

**Comment by scottredracecar** [comment]
Seems to not be in demand
