### ISSUE TITLE
[General] Upgrade options on Map view

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#3944]
I would like to be able to click on tiles in map view and see the build options, kind of like we can see upgrade options by clicking a tile in the tile manifest. 

Planning around others builds is one of the more challenging thing to do for me in this interface. The hot keys are great and definitely assist with this problem. Still I think my above suggestion could help a lot. 

I am rotationally challenged and it's hard for me to conceptualize the chirality of some of the tile options.

I am aware that cloning a game into hotseat mode is an option. One that I do use on occasion that helps a bit with the issue I am having.

**Comment by yzemaze** [comment]
duplicate #3812
