### ISSUE TITLE
1830 Corp value not dropping when shares sold in SR

### ISSUE THREAD

**Issue by NeilEJ** [tobymao/18xx#3946]
https://18xx.games/game/28038

https://18xx.games/game/28038?action=479

during a SR, a share was sold of NYC
NYC was valued $67 prior to the share sale
NYC was valued $67 following the share sale
NYC was not ‘shelved’
NYC marker was in the right most column where the $67 value is one step above yellow $60 value

Apple iPadOS 14.4
![B15FEA4E-D8B1-42C9-BA75-F3E47E29953E](https://user-images.githubusercontent.com/79166927/108111489-a4f23080-708c-11eb-95ea-f1725f40d470.png)
![E3D9566E-9B3A-445C-95AC-1392A9C311CD](https://user-images.githubusercontent.com/79166927/108111500-a7548a80-708c-11eb-8382-cc72d21d7d82.png)

**Comment by dfannius** [comment]
The NYC marker dropped from one 67 box to another 67 box.
