### ISSUE TITLE
[18CZ] After acquiring a company, the 40K token of the acquiring company should become a 100K token

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#3957]
https://18xx.games/game/27945?action=483
BN has just placed a token on the board for 40K, even though it already has other tokens on the board via acquisition so it is no longer eligible for the 40K token.

**How to Reproduce the Bug?**

Acquire a company.
Note that the 40K token is still available when it should actually be a 100K token, since the acquisition gives the acquiring company tokens on the board. The 40K token is only available when there are no other tokens from the company on the board except for the home token.

For reference:
https://boardgamegeek.com/thread/2405214/question-regarding-token-placement-cost-after-acqu

**Comment by benjaminxscott** [comment]
Sounds like after an acquisition, a company's next token always costs 100?

**Comment by khamsoul** [comment]
Effectively, yes.

**Comment by Zwergenpunk** [comment]
Oh. I thought the 40 stays 40.

**Comment by benjaminxscott** [comment]
Other wrinkles that probably should be in this same codepath that idk if we handle currently

1 give the acquirer any unplaced tokens from the acquiree
2 if the merger results in an illegal "double token on a hex", give one of them back to the acquirer corp

```
The larger company [acquires] all non-placed station markers. These markers may be used
 as additional station markers for the price of 100 K each. The stations on the map remain there
 and now belong to the larger company.
(Exception: if both companies had station markers on the same hex, one of them must be
removed from the map and returned to the charter. It may later be placed for 100 K 
```

**Comment by Zwergenpunk** [comment]
Yep thats all handled :). All new and returned tokem cost 100. just the Token that cost 40 and is already on the company has to change from 40 to 100

**Comment by benjaminxscott** [comment]
ah gotcha

**Comment by benjaminxscott** [comment]
[testcase](https://gist.github.com/benjaminxscott/43f0167944f3e470d786c3785a8c9519)
(the one in this ticket was pinned and deleted)
