### ISSUE TITLE
Better way to tell which corporations already operated

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3958]
This is particularly for 1817, but would apply to any game. In face-to-face play, it's easy to tell which corporations have already operated and which are still on deck - the operated corporation tokens are flipped upside down. It's not so easy to see that here, for example:

<img width="465" alt="Screen Shot 2021-02-16 at 5 56 42 PM" src="https://user-images.githubusercontent.com/8732435/108145467-56d73000-7080-11eb-8c39-395038e37d43.png">

It would be nice to have some sort of an indicators - greyed out, or outlined?

**Comment by yzemaze** [comment]
@ChrisTheCat
btw: If you already have the perfect test case at hand please always include a link (with action) or a gist, too – else we have to take way more time to find one than it would cost you to copy & paste.

**Comment by ChrisTheCat** [comment]
I don't have a perfect test case. Any 1817 game would do fine, none is more
perfect than another.

**Comment by yzemaze** [comment]
It’s not about "perfect", it’s about having a test case.
Even if all (1817) games were fine (wrong!), whoever takes on an issue would have to look for a game and might need to scroll through history to find an action where at least one company has already operated. Even if this might not take much time, it takes time and it’s pretty unnecessary if you already have a test case at hand. So if you’d like to make developers’ life easier: Please just do as I asked.

**Comment by ChrisTheCat** [comment]
https://18xx.games/game/28159?action=296
https://18xx.games/game/27927?action=762
https://18xx.games/game/27850?action=421
https://18xx.games/game/27496?action=284
https://18xx.games/game/27431?action=612
https://18xx.games/game/27307?action=586

**Comment by scottredracecar** [comment]
I swear the tokens used to have a flipped gray side months ago. It would be
nice to know why that got changed back, unless I am imagining this. Maybe
it was that the gray tokens were too hard to distinguish, but now I only
use simple tokens when available, so it's not such a problem with those.
