### ISSUE TITLE
18CZ log doesn't include full setting of priority

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3959]
https://18xx.games/game/27956?action=159

[17:38]OFE's share price changes from K50 to K53
[17:38]beardbru has priority deal
[17:38]-- Operating Round 3.1 (of 1) --

The log only shows who was given priority, not who got position 2, 3, etc. The log should probably just say:

[time]New priority order: beardbru, ChrisTheCat, papavk, Corian09, tgg

**Comment by benjaminxscott** [comment]
It's a good idea, I'm not sure if other games output this list fwiw - I think spreadsheet shows the order, and Entities is implicitly ordered

(18LA and 22 has a similar reordering so I think such a feature would want to be generic)

Could you remove bug label? There's a PR freeze at Toby's request so to avoid confusion as to which items are bugs or not

**Comment by ChrisTheCat** [comment]
I don't know how to remove the bug label.
