### ISSUE TITLE
18CZ medium corporations require 60% to float

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3960]
While the rule may be "at least 50%," in practice medium companies with a 40/20/20/20 split require 60% to float. It would be better if that was the percentage displayed on the charter.

**Comment by Zwergenpunk** [comment]
For now we won't change that. 
If we change it to 60% there will be another person that claims, that the rules say only 50% are needed.

If this will come up more often, we will maybe review it.
