### ISSUE TITLE
18CZ - Broken game -  Blocking step Sell then Buy Shares cannot process action 

### ISSUE THREAD

**Issue by LaytimeDemurrage** [tobymao/18xx#3962]
**What's your Game ID?** - Game ID 28000

If your game is "Multiplayer" = https://18xx.games/game/28000?action=82

Not sure what triggered it, but the game is broken.

**Comment by benjaminxscott** [comment]
It could be due to a bugfix that was deployed after the game started, games in alpha don't get migrated or pinned so it's probably not going to be continuable unfortunately

**Comment by khamsoul** [comment]
I’m hitting this in my CZ game too, and even Tools->End Game triggers an error message. Is there a workaround to clear broken games from my list of active games?
![BA5A2DE0-FF19-4FAC-BCFB-19C22CA02DB0](https://user-images.githubusercontent.com/5924761/108164802-5ce00780-70a6-11eb-8368-277dd0e536f7.png)

https://18xx.games/game/27945

**Comment by tobymao** [comment]
i've archived your games
