### ISSUE TITLE
Enhancement: automatic auctions

### ISSUE THREAD

**Issue by arcee1986** [tobymao/18xx#3964]
When players are bidding on something (such as a private company in the beginning of 1889) asynchronously, there can be a long delay while they bid it up $5 at a time.  It should be possible to put in a sealed max bid.  If all players do so, the site could resolve the auction automatically.  For example A is first to act, sets max 130, B sets 120, C sets 130, A gets it for 130.

I have suggested this as an option to use (not a setup option, but an alternate box/button during bidding), for a few reasons:
- in a multiplayer situation my bid might depend on which players drop out when.
- There may be other effects of the bid, such as 1867's minor corp treasury and stock prices, meaning that lowest possible win is not necessarily what I want.
- maybe I need some irrational bidding fever!

**Comment by jenf** [comment]
The auction style can change player behaviour.

Also the maximum bid would be visible to other players via the json.

Won't fix
