### ISSUE TITLE
Gap in email notifications shortly after leaving the site

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#397]
I believe the current implementation of email notifications has a gap. If I leave the site, then it becomes my turn in a game less than 60 seconds later, I think that I won't get an email notification. This seems like misbehavior that should be addressed.

**Comment by tobymao** [comment]
this is working as intended. do you have another proposal?

**Comment by sparr** [comment]
My initial rough idea would be to keep track of notifications not sent, then send them if the player's session expires after without being refreshed.

In the current case, I missed the start of a realtime/sync game :/

**Comment by angelkurisu** [comment]
The way I've seen this solved elsewhere is that a turn/action notification is sent if it has been your turn for more than X minutes (depending on the game's weight)

For an 18XX, you could have the system queue a notification to be sent in say, 10 minutes, when it becomes a player's turn to act. When it's time to send it out, the system checks "Is the game state still where it was?" If so, actually send notification. If the game state has advanced, it dumps it.
