### ISSUE TITLE
[18CZ] autopass during the ISR if funds are insuficient

### ISSUE THREAD

**Issue by skizelo** [tobymao/18xx#3981]
If someone doesn't have enough money to draft a local railway, the client still waits for them to Pass (their only legal move). I noticed it in this game here https://18xx.games/game/27953?action=26 where Silvergoose had $45 and the only remaining local costs $80.

**Comment by benjaminxscott** [comment]
I have a branch for this after the feature freeze thaws (only bugfixes for now)
https://github.com/benjaminxscott/18xx/tree/18cz_autopass_draft
