### ISSUE TITLE
Game Deleted without Notice

### ISSUE THREAD

**Issue by tckoppang** [tobymao/18xx#399]
My game #448 was just deleted without notice. I had it bookmarked, but the link just throws an error now when I try to load the URL. Was there a problem with the server? Or did one of my fellow players, perhaps, gain permission to delete the game? It certainly wasn't finished. I really don't know what happened! https://18xx.games/game/448

**Comment by tobymao** [comment]
an email was sent explaining this deletion. it was due to the routing rewrite

**Comment by tobymao** [comment]
double checking and i did send an email to the one listed in the database with your username

**Comment by tckoppang** [comment]
Yep, just checked my email and the notice came through. Well, bummer. Thanks for the follow up.
