### ISSUE TITLE
[18CZ] Small Local Railway Power Randomly used

### ISSUE THREAD

**Issue by heidebrechtluke** [tobymao/18xx#3990]
https://18xx.games/game/28518

- Action 143 https://18xx.games/game/28518?action=143 - something happened to randomly trigger the company special action without the player having used it.  

This is my first report so sorry for formatting.  

Company MW - first to operate in OR 5.1 was looking to use local railroad (Small #3) special power to lay purple edged tile but was unable to.  Map remained "greyed out".  Players noticed that special power was used regardless. 

Using Chrome on Windows laptop.

**Comment by ChrisTheCat** [comment]
On action 143, small #3 is listed at 1/1. On action 144, it's 0/1.

**Comment by benjaminxscott** [comment]
I can repro this via given [testcase](https://gist.github.com/benjaminxscott/23cdcbb163ee5a65f28f0e8d478744c7):

- click G20
- click to enable private ability toggle
- click any other non-greyed tile, such as G24
- click G20 again
- click to disable private ability toggle
- select a regular green tile for G20
- uses selected private ability

May be a generic private ability issue, I have no idea how that code works 
cc @michaeljb 

The CZ privates use a [standard `tile_lay`](https://github.com/tobymao/18xx/blob/master/lib/engine/config/game/g_18_cz.rb#L307) ability with restricted `hexes` that don't include G20, so not sure what can be changed on the CZ side

switching out bug label using [this similar rubric](https://github.com/tobymao/18xx/issues/3783#issuecomment-778243112)

**Comment by heidebrechtluke** [comment]
We were just entering SR 7 and the game quite with an error: {"error":"<<: undefined method `<<' for nil"}

We are unable to access it again and it does not appear on the homepage on 18xx.games.

**Comment by heidebrechtluke** [comment]
If it is possible to salvage the game we would like to finish.

**Comment by tobymao** [comment]
nope sorry the game is archived

**Comment by Zwergenpunk** [comment]
That is really interesting. One tile_lay ability does not have a limit on hexes so all hexes are possible.
But both abilities have a restrain on tiles, an tile can `#208` never be placed with an ability. =/

**Comment by Zwergenpunk** [comment]
I created another effect, but probably the same origin:
You can use the purple upgrade but as a tile_lay so you could probably place every turn a purple tile
https://gist.github.com/Zwergenpunk/93a852ae164bee9e76841dd6002e8e38

To reproduce: 
Be in track Step:
- click on tile to build:
- activate ability
- select purple tile
- deacivate ability
- place tile
- profit

**Comment by Zwergenpunk** [comment]
Should be fixed with changes from @crericha
