### ISSUE TITLE
[1846] Can't assign MPC Token

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#3996]
https://18xx.games/game/27406

PRR previously bought the Meat Packing but didn't assign the token in that same round. 2 ORs later, there is no option for it now to place the token. The game is still in green phase so this should be possible.

**Comment by OedipussyRex** [comment]
Cloned the game and messed around. Meatpacking, already in the company, has no button above to assign the token. In addition, after Steamboat is bought in, it also isn't given a button to possibly reassign the token location, which it (Steamboat) is allowed to do when bought in and at the start of each OR until Brown.

**Comment by benjaminxscott** [comment]
Which step? (Or include the json blob at the step) It looks like the game is still going on

**Comment by OedipussyRex** [comment]
Here's a json where I cloned and undid to the start of PRR's OR. Meatpacking is in the company at 1/1, but no button for abilities.
https://gist.github.com/OedipussyRex/41cb8f26aba9b2dff5420ff629511089
