### ISSUE TITLE
confirmation dialog hidden on row A when zoomed out

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#4000]
https://18xx.games/game/28317?action=1436

For a few turns now, and with multiple minors, I’ve been unable to lay a tile on A16. There are tiles available, I have the terrain cost and a valid route. When I tap the hex, I select any of the available tiles, it places it, but I’m not given the Green Check/Red X to confirm or reject the placement. 

From what I can tell, it’s only that hex.

**Comment by roseundy** [comment]
I can't reproduce this. It works for me when I clone your game to that point.

**Comment by roseundy** [comment]
What OS/browser are you using?

**Comment by philcampeau** [comment]
Safari, iOS 14.4, iPhone 8

**Comment by roseundy** [comment]
I was afraid of that. This might be phone/tablet vs. desktop issue.
@yzemaze ? There is nothing in 18Mag that should affect whether you get the checkmark dialog.

**Comment by yzemaze** [comment]
Best guess: Confirmation dialog gets rendered, but is invisible because it gets moved too much to the top and is then hidden, because of the overflow. I’ll check.

**Comment by yzemaze** [comment]
It looks like this on Browserstack (iPhone 8, iOS 13.0, Safari and iPhone 11, iOS 14.0 Safari)
![image](https://user-images.githubusercontent.com/33390595/108401562-c41fc800-721c-11eb-9196-c1d8ad3cf75c.png)

**Comment by yzemaze** [comment]
Hah. @philcampeau Zoomed out a lot? (5+ steps?) Then the dialog disappears indeed …
![image](https://user-images.githubusercontent.com/33390595/108402396-bcacee80-721d-11eb-97c0-715e814b9602.png)

**Comment by philcampeau** [comment]
Mystery solved! Zooming in did in fact solve it!
