### ISSUE TITLE
[18CZ] Company unable to cross-buy train

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4004]
https://18xx.games/game/28590?action=259

The EKJ has no train and wants to cross-buy the 4T out of the BN, but for some reason this is not allowed.

**Comment by Zwergenpunk** [comment]
I read the rules wrong. 
I understood that when you have to buy a train, you cannot buy from another player.

But apparently it is, that you cannot take a dept to buy a train from another corporation

**Comment by pstone1** [comment]
Right. Should be the same as 30/89/46/most titles. You also cannot contribute the presidents money to a cross buy, but you are allowed to cross buy if the company has at least 1$, so being in emergency financing should not preclude a cross buy, but selling a share to fund it (or paying more than in the company treasury) would.

**Comment by Maxwell-Frank** [comment]
It should be the same as 89; can cross-buy trains for <= company treasury, but can only take loans to buy trains from the bank/pool.

**Comment by Zwergenpunk** [comment]
yep, thanks. I think i fixed it (when deployed)
