### ISSUE TITLE
[18CZ]  Game breaks on route running step 

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#4013]
My instinct tells me that this has already been reported...  but on the off-chance it hasn't, here it is.

Can't run a route at this step.

edit: https://gist.github.com/benjaminxscott/3650f87325023ec501f21c74a76e91db

**Comment by Zwergenpunk** [comment]
What error do you receive? I cannot reproduce it, and when I run a train and validate the game log, no error is thrown

**Comment by benjaminxscott** [comment]
can't repro either, using these routes it works

```
D5-E10
D5-D3
```

@SmithInMN - could you clarify which routes are attempting to be run? 
(and/or a screenshot of the repro case)

**Comment by Zwergenpunk** [comment]
Closing it for now since no further information were provided
