### ISSUE TITLE
[18CZ] Small company payout should be 50/50

### ISSUE THREAD

**Issue by chrispday** [tobymao/18xx#4015]
During the pay out of a small company for 50 revenue, paid out 12/share (2.0 per player) when it should have paid 25 each as 50% shareholders.
https://18xx.games/game/28176

From the log
```
[12:54]VBW passes place a token
[12:54]VBW runs a 2a train for K50: I12-I10
[12:54]VBW pays out K50 = K12 per share (K24 to ChrisD, K24 to Liturgia)
[12:54]VBW's share price changes from K63 to K68
```

From the rules
```
The revenue is always rounded up in favor of the
owner. For example: If the total revenue is K 110,
the owner of a 25% share receives K 28. A player
who owns two 25% shares receives exactly 50% of
the revenue, or K 55, and a player who owns a 50%
Director’s Certificate and a 25% share receives K
83. Calculation cards are included.
```

**Comment by mouseworthy** [comment]
To clarify the issue - it's not just the 50% split, it impacts all odd (that is 30, 50, 70, etc) revenues for small (4-share) companies. From the same game:

```
[14:12]BCB runs a 2a train for K40: E14-E12
[14:12]BCB runs a 2a train for K30: E14-E16
[14:12]BCB pays out K70 = K17 per share (K51 to packrat, K17 to mouse)
```
(where payouts for that should be 53 and 18 respectively)

**Comment by Zwergenpunk** [comment]
Yep, we know.

It is. A little but complicated, because all other games have a corp size of 2 5 or 10 and that is nice for dividing.

4 is not so nice. I just rounded down for now that server and client are in sync.
Will fix it soon.
