### ISSUE TITLE
1817 add totem variant

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4016]
The 1817 totem variant is intended to remove the benefit of sitting to the left of the player that merges a lot. It only applies during M&A rounds.

At the beginning of the game, place a totem in reverse priority order. E.g. in a four player game, the last player in priority gets the 1 totem, the third player gets the 2 totem, and so forth.

When a player merges or converts, after the president buys shares, the player with the 1 totem gets first dibs on the new share, the 2 totem gets second dibs, and so forth. If any player exercises their totem option to buy a share, they move to the bottom of the totem and all players that were behind them move up one position. If a player declines to purchase a share, they retain their position in the totem.

**Comment by jenf** [comment]
Please provide reference to where the varient is discussed

**Comment by ChrisTheCat** [comment]
https://groups.io/g/18xx/topic/40541216#45551

**Comment by crericha** [comment]
@tobymao do you approve of this variant? I'd consider implementing it if you bless it.

**Comment by tobymao** [comment]
this is the "seattle" variant? if you wanna do it go for it

**Comment by crericha** [comment]
Yes, correct. Okay, I'll add it to my mental list of things I want to do eventually.
