### ISSUE TITLE
[18CZ] Rusted trains are showing in the train depot as discards

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#4020]
https://18xx.games/game/28871?action=730

UG just bought a 3d train from the depot even though it should have been rusted as we are in phase i.

**Comment by khamsoul** [comment]
I guess this is just the logical consequence of https://github.com/tobymao/18xx/issues/4012 and discarding after hitting the train limit.

**Comment by Zwergenpunk** [comment]
Fixed. Although it is complicated. 2 train may show up in discsrd but only the 2+2 is buyable for example.
