### ISSUE TITLE
[18CZ] After hitting the last "Skip Companies" button at the end of the game, "Loading game..." is displayed forever

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#4022]
https://18xx.games/game/28871

Game 28871 cannot be loaded (displays "Loading game..." forever) but it does show up as a finished game in my profile.

<img width="379" alt="Screen Shot 2021-02-18 at 10 22 16 PM" src="https://user-images.githubusercontent.com/5924761/108465962-c3485f80-7237-11eb-9673-a8749fb0c50e.png">

**Comment by Zwergenpunk** [comment]
=( I was so excited.

**Comment by khamsoul** [comment]
Haha I did wonder if our game was the first CZ that ran to completion

**Comment by benjaminxscott** [comment]
Not sure if we can triage this since the game is archived, if it's OK to close w/ you
