### ISSUE TITLE
Rule 8.1d Routing through blocked cities

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#403]
1. KO was allowed to run a route through E2 and F9 with its 6T, both of which are blocked to KO. 
2. KU was allowed to run a route through E2, F9, and H7 with its D, all 3 of which are blocked to KU. 

This may have been the case even before the new routing system.
This is probably a duplicate of https://github.com/tobymao/18xx/issues/120, but the title name there talks about revenue, not route legality. 

JSON blob of the HS game in this gist: https://gist.github.com/yoyoson/36a2fa44fdd1bed569f015f88118090b

**Comment by tobymao** [comment]
thanks i have a fix for this coming tomororow

**Comment by yoyoson** [comment]
Thank you in advance, and for the amazing efforts you're putting into this!!
