### ISSUE TITLE
18CZ Missing Rule for buying train when blocked with not runnable trains

### ISSUE THREAD

**Issue by Zwergenpunk** [tobymao/18xx#4033]
> The only exception is in the rare circumstance that a Phase change leaves a company at the train limit with only trains the company can’t run. Then, the company may and must buy a train it can run and then return one other train to the Train Pool without compensation.

This is not implemented yet.

**Comment by benjaminxscott** [comment]
Can we check "if company is at train limit without any runnable trains", and then force a discard step to get to `trainlimit -1`

Instead of doing exactly what the rules say, of buying and then discarding

**Comment by Maxwell-Frank** [comment]
What about the contrived scenario in which a company just buys up to train limit with trains it cannot run?  Is it then compelled to discard to buy a runnable train?  This doesn't seem to be explicit in the rules.

**Comment by benjaminxscott** [comment]
My read is it would be compelled to do so (and I think this is enforced currently)

A company could do that, and in fact may want to do so in order to force-rust trains of different sizes that other companies own

```
VIII.10 Purchase of Trains
Each share company must at the end of its operating turn own a train which it could run

A company may own smaller trains. Still, each company must own a train it could run for revenue (even if it currently has no
revenue-producing route.)

```

**Comment by Zwergenpunk** [comment]
Yeah that is enforced. You have to buy a runnable train. If you have only 1 slot open the UI only shows runnable trains

**Comment by benjaminxscott** [comment]
> If you have only 1 slot open the UI only shows runnable trains
This impl seems correct, and my note about it buying up to train limit and then discarding is incorrect

```
Trains can be never scrapped voluntarily. Scrapping only happens during a phase change [or acquisition]
```

**Comment by Zwergenpunk** [comment]
I asked Lonny about that and have now a clue what todo and how this is happening:

A medium corp buys  a 2+2c and 2 3d trains in its turn. Until its next turn all e are bought and 1 f train.
The corp has now only 2 3d trains an is at the train limit. 
In that case the corpoation may return 1 3d train to the train pool and has to buy a 4+4 train.
The returning is happening in (or right before) the buy_train step.

**Comment by Zwergenpunk** [comment]
I wanted to implement and tried to reproduce it for the first time.
The behaviour is now pretty correct:
The corporation has only 2 3d trains and has to buy a new train. 

After buying a train a discard step is added immediately.

This is not the actual expected behaviour but so close that I'm not going to change anything.

@ViennaTramways do you think that is reasonable?

If someone wants to try it here is gist:
https://gist.github.com/Zwergenpunk/8ddc768cf3bfd168f2c26af4cdfa5630

**Comment by ViennaTramways** [comment]
Yes,
should be ok I think

Lonny

Am Sa., 24. Apr. 2021 um 22:59 Uhr schrieb Michael ***@***.***
