### ISSUE TITLE
1830 Erie Home Station Placement

### ISSUE THREAD

**Issue by Beezy18xx** [tobymao/18xx#4036]
Erie is being prompted to select its home station placement after a different company upgrades the Erie's yellow home tile to green. The prompt happens during the other company's turn. When the Erie president (if different from the current acting player) is prompted to select a home station location, the game informs the player it is not their turn and does not permit placement by that player. The current acting player may select the home selection instead. The Erie president should be able to select which side of the tile.

**Comment by dfannius** [comment]
@Beezy18xx Can you link to the game?

**Comment by dfannius** [comment]
Looks like it's https://18xx.games/game/28977?action=369.

**Comment by Beezy18xx** [comment]
Yes, https://18xx.games/game/28977?action=369

**Comment by tobymao** [comment]
we've ruled that the player laying the tile determines the position of the token.

**Comment by Beezy18xx** [comment]
I assume the code for implementing the Erie's behavior can be found in 1828 if you want an easy fix that some people play with regarding the Erie's home. The alternative that groups play with is the Erie selecting the location on its operating turn and its home not being able to be stationed until it does so. 

I have not yet come across a group that has decided a company other than the Erie gets to select where the Erie's home station gets to be. I would request implementing a version of the game that reflects at least some portion of how the game is actually played.

**Comment by clearclaw** [comment]
That's pretty clearly wrong.  The AH rules make clear that the Erie must select the location of its home,  quote: "No other token may be placed here until the Erie has established its base."  That's the ERIE establishing its home, not the tile-placing player.  

Common practice is that the ERIE director must select a HOME immediately the tile is placed, should the ERIE have operated, interrupting other actions.  If not, then the ERIE will select its home when it operates.

**Comment by tobymao** [comment]
The AH are not clear about what happens in an upgrade situation, so your statement is false.

**Comment by tobymao** [comment]
I'm open to having someone implement the Erie placing variant as an optional rule. So if someone wants to tackle that, it will be merged.

**Comment by Beezy18xx** [comment]
If you're going to be lazy about it I'd suggest at the very least fixing it so that the Erie president isn't prompted for the Erie to place its station when its tile is upgraded and then being told its not their turn.

**Comment by tobymao** [comment]
No need to be condescending. Please update the issue accordingly. I will reopen this issue to reflect that is the change to make.

**Comment by tobymao** [comment]
closed for #4040
