### ISSUE TITLE
[1830] Log is incorrect when ERIE token is being replaced

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#4040]
In this game, ERIE has already placed a token in its home hex when it operated. NYC upgrades the tile and is prompted to place ERIE's token in either city space (correct behavior).
https://18xx.games/game/28977?action=369

However, the log says:
[15:48]ERIE must choose city for token

This comment is misleading because although ERIE's charter is displayed, NYC retains the action to replace the token.

A better prompt for this action would be:
Choose a city for the ERIE token

This issue probably also applies to 1836Jr. (sorry I didn't check!)

**Comment by crericha** [comment]
I don't see where in the 1830 rulebook it says the corporation laying the tile gets to choose the token location. I checked 1828 too and its rules explicitly say Erie gets to choose.

@scottredracecar, can you point me to the relevant rule for 1830?

**Comment by tobymao** [comment]
the 1830 rules don’t address this edge case.

**Comment by crericha** [comment]
And no clarification from Francis Tresham before he passed?

Is there any precedence in the 18xx family for other corporations choosing where another corporations token goes?

While the specific edge case isn't addressed, the rulebook only speaks of a corporation placing its own tokens, so lacking better info, it seems to me the bug is that NYC is placing the token.

Thoughts?

**Comment by tobymao** [comment]
Intuitively, it makes sense that when a tile is upgraded, the corporation laying the tile is the one that choses how it is laid. So why would a corporation that is not operating decide where to move their token? If you think about it from a thematic perspective, a corporation building track isn't going to accommodate what another corp wants. It will simply choose to build track however it wants. The 'Erie' has already chosen where it's home station goes. If it cares about how future track is built, it should build it itself.

**Comment by crericha** [comment]
Thematically, I think Buffalo and Dunkirk are in fixed locations. If Erie is forced to lay a token (which other games don't require), then they are the ones determining the fixed location of it...not someone who runs track through the city.

**Comment by tobymao** [comment]
The specific situation is that Erie has already laid the token. They have thus chosen where there token is. They are fixed. When someone lays new track they determine how they want to route it. The corporation laying new track hasn't moved Erie's tokens. They've simply laid the track however they want. Erie has no say in how another corporation lays its track.

**Comment by crericha** [comment]
My point is if Erie lays their token here in Dunkirk

![image](https://user-images.githubusercontent.com/67359577/108951008-36d1de80-7635-11eb-8db5-ce8e9f6d43fe.png)

and PRR then lays the tile and places the Erie token like this

![image](https://user-images.githubusercontent.com/67359577/108951275-aa73eb80-7635-11eb-9d09-f83c0a45cc81.png)

then it doesn't make thematic sense to me why PRR gets to move the physical location of Dunkirk to above Buffalo. Sure PRR gets to decide how the tile goes in, but they can't arbitrarily decide Buffalo is now south of Dunkirk.

Its unfortunate that the rule book doesn't specify and their wasn't a ruling from Mr. Tresham, but I'm having a hard time coming up with a reason that a different corporation gets to choose where the Erie station goes, both thematically and by precedence from other games in the 18xx family. The closest thing we have is JC clarifying the rule in 1828 to allow Erie to lay the token (only one data point and not enough to draw a conclusion). I wonder what the dos game does...

My opinion is there is a lack of theme or precedence for the tile laying corp to do more than determine where the tile track heads are and for Erie to choose the token location.

**Comment by crericha** [comment]
The dos game supports your position Toby.
