### ISSUE TITLE
[1828.games] Champlain & St. Lawrence only allows use of ability when first purchased

### ISSUE THREAD

**Issue by bubba0077** [tobymao/18xx#4041]
**Issue**
CPR was unable to use the special power of Champlain & St. Lawrence to lay a track in B24 in OR 4.1. An option was given when Champlain & St. Lawrence was first purchased, but afterwards it could not be used.

Unable to use: https://18xx.games/game/28486?action=217
First purchased: https://18xx.games/game/28486?action=152

https://gist.github.com/bubba0077/85a79aa25b1d231e60de582af170a5c1

**How to Reproduce the Bug**

1. Purchase Champlain & St. Lawrence
2. Note the option to lay the extra track
3. Decline the option
4. Champlain & St. Lawrence's ability can no longer be used.

**Which Browser / Platform?**
Tested on both Firefox 85.0.2 and Chrome 88.0.4324.182

**Comment by crericha** [comment]
Good catch. Fixed.
