### ISSUE TITLE
1846 28394

### ISSUE THREAD

**Issue by SYXXsFM** [tobymao/18xx#4049]
Maybe connected to the way in which programming reacts to the use of arrrow keys but I tried to set rites for NYC in the final OR and could not get the ones I wanted so I left my laptop, When I returned the NYC go had been terminated and it had withheld its [incorrect] dividend. I have no idea why.

**Comment by yzemaze** [comment]
https://18xx.games/game/28394?action=580
From the game data (tools – show game data – search for `id": 580`) it looks like you cleared all your routes/trains and submitted $0 (at 1613813095 / GMT 09:24:55). There aren’t any undos logged there.

Arrow hotkeys just step through history, they have nothing to do with undo/redo. You need to use buttons or ctrl+z/y to undo/redo actions.

**Comment by dfannius** [comment]
This seems unlikely to be a real issue; we can reopen it if more comes to light.
