### ISSUE TITLE
18CZ need previous train information for acquisitions

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4054]
When acquiring a small or medium corporation, the acquiring corporation may convert a train to a larger type that is represented on the same train card (a physical card in the game with three types of trains printed on it). For example, a 3d could be converted to a 3+3d or a 3Ed.

At this phase of a game (https://18xx.games/game/27956?action=470#info) the info tab does not have this information, because the previous train roster has been removed.

It would be nice if there was an easy way to find out, prior to going through the motions of an acquisition, what the potential train conversions are. The workaround for now is to go back to the start of the history and look at the train roster there, but that's non-intuitive for most users. (You could also look in the rules, but that's even more inconvenient.)

**Comment by Zwergenpunk** [comment]
Any idea what would be easy doable? We could show in the buy Corporation step all trains of corps that can be bought and show upgrad paths and costs

**Comment by jenf** [comment]
Fixed by #4739
