### ISSUE TITLE
[18SJ] Game broken due to second tile lay issue: GameError: Second tile lay or upgrade only allowed if first or second improves main lines!

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#4064]
https://gist.github.com/vints1/77255b988be269b9589a3c22e66d3311

https://18xx.games/game/27436?action=319

Seems the game broke when a player was trying to use the second tile action for main lines to upgrade a city to green.

**Comment by perwestling** [comment]
@vints1 The tile lays in E8 and F9 is not allowed as none of them improves the mainline. That means the tile lay must create a path along the main line from Stockholm to Malmö. 
A previous bug made this allowed (as it only checked edges, not paths) but a recent fix made the given orders illegal and that broke the game. And it cannot be repaired.

So I suggest deleting the game.
