### ISSUE TITLE
Zoom-in hotkey not working on Chromebook or Windows (both Chrome and Firefox)

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#4068]
When on the Map view of a game, I can't use the keyboard zoom in shortcut [+], even though the zoom out [-] and zoom reset [0] shortcuts are working fine. The zoom in button is also working fine. 

I noticed this problem first of all in my multiplayer game of 1830, but also when viewing other players' non-1830 games. 

It is happening in Chrome on both my Chromebook and Windows machine. I opened up Firefox to see if the problem existed there, but unfortunately the keyboard shortcuts don't appear to be working at all in Firefox.

**Comment by yzemaze** [comment]
I can’t reproduce your problem with Chrome. + works fine.
Which keyboard layout do you use? Which + key are you using? (letter-block or numpad?) Are you sure your keyboard works fine?

> I opened up Firefox to see if the problem existed there, but unfortunately the keyboard shortcuts don't appear to be working at all in Firefox.

They do work in Firefox, but you need to click once into the game area.
> Shortcuts function only if div#game or body is focussed. There should be no interference with the chat/input. Downside: on some browsers one click is necessary to focus (almost? anywhere but button, inputs, chat and top menu bar) before shortcuts work as intended. div#game is set to autofocus, but this is a hack and doesn’t work reliably on all browsers. (While testing Chrome did fine, FF didn’t. ymmv)

from https://github.com/tobymao/18xx/pull/3811#issue-572563297 This behavior will be improved.

**Comment by zurfarosa** [comment]
OK, now got the other keyboard shortcuts working in Firefox on my Windows laptop - but the [+] shortcut isn't working, even though the [-] and [0] shortcuts are. 

So the shortcut isn't working for me: 
- On Chrome or Firefox
- On Windows or Chromebook
- Even when I disable all my Chrome extensions
- Even though I have no problem typing [+] on my keyboard. 

My keyboards are both UK keyboards, and I'm using the row of numbers above the QWERTY row (not a numpad).

**Comment by yzemaze** [comment]
> Does the + button work like it should?

(when clicked with a mouse) Does the behavior of + hotkey change after that?

Also: Log out and log in and check again please.

**Comment by yzemaze** [comment]
Lachlan on Slack [confirmed](https://18xxgames.slack.com/archives/CV3R3HPUZ/p1613901873044200) the issue. I’ll dissect …

**Comment by zurfarosa** [comment]
> (when clicked with a mouse) Does the behavior of + hotkey change after that?

No, when I click the zoom-in button with the mouse, the [+] hotkey still doesn't work. 

> Also: Log out and log in and check again please.

When I log out and browse other people's games, the problem persists (i.e. zoom-out and zoom-reset hotkeys work, but zoom-in doesn't). Logging back in again doesn't change anything. 

I'm using a UK keyboard ([layout shown here](http://www.farah.cl/Keyboardery/A-Visual-Comparison-of-Different-National-Layouts/#enUK)), but as far as I can see, you access the [+] character the same on UK and US keyboards (i.e. shift + the key two to the right of [0]). Switching to US keyboard makes no difference.

**Comment by yzemaze** [comment]
It shouldn’t make any difference at all, but I’m using qwertz-layout and it works fine. But Lachlan had the same experience as you which is confirmation enough that it’s a general problem.
