### ISSUE TITLE
Enhancement - Stock Round - Pass / Done Button In Line with Company List

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#4069]
Because the Done (Shares) button appears above the Player and Company information it's very easy to forget that you need to click it to end your Stock Turn.  

You could add a fake company which acts as the Pass / Done (Shares) button.  This would be a large visual reminder that you need to end your Stock Turn.

**Comment by yzemaze** [comment]
As long as it’s your turn the game menu background should be colored orange (if you didn’t configure another color). This should be an obvious enough hint it’s still your turn.
If it isn’t it’s rather a general issue of "move to next action/user" buttons not being distinct or highlighted. Please submit another issue with a more general suggestion if you agree. Changing button placement on a specific tab to match one user’s preference isn’t the way to go in this case.
