### ISSUE TITLE
[18CZ] Companies Need 50% in Player Hands to Float

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4071]
https://gist.github.com/Maxwell-Frank/684d8cc94f1a68fc88c2099e4cda3ae0

Companies require 50% in **player hands** to float.  Shares in the market (that should not exist) do not count towards this.  This should increase the priority in resolving #3876 as the market is causing actual gameplay issues. 

See official clarification [here](https://boardgamegeek.com/thread/1882303/article/27421076#27421076).

**Comment by benjaminxscott** [comment]
Thanks for finding these testcases!

If the market refactor mentioned in the other issue is the approach you'd prefer, feel free to make a PR
