### ISSUE TITLE
1860 - Nationalization - running rout with company names switched

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#4086]
https://18xx.games/game/27858

I don’t know how to say what action it is, but here is. The screen shot of what happened.
Essentially, the FYN and NGSTL operated and when they ran their trains, it changed it to the other company running their trains and recorded the total.  To be clear, the FYN has two trains listed as its trains and ran when the NGSTL ran trains. NGSTL has the one train ran as the FYN’s train. 

I tried to look and see if this is listed anywhere and didn’t find it... but did that before and duplicated a request. So I hope this is new!  Sorry if it is a repeat. Also, if it is a repeat, I would love direction on how to find already filed things so I do better in the future. :)
Jen

![E63D1A7C-D47B-41AE-BB26-50F98ACA6CAC](https://user-images.githubusercontent.com/73318207/108627092-0d386d80-7411-11eb-86c1-e80bd75ed76a.png)
![A0FEFA14-B9B1-402C-A428-F1D65759D183](https://user-images.githubusercontent.com/73318207/108627094-0e699a80-7411-11eb-9f30-022550241b1f.png)

**Comment by Eludyan** [comment]
Oh it actually ran the wrong companies trains... anyway. I hope you can figure it out :)

**Comment by roseundy** [comment]
I'm not sure what's going on here. When I back the game up to FYN's run in OR 11.2 and clone it, it works fine. It looks like the database got corrupted somehow. It's almost as if the "submit" for FYN's route got skipped over.
