### ISSUE TITLE
Train limit decrease should offer choice of which trains to discard

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#409]
"The president decides which train is discarded"

**Comment by jenf** [comment]
What's the current behavior?

**Comment by jenf** [comment]
(And can you add a json near that state)

**Comment by sparr** [comment]
I apologize, I think what happened was that another player acted for me. When I roll the game state back to that point I see an action. I will close this issue and reopen it if I can reproduce this in a hotseat game later.
