### ISSUE TITLE
18CZ EMR bug breaks game

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4090]
https://18xx.games/game/27956?action=535

NWB is required to buy a train. The game should be forcing ChrisShaffer to take a K81 loan to finance the train. Instead, it is offering share sales or bankruptcy, neither of which are allowed by the 18CZ rules.

NWB has K170.
ChrisShaffer must contribute K180 for NWB to afford a train from the Depot.
ChrisShaffer has K99 in cash.
ChrisShaffer has K0 in sellable shares.
ChrisShaffer must sell shares to raise at least K81.
ChrisShaffer does not have enough liquidity to contribute towards NWB buying a train from the Depot. NWB must buy a train from another corporation, or ChrisShaffer must declare bankruptcy.

**Comment by Zwergenpunk** [comment]
Ou thats a regressiom bug. It worked sometime ago. I think i know whats happened. Need mure fixtures :(

**Comment by benjaminxscott** [comment]
We [define liquidity during EMR](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_cz.rb#L430) to only reference player cash, so it wouldn't have allowed stock sales even if there was enough to cover

The UI runs through the boilerplate EMR flow since we don't redefine that, which is why it outputs the sellable shares info

**Comment by ChrisTheCat** [comment]
This should not be closed. What am I supposed to do? The game wants me to sell shares (impossible) or declare bankruptcy (also impossible). How am I to continue my turn?

**Comment by benjaminxscott** [comment]
Zwerg noted to buy the train that is legal for the company to run, and it
will auto-take loans to raise funds

(This seemed to work in my test)

There's another issue to make the text clearer
https://github.com/tobymao/18xx/issues/4100

-_Ben
