### ISSUE TITLE
[1861]Initial auction, player gets to pass twice

### ISSUE THREAD

**Issue by whytestone** [tobymao/18xx#4095]
Player saundersag passes to bid on the first private company, one of all players places a bid, now it's saundersags turn again and the only player with a bid should have won that auction but saundersag still get the question to place a bid or pass.

**What's your Game ID?**
https://18xx.games/game/29149

**How to Reproduce the Bug?**
Saundersag is priority deal, multiplayer 4player. All except one should pass, now first player get question again even though passed.

![Screenshot_20210221-192107_Chrome](https://user-images.githubusercontent.com/1461175/108634554-583a9b00-747a-11eb-83a2-514f5456dff3.jpg)

**Comment by Maxwell-Frank** [comment]
As ruled in an earlier issue (#2946), passing on starting an auction does not preclude a player from bidding on that private once the auction has been started. This is not a bug.

**Comment by jenf** [comment]
Not a bug, note 'declined' is in the log specifically for this ambiguity
