### ISSUE TITLE
[18CZ] able to buy invalid trains during EMR

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#4099]
[testcase](https://gist.github.com/benjaminxscott/4424d9fb82eaab59297d84f6f6cba07a)

@Zwergenpunk I think we need to hide trains that aren't runnable by the corp, and hide trains that are owned by other corps
(the `5g` and the `3c` here)

![Screenshot 2021-02-21 at 12 00 19 PM](https://user-images.githubusercontent.com/1711810/108636793-784b6980-743c-11eb-946c-8cf32f38cc4f.png)

```
The train may be bought only from the bank or the Train Pool, but not from another company.
The Director may not buy a further train for the company 
```

My read is that `The Director may not buy a further train for the company ` means that the corp can't buy a non-runnable train and then buy a runnable train

Since the corp can only buy one train during EMR, if it buys a non-runnable train during EMR then it will won't have a runnable train at the end of its turn

**Comment by Zwergenpunk** [comment]
Sorry the gist is broken, (and no idea at which state is is ok)
The problem with the 3C train is that the company has probably more than 0$, so it is possible to buy the train without EMR from another corporation. If it has 0 it shouldn't be there anyway (I guess)

I think the 4+4 train should no be visible. yes (except the company has 350$, but not 400$) 
I don't think the game allows to buy the 4+4, but it shows.

**Comment by Zwergenpunk** [comment]
I think I found the bug problem
The player may only the variant if other variants of he has enoght money

**Comment by Zwergenpunk** [comment]
It was also possible to buy an other variant with EMR before PR

**Comment by benjaminxscott** [comment]
> I don't think the game allows to buy the 4+4, but it shows.
In that testcase, the `4+4` is the only valid train to buy via EMR, since NWB is medium (it worked when I tried it)

**Comment by benjaminxscott** [comment]
> The problem with the 3C train is that the company has probably more than 0$, so it is possible to buy the train without EMR from another corporation. 

You're right, presumably this step would happen before it's forced into EMR

> If it has 0 it shouldn't be shown

Correct, I believe
