### ISSUE TITLE
Laying Track - Microsoft Edge

### ISSUE THREAD

**Issue by zchillman** [tobymao/18xx#41]
Currently experiencing difficulty laying track while using the site through Microsoft Edge on laptop. When selecting a legal hex in which to place track, none of the track tiles populate. However, when using Chrome on mobile, track options populate with no issues.

**Comment by tobymao** [comment]
i only test on safari, chrome, and firefox i'll label this one as lower priority

**Comment by jenf** [comment]
Looks like it's causing an error in
TileSelector:get_coordinates

**Comment by tobymao** [comment]
oh wow that should be an easy fix

**Comment by jenf** [comment]
yep, PR now available :)
