### ISSUE TITLE
Tabbing away from route selection clears it

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#410]
I was in the Game tab, selecting routes for my trains. I selected all routes and saw the total. Then I clicked on the Spreadsheet tab to see how that compared to other companies' recent runs. When I returned to the Game tab, my routes were entirely cleared out and I had to start over. Reproduced.

**Comment by tobymao** [comment]
i recently added code that wipes the state when the view is destroyed

a more robust solution would be whenever an action is processed to clear all state

**Comment by scottredracecar** [comment]
I verified this is fixed now.
