### ISSUE TITLE
18CZ EMR text needs UI improvement

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4100]
https://18xx.games/game/27956?action=535

NWB is required to buy a train. The text below about selling shares and declaring bankruptcy is incorrect, and should be suppressed. Buying the train results in the appropriate loan being taken.

NWB has K170.
ChrisShaffer must contribute K180 for NWB to afford a train from the Depot.
ChrisShaffer has K99 in cash.
ChrisShaffer has K0 in sellable shares.
ChrisShaffer must sell shares to raise at least K81.
ChrisShaffer does not have enough liquidity to contribute towards NWB buying a train from the Depot. NWB must buy a train from another corporation, or ChrisShaffer must declare bankruptcy.

**Comment by Zwergenpunk** [comment]
Thats definitly true. I tried to change it a little bit, but broke other games. So i just let it be.

Not quite sure what to change. Maybe it would be best to add the information right at the "price" of the corporation.

![image](https://user-images.githubusercontent.com/7661170/108638062-ac02af80-748d-11eb-9e1a-bba19d09b30b.png)

And adjust the text below that taking a debt is required
