### ISSUE TITLE
18CZ wrong text on abilities

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4102]
https://18xx.games/game/27956?action=540

May either ignore the cost to build a river or hill tile or lay a special purple-edged tile on yellow or green cities

The text above for a medium company is incorrect. Small companies may lay a special purple-edged tile on green cities or towns, medium on green or brown, and large on green, brown, or grey. There are no purple-edged yellow tiles. The text should also mention towns.

**Comment by ChrisTheCat** [comment]
Note that the interface actually allows the correct tile placements, only the descriptive text is incorrect.

**Comment by benjaminxscott** [comment]
the town

**Comment by ChrisTheCat** [comment]
Is the color also fixed? The text says "yellow / green" which should be "green / brown"

**Comment by benjaminxscott** [comment]
The current "lays on" means that the tile is a legal lay on the current tile of that color
(e.g. "small can lay on yellow")

>  Small companies may lay a special purple-edged tile on green cities or towns

I don't think this is the case, it can't lay a tile **_on_** green cities/towns

**Comment by benjaminxscott** [comment]
It can be reworded to make more clear that a small lays a green tile (etc)

Especially since the physical version has green/brown/gray tiles on the private cards

**Comment by ChrisTheCat** [comment]
It would be much clearer if the text described the type of tile that can be
*placed* rather than the type of tile that would be *replaced on the map*
