### ISSUE TITLE
[1849: Kingdom of Two Sicilies] Variable revenue information (white/gray/black) on Info page

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#4106]
The colored variable revenue status (White/Gray/Black) needs to be included on the info page (Just as in 1849)

Thanks!

**Comment by perwestling** [comment]
From 1849:
![image](https://user-images.githubusercontent.com/2631151/108688717-852d9300-74f8-11eb-9eb9-c87d674c2230.png)

From 1849 KoTS:
![image](https://user-images.githubusercontent.com/2631151/108688773-95de0900-74f8-11eb-8e4e-f6a85a6a0e45.png)

**Comment by jason-johnson** [comment]
Assign to me please unless someone else is already on it

**Comment by perwestling** [comment]
@jason-johnson Can this issue be closed?

**Comment by jason-johnson** [comment]
Well, I'm not the reporter of the issue.  I believe I've fixed it though.

**Comment by dfannius** [comment]
The fixer of the issue should feel free to close it (at least in this project).
