### ISSUE TITLE
[18CZ] refactor private view

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#4107]
Migrating the discussion from https://github.com/tobymao/18xx/issues/3867#issuecomment-782734148 to its own issue

Closed by https://github.com/tobymao/18xx/pull/4104

**Comment by crericha** [comment]
When I play the game live, I look at all the values down the column to determine opportunity. I ask myself if I don't buy one on this column now and inst ad buy from another, what will be the cost for me when it comes back around to my turn. Like can I afford to take another large and still have cash for a small a few spots down and enough to start a corporation. Please make sure there is a way to do this still.

**Comment by crericha** [comment]
Perhaps use three columns. The UI supports this if `auction.tiered_auction? == true`. See 1828 for an example.

**Comment by benjaminxscott** [comment]
Agree w/ listing all, see https://github.com/tobymao/18xx/pull/4104 for 3 columns

Haven't used `auction.tiered_auction?` but that may be cleaner than reimplementing

We can also tweak later

**Comment by Zwergenpunk** [comment]
I don't know if I lke the tiered_auction. We of course need to group by revenue and not by value.
But on mobile this does not gain us anything.

I think it would be best to see the available picks at top.

My suggestion would be to show the available in top, and then unavailable as list below.

**Comment by Zwergenpunk** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/7661170/108681926-fae13100-74ef-11eb-8dea-6cd006547ccb.png)

**Comment by Maxwell-Frank** [comment]
All the privates need to be available for purchase at all times. There is _no_ requirement to purchase the cheapest private of a group.

**Comment by benjaminxscott** [comment]
fixed by https://github.com/tobymao/18xx/pull/4115
