### ISSUE TITLE
Easier to parse tile display

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#411]
**3 x 2** is a little ambiguous - does it mean *3 x no.2 tiles* or *2 x no.3 tiles*? Maybe reformat it as **3 x no. 2** .

Also, could there be a graphical representation of how many of each tile remain - for example, if there are three tiles remaining, perhaps you could see the edges of two tiles underneath the top one?

**Comment by dfannius** [comment]
I personally use `#` to refer to tile types (e.g., `3 × #2`), but I'm not sure if I picked it up from somewhere and it's semi-standard or if I just made it up myself.

**Comment by zurfarosa** [comment]
I agree 3 x #2 would be an elegant solution

**Comment by dfannius** [comment]
If we make that the default way of representing tile IDs, we should do so in the log as well.
