### ISSUE TITLE
Trains don't sort correctly in the Spreadsheet tab

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#4112]
Clicking on the header for the Trains column in the Spreadsheet tab (multiple platforms and browsers) doesn't sort as expected. Here, for example, is what I see for a [recent game of 18Chesapeake](https://18xx.games/game/29122):

<img width="118" alt="Screen Shot 2021-02-22 at 12 48 37 PM" src="https://user-images.githubusercontent.com/757327/108748318-718c2780-750c-11eb-80fd-ba1e964c796b.png">

**Comment by yzemaze** [comment]
Right now it just sorts by number of trains. Would you expect alphanumerical order (after that)?

**Comment by orome** [comment]
Anything consistent would work. E.g., by train it takes to wipe out all owned trains (so `3, 3, 3` would be less than `4`, for example), then number of trains; but whatever makes the most sense (and isn't a pain to do).

**Comment by dfannius** [comment]
It does seem pretty weird to sort by a column and then not have all of the entries in that column be grouped together.

The ordering that seems most natural to me (in order) is to compare:

1. Number of trains - higher is better
2. Index number of best train (when sorted by index number) - lower is better
3. Index number of second-best train, etc.

By "index number" I mean the row of the "upcoming trains" table it is in.
