### ISSUE TITLE
1828.games unable to enter game

### ISSUE THREAD

**Issue by fabianpk** [tobymao/18xx#4119]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

I'm not able to enter the game, https://18xx.games/game/23056
The last thing I did was to test to click "Merge" on one of my companies in a stock round, and now I can't enter the game anymore. I was trying to Merge PRR with some other company,, but I wasn't sure I'd be able to. 

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Just try to enter the game, it doesn't work on my computer or my phone. 

![bild](https://user-images.githubusercontent.com/38062242/108776538-d5413f80-7562-11eb-8d3a-1948889fd8cb.png)

**Which Browser / Platform?**
Firefox on windows 10. Safari (iOS 14.4) and Firefox in iphone & ipad. 
/check-the-version-number-of-safari-446563)

**Comment by roseundy** [comment]
Broken by Harzbahn 1873 code changes.
