### ISSUE TITLE
JUST WANT TO ACKNOWLEDGE AND THANK YOU ALL FOR WHAT YOU ALL PROVIDE FOR US!!

### ISSUE THREAD

**Issue by databoy01** [tobymao/18xx#4122]
NO NEW IDEA-  Just wanted to acknowledge all you all do and thank you. Many users are very appreciative of all the work you all have provided for our enjoyment.  I know I appreciate it and I am sure others do likewise.  So sincerely I THANK YOU!!  

**What's your idea?**

Let us know your proposed changes.

**Are there related ideas?**

Other contributors may be working on something similar, [check out the list of open feature requests](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to see if there's opportunity to collaborate.

**Did you join the Slack?**

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ) and meet your fellow contributors!

**Comment by Eludyan** [comment]
I second this!  I really appreciate this group and all the work the devs do! :)

**Comment by tobymao** [comment]
thanks, glad you enjoy the site!
