### ISSUE TITLE
[18CZ] Force Small-Medium-Large View Order in Private Draft

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4132]
https://gist.github.com/Maxwell-Frank/3c6e4b5acb123f6b36dd0d2d3b55e3d1

Even though the company sizes are now grouped together, it appears that the rows themselves are still being sorted by the price of the cheapest private in the row. I would suggest that the rows remain in Small-Medium-Large order, regardless of the costs of the privates remaining. 

In the example above, the order changed to Medium-Small-Large when a certain combination of privates were purchased.

**Comment by Zwergenpunk** [comment]
Yeah i think when the cheapest one is a medium it changes. 
Thanks for the report
