### ISSUE TITLE
[18CZ] Acquiring a smaller company loses the K40 token on the charter

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#4134]
__VIII.9 Acquisition of a smaller company__
* The larger company receives from the smaller company: all treasury, all local railways and all non-
placed station markers. These markers may be used as additional station markers for the price of
100 K each. _The stations on the map remain there and now belong to the larger company._
(Exception: if both companies had station markers on the same hex, one of them must be
removed from the map and returned to the charter. It may later be placed for 100 K in accordance
for the rules for placing stations.) Place the smaller company charter below that of the larger one
to indicate that the two companies are now one.
(emphasis mine)

Technically, the tokens of the acquired company are not replaced -- that is just done as a convenience -- and they most certainly are not replaced with the K40 token from the acquiring company's charter, yet that appears to be what is happening. See UG and KK, both of which did not place their K40 token, yet no longer had it after acquiring smaller companies. I do not know if it also happens with Medium companies acquiring Small companies because I'm too lazy to check at the moment.

https://gist.github.com/OedipussyRex/d335a89d00cfde249ec50e4db54eb466

**Comment by Zwergenpunk** [comment]
This is confusing, but correct.
There it was discussed:
https://github.com/tobymao/18xx/issues/3957

**Comment by OedipussyRex** [comment]
You'll notice my response to the question on BGG linked in that other bug report. Never saw the follow-up. Still disagree, but who am I to argue with game designer?

Closing

**Comment by Zwergenpunk** [comment]
yeah it it super random. I don't like it neither....
