### ISSUE TITLE
[1860] FYN neither pays nor withholds revenue

### ISSUE THREAD

**Issue by ikelly** [tobymao/18xx#4136]
**What's your Game ID?**

https://18xx.games/game/26162?action=644

**How to Reproduce the Bug?**

From the linked action, select a route for FYN and click Submit. This results in:
```
[11:08]FYN runs a 9+5 train for £360: I11-H10-H8-I7-I7-J6-J4-I5-H4-H4-G3-G5-F4-F2-E5-D6-C5-B4
[11:08]FYN skips buy trains
```

No option is given to pay out or withhold. Observe that no cash is paid out or withheld, and the company's share value does not change.

Some circumstances that could be involved:
* FYN was insolvent and this is its first turn of solvency after buying a train again.
* FYN is also at the very bottom of the stock chart (£7).
* The company (S&C) that ran prior to FYN just went bankrupt.
* The Southern Railway has already formed in the previous OR.
* Nationalization is about to begin at the end of the round but has not yet begun.

**Which Browser / Platform?**
Chrome 88.0.4324.182
Desktop

**Comment by roseundy** [comment]
FYN dividend step was skipped. Still debugging why, but definitely a bug.

**Comment by roseundy** [comment]
Bug was caused by S&C going bankrupt immediate before the FYN's run. The operating round after_process method doesn't deal well with being called after a corporation is removed from the @entities array.

**Comment by roseundy** [comment]
S&C went bankrupt and is affecting FYN running next. For some reason the dividend step for FYN isn't even being evaluated.
