### ISSUE TITLE
[1830] You cannot progress in a game when a player is unable to sell shares over cert limit

### ISSUE THREAD

**Issue by doroudis** [tobymao/18xx#4138]
If a player is holding a number of shares exceeding the certificate limit specifically in companies that
(i)  each have 5 shares in the bankpool and
(ii) are not in the yellow/orange/brown regions of the stock market,
they will be unable to sell shares in their next SR and therefore.  It's not clear what the actual rule should be in 1830, but in any case, as far as I could tell, it appears that you can't go any further in the game in 18xx.games.

I think this situation is unlikely to come up in an actual game (so it is likely low priority), but I was successfully able to cause such a situation to occur in a hotseat game.

[I've pasted the json of a hotseat game a gist here.](https://gist.github.com/doroudis/56b47bd38efb858fd1dca9187c7466b6)

This issue probably also applies to all games with a cert limit, a yellow region in the stock market, and a limit of 5 shares in the bankpool (e.g., 18 Chesapeake, 1882, 1889).

**Comment by ventusignis** [comment]
I was planning on forcing this scenario in a hotseat game at some point. In the rules clarification for 1856 I saw if this scenario occurs the player is allowed to remain over limit until they are able to sell further down towards compliance

**Comment by dfannius** [comment]
That's good to know. Our consensus on Slack was that that's what the rule should be: if you can't reduce the amount by which you are violating the cert limit, you're okay.

**Comment by doroudis** [comment]
Thanks, ventusignis, didn't know that.
