### ISSUE TITLE
1828 random company going up on the stock market (undo did not undo correctly)

### ISSUE THREAD

**Issue by ElayneTrakand** [tobymao/18xx#4140]
https://18xx.games/game/29537

[21:16]Elayne buys a 10% share of MP from the market for $58

[21:41]MP pays out $80 = $8 per share ($56 to Elayne)
[21:41]MP's share price changes from $62 to $65
[21:41]MP skips arrange trains between shells

What steps cause the unexpected behavior?

First, I bought up to 70% in the SR, company did not sell out.
Second, I checked whether it was possible to trade up to 70% when merging, and then undid the action, as I did not actually want to merge.
I think that the bug occurred at this point, since later in the OR the arrange trains between shells step was visibly skipped, even though it should not have occurred.
Other than that, there is no explanation as to why the company would rise on the stock market without any visible statement to that effect.

The game was played on Windows 10 - Chrome.

**Comment by dfannius** [comment]
It wasn't immediately clear to me what the unexpected behavior was; it's that MP moved up from $58 to $62 at the start of OR4.1 (https://18xx.games/game/29537?action=344). This happened after the undo sequence so I'm not sure it's related.

**Comment by ElayneTrakand** [comment]
Hi dfannius,

I don't know either, but considering that the game prompts both the MC and MP to skip shuffle trains between shells step (which doesn't occur normally with non-merged companies) certainly suggests that it is connected.

**Comment by crericha** [comment]
The behavior is correct.

The relevant rule is in 12.2

> If the stock price marker was in the gray area of the Stock Market at the start of its movements then the stock price marker is moved up one more row.

**Comment by ElayneTrakand** [comment]
That is quoting a rule without more context though. That rule only applies if the company is sold out, which it wasn't.

**Comment by crericha** [comment]
Depends on what you think additionally means. To me, its in addition to moving up because sold it, it also moves up for these reasons. I'll check with JC.

**Comment by ElayneTrakand** [comment]
I've played this with JC a long time ago. This is exactly how he explained this rule to me.
Otherwise you would rule that ANY company in the gray area moves up one, regardless of how many of its shares are sold, and that is just bonkers.

**Comment by dfannius** [comment]
I think that the rules clearly support Elayne's interpretation (the fact that the subitems say "the stock price marker" rather than "a stock price marker" is icing on the cake), but luckily we have access to the ultimate authority on the matter.

**Comment by crericha** [comment]
I confirmed with JC. Fix incoming. Since this will change the order corporations operate, many games will be pinned.
