### ISSUE TITLE
1849 SMS unable to place token in Marsala

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4143]
https://18xx.games/game/29606?action=233

In a 3 player game, the CTL was removed from the game during setup. Later, the AFG was trying to use the SMS power to teleport a tile/token to a coastal city hex ("all cities except Caltanisetta and Ragusa"). AFG was not offered the opportunity to place the token in Marsala, presumably because it was still "reserved" for CTL.

Note that the player didn't intend to place the token there, it's obviously not the best play, we just noticed it wasn't highlighted.

**Comment by crericha** [comment]
There isn't a reservation for CTL. You would see it in the city.

Teleport powers must list the possible destination hexes. My guess is the Marsala hex isn't in the list. Should be a one line fix.

**Comment by crericha** [comment]
https://github.com/tobymao/18xx/blob/fab8291ebf7356de7afa39325730cbbba5081e79/lib/engine/game/g_1849/game.rb#L598
