### ISSUE TITLE
Add 'admin mode' that allows arbitrary map/cash changes

### ISSUE THREAD

**Issue by bazik123** [tobymao/18xx#4145]
When using 18xx.games as a moderator for an in-person game it would be great to be able to fix some errors that arent cought until few rounds later. 'we placed that tile only on the real board', 'I said I wanted to purchase the private for $100 but you fat fingered $10 into 18xx.games'...

my idea:
- add an 'admin mode' button next to 'master mode'
- when active, add options to add/subtract money from any entity
- when active, allow any tile to be placed on any space on the map
- prefrerrably use bold red font in the gamelog window

**Comment by benjaminxscott** [comment]
Discussed in dev slack, we believe this type of feature isn't in scope for the project
