### ISSUE TITLE
[1817NA] Wrong number of shorts

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#4148]
https://18xx.games/game/25381?action=1071

The spreadsheet says NYSW has been shorted 5 times, but players only hold 4 shorts.

**Comment by jenf** [comment]
the market had one at https://18xx.games/game/25381?action=976
This is the point where it goes wrong
18xx.games/game/25381?action=1003
It's not collapsing the short properly when a real share is sold.
