### ISSUE TITLE
Underpaying routes (D Phase) in 1889

### ISSUE THREAD

**Issue by Jon-Ger** [tobymao/18xx#415]
The last few rounds (game ID 902 for 1889) I noticed that the game was not totaling route values appropriate for the route selected. I think it is dropping the first or last city/off board location value, but can't be sure.

Game Log:
KO's share price changes from ¥200 to ¥225
Jon_G receives ¥330 = ¥55 x 6 shares
pgh_gamer receives ¥220 = ¥55 x 4 shares
KO pays out ¥550 = ¥55 x 10 shares
KO runs a 6 train for ¥290 (I2, I4, H7, G4, E2, F1)
KO runs a 5 train for ¥260 (L7, K4, I4, I2, J1)
KO spends ¥80 and lays tile 8 with rotation 3 on E4
Jon_G operates KO
-- Operating Round 10.1 --
![Miss calculating route value in D phase](https://user-images.githubusercontent.com/65629962/82383204-2e7faf80-99e2-11ea-9662-d7105a65c8d5.jpg)

**Comment by tobymao** [comment]
it is correct. only the D train gets the gray bonus on offboards.
