### ISSUE TITLE
1856: Handle destination-reaching of unparred corporations

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#4150]
Currently the implementation only checks for destination of *parred* corporations on the track lay step.

The rules don't explicitly state what happens to unparred corporations when their home station is connected to their destination (they have not laid their home token. The TGB hasn't selected which side of the OO to use either).

The rules state:
![image](https://user-images.githubusercontent.com/2993555/109043166-09ba1600-769f-11eb-8391-e657007fbabd.png)

I note that the rules states that this check is done when a tile is laid, but does not state when the corporation starts.

Since the THB has to pick which hole it starts in if the green OO is already laid when it starts, the THB will have to wait until `HomeToken` to determine if it has destinated or not. For simplicity and consistency I plan on implementing this so `HomeToken` does a destination check for all corporations

**Comment by crericha** [comment]
Unparred corporations don't have a token on the board, so they don't have have a path to reach their destination, no?

**Comment by jdgalt** [comment]
The wording of the quoted rule leaves something to be desired.  But its first sentence gives the answer: the company "starts" or is "opened" **when a player purchases the president's certificate.**
