### ISSUE TITLE
Front page: call out games with updates

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#4153]
For those of us in a bunch of async games, it would be nice if the games in "Your Games" that had changed since the last time you looked at them (because other people have moved) were called out in some way, with a little icon or a slightly different color or something. I don't know what information is currently stored, but if we knew for every one of your games a) the last action ID you had observed and b) the current action ID of the game, we could just display the game card differently if b > a.

**Comment by tobymao** [comment]
this is not feasible as storing last action observed is expensive, closing as i don't forsee this happening
