### ISSUE TITLE
Programmed actions - suggest separating Convert/Merge from Friendly Sale

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4164]
It would be nice if these were separated. Current layout:

*****

Program Pass in Mergers
This will pass converting/merging or offering your corporations automatically. It will not pass otherwise still allowing you to buy shares, bid etc. It would also be nice if they were ordered correctly for the friendly sale round (as shown in my proposed version below).

Pass on Corporations:

    ME
    NYOW
    NYSW
    WC

Pass in Rounds:

    Merger and Conversion Round
    Acquisition Round

*****

Proposed layout:

*****

Pass on convert or merge. This will still allow you to buy/sell shares if other players convert or merge their corporations.

    ME
    NYOW
    NYSW
    WC

Pass on friendly sale. This will still allow you to bid if other players offer a corporation for friendly sale.

    WC
    NYSW
    NYOW
    ME

**Comment by ChrisTheCat** [comment]
One of the reasons for this request is that I might want to autopass on convert/merge for ME, NYOW, NYSW and not ME, while then autopassing on friendly sale for all four (or a different subset).

**Comment by jenf** [comment]
That could be done, now the problematic question of how to upgrade everyone's settings :)

I won't change the order they show up in (because you can activate it before you've had your turn so it's best not assuming they'll be in a specific order)

I'll look at this when the other programmed actions are completed.

**Comment by jenf** [comment]
It'd also be good to have a flag allowing disabling if another corp actually does something as the train rush might change.
