### ISSUE TITLE
[1817] Simultaneous bankruptcy

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#4173]
This is an odd situation, that I manufactured to see how the implementation works. I think it's unlikely it ever happens in a real games.

The rules don't specify an order for cash crisis to be resolved, so I'd say they're happening simultaneously. It also states that if only one player is left in the game, they win. But naturally this implementation had to set an order for the cash crisis to be resolved. 

I was curious to find out what happened if all the remaining players in the game went bankrupt at the same time. Would the game end before resolving the last cash crisis giving a "random" player the victory? Or would it go through all the cash crisis before checking for the end game condition and show all players as bankrupt?

The answer was a bit underwhelming. It turns out the game just breaks.

https://gist.github.com/daniel-sousa-me/a3d5d0555e903d9b37e1546f22aefed9

**Comment by jenf** [comment]
actually looks like a ui bug

**Comment by daniel-sousa-me** [comment]
Yeah, it threw something related to `company?` lol

Apparently there's a ruling from one of the designers that kinda settles this: https://groups.google.com/g/dtg-proto/c/TQ_tcl0_SD8/m/03cammFQJZUJ
My interpretation is that the player furthest from the president wins the game.
