### ISSUE TITLE
Explicit logging of scripted actions

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#4177]
**What's your idea?**

Currently scripted actions are indistinguishable from regular actions, unless you look closely at the reaction times, clone or json.

I would suggest to either:
1) announce it to all players what the scripted action is, or
2) mark scripted actions in the log explicitly with "(scripted)" prefix or extra line in the log

IMO this would make it more transparent to everyone, exactly as it is now with the announcements "please pass for me" or "please buy XX for me until it floats"
It would also make it easier for other users to discover the feature.

**Are there related ideas?**

has been discussed just now in 18xx.games channel on Slack

**Did you join the Slack?**

Yes, Jeroen

**Comment by tobymao** [comment]
popular vote in slack indicates this is not wanted, we should close this if the trend continues as won't fix

**Comment by jenf** [comment]
As voted upon by slack, won't fix.
