### ISSUE TITLE
Login/Forgot Password/Create Account no longer work

### ISSUE THREAD

**Issue by jamesjsnell** [tobymao/18xx#4182]
Hello - I attempted to change my Profile Name after logging in (went to Profile, Change Profile Name, ...) and hit Save Changes.   Nothing seemed to change and now the Login/Forgot Password buttons no longer work (pressing the button has no response).  I have deleted all browsing data and cookies, rebooted, and tried different browsers.  I am able to log in from my phone.

Any ideas on what's happening?

Thanks (I'm a monthly Patreon subscriber)

Jim

**Comment by yzemaze** [comment]
I can’t confirm these problems. If you can login fine with your phone, it’s rather likely a local problem. Try re-starting your browser with disabled add-ons, in rescue mode or with a new profile etc.
"tried different browsers" doesn’t say a lot without explicitely stating which ones and listing their versions.

**Comment by jamesjsnell** [comment]
Thank you for the response!  I know the description was vague but was
hoping you’d run into something similar previously.  I’ll give this other
steps a shot. Thank you again.  18xx.games is an awesome platform.

**Comment by tobymao** [comment]
what browser and device are you on?

**Comment by jamesjsnell** [comment]
Windows 10 and the both latest version of Chrome and Edge don't work.  It seems like it's all buttons that no longer work, not just login/password.  It happened immediately after trying to change my Profile name.

Shout if you hear of anything similar from other 18xx'ers.  Thanks!

**Comment by tobymao** [comment]
even when you clear your cache? i tried changing my name and have no issues

**Comment by jamesjsnell** [comment]
Unfortunately clearing cache, rebooting, safe mode, different browsers,
etc. all fail to fix it.  The fact that it no longer works in any browser
on this computer makes me think it's something with Windows not with the
browser.

Again, I know this is a local issue and I really don't expect help
troubleshooting my PC.  Was looking for info if you had heard something
similar from other users but it doesn't sound like you have.

Thank you for your responses!

Jim

**Comment by tobymao** [comment]
can you show me a screen shot of what happens? can you open up your console and show me the error? are you a dev?

**Comment by jamesjsnell** [comment]
All buttons are non functional so there really isn't anything to see.  I
load 18xx.games (in either Chrome or Edge), links work (I can navigate to
the Login/About/Signup pages), but buttons are unresponsive on all pages.
Not sure if Developer mode in Chrome is helpful.

[image: image.png]
