### ISSUE TITLE
18WO Question Game 30061 - Is there a bug with Nieuw Zeeland?  Seems like I never got a chance to place 2nd token, so I cannot lay track

### ISSUE THREAD

**Issue by Foxrik** [tobymao/18xx#4189]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by ventusignis** [comment]
Can you please provide some information on the game you were playing so I can look into this?

What's your Game ID?

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like https://18xx.games/game/31337

    (optional) Provide a link to the specific action that triggered the bug using the Game tab and History navigation arrows. Copy the resulting link from your browser which will look something like https://18xx.games/game/31337?action=42

If your game is "Hotseat", provide a link to your raw game data by using the Tools tab and Copy Game Data.

Paste that data into a github gist and share the resulting link which will look something like https://gist.github.com/[your_name]/[some_letters].

**Comment by jenf** [comment]
No game info provided, comment if you can still see the issue

**Comment by Foxrik** [comment]
Please forgive me if I can’t embrace GitHub.  Unlike possibly the majority of 18xx.games nerds I am not an IT person.  Just a dumb end user.

The issue was in Game 30061 on 18xx.games.   We finished the game despite the issue, so you can find it in my closed pile.  Foxrik (my username), EdFactor, ScottRedRacer in a 3-player 18WO.

In the first iteration of 18WO on the site, which I last played a month ago, it had the same kludge around token purchases that the whole 1817 family has had.  Namely, when you started a 5 or 10 share company from scratch you had to take a future stock-round action to pay for tokens.  (In the real game this is a bonus action at the time the company starts.)  This has since been changed.

In 18WO there is a special case for starting a company in Nieuw Zeeland.  According to the rules, at the end of the stock round, the owner can place a token in any empty city site.  Since NZ itself is not connected to the map, this is necessary if they ever hope to have a run.  In the original 18xx.games implementation, the game correctly offered this option at the right moment.  In game 30061, this did not happen, and going back through the log, I could not see any place where it was offered.  So the RR can never run!

We embraced the issue and finished the game.  I merged the company with another so it was sort of OK (although the game overall was still a bloodbath).  I note that the second special power of the NZ – free loan payment for 1 loan – seemed to work fine, even after it merged up.

Maybe I’m just an idiot and didn’t work the buttons right.  If so, please let me know how – I’d like to play this game again sometime.

Thanks,

Rick





Richard Dutton

Chief Quality Officer

O: 972-776-3132<tel:972-776-3132> | C: 708-714-4024<tel:708-714-4024>

richard.dutton@usap.com<mailto:richard.dutton@usap.com>

www.USAP.com<http://www.USAP.com>

[cid:33457fa725e7c020be43c00c7c0a4b72904efeb4] <http://www.USAP.com>

[cid:69fdb15eebef9c189c3c6c730fa987f676c7f466] <https://www.linkedin.com/company/us-anesthesia-partners>

[cid:4102b6145dc8c5d363932ab5fc6e25f234d6b20c] <https://www.facebook.com/usanesthesiapartners/>

[cid:ae85a7520c93b456077998651edd34fd0522ffc4] <https://twitter.com/usap_updates>

**Comment by jenf** [comment]
Thanks for the game info, we'll investigate

**Comment by ventusignis** [comment]
I am able to reproduce the bug; it happens when both:
 * There is no choice of corporation starting size (phase 4, 6, 7, 8)
 * There is no contest on the bid (such as bidding 400)
