### ISSUE TITLE
18Chesapeake issues

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#419]
1. bo thinks it can token itself
2. can run from offboard to offboard

**Comment by scottredracecar** [comment]
Plain yellow track #7/#8/#9 are unlimited per the rules.

**Comment by tobymao** [comment]
do you think 20 will be enough?

**Comment by scottredracecar** [comment]
Yes

**Comment by yraelrocks** [comment]
Private 2 - CPR shouldn’t allow the yellow tiles to be disconnected from each other.

Game Id 1149

![Uploading E41BC54A-91F5-4F4C-8D55-330CC65B8AD2.png…]()
