### ISSUE TITLE
[1822] Minor 14 Upgrading London Breaks Game

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4195]
https://18xx.games/game/30160

Minor 14 tried to upgrade London and now the game will not load.

**Comment by ventusignis** [comment]
https://gist.github.com/ventusignis/49ad3c199a4e81fdd5b6c7e060c801d6.js

**Comment by ventusignis** [comment]
https://gist.github.com/ventusignis/49ad3c199a4e81fdd5b6c7e060c801d6
