### ISSUE TITLE
1822 better display of decks

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4197]
In this game, you can see the decks of minors, concessions, and private companies on the entities tab. However, it's a very long vertical list. It would be nice if there was a more concise display of the decks.

One possible display:

Minors: 24, 18, 19, 6, 12, 14, 13, 23, 4, 10, 15, 20, 2, 3, 17, 21, 22, 8, 5, 16, 11, 7, 9
Concessions: LNWR, GWR, LBSCR, CR, SWR, LYR, NBR, NER, MR, SECR
Privates: BEC, L&SR, HR, Tax Haven, S&BR, B&ER, M&GNR, K&TR, LC&DR, etc...

Or this:

```
Minors    Concessions    Privates
24          LNWR           BEC
18          GWR          L&SR
19          LBSCR          HR
6            CR          Tax Haven
12           SWR          S&BR
14           LYR          B&ER
13          NBR          M&GNR
23          NER          K&TR
4           MR          LC&DR
etc   etc    etc
```

**Comment by magnusfalt** [comment]
Under Info -> Timeline, you will now see something like you first suggestion.

**Comment by joeyd4329** [comment]
Is it possible to have this list form present on the map as well? The upper right corner of the map is pretty spacious and could allow for that. Toggling between the map and the list constantly can be a little dizzy.
