### ISSUE TITLE
1822 More descriptive titles for private companies

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4198]
In the physical game, there are graphics on the private companies that make it easy to see at a glance what powers they offer. As that is missing from the online game, perhaps the names of the private companies could be moved into their descriptions, and the titles could be a brief summary of their power. Also, in physical play people often refer to the private companies by number. I know that P3 and P4 are the permanent 2 trains, and that P6 and P7 are the mail contracts.

Thus, instead of:

BEC
MAJOR, Phase 5. 5-Train. This is a normal 5-train that is subject to all of the normal rules. Note that a company can acquire this private...

Display this:

P1 - 5 Train
Major, Phase 5. Butterley Engineering Company (BEC). This This is a normal 5-train that is subject to all of the normal rules. Note that a company can acquire this private...

And instead of:

S&HR
MAJOR, Phase 2. Permanent 2-Train. 2P-train is a permanent 2-train. It can’t be sold to another company. It does not...

Display this:

P3 - Permanent 2 Train
MAJOR. Phase 2. Shrewsbury and Hereford Railway (S&HR). 2P-train is a permanent 2-train. It can’t be sold to another company. It does not...

**Comment by yraelrocks** [comment]
Also clarification on what’s a private company vs minor vs concession. Currently all labelled private company which is potentially misleading.

**Comment by magnusfalt** [comment]
We still need to have the caption relatively short. Many of the privates have a use count ie P10, P12. P16. tax haven you see what share it has bought. P15 you see how much money it have accumulated. P9 you see if you have used the double your cash in the stock round.

But including the Px im all for.

**Comment by magnusfalt** [comment]
One solution is to change the caption and description of the company when its acquired. I have this on my todo, since you dont need to see MAJOR/MINOR, phase x after its acquired.

**Comment by DarthIA** [comment]
It would be nice if MAJOR/MINOR and phase could be added as a label in the card, somehow. Not sure if this is feasible or too hard, but just my 2 cents.
