### ISSUE TITLE
1822 - token of minor 14 disappears

### ISSUE THREAD

**Issue by TomdeGre** [tobymao/18xx#4201]
Discovered in a hotseat game.

14 was floated on the lbscr spot. 14 Token was gone the next OR. Potentially caused by the lbscr floating, although the problem surfaced before that token appeared.

**Comment by TomdeGre** [comment]
Appears to also have been caused by london being upgraded on further investigation

**Comment by magnusfalt** [comment]
This was the same error as #4195

This is fixed as soon as #4199 goes live.
