### ISSUE TITLE
[1822] Minor Company 20 Illegal Tile Lay

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#4204]
https://18xx.games/game/30242

Minor Company 20 was able to lay a straight dit town into Newport from Carduff. I layed the track no paying attention. I don't think this is a legal tile lay.

https://gist.github.com/joeyd4329/e277d8f646fd4d6938f1675e191df589

**Comment by magnusfalt** [comment]
The current tilelay of hex G34 from Pontypool by minor 20 is legal. Pontypool have a path SE into that hex. What was it that was illegal?

I know it is a little bit tricky with the Merthyr Tydfil & Pontypool paths.

**Comment by magnusfalt** [comment]
The whole Merthyr Tydfil & Pontypool junction is hard to figure out. But yes 20 shouldnt be able to lay a straight from cardiff, and they shouldnt be able to lay on hex E36 if not connected through Newport.
