### ISSUE TITLE
1822 remove "concession" from Info -> Timeline

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4207]
https://18xx.games/game/30130?action=53#info

Timeline currently shows:

Concessions: CONCESSION: LNWR*, CONCESSION: GWR*, CONCESSION: LBSCR*, CONCESSION: CR, CONCESSION: SWR, CONCESSION: LYR, CONCESSION: NBR, CONCESSION: NER, CONCESSION: MR, CONCESSION: SECR

Suggest changing it to this, which is easier to read:

Concessions: LNWR*, GWR*, LBSCR*, CR, SWR, LYR, NBR, NER, MR, SECR

**Comment by joeyd4329** [comment]
I again want to promote that I think showing the timeline along with the map on the same page would enhance the playing experience since the map and the order of things are very relevant to each other.

**Comment by magnusfalt** [comment]
> I again want to promote that I think showing the timeline along with the map on the same page would enhance the playing experience since the map and the order of things are very relevant to each other.

It is a good suggestion, i will close this issue with a fix for the orginal improvement. You can make an enhancement issue for that specific case.

**Comment by joeyd4329** [comment]
Sounds good, wasn't sure if I should open an enhancement issue or not.
