### ISSUE TITLE
[18CZ] should not be able to buy in a smaller corp for less than half of its share value

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#4209]
Chrome 88.0.4324.186

KFN is able to acquire OFE for $1 to $33 per share
(minimum should be $34 since the OFE price was $68 at the time)

Looks like this is repro'able by typing the value into the input field
(if you click the "arrows" on the input field to reduce the value, it correctly restricts input to `min` and `max`)

[testcase](https://gist.github.com/benjaminxscott/666f4a35c30b415e77f4089097e7d29e)

edit: we should also check that the "max_price" (1.5 * share_price) is also enforced

**Comment by Zwergenpunk** [comment]
When I open the gist and go into KFNs turn the price for OFE is correct.
![image](https://user-images.githubusercontent.com/7661170/109547504-bb0be200-7acb-11eb-9014-71fc9c106b1a.png)

**Comment by benjaminxscott** [comment]
Hmm so the html "should be" filtering input

It looks like the bug is repro'able though?

![image](https://user-images.githubusercontent.com/1711810/109551960-12875f00-7a86-11eb-93e9-5493f7ed020f.png)

**Comment by Zwergenpunk** [comment]
Yeah we should at least validate in the backend
