### ISSUE TITLE
map drawing issues with new games e.g. 1835 while using 18xx-maker transformation into 18xx.games .

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#421]
Map Drawing Issue #1:
The expect result should like this:
![image](https://user-images.githubusercontent.com/64490299/82480515-3586ea80-9ad4-11ea-916e-ccf318be3da9.png)

the original output from xx.json into xx.rb is:
"gray":{
  "t=r:10;p=a:1,b:_0" : ["P17"],
....
then no map shows up, in the browser is only
![image](https://user-images.githubusercontent.com/64490299/82480245-ca3d1880-9ad3-11ea-83b1-322339e0b530.png)
after modifying into:
"gray":{
  "t=r:10;p=a:1,b:_0;p=a_0.b:1" : ["P17"],
the engine start working again and the map is like this:

![image](https://user-images.githubusercontent.com/64490299/82481796-243edd80-9ad6-11ea-87bb-fb1f5d578a24.png)

**Comment by hast18xx** [comment]
#2
expected is
![image](https://user-images.githubusercontent.com/64490299/82524205-a65af080-9b2e-11ea-9f4c-a902cc37c2d2.png)
18xx-maker comes with:
            %w[N5] => 't=r:10;t=r:10;p=a:3,b:_0;p=a:4,b:_1;p=a:_1,b:5',
            %w[N7] => 't=r:10;p=a:2,b:_0;p=a:_0,b:4;p=a:0,b:_0;p=a:_0,b:5',

to make it drawable those was changed into:
      "t=r:10;p=a:0,b:_0;p=a:1,b:_0;p=a:2,b:_0": [
        "N5"
      ],
      "t=r:10;p=a:1,b:_0;p=a:_0,b:5;p=a:2,b:_0;p=a:_0,b:3": [
        "N7"
      ],
![image](https://user-images.githubusercontent.com/64490299/82524489-5f212f80-9b2f-11ea-92cf-a671a28d170b.png)

**Comment by hast18xx** [comment]
#3
expected is:
![image](https://user-images.githubusercontent.com/64490299/82524602-ae676000-9b2f-11ea-8468-0d5f07dab34b.png)
18xx-gamemaker :+1:       "c=r:20;p=a:1,b:_0;p=a:_0,b:3;p=a:3,b:_0;p=a:_0,b:5;p=a:1,b:_0;p=a:_0,b:5": [
        "N13"
      ],
![image](https://user-images.githubusercontent.com/64490299/82524814-27ff4e00-9b30-11ea-8d02-2ab2ea85ab6c.png)

**Comment by hast18xx** [comment]
#4a 
expected is (gray)
![image](https://user-images.githubusercontent.com/64490299/82524960-87f5f480-9b30-11ea-9fc6-7791c0e2021c.png)
18xx-gamemaker

      "t=r:10;p=a:1,b:_0;p=a:_0,b:4;p=a:0,b:_1;p=a:_1,b:5": [
        "G4"
no town at  Koblenz (gray)      ],
![image](https://user-images.githubusercontent.com/64490299/82525340-66493d00-9b31-11ea-9bfa-eefc839ab486.png)

#4b)
expected is yellow - two stations avail (see pic above)
18xx-maker:
    "yellow": {
      "c=r:40;c=r:40;p=a:3,b:_0;p=a:4,b:_1;l=B": [
        "L19"
      ],
      "c=r:0;c=r:0": [
        "J3",
        "G6",
        "E6"
      ]
one town symbol  is missed

**Comment by hast18xx** [comment]
Was closed by mistake

**Comment by roseundy** [comment]
Please check again, I'm pretty sure these are now fixed.

**Comment by roseundy** [comment]
This is how these tiles can now be rendered:
![render_1](https://user-images.githubusercontent.com/8494213/94220014-4f32a700-fea5-11ea-8303-710059db0954.png)
![render_2](https://user-images.githubusercontent.com/8494213/94220018-50fc6a80-fea5-11ea-8d1c-bf0a3b9a16ac.png)
![render_3](https://user-images.githubusercontent.com/8494213/94220021-52c62e00-fea5-11ea-8336-88a4cf2e8c80.png)
![render_4](https://user-images.githubusercontent.com/8494213/94220025-55288800-fea5-11ea-8953-4f0faaf2da43.png)
