### ISSUE TITLE
[18CZ] should not be able to purchase a scrapped train

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#4211]
NWB bought in BCB and scrapped both its `2a` trains

EKJ is able to buy in those `2a` trains from NWB on its turn, even though they have been scrapped

[test case](https://gist.github.com/benjaminxscott/e90674ef9a3f35d6b329aae33abb1e14)
edit: fixed json

**Comment by Zwergenpunk** [comment]
Pretty sure I fixed that.
I cannot reproduce it in the current version.

**Comment by michaeljb** [comment]
There's a small JSON syntax error in @benjaminxscott's link, cleaned up here - https://gist.github.com/michaeljb/bbb57cd0db85352443a5e4310ae5617d

With the above loaded into the currently deployed code (adb0153d), 18xx.games is allowing EKJ to buy the `2a` trains scrapped by NWB as @benjaminxscott describes.

![Screenshot 2021-03-01 224854](https://user-images.githubusercontent.com/1045173/109604234-6888f080-7ae0-11eb-84d0-4d55612058e4.png)

**Comment by Zwergenpunk** [comment]
Oh wow you're totally right. I did not understand it correctly.
The corporation has the scraped trains even if they don't appear on their card.

I think I do not reset the owner correctly. I tried to set it to itself but there was a problem and I did not see that buying option.
