### ISSUE TITLE
[1822] Show Timeline On Map

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#4213]
It would be very useful to show the Timeline that is shown under the Info tab right now on the Map page as well. The timing of the deck and very relevant when looking at the map and it would save from tabbing back and fort

If possible, it could fit nicely in the upper right portion of the map space since its basically blank. But I'm not sure if that space is reserved for the map grid only or something.

In any case, displaying the timeline alongside the map would be a helpful enhancement.

**Comment by CaptainObi** [comment]
@joeyd4329 By timeline do you mean the order of bid boxes and cards?

**Comment by joeyd4329** [comment]
Yes. The same info that is shown in the Info tab under Timeline would also be very useful to have alongside the map.

Maybe a column format on the map would fit better? Either way, knowing what the order of cards while looking at the map is a pretty critical element.

**Comment by pstone1** [comment]
Yes. Similarly, I would put everything that are in the current bid boxes on the market tab, at the bottom. You can currently see the whole list either in the timeline on info, or more detailed view on entities. The detail of each company does is helpful if you do not know the acronyms, but the entities tab shows everything in a giant list. The market tab would be a good place to put the next set of minors, the next set of private companies, and the current available set of concessions.
