### ISSUE TITLE
Turn timer / auto-play

### ISSUE THREAD

**Issue by Bastwood** [tobymao/18xx#422]
I'd be nice to be able to set a turn timer for real-time games in order to better control the length of the games. If a player doesn't take their turn within the allotted time, they automatically pass/do nothing.

There are some tricky edge cases that'd need to be tackled, such as what to do in scenarios where passing/doing nothing isn't really applicable. For example, during private auction it could be better to just buy the cheapest private, since plain passing could create an infinite loop if everybody just keeps passing.

Other problem cases include emergency financing (what shares to sell if out of money; maybe just sell random ones?) and running routes (don't have a good solution for this one).

**Comment by sparr** [comment]
There has been some discussion of this on Slack.

My recommendation is to have a defined list of automatic actions, to be taken in any situation where a player has failed to act (out of time, abandoned the game, deleted their profile, etc). Basically this would be like making the dumbest possible AI.

Situations, like emergency fundraising, where the player is forced to make some non-neutral decision could fall back on any number of algorithms, all of which have pros and cons, including choosing randomly.

For running routes, eventually we will have an automatic route optimizer, but until then I think it should just be left to the other players to calculate and operate in master mode, perhaps with a message instructing them to do so.

**Comment by tobymao** [comment]
i think as a first pass people should just rely on master mode

**Comment by Djeefther** [comment]
I am hosting one play and could master to pass, but I should control the time myself, I said on that that everyone should play every 12h if possible. But a clock of timing and notification you be an improvement. Maybe just play on max in X time, or more complex chess-timing with a limit to play. And notifications in the future.

**Comment by tobymao** [comment]
there's a bigger ticket for timer closing
