### ISSUE TITLE
1822 - English Channel - won’t let you lay tile after using power to token 

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#4224]
The code doesn’t let the owning company of the English Channel lay the token through the power then lay tile on that space.  I feel like this is not working as intended. 

https://18xx.games/game/30355?action=869

**Comment by magnusfalt** [comment]
The rules is very specific about that you have to do all the steps on you operating turn in order. You cant token before you lay track and so on. In the case you mention, you can lay track and then use your English Channel power to token. And as you pointed out, you can only use the power of the EC to lay track there is no slot available in the english channel. So this is green -> brown or brown -> gray.

**Comment by magnusfalt** [comment]
But there still is a bug i see according to the rules. But i still dont see anywhere that you can use the power before the lay tile step.

3.1.17 The use of P5 to place an exchange token in the English Channel does not require the owning company to be able to trace
a route to the English Channel. It does not count as the company’s token placing step. If there is no token space available,
the private company also allows the owning company to upgrade track to create a token space. This upgrade is subject to
the standard £100 cost and track colour phasing and counts as the track laying action for the operating company.

**Comment by Eludyan** [comment]
You are laying the token as part of using the private, not the lay token step as it says that it is not part of the lay token step. Therefore, since you can use a private at any time during the turn, it goes to say that you can use it to lay that token then do your lay track step.  I can ask in the 18xx email chat that Simon sometimes responds to. Scott would probably be able to give clarity, too.

**Comment by magnusfalt** [comment]
You might be right, but as per the rule 5.3.1. I did it so you only can use the EC token in the token step, and if you have to lay a tile then you will have this option during the lay tile step.

**Comment by magnusfalt** [comment]
I have fixed the bug where EC counted as the token step. Now you can use EC and you can also token somewhere else.

**Comment by Eludyan** [comment]
I sent an email to the 18xx group and Simon is responding... hopefully we can have a rule clarification about what step the token placement by the private takes place soon.

**Comment by magnusfalt** [comment]
Great thank you.

**Comment by Eludyan** [comment]
An answer! The implementation is accurate!  There needs to be an ability though to lay the track if there is not a token spot available and it would cost $100.  We did not test if this situation works as it did not happen.

From Simon:

Ah, sorry, now I get the question.
If there isn't a token space  it allows you to upgrade & token simultaneously. 
But if there is a token space then you can't token and upgrade anyway because the turn order of track then token takes precedence and you can't subsequently lay track having placed a token.  Even though use of the EC private doesn't count as the one token lay per OR, it still happens during the lay tokens step. 

S.

**Comment by magnusfalt** [comment]
Ok great then i dont have to change anything :) Thank you for your commitment to find bugs.

Yes the EC ability will show it self during the lay track step if there isnt a slot ready in EC, and the tile is green and phase color is brown. If tile is brown and phase color is gray. Since upgrading from yellow to green doesnt open up a slot.

**Comment by magnusfalt** [comment]
I can also say that The English Channel private was by far the hardest to implement of all the privates, so its good that all the cases will be tested.

**Comment by magnusfalt** [comment]
There is a bug with M-T and pontypool. As it is now, you cant run routes though but you can lay track as it is a connection. I im trying to figure out how to fix this.

Midwales it offboard, just graphics that is showing it wrong.

**Comment by magnusfalt** [comment]
M-T and pontypool tracks counts as one, that exception is in the game.

**Comment by Eludyan** [comment]
When you say run routes through, i feel like that is working as intended. You should not be able to run through both cities.  You would start at one and run out but not start from the 19 and run in, through the cities, and out toward the 10...

**Comment by magnusfalt** [comment]
Im pretty sure the routes are working as intended when you run your trains. But take i e you have minor 20, it have access to Cardiff when laying track, even if there is no track on Newport. So it can lay on hex E36 and it can lay a straght yellow town tile from cardiff towards SWR home tile. This is wrong, the track on M-T and pontypool is terminal and shouldnt go beyond E34 and F33.

**Comment by magnusfalt** [comment]
There is an issue on this #4204, so i will try to fix it as soon as i have a good solution.
