### ISSUE TITLE
[1849] Game considers company has route even though it was destroyed during the earthquake

### ISSUE THREAD

**Issue by ggohierroy** [tobymao/18xx#4230]
https://18xx.games/game/28588?action=416

Steps to reproduce:

- Float SFA when no tracks are leading to its home base (company has no legal route)
- Use Società Marittima Siciliana to teleport to Messina
- Run company -> Profit
- Trigger earthquake
- SFA no longer has a route

Expected behavior during train buy phase of the company:

- SFA doesn't need to buy a train because it no longer has a legal route they can run

Current behavior:

- SFA is forced to buy a train

**Comment by dfannius** [comment]
Fixed with #4232.
