### ISSUE TITLE
[1822] Indicate Destination Tokens when Simple Logos is turned on

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4235]
https://18xx.games/game/30447?action=407#map (see LBSCR destination)

In the physical game of 1822, the company destination tokens are visually distinct from the company's other tokens. This visual distinction is helpful when looking at the map, especially for players who are not running the company. 

I believe the physical printing uses a black token to distinguish this, but modifications may be needed for this implementation.

**Comment by magnusfalt** [comment]
If you look at the tokens, destination tokens have a black background by the text. All the other have white background.

**Comment by Maxwell-Frank** [comment]
If you have "Simple corporation logos" turned on, that black background does not appear

**Comment by magnusfalt** [comment]
> If you have "Simple corporation logos" turned on, that black background does not appear

This is true, very strange. I will look into it.
