### ISSUE TITLE
1817: 10 share corp started below $150 cannot buy tokens by simply selling shares

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#4238]
See subject - I can par a corp at $100 and it doesn't have enough to buy tokens ($150). When it comes back to me I can buy a 3rd share and that should let the corporation buy its tokens but it doesn't. I have to take a loan in the corp to get the tokens.

What is expected is that after a share sale, a check is done to see if the corp can buy its tokens and it does if possible

Gist:
https://gist.github.com/ventusignis/d74c5e8cd085683a603a0c6b0a7e8fcd

**Comment by jenf** [comment]
Shoot, forgot about that way to put money into the company, will fix tonight.
