### ISSUE TITLE
1856: Issues found to be fixed lated

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#4247]
- [x] Trainless corporations skip paying interest
- [x] Force buying trains doesn't work
- [x] Token step is skipped even if a loan could be taken to afford token

- [x] In 1856 if a corporation is trainless, it goes straight from Track & Token to Buy trains; since the Route & Dividend steps are skipped entirely the interest check is skipped and the corporation gets away with taking a loan in TrainBuy without interest being deducted.
- [ ] Nationalization broke - `@round.active_step` is returning null in `event_nationalization!`

**Comment by jenf** [comment]
what's left to do on this?

**Comment by ventusignis** [comment]
I've been using this as a catch-all for regressions I find while doing testing for 1856 development
