### ISSUE TITLE
1822: Running order got corrupted during OR

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#4263]
4 of us tried a game tonight.  At this point, you can see there are 6 minors and 3 majors in the running order in OR4.1:
https://18xx.games/game/30489?action=271

The LYR (last) is about to run. It winds up buying the first 3T out of pocket with help from waaayback (after causing a stock sale (clue?)), triggering Phase 3 and killing some L's (another clue?).    We then move to OR4.2 and things seem fine, until the 7 runs.  At this point, the majors disappear from the running order (click the ">" button once to see):
https://18xx.games/game/30489?action=281  

Next, at this point everything after the 20 disappears (click the ">" button once to see):
https://18xx.games/game/30489?action=289

Then, after the 20 runs, the game jumps to SR5.   Game is still sitting here, we abandoned it.

**Comment by magnusfalt** [comment]
Thank you for the very thorough bugreport. And you are correct, the bug had to do with the sale of a share during the emergency train buy. There is a fix for this in the linked pull request just waiting for approvement.

**Comment by waaayback** [comment]
Thanks!  Will this game be playable or should we abandon it?

**Comment by magnusfalt** [comment]
> Thanks! Will this game be playable or should we abandon it?

Since you havent done anything after the "bug" you can continue as soon as the patch hits live, and it will be minor 3's turn.

**Comment by waaayback** [comment]
How do I know when the patch is live? Is there somewhere to check on Github?

**Comment by dfannius** [comment]
See the "Current version" on https://18xx.games/about.
