### ISSUE TITLE
18CO Game cannot continue

### ISSUE THREAD

**Issue by coleman07** [tobymao/18xx#4264]
We're sorry this game cannot be continued due to GameError: Blocking step Lay Track cannot process action 170

Broken action: { "type": "run_routes", "entity": "KPAC", "entity_type": "corporation", "id": 170, "created_at": 1614052791, "routes": [ { "train": "2-2", "connections": [ [ "C15", "D14" ], [ "D14", "E15" ] ], "hexes": [ "C15", "D14", "E15" ], "revenue": 70, "revenue_str": "C15-D14-E15" }, { "train": "2P-0", "connections": [ [ "C15", "D16", "E15" ] ], "hexes": [ "C15", "E15" ], "revenue": 60, "revenue_str": "C15-E15" }, { "train": "2-3", "connections": [ [ "E15", "F16", "E17", "E15" ] ], "hexes": [ "E15", "E15" ], "revenue": 60, "revenue_str": "E15-E15" }, { "train": "2-4", "connections": [ [ "E27", "F26", "F24" ] ], "hexes": [ "E27", "F24" ], "revenue": 60, "revenue_str": "E27-F24" }, { "train": "2-1", "connections": [ [ "C15", "B16", "A17" ] ], "hexes": [ "A17", "C15" ], "revenue": 70, "revenue_str": "A17-C15" } ] }
Please raise a bug report and include this link (https://18xx.games/game/27384?action=169)

**Comment by michaeljb** [comment]
I'm doing a release that fixes some issues with private company ability timing, affected games will be broken for a few minutes. This game ID is in the list to be migrated, so it will be fixed soon.
