### ISSUE TITLE
1822 - priority listed on entities 

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#4265]
It would be helpful if who has priority was added back onto the person on the entities page during ORs and game page during the stock round like other games have. 
Thank you for all you are doing for this amazing game! 
Jen

**Comment by waaayback** [comment]
Agreed!  Also, I would go one step further... the players on the entities page should be listed in the recalculated upcoming SR order, left to right, after every stock round.  1822 stock round order is not based on seating.

I notice that right now (7 Mar) the upcoming stock round order *is* correct on the Spreadsheet tab, but *not* on the Entities tab.

**Comment by Eludyan** [comment]
If reordering the images and such is difficult, it could be a tag/label “priority 1” “priority 2“ etc

**Comment by waaayback** [comment]
Sure, that works

**Comment by magnusfalt** [comment]
The order on the entitles page should be the correct order in which the next stock round should be in during the operation round. Ive checked a few games and what i can see this is the case. I might be wrong though if you can give an example where this isnt so.
