### ISSUE TITLE
1849Boot - parring at $216 in yellow

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#4266]
21:56:25Humanpriesthttps://18xx.games/game/30861
I was able to par the starting company at higher than 100
21:57:09Is a responsible adult able to do the bug report for me? 😂

would fill out a better issue but still watching over the migration for #4191

**Comment by michaeljb** [comment]
https://18xx.games/game/30861?action=38

**Comment by scottredracecar** [comment]
I have a fix for this along with a corporation revamp for the boot. Coming soon.
