### ISSUE TITLE
1889 autopass in SR and Dougo [GameID #735]

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#427]
Hi Toby,
finally found two new issues in 1889. First this small one:
In game 735, I bought Dougo. Then in SR1, I did some actions till I was out of money. After that it was decided that: "spobster has no valid actions and passes", while I could have still exchanged Dougo for a share. So it would have been nice to get the turn back, I did have a valid action. Of course you may argue that you should immediately use the Dougo, but that is not always as obvious.
I will file the second right after this one.
Cheers, spobster

**Comment by Spobster** [comment]
Wow.... major coincidence, was just reading back a bit on slack and found that exactly today you have been discussing this one :)
Maybe the best way to do it is not to correct the autopass, but to give the owner of dougo a final turn (that does not affect priority) at the end of every stockround?

**Comment by tobymao** [comment]
i don’t think that makes sense, you can just exchange the share in the OR.

**Comment by Spobster** [comment]
I guess that doesn’t work if you want to use it to float the company and still want to join the upcoming OR...



Op 21 mei 2020 om 03:33 heeft Toby Mao <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


i don’t think that makes sense, you can just exchange the share in the OR.
