### ISSUE TITLE
Game subtitles

### ISSUE THREAD

**Issue by mavit** [tobymao/18xx#4271]
Many 18xx games have a descriptive subtitle to go along with their year (e.g., “1889: History of Shikoku Railways”).  Should we mention these somewhere?  They give a flavour of the different games, and might help with SEO.

In the interests of brevity we probably don’t want to use the full title everywhere, but I feel it belongs on the Info tab, at least, and probably the Create New Game page too.

**Comment by michaeljb** [comment]
Fixed by #4512
