### ISSUE TITLE
[1849] Game isn't letting me connect narrow gauge to standard gauge as first lay

### ISSUE THREAD

**Issue by ggohierroy** [tobymao/18xx#4273]
https://18xx.games/game/28588

Situation:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/1578363/109828103-54411280-7c0a-11eb-92b7-3513f16f4a70.png">

I'm trying to lay a track for SFA so that narrow gauge goes against standard gauge since I'm trying to prevent it from operating. (it has no trains and I don't want to buy one)

Expected behavior:
I can put down a straight yellow city tile and flip it so that narrow goes against standard

Current behavior:
The game doesn't let me flip the tile

**Comment by dfannius** [comment]
Fixed with #4288.
