### ISSUE TITLE
Allow email notifications only for some (async) games

### ISSUE THREAD

**Issue by bazik123** [tobymao/18xx#4275]
For async games email notifications make sense. 
For live games they do not, AT ALL.

a single global setting forces people to either get ton of spam from live games, or (more likely) to not get emails for async games.

Request:

Allow a game to have different notification settings from the main profile.  Perhaps a [Live game - no emails sent] checkbox close to `invite only` one ?

**Comment by yzemaze** [comment]
There shouldn’t be any "spam from live games", because you shouldn’t get any mails as long as you’ve got an active 18xx.games tab/window.
Did you experience something different?

**Comment by tobymao** [comment]
you won't get emails for live games
