### ISSUE TITLE
Option to enable simple corporation logos from within games individually. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#4278]
For the most part, I like using the fancier corporation logos in game, but there are a couple of games whose tokens are just impossible to distinguish. 

Rather than having to switch back & forth depending on my game, it would be nice to have the option to enable the feature one game at a time Via each game’s Tools tab.

**Comment by dfannius** [comment]
I really want this now that 1846 has simple logos; I prefer simple logos on other games so I have the global switch turned on but I prefer the fancy logos on 1846, which now I don't get anymore.

**Comment by scottredracecar** [comment]
I think how this should work is that the system has a per-user record of the last "token state" the user had the game in for that title. 

So if I like simple logos in 1817, I would toggle that on in the map. Then if I like standard logos in 1846, I toggle that on in the map as well. The system remembers that I last had 1817 in simple and 1846 in standard. 

There are no settings/checkboxes, it just remembers.

**Comment by philcampeau** [comment]
At a bare minimum, I think it would be nice to be able to activate it
manually in each game, the same way I can enable Master Mode in a game and
it stays enabled for that game.

>
