### ISSUE TITLE
[18Chesapeake] Game allows placement of a tile that does not extend a route

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#4287]
The [game allows](https://18xxgames.slack.com/archives/C012K0CNY5C/p1614812216385000) placing of a tile that fails to "extend a route of the company", at least from [this position](https://18xx.games/game/30071?action=470), where the C&A is allowed to place tile 4 with rotation 0 in I5.

<img width="844" alt="Screen Shot 2021-03-03 at 5 53 28 PM" src="https://user-images.githubusercontent.com/757327/109884057-5aef7a00-7c4a-11eb-8351-dd26693e408e.png">

**Comment by ventusignis** [comment]
I just found this looking at the pathing code and I was about to submit a bug with this example
![image](https://user-images.githubusercontent.com/2993555/109895662-98113780-7c5d-11eb-8883-75ec89c1db56.png)

**Comment by tobymao** [comment]
reopening this since i had to revert due to performance issues

**Comment by orome** [comment]
An illustration of the loop that appears to allow the illegal placement in the OP:

<img width="681" alt="Screen Shot 2021-03-15 at 4 36 16 PM" src="https://user-images.githubusercontent.com/757327/111218198-cde2e400-85ac-11eb-8538-8cf6dceabdb1.png">

**Comment by roseundy** [comment]
So, I'm pretty sure this can be fixed by using an edge check instead of this:
         next if paths[path]
to the central node.walk loop. Of course we will have to store the edges for the path yielded by node.walk

**Comment by roseundy** [comment]
And I already found a flaw in my proposal. When tracing from a node, two divergent paths from a token may take you to two different nodes. Both of those sets of paths are fine, but they will have an edge in common. The only time you want to reject a path with a re-used edge is when you are following a chain of nodes.

**Comment by michaeljb** [comment]
here's a gist with a hotseat game recreating ventusignis's example, the last action is laying the 25 on F8 - https://gist.github.com/michaeljb/b3ee552eadec0d76edb4d00748f137ed
