### ISSUE TITLE
History navigation should skip over undos

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#4289]
We've discussed this many times on Slack but I don't think an issue was ever created.

Players often undo many times while executing their turn as they try things out; it's not unusual in my games for a whole turn to be done and undone 5+ times in the process of arriving at a final set of actions. Stepping through these actions when reviewing someone's turn is a gigantic chore. History navigation should skip over the undone actions and only step through the actions that were actually performed.

Being able to step through undos could be of use when debugging, so it would be nice to have some sort of flag for this, even just a variable one can set in code.

**Comment by daniel-sousa-me** [comment]
Related: also skip messages

This should be easier to implement and probably happens almost as often
