### ISSUE TITLE
Train discarding UX could be clearer

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#429]
So, this is a pretty common situation...I have KO, which buys a 5 train, moving the game into a new phrase and reducing the train limit from 3 to 2. The KU in this case has a 3 a 3 and a 4, so needs to discard one. But the game just prompts me (the KO, and I don't own the KU) per the screenshot...

![IMG_0039](https://user-images.githubusercontent.com/830087/82519011-3ca10d80-9b53-11ea-9077-b0e7ff4c6262.PNG)

It doesn't mention which railroad needs to discard, and it doesn't move control of the game to that player. This seems very unclear, and there's no good way to ask them "hey, what do you want to discard?" Of course, in this case the answer will be the 3 99% of the time, but...still, this doesn't seem right.

**Comment by sparr** [comment]
Is the KU not also underlined and/or bolded in the corp list?

I agree that it should be more clear in the UI, perhaps with the corporation name above the discard options?

**Comment by jcoveney** [comment]
The KU was not underlined or bolded -- there was no UI indication as to whose company needed to discard, and control was not given to the director of that company?

**Comment by tobymao** [comment]
6f25625
