### ISSUE TITLE
[1822] Game does not allow one player to bid or buy shares during the stock round

### ISSUE THREAD

**Issue by thornduck** [tobymao/18xx#4294]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**
https://18xx.games/game/31032

What steps cause the unexpected behavior?

-During the SR, RandomGuy can't take any bid or stock actions
-All players lose bid tokens during RandomGuy's turn

**Comment by magnusfalt** [comment]
The game you reference to have been archived during last nights patch so i cant debug it. Ive added some extra checks in the stockround see if that helps. If the bug comes up again, please make an new issue with the new game id.
