### ISSUE TITLE
UI shows Dougo exchange when master mode is not enabled

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#430]
Screenshot captures the issue fully I think? I don't own Dougo, it's my turn, I click on IR and it has the prompt to buy it for someone else.
![IMG_0040](https://user-images.githubusercontent.com/830087/82529805-60258180-9b6e-11ea-9d25-2e57d7c1b139.PNG)

**Comment by jenf** [comment]
Previously there was no master mode, so you could act as other players. It should now only show when master mode is activated.

**Comment by sparr** [comment]
The buttons to act as other players are still visible everywhere, not just here.

**Comment by Jer3my33** [comment]
Yep, just wandered in to report this. This is not just a display issue, but additionally it is also allowing me to actually take that action by pressing the button. Having said other player trade in the Dougo private and for an additional error, that action is being treated as my stock purchase for my turn and moving action to the next player :-)
