### ISSUE TITLE
1830: after first D is bought, still given option to upgrade to D

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#4300]
Game json: https://gist.github.com/jcoveney/a66c1798c6fbdb5a692ad8bd0dbcc8b9

Where I noticed the issue: https://18xx.games/game/29232?action=1186

Pretty straightforward. A D was bought via upgrade...as far as I know, once the first D is out, no more upgrades should be possible?

**Comment by dfannius** [comment]
I don't see anything in the AH or Lookout rulebook that prohibits this, and in fact the AH rules seem to implicitly acknowledge the possibility:

> Once the first 6 Train is purchased, D (Diesel) Trains are also available as an alternative to other 6 Trains. Diesels may be bought for the $1100 face value or for $800 with a trade-in. Either a 4, 5, or 6 Train may be traded in for the $300 discount, **but note that the purchase of the first Diesel removes the remaining 4 Trains from play** [implying that the other trains can still be upgraded].

**Comment by crericha** [comment]
You can always upgrade a train to a D. What goes away is the ability to upgrade a 4 to a D because the 4s rust on the purchase of the first D.

Relevant rule from section 7.6 in the Mayfair rulebook:

> Diesels — Once the first 6-train is bought, the diesel (“D”)
> trains may be purchased in addition to any 6 trains still in the
> bank. A diesel train costs $1100. But, the price is only $800 if
> the railroad “trades-in” a 4-, 5-, or 6- train. The exchanged train
> (if not obsoleted by the exchange) is placed in the open market.
