### ISSUE TITLE
1822: Some small map and game tab typos/issues

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#4317]
I figured these were all minor and simple enough not to require a separate defect for each.  If I need to break them up LMK.

1) The L&Y's charter on the various tabs is missing the word "Railway". All the others have that.
2) London's value is hidden under the "London" label. Suggest moving the value to the middle of the tile, to match the real game.
3) The Mountain terrain icon for Manchester is similarly hidden. Perhaps move "Manchester" underneath and move the destination icons to the top left.
4) Two privates (the L&SR and the L&SR)  :-) have the same acronyms, it's confusing.
5) Privates: the private numbers (P1, P2, etc) are used in the player's area of the spreadsheet, and the acronyms are used pretty much everywhere else, and there's no 'lookup table'.  Suggest that the *numbers* be used everywhere (it's what most players of 1822 use; I can tell you the 2T's are P3 and P4 but I have no idea what they're named) and put both the number and acronym on the private 'cards' for a reference.  
6) The players' vertical columns in the spreadsheet are not aligned between the upper and lower sections (probably due to the privates listings)
7) At the end of the SR in the early game, you get the following:  _"X minors with no bids. If available up to X L trains will be removed"._  Why the "If available up to" part?  It's confusing, and the game should know how many will be removed. :-)

**Comment by magnusfalt** [comment]
We can do them all at once here.

1. [ ]
2. [ ]  This i might not be able to fix, all the labels on a city is auto generated and as it is now we cant tell where the labels should be.
3. [ ]  Same as above
4. [ ] Missed that one :)
5. [ ] There is another issue #4198 where we talk a little bit more about this. But yes the Px label should be on the company card
6. [ ] See if @yzemaze might have a look at this.
7. [ ] The log message is set before the accual train removad. But yes it might be confusing, shall se if i can move it.

**Comment by jenf** [comment]
For 2, we can do a if 6 cities, place value in middle.

**Comment by magnusfalt** [comment]
I will close this with the linked PR, there still is the issue with Manchester. I will see if we can do a cleanup of the tiles where you cant see all the information.
