### ISSUE TITLE
[1822] Company Should not be Allowed to Skip Placing Destination Token

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4318]
Right now, companies are given an option to place their destination token and can click "skip" if they do not want to place it. However, rule 5.11.1 states:
`After its tile laying step, if the major company can trace a route from its home station to its destination station then it must place its destination station token in its destination station: this is free of charge.
`
Placing your destination token should not be optional.  It would be great if it would be placed automatically once a connection has been made.

**Comment by magnusfalt** [comment]
This is purley out of technical stand point. Traversing the map to check if a path is valid is very costley cpu wise. We dont want to do this all the time, as it is now we only do it when you press a city. But i might be able to do the same when you press skip and you get an error if you have a path.

There is a another action i will look into later as well, that have to do with autoactions.
