### ISSUE TITLE
[zigzag markets] When more than 3 medium tokens are on the same market price in the top row, the 4th token is obscured by the bottom row

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#4321]
https://18xx.games/game/28521?action=416#market

For example:
![Screen Shot 2021-03-04 at 11 12 13 PM](https://user-images.githubusercontent.com/5924761/110080488-5f498f00-7d3f-11eb-952e-a4a6e2cd282c.png)

**Comment by Zwergenpunk** [comment]
Thanks.

This has to be true for all games.
I think, most games do not have so many corporation

**Comment by yzemaze** [comment]
> This has to be true for all games.

FYI: It was only a problem for titles with different token sizes *and* a zigzag market. 18CZ might be the only one thus far.

**Comment by Zwergenpunk** [comment]
Ah ok.
Thanks for the fix :)
