### ISSUE TITLE
1822 better graphic presentation of Mid-Wales

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4327]
Mid-Wales in E28 should be drawn as a dead end for all incoming track, rather than a pass through. i.e. it should look more like Highlands than Glasgow.

It actually looks like the lines coming from F27 have arrows, but the rest don't? At any rate, it would be even better if grey dead end arrows had some separation to make them easier to see, like the ones in Methyr-Tyfdil and Pontypool.

**Comment by magnusfalt** [comment]
They are dead ends, just the cities is hiding them. So you cant pass though midwales. But i agree, the arrows should be shorter so you see them better. There are more locations on the map where this is a "problem"
