### ISSUE TITLE
[1822] Enhancement request to add highlight to companies in current auction

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#4328]
Add in an new color option for 1822, and other 1822 family games, where the items up for bid in the current stock round are highlighted when looking at the map tab. Below is a poor mock-up of the minors 5, 8 and 10 being highlighted to stand out as part of the current auction round while others are not.

The colors should be customizable on the user level as not to conflict with other color settings made by individuals.

![image](https://user-images.githubusercontent.com/67166181/110142029-f986f280-7d92-11eb-9f03-0622c9cefa92.png)

**Comment by magnusfalt** [comment]
Good suggestion, ive thought of this as well. Since on the physical game we always took the tokens for the minors in the bidboxes and placed them on the map just to see easier which was up for bidding.

**Comment by pstone1** [comment]
Even if the ones in bid boxes just had a bigger font and a thicker stroke around the city, this would probably be enough. 

Bonus points for buttons at the bottom of the map to cycle through the upcoming deck. So positions 1-4, 5-8, 9-12, etc. would highlight the upcoming minors too.

**Comment by waaayback** [comment]
Sorry for the bandwidth and the dumb question...  (Magnus, I tried to PM you but couldn't figure out how)

It looks to me like these changes have been merged (via #4435 and #4449), but they're not showing up in our new game (started today, [32368](https://18xx.games/game/32368)  Or what am I missing?

**Comment by magnusfalt** [comment]
Sorry for the late answer, but have been away from the computer. The reason you didnt see the change is when issues gets merged into master there (the branch which the liver server runs on) it doesnt automatic get transfered to the live server. Someone from the dev team have to run a script manually to transfer the code from github to the live server.

You can see under Current version on the https://18xx.games/about exacly which commit the liver server is on. As it is when i post this, the last commit on the live server is also the last commit here on github, so they are synced up.

**Comment by waaayback** [comment]
Thanks Magnus for your response, I really appreciate it.  It’s all clear to me now. :-)
