### ISSUE TITLE
Station tokens not showing on mobile (Android, Chrome)

### ISSUE THREAD

**Issue by willbeplayin** [tobymao/18xx#433]
https://i.ibb.co/GfDPWXp/1889bug3.png Here's a snip from game played on Windows using Chrome.

Here's a screenshot of the same game using Chrome on Android

https://i.ibb.co/n618km7/1889bug2.png

The station tokens are either transparent or missing completely and thus I can only do SR's on mobile, routing the tracks on OR is nigh impossible since I can't see where the stations are.

Keep up the good work!

**Comment by tobymao** [comment]
super weird, what kind of phone do you have and what version of chrome? what's your game id?

**Comment by sparr** [comment]
It looks like only the background circles are failing to render, but since the logos are white they are fully invisible on white token spots, and barely visible when overlapping a reserved label.

**Comment by sparr** [comment]
Does this happen in "View Desktop Site" mode in mobile Chrome for you?

**Comment by willbeplayin** [comment]
Honor 7, latest Chrome version. Using the "View desktop site" ie. view as it were on the computer desktop, it doesn't help either. This happens on every game ID, not just one. If you need more screenshots, let me know. :)

**Comment by jenf** [comment]
Does the following have a green background?
https://18xx.games/logos/1889/SR.svg

**Comment by willbeplayin** [comment]
Well, it does, when viewed on computer and on mobile since it's a direct link to the .jpg. 

When viewing on mobile, KO logo at K4 shows, same for AR at K8 even with green tile and KU at C10,  F9 AND also, weirdly enough, on the P tile at G12. So these are the ones that are showing properly.

What doesn't show properly is UR B7, IR E2, SR I2 and all the rest of the tokens that been put on the map. Game #993 in reference but this is the problem for all games. I can do full screenshots too.

**Comment by willbeplayin** [comment]
[https://i.ibb.co/zGQjJFn/bug1889.png](url)

**Comment by jenf** [comment]
@willbeplayin what version of Android are you using? Can you provide the exact model of the phone?

**Comment by willbeplayin** [comment]
Android 6.0, Honor 7 ( PLK-L01 ). Same thing happens with 18Chesapeake.

**Comment by jenf** [comment]
Setup an AVD with Android 6.0, the stock browser doesn't show any of the company logos on the map,will try later with proper chrome

**Comment by jenf** [comment]
Does this still occur, how about on chesapeake?

**Comment by willbeplayin** [comment]
> Does this still occur, how about on chesapeake?

Yes, Game #2351 does now show either PRR tokens for example. I can give you more examples.

**Comment by willbeplayin** [comment]
> > Does this still occur, how about on chesapeake?
> 
> Yes, Game #2351 does now show either PRR tokens for example. I can give you more examples.

Actually it only seems to happen with PRR tokens with Chesapeake. I haven't really played any OR rounds on mobile for weeks.

**Comment by tobymao** [comment]
this is probably an issue with your phone rendering specific svg
