### ISSUE TITLE
[18cz] Small Local Companies abilities triggered without benefit

### ISSUE THREAD

**Issue by scottnicholson** [tobymao/18xx#4334]
-https://18xx.games/game/31296 

- When the players went to try to use the Small Local Company, they were not able to, as the game showed the uses of (0/1).   A player who had a Small and Medium Local Company in a medium operating company was able to activate the Medium Local Company for a green tile lay, but the Small Local Company showed as being used (even though he doesn't recall using it).

Our only guess would be if the Local Company's ability to pay for terrain is being triggered without notification or request?  We couldn't find a spot in the log where this happened.   It happened to another player as well, who didn't recall using his small local company's ability, but the game showed it as being used.

**Comment by Zwergenpunk** [comment]
Thanks for the issue.
We had the problem at the beginning but it shoud have been fixed. 

If you have some time you could rewind the game and Check when exactly the ability was used. If not I will do it :)

**Comment by scottnicholson** [comment]
The ability wasn't used.  That's the problem - for two different players with Small Local Companies, they showed the abilities as used, but they were never used. 
I don't find anything in the log that shows them as being used, but maybe we don't know what to search for.

**Comment by Zwergenpunk** [comment]
Yeah at some point during track laying thr Counter goes from 1/1 to 0/1. 
It would be best to have that Action.

**Comment by Zwergenpunk** [comment]
I found the first action.
https://18xx.games/game/31296?action=295

When I clone the game it works like expected. When you activate the ability, and lay a tile the ability is used. If you just lay the tile in a normal way the ability is not reduced. 

Maybe it is a bit confusing that the "discount" ability is activated.
