### ISSUE TITLE
[1822] Incorrect number of 5 trains

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#4336]
https://18xx.games/game/31268

Not including the private companies, the trains with the 5P label, there are too many 5 trains. In the game linked above there are three held by companies and one available for purchase. According to page 17 of the linked rules there are only three 5 trains for sale.
![image](https://user-images.githubusercontent.com/67166181/110169175-8b075c00-7db5-11eb-81d5-4cd1bf84fd56.png)

**Comment by magnusfalt** [comment]
You are correct, you get blind the looking at the same numbers when you test. So you dont relect on them after a while :)

**Comment by magnusfalt** [comment]
Good thing we have great testers out here :)
