### ISSUE TITLE
[1822] Sold-out Companies on the Top Row Should Move Down and to the Right

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4343]
https://18xx.games/game/31338?action=964

LNWR was sold out at the end of the SR and should have moved diagonally downwards to the right, since it was on the top row, but the stock price did not move at all. 

4.11.1:
`At the end of the stock round, if 100% of any company is in players’ hands the stock market token for each such company rises one space vertically on the stock market, if possible. If the token is already at the top of the chart, it moves diagonally one space down to the right.`

**Comment by magnusfalt** [comment]
Yes i missed that part of the rule.
