### ISSUE TITLE
[1822] Game #31338 is Incredibly Laggy

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4346]
https://18xx.games/game/31338

Near the end of the game #31338 the game started becoming so slow and laggy that we were unable to finish. We all started receiving "page is non-responsive" errors from our browsers and single actions took minutes to register.

**Comment by tobymao** [comment]
g_1822/step/route.rb#11

@game.can_run_route? calls graph excessively , are you clearing the graph or something?

**Comment by tobymao** [comment]
https://drive.google.com/file/d/1OQkfsxg_ObNlKLwvyDbHj9sBEmSRs-E1/view?usp=sharing

here is a stackprof to help you fix the issue @magnusfalt

**Comment by magnusfalt** [comment]
> Game 31440 seems to have the same problem described in original post by Maxwell-Frank. It's a three player game, and it became very slow in the eighth set of operating rounds. Now we're in the ninth set, and it's even slower.

There is a solution for this that fixes this game as well. Just waiting for approvement for it to hit live.

**Comment by tobymao** [comment]
this is fixed for real now
