### ISSUE TITLE
Skip track

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#4348]
Commit 61d1017539ce7e279746936b9d1f309cbbf73942 introduced a `can_buy_tile_laying_company?` method on `lib/engine/step/tracker.rb` which prevents the tile laying step to automatically finish if there is some company that could be bought that would allow for an additional tile lay.

Imo, this is adding a bunch of unnecessary passes in a lot of games. I suggest a middle ground, where we only do this if the company is owned by the same player. This can be easily done by adding the following at line ~328:
```next false unless company.owner == entity.owner```

This is particularly annoying in 1870, because the river private is often bought late. It allows an extra track lay, but only for 2 corporations and in their homes.

What are your thoughts? @michaeljb @tobymao

**Comment by michaeljb** [comment]
That'll take another migration to remove some pass actions, but that should be an easy migration, and makes sense for virtually all cases

**Comment by daniel-sousa-me** [comment]
Thanks. I don't have any experience with migration and assumed it's trivial to someone that knows what they're doing. That's why I opened an issue with code x)

**Comment by michaeljb** [comment]
Yep I'll be able to test out a migration for this in a bit, want to deal with a few other issues first but hoping to get to this this evening 🙂
