### ISSUE TITLE
Spreadsheet legend doesn't include "half-paid"

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#4357]
<img width="258" alt="Screen Shot 2021-03-06 at 10 02 30 AM" src="https://user-images.githubusercontent.com/1295244/110211114-17bc2380-7e63-11eb-9394-0bb8abb202be.png">

`spreadsheet.rb` includes the line
```
                h(:td, { attrs: { colspan: @halfpaid ? 6 : 3 } }, "[withheld]#{' ¦half-paid¦' if @halfpaid}"),
```
but `@halfpaid` doesn't seem to exist.

**Comment by yzemaze** [comment]
Link?
