### ISSUE TITLE
[18Chesapeake] 2P - N&W only 9 shares

### ISSUE THREAD

**Issue by Vitriool** [tobymao/18xx#4364]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Game ID: 31485

Twoplayer: https://18xx.games/game/31485

I suppose there were 10 shares for N&W in the beginning of the game, I have no idea when it was set back to only 9.

Chrome Version 88.0.4324.190 (Official build) (64-bits)
Laptop (Dell, Windows 10)
![18Chesapeake 31584 shot01](https://user-images.githubusercontent.com/80178202/110222207-e2e6b580-7ed0-11eb-89d7-f74530be5db0.png)
![18Chesapeake 31584 shot02](https://user-images.githubusercontent.com/80178202/110222208-e37f4c00-7ed0-11eb-9e11-c0ca8df20726.png)

**Comment by yoyoson** [comment]
In 2p 18Ches, when the non-president player buys a share of a company, another share is removed. That's what happened earlier in that game, when Mystic bought an N&W share: https://18xx.games/game/31485?action=36

For reference, this is rule 14.3 in the 18ches rulebook.

**Comment by Vitriool** [comment]
Yes, I've checked the rules. My first 2p Chesapeake.
No bug.
