### ISSUE TITLE
1817 persistent payoff / take loan button locations

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4372]
If a corporation is at maximum loans, only the Payoff Loan button appears.

https://18xx.games/game/26561?action=836

<img width="418" alt="Screen Shot 2021-03-07 at 8 22 31 AM" src="https://user-images.githubusercontent.com/8732435/110246887-4d721280-7f1e-11eb-85a1-fca9e41496a8.png">

As soon as the President clicks the Payoff Loan button, a new Take Loan button appears in its place, and the Payoff Loan button shifts to the right.

https://18xx.games/game/26561?action=837

<img width="468" alt="Screen Shot 2021-03-07 at 8 24 08 AM" src="https://user-images.githubusercontent.com/8732435/110246935-89a57300-7f1e-11eb-9502-21cfc2e8324e.png">

Players frequently want to pay off more than one loan, and just click twice to do so, resulting in this:

https://18xx.games/game/26561?action=838

<img width="461" alt="Screen Shot 2021-03-07 at 8 25 23 AM" src="https://user-images.githubusercontent.com/8732435/110246969-afcb1300-7f1e-11eb-802d-6cc652474752.png">

It would be much better if the Payoff Loan button stayed where it was, so that a President can just click the number of loans they want to payoff. I don't think there is ever a time that someone would want to payoff a loan and then immediately take it again.

**Comment by bridger15** [comment]
Agreed.  If Payoff Loan was always to the left, it would be a much less frequent problem.  It's super rare that you'd want to take multiple loans in the phase where you are able to pay them off.
