### ISSUE TITLE
1822: A few minor feature requests

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#4376]
You folks are doing a great job with 1822..  keep it up!    
Here a few small things we've noticed.  If I need to break these up separately LMK)

1) During each SR, highlight the 4 available minors on the map. This is as simple as shading their home token circles a stand-out color. I suggest a light green (similar to the NER's charter color) but any reasonable color would do.
(never mind, just saw this is #4328)

2) During each SR, highlight the players' bids in a unique color on the minor, private, and concession cards.  In the physical game, it is easy to quickly grok where your bids are, due to the colored bidding cubes.  On the screen, this information 'pops' a bit less. See example below (hopefully it would be more subtle colors, that's all I had handy) :)

3) Minor #14 should point out on its card that it needs to spend $20 to lay its home token.  Unlike a terrain cost, this is not on the board and is easily overlooked.  

Example for #2
![image](https://user-images.githubusercontent.com/66023744/110250058-6cd16580-7f47-11eb-8a5a-a358265b02b5.png)

**Comment by yzemaze** [comment]
@waaayback I’ll take a look at 2. Would you like player colors somewhere else, too?

btw: Next time please split into separate issues.

**Comment by magnusfalt** [comment]
@yzemaze there is another issue #4385 where they talk about the same problem.

**Comment by waaayback** [comment]
No, I think the 'bidding cubes' is the only place where player colors 
are useful, thanks.

Roger on splitting up the bugs.  I figured these were all small quick 
items or I would have.

On 2021-03-10 13:05, yzemaze wrote:

> @waaayback [1] I'll take a look at 2. Would you like player colors 
> somewhere else, too?
> 
> btw: Next time please split into separate issues.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] https://github.com/waaayback
[2] https://github.com/tobymao/18xx/issues/4376#issuecomment-795836939
[3]
