### ISSUE TITLE
1828.games C15 not blocked while C&P in player hands

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4378]
https://18xx.games/game/31646?action=228

The C&P private company text says "Blocks Peterborough (C15) while owned by a player." The rules say "Blocks:C15 and reserves a station location at C15."

However, the server allowed the C&P to upgrade C15 while C&P was still owned by a player.

**Comment by ChrisTheCat** [comment]
Actually, in a different section in the rules, it says that the C&P power may be used to upgrade Peterborough to green, so there is an exception to the rules and component text.

I revise this to request that the text on the C&P private company call out this exception. Perhaps "Blocks/reserves Peterborough (C15) while owned by a player" would work.

**Comment by crericha** [comment]
To make sure I understand. Behavior appears to be correct, but the private's text is misleading?

**Comment by ChrisTheCat** [comment]
Correct.
