### ISSUE TITLE
1867 Incorrect Route Value with 5+5E

### ISSUE THREAD

**Issue by lbrande** [tobymao/18xx#4382]
https://18xx.games/game/31645?action=547

The value of the just run route should be 820 but is 800.

**Comment by dfannius** [comment]
That is, (100+100+80+70+60) * 2.

(By the way, it would be nice if the route string showed which cities are counted, like N/M trains in 1846.)

**Comment by jenf** [comment]
800
["A19", "D2", "L12", "F16", "D16"]

Stop must include your token, NTRs only token in the route is D16.

But yeah we should make it obvious which stops are payouts and do this more generically for all games.

**Comment by jenf** [comment]
"One of the counted revenue centers has a station token from the operating company."
