### ISSUE TITLE
[1822] Significant lag when E train route exceeds 18 stations

### ISSUE THREAD

**Issue by tommccorry** [tobymao/18xx#4383]
**What's your Game ID?**

https://18xx.games/game/31436

**How to Reproduce the Bug?**

When entering route for the LYR Express train, once I get above 18 stations on the route their is a significant lag between picking the next station. Web browse repeatedly asks to wait or cancel. Eventually station is added to route.

**Which Browser / Platform?**
- Chrome, Edge on PC Windows 10
- Chrome on IOS 14

**Comment by dfannius** [comment]
Same as #4346 and #4354?

**Comment by magnusfalt** [comment]
I guessing it is. We are working on a solution to optimize the route network tree. 1822's route network is massive with all the route possibilities a train can take.
