### ISSUE TITLE
1828 treasury shares incorrectly labeled IPO on spreadsheet

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4389]
The NKP reserved treasury share is listed in the spreadsheet as an IPO share.

<img width="342" alt="Screen Shot 2021-03-07 at 3 56 58 PM" src="https://user-images.githubusercontent.com/8732435/110260264-3eac4f80-7f60-11eb-8671-c57822b34226.png">

<img width="441" alt="Screen Shot 2021-03-07 at 3 56 53 PM" src="https://user-images.githubusercontent.com/8732435/110260267-40761300-7f60-11eb-828c-396c86194338.png">

**Comment by crericha** [comment]
Affects all games with reserved shares. Those shares probably shouldn't show up under IPO/Treasury.

**Comment by ChrisTheCat** [comment]
You might look at how 18CO represents corporations owning shares.
