### ISSUE TITLE
Reconfigure game tab in OR

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#439]
a)  revenue calculation 
 while clicking on the hexes and doublechecking the hex values in the train row there are many scrollings nessescary .
In the screenshot below there is a -30% zoom, that is close to the percentage when names & hex values become hard to read.   But the full map and the buttons and train income row  still dont fit on the whole screen.
Would it be possible to exchange the "blue circled" part, with company information against the "red circled" one?
![image](https://user-images.githubusercontent.com/64490299/82645059-93b9e780-9c12-11ea-951b-820039d8dac7.png)

**Comment by jenf** [comment]
I'd almost suggest that the corporation card should be before the action in general
