### ISSUE TITLE
Suggest the option to allow rolling back the previous action/s

### ISSUE THREAD

**Issue by Sabor117** [tobymao/18xx#4396]
Just to start off saying you're doing the Lord's work with this app and website. A group of friends and I tried out 1817 the other day and it worked super well and was largely very intuitive and easy to follow. Huge props for the amount of effort that's clearly gone into this already.

One issue we had though is that this was our first foray into an 18xx game, and also the first time on the site as well, and that meant a few mistakes were made throughout the course of an evening. Not mistakes in the sense of the long-term strategy but rather accidental mis-clicks and the like (such as one very painful example of someone on the verge of bankruptcy forgetting to run his trains and therefore getting kicked out of the game).

I'd like to propose the idea that the initiator/owner of the game be given the ability to rewind actions so as to account for this kind of mistake (in the same way that in an actual board game people might be given the opportunity to take back moves).

I've no idea how challenging this would be to implement, but I envisage it simply taking a step back in the log of events that have transpired. Obviously you could have the option to disable it for games with strangers.

**Comment by dfannius** [comment]
This is exactly what the Undo button is intended for (to the bottom right of the log window). Did you not notice it, or are you proposing some functionality that it doesn't provide yet?

**Comment by Sabor117** [comment]
Ah, we definitely did not notice it. The guy who was running the game mentioned after we'd finished that he would have liked that functionality and I just assumed that it wasn't present. That's a bit embarrassing.

Is this something that one has to opt in on when creating the game? Or is it always present?

**Comment by dfannius** [comment]
It's always present. I think you'll like it! I'm going to close this since I think everything you want is already there.
