### ISSUE TITLE
calculating routes for revenue while there was neither a tile  nor a token lay

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#440]
Because the "last run" revenue is known, it would be nice to have a button to simply agree that the "last run" value  could be taken again.  When the game comes close to an end it is often the case that there are no changes until the bank runs out of money and game is over

![image](https://user-images.githubusercontent.com/64490299/82646004-17c09f00-9c14-11ea-93c4-e9726542c79d.png)

**Comment by jenf** [comment]
dup of #283
