### ISSUE TITLE
[1830] ISR - Owner of M&H Private Not Given Option to Exchange - Auto Skipped by System

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#4403]
Playing live and noticed this.  Verified in a Hotseat game.  In the ISR the owner of the M&H in their turn can do the exchange for an NYC share even if they have no money.  They should not be auto-skipped.

Hot Seat Game Gist:
https://gist.github.com/rheretic/eaf157e343ccc174729b9b7c330c530c

Live Game Gist:  (I don't think player set AutoPass.)  Game 31478
https://gist.github.com/rheretic/06b61f03a13f21e6a901221a76066f88

**Comment by crericha** [comment]
1828 has code to support not skipping a player if they can exchange. See 1828 customizations of buy_sell_par_share and exchange steps.

**Comment by Maxwell-Frank** [comment]
Presumably if someone is working on this, they can also fix this for the Duogo in 1889?

**Comment by bentziaxl** [comment]
won't fix. Player can exchange on another player's turn. At this point it will break a lot of games, too much effort to fix
