### ISSUE TITLE
[1830/1889] M&H/Dougo owner is not prompted to exchange when there is only 1 share remaining

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#4408]
https://gist.github.com/rheretic/8fd54234e5281196d9e74c72ae3bc5b9

Ordinarily as a speed to play, only allowing the M&H owner to exchange during their Stock Turn is fine.  However, there are times when this is going to make a big difference.

As shown in the Gist, the owner of the M&H is not given the option to exchange for the 10th share before someone buys it.

When there is just one share available in the Pool, or in the IPO (and especially when there is only one share period), there is a chance that the M&H owner will want to do their exchange when it is not their turn.

I recommend watching for 1 Pool or 1 IPO share, and before the next player gets their Stock Turn the Owner should be queried about using the swap.  The answers can be "Yes", or "No, but keep asking me." or "No.  Don't ask me again."

_It's pretty unlikely that a person is going to say and intended Don't ask, and somehow the game state so radically alters itself that the person changes their mind.  If this is a big concern then don't allow the Don't and just keep asking them._

**Comment by rheretic** [comment]
@crericha

**Comment by rheretic** [comment]
1830 allows for "The exchange may be made during the player’s turn of a Stock Round or between the turns of other players or Railroads in either Stock or Operating Rounds."

**Comment by michaeljb** [comment]
While the M&H owner is not prompted, they can make the exchange even on another player's turn.

Here's an example where "michaeljb2"  made the exchange on "michaeljb"'s turn - https://18xx.games/game/32454?action=10

Abilities that belong to other players are hidden by default, so to do this the M&H owner must click "Show others", then "Mohawk & Hudson (michaeljb2)", then "NYC IPO share". BTW the active player can't use this button to force the exchange, only the M&H can do it

**Comment by rheretic** [comment]
There is a related Issue that is probably resolved / mitigated by this too.

I'll have to try this out, and then try to explain it to my group!  😱 

Would this work in a Hotseat game?

**Comment by michaeljb** [comment]
@rheretic yeah this works fine in hotseat, just have to start by clicking the "Show others" button.

I found the other issue, #4403. Looks like it's the same thing so I'll actually close this one as a duplicate issue.

**Comment by rheretic** [comment]
Both of these are related but not exactly the same.

Before you showed me how it worked I considered these to be genuine bugs.  It's really a knowing how it works.  But it's inobvious!

It might be useful to add verbiage to the M&H explaining how to use it when not specifically prompted to do so.

As described in the other Issue I think there is a game that avoids the auto-pass problem and that is probably pretty reasonable to implement.  Enhancing to solve this issue is probably a little more difficult.

Since the system is not prompting you, and you have to know before hand exactly how it works, I'd hate to be sitting in a game and have this come up and stymie the game!

**Comment by scottredracecar** [comment]
I suggest to add this information to the implementation notes please.
