### ISSUE TITLE
[1849:KTS] Token images corrupted

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#4417]
In our game, the tokens of BTR and TSR are not showing up correctly. 
https://18xx.games/game/31038

![image](https://user-images.githubusercontent.com/77583169/110553738-4d287180-80ee-11eb-99f9-7abdf543dc32.png)
![image](https://user-images.githubusercontent.com/77583169/110553785-63363200-80ee-11eb-8547-e25a2d5300ea.png)

**Comment by scottredracecar** [comment]
These are renamed and their token images were deleted. New games use the new names and tokens.
