### ISSUE TITLE
[18CZ] SR1 is missing on the spreadsheet of values

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#4420]
https://18xx.games/game/31219?action=271#spreadsheet

Technically it could be a different value from OR1.1 if a company was bought out, granted this usually does not happen.
![Screen Shot 2021-03-09 at 9 34 06 PM](https://user-images.githubusercontent.com/5924761/110581447-6990d200-811f-11eb-8a9c-ce01e1737519.png)

**Comment by yzemaze** [comment]
> Technically it could be a different value from OR1.1 if a company was bought out, granted this usually does not happen.

And that’s exactly why it doesn’t turn up in the table. Rounds are only rendered if at least one value differs to the previous round.
