### ISSUE TITLE
[18CZ] Cross-company train purchase was allowed during emergency financing, instead a forced loan

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#4421]
https://18xx.games/game/31219?action=256

OFE has just resolved emergency financing by purchasing a train for 1K from MW even though this is not allowed, and a loan should have been triggered. I pasted the relevant section of the rules below:

<img width="1105" alt="Screen Shot 2021-03-09 at 9 42 23 PM" src="https://user-images.githubusercontent.com/5924761/110581971-56cacd00-8120-11eb-97d2-c754fbdda0e3.png">

**Comment by Zwergenpunk** [comment]
No this is allowed. The player can always choose to buy from another corporation and not go into EMR. It would only not be possible if the corporation has exactly 0 money. In thst case only EMR from the depot/discard is possible.

**Comment by khamsoul** [comment]
Ok yeah reading the rules again I agree.
