### ISSUE TITLE
When there are multiple possible paths between two revenue centers, the routing does not handle it well

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#443]
The way the path to use is chosen is unclear, and can incorrectly prevent a valid route from being run.

This zip file includes two game JSON files and an mp4 video demonstrating the problem for each. - 
[routing examples.zip](https://github.com/tobymao/18xx/files/4669051/routing.examples.zip)

Try to run F9 - C4 - E2 - F1 / Kouchi - Ohzu - Matsuyama - Imabari for Iyo and Sanuki. In the SR case, clicking on the nodes in the "right" order gets the route, but IR seems unable to run the route at all.

![Screenshot from 2020-05-22 09-43-21](https://user-images.githubusercontent.com/1045173/82685018-c8c53a80-9c10-11ea-9a0c-e8283e29cc9f.png)

**Comment by tobymao** [comment]
you just need to click kouchi again to cycle the correct path

the fix would be to prune the illegal options

**Comment by michaeljb** [comment]
Relabeling to enhancement, the UI for this should be improved.

**Comment by michaeljb** [comment]
I think the route instructions under "Select routes" cover this now.
