### ISSUE TITLE
Firefox on mobile: route selection difficult due to "copy/select all" popup

### ISSUE THREAD

**Issue by BGarmon80** [tobymao/18xx#4430]
Since Chrome's freezing issues, I've been using Firefox on Android (Note 10+).

One annoying bug/feature is any time I click on a hex to establish a route, I'm given the "select all/copy" function and it highlights the token spot. This makes it difficult or impossible to click on other hexes and generally makes for a bad experience. 

Not sure if this can actually be fixed, but wanted to bring it up. 
![Screenshot_20210310-064656_Firefox](https://user-images.githubusercontent.com/77456523/110632357-24938c80-816d-11eb-9c76-f87b02a92f8e.jpg)

**Comment by Zwergenpunk** [comment]
Yeah I have that as well. I thought its only me since nobody ever reported it

**Comment by yzemaze** [comment]
Iirc there’s an option to suppress this popup. I’ll take a look.

**Comment by yzemaze** [comment]
Should be fixed after next deploy. Be sure to force reload your tab, so CSS gets updated.
If the problem should persist, comment here.
