### ISSUE TITLE
Entities list player order wrong 1822

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#4454]
This was originally stated as how it should be and our current game is not showing the player order correct with priority order. 
https://18xx.games/game/32273#entities

**Comment by magnusfalt** [comment]
https://18xx.games/game/32273?action=882#entities
-- New player order: edhew (£62), Avemo3 (£49), EZmacncheese (£3), Eludyan (£0)
Some privates income, why the cash is different in the image.
![882](https://user-images.githubusercontent.com/10232503/110947021-eac6af80-833f-11eb-88e6-bad0643e00e8.png)

https://18xx.games/game/32273?action=1086#entities
-- New player order: Eludyan (£65), Avemo3 (£58), edhew (£23), EZmacncheese (£12)
![1086](https://user-images.githubusercontent.com/10232503/110947116-092cab00-8340-11eb-8718-fba0f850ab40.png)

https://18xx.games/game/32273?action=1230#entities
New player order: Avemo3 (£937), edhew (£518), EZmacncheese (£248), Eludyan (£4)
![1230](https://user-images.githubusercontent.com/10232503/110947133-0e89f580-8340-11eb-9bb4-c43faa6f7334.png)


Theese was the last 3 stockrounds and the first action after it. I cant see what you mean that the order is wrong. If you point to a specific action in the game where its wrong.

**Comment by magnusfalt** [comment]
> The sequence is correct but it is showing me as first instead of EZ https://18xx.games/game/32273?action=139#entities
> […](#)
> Sent from my iPad
> On Mar 12, 2021, at 06:36, Magnus Fält ***@***.***> wrote: ﻿ https://18xx.games/game/32273?action=882#entities -- New player order: edhew (£62), Avemo3 (£49), EZmacncheese (£3), Eludyan (£0) Some privates income, why the cash is different in the image. https://18xx.games/game/32273?action=1086#entities -- New player order: Eludyan (£65), Avemo3 (£58), edhew (£23), EZmacncheese (£12) https://18xx.games/game/32273?action=1230#entities New player order: Avemo3 (£937), edhew (£518), EZmacncheese (£248), Eludyan (£4) Theese was the last 3 stockrounds and the first action after it. I cant see what you mean that the order is wrong. If you point to a specific action in the game where its wrong. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Very strange its correct for me.
-- New player order: EZmacncheese (£280), Avemo3 (£250), edhew (£245), Eludyan (£165)
![image](https://user-images.githubusercontent.com/10232503/110962686-83b1f680-8351-11eb-9c8c-21c068b2d87d.png)

**Comment by Eludyan** [comment]
I think it is putting the player first then in order from there. So adding a “priority” tag would make it clear who has first turn in priority order.
Since you are not playing, that isn’t adjusted for.

**Comment by Eludyan** [comment]
The sequencing added looks great!
Thank you for all you are doing to make this game, and others, fabulous!
Jen

**Comment by magnusfalt** [comment]
This change i cant take credit for, it was made for 18cz but it will show for 1822 as it is the same mechanics for determined the player order. I will close this then :)
