### ISSUE TITLE
[1860] Restarted companies remain insolvent 

### ISSUE THREAD

**Issue by mattroy** [tobymao/18xx#4455]
https://18xx.games/game/32281?action=409

**How to Reproduce the Bug?**

An insolvent company that goes bankrupt should no longer be insolvent after being restarted. 

In this case IWNJ could not lay H6 because it was invsolvent.

**Comment by roseundy** [comment]
Not true. Mike Hutton ruled that the insolvent condition stays with the the bankrupted company. Please see the FAQ.

**Comment by mattroy** [comment]
If the company remains insolvent then shouldn't it also remain insolvent during the round? In this game after the company doesn't lay track it suddenly became solvent despite not having a train

**Comment by roseundy** [comment]
That was also addressed by the designer - insolvency is checked before running routes. If the train has enough cash to buy a train, it is no longer insolvent.
