### ISSUE TITLE
1830 - Brown

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#4456]
Players are able to buy brown shares from market and IPO.

This should be at a bare minimum an optional rule to turn on/off at the creation of game,.

**Comment by dfannius** [comment]
I think the bare minimum is to document on the wiki which rules interpretation the site uses.

For reference, the relevant section in [Steve Thomas's 1830 rules clarifications document](http://www.18xx.net/1830/1830f.htm) is titled "'Brown' Stock".

**Comment by perwestling** [comment]
Bare minimum would be to do nothing....

When it comes to this issue it would also be interesting if a similar "problem" exists for "yellow" shares; can you buy IPO shares for a "yellow" company when you are at cert limit?

**Comment by Maxwell-Frank** [comment]
The Lookout rules that we have linked as the official rulebook allow purchasing multiple brown shares only from the bank pool.  I think it would be a poor decision for the only available implementation to directly disagree with the linked rules.

**Comment by tobymao** [comment]
we've been matching the DOS version so far. looks like DOS matches lookout games, which is you can only buy from the bank pool? if so we should fix it

**Comment by Maxwell-Frank** [comment]
People clearly have strong opinions on this matter, so I believe both options should be implemented. I'll let you all argue over which should be the default ;)

**Comment by steve-yu** [comment]
There's no ambiguity with the latest set of published rules where you can only buy from the bank pool.  I used to love playing Axis and Allies Revised edition, but it doesn't mean that as new versions come out with new rules or errata, I demand that we only play on the ruleset I happen to like.

**Comment by tobymao** [comment]
totally agree @steve-yu

**Comment by dfannius** [comment]
Yep, the Lookout rules don't interpret the Avalon Hill wording the way that I would have, but they are explicit, and they are the rules we link to.

**Comment by perwestling** [comment]
I do not know who feels strongly about this; after all it is a pretty rare thing. 
And has has been mentioned, the big difference in price between IPO and market price makes it unlikely that it will have that big an impact on any game.

Now, as I mentioned before, I do believe the situation is similar for Yellow (and Orange) - if I interpret it correctly you should not be allowed to buy IPO shares of a company in yellow if you are on cert limit (total and/or corporation).

So I believe we need to have a consistent behavior for all colors, and not just brown, when it comes to market/IPO handling.

We should also check that the color used in the charter does not show on IPO - as I recall, it don't, but it could be worth double checking.

And finally - yes, it is good if the rule set we link to is the one we use. I know there are other titles that break this (e.g. 18GA) but that need to be handled on a case by case. (18GA: The implementation is somewhere between the two official versions that exists. Designer has suggested some changes to make it more similar to the latest official version but there is still some differences. These differences should be noted on the wiki page - they might be implementation choices, but they should be listed.)

**Comment by dfannius** [comment]
> I do not know who feels strongly about this; after all it is a pretty rare thing.
> And has has been mentioned, the big difference in price between IPO and market price makes it unlikely that it will have that big an impact on any game.

There's a really vigorous discussion on the 1830 tournament Discord and some people there seem to think it makes a big difference. I don't know if they're exaggerating but they certainly have more 1830 experience than me.

> Now, as I mentioned before, I do believe the situation is similar for Yellow (and Orange) - if I interpret it correctly you should not be allowed to buy IPO shares of a company in yellow if you are on cert limit (total and/or corporation).

I don't think so:

- The Lookout rules, which we link to and at least have the benefit of being explicit about these things, do not disallow it (but explicitly disallow buying multiple brown shares from the IPO).
- The Avalon Hill rules, whose confusing wording about brown shares led to the Lookout interpretation of brown shares (which I personally think is a weird interpretation, but that's not important), are much less open to interpretation for yellow and orange, and the Steve Thomas clarifications document doesn't even mention the possibility of interpreting them other than by the Lookout (and current 18xx.games) rules.

**Comment by ArielAyanna** [comment]
I strongly disagree with the proposed approach. Linking to a flawed rule set should not then necessitate a flawed implementation of the game (not saying one rule or the other is correct,  just speakig generally). With the current implementation,  players can play either way.  If this changes, playing so that you can't buy from ipo will be mandatory.  Personally,  i do think it matters and i do think permissive version is better,  since it leads to additional strategic space within the game.

**Comment by jenf** [comment]
Note for the implementer, not matter approach taken. 1882 requires the opposite interpretation of the rules as written by Lookout for 1830

**Comment by perwestling** [comment]
Personally I do not think which rules used matter much, as we would adapt our play to whatever rules are used...

I do find it strange that brown and yellow shares are handled differently, though.
The Avalon Hill rules talk about "Certificates whose value has descended into the yellow zone" and "Stock valued in the brown zone". If IPO is not "stock valued in the brown zone" then it surely cannot be a certificate whose "value has descended into the yellow zone" either, can it?

I do not think the 2018 version from Lookout is 100% clear about how to handle IPO share buying. For brown shares it does specify that all shares bought from market are counted as ONE buy, but I am not convinced that that was intended to explicitly forbid buying one share from IPO at the same time.

Anyway, this shows how difficult it is to write clearcut rules. 

So I suggest to link to one set of rules, and then adhere to the common interpretation of these rules (whatever that may be) and then put in a passus on the wiki page under "Rules Clarification" about how 18xx.games handles this.

I do not see the need to make optional rules implementation for this.

**Comment by dfannius** [comment]
Many people on various Slacks and Discords have expressed extreme displeasure with having the site only use the Lookout rule with no option to disable it, and Toby has said on Slack that he's fine with an option, so I'm pretty convinced that that's what we should do. And if there is an option. all the devs seem to agree that the default should be the Lookout rule.
