### ISSUE TITLE
18GA: Corrections based on designer feedback

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#4457]
Have gotten these three points of feedback from the designer of 18GA:

"1. Change the $40 build costs in hexes E3, F2, H2 and I3 to $20 to make it equal to the version 2 map.

2. I noticed that the Waycross hex is not shown with the W&S private company. I seem to recall that this is due to the W&S private not blocking tile laying in the Waycross hex just as the Lexington Terminal private company is not shown on the map.

3. I agree that it might be easier to leave off the two hexes added near Savannah because that variant also placed one of the Georgia RRs tokens in the new offboard Charleston hex and that would require new coding to show it has one less token due to it being pre-printed on the map."

There were also a 4th point, about variants for 18GA, but I have added that to the 18GA variant issue.

It seems the 18xx.games version is a hybrid between release 1 and release 2. The above corrections will make the game come closer to version 2. 

Also, the rule link (to version 1) might be broken. The version 2 rules is available on DeepThought Games web page, and could possibly be used instead of version 1 if that no longer is available.

**Comment by perwestling** [comment]
If someone picks this up, do not hesitate to contact me for further information.

**Comment by ryandriskel** [comment]
For item 2, is this just showing an icon on that hex for that private?

For item 3, I'm a bit confused as to the needed changes as the response is a bit rambly.
