### ISSUE TITLE
1822 - Cannot simultaneously use P2 + P10 for a single track lay

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#4469]
https://18xx.games/game/32376

When a major or a minor has multiple private companies it appears that it is impossible to use more than one power at a time.

Specifically this is going to come up frequently with privates P2 + P10.

I have encountered it in an earlier game today.

**Comment by magnusfalt** [comment]
There is a limitation with the current implemenation, and it would require quite a big rewite to be able to use two powers at once. 1822 is the first game where this have been encountered. Will keep this issue, if it comes up for discussion to change it.

**Comment by DrPooter** [comment]
Thanks!

**Comment by michaeljb** [comment]
Some thoughts on what will need to be changed in order to fix this

* when a tile lay action is done with a private company's power, the action's entity is the private company - https://github.com/tobymao/18xx/blob/master/lib/engine/action/lay_tile.rb -- perhaps it could be changed so the entity is the owning corporation, and a new field could refer to the company abilities used? There are still cases such as Mitsubishi Ferry in 1889 where it still makes sense for the entity to be the private company
* in the UI, abilities are activated using the `selected_company` value in the store, this will probably need to be changed to an array of companies - https://github.com/tobymao/18xx/blob/master/assets/app/view/game/abilities.rb
* may need to identify on an ability definition that it can be combined with other specific abilities--probably point to the other company's `sym` and the other ability's `type`

**Comment by arcee1986** [comment]
Wondering if this would work as a workaround: change P2 to bulldoze a town on a tile placed this turn.  So the sequence would be use the other private first, then use P2 to replace the new tile with a townless one.  This isn't 100% identical (for example, the town tile that you temporarily place might be exhausted) but I think it would cover many cases.

**Comment by michaeljb** [comment]
https://boardgamegeek.com/thread/2661644/article/37745481#37745481

> “Eludyan: LimeTurtle — Are you around still?
> There is some debate about combining privates in ‘22 since the rules explicitly state that P2 and P11 can be used together, people think that it is then disallowed for others since it is not explicitly allowed...
>
> LimeTurtle: Hi, the combining of P2 and P11 was intended as an example.
>Not as the only exception to a rule.
> Other privates could be combined. Eg terrain discounts with dit dozer
> Do you have a specific example?
> Do I need another errata?
>
> Eludyan: I think an errata would help people
> I totally get it.. and have been playing that way all along
>
> LimeTurtle: Its a school night and my bed time, so you will have to make do with that conceptual answer for now.
>
>Eludyan: Some say that you cannot use adv tile lay, extra tile lay, and dot killer together
> I am totally fine with that answer it is how I have always played
>
> LimeTurtle: They would be wrong.

https://boardgamegeek.com/thread/2661644/article/37770276#37770276

> Just to confirm, there is no specific restriction on using multiple privates to lay track. If they can work together then it is permitted. Are there any instances where they can't work together? I con't think of any, and as noted above, I'm not going to peer at the rulebook to refresh my memory.

I've been thinking about an approach where each combination of company abilities is represented as a new ability that appears when the relevant companies are owned. Here are the relevant privates and their combos across the 1822 family:

### 1822

* P2 - Remove A Town - lays/upgrades tile to next color, removes town; single-town hexes only
* P8 - Mountain/Hill Discount - token to pay for one rough/hill/mountain hex
* P10 - River/Estuary Discount - two discount tokens to pay for crossing an estuary, can be used on same or different lays; also, discount of $10 on other river costs
* P11 - Advanced Tile Lay - lay a non-city tile of the next available color
* P12 - Extra Tile Lay - 1/2 extra yellow tile lay(s) for Minor/Major

In Phase 2, Minor 19 could lay a yellow to the SW of Cardiff and then use all 5 privates to lay (P12) a plain green tile (P11), removing Newport (P2), for free pointing at Bristol (P8+P10). Therefore all 26 combinations of 2 or more of these 5 are valid. (2^5=32 combinations, minus the 6 combinations that are 0 companies or just 1 of the 5)

This many combos for one title seems like it may be impractical, the others aren't so bad without the P8 or P10 equivalents.

### 1822MX

* P8 - Advanced Non-City Tile Lay
* P9 - Extra Tile Lay - Major gets 1/2 extra yellow(s) in phase 2/3+
* P12/P13 - Remove Town

#### Combos

* P8+P9
* P8+P12
* P8+P13
* P8+P9+P12
* P8+P9+P13
* P9+12
* P9+P13

### 1822PNW

* P7, P8 - Removes Town
* P11 - Extra Tile Lay - Major gets 1/2 extra yellow(s) in phase 2/3+

#### Combos

* P7+P11
* P8+P11

### 1822CA 

> Some private company abilities are used in place of a company’s normal track-laying step (P12, P19-20, P29-30). Others are used in addition to the normal track laying step (P14-18, P21). One or more of the second group’s abilities may be used in conjunction with a private ability from the first group.

* in place of normal track laying step:
    * P12 - Advanced Non-City Tile Lay
    * P19 - Crowsnest Pass - free CP tile, uses full track laying step
    * P20 - Yellowhead Pass - free YP tile, uses full track laying step
    * P29/P30 - Remove Single Town
* in addition to normal track laying step:
    * P14-P18 - free Toronto/Ottawa/Montreal/Quebec/Winnipeg upgrades, with connection
    * P21 - 3-Tile Grant - 3 extra yellows, Major only; exempt from terrain fees; cannot build in $120 mountains or M,O,Q,T,W

#### Combos

* P12+P19
* P12+P20
* P12+P29
* P12+P30
