### ISSUE TITLE
Discord/Slack for dev contributions?

### ISSUE THREAD

**Issue by Breich90** [tobymao/18xx#447]
Bored and unemployed full-stack dev/18xx enthusiast here--would love to help extend the code for other games.  Is there a server discord/slack to talk about the code?  Would love to extend for 1830 or a host of any other 18xx's out there.  1849 would be a good one since I believe it is open source.

**Comment by dfannius** [comment]
We mostly talk on the 18xx Slack (see https://boardgamegeek.com/thread/1811150/18xx-slack) in the #18xxgamesdev channel.

**Comment by tobymao** [comment]
https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ

channel 18xxgames

we don’t have permission for 1830 yet
