### ISSUE TITLE
[1822] Pullman connects to E train

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4475]
Due to rule 5.5.6 a pullman may not be connected to an E-train, but it's possible at the moment.

game: 1822
https://18xx.games/game/31915

**Comment by michaeljb** [comment]
I found another instance https://18xx.games/game/32193?action=1228

Here's another from #4479 - https://18xx.games/game/32426?action=1100

**Comment by magnusfalt** [comment]
This issue was solved with #4460 and just waiting to be deployed to live :)
