### ISSUE TITLE
[1822] Movement of Share Prices in a Stock Round

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4477]
rule 4.11.1 says, that a company's share price raises if it's 100% in players hands. 

Share price at the top of the chart should move diagonally one space down to the right.

This didn't occured in our game after SR10

https://18xx.games/game/31915

**Comment by michaeljb** [comment]
This impacted SECR, GWR, and SWR at https://18xx.games/game/31915?action=1432

**Comment by magnusfalt** [comment]
Thank you for the rigid testing, but this issue have just been solved and merge with #4459 . Just waiting for the code to hit live :)
