### ISSUE TITLE
18Ches passing on Baltimore & Ohio Railroad errors

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#448]
Error: "undefined method 'president' for nil:NilClass"

{
  "id": 1090,
  "description": "Sunday on the Chesapeake",
  "user": {
    "id": 972,
    "name": "Excalabur"
  },
  "players": [
    {
      "id": 973,
      "name": "worgl"
    },
    {
      "id": 197,
      "name": "adam"
    },
    {
      "id": 972,
      "name": "Excalabur"
    }
  ],
  "max_players": 4,
  "title": "18Chesapeake",
  "settings": {
    "seed": 9.174285096030202e+37
  },
  "status": "active",
  "turn": 1,
  "round": "Auction Round",
  "acting": [
    197
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 1,
      "company": "Chesapeake and Ohio Canal",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 2,
      "company": "Baltimore & Ohio Railroad",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "Excalabur",
      "entity_type": "player",
      "id": 3,
      "company": "Columbia - Philadelphia Railroad",
      "price": 45
    },
    {
      "id": 4,
      "type": "bid",
      "price": 55,
      "entity": "worgl",
      "company": "Baltimore and Susquehanna Railroad",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "undo",
      "entity": "adam",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "bid",
      "price": 55,
      "entity": "worgl",
      "company": "Baltimore and Susquehanna Railroad",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "undo",
      "entity": "adam",
      "entity_type": "player"
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 8,
      "company": "Baltimore & Ohio Railroad",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 9,
      "company": "Columbia - Philadelphia Railroad",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Excalabur",
      "entity_type": "player",
      "id": 10,
      "company": "Chesapeake and Ohio Canal",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 11,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 12,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Excalabur",
      "entity_type": "player",
      "id": 13,
      "company": "Delaware and Raritan Canal",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Excalabur",
      "entity_type": "player",
      "id": 14,
      "company": "Columbia - Philadelphia Railroad",
      "price": 55
    },
    {
      "id": 15,
      "type": "bid",
      "price": 60,
      "entity": "adam",
      "company": "Columbia - Philadelphia Railroad",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "undo",
      "entity": "Excalabur",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "adam",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 18,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 19,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 20,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 75
    },
    {
      "type": "pass",
      "entity": "adam",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 22,
      "company": "Chesapeake and Ohio Canal",
      "price": 95
    },
    {
      "type": "bid",
      "entity": "Excalabur",
      "entity_type": "player",
      "id": 23,
      "company": "Chesapeake and Ohio Canal",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 24,
      "company": "Chesapeake and Ohio Canal",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "Excalabur",
      "entity_type": "player",
      "id": 25,
      "company": "Chesapeake and Ohio Canal",
      "price": 110
    },
    {
      "type": "pass",
      "entity": "worgl",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 27,
      "company": "Baltimore & Ohio Railroad",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 28,
      "company": "Baltimore & Ohio Railroad",
      "price": 120
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 29,
      "company": "Baltimore & Ohio Railroad",
      "price": 125
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 30,
      "company": "Baltimore & Ohio Railroad",
      "price": 130
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 31,
      "company": "Baltimore & Ohio Railroad",
      "price": 135
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 32,
      "company": "Baltimore & Ohio Railroad",
      "price": 140
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 33,
      "company": "Baltimore & Ohio Railroad",
      "price": 145
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 34,
      "company": "Baltimore & Ohio Railroad",
      "price": 150
    },
    {
      "type": "bid",
      "entity": "adam",
      "entity_type": "player",
      "id": 35,
      "company": "Baltimore & Ohio Railroad",
      "price": 155
    },
    {
      "type": "bid",
      "entity": "worgl",
      "entity_type": "player",
      "id": 36,
      "company": "Baltimore & Ohio Railroad",
      "price": 160
    },
    {
      "id": 37,
      "type": "bid",
      "price": 165,
      "entity": "adam",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 38,
      "type": "undo",
      "entity": "worgl",
      "entity_type": "player"
    },
    {
      "id": 39,
      "type": "bid",
      "price": 165,
      "entity": "adam",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 40,
      "type": "undo",
      "entity": "worgl",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "adam",
      "entity_type": "player",
      "id": 41
    }
  ],
  "created_at": "2020-05-22",
  "updated_at": "2020-05-22"
}

**Comment by tobymao** [comment]
i don't see any error? closing because it seems to work

**Comment by TheExcalabur** [comment]
I am also a player in the game, and it still throws the error at the top of the game log (Error: "undefined method 'president' for nil:NilClass") after the B&O private is bought and then refuses to continue while synced.
