### ISSUE TITLE
auto-skip [1817] - cannot enable on your turn if a short was taken last

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#4480]
**game**: https://18xx.games/game/23680?action=2426
**repro**: When an opponent has shorted a company since your last turn, attempt to enable auto-skip during your turn. The message stating it's enabled will immediately be followed by a message stating it's been disabled due to action "short bought".
**browser/platform**: Chromium 88.0.4324.182, Desktop (Linux)

![auto-skip-bug](https://user-images.githubusercontent.com/332270/111033558-d803b780-83df-11eb-9024-b77e234adf44.png)

**Comment by jenf** [comment]
dup of #4427
