### ISSUE TITLE
1822 offered illegal merger

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4489]
https://18xx.games/game/31523?action=331

Says M24 can merge with LBSC but that is incorrect. They are not connected by track. 

![DECCC2AE-168D-47B0-967B-920C4130F6E3](https://user-images.githubusercontent.com/8732435/111041631-fd97bd80-83ed-11eb-92bc-14b8634711c3.png)

**Comment by magnusfalt** [comment]
The reason for showing all minors is a technical one. Trying to find the routes to every minor, in phase 5 this can be plenty of the is very time consuming. Trying to traverse the map for all minors when trying to access which to show isnt an option. So we made it if you try to merge you will get an error that there isnt an route to the minor.

Gonna keep this issue if we find a better solution to the map traversing, we are working a few angles here.

**Comment by magnusfalt** [comment]
The text is as you say is incorrect though, this can change to might merge of something.

**Comment by jenf** [comment]
@magnusfalt 1861/67 restricts merges to corps that can connect, probably worth looking at how it does it.
It uses an auto-action to fake a pass when there's not merge candidates.
It's done on the client so we can mostly ignore the performance problem.

**Comment by rclyne** [comment]
Perhaps change the text to say something like "Minors in the game" until it is fixed?
