### ISSUE TITLE
18Mag - significant slowdown-unresponsive

### ISSUE THREAD

**Issue by Panzerlied7** [tobymao/18xx#4493]
Game Id: 32528

Started a 5 player game (Live) at 1pm and everything was fine. 
Between 4:30 and 5pm - just as we were getting to the OR prior to the final SR and the final 3 ORs - the system became slow and unresponsive for 5 of us. We are distributed in ME, NH and MA using various browsers and systems including a MSFT Surface (who knew). As the time progresses from 5 to 6pm the responsiveness declined even more and we could no longer really play the game and I ended it after 20 minutes for the last minor to run and then running thru the majors was relatively responsive. 

On my system I would get dozens of "the server is unresponsive - do you want to wait or exit the page" messages. 

JimA

**Comment by Panzerlied7** [comment]
As an additional comment on this game - so after several off line I went in to review the game and it took over 20 seconds to load and I had one 'wait' option for the server notice. I then tried several other of my finished games and none took over 3 seconds to load. I then tried again with the 32528 game and again it took over 20 seconds and a 'wait' message before loading.

**Comment by roseundy** [comment]
Thanks for the bug report. Any of our games with largish maps and and a lot of track are subject to the issue. We are working on it.

**Comment by tobymao** [comment]
fixed
