### ISSUE TITLE
auto-action: buy until it floats

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#4496]
Actual I am able to buy shares until I have a given amount of shares.

When I start a new company, I normally buy shares until the company floats. The number of shares I need depends on the other players.

In the past all auto-buys were managed via message and master-mode. We normally hat two messages: „done until someone sells“ (which is implemented as auto-action) and „buy ... until it floats“ (which I miss as an auto-function).

**Comment by Zwergenpunk** [comment]
The option is already there. It was the first Auto Action

**Comment by jenf** [comment]
already implemented
