### ISSUE TITLE
Auction phase - cannot bid on Duogo Railway

### ISSUE THREAD

**Issue by rthomp9595** [tobymao/18xx#45]
3 companies have been already bought, leaving two in a 2p game. I can place a bid on the first company but not being allowed by game to bid on the Duogo Railway at the moment. ID 59 game

**Comment by tobymao** [comment]
interesting. please leave it there for me, i'll look at it tonight

**Comment by tobymao** [comment]
sorry, this is not a bug, you have an active auction with sumitomo, you need to resolve that first

**Comment by rthomp9595** [comment]
Sorry to bother you. Yes, my mistake.
Thanks Tony - this is really cool what you’ve designed.
Rob

**Comment by rthomp9595** [comment]
Thanks Toby. Pardon the spell-correct typo!!
Rob
