### ISSUE TITLE
[1846] Game Broken Due to Earlier Bankruptcy

### ISSUE THREAD

**Issue by Fellstone** [tobymao/18xx#4516]
<https://18xx.games/game/30436?action=682>

Game broken due to earlier bankruptcy that is now considered to have happened erroneously. Game requested that we fill out a bug report due to the following:

GameError: Cannot go bankrupt. ERIE's cash plus Yallweh's cash and sellable shares total $891, and the cheapest train in the Depot costs $800.
Broken action: { "type": "bankrupt", "entity": "ERIE", "entity_type": "corporation", "id": 683, "created_at": 1615724625 }

Seems like it might be related to [1846, bug fix] prevent illegal bankruptcy--fix total_emr_buying_power calculation #4509

Not sure if game 30436 is salvageable. Just reporting the issue here because of the prompt at the top of the game page.

**Comment by michaeljb** [comment]
will pin this game, should be playable again in a few minutes

**Comment by michaeljb** [comment]
@Fellstone your game is back online. Thanks for reporting!

FYI, here's what broke it: https://18xx.games/game/30436?action=680 - by the rules, Yallweh should have been forced to have ERIE emergency issue 4 shares, then they'd have to sell their NYC share, which would have then given enough money to buy the grey train and stay alive, so bankruptcy should not have been an option.

**Comment by Fellstone** [comment]
Much obliged. Thank you!
