### ISSUE TITLE
[1822] Move Card Private is Broken or Needs a UX Overhaul

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4522]
https://18xx.games/game/32904?action=1176

The NER owns the "Move Card" private, but we were unable to make it work. Numerous players tried in game, and in cloned hotseat games, and we were unable to figure out when/where to click to move a card.  

Either it's broken or it needs to be easier to use.

**Comment by magnusfalt** [comment]
Ive made so you only can use the LUR ability during the issue/redeem step. This is the last step before you enter any stock round where it matters which the order the stack is. So i thought it was the most logical step to have it.

Ive made so it will show it self during the track lay and token step as well now.
