### ISSUE TITLE
18Ches - Cornelius Vanderbilt does not close

### ISSUE THREAD

**Issue by Dimikosta** [tobymao/18xx#453]
In 18Chesapeake the Cornelius Vanderbilt private does not close after the associated company buys its first train.

Attached is the game data from a hotseat game.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Columbia - Philadelphia Railroad",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "Columbia - Philadelphia Railroad",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "Chesapeake and Ohio Canal",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Chesapeake and Ohio Canal",
      "price": 90
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "Baltimore & Ohio Railroad",
      "price": 105
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "company": "Delaware and Raritan Canal",
      "price": 15
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "company": "Columbia - Philadelphia Railroad",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "company": "Columbia - Philadelphia Railroad",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "company": "Chesapeake and Ohio Canal",
      "price": 95
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16,
      "company": "Cornelius Vanderbilt",
      "price": 200
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 17,
      "corporation": "LV",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 18,
      "corporation": "C&A",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 19,
      "corporation": "SRR",
      "share_price": "70,4,2"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 20,
      "share": "LV_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 21,
      "share": "C&A_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 22,
      "share": "SRR_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 23,
      "share": "LV_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 24,
      "share": "C&A_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25,
      "share": "SRR_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 26,
      "share": "LV_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 27,
      "share": "C&A_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 28,
      "share": "SRR_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 29,
      "share": "LV_4"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 30,
      "share": "C&A_4"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 31,
      "share": "SRR_4"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 33
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 35,
      "hex": "J2",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 36,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 38
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 39,
      "hex": "J6",
      "tile": "57-1",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 40,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 41,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 42
    },
    {
      "type": "lay_tile",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 43,
      "hex": "H4",
      "tile": "57-2",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 44,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 45
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 47
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 48
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18Chesapeake",
  "description": "",
  "max_players": "6",
  "id": "hs_1590172722",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-05-22",
  "result": {}
}

**Comment by gchambers419** [comment]
This may be a moot point once the above is fixed, but the game offers to let the player buy Vanderbilt despite game text forbidding it.
