### ISSUE TITLE
[1822] P10 doesn't reduce track laying cost, when used with 2nd tile lay action

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4533]
game ID: 30135

https://18xx.games/game/30135?action=831

P10 does reduce the track laying cost of river terrain by 10 bucks. P12 allows the owning company to lay a second tile in it's operating turn. Minor #24 owns both privates, but can't use them together. P10 does not provide the discount if used as a second tile.

**Comment by magnusfalt** [comment]
As it is now you cant use to powers during the same tile lay. But i have made so you can use the extra tile lay when even during your tile lay. Lay normal tile, use extra tile lay, use P10 on third normal tile lay and the use the last extra on the fourth. This will help a little bit. There is an issue where we will keep track if we can change to be able to use 2 powers at once #4469.

But there is a bug though in that game like you said, you should be given £10 in discount when upgrading Birmingham. This i will take a look at.
