### ISSUE TITLE
[18CZ] Game offers upgrading to rusted trains

### ISSUE THREAD

**Issue by crumpetsfortea** [tobymao/18xx#4535]
Currently, when a Large company aquires a Medium company, the game offers to upgrade Blue trains to Green trains even when the corresponding Green trains have already been hit by a rusting event.

See the following example:
https://18xx.games/game/31629?action=723

**Comment by Zwergenpunk** [comment]
Funny thing is, when I woke up today I thought of this exact problem. 
Thanks for reporting it. Should be an easy fix.
