### ISSUE TITLE
[1870] Track Able to be Laid Across the Mississippi before the Bridge is bought in

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4539]
https://18xx.games/game/33003?action=194

The Frisco was able to lay H17 across the Mississippi before the Bridge private was bought in.

**Comment by benjaminxscott** [comment]
just to note that you'll want to undo that action, if you want to continue the game after this is patched
(otherwise it'll break, and we don't pin alpha games)

[saved off json](https://gist.github.com/benjaminxscott/37b07752b0f82b006f0f5c26fc32d690)

**Comment by Maxwell-Frank** [comment]
We're done with the game, so if it dies, it dies!
