### ISSUE TITLE
1870 bugs - destination run $ with shares in IPO

### ISSUE THREAD

**Issue by PeteC66** [tobymao/18xx#4549]
Two bugs in 1870.
1. Baton Rouge should be an $80 river, not $40.
2. When I ran FW on its destination run with 20% in the IPO, the RR did not get the $54 it should have.
Also, it is Fort Worth, not "Fortsworth".

https://18xx.games/game/33060

**Comment by ChrisTheCat** [comment]
https://18xx.games/game/33060?action=686

**Comment by michaeljb** [comment]
terrain cost was fixed in #4546
