### ISSUE TITLE
[1870] Mississippi River Bridge Company Bought in OR1, not shown under company

### ISSUE THREAD

**Issue by OzLocutus** [tobymao/18xx#4554]
Game https://18xx.games/game/33080

I am running MP. As per rules, I buy the Mississippi River Bridge Company in OR1.1 for $40.

compare https://18xx.games/game/33080?action=55 and https://18xx.games/game/33080?action=56

When MP buys the company, the company is there. Once it lays it's home tile, the private appears to close. Pretty sure the company does not close under any circumstances until the first 5 train is bought. 

Note I also bought Great River Shipping Company in the Same OR, since I bought 2 three trains.

![Bug MP Buying Bridge Company](https://user-images.githubusercontent.com/69135822/111441392-64ed9e80-875b-11eb-8b23-bdb2de64ab5c.JPG)

**Comment by OzLocutus** [comment]
Is this one resolved?

**Comment by michaeljb** [comment]
Fixed by #4557
