### ISSUE TITLE
[1822] Company 23 can not submit a valid revenue

### ISSUE THREAD

**Issue by neutronc** [tobymao/18xx#4564]
https://18xx.games/game/31242

No Valid single Location Route can be selected. The L should be able to create a 1 Stop route (just its home token) and be able to submit the value of the single location as valid revenue.

**Comment by neutronc** [comment]
And in the next minute i was able to do so after trying 15 minutes fruitless...

**Comment by magnusfalt** [comment]
We reverted some code that was breaking a few games.
