### ISSUE TITLE
[18CZ] Player allowed to buy shares before paying off loan

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#4568]
https://gist.github.com/vints1/8e39c40727aa96aa3b9099492a119b72

https://18xx.games/game/30454

The current player was able to par a new company without first paying off their loan.  

See rules page 19:

No  player  who  is  in  debt  may  buy  shares  in  a  subsequent  Stock  Round  unless  the  debt  (but  not  the penalty interest charge) has been paid off in full.  Payment may be made at any time during a Stock Round, and payment  of the entire debt is required if the player wants to buy more shares

**Comment by Zwergenpunk** [comment]
Woopsie. Buy shares from market or IPO is forbidden, but paring was allowed.  -> The player who pared the corporation would can not float the corporation. 

Thanks for reporting.
