### ISSUE TITLE
[1822 MRS] Train removed even when no minor company left

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4569]
In our game of 1822 MRS (I expect to have the same issue for 1822 as well) we bought the last minor company from the bid box. Since there was the minor from the first bid box sold, I expected not to get a train removed at the end of the stock round. But we got the message, there is no minor company left, thus a train will be removed. I assume it's a bug (rules: 4.10.3)

https://18xx.games/game/33178?action=733

**Comment by magnusfalt** [comment]
No it was a deliberate decision to make it so. I was interpreted the rule as if no bid on bid box 1 a train will export. But after reading the rule again it explicit says minor company.
`Then, if the minor company in bid box
1 is unsold at the end of the stock round it is removed from play, together with the next available train from the bank (not
the bank pool – any trains in the bank pool are ignored).`

**Comment by Ticketautomat1** [comment]
I assume I wasn't clear enough. I did not buy the last minor from the bid box directly, I bid on it while the stock round (and thus I bought it) so I was surprised that a train was removed though.

**Comment by magnusfaltinbooks** [comment]
Ahh ok, its a bug then :)
