### ISSUE TITLE
[1822] visible tax haven shares

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4570]
If there is a share bought for the tax haven, it's not visible at the moment. I suggest to make a notice in the company sheet, like if a player would own it. I'm always confused, when there only 9 shares exist.

**Comment by magnusfalt** [comment]
As it is now you can see which share the Tax haven have bought by looking at the company in the player who owns it.

![image](https://user-images.githubusercontent.com/10232503/111591189-65bc1a00-87c7-11eb-94fa-ceb18a0f674b.png)

But yes we could improve th ui for this.
