### ISSUE TITLE
18Chesapeake: Can't change train prices when buying between companies

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#458]
In OR 1.1, B&O operated first, bought (3) 2T; later in the OR, SRR wanted to buy a 2T from B&O, could only do so at market price.

**Comment by tobymao** [comment]
can you post your game json in here so i can repro this?

**Comment by tobymao** [comment]
closing for now, reopen if you can send me the game data where this happens

**Comment by wcraigtrader** [comment]
That was a me not understanding the UI problem, sorry.
