### ISSUE TITLE
1822MRS: Train exported even though bid box 1 minor had a bid

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#4580]
Issue encountered in 1822MRS game 33178: https://18xx.games/game/33178

There was one minor left in the game in stock round 7 as others had been either run earlier in the game or acquired direct from the bid boxes during the previous operating rounds. A player bid on this minor. Although they had a bid, we still got the message "No minor in first bidbox and with this no bids, a 7 train is removed" at the end of the stock round and a train was exported. This is the final action before this message: https://18xx.games/game/33178?action=732

(The minor bid seemed to be resolved correctly and the minor went on to operate as usual, however the extra train should not have been exported as I understand the rules as the minor 12 Eastern Union Railway was in bid box 1 and did receive a bid. The statement that there was no minor in the first bid box was only true once all the bids were already resolved.)

**Comment by magnusfalt** [comment]
Thank you for testing, there is already an issue about this from the same game #4569. Closing this as a duplictate.
