### ISSUE TITLE
1828.games unable to lay tile

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4592]
https://18xx.games/game/33221?action=460

The GT should be allowed to upgrade a tile, but is only offered the opportunity to lay a yellow tile. I don't see anything in the rules to indicate that both tiles must be yellow if the E&K special power is used.

**Comment by michaeljb** [comment]
Looks pretty clear to me--from page 21 of https://kanga.nu/~claw/1828/1828-Rules.pdf

![Screenshot 2021-03-18 222954](https://user-images.githubusercontent.com/1045173/111731647-84f38f80-8839-11eb-81a0-f5150358c1ce.png)

**Comment by ChrisTheCat** [comment]
Whoops
