### ISSUE TITLE
Game showing my turn on front page when it wasn't during 1830 auction

### ISSUE THREAD

**Issue by StormCrow42** [tobymao/18xx#4595]
While playing https://18xx.games/game/30570, 2 times now the front page showed it to be my action (and I believe I got email pings), but then when I entered the game it wasn't my action.  Both occurrences were during the initial auction, where the bidding was for a private that I was involved in resolving, but not the lowest bidder.  There were no undos in the log to provide a possible explaination.

**Comment by StormCrow42** [comment]
looking back at the log, it looks like the front page thinks priority is just being passed clockwise among the bidders rather than in the proper lowest bidder order.  In both occurrences the previous actor was the player just before me in priority, but the lowest bidder was later in priority than me.

**Comment by tobymao** [comment]
closing now as not reproducible
