### ISSUE TITLE
Set aside money in private bids

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#460]
Money bid for privates should be set aside and not made available until that private's auction is resolved. Right now a player can bid up to their entire current bankroll even if they have outstanding bids on other privates. This can also lead to stuck states where, for example, a player has placed the only bid on P6, and wins P5 with a gigantic bid that doesn't leave enough money for P6 to resolve.

**Comment by sparr** [comment]
https://github.com/tobymao/18xx/blob/master/assets/app/view/auction_round.rb#L60
https://github.com/tobymao/18xx/blob/master/lib/engine/round/auction.rb#L209

These are the two locations the maximum bid would need to be calculated, if someone decides to go that route.

Another approach would be to actually spend/move the money out of the player's cash until the bid resolves, then return the losing bids. In this case, all the current logic based on their cash would work as-is.
