### ISSUE TITLE
Send game end notifications when someone deletes their account

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#4602]
I haven't had this happen to me, so I am just going off descriptions from others, but it appears that when a user deletes their account, all their games are immediately deleted as well. This leaves the other players in the dark about what happened.

Instead, I think that a process should happen where each of the games that this player is in is manually ended by that player (possibly also with a note that it is because the user deleted their account). Then after those notifications have been triggered to send, delete the account and the games.

**Comment by jbennett-rula** [comment]
This just happened to me, disappointed that there's no plan to address this
