### ISSUE TITLE
[1867] - Can't skip towns

### ISSUE THREAD

**Issue by futzy314** [tobymao/18xx#4609]
**What's your Game ID?**

https://18xx.games/game/32881

**How to Reproduce the Bug?**

OR 1.2 - operating AE

Track from Trois-Riveres through St Jerome into Montreal.  In 1867, you are allowed to skip towns, but I was forced to run my train from Trois-Riveres to St Jerome, I couldn't skip over St. Jerome to get to Montreal with a 2 train.

![1867-issue](https://user-images.githubusercontent.com/17149477/111825944-16a0e280-88b6-11eb-9728-4b9d2d0070b7.png)

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
- Chrome - 89.0.4389.90
- Platform (Mobile, Tablet, Desktop)
- Desktop

**Comment by OedipussyRex** [comment]
You still need to click on St. Jerome to get to Montreal even if you do not want to include it in the total for the run. All pay-points need to be selected when running a route, including those that are skipped. If the game is telling you you have too many stops for the train after selecting Trois-Riveres-St. Jerome-Montreal then there's a problem, but I cloned the game, undid to AE operation, and added Montreal to the run with no issue. Different browser, but still . . ..
