### ISSUE TITLE
Display decreased minimum bid on company card during private auction

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#461]
`Delaware and Raritan Canal minimum bid decreases from $20 to $15`

After a few auction actions, this message will be scrolled off the screen. It would be nice if it was represented on the company card, e.g.

```
PRIVATE COMPANY
Delaware and Raritan Canal
No special ability. Blocks hex K3 while owned by a player.
Value: $20                                     Revenue: $5
Minimum Bid: $15
```

PS: It would also read better to me if it said "purchase price" instead of "minimum bid" in the message and card.

**Comment by scottredracecar** [comment]
Sure, but this should be an incredibly rare event outside of test cases.
