### ISSUE TITLE
1870 connect to destination no trains

### ISSUE THREAD

**Issue by Heifernomore** [tobymao/18xx#4615]
**What's your Game ID?**  32944

https://18xx.games/game/32944
![Screenshot_20210319_220747_com android chrome](https://user-images.githubusercontent.com/80989004/111847556-f9ddcc80-8900-11eb-9290-bcdf619305b6.jpg)

**Which Browser / Platform?**
Firefox Laptop and android phone

**Comment by daniel-sousa-me** [comment]
This was fixed by #4589

If you undo the previous action and do it again (don't click on redo) the game will continue normally.

**Comment by Heifernomore** [comment]
But that says the fix was 2 days ago. This happened last night. I did undo and not redo twice. It didn't work 🤷‍♀️ Unfortunately my husband ended the game so I can't try again now unless there's a way to get it back.

**Comment by daniel-sousa-me** [comment]
You can undo the "end game". I tried it in a clone and it worked as expected

The fix was committed to here 2 days ago, but it took a while for it to get merged

**Comment by daniel-sousa-me** [comment]
Maybe try Ctrl+Shift+R to ask the browser to refresh the cache

**Comment by Heifernomore** [comment]
Yes sorted. Thank you 😊

**Comment by daniel-sousa-me** [comment]
Sorry for the inconvenience

**Comment by Heifernomore** [comment]
No inconvenience. Thanks for all your help 😊
