### ISSUE TITLE
[1822MRS] M14 token space can be filled by another company

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#4618]
https://gist.github.com/rclyne/8c62b46077e2f0e24615e6c88b325fb9

If M14 is acquired by a major company but the company does not take the token then another company can place a token in the space M14 used to be in.  In the example game here, LNWR bought M14 and MR paid to place a token in the M14 space

![image](https://user-images.githubusercontent.com/11814681/111855440-e80a2280-891c-11eb-8292-40e9e488b073.png)

In the board game version, M14 does not place their token in the London space but on a rondel to the side so this can never happen. 

Browser - Safari OSX Version 14.0.3 (16610.4.3.1.4)

**Comment by magnusfalt** [comment]
You are not the first one to open an issue about this. The game actually do this correct, its a rule i also missed when i played the physical game. If we take the last version of the rules.

https://boardgamegeek.com/filepage/219065/1822-railways-great-britain-rules

7.1.2 If a major company acquires M14 then it may place an exchange token on the London rondel in M14’s home station as per the
normal acquisition rules. If the major company chooses instead to move an exchange token to the available station area on its
charter, then the space vacated by the M14 token **becomes available for another company to place a station token**. Rule 6.1.9
still applies.

I will close this issue as the game follow the rules.

**Comment by rclyne** [comment]
Can you tag this with 1822 so people can find it
