### ISSUE TITLE
18Ches: Player should get Cornelius presidency before setting par price

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#462]
```
Player 2 buys Cornelius Vanderbilt for $200
Player 2 pars B&O at $95
Player 2 receives a 20% share of B&O
Player 2 becomes the president of B&O
```
This is mostly cosmetic, and would require a divergence from the normal par setting process, but my reading of the rules suggest that the share and presidency should be taken before the par price is set. This is particularly notable when it's B&O, which another player will already own a share of and be shown on the corporation card.

**Comment by tobymao** [comment]
what's the situation when it's b&o? i don't think i'm going to fix this

**Comment by sparr** [comment]
The messages are the same for any company. What makes B&O special is that another player already owns a share of it at that point, so when this step shows the corp card (as it does for whichever corp you're getting with P6), it has P5's owner's name with one share but not P6's owner's name with two shares.

This was mostly for posterity, it't not important to fix and I'm fine with it being closed until some far future date when all these unimportant action order bugs get fixed by some major refactor.

**Comment by tobymao** [comment]
ok closing for now
