### ISSUE TITLE
[Harzbahn 1873] Information on mines certificates

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4630]
The mines certificates of the start auction (and the ones used later in the game) should bear the mines' names.

The mines certificates of the start auction should not display the maximum revenue of the mines (called merely "Revenue" at the right bottom). This is misleading during start auction. Rather, it should be shown how much the mines currently cost (face value + current premium).

Information on the achievable revenue is already shown in the middle of the mines' start auction certificates. This information should be retained!

Klaus Kiermeier

**Comment by roseundy** [comment]
I agree, "revenue" is definitely misleading in this context. Ideally, it would be a range. I'm reusing the logic for a "normal" 18xx private company during the draft, which has a value and a revenue associated with it. I chose to use the maximum possible revenue for the mine, but I can change it to the value.

I can add the mines' full names as you suggest.

**Comment by roseundy** [comment]
OK, I will add the total price being paid to the "Buy" button, and list the full range of revenues on the corporate card.

Also by the name of the mine, I assume you mean the location? I can't find actual names listed in the Rules anywhere.
