### ISSUE TITLE
[Harzbahn 1873] Connectedness status of mines should be displayed on their certificates

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4633]
**What's your idea?**

Let us know your proposed changes.

The connectedness status of mines (connected or unconnected to the state railways) should be displayed on the mines' certificates, at least the ones that are used later in the game.

At the start of the game only mine #15 is connected. This should be visible -- as well as the unconnectedness of all other mines.

Klaus Kiermeier

**Are there related ideas?**

Other contributors may be working on something similar, [check out the list of open feature requests](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to see if there's opportunity to collaborate.

**Did you join the Slack?**

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ) and meet your fellow contributors!

**Comment by roseundy** [comment]
This is already shown by whether the revenue numbers beyond M1 are grayed-out or not:

Unconnected:
![unconnected mine](https://user-images.githubusercontent.com/8494213/111886705-5f7b9880-8995-11eb-92d3-77db318666d2.PNG)

Connected:
![connected mine](https://user-images.githubusercontent.com/8494213/111886708-64d8e300-8995-11eb-83b8-2ceafb8bcf91.PNG)

I know this is somewhat on the subtle side, but there is a lot of information that needs to be communicated.
