### ISSUE TITLE
Harzbahn 1873 Math error PMC CO buying mine 7 in Player's Guide sample game

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#4638]
Hotseat game: hs_snzqfeqr_1616271949

Playing the sample game printed in the player's guide (R8), link: https://www.dropbox.com/s/rbs59zimqvqybay/1873%20Players%20Guide%20R8.pdf?dl=0

It's in OR 3.1, operation of PMC CO when buying Mine 7.  PMC CO has 345M before purchase, makes purchase at 340M, and game shows PMC CO to have 30M after purchase.  It should have 5M.

**Comment by roseundy** [comment]
Be aware that I can't see your hotseat game. Follow the instructions on attaching a gist.

**Comment by roseundy** [comment]
Also, it looks like you found an error in the player's guide not my code. Mine 7 had 25M in its treasury when it was purchased by the CO. So the the CO should indeed have 30M (5M from CO + 25M from 7).

**Comment by fanman80** [comment]
You're right about the amount in the mine 7 treasury transferring to the CO.  So there is an error in the player guide.

**Comment by fanman80** [comment]
There was no math error by the 18xx.games implementation.  The referenced Player's Guide did not account for the transfer of treasury funds from the purchased entity to the purchasing entity.
