### ISSUE TITLE
Harzbahn 1873 Suspected Revenue calculation error

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#4646]
"Playing" example game in Player's Guide, OR 3.1, HBE operation, train revenue looks incorrect.
HBE has a T1 & T2:
T1 is running the concession route, and that part looks OK.
T2 is running D15 - E16 - F15 (which looks correct) & D15 - D13 - D11 - E10 - D9 (looks like error is in calculation of revenue from D9)

Gist:  https://gist.github.com/fanman80/5b0613b3e004f6389b22f5bad86b1e1d

Attempted screen shot:
![image](https://user-images.githubusercontent.com/70117294/111891289-dd549980-89bf-11eb-80ae-76fa7e132086.png)

**Comment by fanman80** [comment]
Additional screenshots:
![image](https://user-images.githubusercontent.com/70117294/111891701-bfd4ff00-89c2-11eb-8ca6-df177a481832.png)

![image](https://user-images.githubusercontent.com/70117294/111891713-d4b19280-89c2-11eb-9175-cade18030b3b.png)

![image](https://user-images.githubusercontent.com/70117294/111891721-e09d5480-89c2-11eb-846b-ecb325b97773.png)

![image](https://user-images.githubusercontent.com/70117294/111891730-f1e66100-89c2-11eb-9311-5fe18a6ebfab.png)

**Comment by fanman80** [comment]
Notice in the screen shots that when D9 is added to the route, the revenue only increases by 30M.  It should increase by 70M (2 (train size) x 30 (mine multiplier) + 10 (town without token value)).

**Comment by roseundy** [comment]
Mine 10 had an incorrect multiplier. Was reported on the 18xx chat first. Already fixed.

**Comment by roseundy** [comment]
FYI, your game will now fail with the fix, because HBE now has enough cash that it won't be automatically passed out of the train buying step.
