### ISSUE TITLE
1822 (Game 32683)

### ISSUE THREAD

**Issue by bjorsa** [tobymao/18xx#4652]
Game was unable to be upgraded to latest version and remains broken.

https://18xx.games/game/32683?action=1478

**Comment by perwestling** [comment]
The game is "pinned" so it will not be fixed. If it cannot be played I recommend you close the game and start a new one.

**Comment by bjorsa** [comment]
It seems like none of us are able to close the game either. Would it be possible for you to delete it?

**Comment by michaeljb** [comment]
@bjorsa the game has been archived

**Comment by bjorsa** [comment]
Thank you!
