### ISSUE TITLE
[Main chat] Safari browser on mobile assumes chat input is a login field

### ISSUE THREAD

**Issue by antonjonsson** [tobymao/18xx#4656]
Visiting the site on my iPhone (Safari / iOS 14.4.1) today, I got a popup asking if I wanted to login using touch id. Doing so I ended up typing my email adress into the chat. Noticed that several other users also posted their email in the main chat earlier.

**Comment by yzemaze** [comment]
Should be fixed after next deploy. If it’s still a problem tomorrow, just post here and I’ll re-open the issue.

**Comment by Bobsson** [comment]
I don't know about whether this is (still) tied to iOS Safari, but it's definitely still happening.  
![image](https://user-images.githubusercontent.com/2022339/130140853-2845349f-d591-4532-a1f4-a4334c563908.png)
