### ISSUE TITLE
[1822] Created not necessarily token space for dest token

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4659]
I floated SECR in phase 6 and built track to Dover. After I placed their destination token on a yellow tile it created a second token space, although there is no other station token on this one.

https://18xx.games/game/33254?action=1418

**Comment by magnusfalt** [comment]
Yes when i fixed the destination token of LYR and LNWR yesterday i introduced this bug. There is an issue of this already #4650 and it will be fixed in #4651.

Closing this.
