### ISSUE TITLE
Delaware and Ratritan didn't block K3

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#466]
Happened to notice ths well into the game.

**Comment by gchambers419** [comment]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Delaware and Raritan Canal",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Columbia - Philadelphia Railroad",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "Chesapeake and Ohio Canal",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Baltimore & Ohio Railroad",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "Cornelius Vanderbilt",
      "price": 200
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "corporation": "C&A",
      "share_price": "80,3,3"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "corporation": "PRR",
      "share_price": "95,2,4"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "corporation": "B&O",
      "share_price": "95,2,4"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "share": "C&A_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "share": "PRR_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "share": "B&O_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "share": "C&A_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "share": "PRR_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "share": "B&O_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "share": "C&A_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "share": "PRR_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "share": "B&O_4"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "share": "C&A_4"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "share": "PRR_4"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 24,
      "hex": "F2",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 25,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 26,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 27
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 28,
      "hex": "G7",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 29,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 30,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 31
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 32,
      "hex": "J6",
      "tile": "57-1",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 33
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 35,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 40,
      "hex": "E3",
      "tile": "57-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 41
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 42,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 43,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 44
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 45,
      "hex": "F8",
      "tile": "X1-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 47,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 48,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 49
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 50,
      "hex": "J8",
      "tile": "9-1",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 51
    },
    {
      "type": "run_routes",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 52,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "J4",
              "J6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 53,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 55,
      "corporation": "SRR",
      "share_price": "95,2,4"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 56,
      "corporation": "LV",
      "share_price": "95,2,4"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 57
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 58
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 59,
      "corporation": "PLE",
      "share_price": "95,2,4"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 60
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 61,
      "share": "LV_1"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 62
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 64
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 65,
      "hex": "D4",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 67,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 68,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "buy_company",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 70,
      "company": "Chesapeake and Ohio Canal",
      "price": 160
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 72,
      "hex": "H6",
      "tile": "X5-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 73
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 74,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 75,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 76
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 78,
      "hex": "J4",
      "tile": "X3-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 79
    },
    {
      "type": "run_routes",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 80,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "J4",
              "J6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 81,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 82
    },
    {
      "type": "buy_company",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 83,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 85,
      "share": "PLE_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 86,
      "share": "SRR_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 87,
      "share": "LV_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 88,
      "share": "PLE_2"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 90
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 91
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 92,
      "hex": "D2",
      "tile": "57-3",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 93
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 94,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 95,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 97
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 98,
      "hex": "E7",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 100,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 101,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 102
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 103,
      "company": "Columbia - Philadelphia Railroad",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 104
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 105,
      "hex": "K3",
      "tile": "2-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "run_routes",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 107,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "J4",
              "J6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 108,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 109,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 111
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 112,
      "hex": "C5",
      "tile": "57-4",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 113,
      "city": "57-4-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 114,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "C5",
              "D4",
              "E3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 115,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "Columbia - Philadelphia Railroad",
      "entity_type": "company",
      "id": 118,
      "hex": "H2",
      "tile": "9-3",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "Columbia - Philadelphia Railroad",
      "entity_type": "company",
      "id": 119,
      "hex": "I3",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 120,
      "hex": "D8",
      "tile": "57-5",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 121
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 122,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 123,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 124,
      "train": "3-3",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 125
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 126,
      "company": "Baltimore & Ohio Railroad",
      "price": 200
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 127
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 128,
      "hex": "J10",
      "tile": "7-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 129
    },
    {
      "type": "run_routes",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 130,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "I9",
              "J10",
              "J6",
              "J8"
            ]
          ]
        },
        {
          "train": "3-2",
          "connections": [
            [
              "J4",
              "K3"
            ],
            [
              "J4",
              "J6"
            ]
          ]
        }
      ]
    },
    {
      "type": "undo",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "run_routes",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 132,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "I9",
              "J10",
              "J6",
              "J8"
            ]
          ]
        },
        {
          "train": "3-2",
          "connections": [
            [
              "J4",
              "K3"
            ],
            [
              "J4",
              "J6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 133,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 134
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 136,
      "share": "SRR_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 137,
      "share": "LV_3"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 138
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 139,
      "share": "SRR_3"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 140
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 141
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 142
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 143,
      "hex": "F2",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 144
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 145,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "D2",
              "E1",
              "F2"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 146,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 147,
      "train": "3-5",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 148
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18Chesapeake",
  "description": "",
  "max_players": "6",
  "id": "hs_1590194281",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-05-22",
  "result": {}
}

**Comment by tobymao** [comment]
fixed
