### ISSUE TITLE
[1822NRS] Should not be able to run a single train from London to London

### ISSUE THREAD

**Issue by magnusfalt** [tobymao/18xx#4661]
- You shouldnt be able to run from one london city to another.

**Comment by michaeljb** [comment]
Easy to solve by putting both cities into a "group", e.g., here's how the Chicago (D6) tile in 1846 is defined to prevent running Chicago to Chicago

https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1846/game.rb#L677

**Comment by magnusfalt** [comment]
Good idea.
