### ISSUE TITLE
Harxbahn 1873 Start Auction Minimum Bid Too High

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#4664]
In the rules for the start auction (2.1) the third sentence of the third paragraph reads "**The minimum bid is zero** and all higher bids must be multiples of ten."  However, the implementation does not seem to allow for a bid of zero in the start auction.

**Comment by roseundy** [comment]
Good catch. Whenever I tested a premium of zero, I got it by passing all around.

**Comment by roseundy** [comment]
No pins required

**Comment by fanman80** [comment]
Thanks.  Although, I don't think a zero bid will win the start auction, it does give the first player more of a chance to stay in the bidding longer.

Thanks again for all your hard work on this.  It seems to work very well overall, and I'm enjoying it.
