### ISSUE TITLE
[1822] Looks Like Possible Shares of Floating LNWR Calculated Wrong - Or Other Issue

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#4669]
https://18xx.games/game/33676

When I floated the LNWR holding the concession it showed that I could buy four shares which is exactly what I calculated.  However, it looks like LNWR Conc. is 1 Share and not $100 like the other Conc.

So I have ended one share below where I expected.

So either:  The Float Share calculation was wrong (it used $100 for the value of the Conc.  just like I did) or the concession converted wrong.

**Comment by magnusfalt** [comment]
It is the correcvt bahaviour when its floating, but the possible shares calulation looks like its wrong for LNWR.

**Comment by rheretic** [comment]
Thanks!  That's exactly what I figured!
