### ISSUE TITLE
Game card displayed incorrectly (wrong owner, "Error rendering game card")

### ISSUE THREAD

**Issue by ikelly** [tobymao/18xx#4671]
Not sure what I did, if anything, to cause this. The tab was pretty old and stale.

This game card shows "Error rendering game card" and the site incorrectly shows me as the owner of the game, including showing the Delete button, but I am not in the game.

**Which Browser / Platform?**
Chrome 88.0.4324.186
Desktop

![Screenshot 2021-03-21 at 11 03 39 AM](https://user-images.githubusercontent.com/1767452/111913931-a5883900-8a35-11eb-8b6e-eebec120f13c.png)

**Comment by daniel-sousa-me** [comment]
Most likely your browser is running an outdated cached version. Try hitting Ctrl+Shift+R

**Comment by michaeljb** [comment]
Yeah that's the most likely cause, but it definitely shouldn't be showing you as the active player or presenting the delete button.

**Comment by daniel-sousa-me** [comment]
When I drew that card, I only took hotseat games into account. That's probably why it shows like that
