### ISSUE TITLE
[1822NRS]  Extra Station Spot Created for Destination Token in Manchester When Empty Slot Exists. 

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4674]
https://18xx.games/game/33842?action=368

LYR destinates in Manchester and an extra station spot is needlessly created.

**Comment by michaeljb** [comment]
Looks correct to me--before and after destinating there are two city slots, when LYR destinates they fill the second, when the green X2 tile is laid it gets a third one.

This behavior was recently modified in https://github.com/tobymao/18xx/pull/4651 so if you have an old client you may be seeing the old behavior. Have you tried refreshing?

**Comment by magnusfalt** [comment]
As michael said, this is fixed in the PR #4651.

**Comment by Maxwell-Frank** [comment]
Weird, it looked broken to me. I think the PR might have been merged after we started the game but before I refreshed my browser? 

Regardless, it looks fine now.
