### ISSUE TITLE
Game engine does not enforce groups usage on routes, only UI does

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#4676]
18CZ gist running from Praha to Praha - hotseat json, Praha has no tile yet - https://gist.github.com/michaeljb/441f494336988cd8cfff43672eae8d87

With the code on https://github.com/tobymao/18xx/pull/4673, that run cannot be selected in the routing UI, but if the game JSON already has the route submitted, it is incorrectly allowed

**Comment by roseundy** [comment]
Isn't this a natural consequence of how we only calculate route revenue on the UI?

**Comment by michaeljb** [comment]
> Isn't this a natural consequence of how we only calculate route revenue on the UI?

Yeah, probably. I was just surprised doing https://github.com/tobymao/18xx/pull/4673 that it still accepted the illegal route that had already run. Don't think it's a big enough deal to worry about then. Thanks!
