### ISSUE TITLE
1822 add auto actions for laying destination token (or skipping lay destination token)

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#4680]
Since there is no "choice" when laying the destination token, the user should not be prompted to either skip or lay the destination token. It should be done with an auto action.

In this example, LYR must lay its destination token. The token should be automatically laid with no user interaction (log the placement as normal).
https://18xx.games/game/33787?action=231

Conversely, in this action, LYR has not reached its destination so an auto action should skip the destination token placement automatically (no comment).
https://18xx.games/game/33787?action=191

**Comment by jenf** [comment]
Since previous games have been deleted
Has reached
https://18xx.games/game/30797?action=1261
