### ISSUE TITLE
Harzbahn 1873 Green Tile Trouble KZE

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#4687]
Hot seat game in OR 5.1 the game "hung" when trying to lay a green tile on hex G4.  The concession route had been built previously by a mine, and the KZE was formed and floated in AR/SR 5.  Prior to the operation of the KZE a PMC bought some level 3 machines to trigger phase 3.  So green tiles were available.  During KZE's turn, when I clicked on hex G4, the game gave me a choice of tile 971 and 972.  I clicked on 972, the red "X" and green check appeared for confirm or cancel, I clicked on the green check and then the red "X", and the game seemed to be unresponsive.  When I clicked on the "undo" button the game went back to the beginning of the KZE's turn.  I tried this with the 971 tile with the same results.  I tried 972 again and then went to the main page that shows my games and has the link to the GitHub.  Now I am not getting back into the game.  Clicking on the "enter" button for the game does not seem to work.

Gist link:
https://gist.github.com/fanman80/3c017d657335495d3a0376a517ee15db

I was meaning to capture some screen shots, but as I said above, I can't get back into the game.

**Comment by fanman80** [comment]
I'm also a participant in game https://18xx.games/game/33452 which is Harzbahn 1873.  I'm having no problems entering this game, and I have not encountered any problems with the other games in which I am participating on the site.

**Comment by crericha** [comment]
Known issue. Will be fixed on the next deploy.

**Comment by crericha** [comment]
It has to do with laying tiles that have a purple border.
