### ISSUE TITLE
[Harzbahn 1873] Negative train income (?) Company did not go into receivership

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#4697]
**What's your Game ID?**
https://18xx.games/game/33834?action=452

**How to Reproduce the Bug?**
After SHE was open and two track were build, company was automatically charged 120M (looks like negative income from train run). I can't find anything  in the rules to back up such a charge.

Right after that it couldn't buy a new train (not enough funds) and it had no option available to become insolvent or in receivership (don't remember which is which :P )

**Which Browser / Platform?**
n/a

**Comment by roseundy** [comment]
Hmmm. Aside from the mystery 120M it was charged, it should have been given the option to pass on train purchase.

**Comment by roseundy** [comment]
Logic error - used last corporations maintenance instead of re-calculating it.
