### ISSUE TITLE
After buying a 3-train another run trains action (Game id 34)

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#47]
After buying the first three train active player (Jones) gets another run trains action
![A2BE08D5-CA4A-453C-9DBA-7AD6FAFD8FD5](https://user-images.githubusercontent.com/63635335/79382517-e9400c00-7f63-11ea-877e-6cc37fb47aec.png)

**Comment by tobymao** [comment]
thank you please preserve this state so i can repro and fix
