### ISSUE TITLE
[1870] Tile laying error

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#4703]
We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action 758
Broken action: { "type": "lay_tile", "entity": "SP", "entity_type": "corporation", "id": 758, "created_at": 1616351984, "hex": "N17", "tile": "5-0", "rotation": 2 }
Please raise a bug report and include this link (https://18xx.games/game/33777?action=757)

**Comment by daniel-sousa-me** [comment]
A bugfix (probably a5744843a2f7a4092a92636704b6da28a7792b44) broke the game and it needs to be archived.

**Comment by michaeljb** [comment]
The game has been pinned now (and I checked for other broken games, fortunately this was the only one)
