### ISSUE TITLE
[Harzbahn 1873] undefined method 'name' for nil

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#4704]
**What's your Game ID?**
https://18xx.games/game/33834?action=525

**How to Reproduce the Bug?**

issue 1
What steps cause the unexpected behavior?
- click "skip trains"
- "undefined method 'name' for nil " will be displayed
- can't proceed with game

issue 2
- click "buy" to buy 4S from The Depot
- "illegal train depot buy" will be displayed
OR
- click "buy" to buy any other train from my other company
- works as expected

**Which Browser / Platform?**
n/a

**Comment by roseundy** [comment]
Wow. The skip trains bug is actually a problem with our Ruby->javascript path I think that shows up when a company goes insolvent.

The buy 4S bug was due to an erroneous action validation I added recently

**Comment by roseundy** [comment]
BTW, The Union (U) mine is one mark short of not going insolvent!
