### ISSUE TITLE
18MEX: Implement Variant Package #1 - The Baja-Copper Connection

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#4710]
An official variant of 18MEX.

If you need details contact @perwestling

**Comment by michaeljb** [comment]
@philcampeau was talking about working on this on slack (looks like I can’t assign him on the ticket though)

**Comment by philcampeau** [comment]
Tbh I’m still figuring out the ins and outs of how the code works. If someone else wants to take this on, it’s pretty straight forward.

**Comment by perwestling** [comment]
@philcampeau I created this intending to assign it to you. Take your time...

**Comment by philcampeau** [comment]
Will do!
