### ISSUE TITLE
There should be an indicator that you have a local note

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#4713]
As someone with a lot of games at once, notes are really useful to manage what I want to do. That said, most of my games don't have notes. It's tedious to always have to go to the tools tab every time I take a move to see whether or not a given game has a note. Thus, it'd be extremely nice to have a nice little reminder somewhere on the main game screen that there is a note to reduce the amoutn of hopping around necessary.

**Comment by jenf** [comment]
Could probably add the tick similar to how we do on auto-actions
