### ISSUE TITLE
Bug in Auto function ?

### ISSUE THREAD

**Issue by SyagriusP** [tobymao/18xx#4714]
[1889] unable to reach Auto menu

Game ID : 29493

https://18xx.games/game/29493

I used the Auto menu to generate an auto order (although I do not remember which specific order it was, probably pass but I may have planned something different like an auto buy in some company)

The Auto menu appears with a "validated mark" next to it, which may mean that some kind of auto order is currently active for me
Nonetheless, when it's my turn to play, nothing happens automatically and I have to give my pass order (no other choices, I am at max shares)
When I try to access the auto menu, nothing happens either

I suspect that the auto order that I gave is not pass but something somehow illegal (like trying to buy another share while already at max number of shares)
Is there a way to get out of this conundrum?

I am using Firefox 86.0.1 version on a HP Pavilion computer

**Comment by jenf** [comment]
when it's your turn again it'll deactivate. i'll try an address the problem tonight

**Comment by SyagriusP** [comment]
Thanks

I do not know what created the issue but thought that I should report 
it, in case it revealed an hidden bug



Not sure if I should raise it here but, when I created my account on 
GitHub, I had the surpise to see that Syagrius (my usual game nickname) 
was already taken. Since it is quite rare (it is the name of a Roman 
general in the North of France in the 5th century), I wonder if it was 
created automatically when I started playing on 18xx.games. In that 
case, I was not aware of this and did not note the associated password 
(hence I created this new SyagriusP nickname, where P stands for Paris 
where I live)

Regards



                         Vincent

Le 23/03/2021 à 13:21, Jennifer Freeman a écrit :

**Comment by dfannius** [comment]
18xx.games does not create github accounts for users (I doubt that it could). You can see the GitHub account of the person who grabbed your usual nickname here: https://github.com/Syagrius

(I am empathetic because my usual handle is dfan, and that was reserved here as well. Dfannius was not the name of a Roman general, though.)

**Comment by jenf** [comment]
found fix, dup of #4605
