### ISSUE TITLE
Auto-buy should stop once floated, if option to sell

### ISSUE THREAD

**Issue by tom-blight** [tobymao/18xx#4715]
Currently the auto-buy-til-floated feature passes _after_ the buy action that floats the company. In sell-buy-sell or buy-sell games this it a little presumptuous :)

I believe it's quite common tactic to sell a share after floating a company, to ward off stock-trashers. Particularly if you've bought all 60% yourself, and you can sell down to 50% and still secure the presidency. 

I'd certainly like that option. This could be the default, i.e. make a change to the way auto-buy-til-float works, or could be an added checkbox  [ ] don't pass after floated

**Comment by jenf** [comment]
Don't suppose you have a sample game where you saw it do this?

**Comment by tom-blight** [comment]
Hmm - not one off the top of my head. But any 1830 game where autobuy is
used should demonstrate this.
