### ISSUE TITLE
18Ches - Vanderbilt private displaying different Corps

### ISSUE THREAD

**Issue by WeeMadAndo** [tobymao/18xx#472]
As per screens - inconsistent reporting/display of President's Share associated with Vanderbilt. Game id 1144. 

![Screenshot_20200523-145805](https://user-images.githubusercontent.com/65803330/82723059-4c655100-9d0f-11ea-874a-bdb604c95573.png)
![Screenshot_20200523-160620](https://user-images.githubusercontent.com/65803330/82723071-71f25a80-9d0f-11ea-8814-f1ba9d05552d.png)
![Screenshot_20200523-160635](https://user-images.githubusercontent.com/65803330/82723074-7585e180-9d0f-11ea-8677-bb6929f6fd18.png)

**Comment by tobymao** [comment]
when were these screen shots taken? if you can still repro this issue please reopen as i just fixed it. if these were taken a couple hours ago then it shouldn't happen again.

**Comment by WeeMadAndo** [comment]
Taken over the last hour or so - but everyone is reporting it being
consistent display now.
