### ISSUE TITLE
[18FL] President Can only Contribute Personal Cash for Cross-buy if the Company has no Cash

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4724]
https://gist.github.com/Maxwell-Frank/97db638deb2886b9f929a8c91f44c48a

8.4.2: The President may only contribute presidential cash to cross-buy in an EMR situation if the company has **no cash.** Otherwise, cross-buys are limited to $1-current_treasury_cash.

**Comment by ventusignis** [comment]
This PR fixes this:
https://github.com/tobymao/18xx/pull/4729

**Comment by michaeljb** [comment]
closing per @ventusignis's comment about this issue being fixed by #4729
