### ISSUE TITLE
[18Chesapeake: Off the Rails] Chesapeake and Ohio Canal private does not let to place a token

### ISSUE THREAD

**Issue by pedro-girao** [tobymao/18xx#4726]
Hi there,

Game: https://18xx.games/game/33925

So this is a game of 18Chesapeake: Off the rails, and this issue is exactly what the title says. I mean, it should be possible to place a token in D2? At least that's my understanding of the power of the private.

Following is a print screen and the game_data.json.

![image](https://user-images.githubusercontent.com/7449150/112171449-bc708c00-8beb-11eb-8d42-03fe2fb6ae5f.png)
[game_data.txt](https://github.com/tobymao/18xx/files/6190752/game_data.txt)

Let me know if there is anything else I can provide to help.
Thank you!

**Comment by tobymao** [comment]
broken by ec4fd27b4fd3 cc @ventusignis  

fix inc
