### ISSUE TITLE
Add liquid cash to player info/spreadsheet

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#473]
When I was trying to setup a company is forgotten to take into account the privates.

It'd be useful to show how much a player has if they sell all the shares they can sell.

**Comment by hast18xx** [comment]
one more nth is to see players available cash in the names row

![image](https://user-images.githubusercontent.com/64490299/82729841-30f04b00-9cfb-11ea-8014-a47e9bd3537f.png)

**Comment by ChrisTheCat** [comment]
Now that this is on the player cards, could it also be added to the spreadsheet?

**Comment by yzemaze** [comment]
@hast18xx 
Players’ cards with cash is rendered right below the corporations. If that’s not enough please open a new issue.
