### ISSUE TITLE
[Harzbahn 1873] Closed mines are offered to form PMCs

### ISSUE THREAD

**Issue by beorn7** [tobymao/18xx#4730]
**What's your Game ID?**

https://18xx.games/game/33487?action=147

**How to Reproduce the Bug?**

Mine 1 is offered as the second forming mine to create PMC _Union_. Mine 1 is closed, though, so that's against the rules.
If you actually select mine 1 for merging, the error message "undefined method `shares_by_corporation' for nil" appears. (So the good thing is: You cannot actually execute the move. But closed mines shouldn't be offered in the first place.)

**Comment by roseundy** [comment]
This was fixed. For some reason @players.include?(nil) was returning true.
