### ISSUE TITLE
[1846] Add new private companies from 2nd printing

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#4732]
With the second printing coming out the designer has also included two new privates. The deliveries are scheduled for April so I imagine the privates are finalized.

Details on them are not publicly available as of yet, but if the designer does give the specifics would the original implementation agreement cover the new privates?

Some details here:

https://boardgamegeek.com/thread/2589981/1846-gmt-reprint-2nd-edition-now-printer

**Comment by dfannius** [comment]
Yes, we plan to implement the new privates.

**Comment by michaeljb** [comment]
Got a good start on the logic for the new privates, but we won't have the particulars from Tom until GMT is ready to ship the new games out.

Once I've got the full info it shouldn't be long to finish implementing them, then I'll just need to make sure the optional rule stuff is in place and have a way to migrate all old 1846 games to use the 1E optional rule.
