### ISSUE TITLE
18CZ, upgrade 8885 >> 8894p not possible, only MasterMode Possible

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#4735]
18cz, Game https://18xx.games/game/32463
the upgrade of the Tile 8885/D27 to the tile 8894p is not possible (the new tile is not shown)

actual: we can finish the game only with the master mode.

**Comment by Zwergenpunk** [comment]
I'm not sure at which point the upgrade was possible. Can you make a link direkt to the action? 

The mastermode problem is fixed soon

**Comment by volker18xxdev** [comment]
18CZ: Phase j - Operating Round 8.2 (of 3) - Lay/Upgrade Track KK, maybe id 891, as far i interprete the game data right.

**Comment by Zwergenpunk** [comment]
The 8894p tile can only be placed with a abilitiy of a medium/large company. 

The kk corporation did not have any companies.
