### ISSUE TITLE
[1828.games] Unable to place station in Scranton using D&H's ability

### ISSUE THREAD

**Issue by bubba0077** [tobymao/18xx#4741]
### Description
During OR 3.2, Erie attempted to use the ability of Delaware & Hudson to lay a tile in Scranton (F20) and place a station there. Erie is able place the tile, but unable to add a station token.

This is Erie's second OR, having upgraded the Erie tile and placing its home token in its first OR

[Game 32320](https://18xx.games/game/32302?action=389)
[JSON](https://gist.github.com/bubba0077/e77c62971cbe4d9e6f45d7454a743a70)

JSON data is from the start of Erie's turn.

### Steps to reproduce from JSON save point
1. Click D&H button to activate ability
2. Click on Hex F20
3. Lay tile
4. Click on Hex F20 to attempt to place station

Expected: station token added
Actual: Nothing happens (no error, no token placed)

### Additional information
- Other players attempted to complete the action using master mode with the same result.
- The issue is still seen in a cloned copy of the game.
- D&H has worked correctly in the past for other companies.

**Comment by tobymao** [comment]
fixed by d08da595e82fa7df072fe89b28d4ed9d3ef00c56
