### ISSUE TITLE
Out of order destination runs don't work in 1870

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#4747]
https://gist.github.com/ventusignis/887f3a12782c661e4e113d1571e1cae1

FW was supposed to do its destination run as there was a 4T-sized connectino from Fort Worth to Denver after the Katy ran but it didn't get to do it.

**Comment by ventusignis** [comment]
https://18xx.games/game/34179
The FW didn't get to do a destination run when it got back to its turn either

**Comment by daniel-sousa-me** [comment]
I'm sorry, I had missed this report. Meanwhile this has been fixed by #4752

**Comment by crericha** [comment]
Daniel's comment implies that the issue is resolved. @ventusignis, would you mind verifying with the gist and closing if resolved?
