### ISSUE TITLE
[Harzbahn] undefined 'owner=' method for nil

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#4751]
**What's your Game ID?**
https://18xx.games/game/34140?action=563

**How to Reproduce the Bug?**
Can't pass during stock round. As a result game can't continue. We are getting :
undefined 'owner=' method for nil
message instead.
We tried to undo/redo multiple steps, but it changed nothing.

It is likely related to autopass feature.  "pass button" issue started to my friend exactly after I enabled autopass. Also when we were undoing some steps autopass started to enable itself (green symbol next to AUTO) at random in turns when it wasn't previously enabled.

**Which Browser / Platform?**
n/a

**Comment by roseundy** [comment]
Another stupid coding bug. I continue to have the dumbs about deleting elements I'm iterating over.
