### ISSUE TITLE
[Harzbahn 1873] No unlocking of WBE concesion route hexes in Phase 3: this is against the rules

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4755]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33770

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

The game is in Phase 3 (green). And according to Rule 4.4.1:
"On the three light brown concession-route hexes of the WBE (C10, C12, C14), track may only be built from Game Phase 3 on."
But: When the HBE tries to place a tile on C14, this action is rejected from the program and the following note appears:
"The server did not accept this action due to: illegal action: C14 is not upgradable to 75..."
Rather, on C14, tile 75 or tile 956 should be buildable, and in both cases, a tile 962 needed to be reserved.

By the way: the WBE concession must then be available (earlier availability) in the next auction round.

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by roseundy** [comment]
I'm not sure what's going on here. When I clone your game and undo to the HBE's turn. I can lay that tile with no problem:

![log](https://user-images.githubusercontent.com/8494213/112322677-ba9fda80-8c76-11eb-85a7-b59486f28d24.png)
![Hiemburg lay](https://user-images.githubusercontent.com/8494213/112322693-be336180-8c76-11eb-959f-471d2dfcf032.png)

I will see if I can reproduce this outside of a hotseat game.

**Comment by roseundy** [comment]
OK, I was able to reproduce this on a multiplayer game. Need to debug.

**Comment by roseundy** [comment]
Was comparing a symbol to a string. Works fine in hotseat, but not multiplayer.
