### ISSUE TITLE
[1870] Share price didnt change after 2shares sold

### ISSUE THREAD

**Issue by BobProbst** [tobymao/18xx#4759]
1870: 2shares of Frisco were sold. Well above the soft ledge and the price didnt change
https://18xx.games/game/33299
no offer or message to price protect either although i would have been unable to buy both shares
i'd refused a price protect earlier in the sr on that co.

**Comment by BobProbst** [comment]
After buying a diff share and passing, then the price dropped.  So I'd guess that there was some pending event that didn't happen until after my action and not before

MantisToboggan buys a 10% share of SP from the IPO for $68
[11:42]MantisToboggan declines to sell shares
[11:42]MantisToboggan can't price protect 2 shares of SLSF
[11:42]SLSF's share price changes from $110 to $90

**Comment by daniel-sousa-me** [comment]
Yes, it only drops at the end of the turn, because that's when price protections is triggered

**Comment by BobProbst** [comment]
> Yes, it only drops at the end of the turn, because that's when price protections is triggered

So if player a sells player c&b's shares, then player c passes on price protection and then player b has to buy sell or pass before they make a decision about price protection? That doesnt feel right and is exactly how it played out

**Comment by daniel-sousa-me** [comment]
You are right, indeed I missed that sell. SLSF's price should have dropped before you played. This instance is particularly bad because you could have sold shares to protect it.

But that bug has been fixed 4 days ago. You are running a pinned version (which shouldn't have happened on an alpha game)

**Comment by michaeljb** [comment]
@daniel-sousa-me want me to archive the game?

**Comment by daniel-sousa-me** [comment]
Since it's done, I think we can leave it to the players to decide if they want to continue.

**Comment by jenf** [comment]
Issue seems to only apply to a pinned game, closing.
