### ISSUE TITLE
[1817] Game 15967 is stuck loading game.

### ISSUE THREAD

**Issue by Antivamp** [tobymao/18xx#4768]

**Comment by roseundy** [comment]
1817.

Uncaught gargs: (2) ["#a40122", 0.5]message: "undefined method `convert_hex_to_rgba' for #<View::Game::Part::CitySlot:0x4701e>"name: "convert_hex_to_rgba"stack: "convert_hex_to_rgba: undefined method `convert_hex_to_rgba' for #<View::Game::Part::CitySlot:0x4701e>↵    at g.$method_missing (https://18xx.games/assets/deps.js:4:12818)↵    at g.a (https://18xx.games/assets/deps.js:1:12421)↵    at p (https://18xx.games/assets/main.js:2:522723)↵    at K.$each.$$p (https://18xx.games/assets/deps.js:9:50849)↵    at t.yield1 (https://18xx.games/assets/deps.js:1:14043)↵    at Array.$collect (https://18xx.games/assets/deps.js:9:74517)↵    at Array.$__send__ (https://18xx.games/assets/deps.js:4:7257)↵    at Object.t.send2 (https://18xx.games/assets/deps.js:1:16269)↵    at t.send (https://18xx.games/assets/deps.js:1:16107)↵    at g.$each (https://18xx.games/assets/deps.js:9:50242)"__proto__: g

**Comment by crericha** [comment]
Game loads now. Can someone else please verify that it isn't only me?

**Comment by jenf** [comment]
Possibly player colours related

**Comment by jenf** [comment]
Yeah, disabling player colors fixes it. 7 players, will look in more detail tonight

**Comment by Antivamp** [comment]
Game still does not load for me.

Sent from my iPhone

On Mar 25, 2021, at 7:29 AM, Jennifer Freeman ***@***.***> wrote:

﻿

Yeah, disabling player colors fixes it. 7 players, will look in more detail tonight

**Comment by jenf** [comment]
Temporarily find any 1817 game you can open, and go to the map and disable player colors
