### ISSUE TITLE
[18Mag] Show value gained from minors and majors separately

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#4779]
**What's your idea?**

I'm in a close game right now where I will lose because I didn't invest in quite the right companies.  I was trying to evaluate if I could catch up to the leaders by running better routes or if their gains over me were more due to the payouts from their major company holdings.  Since these value increases aren't separated in the Spreadsheet and I was too lazy to do the math on my own, I thought I'd throw it up as a suggestion here and see if it's something others would like to see implemented as well.

**Are there related ideas?**

Did not see any similar requests in the open issues.

**Comment by roseundy** [comment]
Don't know about this one. Are there other games that would benefit breaking out minor income from major income?

**Comment by vints1** [comment]
I'm too new to 18xx in general to answer your question for all games out there, but I don't see a reason to do this for any other game on .games at the moment.  Maybe 22?  

I don't feel strongly about this.  I just thought I'd offer it up as a suggestion since I happened to have experienced this in one of my games.  I'll leave it up to those of you doing the actual work to decide if it's worth it.

**Comment by scottredracecar** [comment]
closing, doesn't seem to be interest in this feature.
