### ISSUE TITLE
[18FL] incorrect token/hotel price

### ISSUE THREAD

**Issue by BobProbst** [tobymao/18xx#4781]
https://18xx.games/game/34246
Happened at 10:40est
SR has a bonus token in Tallahassee and tried to place a hotel in the town just west and I got the message:  Sr Doesn't have $100 to place a hotel.  I think it should have been only $20 as measured from the bonus token in Tallahassee

**Comment by ventusignis** [comment]
https://github.com/tobymao/18xx/pull/4784
