### ISSUE TITLE
[Harzbahn 1873] When buying switchers from other companies, the rules may be broken.

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4785]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33770

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In Operating Round 7.1, the director of the WBE bought a 2-switcher from mine #2 of Union.
- He was able to do this for a price much higher than allowed, namely for 1000 M.
- Allowed are at most 100M.
Klaus Kiermeier

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by roseundy** [comment]
Bad programming practice - I assumed the UI wouldn't let such a large value through. If you use the "up/down" buttons on the price entry, it won't let you go above 2 x the value of the train, but you can still type any number you want.

It's bad practice for me to not validate the action.
