### ISSUE TITLE
[Harzbahn 1873] Impossible to upgrade hex G20

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4786]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33770

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In Operating Round 7.1 (Phase 5) the director of the GHE tried to upgrade hex G20 from green to brown.
- This was not possible although the necessary tile was available.
- Other hexes could be upgraded to brown.

Klaus Kiermeier

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by roseundy** [comment]
The problem is that the tile laying code base is not happy with laying a tile that has track that runs of the edge of the map.
I predict that upgrading B19 will have the same problem. The rules would also seem to prohibit this, but I'm not going to argue with the designer. :-)

The fix is to add gray tiles extending the track:
![new gray](https://user-images.githubusercontent.com/8494213/112532346-56604200-8d6e-11eb-808a-9db0aee4ccc5.png)
