### ISSUE TITLE
[1828] can’t open game 28559

### ISSUE THREAD

**Issue by jrt1817** [tobymao/18xx#4787]
Every time I try to enter ongoing 1828 game at https://18xx.games/game/28559, I get a white screen. Tried for over a week. Thanks!

**Comment by jenf** [comment]
Pinned game. Unrecoverable.

Uncaught 
v
args: []
message: "undefined method `buyable' for nil"
name: "buyable"
stack: "buyable: undefined method `buyable' for nil↵    at v.$method_missing (https://18xx.games/pinned/61d10175.js:4:12537)↵    at v.p (https://18xx.games/pinned/61d10175.js:1:11670)↵    at v.$can_gain? (https://18xx.games/pinned/61d10175.js:93:449191)↵    at S (https://18xx.games/pinned/61d10175.js:14:309271)↵    at Object.m.yieldX (https://18xx.games/pinned/61d10175.js:1:13577)↵    at Le (https://18xx.games/pinned/61d10175.js:8:24510)↵    at Object.m.yield1 (https://18xx.games/pinned/61d10175.js:1:13294)↵    at Array.$each (https://18xx.games/pinned/61d10175.js:8:77223)↵    at m.send (https://18xx.games/pinned/61d10175.js:1:15228)↵    at Array.$any? (https://18xx.games/pinned/61d10175.js:8:24393)"
__proto__: v
