### ISSUE TITLE
[1822] Majors can have both a 2P and an LP

### ISSUE THREAD

**Issue by PeteC66** [tobymao/18xx#4789]
https://18xx.games/game/34426

GWR has both a 2P and a LP train.  Majors are only supposed to have at most one 2 or L permanent.

**Comment by PeteC66** [comment]
Happened in OR 5.2

**Comment by PeteC66** [comment]
More related problems.  The LP train eventually had to be discarded by the GWR.  I can't find when it happened in the log anywhere but I think it happened when the first T4 was bought and the train limit went from 4 to 3.  So now the LP train is in the open market and nobody can emergency fundraise because you have to buy the cheapest train, the LP train is recognized as the cheapest because it has no cost, and you can't buy it.

**Comment by PeteC66** [comment]
The LP was discarded at time 16:52, when the GWR acquired another minor (M30).  When the GWR acquired the LP it was when it acquired M14 at 14:49 in the game.  The game recognized the LP had to be discarded when M30 was merged in later but not originally when M14 was merged in earlier with the LP on it.

**Comment by PeteC66** [comment]
Just in case the times don't tell you anything the acquisition of M30 by GWR and the LP discard happened in OR8.2

**Comment by yzemaze** [comment]
> Just in case the times don't tell you anything

They usually don’t because they are displayed in local time of the viewer. Links with action-param would help a lot, e. g. https://18xx.games/game/34426?action=558

**Comment by kelvinatang** [comment]
Similar thing happened here: https://18xx.games/game/35941?action=446

NBR major already had a 2P, acquired the 1 Minor which had an LP, and was not forced to discard one of them from the game.  After the acquisition, the NBR was over the train limit and had to discard a normal 3 train to the bank pool.

We did not have to return one of the special trains to the bank pool and was able to finish the game.
