### ISSUE TITLE
Allow modification of past moves in place

### ISSUE THREAD

**Issue by sparr** [tobymao/18xx#479]
In my current game I just discovered that someone under-ran a train 50 actions ago. Since it's an async game this is the first time I've looked at the game since it happened, so it seems reasonable to want to fix it. However, no one wants to do the leg work to roll everything back to that point and then re-do the later actions.

For situations like this I think there should be an even-more-Master mode that allows changing history, perhaps with some UI or perhaps just by allowing direct changes to the game data JSON. This would need to be made very obvious in the game log when it happens

**Comment by tobymao** [comment]
one way to do this would be to be able to clone multiplayer games. doing so, then you could edit the json however you want.
