### ISSUE TITLE
Can’t place Ohzu tile after undo action (game id 34)

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#48]
After buying private for an illegal amount (¥5 More than company treasury) received an error. After pressing undo the possibility to place Ozhu was never offered again

**Comment by tobymao** [comment]
thank you please preserve this state so i can repro and fix

**Comment by tobymao** [comment]
maybe you need to refresh after the error? i can't repro this right, if you can give me a fresh game state with i'll try
