### ISSUE TITLE
Right Clicking Navigation Tabs, Open Link in New Tab 

### ISSUE THREAD

**Issue by leisenstein** [tobymao/18xx#4801]
**How to Reproduce the Problem?**
**Right click a Navigation tab and choose Open Link in new tab**

What steps cause the unexpected behavior?

**I often right click Navigation tabs and choose "Open link in new tab".**
**This is not working as expected. It should open a new browser tab with the #naviation tab as the url.**

**Ex, Right clicking *Entities* and choosing Open link in new tab should open a new browser tab with the url: _/game/12345#entities_**

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
 **Chrome (or Edge)**
**Windows 10 Latest**

**Comment by yzemaze** [comment]
cf. #1060
