### ISSUE TITLE
Request: [1861] Short variant

### ISSUE THREAD

**Issue by MarkOlree** [tobymao/18xx#4803]
**What's your idea?**

The latest GTG 1861/1867 release features a 1861 Short variant [1861S] proposing 3 rule variants to shorten the game-play. They can be added as optional choices at the start of the game.

**15. 1861 Short variant**
There are three separate sets of rules you can use to shorten a game of 1861. These three can be played in any combination. If this is your first play of 1861, it is recommended to use all three rule changes.

**15.1. Starting Bundles**

- Instead of the usual auction of Privates and Minor Companies, the initial setup includes bundles of Private and Minor Companies for sale – one to each player during the first Stock Round. Once a player has acquired a bundle, they take no further part in the Stock Round. All bundles have the same Minimum Bid.

- During the first Stock Round,starting with the player with Priority Deal, a player without a bundle must nominate one and place a bid of at least its Minimum Bid. Bids must be made in multiples of $5 and the player left of the last winner becomes the active player. When a bundle is acquired, place the treasury amounts on their respective charters then set the stock price for each Minor Company equal to half the amount placed in each treasury (rounded down).

- Players may find it useful to set up the bundles with the appropriate amount of money in each Minor
Company before beginning the auction. Some bundles come with some cash; give this to the acquirer with the Private and Minor Companies (this money may not be used to bid up on the bundle!).

**15.1.1. 3-player**
Minimum Bid: $395

- Bundle 1: Private 1, Private 5, N with $165, KB with $100, Bonus Cash: $10

- Bundle 2: Private 3, Private 4, MNN with $130, SPW with $120

- Bundle 3: Private 2, MK with $140, KK with $110, KR with $100

**15.1.2. 4-player**
Minimum Bid: $275

- Bundle 1: Private 5, N with $165, Bonus Cash: $20

- Bundle 2: Private 2, SPW with $120, RO with $100, Bonus Cash: $10

- Bundle 3: Private 1, MK with $140, KR with $100, Bonus Cash: $5

- Bundle 4: Private 3, Private 4, MNN with $130

**15.1.3. 5-player**
Minimum Bid: $220

- Bundle 1: Private 2, N with $165, Bonus Cash: $10

- Bundle 2: Private 4, MK with $140

- Bundle 3: Private 5, MNN with $130

- Bundle 4: Private 1, Private 3, SPW with $120, Bonus Cash: $5

- Bundle 5: KK with $110, KR with $100, Bonus Cash: $10

**15.2. Operating the Russian State Railway**

- The Russian State Railway has no treasury and no loans, just trains and station markers.

- During Phases 4 to 7, at the end of each set of operating rounds, just before the second Merger Round, the Russian State Railway exports the next available train from the Train Yard.

**15.3. Game End**
The end of the game is triggered by the purchase of the first 6-train. Finish the Operating Round, and play two more Operating Rounds, with a Stock Round in the usual sequence.

**Comment by perwestling** [comment]
The short variant was discussed in an 18xx chat channel, and several thought it was a good way to introduce 1861. So I think this could be a good variant to implement.
