### ISSUE TITLE
[18CZ] Vaclav - player actions show as master mode incorrectly

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#4806]
Master mode logging is related to the "player" key being set on the action hash, which is a necessity for Vaclav. The actions don't immediately show up as master mode, but when refreshing they all do; only moves taken by the wrong player should appear as master mode moves.

**Comment by Zwergenpunk** [comment]
Do you know if  that bug is related to 18cz only or could that happen in any game?

**Comment by michaeljb** [comment]
Right now it's limited to 18CZ since AFAIK that's our only game that makes a fake player where the other players must act on its behalf.

**Comment by Zwergenpunk** [comment]
I think the "problem" is here: https://github.com/tobymao/18xx/blob/8eaf548d300191109544db593c9011009f93c630/lib/engine/action/base.rb#L16

The user is set and when the user is set, the master mode log is shown.

I don't tink it is possible to adjust the action base so we have to adjust when the master mode log is shown.
