### ISSUE TITLE
[Harzbahn] The server did not accept this action due to: array cant be coerced into intiger

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#4807]
**What's your Game ID?**

https://18xx.games/game/34140?action=728

**How to Reproduce the Bug?**
- Choose QBL route  via E16-E18-E20
- press submit
- "The server did not accept this action due to: array can't be coerced into integer" message will pop up and page will be reloaded

Any other QLB route cause the same issue.

**Which Browser / Platform?**
n/a

**Comment by roseundy** [comment]
Works fine hotseat => another Ruby vs. JS bug in my code :-(

**Comment by roseundy** [comment]
Pretty much same issue as before: using a string when it should be a symbol - this time in PHASES
