### ISSUE TITLE
[1860] Variant option for expansion locomotives

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#4809]
If the designer has given the go-ahead could the expansion locomotives be implemented as a variant?

The description of the expansion says the same trains are not used each time so it may not be as straightforward. https://boardgamegeek.com/boardgameexpansion/173456/1860-locomotives-isle-wight

**Comment by roseundy** [comment]
I've already commented about this before. This is a fairly large undertaking and I'm not particularly interested in doing it.

**Comment by roseundy** [comment]
Dup of #2991
