### ISSUE TITLE
[18CO] “get slot for nil” error

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#4817]
Trying to start the Denver SLC RR and I get an error message. Should be room for the token in Denver... if not, shouldn’t the corporation be removed from the game anyway?

https://gist.github.com/benjaminxscott/e63d117c6790b2ad2d3ea17153e8ae95

**Comment by ryandriskel** [comment]
Thanks for the report. I've got my system running again so I'll take a look.
