### ISSUE TITLE
Notify player if they click to try the next rotation and there aren't any

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#482]
Trying to place a straight city.  Wanted to rotate it to connect to a different piece of track but that wasn't legal so it didn't switch.  It would have helped it it had said so.

~~Trying to rotate city tile but it won't move.~~

~~Undo, refresh, retry didn't help.~~

(Deleted game state)

**Comment by gchambers419** [comment]
Converting to feature request - Notify user if no other rotations

**Comment by gchambers419** [comment]
Similar notification for no available upgrades

**Comment by tobymao** [comment]
won't do for now
