### ISSUE TITLE
[Harzbahn 1873] Introduce autopass in auctions for players having not enough cash to bid

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4826]
**What's your idea?**

Let us know your proposed changes.

See headline and:

https://18xx.games/game/33545?action=299

where such an autopass did not happen.

**Are there related ideas?**

Other contributors may be working on something similar, [check out the list of open feature requests](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to see if there's opportunity to collaborate.

**Did you join the Slack?**

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ) and meet your fellow contributors!

**Comment by yzemaze** [comment]
@KlausKiermeier Please remove the default issue text before adding your comment/idea (next time).
