### ISSUE TITLE
[18CZ] after corporation acquistion, the acquiring corporation loses their $40 token

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#4828]
Before acquisition, BY has not yet placed their $40 token - https://18xx.games/game/34045?action=302

After acquiring BN and its three $100 tokens, BY has four $100 tokens, when it should have one $40 token and three $100 tokens - https://18xx.games/game/34045?action=303

edit to add: another case from the same game, BN acquiring EKJ. Both BN and EKJ have their $40 token, after the acquisition BN should still have exactly one $40 token

before - https://18xx.games/game/34045?action=162
after - https://18xx.games/game/34045?action=163

**Comment by michaeljb** [comment]
hmm I just found  #3957 which claims that the acquiring company does lose the $40 token.

From page 17, VIII.9 in the 18CZ rules:

> The larger company receives from the smaller company: all treasury, all local railways and all non-placed station markers. These markers may be used as additional station markers for the price of 100 K each. The stations on the map remain there and now belong to the larger company. (Exception: if both companies had station markers on the same hex, one of them must be removed from the map and returned to the charter. It may later be placed for 100 K in accordance for the rules for placing stations.) Place the smaller company charter below that of the larger one to indicate that the two companies are now one.

I don't see an instruction there for the larger company to move their $40 token to the $100 spot. Will check BGG and elsewhere.

**Comment by michaeljb** [comment]
Found a comment quoting an email from Lonny on BGG confirming that the implementation is correct - https://boardgamegeek.com/thread/2405214/article/34514502#34514502

> When a company places a token, it first counts all tokens it already has on the board, no matter if they are it's original tokens or tokens earned by acquisitions. If it's only the home token, then the next token cost $40. If it's two or more tokens then each additional token cost $100.

I'm going to add a comment in the code since I don't think this is clear from the RAW. Page 14, under VIII.6 states:

> The first additional station that a company places costs 40 K. Each further station costs 100 K.

Like Oedipussy Rex in the linked BGG thread, I never interpreted that to mean tokens placed by smaller companies which have since been acquired should count as having been placed by the larger company.

**Comment by michaeljb** [comment]
Aaaand I just saw that in #3957 they also linked to the BGG thread I also found 🤦 Sorry!

**Comment by Zwergenpunk** [comment]
:D the comment in the code helps ;) But maybe we should out it even in the wiki
