### ISSUE TITLE
[1870] Connection run when train can’t reach destination

### ISSUE THREAD

**Issue by webbtraverse08** [tobymao/18xx#4830]
Game 33001

https://18xx.games/game/33001

GMO has track connecting to destination, but doesn’t qualify for the connection run because it cannot reach. No valid connection routes can be made so the game gets stuck.

**Comment by daniel-sousa-me** [comment]
This was fixed by #4752

You have to Undo twice (to SSW's discard train action) and do the action again (don't click on Redo). This should let the game go forward. If the problem persists, clear your cache and try again.

**Comment by webbtraverse08** [comment]
Thanks! Worked.
