### ISSUE TITLE
18CZ

### ISSUE THREAD

**Issue by Magulomania** [tobymao/18xx#4833]
Hello, when playing 18CZ this happened.

We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 115
Broken action: { "type": "pass", "entity": "VBW", "entity_type": "corporation", "id": 115, "created_at": 1616887498 }
Please raise a bug report and include this link (https://18xx.games/game/34710?action=114)

**Comment by michaeljb** [comment]
Hi, there was a recent 18CZ bug fix and your game had to be archived, sorry. Thanks for alpha testing!
