### ISSUE TITLE
[Harzbahn] Blocking step Pay or Withhold Dividends cannot process action 638

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#4834]
**What's your Game ID?**
https://18xx.games/game/34140?action=637

What steps cause the unexpected behaviour?

Just open the game, and you will see the message:

```
We're sorry this game cannot be continued due to GameError: Blocking step Pay or Withhold Dividends cannot process action 638
Broken action: { "type": "buy_train", "entity": "QLB", "entity_type": "corporation", "id": 638, "created_at": 1616699734, "train": "5T-3", "price": 1200, "variant": "5T" }
Please raise a bug report and include this link (https://18xx.games/game/34140?action=637)
```

Not sure if this is a continuation of this issue:
https://github.com/tobymao/18xx/issues/4807
but the game doesn't work since then.

**Which Browser / Platform?**
n/a

**Comment by roseundy** [comment]
A bug with QLB was fixed and your game needs to be pinned to the previous version of the code.

**Comment by SirYaro** [comment]
Would you mind doing so? Atm game displays blank screen :(

**Comment by roseundy** [comment]
We are working on it, but it's proving to be harder than anticipated due to an unrelated tools change. Hopefully soon.

**Comment by roseundy** [comment]
OK, you should be good to go. You won't pick up any more additional fixes, however because one of the recent fixes changed a token cost for the QLB which affected your game.
