### ISSUE TITLE
[18FL] Game won't load

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#4842]
https://18xx.games/game/34832

- Can't link to action but it was right after LN ran a 2T and 3T with port token out of its home station.

**Comment by ventusignis** [comment]
This affects other games of 18FL as well; something that got merged to master in the last few days broke 18FL
I'll be able to look into this after work today

**Comment by jenf** [comment]
Possibly linked to https://18xx.games/game/34197 not loading.
