### ISSUE TITLE
Harzbahn 1873: Label tiles reserved for concession route as "Reserved" on tile manifest

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#4844]
While playing game 34033, link: https://18xx.games/game/34033 , I noticed a tile, #986, that would become available next phase was labeled as "none left" on the tile manifest,
![image](https://user-images.githubusercontent.com/70117294/112762341-c405ab80-8fc4-11eb-926c-4f07980d06d0.png)

 and the tile was not on the map board.
![image](https://user-images.githubusercontent.com/70117294/112762354-da136c00-8fc4-11eb-8cc3-c18b69c632f3.png)

I was in the process of filing a bug report and looking in the game history to when the corresponding tile, #974, of the current phase was placed when I noticed "Reserving tile #986 for WBE concession route in hex D15"
https://18xx.games/game/34033?action=524

I would prefer to see the reserved tile labeled as "Reserved" rather than as "none left".

**Comment by roseundy** [comment]
I've pretty much ignored displaying info about reserved tiles on the manifest, but I see the utility. It just wasn't a first priority.

**Comment by fanman80** [comment]
I appreciate you getting the game up and running before worrying about this.  It is minor.  

When I saw the "None Left" on a tile that I knew had yet to be played, I thought there might be a bug.  Then I saw the reservation statement in the history and had an "aha" moment.
