### ISSUE TITLE
[18CZ - 2p] Vaclav unable to upgrade ATE tile as SX

### ISSUE THREAD

**Issue by jason-johnson** [tobymao/18xx#4851]
**What's your Game ID?**

https://18xx.games/game/34382

One location where this can be seen is here:

https://18xx.games/game/34382?action=238

Vaclav would like to upgrade the ATE tile so he can run a decent route but as soon as he upgrades it the game gets in a weird state where both of us were shown as the active player (i.e. both underlined) but neither of us could lay the ATE token.  Not even in master mode.

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**

Mac OSX, Safari 14.03.  Not sure about the other player but we both saw this problem.

**Comment by michaeljb** [comment]
Just adding a little bit more detail.

> both of us were shown as the active player (i.e. both underlined)

I see this on the home page, but in game it is only Ezmodius who appears to be active--which is correct.

Clicking on either city raises the error banner with the message "ATE cannot lay token on <tile_id>".

This behavior should be the same as 1830's ERIE.

**Comment by Zwergenpunk** [comment]
Interesting bug, the explanation is in the PR that fixes that ;)
