### ISSUE TITLE
[18Chesapeake] Puchase of yellow shares forbidden if the player is already at cert limit

### ISSUE THREAD

**Issue by dmitryleskov** [tobymao/18xx#4852]
Confirmed as errata by the designer: 

https://boardgamegeek.com/thread/2629974/article/37361979#37361979

**Comment by dfannius** [comment]
Can you point to a game and action that demonstrates the problem?

**Comment by dfannius** [comment]
I tried to reproduce this bug and couldn't. If you find a game and action that demonstrates it, please paste it here.

**Comment by dfannius** [comment]
(Here's the gist of the test case I created, from rewinding a completed game and engineering a buy-yellow-while-at-limit situation: https://gist.github.com/dfannius/e2226dc0f15ecb679e87ec9e2aca88bf)
