### ISSUE TITLE
[1870] Granting a connection run to a company without a train capable of doing it

### ISSUE THREAD

**Issue by MarkS-choochoo** [tobymao/18xx#4853]
**What's your Game ID?**

https://18xx.games/game/32946

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

MKT made a track link from KC to its destination in Southwest here:
https://18xx.games/game/32946?action=459

After several more companies had operated, and in the following OR, the game prompted MKT to make its connection run despite having a only a 3T and 4T, neither of which is capable of making the run:
https://18xx.games/game/32946?action=501

The game is effectively hung as it will not let MKT even submit an "invalid" run that does not contain a connection run.

**How to Reproduce the Bug?**

see above

**Which Browser / Platform?**
Windows 10, Firefox 87

**Comment by daniel-sousa-me** [comment]
This has been fixed. You must been running on a cached version of the site.

Do Ctrl + Shift + R do force refresh. Then you need to Undo twice to SLSF's turn and do the action again (don't click on Undo). Now it should be working.

**Comment by MarkS-choochoo** [comment]
That worked, thanks for the fast reply. Another player tried to get past the bug via Master Mode and couldn't either, so I guess both of us were on a cached version.

**Comment by daniel-sousa-me** [comment]
Yeah, that happens often because the code is stored in static files. I'm working on a fix for that
