### ISSUE TITLE
Separate alpha and playtest games. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#4855]
I think that the site should have a separate and distinct play test category in the game selection menu. 

Currently playtest games are lumped in with alpha games. This can be misleading for two reasons:

1- it’s entirely possible that major changes in gameplay may happen from one iteration to the next, which wouldn’t normally happen with alpha games. 

2- seeing a game sitting in alpha for months at a time gives the impression that it is highly buggy and likely unplayable. 

While there Is a crossover for the purposes of alpha and playtest, I think creating distinct categories would be beneficial. It would also signal to players that the designer is looking for feedback on the design.

**Comment by jenf** [comment]
Done.
