### ISSUE TITLE
[1828.games] Merger procedure does not correctly prompt the player about which share is the "odd" share.

### ISSUE THREAD

**Issue by mlatuprosa** [tobymao/18xx#4857]
**Issue**: when a player has an odd number of shares in two companies that merge, and some shares in both, depending on the order of the merger, they may not be prompted about which share to keep, and when they are prompted the prompt does not do anything.

Link to game JSON: https://gist.github.com/mlatuprosa/158a64f10d50ade791cb95bef80cbd65

**How to Reproduce the Bug?**

- Obtain two presidencies of floated companies with an odd total number of shares. In the example game, player 2 has 60% of PRR and 30% of NW and they haven't merged yet.
- Merge the two companies in either order.
- If you merge the company with fewer shares held into the company with more shares held (NW into PRR in the example), you will be prompted about which share to keep, but regardless of which one you pick you will be prompted to sell or exchange as if you called the share in the 30% company (NW in the example) the "odd" share. 
- If you merge the company with more shares held into the company with fewer shares held (PRR into NW in the example), you are not prompted about which share to keep at all, and it considers the share in the 60% company to be the "odd" share. 

A live game with a similar issue was https://18xx.games/game/32302?action=793 where the same behavior can be seen upon merging B&M (60% held, freshly floated) into C&O (50% held, not floated) vs. merging C&O into B&M.

**Which Browser / Platform?**
- Firefox 85.02

**Comment by crericha** [comment]
The player is only prompted if it is possible for them to have a choice. The 2:1 exchange sources are 1) the player's hand, 2) discard, 3) other players, 4) IPO, and 5) bank pool. This means that if the number of 2:1 exchanges the player will do is greater or equal to the number of shares they have, in the corp that initiated the merge, then they can not opt to keep a share of that corp. 

For example, the player has 3 NW and 6 PRR shares. If the PRR merges into the NW, then the 3 NW will be needed for the exchange, so a PRR share must be the share kept. On the other hand, if NW merges into PRR, a minimum of 4 PRR shares are needed for the exchange, so the player has a choice of which share to keep.

> but regardless of which one you pick you will be prompted to sell or exchange as if you called the share in the 30% company (NW in the example) the "odd" share.
This is a bug.

**Comment by mlatuprosa** [comment]
Why do shares of the company that initiated the merge have to be involved in every 2:1 conversion? This does not seem to be implied by the phrasing of 7.5.2.4 (a) to me.

**Comment by crericha** [comment]
Its because the public company initiating the merge will become the entity for the system and thus their shares are the system shares.

**Comment by mlatuprosa** [comment]
7.5.2.4 (a) says:
- Each player trades all pairs of shares they have of either and/or both merging public companies for single shares of the new system if available 
- If  the  total  number  of  shares  the  player has of both public companies is odd, the player may freely choose which share to leave un-traded

To me, what you are saying contradicts this. I understand that in the implementation, the system as an entity is the initiator, but I would consider that to be an implementation detail, not a rule to be enforced.

**Comment by crericha** [comment]
There is no rule being enforced. The player decides when they start the merge as that corporation becomes the system. This is the same behavior for mergers in 1817, 1861, 1867, etc.

**Comment by mlatuprosa** [comment]
My point is that the behavior you described, where every pair of shares exchanged for system shares must contain at least one share from the initiator of the merge, isn't stated anywhere in the printed rules. 

This is irrelevant in all three of those examples because in those games there is no such thing as an "odd share". The other 18xx title that I know of with somewhat similar behavior is 18C2C, but in that game odd shares are just lost and so it does not matter "which one" you lost.

**Comment by crericha** [comment]
Okay, I think I see where your confusion is now.

As per "7.5.2.1 Share trading process", the system share comes from the first available source in the following order: 1) the player's shares, 2) discarded shares, 3) other players, 4) IPO, and 5) bank pool.

If the player has 3 NW and 6 PRR and are merging PRR into NW, their first 3 system shares will come from the those 3 NW shares. After that point, they will have 3 PRR shares and will use one of the other sources to get their last system share, with the remaining PRR share being the odd share.

**Comment by bubba0077** [comment]
Here's how I read the rules as written:

Per 7.5.2.1, the first source of shares is the player's shares _of those being traded in_. 7.5.2.4 (a) is clear that you get to choose which of the odd shares to not trade (and be handled later in (b)). So if you choose one of the smaller holding to be the odd share, it's not available to be used as a system share yet (in the physical game, the system shares are held face-down to prevent confusion).

**Comment by crericha** [comment]
The implementation matches my understanding of the rules. Feel free to reach out to JC and if he concurs with your interpretation, I'll change it.

**Comment by mlatuprosa** [comment]
I reached out to him on BGG, we'll see if he replies.
