### ISSUE TITLE
18FL private problem

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#4866]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by saxafras** [comment]
Have played 2 FL games where the private allowing a token anywhere, then makes that city not upgradeable or the entities tab fails to work.

**Comment by ventusignis** [comment]
I've found a fix for the entities tab breaking; do you have links for the games where you see this behavior? `then makes that city not upgradeable`

**Comment by saxafras** [comment]
https://18xx.games/game/34585   This one now not loading as well.  (east of Tampa)

Id: 34275  This one we manually ended.  (Tampa)

**Comment by ventusignis** [comment]
Game 34585 is working now, this PR fixed that

https://github.com/tobymao/18xx/pull/4869

**Comment by ventusignis** [comment]
I was able to replicate the issue in game 34275 and I'll fix that sometime tomorrow

**Comment by ventusignis** [comment]
For 34275 it errored out on action 97 - this game started a little before the fix for home tokens (all home stations start laid on the map; so SR's lay beyond yellow tampa was illegal due to tampa being tokened out by the unstarted ACL)

https://18xx.games/game/34275?action=97

Do you have any other example games with issues in Tampa?
