### ISSUE TITLE
Displaying tile counts in a more visually intuitive way

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#4868]
When playing online I find it hard to get a sense of how many of each tile remain. When playing in real life this isn't a problem, as you can easily get a sense of how many remain from the depth of the pile. 

I wonder if the tiles could be represented visually in a 'pile' using a 3D overlapping effect, as in this [mock-up](https://docs.google.com/drawings/d/1mwCdXbFAw8B1VBBBddqs2mXya3rrRRrcVW2_HIbTiIk/edit?usp=sharing), which displays a pile of 4 and 2 tiles respectively. 

In addition, in the interests of reducing information overload, perhaps there could be a checkbox allowing users to display only the tile count, and not the roster number,so "\#3 x 2" becomes simply "2".

**Comment by yzemaze** [comment]
> I wonder if the tiles could be represented visually in a 'pile' using a 3D overlapping effect, as in this [mock-up](https://docs.google.com/drawings/d/1mwCdXbFAw8B1VBBBddqs2mXya3rrRRrcVW2_HIbTiIk/edit?usp=sharing), which displays a pile of 4 and 2 tiles respectively.

This could be done, but would need a lot of work to look as nice as you imagine *and* work with the current environment. Look closely and you’ll spot the problems …
![image](https://user-images.githubusercontent.com/33390595/112944385-09e08200-9133-11eb-9c5d-3937046bbefb.png)
=> bad benefit-cost ratio

> In addition, in the interests of reducing information overload, perhaps there could be a checkbox allowing users to display only the tile count, and not the roster number,so "#3 x 2" becomes simply "2".

That’s a good idea. I’ll take a look.
