### ISSUE TITLE
1849 last certificate purchaseable from treasury even when there is 50% in market

### ISSUE THREAD

**Issue by Narvinyar** [tobymao/18xx#4875]
Last certificate was purchased despite 50% being available in the open market. Rulebook says "It is not possible to purchase
the “last certificate” from either location if a normal certificate is
available."

https://18xx.games/game/34753?action=316

![image](https://user-images.githubusercontent.com/77132865/112934508-86378d00-9154-11eb-8ebf-ec75c067edf7.png)

**Which Browser / Platform?**
Chrome Version 89.0.4389.90

**Comment by dfannius** [comment]
I assume Narvinyar closed this because it's the correct behavior. The rule quoted is from section 9.6 in the AAG rules and is ambiguous, but the end of section 9.3 makes the correct rule clear.
