### ISSUE TITLE
18FL- clicking around Miami

### ISSUE THREAD

**Issue by BGarmon80** [tobymao/18xx#4881]
Game 34167 as an example. 

On Android using Firefox.

Trying to click on Miami to upgrade only works when I click on the left side of the tile. Once I finally got the upgrade to be selected, I couldn't confirm by clicking the check.

**Comment by BGarmon80** [comment]
It appears that the game is now frozen at loading.

**Comment by yzemaze** [comment]
Loads fine. If you still would like to close, you can do it yourself now.
