### ISSUE TITLE
[1846] Steamboat Token remains in Brown when private not bought in

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#4884]
https://gist.github.com/OedipussyRex/ebfc8983f20f50aa8b38bb3e68856d02

The first Brown train has been purchased and the token for Steamboat remained on the board even though the private was owned by a player, not a corporation. In this case, the port bonus is supposed to go away when the private closes.

**Comment by benjaminxscott** [comment]
Is there a rules reference or BGG errata to confirm this?

(I don't see a SC exception to the "markers stay until gray" rule, presumably the assignment and markers would stay)
• Remove Private Companies (but not markers), except the Mail
Contract (provided it is owned by a corporation, not a player).

**Comment by dfannius** [comment]
My first assumption would be that any access that has previously been granted remains and that it doesn't have to be actively renewed every OR (which would mean that the current implementation is correct). Probably worth asking Tom on BGG.

**Comment by OedipussyRex** [comment]
Here we go. https://boardgamegeek.com/thread/2015186
In this thread the question is asked: "If the steamboat private is still in the payers hands on the phase change that closes the private, do the tokens go with it?"
To which Tom Lehmann replies: "Yes."

You'll probably also note my participation in that thread.
