### ISSUE TITLE
[18Ches] Green tile upgrade rotation allowed that changes original track

### ISSUE THREAD

**Issue by jeffobocko** [tobymao/18xx#489]
In hex L4, the yellow track was a sharp curve from K3 to New York. When upgrading, I clicked on the upgrade that added a gentle curve to the sharp curve, and it changed where the sharp curve went from the previous tile. Now it went down to K5 instead of up to L2 (NY).

![L4](https://user-images.githubusercontent.com/50852698/82744499-5c992280-9d47-11ea-8cd2-b6c9015ad41c.png)

**Comment by jeffobocko** [comment]
Here is the code from the two tile lays if that helps:

 yellow
 {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 237,
      "hex": "L4",
      "tile": "7-0",
      "rotation": 2
    }, 
 
 upgrade
 {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 482,
      "hex": "L4",
      "tile": "29-0",
      "rotation": 1
    },

**Comment by tobymao** [comment]
dup
