### ISSUE TITLE
[1860] Unable to buy shares "Comparison of Number with NilClass failed"

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#4892]
https://18xx.games/game/34865

Cannot buy any shares, immediately get an error message:  "Comparison of Number with NilClass failed". Have cash and cert space.

**Comment by roseundy** [comment]
This looks like an auto-actions issue.
@jenf can you take a look?

**Comment by roseundy** [comment]
It seems that an auto-buy of BHI&R was programmed until it floated. It has floated, but activate_program_buy_shares is still being called.

**Comment by roseundy** [comment]
Looking at the JSON, I wonder if the auto actions has a bad interaction with the home_track lay that BHI&R had when floated.

**Comment by jenf** [comment]
Very weird, somehow they've programmed buy shares but not actually programmed what they wanted

    {
      "type": "program_buy_shares",
      "entity": 316,
      "entity_type": "player",
      "id": 350,
      "created_at": 1617231036,
      "corporation": "BHI&R"
    },

**Comment by pstone1** [comment]
It seems to have fixed itself, guess you helped out on the back end, thanks

**Comment by jenf** [comment]
the other player disable their auto action.
