### ISSUE TITLE
[1822] "undefined method `use!' for nil" when using English Channel ability (P5-LC&DR)

### ISSUE THREAD

**Issue by TheNarratorSA** [tobymao/18xx#4893]
Using Firefox on desktop. Game is 32937: https://18xx.games/game/32937
Starting from this action: https://18xx.games/game/32937?action=872

Playing as LYR and attempting to use the P5-LC&DR English Channel ability. After clicking on "move an exchange station token to the available station token section" button I get the following error messsage:
![image](https://user-images.githubusercontent.com/81725897/113234692-1c022200-92e5-11eb-862a-7a513e38403c.png)
And the action fails with no progress.

**Comment by magnusfalt** [comment]
The problem was that LYR didnt have any exchange tokens left. The bug was that the ability shouldnt have been seen.
