### ISSUE TITLE
[General] Password change

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#4895]
Hi.

For some security reasons I need to change my password. I was told to open a bug ticket to do that. 
How can proceed with change?

And I just need to ask that. What is the reason to hide such core security feature from public?

**What's your Game ID?**
n/a

**How to Reproduce the Bug?**
n/a

**Which Browser / Platform?**
any

**Comment by yzemaze** [comment]
If it’s urgent: logout, then use password reset via login – [forgot password](https://18xx.games/forgot)

**Comment by SirYaro** [comment]
Thank you so much
