### ISSUE TITLE
Illegal tile placement possible (game id 34)

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#49]
D3 was placed by Tosu electric railway
![0A7C5AC3-6C1A-4DEE-B46D-51EB58BA3CD2](https://user-images.githubusercontent.com/63635335/79384707-ad0eaa80-7f67-11ea-9620-1eaba73788ac.png)

**Comment by tobymao** [comment]
are you referring to J5? is that illegal?

**Comment by MoshiMaro** [comment]
D3 by Tosu

**Comment by tobymao** [comment]
what's illegal about it?

**Comment by tobymao** [comment]
ah it's because it's blocked?

**Comment by MoshiMaro** [comment]
Uwajima Token in Ohzu should block or not?

**Comment by tobymao** [comment]
correct, thanks for the report.
