### ISSUE TITLE
18chesapeake - corporation forced to buy train despite no valid route

### ISSUE THREAD

**Issue by WeeMadAndo** [tobymao/18xx#490]
18Ches rules state that train is only required to be purchased once a valid revenue route is created. See screenshots - PLE has multiple locations, but not revenue routes, however no option to skip train purchase. 

![Screenshot_20200524-211602](https://user-images.githubusercontent.com/65803330/82752847-4f8e3900-9e04-11ea-9257-1e5b88f30678.png)
![Screenshot_20200524-211630](https://user-images.githubusercontent.com/65803330/82752849-52892980-9e04-11ea-8b02-68317ebb16f2.png)

**Comment by dfannius** [comment]
Can you paste the JSON from your game? (Tools / Copy Data)

**Comment by WeeMadAndo** [comment]
{
  "id": 1144,
  "description": "Launceston Learners",
  "user": {
    "id": 418,
    "name": "WeeMadAndo"
  },
  "players": [
    {
      "id": 768,
      "name": "Eucalypt"
    },
    {
      "id": 418,
      "name": "WeeMadAndo"
    },
    {
      "id": 423,
      "name": "Sparky"
    }
  ],
  "max_players": 6,
  "title": "18Chesapeake",
  "settings": {
    "seed": 4.15218167784604e+37
  },
  "status": "active",
  "turn": 5,
  "round": "Operating Round",
  "acting": [
    418
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 1,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 2,
      "company": "Chesapeake and Ohio Canal",
      "price": 85
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 3,
      "message": "Reading the rules is for suckers. Let's do this!"
    },
    {
      "type": "bid",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 4,
      "company": "Columbia - Philadelphia Railroad",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 5,
      "company": "Cornelius Vanderbilt",
      "price": 205
    },
    {
      "type": "bid",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 6,
      "company": "Cornelius Vanderbilt",
      "price": 210
    },
    {
      "type": "bid",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 7,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 8,
      "company": "Baltimore & Ohio Railroad",
      "price": 105
    },
    {
      "type": "message",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 9,
      "message": "Are you calling me a sucker?   What else was I supposed
to do with anew game while in lockdown?"
    },
    {
      "type": "bid",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 10,
      "company": "Baltimore & Ohio Railroad",
      "price": 110
    },
    {
      "type": "pass",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 12,
      "message": "I was g"
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 13,
      "message": "Ugh"
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 14,
      "message": "Ugh I was going to use the comparison site to figure out
the rules once we start, but Chesapeake isn't on it."
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 15,
      "company": "Delaware and Raritan Canal",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 17,
      "company": "Baltimore & Ohio Railroad",
      "price": 115
    },
    {
      "type": "bid",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 18,
      "company": "Baltimore & Ohio Railroad",
      "price": 120
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 19,
      "company": "Baltimore & Ohio Railroad",
      "price": 125
    },
    {
      "type": "pass",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "message",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 21,
      "message": "Is the Vanderbilt Pres a PLE or PRR? I've had it display
both. What is it showing for others?"
    },
    {
      "type": "message",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 22,
      "message": "Umm I thought it was prr. It’s showing ple now. "
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 23,
      "company": "Cornelius Vanderbilt",
      "price": 215
    },
    {
      "type": "bid",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 24,
      "company": "Cornelius Vanderbilt",
      "price": 220
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 25,
      "message": "Ple for me"
    },
    {
      "type": "message",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 26,
      "message": "Hmm. I'll log that issue."
    },
    {
      "type": "message",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 27,
      "message": "PLE or PRR both worked for me so I kept on with it. If it
suddenly became something in the other corner I'd be upset."
    },
    {
      "type": "bid",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 28,
      "company": "Cornelius Vanderbilt",
      "price": 225
    },
    {
      "type": "bid",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 29,
      "company": "Cornelius Vanderbilt",
      "price": 230
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 30
    },
    {
      "type": "par",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 31,
      "corporation": "PLE",
      "share_price": "95,2,4"
    },
    {
      "type": "par",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 32,
      "corporation": "PRR",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 33,
      "corporation": "SRR",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 34,
      "corporation": "B&O",
      "share_price": "80,3,3"
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 35,
      "share": "PRR_1"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 36,
      "share": "SRR_1"
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 37,
      "share": "B&O_2"
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 38,
      "share": "PRR_2"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 39,
      "share": "SRR_2"
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 40,
      "share": "B&O_3"
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 41,
      "share": "PRR_3"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 42,
      "share": "SRR_3"
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 43,
      "share": "B&O_4"
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 44,
      "share": "PRR_4"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 45,
      "share": "SRR_4"
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 46,
      "message": "I already see about 18 things I could have done better."
    },
    {
      "type": "message",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 47,
      "message": "I'm realising that I have made mistakes too."
    },
    {
      "type": "message",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 48,
      "message": ""
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 49,
      "message": "It will make the face to face game less stressful"
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 50,
      "share": "SRR_5"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 51,
      "share": "PRR_5"
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 53,
      "share": "B&O_5"
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "pass",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 56,
      "hex": "G7",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 57,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 59,
      "hex": "F2",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 60,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "id": 62,
      "hex": "H4",
      "tile": "57-1",
      "type": "lay_tile",
      "entity": "SRR",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 63,
      "type": "undo",
      "entity": "SRR",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 64,
      "hex": "H4",
      "tile": "57-1",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 65,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 67,
      "share": "PRR_6"
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 68,
      "share": "B&O_6"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 69,
      "share": "B&O_7"
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 70,
      "share": "PRR_7"
    },
    {
      "type": "pass",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 73
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 74,
      "hex": "F8",
      "tile": "X1-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 75
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 76,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 77,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 78
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 79,
      "hex": "E3",
      "tile": "57-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 80
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 81,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 82,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 83
    },
    {
      "type": "lay_tile",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 84,
      "hex": "I5",
      "tile": "3-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 85
    },
    {
      "type": "run_routes",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 86,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "H4",
              "I5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 87,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 88
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 89,
      "share": "B&O_8"
    },
    {
      "type": "message",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 90,
      "message": "All these bloody town hexes!"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 91,
      "share": "PRR_8"
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "pass",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 94
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 95,
      "hex": "E7",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 97,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 98,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 99,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 101,
      "hex": "D4",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 102
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 103,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 104,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 106
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 107
    },
    {
      "type": "run_routes",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 108,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "H4",
              "I5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 109,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 111,
      "share": "SRR_6"
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 112,
      "share": "SRR_7"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 113,
      "share": "PLE_1"
    },
    {
      "type": "buy_share",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 114,
      "share": "SRR_8"
    },
    {
      "type": "pass",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 115
    },
    {
      "type": "pass",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 116
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 118,
      "hex": "D8",
      "tile": "57-3",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 119,
      "city": "57-3-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 120,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "D8",
              "E7",
              "F8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 121,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 122
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 123,
      "hex": "C5",
      "tile": "57-4",
      "rotation": 1
    },
    {
      "id": 124,
      "city": "57-4-0",
      "slot": 0,
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation"
    },
    {
      "id": 125,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation"
    },
    {
      "id": 126,
      "city": "57-2-0",
      "slot": 0,
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation"
    },
    {
      "id": 127,
      "type": "undo",
      "entity": "PRR",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 128
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 129,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "E3",
              "F2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 130,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 131,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 132
    },
    {
      "id": 133,
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation"
    },
    {
      "id": 134,
      "type": "undo",
      "entity": "SRR",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "lay_tile",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 136,
      "hex": "G3",
      "tile": "58-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 137
    },
    {
      "type": "run_routes",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 138,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "G3",
              "H4"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 139,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 140,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "buy_train",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 141,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 142
    },
    {
      "id": 143,
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation"
    },
    {
      "id": 144,
      "type": "undo",
      "entity": "WeeMadAndo",
      "entity_type": "player"
    },
    {
      "type": "buy_company",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 145,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 146
    },
    {
      "type": "buy_share",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 147,
      "share": "PLE_2"
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 148,
      "share": "PLE_3"
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "sell_shares",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 151,
      "shares": [
        "PRR_5"
      ],
      "percent": 10
    },
    {
      "type": "buy_share",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 152,
      "share": "PLE_4"
    },
    {
      "type": "pass",
      "entity": "Eucalypt",
      "entity_type": "player",
      "id": 153
    },
    {
      "type": "pass",
      "entity": "WeeMadAndo",
      "entity_type": "player",
      "id": 154
    },
    {
      "type": "pass",
      "entity": "Sparky",
      "entity_type": "player",
      "id": 155
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 156,
      "hex": "C9",
      "tile": "8-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 157
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 158,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "D8",
              "E7",
              "F8"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 159,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 160
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 161
    },
    {
      "type": "buy_company",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 162,
      "company": "Chesapeake and Ohio Canal",
      "price": 160
    },
    {
      "type": "lay_tile",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 163,
      "hex": "D2",
      "tile": "57-5",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 164,
      "city": "57-5-0",
      "slot": 0
    },
    {
      "id": 165,
      "type": "buy_train",
      "price": 180,
      "train": "3-4",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 166,
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 167,
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 168,
      "type": "undo",
      "entity": "SRR",
      "entity_type": "corporation"
    },
    {
      "id": 169,
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 170,
      "type": "undo",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "type": "buy_train",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 171,
      "train": "3-4",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 172
    },
    {
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation",
      "id": 173
    },
    {
      "type": "lay_tile",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 174,
      "hex": "H4",
      "tile": "15-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 175
    },
    {
      "type": "run_routes",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 176,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "G3",
              "H4"
            ]
          ]
        },
        {
          "train": "3-2",
          "connections": [
            [
              "H6",
              "I5"
            ],
            [
              "H4",
              "I5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 177,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "pass",
      "entity": "SRR",
      "entity_type": "corporation",
      "id": 179
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 180,
      "hex": "B6",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 181,
      "city": "57-4-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 182,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "A7",
              "B6",
              "C5"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "E3",
              "F2"
            ],
            [
              "C5",
              "D4",
              "E3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 183,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 184,
      "train": "3-5",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 185
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 186
    }
  ],
  "created_at": "2020-05-23",
  "updated_at": "2020-05-24"
}

**Comment by dfannius** [comment]
Note to developers: `Round::Operating::must_buy_train?` is currently marked as a hack that doesn't completely support the correct rule, so this is not a surprise (although of course it needs to be fixed).
