### ISSUE TITLE
[1828.games] Game state frozen during SR1 merge.

### ISSUE THREAD

**Issue by edvinvoneuler** [tobymao/18xx#4901]
Game: https://18xx.games/game/35420 
It is currently in the frozen state but I messed around a bit in Master Mode to see if it was reproducible within the same game.

gist with game json: https://gist.github.com/edvinvoneuler/34a9d501ab5c32d881048d65c80d62b6

**How to Reproduce the Bug?**

- During SR1 one player merged two corps, MC into GT (see screenshot for share distribution and liquid cash)
- The first minority shareholder chose "Exchange".
Notes:
It works to merge GT into MC, this doesn't present the frozen "choose player" option.
It works if the player chooses "Sell" instead of "Exchange"

![image](https://user-images.githubusercontent.com/39345445/113302071-fe8e8180-92ff-11eb-8d8a-fefb327bfd40.png)

- Browser Version: Chrome 89.0.4389.90
- Platform: Desktop

**Comment by crericha** [comment]
Thank you for the bug report. The issue has been fixed.
