### ISSUE TITLE
1870 game cannot be continued due to GameError

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4903]
https://18xx.games/game/33785

We're sorry this game cannot be continued due to GameError: 15 is not upgradeable to 63
Broken action: { "type": "lay_tile", "entity": "GMO", "entity_type": "corporation", "id": 543, "created_at": 1616973717, "hex": "C18", "tile": "63-0", "rotation": 0 }
Please raise a bug report and include this link (https://18xx.games/game/33785?action=542)

**Comment by daniel-sousa-me** [comment]
Game needs to be archived or pinned to anything before e08ae0e75

**Comment by jeroenh** [comment]
Daniel also meant to say that this particular problem has been fixed in 79b37d2

**Comment by jenf** [comment]
Archived...
