### ISSUE TITLE
18FL 10-share upgrade

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#4908]
In game https://18xx.games/game/34585?action=181, Skipping from SR to SAL, OR 4.1 going into 4.2, no option to convert to 10-share given

**Comment by saxafras** [comment]
34585.  Skipping from SR to SAL, OR 4.1 going into 4.2, no option to convert to 10-share given

**Comment by ventusignis** [comment]
At the action in the linked game the SR is already a 10 share corporation at the start of it's turn, so it cannot convert twice.
Is that the correct action in the game @saxafras ?

**Comment by jenf** [comment]
game no longer exists, question not answered closing.
