### ISSUE TITLE
Request - 1861 - 2 Player Variant

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#4909]
Can we have the 2-player variant added as an option to 1861 please?

This can be with or without the short game options - see #4803

**Comment by jenf** [comment]
1861 and 1867 already supports 2 players

**Comment by ianwilson156** [comment]
Great!
When you start a game, it defaults to 3 players and you can change it 
upwards or downwards - I just hadn't noticed the 'downwards' bit.


------ Original Message ------
From: "Jennifer Freeman" ***@***.***>
To: "tobymao/18xx" ***@***.***>
Cc: "ianwilson156" ***@***.***>; "Author" 
***@***.***>
Sent: Friday, 2 Apr, 21 At 20:50
Subject: Re: [tobymao/18xx] Request - 1861 - 2 Player Variant (#4909)


1861 and 1867 already supports 2 players
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/tobymao/18xx/issues/4909#issuecomment-812684883> , 
or unsubscribe
