### ISSUE TITLE
[1870] Frisco didn't get Destination Run

### ISSUE THREAD

**Issue by BobProbst** [tobymao/18xx#4911]
https://18xx.games/game/33299
I believe Frisco should have gotten a destination run in OR5.2 (E12-H13-M20-M22 with a 4 train)
am I misunderstanding something?
it is a pinned game so maybe it's already corrected in the current version
It is pinned to version 5eab45d72,

**Comment by jeroenh** [comment]
destination run should have happened here: https://18xx.games/game/33299?action=556
Some changes have been made to connection detections, the graph and related things. I'm 90% certain the new code would detect the connection run.

**Comment by daniel-sousa-me** [comment]
If it's pinned it's almost certainly that

**Comment by daniel-sousa-me** [comment]
On the beginning I was annoyed by alpha games getting deleted instead of pinned, but now I 100% understand the decision
