### ISSUE TITLE
Easier way to determine what's happened since last move

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#492]
It's easy to skip what happened since your last move, it'd be nice if we could improve it.

* Highlight text and actions since your last move maybe in a different colour
* Maybe on the review history have a "goto my last turn" so you can step through

**Comment by ChrisTheCat** [comment]
An instant replay since your last turn is a common feature in apps like Through the Ages.

**Comment by jenf** [comment]
This is covered by other tickets
