### ISSUE TITLE
Unable to change logo colour, stop receiving emails or change password

### ISSUE THREAD

**Issue by Christopher-Annandale** [tobymao/18xx#4920]
**How to Reproduce the Problem?**

What steps cause the unexpected behaviour?

I tried to change my password using the forgotten password link. The message I received after trying reads "name may not be empty".

![image](https://user-images.githubusercontent.com/56683869/113444561-07f51800-93ec-11eb-8b59-0ed6f9cc6fa0.png)

I decided that I didn't like the red 18xx logo anymore and that I was receiving too many emails so I unchecked the boxes and touched nothing else. Save changes and get the same message "name may not be empty"

![image](https://user-images.githubusercontent.com/56683869/113444676-468ad280-93ec-11eb-8dea-0ccbd1bdc797.png)

**Which Browser / Platform?**
Chrome Version 88.0.4324.190 (on Desktop)
Samsung Internet version 13.2.2.4 (on mobile)

**Comment by yzemaze** [comment]
I can’t reproduce these problems. Password reset and changes to profile settings work fine.

**Comment by Christopher-Annandale** [comment]
Logging out and in doesn't seem to affect it on either device or browser.
I recently changed the colour scheme from default to darker without issue. Have just tried changing the hotseat game colour from purple to green, resetting to default, manually changing the colours back to default, saving the changes and all of them caused the error message.

I will send smaller images in future.

**Comment by Christopher-Annandale** [comment]
I won't open another issue but whatever you did, it didn't work :(
