### ISSUE TITLE
QoL - 1817 - More Prominent Liquidation Warning

### ISSUE THREAD

**Issue by Anzelak** [tobymao/18xx#4924]
I am new to 18xx and new to 1817 and have been stumbling through teaching this excellent game to many new people.

On several occasions, especially in async games, inexperienced players conduct OR turns that cause their company to go into liquidation through failure to make their interest payments. They don't realise this until the end of the OR round and are frustrated that there was an action available that would have avoided liquidation. 

I'm aware you make the "interest due" yellow in the company card but this normally sits below the fold in the current UI beneath available trains.

![image](https://user-images.githubusercontent.com/81834688/113459751-5f0be480-940e-11eb-92bc-fb61ad08f062.png)

It would be good if the "Xcompany cannot afford $yyy interest and goes into liquidation, transferring $zzz to Player1" could be made bold in the chat.

Alternatively, or additionally, a text based warning beneath Done (Trains) could read something like: Warning: completing this turn will cause Xcompany to go into liquidation! Bad example:

![image](https://user-images.githubusercontent.com/81834688/113459869-c2961200-940e-11eb-9c69-af3c22e82d6a.png)

I note you already have excellent warnings to this effect for paying in full/half/withholding, and these are incredibly helpful. I think the above would be great too.

Cheers!

**Comment by Anzelak** [comment]
Similiar to the above, it would be good if the same interest-paying warning could caution players that their company will slip into acquisition, too.

**Comment by jenf** [comment]
dup of #2600
