### ISSUE TITLE
[1817] - ID 24083 game cannot be continued due to GameError: Blocking step Lay Track

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#4925]
This game was previously pinned on a different update, more than a week ago. But today it’s entered this stuck state. Can it be repaired? This is one of those very long running async games. All your help is appreciated. 

https://18xx.games/game/24083?action=1539

**Comment by jenf** [comment]
Fixed, i've deleted the last few actions.

**Comment by yoyoson** [comment]
Amazing, thank you @jenf!
