### ISSUE TITLE
Auto-order on auctions (1817 style and so on

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#4928]
Basically the idea is to have 1 (or 2) additional bid options

One would be, bid up to X and then pass the auction
The other would be, bid up to X, then let me figure it out

So lets say it's an acquisition bid on 1817, if player A set X at 350, B at 300 and C at 150, then player A would automatically win the bid, and pay 310 (just enough to outbid player B)

The second alternative is just so people can say "i'll bid up to 300 for sure, so let's do that, and if anyone is still on after that i'll think a bit more

It's also useful when you have different tiers of bid, for instance, player B in the previous case could be fine letting A take it for 200, but if there is a chance player C would take it then player B may not be ok with letting it go for less than 300.

**Comment by ryandriskel** [comment]
Any progress on this one @magnusrk-ch ? I happened to independently be working on the same functionality.

**Comment by slapphappyjazz** [comment]
This would also be useful for the auction in 1860.
