### ISSUE TITLE
Show Corporation-Owned Private Companies on the Map

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#493]
The current implementation is that private companies with blocking hexes are shown on the map when the game begins, but then are removed once they are purchased by a corporation.

![image](https://user-images.githubusercontent.com/29106780/82755249-0c967c00-9d98-11ea-904a-0007a8160f97.png)

- This is good because that shows the user that the hexes are no longer blocked.
- This is bad because some private companies have special powers that can be used when they are in the corporation. Players may forget to use useful powers since they are no longer displayed.

In the physical game, the change in state is not reflected at all on the board. This is okay, because we can check where the privates reside easily enough. However, in an electronic version, we have the opportunity to change the display when the state changes from "blocked" to "not blocked and special power can be used here."

I propose to recolor the private company once it is corporation-owned. Perhaps blue or red.

Once a private company closes, then I think it is fine to completely remove it from the map.

**Comment by gchambers419** [comment]
Is there enough empty space in a typical such hex to add a "no build" icon next to the company symbol?
