### ISSUE TITLE
[Harzbahn 1873] Laying track and building stations on other companies' concession routes...

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4936]
**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33488

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- During Operating Round 8.1, the SHE built a station in E6 (undone afterwards). That was possible and was correct, although the station was built on an NWE concession hex with the NWE not yet operating, since there was another free station circle on the reserved tile 970.
- This was action https://18xx.games/game/33488?action=877
- But previously, during the same Operating Round 8.1, the WBE, after building the tile 962 on D7 (action https://18xx.games/game/33488?action=870), tried to build also a station there. That was not allowed by the system although it should have been allowed since on the reserved tile 975 there is indeed a free station circle so that such a station building by the WBE did "not prevent the [concession] company from building a station in the same hex of its concession route during its first OR" (see Rule 4.4.2).

By the way: could it be checked please if the following is implemented correctly: 
- If  company A builds on the concession route of company B a tile of exactly the reserved tile type: does it actually use the reserved tile (this should be the case), or does it use another one of the same type, thus "freeing" the reserved tile.
- This is important since if this is not correctly implemented, this would mean that only company B could build this tile if all other tiles of this type were currently placed on the map.

Klaus Kiermeier

**Comment by roseundy** [comment]
OK, I'll check the station issue.

For the second issue, the way I have this implemented only the concession company can place a reserved tile. It was not clear to me in the rules that a reserved tile could be used by any other company.  From the rules:

"If the corresponding company later builds its concession route, such reserved tiles are then used...."

Note that it doesn't say "if any company".

**Comment by KlausKiermeier** [comment]
Mmh, you are right, the rules' wording is done here in such a way that you have to understand it your way. 
This is a bit unfortunate since the reasoning behind all this reservation stuff was, of course, to make it always possible to build the concession routes. Not to block some tiles for no reason. 

Nevertheless, this should be a very very very ... rare case that a tile is reserved and no other tile of the same type is available to be built on the particular hex. Even here, it wouldn't have been the case, since other tiles of the same type would have been available. And since I don't want to go again deeper into rules amendments, I think we should leave it as it is: the rules as well as your implementation.

But the issue concerning the station placement you should still consider!

Thanks again, Steve,
Klaus
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Laying track and building stations on other companies' concession routes... (#4936)
Datum: 2021-04-03T19:45:32+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
OK, I'll check the station issue.
For the second issue, the way I have this implemented only the concession company can place a reserved tile. It was not clear to me in the rules that a reserved tile could be used by any other company. From the rules:
"If the corresponding company later builds its concession route, such reserved tiles are then used...."
Note that it doesn't say "if any company".
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/4936#issuecomment-812900110", "url": "https://github.com/tobymao/18xx/issues/4936#issuecomment-812900110", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿

**Comment by roseundy** [comment]
I won't just consider it, I will fix it! I see in the rules where this case is covered. I just didn't think it through.
