### ISSUE TITLE
18Chesapeake: Export of first 3T does not increase ORs following next SR

### ISSUE THREAD

**Issue by mfwesq** [tobymao/18xx#494]
Here is JSON demonstrating issue:

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Delaware and Raritan Canal",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Columbia - Philadelphia Railroad",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "Baltimore and Susquehanna Railroad",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "Chesapeake and Ohio Canal",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Baltimore & Ohio Railroad",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "Cornelius Vanderbilt",
      "price": 200
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "corporation": "PRR",
      "share_price": "95,2,4"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "corporation": "B&O",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "corporation": "LV",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "corporation": "C&A",
      "share_price": "70,4,2"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "share": "B&O_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "share": "LV_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "share": "C&A_1"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "share": "B&O_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "share": "LV_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "share": "C&A_2"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "share": "B&O_4"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "share": "LV_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "share": "C&A_3"
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "share": "LV_4"
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21,
      "share": "C&A_4"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 25,
      "hex": "G7",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 26,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 27,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 28
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 29,
      "hex": "J2",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 30,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 31
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 32,
      "hex": "J6",
      "tile": "57-1",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 33
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 35,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 36,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 41,
      "hex": "F8",
      "tile": "X1-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 42
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 43,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "F8",
              "G7",
              "H6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 44,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 45,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 47
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 48,
      "hex": "J2",
      "tile": "15-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 49
    },
    {
      "type": "run_routes",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 50,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "J2",
              "K1"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 51,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 52,
      "train": "3-2",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 55,
      "hex": "J4",
      "tile": "X4-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 56
    },
    {
      "type": "run_routes",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 57,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "J4",
              "J6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 58,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 59
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18Chesapeake",
  "description": "",
  "max_players": "6",
  "id": "hs_1590331566",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-05-24",
  "result": {}
}

**Comment by scottredracecar** [comment]
I just tried your JSON and it worked okay for me. The export happens at the end of the OR set so it was SR-OR3.1-OR3.2-SR which is correct.

**Comment by mfwesq** [comment]
I guess I was not explicit and clear enough. Here is what happened. I have marked where things happened that are not in accordance with the RAW.

0. OR1: Seven 2Ts are bought.
1. End of OR1: The FIRST 3T was exported
2. SR2: passes
**WRONG>>>>>>>**3. End of OR2.1: The SECOND 3T was exported **SHOULD BE OR2.2**
**WRONG>>>>>>>**4. SR3

**Comment by scottredracecar** [comment]
It correctly goes to OR2.2 when I put the JSON in.

Maybe try it again. It looks like toby fixed this in the update he made when he closed the issue.

**Comment by tobymao** [comment]
this was indeed broken, but i fixed it

**Comment by mfwesq** [comment]
Great! Thanks for your hard work on this site. We'll be trying again tomorrow. Looks like the tile-laying privates are also working now.
