### ISSUE TITLE
[1861] Add a Train Trade in optional Rule

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#4940]
1867 added the ability to trade in 5 and higher trains for a discount of half their face value on a new train, which adds a fair bit of decision space for how end game companies end up. This seems like it would be a good optional rule for 61, and is hopefully easy to implement since it is already set up for 67.

**Comment by jenf** [comment]
@ianwilson156 any thoughts on this? We're generally against non-official optional rules. So it's if something you feel is valid it can be done.

**Comment by ianwilson156** [comment]
This has been discussed off and on over the past few years. I think it is ok, as long as it is agreed at the beginning of the game.
