### ISSUE TITLE
[1846] missing operating round for IC

### ISSUE THREAD

**Issue by Dit-ben-ik** [tobymao/18xx#4941]
1846: 
In operating round 2.2 IC did not get a chance to run.

![1846_bug](https://user-images.githubusercontent.com/81877725/113488936-7a83f780-94c1-11eb-9657-1aeef07ad0c0.jpg)

We have simply continued as a training game and nothing went wrong after that.

https://18xx.games/game/35294
time in game: approx. 22.41

**Comment by dfannius** [comment]
When I undo to the end of B&O's turn in OR2.2 in hotseat mode, IC is able to run as it should. So I can't tell what went wrong, although certainly something did.

**Comment by crericha** [comment]
We talked on slack about it maybe being related to undos. I went back to the first action after IC was skipped (288) and there aren't any undos near there. I thinking it was something else.

**Comment by michaeljb** [comment]
Could be, will take a look.

**Comment by michaeljb** [comment]
I was able to reproduce in a multiplayer game on my local instance

* all other companies had to be sold out
* one tile laid by a corporation, not with MC's power, after MC was bought in
* owning corporation is on the "buy/use companies" step, after the buy trains step
* MC power used for one track lay
* one of the users types a message

**Comment by michaeljb** [comment]
Got a code change that fixes this in my local multiplayer game, though I still can't explain why IC got skipped.

**Comment by michaeljb** [comment]
Found two other occurrences where the MC or O&I lays one tile, and then a chat message skips their second action (which should either be another tile lay or a pass)

* https://18xx.games/game/11362?action=133
* https://18xx.games/game/23182?action=212

Neither of them caused any other craziness like the IC losing a turn though.
