### ISSUE TITLE
1817 option to never take an automatic loan

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4943]
Once again, I got completely hosed because the game automatically took a loan to pay interest. If I had been warned, I would have been able to undo the train purchase I made and buy the train across for 25 less to save money to pay interest.

I would REALLY REALLY like a profile option for 1817 that says "NEVER TAKE A FREAKING AUTOMATIC LOAN."

**Comment by jenf** [comment]
Dup of #2600 (or at least the fix)
