### ISSUE TITLE
1817 display paid/half/held on the corporation cards

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4944]
NYOW half paid for 110. You can see that because the payout in the spreadsheet has dashed brackets.

<img width="51" alt="Screen Shot 2021-04-03 at 2 01 04 PM" src="https://user-images.githubusercontent.com/8732435/113491371-193e3300-9485-11eb-889a-7f4155edcafa.png">

It would be nice if the Last Run on the card on the game tab and the entities tab used the same indication of paid/half/full.

<img width="329" alt="Screen Shot 2021-04-03 at 2 01 15 PM" src="https://user-images.githubusercontent.com/8732435/113491369-18a59c80-9485-11eb-9e5d-68b6a96e546d.png">

**Comment by yzemaze** [comment]
NB: https://github.com/tobymao/18xx/issues/3958#issuecomment-780535380
