### ISSUE TITLE
1860 QoL - Differ home tokens on map

### ISSUE THREAD

**Issue by wiyumB** [tobymao/18xx#4946]
In 1860, each company must include its home token for some part of its runs. So it would be helpful if the home tokens were visibly identifiable on the map. Something clean and simple would go a long way.

**Comment by ventusignis** [comment]
1862 will need this too; maybe using a star symbol on the token like in 1862 would be a good way to do this

**Comment by roseundy** [comment]
My opinion is that adding a star to the token will make them even more illegible than they already are. I'm going with a more subtle approach:

![1860_highlight](https://user-images.githubusercontent.com/8494213/117207981-d63bec00-adb1-11eb-85e6-2b586340a16f.png)
