### ISSUE TITLE
1822 add brief description to private companies

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4947]
The Info tab lists the private companies like this:

Privates bidbox 1 : P1-BEC*, P13-YN&BR, P14-K&TR, P4-SDR, P19-AEC, P3-S&HR
Privates bidbox 2: P12-L&SR*, P8-E&GR, P11-B&ER, P10-G&SWR, P5-LC&DR, P2-MtonR
Privates bidbox 3: P18-C&HPR*, P17-LUR, P15-HR, P6-L&SR, P20-C&WR, P7-S&BR

It would be nice if they had brief descriptions, like the ones I added to my Private Notes for the game.

Privates bidbox 1 : P1-BEC* (5T), P13-YN&BR (P+), P14-K&TR (P+), P4-SDR (P2), P19-AEC (PL), P3-S&HR (P2)
Privates bidbox 2: P12-L&SR* (extra tile), P8-E&GR (mountain), P11-B&ER (advanced), P10-G&SWR (estuary), P5-LC&DR (Channel), P2-MtonR (dit paver)
Privates bidbox 3: P18-C&HPR* (exchange), P17-LUR (card), P15-HR (highland), P6-L&SR (mail), P20-C&WR (mini highland), P7-S&BR (mail)

It would be nice if the brief descriptions were also used for the log entry at the beginning for removed private companies and on the charters.

**Comment by fanman80** [comment]
This is an enhancement that I would like to see as well.

**Comment by jenf** [comment]
@ChrisTheCat / @fanman80 please provide brief descriptions for each private and i'm sure they can be implemented.

**Comment by ChrisTheCat** [comment]
Happy to do it. What's the limitation on the length of the text string?

**Comment by jenf** [comment]
I'm not sure, try and make it sensible.

**Comment by ChrisTheCat** [comment]
For most of them, simply swap the abbreviated name with the description already in the text immediately after the phase number. I've suggested shorter text for some if length is an issue.

P1: Swap "BEC" and "5-Train"
P2: Swap "MtonR" and "Remove Small Station" (or "Remove town")
P3: Swap "S&HR" and "Permanent 2-Train" (or "Perm 2T")
P4: Swap "SDR" and "Permanent 2-Train" (or "Perm 2T")
P5: Swap "LC&DR" and ""English Channel"
P6: Swap "L&LR" and "Mail Contract"
P7: Swap "S&BR" and "Mail Contract"
P8: Swap "E&GR" and "Mountain/HIll Discount" (or "Hill Discount")
P9: Swap "M&GNR" and "Declare 2x Cash Holding" (or "Double Cash")
P10: Swap "G&SWR" and "River/Estuary Discount" (or "River Discount")
P11: Swap "B&ER" and "Advanced Tile Lay" (or "Adv Tile")
P12: Swap "L&SR" and "Extra Tile Lay" (or "Extra Tile")
P13: Swap "YN&BR" and "Pullman"
P14: Swap "K&TR" and "Pullman"
P15: Swap "HR" and "Ł10x Phase" (also sometimes just called "Highland")
P16: Swap "TH" and "Tax Haven"
P17: Swap "LUR" and "Move Card"
P18: Swap "C&HPR" and "Station Marker Swap" (or "Station Swap")
P19: Swap "AEC" and "Permanent L-Train" (or "Perm L")
P20: Swap "C&WR" and "Ł5x Phase" (sometimes called "Mini Highland")
P21: Swap "HSBC" and "Grimbsby/Hull Bridge" (or "GH Bridge")
