### ISSUE TITLE
Add hotkeys

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#495]
One of my favorite features of Board18 is the implementation of hotkeys. This makes navigating the screens easy. 18xx.games could benefit from hotkeys.

I propose the following which is just a first draft, but these (mostly) make sense to me.

History
- [⌘/Ctrl + ←] previous action
- [⌘/Ctrl + →] next action
- [⌘/Ctrl + b] jump to beginning
- [⌘/Ctrl + e] jump to end

Tabs
- [G]ame
- [P]layers
- [C]orporations
- [M]ap
- M[A]rket
- Trains/[P]hases
- [T]iles
- [R, "pRivate"]Companies
- [S]preadsheet
- T[O]ols

**Comment by scottredracecar** [comment]
For a sample of what how this works to use the keyboard to navigate screens within a webpage, gmail users can use these shortcuts to test.
https://support.google.com/mail/answer/6594?co=GENIE.Platform%3DDesktop&hl=en

**Comment by sparr** [comment]
Please do not override existing common browser shortcuts like [⌘/Ctrl + ←]. Otherwise I like this idea and most of the shortcuts suggested.

**Comment by zurfarosa** [comment]
To these shortcuts, I would add:
/ focus on text box (i.e. to chat)
? list of keyboard shortcuts
