### ISSUE TITLE
Harzbahn 1873 Seems to "hang" on routing 8th diesel in game 34033

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#4952]
Game: https://18xx.games/game/34033

OR 9.3, operation of HBE, first company to operate in round.

The HBE acquired a new 5T in previous OR and scrapped a 3T.  After assigning routes to the new 5T, the game seems to hang and becomes unresponsive when trying to assign a route to another diesel (a diesel that did not have a route in the previous OR.

Screen shot just prior to route assignment to diesel:
![image](https://user-images.githubusercontent.com/70117294/113510154-ff512e80-951e-11eb-85a7-1c60ba8b3afc.png)

Attempting to assign 8th diesel route F11 - G12 - H13 screen shot (clicked on F11 and then G12):
![image](https://user-images.githubusercontent.com/70117294/113510384-425fd180-9520-11eb-9886-603cd9393d2d.png)

The game responds to the "clear train" button, but it won't assign the route.

**Comment by fanman80** [comment]
Although the game would not show the diesel run F11 - G12 - H13, it did include it in the company's runs when I clicked on the "submit xM" button.

Note: I was running away with the game, and as a courtesy to the other players, I wanted to continue the turn with or without the revenue from that diesel.

**Comment by yzemaze** [comment]
Known issue. Routes are limited to 16 colors.
@roseundy

**Comment by roseundy** [comment]
Well that happened sooner than I expected.

**Comment by roseundy** [comment]
With the fix, it no longer hangs. Seventeen routes:

![seventeen](https://user-images.githubusercontent.com/8494213/113526741-6e0ea600-9578-11eb-9680-1bd17c7b060e.png)

Route colors will now cycle back through previous colors.
