### ISSUE TITLE
[Harzbahn 1873] Face value of independent mines is not counted towards the "Value" of the players

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4955]
As said above, the "Values" of the players do not include the face values of their independent mines.
This does not affect game play as such, but if at the end of a game there were still independent mines owned by players, their face values would contribute to the fortunes of their owners, according to the rules.

Klaus Kiermeier

**Comment by roseundy** [comment]
Yet another rule I glossed over. Will fix.
