### ISSUE TITLE
[1822] Unable to payout 2P separately (if you also have Pullman)

### ISSUE THREAD

**Issue by Saintis** [tobymao/18xx#4956]
Game https://18xx.games/game/35073, first noticed in OR 6.1, NBR.

Expected behaviour: be able to pay out 2P separately from 6+.

Observed behaviour: there was no option to pay 2P separately, just the standard full / half / withhold.
https://18xx.games/game/35073?action=838

**Comment by Maxwell-Frank** [comment]
Same issue with the Permanent L:
https://18xx.games/game/35875?action=1081
