### ISSUE TITLE
Unbale to buy more trains when a train is discarded

### ISSUE THREAD

**Issue by lucasandradefisico** [tobymao/18xx#496]
Hi, in our game of 1889 a corporation had cash to buy 2 trains. 

After it bought the first train a diferent corporation had to discard a train because the train limit changed.

After that the game jumped for the next corporation and didn't allowed the corporation to buy a second train.

**Comment by jenf** [comment]
Do you have a game Id?
How many trains did it have at the time? What train did it initially buy?

**Comment by tobymao** [comment]
https://www.18xx.games/game/1224?action=316
