### ISSUE TITLE
Keyboard shortcuts for navigating to the home page, and for entering games from the home page

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#4964]
Could we have a keyboard shortcut to navigate to the home page from within a game, similar to `cd ~` in a terminal?

In addition, could there be a keyboard shortcut for entering a game from the home page? One way to do this might be to have the ID number of each game as a clickable link, allowing users to enter the game via CTRL F -> ESC -> ENTER.

**Comment by yzemaze** [comment]
dup #3932
Please post your suggestion there.

**Comment by yzemaze** [comment]
> One way to do this might be to have the ID number of each game as a clickable link, allowing users to enter the game via CTRL F -> ESC -> ENTER.

If you insert shift+tab between esc and enter this should work already.
