### ISSUE TITLE
[18FL] Terminal Company Can't Lay Free Token

### ISSUE THREAD

**Issue by RBaron11** [tobymao/18xx#4967]
[18FL] Terminal Company Won't Lay Free Token

Game ID: 35813

https://18xx.games/game/35813

I first noticed this in OR 5.2. I'm running SAL with the Terminal Company. I have tried multiple times to lay the free token in multiple citites, to see if I could get it to work. When I click the Abilities button, the cities highlight like it know I want to place the token. When I click into a city, I get a Price=null error.

Thanks for all your hard work!

**Comment by ventusignis** [comment]
This PR fixes this and has been merged
https://github.com/tobymao/18xx/pull/5004
