### ISSUE TITLE
[Harzbahn 1873] Player order not correctly determined at the end of SR

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4969]
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33545

What steps cause the unexpected behavior?

- In Stock Round 6 player order was:
- Banker1105/JibJibMonkey/Ham/KKiermeier/jsterphone
- At the end of that stock round, Banker1105 and jsterphone both had 15M cash
- So, Banker must have been ahead of jsterphone in the new player order
- Unfortunately, it was the other way round
- See https://18xx.games/game/33545?action=717

**Comment by roseundy** [comment]
I will of course fix this, but once I make the change, it is possible that some games in progress will have to be "pinned" and will not be able to pick up additional bug fixes.
