### ISSUE TITLE
[Harzbahn 1873] Diesel railcar not shown for purchase from another company

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4970]
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33487

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- During Operating Round 7.2, the SHE wanted to buy a diesel railcar from the QLB
- This was not possible since the diesel railcar was not displayed as a train on offer

**Comment by roseundy** [comment]
Typo.
