### ISSUE TITLE
[Meta] Unable to Change Any Profile Settings

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4971]
If I go to my profile (TIE53) to and try to change any settings, I receive a "name may not be empty" error after clicking save changes.  The settings I change appear to stay selected in the profile tab but are not implemented in the interface where appropriate.

**Comment by yzemaze** [comment]
dup of #4920 and already fixed by #4965
Deployment was 1 hour ago, so this should work now. If it doesn’t just post here.

**Comment by yzemaze** [comment]
PS
> my profile (TIE53)

Afaik you’re currently registered as `TIE53 (he/him)`. The whitespace _was_ the problem.
