### ISSUE TITLE
1817 remove Pittsburgh private ability after Pittsburgh yellow tile is laid

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#4974]
https://18xx.games/game/26561?action=1643

After any yellow Pittsburgh tile is laid, the Pittsburgh Steel Mill ability should be reduced to zero uses on the owning corporation, which will prevent it from appearing as an availability ability with a button. Currently, it is only set to zero if "good" Pittsburgh is laid using the private company ability. It is not set to zero if "bad" Pittsburgh is laid.

**Comment by jenf** [comment]
looks like a regression, it used to close properly.
