### ISSUE TITLE
[Harzbahn 1873] Bugs concerning Insolvency through lack of money to buy cumpulsory train

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4978]
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33545

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In Operating Round 6.1 the SHE operates for the first time.
- Up to https://18xx.games/game/33545?action=794 all is correct.
- But not what is shown as information for the player:
- "SHE has 200 ℳ": correct
- "KKiermeier must contribute 100 ℳ for SHE to afford a train from the Depot": incorrect (twice):
- First of all: in Harzbahn 1873 a player **never** contributes money to train purchases of companies.
- Second: The train to be bought from the Depot, a 3T, costs 450M, not 300M (300M is the price of a 3M, but railway companies can never possess machines).

- It follows https://18xx.games/game/33545?action=795 namely: "SHE passes buy compulsory train" (leading to insolvency and the recapitalization procedure)
- During this procedure there is one error and also a misleading statement:
- First: "SHE's share price changes from 110 ℳ to 100 ℳ" 
- This is wrong. The share price already dropped when the SHE didn't run a train. It doesn't drop once more.
- Second: "5 IPO share(s) of SHE are sold to share pool" 
- This is misleading since, according to the rules, the shares are "put into the bank pool...", they are not sold.
- But in fact, I admit, the misleading term "sold" doesn't actually affect game play since the "sale" didn't affect the share price.

Klaus Kiermeier

**Comment by roseundy** [comment]
1. The message "KKiermeier must contribute 100 ℳ for SHE to afford a train from the Depot" is an artifact of the common code base for train purchases I'm using. It has zero effect on the actual game play. I will remove it.
2. The price drop issue was unclear to me from the rules (obviously). The first Clarification under Section 6 made it seem like there was an additional drop. The code fix is trivial.
3. I'll change the wording.

**Comment by roseundy** [comment]
Note that when I fix the player order issue (for ties), this game will break. Consequently, this game will be pinned and will not be able to see any fixes I made for this bug.

**Comment by KlausKiermeier** [comment]
Steve,

That the message  "KKiermeier must contribute 100 ℳ for SHE to afford a train from the Depot" is an artifact of the common code base for train purchase was absolutely clear to me. I also recognized that it didn't affect the actual game play. Nevertheless, it is of course misleading ;-)

Price drop: there is only a price drop when a railway company has not enough money to pay for it compulsory train, and only the one when it (as all railway companies) doesn't run a train in its first OR (except for the QLB). This is the normal price drop, and the clarification is there to make clear this price drop happens. Since: in all other cases where a company becomes insolvent there is no price drop at all.

And thanks for changing the wording!

Klaus
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Bugs concerning Insolvency through lack of money to buy cumpulsory train (#4978)
Datum: 2021-04-06T17:24:02+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
The message "KKiermeier must contribute 100 ℳ for SHE to afford a train from the Depot" is an artifact of the common code base for train purchases I'm using. It has zero effect on the actual game play. I will remove it.
The price drop issue was unclear to me from the rules (obviously). The first Clarification under Section 6 made it seem like there was an additional drop. The code fix is trivial.
I'll change the wording.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/4978#issuecomment-814209480", "url": "https://github.com/tobymao/18xx/issues/4978#issuecomment-814209480", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿
