### ISSUE TITLE
Unable to close company in 1870

### ISSUE THREAD

**Issue by fabianpk** [tobymao/18xx#4987]
I have a company on the verge of closing in 1870, but when I'm taking it there I get an error message. The game is 

https://18xx.games/game/35230

The stock value is 10, so it would go left and close. I've never played 1870 before, but the stock market says "Corporation closes", and I get the message:

Undefined message pass for nil

**Comment by daniel-sousa-me** [comment]
Yes, it should close. I'll take a look

**Comment by daniel-sousa-me** [comment]
This is going to take a while. The fix por the problem is simple, but it is raising a problema in a corner case scenario that with enough games will certainly happen. So I want to do it correctly at first, but I can't figure out how
