### ISSUE TITLE
Curly braces error message popup

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#499]
I'm unsure what's causing it, but I've seen this a handful of times in 1889 and now once in 18Chesapeake. I guess the primary problem is it's an unhelpful error message.
 
Actually, maybe this is indicator of client-server desync? I ran a ctrl+shift+R refresh after receiving this and the page reloaded into the state just before my last action. 

![curly_braces_error](https://user-images.githubusercontent.com/525244/82764101-80597880-9dda-11ea-9754-90ac1a30e741.jpg)

**Comment by tobymao** [comment]
this means that i'm deploying the server. you made a move just as it's restarting, so the move is not saved

**Comment by jenf** [comment]
@tobymao what's your suggested fix? I could see either:
* A better error message?
* Retry sending the move to the server?

**Comment by tobymao** [comment]
you shouldn't get this anymore
