### ISSUE TITLE
[18CZ] Inlcude total cost when buying other companies and train upgrade costs

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#4990]
This is really a request for more info and basically to save on calculator work.  I guess that makes me lazy?

More than once, when trying to orchestrate a company takeover, I've miscalculated by a few Kroner in such a way that I needed to restart from the beginning or pull out the calculator.  It would be great if the game showed what the total cost to the company would be as you input different values as well as the money going to share owners.  

In addition, it would be nice to see upgrade costs for trains in the company you're buying out as well, this way you can maximize the buyout price while ensuring you have money left to upgrade a train or for tokens or something else.

**Comment by Zwergenpunk** [comment]
haha no, I also had the problem. Would not be so complicated to show that information before actually purchasing the corporation
