### ISSUE TITLE
[Harzbahn 1873] NWE must not buy 1T as its compulsory train

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4997]
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/35738

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

https://18xx.games/game/35738?action=469

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In the above action the NWE bought a 1T train from the HBE.
- This should not have been allowed since at this step the NWE was obliged to buy, as its first train purchase, a train that qualifies as its compulsory train, and the 1T doesn't (see the respective "Special feature" in Rule 4.4.7).
- All the remainder of the insolvency and recapitalization procedures are correct.

**Comment by roseundy** [comment]
Interesting. I have code to make sure a 1T purchase didn't count as the compulsory purchase, but I don't have logic to prevent the buy entirely.

**Comment by roseundy** [comment]
As you know, the rules say:
```
Special feature: To ensure that the NWE can service its complete
concession route, it must not buy the 1-train as its compulsory train.
```
I misinterpreted this.

**Comment by roseundy** [comment]
I'm also going to assume that a company that still needs to make its compulsory buy cannot be allowed to buy switchers.

**Comment by roseundy** [comment]
So my code was preventing buying 1Ts  from the bank when NWE needed a compulsory buy, but it wasn't preventing it from buying one from another company. In addition, the code wasn't preventing diesel buys as a compulsory buy for any company, and wasn't preventing switcher buys from other companies as a compulsory buy.
