### ISSUE TITLE
1870 Stock Market Enhancement

### ISSUE THREAD

**Issue by Bearcat89** [tobymao/18xx#4998]
It would be nice if the presentation of the stock market in 1870 showed the reissue price of stocks (as it is shown in the IPO section of the physical copy of the game).

**Comment by volker18xxdev** [comment]
also the shares in the treasury should be shown in a seperate column and not in the IPO

**Comment by Bearcat89** [comment]
I see the update has added a separate entry for redeemed shares in the company but still no reissue par prices on the stock market display...

**Comment by daniel-sousa-me** [comment]
That's very good to know ^^ I took no part in that

The reissue is in my todo list, but I've been really busy with life stuff
