### ISSUE TITLE
Location name is not centered in its background box

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#500]
![Screenshot from 2020-05-24 14-44-04](https://user-images.githubusercontent.com/1045173/82764593-1be3ec80-9dcd-11ea-8dd4-0469eb30e246.png)

**Comment by michaeljb** [comment]
Even more off center on mobile (Firefox on iPhone)

![Uploading 471FE3B9-F488-4BD7-85A6-2375942D5EB5.png…]()

**Comment by michaeljb** [comment]
![4558E9F8-F9A3-402A-A4BD-1BCBF2D0CA10](https://user-images.githubusercontent.com/1045173/82764679-cd831d80-9dcd-11ea-8e2a-8b025e305bfc.png)

**Comment by kelsin** [comment]
As for the first image in this issue... it's just text rendering in browsers.... it's just going to be like that. All depends on exact settings in the font, combined with the rendering library used (varies from system to system) and the browsers math (and rounding errors) for svg positioning.

For the second, try removing alignment-baseline and only using dominant. I remember something about this in firefox?

**Comment by tobymao** [comment]
this happens because safari doesn't support dominant baseline
