### ISSUE TITLE
[1822] Unable to continue Game in browser

### ISSUE THREAD

**Issue by NeutronCoreanus** [tobymao/18xx#5009]
https://18xx.games/game/31242?action=1285

**How to Reproduce the Bug?**
opening game in Browser shows:
We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 1286
Broken action: { "type": "pass", "entity": "SECR", "entity_type": "corporation", "id": 1286, "created_at": 1617901612 }
**Which Browser / Platform?**
Firefox 87.0 (64 Bit) on Win10 Desktop

**Comment by magnusfalt** [comment]
I have no problem loading the game. Make sure you try a hard fresh in the browser.

**Comment by NeutronCoreanus** [comment]
issue fixed by unpinning and and then reloading.
