### ISSUE TITLE
[Harzbahn 1873] Company should become insolvent, but doesn't

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#5010]
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/35738

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- During Operating Round 5.2, the GHE has an income of 170M, 0M in its treasury, but 570M maintenance costs are due.
- So it should become insolvent.
- But when clicking on "Submit 170M" nothing happens; only the following message appears:
- "All shares must be from the same corporation."
- This makes no sense at all.

**Comment by roseundy** [comment]
Easy fix. Missing sanity check on forfeiting shares on insolvency.
