### ISSUE TITLE
1868 Wyoming check list

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#5011]
1868: Boom and Bust in the Coal Mines and Oil Fields of Wyoming

Should have started taking notes right when I started reading through the rules; will fill in all stuff before 11.3.4 later

# New Stuff

Issues found / things changed after the original list was implemented

## Bugs

- [x] undoing or using history nav breaks rendering uranium town revenue (it shows the base revenue instead of the revenue with the uranium bonus)
- [ ] development tokens are often rendered on top of boom city revenue

## New Features

- [x] new private companies (holding for more IRL playtesting)
- [x] three stacks of corporations, only top of each can be started
- [x] more corporations, including some with purple homes
- [ ] autopass for development rounds

# Original List

## Tile Rendering

- [x] boom towns
- [x] boom cities
- [x] bb/Bb/bB tiles
- [x] east/west bonuses
- [x] city name positioning/wrapping for K11 - "Atlantic City & South Pass City"
- [x] uranium icon (currently using port as placeholder)
- [x] better purple for Rapid City and Chadron, custom brown for Yellowstone
    - need to make `register_colors(purple: '#6f30a0')` work for a hex that is colored `:purple` (and same thing for `:yellowstone`)
- [x] better white for boom town/city revenues
- [x] offboard revenue placement

## Tiles

- [x] boomtown/boomcity tiles need to be implemented as proper double-sided tiles

## Stock Market

- [x] better blue for par values

## Company Abilities
- [x] P3/P5/P6 - choose one of the three connected to it
- [x] P1 Hell on Wheels
    - [x] close when golden spike is complete
- [x] P2 Wylie Permanent Camping
- [x] P3a Union Pac Coal
    - [x] 11.2.1.2 - UP coal DT
    - [x] place at same time other coal DT would be placed
    - [x] may be moved, terrain costs paid each time
    - [x] cube goes away, private closes at phase 5
- [x] P3b Buffalo Bill's Bonanza Oil
    - [x] 11.2.1.3 - BZ oil DT, placed in phase 5
    - [x] $0 base cost to place, $0 to maintain
    - [x] may be moved
    - [x] must pay terrain to place
- [x] P3c Fremont Expedition
    - [x] 11.2.1.4 - $20 discount from terrain cost for DT placement
- [x] P4a Grenville M Dodge
    - [x] one-time-use extra tile lay, 2 or 3 yellows, ignore terrain costs, then close
- [x] P4b Edward Gillette
    - [x] $15 terrain discount for each tile lay, all terrain
    - [x] still get Credit Mobilier revenue
- [x] P4c Frederick W Lander
    - [x] $60 terrain discount once per OR, all terrain
    - [x] still get Credit Mobilier revenue
- [x] P5 John S General Jack Casement
    - [x] extra tile lays/upgrades
- [x] P6 American Locomotive Corp 4-8-8-4 "Big Boy" Wasatch Class Locomotive
- [x] P7 Pure Oil Camp
    - [x] 1 token spot is reserved for the owning corp
    - [x] cannot go on a ghost town hex
- [x] P8 Laramie, Hahn's Peak & Pac
    - [x] pays $20 during ISR, $40 during green phases, $0 otherwise
    - [x] becomes LHP train as phase 5
- [x] P9 Thomas C Durant
    - [x] closes at the end of ISR
- [x] P10 Oakes Ames and Oliver Ames, Jr
    - [x] can exchange for UP double share, uses up buy action
    - [x] UP receives cash from bank when exchange is made
- [x] manually close companies at any time (help with cert limit)

## Railroads

- [x] 5 of the corporations can't start until phase 4: C&N, DPR, FEMV, LNP, OSL
- [x] place token when floating
- [x] Denver Pacific Railway and Telegraph Company requires an open city location to place its home station token
    - [x] if all DPR's tokens BUST out, it gets a new home in a future SR
    - [x] if it has no token in an OR, it has no action, stock price just moves left
- [x] from phase 2, float at 20% w/ incremental cap
- [x] in phase 5, float at 60%, full cap (remaining 40% immediately placed in market)
- [x] LNP/OSL: if corporation's home hex is not upgraded when it floats, the green tile gets placed and _does not count_ against corporation's initial lays (also terrain is free)

## Bust Rounds

- [x] zero development tokens --> ghost towns

### 2 Sequence of a Set of Rounds

- [x] SR - OR -Bust - OR - Bust

### 4.3 Boomtown and Boom City Examples

- [x] after DTC placement causes a Boom and there is a choice in how the new tile is placed, whoever originally placed the tile chooses the new Boomtown/Boom City arrangement

### 9 Initial Stock Round

- [x] if all players pass on buying the cheapest company, it gets removed
- [x] if Thomas C Durant is the cheapest, instead there is one OR
    - [x] phase-based privates pay half rounded up
    - [x] players with unresolved bids gain $5 (per private?)
    - [x] bidding on other privates counts as "passing" on the face value private

### 10 Stock Rounds

- [x] first stock round order is most cash to least
- [x] subsequent rounds is passing order
- [x] each share drops price
- [x] sell-buy
- [x] shares sold before operation give player cash at new price rather than original price
- [x] sold out move up; if at top, move down and right
- [x] brown: may buy from open market or IPO in one action
- [x] UP 20% share rules
    - [x] no longer reserved if P10 unsold in auction; anyone may buy (even if other shares available?)
    - [x] in bank pool, can only be bought if last one available
    - [x] if another share in bank pool, player can sell 10%, exchanging this for the cert in the pool
    - [x] UP cannot redeem this share

### 11 Operating Rounds

- [x] coal and oil companies place development tokens first, then usual stuff
- [x] development tokens can expire on certain train purchases
- [x] may buy in privates starting in phase 3, for $1 to face value
- [x] may issue any time during OR turn; lower the stock price just like normal sales; up to normal 50% limit in open market
- [x] may redeem any time during OR turn; may not issue and redeem on same turn
- [x] train exported at end of OR set
- [x] uranium bonus revenue
- [x] only RCL may use its purple home hex

### 11.2 Operating Coal and Oil Companies

- [x] coal: in priority order, players may place coal DTs
    - [x] color of DT matches phase
    - [x] pay terrain cost
    - [x] phase 2: two per OR
    - [x] phase 3+: 1 per OR
    - [x] max 2 coal DT per hex
- [x] oil: phase5+, in priority order, player owned oil companies operate
    - [x] 1) may remove oil DTs
    - [x] 2) pay maintenance for remaining oil DTs
    - [x] 3) may place one new oil DT, and re-place any that were removed
    - [x] player pays placement cost plus terrain costs
    - [x] max 1 oil DT per hex
 - [x] DTs can be placed in hex that is not a revenue location
 - [x] DTs not adjacent to a Boomtown do nothing

### 11.2.2 Boomtown Conversion to a Boom City

- [x] when DT placement makes a Boomtown tile hit DTC of 3+, the boomtown tile is immediately upgraded
    - [x] brown: DTC 5+, two-city Boom city
    - [x] Yellow and brown Double Boomtown tiles have only one Boom City and the other remains a Boomtown. On brown and gray double Boomtown tiles they become a joined Boom City.
    - [x] gray Boomtown and Boom City tiles are limited

### 11.3 Track Laying and Tiles

- [x] 6 track laying points
- [x] yellow: 2 points
- [x] brown/gray: 3 points
- [x] may lay/upgrade same tile multiple times in turn
- [x] semi-restrictive
- [x] border terrain only paid when connection is complete
- [x] 11.3.2 tiles unlimited except for C, G, L, J, and gray tiles
- [x] ghost town tiles appear when a boomtown busts
- [x] laying the overpass green tiles costs $20

### 11.3.3 Special Plain Track Tiles

- [x] GT tiles reserved for Jeffrey City / Shirley Basin are trackless at beginning of phase 7--instead of using special tiles, just remove towns and rename those hexes
- [x] B5 are for brown boom city tiles busting to ghost towns, cannot be used otherwise
- [x] WRC tile should be gray--take a normal yellow tile, turn it gray after being laid there

### 11.3.4 Crédit Mobilier

- [x] CM (bank) pays terrain cost to UP shareholders as bonus revenue, iff the new track extends route W from Omaha or E from Ogden
  - must be first tile in CM region in that column to get bonus
  - if other track in region connects to Ogden and goes further E, no bonus
  - if other track in region connects to Omaha and goes further W, no bonus
  - track total credit mobilier has paid out, log totals

### 11.5.4 Route Bonuses
- [x] Golden Spike Bonus: one train running Omaha -> Ogden may add Ogden -> Promontory Summit (if a stop remains)
  - [x] collect $180 bonus
  - [x]  Promontory Summit goes away
  - [x] Ogden gets the W:$50 bonus, which may apply to other trains running in the same OR
  - [x] close Hells on Wheels private
  - [x] ends Credit Mobilier revenue
- [x] Northern Spike Bonus: like Golden Spike; E -> Billings, bonus different depending on which Billings

### 11.5.5 Double Heading Trains

- [x] two or more trains run together, adding C and t numbers together

### 11.7 Distributing Revenue

- [x] 0: move left
- [x] sold out: move up, or if at top row move down and right
- [x] share sold/issued: move down
- [x] less than market price: no movement
- [x] at least market price: move right
- [x] at least 2x market price: move right again
- [x] at least 3x market price: move right again

### 11.9 Emergency Train Buying

- [x] first issue shares until can buy a train, or cannot issue more shares
- [x] president may contribute cash when cross-buying
- [x] president may sell "extra" shares to buy a C+t train instead of just the C version
- [x] bankruptcy: put shares and cash in open market, end the game

### 12 Bust

- [x] check Boom Cities for enough DTC to remain a boom city; downgrade to appropriate boom town tile if DTC < 3
- [x] return station tokens to most expensive spot on corporation charter
- [x] single-city boom town hex w/ two-city boom city tile on it busts back to single-town boomtown tile (5 DTs can still get it back to two-city tile)

### 13 Game End

- [x] once a 7-Train is purchased/exported, complete 3 more full ORs while following the usual SR/OR cycle
- [x] private companies don't count toward player value

### Optional Rule

- [x] during setup, randomly remove two of P3a/P3b/P3c and two of P4a/P4b/P4c, instead of the auction winner choosing which company they get
- [x] better async dev rounds? each player places coal then oil, instead of all players doing coal then all players doing oil

### Miscellaneous

- [x] remove logic for double boom cities (rules have since been simplified so that all brown/grey boom cities are one city with two slots, all boomtowns should render as a single town)

**Comment by michaeljb** [comment]
"unlimited" tiles aren't working correctly with a custom tile definition--for instance, the second Y57b doesn't have the boomtown outline and the town comes out as a rectangle

**Comment by michaeljb** [comment]
home token rule update - tokens should be placed on float; if DPR is parred in phase 5, its owner chooses a spot to reserve, and then it gets its token there when it floats

**Comment by michaeljb** [comment]
note: tiles with towns do not upgrade past green

in order to get to B5b, B5bb, 5b, and 5bb, a tile must have boomed to just a city in green, then upgraded to brown/gray, then busted

**Comment by scottredracecar** [comment]
This is a pretty fun game. I hope it gets implemented.

**Comment by michaeljb** [comment]
I know the map has shrunk since I've touched this, and I think some other rules have been changed so there's a fair amount of rework to do. I still aspire to getting back to implementing this when some IRL things settle down. I would happily support anyone who decided to pick up the torch before then.

**Comment by michaeljb** [comment]
notes for future self

* some stuff for implementing the +1+1 token and the 2+1 permanent train from the private is lifted from 1822, maybe that could be generalized?
* some stuff for double-sided tiles is coming from 18Mag, but what's already there doesn't support unlimited double sided tiles

**Comment by michaeljb** [comment]
Fully implemented with no known bugs (for now)! It's currently on my dev server and a branch in my fork. Will now work on getting PRs open and progress towards alpha on the real site.
