### ISSUE TITLE
[Harzbahn 1873] Cannot start Diesel on southern concession route of NWE

### ISSUE THREAD

**Issue by beorn7** [tobymao/18xx#5015]
**What's your Game ID?**

https://18xx.games/game/33486?action=974

**How to Reproduce the Bug?**

Have the NWE with a Diesel. Assign as the first Diesel route the _southern_ concession route of the NWE. The following happens:

![image](https://user-images.githubusercontent.com/5609886/114242617-7fe2b580-998b-11eb-8019-107845f31b25.png)

The error message is correct but no new Diesel route has shown up, so you cannot assign the _northern_ concession route, so you can never escape this situation.

_However_ (and weirdly), if you start with the _northern_ concession route as the first Diesel route, everything works as expected:

![image](https://user-images.githubusercontent.com/5609886/114242821-d05a1300-998b-11eb-9335-ffa1a837716e.png)

Note the same error message, but the new white `D` box underneath the orange one (which can be used to assign the other concession route and go on as normal).

**Which Browser / Platform?**
- Browser Version: Google Chrome | 89.0.4389.114
- Platform: Desktop

**Comment by beorn7** [comment]
Just heard that others had a similar problem in different situations, i.e. the new Diesel box didn't appear, but clicking on the existing one or doing something else in the UI sometimes helped.

I guess letting new routes pop up is pretty unique to 1873, and something doesn't work reliably here in the UI.

**Comment by roseundy** [comment]
I have a fix that improves this, but unfortunately there are still cases where the new diesel just show up. The good news is that clicking on a third city once you have started a route will add the new diesel.

**Comment by roseundy** [comment]
The fundamental issue is that the game logic can't force a refresh of the UI.
