### ISSUE TITLE
[1870] - Certificate limit not enforced after company left yellow area

### ISSUE THREAD

**Issue by cane771** [tobymao/18xx#5019]
At the beginning of SR 6 one player was above his share limit. This was marked red „17/16“ but he was not forced to sell one share. Neither as first action (as I would have expected) nor befor end of SR.

We just did so manually to continue the game.

https://18xx.games/game/36048

https://18xx.games/hotseat/hs_tqffjmwh_36048

**Comment by daniel-sousa-me** [comment]
Thanks for reporting. I didn't test that part, because it supposedly "came for free"
