### ISSUE TITLE
[1849] Forced sale of all stock uses "Declare Bankruptcy" button even if player won't go bankrupt

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#5022]
https://18xx.games/game/35413?action=630

Player Roger_jay should go bankrupt here, but instead the company closes, while its stock is not yet in the black.

**Comment by dfannius** [comment]
From the current AAG rules, Section 10.7, with relevant parts in bold:

> **If the president is unable to raise enough money, they sell all of the stock they are able to, and then place all of the money in the corporation’s treasury. The corporation is then closed**; see section 11. At this point, if the president has no stock left they can either leave the game (finishing with L. 0) or take a L. 500 loan from the bank. In the latter case L. 750 will be subtracted from their total value at the end of the game. **If the player still has stock (because they were unable to sell the certificates), they continue the game with L.0 and their remaining stock.**

The rules seem to have been followed. Can you clarify what you think should have happened instead?

**Comment by scottredracecar** [comment]
I guess the implementation is correct, but the text and button on the EMR train buy are misleading ("Declare Bankruptcy" is not appropriate).
https://18xx.games/game/35413?action=629

**Comment by dfannius** [comment]
Good point. I'll edit this bug to be about that.

**Comment by dfannius** [comment]
It would also be nice if the explanatory text said precisely what was going to happen after all possible shares were sold.
