### ISSUE TITLE
18MEX minor companies unable to lay track in ORs before all private companies purchased

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5025]
This is likely a low priority bug, as it shouldn't happen often (ever?) with normal play.

https://gist.github.com/ChrisTheCat/34dcce02e73b7e9e5961da7d028d5682

18MEX does not have an "initial auction round" or an "initial stock round." Rather, it begins in SR1. If SR1 completes without all the private companies in player hands, OR1 is conducted and then SR2 begins, with restrictions on what players can do (they can only bid on and purchase private companies until all are owned by players). This continues if SR2 also ends without all the private companies in player hands - OR2 is conducted, etc.

Because 18xx.games implements the private company auction in a special "initial auction round," in the case when all private companies are not in player hands, 18xx.games does not conduct an OR as required. Rather, as a shortcut, the private companies pay revenue and the minor companies pay 30 (half-paid 15/15). Normally, this isn't a problem, as minor companies B and C cannot lay track until OR3 and minor company A cannot lay track until OR4. However, in the unusual case where players enter OR3 without having purchased all the private companies, the minor companies' track lay steps are skipped.

I'm guessing the fix would require some refactoring to begin the game in SR1 (not in an initial auction round) and to force players to bid/buy private companies in SR2, SR3, etc. while private companies remain in the bank.

For now, here is the wiki text describing this issue:

> What does a minor company owned by a player do in case everyone passes during a stock round without purchasing all the private companies?
> 
>     According to the rules an operating round is conducted. The private companies that are owned by players pay revenue, and minor companies that are owned by players operate. In the second and subsequent stock rounds, the players must continue to bid on and purchase private companies, and may not launch corporations or buy/sell shares in corporations until all private companies are in player hands. (Note that if the Mexico City - Acapulco Railroad / P1 has not been purchased, its price is reduced, see rule 3.1.2.)
>     The current implementation does not allow the minor companies to lay track in operating rounds if all private companies have not been purchased. They simply pay 30 revenue (15 to player and 15 to treasury). This is only a problem if there are three operating rounds prior to the purchase of the last private company, as the minor companies are unable to lay track in the first two operating rounds. A ticket has been submitted to fix this problem, which is unlikely to occur during regular play.
>

**Comment by michaeljb** [comment]
1846 2p can possibly be referenced -- in the auction if all players pass, 2 full ORs take place before returning to the auction, allowing Michigan Southern and Big 4 to lay track and have full OR turns

**Comment by perwestling** [comment]
In the 18MEX case minors to do not have enough cash to do anything until OR3. And it feels like a very unlikely scenario it will ever happen. 
It is of course possible to fix, but it is very low priority.

So I suggest that we close this one with "won't fix" label, and refer to it from the Wiki.

**Comment by perwestling** [comment]
What is lost is the possibility for Minors to build track in OR3+, but this is a very small benefit. Instead they can just continue to collect income waiting privates to be sold out, and a Major to float. 
I think the owner of the Minors hardly will complain as they are making a profit. Some player, without privates/minors, is probably losing the game if this continues, so players should definitely not let this happen.

**Comment by ChrisTheCat** [comment]
Makes sense to me.

**Comment by ChrisTheCat** [comment]
Well, if I were in that position as the owner of a minor, I would still
complain.

However, I agree that it's very unlikely to happen absent very bad play.
