### ISSUE TITLE
Undo with non-Master Mode

### ISSUE THREAD

**Issue by gamergeek65** [tobymao/18xx#503]
I believe This is more of an enhancement request than a bug.

When playing a game and Master Mode is not enabled, I would suggest you do not let the Undo feature go back to a previous player’s turn.  It should only allow undos back to the beginning of that player’s turn.  If master mode is enabled, undo can go back to other players turns.

Btw, I love your site and your game implementation.  Very well thought out.  I have been enjoying for several weeks now.

**Comment by tobymao** [comment]
this is hard because if you move to the next player's turn you'd have to go to master mode

doing something smarter would be more involved
