### ISSUE TITLE
[1822] Players should be allowed to bid on Tax Haven even when at Cert Limit

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5031]
https://18xx.games/game/37143?action=460

Since the Tax Haven does not count as a certificate, a player should be allowed to place a bid on the Tax Haven even when at the certificate limit. This is currently not allowed.

**Comment by scottredracecar** [comment]
That isn't allowed per 4.10.8.

**Comment by Maxwell-Frank** [comment]
Closed per Tax Haven briefly counts as a certificate for purposes of bidding.
