### ISSUE TITLE
Revenue values in OO tiles not visible depending on the orientation (1836jr)

### ISSUE THREAD

**Issue by DarthIA** [tobymao/18xx#5043]
In game 36317, in the tile number 66 in H10 the OO label is in front of a revenue value, making more difficult to see (although I know it has the same value as the other city in the tile). 

![image](https://user-images.githubusercontent.com/24686708/114527988-df211e00-9c48-11eb-9fa1-a1f9c8a5e878.png)

If you need the JSON data of the game I can also provide it.

**Comment by scottredracecar** [comment]
Cannot reproduce, this game suggestion is different than the screenshot?
https://18xx.games/game/36317
