### ISSUE TITLE
[18MEX Baja] Uncaught error for CdB action when out of tokens 

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#5044]
When you try to use the CdB action, but the company is out of tokens, you get an error message "undefined method 'price=' for nil"

**Comment by jenf** [comment]
Do you have a sample game where it's seen

**Comment by jeroenh** [comment]
I went a bit back and forth with MC in this game, https://18xx.games/game/36927 and it came up. You'd have to go back to here to try yourself: https://18xx.games/game/36927?action=264
