### ISSUE TITLE
1817WO game # 37272: bug during initial auction

### ISSUE THREAD

**Issue by billbold2** [tobymao/18xx#5047]
https://18xx.games/game/37272

In the initial auction I purchased the Pittsburg Steel Mill for $30. $10 in seed was added to get to the $40 price, but it looks like $40 was subtracted from my account instead of $30. I should have $310 in cash instead of $300. 

Screen print included. The 21:47 mark. Am I reading the rules for the use of seed money correctly? My opponent had the same thing happen to him when he purchased the coal mine right before me.

[Game 37272 issue.pdf](https://github.com/tobymao/18xx/files/6306548/Game.37272.issue.pdf)

**Comment by ventusignis** [comment]
https://18xx.games/game/37272?action=9

At action 9 you have $330, and when the auction finalizes, you have $300 which accounts for the $30 out of pocket for the private

**Comment by jenf** [comment]
Players start with $330, looks like correct behaviour.
