### ISSUE TITLE
[18FL] Price stops increasing when one 10-share corporation hits 200. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5049]
https://18xx.games/game/37385?action=303

While 5-share corporations are limited to a 200 share price, 10-share corps should be able to move past this line. However, in our game at action 303, SR was worth 200 and ran for $410, but its price did not change. This corporation was manually converted from 5-share to 10-share. 

It happened again at this action: https://18xx.games/game/37385?action=363
But you'll notice by this time LN has passed the line without problem. LN was also manually converted by the player earlier in the game.

**Comment by ventusignis** [comment]
Ah, sorry about that, I pushed up a fix that just needs to be merged and deployed

**Comment by philcampeau** [comment]
Brilliant! Glad it was such a quick fix.
