### ISSUE TITLE
Glitch - When buying a new train than forces other player to discard trains

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#505]
When buying a new category of trains that impose a limit of trains and another player has to discard trains, the other player is called to discard trains and after that, the original player passes automatically without the possibility to buy another train as should be.

**Comment by Djeefther** [comment]
I am working with reproduction steps

**Comment by tobymao** [comment]
was this in a multiplayer game or hot seat? you can just copy the game data from the tools tab

**Comment by Djeefther** [comment]
**Reproduction steps:** (but unfortunately the bug do not show ups)

1. Start an 1889 hot-seat game with 3 players importing JSON state from https://gist.github.com/Djeefther/c0f75904c59b01f0e9d07a82e3762ad4
2. Playing with player 1 and operating KO buy Train 5 on the first option for ¥450
3. As Player 3 operation with SR discards one of the 3-trains.
4. Player 1 will not be able to buy another train

I was trying to reproduce the steps I had seen on a multiplayer match. But now on hot seat reproduction, it worked as should be and the player that triggered the discards could buy another train.

**Comment by Djeefther** [comment]
It was on multiplay

**Comment by tobymao** [comment]
i fixed it today . next time you can go to tools and copy the game data for me
