### ISSUE TITLE
[1860] Timing with new company floats causes companies to operate in the wrong order.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5055]
Floating companies (not parring them) should add a company to the stock market.
See https://www.dropbox.com/s/usfbqtdjzx6ug8f/1860-rules.pdf
Page 8.
Sec. "Flotation and Capitalization"
First paragraph, last sentence.
This rule is also referenced Page 7. Sec "Share Price Movement" first paragraph.

This causes incorrect stacking of tokens when another company arrives at the same stock price between parring and floating (via stock sale, or via another float)

Repro 1:
Par S&C at 62.
Buy S&C share.
Sell S&C share.

Expected: No Marker goes on the stock market. Share may not be sold.
Observed: Marker goes on stock market immediately. Share sale is allowed.

Repro 2:
Par S&C at 62.
Par VYSC at 62.
Sell IWNJ (price falls to 62).
Float VYSC.
Float S&C.
Stock round ends.

Expected operating order: IWNJ, VYSC, S&C
Observed operating order: S&C, VYSC, IWNJ

**Comment by roseundy** [comment]
Nice catch. I will have to modify flotation to move the "marker" to the bottom of the stack.

**Comment by physic** [comment]
> Nice catch. I will have to modify flotation to move the "marker" to the bottom of the stack.

That's not quite sufficient. You must also prevent sales of the shares which *do not yet have a market price*

**Comment by roseundy** [comment]
Interesting. The rules are not explicit about that. In fact the rules seem to contradict this. Under "Flotation & Capitalization" it says that companies float "when 50% or more of there shares have been bought from the IPO. Shares in the bank pool do not count towards this total."

How can there be shares in the bank pool if you can't sell before flotation?

**Comment by physic** [comment]
That's an excellent point. There seems to be a slight inconsistency in the rules. I've posted the question to the 1860 forum on BGG. The designer has been quick to resolve rules questions in the past.
https://boardgamegeek.com/thread/2640955/article/37493563#37493563

In the meantime, the line you reference strongly suggests that Mr. Hutton's intention was that shares may be sold. and that your suggested fix is appropriate.

**Comment by roseundy** [comment]
Even if it is legal to sell unfloated company shares, I think I need to fix to code to always make sure the sale price is based on the par price, not the market price. This would only come into play for bankrupted companies. I think. The exception to allow price drops on bankrupted companies makes this uncertain.

**Comment by roseundy** [comment]
I think I'm just going to make the fix to re-order the markers correctly when a company floats.
