### ISSUE TITLE
[1846] GT didn't get extra station when absorbing MS

### ISSUE THREAD

**Issue by coleman07** [tobymao/18xx#5059]
https://18xx.games/game/37531

GT bought MS but didn't get the 4th token. IC bought Big4 right at the start and went from 4 tokens to 5.

**Comment by dfannius** [comment]
When GT bought MS, GT already had a token in Detroit. Rule 6.92 says (emphasis mine):

> Add an Independent Railroad’s treasury to its corporation’s treasury; its 2-train to its trains, and replace its token with an extra token of the purchasing corporation (**unless it already has a token in this city**).

So MS's token (correctly) just disappeared.

**Comment by coleman07** [comment]
Thanks Dan. I was reporting on behalf of a Guru
