### ISSUE TITLE
Add mechanism to hide or delete matches not owned by you

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#506]
Improvement that consists of adding a mechanism allowing the non-owner of a game that is in course to hide, leave or delete that game. 

The situation is I had an example match, just teaching the game to me, and all plays are not going to play any further this game. The owner could delete the match but haven't, and the match always shows up on my front-page even all plays had abandoned it. 

The delete or leave solutions could have bigger impacts than just "hiding" or "archiving" mechanisms that remove until some movement in the game.

**Comment by jenf** [comment]
All players can now end a game, therefore it won't show on the main page
