### ISSUE TITLE
1870

### ISSUE THREAD

**Issue by RandallNlsn** [tobymao/18xx#5060]
Two issues: 1) when two tokens occupy the same space, and the top company has a share sold, but doesn't move because it's on the ledge, it swaps places with the bottom token. Only when a token moves into a shared spade does it go to the bottom of the stack

2) when reissuing a share with a CMV of $300, the new par price should be $225. The site has the share reissued at $200.

**Comment by daniel-sousa-me** [comment]
Can you provide an example of a game where (1) happened?

$200 is the highest possible par. There's already an issue to put that information on the market tab (sorry, I've been too busy :( )

**Comment by Bearcat89** [comment]
> $200 is the highest possible par. There's already an issue to put that information on the market tab (sorry, I've been too busy :( )

According to the rules $200 is NOT the highest possible par.  There was a printing limitation on the physical stock market in the Mayfair product, but the rules clearly state (in the section on reissuing shares) "If the new par value is greater than $200, the par value token should be placed on the top row of the stock market in the square closest to the new par value." as opposed to the normal par value chart on the bottom of the stock market display.

**Comment by RandallNlsn** [comment]
Yes, agreed .... Last paragraph of Mayfair rules under Share Reissued
spells it out

**Comment by daniel-sousa-me** [comment]
I had completely misread that sentence. Thanks for the clarification.

**Comment by RandallNlsn** [comment]
Hey Dan,

Thanks for to you're attentiveness on this! The 1870 application is really
good and very much appreciated...

Regarding that other issue, the please see game #35406, date 4-7-21, time
1447 hours.


MP and SLSF both shared the $120 space just above the ledge. One share of
MP was sold, but the ledge held it from moving down. However the
application moved the MP token underneath the SLSF token ....

The tokens order should not have changed, since no token moves into that
stock square ....

Thanks again! Great job!

Randall Nelson
