### ISSUE TITLE
[18SJ] Stockholm to Stockholm routes are permitted when they shouldn’t be

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5062]
https://18xx.games/game/35388?action=461

On this action, the player submitted a run that included two locations from Stockholm, but the rules say a train may not visit Stockholm more than once.

**Comment by benjaminxscott** [comment]
You may want to rewind that game if your group agrees, since after this fix is deployed it **will not** break on that revenue step, since it was already submitted

(the route is only checked on the frontend, if it's already been submitted in the game state then it won't break)

**Comment by philcampeau** [comment]
I believe it actually already was undone actually. 
 Here is an image of the accepted route. 

![1AD9E32C-5C80-42EE-B437-74101BA3FCA0](https://user-images.githubusercontent.com/26125362/114938446-1dffd100-9e0d-11eb-90c0-cc1a35a4ec97.jpeg)

**Comment by benjaminxscott** [comment]
Ah OK, so your group already undid the "illegal route" [and proceeded with a legal route](https://18xx.games/game/35388?action=467)
