### ISSUE TITLE
email link without HTTPS

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#5063]
the 18xx mail-server sents mails for next move.
The link to the game "http://tracking.18xx.games/tracking/......" is without HTTPS, when clicking on the link, there is a warning about insecure link.

Enhance the link with HTTPS.

**Comment by benjaminxscott** [comment]
Not that we shouldn't change this, but to confirm, you're talking about the browser warning in the toolbar?

(not like an interstitial click-through)

e.g. on chrome
![Screenshot 2021-04-15 12 54 37 PM](https://user-images.githubusercontent.com/1711810/114930387-cbf98400-9de9-11eb-9c2c-5a4b1e859409.png)

**Comment by tobymao** [comment]
what link in the email is this? it must be a hidden tracking link? i don't send a link like this so it must be inserted by the provider

**Comment by volker18xxdev** [comment]
i ment the link in the email from "no-replay@18xx.games"
![grafik](https://user-images.githubusercontent.com/80693707/114931781-f9b8ea00-9e36-11eb-9618-46b278827652.png)

link behind: "Go To Game ????", when clicking on this link my browser firefox shows following message.
![grafik](https://user-images.githubusercontent.com/80693707/114932160-751a9b80-9e37-11eb-8245-71f57eebf990.png)

**Comment by tobymao** [comment]
must be some kind of ad blocker?

**Comment by volker18xxdev** [comment]
My browser want always to open an secure connection to your website (only-https-mode). 
The Email-link open always an insecure connection.  
It's an usual procedure, always to open a secure connection (https)

**Comment by tobymao** [comment]
this is not my website, it's an email click tracker
