### ISSUE TITLE
Purchase train from another director

### ISSUE THREAD

**Issue by mjshaver** [tobymao/18xx#5065]
During the purchase trains step (eg. In 1830). After clicking "show trains from other players".

I propose that 1) that after [corp name] [train name] [proposed price] the button says "request to buy" instead of just "buy" and 2) the other director is given a mini turn. Such as "Mike the director of the B&O has requested to buy the 5 train from the Erie for $120. Do you agree to the purchase?" with "yes/no" buttons.

The following game has been delayed for several days because the director of the second company hasn't seen the written request to purchase his train.
https://18xx.games/game/30655

**Comment by jenf** [comment]
We ask for confirmation, we've previously discussed how to implement this and the currently implemented behaviour seems the best trade off.

**Comment by mjshaver** [comment]
But you don't ask for confirmation from the other director. You just warn
the acting director that they need confirmation and give the option to
click okay.

https://18xx.games/game/30655
This game has been paused for days because they can't get confirmation from
the other director. Even though the purchaser has clicked "confirm".

Similar to discarding an extra train, if you shifted focus to the other
director and asked them to confirm it would be much easier to get them to
notice that they need to act for the game to continue.

Thank you for your time,
Mike
Ps. I love the site. Thanks for all your hard work.
