### ISSUE TITLE
[1870] Sold out companies in top row should move right and down

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#5067]
https://18xx.games/game/37666?action=502

See ATSF

> Up one row if all shares are owned by players or the company at
the end of a stock round. If the token is at the top of the market, it moves,
instead, one row downward and one column to the right.

**Comment by daniel-sousa-me** [comment]
:O

**Comment by crericha** [comment]
FYI, this is probably what you need: https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_ny/stock_market.rb

**Comment by crericha** [comment]
Nevermind, I didn't notice you recently created a fix.

**Comment by daniel-sousa-me** [comment]
Maybe we should generalise this. I think 1822 also should do this.
