### ISSUE TITLE
18CZ upgrade Train to obsolete type

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#5077]
https://18xx.games/game/35044?action=577

https://gist.github.com/benjaminxscott/6d904b601acf2b90d57507ccfde733ca

ATE buys OFE for 75 K per share receiving 130 K, trains (3c), and tokens (3: hexes )
OFE closes
ATE upgrades 3c to 2+2c for 0 K
As the 4+4f was already sold, the upgrade of the 3c should not be possible. 
Solution: an upgrade to a deleted train type should not be possible.
@ViennaTramways: is this intrepretation ok?

**Comment by ViennaTramways** [comment]
Yes, this interpretation is correct.
Lonny

Am Sa., 17. Apr. 2021 um 20:43 Uhr schrieb volker18xxdev <
***@***.***>:

**Comment by Zwergenpunk** [comment]
Can you link me the exact action? Or at least which round it happened?

**Comment by volker18xxdev** [comment]
hi operation round 6.2. I assume id 577.
    {
      "type": "swap_train",
      "entity": "ATE",
      "entity_type": "corporation",
      "id": 577,
      "created_at": 1618576760,
      "train": "3c-2"
    },
