### ISSUE TITLE
Ranking Players

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#508]
Ranking based on ELO-score or another similar method.

**Comment by jcoveney** [comment]
IMO, the platform is not the right place to do this. The mix of game styles (private, open, fast, slow, async, live) make it hard to compare. That said, I've been thinking about organizing a terra mystica snellman style league for 18xx...

**Comment by dfannius** [comment]
In addition to what @jcoveney said, I think a lot of people simply don't want to play rated games. Also, as soon as you start rating games, bad behavior (e.g., abandoning games) becomes something people care about a lot more. There's also behavior like kingmaking that isn't even necessarily bad and is in some way unavoidable, but right now if someone complains you can just say "just pretend you won and move on to your next game", but with rated games people could start feeling that other players are "ruining their rating".

An opt-in league with well-defined rules sounds a lot more reasonable to me.

**Comment by tobymao** [comment]
closing for now

**Comment by Djeefther** [comment]
Nice evaluation, kind of confusing, and not a priority right now. Thanks, guys.
