### ISSUE TITLE
Identify on log that some action was made by master mode and who did it

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#509]
Identify on the log that some action was made by master mode and who did it, currently looks like the own person made.

**Comment by jcoveney** [comment]
Agree that this would be very useful

**Comment by rally5** [comment]
Yes I would like this feature as well.

**Comment by ryandriskel** [comment]
Looking for suggestions on a more specific implementation. I'm toying with the idea of tackling this but the below solution is the best I have so far given the current log functionality.

<img width="374" alt="Screen Shot 2020-10-15 at 6 11 06 PM" src="https://user-images.githubusercontent.com/15675400/96198395-f12c3900-0f11-11eb-9856-68501c2c22f5.png">

**Comment by rally5** [comment]
Yes that's better than nothing.
