### ISSUE TITLE
1817NA - Not prompting for "remove token step"

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#5093]
This game is stuck at the "remove token step" but the log is not prompting for that.
https://gist.github.com/scottredracecar/928205e793e444064104a279af23e5cb

**Comment by jenf** [comment]
[22:57]DL&W will be above token limit and must decide which tokens to remove

It does show it in the log, but it's not the last line of logging. It's a bit of a technical limitation really.

**Comment by scottredracecar** [comment]
Can there be a pause until the tokens are removed before the additional log lines are displayed?

**Comment by jenf** [comment]
not easily
