### ISSUE TITLE
1830 Another corporation can place token on Erie tile before Erie is floated

### ISSUE THREAD

**Issue by biddu6566** [tobymao/18xx#5097]
Game: https://18xx.games/game/30649

Erie was not yet floated in OR5.2 and NYC upgraded and tokened Erie's hex. 

In Lookout Rules at least it is clearly stated this is not allowed till Erie has placed its home station which will not happen if Erie is not floated yet (Section 6.3). Same rules in AH rules section 19.1

**Comment by jenf** [comment]
Only the token is illegal according to 6.3
