### ISSUE TITLE
[1882] - Corporation (QLL) issued a share

### ISSUE THREAD

**Issue by SLOFila** [tobymao/18xx#5107]
Game ID: 37905

QLL issued a share, making it drop in the market, allowing it to be bought for the new lower market price.

https://18xx.games/game/37905?action=120

**Comment by jenf** [comment]
Huh, the share is being sold by a player, but obviously they don't own it

`      "type": "sell_shares",
      "entity": 8528,
      "entity_type": "player",
      "id": 120,
      "created_at": 1619053067,
      "shares": [
        "QLL_5"
      ],`
