### ISSUE TITLE
Add a user to "acting" when they're mentioned

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#5109]
While writing #5108 here, it occurred to me that we could add a user to the `acting` array when they're mentioned until they act in some way. This would go away if they did some "normal" games action (or send a message), but there could also be button to "mark as read" that just added a spurious action.

**Comment by physic** [comment]
Yes please. I want to be able to ping a player. I want it to turn orange as if it's my turn, when there's a ping that I haven't acknowledged (by interacting with the game in some way).

This is crucial for games where deal-making or buying from other players is common. e.g. "@jonathan would you like to sell the CO your #9 mine for $300?" Currently it remains the acting player's turn, and from the homepage, there is no way for me to tell that the game is effectively blocked on my acknowledgement of the question.
