### ISSUE TITLE
Add Timestamps in log

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#511]
Currently, no indication on time is given, especially on async games this could be confusing. Add also time zone in the log, and if possibles show all times automatically on the user time zone.

**Comment by jcoveney** [comment]
Agree that this would be very useful

**Comment by twoscoopsofpig** [comment]
Bump

**Comment by Nate-Mg** [comment]
Bump. This would be super-useful IMHO.

**Comment by daniel-sousa-me** [comment]
So, good news, yesterday I noticed that the time of the actions is already being stored in the server anyway. Probably it's automatically added by the db, but it shouldn't be to hard to make it also available on the client.
Then we can start thinking about implementing chess clocks and such.

@tobymao are you ok with exposing this info in the json?

**Comment by tobymao** [comment]
yes
