### ISSUE TITLE
[1822] Automatically Skip Asking About P9 if it Won't Affect Turn Order

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5110]
There was some complaint voiced in the general chat box that a player should not be asked if they want to use P9 to double their cash holdings at the end of a stock round if it would not affect turn order.  

Obviously, this could just be done in master mode, but auto-skip would save someone a click!

**Comment by KevinR1000** [comment]
This looks non-trivial, and so probably merits a separate function.  I think that something like this would work within the current company_choices_mgnr() function [but I still think in C so there is probably a far better way to do this].

The choice is irrelevant if all other players have either more than double the MGNR (F9) owner's cash or less than the MGNR owner's cash (or if MGNR owner's cash is zero).  So, loop over players and set a flag if one falls in the middle.

File:  lib/engine/game/g_1822/game.rb
Line:  1508 (after return {} )

```
mgnr_owner_cash = company.owner.cash
mgnr_choice_relevant = 0
if mgnr_owner_cash > 0
    @players.map do |p|
        mgnr_choice_relevant = 1  if p.cash <= 2* mgnr_owner_cash && p.cash >= mgnr_owner_cash
    end
end 

if mgnr_choice_relevant == 0
    @log << "Double actual cash holding is irrelevant when determining player turn order."
    company_made_choice_mgnr(company)
    return{}
end
```

**Comment by jenf** [comment]
Could you provide a sample game with reference to the action?

**Comment by KevinR1000** [comment]
The action immediately after https://18xx.games/game/38402?action=248 .

> [22:55]edhew chooses to double actual cash holding when determining player turn order.
[22:55]-- New player order: KevinR (£55), edhew (£21 doubled), warder57 (£8)

Note that it does not matter whether edhew was sorted by his true money (£21) or doubled (£42), because I was higher than 42 and warder was lower than 21.

**Comment by KevinR1000** [comment]
That is, we want to automate the decision at https://18xx.games/game/38402?action=248 , so that we do not need to wait for Ed to make a meaningless decision.
