### ISSUE TITLE
Buying a train from a company with a different president

### ISSUE THREAD

**Issue by mindphaser1** [tobymao/18xx#5111]
last night we were playing a game of 18Chesapeake and one of the players wanted to buy a train from me. I agreed to the transaction (we were using discord for voice chat while we were playing), but in the game that player went to purchase the train for the agreed price, but it never prompted me to accept the offer, it just automatically went through. Should there not be a prompt for me in this case to accept the offer in the game before it is finalized?

**Comment by benjaminxscott** [comment]
I believe this is by design:

https://github.com/tobymao/18xx/issues/1557
https://github.com/tobymao/18xx/issues/1619

Added [to faq](https://github.com/tobymao/18xx/wiki/FAQ#gameplay)

**Comment by jenf** [comment]
By design. There's a confirmation to confirm that the player has requested. We don't enforce the other person agreeing to it but get confirmation that the other player has got permission.
