### ISSUE TITLE
1870 tile manifest incorrect

### ISSUE THREAD

**Issue by RandallNlsn** [tobymao/18xx#5112]
The yellow city tiles have incorrect amounts ... There should be only two #5s, two #6s, and four #57s ... Not five of each.

Thanks

Randall

**Comment by dfannius** [comment]
My copy of the rules says that there are two #5, two #6, and five #57 tiles.

**Comment by RandallNlsn** [comment]
Yes that is correct...

However the app has five tiles of each.... Which is incorrect
