### ISSUE TITLE
[1822NRS] Error message: "undefined method 'owner' for nil."

### ISSUE THREAD

**Issue by ViennaTramways** [tobymao/18xx#5119]
Game ID: 38583.

Game stucked. Can't do anything.
Error message: "undefined method 'owner' for nil."

Possible reason: The CR placed it's destination token which is shown as normal token.

**Comment by Acro84** [comment]
I'm getting a similar error in my game as well during the Track turn. The error occurs even when the company lays no tracks.

Game ID: 35518
Message: "undefined method 'place' for nil"

**Comment by Thomas-CET** [comment]
We had the same problem in game 38404 (player HUGE used a normal token instead of destination token, game got stuck). We ended it then prematurely.

**Comment by santouryuu3** [comment]
Same error in 37842. GWR forced to place wrong token, leading to inability to get past track laying on next part of OR with message "undefined method 'place' for nil"

**Comment by jenf** [comment]
Apologies, will be fixed in a few minutes.
