### ISSUE TITLE
1822+ - bug report

### ISSUE THREAD

**Issue by jrt1817** [tobymao/18xx#5121]
https://18xx.games/game/36789

Player Hushed was forced to sell a share that hadn't finished its first operation (SCR).  The rulebook explicitly disallows this (4.4.1, 5.15) saying that you cannot sell a share of any company that "has not completed an operating round."

**Comment by michaeljb** [comment]
Is that the correct game link? I don't see a player named "Hush", the only sale at all I see is 18xxperson selling GWR at https://18xx.games/game/36789?action=420 after GWR has operated.

**Comment by michaeljb** [comment]
Is this the right moment? https://18xx.games/game/38603?action=477

Hmm actually, no I don't think it's that; there Hushed sells SECR during EMR for Minor 4 after SECR operated in the previous round.

There are quite a few 1822+ games with Hushed and daroj (I'm guessing that's you @jrt1817 since daroj is also in the game you linked), if you could help out with identifying which game has this bug is, that would be great.

```
{31787=>["Hushed", "daroj", "wheresvic", "Aolivei8", "TrancisFresham"],
32709=>["Hushed", "daroj", "AndyPy", "wheresvic", "Aolivei8"],
32882=>["Hushed", "daroj", "wheresvic", "Aolivei8", "Tealsplash"],
33131=>["Hushed", "Vecna", "AndyPy", "wheresvic", "BradT"],
33818=>["Hushed", "DrAwesome", "daroj", "Aolivei8", "Tealsplash"],
34272=>["Hushed", "Databoy01", "daroj", "Raymong"],
34583=>["Hushed", "TIE53 (he/him)", "wheresvic", "Sarah (She/Her)"],
35114=>["Hushed", "daroj", "Raymong", "Starfire"],
35290=>["Hushed", "daroj", "wheresvic", "cutebeast"],
35412=>["Hushed", "daroj", "starchitect", "Raymong", "haoma119"],
35565=>["Hushed", "Avemo3", "Aolivei8", "Raymong"],
35727=>["Hushed", "daroj", "wheresvic", "Raymong", "MotoGymkhana"],
35734=>["Hushed", "daroj", "wheresvic", "Raymong"],
36095=>["Hushed", "DrAwesome", "daroj", "Talbatross"],
36505=>["Hushed", "DrAwesome", "daroj", "Raymong", "cutebeast"],
37239=>["Hushed", "adam", "daroj", "Aolivei8"],
37499=>["Hushed", "DrAwesome", "daroj", "wheresvic"],
38086=>["Hushed", "daroj", "heliopolix", "Raymong"],
38603=>["Hushed", "DrAwesome", "daroj", "wheresvic", "Raymong", "BradT"]}
```

**Comment by jrt1817** [comment]
36789 is the game (see my link above).

**Comment by dfannius** [comment]
Hushed is not in game 36789. Can you double-check your info? michaeljb listed all the games that he thought you might be referring to in his latest comment.

**Comment by michaeljb** [comment]
@jrt1817 If you could share a link directly to the point in the game with the bug that would be the most helpful.

In the log you can click on any line and a "Review from here" button appears; click that and something like `action=123` will be added to the URL in your browser. You can also use the buttons next to "History" to move backward and forward through the game, adding or subtracting 1 to the `action` number. Then you can copy it here and that makes it easier for us to debug.

Based on a text search in the whole game log for "sells", this is the only point in 36789 where any player has sold shares, but as I explained in my first comment I don't think the site is mishandling the rules here: https://18xx.games/game/36789?action=420

**Comment by dfannius** [comment]
@jrt1817 This will probably be closed if you're not able to supply the requested information. Please read our responses carefully.

**Comment by jrt1817** [comment]
Yeah, I did, but I've played so many games that I couldn't track down the
game in question when Iooked.

Really sorry.  I'll look at my completed games one more time and see if I
can locate the proper game.

Thanks!

**Comment by jenf** [comment]
closing
