### ISSUE TITLE
[18CZ] Companies ability button not working

### ISSUE THREAD

**Issue by DarthIA** [tobymao/18xx#5128]
I am trying to use the ability of a large company owned by PR, and the button does not show the text of the ability like before, so I cannot lay a purple tile nor I can sell the company to the bank. Additionally, if I click on the company button, and go to another tab (e.g. Entities), the game freezes, not letting me to go to another tab, and I have to refresh the page.

The game ID is https://18xx.games/game/37445 and I am using Chrome 90.0.4430.85 (MacOS).

**Comment by Zwergenpunk** [comment]
Yep thats broken =(
