### ISSUE TITLE
Redraw tiles to make it obvious that you cannot change track at a crossover

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#513]
These Vassal tiles (for a different game) should give you an idea of what I mean:

![image](https://user-images.githubusercontent.com/15707007/82784150-da4c5380-9e57-11ea-8366-8b9bc97ad204.png)

It's visually obvious that you can't change track at the crossover as one track lies on top of the other.  

Probably not necessary for experienced players, but as a noob I've been caught out by misreading the tiles. 

EDIT: The Carthaginian redesign came up with an elegant way of doing the crossovers: 

![image](https://user-images.githubusercontent.com/15707007/82784623-d79e2e00-9e58-11ea-93e8-c0b4179a18d4.png)

**Comment by roseundy** [comment]
I have a thought on how to do this, but I'm not sure how robust it will be.

**Comment by roseundy** [comment]
This is what I'm implementing:
![crossover_2](https://user-images.githubusercontent.com/8494213/94375432-cd26c600-00d0-11eb-8a39-3e4ec79dcfa9.png)
![56_crossover](https://user-images.githubusercontent.com/8494213/94375434-d152e380-00d0-11eb-9ccf-591b962aa764.png)
