### ISSUE TITLE
[Harzbahn 1873] Buying a switcher with maintenance costs that seller should pay caused wrong message and didn't work

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#5130]
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/35738

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In Operating Round 6.2 the QLB wanted to buy the 3S from Mine #8 of the CO for 1M.
- Since in the present game phase the 3S incurs maintenance costs of 30M, either the buying or the selling company must pay these costs.
- The default procedure is that the buyer pays.
- But there is a small box that can be ticked so that the seller pays.
- The QLB director ticked this box and then pressed "Buy".
- After that, the system unexpectedly didn't perform the transfer of the 3S and the money as desired.
- Rather, there came the following message: "Seller has insufficient funds to pay maintenance."
- In fact, this is incorrect since the seller, the CO, still has 85M, enough to pay the 30M maintenance costs.

Klaus Kiermeier

**Comment by KlausKiermeier** [comment]
Maybe the program tried to get the 30M maintenance costs from Mine #8, and not from the CO.

**Comment by roseundy** [comment]
Yes, very likely Klaus.

It wouldn't be the first time I have to handle a minor owned by a major specially.
