### ISSUE TITLE
Abhorrent language in chat

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#5132]
This is entirely inexcusable and indefensible. Jokes about sexual assault have no place in society. Period.

I hope the admins of this site are in agreement with this.

![081B6484-24DE-401D-B151-EAD766EB9619](https://user-images.githubusercontent.com/64490754/116015574-5ff3f880-a5ff-11eb-9914-6928cd24fdf2.jpeg)

**Comment by SmithInMN** [comment]
I’m so completely disgusted by this language and this behavior, I can’t even express it.

This transcends offensive on any number of levels. This needs to be addressed.

![7FA3FDA5-2FAB-422B-8232-8810815D3C3C](https://user-images.githubusercontent.com/64490754/116015765-1eb01880-a600-11eb-925c-ff578a4facb1.jpeg)

**Comment by tobymao** [comment]
agreed. the mods are aware thanks for the report.

**Comment by SmithInMN** [comment]
Thanks, Toby... I appreciate it.
