### ISSUE TITLE
Confirmation dialog is ambiguous when purchasing from another player

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5134]
When a player tries to buy something from another player, there is a yellow warning box with text
> This action requires consent from SellingPlayer!  [Confirm]

This language is ambiguous as to whether the buying player is confirming that they *need* consent or that they *have* consent.
18xx.games interprets a confirmation as *having* consent.

Changing the implementation is difficult and will delay async games.
Changing the dialog seems appropriate.

**Comment by KevinR1000** [comment]
See pull request https://github.com/tobymao/18xx/pull/5133

**Comment by KevinR1000** [comment]
See also issues https://github.com/tobymao/18xx/issues/5111 and https://github.com/tobymao/18xx/issues/5065, just in the past 10 days.

**Comment by michaeljb** [comment]
Closed via #5133
