### ISSUE TITLE
18CZ tile upgrade with local RR not possible

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#5135]
game, Id: 38092, 18CZ: Phase e - Operating Round 5.1 (of 2) - Lay/Upgrade Track
      "id": 437,

Player Billbold as President of NWB want to use the ability of his local RR, do upgrade a tile from 58 to green/violett.
When selecting F13, no tiles where shown.

**Comment by Zwergenpunk** [comment]
Already fixed. Should be deployed soon
