### ISSUE TITLE
[1830] Eire Has No Route But Forced to Buy a Train - Game 36941

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#5137]
https://18xx.games/game/36941

Eire has deliberately set so that it does not have a route.  Somewhere in the calculation the system is deciding Eire does and is forcing a train buy.

**Comment by rheretic** [comment]
1830: Phase 5 - Operating Round 7.1 (of 2) - Buy Trains - Eire

(I'm buying the train to push the game along for my friends.)

**Comment by dfannius** [comment]
When I try it in hotseat mode, Erie can just click the Skip (Trains) button and not buy a train. Can you confirm that it's forbidding you from not buying a train? You may also want to refresh the page before trying just in case. If possible, a screenshot would prove that something weird is going on.

**Comment by dfannius** [comment]
Here's what I see in hotseat mode:

<img width="580" alt="Screen Shot 2021-04-26 at 11 34 27" src="https://user-images.githubusercontent.com/1295244/116110122-67f57c00-a683-11eb-837f-5de348d04e98.png">

**Comment by dfannius** [comment]
(I also see the Skip (Trains) button this moment when I look at the current state of your game, not in hotseat.)

**Comment by rheretic** [comment]
Wow!  I just F5'ed and the line Eire must buy a train went away.

**Comment by rheretic** [comment]
It was there five minutes ago!

**Comment by rheretic** [comment]
[11:22]rules_heretic: Bug!
[11:29]rules_heretic: My Eire has no route but the system is forcing me to buy a train. At this point it doesn't matter to me that much since I'm not going to win anyway. I have submitted an Issue on this. We're going to proceed as if I had actually wanted to buy the 5T.
[11:38]Puck017 : I think I had the same issue in the game Len Bankrupted me. I thought since the Ny
[11:38]rules_heretic: F5 has cleared this now.
[11:39]Puck017 : NYC tile hadn't been placed I wouldn't have to buy a train, but it made me anyways.

This is comments being added to the game by another player.  This is some Issue here for certain even if it is weird and intermittent.

**Comment by dfannius** [comment]
OK, glad it's resolved. I'll leave this up for now in case another dev thinks there's something worth looking at.

**Comment by rheretic** [comment]
You might actually be able to reproduce this by rolling the game back to the beginning of my OT and take the actions that I took.
