### ISSUE TITLE
[18CZ] game 38092. RR Can't place a purple border tile

### ISSUE THREAD

**Issue by billbold2** [tobymao/18xx#5138]
Action: https://18xx.games/game/38092?action=438

Data: https://gist.github.com/benjaminxscott/f5a4da590fee3c1af986a3dfb3d9cfa7

The NWB is unable to place a purple border tile in hex F13 via the Rauditz-Kmetnowes local RR. Am I reading the rules wrong or is this a bug? PDF of my screen attached.
[18cz game 38092.pdf](https://github.com/tobymao/18xx/files/6378411/18cz.game.38092.pdf)

**Comment by Zwergenpunk** [comment]
Fix will be deployed soon
