### ISSUE TITLE
Strangely, the 7 "2-train" turn into 6 in 18Chesapeake

### ISSUE THREAD

**Issue by hadesfury** [tobymao/18xx#514]

**Comment by gchambers419** [comment]
Actually, there are 6 2trains in 1889, and 7 in 18ches.  They are individual games after all.  Counts confirmed  in downloaded rulebooks.

**Comment by hadesfury** [comment]
Yes, sorry if I was not clear enough but during our game, when we bought the 6th 2-train, the next one was a 3-train .. so it does not take the value on "7" correctly or there is some other think I did not take notice of. Here is our game https://18xx.games/game/1245

**Comment by dfannius** [comment]
A 2-train was exported at the end of OR1. See section 11.9 in the 18Chesapeake rulebook.

**Comment by dfannius** [comment]
I think this issue is resolved so I'm closing it; if you think there is still an issue please reopen it with the new info.
