### ISSUE TITLE
[18CZ] - plus trains (like 2+2b) do not count number of towns correctly

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#5140]
https://18xx.games/game/34045?action=411 - [cloned in a gist](https://gist.github.com/michaeljb/c880451ab3ec4d76df8510b20e8b51be)

At this point, the ATE has a 5+5 train and should be able to start a route at the town in A10 which hits the 3 cities at B9, D17, and B13, ending at the town in B15, and hitting all towns along the way. That makes a total of 3 cities and 6 towns, and the route gets flagged as illegal.

18CZ rulebook:

> **Plus-Trains** (medium trains for medium companies, blue)
> may travel through the total number of revenue locations up to
> the number stated on the card, with the restriction that the
> maximum number of cities and red tiles included on the route is
> the first of the two numbers shown. For example, a 3+3 train may
> travel through at most 6 revenue locations, no more than 3 of
> which may be cities or red tiles. As with normal trains, the length
> of the track is immaterial and no revenue locations on the route
> may be omitted.

Therefore, a 5+5 train should be able to hit 10 locations, with up to 5 of them being cities/offboards, so this route with 3 cities and 6 towns should be allowed (and its "Used" should probably be rendered as "4+5"):

![Screenshot 2021-04-26 142123](https://user-images.githubusercontent.com/1045173/116145574-bbbf8f80-a69a-11eb-9396-ee050b5f121e.png)

1868 Wyoming features plus-trains that behave in the same way, so I modeled its plus-trains after 18CZ's but quickly found they did not quite behave correctly in 1868 Wyoming, and then I found that they are not behaving correctly in 18CZ either.

**Comment by roseundy** [comment]
All of the trains in 1860 work like this.

**Comment by michaeljb** [comment]
Current `distance` definition for 18CZ's `5+5h` train:

```ruby
[{ 'nodes' => %w[city offboard], 'pay' => 5, 'visit' => 5 },
 { 'nodes' => ['town'], 'pay' => 5, 'visit' => 99 }],
```

Following the model used in 1860, I set it to:

```ruby
[{ 'nodes' => %w[city offboard], 'pay' => 5, 'visit' => 5 },
 { 'nodes' => ['town'], 'pay' => 5, 'visit' => 5 }],
```

Now that route is valid, but under-reported. It shows "3+5" is used, and the last town isn't counted. The value of this route is 200K before adding the last town, and remains 200K after adding it:

![Screenshot 2021-04-26](https://user-images.githubusercontent.com/1045173/116155535-705fae00-a6a7-11eb-8202-59b2a2402ba2.png)

I'm also concerned that the `'visit' => 99` allows for hitting more towns than is allowed by the 18CZ or 1868WY rules.

-----

Just got promising results with this config, will need do some more testing and then either update 18CZ's `route_distance` method to report this as `4+5`, or decide that `3+6` is acceptable.

```ruby
[{ 'nodes' => ['town'], 'pay' => 5, 'visit' => 5 },
 { 'nodes' => %w[city offboard town], 'pay' => 5, 'visit' => 5 }],
```

![Screenshot 2021-04-26 155521](https://user-images.githubusercontent.com/1045173/116155801-dcdaad00-a6a7-11eb-8117-da4e0f57a5fb.png)

**Comment by michaeljb** [comment]
Think I've got something working to report it as `4+5`, will try and submit a PR tonight.

**Comment by roseundy** [comment]
Unfortunately, 1860 has it own custom compute_stops and check_distance. I did find and fix a bug with the default check_distance for one of the games I implemented. There might still be one in compute_stops.

**Comment by roseundy** [comment]
OK, don't look at 1860, look at 18Mag. And in fact, you have to look at the distance I substitute in for a normal train distance to implement an N+M train that a normal train can be modified into:
`                         {
                           nodes: %w[city offboard town],
                           pay: route.train.distance,
                           visit: route.train.distance,
                         },
                         {
                           nodes: %w[town],
                           pay: route.train.distance,
                           visit: route.train.distance,
                         },
`

**Comment by Zwergenpunk** [comment]
Thanks. I did not know that :)
