### ISSUE TITLE
[18CZ] No stations allowed in the home hex of ATE when closed before operating

### ISSUE THREAD

**Issue by DarthIA** [tobymao/18xx#5146]
In https://18xx.games/game/37445?action=716 SX cannot establish a station on B9, even though ATE is already closed. The situation is very particular, since ATE floated the previous SR, but then kk acquired ATE before its first operating turn.

![image](https://user-images.githubusercontent.com/24686708/116252106-8d5fb400-a76f-11eb-8cd4-1f84b4a8758a.png)

Just reproduced the bug by cloning the game from that step and trying to lay a token on B9.

**Comment by Zwergenpunk** [comment]
Hehe intresting...should be an easy fix when. Can do it tonight I think.
