### ISSUE TITLE
Harzbahn mine display

### ISSUE THREAD

**Issue by Bobsson** [tobymao/18xx#5149]
In Harzbahn 1873, some of the mines have a transparent background and also a black border around the numbers to indicate what machine/switchers they have.  On the default black background of the site, the borders are therefore invisible.

Compare the highlighted vs unhighlighted versions of the company card, and the display above it (which can't be highlighted).

![image](https://user-images.githubusercontent.com/2022339/116267976-dfdaa980-a74a-11eb-899d-f1b5a6b3caa3.png)![image](https://user-images.githubusercontent.com/2022339/116268029-e9641180-a74a-11eb-95ed-95c17b449095.png)

**Comment by roseundy** [comment]
Dup of #4913
