### ISSUE TITLE
[1870] SCC Token Cannot be placed in Houston

### ISSUE THREAD

**Issue by iansc-18xx** [tobymao/18xx#5151]
1870 game 38345.

I am unable to place the Southern Cattle Company token in Houston [M6] (which should be allowed), but I am able to place it in Baton Rouge [M14] (which should be illegal).

**Comment by benjaminxscott** [comment]
Presumably `N1` (Southwest) is also valid, which was missing

Which game is this? The ID listed is a 1889 game

**Comment by iansc-18xx** [comment]
This is game 38435. Thanks.
