### ISSUE TITLE
1822: error in turn sequence when train limit changes

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5152]
In the below-linked 1822+ game, there was an anomaly in the turn sequence around the noted action.
https://18xx.games/game/39190?action=865

In the game, the following things happened:
(1) The first minor for auction (M22) was not bid on, so the first 5T was discarded.
(2) The first minor in the turn sequence (M4) started its OR and made a decision on whether to acquire privates.
(3) LYR and LBSCR needed to discard trains because they were over the new train limit (phase 5 has a 2-train limit).
(4) M4 continued its OR.

As far as I can tell, the proper sequence should be (i) 5T discarded, (ii) discard trains being over limit, then (iii) begin OR of first company.

**Comment by magnusfalt** [comment]
Thank you for the feedback. There already is an enhancement issue about this #4773. Im gonna close this.
