### ISSUE TITLE
Not Receiving Notifications

### ISSUE THREAD

**Issue by galfridus** [tobymao/18xx#516]
Playing 18Chesapeake, notifications is on in Profile. Not receiving notifications when it is my turn.

**Comment by tobymao** [comment]
if you have tab open with the website you will not receive emails.

**Comment by galfridus** [comment]
I would put a note on the profile page to make this clear.

Also, lots of people leave many tabs open - I would prefer to get emails regardless. (I certainly understand that you may not want to do that for technical or cost reasons.)

**Comment by galfridus** [comment]
Logged out of site, closed window, still do not receive notifications. Waited about an hour after it became my turn.

**Comment by tobymao** [comment]
pm me your email on slack

**Comment by tobymao** [comment]
i can see that you're logged actively pinging the site with this user name

**Comment by galfridus** [comment]
Toby,

Earlier tonight I was not. From around 5:48 PM to 8:16 PM (eastern US) I 
was logged out, my turn came up, no notification.

I am logging out now and closing the window again (before sending this).

Thanks,

Geoff


------ Original Message ------
