### ISSUE TITLE
[1822] Do not display Close Message for Highland/mini-Highland if they are not open

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5168]
https://18xx.games/game/39386?action=696

Currently, when a grey train is purchased, an event appears in the log that reads `Event: P15-HR and P20-C&WR now closes and its money returned to the bank --`

This causes some confusion because it could imply that one, or both, of the privates were still open (i.e. in player hands) and actually closed.  This message appears even in a 22MRS scenario where neither private were even in the game.

**Comment by KevinR1000** [comment]
Relevant code is in `/lib/engine/game/g_1822/game.rb ` at about line 729.
`def event_phase_revenue!`

**Comment by dfannius** [comment]
Fixed by #5173 (as brought to my attention by @andypymont).
