### ISSUE TITLE
Bankruptcy in 1860 doesn't cancel auto actions

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5170]
Selling shares normally cancels auto actions. But if a player sells shares, driving a company bankrupt, the SR immediately ends, and auto-actions are never cancelled.

A bankruptcy is an important *Event*. It should cancel auto actions, rather than somehow preserving the previous SR's auto actions.

We ran into this in game 39135

**Comment by roseundy** [comment]
@jenf, any insight?

**Comment by jenf** [comment]
Huh, never expected bankruptcy to occur in a stock round. I'll have a look

**Comment by roseundy** [comment]
The same solution will have to be applied to 1862 (which also has stock round bankruptcies). Note that both of these are corporate bankruptcies, not player.
