### ISSUE TITLE
[1822] LNWR unable to merge in connected minor 15, tile #142 at M36 Herford possible problem.

### ISSUE THREAD

**Issue by einarfaa** [tobymao/18xx#5172]
As the LNWR I was unable to merge in minor 15, even when they were connected through N37 and M36. Tile #142 in M36 is a possible problem as I was later able to merge in 15 in the same company going from a station in Birmingham I30.

[Link to the game at a time when the error can be reproduced](https://18xx.games/game/39343?action=399)
![Screenshot](https://user-images.githubusercontent.com/83393823/116518104-2279be80-a8d0-11eb-88d4-ba78008083f2.png)

**Comment by KevinR1000** [comment]
It appears that LNWR has insufficient cash to acquire 15.
M15 share price:  £90
Value of all M15 shares: £180

LNWR share price:  £70
Value of 2 LNWR shares:  £140
**Cash required from LNWR:  £40** (180-140)

Cash in LNWR:  £36

**Comment by crericha** [comment]
Per @KevinR1000 comment, not a bug.
