### ISSUE TITLE
Add new Email messages (Game Start, Game End)

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#518]
Send email at end of game with the score and final map and probably the spreadsheet view

**Comment by ChrisTheCat** [comment]
And a link back to the game.

**Comment by tobymao** [comment]
end game emails are enabled

**Comment by ChrisTheCat** [comment]
Enhancement request: allow users to select "receive all end game emails, regardless of other notification settings"

**Comment by dragon12** [comment]
Adding my +1 to @ChrisTheCat , and ditto for start game messages.
