### ISSUE TITLE
Recommended number of players

### ISSUE THREAD

**Issue by LuthienDaSilva** [tobymao/18xx#5185]
**What's your idea?**

When starting a new game (create new game), I believe it would be helpful if you state recommended number of players, much like stated on BGG.

**Comment by bridger15** [comment]
Not a bad idea.  A lot of people are trying out new games blind and we get a lot of questions in slack about what a 'good' number of players is for a given game or 'what game is best with x players'?

It would all be subjective of course.  But the "best at" and "recommended" options in BGG seem like good ways to allow for nuance.  Some games have a strong consensus that the game only plays well with X-Y players.  Others have a majority that like it at range X-Y, but a minority who say it's still interesting and just 'different' at Z players.  The first category would only list "best at", whereas the second category would have a "best at" and "recommended" listings.

**Comment by philcampeau** [comment]
Even just listing the supported player counts for each game would be helpful.
