### ISSUE TITLE
18Ireland: Stocks shouldn't be shown if emergency buy from discard and player can afford it

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#5187]
https://gist.github.com/adamranderson/d8eab8510bcaa9da9a17f4eb0b8f85fd
https://18xx.games/game/39612?action=381

DKR is emergency buying a train and is forced to buy 1H. Raymong has the money for the 6H after selling one share.

From 6.10 of rules.
"f the company enters emergency fund raising, the director may
choose whether to buy a train from the bank pool or from the
bank, even if the new train from the bank is more expensive"

**Comment by scottredracecar** [comment]
I think the implementation is correct. Raymong has enough money to buy a train wihout EMR so EMR is not allowed. This is a weird wrinkle in the 18Ireland rules.
https://boardgamegeek.com/thread/1937562/emergency-fund-raising

**Comment by jenf** [comment]
Updated action showing the sell shares interface incorrectly
https://18xx.games/game/41305?action=618
