### ISSUE TITLE
1849: Tidy up game end code and check bankrupcy actually works

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#5189]
Add a spec to cover all the game ends conditions for 1849
Check that bankrupcy actually works as intended (code inspection seems to indicate it won't end the game)
Remove the probably unnecessary game end code
Remove the stock market changes (as I think they're unnecessary now)

**Comment by tysen** [comment]
Bankruptcy doesn't end the game in 1849.

**Comment by jenf** [comment]
If only one player is left the rulebook says it does
