### ISSUE TITLE
Improvement in player resume on Stock Rounds

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#519]
Currently, In Stock Rounds, bellow corporations have the players monetary status.

In the attached image below it is possible to see the current info shows in these cards, each card contains some info about one player monetary status.

![image](https://user-images.githubusercontent.com/4177168/82855730-7a4ebf00-9ee2-11ea-8474-25ecd140c73c.png)

My suggestion is to exchange "value" to "net worth" if that do not contraries the game vocabulary or manual. **And mainly bellow that "net worth" line (currently "value") add two subdivisions of "net worth", "liquidy assets" and "non-liquidy assets" that summed should be the same as net worth.**

Objective: helps the own player and others to easily predict how much cash each player could generate if sells all available items to sell in this stock round, so "liquidy assets" are: cash, stocks that could be sealed without breaking rules (presidential-companies-rule and maximum stocks on market and maybe others). And non-liquidy assets should be everything else.

This liquidy-asset is a picture of the current stage in the round, and with the stock round going step by step those two values could change, and the proposal featured should not cover this changes inside the stock rounds, just updated after every round inside the stock rounds.

**Comment by tobymao** [comment]
#512 addresses this

**Comment by Djeefther** [comment]
Amazing!! Expecting this pull requests on merge.

PS: I've been opening a lot of issues, but all of them I look before on issues if it is not duplicated, also the opened and the closed. But not in pull requests and things like that. Great work.
