### ISSUE TITLE
18Ireland Id: Dongal tries to force other tiles to be connected

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#5193]
https://18xx.games/game/39559
DR power fails while laying track in F4 and E3 see SC

![Screenshot_20210501-105913_Chrome](https://user-images.githubusercontent.com/64490299/116777272-057af200-aa6e-11eb-8403-11e4a93e59f0.jpg)
![Screenshot_20210501-110010_Chrome](https://user-images.githubusercontent.com/64490299/116777276-0d3a9680-aa6e-11eb-9425-be48775501ec.jpg)
![Screenshot 2021-05-01 11123618Ireland](https://user-images.githubusercontent.com/64490299/116777728-39561780-aa6e-11eb-991b-3585c6d29bde.jpg)

Windows 10 goole Chrome

 one tile lay it is accepted

![Ire](https://user-images.githubusercontent.com/64490299/116777897-1d06aa80-aa6f-11eb-817c-b7164a63ff7b.jpg)

not sure if the following is also a bug?
teh small track bonus does not appear any longer after Colloney (E7) has been upgraded?

![Ire1](https://user-images.githubusercontent.com/64490299/116777959-9f8f6a00-aa6f-11eb-97b2-c145d9db7e64.jpg)

playing one more OR the small track bonus is calculated right
![Ire3](https://user-images.githubusercontent.com/64490299/116778368-c484dc80-aa71-11eb-8b28-3b264acc5dbe.jpg)

this constellation fails also:
![Screenshot_20210501-120140_Chrome](https://user-images.githubusercontent.com/64490299/116779326-00ba3c00-aa76-11eb-9703-6e07c3cc8d5e.jpg)

**Comment by jenf** [comment]
"teh small track bonus does not appear any longer after Colloney (E7) has been upgraded?:"

Colloney is no longer exclusively narrow-gauge so this is correct behaviour

**Comment by jenf** [comment]
https://18xx.games/game/39559?action=306 for the Dongal bug

**Comment by jenf** [comment]
not strictly an 18ireland bug but a more general bug.
