### ISSUE TITLE
Can't get game back to current State after a mistaken Undo

### ISSUE THREAD

**Issue by BobProbst** [tobymao/18xx#5195]
https://18xx.games/game/37268

I undid a game to the wrong point , I went to the start of NFL's 8.1 OR instead of 8.2. I laid a tile, realized my mistake and tried to undo back to the correct place.  I hit the Restart Turn to see if that would get me back etc. I'm stuck in 8.1.  However, when I look in the game data, I can see the actions from 8.2 that got me there.  So no one's moves are lost, the game's just in a state that we can't get out of without replaying the last OR.

I was not in Mastermode when any of this happened by the way.

Is there any thing that can be done?

**Comment by michaeljb** [comment]
OK so at https://18xx.games/game/37268?action=463 you undid to action 406, then laid a new tile

```
{
      "id": 463,
      "type": "sell_shares",
      "entity": 1487,
      "shares": [
        "HSM_1",
        "HSM_6"
      ],
      "percent": 20,
      "entity_type": "player",
      "user": 1487,
      "created_at": 1619873054
    },
    {
      "id": 464,
      "type": "undo",
      "entity": "NFL",
      "action_id": 406,
      "entity_type": "corporation",
      "user": 1487,
      "created_at": 1619873075
    },
    {
      "type": "lay_tile",
      "entity": "NFL",
      "entity_type": "corporation",
      "id": 465,
      "created_at": 1619873080,
      "hex": "B10",
      "tile": "57-1",
      "rotation": 2
    },
```

The only way to undo an undo is to immediately click "redo"; doing any actions other undo or redo create a new "branch" separate from the original one.

With the current implementation, there's no way for the game interface to get back to a different branch.

I can try manually removing actions from the game for you back to [action 461](https://18xx.games/game/37268?action=461), the start of NFL's turn in 8.2

**Comment by michaeljb** [comment]
I've removed all the actions after 461 (except for chat messages), so it's back to NFL's turn at the start of 8.2.

For posterity, here are the commands I ran in an `irb` console:

```
require_relative 'models'
Dir['./models/**/*.rb'].sort.each { |file| require file }
Sequel.extension :pg_json_ops

game = Game[37268]
actions = game.actions.select { |a| (a.action_id > 461) && (a.action['type'] != 'message') }
actions.each(&:delete)  
```

**Comment by BobProbst** [comment]
Thank you!

**Comment by Maxwell-Frank** [comment]
This is still broken.  I try to make my tile lay with the Nord and get an error message: 
![Nord Tile Lay](https://user-images.githubusercontent.com/75334833/116820993-73421f00-ab3d-11eb-8ae0-c0a0128f207e.png)

**Comment by michaeljb** [comment]
When I deleted the actions earlier, I didn't change the IDs on the chat messages that MantisToboggan originally sent, I think that's causing the conflict you're seeing. I've just deleted those chat messages, is the game working again?

**Comment by Maxwell-Frank** [comment]
Still doesn't work. Same error.

**Comment by michaeljb** [comment]
OK I've added back the chat messages I deleted and tweaked the action IDs, could you give it another try? Even just sending a chat message should be enough to verify it's working, so anyone should be able to test. @BobProbst @Maxwell-Frank
