### ISSUE TITLE
18Ireland Users who could have proposed a merger were autopassed

### ISSUE THREAD

**Issue by Anzelak** [tobymao/18xx#5196]
In [this game](https://18xx.games/game/39559?action=327), at the linked step, all users were auto-passed instead of being able to offer mergers. Having clarified the rules with the book and in the general chat, I feel satisified that this is a bug and autopass is not working as intended here.

**Comment by jenf** [comment]
Could you be more specific which players and what corps should be allowed to merge?

**Comment by Anzelak** [comment]
Sure @jenf. 

For example, I think Blobble should have been able to propose a merger between UR and LER but was autopassed:

![image](https://user-images.githubusercontent.com/81834688/116789493-12680780-aaa7-11eb-8e90-f7e6e9860f04.png)
![image](https://user-images.githubusercontent.com/81834688/116789501-1c8a0600-aaa7-11eb-9898-86e2cb9551c7.png)

That's [at this step](https://18xx.games/game/39559?action=328)

[I was autopassed here](https://18xx.games/game/39559?action=331) and, if I understand correctly, should have been able to propose mergers for UR/LER (as above) and also for WKR/WLR:

![image](https://user-images.githubusercontent.com/81834688/116789569-5955fd00-aaa7-11eb-9c8d-509af0c0c5bc.png)

**Comment by Maxwell-Frank** [comment]
Any player who holds at least one share in a merge-eligible company should be allowed to propose a merger even if they do not own shares of the other company.

**Comment by Anzelak** [comment]
Quick update: in the same game Anzelak/Blobble were autopassed in Merger Round 4, too :)

**Comment by Blobbley** [comment]
For the sake of clarity - Blobble was not autopassed in Merger Round 4. (I passed voluntarily). But I was in merger round 2.

**Comment by Anzelak** [comment]
Also occuring in this game https://18xx.games/game/39673. Merger round 3 (for Anzelak). Weird; I must be cursed :D
