### ISSUE TITLE
[1822]  Offshore Tax Haven not always included in player value

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#5200]
The Offshore tax haven value doesn't always should up in the player value.  It looks like the tax haven value is included, but there is a bug that it isn't always included. If I refresh the page, it isn't included. If I click on the entities tab, it is included after that (on both game and entities tabs). Strange.

https://18xx.games/game/35825?action=1109

**Comment by crericha** [comment]
Actually, it looks like the tax haven value is included, but there is a bug that it isn't *always* included. If I refresh the page, it isn't included. If I click on the entities tab, it is included after that (on both game and entities tabs). Strange.

**Comment by perwestling** [comment]
Also it does not seem to appear in the corporation charter, that TH owns a share.

![image](https://user-images.githubusercontent.com/2631151/117249075-46458300-ae41-11eb-9ea2-04702ffbf95b.png)

**Comment by magnusfalt** [comment]
Its tricky go get it to show on the corporation card because the share is stored on a "dummy" player. So it isnt in the player or corporation array.

**Comment by magnusfalt** [comment]
Ive really tried to not add any very special 1822 code in the base.

**Comment by dfannius** [comment]
If it is calculated correctly at the end of the game, then we should remove the bug label, which should be reserved for problems that prevent the game from being played correctly.
