### ISSUE TITLE
18Ireland Mergers

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#5201]
https://18xx.games/game/39559

I believe there are a number of issues with the implementation of mergers at the moment:

Currently people who should be able to propose mergers can't:

_RULES 7.2: 5-share companies to create a new 10-share company. The player making the proposal must be the owner of at least one share of at least one of the companies involved._

The end of merger rounds is also wrong:

_RULES 7.5: The merger round ends when all players have passed in turn. Proceed to the next share round. The priority deal card does not move during a merger round._

Currently, each player is offered to propose a merger once (or erroneously autopassed) and then the round ends. Instead of carrying on until each player passes in turn (like an SR). Ie. Rounds do not extend to a further circuit of turns when someone makes an action.

**Comment by Anzelak** [comment]
This references [the issue raised here](https://github.com/tobymao/18xx/issues/5196).

**Comment by jenf** [comment]
issue 1 is a dup of #5196
issue 2 is a dup of #5220
