### ISSUE TITLE
UR missing from Belfast bottom station location

### ISSUE THREAD

**Issue by treaty1691** [tobymao/18xx#5212]
UR missing from bottom location in Belfast hex .. as on real boardgame map ...

**Comment by michaeljb** [comment]
"UR" is one the tile to indicate that UR has a reservation there. I'm unsure if assigning UR's home reservation to one of the cities would affect game play, so I'll leave that to @jenf to figure out.

**Comment by jenf** [comment]
E21 is in the same situation on the physical board. I don't think it actually makes any gameplay difference as the tile isn't connected and the general erie home token rules apply.

**Comment by jenf** [comment]
It's correct behaviour to have tile reservation rather than city.

If it's associated with a city it'll follow the city, so when a tile is layed the reservation will be linked with the city causing issues.
