### ISSUE TITLE
[Harzbahn 1873] Please rise certificate limit to 999 or infinite

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#5214]
**What's your idea?**

In Harzbahn 1873 there may be, in theory, up to135 certificates in players' possession. Presently, the certificate limit is set to 99. This could be not enough, especially in a 2-player game. It is not very likely but could happen.
The idea is to rise the certificate limit from 99 to 999 or even to infinite, similarly to the infinite availability of yellow tiles in some games.

Klaus Kiermeier

**Comment by beorn7** [comment]
An explicitly infinite (“∞”) limit would also be clearer to the players, which affects more than just 1873 but all games with infinite limit. (In 1860, the limit becomes infinite during the game, for example.)

Not sure about how that works in Ruby, but if it has a notion of MaxInt or something, that value could be used, and it could be rendered in the display layer as “∞” rather than the actual (very large) number.

**Comment by roseundy** [comment]
Increasing the limit for Harzbahn is easy. Implementing an explicit infinite limit will take more work.

**Comment by roseundy** [comment]
The easiest thing is to change the limit to 999 and then disable showing it.

**Comment by KlausKiermeier** [comment]
I think this would do it.
Thanks, Steve. 
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Please rise certificate limit to 999 or infinite (#5214)
Datum: 2021-05-02T18:50:42+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
The easiest thing is to change the limit to 999 and then disable showing it.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/5214#issuecomment-830837813", "url": "https://github.com/tobymao/18xx/issues/5214#issuecomment-830837813", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿
