### ISSUE TITLE
Do not disable auto-pass, if the conditions haven't been met since enabling it

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#5215]
In this game: https://18xx.games/game/39177 I turned on auto-pass, then someone passed. It was my turn then and my auto-pass had been disabled:
```
[09:58]-- Enabled programmed action Buy Shares
[18:03]Miranda passes
[18:03]-- Disabled programmed action due to 'Shares were sold'
```
 I'm guessing that happened, because the engine considers every action since the user's last action. It would be nice though, if it only considered the actions taken after enabling auto-pass.

**Comment by slapphappyjazz** [comment]
I also noticed this, in a game of 18Ireland (https://18xx.games/game/39990 ,SR2).
