### ISSUE TITLE
18Ireland — player skipped during merger round 

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#5219]
**What's your Game ID?**
https://18xx.games/game/39912?action=346

**How to Reproduce the Bug?**

Player (adam) skipped in merger round for no apparent reason (action just passed).  He has several legal proposable mergers. (may be related to issue 5218 in the same game—potentially issues with the DD tile?).

**Comment by jenf** [comment]
looks like a dup of #5196
