### ISSUE TITLE
1889: Presidential Contributions during Diesel Upgrade

### ISSUE THREAD

**Issue by wiyumB** [tobymao/18xx#522]
Currently in 1889 (possibly also 18Chesepeake), a President may contribute funds when upgrading to a diesel for 800¥ (as opposed to only when trainless and buying it outright for 1100¥).

**Comment by jenf** [comment]
Do you have a game id to help use recreate?

**Comment by tobymao** [comment]
@jenf should be easy to add safety code to ensure this doesn't happen

**Comment by Spobster** [comment]
I did it with IR in game 877. And I have done it before with AR in game 892. It only works if you have no company at the start of your turn, then buy a 4T from another company and then your president can contribute upgrading that 4T to a D. It doesn't work if you start the company's turn with a 4T in the company's stock :)
