### ISSUE TITLE
[1822] Make whether a private company pays income when owned by a corporation more clear

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#5229]
Only a few companies have revenue when owned by a corporation (P2, P9, P11, P12). It would be useful to have an at a glance indicator of this on company cards. Suggestion: make the revenue field on the card display both values as player/corporation revenue. So P2 would display "Revenue £10/£10." P1 however, with no revenue when owned by a corporation, would show "Revenue £5/£0" This would only display on the private company card, the income field on a player or corporation card would display the relevant value as now.

**Comment by KevinR1000** [comment]
Note that the description of these privates already explain that owning companies earn revenue until closed.
See https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1822/entities.rb
Lines 29-31, 161-162, 206-207, and 230-231.

(This description does not appear on the physical cards.)

**Comment by physic** [comment]
It is quite clear on the physical cards. When you flip them over, they still clearly say +$10 income in large letters in the corner, not buried in the rules text on the card. This is definitely a chore on .games
