### ISSUE TITLE
1889: illegal tile upgrade

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#523]
Not sure if this has been noticed/fixed etc, it can be hard to keep up :) regardless:

<img width="478" alt="Screen Shot 2020-05-26 at 21 46 47" src="https://user-images.githubusercontent.com/830087/82908674-e3920900-9f9a-11ea-9c77-4369e9ff123b.png">
<img width="490" alt="Screen Shot 2020-05-26 at 21 46 52" src="https://user-images.githubusercontent.com/830087/82908692-e987ea00-9f9a-11ea-8ea1-ce77e2ea451b.png">
<img width="528" alt="Screen Shot 2020-05-26 at 21 46 57" src="https://user-images.githubusercontent.com/830087/82908697-eb51ad80-9f9a-11ea-9501-13fc7521a0ba.png">

**Comment by jenf** [comment]
Dup of #168
