### ISSUE TITLE
18Ireland - Merger Ties

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#5230]
https://18xx.games/game/40013?action=466

If a merger is a tie, then it doesn't go ahead. In this game, I had 5 votes for the merger and it went ahead immediately, despite the fact the other players could have collectively voted for 5 against, resulting in a tie and stopping the merger.

**Comment by jenf** [comment]
Updated action id is
https://18xx.games/game/40013?action=447

**Comment by jenf** [comment]
If you want to continue you game, I'd suggest undoing to this merger ASAP.
