### ISSUE TITLE
[1822] Stock market par values are misleading

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#5236]
The stock market shows that par prices are between 50 and 100; however, the 50 par price is only for minors. This is misleading when planning to par a major and being surprised when you can't open at 50.

**Comment by KevinR1000** [comment]
The physical copy distinguishes 50 from the other par values (50 is shaded, others are outlined).

In the MARKET table in game.rb, the higher par values are labeled `px` while 50 is labeled `p`.  So, we just need to find where `px` is interpreted.

**Comment by crericha** [comment]
You can use STOCKMARKET_COLORS constant to distinguish. 1817 may be a good example.

**Comment by KevinR1000** [comment]
I have untested code at https://github.com/tobymao/18xx/compare/master...KevinR1000:patch-2 .
The UI uses only the first letter to match colors/text to a stock market cell, so I replaced `px` with `b`, which then matches `both_par`.

**Comment by magnusfalt** [comment]
I think a text as well is needed if we are into this issue. Since in Phase 1, it doesnt matter how much you bid on a minor, it is always on 50, and so on.

**Comment by KevinR1000** [comment]
I'd debated labeling the main "both" par section as "Par value for Major or Minor (Phases 2-7)", but wasn't sure on space.  Once I have a development environment running, I'll be able to play around with text on the market tab.
