### ISSUE TITLE
 [18Ireland] - Game Crashed after company merger

### ISSUE THREAD

**Issue by casabian** [tobymao/18xx#5237]
**What's your Game ID?**
`https://18xx.games/game/40177`

**How to Reproduce the Bug?**
- Company merge succeeded
- Unable to move trains after merge
- Unable to enter the game

**Which Browser / Platform?**
- All Browsers

**Browser Logs**
`TypeError: NilClass can't be coerced into Numeric↵…    at https://18xx.games/assets/main.js:2:247703
client.js:24 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info`

**Comment by jenf** [comment]
Issue with Shannon private
