### ISSUE TITLE
Unread chat message indicator

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5239]
It's great that there are buttons now to show/hide the log and chat in the game, so you can easily see the chat messages. However, if a chat message has scrolled off screen (and almost all of them will before my next turn) it would be nice if there was an indicator "hey, there have been chats since your last turn, you should click the hide log button so you can see them."

Something similar to the pencil/paper icon by the Tools label that reminds you that you have personal notes would work.

**Comment by scottredracecar** [comment]
Good idea. I hope someone can implement this.
