### ISSUE TITLE
Chesapeake: B&S and C&P tile lays

### ISSUE THREAD

**Issue by webbtraverse08** [tobymao/18xx#524]
Currently, the B&S and C&P tile lay functions require two clicks on the privates, which would allow for someone to lay only one tile. These private companies should grant their owning company an ability to lay both or none. It also does not appear to enforce/require the two tiles be connected in all cases.

**Comment by gchambers419** [comment]
Also, the text of the privates says the powers can only but used during tile laying, but it appears they can be used immediately after buying them at the end of the round

**Comment by waaayback** [comment]
> 
> 
> Currently, the B&S and C&P tile lay functions require two clicks on the privates, which would allow for someone to lay only one tile. These private companies should grant their owning company an ability to lay both or none. It also does not appear to enforce/require the two tiles be connected in all cases.

I just found this bug today also.  I own the C&P and the game will allow me to lay 2 unconnected tiles as well as just 1 tile.

**Comment by waaayback** [comment]
> 
> 
> Also, the text of the privates says the powers can only but used during tile laying, but it appears they can be used immediately after buying them at the end of the round

It does not say that.  Show me where.  It just says it's "in addition to the company's tile placement action".  What you describe is legal.

**Comment by dfannius** [comment]
The text for the B&S private is (emphasis mine)

> Blocks hexes F4 and G5 while owned by a player. The owning corporation may lay two connected tiles in hexes F4 and G5. Only #8 and #9 tiles may be used. If any tiles are played in these hexes other than by using this ability, the ability is forfeit. These tiles may be placed even if the owning corporation does not have a route to the hexes. **These tiles are laid during the tile laying step** and are in addition to the corporation’s tile placement action.

The text for the C&P private is similar.

Scott Petersen has confirmed on Slack that this is the correct interpretation of the printed rules.
