### ISSUE TITLE
[1861] Allows my trains to stop at more stops than it should

### ISSUE THREAD

**Issue by bwobbones** [tobymao/18xx#5240]
**What's your Game ID?**
https://18xx.games/game/39089

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. https://18xx.games/game/39089?action=1038

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
I just was able to go to more stops than i should be able to.

![image](https://user-images.githubusercontent.com/705505/117081138-23598880-acf4-11eb-8341-ef1acd100cff.png)

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  90.0.4430.93 
- Platform (Mobile, Tablet, Desktop)

**Comment by jenf** [comment]
1861 trains optionally stop at towns. So while it shows 7 stops, it's only using 5 for payout.

(There's an enhancement to improve the 'Used' part)
