### ISSUE TITLE
[1822] Destination token abiltity text is truncated on lower resolutions

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5248]
The LNWR charter looks like this:
![image](https://user-images.githubusercontent.com/2631151/117131939-6b36e900-ada2-11eb-9bc3-cddaf5c8c45b.png)

As can be seen the text is cut a bit short. I believe it is possible to have a longer version that can be seen when expanding.

But the text says that it receives a token at I22 when floating. I am in a game (https://18xx.games/game/40016#entities) where LNWR did float during SR, and it is now OR. The I22 token has not yet appeared though. I assume it will appear when LNWR starts its operating, but we'll see.

Anyway, I think the text in the corporation charter might need some update.

**Comment by perwestling** [comment]
It might be a general problem in 1822 as there are more that are cut short.
![image](https://user-images.githubusercontent.com/2631151/117133226-493e6600-ada4-11eb-9bfc-658741606110.png)

**Comment by magnusfalt** [comment]
It depends on the resolution you have. If we gonna make everything responsive its a bigger job.

![image](https://user-images.githubusercontent.com/10232503/117254562-d6d39180-ae48-11eb-8a5b-44ed9dcedaac.png)

**Comment by magnusfalt** [comment]
Token location should be fixed in #5309
