### ISSUE TITLE
[1870] Id: 39875

### ISSUE THREAD

**Issue by ViennaTramways** [tobymao/18xx#5249]
The game is suddenly archived, and I have no idea why. But it looks like all 1870 games are archived.

**Comment by jenf** [comment]
The tile count was incorrect, which was fixed yesterday.

Alpha games when archived are likely because we've fixed a bug.

**Comment by daniel-sousa-me** [comment]
There were too many city tiles, so all games that used more than they should have been deleted. Sorry
