### ISSUE TITLE
1817 players not offered opportunity to buy shares after mergers and conversions

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5253]
https://18xx.games/game/31868?action=1302

- In the PW merger, uncle_milt was not offered the opportunity to buy a share at 165.
- In the PLE conversion, ChrisShaffer, uncle_milt, and beardbru were not offered the opportunity to buy a share at 100.
- In the A&S merger, uncle_milt was not offered the opportunity to buy a share at 150.

**Comment by KevinR1000** [comment]
At the linked action, Entities shows uncle_milt, ChrisShaffer, and beardbru at cert limit (5/5).

**Comment by ChrisTheCat** [comment]
Ahhh.... that super low 12 player cert limit, got it!
