### ISSUE TITLE
1822 - Unable to interact in stock round

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#5271]
Game: https://18xx.games/game/34492?action=709

After shionyann passed their SR turn, all of the bids have disappeared, and I can't interact with any of the entities. The problem persists when I clone. I even tried undoing everyone's SR turn and passing them until it's mine, but I still can't interact with anything.

**Comment by Maxwell-Frank** [comment]
Are you able to payoff your loan? I cloned the game and paid off your loan, and then was able to interact with the entities.

**Comment by Auzzy** [comment]
You're 100% correct. I forgot I took the loan, and looked right past the "pay off loan" button. Thanks!

**Comment by dfannius** [comment]
Do we consider it a bug that all the existing bids disappeared until the loan was paid off? That seems odd to me but I haven't played 1822.

**Comment by Maxwell-Frank** [comment]
@dfannius Already filed in #5024
