### ISSUE TITLE
[18Ireland] Cost of station token isn't 0 pounds

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#5275]
https://18xx.games/game/40351

https://18xx.games/game/40351?action=388

A station token of the merged company is shown as 0 pounds, but should be 50 pounds, see rules: 6.6 (p.8) and 7.4 (p.12)

**Comment by jenf** [comment]
maybe not a dup of #5307

**Comment by jenf** [comment]
correct, still an issue

**Comment by jenf** [comment]
https://18xx.games/game/40351?action=273
