### ISSUE TITLE
[Webhooks] Custom Discord webhooks not recognized.

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#5289]
Attempting to add a discord webhook currently results in the error "webhook_url only supports Slack and Discord, let us know if you want others" A discord webhook should look something like this: https://discordapp.com/api/webhooks/840703942626115634/urgw6SuZkhbu0SdYXeNZZi0w0cgRGScBKNekjBY2yBuxmZRez4_enXRa8w9P3nIz4OjV 
If it is looking for discord.com, it may be getting confused by the "discordapp.com" in the link.

It would be useful to include this link in the wiki page so people know how to create a webhook in discord: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

...also currently webhooks send notifications for every action, which I assume is more than intended.

**Comment by Auzzy** [comment]
I've also been seeing a notification for every action. I've submitted a separate issue to make it easier to track/find: https://github.com/tobymao/18xx/issues/5291

**Comment by tobymao** [comment]
fixed, you can edit the wiki yourself

**Comment by gpanders** [comment]
Is this fix deployed? We are not receiving webhooks for discordapp.com URLs, but they work for discord.com URLs.

It looks like the case branch [here](https://github.com/tobymao/18xx/blob/master/lib/hooks.rb#L17) needs to be updated.
