### ISSUE TITLE
1822 base game: starting cash for 5 player game is 525, not 420

### ISSUE THREAD

**Issue by claytonRR** [tobymao/18xx#5290]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by KevinR1000** [comment]
It appears that this refers to this game:  https://18xx.games/game/40884?active=4
5 players, each with 420.  That is consistent with rulebook (Kickstarter printing).

Code looks correct, matching the figures in the rulebook:

<img width="530" alt="Screen Shot 2021-05-08 at 22 59 43 " src="https://user-images.githubusercontent.com/82781561/117560212-53d15780-b051-11eb-8bec-d45312745175.png">

https://github.com/tobymao/18xx/blob/e662f019a5ec95327ef1e02f29b935b5c9525a36/lib/engine/game/g_1822/game.rb#L42

Also true for **Medium Regional Scenario**:
<img width="154" alt="Screen Shot 2021-05-08 at 23 00 32 " src="https://user-images.githubusercontent.com/82781561/117560222-5df35600-b051-11eb-9a64-95006c2d0ede.png">

https://github.com/tobymao/18xx/blob/e662f019a5ec95327ef1e02f29b935b5c9525a36/lib/engine/game/g_1822_mrs/game.rb#L37

And for **North Regional Scenario**:
<img width="154" alt="Screen Shot 2021-05-08 at 23 00 58 " src="https://user-images.githubusercontent.com/82781561/117560228-6481cd80-b051-11eb-8514-2ff161ad74b9.png">

https://github.com/tobymao/18xx/blob/e662f019a5ec95327ef1e02f29b935b5c9525a36/lib/engine/game/g_1822_nrs/game.rb#L36

**Comment by claytonRR** [comment]
I think that is a case of user error (mine) for misreading the tables.
Table 1 in the locked rule from May 1, 2018 for publication in 2020 is
split across two pages. Evidently, I saw the bid tokens as number of
players on the last row of the bottom half. Thanks for the heads-up.
