### ISSUE TITLE
custom slack webhooks not recognized

### ISSUE THREAD

**Issue by thebamaman** [tobymao/18xx#5292]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

**How to Reproduce the Bug?**

Trying to save a custom webhook of the form "https://hooks.slack.com/services/..." causes a similar banner at the top (webhook_url not recognized...) as the earlier discord bug.

**Which Browser / Platform?**
Google Chrome | 90.0.4430.93 (Official Build) (64-bit) (cohort: Stable)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.928)
JavaScript | V8 9.0.257.23

**Comment by tobymao** [comment]
fixed
