### ISSUE TITLE
[1861] In SR, show companies in operating order

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#5295]
During the SR, the companies are shown in price order.  In many games, this is also the operating order.  In 1861, all minors operate before majors.
Our group thought the UI would be clearer if the minors were displayed first.

(This was partly to make it easier to see which companies are minors and which majors.  I see that, since we played, there has been a change to the logos to make this clearer, which is good.  The issue of operating order still stands).

**Comment by scottredracecar** [comment]
This needs to be done in game-specific code. Different games handle this differently and it is up to the implementer to decide how or use the default.

For 1861 in particular, I would suggest that most of the SR actions pertain to public companies, not minors, so they should be presented first.

I would suggest that if you don't like how a certain game has implemented this to file a specific issue and if someone is maintaining it, it may be fixed. Ultimately it is a judgment call.
