### ISSUE TITLE
Make it obvious how to ping a player whose turn it is

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#5297]
I wanted to "ping" the current player in an async game, to remind them it was their turn.  (I suspected they had missed the automatic notification, and it turned out this was indeed the case).  I couldn't see how to ping them, so I resorted to e-mail outwith the game.  rr18xx has a button on one of its tabs to remind a player that it's their turn.

After trawling the docs this morning, I found that typing "@user" in the chat will send them a message.  But it's not obvious from the UI.  Here are some suggestions for making this easier.

1 - add a sentence to the help or the tools page

2 - add help text to the chat box itself, that is deleted when you start typing in the box

3 - add a "notify current player" button, either next to the chat box or on the Tools page.  Selecting this would switch to the chat box and enter "@user" - so the player selecting this option will quickly learn how to notify from the chat.

3a - a for option 3, but use with a "notify player" button that brings up a drop-down list to select the player to notify.

4 - make the player name on the Game page into a menu, with options to notify the player (as above) or view profiler.

**Comment by marndt93** [comment]
What if a mail icon was added next to each player name on the game page.  Clicking this would add the ping message to the chat.
![image](https://user-images.githubusercontent.com/28715646/151258474-4c3efc6d-b9f9-4931-abb0-163f4aab77ac.png)

Alternatively a placeholder could be used to show the notify player command
![image](https://user-images.githubusercontent.com/28715646/151259207-e808da3c-4815-4f2c-b636-278e82fe351e.png)

**Comment by tobymao** [comment]
let's go with placeholder, very elegant and clear

**Comment by slapphappyjazz** [comment]
Looks good, but the message should use the same word in both places, either
Use @player command to ping a player, or
Use @user command to ping a user.

**Comment by marndt93** [comment]
I was planning to use "Use @username command to ping a user" to remain consistent with the message in the Tools tab.

**Comment by slapphappyjazz** [comment]
Sounds good to me.
