### ISSUE TITLE
Change text of "Skip (Companies)"

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#5298]
This button would be better as either 
"Skip (Privates)", or
"End Turn".

This has bugged me since the launch of the 18xx.games site.  Maybe it looked sensible when implementing 1889 to call private companies "companies", contrasted with "corporations", but this is not a standard 18xx terminology.  Everyone I know calls private companies "privates" - it's common to call "pay the privates" at the start of each OR.  Many games use the term "public companies" or "major companies" for ordinary companies, rather than "corporations".  And in everyday English, people rarely distinguish between a "company" and a "corporation".

Also, the phrase "Skip (Companies)" implies that there is a "buy companies" phase which is being skipped.  This isn't true.  What the button is actually prompting for is to confirm that the player is ending the turn, so "End Turn" would be a more accurate label.

Arguably, the UI could be enhanced by adding a "buy privates" button whenever this is a viable action, as a reminder that this is an option.  At present, you have to scroll down to see the private companies, so the UI isn't presenting all the available options in a user-friendly way.

**Comment by tobymao** [comment]
there is no standard. the closest we have is 1830 which calls them companies vs corporations. 18xx.games has standardized on these terms.
