### ISSUE TITLE
1882 - Player 1 has 13/14 certificates, but cannot purchase a share. 

### ISSUE THREAD

**Issue by crambaza** [tobymao/18xx#5302]
Player 1 is at 13/14 certificates, but cannot buy another share. We are at D trains, and all privates have closed.

Player 1 did previously have the Saskatchewan Central Private, which allowed them to open the SC public company, but I don't know if this has anything to do with the bug. The other players, 2 and 3, are able to reach 14 certs. 

**What's your Game ID?**
Id: hs_grwgrrbu_1620593473

https://gist.github.com/crambaza/0d05169ade0098a21d0337fa4c90594a

**How to Reproduce the Bug?**

Player 1 is trying to buy a share, but cannot.

**Comment by dfannius** [comment]
What specific share is Player 1 trying to buy? When I open that game in hotseat, Player 1 can buy CNR or SC shares from the market, which are the only shares they can afford.

**Comment by crambaza** [comment]
Oh my goodness, I'm a total idiot, and I apologize for wasting your time.

Please delete my issue inquiry.

Curt

________________________________
