### ISSUE TITLE
1849: can somehow submit dividends as different corporation

### ISSUE THREAD

**Issue by mtg3992** [tobymao/18xx#5306]
After action 564, when CTL ran, it paid out and adjusted the stock price of IFT instead. After an undo, it behaved correctly. Not sure if this is a bug or just a microchip farting.

**Comment by jenf** [comment]
https://18xx.games/game/40465?action=565

**Comment by jenf** [comment]
Strange
`    {
      "type": "dividend",
      "entity": "IFT",
      "entity_type": "corporation",
      "id": 565,
      "created_at": 1620580415,
      "kind": "payout"
    }`

**Comment by scottredracecar** [comment]
game is archived now
