### ISSUE TITLE
1817 home tokens incorrectly labeled

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5307]
https://18xx.games/game/31868?action=1374

The UR tokens should be listed as H9 and G6, not 0 and G6. Similarly, the home tokens on the A&A and PSNR charters shown should be listed with coordinates and not 0.

<img width="683" alt="Screen Shot 2021-05-10 at 8 57 02 AM" src="https://user-images.githubusercontent.com/8732435/117688520-b1f35d00-b16d-11eb-87d3-838c50ddec54.png">

**Comment by jenf** [comment]
dup of #5127

**Comment by jenf** [comment]
At ?action=206 it shows correctly
But then disappears by ?action=353
Disappears at exactly ?action=268
