### ISSUE TITLE
1822 L train purchases by Major

### ISSUE THREAD

**Issue by Dirkxx** [tobymao/18xx#5311]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by Dirkxx** [comment]
When i look at the rules in 5.5.3 it says L trains can only be purchased by Majors. The last game i played i was able to purchase an L train in the first operating round of LNWR from the bank pool?

**Comment by bazik123** [comment]
this is a big issue as it has a side effect of forcing majors to emergency purchase L trains, meaning it's much harder than it should be to open a major with 100$ and spend some money on track building

**Comment by Dirkxx** [comment]
I guess I miss read the rules...
It states “5.5.3 A minor company (only) may buy an L-train, if any remain available for purchase from the bank or bank pool”
Is the intent that a Minor company can ONLY buy an L-train?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Dirkxx** [comment]
Correct but I was able to buy a L train with a Major on my first turn before being able to operate.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dfannius** [comment]
Looking at the code, it definitely is attempting to implement the rule in which, during First Turn Housekeeping, only minors may purchase L trains. Unless you provide a link to a game and action demonstrating an issue, I'm going to assume that in your game a major bought an L train in step H of 5.3 Operating Round Actions, which is perfectly legal, not in step A, which wouldn't be. Of course if there really is a bug and it can be demonstrated it will be fixed.

**Comment by Dirkxx** [comment]
I’ll look at it again tonight.

Derek Smith
613-898-6364

On May 15, 2021, at 9:20 PM, Dan Schmidt ***@***.***> wrote:

﻿

Looking at the code, it definitely is attempting to implement the rule in which, during First Turn Housekeeping, only minors may purchase L trains. Unless you provide a link to a game and action demonstrating an issue, I'm going to assume that in your game a major bought an L train in step H of 5.3 Operating Round Actions, which is perfectly legal, not in step A, which wouldn't be. Of course if there really is a bug and it can be demonstrated it will be fixed.

**Comment by Dirkxx** [comment]
Ok I have reread the rules and understand what you are referring to when you say first turn house keeping. So you are correct. The L train was bought after the run trains phase of the turn in which the major did not operate because it had no trains. All legal as I now understand from your description.

Derek Smith
613-898-6364

On May 16, 2021, at 7:05 AM, Derek Smith ***@***.***> wrote:

﻿ I’ll look at it again tonight.

Derek Smith
613-898-6364

On May 15, 2021, at 9:20 PM, Dan Schmidt ***@***.***> wrote:

﻿

Looking at the code, it definitely is attempting to implement the rule in which, during First Turn Housekeeping, only minors may purchase L trains. Unless you provide a link to a game and action demonstrating an issue, I'm going to assume that in your game a major bought an L train in step H of 5.3 Operating Round Actions, which is perfectly legal, not in step A, which wouldn't be. Of course if there really is a bug and it can be demonstrated it will be fixed.

**Comment by dfannius** [comment]
Great, thanks for checking. I’ll close this up.
