### ISSUE TITLE
Add Game Description to Webhook pings 

### ISSUE THREAD

**Issue by dangolder** [tobymao/18xx#5312]
Original: As a masochistic 18xx player who plays too many games, I want to be able to see at a glance which games it is my turn in, so that I don't have to memorize dozens of IDs 

**Update after conducting user interviews:**
As a masochistic 18xx player who plays too many games at once, I want to be able to see at a glance which games it is my turn in, so I know if I am up in games that I can act quickly in or if it's something that will require more thought

It would be great if we could (perhaps optionally?) add game title and/or description to our webhook pings.

**Comment by dangolder** [comment]
Some context in our Server Suggestions: https://discord.com/channels/692794539169284186/748984795568013373/841713589894774795

Invite if you're not already in: https://discord.gg/zwfXrYa8wT

**Comment by tobymao** [comment]
to be fair, there was no need for you to memorize a dozen ids anyways, if you go to the home page, you'll see which games need a move

**Comment by dangolder** [comment]
good point -- I updated my user story to reflect a deepened understanding of the "Masochistic 18xx Player" persona
