### ISSUE TITLE
Take SR turns from Entities tab

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#5313]
Stock Round: Would be wonderful if one were able to take turn from the Entities tab. This information is usually needed to make an infomed decision anyway. Related to this: It would be lovely if the 2+ corporations owned by each player were listed top to bottom in their current Operating Order; even better for titles where active changes due to stock selling could be immediately reflected

**Comment by scottredracecar** [comment]
All the game actions are done in the game tab. It's just the way it is designed. :-)
