### ISSUE TITLE
[18Ireland] UI not allowing narrow gauge lay in hex e3 (or narrow-only upgrade in f14)

### ISSUE THREAD

**Issue by thebamaman** [tobymao/18xx#5320]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

**What's your Game ID?**

https://18xx.games/game/39838

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. https://18xx.games/game/39838?action=549

![18ireland-narrow-bug](https://user-images.githubusercontent.com/14103648/117901511-1bb85780-b291-11eb-8778-3a8c7028fef8.png)

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

During OR7.1 as MRNCC I tried to lay a narrow gauge track on hex e3 so as to extend to d4 to improve the value of Londonderry.
The UI only presented broad gauge track as shown in the screenshot.
I also tried to upgrade F14 to continue the narrow gauge network from there, but I was only presented with broad/narrow gauge extensions from Maryborough.

**Which Browser / Platform?**
Google Chrome | 90.0.4430.93 (Official Build) (64-bit) (cohort: Stable)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.928)
JavaScript | V8 9.0.257.23
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**Comment by BGarmon80** [comment]
I've had this occur in a game I was playing, but it was archived last night. Different location, but same situation where a broad and narrow gauge track were leading toward the new track space and the only options given were broad gauge.
