### ISSUE TITLE
[1822+] Descriptions of P3 and P4 are inaccurate

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#5327]
The description of P3 and P4 state "A company may not own more than one 2P train.", which is missing the information, that a company owning a 2P train cannot own an LP train. The description of P19 reflects that correctly: "A company cannot own a permanent L-train and a permanent 2-train."

It would be nice if the descriptions of P3 and P4 could be adjusted, since that can lead to some confusion.

Edit: I don't know why this got the "needs triage" label and I can't remove it, it seems.

**Comment by benjaminxscott** [comment]
When issues are created, they have `needs triage` label auto-added so maintainers can tell which ones have been triaged or not
