### ISSUE TITLE
[1828.games] Auto buy bought a pre merger share in a merged company after the company merged

### ISSUE THREAD

**Issue by Picklesgrr** [tobymao/18xx#5333]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

https://18xx.games/game/40022

it happened at 14:51 but was undone I I cannot see it easily now. 

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
SR5
I floated NYNHH then NYC at $71 using auto buy until floated. Next turn I merged the companies. Turn after that my go was skipped and I had bought a NYC for $67. (Auto buy was still enabled) 

I also bought an "unmerged" share in a merged company when I was messing around in hotseat earlier and I could not get rid of it but I just deleted that instance. In that case I did it manually but was not paying attention to what I did 

**Which Browser / Platform?**
PC using Brave

No screenshots were taken.

**Comment by crericha** [comment]
@magnusrk-ch is this still possible? If so, would you mind looking into it?

**Comment by crericha** [comment]
What I think is going on is the original two companies weren't closed using @game.close_corporation, so while the corporation itself was marked as closed, it was still hanging around.

I pushed a candidate fix that deletes the shares and the corporations from the game. I didn't have an easy way to test it though. Could someone try it out in a day or two when its deployed?

@magnusrk-ch, while I hopefully fixed the issue, perhaps auto buy should check to see if the corporation is closed before buying the share?

**Comment by crericha** [comment]
The potential fix is deployed. Can someone volunteer to verify? The linked game is archived, so I couldn't do so easily.

**Comment by magnusrk-ch** [comment]
Auto buy looks for shares that are buyable and in circulation, so in this case I would say the bug is on the game for not cleaning up after mergers.

More generally, though, Auto buy would benefit from a more robust API for checking what is allowed to buy.

**Comment by crericha** [comment]
Closing as this should be fixed. Reopen is still a problem.
