### ISSUE TITLE
Game showing incorrect players turn game 41002

### ISSUE THREAD

**Issue by corian09** [tobymao/18xx#5338]
[Game 41002[(https://18xx.games/game/41002) 18 Irish rails it is showing my turn”corian09” and not the correct persons turn. I have tried sending the @ it’s your turn to that other player but no luck.

**Comment by dfannius** [comment]
Where is it saying that it's your turn? On the card for the game on the front page of the site?

**Comment by corian09** [comment]
It’s showing it’s the other players turn in the game but yes on the card and on my feed it’s showing that it’s my turn

**Comment by benjaminxscott** [comment]
Looks like that particular game is archived, fwiw - not sure if this issue can be triaged
