### ISSUE TITLE
[18CZ] Turn off auto-pass for SR1 if enabled in Draft 1

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#5344]
The auto-pass description says: "Auto actions will disable themselves if: [...] It is the end of the round in which they are turned on.". This does not seem to apply for the Draft round in 18CZ, see game https://18xx.games/game/41947. hurrlipurr turned on auto-pass in Draft 1, which then also auto-passed their first turn in SR 1 (the game is back in Draft 1 in order to allow them to turn off auto-pass and be the first to float a Small Company in the Stock Round).

Edit: If the game hasn't progressed by the time a mod looks at it, could you be so kind and turn off hurrlipurr's auto-pass?

**Comment by Zwergenpunk** [comment]
Sorry, but we cannot without alot of work undo player actions.

@jenf any idea why this is happening?

**Comment by roseundy** [comment]
See how I handle this in 1862. Basically, you could clear auto-actions at the end of the draft round.
