### ISSUE TITLE
Add support for "points up" maps / hex reference variation

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#535]
I believe this change is coming/needed for 1846 anyway.

The current games have hexes with flat sides on the top and bottom. Some games, like 1846, have vertical (flat) sides. There is a need when setting up configuration files to be able to specify whether the orientation is flat/horizontal ("h") or vertical ("v").

Additionally, while we're making this more complicated, there is variation among games about whether the hex references are letters across the top or along the side (vice versa for the numbers).

I think it would be best to support all four configurations (v/letters), (v/numbers), (h/letters), h(numbers), but I also think it would be okay to be opinionated about it and just say letters are always across the top (most common), and the game references need to be changed to fit when adding new games.

**Comment by tobymao** [comment]
i’ve decided to be opinionated here and go with consistent and simple layouts
