### ISSUE TITLE
Harzbahn 41841

### ISSUE THREAD

**Issue by Daniel18xx** [tobymao/18xx#5353]
Harzbahn Beta - game 41841- there's some technical issues.  I passed at 80, and Espee auto-overbid to 90 (instantaneous to my bid).  it showed this on my phone.  But when I went to the desktop, it didn't reflect Espee's autooverbid.  I went back to the desktop and submitted a bid of 90 (because Espee's bid didn't exist), and it took my bid, still not showing Espee's action.  (ie. refreshed on two different devices and it showed two different game states, Physicssquirrel suggests a java script cashing issue.

**Comment by roseundy** [comment]
@jenf can you also take a look?

**Comment by roseundy** [comment]
Also, I'm not sure how well auto actions for the auctions are supported.

**Comment by physic** [comment]
Daniel and I did some more digging here. Still confused about the Auto action (maybe the other player took their move very very fast)

But the reason the gamestate was showing differently was that Daniel was not logged in on the phone, (but it does that thing where it makes the move and shows a "try cloning the game" popup saying your move wasn't saved.)

FWIW that feature can be confusing (def confounded Daniel), and I would consider showing the "try cloning" dialogue still but just not letting the move go through locally. That way when someone dismisses the dialog, they don't do a double take and think the move went through.
