### ISSUE TITLE
18Ireland: can repropose a failed merger (game 39990)

### ISSUE THREAD

**Issue by Tom-Walker-Big-Health** [tobymao/18xx#5357]
At this point: https://18xx.games/game/39990?action=507

I was able to propose a merger for EBSR and WKR although this merger had been rejected this MR.

Once a merger has failed in a given MR, IIRC it can't be reproposed.

**Comment by jenf** [comment]
If you actually propose it, it won't allow you.
`[17:10]neutronc (GMT +1) already proposed the same exact merger of EBSR,WKR. This is against the rules, clearing proposal.`
(It's done this way to avoid the complexity of the 3 way mergers)
