### ISSUE TITLE
[18GA] Open City Space Images Not Loading with Simple logos

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5359]
https://18xx.games/game/36506?action=636

The image file used to created the Open Cities in 18GA appears to have gone missing:

![Open Cities](https://user-images.githubusercontent.com/75334833/118526505-eb940d00-b705-11eb-984a-5382cf7e388f.png)

**Comment by Maxwell-Frank** [comment]
After further research, these "Open City" spaces only do not load when Simple Logos are turned on.

**Comment by perwestling** [comment]
@Maxwell-Frank I do not seem to be able to recreate this problem. Maybe it has been fixed?
