### ISSUE TITLE
[18Ireland] 3H' should be tradeable for Diesels

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#5360]
Is it possible to get a discount for trading a 3H' in the first Diesel of the game (like trading a 4T into a Diesel in 1830).

If yes, maybe it should be mentioned in the Upgrade Discount table in the Info tab (yeah, I must admit that it's full with discount information of 8H and 10H trade-in's)

At the moment it reads, if it's only possible to trade-in an 8H or a 10H to a Diesel train.

**Comment by perwestling** [comment]
[https://boardgamegeek.com/thread/2660873/train-trade](BGG forum discussion)

Information could possibly also be added on the wiki page.
