### ISSUE TITLE
[1862] Clarify Availability of Companies

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5368]
It would be great if the map somehow indicated which companies were currently available to start (as opposed to those coming out in later phases).

**Comment by joeyd4329** [comment]
Also train permits attached to each company conveyed on the map as well would be really nice.

**Comment by roseundy** [comment]
I'm still struggling to find a relatively easy way to do both of these things. There are 20 companies - each with distinct colors - so creating 3 versions of each logo is not appealing.

**Comment by Maxwell-Frank** [comment]
Can you add colored rings around the tokens to display the permits without interferring with the "show player colors" feature? I think it's most important to display the permits before the companies start.  Obviously, it's always important to know what permits a company has, but I definitely care more when I'm looking at which companies to float than when companies are in operation. 

Maybe something like changing the size of the tokens to display whether they are currently available or not would help.  It wouldn't be granular enough to display which phase they will be available in, but it might at least resolve the binary _available or not available_ issue.

**Comment by roseundy** [comment]
I've got some ideas I'm working on. It's unlikely that I'll be able to show phase availability in addition to everything else - just available now or not.

**Comment by otdewiljes** [comment]
> 
> 
> I'm still struggling to find a relatively easy way to do both of these things. There are 20 companies - each with distinct colors - so creating 3 versions of each logo is not appealing.

I would suggest something like this (except not ugly; this was whipped up in a couple of minutes to make our game semi-playable):
![image](https://user-images.githubusercontent.com/4226724/118728880-29438380-b835-11eb-93c8-3c112290d872.png)

The hex colours indicate the type of company (red for Express, purple for Freight, light blue for Local, for obvious reasons). The white dots indicate the phase in which they become available; letters might be better.
I suppose this could also be achieved by adding tokens of a dummy company (or 3*3 dummy companies: blue A, red A, purple A, red B, etc).

**Comment by roseundy** [comment]
I'm going with this. We don't need to clutter the map any more than it already is.

![markers](https://user-images.githubusercontent.com/8494213/118737338-e4eac000-b801-11eb-9701-3b4f088b17cb.png)

**Comment by ChrisTheCat** [comment]
This is what I just did before I came here to find this thread. I personally find the diamond/hex/circle not distinct enough to identify freight vs local vs express. Perhaps you could make the diamond/hex/circle symbols larger?

<img width="785" alt="Screen Shot 2021-05-18 at 4 45 59 PM" src="https://user-images.githubusercontent.com/8732435/118737732-53c41b00-b7fa-11eb-85d2-32798d13690a.png">

**Comment by roseundy** [comment]
Sorry, the markers on the map are already taking up too much real estate. I know it looks OK on an empty map, all these symbols have to compete for space with city slots and track.

**Comment by roseundy** [comment]
This was implemented in PR #5394.

From my pre-GMT copy of 1862: circles - express, diamonds - local, hexagons - freight. There are already way too many colors related to icons, so I'm keeping it simple: white - available, black - not available.
