### ISSUE TITLE
[1862] Merger of Charted and Non-Chartered Company does not preserve Treasury Shares

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5369]
https://18xx.games/game/42309?action=133

When a chartered and non-chartered company merge, the company should discard 1/2 of it's shares (and undergo the option process as necessary). The current implementation seems to discard all shares to the market.

**Comment by roseundy** [comment]
Code is not trading FDR treasury shares for ESR shares (which are in market) correctly.
