### ISSUE TITLE
[1862] Unable to Run Train After Merge

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5371]
https://18xx.games/game/42309?action=461

The ECR merged and is not given an option to run its Freight train.

**Comment by Maxwell-Frank** [comment]
Note: I tried this again later in the game, and I still didn't get the train. I think there is an issue with merged companies acquiring the trains from the other company when you merge at the beginning of a turn.  End of turn merges seem to work properly.

**Comment by roseundy** [comment]
I need to clear the "operated" flag on the trains that come from the non-survivor. This happens at the beginning of the OR turn for each company, but the non-survivor never got to that point and the flags will be wrong if it operated on the previous OR.
