### ISSUE TITLE
Displayed order of shareholders should match presidency transfer

### ISSUE THREAD

**Issue by kaelistus** [tobymao/18xx#5374]
I want the displayed order of shareholders on the corporation card to match the order in which presidency would transfer? (and I think that when there’s a tie in number of shares, this order is usually priority order?)

When it is not, although the rules are followed, I find the display confusing. For example:

If I see a company box that looks like this:
A: 5
B: 2
C: 2
I expect that B and C are ordered by who gets the presidency next. Meaning if A sells 4-5 shares, B gets presidency. In this game, C got the presidency. Note that this is correct. C Should have gotten the presidency, but I would have expected the order to display like this:
A: 5
C: 2
B: 2
instead.

See https://18xx.games/game/40790 as a situation where cwmassey sold 5 shares of GNRI and made kaelistus president. Display order was confusing and I didn't expect that.

**Comment by roseundy** [comment]
So basically: sorted by number of shares, with ties broken by distance from priority deal.
