### ISSUE TITLE
1822 - Minors 21 and 22 can illegal tile lay thru  the Pontypool 2 tile terminus

### ISSUE THREAD

**Issue by xasil** [tobymao/18xx#5375]
Minor 21 is able to lay track northward thru Pontypool. Laid tile on H29. Seems like Minor 20 is able to also lay illegally  thru 21's spot towards Fishgard, giving the green tiles dialog out of phase.

https://cdn.discordapp.com/attachments/607753162710843392/844055538576130068/unknown.png

**Comment by magnusfalt** [comment]
Can you please suply a link to the game where you manged to do this.

**Comment by xasil** [comment]
https://18xx.games/hotseat/hs_zhuoydar_1622753560

M21 laid tile on G34 in or1.1,which seems to violate Rule 9.1.2 treating the twin cities as termini[for running trains]. This was in a 1822MRS hotseat game.

**Comment by fanman80** [comment]
This looks related to bug 5680 - [1822] Unable to run a 4T route through MT&P when there are tokens on both sides #5680 and bug 6271 - 1822 (MRS) Game seems to allow building track through Wales off map grey areas. #6271.
