### ISSUE TITLE
Stock price incorrectly updated twice after payout in 1889 game

### ISSUE THREAD

**Issue by BenKenobi** [tobymao/18xx#538]
Hi,

the bug manifested itself in the following 1889 game: https://18xx.games/game/697

As you can see from the log, during the Operating Round 5.1 the Iyo Railway corporation paid out a dividend and then its stock price was updated twice: the first time it was correctly raised from Y100 to Y110, but at the same time the game also stated that the corporation "did not run" and the stock price was changed back to Y100 again.

Here the relevant messages from the log:

-- Operating Round 5.1 --
[...]
IR lays tile #23 with rotation 0 on F5
IR runs a 3 train for ¥90 (F1, E2, C4)
IR runs a 4 train for ¥130 (B7, F9, F3, E2)
IR pays out ¥220 = ¥22 x 10 shares
Nick receives ¥22 = ¥22 x 1 shares
BenKenobi83 receives ¥88 = ¥22 x 4 shares
IR receives ¥110 = ¥22 x 5 shares
IR's share price changes from ¥100 to ¥110
IR does not run
IR's share price changes from ¥110 to ¥100
IR skips buying trains
IR skips buying companies

**Comment by tobymao** [comment]
this is a pinned version so probably not relevant anymore
