### ISSUE TITLE
1862 bug- when forced train buy because all trains rusted, eventually gives 2 options that both do nothing

### ISSUE THREAD

**Issue by shawnus79** [tobymao/18xx#5382]
https://18xx.games/game/42411

happened with N&E got trains rusted
[02:01]-- Event: 3E, 3F trains rust ( N&E x1, E&H x1, ECR x1, NGC x1) --

[02:16]Shawnus operates N&E 

(We undid and did a merge instead, just to keep it going)

Chrome Version 90.0.4430.212 (Official Build) (64-bit)
Windows 10

**Comment by roseundy** [comment]
OK, what I see is a bug on refinancing (which is basically a bug in the merger code).
