### ISSUE TITLE
[18Ireland] Merger results badly described

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5386]
See https://18xx.games/game/39941?action=321

> [16:11]KevinR casts 1 votes against merger (For: 4, Against: 6)
[16:11]Votes are tied and proposal is rejected

Issue is in `def check_result` at 
https://github.com/tobymao/18xx/blob/9b98d06b8ab9a7e6b850a2e8e706e41c3c1383e1/lib/engine/game/g_18_ireland/step/merger_common.rb#L19

`@round.votes_needed` seems to be set to half+1 since ties go against the proposal, but this means that the test for a clear against victory is `>=` not just `>`.

**Comment by jenf** [comment]
fixed
