### ISSUE TITLE
[1862] 1F Trains Issue

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#5388]
https://18xx.games/game/42441?action=173

The FDR should essentially have a 3F train and be able to run from port to N hex with two intervening next
 with three 1F trains right? Since all freight trains are to be considered one long chain?

**Comment by Maxwell-Frank** [comment]
Each 1F needs to be a valid run, so you need a token in Ipswich to make that happen.

**Comment by joeyd4329** [comment]
I still wasn't able to run from Port to Ipswich with the two intervening hexes after I placed token. The small town shouldn't make a problem I would think because it only cares about hexes, starting and ending in offboard/city.

**Comment by roseundy** [comment]
Routes can never begin or end at towns. There is no way to connect Felixstowe to Ipswich with a pair of 1F trains, since each train needs to run a valid route - even if the chain of 1F's looks good.

**Comment by joeyd4329** [comment]
I don't see anywhere in the rules where it states that. Per the rules "Freight trains ignore small stations" ... "If a Company Runs multiple freight trains, these must connect with each other end-to-end, and once score the end points of the combine trains plus the bonus for intervening hexes" .. Also gives an example of a F2 and F3 running as a F5 train, and then says next "Similarly two F1 Trains and a F3 train would act the same as a F5 train".

**Comment by roseundy** [comment]
7.8 Running trains

* Train routes must begin and end in large stations or off-board areas
