### ISSUE TITLE
[1862] newly merged company can't run existing trains if the surviving company was initially trainless. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5392]
https://18xx.games/game/42447

When merging two companies that have not yet operated this OR, if one has a train and the other is trainless, the game doesn't allow you to run trains if you choose the initially trainless company as the surviving one. If the company that had a train is the surviving train, you are permitted to run them.

**Comment by roseundy** [comment]
Once again foiled by that fact that the originator is not necessarily the survivor.
