### ISSUE TITLE
[1862] unable to lay tile on connected hex

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5396]
https://18xx.games/game/42447?action=641

Issue is occurring on all tested browsers.

ESR is unable to lay a tile on C10 despite being directly connected to it. What's also weird is after ESR laid a tile on G12, C10 became available as a second tile lay.

**Comment by roseundy** [comment]
The ESR token adjacent to C10 was acquired from the non-survivor during the previous merge. I have forgotten to clear the graph on merges, since it represents a token placement.
