### ISSUE TITLE
18Ireland: Initial auction does not automatically skip player lacking money during auction

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5407]
Game link: https://18xx.games/game/42524?action=7

Player has £5 remaining, but is still asked to raise their bid. 

Preferred functionality would be to autopass in auction if there is no legal bid. 

Now this might be a general "bug" and not affecting just 18Ireland.
And the bug is very minor as the players can wait for the pass, or automode it.

**Comment by jenf** [comment]
It's a general bug, the code is identical. I'm gonna mark as won't fix.
