### ISSUE TITLE
Buying a second share of B & O 

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#541]
~~If you buy the private that gives you a share of B & O, should you be able to get the President's share by buying an additional single share?~~  Per rule citation below, this is not permitted.

I had enough money to buy one share of B & O at the par value I set, but not to buy two.  However, I already had one share from the private.  I got a message about not being able to buy the share.

Suggest clarifying the situation by saying (in this case) "You do not have enough money to buy the President Certificate"

**Comment by dfannius** [comment]
> If you buy the private that gives you a share of B & O, should you be able to get the President's share by buying an additional single share?

No. Section 10.4 of the rules (emphasis mine):

> To buy a single share of stock, the player whose turn it is transfers one 10% certificate from the initial offering or the bank pool into their own holdings. T**he president’s certificate of the public company must already be owned by a player.**

The rules about exchanging the president's certificate when the presidency changes are independent from this.

**Comment by scottredracecar** [comment]
You can't buy a single share. How would you know how much to pay for it? A par hasn't been set yet. Par is set only upon the purchase of a president's certificate.

**Comment by gchambers419** [comment]
@scottredracecar - the app prompts for a par value.  (Can't remember if it does so before offering the action buttons.)

@dfannius - OK, adjusting bug report appropriately

**Comment by tobymao** [comment]
seems like there is no bug then

**Comment by gchambers419** [comment]
@tobymao - I advocate in the adjusted issue text to clarify that you're trying to buy the president cert and don't have enough money, but I'm not sure that's worth worrying about.
