### ISSUE TITLE
18Ireland: cert limit shouldn't change on bankruptcy

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#5411]
https://18xx.games/game/39604?action=826

The rules don't mention anything about the cert limit changing when a player goes bankruptcy, but apparently the implementation changes it as if the number of players has decreased.

**Comment by perwestling** [comment]
You are probably right, but to be sure I [asked about it on BGG](https://boardgamegeek.com/thread/2662840/article/37751423#37751423)
