### ISSUE TITLE
18MS - Private Erroneously Allows Teleport 

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#5414]
https://18xx.games/game/42545?action=128

MMR allows me to teleport during my token lay, whereas it should only allow otherwise legal tokens to be cheaper

**Comment by Akado05** [comment]
When using the Meridian and Memphis Railway private, the GMO company was allowed to teleport into the far Northeast, completely circumventing the defensive chasm and token blockade set up to discourage such actions.

Please, do not allow this intrusion to happen.  Token wars are important.
