### ISSUE TITLE
18Ireland Game Broken

### ISSUE THREAD

**Issue by garretwehrman** [tobymao/18xx#5417]
GameError: Blocking step Sell then Buy Shares cannot process action
Broken action: { "type": "buy_shares", "entity": 316, "entity_type": "player", "created_at": 1621470181, "shares": [ "MGWR_8" ], "percent": 10 }

https://18xx.games/game/39604?action=845

**Comment by jenf** [comment]
Linked to the cert limit change.

18Ireland needs an archive sweep run

**Comment by jenf** [comment]
archive done
