### ISSUE TITLE
[1862] George Hudson Manoeuvre Must Add Multiples of $10

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5418]
https://18xx.games/game/42836?action=219

When performing the George Hudson Manoeuvre, companies must add cash in multiples of $10 (rule 7.8.6)

**Comment by roseundy** [comment]
Well, I missed that rule.

**Comment by roseundy** [comment]
There was a second bug lurking there as well. When doing the GHM, the price went up correctly, but the revenue being paid out on shares was not increased.

**Comment by roseundy** [comment]
Unfortunately, the fix for may kill any game that used the Hudson Manoeuvre.
