### ISSUE TITLE
18Ireland- can't bid on minor after selling another share

### ISSUE THREAD

**Issue by BGarmon80** [tobymao/18xx#5424]
https://18xx.games/game/42546

Cannot sell a share (in this case DKR) then bid on next available minor (in this case EBSR).

**Comment by Maxwell-Frank** [comment]
That's a rule (5.2). Either sell shares and buy a share _or_ start a new company.

**Comment by BGarmon80** [comment]
Well that's embarrassing. My apologies!

**Comment by jenf** [comment]
Correct behavior
