### ISSUE TITLE
1862: Rules unclear as to how to count "crow flies" bonuses with offboards

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#5429]
![image](https://user-images.githubusercontent.com/64785010/119221277-da287780-baee-11eb-9daa-d1c25c6480b1.png)

The run gave 80 + 30 + 80. Should the game count the one hex in between port Wells-Next-the-sea?

![image](https://user-images.githubusercontent.com/64785010/119221367-4c995780-baef-11eb-8d77-f9f89c5aced5.png)

Looking at this image, the "as crow flies" starts from the entry hex, not directly through London.

It does say "offboard locations with multiple entry". Does that not work with ports? Honestly you could interpret the rule in either way.

**Comment by Azuureth** [comment]
![image](https://user-images.githubusercontent.com/64785010/119221622-74d58600-baf0-11eb-8a9b-ae5b934456cf.png)

If you look at this picture, "as the crow flies" there is only 1 hex, but the game tells you get 2 hexes into the bonus

**Comment by Azuureth** [comment]
https://boardgamegeek.com/thread/2663571/need-official-freight-route-ruling
This post seems to tackle the same issue. 

https://boardgamegeek.com/thread/966793/article/12089785#12089785
And there was link where Mike Hutton commented on the case

**Comment by roseundy** [comment]
I am well aware of this issue and recently changed the behavior to what you are seeing. I was the one who posted this question on BGG.

I don't find Mike Hutton's responses up to this point unequivocal in any way. Until Mike responds to my question I'm am not going to change this again.

**Comment by roseundy** [comment]
As far as your third example goes, it's still not clear to me since Mike may be suggesting a different tile was laid on Wells that would allow the NW connection. Unfortunately that example wasn't in my copy of the rules.

**Comment by roseundy** [comment]
For reference this is what Mike agreed was correct:
"For off-board locations, the count of intervening hexes is made to the hex connected to the entry point used by the train. When choosing the route for the train, you may choose any point of entry that the train may reach (e.g. there is no obligation to choose the entry point that is closest to the other end of the route)."

Which of course contradicts the GMT rules example.

**Comment by Azuureth** [comment]
I would argue that since this is verified by the author
"For off-board locations, the count of intervening hexes is made to the hex connected to the entry point used by the train."

Each entry hex itself is intervening hex. Then there is no contradiction in the rules. The offboard location is not a hex per se, but just that, off board.

**Comment by roseundy** [comment]
Sorry I disagree.

The "hex connected to the entry point used by the train" **is** the offboard hex.

**Comment by Azuureth** [comment]
Sorry I disagree.

The way I interpret the rules they fit with given examples, yours do not.

the London route with current implementation also gives only 2 intervening hexes, tested in hotseat.

**Comment by roseundy** [comment]
True, but it's trivial to get the larger bonus to London by changing the route. The code change to automatically see if a better legal route exists is substantially larger than what I've done so far.

**Comment by philcampeau** [comment]
The rules example provides in the original report 100% confirms that it should be two hexes, not one. 

If we’re going to assume that Mike may have meant something that isn’t what is shown in the picture, the entire rulebook is up for debate.

**Comment by roseundy** [comment]
Mike has spoken. This will be fixed.
