### ISSUE TITLE
[1862] Harwich tile wrong #797

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#5438]
[1862] Harwich tile wrong #797

the spoke for brown Harwich is on the wrong side, it should be a righty.

![0590F96A-D1CB-43EF-9470-DD4792854059](https://user-images.githubusercontent.com/73144084/119235877-8de73280-bb02-11eb-834b-cf3358278759.png)

![47A44BD0-C6E0-4128-AFFC-86887F6C1D23](https://user-images.githubusercontent.com/73144084/119235900-a9ead400-bb02-11eb-8324-724856a3bc1a.png)

**Comment by roseundy** [comment]
Well, poop.

**Comment by KevinR1000** [comment]
See https://github.com/tobymao/18xx/pull/5436
