### ISSUE TITLE
1822 Major MR not given option to buy minor

### ISSUE THREAD

**Issue by xasil** [tobymao/18xx#5444]
https://18xx.games/game/41663

MR not given option to buy in a minor in OR4.2, even tho MR and minors connected have operated.

**Comment by KevinR1000** [comment]
Player's minors each have share value of £110.
MR has £60 in treasury, along with shares at £70.
MR would need **_£80_** and two shares to buy either of player's minors.
    (2x £70 + £80 = 2x £110)
So step skipped.

**Comment by perwestling** [comment]
Seems correct
