### ISSUE TITLE
[18Zoo] GameError: G7 is not upgradeable to X8

### ISSUE THREAD

**Issue by Andrewey** [tobymao/18xx#5448]
https://18xx.games/game/42877?action=64

GameError: G7 is not upgradeable to X8
Broken action: { "type": "lay_tile", "entity": "ANCIENT_MAPS", "entity_type": "company", "id": 65, "created_at": 1621640947, "hex": "G7", "tile": "X8-2", "rotation": 2 }

**Comment by carlorusso** [comment]
Today went online the bug fix related to "when both base 2 and base 3 are selected, only base 3 is used"; so now the map is not valid anymore, sorry.
you can see here: https://18xx.games/game/42877?action=44 ; the action executed cannot be done anymore

**Comment by carlorusso** [comment]
So the game should be closed and restarted

**Comment by carlorusso** [comment]
@jenf I just updated the pr where I fixed this bug: https://github.com/tobymao/18xx/pull/5423
can you archive this game?
