### ISSUE TITLE
1862 Refinancing bug: refinance not available when shares in treasury.

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#5449]
**What's your Game ID?**

https://18xx.games/game/43189?action=158

**How to Reproduce the Bug?**

A company has the option to *choose* between refinancing and selling treasury stock when it is unable to afford a train.  This appears to be implemented incorrectly: The FDR is not given the option to refinance, and is only prompted to sell treasury shares.  Checking the implementation checklist, this appears to be deliberate but incorrect rules implementation.  The correct implementation would expose both share sales and refinancing to the user when funds were short for a new train.

**Comment by roseundy** [comment]
Interesting. The first edition rules are different.

**Comment by roseundy** [comment]
After re-reading the first edition rules, I see that it can be interpreted either way. Since Mike didn't list this in the GMT rules as a change from the first edition, this is indeed a bug.

**Comment by TheExcalabur** [comment]
Yeah, there's communications from Mike pre-GMT edition that it's intended that it's a choice.  Sorry :(

**Comment by roseundy** [comment]
I have found a way to implement this without breaking any games.
