### ISSUE TITLE
[1862] Wrong stock value

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#5453]
495 should be 475

**Comment by roseundy** [comment]
Not on my copy.

**Comment by roseundy** [comment]
The next lower value is 460 and the next higher is 530. Giving a spacing of 35 and 35. If it was 475 it would have a spacing of 15 and 65.

**Comment by roseundy** [comment]
Actually, the problem is that 460 was left out. Crap. I need a proof-reader.

**Comment by daniel-sousa-me** [comment]
I was already half asleep when I wrote the issue lol
I noticed the weird jump when playing and then when I looked at the image,

>  I need a proof-reader
I know the feeling xD
1870 also had a bunch of these mistakes
