### ISSUE TITLE
[18Ireland] DCR private should mention connectivity requirements

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5456]
In a game of 18Ireland the SLNCR bought in DCR private after having run the trains.
DCR appear as an ability.
When clicking on it it highlights hex H4, but when clicking on H4 no tiles are given as an option to lay. 
From reading the description it seems SLNCR should be able to build in that hex.

https://18xx.games/game/42524?action=282
![image](https://user-images.githubusercontent.com/2631151/119310779-8b0a5000-bc70-11eb-8ea5-6a8300e4b03a.png)

**Comment by Maxwell-Frank** [comment]
@perwestling It looks like you're not connected to the hex.

https://boardgamegeek.com/thread/2534083/article/36197771#36197771

**Comment by jenf** [comment]
From the full rulebook ' subject to normal track laying rules'

**Comment by perwestling** [comment]
Agreed - the rules was quite specific, so updating the text is good.
