### ISSUE TITLE
[1862] Can't upgrade tile for Felixstowe when starting new company

### ISSUE THREAD

**Issue by cutebeast** [tobymao/18xx#5459]
Game ID: https://18xx.games/game/43284

1862: Phase B - Operating Round 3.1 (of 2)

new company FDR unable to upgrade the tile to place a token.

**Comment by roseundy** [comment]
This got broken when the new "semi-restrictive" track laying rules were added.

**Comment by roseundy** [comment]
My regression didn't catch this because we don't check track restrictions when replaying actions.
