### ISSUE TITLE
1882 Special Rules Summary

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#546]
I went through the 1882 rules and took notes on special rules that I think may need to be coded.
Latest rules: https://docs.google.com/document/d/1ERTlNSDpvj4Wd5Pbt21_j46hcH7xtS0_gOBGooBwIXs/edit

**Items in bold may be better to wait for the robust 1846 solution before implementing.**

- [x] Switch order of axis (A-Z should be vertical)

(Things marked (alpha) can probably wait until after the alpha release)
**Auction**
- [x] (alpha) The first available company reduces by $5, not just the first.

**P2 Saskatchewan Central Company**
- [x] P2 can be exchanged in the stock round as a buy action to close it and open the SCR corporation. To enact the exchange:

- - [x] the president discards P2 from the game, selects a par for SC, pays for one share, receives the presidency of the SCR
- - [x] chooses any non-reserved city or neutral token space
- - [x] alpha: ensure you can choose neutral or non-reserved city in a tile with both
- - [x] adds an extra train of the current available new train from the bank is a 3/4/5/6. 

- [x] P2 stays open until Phase 6 unlike the others that close on Phase 5.
- [x] Until P2 is exchanged SCR cannot be opened

**P4 Trestle Bridge Company**
- [x] P4 comes with a random 10% share of HBR/CPR/CNR/QLL/GTP (similar to Cornelius Vanderbilt)
- [x] P4 pays revenue each time a bridge (river hexsides preprinted on the map) is crossed, $10 to its owner.

**River Hexsides**
- [x] There are river crossing hexsides. No cost to lay up to the hexside, but pay to bridge it (make a connection across it). **(this function should come with 1846)**

**NWR Hexes** (several hexes in the northwest are labelled on the map "NWR" (north west rebellion), **(likely implement these as "sticky" icons, as in the steamboat from 1846)**
- [x] Place the "NWR Card" under the first [3/4/5/6] train (select 3/4/5/6 randomly) at game setup
It's probably best implementing this as an event. However it should also be included in the 'Info' page as well as put into the log.
- [x] If you lay in a NWR hex, you get $20 for each lay (must pay any extra costs before getting the $20). **(possibly this can be a negative payment, the opposite of tile action payment in 1846)**
- [x] When the NWR card is revealed, remove all yellow tiles in hexes marked NWR from the board (back to the tile stock).
- [x] (alpha) NWR is implemented as a phase change, this should be as the card after the n-1 train (SC can cause this to be different)

**Display Issues**
- [x] We will need to find a way to display river hexside costs on map (tricky since it needs to be visible on both sides of hexside, perhaps just display small numbers along both hexsides. **(handle this in the same way as 1846)**
- [x] We will probably want to display NWR hexes on the tiles (perhaps as an overlay if this is feasible?). **(likely implement these as icons, as in the steamboat from 1846)**

**Company/SR Miscellany**

- [x] Game is sell-buy-sell
- [x] Implement brown zone (also for 1836Jr)

**Canadian National Railway Corporation/Neutral tokens**

We need to add the concept of neutral tokens which are “blank” tokens that hold the city open (trains can pass through as if it were an untokened city). This is a new 18xx concept AFAIK, but a good one and probably likely to be reused.

- [x] Each company has one neutral token (except not CPR and CN) that can be placed as the company's token placement.
- [x] Placing these are always free and have no association to the company that laid it once it is laid. Placing is instead of a normal token.
- [x] Neutral tokens do not block train runs
- [x] CN may not be parred until there is a neutral token on the board. If there are no neutral token on the board when it operates (such as by SC starting there and discarding it, it operates as a suitcase until someone plays a neutral and it can run from there).
- [x] CN does not have board tokens, it runs neutral tokens.
- [x] It is allowed for a company to place a neutral station marker in a city where that company already has a station.
- [x] There may only be one neutral station marker in a hex

**OR Miscellany**
- [x] Token laid on first operating except CN and Saskatchewan
- [x] May lay one tile for free and may lay one extra yellow tile for $20. **(possible tie in for tile payments in 1846?)**
- [x] There is a fishing hex that counts for free onto a route.
- [x] (alpha) When determining whether a company has a legal route for train ownership purposes, the company president can choose whether to count the fishing exit or not.
- [x] QLL is kind of like Erie in 1830. Selects a home when it forms. Must leave a space open for it.
- [x] (alpha) Trains that companies discard for any reason are removed from the game, not placed in the market.
- [x] (alpha) A route gets a bonus $100 for running [A9 or B2] to L2. **(probably can already implement this as using the new group function on tiles)**
- [x] Emergency money raising is the same as 18Chesepeake
- [x] Track laying is permissive.

**Game End**
- [x] (alpha) Game ends if a company reaches the top right market space. If in OR, finish the OR, if due to all sold at the end of an SR, the game ends immediately.
- [x] Bank break, handled as usual, complete the set.

**Config file**
- [x] CPR is the 20% (B&O-type company with P5)
- [x] Train limit is 3 on Phase 5
- [x] There are orange and brown spaces on the stock chart (1830 chart)
- [x] CNR doesn't have a home station

**Comment by scottredracecar** [comment]
A little more info about the blue fishing hex. It is allowed to add this as a stop for free. I.e. a 2T can run two other cities and then also add the village and count the revenue, but not count against the train. Or if the company doesn't even have two revenue centers, it can run a route from the city to the fishing hex legally.

**Comment by TheExcalabur** [comment]
One corner case to make sure of: AIUI if p2 is exchanged the new train goes on *top* of the pile, potentially moving the NWR trigger to the second train purchased of a type.

**Comment by jenf** [comment]
I'll try and pick up the Neutral token laying this week

**Comment by jenf** [comment]
Moving status into https://github.com/tobymao/18xx/projects/1 as it provides more scope
