### ISSUE TITLE
[1889] Home stations of all freshly floated companies get placed at start of subsequent OR

### ISSUE THREAD

**Issue by dmitryleskov** [tobymao/18xx#5460]
In 1889, the home station of a company gets placed when that company first operates. The current implementation places it at the very start of the OR in which the company _will_ have first operated.

See for instance:

https://18xx.games/game/38855?action=48 (UR and TR place home tokens)
https://18xx.games/game/38855?action=258 (KO, KU, AR, and SR all place home tokens at once)

**Comment by michaeljb** [comment]
> 7. Home Token
> Each company has a free home station token that it must place on its starting city at the beginning of its first operating round, whether or not a a tile has been placed there.

\- https://secure.deepthoughtgames.com/games/1889/Rules.pdf, page 8

The site interprets "the beginning of its first operating round" to mean the beginning of the OR, rather than the beginning of that company's first OR turn.

If there's a good source indicating it should be interpreted as the beginning of the company's first OR turn, we can update the site.

**Comment by dfannius** [comment]
4.1.2 says "A company that is operating may buy a private company [...] at any point during its operating round", which definitely implies that the phrase "its operating round" refers to "the time during an OR when it operates" and not "the entire OR of which its operation is a part".

That's also the most natural interpretation to me personally, not that that should carry any particular weight.

**Comment by michaeljb** [comment]
I like that reasoning @dfannius 

However, @jenf just posted this in Slack:

> The GTG draft rulebook says 'The Corporation’s ¥0 station token is placed on its reserved city spot at the start of the next Operating Round.'

So it looks like for now we'll be leaving the 1889 implementation as-is.

**Comment by michaeljb** [comment]
It's my understanding that we want to follow whatever the GTG rules end up being. If Josh changes those, or it's decided that we should use DTG's rules (with the logic from @dfannius's comment), I have no problem with the behavior changing. (Fortunately in this case, it would only open routes up, so it couldn't break any existing games)

If someone wants to make this change, it's two lines:
* delete this line - https://github.com/tobymao/18xx/blob/5b4070e52759d6a7840dda4f5c4e981c3cd6f20d/lib/engine/game/base.rb#L209
* change this value from `:operating_round` to `:operate` - https://github.com/tobymao/18xx/blob/5b4070e52759d6a7840dda4f5c4e981c3cd6f20d/lib/engine/game/g_1889/game.rb#L439
