### ISSUE TITLE
18Ireland: Can somehow select narrow gauge track options when running routes

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#5469]
Selecting I11 -> I13 -> G13 allows you to select narrow gauge which shouldn't be possible.
https://18xx.games/game/41305?action=669

**Comment by slapphappyjazz** [comment]
I've just seen something similar - there is a legal broad gauge route, so there is not effect on the game, but the route selection is showing a connection via narrow gauge.  https://18xx.games/game/45772?action=655 
![18Ireland_route_error](https://user-images.githubusercontent.com/36824573/123857783-aa089b80-d91a-11eb-8e23-43a64bbb0618.png)
