### ISSUE TITLE
1882 Map Fixes To Do

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#547]
This is a list of things that I don't know how to resolve on 1882 map.

- [x]  The yellow OO is supposed to look like an 1830 OO, but it looks like this:
![image](https://user-images.githubusercontent.com/29106780/83104338-237dec80-a07e-11ea-9e3b-03b43d29da4c.png)

- [x] The USA offboard is value 30/30 which apparently means it doesn't display the revenue (changing to 31/30 works).
![image](https://user-images.githubusercontent.com/29106780/83104403-4ad4b980-a07e-11ea-91b3-141a486175a2.png)

- [x] Hex F2 should be blue
![image](https://user-images.githubusercontent.com/29106780/83104463-6c35a580-a07e-11ea-9478-29f992c77787.png)

- [x] Label for J10 gets pushed down too far south (other long ones seem to do fine)
![image](https://user-images.githubusercontent.com/29106780/83104532-8ec7be80-a07e-11ea-835e-d24212e34296.png)

- [x] Also, we need to figure out how to label the "NWR" hexes. This is how they are labeled on the AAG map. It would be best if these labels were overlays so that they are still visible when a tile is laid there. (see here for rules: https://github.com/tobymao/18xx/issues/546)
![image](https://user-images.githubusercontent.com/29106780/83107144-52e32800-a083-11ea-858c-22a645d9b8f0.png)

- [x] J10 (Pile o'Bones) should have a label saying QLL starts there

**Comment by dfannius** [comment]
It would be nice to be able to have non-breaking spaces in names in general (if we don't already). This would handle Pile o' Bones and would also probably come in handy in future titles.

**Comment by michaeljb** [comment]
@dfannius we do have that, it's just when I was writing that bit of code, I didn't anticipate a name with so many spaces. I think it shouldn't be too hard for anyone to fix.

https://github.com/tobymao/18xx/blob/33d1461630ab7f80c56044d360a04dd5ffa6f74e/assets/app/view/part/location_name.rb#L234-L257

https://github.com/tobymao/18xx/blob/2cc779af268769960f1062611f7b5307b2aa1277/spec/assets/app/view/part/location_name_spec.rb

**Comment by kelsin** [comment]
I have the data for the NWR hexes, as soon as we know what type of element to create in the 18xx.games encoding we can add that easily.

**Comment by jenf** [comment]
The yellow OO is supposed to look like an 1830 OO, but it looks like this:

It has two Cities rendered underneath each other

**Comment by jenf** [comment]
I think we're good with the map now
