### ISSUE TITLE
1862: A company in receivership was acquired by another company not in receivership.

### ISSUE THREAD

**Issue by mtsay** [tobymao/18xx#5471]
Per 1862 rule (the one linked under info tab) under section 8.0 Receivership on page 20:

"A company in receivership cannot merge with, or be acquired by, any other company."

However, in [game 42395](http://18xx.games/game/42395), L&H was able to merge with L&D, which was in receivership at the time.

- [link to game 42395](http://18xx.games/game/42395).
- [the state immediately before the merger](https://18xx.games/game/42395?action=295). Note that L&D was in receivership since no players hold 30% of the company and the log line at 8:16 confirmed that L&D was in receivership.
- [game data](https://gist.github.com/mtsay/59793c775adf481db8f8225f30c723ba).
- [1862 implementation checklist](https://github.com/tobymao/18xx/issues/4818): no items indicate that this rule have been implemented.

**How to Reproduce the Bug?**

- create a hot seat game.
- player 1 starts 2 nearby companies, say ESR and EUR, in SR1.
- these 2 companies build tracks toward each other and link up in OR 1.1.
- player 1 sells all shares in ESR in SR2.
- in OR 2.1, when EUR operates, during the merger step, first show companies from other players and then select ESR to merge with.

**What steps cause the unexpected behavior?**

- such merger was prohibited by the cited rule. However, the observed behaviour was that the game checks for player consent and proceeds to merge these two companies once consent is confirmed.

**Comment by roseundy** [comment]
Shame on me for the bug (which I will fix). Shame on the player for clicking through the warning about merging with a company they didn't own.

**Comment by mtsay** [comment]
@roseundy No worries; we all miss a rule or two. Thanks for all the hard work you've put into implementing this game.
