### ISSUE TITLE
18Ireland - Charlesville & Limerick Junction label covers dit

### ISSUE THREAD

**Issue by jftaylor21** [tobymao/18xx#5479]
I had a difficult time trying to figure out why I couldn't select a route between Limerick and Cork for my 4H train in https://18xx.games/game/40144. Someone eventually pointed out that there is a dit hidden behind the Charlesville & Limerick Junction label.

I don't have specific advice on how to fix this, but I wonder if there is something we can do to make the dit more visible.

**Comment by michaeljb** [comment]
You can use the "Location Names" button at the bottom of the map to show/hide the "Charlesville & Limerick Junction" label. I don't know of any plans to improve the automatic rendering of the location names.
