### ISSUE TITLE
18Ireland suggestion regarding phase changes 

### ISSUE THREAD

**Issue by databoy01** [tobymao/18xx#5488]
After phases like especially phase 6 when you are able to actually start companies without bidding it would be nice to know that at the start of the SR, especially if you are the priority player….  It’s an unfair advantage for a player to not know that wasn’t an option available to them especially when it just happens and now they are effectively cut off (my two cities are now blocked from each other making a 8H useless) after playing a very competitive game waiting for this exact moment, yet not knowing that was in effect.

**Comment by jenf** [comment]
It says it in the info tab

**Comment by jenf** [comment]
'Majors can be ipoed'. Not an issue.
