### ISSUE TITLE
Illegal tile placement

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#549]
If I am not mistaken: 

In OR3.2, this was an illegal tile upgrade as it did not create a new route:
TR lays tile #19 with rotation 2 on C8

It happens pretty often with this tile that people lay it down illegally...

**Comment by jenf** [comment]
Please provide a game id, or the JSON data if a hotseat game (Tools)

**Comment by Spobster** [comment]
Good point, game 778 :)
Thanks for your endless efforts!

**Comment by tobymao** [comment]
your game is pinned that means the bug is fixed and your game was caught
