### ISSUE TITLE
Option for Custom Game Set-up in Games with Randomized Starts

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5491]
There have been many times, especially in hotseat, where I wished there was an option to start a game with a customized set-up.  This would apply to games like 46, 49, 22, etc. where the set-up is random.  Right now if you want to fiddle around with the new Boomtown private in 46, you have to keep re-creating hotseat games until you get one where it's included. 

This could also be used to create duplicate set-ups for tournaments.  It would be fun to have an 1822 tournament where multiple tables play with the same company orders.  

I assume this is a complicated change to make, but I just wanted to float the idea out there and get the discussion rolling on whether other people are interested in this feature.

**Comment by Zwergenpunk** [comment]
I was just debugging 1840 with 18 minors which are selected at random...would be easier to have an option to set the setup. 

But I think that it is too complicated to implement that, since it needs to be implemented for every game a little bit different.

**Comment by scottredracecar** [comment]
An easy half-measure for implementation would be to allow the game seed to be defined during setup. For example, in this game:
"seed": 264904779,
https://18xx.games/game/43793

If you hotseat around to get a seed that does what you want, you could use that seed indefinitely.

**Comment by Zwergenpunk** [comment]
A fixed seed could be quite intresting for the tournaments...

**Comment by tobymao** [comment]
yes, i think the fixed seed is the only reasonable way to do this

**Comment by ChrisTheCat** [comment]
Note that a seed would work for many games, but for 1846 it would mean the deck of privates was static-preset.
