### ISSUE TITLE
Missmatch front page and actual game

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5504]
The front page looks like this:
![image](https://user-images.githubusercontent.com/2631151/119977257-7dc6cb80-bfb8-11eb-9055-a3115131ab2f.png)

If I enter the game, another player is up:
![image](https://user-images.githubusercontent.com/2631151/119977494-ce3e2900-bfb8-11eb-91b7-1aa6707d994d.png)

I can see in the log that DKR's action was mastermoded. When they are the buy companies is automatically skipped.
If I clone the game, and redo until back of DKR, and do the orders in hotseat mode, I now get a question if DKR should buy a company.

So I guess that the discrepancy between front page and actual game state is caused by this difference.

Link to game: https://18xx.games/game/42524?action=522

**Comment by perwestling** [comment]
There seem to be some connection to the corporation getting too little money to buy a company (by building an extra tile). But it might be that there is something that miss to update the current player in actions, maybe?

**Comment by perwestling** [comment]
It should be noted that the game is not possible to continue as trying to make further actions are refused by the server.

**Comment by philcampeau** [comment]
No similar reports in over a year. Will close.

We can always reopen if the problem starts popping up again.
