### ISSUE TITLE
1860 - Privates can be exchanged out of turn

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#5505]
Per the rules:

Exchanges must occur during the owning player’s turn in a stock round

currently, you can click “show others” and exchange your private on someone else’s turn. This means you can exchange your private before someone buys Fishbourne even if you’re the wrong side of PD.

https://18xx.games/game/42893?action=571

**Comment by roseundy** [comment]
I swear I never saw that button when I was developing 1860.

**Comment by Blobbley** [comment]
Perhaps it’s been added by some other game and migrated into 1860?

**Comment by roseundy** [comment]
Fix is easy. I may combine the fix for this with a fix for #4999
