### ISSUE TITLE
1862- bug chartered company obligation fine

### ISSUE THREAD

**Issue by stej-hl** [tobymao/18xx#5508]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

1862 - fine for not launching a company( chartered) not possible as player. doesn't have the money.
leading to an impossibility to go forward
**What's your Game ID?**

https://18xx.games/game/42343

**How to Reproduce the Bug?**
when I click on pass , bendalf is fined for not launching his company but can't do it money wise leading to a bug.

Please include screenshots (you can drag and drop or upload them into this  #issue)
![Screenshot_20210528-071116](https://user-images.githubusercontent.com/77860308/119996949-0f681600-bf84-11eb-9eac-f4bc493ede1d.jpg)
Browser / Platform?**
phone, chrome

**Comment by stej-hl** [comment]
![Screenshot_20210528-071116](https://user-images.githubusercontent.com/77860308/119996816-f2334780-bf83-11eb-8152-b6afc5a60b2c.jpg)

**Comment by roseundy** [comment]
Wow. Three unmet obligations. When this is fixed two players will effectively be out of the game.

**Comment by stej-hl** [comment]
yeah, clearly it was a learning experience for some.

Stephane
