### ISSUE TITLE
18Chesapeake: Able to force bankruptcy when president have enough liquid shares to buy the cheapest train

### ISSUE THREAD

**Issue by alexpung** [tobymao/18xx#551]
[game.txt](https://github.com/tobymao/18xx/files/4696971/game.txt)

At id 370 I can force bankruptcy with the "Declare bankruptcy button"

This should only happen when the presedent sell every legal shares and still can't buy the cheapest train in bank or bank pool

rules:

> _If the company is still unable to buy a train after
> the president has contributed all possible funds and sold all
> shares that can be legally sold and no other company is
> willing to sell one of its trains to the company for an
> agreeable price, then the player is declared bankrupt and
> the game is immediately ended._

**Comment by jenf** [comment]
1889 rules match 18Chesepeake behavior (12.1)

(There's always a End Game button otherwise)

**Comment by jenf** [comment]
I don't think this can be implemented.

Technically a player can buy a train from another company, and we have no way of marking unwillingness for other corps to sell trains. The only way to enforce this correctly is to force the players to sell all their shares manually and then render the Declare Bankrupcy button. Which is a bit of a bad UI.

Won't fix.

**Comment by kaelistus** [comment]
I would argue that forcing players to sell their shares manually then render the declare bankruptcy is not idea, but is better than allowing players to do illegal moves. In the game, one player pressed declare bankruptcy thinking he was doomed but would not have had he realized he was breaking the rules (It changed the winner of the game)

But, could we not count all the legal shares a player can sell / liquidity, and only render the declare bankruptcy button if that isn't enough? Also, did this actually already get done in that PR that got merged 11 days ago?

**Comment by alexpung** [comment]
In http://www.rr18xx.com/ it works like this

1. Enter no train routine
2. The president have option to buy from other company or bank/bank pool
3. If company treasury < cheapest train price in bank/bank pool, also shows option to "buy with president help".
4. If "buy with president help" is chosen, 
while company treasury + president cash < cheapest train price
present options to sell stocks for minimal amount necessary.
Also calculate sell all at once value of remaining stocks and shows "declare bankruptcy" if 
company treasury + president cash + remaining sell-able shares < cheapest train price

**Comment by pstone1** [comment]
Perhaps a good UI solution would be to have a "Sell all Shares" button, and only render the Declare Bankruptcy button after all shares are sold.

**Comment by alexpung** [comment]
> Perhaps a good UI solution would be to have a "Sell all Shares" button, and only render the Declare Bankruptcy button after all shares are sold.

The "Sell all Shares" is not really necessary. Once the game know you don't have enough sellable shares you can just show the Declare Bankruptcy button.

My step 4 is just to cover the corner case that shares of the same company could be sold, one at a time, to get less money then otherwise, to engineer a bankruptcy.

**Comment by scottredracecar** [comment]
> The "Sell all Shares" is not really necessary. Once the game know you don't have enough sellable shares you can just show the Declare Bankruptcy button.

Better than that, if the system knows you don't have enough sellable shares, the game can just end automatically. This check can be done at first and then after each sale.

**Comment by pstone1** [comment]
> > The "Sell all Shares" is not really necessary. Once the game know you don't have enough sellable shares you can just show the Declare Bankruptcy button.
> 
> Better than that, if the system knows you don't have enough sellable shares, the game can just end automatically. This check can be done at first and then after each sale.

Cannot quite do that, as you always technically have the option to buy trains from other players companies. It is also just a good idea to make the game only end by a direct player input.

**Comment by scottredracecar** [comment]
Well, this assumes you are entering a forced train buy mode, which we currently don't have. In the extreme case, even if you are down to $1 in your treasury and hand combined (after all sellable shares), you can still buy over a train from another company in 18Chesapeake. 1889 is different.

So the button could be "Force Buy Train From Bank". That puts us in force buy mode and the system can determine whether the player is bankrupt or not. Really, there is not ever any need for a "Declare Bankrupt" button because the system can know at any given point whether the player is bankrupt or not at any given time.

**Comment by pstone1** [comment]
One thing that would also make things more clear would be to show all the sell share buttons below corporations even when specific companies are not selected. Right now, you have to click on each company to see which shares you can sell, which can lead to players thinking they are bankrupt when they are not. 

![image](https://user-images.githubusercontent.com/13589848/84684569-6fde7e80-aefe-11ea-955e-0c6bfcc5b35f.png)

In this example, the player can also sell a share of NW but cannot easily see that from the UI unless they click on NW. The sell shares button should appear below all corporations with valid shares to sell, regardless of which one is selected.

**Comment by ChrisTheCat** [comment]
The interface should only allow you to declare bankruptcy when you are actually bankrupt. If you really want to keep the current button, it should be renamed "I quit" and not "declare bankruptcy"

**Comment by michaeljb** [comment]
A couple 1846 examples of illegal bankruptcy - [5857.json](https://gist.github.com/michaeljb/2195748fd6df884df5f15f6d27213117) and [8795.json](https://gist.github.com/michaeljb/97136e5a2ff7a11a60ce082a097d84a1)
