### ISSUE TITLE
[1861] Game End Condition on Info Tab is Incorrect

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5528]
https://18xx.games/game/44029#info

The End Game condition on Info tab currently reads: "Finish the current OR set, then end after the next complete OR set"

The actual rule depends on when the first 8 train is bought and does not always run another full OR set.  This should be corrected so players (like me) don't think there is more game left than there is.

**Comment by ollybh** [comment]
This issue can be closed as complete. The game end description for reaching phase 8 now reads:

> If the first 8-train is purchased in the first OR of a set the game finishes at the end of the current OR set, otherwise the game ends at the end of the next OR set. In both cases the last OR set is extended to three ORs.

This was changed in pull request #8619.
