### ISSUE TITLE
1862: Hide trains you don't have permit for

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#5530]
I have seen few times a case where a player accidentally bought a wrong train type.

As people have several games going, it might be wise to hide trains you don't have permit for, in similar manner you hide trains from other players.

**Comment by ventusignis** [comment]
As long as you can force-show the other trains that'd be ok; there's a case for buying a bunch of warrantied up trains in a chartered corporation for a non-chartered friend

**Comment by roseundy** [comment]
This was addressed by #6029
