### ISSUE TITLE
[Harzbahn 1873] Diesel routes are unable to reuse each other's track.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5535]
Env: Chrome
Hotseat: https://gist.github.com/physic/c41d8454196a7d92c3e1ffb02dae55dd
See action 790.

Repro: On action 790, try to add a new Diesel route starting from Hasselfelde.

Expected: I can trace a diesel route to any token I can reach.
Observed: I am blocked in Ruebeland by another preexisting Diesel route. Since Ruebeland does not have a SHE token, the route is illegal and cannot be submitted.

Diesels are not standard trains, and they may reuse one another's track.
From the rules: "No two of the routes serviced by *standard trains* of a company may have any track in common."

**Comment by roseundy** [comment]
I asked @KlausKiermeier about this specifically, and diesels may not reuse each others' track. He has clarified this in the new edition rules:

`Nevertheless, as with the routes a standard train may run, the routes a diesel railcar services may cross each other or meet in towns or villages but are not allowed to have any track in common.`
