### ISSUE TITLE
[Harzbahn 1873] Feature Request: UX Improvement for Reassigning Switchers

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5536]
The checkboxes for reassigning switchers, and assigning mines and switchers are tiny and hard to click, and the need to check them before taking the desired action is unintuitive and takes a lot of clicks.

For Reassigning Switchers, I propose:

In the list of mines, make the whole mine clickable, instead of just a checkbox. In the CHECKED state, highlight the checked mine.
Once a second mine is CHECKED, perform the swap immediately and uncheck all mines (rather than requiring an additional click of the "Reassign Switchers" button)

Pros:
- Removes an unnecessary button.
- Instead of 3 clicks, 2 of them tiny checkboxes, there are two clicks of big friendly rectangles.

**Comment by KKiermeier** [comment]
Would be nice, indeed. In particular, being forced to "uncheck" the checkboxes after having performed a reassigning action is a bit exhausting...
