### ISSUE TITLE
[Harzbahn 1873] Feature Request: UX Improvement for parring companies

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5537]
When parring a company in Harzbahn, you have a choice of how many shares to buy (up to 40%).

The current implementation (for buying two shares) is:
Click company. (Buttons appear with possible par prices)
Click par price. (One share is purchased. Company may jump around on screen)
Click company again.
Click Buy a treasury share.

Proposed implementation:
Click company. (Buttons appear with possible par prices)
Click par price. (Individual buttons appear offering options for one or two shares, up to the number of shares the active player can afford [up to four shares for purchase options on 10-share reorganized companies])
Click number of shares. (That many shares are purchased all at once)

Pros: 
- Much less likely to accidentally forget to buy a second share, assuming that you already bought two, and then realizing your mistake on your following stock turn. (since in every other 18xx game, parring a company automatically buys two shares). 
- Fewer clicks.
- Far less cursor travel distance.
- Familiar UX like the *Sell 1, Sell 2* buttons.

Cons: None

**Comment by KKiermeier** [comment]
Good idea! Would definitely be an improvemnet.
