### ISSUE TITLE
[Harzbahn 1873] Feature Request: UX Improvement. Buying machines

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5538]
The checkboxes for reassigning switchers, and assigning mines and switchers are tiny and hard to click, and the need to check them before taking the desired action is unintuitive and takes a lot of clicks.

My proposed UX for buying machines:
Click Buy Machine button
(If the purchased machine is at least as large as the number of mines with a smaller machine, automatically assign the machine to all such mines. Otherwise, show a list of mines. Make the entire mine clickable. In the CHECKED state, highlight the mine)
Click mines to check and uncheck them. Once a number of mines is checked equal to the machine size, click *Confirm Selection*

**Comment by KKiermeier** [comment]
Also nice. Would make the buying of machines more comfortable for the user.
