### ISSUE TITLE
[Harzbahn 1873] Feature Request: UX Improvement. Buying Switchers

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5539]
The checkboxes for reassigning switchers, and assigning mines and switchers are tiny and hard to click, and the need to check them before taking the desired action is unintuitive and takes a lot of clicks.

Additionally, I have to be careful to assign switchers to a mine that doesn't already have one, or I could accidentally scrap one of my switchers.

Current UX for buying two switchers:
1. Click the buy button. (oops you didn't click a checkbox yet. try again)
2. Squint and check which mine runs the best switcher.
3. Click a little checkbox.
4. Click the buy button.
5. Squint and check which mine runs the next best switcher.
6. Unclick that checkbox.
7. Click a different checkbox.
8. Click the buy button.

My proposed UX for buying two switchers (from bank or from other corps):
1. Click the buy button.
- If the mining corp has as many switchers as it has mines, prohibit the purchase, and make me scrap a switcher first.
- Otherwise automatically assign the switcher to the first mine that doesn't have one already, in the following order: Highest value switcher connected to the National Railway, followed by highest value switcher not connected to the National Railway.
2. Click the buy button again.

Pros:
- Fewer clicks, especially when buying multiple switchers one after another
- No tiny checkboxes
- Trivial assignment calculation is done automatically 
- Impossible to accidentally scrap a switcher when buying another one.
- You can always reorganize them when you run, so there's little downside to this convenience.
 
Cons:
- One could argue that making the optimal switcher choice should be left up to the player, even though it's utterly trivial (I don't buy this argument, but one could argue)
- In the case where you actually want to scrap a switcher, being forced to do so deliberately takes one more click and some extra cursor travel.

**Comment by KKiermeier** [comment]
Would also be a nice improvement.
