### ISSUE TITLE
[Harzbahn 1873] Feature Request: Lay the concession route automatically on a corp's first turn

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5540]
A company must lay its concession route on its first turn. When I go to lay the concession route, 18xx.games seems to already know exactly which tiles to lay and in which orientation, as it gives me only one choice. It takes 3 clicks per tile, and can be fairly laborious for companies like NWE that need to lay a lot of tiles.

Please automate the tile lay step and lay the whole route without user input.

**Comment by KKiermeier** [comment]
Would be very helpful, especially for the NWE.
