### ISSUE TITLE
[Harzbahn 1873] Feature Request: Update Mine 12 private and Mine 12 independent mine with special ability text.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5541]
Neither the Yellow Mine 12 card in the initial auction nor the Red Mine 12 card in player hands gives any indication that it lets you open the HW.

In both cases, please update the description of Mine 12 to remind players that it comes with the special ability: "Reserves the right to open HW in SR1"

**Comment by KKiermeier** [comment]
Very good!
