### ISSUE TITLE
[1862] - cannot merge two companies

### ISSUE THREAD

**Issue by rbayu2** [tobymao/18xx#5545]
https://18xx.games/game/43859

![WhatsApp Image 2021-05-31 at 23 10 25](https://user-images.githubusercontent.com/85142852/120254806-db0e9580-c2b4-11eb-970c-b3ceab1adae5.jpeg)

![WhatsApp Image 2021-05-31 at 23 11 07](https://user-images.githubusercontent.com/85142852/120254816-de098600-c2b4-11eb-8d4b-18f36c46ac6f.jpeg)

It gives error message ArgumentError.

Please help and thanks.

Regards,
Ricky

**Comment by roseundy** [comment]
Code was confounded by a merger of two trainless companies.
