### ISSUE TITLE
1856: (Minor) Brown Lake tiles and brown london shouldn't share a label

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#5549]
The tile mix in 1856 includes "L" tiles (5-sided) for play next to the lakes on marked spots, and also a special brown tile for London, ON.  In the tile mix these are both labelled "L": the label on the London tile should probably be changed ("LON"?).

(I haven't tested if you can play the lake tiles in london.)

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/120325935-28d7cd80-c2b6-11eb-9fb9-41df0397affb.png)
Would differentiating them like this work?
