### ISSUE TITLE
[1822MRS] Minor 9 can't skip track

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#5554]
https://18xx.games/game/43242?action=343

Happens in cloned games too.  Minor 9 can lay a track, but if it clicks "Skip Track" nothing happens and then it can't do anything (can't then try to lay a track after the fact).

**Comment by jenf** [comment]
`Uncaught 
g
args: [g]
message: "undefined method `tokened_by?' for nil"
name: "tokened_by?"
stack: "tokened_by?: undefined method `tokened_by?' for nil\n    at g.x (https://18xx.games/assets/deps.js:4:12818)\n    at g.a (https://18xx.games/assets/deps.js:1:12421)\n    at g.Ut (https://18xx.games/assets/main.js:1:211874)\n    at ue (https://18xx.games/assets/main.js:2:254895)\n    at Object.t.yield1 (https://18xx.games/assets/deps.js:1:14043)\n    at ue (https://18xx.games/assets/deps.js:9:27604)\n    at t.yield1 (https://18xx.games/assets/deps.js:1:14043)\n    at Array._r (https://18xx.games/assets/deps.js:9:78826)\n    at Object.t.send2 (https://18xx.games/assets/deps.js:1:16269)\n    at t.send (https://18xx.games/assets/deps.js:1:16107)"
__proto__: g`

**Comment by jenf** [comment]
Looks related to if 9 doesn't have a valid route

**Comment by magnusfalt** [comment]
fixed in #6791
