### ISSUE TITLE
[1856] unable to take advantage of .5 above cert limit after formation of CGR

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5562]
https://18xx.games/game/44472

According to the rules 

> CGR Share Limits
> If more than 10 CGR shares are issued, each CGR share counts as only  a certificate. Players may then hold up to 12 CGR shares and the open market may hold up to 10 shares. **Players may hold one half certificate above the current stock limits, but players may not purchase a half share if they are currently at their limit.**

In our game, I was at 15.5/16. I purchased a share of Credit Valley Railway, and the game is now telling me that I need to sell to get back under cert limit. My reading of the rules is that this would be permitted.

**Comment by ventusignis** [comment]
Yeah that looks like a clear miss on the rules on my part

**Comment by ventusignis** [comment]
I found this on the implementation notes of rr18xx; considering it refers to a later printing of the rules I'm inclined to leave this as for now and focus on other issues

http://www.rr18xx.com/doc_rules_all.html#r_1856

> 7. You can't exceed certificate limit by 0.5 shares
In the online rules in the CGR Share Limits section (p.24) it says: "Players may hold one half certificate above the current stock limits, but players may not purchase a half share if they are currently at their limit". Thankfully this bizarre rule was excised from the more recent printed version, and the online implementation does not allow players to exceed the certificate limit by half a share.


Also rr18xx refers to 2.2d (the PDF I've found around online) as "the old version" of the rules
>  the earlier v2.2d rules.

**Comment by ventusignis** [comment]
To quote Bill Dixon
> The original 1992 rules had the half share over rule. The rule was gone by the 1994 rules

The official ruling on this is no half cert over. Once 1856 enters beta if someone wants to take ownership of this to make an optional rule to make this an option at game creation that'd go well but I think no half-certs-over will be the default rules going forward
