### ISSUE TITLE
[18Ireland] Game completely crashed after Undo

### ISSUE THREAD

**Issue by mholzma** [tobymao/18xx#5565]
This is for the following game:

https://18xx.games/game/40276

The action it told me to copy is:
https://18xx.games/game/40276?action=657

I was rolling back a turn with the Undo button right after the mholzma second company ran. Potentially to withhold instead of payout when it crashed.

Now the game is listed as archive.

**Comment by jenf** [comment]
The game had someone illegally starting a corp in a city without track which was fixed last night

**Comment by mholzma** [comment]
Does that mean there was a fix in the base code that caused the game to be in an invalid state?

**Comment by jenf** [comment]
yep

**Comment by mholzma** [comment]
Thanks, I don't think anyone did actually do that, but maybe hitting Undo caused some other action to creep in that caused that invalid state. Any way I can go look at the game to see it, even if it is no longer valid? Thanks for the help!
