### ISSUE TITLE
[18Ireland] Should skip merge proposal phase when no legal merge proposal is possible

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5566]
https://18xx.games/game/40916?action=811

In this game there are two minors that can merge.

One player suggest this merge, and it is rejected.

Then the second player gets the opportunity to suggest merge. Now there is no valid merge to suggest, as the identical merge cannot be resuggested according to the rules.

This is a very minor thing as all it does is to prolongue the asynch game a bit, and fixing it will break the games, so it might not be worth fixing.

**Comment by dfannius** [comment]
I don't think the labels "enhancement" and "minor bug" are compatible so I'm removing the latter.
