### ISSUE TITLE
[18Ireland] Info page showing 0/4 3H trains

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#5577]
https://18xx.games/game/39990?action=770 

The first 10H has just been purchased and 3H trains have been added to the list in the info page, but the page shows 0/4 remaining instead of 4/4.

As far as I can tell, the trains are actually available to purchase.

![image](https://user-images.githubusercontent.com/36824573/120543614-69356980-c3e4-11eb-9c4f-cd82396f2f69.png)

I'm using the Firefox 89 but I doubt that's relevant.

**Comment by Azuureth** [comment]
If you look at the picture, the 3H' are in the bankpool and not in the bank offerings.

**Comment by slapphappyjazz** [comment]
Why are they listed in the bank offering at all?  They aren't listed there until they appear in the bank pool.  (Which is itself a problem, because you can't see in advance what they will cost).
