### ISSUE TITLE
1861 - unable to sell stocks

### ISSUE THREAD

**Issue by WeeMadAndo** [tobymao/18xx#5578]
https://18xx.games/game/41389

Noticed that I was unable to sell a stock that I cannot identify a rules issue preventing me from selling (MK) - other stocks seem to be working as normal. Other players in the game tested and replicated issue under Master Mode and identified similar issues with some of their own holdings (SE).

**Comment by Maxwell-Frank** [comment]
You can't sell a share of a company before it has operated for the first time. MK was formed in the prior merger round and has not yet operated.

**Comment by WeeMadAndo** [comment]
There we go. No one managed to spot it. Thank you very much.

**Comment by jenf** [comment]
Not an issue.
