### ISSUE TITLE
1862: Can't chain freight chains over a town.

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#5579]
https://18xx.games/game/44624?action=207

Expectation: N&E runs 2x2F trains from London to the West connecting at Royston.
Actual: "Route cannot begin/end in a town" 

This is overall a rules clarification on if this route should work.

From section 7.8
"Train routes must begin and end in large stations or off-board
areas. They may not end in small stations, and must include at
least two large stations or one large station and one red off-board
area or port."

"Freight trains ignore small stations. In the case above, the small
station has no effect on the longer blue run.
If a company runs multiple Freight trains, these must connect with
each other end-to-end, and only score the end points of the combined trains plus the bonus for intervening hexes."

**Comment by dfannius** [comment]
Rule 7.8, first bullet:
> Train routes must begin and end in large stations or off-board areas. They may not end in small stations, and must include at least two large stations or one large station and one red off-board area or port.

The rules for Freight trains in 7.8.1 are about how they are scored. They do not change the definition of a legal route. This is not very clear from the wording and trips up a lot of people.
