### ISSUE TITLE
18Ireland: Diesel ran through token in Dundalk&Drogheda

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#5580]
Dundalk&Drogheda had token pointing left. Show last run shows that GSWR ran through the token when it should have ran through the town.

game ID 42381

https://gist.github.com/Azuureth/94dc26bf54f7e6b30efbe13be1d5f09f

![image](https://user-images.githubusercontent.com/64785010/120654896-68531500-c482-11eb-8b64-49411613b42d.png)

**Comment by ventusignis** [comment]
https://18xx.games/game/42381?action=831 for the dividend action immediately following GSWR's route step

**Comment by perwestling** [comment]
This is essentialy the same problem as #5279 so I think we can close this issue as a duplicate. OK?

**Comment by jenf** [comment]
It's covered by #5279
