### ISSUE TITLE
[18DE] half-pay per-share info is shown in dollars, and not rounded.

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5582]
![C0522198-DFEF-42E8-926D-588F2057247C](https://user-images.githubusercontent.com/26125362/120668697-b2c19b00-c45c-11eb-92a2-0ba9bea2f94c.jpeg)

image shows the issues described in title.

Game reference: https://18xx.games/game/43782?action=349

**Comment by Maxwell-Frank** [comment]
It's a 2-share company, so it shouldn't round.  The currency switch is technically the most minor of bugs, though.
