### ISSUE TITLE
[1862] Map Legend

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#5585]
A couple couple minor improvements to the map view. (not the play map but the map you see when you click on the map tab)

The map could use a simple legend reminding people what each symbol signifies, circle = X, Diamond = Y 

And could you find a way to highlight companies that can be started vs companies that cannot yet be started.

As for game play, train buying could use a warning if you are ending your purchase trains step without a train you can run,
Buying the wrong train is a big problem in 62 games and undo isn't always a satisfactory solution.

**Comment by roseundy** [comment]
I already highlight companies that can be started vs. not (white vs. black).
