### ISSUE TITLE
[1840] Initial Private Auction Not Quite Correct

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5586]
From the rules: 
`The Starting Player chooses one of the six Private Companies to be auctioned. That player may make an initial bid of at least the
company's face value or a multiple of 5 Gulden higher. Alternatively they may pass.`

This appears to mean that the starting player may pick a private company to put up for auction, but is not compelled to make the first bid. This is further supported by `If all players pass (there are no bids) during the auction of the first Private Company`.  There cannot be no bids on a company if a player is compelled to bid when they put a private up for auction.

**Comment by Zwergenpunk** [comment]
Oh yeah I did not saw the rule that when everyone passed, the price is decreased. That only makes sense if you are allowed to pasd sfter selecting

**Comment by Zwergenpunk** [comment]
I asked Lonny what the real solution is.

So it seems like choosing and bidding are the same thing. So this auction is like a 1817 selection auction but with the 1830 price reduction/payout mechanic.
