### ISSUE TITLE
[1840] Stadtbahn Tiles Must be Laid from a Stadtbahn Token

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#5587]
When laying Stadtbahn tiles, they must be laid from one of the Stadtbahn tokens. You cannot just lay Stadtbahn tiles in the middle of the route. 

https://gist.github.com/Maxwell-Frank/6a94d9af57b2ea390d6ecfc401b9374a

**Comment by Zwergenpunk** [comment]
Ah interesting. I did not find anything in the rules about that when Implementing. Now Inimmediately found the rule that explains that...
