### ISSUE TITLE
Lots of 504 Gateway Time-Outs

### ISSUE THREAD

**Issue by richardtempura** [tobymao/18xx#559]
Cannot finish game in progress. Continually getting 504's

**Comment by richardtempura** [comment]
![Uploading Screen Shot 2020-05-28 at 11.43.55 PM.png…]()

**Comment by richardtempura** [comment]
In addition, those curved brackets that keep popping up as a warning...

**Comment by tobymao** [comment]
it means i'm deploying just wait a couple seconds
