### ISSUE TITLE
[1822] Tax haven bypasses mandatory sell over certificate limit

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5594]
See https://18xx.games/game/39055?action=1190

Rule 4.4.7 requires a player above the certificate limit to sell down at first opportunity.  
> 4.4.7 A player who owns more certificates than the certificate limit allows must sell stock, if possible, to bring themselves within the limit at their first opportunity in a stock round.

18xx.games enforces this by not displaying a "Pass" button when over cert limit:
<img width="341" alt="Screen Shot 2021-06-03 at 16 52 04 " src="https://user-images.githubusercontent.com/82781561/120717233-d00e5d80-c48c-11eb-9d44-abf52c7b956e.png">

But, when Tax Haven buys a share, it automatically passes.  This means that it can pass even though the player still must sell to reach cert limit.
<img width="517" alt="Screen Shot 2021-06-03 at 16 52 24 " src="https://user-images.githubusercontent.com/82781561/120717291-e87e7800-c48c-11eb-8eaf-3ae9cd1a1932.png">

I suspect that the issue arises in `def process_choose_ability` in `g_1822/step/buy_sell_par_shares.rb`.  Presumably there should be a cert limit check before this line:
https://github.com/tobymao/18xx/blob/c09be4544602307afeda12a24010b8aa89b00ea7/lib/engine/game/g_1822/step/buy_sell_par_shares.rb#L160

**Comment by dfannius** [comment]
Unfortunately the above game is now archived, so new example would be useful.

**Comment by philcampeau** [comment]
No similar reports in quite some time. Will close.

We can always reopen if the problem starts popping up again.
