### ISSUE TITLE
Add more detail to corporations card

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#56]
Use left and right columns like in rollingstock.net

**Comment by dfannius** [comment]
I'm not sure what detail this is referring to specifically, but I think we need at least

- IPO price (there is no par-price chart, and even if there were, I think it should go here too)
- market price (even though it is already on the stock market chart)
- number of shares in the market (is this currently displayed anywhere?)

**Comment by Talbatross** [comment]
Redid the UI for corps and had Toby merge it in.  Let me know if it has everything you're thinking of.
