### ISSUE TITLE
Bug: Refresh the browser redirect me to a different game

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#560]
When in a game that I entered clicking by the home page (like https://www.18xx.games/game/1358) it is ok. But if a refresh the browser or type the same route in a browser the game looks like the initial setup.

Pictures and datasets of both results 

Correct Game:
![image](https://user-images.githubusercontent.com/4177168/83221752-0b28d300-a14d-11ea-9048-e64ca2ab3965.png)

After refreshing browser:
![image](https://user-images.githubusercontent.com/4177168/83221950-a457e980-a14d-11ea-8c5f-06f46fbdaa53.png)

**Comment by Djeefther** [comment]
**Datasets**:

**Correct game **:
https://gist.githubusercontent.com/Djeefther/f326aec4dd3bfbdebb7668d155d1541b/raw/eb31f032e6b1c6217debbe8e677685be5d312a1e/18xx-games-issue-560-datasets-correct.json


**After refreshing browser**:
https://gist.githubusercontent.com/Djeefther/f326aec4dd3bfbdebb7668d155d1541b/raw/eb31f032e6b1c6217debbe8e677685be5d312a1e/18xx-games-issue-560-datasets-after-refresh-browsing.json

**Comment by tobymao** [comment]
on it

**Comment by tobymao** [comment]
deploying a fix
