### ISSUE TITLE
[1846] automatically assign boomtown private to H12 when purchased by corp

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#5603]
When the "Boomtown" private is purchased by a corp, its bonus is not assigned to H12 (the only hex it's valid for)

The verbiage on the private says "corp **may** assign the marker", but that seems like a fairly niche case where you wouldn't want to assign the bonus, versus the average case where a player forgets to assign it

![image](https://user-images.githubusercontent.com/1711810/120867800-8c2c5e80-c547-11eb-9468-c694a9a285c8.png)

**Comment by Maxwell-Frank** [comment]
Implementing this would require a function for a player to _remove_ the marker if they do not wish to assign it, which just feels clunky.

**Comment by benjaminxscott** [comment]
Fair point

It's probably OK to leave as-is
