### ISSUE TITLE
[1840] Undo and/or Restart Last Turn  fails;  game iD 44873

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#5606]
![1840_20210605-122522_Chrome](https://user-images.githubusercontent.com/64490299/120889145-1209e180-c5fc-11eb-8eba-71b75a0fdbf9.jpg)

**Comment by bendelker** [comment]
Got the same error.

**Comment by Zwergenpunk** [comment]
@bendelker do you have a game and Action Id?

**Comment by bendelker** [comment]
Game ID:  44502
Just went to check the game, and it’s broken with this error:  https://18xx.games/game/44502?action=267
