### ISSUE TITLE
Improvement: In OR (Operation Round) allow an auto search button of the best route

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#561]
In OR (Operation Round) allow an auto search button of the best route maximizing the earnings, as the http://www.rr18xx.com/ does. 

The main reason is that at the end of the game is a tedious process routing with a diesel train. And mainly this manual process slow does the game as each player makes more counts.

Additionally, maybe the host of the game could allow or not that feature, since, some players may enjoy looks for themselves the best route, for me, it is time-consuming.

**Comment by tobymao** [comment]
this is planned in the future but will be a per game option as path finding is a part of the game and should only be allowed if the players agree

**Comment by NickHeiner** [comment]
This would be a great feature for groups that choose to use it. For my group, we consider the pathfinding to be toil, so it would be great to have the engine do it for us.

**Comment by NickHeiner** [comment]
I would consider implementing this myself. @tobymao would you accept a PR?

Does anyone know the semantics of the tile config? For example:

```rb
'58' => 'town=revenue:10;path=a:0,b:_0;path=a:_0,b:2',
```

![image](https://user-images.githubusercontent.com/829827/86027564-b8f5fe80-b9e5-11ea-87ac-861eac60fa3d.png)

And architecturally, what piece of code would you put this in?

**Comment by tobymao** [comment]
hi @NickHeiner this would be very involved and something that we'd need to discuss a lot, if you're serious about implementing this, I think we should discuss in slack. So if it is done 'correctly', I'm happy to accept it.

The configuration means that there is a town with revenue 10, a path from edge 0 to the town and a path from the town to edge 2. view/game/tile.rb has a lot of stuff in it.

**Comment by jenf** [comment]
Few notes from previous discussions:
* Implementation is client side to avoid server load (but this can be done easily enough using the ruby -> opal bridge)

**Comment by tobymao** [comment]
done
