### ISSUE TITLE
[1822+] Game broken, can't get back in

### ISSUE THREAD

**Issue by cfcurtis** [tobymao/18xx#5610]
Game ID: https://18xx.games/game/44955

`
main.js:2 Uncaught 
g {name: "first", message: "undefined method `first' for nil", args: Array(0), stack: "first: undefined method `first' for nil\n    at g.x…send2 (https://18xx.games/assets/deps.js:1:16269)"}
args: []
message: "undefined method `first' for nil"
name: "first"
stack: "first: undefined method `first' for nil\n    at g.x (https://18xx.games/assets/deps.js:4:12818)\n    at g.a (https://18xx.games/assets/deps.js:1:12421)\n    at g.oe (https://18xx.games/assets/main.js:2:259670)\n    at se (https://18xx.games/assets/main.js:2:261365)\n    at t.yield1 (https://18xx.games/assets/deps.js:1:14043)\n    at Array.ge (https://18xx.games/assets/deps.js:9:74517)\n    at Object.t.send2 (https://18xx.games/assets/deps.js:1:16269)\n    at Object.t.send (https://18xx.games/assets/deps.js:1:16107)\n    at Array.ee (https://18xx.games/assets/deps.js:1:18432)\n    at Object.t.send2 (https://18xx.games/assets/deps.js:1:16269)"
__proto__: g
`

**Comment by tobymao** [comment]
auto routing is not saving connection hexes

**Comment by cfcurtis** [comment]
Two players were able to take actions but we're back to having the same issue now.
