### ISSUE TITLE
[1861] "Show last route" option for RSR

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#5620]
In 1861, the "Show Last Route" option on the map page doesn't list the RSR.  This doesn't block play in any way but would have been nice to have during the game today, so that we could review the route that was chosen by the RSR director.

**Comment by ollybh** [comment]
This issue can be closed as complete, it was fixed by pull request #8618. The RSR can now be chosen from the route history selector underneath the map and it's last runs are shown.

**Comment by crericha** [comment]
@ollybh if you link the issue to the PR, it will automatically close
