### ISSUE TITLE
[1840] revenue for  hex I11 is zero and not 10; gameID 45017

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#5621]
![1840f 2021-06-06 195515](https://user-images.githubusercontent.com/64490299/120935161-b7f34400-c701-11eb-87fc-d9f581c8885a.jpg)
![1840g 2021-06-06 195546](https://user-images.githubusercontent.com/64490299/120935164-ba559e00-c701-11eb-97a9-3bb130aeb3f2.jpg)

**Comment by Zwergenpunk** [comment]
yeah thats the same error as the other issue.
