### ISSUE TITLE
Leave companies previous run on the map during the operating round

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#563]
It'd be useful when reviewing other players turns and when on your own to see how they ran their companies on the map.

(This needs the last route improvements i'm currently working on)

**Comment by jenf** [comment]
I'm going to expand this, outside of the corps turn you should be able to use the map to see their last route.

**Comment by PedroRCSequeira** [comment]
as a "quick look" version, I believe it could be useful to see, in the entities tab, which trans ran last time, so it would have something like: Last Run: $200 (2, 2, 3/5)

**Comment by perwestling** [comment]
A suggestion that came up in a Slack channel (dfan, I believe) was that you should be able to click on the Last run on the corporation, and this would display that run.
