### ISSUE TITLE
[18ZOO] train run should now have the $N inside the texts

### ISSUE THREAD

**Issue by carlorusso** [tobymao/18xx#5634]
18ZOO has two currencies:
$N are for only money, train revenue doesn't contain anything

![image](https://user-images.githubusercontent.com/1408567/120980125-96806f80-c776-11eb-81df-7e55ef66586c.png)
![image](https://user-images.githubusercontent.com/1408567/120980185-a8faa900-c776-11eb-97e3-e45b7bafd7da.png)

Please remove $N from the previous points

**Comment by serpentium** [comment]
To clarify, should look like
GI runs a 2S train for **50N**: L4-K9
GI pays out **50N** = 1$N per share (2$N to Player 1)
