### ISSUE TITLE
[1840] question about token placement; gameID 45348

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#5637]
Tram 5 takes a bonus action first on I15 (Margareten) (yellow tile) 
next I 15 is upgraded to green creating a new token space, but the token bonus (free) lay is not possible. The token is charged normally

![1840h 2021-06-07 140109](https://user-images.githubusercontent.com/64490299/121014818-b2960800-c79a-11eb-8322-249c8b09ebca.jpg)
![1840i 2021-06-07 140228](https://user-images.githubusercontent.com/64490299/121014830-b4f86200-c79a-11eb-9c51-14f34add88a4.jpg)
![1840j 2021-06-07 140356](https://user-images.githubusercontent.com/64490299/121014839-b75abc00-c79a-11eb-8789-36947853a64b.jpg)
![1840k 2021-06-07 140741](https://user-images.githubusercontent.com/64490299/121014850-b9247f80-c79a-11eb-9b08-629c6968f489.jpg)
![1840l 2021-06-07 140958](https://user-images.githubusercontent.com/64490299/121014866-bb86d980-c79a-11eb-849f-e223ca9a964a.jpg)

**Comment by Zwergenpunk** [comment]
I'm not sure if thats the expected way.

The first two rules just says that you can place an additional token in one round.
In the 3rd rule for me it is pretty clear, that you lay a orange framed tile and then immediately perform the action.

**Comment by Zwergenpunk** [comment]
@ViennaTramways what do you say is correct?

**Comment by ViennaTramways** [comment]
Zwergenpunk, you are correct. If you place an orange framed tile you have to perform the action immediately before you do something else.
