### ISSUE TITLE
[1856] Extra Pass required even though no action is possible

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5639]
During operation, when you take a loan early the game still requires you to pass last, even though you are not allowed to take more.
And that even if you do not have funds to repay any loan.

So the game should skip pass in these situations.

https://18xx.games/game/44377?action=133

![image](https://user-images.githubusercontent.com/2631151/121035025-cbf47f80-c7ad-11eb-898d-4e80e476d180.png)

**Comment by perwestling** [comment]
If I pass in the above situation, the next step is to potentially buy and companies, but in this very case there is no action to do but Pass.

**Comment by ventusignis** [comment]
I know what I can do to fix this but it would archive every game of 1856; is it possible to migrate alpha games or would this have to wait until 1856 is beta?

**Comment by ventusignis** [comment]
The fix is to change line 16 in `loan.rb` as such:
`            actions << 'pass' if blocks? && !actions.empty?`
The complication is this breaks nearly every 1856 spec game which would need to be adjusted
