### ISSUE TITLE
[1840] last "Stadtbahn" tile lay is not possible, gameID 45364

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#5642]
SJE has enough money and tile "L2" is avail, but F12 is no option

![1840m 2021-06-07 184824](https://user-images.githubusercontent.com/64490299/121059035-48dd2480-c7c1-11eb-8136-07744b66e0ad.jpg)

**Comment by Zwergenpunk** [comment]
..argh i know why

Stupid bahnhof on f12.

Thanks for finding it.
