### ISSUE TITLE
[1846] BoomTown Token never removed

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#5647]
During 1846, x number of privates are removed from the start of play. When O&I and other similar privates are removed, the text on their tiles is removed, but when Boomtown is removed, it’s symbol remains on the board. This may also be the case for Steamboat.

Would it be possible for these to be removed in games where they are not present in order to make this clearer?

Thank you!

**Comment by benjaminxscott** [comment]
I have a PR for this
