### ISSUE TITLE
[1840] - Multiple Bug Report

### ISSUE THREAD

**Issue by tommccorry** [tobymao/18xx#5654]
**What's your Game ID?** : https://18xx.games/game/45518

1) Typo - The logo for the SJE is incorrect. It has the same logo as the DTK&C. The SJE logo looks like a gear with the letters SJE superimposed.

2) Typo - On the info page, in the game phases section, the column header should be "LRs" not "ORs"

3) Major Bug - When the SJE pays out 400 at action 603 (https://18xx.games/game/45518?action=603), it does not advance three steps on the stock market. If I pay out 390 it will advance by 2, if I pay out 500 it will advance by 3, but any value in the 400s result in no stock movement.

4) Major Bug - At the end of stock Round 2 (https://18xx.games/game/45518?action=481) when priority for next Stock Round is set, it appears to have ordered the players from least to most instead of most to least. **tmccorry** had 0 money at the end of the SR yet had priority over other players with money.

5) Suggestion - The UX for the train assignment caused errors several times with different players who forgot to hit reassign before hitting the button to continue. Recommend just having players assign all trains each CR (i.e. set them all to unassigned when entering the screen) and just have a single button to complete the assignment and go on to the next player.

Regards,

Tom McCorry

**Comment by dfannius** [comment]
Thanks for the comprehensive report. In the future, please create one issue per bug; this makes it easier for us to track the state of individual bugs.

**Comment by tommccorry** [comment]
WILCO.

Thanks for the great system!

Regards,

--------------------------------------------
Tom McCorry

**Comment by Zwergenpunk** [comment]
The fixes are on the way.
I'm not sure what the best solution is for the reassigning. Resetting every CR is not ideal as well =(

For now I added some auto handling for reassigning, that when you have 1 train and 1 corp the train is assigned automatically.
