### ISSUE TITLE
[1822] Minor 18 does not give access to exchange token

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5655]
https://18xx.games/game/41566?action=1364

LYR owns P18-C&HPR (MAJOR, Phase 5. Station Marker Swap. Allows the owning company to move a token from the exchange token area of its charter to the available token area, or vice versa. This company closes when its power is exercised.)
It has £150 and an available exchange token. 

But it has no ways of moving the token to use it. Instead it automatically skips place token.

**Comment by magnusfalt** [comment]
I had to make a comprimise here, you have to use the P18 before the place token step. So if you undo to the place tile step, you can use P18 here and then it will stop at the place token step.

**Comment by perwestling** [comment]
I managed to do just that, so I thought I had skipped on creating this issue.

Maybe we can just add a note under "Implementation notes" or "Known Problems", and close the issue?
https://github.com/tobymao/18xx/wiki/1822

**Comment by perwestling** [comment]
So it was.
