### ISSUE TITLE
Need to change email

### ISSUE THREAD

**Issue by DashingAbout** [tobymao/18xx#566]
OK I am stupid but I entered gibberish as my email address. I can't change it in my profile, what can I do?

**Comment by jenf** [comment]
Probably best if we implement it

**Comment by DashingAbout** [comment]
You can never have enough features to cover every form of stupid!

**Comment by tobymao** [comment]
dashingabout, can you contact me on twitter or some other DM so i can change this for you?

**Comment by DashingAbout** [comment]
Blimey I’ve not used my Twitter account since I set it up! Also I don’t know what handle to use for you?

Other means:

WhatsApp:          +44 (0)7809716899
Discord:                Dashing#0634
Skype:                  ddashing

Now we are getting into more obscure territory:

Facebook messenger:    Darryl Ashing (there’s not many of us in the world)

And err I think that’s it.

Darryl
