### ISSUE TITLE
[1862] Unable to Cross buy trains with changed warranty

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#5667]
[Hotseat Gist](https://gist.github.com/pstone1/ce789b6f4f18f9c43caad8c7e6a8bbbc)

Attempting to cross buy a 1F creates the error "Not a buyable train" While it is a train of the wrong permit type, that should not prevent the sale of the train, in this case so that WStI will have enough cash to buy a train by the time its 1Fs are rusted next round.

Rules reference: " Companies may buy trains of ANY type, but may only gain revenue for those trains of the type they have permits for. Trains come in bands A-H. All the trains in a band must be bought from the bank before trains in the following band are available. Every train in the same band has the same cost. Trains may be bought from the bank or from another company for current train cost. Note that this cost is a set price, and is not chosen by players. The initial cost is printed on the train card. To start with, trains are bought from the bank and from other companies at this price. However, after the sale of any trains in a later band, a train from an earlier band is bought and sold at half face price"

**Comment by roseundy** [comment]
It wasn't related to not having a permit at all. It was because the code couldn't handle buying a train whose name doesn't match the original name for the train. This happens when warranties are used or added.
