### ISSUE TITLE
[1862] Unable to Upgrade to Tile #20 over a straight dit

### ISSUE THREAD

**Issue by Talbatross** [tobymao/18xx#5668]
https://18xx.games/game/45673?action=370

ENR is unable to lay a double straight on C12 even though it should be able to.
ENR should also be able to lay a double straight on E10 but the tile cannot be rotated to fit.

**Comment by roseundy** [comment]
Well that's embarrassing. I had to create "hidden" tiles to deal with the way dit/plain track is upgraded in 1862. I missed one.
