### ISSUE TITLE
18Chesapeake: In hot seat games, PRR always gets "randomly" assigned to CV

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#567]
In every hot seat game of 18Chesapeake I've created, the PRR is always assigned to Cornelius Vanderbilt. I think that randomization is not working correctly for hot seat games.

**Comment by michaeljb** [comment]
Same thing for me.

**Comment by wcraigtrader** [comment]
Also, the players all start the auction in the same order (1, 2, 3, 4, 5, ...) instead of being randomized. 

I believe that the RNG seed is not being initialized, but I haven't found the right spot in the code for it.

**Comment by tobymao** [comment]
most likely the game id is not passed or parsed correctly. the seed is the game id which would be the time stamp of the game

the player order never changes, you input it in, that’s the order
