### ISSUE TITLE
1840: Bonus action allowed line to place token for free

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#5670]
The way I read the rules, even the bonus action token is not free.

Due to missclick or bug, I failed to transfer tram to the line, so it had no money.

Game Id: 44365

Edit: I said "free" when I should have said "not free"

![image](https://user-images.githubusercontent.com/64785010/121526690-4c132300-ca02-11eb-81fc-f79095d8ca84.png)

**Comment by Zwergenpunk** [comment]
I have no idea where you see a problem?

**Comment by Azuureth** [comment]
Could be I'm reading the rules wrong.
![image](https://user-images.githubusercontent.com/64785010/121666895-6c9ab600-cab2-11eb-89f0-2306cbc1aed2.png)

![image](https://user-images.githubusercontent.com/64785010/121667073-9653dd00-cab2-11eb-9db1-b243dbbba14f.png)

The line did not have money for the token, which should have costed it 20 gulden. I think the price should still be payed even if the token is from bonus action?

**Comment by Zwergenpunk** [comment]
the bonus token is free
https://boardgamegeek.com/thread/2601107/bonus-action-questions-1-yellow-orange-edge-allowe
