### ISSUE TITLE
[18Mag] Yellow O-O tiles have town name over price

### ISSUE THREAD

**Issue by lkingsford** [tobymao/18xx#5673]
https://gist.github.com/benjaminxscott/b3df76e12b53b97059ccbf58dae94e4a

> tile #L32 with rotation 2 on I14 (Újvidék & Pétrovárad)

> tile #L32 with rotation 5 on D19 (Szatmárnémeti & Nyíregyháza)

Screenshots are attached 

![2021-06-11 10_57_54-18Mag - 44397 - 18xx Games - Vivaldi](https://user-images.githubusercontent.com/478240/121615314-ed05ea80-caa3-11eb-976f-a7db91eeec25.png)
![2021-06-11 10_57_44-18Mag - 44397 - 18xx Games - Vivaldi](https://user-images.githubusercontent.com/478240/121615315-ee371780-caa3-11eb-9ab0-2f805598e3a9.png)

The O-O yellow tiles in 18Mag have the town names over the top of the tile upgrade cost, meaning you can't see the cost. Example tiles are D19 and I14.

**Which Browser / Platform?**
- Browser Version
Observed on Vivaldi 3.0.1874.38 (Chromium based) on Windows and Android 11 Mobile Browser

**Comment by philcampeau** [comment]
From what I can see, this issue no longer occurs, probably thanks to the commits by Michael above. Closing for now, can always reopen if problem persists.
