### ISSUE TITLE
1846 Autorouting and Mail contract

### ISSUE THREAD

**Issue by santouryuu3** [tobymao/18xx#5675]
1846 Hotseat game- Autoroute leads to Mail contract being applied to two separate trains Copied Game data below. Haven't submitted Hotseat bug before so apologies if I did this wrong

https://gist.github.com/Zwergenpunk/81b0702a1a9f77fed87116985c71262a

**Comment by daniel-sousa-me** [comment]
Same thing happened here: https://18xx.games/game/45077?action=185

**Comment by tobymao** [comment]
fixed by #46c1e33
