### ISSUE TITLE
1888 - Unable to use Terracotta Private

### ISSUE THREAD

**Issue by jehayward** [tobymao/18xx#5677]
Game ID: 45683

We're in phase 4. I'm attempting to use the terracotta army private company to lay the upgraded revenue red tile in Xi'an, but it is not allowing me to. I've tried laying it prior to my regular lay and after.

**Comment by perwestling** [comment]
https://18xx.games/game/45683?action=236

I cloned the game at this point in time, clicked on the ability, and clicked on Xi'an - but nothing happens.

![image](https://user-images.githubusercontent.com/2631151/121702770-76ccac80-cad2-11eb-9f09-68cbe14e2be8.png)

**Comment by roseundy** [comment]
Yep, I horked up Terracotta Army after I fixed the Ferry power.
