### ISSUE TITLE
[1888] Show destination information on charter

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5678]
Wiki page (https://github.com/tobymao/18xx/wiki/1888) states: "If a train’s route contains both home and destination the bonus shown on the company sheet is added to the income."

This information is not shown in-game in the 18xx.games version. I would suggest add this - compare e.g. 18AL on one way of doing it.
(In essence: having a corporation specific ability that show the destination, and the bonus.)

**Comment by roseundy** [comment]
Well, I went to some length to show it on the map. I can add it to the corporate status text.

**Comment by perwestling** [comment]
It is nice to have it on the map, of course, but I found it a bit hard to connect the colors on the map with the actual corporation. Adding e.g. a base attribute with description text, possibly a longer version explaining destinations, might improve usability.
