### ISSUE TITLE
[1822] Unable to run a 4T route through MT&P when there are tokens on both sides

### ISSUE THREAD

**Issue by mtsay** [tobymao/18xx#5680]
This issue was discovered in a hot seat game. When SWR has stations in both D35 and F33 and SWR tries to run a 4T via D35-F35-E34-F33, the route was deemed invalid with the error message "Route is not connected".

Upon further investigation, I learned that:
- when user clicks stations in the order D35-F35-E34-F33 (from west to east)
  - the route in the interface shows F33-E34-F35-D35 (in reverse order of stations being clicked)
  - and the route is deemed invalid despite being a valid route from a human point of view.
- when user clicks stations in the reverse order (from east to west)
  - the route in the interface shows D35-F35-E34-F33
  - and the route is deemed valid.

[game data](https://gist.github.com/mtsay/0a52bb67f1574659365930be0226f628)

Route info: 
<img width="305" alt="Screen Shot 2021-06-11 at 10 05 03 AM" src="https://user-images.githubusercontent.com/72957217/121725381-0d32ab00-ca9e-11eb-87c4-473fa602c6da.png">

Actual route on the map:
<img width="653" alt="Screen Shot 2021-06-11 at 10 20 36 AM" src="https://user-images.githubusercontent.com/72957217/121725923-baa5be80-ca9e-11eb-9dea-c7b9bbf73a4f.png">

**Comment by fanman80** [comment]
This looks related to bug 5375 - 1822 - Minors 21 and 22 can illegal tile lay thru the Pontypool 2 tile terminus #5375 and bug 6271 - 1822 (MRS) Game seems to allow building track through Wales off map grey areas. #6271.

**Comment by dfannius** [comment]
This seems to be fixed now, perhaps by #6963, which rewrote the code for checking valid routes.
