### ISSUE TITLE
1862: Priority Deal seems to change during parliament round

### ISSUE THREAD

**Issue by Jonsered777** [tobymao/18xx#5684]
When somebody floats a company during parliament round priority deal seems to change to the person after. However after parliament round it corrects itself back to the player who had priority before parliament. So it works like it should work but it is kinda confusing during parliament round.

**Comment by roseundy** [comment]
Yes, Parliamentary Rounds and Stock Rounds both start with the player with priority deal, which is set at the end of the Stock Round.  However, during the Parliamentary Rounds, after a player wins an auction, the next player is the one to the left of the auction winner.

Is this what you are seeing? If not please specify a game id where you saw the problem.
