### ISSUE TITLE
1889 Illegal D Train Purchase

### ISSUE THREAD

**Issue by ezRAez** [tobymao/18xx#569]
Game ID: 1296

OR: 9.1

TR had $349 in its treasury, as well as 4 train.  TR's president used their own personal cash, along with the $349 from the company's treasury to purchase a D train for TR.

Since the company still had a train, I don't think it should be allowed to purchase a D train using the president's money.

Fwiw, we undid that illegal purchase and continued from there.

**Comment by tobymao** [comment]
this isn't possible anymore
