### ISSUE TITLE
1817: Indicate acquisition if loan is taken

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#5693]
Hello.

In 1817 the dividends payout screen clearly indicates acquisition state depending if the dividends are paid/half/withheld.

Being a noob, I accidentally took loan that put my company in acquistion.

Could similar info be added to the "take loan" button to remind players that they can't get more money without problems. Since often times the game is played on a mobile and it's easy to lose the big picture.

**Comment by Azuureth** [comment]
Or even some kind of confirmation step:

"Company has moved into acquisition/liquidation: Confirm"

**Comment by jenf** [comment]
It should be showing a warning.

**Comment by jenf** [comment]
Could you provide a game id?

**Comment by Azuureth** [comment]
I actually undo'ed the situation, so I cannot give you an ID.

So, the situation was this. My company was at $45 dollars. Neither withhold or loan alone would put me in acquisition. Seeing a new train I both witheld (down to $40) and took a loan (down to acquisition).

Later I realized this mistake.

**Comment by davidlaughlin** [comment]
I think we just had this occur in this game: https://18xx.games/game/68977

The owner of the B&A took a couple of loans that put it into the Acquisitions section of the market but there doesn't appear to be a warning on the button.  Easy to miss if you aren't looking at the stock market.

Before (no warning message on the Take Loan button):
![image](https://user-images.githubusercontent.com/6003837/153058915-db6354fb-7ce9-4108-80e5-079fba7363dc.png)

After:
![image](https://user-images.githubusercontent.com/6003837/153058948-a7d87bc0-5ab0-4767-9212-6349b15d2baf.png)
