### ISSUE TITLE
[1846] [autoroute] autoroute uses illegal train with MS buying

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#5694]
https://18xx.games/game/45197?action=107

In this game MS has run, GT buys it, and acquires the 2 train. Since that train has already run this OR, it cannot be used again. 

Pressing autoroute does enable the train, allowing for an illegal higher revenue.

**Comment by benjaminxscott** [comment]
repro https://gist.github.com/benjaminxscott/77a101aff47c79f0a0fc3489fa14077d
