### ISSUE TITLE
Bold text used in log when buying private from Bank

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5698]
When a player buys a private that has an owner the log text appear as Bold

Example from 1893:

**-- Player 1 buys Anleihen der Stadt Köln 8 from The Bank for 100M**

This is a bit cluttering the log when it is a common action (like in 1893...)

I believe the intention of making it bold was to make it easier for players to see if someone bought one of their privates.
In this case buying from The Bank is common (in some titles).

I suggest changing so that boldning (in lib/engine/step/buy_sell_par_shares.rb) is not done when owner is the Bank.

The alternative is to remove the boldning, as this seems to be the only place in the code that does this (when buying companies).

**Comment by erperreault** [comment]
Is this still active? I just bought a private from the bank in 1860 and it's not bolded in the game log.
![Screenshot from 2021-08-06 10-15-42](https://user-images.githubusercontent.com/69309175/128523892-79340f70-21d8-41c4-aa09-de164ab76e8a.png)

**Comment by roseundy** [comment]
Pretty sure that's a different section of code.

**Comment by marndt93** [comment]
Has there been any thought about allowing the user to set custom colors for different log events in the user profile settings?  This could make it easier to differentiate between game logs and player messages.

**Comment by tobymao** [comment]
game logs and player messages can be filtered now as toggles.

log colors i think is just too much, there are already a wealth of configurations in profile for colors
