### ISSUE TITLE
1862: Cities are counted multiple times for local subsidy

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#5703]
See the screenshot: The two local trains touch nine hexes, so the subsidy should be 90, but it is 100, because Ely is counted twice. The game is 46076.

The rules state: "Each hex is only worth 10 in subsidy to the company regardless of the number of times it is visited by Local trains."

![image](https://user-images.githubusercontent.com/1355029/121823146-8fd88780-cca3-11eb-82de-fdc36d82a936.png)

**Comment by roseundy** [comment]
Odd, I have code that specifically accounts for this. Not seeing where the bug is yet.

**Comment by roseundy** [comment]
Had a "return" in a loop where I should have had a "next"
