### ISSUE TITLE
Game 45972 18Ireland - Game won't progress to next player

### ISSUE THREAD

**Issue by Corvus-IRL** [tobymao/18xx#5705]
https://18xx.games/game/45972

The game resets back to the active player (Eireabu) when the pass action is taken during the merge selection which doesn't allow the game to progress. Also the active player on the 18xx main page is shown incorrectly as Corvus_IRL.

Problem is present on Android/Chrome.

**Comment by jenf** [comment]
Confirmed, fails on server mode, but works in hotseat

**Comment by jenf** [comment]
Server thinks it's OR, hotseat think's its MR

**Comment by jenf** [comment]
Ha, SLNCR has £22, City of Dublin Steam is £45.
Server is rounding up, client is rounding down
