### ISSUE TITLE
[1862] Freight train revenue Lowestoft off-board

### ISSUE THREAD

**Issue by H1llsman** [tobymao/18xx#5718]
From this point: https://18xx.games/game/46384?action=145
If Lowestoft get upgraded to a K pointing south and a 2F train runs:
Beccles (G8) - Lowestoft (H7) - Offboard Port (phase C, so middle values)

From my understanding of the rules the expected revenue of the route should all be 20 + 90  + 30 = 140
This works as intended for the NE and SE port:
![1862 freight issue2](https://user-images.githubusercontent.com/85963784/122129369-48cecb80-ce36-11eb-92b4-5f14cc2fa0b1.PNG)

But if I trace the route to the southern port the pay out is only be 20 + 90:
![1862 freight issue](https://user-images.githubusercontent.com/85963784/122129380-4e2c1600-ce36-11eb-8c7f-833646f29666.PNG)
This seems incorrect: The crow would have to fly from the Off-board sea zone, into Lowestoft (south) to Beccles. This behavior is working correctly for the NE and SE entry points, just not the South entrance.

In this case it would be trivial to reroute the path but if Lowestoft (H7) somehow only had track pointing to the southern port: this would result in an incorrect revenue.

**Comment by roseundy** [comment]
Dup of #5429
