### ISSUE TITLE
18CO - Grand Junction and Grand River ability not fully realized

### ISSUE THREAD

**Issue by deaconbluz** [tobymao/18xx#5719]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. According to rules description, yellow towns that are highlighted do not represent full availability of upgrade options

Game ID 46185

**Comment by ryandriskel** [comment]
Hi Deacon. I realize it has been 6 weeks but I'd love to resolve this bug. However, there isn't much detail to go off here. I'm not sure I can help without knowing what you were seeing vs what you were expecting to see.
