### ISSUE TITLE
1846 New core features 

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#572]
Best guess, first pass:

- [x] Variable number of initial trains based on player count
- [x] Two-sided trains (choose side at purchase, can't change later)
- [x] N/M trains - (e.g. 3/5 - move up to five but only count three of them.)
- [x] Random starting privates and corps
- [x] Variable # of starting privates and corps based on player count
- [x] Independent Railroads (bought & sold like privates, but also run like corporations)
- [x] IRRs come with a train, free starting token.
- [x] Pseudo-draft for privates rather than auction.
- [x] Wounded (obsolete) trains get one final chance to run
- [x] Independent Railroads come with debt that must be paid off when buying them.
- [x] Corps float when President's share is purchased
 
- [x] Construction costs for connecting to track across certain hexsides.
- [x] Up to two yellow placements or one yellow placement and on upgrade per OR turns
- [x] Corp can issue or redeem stock during OR turns, with limits.
- [x] Emergency money raising is 18Chesaepeake style
- [ ] Emergency money raising can issue stock
- [x] Tokens that give extra revenue when paced by a city to companies that own a certain private

- [x] Game plays between 3 and 5 - System currently hard-codes lower limit at 2 and top count at 6.

From Joshua Starr:

- [x] $20 cost for any tile placement
- [x] IC tile placement costs waived for specific hexes
- [x] Reserved token locations for PRR and B&O
- [x] E-W route bonus
- [x] Special operating order in OR1A
- [x] 2x and 3x stock bumps depending on stock price
- [x] Corps with 0 stock price are closed
- [x] Shares issued at next lower stock price, shares redeemed at next higher stock price

**Comment by joshyboy20k** [comment]
- [ ] $20 cost for any tile placement

- [ ] IC tile placement costs waived for specific hexes

- [ ] Reserved token locations for PRR and B&O

**Comment by gchambers419** [comment]
- [ ] Independent Railroads come with debt that must be paid off when buying them.

**Comment by joshyboy20k** [comment]
- [ ] E-W route bonus

- [ ] Special operating order in OR1A

- [ ] 2x and 3x stock bumps depending on stock price

- [ ] Corps with 0 stock price are closed

- [ ] Shares issued at next lower stock price, shares redeemed at next higher stock price

**Comment by scottredracecar** [comment]
This is a community-generated list of special rules for 1846 along with considerations about how to make them more robust to make it easy to add them for new game implementation.
https://docs.google.com/document/d/1K_dZYJ-OqFjFQLdOABZE1zRbcMvJ3NNPfwhqw48nM4M/edit

**Comment by gchambers419** [comment]
At least one of the edit points for the player count https://github.com/gchambers419/18xx/blob/9f836b6a563107f0dc7e5369b648b78e1b2115fe/assets/app/view/create_game.rb#L86

**Comment by michaeljb** [comment]
Special private icons like port/steamboat and meatpacking will need to be done. I'm starting on ports in #647

**Comment by benjaminxscott** [comment]
Note that Erie also has a reserved token in D20, with the same rules as PRR and BO's reserved tokens

**Comment by Spobster** [comment]
In addition to Erie, PRR and BO, also IC has a reserved spot. Erie and IC do only partially have the same rules as PRR and BO:
**Same:** The Erie, Baltimore & Ohio, Illinois Central, and Pennsylvania have, until phase IV,
reserved city spaces in Erie, Centralia, Cincinnati, and Ft. Wayne, respectively, in
which they may place a token for $40. 
**Different:** The Baltimore & Ohio and Pennsylvania may each place a token in a
city, Cincinnati and Ft. Wayne, respectively, that it does not connect to. These tokens
have two prices listed. Use the lower price, $40, if the corporation does connect to
that city space when placing the token; use the higher price, $100 or $60, otherwise.

**Comment by tobymao** [comment]
closing for now

**Comment by gchambers419** [comment]
Agreed.  Anything still missing can get a fresh bug.
