### ISSUE TITLE
Improved description / instructions for Webhooks

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5720]
After reading this wiki page: https://github.com/tobymao/18xx/wiki/Notifications

I have these questions:

1. What does a Webhook actually do?
2. How do you know what to put in the Webhook URL field when you choose custom?
3.  If you choose "18xx Slack" instead of custom, what does that mean?
4. Once you enter everything correctly on the form, how and where will you receive notifications?

I'd update the wiki, but I actually have no idea what the answers are to my questions.

**Comment by tobymao** [comment]
1. a webhook is a mechanism where 18xx.games server hits another server to notify it of something, in this case when you make a move 18xx server will tell discord or slack that something happened, which would then notify you
2. google for slack / discord webhook or ask your discord admin to provide you a webhook
3. 18xx slack is the 18xx slack, in #18xxgamesnotifications channel
4. if you use 18xx slack, it will be in that channel, if you do custom, it will be in the channel that you set it up for
