### ISSUE TITLE
[1893] Parameter mismatch when buying last minor

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5728]
![image](https://user-images.githubusercontent.com/2631151/122258641-8df40b80-ced1-11eb-8391-cd5815a729e9.png)
https://18xx.games/game/46441?action=14

Attempt to buy Minor 5 result in the error text appearing in the GUI.

**Comment by perwestling** [comment]
Correction did not solve this issue. New attempt to fix this is needed.

**Comment by tobymao** [comment]
did you not test it?

**Comment by perwestling** [comment]
@tobymao I only tested it in hotseat at first. The train count correction (from a couple of days ago) broke my complete reference game so do not have any regression tests for 1893.
