### ISSUE TITLE
1862: obligation fines and priority deal

### ISSUE THREAD

**Issue by pedropp001** [tobymao/18xx#5730]
Hello there. We have just noticed that maybe there is an issue/bug with priority deal and obligation fines in 1862. If there is something I am missing on rules, I'm sorry in advance and I'd appreciate if somebody could help anyway.

When somebody can't fulfill their obligations, this must be solved through selling assets etc. to pay a fine. After player sells the necessary amount and pays what is due, does the priority deal change hands? In my understanding, this wouldn't be the case. However, in this game, priority deal went from me (first to pass) to the player who paid obligation debt itself on SR4:

https://18xx.games/game/45523

In this other game (SR3), priority deal went to the player following the one who had to take on an obligation fine:

https://18xx.games/game/43749?action=291

It doesn't seem consistent to me, and it seems that both are not in accordance to the rules, that states clearly: "The Priority Deal token is then given to the player who started the round of consecutive passes" (6.6). As I understand it, there is no passing after player pays the obligation fine.

Is that correct?

Thanks in advance!

**Comment by roseundy** [comment]
Yep, I can believe there is an issue with this in my implementation. Unfortunately, because missed obligations are fairly rare events, it hasn't been as well tested as other parts of the game.
