### ISSUE TITLE
Add a Bond concept, somewhere between Company and Corporation/Shares

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5733]
Thought some more on Bonds. 

Having as a concept of its own, on par with Corporation/Share, sounds like a good idea. 

Think having it appear as Bond charters in the Entity view, showing the number of bonds (not percent) each player own, how many is left (in market), might be good.

In Stock Market it can be used to connect Buy and Sell buttons, and you could possible sell a bundle, or buy one, in your round. Bond wont be a share holder, I presume. 

Bonds can pay out dividend at start of each OR. They can have a set price and a value. (Might want to have them separate if they buy and sell price were to differ.)

On the player charter Bonds can be presented as a Bond name plus count (not percent).
Bonds can have any number.
Do not think they need any Limit.

I think this would work for Bank of England, although I have not read those rules.

- [ ] Implement Bond class
- [ ] Implement Issuer class (e.g. 1893 AdSK)
- [ ] Created at start
- [ ] Bonds can be issued by Corporation (e.g. 1849 Advanced Game)
- [ ] Should have a price, and a value
- [ ] Should be possible to Sell during stock market - should be regarded as a Sell action
- [ ] Should be possible to sell bundles during stock market
- [ ] Should be possible to Buy during stock market - should be regarded as a Buy action
- [ ] Not possible to Buy in the same SR that you sold them
- [ ] Should support auto buy, compare #5795 
- [ ] Presentation in stock market
- [ ] Presentation in Entity tab
- [ ] Presentation in Spread sheet
- [ ] Presentation in Player charter
- [ ] Should affect liquidity
- [ ] Should affect value
- [ ] Should be possible to sell during emergency funding
- [ ] Should affect cert limit
- [ ] Pay out dividend at start of each OR
- [ ] Consider that it should be possible to have multiple Bond types/names
- [ ] Implement in selected titles
  - [ ] 1830 variant
  - [ ] 1848, Bank of England
  - [X] ~~1849 variant~~
  - [ ] 1893, AdSK

**Comment by Zwergenpunk** [comment]
I'm not sure whats the difference between bonds and MHE in Harzbahn or the city lines in 1840. They are corporations where you can buy shares but are handled in some automatic way

**Comment by perwestling** [comment]
@Zwergenpunk In the real world: https://xtbs.com.au/insights/differences-between-shares-and-bonds/
"Shares are part-ownership in a company, bonds are IOUs
“What is the difference between shares and bonds?”

Shares and bonds are both types of investment securities, but they have very different characteristics and behave very differently. Simply put, when an investor buys shares they are buying part of a company; when they buy bonds, they are lending money to a company."

Now from an 18xx perspective I would say that bonds:

- Have a set price that are not affected by what happens in the game
- Does not give you any part of the corporation (if they are connected to one) so you cannot control anything
- It tends to be just an investment, where you know how much you will get paid over time
- Are risk free - what you loose is the opportunity loss from not investing in something else with better revenue prospect (but having a risk)

MHE could possibly be a bond, with the special rule that sell drops price/value before phase 5. Also MHE own trains.
NdeM in 1822MX is somewhat similar to MHE, although it does lay track, and if I remember correctly does not change value?

City Lines in 1840 I do not know about so I cannot fathom if it works best as a Bond thing, or something else.

So maybe Bond would be for directorless corporations, that do not operate? And that is what is common for the 4 titles I suggested. (Although I am not sure how Bank of England in 1848 is handled as I think I takes over corporations that go bankrupt? Does it operate? Need to read up on that one.)

**Comment by roseundy** [comment]
I think the main issue is that, unlike the MHE, a corp can have both stocks and bonds each with separate behavior.

**Comment by perwestling** [comment]
@roseundy Did not consider that - which titles has such bonds?
My initial idea was to make a Bond charter in the GUI, similar to Corporation charter. But that might not be a problem? 
So what should that be called? The "entity" that groups the bonds? Like "Bond Corporation"? The issuer of Bonds? 
In 1893 the bonds are issued by City of Cologe - so City of Cologne (Köln Stadt) would have to be this... entity.

Hm, found something interesting: Callable bonds? I guess I need to study it a bit more?

**Comment by perwestling** [comment]
Comment from @benjaminxscott : there's a writeup on 48 BoE here #2548

**Comment by perwestling** [comment]
Yes, 1849 have corporation bonds, where they can issue a bond to get 500 lire - work as a loan. In my initial design I have a Bond class, with an Owner, and an Issuer class. The Issuer class should be used for 1893, and maybe 1848.
1849 will use Bond class and the Corporation will be the issuer. 

The commit should cover all these cases.

**Comment by perwestling** [comment]
After starting to implement 1849 bonds, I realize that this would work better as a one-off Loan. The Loan step could be used for this. Would probably work more or less as in 1856, but just having max one loan. The Loan view could be changed to make Take Loan and Repay Loan buttons configurable, so that 1849 loan step could use Issue Bond and Repay Bond as text instead.

But I will at least implement some to make it possible for Corporations to own Bonds.

**Comment by perwestling** [comment]
I am now closing this, but for future reference these two PRs contains my attempt at doing Bonds:

- https://github.com/tobymao/18xx/pull/5990, contains general Bond concept, Auto-buy for Bonds, use of Bonds in 1893.
- https://github.com/tobymao/18xx/pull/6043, just the general Bond concept in one PR
