### ISSUE TITLE
[1840] Problem during city operations

### ISSUE THREAD

**Issue by DerekLong101** [tobymao/18xx#5735]
In a game of 1840 yesterday, I encountered a problem reported as "Route must contain token" during the City train operations. I have attached the complete game record to the point of failure, but will try to reduce it to see if I can spot where the problem is introduced.

https://gist.github.com/Zwergenpunk/89a7c58688784b61b5a4c7937c737698

Game: https://18xx.games/game/46523

**Comment by Zwergenpunk** [comment]
can you link the json as a gist (https://gist.github.com/) I'm not going to download a random zip file (no offense just careful ;))

**Comment by Zwergenpunk** [comment]
Good catch ;)
The problem is the token of 14 which replaced the V token. The token check should ne be enabled for city tracks.
![image](https://user-images.githubusercontent.com/7661170/122382688-7321a580-cf6a-11eb-9b1c-0a3550f8ca13.png)

**Comment by DerekLong101** [comment]
Thanks for investigating this. Interestingly, that token went in several turns earlier and did not trigger the bug. I think it was the addition of the tile at G5 that triggered the subsequent test for the token.

**Comment by Zwergenpunk** [comment]
yeah exactly. when G5 is not placed there is route possible. with G5 the correct route revenue should be 10
