### ISSUE TITLE
Forced auction fail on purchase (in hotseat?)

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#5737]
During the SR2 'forced' auction, no player can buy the one remaining paper due to 'undefined method <player>'.  

Repo steps: 

Start game, buy all but one thing between the players.  During SR2 auction, the game breaks.  

https://18xx.games/hotseat/hs_icezadpu_1623933983 is currently in this gamestate.

**Comment by perwestling** [comment]
@TheExcalabur: Hotseat games are local to your browser. They can be broken by code upgrades.

The link you give does therefor not link to any game that anyone else can access. To share the game you need to create something that makes it possible to download. 
See e.g. https://docs.github.com/en/github/writing-on-github/editing-and-sharing-content-with-gists/creating-gists

**Comment by TheExcalabur** [comment]
> @TheExcalabur: Hotseat games are local to your browser. They can be broken by code upgrades.

My apologies, I hadn't realised that the hotseat version was local.  Here's a gist on aa reproduction following my steps above: 
https://gist.github.com/TheExcalabur/1a542c6c985e74536836a92084e36167

(and yes, it's still broken but now with a better error message.)
