### ISSUE TITLE
[1893] Unable to purchase private company.

### ISSUE THREAD

**Issue by cherneydh** [tobymao/18xx#5739]
We got through the private draft until Hafen and Fond were left. Attempting to buy either prompts the following error:

Error message:
The server did not accept this action due to: wrong number of arguments (given 1, expected 0)... refreshing.

Game:
https://18xx.games/game/46504

{
  "id": 46504,
  "description": "MVPC",
  "user": {
    "id": 547,
    "name": "cherdan"
  },
  "players": [
    {
      "id": 316,
      "name": "Lemem"
    },
    {
      "id": 547,
      "name": "cherdan"
    }
  ],
  "max_players": 3,
  "title": "1893",
  "settings": {
    "seed": 57854797,
    "unlisted": true,
    "auto_routing": false,
    "player_order": null,
    "optional_rules": []
  },
  "user_settings": null,
  "status": "active",
  "turn": 1,
  "round": "Draft Round",
  "acting": [
    316
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": 316,
      "entity_type": "player",
      "id": 1,
      "created_at": 1623905612,
      "company": "EVA",
      "price": 150
    },
    {
      "type": "bid",
      "entity": 547,
      "entity_type": "player",
      "id": 2,
      "created_at": 1623905888,
      "minor": "KFBE",
      "price": 200
    },
    {
      "type": "bid",
      "entity": 316,
      "entity_type": "player",
      "id": 3,
      "created_at": 1623930235,
      "minor": "EKB",
      "price": 210
    },
    {
      "id": 4,
      "type": "bid",
      "price": 100,
      "entity": 547,
      "company": "HdSK",
      "entity_type": "player",
      "user": 547,
      "created_at": 1623938361
    },
    {
      "id": 5,
      "type": "undo",
      "entity": 316,
      "entity_type": "player",
      "user": 547,
      "created_at": 1623938365
    },
    {
      "type": "bid",
      "entity": 547,
      "entity_type": "player",
      "id": 6,
      "created_at": 1623938370,
      "minor": "KBE",
      "price": 220
    },
    {
      "type": "bid",
      "entity": 316,
      "entity_type": "player",
      "id": 7,
      "created_at": 1623938393,
      "minor": "BKB",
      "price": 190
    },
    {
      "type": "bid",
      "entity": 547,
      "entity_type": "player",
      "id": 8,
      "created_at": 1623938401,
      "minor": "KSZ",
      "price": 100
    },
    {
      "id": 9,
      "type": "pass",
      "entity": 316,
      "entity_type": "player",
      "user": 316,
      "created_at": 1623938446
    },
    {
      "id": 10,
      "type": "undo",
      "entity": 547,
      "entity_type": "player",
      "user": 316,
      "created_at": 1623938448
    },
    {
      "id": 11,
      "type": "pass",
      "entity": 316,
      "entity_type": "player",
      "user": 316,
      "created_at": 1623938458
    },
    {
      "type": "message",
      "entity": 316,
      "entity_type": "player",
      "id": 12,
      "created_at": 1623938469,
      "message": "The game doesn't want me to pick one of these."
    },
    {
      "type": "message",
      "entity": 316,
      "entity_type": "player",
      "id": 13,
      "created_at": 1623938471,
      "message": ":D"
    },
    {
      "type": "message",
      "entity": 316,
      "entity_type": "player",
      "id": 14,
      "created_at": 1623938478,
      "message": "Seems to be a bug"
    },
    {
      "id": 15,
      "type": "undo",
      "entity": 547,
      "entity_type": "player",
      "user": 316,
      "created_at": 1623938539
    },
    {
      "type": "message",
      "entity": 547,
      "entity_type": "player",
      "id": 16,
      "created_at": 1623938576,
      "message": "huh"
    },
    {
      "type": "message",
      "entity": 547,
      "entity_type": "player",
      "id": 17,
      "created_at": 1623938581,
      "message": "which one do you want?"
    },
    {
      "type": "program_share_pass",
      "entity": 547,
      "entity_type": "player",
      "id": 18,
      "created_at": 1623938598
    },
    {
      "type": "program_share_pass",
      "entity": 547,
      "entity_type": "player",
      "id": 19,
      "created_at": 1623938600
    },
    {
      "type": "program_disable",
      "entity": 547,
      "entity_type": "player",
      "id": 20,
      "created_at": 1623938600,
      "reason": "user"
    },
    {
      "type": "message",
      "entity": 316,
      "entity_type": "player",
      "id": 21,
      "created_at": 1623938677,
      "message": "Hafen"
    }
  ],
  "loaded": true,
  "created_at": 1623856112,
  "updated_at": 1623938677
}

**Comment by perwestling** [comment]
Correction to be deployed later today.

**Comment by perwestling** [comment]
@cherneydh  - now it should work again. Try it out. I am closing this issue, and if problem still remains we can reopen it.
