### ISSUE TITLE
[1893] Error in First SR; Can't progress the game

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#5740]
https://18xx.games/game/46525

I can't buy the KSZ minor.  Every time I try the game throws an error in the red bar:  The server did not accept this action due to: wrong number of arguments (given 1, expected 0)

In fact, I can't buy the other private or pass - so the game is stuck.

**Comment by perwestling** [comment]
This is the same cause as for #5739 and #5728. A new fix has been made and will hopefully be deployed today.

**Comment by vints1** [comment]
Gah, I swear I searched for open tickets before posting.  Sorry for the duplication!

**Comment by perwestling** [comment]
No worries - 5740 and 5739 were submitted almost the same time. And 5728 had been closed (as I thought it had been fixed).

**Comment by perwestling** [comment]
@vints1 - now it should work again. Try it out. I am closing this issue, and if problem still remains we can reopen it.

**Comment by vints1** [comment]
It works - thanks!

    On Thursday, June 17, 2021, 10:56:14 AM CDT, Per Westling ***@***.***> wrote:  
 
 


@vints1 - now it should work again. Try it out. I am closing this issue, and if problem still remains we can reopen it.
