### ISSUE TITLE
18Ireland - Certain situations allow one to run on narrow guage

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#5744]
18Ireland

If a town is connected by both narrow and wide guage, the implementation allows you to run on the narrow gauge track. I’ve posted screenshots of this, game https://18xx.games/game/39948?action=851

Allows me to run E7-D6-F6-G1 (Narrow: £30)

D6 to E7 has two possible routes, the narrow gauge track only crosses one hex edge and the normal gauge requires 2

**Comment by Blobbley** [comment]
![IMG_3028](https://user-images.githubusercontent.com/69050942/122521881-3fe42280-d00d-11eb-9001-d8b9be63932c.PNG)
![IMG_3027](https://user-images.githubusercontent.com/69050942/122521889-42df1300-d00d-11eb-83ac-36ee852d18ea.PNG)

**Comment by jenf** [comment]
dup of #5469
