### ISSUE TITLE
 [1856] Is value calculation correct?

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5745]
This is the spread sheet after SR 5:
![image](https://user-images.githubusercontent.com/2631151/122531373-b722b200-d01f-11eb-9bc6-7b7d9d814ea8.png)

The game is at https://18xx.games/game/44377?action=408

Question is how the value for player Liol could increase by $200 during the SR?

**Comment by Maxwell-Frank** [comment]
It's definitely not correct.  [Here](https://18xx.games/game/44377?action=370), Liol's value is less than their liquidity. Their stocks and cash sums to $633, which is lower than their value, for some reason.

**Comment by ventusignis** [comment]
It's correct. The key factor is for the purposes for end game scoring and hence value, the value of a corporations share is reduced by $10 for each outstanding loan it has. Liol started the SR with 2 LPS shares with market value of 90 and 7 loans so selling those netted a value gain of $140 alone
