### ISSUE TITLE
[18ZOO] - 1S cannot handle single city + multiple towns

### ISSUE THREAD

**Issue by carlorusso** [tobymao/18xx#5749]
https://gist.github.com/carlorusso/6665d3c9bf7d737020405173d8fc4302
http://localhost:9292/fixture/18ZOO/or_power.patch?action=88

select local on click works:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1408567/122560486-f3b2d580-d040-11eb-8f75-e5448811abb9.png">

select a city + a town works:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/1408567/122560546-03321e80-d041-11eb-9e23-9027c09c87ad.png">

cannot select a 2nd town:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/1408567/122560589-104f0d80-d041-11eb-8c4c-63de8b1fcf1f.png">

**Comment by tobymao** [comment]
this change doesn't really make sense to me, what does a local train mean?

**Comment by carlorusso** [comment]
"local train" is used for trains that can touch a city (and maybe other town)

**Comment by tobymao** [comment]
how does it differ from 1822?

**Comment by carlorusso** [comment]
1822 has the L train that can touch a city and a single town.
and the current code works perfectly to handle just a single town.
I need to be able to touch any number of town (other than a single city); and with the current code, when you click the second town, it will remove the city

**Comment by tobymao** [comment]
isn't that just a normal train? for example in 1830, a train can run from a city to a town, how is that different from a local train?

**Comment by carlorusso** [comment]
local train are able to run:
- single city (will use "local")
- city + towns
! local train are not able to touch a single city (they need at least 2 node to be considered)
