### ISSUE TITLE
[1893] Error when trying to buy after auction price is lowered

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#5755]
https://18xx.games/hotseat/hs_ykqftonn_1624071823

Error message:  undefined method `player' for <Engine::Game::G1893::Step::StartingPackageForcedAuction>

This error is reproductible, tried several hotseat games and this or a similar error came up every time.

If all players pass, and the price is reduced, when a player tries to buy the private for the reduced price they get an error such as the one above.

**Comment by tobymao** [comment]
hot seat games aren't available to us

**Comment by luigicoolGH** [comment]
I was not aware of that.  The error is easily reproducible.  All one needs to do is have everyone pass during the auction of a private like FdSD for a couple of rounds, so that the price goes down, and then try to buy it.  Fastest way to reproduce it is to start game, have player 1 select FdSD for auction, pass a few times, then have player 2 try to buy it at the reduced price.

**Comment by tobymao** [comment]
can you please add the json gist?

**Comment by perwestling** [comment]
Is probably same cause as #5750

**Comment by perwestling** [comment]
I have now created a correction for #5750. I think it might be the same cause, so I will close this ticket.

I will close this ticket when the correction have been deployed. And you can reopen it if the fix does not help.
You can wait with any gist.

**Comment by perwestling** [comment]
@luigicoolGH I have put up a couple of fixes, but they will break your game. Your game will probably be saved if you do undo until the choice of thing to auction off is selected. 
One of the fixes now skip players that cannot afford to purchase what is up for auction (with its current price). Therefor passes done in the old version breaks the game when you get a new version.

So, a couple of undoes should save the game, in case you do it before the new version arrives. If not, the game is probably broken and you will have to delete it and create a new one.

**Comment by luigicoolGH** [comment]
undefined method `player' for <Engine::Game::G1893::Step::StartingPackageForcedAuction>

Problem persists.  It is consistently reproduced.  Fastest way to reproduce it is to have everyone pass during the auction, pass during SR, choose a company, pass to reduce price during next auction, and then try to buy. This is just a test, so there is no problem of losing existing games.  

I don't know how to do the json gist, all I can do is copy the json from the hotseat game.

{
  "status": "active",
  "actions": [
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "created_at": 1624130234
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "created_at": 1624130234
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "created_at": 1624130235
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 4,
      "created_at": 1624130238
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 5,
      "created_at": 1624130239
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "created_at": 1624130240
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "created_at": 1624130241
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 8,
      "created_at": 1624130241
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9,
      "created_at": 1624130247,
      "action_id": 7
    },
    {
      "type": "undo",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 10,
      "created_at": 1624130247,
      "action_id": 6
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 11,
      "created_at": 1624130248,
      "action_id": 5
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "created_at": 1624130248,
      "action_id": 4
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13,
      "created_at": 1624130249,
      "action_id": 3
    },
    {
      "type": "undo",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 14,
      "created_at": 1624130249,
      "action_id": 2
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15,
      "created_at": 1624130250,
      "action_id": 1
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16,
      "created_at": 1624130257
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "created_at": 1624130263
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "created_at": 1624130264
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "created_at": 1624130265
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 20,
      "created_at": 1624130266
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21,
      "created_at": 1624130269
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 22,
      "created_at": 1624130270
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 23,
      "created_at": 1624130270
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 24,
      "created_at": 1624130271
    },
    {
      "type": "undo",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25,
      "created_at": 1624130276
    },
    {
      "type": "undo",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 26,
      "created_at": 1624130280
    },
    {
      "type": "undo",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 27,
      "created_at": 1624130280
    },
    {
      "type": "undo",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 28,
      "created_at": 1624130282
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 29,
      "created_at": 1624130289
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 30,
      "created_at": 1624130289
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31,
      "created_at": 1624130290
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 32,
      "created_at": 1624130290
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 33,
      "created_at": 1624130294,
      "company": "FdSD",
      "price": 190
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 34,
      "created_at": 1624130297
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 35,
      "created_at": 1624130298
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 36,
      "created_at": 1624130298
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 37,
      "created_at": 1624130303
    }
  ],
  "id": "hs_aadufxng_1624130231",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    },
    {
      "name": "Player 4"
    }
  ],
  "title": "1893",
  "description": "",
  "max_players": "4",
  "settings": {
    "optional_rules": []
  },
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2021-06-19",
  "loaded": true,
  "result": {},
  "turn": 2,
  "round": "Draft Round",
  "acting": [
    "Player 2"
  ],
  "updated_at": 1624130303
}

**Comment by luigicoolGH** [comment]
Problem seems to be fixed! Thank you Per! :-)

**Comment by perwestling** [comment]
@luigicoolGH It can take some time between issue corrected, and the fix being deployed (which means made available to the players). If you want to know the more gritty details there is an About on the first page, and the you can see the Current version, as well as the latest version on "master". If there is a commit that is on master but the Current version has not been step to or passed that, you have the situation I was talking about.
The delay in deploy can be to several reasons. One of them can be that it creates some problem that need to be fixed.

Anyway, thanks for reporting the issue. Looking forward to the next one ;-)  so that we can make 1893 a great implementation.
