### ISSUE TITLE
[1822] Emergency fundraising permits prohibited sale of shares

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5764]
See https://18xx.games/game/43688?action=1017

LYR was started and floated during SR 7.
During OR 7.1, LYR had a forced train purchase and president had insufficient cash.

Relevant rules:

> **5.15.1** If the director has insufficient funds, they must sell stock. The normal constraints on stock sales apply.
> **4.4.1** In their stock round turn, a player may sell any number of stock certificates, transferring them from their holdings into the bank pool subject to the constraints set out below:
> Private companies, minor companies, and concessions may not be sold.
> • Shares cannot be sold in a company that has not completed an operating round. 

Since the president's holdings consisted entirely of private companies, minor companies, and shares in a company that had not completed an OR, I should have been forced to take a loan.

Instead, 18xx.games insisted that I sell shares in violation of the "not completed an OR" rule.

Screenshots:
<img width="332" alt="Screen Shot 2021-06-19 at 10 54 28 " src="https://user-images.githubusercontent.com/82781561/122648050-e2270780-d0ec-11eb-9fe7-b9f20c2f0dfa.png">

<img width="364" alt="Screen Shot 2021-06-19 at 10 55 03 " src="https://user-images.githubusercontent.com/82781561/122648054-e4896180-d0ec-11eb-8eaa-d06c60a31136.png">

<img width="569" alt="Screen Shot 2021-06-19 at 10 57 01 " src="https://user-images.githubusercontent.com/82781561/122648107-261a0c80-d0ed-11eb-8153-6f4e3a13cc36.png">

**Comment by KevinR1000** [comment]
I think that this is caused ultimately by g_1822 using `SELL_AFTER = :operate` when the rule is "Shares cannot be sold in a company that has not **_completed an operating round_**."

`SELL_AFTER = :operate` is keyed to `corporation.operated?` which in turn is `!@operating_history.empty?` (in `engine/operator.rb`).

For other actions (e.g., acquire minor, issue shares), g_1822 checks either `entity.operating_history.size > 1` (good) or `entity.operating_history.size < 2` (bad).

It is possible that 1822 requires a new case for `SELL_AFTER` in `def liquidity` in `engine/game/base.rb`.  For 1822 specifically (which always has 2 ORs for major companies), the test could be something like `operating_history.size > 1 || (operating_history.size == 1 && @round.round_num >1)`.

**Comment by scottredracecar** [comment]
Yeah, this all sounds right to me

**Comment by KevinR1000** [comment]
Ruling from Simon:  https://18xx.games/game/43688?action=1074

> KevinR: When precisely do shares in a major become sellable? 
> KevinR: Is the the end of its turn in the OR, or the end of the entire OR?
> LimeTurtle: Ah, end of its turn. Shares could be sold later in same OR through EMR

**Comment by scottredracecar** [comment]
4.4.1 says "Shares cannot be sold in a company that has not completed an
operating round."

So it may be best if we double-double-check with Simon before making the
change because I would consider this in need of an erratum to rule that
way. To me, an operating round is the full round.

**Comment by KevinR1000** [comment]
Simon's fairly distracted right now.  Give him a week or more.

There is some sloppy wording, so maybe a FAQ but not necessary a full erratum.  But that's your call as publisher.

The "Easy to Miss Rules" summary on page 34 says:
> • May only be sold once the company has completed one turn of operation.

Issuing says:
> 5.19.3 A company may not issue stock in its first operating turn.

Of course, issuing (and acquiring) can only be done on the company's turn, so "after first turn" and "after first OR" are the same.  Only emergency selling can happen after the company's turn but still during its first OR.

(Meanwhile, I'll continue learning these data structures to try to see how the first OR can be identified robustly.)

**Comment by philcampeau** [comment]
I just verified in a hotseat game, this is definitely implemented properly at this point. Likely whoever fixed it forgot to close this game.

**Comment by philcampeau** [comment]
I thought the issue was resolved, but on further testing, this still occurs. It won't force you to sell shares of the unoperated company if funding for another entity, but for the corp itself, it will allow you to sell them. 

I'll look into this more.
