### ISSUE TITLE
[18ZOO] Game broken and the game requests a bug report to be sent for 18zoo

### ISSUE THREAD

**Issue by databoy01** [tobymao/18xx#5770]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

18Zoo 

**What's your Game ID?** 

https://18xx.games/game/45953

Multiplayer game as an FYI 

It states the following “ We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 253
Broken action: { "type": "pass", "entity": 153, "entity_type": "player", "id": 253, "created_at": 1623950021 }
Please raise a bug report and include this link (https://18xx.games/game/45953?action=252)”

**Bug started on its own**

**Which Browser / Platform?** I’m using iPad, although game looks stuck on its own. 
- Browser Version new iPad 11 pro

**Comment by carlorusso** [comment]
@databoy01 I'm sorry, I just released these two bug fixes (https://github.com/tobymao/18xx/issues/5748, https://github.com/tobymao/18xx/issues/5702) and I think it broke your game :(

**Comment by databoy01** [comment]
Hello Carlo,

Can you end the game somehow?  It’s showing in my active games and I cannot end it as it gives me an error for that too. Thank you. 


Regards,

Ken Falls

**Comment by carlorusso** [comment]
@databoy01 admin archived it
