### ISSUE TITLE
[1846] autoroute not taking E/W bonus into account

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#5778]
It seems that autorouting didn't take the E/W bonus into account for at least this specific example, and perhaps generally

Repro: https://gist.github.com/benjaminxscott/940131b7fe3ef7fdacb2ef49981445ef

In this example, it gets 36/share when it s.b. 41

(I'm not entirely sure how autorouting is implemented, so this may be a case-specific issue of the algo saying "we calculated the 2 train first, found a route and short-circuited")

**Comment by tobymao** [comment]
works for me, i get 41 a share

**Comment by benjaminxscott** [comment]
To note from slack:
- In the above example, it will attempt to maintain the prior 2-train runs, so hitting `auto` will route around those "locked" runs, emitting 36
- Hitting `clear all` then `auto` will re-calculate all routes, emitting 41
