### ISSUE TITLE
[18DE] Merge with company of different owner is impossible

### ISSUE THREAD

**Issue by barattie** [tobymao/18xx#5781]
Game: https://18xx.games/game/43314
Phase: Phase 4 - Merger Round 3.2 (of 2) - Convert or Merge Corporation

- BY is playing
- Show Corporations from Other Players
- Select OB
- Click on Merge
- The screen briefly shows a yellow banner containing Confirm button and warning: "Click Confirm if todpv has already consented to this action". I do not click Confirm and game goes back to BY Merge turn (screenshot attached). I thought that now it was todvp turn to accept or decline the merge?

<img width="1505" alt="Schermata 2021-06-21 alle 09 27 24" src="https://user-images.githubusercontent.com/86224965/122723852-b1250f00-d273-11eb-853d-b2cda4f4e614.png">

- Browser Version
- Safari Version 14.1.1 (15611.2.7.1.6, 15611)
- Platform: Desktop

**Comment by Zwergenpunk** [comment]
The confirm is just in the user interface. The other player does not has to do anything.

Right now we do not support real user interaction. You could also buy all trains of other corporations etc.

There is somewhere an issue  (or multiple) which describes the problem

**Comment by barattie** [comment]
Thanks a lot!AlexOn lun, giu 21, 2021 at 10:17, Michael ***@***.***> wrote:
The confirm is just in the user interface. The other player does not has to do anything.
Right now we do not support real user interaction. You could also buy all trains of other corporations etc.
There is somewhere an issue  (or multiple) which describes the problem

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/tobymao/18xx/issues/5781#issuecomment-864829624",
"url": "https://github.com/tobymao/18xx/issues/5781#issuecomment-864829624",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
