### ISSUE TITLE
[1893] First Stock Round: Can‘t buy last certificate (here: EKB)

### ISSUE THREAD

**Issue by Thomas-CET** [tobymao/18xx#5789]
https://18xx.games/game/46897 

I have 130 M. It is my turn. EKB is offered to me for 100. Why can’t I buy it?

**Comment by perwestling** [comment]
@Thomas-CET - this was fixed in the latest deploy. Refresh and check again to see if it works now.

**Comment by Thomas-CET** [comment]
@perwestling Thanks - that did the trick.
