### ISSUE TITLE
1822, Minor 14 can't merge into LBSCR

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#5798]
game #40463, Step 726
The LBSCR want to merge the Minor 14. Connection is established.
![grafik](https://user-images.githubusercontent.com/80693707/122990878-b59d1500-d3a4-11eb-8567-716d658ba718.png)
![grafik](https://user-images.githubusercontent.com/80693707/122991049-e2e9c300-d3a4-11eb-9698-f6fdede588e1.png)
The merge isn't offered.
Not allowed by rules or Bug?

**Comment by Maxwell-Frank** [comment]
@volker18xxdev Your company can't afford to acquire it.  Minor 14 is at $120/share, meaning the company has to give you $240 of assets.  It would need to give you 2 shares at $110 each and $20 of cash to make up the difference.  Your company has $13, which is less than $20.
