### ISSUE TITLE
[1862] User cannot pass during merge (illegal action)

### ISSUE THREAD

**Issue by Krzysztof-PL** [tobymao/18xx#5799]
Game ID: 47215 (stay open)

During pass in Merge step appears message:
The server did not accept this action due to: illegal action: Blocking step Acquier cannot proces action 274... refreshing

**Comment by roseundy** [comment]
I can't reproduce this. Can you hard refresh your browser (on a PC: <ctrl><shift>R) and try again?

**Comment by Krzysztof-PL** [comment]
We are trying all in Master Mode. I attach screenshot
![1862 error](https://user-images.githubusercontent.com/86325701/123004276-b0e05d00-d3b4-11eb-90d3-294007610450.jpg)

**Comment by roseundy** [comment]
This was a challenging bug to find. The root cause was a rounding error when EUR merged earlier in the game.

**Comment by roseundy** [comment]
Once the bug fix is released, you will find that the game will be on the redeem shares step for EUR.
