### ISSUE TITLE
Exchange Dougo Railway (game id 75)

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#58]
I can't (seem to find out how to) exchange the Dougo Railway private for a Iyo share during SR1.

Edit: I figured it out so it's not a bug. It isn't intuitive though. When I want to exchange I need to:
- go to the companies tab, 
- select Dougo
- go to the game tab
- press the then appeared button to exchange share.

Perhaps this can be made in a more transparent way.

**Comment by benjaminxscott** [comment]
Perhaps add a 'Exchange Share' next to the current 'Buy IPO Share' button, which only appears when Iyo is selected by the player who owns the Dougo

Something I ran into while testing out is that if the Dougo-owning player buys Iyo 4 shares and runs out of money, they never get another turn so cannot exchange for the 5th share, so I'd imagine there needs to be some additional logic for "the Dougo-owning player has a valid move even if out of money"j

**Comment by eratos** [comment]
I'm glad you posted this, because I'm having the exact same problem!

**Comment by jenf** [comment]
@benjaminxscott technically Dougo can be exchanged at any point, and the current interface can do this. The new button will allow out of turn exchanges during the stock round (the old mechanism will remain for the case that someone wants to use the power during an OR)
