### ISSUE TITLE
[18Ireland] bidding allowed while at certificate limit

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#5808]
In an 18Ireland game a company is put up for auction, a player at their certificate limit is allowed to bid, but should not be.

In this game: https://18xx.games/game/40923?action=645
UR is put up to auction, and I (jeroenh) entered the bidding, not realising I was at my limit.
I only found out I was at my limit when I tried to enter a winning bid that nobody else could top. The game did not allow that because I could not buy it.

The implementation should have prevented me from joining the bidding in the first place, because I can never win the bidding.

**Comment by jeroenh** [comment]
Heard from other player in that game involved in the final stage of bidding: they could not pass because I was at my cert limit.

**Comment by jenf** [comment]
Probably a bug in other 'bidding' games :(
