### ISSUE TITLE
[1860] train liability bug when no valid route but company can afford train from bank/initial offering 

### ISSUE THREAD

**Issue by ckarlof** [tobymao/18xx#5821]
I believe there is a bug in the train liability rules in 1860. The Insolvency section of the [1860 rules](https://tesera.ru/images/items/154476/1860.PDF) says: 

"If a company doesn’t have any trains at the end of its turn, then it must buy one from the bank, initial offering, or 
another company (by mutual consent of the director(s) of both companies), if it can afford one."

If the company can't afford a train AND has a valid route, then it becomes insolvent. 

However, my interpretation of this is that if a company doesn't have a valid route, it **still must buy a train** if it can afford one from the bank or initial offering. Here's an example of a game there that rule is violated: https://18xx.games/game/43431?action=234

BHI&R has no valid route and £680. It can afford the 4+2, but skips buying trains. 

I believe the [18xx rules differences list on FWTWR](http://www.fwtwr.com/18xx/rules_difference_list/single_list.htm#9) is also clear on this: 

Top9.2 - Must a major share company buy a train if it does not have one?
 1860, 18GB Yes, if it is able to do so. If it cannot buy a train and has a route it is declared insolvent and must lease a train from the bank, retaining dividends, until it is able to buy a train.

I also able to reproduce this bug in more recent game here: https://18xx.games/game/43478?action=346 If you put the game into hot seat at this point, VYSC does not have a valid route, can afford the 5+3, but is not required to buy a train by the interface (i.e., it can "skip trains"):

<img width="954" alt="Screen Shot 2021-06-23 at 11 27 29 PM" src="https://user-images.githubusercontent.com/2365255/123213478-e6e81480-d47a-11eb-9e84-6b08becec10d.png">

**Comment by roseundy** [comment]
OK, thanks. Hopefully, this won't be hard to fix.

**Comment by ckarlof** [comment]
Thank you!
