### ISSUE TITLE
Remove "Sym" label from corporation charters

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#583]
The symbols are self evident and don't need labeling. Removing "Sym" would also allow you to render the symbol in a larger font if desired. At any rate, no need for clutter on the charter.

**Comment by tobymao** [comment]
i don’t think they are in 1889

**Comment by tobymao** [comment]
oh you mean the label sym

**Comment by ChrisTheCat** [comment]
<img width="350" alt="Screenshot 2020-05-30 10 31 34" src="https://user-images.githubusercontent.com/8732435/83335308-bfffe480-a260-11ea-9d16-bd6cb4382322.png">

Not sure I understand your comment @tobymao. What I'm suggesting is that instead of:

```
TR      3,4      ¥283
Sym  Trains   Cash
```

```
TR      3,4      ¥283
         Trains   Cash
```

And the TR font could be larger and vertically centered.

**Comment by ChrisTheCat** [comment]
The "Cash" label might also be unnecessary - the currency symbol is sufficient.

**Comment by michaeljb** [comment]
Been thinking for a while it might be nice to just move the sym into the top of the card, e.g., "Tosa Electric Railway (TR)"

**Comment by gchambers419** [comment]
I'd find it helpful to put a copy of the token symbol in there too.  It's hard to make out the ones already there when they're all greyed out because they've been placed

**Comment by dfannius** [comment]
> Been thinking for a while it might be nice to just move the sym into the top of the card, e.g., "Tosa Electric Railway (TR)"

I tried this locally a while ago and ran into problems with "Takamatsu & Kotohira Electric Railway (KO)" being too long.

**Comment by yzemaze** [comment]
> I tried this locally a while ago and ran into problems with "Takamatsu & Kotohira Electric Railway (KO)" being too long.
It isn’t with just the Sym, but with a token it runs a bit long. That said an ellipsis (…) for veeery long names is easy to do. So how about this?
![image](https://user-images.githubusercontent.com/33390595/83918679-83108200-a779-11ea-868e-483fa5d1914e.png)

**Comment by dfannius** [comment]
That's basically the single place that the full name of a corporation is presented. I don't think we should cut it off if at all possible.

**Comment by gchambers419** [comment]
Put the symbol and token in the gray area?

**Comment by yzemaze** [comment]
![image](https://user-images.githubusercontent.com/33390595/83919071-2f526880-a77a-11ea-8b96-d1e7cdf9a900.png)

**Comment by gchambers419** [comment]
That works too

**Comment by yzemaze** [comment]
It’s basically down to (personal) preferences. Everything goes:
![image](https://user-images.githubusercontent.com/33390595/83920986-b3f2b600-a77d-11ea-9f36-95d53e3732bb.png)

**Comment by ChrisTheCat** [comment]
Need to plan ahead for games where companies can have 6 or 8 or even 20 tokens

I do like the versions with the symbol in a large font.

**Comment by tobymao** [comment]
the games with 20 tokens can have a scroller, you aint fittin 20 tokens on
anything

**Comment by scottredracecar** [comment]
Charter design has been revised to not include the Sym label
