### ISSUE TITLE
[1862] Acquisition procedure not working correctly - director forced to sell option when there are still shares available

### ISSUE THREAD

**Issue by jstern78** [tobymao/18xx#5833]
Game ID: 46266
Link at the problematic action: https://18xx.games/game/46266?action=612
[](https://18xx.games/game/46266?action=612)

Game State Description:
Y&N is in the process of acquiring WVR. JonS is the director of both companies.
Prior to acquisition (in turn order):
JonS has 6 shares of WVR and 5 shares of Y&N
Juztyn has 1 share of WVR
jrebs has 2 shares of WVR
Y&N has 4 shares in treasury

Expected Result:
I am not an expert on the game, but my understanding is that the exchanging of shares and opportunity to purchase options should proceed in turn order, starting with the director and ending with the company treasury. After exchanging shares, the expection was:
JonS: 5 shares + 1 option
Juztyn: 1 option
jrebs: 1 share
Y&N: 2 shares
This would continue with JonS followed by Juztyn having the opportunity to exercise their option.

What actually happened:
JonS did not have an opportunity to exercise the option and was forced to sell it. It looks like what is happening is that it is only trying to trade in non-surviving shares of WVR for shares of Y&N in the market. My reading of 5.2.4 2) explains that if there are no shares in the market, you exchange with players acting later in turn order. In other words, the director should have first dibs on exercising their option. I believe that the shortcut described in 5.2.4 1) that suggests players exchanging simultaneously to save time is not supposed to disrupt the ordering of the exchange. In short, when there are no shares of Y&N left in the market, JonS should exchange his option share of WVR for a Y&N share with the next player who will act in the merge process - in this case Juztyn. The way the process played out in this game was that JonS was forced to sell the option, leaving an unassigned share in the market.

**Comment by jstern78** [comment]
The rules state: "Option shares must be swapped in this way too, after the player’s other non-surviving shares have all been swapped." Not after _all_ players' other non-surviving shares...

Maybe this is the issue?

**Comment by roseundy** [comment]
The implementation is correct. The reason JonS didn't exercise the option is that there simply was no cash for it. Going into the Acquisition JonS only had £19 and thus was forced to sell the option.

**Comment by jstern78** [comment]
Thanks for looking into it. You are right.
