### ISSUE TITLE
[1893] #KV63 wrong value?

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#5834]
#KV63 is worth 30 in brown, which seems incorrect given that the green value is also 30. I am aware some games do this on purpose, but I cannot find a tile register online for 1893 and it doesn't seem like that kind of game.

**Comment by perwestling** [comment]
Well spotted - KV63 should be 40.

There are now two buds with the variant tiles, this one and #5819, and they will be fixed at the same time.

**Comment by perwestling** [comment]
It should now be correct, and fix has been deployed, so I close this ticket.
