### ISSUE TITLE
1840 selling shares

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#5840]
https://18xx.games/game/47616?action=723
Unable to sell 3 shares of a City Company (D) when there were 40% in the Market. We are unable to find where the rules limit the amount in the bank pool to 50%… restrictions on sales are page 10 section VII.4
We also noticed that it gives people a presidency * when they have 20% after someone sells.  We are unsure if this is also part of what is preventing the sale or not… 
Thanks!

**Comment by Zwergenpunk** [comment]
Oh thats intersting. i never sold a city corporation while testing. Thanks for the report. 
Thats a bug. You should be able to sell everything

**Comment by Eludyan** [comment]
It definitely does not currently let you sell the “presidency” of a city corp… which should not exist.
