### ISSUE TITLE
1840 running track payouts

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#5841]
When running trams, the pay does not update unless you redo the run after upgrading tile. If using the prefilled in track, it pays the original amount. 
The below action does not show the error as we fixed it… but you should be able to undo back and then redo to see it do the error. I hope!

https://18xx.games/game/47616?action=1014

**Comment by Zwergenpunk** [comment]
That seems pretty weird, since something like this should happen in every game/turn.

Can you explain how i can create the state from your link?

**Comment by Eludyan** [comment]
If you go to after the company laid track and before the company ran and let it auto select the route, write down the amount. Then reselect the route and it should be an adjusted amount. I agree, it should happen everywhere and honestly I never have bothered to check if it does. 
Mark said it was happening to all of his companies, so I imagine it happened to everyone and we didn’t notice? I don’t honestly understand it myself… Mark Derrick is the one who noticed it happening at all.  I just filed all the bug reports for our game on behalf of our group. 
Jen

**Comment by Zwergenpunk** [comment]
I'm sorry I cannot reproduce the bug =/

**Comment by Eludyan** [comment]
Thanks for trying!  If I see it again I will try to get screen shots and such. 
Jen
