### ISSUE TITLE
[1870] Simultaneous Connection Runs tell multiple players it's their turn

### ISSUE THREAD

**Issue by skizelo** [tobymao/18xx#5847]
https://18xx.games/game/37799?action=598

3 companies with 3 different presidents could reach their destination through a single tile lay. The UI which tells players to take their turn was on for all three of those players, even though only one of them was actually up to play.
![1870 bug 1](https://user-images.githubusercontent.com/77389765/123545597-c35dec00-d750-11eb-8b3c-1302cf83744f.png)
![1870 player order 2](https://user-images.githubusercontent.com/77389765/123545599-c3f68280-d750-11eb-9ef8-7bd786a7c9d1.jpg)
![1870 player order 3](https://user-images.githubusercontent.com/77389765/123545601-c48f1900-d750-11eb-9f75-0e9caef9cb24.jpg)

**Comment by Maxwell-Frank** [comment]
To add to this, it looks like the connection runs are also occurring in the wrong order. When multiple companies become eligible at the same time, the currently operating company goes first, followed by the other companies in stock price order (p. 22).  Which in this case would be MP, ATSF, MKT.

**Comment by tobymao** [comment]
i think the intent though is to have active_players mean that they can make a move, this fix doesn't seem correct as active_players for 1870 may just be wrong?

**Comment by JoeB989** [comment]
Needs more discussion I guess.  Some notes in canceled PR  https://github.com/tobymao/18xx/pull/7084

**Comment by JoeB989** [comment]
Downgrading to minor bug because this is visual confusion only.  Invalid actions (wrong player running the destination) are prevented.  Also split out a new bug #7145 for the incorrect railroad ordering during destination run.

**Comment by daniel-sousa-me** [comment]
@JoeB989 Thanks for fixing all the 1870 bugs! Only now I've found the time to look into them

Are you working on this? If not, I can take care of it.

I never really understood how the active player thing works, and I was just throwing random arrays at it, until something worked :|

**Comment by JoeB989** [comment]
No, I haven't figured out how to handle it yet.  I'll let you :)
