### ISSUE TITLE
[18Zoo]  Enter button needs to be clicked twice to load game

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#5848]
At the main page, when selecting a game of 18Zoo the "Enter" button needs to be clicked twice to enter the game.  The first time one clicks, the "Enter" button simply greys out.  Clicking a second time (on the greyed out button) then allows the game to load.
 This does not happen with other titles.

**Comment by benjaminxscott** [comment]
Hmm I can't repro this on a multiplayer or hotseat game, but perhaps this was a temporaryissue with the frontend?

**Comment by scottredracecar** [comment]
closing, please reopen if this is a persistent issue you think should be resolved.
