### ISSUE TITLE
[Harzbahn 1873] Cannot add additional diesel routes unless the whole concession route is traced already.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5854]
Hotseat: https://gist.github.com/physic/9ea72a741f49691608ea6d789e9026e5
Action: Current (latest) action. action=768

Scenario 1.
Click the D under trains.
Trace any legal diesel route.
Click the D again.
Expected result: An additional D slot appears.
Observed result: No additional D slot appears. 

Scenario 2.
Click the D under trains.
Trace the illegal route consisting of both of NWE's concession routes, concatenated.
Click the D again.
Observed result: An additional D slot appears.

My suggestion is to remove the requirement that the first route traced is the concession route. It's already checked on the "Submit route" button, and there's already a helpful message saying why the route is invalid. No need to block adding diesel slots as well.

**Comment by roseundy** [comment]
This will fixed by adding direct user control over the number of diesel trains. This will happen in the next week or so.

**Comment by scottredracecar** [comment]
@roseundy did this get fixed?

**Comment by roseundy** [comment]
Not yet. It's one of the enhancement I'll get to after I get 21Moon to alpha.

**Comment by beorn7** [comment]
Even the workaround doesn't seem to do the trick  anymore in https://18xx.games/game/73033 . We are stuck in that game (and it's a tournament game…).

Could a "Add a D train" button be added to the games in progress so that we can finish the tournament?

**Comment by beorn7** [comment]
Somehow I managed to add a D now. I think it involved clicking the Auto button, but I'm not sure.

https://18xx.games/game/73033?action=824 is the action just before selecting routes, for anyone who wants to play with it.

**Comment by roseundy** [comment]
New UI to add/subtract a diesel:
![Harzbahn_add_diesel](https://user-images.githubusercontent.com/8494213/156940384-14393afb-d066-4cc7-8901-6ee5ed340326.png)

One thing to be aware of with the new UI is that when you create a new diesel, the new route created for it is _not_ selected.

**Comment by roseundy** [comment]
Note that the "Reset" button won't remove/add trains to how it started before trains were added or subtracted by the user. However, refreshing the page will reset everything back to the start.
