### ISSUE TITLE
[Harzbahn 1873] Engine allows laying track tile that does not preserve existing track.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5856]
Hotseat: https://gist.github.com/physic/9ea72a741f49691608ea6d789e9026e5
Action: 733

GHE lays F9. Before the track lay, the W and NE hex edges both connect to the same village. After the track lay the W and NE hex edges connect to different disconnected village stations.

**Comment by roseundy** [comment]
I think I need a ruling from @KKiermeier on this. I'm inclined to view this as a bug, but being able to split villages into two pieces when upgrading from yellow to green is novel for most 18xx games.

Before the upgrade:
![village_before](https://user-images.githubusercontent.com/8494213/123677651-9e29b600-d802-11eb-87df-432cf65fcd87.png)

Is this a legal upgrade:
![village_after](https://user-images.githubusercontent.com/8494213/123677676-a5e95a80-d802-11eb-860b-3107a451de18.png)

**Comment by roseundy** [comment]
This is more complicated than I thought. While the tile is a legal upgrade, I don't think the orientation is legal.

**Comment by KKiermeier** [comment]
In fact, this is no legal upgrade since the previously existing connection is disrupted. 
I'll have to consult the rules once more. I'm pretty sure the rule is clear at this point. At least I believe so. But even if not, it was definitely not intended by me to let such an upgrade, that disrupts a previously existing track connection, be legal.

**Comment by KKiermeier** [comment]
In 4.4.1 of the rules there is a point that says:

"When upgrading, existing track mus be maintained and existing connections must not be cut off."

I think this is clear enough to make the above upgrade illegal.

**Comment by roseundy** [comment]
OK, I was pretty sure it was indeed a bug.

**Comment by physic** [comment]
> This is more complicated than I thought. While the tile is a legal upgrade, I don't think the orientation is legal.

That is correct. However, even illegal tiles are shown here as options, and may be placed, such as 964 and 970. (Double sharp, and double straight)

**Comment by roseundy** [comment]
Yes. I just came to post that there are multiple bugs here.
