### ISSUE TITLE
[1840] Map hex G11 should have Stadtbahn track from SE to NE

### ISSUE THREAD

**Issue by KKiermeier** [tobymao/18xx#5859]
On the printed map there is the track mentioned above. 
The map at 18xx.games doesn't show it.

**Comment by Zwergenpunk** [comment]
Oh wow. I totally missed that. Explains alot...

**Comment by Zwergenpunk** [comment]
There is still an issue with the city track line. It still cannot build F12 when G11 is not upgraded

**Comment by KKiermeier** [comment]
In the fixed map: is the value of the Stadtbahn halt in G11 really 10 (and not 30)?

**Comment by philcampeau** [comment]
I don't have a copy of the game. My friend who owns it said it was 10.

**Comment by KKiermeier** [comment]
OK, thanks, I tried to figure it out from the map reproduction in the Rules, which is somehow blurred. Sorry.

**Comment by Zwergenpunk** [comment]
![Capture+_2021-06-30-23-41-11.png](https://user-images.githubusercontent.com/7661170/124035361-b6fdbb80-d9fc-11eb-9c0a-1391f07e02c0.png)

**Comment by KKiermeier** [comment]
Thank you! This settles it ;-)
