### ISSUE TITLE
[1817] Next acquisition begins before Cash Crisis is resolved

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5860]
When a liquidated company is acquired, the next company that could be acquired is identified and named in the log before the cash crisis from the liquidation is resolved.  It would be keen if the cash crisis code could be called before the next acquisition.

See for example https://18xx.games/game/36945?action=1341 or https://18xx.games/game/36945?action=1307

The sequence of log messages at 1341, with my annotations, is as follows:
> H passes taking additional loans

_Acquiring company is done paying for acquisition._

> nigelsandwich settles Bess debts for $415

_Liquidated company passes debts up to president_

> R cannot be bought at $450, skipping

**_Lowest-price company remaining has higher market value (and loans) than any company can afford to acquire._**

> A&A may be offered for sale for $230

**_Lowest-price company remaining could be acquired._**

> nigelsandwich enters Cash Crisis and owes the bank $338

_President of liquidated company cannot afford debts_

The sequence of messages at 1307 similarly buries important information about the next acquisition.

> H passes taking additional loans

_Acquiring company is done paying for acquisition._

> santouryuu3 settles A&S debts for $118

_Liquidated company passes debts up to president_

> WC is being liquidated, bank offers $0, corporation had $14 and 3 loans

**_Cash and loans of next company to be liquidated are isolated._**

> nigelsandwich cannot bid $10 and is out of the auction for WC
> santouryuu3 cannot bid $10 and is out of the auction for WC

**_Some players cannot afford minimum bid for next company to be liquidated._**

> santouryuu3 enters Cash Crisis and owes the bank $6

_President of liquidated company cannot afford debts_

**Comment by jenf** [comment]
this just relates to the log, and it'd be very awkward to fix
