### ISSUE TITLE
[1817] Missing auto action handling for loan taken

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5861]
![image](https://user-images.githubusercontent.com/2631151/123716516-0b792d80-d87b-11eb-9c8b-ba56443891c7.png)

https://18xx.games/game/41567?action=816

**Comment by perwestling** [comment]
![image](https://user-images.githubusercontent.com/2631151/130359607-5243d3f4-a753-4871-8ffb-2f457964385e.png)

**Comment by magnusrk-ch** [comment]
It was noted on #6357 that taking a loan is definitely shenanigans, but we could make the message less cryptic by adding a custom error message.

E.g. "Disabled programmed action due to #{company} taking a loan"
