### ISSUE TITLE
[1822] Auto Routing does not recognize that L trains can run "within" a station token.

### ISSUE THREAD

**Issue by Arctem** [tobymao/18xx#5862]
Hotseat game: https://gist.github.com/Arctem/b20581f20818bba049d0cae441398b18

**How to Reproduce the Bug?**

- When running trains for 5 (or any other company without a connection to a second city) click "Auto".
- Observe that no route is created.
- Manually select the tile that the L train will run to and observe that the game does allow an L to run within a single city. (you might have to click "Reset" for this to work).

![image](https://user-images.githubusercontent.com/315583/123718299-a77f4680-d833-11eb-867f-149c22fb2192.png)

![image](https://user-images.githubusercontent.com/315583/123718305-abab6400-d833-11eb-8ca0-36f6085a995a.png)

**Which Browser / Platform?**
Chrome 91.0.4472.114
Laptop, Debian variant

**Comment by ChrisTheCat** [comment]
Confirmed. Auto routing works if there is a city + town, but fails on solo city.
