### ISSUE TITLE
[18CZ] Autorouter does not respect rules for running trains.

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#5863]
In 18CZ, a company can only run trains of its same size, even though it can own smaller trains.  The autorouter creates routes for smaller (unrunnable) trains and those trains produce revenue.

For example, see https://18xx.games/game/46491?action=972.
SX is a large corporation, so it can own and run a large train (8E) but can only own (not run) a medium train (5+5i).

But, the autorouter plans routes for both trains:
<img width="1731" alt="Screen Shot 2021-06-28 at 19 27 01 " src="https://user-images.githubusercontent.com/82781561/123719549-76a90c80-d847-11eb-9c18-fa017ffeb3eb.png">

And if I click "Submit", both trains produce revenue:
<img width="778" alt="Screen Shot 2021-06-28 at 19 31 58 " src="https://user-images.githubusercontent.com/82781561/123719619-9a6c5280-d847-11eb-9409-1304cde2cce2.png">

Presumably either the autorouter needs to recognize non-runnable trains or 18CZ needs to be modified to block non-runnable trains in a way the autorouter will respect.

**Comment by benjaminxscott** [comment]
May need to update `runnable_trains` for corps, as that's what the autorouter uses to denote what should run 
e.g. https://github.com/tobymao/18xx/pull/5777
