### ISSUE TITLE
[1817] [Hotseat] Crashed Game,  GameError: Blocking step Acquire Corporations cannot process action 1600

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#5864]
**We're sorry this game cannot be continued due to GameError: Blocking step Acquire Corporations cannot process action 1600
Broken action: { "type": "pass", "entity": 164, "entity_type": "player", "id": 1600, "created_at": 1624941439 }**

I found a broken Blocking Step in the middle of acquisitions. I was either Passing or Paying Off a last Loan (4th of 4) after A&S acquired a corp. 

The Gist: 
https://gist.github.com/yoyoson/00a0aa0f0915f70a5297e713fc7647d6#file-1817-crash-on-payoff-loan-blocking-step-acquire-corporation

To recreate: 

Original game link: https://18xx.games/game/40867
I didn't see this problem yet in this actual multiplayer game; the problem only arose during my Hotseat simulations. 

**How to Reproduce the Bug?**

1. Copy the game data from the gist. 
2. Create a new game 
3. Import a Hotseat Game 
4. Paste the game data, press Create
5. Immediately, I see the error, "_We're sorry this game cannot be continued due to GameError: Blocking step Acquire Corporations..._"

I'm trying to reproduce the error in other ways, and having trouble doing so. e.g. I am trying to back up to a recent point before and replay the same actions again, but that doesn't seem to induce the error. Since I can't Undo from the Crashed game state, I have to either remove the last 1-3 actions from the list of actions (and Create the game like this) or else Review the History to a certain point, and then go into Tools and clone the game from there. But those attempts don't seem to cause the error; It just continues on like there's no problem at all. The only way I've been able to reproduce the issue is to take the above gist data dump (which I can assure you was a direct Copy from the Tools page, unaltered) and Create a new game from it. 

Could it be a file integrity issue? I have 18+GiB  free on the drive that Chrome is running on, so I don't think it ran out of disk space in reaching this point. I haven't combed the data for any other weirdness. 

**Which Browser / Platform?**
- Browser Version
<html>
<body>

Google Chrome | 91.0.4472.114 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Windows 10 OS Version 2009 (Build 19042.1052)
JavaScript | V8 9.1.269.36

</body>
</html>

I reproduced it in Firefox just now as well.

- Platform: **Desktop**

**Comment by jenf** [comment]
There seems to be two 1599 actions
```
    {
      "type": "undo",
      "entity": 3882,
      "entity_type": "player",
      "id": 1599,
      "created_at": 1624941436
    },
    {
      "type": "pass",
      "entity": 164,
      "entity_type": "player",
      "id": 1599,
      "created_at": 1624941439
    }
```
Possibly you tried to do something while an undo was also being processed

**Comment by yoyoson** [comment]
Good call. Thank you for taking a look at this! I think in a server-hosted game, perhaps this sort of "dbl action ID" would be caught by the server and rejected? Thus, this is unlikely to be a serious issue and perhaps this ticket should be closed.

**Comment by tobymao** [comment]
yea should be impossible for this to happen on the server since we have a db lock
