### ISSUE TITLE
[18CZ] missing tile upgrade

### ISSUE THREAD

**Issue by tobtobtob** [tobymao/18xx#5873]
https://18xx.games/game/46605

OFE runs a train to D27 (Frydland & Frydek) on OR3, but on the following stock round (SR4) I can't see the upgrade anymore. I remember upgrading the OO tile to green with OFE, but I cannot see it neither in the log nor in the map.

<img width="627" alt="Näyttökuva 2021-6-30 kello 12 58 29" src="https://user-images.githubusercontent.com/3036759/123941792-2cd53900-d9a3-11eb-8b0e-40795699169d.png">

<img width="393" alt="Näyttökuva 2021-6-30 kello 12 58 43" src="https://user-images.githubusercontent.com/3036759/123941811-32328380-d9a3-11eb-8f99-d40fd8842ad5.png">

I used Chrome on laptop.

**Comment by benjaminxscott** [comment]
Hmm yeah the tile build doesn't exist in the [game actions](https://gist.github.com/benjaminxscott/e636e50dbbb9a8dd7a5ea813410d925b)

If I undo to the route running step locally, it doesn't allow a routes to D27

I'd suggest undoing to the tile laying step and try to lay it / run routes again

![Screenshot 2021-06-30 8 32 18 PM](https://user-images.githubusercontent.com/1711810/124061607-0683bd80-d9e4-11eb-82a4-39bbad14d4e2.png)

**Comment by dfannius** [comment]
This game is archived so I don't know how feasible it is to explore this anymore (also it's 7 months old, so if there is a bug, hopefully there is a more recent example).
