### ISSUE TITLE
[1840] Station hexes included as part of tram line route before station tile laid. Game #46947

### ISSUE THREAD

**Issue by McGill31** [tobymao/18xx#5874]
https://18xx.games/game/46947

The rules require 2 revenue locations for a valid route that generates revenue.

Linie 1 has a "route" from C17 to D18, scoring 30 for the marker on D18 plus zero for C17. 

https://18xx.games/game/46947?action=147

C17 is a purple station hex without a tile laid yet, so it is not a revenue location. Therefore, the route should not be valid, as it only has one revenue location until the station tile is laid.

**Comment by Zwergenpunk** [comment]
Yeah I missed that in the rules. Thanks for reporting

**Comment by scottredracecar** [comment]
I'd suggest to check with Lonny before changing this. Seems 50/50 to me how he might rule it.

**Comment by McGill31** [comment]
If you are going to check with Lonny, then it may also be worth checking if an empty interchange (City tile with no Linie's station marker) is a valid revenue location.

https://18xx.games/game/46947?action=166

This shows Linie 10 claiming a route from G15 (with marker) to F14 (without marker) scoring 20 for G15 and nil for F14. As I read the rules, this should be allowed as F14 is a revenue location even though no revenue can be paid to Linie 1. I base this on the rules saying that a tokened out interchange (with no marker of the Linie running the tram) can be the end of a route but no revenue is scored by the Linie, but Lonny could rule that an interchange without any markers is not a revenue location.

**Comment by Zwergenpunk** [comment]
> If you are going to check with Lonny, then it may also be worth checking if an empty interchange (City tile with no Linie's station marker) is a valid revenue location.
> 
> https://18xx.games/game/46947?action=166
> 
> This shows Linie 10 claiming a route from G15 (with marker) to F14 (without marker) scoring 20 for G15 and nil for F14. As I read the rules, this should be allowed as F14 is a revenue location even though no revenue can be paid to Linie 1. I base this on the rules saying that a tokened out interchange (with no marker of the Linie running the tram) can be the end of a route but no revenue is scored by the Linie, but Lonny could rule that an interchange without any markers is not a revenue location.

I'm prett sure that the implementation is correct, but I'm not 100% sure. It could be possible, but it would be very confusing.
With the purple tile it is a little different since there is nothing on the tile yet.

**Comment by Zwergenpunk** [comment]
I have an answer. The route to the empty purple tile is valid
