### ISSUE TITLE
[1882] NWR private missing ability button

### ISSUE THREAD

**Issue by dmajoraddnine** [tobymao/18xx#5879]
Multiplayer game link: https://18xx.games/game/45905?action=347
JSON data: https://gist.github.com/dmajoraddnine/e6280770b2600e06e47bb7c171b7418b

We noticed during OR 6 that the CNR player couldn't trigger the NWR private ability, even though it appears to be legal to do so. I tried to trigger it in hotseat mode in various different ways but the game doesn't seem to recognize that the CNR corp has the private ability.

<img width="1463" alt="Screen Shot 2021-06-30 at 2 11 10 PM" src="https://user-images.githubusercontent.com/1085461/124024515-4edbb500-d9bd-11eb-8ead-f69adbb9a71f.png">

Produced on Desktop Firefox v89.0.1

**Comment by jenf** [comment]
The problem is the CNR token on D6 which is causing the ability to not show
