### ISSUE TITLE
[1846] Guaranteed C&O, Boomtown, and Little Miami not removing proper number of privates

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#5883]
When using the guarantee option, the game removes the normal number of privates for the 1st edition of the game (none for 5p, 1 each of blue & orange for 4p, 2 of each for 3p) then adds in Boomtown and Little Miami, instead of removing an additional one of each at every player count, then adding in the guaranteed privates. Removal of Corporations appears correct.

**Comment by KevinR1000** [comment]
The problem looks to be in `case group` in `def num_removals` at [line 351](https://github.com/michaeljb/18xx.games/blob/6a17aaeaf2e2c5243016fc4fa2aad9c7f13d1905/lib/engine/game/g_1846/game.rb#L351) of `g_1846/game.rb`. 

At [line 317](https://github.com/michaeljb/18xx.games/blob/6a17aaeaf2e2c5243016fc4fa2aad9c7f13d1905/lib/engine/game/g_1846/game.rb#L317), Boomtown and Little Miami were removed from `group`, and so `group` no longer matches `BLUE_GROUP` or `ORANGE_GROUP`.
