### ISSUE TITLE
Add new "My games" view 

### ISSUE THREAD

**Issue by tomhoward87** [tobymao/18xx#5888]
I would appreciate an alternative view (perhaps linked from the front page) to just view my games, without the list of other games, notes, chat, etc - I often will refresh the front page to see if I have any moves to make and it would be nice not to have to scroll past everything else - presumably would be lighter in terms of resource consumption also?

Thanks

**Comment by benjaminxscott** [comment]
I think what I'd +1 would be a button to "hide chat", and making the yellow "patch notes" text block be dismiss-able with an X in the top right
