### ISSUE TITLE
[1893] Message says ‘wrong number of arguments’

### ISSUE THREAD

**Issue by HelenCheale** [tobymao/18xx#5895]
https://18xx.games/game/48258

**Comment by perwestling** [comment]
@HelenCheale At what action does this error occur? I tried to clone the game as it is right now and buy a train, but it did not fail.

**Comment by HelenCheale** [comment]
Hi it won’t let the other player lay track then buy a train.

**Comment by HelenCheale** [comment]
Hi yes I cloned it too but it won’t let the other player lay track. And if
you skip track lay and buy a train it comes up with that message.

**Comment by perwestling** [comment]
I were not able to reproduce the error, by cloning the game. 

The game shows
![image](https://user-images.githubusercontent.com/2631151/124180234-34d0ce00-dab4-11eb-89b7-1f4552463d7f.png)

So what exact action was chosen next? I can try to reproduce it in non-hotseat mode (there is a slight difference between hot-seat and non-hot-seat.)

**Comment by perwestling** [comment]
@HelenCheale - have you refreshed the page? Sometimes the "old code" might remain?

**Comment by HelenCheale** [comment]
Hi yes I have refreshed. So if you lay a straight track lay it does it then
refreshes and comes up with the message ‘wrong number of arguments’ given 1
expected 0

**Comment by HelenCheale** [comment]
If I pass both track lay and buy trains it skips to the next company but
then refreshes and goes back to the first company

**Comment by perwestling** [comment]
OK, I managed to reproduce it.

**Comment by perwestling** [comment]
Problem fixed, but it is not yet deployed.

**Comment by HelenCheale** [comment]
Thank you very much.

**Comment by perwestling** [comment]
@HelenCheale It should be fixed now - please try again.

**Comment by HelenCheale** [comment]
Hi thank you very much it does seem to be working now.
