### ISSUE TITLE
[1893] Server Error When Laying a Tile

### ISSUE THREAD

**Issue by nigelsandwich** [tobymao/18xx#5901]
Getting an error saying the server is not accepting my action due to the wrong number of arguments when I try to lay a tile which causes a refresh. On Chrome on a PC.

https://18xx.games/game/48120

https://gist.github.com/nigelsandwich/731386977d9a2a48f9e6faab327bf3f2

**Comment by perwestling** [comment]
Thanks, this has been reported in #5895 and will be fixed soon.

**Comment by nigelsandwich** [comment]
Thanks, Per

**Comment by perwestling** [comment]
@nigelsandwich It should be fixed now - please try again.
