### ISSUE TITLE
[1836Jr56] [Game #46207] Cannot lay/skip token due to error: "cannot process action 780"

### ISSUE THREAD

**Issue by kodemaniak** [tobymao/18xx#5906]
Game https://18xx.games/game/46207

I can not lay a token or even skip the whole step. The error says: "Blocking step Run Routes cannot process action 780...". Action 780 seems to be token lay action I'm trying to perform.

**Comment by ventusignis** [comment]
The server code is rounding down 5% dividends while the JS code is correctly rounding up 
(at this moment MESS has 30 (6x5%) in the market and a run of 530)
JS: `"payout"=>{"corporation"=>0, "per_share"=>26.5, "divs_to_corporation"=>159`
Server: `{:payout=>{:corporation=>0, :per_share=>26, :divs_to_corporation=>156,`
