### ISSUE TITLE
18CO president offered illegal stock issue choices during EMR

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5909]
https://18xx.games/game/40783?action=605

The president is offered the opportunity to issue 1, 2, 3, or 4 shares of UP. However, issuing 3 or 4 shares results in an error.

**Comment by ryandriskel** [comment]
If for some reason someone else takes this on:

It is correct that issuing 3 / 4 shares is illegal as 2 shares is enough to buy the 6 train. We need to update the UI to not show options that aren't legal ( 3 / 4 shares in this case ).

**Comment by ryandriskel** [comment]
I know what needs to be done here, but I borked some games with my initial implementation. Attempt two coming soon™
