### ISSUE TITLE
1861 Russian run calculated wrong

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#5910]
https://18xx.games/game/47378

The Russian ran for 170 and should have been 160.  See pictures below:

![AE0D7008-CA68-44C1-AF3A-70315AB34CE4](https://user-images.githubusercontent.com/73318207/124288610-9de52f80-db0e-11eb-82f5-d895da1579b5.png)
![3B1B946E-89A4-4AD9-80FF-9BF927C554CC](https://user-images.githubusercontent.com/73318207/124288616-a0478980-db0e-11eb-9913-cafe55458b57.png)

**Comment by ventusignis** [comment]
Does the RSR have a private that gives it a 10 bonus when running to moscow or a different hex?

**Comment by ventusignis** [comment]
Here's the action when the RSR routes:
https://18xx.games/game/47378?action=522

**Comment by Eludyan** [comment]
Oh it does. I’m an idiot. Sorry and thanks!

**Comment by Eludyan** [comment]
I didn’t see it there the first time I looked… smh. I am closing this.
