### ISSUE TITLE
[1849] Cert limit changed

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#5931]
https://18xx.games/game/44907?action=932

https://gist.github.com/benjaminxscott/9a309beab3a8daed6f376230dc161fbb

Right before this action, the certificate limit was 11 per player. After the SFA Closed, it went to 12 per player. 

I couldn't find anything in the rulebook about the certificate limit changing mid-game, my apologies if this is actually not a bug!
Note that: This game started as a 4p game with all 6 companies (cert limit =11). One player decided to leave upon bankruptcy, dropping it to a 3p game. But this action by itself didn't cause the cert limit to change; it only changed after the SFA closed.

**Comment by benjaminxscott** [comment]
I can repro the bug that the cert limit did not change to 12, as would be expected after the player left
`CERT_LIMIT = { 3 => 12, 4 => 11, 5 => 9 }.freeze`

https://gist.github.com/benjaminxscott/b85678a9d984d1bc31440195e8376a27

**Comment by dfannius** [comment]
I wouldn’t expect the cert limit to change when a player went bankrupt. I don’t see anything about it in the rules, and I think that games that do change the cert limit in that case are usually explicit about it.

**Comment by scottredracecar** [comment]
Yes, I agree with Dan and this seems to come up often enough that the default should be that the certificate limit is locked at game start and then there should be a parameter that allows overrides.

**Comment by benjaminxscott** [comment]
Deferring to Scott, it seems like `3.5.2 - Limit of Stock Holding` has some concept of a cert limit under certain scenarios 
(maybe this logic needs to be more specific to a given scenario?)
http://www.18xx.net/1849/1849r416.htm

**Comment by benjaminxscott** [comment]
To clarify, I think there's a related bug where the cert limit didn't change when a player left, and instead only changed when a company closed 
(maybe the relevant cert-limit dropping code only fires on `company.close!` or something)

**Comment by scottredracecar** [comment]
Yeah, there are game setup scenarios in 1849 where the cert limit is
dependent on players/scenario, but I don't think any 18xx game changes the
certificate limit during the game without explicit rules for that.

The site apparently does some cert limit checks after the game starts that
it shouldn't be doing (unless the rules specify it).
