### ISSUE TITLE
1817: Sort public company bids by value

### ISSUE THREAD

**Issue by jason-johnson** [tobymao/18xx#5934]
As [seen here](https://18xx.games/game/46967?action=125) and [with gist](https://gist.github.com/benjaminxscott/440e4da71fd996b0921333a779cd752f), if a player has a restricted set of bids due to cash+privates the error message does not show the possible bids in order.  In the example given the message says possible bids are $160, $200, $150, etc. but since the message goes away fairly quickly it's easy to miss that the lowest possible bid is $150, not $160.

**Comment by KevinR1000** [comment]
Error message if a bid of $140 is attempted is
<img width="566" alt="Screen Shot 2021-07-05 at 00 44 42 " src="https://user-images.githubusercontent.com/82781561/124423448-c5b0df00-dd2a-11eb-9672-b8e4b64a0b00.png">

The code that generates the error message is in `def add_bid` in `g_1817/step/buy_sell_par_shares.rb`.
I suspect that a `sort` command could be used somewhere just before line 224.
https://github.com/tobymao/18xx/blob/6df839e54a2656e14f1d49d4f8369112dacaa5ea/lib/engine/game/g_1817/step/buy_sell_par_shares.rb#L224
