### ISSUE TITLE
1822+ TAX Haven can't buy a share

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#5937]
https://18xx.games/game/40463

Player "Volker18xx" has the TAX-Haven and bought in Stockround 7 a Share to TAX HAven.
In Stockround 8 the player want to buy a share to Tax haven, but the button is not shown. ("id": 1120, instead of paring the NBR buy a MR-Share)
![grafik](https://user-images.githubusercontent.com/80693707/124455246-a006f280-dd89-11eb-93c3-125f31d6371d.png)

**Comment by KevinR1000** [comment]
Tax Haven can only buy one share (optional rule 11.1.2 is not implemented).

Since Tax Haven bought LYR in SR 7 (https://18xx.games/game/40463?action=978), it cannot buy another share and so is not displayed.

**Comment by benjaminxscott** [comment]
It seems like this is closeable, please reopen if this is in error
