### ISSUE TITLE
[1840] tokens should not block stadtbahn runs. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5938]
While not clearly explained in the rules, this was confirmed by Lonny here: https://boardgamegeek.com/thread/2608364/can-stadtbahn-routes-be-blocked-lines-tokens

**Comment by Zwergenpunk** [comment]
this is currently implemnted that way. Do you have a game where this happenend?

**Comment by philcampeau** [comment]
Early morning reporting, sorry for the incomplete info!

https://18xx.games/game/48100 The last run for V went [07:41]V runs a City train for 150: B10-C9-C7-D6-E7-F6-G5-G3

but there’s no reason why V couldn’t have continued past B10 to A13 and A17.
