### ISSUE TITLE
[18FL] show the add'l token slot in tiles for the city chosen by Terminal Company private

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5940]
It would be nice if the terminal city "additional station slot" was highlighted in some way. I saw this during a game:

https://18xx.games/game/47307?action=191

<img width="405" alt="Screen Shot 2021-07-05 at 6 35 21 AM" src="https://user-images.githubusercontent.com/8732435/124479482-2eb04b00-dd5b-11eb-90e9-032b476fc027.png">

However, when I then looked at the tile roster, it still shows this:

<img width="89" alt="Screen Shot 2021-07-05 at 6 35 53 AM" src="https://user-images.githubusercontent.com/8732435/124479552-412a8480-dd5b-11eb-9754-e7759a41048a.png">

So it looked like there would NOT be a new station slot in Jacksonville, leading me to place the last Plant token somewhere else. If I'd realized that the grey Jacksonville tile would eventually look like this, I would have reserved the token:

<img width="362" alt="Screen Shot 2021-07-05 at 6 37 11 AM" src="https://user-images.githubusercontent.com/8732435/124479764-70d98c80-dd5b-11eb-9dc6-17a1a5607a53.png">

Ideally, the tile roster would be updated so that all the upcoming tiles for that city showed the extra slot. However, that might be impractical, so perhaps the token slot on the map could be highlighted in some way to make it more obvious that a slot was added to the tile?

**Comment by ventusignis** [comment]
The additional (FECR) token already shows a shadow which indicates that it is not indicating a normal slot - 18LA's optional private and 1870's destination tokens also use this behavior. I can poke around and see what other options for different styles on this are

**Comment by ChrisTheCat** [comment]
Wow, I had to zoom way up to see the shadow. Definitely too subtle for my eyes.

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/125616080-b585f325-8a83-46f6-a3ae-c9cb0894a109.png)
The linked PR merged so I'm going to close this issue
