### ISSUE TITLE
18VA - incorrect reseat and priority assign after private auction

### ISSUE THREAD

**Issue by ledvolta** [tobymao/18xx#5948]
After the private auction, as per rule 4.1 {Priority Deal is given to the player who has the most cash. You are correct. After the private auctionbut not after each SR.}, players reseat and priority order is assigned from most to least cash,.

**Comment by benjaminxscott** [comment]
Just to confirm, the bug is that the player order is not correctly set after the private auction?

(I wasn't sure if you're reporting a different bug where it was reordering between stock rounds)

**Comment by ledvolta** [comment]
Correct, just after the private auction.  No further reordering issues as far as I’ve seen so far.
