### ISSUE TITLE
[1840]  GameError: Blocking step Place a Token or Lay Track cannot process action

### ISSUE THREAD

**Issue by bootydharma** [tobymao/18xx#5952]
Link: https://18xx.games/game/46212?action=106

We're sorry this game cannot be continued due to GameError: Blocking step Place a Token or Lay Track cannot process action 107
Broken action: { "type": "run_routes", "entity": "3", "entity_type": "corporation", "id": 107, "created_at": 1624291855, "routes": [ { "train": "O1-0", "connections": [ [ "E17", "E15" ] ], "hexes": [ "E15", "E17" ], "revenue": 50, "revenue_str": "E15-E17" } ] }

**Comment by tobymao** [comment]
dup #5949
