### ISSUE TITLE
[18Mag] Implement automatic stock actions

### ISSUE THREAD

**Issue by tomhoward87** [tobymao/18xx#5960]
Is there a technical/gameplay reason that there is no autopass feature for 18Mag? Thanks

**Comment by Blobbley** [comment]
To add; 18Mag doesn't include some features during which autopass usually turns off. Eg; companies cannot be parred.

The 'weirdness' (ie difference from a normal 18xx) generally applies to the ORs; the SRs are actually very simple - only buying and selling is possible. I think autopass should be included, to be turned off when someone sells or someone buys an insecure company.

Thank you!

**Comment by benjaminxscott** [comment]
This is a deliberate choice by the dev team, no blockers besides implementation requiring a bit of work

PRs welcome

**Comment by scottredracecar** [comment]
I think this will eventually be added
