### ISSUE TITLE
[Auto Action 1828] Programmed buy action allowed player to buy a non existent IPO share

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#5964]
https://18xx.games/game/48104?action=606

Wade had an auto buy order for CPR, but there was nothing left in the IPO. He only had $100 and was somehow able to purchase a ghost IPO share for 67 despite shares costing $101 on the market. The purchased share displayed twice on his player card (once for a real share, once for the mystery) and the share did not pay out in the operating round when tested in hotseat.

**Comment by dfannius** [comment]
Seems like a real bug to me.

**Comment by crericha** [comment]
This may be fixed now by a recent commit. Could somoene verify?

**Comment by crericha** [comment]
dup of #5333 and #5408

**Comment by crericha** [comment]
Closing as this should be fixed. Reopen is still a problem.
