### ISSUE TITLE
[1862] Highlight trains that match company permit

### ISSUE THREAD

**Issue by PilotBob** [tobymao/18xx#5966]
**What's your idea?**

It seems that the train selection is inverted during buy Trains. It makes more sense that the trains a company has a permit for should be highlighted rather than the inverse of this.

**Comment by benjaminxscott** [comment]
Hmm, I personally prefer the way it is based on:
- in other games, no highlighting on a train implies it's fine to buy
- adding highlighting implies a warning when buying, so that's good

Combined, those seem like they work pretty well here, but I'm not the decider just my 2 satoshis

**Comment by jenf** [comment]
Closing as won't do.

**Comment by dfannius** [comment]
My suggestion would be to change the color of the highlight away from yellow, which feels a little more like a good thing than a bad thing. A red/pink sort of color has unfortunately already been taken by the Priority Deal marker, but a gray "highlight" might make it more clear that these trains are a bad idea. Another possibility would be to just gray out the text itself.
