### ISSUE TITLE
[1862] Provide a way to show available companies on map

### ISSUE THREAD

**Issue by PilotBob** [tobymao/18xx#5967]
**What's your idea?**

It would be nice to have some way to hide unavailable companies from the map. Perhaps another button at the bottom or putting an X through the company icon on the map.

**Comment by PilotBob** [comment]
It was pointed out to me there already is a subtle block outline to companies not available, that I didn't notice, or see in the docs. But, a way to hide them would still be nice.

**Comment by roseundy** [comment]
The color of the outline indicates whether it is currently available. There is value to seeing currently unavailable companies for planning purposes, so I'm not inclined to change anything.

**Comment by benjaminxscott** [comment]
Having recently played my first game of 62, perhaps the black outline could be made more apparent?

(white dashed line?) (black dashed line?)
