### ISSUE TITLE
Allow webhook definition per game

### ISSUE THREAD

**Issue by beginetienne** [tobymao/18xx#5968]
Like the Java 18XX Rails project, it would be great to allow defining a webhook per game.  That webhook definition would override the user settings, allowing using a different webhook for specific games.  The webhook configuration would apply to all players in the game.  This can accomplish having different kinds notifications per game, which is preferable for players busy with many games.  This also helps introducing new players to the wonderful world of webhooks, who may not be sufficiently tech savvy to create one, and do not care about having their own discord server.

**Comment by tobymao** [comment]
Why would a webhook configuration apply to all players in the game? If anything it needs to be per user game.
