### ISSUE TITLE
18cz train buy

### ISSUE THREAD

**Issue by serpentium** [tobymao/18xx#5975]
https://18xx.games/game/44292

Cannot choose which type of train to buy with a big company and game let me buy only a E train

**Comment by Zwergenpunk** [comment]
hey no it is actually correct. you have to buy a E train . you cannot take a loan to buy a not runnable train

**Comment by serpentium** [comment]
A company may own smaller trains (for example, with the intention of selling them to another company). Still, each company must own a train it could run for revenue (even if it currently has no revenue-producing route.)

**Comment by benjaminxscott** [comment]
I presume this action?
https://18xx.games/game/44292?action=956

Based on my reading, the current behavior is correct, as during EMR the president can provide funding for one and only one train, and the company must still own a runnable train at the end of its turn

(whether the president must take a loan or pays cash is irrelevant it seems)

```
VIII.10 Purchase of Trains
Each company must own a train [at the end of its turn] that it could run for revenue

VIII.11 Emergency Financing

If a company is forced to buy a train and does not have enough in treasury, then it must do
emergency financing: The Director must make up the deficit from his private cash and/or by taking
a loan.

(ed: this is probably the confusing bit) If different trains are available, then the Director selects which to buy.

The train may be bought only from the bank or the Train Pool, but not from another company.

The Director **may not buy a further train for the company** with his private money or put more
money than needed for that train into the company. The company must not have a single K left
after the purchase.
```
