### ISSUE TITLE
[1893] Support Sell of EVA during Forced Train Purchase

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5979]
In the stock round there is a BuyCompanyFromOtherPlayer function. A similar should be able to implement for selling EVA to other player. This would be a good feature in the case of a Forced Train Purchase.

**Comment by tobymao** [comment]
this can just be accomplished by doing asking someone to buy it from you, i don't think we will implement this

**Comment by perwestling** [comment]
@tobymao No, it wont help, as the active player need to raise enough money to buy a train, and that must be done during their turn. 
So it might be the case that the player goes bankrupt despite having that private that could give enough money to avoid that.

I might give this a try.

**Comment by tobymao** [comment]
why? just don't go bankrupt if they have a private then?

**Comment by perwestling** [comment]
@tobymao What is it worth then? It is something the players will decide among themselves, coming to an agreement. In this situation you might negotiate a train buy. If not possible you might have to sell certificates to raise money, and EVA is one of those certificates. In some titles you might be able to sell privates in this situation but 18xx.games does not allow this.

Checking the rules comparision (http://www.fwtwr.com/18xx/rules_difference_list/single_list.htm#10) it says the following:
"1830, 1830NL, 1834, 1857, 1859, 1868, 1876 v2, 1876-30, 1899, 18JP-T, 18Kaas, 18SS, 18SY Yes, at any agreed price, in the buyer's or seller's turn in a stock round, or during emergency money-raising."
So 1830 should support this as well?

That reference says OR/SR for 1893 selling of EVA, but do not mention EMR. I need to check that out.
F
