### ISSUE TITLE
18CZ add size to company tiles

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#5984]
https://18xx.games/game/48957?action=10

Before a company is purchased, you can derive the size from the income, but it's not actually labeled. After a company is purchased, an S / M / L indicator appears on the player card for that company.

It would be nice if the S / M / L indicator appeared in both places.

<img width="344" alt="Screen Shot 2021-07-09 at 10 50 09 AM" src="https://user-images.githubusercontent.com/8732435/125117760-8b856b80-e0a3-11eb-8d47-e895e4eb39f9.png">

**Comment by benjaminxscott** [comment]
here's some context on the current approach
https://github.com/tobymao/18xx/issues/3867

(personally I'd +1 having this issue to have company size in the name)

**Comment by Zwergenpunk** [comment]
Yeah in the initial Auction it is quite painfull...
