### ISSUE TITLE
1822 - minor starting values/cash info by phase

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#5986]
I think it would be helpful to have the minors reflect the actual value / start price and cash based upon the bid amount during a given phase of the game.  I have noticed confusion for people and having this reflected on the bid chapter would be very helpful.  It could be an added line on the charter or typed info at the beginning of the stock round… something along the lines of “Phase L:  New minors will start with 100 and a value of 50 if started this round for any bid value.” Or “Phase 2: New minors will start with a value half the bid rounded down to the nearest start value and double that in cash. Ie 145 bid will start with a value of 70 and 140 cash”

Sorry if this is a duplicate! I couldn’t find it anywhere. :) 
Jen

**Comment by benjaminxscott** [comment]
Check out the PR

Added to the Info tab since the phase title is more "declarative of what's happening in the phase" than informational afaik

It looks like there's three statuses that minors can be in, so I added those to the relevant phase chart

**Comment by Eludyan** [comment]
I love it, thank you!
Jen
