### ISSUE TITLE
[Harzbahn 1873] New company is not given the option to buy switchers before buying its compulsory train.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5994]
https://gist.github.com/physic/f80d04b07d2561d18e7214bbec002fac
action=409

NWE is operating. It is phase 2. The first 3T is on deck.

Expected:
I may buy S2 switchers before buying the 3T.

Observed:
I cannot do anything until I buy my compulsory train. Because it is a 3T, only S3 switchers are available afterwards. I am unable to buy S2s even though it is phase 2.

**Comment by KlausKiermeier** [comment]
Sorry, but the code is correct here. A company is not allowed to buy switchers before it buys its compulsory train. This is according to the rules. 
Klaus

**Comment by physic** [comment]
Ah! Thanks. I keep learning new things XD
