### ISSUE TITLE
[1846] Reserved tokens go away in gray, should cost 80 to place

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#6003]
https://18xx.games/game/49547?action=210

https://gist.github.com/benjaminxscott/28667b76faa6325983cdc298f0edf696

In this case, the Erie was able to place a token in its reserved D20 hex for 40, however in gray the reservations go away so it should cost 80 (afaik)

Likely the same issue with the other reservations

May pin games

**Comment by philcampeau** [comment]
The implementation is correct.

> **6.53 Reserved City Spots**: The Baltimore & Ohio, Erie, Illinois
> Central, and Pennsylvania railroads have reserved city spots in
> Cincinnati, Erie, Centralia, and Ft. Wayne, respectively (see mats).
> Before phase IV, if the corporation with a reserved city spot is in
> play (and hasn’t closed, see section 8), other corporations may not
> place a token in that spot. A corporation placing a token in a spot
> reserved for it pays $40, not $80 (unless it is using an ability to
> place it without a connection), **_even in phase IV (only the “reser-
> vation” goes away, not the listed price)._**

**Comment by Maxwell-Frank** [comment]
@philcampeau is correct. This came up for me, too, in a game the other day.  The reservations and the token discounts are distinct. The reservations disappear, but the discounted tokens live in perpetuity as long as there is a space remaining to token.
