### ISSUE TITLE
1862 - Parliament Round Priority Deal

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#6004]
If a player acts in the parliament round, it changes where the priority deal marker sits on the players entities cards. During parliament round PD should not change as it reverts back to the original Priority owner at the start of the stock round.

**Comment by roseundy** [comment]
Are you saying that PD moves in such a way that the PD is wrong for the next SR? Or is it only cosmetic?

**Comment by Blobbley** [comment]
Sorry Steve - a terribly written bug report.

it is purely cosmetic. If I’m in the parliament round and deciding on my next move, that is partly based on who will be PD in the SR

**Comment by roseundy** [comment]
Gotcha! No worries about the report, I understand.

**Comment by benjaminxscott** [comment]
Also ran into this cosmetic issue, I was thinking hide the priority deal marker during the parliament round

**Comment by Blobbley** [comment]
Doesn’t really help, as you want to know where it is
