### ISSUE TITLE
1862 different shape for express

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6012]
https://18xx.games/game/49186?action=95

Prior to floating, corporations are freight (hex), local (diamond), or express (circle). After floating, they are all circles, even though they are not express. Perhaps express should have a third shape that isn't the same as floated corporations.

<img width="490" alt="Screen Shot 2021-07-13 at 2 42 27 PM" src="https://user-images.githubusercontent.com/8732435/125529253-216ffff8-da31-48a2-a59b-7dfdef569e56.png">

**Comment by roseundy** [comment]
Well, tokens will always be round. The "marker" shapes were chosen based on the symbols used on my first edition copy of 1862.

**Comment by ChrisTheCat** [comment]
Yeah, suggestion is to use a different shape.

**Comment by benjaminxscott** [comment]
Hmm, I'd +1 the current shape, my reading of it was "it's round like the cities that it can count"

Since the markers are off to the side and not in a city slot, was my heuristic to tell them apart fwiw\

**Comment by ChrisTheCat** [comment]
I argue that having a white ring around the token to show that it is an express and using exactly the same graphic for non-express corporations is a problem. It doesn't seem like it would hurt anything to display expresses as a square, for example. I don't think "circle = express, diamond = local, hex = freight" is required.

**Comment by dfannius** [comment]
Yeah, I thought that circles and hexagons were chosen in the original (hardcopy) game as mnemonics for the way that they score. People who come to 18xx.games from playing in IRL will expect the current shapes, I imagine. I like the current system fine but I wouldn't be heartbroken if it changed.
