### ISSUE TITLE
1849 Ends SR1 while players still have cash

### ISSUE THREAD

**Issue by eaduncan** [tobymao/18xx#6013]
Here is the game ID: 49497. Two players still had enough cash to cross-invest in other companies that parred in the first SR. However, the game indicated they had no valid actions once the last company floated and skipped to OR1. I looked in the rules and in the logs and I don't see any reason why those players could not have bought shares of the two L68 companies.

**Comment by scottredracecar** [comment]
Link to action which is post private companies paying. https://18xx.games/game/49497?action=31

Before then, the players didn’t have enough cash to buy anything so the passes were correct.

**Comment by eaduncan** [comment]
🤦  thanks
