### ISSUE TITLE
18va - payout calculation error

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#6021]
I do not think VA is paying the CMDs correctly (or even consistently). IN 49215, both the VR and the WM ran a 1G with a token in the CMD. Both should have paid $50 and earned a $20 subsidy, Instead, VR paid $50, held $20 and earned $20 subsidy. WM paid $30, held $20 and earned a $20 subsidy.

https://18xx.games/game/49215?action=64

https://18xx.games/game/49215?action=59

**Comment by ventusignis** [comment]
In 49215 WM ran its 1G only from the CMD to a mine, it did not use its home token, hence the dividends of 30, not 50
![image](https://user-images.githubusercontent.com/2993555/125644424-3a46b971-a3f6-47f8-9b06-87e2e676a060.png)
![image](https://user-images.githubusercontent.com/2993555/125644484-a959fffd-a178-42a6-98f4-4e64574b8033.png)

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/125644752-49a8f252-581e-4a79-b20f-95af112300cf.png)

**Comment by Eludyan** [comment]
I’ll tell Bruce! Thanks :)
