### ISSUE TITLE
[1817] - Option for a stack based turn order when buying stocks 

### ISSUE THREAD

**Issue by OliverMatheauRaven** [tobymao/18xx#6037]
**What's your idea?**

In 1817 priority deal is very important. However when mid OR mergers or convertion happens it gets ignore entirely. This can often mean that a few players have a lot more stocks then others solely because they are to the left of a player who converted.

The proposed idea is to instead determine who takes the next stock action by a stack.
E.g. if the stack is 1234, player 1 takes the first action then 2, 3, 4.

The first person in the stack gets the option to buy, if they do they go to the back, if not they retain their place.
In stock rounds it's probably best to have it so every player has an action then the stack is set to the new order.

E.g. if the stack is 1234 and one SR round looks like
1 - sells and/or buys
2 - passes
3 - buys
4 - passes
Then the order for the next round is 2413

In mid round mergers the owner should still get first action but after go down the stack.

I think this would allow players to control and plan for stock round turn order better. Particularly at large player counts. And would make for an interesting option! (And may work in other 18xx titles too)

Thank you for your time and for running this amazing site!

**Are there related ideas?**
Not that I could see!

**Did you join the slack?**
No, sorry I don't know ruby and don't think I could help much sadly.

**Comment by ventusignis** [comment]
Is this the same as #4016 ?
https://github.com/tobymao/18xx/issues/4016

**Comment by OliverMatheauRaven** [comment]
Yes! Sorry I didn't see that before creating
