### ISSUE TITLE
[1862] Two non-permanent freights connected end-to-end, but still gets route error

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#6038]
If the train routes are started at the ends and meet in the middle, the game displays a not connected end-to-end error. See picture for details.

https://18xx.games/game/49020?action=217

![image](https://user-images.githubusercontent.com/67359577/125990053-f67a90c1-14de-48c9-ba22-050d8677bf0b.png)

**Comment by roseundy** [comment]
Simple fix - freight_set caching problem.
