### ISSUE TITLE
Cannot use two different `terrain_discounts` in one corporation

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#6041]
AFAIK this only affects 18USA. If a corporation has multiple companies with `terrain_discount` abilities, only the "first" company's (passive!) ability is usable by the corporation

**Comment by scottredracecar** [comment]
@crericha will this be a part of alpha?

**Comment by crericha** [comment]
@ventusignis, what situation were you thinking of? I haven't come across what spawned this issue.

I did make it so you can lay multiple resources on the same tile (two hexes allow this).

**Comment by crericha** [comment]
Confirmed 18USA has logic to determine the correct discount to use
