### ISSUE TITLE
[18CZ] Medium company runs a 2+2 but game log text says it's a 3c

### ISSUE THREAD

**Issue by vints1** [tobymao/18xx#6042]
https://18xx.games/game/46484?action=368

This appears to not be a rule breaking bug, at least as far as I can tell.  In the game text, it says the player ran one train in a medium company, BN, but it is a train for small companies.  If you go back one step, however, you see the player only had the option to run the 2+2 train and the route is a valid 2+2 route.  For some reason the text logger states the player ran the 3 instead of the 2+2.

**Comment by Jay-Davis** [comment]
This isn't logging bug, this is an AutoRoute bug. If you hit Auto, it will run run trains that a company isn't allowed to run and they will count. I just hit this in another game where a medium company ran both a 3+3 and a 3.

To avoid this the player can't use AutoRoute if the company has a train its not allowed to run.

**Comment by Jay-Davis** [comment]
I created a hotseat game from our game that had this problem. Its right at the point where you can hit auto to see it run the invalid train. Here's the link:
https://gist.github.com/Jay-Davis/65a6d1d0bc96fd71c24508143dc6fec2

**Comment by Zwergenpunk** [comment]
Interesting, since we fixed the issue that the auto router runs the 2+2 AND the 3 train. But somehow the log is wrong...

**Comment by benjaminxscott** [comment]
Perhaps the auto-routing log output doesn't know about `can_operate()` so it erroneously emits the message, even though it's not being auto-routed

**Comment by michaeljb** [comment]
I think this is fixed. The game in the original report is archived, and the shared hotseat one is broken from some other fix.

I cannot repro in this hotseat game where a Medium company has a 2+2 and a 3, and has a better route with the 3 - https://gist.github.com/michaeljb/838b16f8c832efcdd1cb0562f69705cc
