### ISSUE TITLE
'62 share limit change on LNER: change from purchase of H train to immediately before next stock round.

### ISSUE THREAD

**Issue by kfoelsch** [tobymao/18xx#6047]
"The London & North Eastern Railway (LNER) forms at the end of the set of operating rounds following the purchase of the first H train."
(From section 10.3, GMT rules) (edited) 

The share limit change wasn't properly executed in https://18xx.games/game/49991.  Apparently it's currently doing the change at the moment the H train is bought?

**Comment by roseundy** [comment]
Interesting. Obviously, I had misread this rule.

**Comment by roseundy** [comment]
This will cause some games to be pinned.
