### ISSUE TITLE
Some sort of visual indicator when there is no valid track for a hex

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#605]
Right now, as far as I know, if you click on a hex with no valid updates, there is no visual feedback that there is no valid track. The hex could be greyed or reddened or something.

I realize that "lack of tiles" probably implies no tiles, but a) visual feedback is good and b) lately, the tile laying has been a little buggy for me. I'll see if it's a known issue, but regardless, sometimes there are valid tiles, but they appear out of view...in this case, when I click on a tile, I don't know how to differentiate immediately between "you can upgrade the tile you just have to go looking for where they are" (usually far on the bottom left), and "you cannot upgrade this tile".

**Comment by jenf** [comment]
I'd suggest we show them, but have them greyed out with a red border.

An improvement would be to add text over the top explaining why (None left, Invalid)

**Comment by benjaminxscott** [comment]
Perhaps show all possible tiles, with a red X on top of the ones that aren't valid (coloring/border seems like it would be harder to discern, imo)
