### ISSUE TITLE
[18zoo] Allowed to buy fourth "power" despite rules limit

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#6074]
This is an issue where 18xx.games is overly permissive relative to the rules, and (it seems) unintentionally so.

Example:  https://18xx.games/game/50339?action=27

To purchase Hole, I used the "Buy HOLE from The Bank" button at the bottom (above the market chart), and then confirmed that The Bank had agreed to the sale (responding to the warning).
I also see now that it applied the wrong price, using the 1$N from the box there.

I suspect that the "Buy XX from The Bank" buttons at the bottom are unnecessary.  Regardless, those buttons seem to bypass the "three powers" check.

**Comment by carlorusso** [comment]
thanks @KevinR1000 , I'm the developer behind 18ZOO, I'll check this :)

**Comment by carlorusso** [comment]
hi @KevinR1000 , thanks again for this submission :)
I found the problem, I have a working patch, but there is a tournament (https://18xx.tools/tournament/18ZOO/) and I prefer to wait for that before releasing this.
