### ISSUE TITLE
[18CZ] Undefined func `company_sale_price` during EMR

### ISSUE THREAD

**Issue by billbold2** [tobymao/18xx#6078]
I was taking the first turn for ATE after it floated in the prior stock round and the game froze. I exited and tried to re-enter but the game is in perpetual load...
I believe it froze at the buy companies step.

https://18xx.games/game/49352

**Comment by Zwergenpunk** [comment]
Wow that is weird. No clue whats going on

**Comment by benjaminxscott** [comment]
> "undefined method `company_sale_price'

**Comment by Zwergenpunk** [comment]
Never heard of that function 🤷‍♂️

**Comment by benjaminxscott** [comment]
I think the issue is in the EMR step, as `ATE` is thrown into EMR and `company_sale_price()` is not defined in CZ's game.rb

I have a PR

**Comment by Zwergenpunk** [comment]
Ah someone added something to emr to sell companies if I remeber correctly
