### ISSUE TITLE
[1817] - initial auction: user can bid over face value

### ISSUE THREAD

**Issue by jason-johnson** [tobymao/18xx#6092]
Per the official rules, in 1817 you cannot bid over face value for a private in the initial auction.  In fact if your initial bid is face value that is actually an immediate purchase.

Currently the implementation allows an initial bid over face value and it allows bidding to continue once face value has been reached.  This should at least be an optional rule (which is off by default).

**Comment by perwestling** [comment]
I think this is a common way to play 1817, as is 10 instead of 5 shorts. This is how 18USA is played.

So, maybe one could add restrict bid to face value as an optional rule, if anyone thinks it is important to not pay more than face e.g. the Pittsburg private.

**Comment by jason-johnson** [comment]
It may be a common way to play but it's a house rule.  The rules clearly say you cannot bid over face.  The reason it's important is it's a big part of the strategy that if you bid face you can't lose.  It also prevents new players from damaging their bidding power for the initial SR.

Of course some people complain that this gives player 1 too much power because they're guaranteed to get Pittsburg.  It's less clear if this is actually a problem but it's probably the main reason for the house rule about overbidding.

**Comment by tobymao** [comment]
by design

**Comment by perwestling** [comment]
@jason-johnson If you think it is important I suggest you create an issue asking for it to be added as an optional rule, as has been done for 5 shorts optional rule.

**Comment by dfannius** [comment]
I thought that's what this issue was! (See the last sentence in the initial comment.)

**Comment by jason-johnson** [comment]
@dfannius  It could have gone either way, I left it up to others to decide if it's a bug report or a feature request.
