### ISSUE TITLE
[1862] Game cannot be continued due to GameError

### ISSUE THREAD

**Issue by BlackMarmote** [tobymao/18xx#6097]
We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 755
Broken action: { "type": "buy_shares", "entity": 4967, "entity_type": "player", "id": 755, "created_at": 1626943572, "shares": [ "ECR_5" ], "percent": 10 }

https://18xx.games/game/45692?action=754

I do not have other details. It was not me who caused the error

**Comment by benjaminxscott** [comment]
Same issue as https://github.com/tobymao/18xx/issues/6098
