### ISSUE TITLE
[1862] game cannot be continued due to GameError

### ISSUE THREAD

**Issue by BlackMarmote** [tobymao/18xx#6098]
We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 822
Broken action: { "type": "buy_shares", "entity": 1236, "entity_type": "player", "id": 822, "created_at": 1627016083, "shares": [ "EUR_7" ], "percent": 10 }

https://18xx.games/game/47580?action=821

**Comment by benjaminxscott** [comment]
It looks like `Phil` is at cert limit, and cannot buy the EUR share 
(not sure how it got into that state)
