### ISSUE TITLE
[18CZ] Incorrect tile upgrades in Tile manifest

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#6099]
Is these tile upgrades correct? Upgrading to two of these would remove existing exits.

The same question about other tile upgrades.

![image](https://user-images.githubusercontent.com/2631151/126946734-c90eaed7-8574-47fa-9191-ad8ff7870ea1.png)

**Comment by Zwergenpunk** [comment]
Oh that could be true. It could be that the upgrade_check is somewhat simplified since these tiles are somehwat special to upgrade (2 towns -> 1 town)=/

**Comment by perwestling** [comment]
Yes, one need to handle those especially in upgrades_to? and all_potential_upgrades.

E.g the Leverkusen tile in 1893, is an example where 2 towns upgrades to 1 city, and that this upgrade is shown in the tile manifest.

**Comment by benjaminxscott** [comment]
Does this affect upgrades in the game (e.g. can someone break the exits in-game)  or just the tile 'previews' ?

**Comment by Zwergenpunk** [comment]
It does work as expected ingame
![image](https://user-images.githubusercontent.com/7661170/127908776-82a0510b-be79-4f28-bfee-982affedbf7f.png)
