### ISSUE TITLE
1840: incorrect number of new line cards added

### ISSUE THREAD

**Issue by DestrinStorm** [tobymao/18xx#6102]
Game https://18xx.games/game/49000

End of acquisition round 1:
Line 1 was the last line purchased, leaving Line 16 in the pool
After the purchase all companies have a line and we move on to line round.  Lines 10,12,16,2,5 and 7 are now available which means only 5 new lines were added.

According to the rules it should have been 6 (since we're playing a 5 player game)

VIII.7 CRf: New Line Cards Are Put into the Line Card Box
Ÿ As long as any company still has space on its charter for a line card,
new line cards are taken from the stack in box CRf and placed face up
in the large grey box, CRe. Always add one more than the number of
players, regardless of how many line cards are already in box CRe.

**Comment by Zwergenpunk** [comment]
Oh wow. I read that totally wrong. I read that the limit is always players count + 1.
