### ISSUE TITLE
[1860] Game 49016 stuck - Continuing requires converting a private to a share

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#6107]
We are starting Stock Round 8 and I float the BHI&R at $68 per share (note:  the error occurs no matter what par price I choose).  The game seems to credit this properly, and then has 2 buttons, one by Abilities, which allows me to convert the Brading Harbour Company into a share of BHI&R and a "Done (Certificates)" button.  If I click the former, I get the conversion share and the game proceeds normally.  If I click the latter, I get an error in a red bar that says "The server did not accept this action due to:  Illegal action:  Blocking step Sell then Buy Certificates cannot process action 396...refreshing."

Any help will be appreciated.

**Comment by roseundy** [comment]
Hmmm. Yeah, this is related to a change I was asked to make. At least now I have a test case for it :-)

**Comment by roseundy** [comment]
Needed to use a symbol instead of a string. Easy fix.
