### ISSUE TITLE
18Ches C&O Canal (P4 private) can't place free token unless you could already afford it 

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#611]
If I try to place the free token when PRR has $40 in treasury, it works fine. When it has $39 in its treasury, I get an error: "PRR cannot lay token on 57-5-0"

[prr_co_canal_token_cost_check.json.txt](https://github.com/tobymao/18xx/files/4719999/prr_co_canal_token_cost_check.json.txt)

In the above game, you're at C&O corp's buy trains step. Try buying a 2T from PRR for $89, then click through to PRR's Tile Lay step. Then place in D2 (uses P4) and then click to token that city. It gives error. 

Then reload the game and repeat, but this time buy a 2T from PRR for $90, and re-attempt, and this time it should work and there should still be $40 in the PRR treasury.

**Comment by mikelietz** [comment]
I see the same thing in game 1678 when I try to place the token with C&O. After laying the tile it only has $10 left over.
[CO_cant_token_json.txt](https://github.com/tobymao/18xx/files/4720151/CO_cant_token_json.txt)

It receives the same error.
