### ISSUE TITLE
Game won't load after undo.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#6110]
Game 50475 will not load, after undoing to the beginning of the game. Other games with far far more actions load just fine. 

Not sure if it is a perf issue or a hard lock, but I waited a few minutes and the game just sits on loading. Unrecoverable.

Repro:
Load https://18xx.games/game/50475
Game sits on loading screen indefinitely.

**Comment by roseundy** [comment]
It's throwing an error, so no amount of waiting will help.

**Comment by roseundy** [comment]
Last action was 201. Looks like undo was action 202.

**Comment by roseundy** [comment]
I can't reproduce in hotseat.

**Comment by tobymao** [comment]
archived
