### ISSUE TITLE
18Carolinas: Can erroneously run to gray spurs?

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#6114]
![image](https://user-images.githubusercontent.com/2993555/127195217-c5fe1673-402c-4ca1-b18c-a999e91e33f0.png)

The game lets you run to the gray spurs. From my skimming of the rules, it looks like this is not a valid route. I believe the spurs need to be given `offboard=revenue:0,visit_cost:99` so that they cannot be run to by trains

**Comment by scottredracecar** [comment]
👍

**Comment by roseundy** [comment]
Yep, nice catch.

**Comment by roseundy** [comment]
Game id?
