### ISSUE TITLE
[18zoo] Out of place "'Two barrels' is closed" message (minor issue)

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#6116]
Very minor issue, but it confused me (slightly).

See https://18xx.games/game/50338?action=345
TI never owned 'Two barrels', so it seems odd to have a "'Two barrels' is closed" message here.

'Two barrels' was used for the second time at action 338, and so the first "'Two barrels' is closed" message at 339 seems proper.
But the messages at 345 and 352 and 359 seem out of place.

**Comment by carlorusso** [comment]
ok, found the problem, and after applying a patch:
![image](https://user-images.githubusercontent.com/1408567/130483398-6732da6d-5139-4357-a444-2fd65f6a7136.png)
