### ISSUE TITLE
[18Carolinas] Not possible to lay southern gauge after phase 5

### ISSUE THREAD

**Issue by Bastwood** [tobymao/18xx#6124]
It doesn't seem possible to lay any more southern gauge track after phase 5 has been triggered. According to the rules, laying southern gauge should still be an option.

![image](https://user-images.githubusercontent.com/18530616/127304879-6b6dbdc7-1af4-4cef-b701-5f048d693aa6.png)

**Comment by roseundy** [comment]
Either I misinterpreted what Scott told me or the rules need to be clarified.
@scottredracecar

**Comment by roseundy** [comment]
And I read something into the rules that wasn't there. I'll fix to allow laying Southern track in the south after Phase 5 starts. Note that Scott says that laying Southern track in the north is not legal before or after Phase 5.
