### ISSUE TITLE
18VA: 4D not doubling offboards correctly?

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#6128]
https://18xx.games/game/49936?action=678#tools

The 4D should be doubling the offboard right?

**Comment by benjaminxscott** [comment]
Is the VR's 4D being used to hit the offboard?

**Comment by ventusignis** [comment]
That step shows my prior run which doesn't hit the off board, if you go forward one step you'll see the run I used

**Comment by benjaminxscott** [comment]
Ah so if offboard is not not tokened, it should be doubling, and currently it's not

(vs. if it's tokened it'll be 4X)
