### ISSUE TITLE
[1840] Routes not extending through open cities.

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#6135]
Game 51215 - Company 1 ran and removed the State token in hex C9.  Per the rules, this should allow me to continue a route through that city (which wouldn't score revenue) to the halts beyond to the west.  However, as you can see in the attached image, it would not allow this.

![image](https://user-images.githubusercontent.com/88008968/127434172-04d21d73-7359-4956-b4a7-d3e0fc69a3d7.png)

**Comment by Zwergenpunk** [comment]
I think the graph gets not updated when a token is removed.
Could be "fixable" in game by reloading or doing one step and then undo.
