### ISSUE TITLE
[18SJ] Auto purchase of 2 trains at start of OR1

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#6142]
https://18xx.games/game/51220

At the start of OR1, KHJ automatically requisitions a 2T as soon as it's done paying dividends (in addition to the one it has and contrary to rules) and then the first operating company automatically requisitions two 2T as soon as one hits "skip token."

**Comment by perwestling** [comment]
This has been corrected but not yet deployed. 

Avoid doing any more actions so game wont be broken when the correction is installed in the server.

**Comment by perwestling** [comment]
@luigicoolGH Now it has been deployed. I will close this issue, and if you encounter any problems you can create a new ticket.
