### ISSUE TITLE
Remove ability to delete games that are started

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#615]
Users aren't notified in the admin deletes a game

**Comment by jcoveney** [comment]
+1, would be very nice. Alternately, there could be a separate section in the user profile for games that were deleted by the admin

**Comment by tobymao** [comment]
there's no record of a game anymore after it's deleted

**Comment by jcoveney** [comment]
That's not something etched in stone. You could create a record. It's not
like people's past games is precious personal information. An email is fine
though.

**Comment by jenf** [comment]
I'd argue we should mark games as to be deleted then remove them after 24 hours, unless Toby deletes them of course. I'd propose doing this as an action like end game, then other players could undo. Then we have a task on the background that'll purge games where the last action is delete.

**Comment by tobymao** [comment]
I'm considering not allowing deleting games, and just changing delete to
end game, thoughts?

**Comment by jenf** [comment]
Only flaw with that is games that have not yet started and will never start for whatever reason.

**Comment by tobymao** [comment]
we can leave deleting for games that haven't started.

**Comment by jenf** [comment]
Sounds good to me 👍
