### ISSUE TITLE
[18Ireland] Companies can run through tokened-out Belfast

### ISSUE THREAD

**Issue by PJBarns** [tobymao/18xx#6157]
https://18xx.games/game/50876?action=1432

It looks like companies can run through Belfast, if that tile is tokened out, when specifically running through the H8 tile twice. In the pasted game:
- Belfast has been tokened by the CBSCR and the MRNCC
- The GSWR during its operating turn is able to run a diesel train through Belfast when using the southwestern and southern pieces of track
- The run is counted as legal, and paid out accordingly

This was replicated by other companies, but not used in the game. Using the GNRI I tried to enter through the northwest entrance and exit through the south but was notified that the route was not connected. 

Playing around in hot-seat mode, it might depend on the gray plain-tile tracks. See following screen-shots:
<img width="2034" alt="Screen Shot 2021-08-01 at 1 18 36 PM" src="https://user-images.githubusercontent.com/76886977/127779902-0409323a-dda3-4aa7-9b1e-794ded5f4771.png">

<img width="2030" alt="Screen Shot 2021-08-01 at 1 18 54 PM" src="https://user-images.githubusercontent.com/76886977/127779910-2429eb40-1e83-412f-96ab-9b0060856466.png">

In the first, by passing through H8 twice the GNRI can legally run through Belfast to the I9 city. In the second, by going directly from Belfast to I9 the route is considered not connected.

Further, when I run through Belfast and stop short of crossing H8, the route is illegal:
<img width="2031" alt="Screen Shot 2021-08-01 at 1 32 05 PM" src="https://user-images.githubusercontent.com/76886977/127780205-47e933bc-9a03-47d7-99e5-4ac843a6c7ba.png">
but if I continue and connect to another stop through H8 it is deemed legal:
<img width="2031" alt="Screen Shot 2021-08-01 at 1 32 11 PM" src="https://user-images.githubusercontent.com/76886977/127780255-e828df89-cbb4-47c1-8fa4-720207000e88.png">

At first we thought it was specific to the southwest and south entrances, but I am able to get a legal route using the northwest and south track:
<img width="2032" alt="Screen Shot 2021-08-01 at 1 36 33 PM" src="https://user-images.githubusercontent.com/76886977/127780315-56e35fb7-e1fb-45b5-90c1-52d7076cd5f3.png">

I'm running the game on Safari, but we've been playing in Chrome and on phones too, so I'm not sure if it is a browser issue.

**Comment by dfannius** [comment]
This is a fantastic bug report and I regret that it wasn't looked at before the game was archived and made inaccessible. Hopefully the pictures will help to reproduce it with the current codebase.

**Comment by dfannius** [comment]
Thanks to the detail in the report, I was easily able to reproduce the bug with the current version of the codebase: https://gist.github.com/dfannius/1a0cc5e1ea9602f0669499b2f6a10943

**Comment by dfannius** [comment]
This is actually a general bug with Lawson track, not specific to 18Ireland; I was just able to duplicate it in 1817. The code to check whether a route is traversable checks that each path segment can be reached from the token, not that the route itself doesn't pass through a tokened-out city.
