### ISSUE TITLE
[18CZ] Not all train names have phase attached

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#6161]
Here's the current train table:

![image](https://user-images.githubusercontent.com/1295244/127854275-21583f2c-59c4-4f6c-a011-eb29c09e853d.png)

All train names have their corresponding phase (a through j) as a suffix except for 5E, 6E, and 8E, which for consistency should be 5Eh, 6Ei, and 8Ej respectively.

**Comment by Zwergenpunk** [comment]
I really don't think that is needed since the phase is only there because some trains are available in multiple phases. why add the phases when they are only available in one phase.

**Comment by dfannius** [comment]
I agree that it is not strictly necessary, but I think it is a nice thing to have for consistency. The other 23 trains have that information. I would rather have the train name be consistently "train type with a phase suffix" rather than "train type with a phase suffix only if the phase is not deducible from the train type".

**Comment by Zwergenpunk** [comment]
yeah there is not much i can argue against ;) I'm just so used to the not postfixed trains^^
