### ISSUE TITLE
[18Carolinas] able to upgrade a city when tiles aren’t available

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#6164]
https://18xx.games/game/51061?action=438

Tile E9 Rock Hill is able to upgrade to a narrow gauge K-shaped city, even though the tiles are unavailable and it’s already a broad gauge city at the moment. 

![610DAA2E-80C1-4E8C-BE94-C29A48D8BC14](https://user-images.githubusercontent.com/26125362/127891528-2f4a424a-29f5-47bf-9bca-9170619890ef.jpeg)
![390E7C1C-3183-4E82-AD82-D25885C527B2](https://user-images.githubusercontent.com/26125362/127891531-957712f2-38b9-4e45-9e86-3c63a07b2434.jpeg)

issue is occurring both on desktop and mobile.

**Comment by roseundy** [comment]
It looks like there are two separate bugs here:
1. There aren't any Southern "K"s left, but it offering it
2. It is illegal to upgrade from standard to Southern track

**Comment by roseundy** [comment]
1. Caused by track conversion not playing nice with double-sided tiles.
