### ISSUE TITLE
[18Carolinas] Game cannot be continued

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#6168]
(https://18xx.games/game/51206?action=0

Entered the game and get the listed error message: We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Certificates cannot process action 1
Broken action: { "type": "buy_shares", "entity": 100, "entity_type": "player", "id": 1, "created_at": 1627568553, "shares": [ "CAR_1" ], "percent": 10 }

Unsure if it is a browser issue but just in case: Windows/ Firefox 90.0.2 (64-bit)

**Comment by roseundy** [comment]
The 5 and 6 player rules were recently changed. This game should have been archived :-(

**Comment by KillerOrca** [comment]
That's fine that this issue is closed, but can someone manually archive the game. I am unable to end the game using the tools section.

**Comment by roseundy** [comment]
@tobymao ?
