### ISSUE TITLE
[1822] LP and Mail Contract

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#6171]
Hotseat clone of game: https://gist.github.com/Auzzy/70ceb6c3383e13f3cc5bf895b93b6379

I'm trying to get clarification on how the LP and Mail Contract interact. The site gives an LP nothing for the Mail Contract, but the rules are unclear on whether that's right, and a BGG search didn't give an authoritative answer. My sense is that it should get half of its run (and the commenters on BGG agree), but the rules also leave open the interpretation of it getting nothing. Could we contact the developer for clarification?

**Comment by tobymao** [comment]
i don't think this is an issue with 18xx.games, maybe post this on bgg?
