### ISSUE TITLE
Indicate when a trainbuy is mandatory in the UI

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#6173]
Add some help text to indicate (when trainless):
Corporation is not obligated to own a train
Corporation is obligated to own a train

-----
As far as I can tell from the rules, in a forced train buy scenario, you are never forced to buy a train from another company. However, it appears that if that other company is the CGR, it is forcing a company to buy the CGR's train, which is incorrect.

I created a hotseat game saved at the exact spot where a company is forced to buy a train and their only allowable option appears to be buying the train from the CGR. Here is a copy of that game: https://gist.github.com/Jay-Davis/f0136029338030b4dd29740d321d2859

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/128116508-813f83d9-8d05-4a2f-8703-e771b2051152.png)
In this case the BBG doesn't have a valid route so it has no obligation to buy a train and Player 2 here is not allowed to contribute personal funds to buy a Diesel for the BBG

**Comment by ventusignis** [comment]
![image](https://user-images.githubusercontent.com/2993555/128116701-1f63c7ba-2647-4629-ae44-d0f4b78d9a99.png)
I redid the BBG's turn to connect to the double-dit tile and it was able to buy a Diesel from the bank using president's cash

**Comment by Jay-Davis** [comment]
Yup, sorry, missed that. Stupid :(

To quote a phrase...."Never mind"

**Comment by ventusignis** [comment]
Don't worry about it, I got tripped up by the same thing myself many times before

**Comment by crericha** [comment]
Doesn't it say "must buy a train" when mandatory?

**Comment by Jay-Davis** [comment]
Yes, it does. This is simply one of those cases where, if you are thinking it is mandatory (falsely), you are not noticing the fact that the message isn't there. So it would just be nice if, when a company has no train at all, at least the error would indicate that you don't have enough money and its not forced to have a train, so its obvious what is going on.
