### ISSUE TITLE
Some 18CO games stuck loading

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#6180]
Trying to open some 18CO games hangs at "Loading game..." The browser console shows "undefined method `num_shares' for nil". This has been reported in games 49971, 50483, 51266, although some other in progress games seem to be working fine, so I'm unsure what the trigger is.

**Comment by tobymao** [comment]
@ryandriskel did something change here?

**Comment by Auzzy** [comment]
Note that we first noticed it shortly after the fixes for CZ were deployed this morning, just before noon Eastern.

**Comment by tobymao** [comment]
it was caused by this

https://github.com/tobymao/18xx/commit/643b804bc1fbd924aea8e674c9f3285180d9e0a4

**Comment by tobymao** [comment]
reverted
