### ISSUE TITLE
[1893] stuck at payout of DE in OR3.2

### ISSUE THREAD

**Issue by amartinsola** [tobymao/18xx#6185]
When paying out dividends, the player owing DE raised the following issue:

[15:55]ilikebutta: I am stuck. Once I select pay out it goes into the HGK merger, but says "The server did not accept this action due to: private method 'move_share' called for <Engine::SharePool>:Engine::SharePool... refreshing"
[15:56]ilikebutta: then it goes back to the pay out/withhold.

https://18xx.games/game/51275

**Comment by amartinsola** [comment]
@perwestling @tobymao this issue appears to be closed. However, the game continues to be broken. Does this mean that the issue is fixed for future 1893 games but we have to manually end this one? Thanks.

**Comment by perwestling** [comment]
@amartinsola The correction has not yet been deployed, ie not yet made available for every player.
When it is deployed I believe the game should be able to continue.
I will ping you when it is deployed.

**Comment by amartinsola** [comment]
Ok, thanks a lot.

**Comment by perwestling** [comment]
@amartinsola Now the fix has been deployed. Please try again.

**Comment by amartinsola** [comment]
@perwestling now it works. Thanks a lot.
