### ISSUE TITLE
18VA: Cannot buy more than one 6T in one OR

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#6188]
It's hard to do but legal. The current implementation forbids it

**Comment by perwestling** [comment]
Did you find this via code review, or via a game play? In the latter case do you have a game to attach?

**Comment by ventusignis** [comment]
I found this a month or so ago by reviewing the rules as and comparing it to how I implemented 18VA. I've copied the corresponding section of rules below. Rereading it now I think it boils down to what does "this rule" in "this rule is no longer in effect" refer to - buying trains in order in the stack, or the entire section?

```
Trains are purchased from the Bank in the order they appear at the top of the train stack. At the beginning of the game, the next 
train available is a 2/1G train. When a corporation buys a new train, it must purchase the topmost train in the train stack. No 
more than one train of the current train may be bought from the Bank in an Operating Round: if there are additional trains 
remaining of the current type, the Corporation may not buy any additional trains from the Bank until the next Operating Round. 
However, if the next train available from the Bank is of a new type, the Corporation may buy that train also. Thus, a Corporation 
may buy at most two trains from the Bank in an Operating Round: the last train of the current type and the first train of the next 
type. Other than the Train Limit, there are no restrictions on buying trains from the Poor or from other Corporations.

Once the first 6/5G train as been bought, this rule is no longer in effect: 4D trains become immediately available 
(concurrently with the second 6/5G train). Thus - in theory - a Corporation could purchase the last 5/4G, the first 6/5G, and the first 4D.
```

**Comment by perwestling** [comment]
I have not looked into 18VA so better remove my asignment.

**Comment by dfannius** [comment]
My interpretation of this text:
> Once the first 6/5G train as been bought, this rule is no longer in effect: 4D trains become immediately available (concurrently with the second 6/5G train).

is that it refers only to the "only purchase from the top" rule, given that the text after the colon explicitly says how the rule changes, and doesn't mention anything else. I'm okay with leaving the issue around until there's a ruling, but I don't think it should get the bug label.

**Comment by philcampeau** [comment]
I'm inclined to agree with dfannius. 

> Once the first 6/5G train as been bought, this rule is no longer in effect: 4D trains become immediately available (concurrently with the second 6/5G train).

The clarification after the colon is only needed to explain that you could buy the first 4D while skipping the second 6/5G. You're always able to buy trains of different ranks from the bank.

**Comment by philcampeau** [comment]
Unless we get confirmation from the designer/publisher that that the current implementation is incorrect, I think we can close this bug for now.
