### ISSUE TITLE
[1860] Typo in flipping tokens

### ISSUE THREAD

**Issue by brenthenson** [tobymao/18xx#6200]
https://github.com/tobymao/18xx/blob/69e40cb90875d57e79fc1eef12b16d5096554fe9/lib/engine/game/g_1860/game.rb#L1556

Currently breaking a few of my games of 1860 : )

e.g. https://18xx.games/game/43479

@roseundy

**Comment by roseundy** [comment]
Well crap. I thought I had testing this.

**Comment by roseundy** [comment]
At least I have a test-case now.
