### ISSUE TITLE
[1840] Missing part of CRe

### ISSUE THREAD

**Issue by DerekLong101** [tobymao/18xx#6206]
The rules are explicit in stating that all companies have a chance to buy/reorganise trams *after* the auction of lines, even if they did not participate in the auction of any lines. This is missing in the current implementation, so if a company waits to see whether a later company buys a new generation tram, then they can be left unable to either buy a new tram after tbe line auctions or reorganise their trams.

**Comment by Zwergenpunk** [comment]
Oh that should be in the implementation.
All player who did not buy a tram have an buy/reorder phase at the end. 
Maybe it somehow got deleted by some refactorings =(

Do you have a game where that happened?

**Comment by DerekLong101** [comment]
@Zwergenpunk: https://18xx.games/game/52694 company round 4 is a game where this happened. I have not checked whether it is now fixed (the game was played 2 days ago, so it would have to be a recent change). I just reloaded the game and the history played through without complaint, so I suspect it might not be updated. I will try to make time to rerun the history to the point where the first purple is bought in the closing stage of CR4 and see whether it has now got a chance for the other companies to buy/reassign trams.

**Comment by Zwergenpunk** [comment]
in action https://18xx.games/game/52694?action=395 there is a buy train step after the pass. everything seems to work in my tests and in your game. If you still see a problem please comment again.

**Comment by DerekLong101** [comment]
The company that got the chance to reassign trains was the one that had just bought them. The problem is that the other two companies got no chance to respond to the purchase by buying and reassigning, which they should have. Sent from my Galaxy
-------- Original message --------From: Michael ***@***.***> Date: 23/08/2021  20:53  (GMT+00:00) To: tobymao/18xx ***@***.***> Cc: DerekLong101 ***@***.***>, Author ***@***.***> Subject: Re: [tobymao/18xx] [1840] Missing part of CRe (#6206) 
in action https://18xx.games/game/52694?action=395 there is a buy train step after the pass. everything seems to work in my tests and in your game. If you still see a problem please comment again.

**Comment by Zwergenpunk** [comment]
oh wow now I understand. I think you're right and this is a bug.

**Comment by Zwergenpunk** [comment]
I cannot reproduce it. This should work correctly =/
