### ISSUE TITLE
[1846 2p Variant] Treasury not being reduced when B&O tries to buy out Michigan southern

### ISSUE THREAD

**Issue by ericsmonte** [tobymao/18xx#6209]
Game ID: 51259

https://18xx.games/game/52760

What steps cause the unexpected behavior?

- attempted to buy MS private with B&O. 
- I actually tried to change up the order, before issuing shares, after, during buy trains step, etc. 

Mobile safari version iOS 14.7.1

**Comment by Maxwell-Frank** [comment]
MS has $60 in the treasury which the B&O receives after it buys it from you for $60.  So the treasury is reduced by $60 and then immediately gets that $60 back.

**Comment by ericsmonte** [comment]
I’m really stupid, sorry! Was running MS with steamboat which I haven’t
done in a while.
