### ISSUE TITLE
18Carolinas - Cannot upgrade double dot

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6216]
~~Hex E7 should be able to upgrade to tile 87s, but cannot
https://18xx.games/game/52901?action=132~~

New updates:

- Change A23 spike to dual gauge
- Add 1825 bankruptcy rule
- No beginning or ending train runs on dits
- Add 1825's tile upgrade paths, for example tile 3 can upgrade to 12/14/15/87/88
- Trains can't run both dits on a hex
- Change all towns to 10 value
- Sell-buy-sell
- Map Changes: F20 city, E21 town named New Bern, C21 town, D12 plain hex (remove Concord name), C11 town, delete hex A19, remove spike "1" on I17
- (maybe renumber the "n" tiles "1n" to 1, or do that later)

**Comment by roseundy** [comment]
I missed this in your upgrade chart.
