### ISSUE TITLE
Game 16204 opens to a blank white page.

### ISSUE THREAD

**Issue by OzLocutus** [tobymao/18xx#6222]
**How to Reproduce the Problem?**

Open Game 16204 (https://18xx.games/game/16204). Game screen opens as blank white page

If we've been playing it too long and it's a not supported version, then happy for the game to be deleted (though we were almost finished! 2 ORs to go!)

What steps cause the unexpected behavior?

None that we're aware of, other than noting the game has been going for months.

Please include screenshots (you can drag and drop or upload them into this issue)

![Capture](https://user-images.githubusercontent.com/69135822/129461347-d467fde2-0f71-4df2-a591-68c040cb6e8f.PNG)

**Which Browser / Platform?**

Happening on all browsers and platforms

**Comment by tobymao** [comment]
archived
