### ISSUE TITLE
Chat should have a delete function

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#6224]
Given the public nature of all the games (and the main-page chat), it's problematic that there appears to be no way to delete or edit chat messages.  Given that people may inadvertently disclose personal information or otherwise send chat that they wish to recall, this is problematic.  (And may be illegal in the EU?)

Suggested fix would be a pop-up like in the log popping up a delete/edit function.  Given that the chat doesn't interact with the game, there shouldn't be a technical problem with editing chat.

**Comment by tobymao** [comment]
for now just file an issue here for the chat to be deleted or message me on slack
