### ISSUE TITLE
[1817] In merger round, "Show corps from other players" button does not appear if the current player has none.

### ISSUE THREAD

**Issue by imcgeoch** [tobymao/18xx#6229]
Steps to replicate:
- As a player, own only one corporation during merger round

Expected behavior:
- The "show corporations from other players" button is present, allowing the player to initiate a merger with another player's corporation.

Actual behavior:
- The button is not present.

**Comment by tobymao** [comment]
link to a game please

**Comment by imcgeoch** [comment]
https://18xx.games/game/50588

**Comment by tobymao** [comment]
https://18xx.games/game/50588?action=477

**Comment by imcgeoch** [comment]
A hotseat game showing the same behavior, with an unaffected player for comparison.
https://pastebin.com/cDSUmnuJ

**Comment by Maxwell-Frank** [comment]
@imcgeoch You cannot legally merge your company since you cannot afford the second share required to create the presidency.
