### ISSUE TITLE
18Carolinas - upgrades not shown

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6231]
Upgrading from southern gauge to standard gauge doesn't work on some tiles. All of the following upgrades should be allowed (plus their "normal" upgrade paths). Some of these upgrades are phase dependent.

          # yellow plain track to green plain track
          '7s' => %w[26 27 28 29],
          '8s' => %w[16 19 23 24 25 28 29],
          '9s' => %w[19 20 23 24 26 27],
          # yellow double-dit to green single-dit or K or X city
          '1' => %w[14 88],
          '1s' => %w[14s 88s 14 88],
          '2' => %w[15 87],
          '2s' => %w[15s 87s 15 87],
          '55' => %w[14 88],
          '55s' => %w[14s 88s 14 88],
          '56' => %w[15 87],
          '56s' => %w[15s 87s 15 87],
          # yellow single-dit to green city
          '3' => %w[12 14 15],
          '3s' => %w[12s 14s 15s 12 14 15],
          '4' => %w[14 15],
          '4s' => %w[14s 15s 14 15],
          '58' => %w[12 13 14 15],
          '58s' => %w[12s 13s 14s 15s 12 13 14 15],
          # yellow city to green city
          '5s' => %w[12s 14s 15s 12 14 15],
          '6s' => %w[12s 13s 14s 15s 12 13 14 15],
          '57s' => %w[14s 15s 14 15],
          # green city to brown city
          '12s' => %w[38],
          '13s' => %w[38],

**Comment by scottredracecar** [comment]
There is a gameplay part of this request besides the tile manifest update (which is the more substantive part of the issue).

In this action, the following upgrades should also be allowed for upgrading hex J10. 
https://18xx.games/hotseat/hs_tdnxrgnd_53440?action=226

Map currently shows:
![image](https://user-images.githubusercontent.com/29106780/130322949-352ef499-1bce-4c6c-8fc4-6e5a726f156b.png)

Tiles currently shows:
![image](https://user-images.githubusercontent.com/29106780/130322981-0b1a2b17-ee8e-4abc-b13b-6bb863d40033.png)

I think these agree with each other (good), but are both missing the upgrade to the standard gauge tile, namely 12 and 15 are allowed to be placed here as well (and all the standard gauge large station upgrades should show up on the interface (except not 13 for this tile)

**Comment by roseundy** [comment]
Yes, this should have been fixed too.

**Comment by roseundy** [comment]
Can you create a gist of this case? I no long have any valid Carolinas games that extend into Phase 6.

**Comment by roseundy** [comment]
NVM. I created my own.  It works:
![Camden](https://user-images.githubusercontent.com/8494213/130324003-876f39a2-a735-4888-86ab-60f6188b9495.png)

**Comment by scottredracecar** [comment]
Sorry, my link was supposed to be this, not the hotseat. I think it doesn't work in this action, although it does look like it works in your screenshot.
https://18xx.games/game/53440?action=226

**Comment by scottredracecar** [comment]
Okay, this is deployed now and I confirm it works properly in the case I suggested. Thanks!
