### ISSUE TITLE
1862 incorrect freight revenue

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6234]
https://18xx.games/game/52338?action=475

Revenue should be 200 + 20 + 20 + 60 = 300, not 280 as shown.

<img width="656" alt="Screen Shot 2021-08-17 at 8 53 29 PM" src="https://user-images.githubusercontent.com/8732435/129834503-10abec74-2b5b-4676-96ae-913dff622015.png">

**Comment by roseundy** [comment]
My algorithm for dealing with an offboard end of a freight route has an error. It's using the last **node** (town/city) before the offboard for doing calculations rather than the last **hex**. Plain track is a rarity in 1862 which is why I never found this before.
