### ISSUE TITLE
[1893Cologne] Game is broken and cannot be continued

### ISSUE THREAD

**Issue by basselhak** [tobymao/18xx#6235]
Description: 

Game reverted to SR1 right as we entered SR6. Seems like all moves beyond SR1 were lost. Provided following error message.

Error message: 

We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 14
Broken action: { "type": "pass", "entity": 1411, "entity_type": "player", "id": 14, "created_at": 1628062946 }

Link to the game: https://18xx.games/game/51692?action=13

Browser: Chrome
OS: Windows 10

**Comment by perwestling** [comment]
Sorry about that. A correction, about player order, did break 1893 games so the existing ones need to be pinned, so that they can complete. Will see if we can fix that today.
