### ISSUE TITLE
-[1849] 20% certificate lost when becoming President 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#6238]
https://18xx.games/game/52816

I had bought the last 20% certificate in RCS, taking over the presidency. When mkkohls sold his shares the last certificate ended up in the market somehow?

**Comment by dfannius** [comment]
From rules section 9.5:

> When changing control of a president’s certificate, if the incoming president has the “last certificate,” the outgoing president may choose whether to exchange the president’s certificate for the “last certificate,” or for two single shares owned by the incoming president. The exchange must be for the “last certificate” if the incoming president does not have two single share certificates to exchange for the president’s certificate.

mkkohls chose to take your last certificate, as indicated in the log:

```
[12:20] Presidency swapped for last cert by default. mkkohls may choose to swap for two 10% shares instead.
[12:46] mkkohls chooses the 20% last certificate
```

Then when mkkohls sold 4 shares, 2 of those shares were the last certificate.

**Comment by BellmakerSA** [comment]
Okay my apologies, never saw that happen before and I missed it in the rules.
