### ISSUE TITLE
1822: Major Train limit not enforced when first 5-train is exported

### ISSUE THREAD

**Issue by outsidePasser** [tobymao/18xx#6239]
Game:  https://18xx.games/game/50845

The first 5-train was exported due to a minor being removed from the game.  This should cause the train limit for majors to go to 2. 
 The LNWR should be forced to remove one of its trains.

**Comment by outsidePasser** [comment]
Follow up:  After the first minor started running (skipped buying in companies), the game then realized that the LNWR had to discard a train.  So it does do the right thing, but the timing is slightly off.

**Comment by magnusfalt** [comment]
This will most likley not be fixed. It works but as you said timing is slightly off.
