### ISSUE TITLE
18Texas Should not allow sales of a company that has not completed an operation

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6243]
But this action allows it
https://18xx.games/game/53523?action=271

**Comment by benjaminxscott** [comment]
Could you clarify action 271 allowing a sale ? It looks like that's in an OR

It looks like `SELL_AFTER = :operate`, I tested that you can't sell a company during a stock round that hasn't operated but perhaps there's another bug I'm missing

**Comment by scottredracecar** [comment]
Thanks for reminding me about this. I think the commit from yesterday unintentionally fixed this as well with no further change needed.
https://github.com/tobymao/18xx/pull/6246/commits
