### ISSUE TITLE
[1840] Missing W line station on I11 (Wien)

### ISSUE THREAD

**Issue by McGill31** [tobymao/18xx#6255]
Hex I11 (Wien) should have a halt for the W Stadtbahn line in addition to the tramline halt and the G Stadtbahn terminus.

It appears that the W line's halt should have the same 30 value as the G line's terminus (the physical map has a single orange 30 value next to the two Stadtbahn stations and a white 10 value next to the tramline halt). This is my interpretation of the station value on the physical map but it may be worth double checking with Lonny.

**Comment by Zwergenpunk** [comment]
Duplicate

**Comment by McGill31** [comment]
Out of interest, which is this a duplicate of. There was another issue regarding the same hex, but it was a different issue. I couldn't find the same issue in another report.

**Comment by Zwergenpunk** [comment]
Its the same issue you mentioned. It is just not as clear as your issue.

Am 22. August 2021 21:31:47 schrieb McGill31 ***@***.***>:
