### ISSUE TITLE
Cert count wrong

### ISSUE THREAD

**Issue by srlindemann** [tobymao/18xx#626]
This is for https://www.18xx.games/game/1718

![image](https://user-images.githubusercontent.com/3675501/83786380-9d0a7180-a660-11ea-9eea-c6ccf8f8df56.png)

**Comment by srlindemann** [comment]
Currently in 5.2. My cert count seems right, but both mctwerk and malayet2 are off.

**Comment by jenf** [comment]
SR is in the yellow
malayet2 has 2 shares not in the yellow
mctwerk 7 not in the yellow, 1 in the yellow

 Shares of companies in the yellow spaces on the stock
market do not count toward the certificate limit

correct behavior

**Comment by srlindemann** [comment]
Doh! Of course. Thanks!
