### ISSUE TITLE
[1846 2p] mode creates extra empty token spots.

### ISSUE THREAD

**Issue by myNameIsFourteen** [tobymao/18xx#6262]
https://18xx.games/game/54085?action=266

The yellow tile laid in Cleveland should have just 1 spot for a token - if NYC had been removed it would have 2 spots, one filled by an NYC token.

**How to Reproduce the Bug?**

Playing 1846 2 player variant, with NYC not removed from the game
Laid a gentle turn Z city in cleveland (tile #292)
Observe that a second token spot is present - it should not be.
![image](https://user-images.githubusercontent.com/3456680/130646147-d1e7d2e1-5c2c-40fa-8b7a-8e41b6e606fa.png)

**Comment by benjaminxscott** [comment]
Same issue w/ Ft Wayne https://gist.github.com/benjaminxscott/f392fcbc3fee977c74a573601d503440

**Comment by scottredracecar** [comment]
1846 2p experts, is this a bug? There is a rule:
"(This token has no effect until a tile is laid in that hex and upgraded to a green tile, see below)"

and

"• Two cities (determined above) each gain a blocking token once their tile is upgraded to green."

Possibly this is not a bug? Please reopen if necessary.

It could be enhanced somehow, but it looks like the game enforces the rules correctly to me?

**Comment by benjaminxscott** [comment]
This is an open bug, the issue is that the NYC is *not* removed from the game, but the site is presenting a "double token slot" Z city as if it were

**Comment by thepackrat** [comment]
I suspect this is caused by the second C&O token in cincinatti, which forces open an extra token hole in the broad laid there. When taht's recycled, it isn't modified back and appears in the upgrade list, which is why it's only the broad.

**Comment by scottredracecar** [comment]
Yes, that seems to be what is happening. 

A fix could be to destroy each 5,6,57,291/292/293 tile when it is upgraded and replace it with a fresh copy.

**Comment by thepackrat** [comment]
Using extra_slot rather than cheater in place second tile works to not break yellow tiles, but it means we'd also need code on the green upgrade to yoink the token back into blocking mode.

**Comment by thepackrat** [comment]
<img width="376" alt="1846-2p-extra tokens" src="https://user-images.githubusercontent.com/12235419/152654912-c3290865-ad81-4142-921d-319210c50d31.png">

**Comment by thepackrat** [comment]
I think the most elegant approach is to have the token appear as a token only at the point of  green upgrade, and have it annotated on the tile in another way until the, perhaps like a 70 destination.

**Comment by thepackrat** [comment]
I have a fix pending that drops the token as the cities go green. Looking for options to hint that the tokens are

**Comment by thepackrat** [comment]
<img width="128" alt="1846-2p-plain" src="https://user-images.githubusercontent.com/12235419/152685619-68784f0f-529e-4de3-8b1d-79165a0d01d8.png">
<img width="128" alt="1846-2p-yellow" src="https://user-images.githubusercontent.com/12235419/152685622-e7c147ab-ec20-43ed-81e4-003e4c231221.png">
<img width="128" alt="1846-2p-green" src="https://user-images.githubusercontent.com/12235419/152685627-9c2cf36d-a012-462c-b748-31c462371381.png">

This is my fix. I defer the token fall to a green upgrade, per the rules, so the tile doesn't need to be levered open, but annotate the hex with an icon indicating a token will fall there which is removed on green when the token falls.

**Comment by myNameIsFourteen** [comment]
I think this looks great to me as a player / person who wrote up the issue.
