### ISSUE TITLE
[18Carolinas] - train can not end in town/dit

### ISSUE THREAD

**Issue by H1llsman** [tobymao/18xx#6264]
https://18xx.games/game/54257

Trains can not end their routes in a town/dit only in cities.
This is not mentioned anywhere in the rules.

**How to Reproduce the Bug?**
https://18xx.games/game/54257?action=73

What steps cause the unexpected behavior?
WNC trains cannot end their routes in Statesville or Winston Salem
![image](https://user-images.githubusercontent.com/85963784/130675623-83557074-1c4d-432d-a149-b242b55a0c4e.png)

**Comment by scottredracecar** [comment]
Sorry, this was a recent rule change and the rules weren't up to date. I just added this now to the rules.
