### ISSUE TITLE
1822 (MRS) Game seems to allow building track through Wales off map grey areas. 

### ISSUE THREAD

**Issue by Picklesgrr** [tobymao/18xx#6271]
https://18xx.games/game/54086

https://18xx.games/game/54086?action=228
(ish we did not actually build the track)

The Minor Railways in S Wales 19 21 24 appear to be able to build track in H31 through the grey Wales areas. 

![image](https://user-images.githubusercontent.com/20401089/130804263-f19cd62b-6384-4465-b6c3-9fee7c783d14.png)
railway 24 turn.

**Which Browser / Platform?**
Brave  but it's a rules bug.

**Comment by Andy-0711** [comment]
Not only that (I'm pretty sure I had the same issue in a game).
IIRC M20 could also run a train from 20 over 21 to 19, which is ... nice  (if it's mine) but obviously wrong.

**Comment by fanman80** [comment]
Game 59795 has the same bug except the minor 20 is cut off but laying track.

![M20](https://user-images.githubusercontent.com/70117294/140442349-a30a80a6-e136-4168-8791-6c9160168848.png)

It's happening in these places:
https://18xx.games/game/59795?action=512
https://18xx.games/game/59795?action=457

**Comment by fanman80** [comment]
The game 59795 also allow the acquisition of minor 20 by the LYR even though minor 20 was not connected to any major.
https://18xx.games/game/59795?action=558
Minor 21 was connected to LYR.  So it seems that minor 20 was deemed connected through E32 and E34.

**Comment by fanman80** [comment]
This looks related to bug 5375 - 1822 - Minors 21 and 22 can illegal tile lay thru the Pontypool 2 tile terminus #5375 and bug 5680 - [1822] Unable to run a 4T route through MT&P when there are tokens on both sides #5680.
