### ISSUE TITLE
[1862] Possible to buy train from company in receivership

### ISSUE THREAD

**Issue by nightflyerkilo** [tobymao/18xx#6283]
**What's your Game ID?**

https://gist.github.com/ikelly/21b80cd7e08113e3c50d0a3e124a1c05

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- ESR has the option to buy a 4/5E or a 5E from L&H, which is in receivership.
- This requires confirming that "Market" consents to the transaction.

Please include screenshots (you can drag and drop or upload them into this issue)

![image](https://user-images.githubusercontent.com/1767452/131069264-09953b74-2da1-4a82-a748-1756ae145a69.png)
![image](https://user-images.githubusercontent.com/1767452/131069313-1730fa49-9f79-41bf-86c0-09d2d9b87912.png)

**Which Browser / Platform?**
- Chrome 92.0.4515.159
- Desktop

**Comment by roseundy** [comment]
It seems likely that this is illegal behavior, but I can find where in the rules it says that you can't buy a train from a company in receivership.

**Comment by ikelly** [comment]
Last sentence of section 8.0. "A company in receivership may not sell any of its trains to another company."

**Comment by roseundy** [comment]
OK, thanks. The last two sentences in the GMT rules don't appear in my first edition rules.

I'll fix this as well as prevent a receivership company being acquired/merged.
