### ISSUE TITLE
[1840] Able to remove Stadtbhan token without visibility to the line that removes the token. 

### ISSUE THREAD

**Issue by lonerockz** [tobymao/18xx#6285]
https://18xx.games/game/48259

In two instances a player was able to pay the $40 to remove a token on one of the Stadtbahn lines even though they can not lay a token to replace the one removed. 

This was vague in the original rules and was clarified here: https://boardgamegeek.com/thread/2605013/removing-stadtbahn-tokens-home-spaces

**Comment by Zwergenpunk** [comment]
The non home city tokens can be removed without being connected to it

**Comment by lonerockz** [comment]
That is not correct. Please see the link where Lonny clarifies the rules.

**Comment by Zwergenpunk** [comment]
This is correct. There are multiple issues around that in github.

**Comment by beorn7** [comment]
Are those not yet released FAQs accessible anywhere? It seems Lonny's clarification needs a clarification, and getting that out ASAP would be great.
