### ISSUE TITLE
[1860] Priority deal is handed out incorrectly in bankruptcy.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#6294]
https://gist.github.com/physic/3f2e9ff138edd899b3091f8d048c95a1
action 459,460

Summary: Priority deal is wrongly being updated every time a player acts, causing the wrong player to get priority when a stock round restarts due to company bankruptcy when two players are tied for number of shares.

**Per the rules, priority deal is handed out at the end of an SR and when a company becomes bankrupt, and at no other time**

Action 459:
Expected: lambdaaurigae should have priority deal, because they had it at the beginning of the Stock Round.
Observed: notnorb has priority deal, because lambdaaurigae took the last action.

**When a company goes bankrupt, priority deal is given to the player with the fewest shares. If there is a tie, it is given to the first player with the fewest shares, starting with the current priority deal and proceeding in player order.**

Action 460:
Expected: lambdaaurigae should have priority deal, because they win ties, having started the current SR with priority deal.
Observed: physicssquirrel has priority deal, presumably because they won the tie because notnorb incorrectly had priority deal just prior.

**Comment by roseundy** [comment]
Shockingly easy to fix.
