### ISSUE TITLE
[1840] can't take advantage of tokens during Construction Phase

### ISSUE THREAD

**Issue by th3tick** [tobymao/18xx#6298]
The rules state:

Construction (not mandatory)
A line may:
§ Lay one track tile or upgrade one track tile
§ Lay a yellow Stadtbahn tile for the cost of 20 Gulden and then perform a
bonus action (see next page)
§ Place a station marker
These three actions may each be performed only once, in any order.
None of these actions is mandatory.

but the order in the game is strictly lay tiles _then_ do tokens.  So I can't do tile, token the newly-reached location, then lay a tile where that token now reaches.

e.g. game 53784

GWStStB lays tile #57 with rotation 0 on J10 (Meidling)
token K9 (can't do this until the end)
Lay H12 granting a second yellow
lay J9 which is now reachable due to the new token

So a legal game move can't be taken in this implementation.

**Comment by Zwergenpunk** [comment]
This is not a legal move. You need to perform the special action immediately after the first tile lay. You can token, tile lay tile lay or tile lay tile lay token.

There is somewhere an issue where this is also brought up

**Comment by th3tick** [comment]
I don't understand.  What it's not letting me do is:

- normal tile lay
- normal token placement
- lay a statbahn tile with bonus yellow
- lay bonus yellow

This in no way violates the rules as shown.  I am laying the bonus tile immediately after the statbahn tile.  I would appreciate any clarification as to how this violates the rules as written.

**Comment by th3tick** [comment]
Note, too, that your comment:

You can token, tile lay tile lay

can't actually be done.  The token is forced to be the last action.

**Comment by th3tick** [comment]
I have confirmed with the designer that this is indeed a bug.  Please re-open:

> Hi Lonny,
> 
> I'm trying to play a game of 1840 on 18xx.games, but it won't allow me to do what I think is a legal action.  I filed a bug on it, but was told it was illegal.  I don't see that it is based on the rules so was hoping you could help clarify.
> 
> The steps I wanted to do with tram line 8 was:
> 
> lay a tile in J10 connecting to K9
> token K9
> lay a Statbahn tile which granted me a bonus action of laying another yellow
> lay a tile in J8 connected to K9
> 
> The game prevents this because you can only place a token after all tile lays.
> 
> Can you help clarify this situation?

and his response:

> you are right. It is legal. I will clarify this with the programer and keep you informed. I already wrote him an email.

**Comment by perwestling** [comment]
I suppose this need to be revisited, @Zwergenpunk

**Comment by Zwergenpunk** [comment]
Ok sorry this is even simpler than I thought. 

This is possible. You just have to click on the greyed out city. This is the same in all games where the token/tile_lay step is together (1846...)

Here is your turn in a cloned game
https://gist.github.com/Zwergenpunk/9478c049b80e1b7cc667c4de38290495

**Comment by th3tick** [comment]
Sorry, not sure how to use a github link to look at a game...

The instructions at the top in the "skip" button say it's a tile lay, so it's very counter-intuitive that there are hidden actions available in addition to the ones it tells and shows you.  Any hope of this being improved so players can tell it's an option?

**Comment by th3tick** [comment]
There is still something strange going on here.  In game:

https://18xx.games/game/53784 - same game as this issue started with.

tram company 8's turn, and it can't put a token in J4, no matter if I try it first, second, or third action for the company.

Why can't it token that location?  It has the money, it has the connection, but the game is disallowing it.

**Comment by Zwergenpunk** [comment]
I'm not sure where the issue is. When I undo to OR 2.1 I can place a Token in J4 with 8. But you cannot build a orange frames tile and place a Token. 

But yes that place should be tokenable if the owning major corp has money.

**Comment by th3tick** [comment]
The issue, I think comes from this confusion:

<img width="218" alt="Screen Shot 2021-09-18 at 8 09 09 AM" src="https://user-images.githubusercontent.com/48138042/133891623-0f7fcbaf-b91a-4931-8bff-fee9e5b75365.png">

At this point, that is revenue in the GWStStB, not anything in 8 itself.  The physical game shows this with a box on the charter for the revenue of thw GWStSstB from all its tram lines, and no money goes in/on the tram lines, as they have none.  But showing money next to the token costs makes it very confusing that you cannot use it for that.
