### ISSUE TITLE
[1860] Autobuy from market sometimes fails with "shares of different sizes exist"

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#6299]
https://18xx.games/game/53037

Action 496 contains the following:

{
          "type": "program_disable",
          "entity": 7706,
          "entity_type": "player",
          "created_at": 1630372683,
          "reason": "Shares of different sizes exist, cannot auto buy FYN from market"
        }

1860 does not have shares of different sizes. It does have reserved IPO shares, but there is no situation in 1860 in which an auto action would be ambiguous. In the market, as in the repro above,  reserved shares are identical to other shares.

**Comment by physic** [comment]
This game is now archived. Other games started around the same time are now pinned to d3974ec8c, so I suspect the repro would work on that version.

**Comment by physic** [comment]
d3974ec8c

**Comment by scottredracecar** [comment]
I don't think we can move forward with this one as currently documented, not enough info. @roseundy ?
