### ISSUE TITLE
[1862] I cannot enter the game

### ISSUE THREAD

**Issue by wsyangp** [tobymao/18xx#6301]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

https://18xx.games/game/49116

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

I cannot enter the game for two months
It just says "loading game...."

Please include screenshots (you can drag and drop or upload them into this issue)
![캡처](https://user-images.githubusercontent.com/89951703/131764857-d9eb51d0-94ad-4bb2-9020-9ffd88884b25.PNG)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by roseundy** [comment]
`Uncaught margs: [m]message: "undefined method `buyable_trains' for <Engine::Game::G1862::Step::RedeemShare>"name: "buyable_trains"stack: "buyable_trains: undefined method `buyable_trains' for <Engine::Game::G1862::Step::RedeemShare>\n    at m.l (https://18xx.games/assets/deps.js:4:12825)\n    at m.u (https://18xx.games/assets/deps.js:1:12950)\n    at m.p (https://18xx.games/assets/main.js:62:76330)\n    at m.S (https://18xx.games/assets/deps.js:15:74629)\n    at m.E (https://18xx.games/assets/main.js:62:434386)\n    at m.S (https://18xx.games/assets/deps.js:15:74629)\n    at https://18xx.games/assets/main.js:63:88276\n    at m.S (https://18xx.games/assets/main.js:63:89091)\n    at m.N (https://18xx.games/assets/main.js:63:89780)\n    at https://18xx.games/assets/main.js:63:77373"[[Prototype]]: m`

**Comment by wsyangp** [comment]
Umm, Can you delete this game please?


2021년 9월 2일 (목) 오전 10:34, Steve ***@***.***>님이 작성:

**Comment by roseundy** [comment]
OK, apparently this has never happened before: a company has no train after the LNER forms.
The company should be forced to re-finance, but there is a bug here.

**Comment by roseundy** [comment]
The bug is that after a company raises money through an ebuy, it needs to call  clear_cache!

**Comment by roseundy** [comment]
Once this is fixed, the game can continue.

**Comment by wsyangp** [comment]
I appreciate you so much.

2021년 9월 2일 (목) 오후 12:57, Steve ***@***.***>님이 작성:
