### ISSUE TITLE
1860 auto routing doesn't use token bypass ability

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6304]
https://18xx.games/game/52943?action=627

The auto router finds an 8+2 for 370+40. You can trivially add Brading to the route for 400+30.

**Comment by ChrisTheCat** [comment]
Same thing happens here https://18xx.games/game/52943?action=630 where the route could easily be improved by adding north Newport.

**Comment by roseundy** [comment]
This is probably never going to be fixed. The ability to route through tokened out cities would require large changes to the auto-router.

**Comment by tobymao** [comment]
closing as won’t fix

**Comment by ChrisTheCat** [comment]
I strongly suggest disabling the auto router in 1860. That would be preferable to providing a known broken tool.

**Comment by dfannius** [comment]
Yeah, I agree. I know that the autorouter is not guaranteed to return the best routes, but not understanding that routes can go through one tokened-out city is almost as bad as consistently running 4-trains through only 3 cities; most of the time there's a trivial improvement to the route.
