### ISSUE TITLE
18 Texas - Blocking step Lay/Upgrade Track cannot process action 107

### ISSUE THREAD

**Issue by gerwalker** [tobymao/18xx#6308]
https://18xx.games/game/53871?action=106

**Comment by scottredracecar** [comment]
Sorry, there was a rule change where now these powers are only usable after Phase 3 starts. I need to update the private company descriptions to reflect this.

I forgot to add a note to archive games that broke based on this rule change.

@tobymao can you please archive this game (and others that broke)?

**Comment by scottredracecar** [comment]
This game is archived now. Good time to start another one I guess. No further changes planned for a few weeks most likely.
