### ISSUE TITLE
18Carolinas Special Rules

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#631]
18Carolinas is a prototype by Scott Petersen (me!)

The following are draft rules from the prototype.

**Setup**

- [x] Randomize and reveal the North Carolina corporations and the South Carolina corporations. The first of each group has par 90 (all four tokens), the second par 80 (three tokens), third par 70 (three tokens), fourth par 60 (two tokens).
- [x] Pass out private companies (see private companies section)

**Stock Rounds**

- [ ] The corporations come out in tranches. When one of the “90” corporations is 100% sold from the IPO, both of the the par 80 corporations become available, repeat similarly for the 70 and 60 par corporations.
- [ ] corporations can be sold into receivership
- [x] no adjustment for sales or all solds

**Private Companies**

- [x] Use number of privates P1-P4 equal to the number of players (up to 4)
- [ ] If there are 5p, then player 5 must buy the presidency of the north company. If there are 6p, then player 6 takes presidency of the South Carolina Corporation
- [ ] May sell private companies to the bank for 30 less than face value, they stay in the pool, but it's generally not a good idea to rebuy them so that rule could just be removed.
- [x] Private companies are never removed.

**Tiles**
- [ ] The tiles are double sided. They have the same tile shape on both sides, but one side is solid (standard gauge) and one side is striped (southern gauge). The only differences are that the towns have revenue 20 instead of 10.

- [ ] Until Phase 5, only standard gauge track can be laid in North Carolina and southern gauge can only be laid in South Carolina. Dual gauge hexes can hold either gauge. After Phase 5, this restriction is removed. After Phase 5, a route between two cities/offboards can be "standardized" from southern to standard. Any tile that route touches is set to the standard side.
- [ ] Routes can be traced on any gauge and can mix gauge as needed for all purposes except a given train’s route may only include one type.
- [ ] Tile upgrades. Double dots can upgrade to 14/15 tiles.

**Train Power/Game Phases**

- [ ] Instead of buying trains, corporations buy “train power”.
- [ ] The trains are user definable each turn, but the minimum train is 2 or [phase-2], whichever is larger. Thus a corporation with 7 power in phase 4 can run trains 2T-2T-3T or 3T-4T or 7T. Whatever combination doesn’t exceed the total train power. 
- [ ] The game starts in Phase 2. Power costs $30 per power. In phase 3, power costs $40 per power, and so on. The final phase is Phase 8 ($90/power). If a new phase would be triggered in Phase 8, we continue in phase 8, but the power now costs $100/power and never increases further.
- [ ] Corporations may buy as much power as they can afford. There is a Total Power that counts all the power that has been bought by all the corporations. When a corporation buys the n*15+1 power, the game enters a new phase. When the game enters a new phase, all the corporations lose [current power]/3 (round down).
- [ ] When a corporation triggers a new phase, the process is:
-- Move “total power” marker up
-- All corporations incur power loss (power/3, round down)
-- Purchasing company buys power at the new phase price
- [ ] Upon the start of Phase 5, all the C tiles are automatically upgraded to their brown tiles (each has only one configuration).

**Stock Price Movement**
- [ ] Must pay out at least CMV to advance
- [ ] Up to quad jumps for 4x CMV payout (1x/2x/3x/4x)

**Forced Train Purchases**
- [ ] A company must have at least as much train power as [phase-2]. If the company does not have this much, they are forced to buy power up to the current phase. If they incur forced train purchase, they must pay 2x the price (EMR as needed). (the 2x number might change to 1.5x).

**Comment by roseundy** [comment]
Hmmm. I also opened an implementation checklist for this #5753
