### ISSUE TITLE
1861 Russian ran for different amount than submitted

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#6312]
The game log says the Russian ran for 70 but the history view shows that the submit says it should have been 180. 
When i do it in hotseat mode, it runs correctly. I am unclear what I am seeing or why it is like that. 
https://18xx.games/game/53896?action=631
https://18xx.games/game/53896?action=634
![1B98AA88-363C-4DD2-BC03-601F3A8253AD](https://user-images.githubusercontent.com/73318207/132277451-445c6c2c-9f42-47f2-bc68-172c5e908269.jpeg)
![03C641FD-62E4-485C-8C7F-4CD09DC94210](https://user-images.githubusercontent.com/73318207/132277454-e24e6416-0fe5-4c60-ac32-f206fc023130.jpeg)

**Comment by dfannius** [comment]
The JSON indicates that RSR was run for 180, then that action was undone, then it was run for 70. I think that the H8-G5-E1-B8-A9 route that shows when you go to action 631 is just the route from previous OR that is displaying as a default. I think this is safe to close.
