### ISSUE TITLE
1861 Russian confirmation

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#6313]
I have seen several games now that someone sub-optimally ran the Russian and it had a pretty big impact upon the game. I wonder if there is an option that could be included for someone/other players to confirm the Russian’s run before entering the stock round. I know not everyone would love this, and also feel many would like it being available. Thanks for all you all do!!
Elud

**Comment by tobymao** [comment]
There will not be programmatic constraints for this. In 18xx.games spirit if you expect this of the table tell people. Sorry.

**Comment by Eludyan** [comment]
Ok thanks!
