### ISSUE TITLE
[1860] There is no way to exchange a private company after making a purchase

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#6314]
Description: There are two stock actions, permitted by the rules, which are impossible to execute in the current implementation.
1. Par a company, and then convert the corresponding private company into the reserved share.
2. Buy a private and then immediately convert it into the reserved share.

Impact: 
The first case can result in a player losing a share because they should have been allowed to par and convert before someone buys the Fishbourne Ferry. The second case, below, results in the play pattern seen in 53035 below, where no one is willing to buy the Fishbourne Ferry (because it will make good shares available and the other players will have dibs) and no one is willing to buy the Ryde, Cowes, or Yarmouth privates (because the implementation won't let them convert their private until their next turn, and it would disappear if the next player then bought the Fishbourne Ferry)

Repro
1. https://18xx.games/game/54302?action=106
Expected: After I buy the President's share of the BHI&R, I may then convert my Brading Harbour private to a share of the BHI&R before the next player's turn.
Observed: Before I buy the President's share of the BHI&R, I may not convert the Brading Harbour. After I buy the President's share of the BHI&R, my turn ends immediately, and I may not convert the Brading Harbour.

2. https://18xx.games/game/53035?action=538
Expected: After I buy a private company out of the market, I can exchange it for a share before my stock action is over, e.g. before the next player buys the Fishbourne Ferry and makes my private go \*poof\*.
Observed: After I buy a private company out of the market, my turn ends immediately.

As far as I can surmise, in all other cases, there is no meaningful reason not to simply convert before my buy action. But in these two cases, conversion is only possible after the buy action and is therefore impossible in the current implementation, because buying currently passes to the next player.

**Comment by roseundy** [comment]
See issue #4999

I'm completely aware of the issues you've raised, but I don't want to require players to have to do an extra "pas" every stock turn unless it matters.

The fix for #4999 allows the exchange before or after buying/selling, but _only_ if the Fishbourne is for sale. This takes care of #1, leaving #2, which I will have to debug.

**Comment by physic** [comment]
I see. So the first special case actually exists. My extrapolation was in error. The second case would require a very similar special case (that would be unlikely to pin very many games) for after someone buys a private while the fishbourne is out.

**Comment by roseundy** [comment]
I was qualifying the fix with #1 with "did you par a company that you have a private for?"
This needs to be expanded to also include "did you just buy a private when the Fishbourne is available?"
