### ISSUE TITLE
[1860] Trains should be able to run through tokens of bankrupt companies

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#6315]
https://18xx.games/game/53084

On page 15 of the rules, it says, "These bases continue to restrict other companies’ track development, but do not prevent other companies from running trains through the cities where its tokens have been placed."

In this game, the BHIR is bankrupt and this is shown by the bar on the tokens.  When I tried to run a train past these tokens, I got the message "Invalid route".  I tried this while playing around in hotseat mode with a couple of different companies.  (It's not actually my turn in the screenshot below but that's not important).

![image](https://user-images.githubusercontent.com/36824573/132413281-6ae60ce0-169a-46c8-acba-c91f89cada3f.png)

This is the only case I can think of in 18xx rulebooks where a token only blocks a route for track building and not for running trains, which makes the rule rather annoying to have to implement.

**Comment by roseundy** [comment]
This must have gotten broken or is an edge case somehow, because I've tested this case.

**Comment by roseundy** [comment]
Something is definitely fishy. The tokens are flipping them back to the non-bankrupted side. I think this is related to a fix I made recently.
