### ISSUE TITLE
[Harzbahn 1873] Bids must be multiples of 10.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#6317]
Rule: When auctioning a concession, bids must be at least 100 marks and a multiple of 10 marks.

Repro: https://18xx.games/game/54269?action=453

Expected: A bid of 267 is rejected.
Observed: The bid went through and a player was able to win a concession for 267 marks.

**Comment by magnusrk-ch** [comment]
Looks like could be just a matter of setting MUST_BID_INCREMENT_MULTIPLE to true?

**Comment by roseundy** [comment]
Yep. Easy fix.
