### ISSUE TITLE
Add a "Your Turn on #{game.id}" button to go to other games where its your turn

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#632]
Some players are playing multiple active games at the same time.

It'd be good if there's a "Your Turn on 1234" button that highlights it's the players active turn on that game.
If there's multiple just pick one. The player can then zoom round the games it's their active turn without needing to return to the main page.

**Comment by jcoveney** [comment]
I would love this

It would also solve another problem, which is taking a turn, going to the main page, then finding out that the turn hadn't committed yet and having to do it again. Such a button could ensure that the current turn has been committed before going to the next game.

**Comment by tobymao** [comment]
i don't think we're gonna do this
