### ISSUE TITLE
[1840] Rename trains to to indicate Company Round they are available in.

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#6321]
Currently, trains are named Y1, Y2, O1, O2, O3 etc, and the number indicates which price the train is sold at, which is controlled by the current round. This is a conceit of the site since the physical game simply has all Yellow trains, no distinction between rounds, but moves the position of the deck to indicate price. If the trains need to have unique numbers/names, let the name at least be informative, by having the number indicate the company round in which they become available.  Then, you know that in CR3, trains O3, R3, and Pi3 are available (currently, its the confusing jumble of O3, R2, and Pi1).

In total you would have:
Yellow: Y1,Y2 (no change)
Orange: O1,O2,O3 (no change)
Red: R2,R3,R4
Pink: Pi3,Pi4,Pi5
Purple: Pu4,Pu5

This should be a simple rename that would make it a bit easier to read what price an upcoming train will be, since you just check the round you want to purchase it in and find that numbered train.

**Comment by Zwergenpunk** [comment]
I like that.
