### ISSUE TITLE
[1840] question

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#6330]
assume tram #1 & #3 have been sold in first round.
#1 operates first. 
a) Both yellow tiles have been laid as shown in the picture below.
b)  station marker is placed in E17

action a) is legal  with no doubt

action b) is my concern:
1) is this a legal action -->  yes/no
( there is a already a space for a station marker for tram3)
2) or should tram1 must not lay the token due to the inoperationality of tram3 until the green phase. 
Is this point still a design issue?

![image](https://user-images.githubusercontent.com/64490299/132898173-2213ae3c-cd02-4be9-8d63-f905d77f2c4c.png)

**Comment by Zwergenpunk** [comment]
Yeah I think it is a bad idea to buy the `#3` when `#1` is also available.
As far as I understand the rules there is nothing that prohibits that.

**Comment by hast18xx** [comment]
Lonny,
its up to you!

**Comment by scottredracecar** [comment]
closing unless we hear a reason to reopen
