### ISSUE TITLE
[1840] Stadtbahn token removal incorrectly "teleports"

### ISSUE THREAD

**Issue by beorn7** [tobymao/18xx#6336]
According to rule IX.6, last item, a line can remove a Stadtbahn token for 40 Gulden. The program allows to remove _any_ Stadtbahn token, but (as [clarified by Lonny](https://boardgamegeek.com/thread/2605013/removing-stadtbahn-tokens-home-spaces)) the intention is that only reachable Stadtbahn tokens can be removed.

**Comment by Zwergenpunk** [comment]
See https://github.com/tobymao/18xx/issues/6285

**Comment by Zwergenpunk** [comment]
No idea when this will be released.

In the bgg thread the question is about the home tokens of the city lines. These cannot be removed. But I understand that this is not as clear as it could be
