### ISSUE TITLE
[1825] Company Allowed to Upgrade a Tile While Not Owning a Train

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#6338]
https://18xx.games/game/56288?action=153

Rule 4.3.2 states that a company needs to reach a tile with a train it currently owns to upgrade it.  The corrolary to this is that you cannot upgrade if you do not own a train. GCR did that.

**Comment by roseundy** [comment]
The problem is with OO tiles.

**Comment by roseundy** [comment]
Not a bug. This is a tile lay, not an upgrade. Upgrades don't apply to the first tile laid on the map, regardless of color.
