### ISSUE TITLE
18Chesapeake Bug Report : "GameError: Cannot use group West Virginia Coal more than once" game id (1105)

### ISSUE THREAD

**Issue by Andre-J-Sousa** [tobymao/18xx#634]
The Game Id is 1105, just making the bug report as expected

> We're sorry this game cannot be continued due to GameError: Cannot use group West Virginia Coal more than once
> Please raise a bug report and include the game id (1105) and the following JSON data

**Comment by tobymao** [comment]
you're not allowed to run coal to coal or pitts to pitts, your game has been pinned
