### ISSUE TITLE
[18Texas] Unable to lay token without laying the 511 tile using Galveston and Red River RR Private

### ISSUE THREAD

**Issue by PJBarns** [tobymao/18xx#6341]
https://18xx.games/game/55388?action=256

According to the rules ( Section 5, P2), the P2 ability should let a company lay the 511 tile *and/or* token in Houston. If we're reading that rule correctly, if another company upgrades Houston so that the 511 can't be laid, the owner should still be able to token because of the "or". In the current implementation, however, the private ability disappears if the track option in not used, taking away the ability to subsequently token. 

For example, in the game linked the owner of the P2 controls the T&P. Houston has been upgraded already by the SP owner. There is still an unreserved spot in Houston because the SP was the one to upgrade it. When the T&P tries to use the ability on the track step, the only thing that happens is the upgrade to brown is shown as "Later Phase". Skipping the track step causes the private ability to disappear, and attempting to token in Houston results in the "Cannot token on I14 because it is not connected" error displaying. 

I think the issue is because the private description in the game doesn't match the rules to reflect the "and/or" nature of the private power. In game, the text makes it seem like the token in I14 is directly tied to being able to lay the 511 tile.

> P2 Galveston and Red River Railway Company. From Phase 3 on, the owning president may place a #511 tile in hex I14 (Houston) and/or place a station marker in this hex during the operation of a company of which they are president. In order to place the station marker, an unreserved space must be available. The corporation does not need to have a route to this hex to perform this action. Performing either action counts as the corporation’s tile lay and station marker placement steps for the operating turn.

vs. 

> Teleport to Houston. Phases 3-4. The owning president may place a #511 tile in hex I14 during the track laying step of a corporation for which they are president. The corporation does not need to have a route to this hex. The tile placed counts as the corporation’s tile lay action and the corporation must pay the terrain cost. The corporation may then immediately place a station token there.

This effectively breaks the P2, since the token power disappears if the tile is already upgraded and the I14 space isn't blocked for upgrades by P2.

**Comment by scottredracecar** [comment]
Yes, you are right, the rules are out of sync with the implementation. I updated the rules to match the implementation.

As for how this *should* actually be handled from a game design perspective, you are right that this makes P2 less powerful in that in some situations it will not be able to be used. In this particular game, the power could have been used in OR4.1 or OR4.2, but those opportunities were not taken. Now that SP has paid the terrain cost in OR5.1, the teleport power is no longer available.

**Comment by scottredracecar** [comment]
Similar situation for P5, but that will take both a yellow and green tile to block, but of course we might expect the P5 player to be a little slower to start as well with the big early outlay of cash for P5.
