### ISSUE TITLE
Maps/Tiles aren't displayed, when town is included

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#6342]
Dev-system. Maps and Tiles aren't displayed, if 'town=revenue:10;path=a:0,b:_0;path=a:_0,b:3' is in the definition for HEXES or TILES.
'town=revenue:10' is displayed. 
![grafik](https://user-images.githubusercontent.com/80693707/133053691-bcc16569-03a6-4b8b-bb0d-ef434dd39f2d.png)
Error raised in the last week.

**Comment by roseundy** [comment]
Is any error being thrown?

**Comment by volker18xxdev** [comment]
stops at loading without an error. Hotseat-Mode.

**Comment by volker18xxdev** [comment]
Solved, clone the rep from scratch.
