### ISSUE TITLE
[1825] Bought 3 train before all 2 trains are sold

### ISSUE THREAD

**Issue by tphon** [tobymao/18xx#6347]
https://18xx.games/game/56299

**Comment by tphon** [comment]
https://18xx.games/game/56299
A few time after a move a pink banner pops up and the move has not been registered on the server.
Just now I bought the last 2 train and the first 3. The game reset cancelling the 2 purchase but allowing the 3.

**Comment by roseundy** [comment]
The game state has gotten corrupted. What did the pink banner say?

**Comment by roseundy** [comment]
If you UNDO the game until before the train purchase, does it still show the bug?

**Comment by tphon** [comment]
Wanted to leave if for you to see, if it's a bug.  Pink banner was very quick, something about server could not process. Had it a few time, placing tiles and after a few attempts it is OK. Shall I undo the 3 purchase and try again?

**Comment by tphon** [comment]
I can't undo now. When trying, I get pink banner that says
The server did not accept this action due to: undefined method 'get_slot' for nil:NilClass... refreshing.

**Comment by roseundy** [comment]
This may be the same bug as #6353 , but it's hard to know for sure without debugging this all the way to root cause.
