### ISSUE TITLE
1825 - Double City Tiles

### ISSUE THREAD

**Issue by knauman** [tobymao/18xx#6349]
https://18xx.games/game/56469
Game start errors out with a Tile #10 inconsistency.
-Optional Rules: BigBank; D1; K2; K3; K5; K7; R1; R2; R3; U3+; Units 1+2+3

Need to standardize the double city spots on the board and tiles.

Original game maps and tiles do not have OO on them.

Unit 1 has OO on tiles and on the board
Unit 2 has OO on tiles and on the board
Unit 3 has OO on tiles and without on the board
D1 has #10 tiles without OO
R2.1 has OO on tiles and on the board
<img width="994" alt="Screenshot 2021-09-14 113618" src="https://user-images.githubusercontent.com/51214001/133288825-46bfc831-fe9f-476a-b7bd-5e350b376102.png">
![image (2)](https://user-images.githubusercontent.com/51214001/133288926-b2f418d9-eb8a-4eb9-86b5-c8caf091762f.png)

**Comment by roseundy** [comment]
OK, thanks. Adding OO makes the upgrade logic easier.
