### ISSUE TITLE
[1825 ] Phase 4: 7-trains rust 3-trains

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#6352]
Kit K3  "Phase 4":  Phase 4 starts with the pucrchase of the first 6 train leaving 3-trains still "in use". Bur with the purchase of the first 7-train, 3-trains are no longer "in use". What means, in my understanding, that 3-trains are rusted by the 7-trains.

**Comment by roseundy** [comment]
Sorry, is there an issue here? Are the 3 trains not rusted by the 7?

**Comment by KlausKiermeier** [comment]
According to the Info tab in game 56300 the 3-trains are not rusted by the 7-trains.

**Comment by roseundy** [comment]
Well, poop.

**Comment by roseundy** [comment]
Yep, the 7 rusting the 3s didn't survive my last restructuring of the code :-(
