### ISSUE TITLE
[1825 Unit 1] Cannot lay tiles with GWR unless game is reloaded

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#6353]
https://18xx.games/game/56408

Could not reproduce the issue in a hotseat game

During OR 3.1 when doing the tile lay for  GWR cannot lay at 12T. I get the pictured error. Tried closing the tab and reloading but cannot move forward with second tile lay.

Also happens when trying to use chat.

Windows 10
Firefox 92.0 64-bit

![image](https://user-images.githubusercontent.com/67166181/133341980-19aff2c8-f598-4bd5-8510-c634758127eb.png)

**Comment by roseundy** [comment]
Constant mutation related to how MP games are started
