### ISSUE TITLE
[Harzbahn 1873] available 3T is not displayed

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#6354]
**What's your Game ID?**
18xx.games/game/54791

**How to Reproduce the Bug?**
The SHE just distributed half and wants to buy a 3T from the depot where three 3T are still available. But the opportunity to buy a 3T from the depot is not shown. It was shown when the SHE distributed full.

**Comment by KlausKiermeier** [comment]
![Screenshot_20210915-094211_Chrome](https://user-images.githubusercontent.com/80912587/133411443-3cf2dd47-52b4-4284-a2c1-0fe02cd40d92.jpg)

**Comment by roseundy** [comment]
Maybe I'm misunderstanding something, but a 3T costs 450 ℳ, and the SHE only has 445 ℳ after withholding half.

**Comment by KlausKiermeier** [comment]
You are absolutely right, and I'm so sorry I had such a blackout. :-(
Please close this issue as soon as possible, it is so emberrasing for me....
