### ISSUE TITLE
Auto pass disabled by take_loan in SR on 1817NA. 

### ISSUE THREAD

**Issue by joflynn** [tobymao/18xx#6357]
In SR 1. One player is maxing loans to drive up interest rates before OR 1.1. 

Would like to auto pass through the SR. 

Log reports:

[14:07]-- Disabled programmed action due to 'Unknown action take_loan disabling for safety’

Expected action, take loan doesn’t disable auto pass. 

game id 56011

**Comment by perwestling** [comment]
This is basically the same issue as #5861 although that is for 1817.

**Comment by magnusrk-ch** [comment]
Can someone familiar with the 1817 family (and ideally other games that support loans) comment on whether taking a loan should ever be considered shenanigans? Otherwise it's trivial to stop it from cancelling auto pass.

**Comment by scottredracecar** [comment]
Yes, 1817 loans should certainly be considered shenanigans.

**Comment by magnusrk-ch** [comment]
So another example of a situation that's definitely shenanigans, but the user is aware of it and would like the option to ignore the shenanigans and keep auto-passing.

**Comment by joflynn** [comment]
Would it still be possibly shenanigans on SR1? That was the concern.

**Comment by scottredracecar** [comment]
Whether yes or no, I don’t think the autopass rules should be sophisticated.

1877 (which us based off 1817) is definitely yes in SR1. This particular play, maybe not. Possibly sometimes yes though.

There should perhaps be a “hard autopass.” That completely ignores all shenanigans.
