### ISSUE TITLE
[1825] Tile #119 could be irregularly promoted

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#6359]
**What's your Game ID?**

https://18xx.games/game/56300

According to the rules of Expansion Kit K5, Tile #119 is promotable from Tile #69 in Phase 3, i.e. once the first 5-train is bought.
In the game above, in Hex T20, Tile #119 was somehow placed irregularly earlier and through an unvalid promotion/upgrade.

**Comment by roseundy** [comment]
I thought I understood what the green/brown stripes indicated, but apparently I'm wrong.

**Comment by KlausKiermeier** [comment]
Yes,  the green stripes are meant to indicate that the tile upgrades a yellow one. The brown stripes mean that this upgrade is only possible once the game is "in brown".

**Comment by KlausKiermeier** [comment]
This is similar to tile 166. This one upgrades green tiles but is only available "in grey".

**Comment by KlausKiermeier** [comment]
Unfortunately, this kind of colour code is not valid for tile 200 where the meaning of the two colours is different.

**Comment by pstone1** [comment]
Perhaps a good 18xx.games notation for tile 200 would be to use the border color (like the purple border tiles CZ or Harzbahn), and also put that border on the base tiles crewe/wolverton/swindon.
