### ISSUE TITLE
[1825] Tiles 81, 82, and 83 should not have valid upgrades.

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#6361]
Looking at the tile manifest, the 3 way green tiles are listed as having an upgrade path to 40, 41, and 42 (identical tiles, but brown). You are not be able to upgrade merely to change a tile color, but not add new track, so 81/82/ and 83 should have no valid upgrades. The key difference between 40/81, 41/82, and 42/83 is that the brown versions of that tile has the advantage of being able to upgrade to the lawson gray 60 tile, but the green versions do not.

**Comment by roseundy** [comment]
Have you encountered this bug in actual game play, or are you just looking at the possible upgrades on the tile manifest? I'm pretty sure the game won't allow the upgrade of these green tiles to the equivalent brown ones.

That being said, it should be fixed on the manifest.

**Comment by pstone1** [comment]
testing in hotseat you are right, it gives the message "must use new track" and wont lay the upgrade. But yes, would be helpful for the manifest to indicate this as well.
