### ISSUE TITLE
[1828.games] Autoroute still creates routes ending in Coalfields without Coal Marker

### ISSUE THREAD

**Issue by Andy-0711** [tobymao/18xx#6365]
https://github.com/tobymao/18xx/issues/6327 is not solved.

> Any Game, e.g. 55044, 54684, 56936. Chrome, Android, Windows 10 21H1x64 / Server 2019
> 
> Part 1: It's half bug, half enchantment:
> 
> The game only shows an error when you begin/end a route in the coalfields when you submit a route not during defining the route. Only after submitting it tells you you can't go through the Coalfields and doesn't accept the route.

=> This part is solved.

> Part 2: It's a bug:
> 
> Autoroute also creates such illegal routes.

=> This part is not solved:
The Interface now doesn't accept coalfields without coal marker - but autorouting still creates routes beginning/ending in coalfields anyway - so the problem is still not fixed. (Worse; you now cannot unclick the coalfield "directly" after using autoroute.)
![Coalfields](https://user-images.githubusercontent.com/81620575/135869171-3641f1de-a537-4c58-a087-0118c1c5767e.PNG)

**Comment by crericha-qualitrol** [comment]
@Andy-0711, you provide a link to game + action where this occurs?

**Comment by Andy-0711** [comment]
As before it has happened in any game with active AutoRouting.
It couldn't occur before SR 6, but I've not checked any further than OR 6.3.
6.1
https://18xx.games/game/56936?action=527
6.2
https://18xx.games/game/56936?action=629
https://18xx.games/game/56936?action=638
6.3
https://18xx.games/game/56936?action=663
https://18xx.games/game/56936?action=669
https://18xx.games/game/56936?action=672

Currently I'm searching for Occurrences where a 5th or 6th train is not handled correctly either - AutoRouting doesn't like that at all. AFAIR with 5 trains it sometimes works, with 6 train it never runs more then 5 trains. Don't know if we ever had 7 or 8 trains. If you want to look at it at the same time wait until I raised that issue and I'll link it here.

**Comment by JoeB989** [comment]
A recent change may have fixed this.  Unfortunately this game has been deleted.  When you have time can you retest and see if this works now?  Or provide a new test game if it still doesn't work.

**Comment by dfannius** [comment]
The linked bug #7416 has been closed as a duplicate but contains a current repro case.

**Comment by JoeB989** [comment]
Confirmed still a problem.  Cause: The auto-router needs 1828's Route.revenue to raise an error with an invalid route like this to avoid treating it as a valid route.  So the fix will need to be in 1828 code not auto-router code.

**Comment by JoeB989** [comment]
BTW I consider this a bug not enhancement request: game allows invalid routes

**Comment by crericha** [comment]
The game will reject the route once it is submitted. It is an enhancement to switch from pre-check to post-check.
