### ISSUE TITLE
[18AL] Cannot buy 4D train due to thrown exception

### ISSUE THREAD

**Issue by ezRAez** [tobymao/18xx#6373]
**What's your Game ID?**

- Game: https://18xx.games/game/55183

- POST request:
```
Request URL: https://18xx.games/api/game/55183/action
Request Method: POST
Status Code: 500 Internal Server Error

created_at: 1632493058
entity: "TAG"
entity_type: "corporation"
id: 561
price: 800
train: "4D-6"
type: "buy_train"
user: 814
variant: "4D"
_client_id: "34fd9671adb24cbbaf807f4c550c03ab"
```

**How to Reproduce the Bug?**

Try and buy a 4D train as TAG.

![Screen Shot 2021-09-24 at 9 23 37 AM](https://user-images.githubusercontent.com/12765592/134690751-c9dfc08f-1084-43d0-a2ef-5f1b805fab88.png)

**Which Browser / Platform?**
- Browser Version: `Google Chrome | 93.0.4577.82 (Official Build) (x86_64)`
- Platform: Desktop

**Comment by perwestling** [comment]
I cloned the game and had no problems buying that 4D.

@ezRAez Do you still have the problem? Have you tried refreshing? If the problem remains I will have to look at it closer.

**Comment by dmajoraddnine** [comment]
@perwestling Thanks for testing, I'm in the same game and it's still busted. When I use Master Mode to try clicking the "Buy Train" button, it throws the error shown in the screenshot.

Here's the AJAX request to `https://18xx.games/api/game/55183/action`:
`{"type":"buy_train","entity":"TAG","entity_type":"corporation","id":561,"user":8562,"created_at":1632764354,"train":"4D-6","price":800,"variant":"4D","_client_id":"bf56fc038ab44e2aaffc0f6a1c9e043e"}`

And the 500 response:
`{"error":"undefined method `id' for nil:NilClass"}`

This is in Firefox on macOS 11.3.1

**Comment by dmajoraddnine** [comment]
Oh that's truly strange, it looks like it does work in a cloned version of the game... Maybe there's something corrupted in the main instance that gets corrected during the clone operation?

**Comment by perwestling** [comment]
There is differences when games is run as hotseat/cloned and multi player, which can cause things to break. I will look into this issue.

**Comment by ezRAez** [comment]
Thanks @dmajoraddnine - we're developers, so let us know if there's any data you need from us!

**Comment by ezRAez** [comment]
Works! Thanks so much @perwestling

**Comment by dmajoraddnine** [comment]
Amazing, thank you!!
