### ISSUE TITLE
[1840] Make central city private locations more distinct from red hexes

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#6375]
Central city privates locations should be more pink (less red) to clearly distinguish them from red hexes.

**Comment by Zwergenpunk** [comment]
Another color ia not really an option. But we could add an icon to the cities. 

Do you think that would help?

**Comment by orome** [comment]
> Another color ia not really an option. But we could add an icon to the cities.
> Do you think that would help?

Not sure what would do the trick. Icons of the landmarks might work, but that risks being ugly if not done right.
Could they be left white (just retaining the red outline, perhaps)?
