### ISSUE TITLE
1822 display loans on spreadsheet

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6378]
https://18xx.games/game/55974?action=431#spreadsheet

In the above linked game, Krongar's loan shows up on the entities tab, but not on the spreadsheet. It would be nice if it also appeared in the spreadsheet.

**Comment by GAFBlizzard** [comment]
I don't know how to upvote this, but I agree.  The loans are in the entities tab, but the spreadsheet would be a nicer overall place to check who has loans in 1822PNW.
