### ISSUE TITLE
[1828.games] Autoroute only routes 5 trains

### ISSUE THREAD

**Issue by Andy-0711** [tobymao/18xx#6379]
https://18xx.games/game/54684?action=315

If you have 6 trains in a 1828-system autoroute always routes only 5 of them. My best guess would be that it is limited to 5 trains even though you can have 8 trains in a 1828-system. I don't think it's caused by a timeout since in later game phases autoroute takes up to ~10 times longer.
![6trains](https://user-images.githubusercontent.com/81620575/135868331-c4b1bc4a-b18f-42c7-b56a-6fc977c7d460.PNG)

Clearly you could place a 6th train here at D4-C5-D6.

Usually a system rarely has more than 5 trains, but it can happen after a merger before a 5/6 train is bought and rusts the 2/3 trains. I have not found another occurrences in my multiplayer games but I'm sure it has happened in some of mine hotseat test games as well.

**Comment by scottredracecar** [comment]
Auto routes all the trains now
