### ISSUE TITLE
[1825] Minor is not able to run its train

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#6386]
**What's your Game ID?**

https://18xx.games/game/56300

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- During OR 8.1 the minor M&C tries to run its built-in 3T-train from its home token in K7 via J6 to H6.
- Expected: A revenue of 70 should be offered to be submitted.
- Seen: The message: "Route must contain token" (cf. below).
- This message appears although the route clearly contains the home token of the company.

By the way: this is the first time that one of the minors act at all in this game.

<html><body>

Train | Used | Revenue | Route
-- | -- | -- | --
3T | 3 | N/A | H6-J6-K7
Route must contain token

</body>
</html>

**Comment by roseundy** [comment]
Apparently, this was the first time two minors that use the same type of train were run
