### ISSUE TITLE
1825 Tile issue

### ISSUE THREAD

**Issue by WRSDixon** [tobymao/18xx#6389]
Trying to start and 1825 Game with Unit 1, R1, R2, R3, D1 and Kt.
Get an error message with tile 37. Tile 37 is in several of the Regional units and a game with R1 - R3 works.
D1 also has tile 37. Is tile 37 implemented differently in kit D1?
Error message:  "conflicting definition of tile 37".

**Comment by roseundy** [comment]
What is "Kt" ?
