### ISSUE TITLE
Bug: When a company is in limit of trains but with money the train buying phase is skiped

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#639]
Even if you could buy from the other company from the same player

Reproduction bug: with this data
https://gist.github.com/Djeefther/27ea889cbb92930299368a5e7cb9d432
Undo until the beginning of "UR (Djeefther)" operation round and continuos until the buying train moment, even if the company has no money to buy a 6T from the market, it could buy a train for other company of the same player.

**Comment by tobymao** [comment]
no you cannot buy a train when you are train tight
