### ISSUE TITLE
1862 Not able to buy fifth share in Parliament round for L&D

### ISSUE THREAD

**Issue by HogueEric** [tobymao/18xx#6390]
**What's your Game ID?**

https://18xx.games/game/56831

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

https://18xx.games/game/56831?action=393

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- I was able to but the fourth share, but not the fifth.  I had sufficient funds.

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - Chrome 93.0.4577.82

**Comment by roseundy** [comment]
You are at the certificate limit. The code is correct.
