### ISSUE TITLE
[1825] Double-heading two 2 trains into a 3 train

### ISSUE THREAD

**Issue by mjshaver** [tobymao/18xx#6391]
**What's your Game ID?**

Rule 4.5.5 says the following:
"If desired two '2' Trains are allowed to be run together and treated as if they are a single '3' Train"

https://18xx.games/game/57751?action=76

**How to Reproduce the Bug?**

The GWR should be able to run a two 2 trains as a 3 train from Swindon (v14) to London (V20). 

But I don't see anyway to do it.  "V14-V16-V20" leads to "3 is too many stops for 2 train"

This is a pretty standard opening for the GWR.
Thanks for all your hard work!
(Is this a bug report or a feature request?)

**Comment by roseundy** [comment]
Like this:

![double_head1](https://user-images.githubusercontent.com/8494213/135769186-066c56cc-74aa-452d-b0ac-e6e13ed7aaba.png)
![double_head2](https://user-images.githubusercontent.com/8494213/135769188-7b799358-96c3-4146-8ef7-5507ebf05aac.png)

Just run a 2 train from Swindon to Reading, and a second 2 train from Reading to London. The code figures out that it is double-heading the two trains.
