### ISSUE TITLE
[1828.games] C&P route should not need to be connected to C&P home token

### ISSUE THREAD

**Issue by Andy-0711** [tobymao/18xx#6395]
I would classify the following as a **Minor Bug**, since most users won't try that; I simply wanted to find out whether an example the author showed would work in 18xx.games.

In [https://18xx.games/game/57858?action=628](url) I upgraded D14.
![C P](https://user-images.githubusercontent.com/81620575/135866137-9ea9927d-07fd-4285-97de-9348a32e66d9.PNG)

Now I should get the revenue from a route between D14 and E15. I can select D14-E15, but it fails with error "route must contain token" both "in preview" as in submitting the route. Additionally, **AutoRoute** sets an illegal route not including D14.

Even though this is counter-intuitive for any 18xx-player, the author states this possibility explicitly in his example 1 in [https://boardgamegeek.com/thread/2162379/cp-private](url), post 16 from Oct., 7th, 2019:
![C P2](https://user-images.githubusercontent.com/81620575/135866333-d5e76497-ea02-4231-8b76-d23adb793fbf.PNG)

In the post before that he states the rules:
> Player revenue is the owning player's choice of half of a 2-train route (two revenue centers) **that includes the placed tile** and any revenue center on it. The placed track tile may be between the two revenue centers that form the route or off one end (see [subsec:General-Route-definition]) and does not need to enclude the Cobourg & Peterborough Railway's station marker. [...]

And he goes on:
> Perhaps I'm too close to the trees, but I'm not seeing how/why people are struggling with this. Sure, it is different from the train-running rules for share companies, but the exceptions and constraints are explicitly listed. The C&P is not a share company and it does not run a train, it just has a revenue defined in terms of a tile lay...

The 1828.games [implementation notes](https://github.com/tobymao/18xx/wiki/1828.Games#implementation-notes) state that 
> The C&P 2-train route is implemented via a 2-train that does not rust.

If it not possible (or too complicated) to correct this wrong behavior the [implementation notes](https://github.com/tobymao/18xx/wiki/1828.Games#implementation-notes) at least should be completed with
> The C&P 2-train route is implemented via a 2-train that does not rust and has to be connected to Peterborough/the C&P home token.

Btw. https://github.com/tobymao/18xx/wiki/1828.Games states that 1828.games is still in beta. AFAIK it's gone productive some while ago and it's shown that way if you start it.

**Comment by crericha** [comment]
It worked when the game launched. Must have been broken by another game.

**Comment by thepackrat** [comment]
We'll need to have fixtures for the more exotic cases. This seems like something that will be clobbered again with a future change otherwise.
