### ISSUE TITLE
Ability to open all games with moves

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#6397]
I'd love to be able to open all of the games that I have that currently have moves. I think this can be done client side, but I ran into one detail.

`var list = document.getElementsByClassName("game card");
for (var i = 0; i < list.length; i++) {
  var buttons = list[i].getElementsByClassName("button_link");
  for (var j = 0; j < buttons.length; j++) {
    window.open(buttons[j].href);
  }
}`

(note: I suck at javascript, am more than happy for you to tell me a better way to do this :P)

Regardless, this opens every game in a new window, clearly need to filter that to just the games with moves. I guess what I was thinking is that an attribute could be added to facilitate this...otherwise I guess I could filter using the orange color that games have when its your turn, but that seems pretty janky!

**Comment by tobymao** [comment]
in ruby, the games have a game state

**Comment by tobymao** [comment]
What do you mean 'client side', do you mean write your own chrome extension?

**Comment by tobymao** [comment]
and if you're just writing your own javascript extension, just check the color of the banner

**Comment by jcoveney** [comment]
A chrome extension, yeah, or even just a javascript snippet I paste into the console :P and yeah, I ended up just basing it off the color of the banner. Hopefull that doesn't change ;)

I suppose I'll just go with that for now.
