### ISSUE TITLE
1870 better gray tile indicators

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6400]
You have to dig pretty deep in the rules to find out that the grey tiles may only be placed in Kansas City and St. Louis. There is no indicator on the map or on the tiles on these cities to match the K and L on the grey tiles.

It would be nice if the K and L were printed on the map and persisted through to each laid tile. Or at a minimum, when the brown tile is laid there, add the letter then.

Alternatively, instead of labeling them K and L, put the actual city names on the gray tiles.

One of the players in our game mistakenly thought the L was for Little Rock. We couldn't figure out why the tile has an L instead of "StL" or "SL" or even "S".

**Comment by benjaminxscott** [comment]
What do you think about the PR?

**Comment by ChrisTheCat** [comment]
If you post images here, I can look at pictures and comment on them...

**Comment by benjaminxscott** [comment]
![image](https://user-images.githubusercontent.com/1711810/136274539-052c0b34-09c4-44cf-b3a6-abb1d4da3bac.png)

**Comment by ChrisTheCat** [comment]
Looks great!
