### ISSUE TITLE
1840 Location of Arsenal

### ISSUE THREAD

**Issue by Aquinasish** [tobymao/18xx#6407]
I notice on the 1840 4P map that Arsenal should be hex J26. The map shows it on J28.

**Comment by benjaminxscott** [comment]
It looks like the city names got shifted by two spots, looks like it should be:

![image](https://user-images.githubusercontent.com/1711810/136301108-752514ca-2a4e-4cdd-a32f-a1a0b447adbf.png)

Based on [this image](https://cf.geekdo-images.com/9H6aLTxvHuFUYuUr7TNn-Q__large/img/-UlHSJ0dlPowgH20jz8CLMHwC1w=/fit-in/1024x1024/filters:no_upscale():strip_icc()/pic5198096.jpg)
