### ISSUE TITLE
[1846] President incorrectly allowed to EMR to buy a Depot train when the corporation should be forced to buy a Discard train

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#6426]
PRR in emergency train buying
Share Price: $80
Player owned shares: 3
Market shares: 0

The player should be able to emergency issue 3 shares @ $60 for $180; however, the game shows only one share can be issued for $60. The amount per share in correct, but the number of shares is wrong.

The amount the player needs to contribute is also wrong.

[game data.txt](https://github.com/tobymao/18xx/files/7327138/game.data.txt)

**Comment by benjaminxscott** [comment]
Looks like that game data is for another game (CZ?) , do you have a candidate game?

**Comment by benjaminxscott** [comment]
Ah maybe I had another file with the same name, in the same downloads folder, I guess

**Comment by michaeljb** [comment]
> [game data.txt](https://github.com/tobymao/18xx/files/7327138/game.data.txt)

I've figured out that in this game, the only thing stopping PRR from illegally buying a 4/6 or 5 train with President contributions is that the President can't muster enough cash for it.

>  that means it's unclear from this example if there is another problem where 18xx.games would allow that 4/6 train to actually be purchased when it should not be (the error message I got in no. 4 makes me think it would not actually allow that purchase)

I've found a handful of games where this did actually happen:

```
[101890, 108251, 110672, 116841, 124913, 126810]
```

The fix for that also fixes the incorrect UI text.
