### ISSUE TITLE
18MEX: incorrect value of Mexican National Railroad private

### ISSUE THREAD

**Issue by tomhoward87** [tobymao/18xx#6427]
The MNR private is listed as having a value of 140 even after the player takes the presidency of the NdM, despite the fact that the private may not be sold to another company. Should it have a value of 0 instead?

**Comment by benjaminxscott** [comment]
I believe the current implementation is correct, based on 6.1(c) the private's value is used to determine a winner

So if someone goes bankrupt before the private is closed, its value contributes to that player's value

**Comment by perwestling** [comment]
Ok to close, @tomhoward87 ?

**Comment by tomhoward87** [comment]
Sorry, yes, that's fine, I hadn't noticed that in the rules.
