### ISSUE TITLE
[1825] Unable to perform a legal upgrade & wrong value on tile

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#6441]
**What's your Game ID?**

https://18xx.games/game/56300

What steps cause the unexpected behavior?

- During Phase IV the GWR tried to upgrade Swindon with tile 200. This was not possible: tile 200 was not shown as a possible upgrade. Similarly when I tried to upgrade Wolverton.
Step: https://gist.github.com/benjaminxscott/c8f08d6d4367cc279168f2d38cb5e072

- Tile 168 should have value 70. Presently it has 40.

**Comment by Aquinasish** [comment]
Should tile #200 not also be upgradeable in phase 3? my physical rules say it should.

**Comment by benjaminxscott** [comment]
There's some issue with [`upgrades_to?`](https://github.com/benjaminxscott/18xx/blob/master/lib/engine/game/g_1825/game.rb#L695) , it throws 
> undefined method `+' for nil

when trying to upgrade

**Comment by KlausKiermeier** [comment]
> Should tile #200 not also be upgradeable in phase 3? my physical rules say it should.

Yes, tile 200 is meant to work as an upgrade from phase 3 on,  i.e., after the first 5-train was bought.
