### ISSUE TITLE
[1846] President allowed to sell shares to help company buy a more expensive train than it could without that sale

### ISSUE THREAD

**Issue by dmitryleskov** [tobymao/18xx#6459]
https://18xx.games/game/58423?action=395

IC has $652, I have $189, together enough to buy a 6T. Yet the game allows me to sell a share to buy a 7/8T.

dfan on the 18xx Slack had to say:

The rules text is “A President who doesn’t have the needed cash must raise it by selling stock shares”. It could be more explicit but my understanding is that the answer to the question is no; normally a player can’t sell stock during an OR, and nothing in that rule grants them that ability unless more money is required. Tom Lehmann’s comment at https://boardgamegeek.com/thread/1849992/article/26939192#26939192 seems to agree: “(if more money is needed, sell shares)“, though again, it could be more explicit.

**Comment by dfannius** [comment]
On Slack, magnusrk argues that the current behavior is correct:

> I don't think so. The decision on which train to buy was already made
> 
> "However, once a corporation has to use cash from its President to purchase a required train, then it may freely buy from the bank any available phase or type of train."
> 
> [...]
> 
> The first stage is that if the company can afford any train without president help, then it is not allowed to get president help. Once you need president help you can choose any train and the president sells shares based on that train, not any other
