### ISSUE TITLE
[1825] Valid tile placements denied in some cases.

### ISSUE THREAD

**Issue by alexarnon** [tobymao/18xx#6468]
Game #58038: https://18xx.games/game/58038

Valid placements for AlexA are not allowed/possible, e.g.:
1. X16 is greyed out, while it should allow placement of a # 52.
2. X8 disallows even a simple # 7 (tight curve).
3. W11 disallows any kind of double-dit tile that should be possible.

Game ID: AlexA

The above have been a problem since the beginning of the game, except for # 1 which appeared only on OR5.2 IIRC (we are playing a semi exploratory game).

I am using Firefox on Mac.

**Comment by HerbyMcGee** [comment]
I have this issue with a different (non-server) error message.
https://18xx.games/game/61154?action=315
When trying to upgrade N13, it says LNWR is "Unable to reach city/town on upgraded tile with any train," which is not true.
 
The same thing happened when LNWR wanted to upgrade N12 earlier in the game.
https://18xx.games/game/61154?action=183

L&Y was able to upgrade N12 with no issues

**Comment by roseundy** [comment]
@HerbyMcGee, this appears to be a separate bug.

**Comment by HerbyMcGee** [comment]
I will create a new issue. Thanks
