### ISSUE TITLE
1870 GMO Chicago, St Louis, Springfield Area. 

### ISSUE THREAD

**Issue by Hylndur101** [tobymao/18xx#6474]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

https://18xx.games/game/60573

Game name 1870

Game ID  60573

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

**How to Reproduce the Bug?**

When running the GMO- We notice a bug when if you start in Chicago, or the northeast. The values are NOT adding up correctly. We start in chicago, go to  Chicago and somewhere else, it does not count Chicago.  The values are not adding up correctly. 

Springfield to St Lous = 150  (st louis being doubled.)  First Screen shot

once a third stop is added -   add Jackson it goes down to 130... when it should add to 190.    Second Screen Shot

Please include screenshots (you can drag and drop or upload them into this issue)

![Spring to st lous](https://user-images.githubusercontent.com/81931661/139520818-fb12cd3d-48db-42a5-ae96-32662fed6ca2.PNG)

![3rd stop](https://user-images.githubusercontent.com/81931661/139520947-9ad89a1e-cc52-4c65-81ca-856b45865195.PNG)

**Comment by crericha** [comment]
In 1870, the destination needs to be at the end of the route in order for it to be doubled.

From the "Operate Trains & Calculate Income" section of the rules:

> A company’s destination station marker doubles the value of the city for that company if that city is at the end of a run.

I hope that clarifies for you why the income is $130 when the third stop is added.
