### ISSUE TITLE
[1822] a bug in placing a destination token 

### ISSUE THREAD

**Issue by Kezerk** [tobymao/18xx#6486]
https://18xx.games/game/60158?action=829

Whether I try to add a second track, lay only one track and hit "Done (Track)" or lay no tracks and hit "Done (Track)", there is an error message "undefined method 'destination' for <Engine::Game::G1822::Step::DestinationToken>"

This apparently only affected me, the game progressed when another user used MasterMode to do the action I was trying to do.

Google Chrome | 95.0.4638.69 (Official Build) (64-bit) (cohort: Stable)
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 10 Version 21H1 (Build 19043.1288)
JavaScript | V8 9.5.172.25

**Comment by Kezerk** [comment]
Same happened in https://18xx.games/game/61055 (action 600). 
Using different browsers (Edge, Opera) didn't work, and one other player tried using MasterMode with same result.

**Comment by Kezerk** [comment]
Could this be a reoccurrence of this issue?
https://gitanswer.com/1822-can-t-lay-destination-token-846574454

**Comment by darkotuskan** [comment]
Same thing happened to me in game 58151

**Comment by databoy01** [comment]
Same thing happening in game 57518.  I was able to screenshot the error and this is what it says.
“ undefined method 'destination' for <Engine:: Game::G1822::Step:DestinationToken>”

Hope it helps.

**Comment by Kezerk** [comment]
And same game as originally - this time when CR would be adding its destination token (fixed by Master Mode move by DukeM):
https://18xx.games/game/60158?action=912

**Comment by tobymao** [comment]
@outsidePasser

**Comment by pedantix** [comment]
This is happening in my game as well.

Looks like a step might have been misplaced in the refactor for 1822mx(which I’m super excited about). 


Looking forward to more great things @tobymao and @outsidePasser. Do you guys need help maybe for 22CA? After this bug is reworked of course

**Comment by waaayback** [comment]
Same thing happening in my game ATM

https://18xx.games/game/58759?action=1121

**Comment by outsidePasser** [comment]
Looking now.

**Comment by altorio** [comment]
Hi, same in game 58184.

**Comment by outsidePasser** [comment]
Fix on the way up.  Tested against 60158, 61055, 58151, 57518, 58759, and 58184.
