### ISSUE TITLE
List par prices in ascending order

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#649]
It would be nice if the par values were displayed 70, 80, 95 instead of 95, 80, 75. Most people count numbers up, not down. I have accidentally chosen the wrong par price several times because of this.

<img width="350" alt="Screenshot 2020-06-07 08 32 32" src="https://user-images.githubusercontent.com/8732435/83973200-a92d4380-a899-11ea-8848-d12192db3100.png">

**Comment by scottredracecar** [comment]
I'll take this

**Comment by scottredracecar** [comment]
This is solved now.
