### ISSUE TITLE
[1846] Cannot assign Meat Packing company after purchase even when connected

### ISSUE THREAD

**Issue by Qaimaqam** [tobymao/18xx#6495]
https://18xx.games/game/60956

OR2.1
NYC purchases Meat Packing with connection to Chicago (established via purchase of Michigan Southern)
When doing this, game log says:
**Meat Packing Company is assigned to NYC
Meat Packing Company is not assigned to a hex**
The meat packing token is greyed out on the NYC charter
Clicking the "Meat Packing Company (NYC)" button for the special ability freezes the map and token cannot be assigned to Chicago, despite connectivity existing.

I have unwound game to just prior to purchase of MPC.

**Comment by tobymao** [comment]
f894faacfe1b382ad05f23af6e97cf09531b58e7
