### ISSUE TITLE
Eliminate unneeded train buying wording

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#650]
From a game log on OR1.

> LV must buy a train either from The Depot, The Discard or other corporations.

There are no trains in "The Discard" and buying across isn't allowed, as a 3 train hasn't been purchased. I suggest that in this case, the display should only be "LV must buy a train from The Depot." In other scenarios, it might be appropriate to say "from The Depot or other corporations" for example.

**Comment by scottredracecar** [comment]
You can buy across anytime in 18Chesapeake.

**Comment by ChrisTheCat** [comment]
That's interesting. Suggestion still stands - don't mention locations that aren't possible to buy a train

**Comment by perwestling** [comment]
@ChrisTheCat I have made a commit that change so that the text would be
  LV must buy an available train

What do you think about that?

**Comment by ChrisTheCat** [comment]
I like it. Good solution.
