### ISSUE TITLE
[1825] Legal tile placement issues "Unable to reach city/town on upgrade"

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#6501]
I have this issue with a different (non-server) error message.
https://18xx.games/game/61154?action=315
When trying to upgrade N13, it says LNWR is "Unable to reach city/town on upgraded tile with any train," which is not true.
 
The same thing happened when LNWR wanted to upgrade N12 earlier in the game.
https://18xx.games/game/61154?action=183

L&Y was able to upgrade N12 with no issues

_Originally posted by @HerbyMcGee in https://github.com/tobymao/18xx/issues/6468#issuecomment-964387254_

**Comment by roseundy** [comment]
This is a more serious problem than I anticipated. My "distance_graph" calculations are broken in the presence of switches. This didn't show up in 1860 since that game doesn't have switches.
