### ISSUE TITLE
[1893] Train limit issue/confusion

### ISSUE THREAD

**Issue by zalasta524** [tobymao/18xx#6509]
Game in question is: https://18xx.games/game/60985

I cannot for the life of me find the train limit for minor companies in the rules, but the 18xx.Games info shows that minor can only own 1 train in phase 5.  In our game minor #2 Köln-Frechen-Benzelrather E still has a 3T and a 4T, it wasn’t forced to discard a train.  The only train limit info I found was from a screenshot of the minor charter which indicated on the bottom “Train limit = 2; 5-train = 1”, perhaps the “5-train” means first 5-train sold which in that case is not functioning as intended.  However, the same screenshot also shows the corporation charters with “train limit = 3; 6-train = 2”, if the same interpretation applies, shouldn’t corporation train limit change from 3 to 2 at phase 6 rather than 5 as it is currently implemented?

![2576134E-43B6-46A1-ADF2-DE582E104059](https://user-images.githubusercontent.com/80227052/141388740-dae829d0-2794-497f-9837-9478ec184d4d.png)
![7125D93E-7F86-44C6-AB9D-100C87E28082](https://user-images.githubusercontent.com/80227052/141388852-504d5fca-5edf-4195-a7f4-b3d68b701651.png)

**Comment by slapphappyjazz** [comment]
In my copy of the game, purchased this year (2021), the train limit on the corporation charters says "“train limit = 3; 5-train = 2”, which would mean that the 18xx.games implementation of the limit for major companies is correct.

However, I came here to report the same issue with minor companies.  I owned one of the green minors and it had two trains when the 5 train was purchased.  Unless there is a special rule about the timing of the enforced merger, I think I should have had to discard one of the trains.  As far as I can see from the rules, the phase change happens immediately, then the forced merger happens in the next merger round.  18xx.games doesn't implement this forced discard.

**Comment by slapphappyjazz** [comment]
However, I came here to report the same issue that 18xx.game doesn't enforce the change in the train limit for minor companies with the first 5 train is purchased.  I owned one of the green minors and it had two trains when the 5 train was purchased.  Unless there is a special rule about the timing of the enforced merger, I think I should have had to discard one of the trains.  As far as I can see from the rules, the phase change happens immediately, then the forced merger happens in the next merger round.  18xx.games doesn't implement this forced discard.
[Edited to put this in a separate comment to make it easier to see].

**Comment by perwestling** [comment]
The picture has rule book version 2.0, and the picture is from 2014.
I have a more recent Marflow copy, also version 2.0. Where 5 train is specified as train limit decreaser on corporation charters, as well as the Phase Table (version 2.0).

But I have now sent a question to Marflow about this, to check if 5 or 6 train is the correct one.

**Comment by perwestling** [comment]
I got an answer from Marflow:

- The train limit for minor railways changes from 2 to 1 with the purchase of the first type 5 train.
- The train limit for railway corporations changes from 3 to 2 with the purchase of the first type 5 train.

The train limit after merge seems to work properly. I will investigate if there is a problem with the train limit during an OR.

**Comment by perwestling** [comment]
It turned out to be a general bug, affecting all games where minors have a decreasing train limit. So I have now pushed a fix for approval.

**Comment by slapphappyjazz** [comment]
I wonder how many games of 1861 or 1867 have accidentally allowed minors to hold onto too many 3 trains?  Probably very few, or someone would have noticed.

**Comment by perwestling** [comment]
Yes, it is a rare thing I believe, and it might have very little effect in the game. But it was a good catch with a simple fix.
