### ISSUE TITLE
18XX.games telegram notifications don’t work with a particular game

### ISSUE THREAD

**Issue by amartinsola** [tobymao/18xx#6513]
All the players have telegram notifications activated but we are not receiving notification from a particular game or Harzbahn 1873. We are receiving notifications from all the other games we are playing, yet the other games are not of Harzbahn 1873. I don't if it happens only with this particular games or with all games if Harzbahn 1873.

**Comment by amartinsola** [comment]
Sorry, the game is https://18xx.games/game/61517

**Comment by scottredracecar** [comment]
This game is over now, but please file another issue or reopen this if you continue to have issues.
