### ISSUE TITLE
[1862] Game Ends at conclusion of OR 5.2

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#6515]
https://18xx.games/game/61947?action=573

The header says the game will end at the end of OR 5.2, but that should be OR 5.3 unless I'm mistaken.

**Comment by roseundy** [comment]
Wow, that was a light-speed game. It definitely broke some code. It might be just the message at the top that is broken.

**Comment by roseundy** [comment]
After playing around in hotseat, it looks like it is just an incorrect message at the top, and only during the stock round. The message is correct once entering the ORs.

**Comment by setrajonas** [comment]
That's what we suspected, good to hear.

**Comment by roseundy** [comment]
This bug potentially affects all titles, not just 1862. It requires the end game to be triggered during the same OR that the phase changes the number of ORs per set.
