### ISSUE TITLE
[1825] Company in receivership cannot upgrade a tile

### ISSUE THREAD

**Issue by DestrinStorm** [tobymao/18xx#6518]
Game: https://18xx.games/game/60178
Action: https://18xx.games/game/60178?action=538

LNWR is in receivership and it is it's turn to operate.
Try and upgrade hex R12 with any tile, you get the error message 'Cannot upgrade a city/town without a train', I believe the company should be able to lease a train on it's turn in order to use that for the purposes of upgrading a tile.  This error is given on almost all upgrades you attempt.  Interestingly it will allow an upgrade of hexag S13 but I'm assuming this is because it is a lay not a promotion (that space has yet to be upgraded)

I think the correct behaviour is that the train lease should be permitted from the start of the turn to allow LNWR to perform upgrades within that train length then it can run that train, must withhold revenue and then will pay £10 for the train lease out of it's cash.

**Comment by roseundy** [comment]
I'm at BGG.CON right now and don't have access to my 1825 rules, so I don't know if the rules allow leasing at the start of the turn vs. just at the point routes are run.

**Comment by DestrinStorm** [comment]
Rules section taken from Unit 1 rulebook:

6.4.3 A Company in Receivership may lease a Train from the unsold stock in the Bank for £10 per turn, This Train remains the property of the Bank at all times. Only one Train may be leased by a Company. (A Train may still be leased even if the Company already owns a Train or Trains.) The leased Train will be the next one on offer for sale. If the Train is of a new type it will not calise a Phase change. (The Train may still run its full distance.)

In which, it doesn't really say explicitly, 'on your turn' to me means it can be at any point on the companies turn.

I think there is an inference from:

6.4.5 If the Receiver is also Directing aother Company his impartiality may be suspect! In such cases an objection may be lodged by two or more players. If the objection stands the Receiver will be required to make an alternative move. An objection will not stand in respect of the following:
The extension of track from a Station in use by the Company.
The promotion of a Tile if this causes an increase in revenue.
The placing of a marker Token if this causes an increase in revenue.

Given how frequently companies in receivership won't have trains I feel the expectation of this paragraph that they are expected to upgrade tiles very heavily implies they should be able to do so
