### ISSUE TITLE
[1825] Company in receivership given limited choice of train lease when Advanced Trains are in play

### ISSUE THREAD

**Issue by DestrinStorm** [tobymao/18xx#6519]
Game and action: https://18xx.games/game/60178?action=615

LNWR is in receivership and is about to run it's trains, it's only being offered the 3T for lease.
The rules aren't very clear here but from the base rules:

6.4.3 A Company in Receivership may lease a Train from the unsold stock in the Bank for £10 per turn, This Train remains the property of the Bank at all times. Only one Train may be leased by a Company. (A Train may still be leased even if the Company already owns a Train or Trains.) The leased Train will be the next one on offer for sale. If the Train is of a new type it will not calise a Phase change. (The Train may still run its full distance.)

Advanced Trains rules:
These trains are available for the price shown on the card after the relevant phase has been introduced as described in 4.7.  They are alternatives to whatever other type of Train is currently on offer.

I see two possible interpretations:
All currently available for purchase trains are options for leasing (I believe this is the intent despite the slightly wooly rules)
OR
The next 'mainline' train is available for leasing and the advanced trains are ignored (I don't think this is a good interpretation)

Certainly what is being offered now (LNWR is only offered a 3T for lease) is wrong, why the 3T and not the U3?  Those are made available at the same time.

**Comment by roseundy** [comment]
I may have to offer a choice of trains to lease. This may complicate the UI somewhat.
