### ISSUE TITLE
Value visible in spreadsheet in 1856 is wrong

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#6521]
In game 61524 the spreadsheet shows a value of 513 for mb1898 with 2x 80, 2x 65, 6x 75 shares and 213 in cash (together 953). Even if I consider the loans (what is not correct for the value of a player) I get a different value. It seems so that from the real value 953 the interest due and the loans have been subtracted (-400 and -40) to get 513.

**Comment by Maxwell-Frank** [comment]
The value shows the final value if the game where to end immediately, which means that outstanding loans in a company lower the value of the shares by $10 per loan.  So you'd get $300 in share value (2x$60, 6x$35, 2x$15) + $213 in cash = $513.
