### ISSUE TITLE
1870 incorrect count of number of shares that could be purchased

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6522]
https://18xx.games/game/59924?action=163

ChrisShaffer has 499. The system says I could buy six shares of IC at 82, which requires 516. The display should show that I can only afford five shares, not six.

<img width="338" alt="Screen Shot 2021-11-18 at 9 13 07 AM" src="https://user-images.githubusercontent.com/8732435/142464068-a2892117-bf07-449d-a5d7-10ac830bc8b0.png">

**Comment by dfannius** [comment]
6 x $82 = $492, or am I missing something?

**Comment by ChrisTheCat** [comment]
Duh. I mistyped in my calculator at 6*86
