### ISSUE TITLE
[18Ireland] Value paid is not value that appears in the log

### ISSUE THREAD

**Issue by BlackMarmote** [tobymao/18xx#6523]
https://18xx.games/game/61429?action=240

I have paid 175 for the 40% share of a company. But the report sys I have bought it for 170. It seemed strange to me.

[21:21]BlackM wins bid on CIR for £175
[21:21]BlackM pars CIR at £85
[21:21]BlackM buys a 40% share of CIR from the IPO for £170

I guess this is enough for you to review.
Thank you very much for implementing it.
Francesc

**Comment by scottredracecar** [comment]
I think the comment is focusing on the log item:
[21:21]BlackM buys a 40% share of CIR from the IPO for £170

The bid was won for 175, the payment is 175, it feels like the log should reflect a payment of 175, not the share price of 170.

**Comment by benjaminxscott** [comment]
I think the "buys X director's share for Y" is boilerplate that we should keep the same

perhaps adding another line for "company received X dollars from the bid" would be cool

**Comment by benjaminxscott** [comment]
e.g. 
![image](https://user-images.githubusercontent.com/1711810/142686360-4d95c0be-ba3c-4092-a433-2bbc21f3b6d6.png)

**Comment by scottredracecar** [comment]
It could also say:
BlackM pays £175 for the 40% share of CIR

(On a new line above BlackM becomes president…)

Not great, but also does not break the boilerplate line.

**Comment by benjaminxscott** [comment]
How about this?

![image](https://user-images.githubusercontent.com/1711810/142708041-4cf1755b-dffa-44c8-9b34-daeca450f29e.png)

**Comment by scottredracecar** [comment]
Looks good to me!
