### ISSUE TITLE
 [18Tokiado] Upgrade to E train before last 6 train is purchased

### ISSUE THREAD

**Issue by tommccorry** [tobymao/18xx#6531]
Game ID -62655

https://18xx.games/game/62655

There is one 6 train remaining in Bank Pool. Game allowed a 4 train to be upgraded to an E train then remaining 6 train was exported. This is not allowed in 1830. Not sure if bug or design feature since rules do not site explicit rule (1830 OR 18Ches OR ???) set they are based on.

**Comment by Maxwell-Frank** [comment]
You can trade a 4T in for a D before the second 6 is bought in '30.
