### ISSUE TITLE
18ZOO - ON_A_DIET issues

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#6535]
`https://18xx.games/game/61692?action=262`
The family owning the ON A DIET power was only able to use it.  They could not block off the second open spot on a green city, instead, the power automatically activated and created a third token spot, preserving the open one.  That is not acceptable, token wars **must** happen.

Oh, and the power didn't close, which implied it is a permanent power for the remaining tokens in the company.  Also probably not acceptable, as the rules state "discard the power" after using it.

**Comment by carlorusso** [comment]
Thanks for raising the problem, I'm going to check it...

**Comment by carlorusso** [comment]
ok, I checked, it's a bug.
The power is applied also if the family don't select it; everything happening after is related to that (because it must not happen).
I'm going to work on that...

**Comment by Akado05** [comment]
Okay , thanks for checking and working on this!

**Comment by carlorusso** [comment]
The fix is ready: https://github.com/tobymao/18xx/pull/6540
now it's a matter of merging, and releasing...
