### ISSUE TITLE
1870 - MRCB private not providing bonus home tile in round 1

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6547]
https://gist.github.com/OedipussyRex/152f971b405201e4cea571e31892bfb8.js

Purchase of the Mississippi River Bridge Company is allowed by SSW or MP in phase one. This is implemented correctly, for case of SSW, at least, as indicated by play linked above. 

However, "If one of these two public companies purchases this private company during their first operating round, that company can lay a tile at its starting city _for no cost and in addition to its normal tile lay(s)_." This is not implemented. SSW was charged $60 for its home tile and limited to only two yellow tiles.

**Comment by crericha** [comment]
@OedipussyRex , please link the game data. It can be copied from the tools menu within the game. Thanks!

**Comment by OedipussyRex** [comment]
Does the link above not give the json?

**Comment by OedipussyRex** [comment]
User error on my part. I figured it out. Sorry to waste your time.
