### ISSUE TITLE
[18NY] Companies are startable in SR 1. 

### ISSUE THREAD

**Issue by SamForestBH** [tobymao/18xx#6549]
https://18xx.games/game/63354

No company should be able to be parred in SR1 except for the D&H. However, another player was able to start the NYH in the first stock round.

**Comment by SamForestBH** [comment]
(This is easily recreated in a hotseat game)

**Comment by crericha** [comment]
Thank you for reporting. Please do not par a corporation in SR1 or we'll have to delete your game when the fix gets deployed.
