### ISSUE TITLE
1873 Harzbahn - unable to replace inactive token

### ISSUE THREAD

**Issue by dagibbs** [tobymao/18xx#6552]
In game 61077, replacement of inactive HBE tokens doesn't seem to work.
KEZ should be able to replace the inactive HBE token at E10 -- they have an available token, > 100 moneys, and can reach the hex -- but clicking on the HBE token, or the hex itself, does not result in anything happening.  Clicking on other legal token locations does result in a token being placed.

Continuing the game in hot-seat mode, finds that WBE can't replace the HBE token at D11 either.

**Comment by crericha** [comment]
You are correct. The fix has been submitted.

**Comment by dagibbs** [comment]
Should this fix my running game?  Or only future games?

**Comment by crericha** [comment]
It should be working properly now. Let me know if it isn't.

**Comment by dagibbs** [comment]
It does now -- but it didn't when I posted.

**Comment by roseundy** [comment]
The fix probably hadn't been deployed when you first replied.
