### ISSUE TITLE
18NY - Remove "Scrap" Terminology

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6562]
After discussing with Pierre today, we decided to remove the "scrap" term from the rules as it is more ambiguous than the standard "rust"/"salvage" terms. In the old version of the rules, sometimes scrap meant rust and sometimes it meant salvage. The new terms are unambiguous. The linked draft mass production rules are up to date.

No gameplay change here, just a text replacement. The term salvage is already used in the implementation, so probably just a label change.

I am not sure where all "scrap" appears, maybe just here?
![image](https://user-images.githubusercontent.com/29106780/144267730-f3993349-0347-4c5d-86c0-a7499112ffd2.png)

**Comment by crericha-qualitrol** [comment]
"Trains to Scrap" is hardcoded in the view, so it is not only a text replacement. Thought will need to go into what the interface should look like to provide the name dynamically? Can it simply reuse what the button says or does it need its own method? Investigation is required to answer that question.

**Comment by tobymao** [comment]
agree we shouldn't have dynamic names, it should be a consistent term like corporation

**Comment by scottredracecar** [comment]
Currrently 1840 and 1873 Harzbahn use the scrap terminology--so I guess it can win out.

However, I find "scrap" to be ambiguous in its usage among various games. I think probably "scrap" is a more common translation of the "rust" term we usually use in English 18xx rules. For example, the 1835 translation uses scrap instead of rust, even though there is no "salvage" aspect--it's just the more direct translation of the German than "rust," which is kind of an abstract concept anyway.
