### ISSUE TITLE
[1870] President at cert limit not offered Share protection when share in Brown is sold

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6565]
https://gist.github.com/OedipussyRex/4204c67a4e1deec82c81c193119eb7c3

Shares in the brown (multiple shares can be purchased as a single action, president can hold more than 60%, shares do not count toward cert limit) are sold. President of the sold company is at cert limit and is not given the opportunity for share price protection. The certs do not count toward the limit, so the president has room to purchase even at limit.

**Comment by emknell** [comment]
also hit us here on a yellow share (which should have been able to be protected since it does not count toward the cert limit:

https://18xx.games/game/68421?action=915

**Comment by OedipussyRex** [comment]
Doesn't apply in your case as you were at 60% ownership. You are still limited to 60% until the value goes into the green, which didn't happen until after you were unable to buy the share.

**Comment by OedipussyRex** [comment]
Crap, you are correct. And I know that. Brainfart is the only explanation I can give for that egregious error on my part.

**Comment by JoeB989** [comment]
I plan to allow this for both At cert limit and Over cert limit.

**Comment by emknell** [comment]
I believe that is correct.
