### ISSUE TITLE
[1870] Share Redemption from other player should give the chance to deny the request

### ISSUE THREAD

**Issue by 12thManStanding** [tobymao/18xx#6567]
In the rules for 1870 it states that, "Share redemptions are not forced sales. A player may deny the request to redeem the share." In our current game, the players have not been given the chance to deny the request. The president of the company is always granted the redemption. In our situation, the president of IC was able to redeem a share from 12thManStanding without that player denying the request.

Game ID - https://18xx.games/game/62172

Trigger- https://18xx.games/game/62172?action=682

**Comment by JoeB989** [comment]
It seems like this is an unimplemented feature.  Or does it work sometimes / for some games?

**Comment by JoeB989** [comment]
@roseundy I propose you change this to an enhancement request to implement a missing rule:
Share Redemption should give player the chance to deny the request

**Comment by scottredracecar** [comment]
I would consider this issue a bug as it is required to properly enforce the rules. Enhancements are more like "nice to haves" rather than "need to haves" to play correctly.

**Comment by JoeB989** [comment]
True.  A number of bugs are of the type "game allows player to make illegal move", which is easily solved by player policing.  Can I mark such bugs as lower priority?

**Comment by tobymao** [comment]
there's a label called rules-permissive

**Comment by scottredracecar** [comment]
If it's a rules permissive item that doesn't look like it will get fixed,
we could close the issue and reference it in the implementation notes on
the wiki. Better to focus efforts on bigger bugs if it is a lot of work to
fix something very minor.

**Comment by scottredracecar** [comment]
I don't think this one qualifies as rules-permissive. If the game rules allow a reaction, the implementation needs to handle it or the game cannot be completed correctly.

**Comment by JoeB989** [comment]
I'll remove.  This and a few other issues can be solved by Undo if a player notices the illegal move (and they sure did notice this one ;).  So priority to fix seems low.
