### ISSUE TITLE
The tracker module's can_lay_tile? returns false when a private can be used to lay a tile

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#6571]
can_lay_tile? calls tile_lay_abilities_should_block? to check to see if there is a private that can be used to lay a tile; however, the method only return true if the private doesn't consume a tile lay. The method should be fixed to work with privates that consume a tile lay, provided the operating entity still has an action available.

Any game with tile lay abilities that consume actions have the potential to break in the case where the corporation cannot lay a tile other than with this ability.

**Comment by crericha** [comment]
I tried adding a call to get_tile_lay() in tile_lay_abilities_should_block?, but it broke a number of 1817 games. I took a quick look at one of the games and it broke because the corporation automatically passed due to not having money to lay the tile and the change caused the step to block due to the coal private.

The easier fix is to do the above and naively ask the player to hit the pass button. 

The more involved fix is to determine if the private's ability can be used. There are a lot of factors that go into that and would not be trivial to implement.

**Comment by scottredracecar** [comment]
Do you mean the 1817 game broke because the corporation should have been been offered the opportunity to lay a tile with use of the private? If that is the case, then I think that is a bug with 1817 and worth breaking those games to fix. Even better if the proposed fix also fixes other things in the process.

**Comment by crericha** [comment]
Thinking about this again, the behavior is correct as is. The reason the game automatically passes for the player is because they don't have enough money to pay the cost to lay a tile (e.g. $20 for second lay in 1817). If the private action consumes a tile lay, it would also cost that additional amount. Since we already know the player doesn't have the cash to do that, its safe to automatically pass.
