### ISSUE TITLE
Variable Turn Order Option

### ISSUE THREAD

**Issue by remzelg** [tobymao/18xx#6578]
**What's your idea?**

Variable turn order as an optional feature (Similar to how auto routing is an option upon game creation)

As a short time player of 1870, 1856, & 1862 on this platform, I've been hurting for the ability to make turn order more deterministic, a rule which my group used pretty extensively before playing 18xx digitally.

Example: 1st player to pass in SR1 goes 1st in SR2. 2nd player goes second. etc etc

I think it would add a lot of potential depth to the stock rounds, and as a long time Terra Mystica player (where variable turn order was eventually amended to the rules), I am a big fan of deterministic turn order in general, and think it brings a good dynamic and depth to decisions made during the stock round.

Would love to take a crack at getting started if there is any interest.

Thanks,

Remy

**Comment by tobymao** [comment]
thanks for the interest, but we don't implement house rules. happy to discuss more on slack

**Comment by remzelg** [comment]
Ok understood. Would be happy to work on this if you happen to change your mind.

Definitely a house rule, but a lightweight one that is not disruptive to the core gameplay loop.
