### ISSUE TITLE
New route: /tiles/custom allows entering custom tile input to instantly render it

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#658]
For confirming your string is correct, this would be faster than editing `lib/engine/config/tile.rb` and then visiting `/tile/<tile_name>` to check the work.

In addition to the tile string, the page should allow for controlling the other parameters of a tile

* color
* location name
* city slots reservations
* company blockers

**Comment by scottredracecar** [comment]
Good idea. What about icon? type? group? etc

**Comment by michaeljb** [comment]
Sorry if my original description was unclear, but the groups, etc are handled in what I called the "tile string", I just wanted to specifically list off the parts of a tile that are not handled in that string since they will need more input fields on this page.
