### ISSUE TITLE
Improve wiki page for 1830

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#6580]
Today the 1830 wiki page is not linked from the 1830 games Info tab. So a link for More Info should be added as there are for other titles.

Checking the existing wiki page (https://github.com/tobymao/18xx/wiki/1830) it does lack some. I did today got a question why it was not possible to buy more than one share when in "brown" (that is, from IPO) and this is a rule interpretation that was decided upon by the 18xx.games developers. I think this could be put in "Rules Clarification" or "Implementation Notes". There might be other things to add as well.

**Comment by benjaminxscott** [comment]
Added [notes here](https://github.com/tobymao/18xx/wiki/1830#implementation-notes)
