### ISSUE TITLE
Cloned games retain opponent's "secret" auto moves

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#6584]
Sometimes I clone games in order to test out what might happen next, given what I would do, and what I believe my opponents would do.

However the cloned game data seems to retain my opponent's auto actions. Mostly it's a concern when I can learn their intent to

- Autopass in SR
- Autobuy in SR

And to a lesser extent,
- Autopass in AR or MR ('17 family games) 

It's not a concern if they've just bought the presidency of a company and it doesnt take a great mental leap to assume they're going to finish floating it. 

But it is a concern if **I inadvertently learn a player's going to autopass**, which means I can safely sell my shares without fear of hostile takeover, etc.

**Comment by yoyoson** [comment]
For example, if I'm in a stock round and it's my turn. I might clone a game, I could buy a share. Suddenly I learn that a player to my left has programmed in autopass. I wasn't looking to find that out, I just wanted to see what would happen next. Without trying, I now know something about my opponent's intents that I shouldn't know.

**Comment by benjaminxscott** [comment]
This is an implementation detail that is documented

![image](https://user-images.githubusercontent.com/1711810/144734155-64a438fa-350d-4b5a-aa99-77b1595632f9.png)
