### ISSUE TITLE
1822-likes not loading in local dev environment

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#6585]
Something in a recent commit (e.g. 39d83064a9985a18faab2d56dc13c2cdb06e1fcd) seems to have broken the ability to start/load hotseat games of 1822/variants

Starting after commit d57c955b (the last state that seems to work), loading a hotseat game of 1822 or a variant results in:

> Uncaught error: constructor {name: '[]', message: "undefined method `[]' for nil"

This is using a local setup that seems sane, Linux using docker-compose, after a `make clean` and rebuild

cc @magnusrk-ch - I'm curious if you can repro

**Comment by tobymao** [comment]
i can repro

**Comment by magnusrk-ch** [comment]
Aha, I forgot to test hotseat games while logged out. My bad.
