### ISSUE TITLE
[18NY] 5DE can't select more than 5 hexes

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#6588]
5DE can't select more than 5 hexes

https://18xx.games/game/63342

As a 5DE it should be able to run through as many hexes as it can reach.

**Comment by OedipussyRex** [comment]
I had that happen for the D&H but not another company in a hotseat game.

**Comment by crericha** [comment]
It has to do with running two trains. The bug will be fixed the next time Toby deploys.
