### ISSUE TITLE
[1862] x/y train is erroneously forced to count home token

### ISSUE THREAD

**Issue by otdewiljes** [tobymao/18xx#6591]
https://18xx.games/game/64194

OR5.2 in the ECR turn, ECR ran 2 2/3 trains (inputted manually): London, Witham, Colchester; Colchester, Harwich, sea. 

It WANTED to do (with skipped stations in parentheses):
London, (Witham), Colchester; (Colchester), Harwich, sea 
but the 18xx.games implementation counted:
London, Witham, (Colchester); Colchester, (Harwich), sea
which is 30 less.

It looks like it forcibly counts Witham. The rules explicitly say that it is allowed to skip one's home token when running x/y trains.
(In my original (2008-2012) version, it says so in paragraph 7.8.3 on page 20: "The station not counted in the run is chosen by the company director, can be any of the stations visited, even teh company home base or the only station with a company marker on the route.")

**Comment by roseundy** [comment]
[13:00]ECR runs a 2/3E train for £210: E12-[D13]-C12-C14
[13:00]ECR runs a 2/3E train for £150: G14-F13-[E12]
[13:00]ECR pays out £360 = £36 per share (£252 to Fedor, £36 to oddman, £36 to Boris)

The route being run _does_ skip Witham. This looks optimal to me. How are you able to get more than £360?

**Comment by otdewiljes** [comment]
Aaaand that one's on me for not double-checking the player who made the
statement. Apologies, again, and thanks for double-checking.
