### ISSUE TITLE
[1862] Stock value does not drop when a share is sold when valued at 200

### ISSUE THREAD

**Issue by otdewiljes** [tobymao/18xx#6594]
https://18xx.games/game/64194?action=664 SR7: I&B, valued at 200, is sold; according to the stock market (in the board version as well as the stock market on 18xx.games) the value should drop when at 200 (200 is the highest value at which SV should drop; I suspect there's a < somewhere there should be a <= 200).

**Comment by roseundy** [comment]
The LNER has formed. No price changes occur on sales after this point.

**Comment by otdewiljes** [comment]
Ah! Excellent point; I stand corrected. Sorry for the hassle.
