### ISSUE TITLE
Make auto route option on by default

### ISSUE THREAD

**Issue by neemel** [tobymao/18xx#6598]
Since auto route option when chosen for a game gives a player a choice to use it or not use it, it is better that it is on by default. When it is not on by default, often people forget to turn it on or they don't know anything about it and they are worried that when they choose it, they won't be able to choose their routes by hand.

I believe it is better most of the time to give players options and auto route option does that but only when it is on. When it is off, there is no option to use it. If someone actually wants that players in their game would not use auto route, they can turn it off when creating the game, but I have not seen anyone who would want such a restriction (why would they?).

I know auto route is not perfect, but it much better than spending 30 minutes trying to figure out the the best route by hand! Thank you!

**Comment by tobymao** [comment]
i disagree. auto route by default was a conscious decision. i think routing is a part of the game. if people want to use it, they should turn it on.

**Comment by neemel** [comment]
Think about it. People can decide to use it only when the option is turned on. When the option is off (as by default), nobody can use it, it is just not available.

I think it is better to give players option by default and if someone wants that in their game nobody should use it THEN he/she turns that off FOR THAT GAME. I’ve played hundreds of games on 18xx.games and so far I have never seen anyone who does not want players to use autoroute. But it has happened quite often, that they forgot to turn it on or they believed that once it is on, then everyone has to use it.

/Neeme

**Comment by scottredracecar** [comment]
A compromise would be to set autorouting to "checked" on game setup. Then
if the game owner doesn't want it on, they can "uncheck" it. I think the
vast majority of players want autorouting on.

I would estimate (through observation) that about half of the games have
autorouting on. I would suspect that the other half either forgot to turn
it on or are ambivalent and wouldn't mind it being on.

I do think that forcing manual routing makes for better quality players,
but I think most players want the option because it can be fussy to select
routes on the site, especially on a mobile device. Speaking from personal
experience, I think most of my turns are made in attention-compromised
situations where if I have autorouting to lean on, I can take a quick turn.
But if I can't autoroute, then I have to wait until later to take my turn.

**Comment by neemel** [comment]
Yes, that was exactly my point, but you said it much better! :)

Tervitades, / Best Regards,
Neeme

**Comment by tobymao** [comment]
How is “turning it on by default” a compromise? 

Anyways, this is one of those agree too disagree situations.

**Comment by neemel** [comment]
Because "turning it on" does not actually turn it on. It only gives an
_option_ for players to use it.

When you don't "turn it on", players don't have an option.

That is why "turning it on" is strictly better. Choice vs no choice.

And this brings us to another point about that auto route check mark. Some
players believe that choosing that will force everyone to use auto route
and this is actually not the case.

That is why it should be on by default and the game owner can check a
different box to "turn it off", so that players _cannot_ use it. I imagine
that _very_ few people would choose that option.

Tervitades, / Best Regards,
Neeme

**Comment by neemel** [comment]
Perhaps the option should be called "auto route cannot be used in this
game".

Tervitades, / Best Regards,
Neeme

**Comment by tobymao** [comment]
It’s not a compromise, it’s simply the proposal of the ticket.

**Comment by scottredracecar** [comment]
I originally read the ticket as there is no longer an option (it’s always
on), but I can see this way to read it too.

**Comment by neemel** [comment]
Toby,

I understand that you are against this, but consider this:

1. When autoroute option is off (as it is by default):

Players who want to use are slightly inconvenienced when routes are simple
(autoroute would save clicks) since the player needs to do more clicking.
In this game phase it does not help with choosing the routes, it just makes
it faster.

When routes are complex and take possibly hours to figure out by hand,
those players would need to clone the game, do the autorouting, remember
the routes and transfer those to the real game. Simply a major
inconvenience.

Players who don't want to use it are unaffected.

2. When autoroute option is on (not default):

Players who want to use it can choose to use it.

Players who don't want to use it are unaffected (they can simply ignore it).

Thus I argue that having the option on is superior in every situation as it
removes inconveniences from players who want to use it and does not affect
others. It does not force anyone to use it or in case that it is turned
off, not to use it, so that part is irrelevant really. It is just a matter
of making it more player friendly.

Besides that argument, I think 18xx.games is a wonderful platform and even
having something like autoroute available is awesome, so thank you in any
case for this!

Tervitades, / Best Regards,
Neeme

**Comment by tobymao** [comment]
Hey Neeme,

I think you're missing the case where if auto routing is off, I would consider it cheating or against the spirit of the game to clone the game and to run auto-routing. 

If auto routing is on by default, more people would use it and be frustrated because it's slow and not prefect. I want there to be some barrier to entry to auto-routing because the implementation is not great. If it's opt-in, then people should know what they're signing up for.

**Comment by neemel** [comment]
Hi Toby,

OK, I understand the point about people starting to complain about it not
being perfect. Perhaps a disclaimer next to the button?

About using cloning - I've never been in a game where the game owner has
intentionally banned autorouting. 99% of the time they just forgot to turn
it on and 1% they don't know how it works and thought it is used
automatically when they choose the option (also a good case to add some
explanatory text to the option).

In any case, I'm fine with it being as it is myself as I know how to use
it. Just thought it would help others.

Tervitades, / Best Regards,
Neeme

**Comment by neemel** [comment]
Btw, someone suggested on the site a good solution (if it can be easily
implemented) - add the option on players' profile to turn it on for all
games created by that player. That would solve the biggest problem with
this that I see - people forgetting to turn it on.

Tervitades, / Best Regards,
Neeme
