### ISSUE TITLE
[1862] Error when trying to pass to finish the SR

### ISSUE THREAD

**Issue by ikelly** [tobymao/18xx#6599]
**What's your Game ID?**

https://18xx.games/game/61856

**How to Reproduce the Bug?**

The player whose turn is up clicks Pass which would end the stock round. Reloading does not help, nor does having another player try it in Master Mode.

**Which Browser / Platform?**
Chrome Version 96.0.4664.55 (Official Build) (x86_64)
Mobile and Desktop

**Comment by ikelly** [comment]
I forgot to include the error message, which is "undefined method 'invert' for nil."

**Comment by magnusrk-ch** [comment]
If you look on the map, the town on G6 has no name label. Acle (G6) has lost the association with its hex somehow. The error happens when walking the graph and hitting Acle, which has a nil @tile.hex property.

**Comment by ikelly** [comment]
This could have been caused earlier in the game by the bug that occurred in https://github.com/tobymao/18xx/issues/6543.

**Comment by magnusrk-ch** [comment]
Definitely. If you look at the game link there it has G6 labeled as Stowmarket (actually E10) instead of Acle.

**Comment by roseundy** [comment]
Yes, it looks like the same root cause. The game state is corrupted and I have no idea how it got that way.

**Comment by roseundy** [comment]
Dup of #6543
