### ISSUE TITLE
Show possible upgrades on the tile manifest

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#660]
It would be nice to be able to see which tiles are upgradeable to which on the tile manifest.

I did most of the work on: https://github.com/daniel-sousa-me/18xx/tree/tile-manifest-improvements

The only thing missing is for each "tile name" add something like this to the CSS:
```
div#tile_block_5:hover ~ div.tile_block_upgrades_from_5 {
    background: gray;
}
```

But I don't know how to add css on demand (or if this is even possible). Alternatively maybe this could be done with javascript?

**Comment by jenf** [comment]
Given you cannot hover on mobile, this would be a bad experience on mobile.

I'm going to be refactoring the tile selector code in the next few days. It might be ideal to reuse that
