### ISSUE TITLE
Error when undoing tile lay

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6601]
https://18xx.games/game/63872?action=244

Lay a yellow tile in L27 south toward Miami, click undo, try to lay an upgrade in J27. Results in this error. Reproducible if you clone the game. Occurs in multiple titles, not just 18FL.

<img width="372" alt="Screen Shot 2021-12-07 at 13 14 07" src="https://user-images.githubusercontent.com/8732435/145107221-79e7833a-5f47-430c-bf41-c0a64a3e8c84.png">

**Comment by KevinR1000** [comment]
I'm not convinced this is an undo problem.  Maybe something connected to determing whether a token or tile is being placed?

Trial 1:
* Open https://18xx.games/game/63872?action=244
* Clone game
* Click on J27 (Fort Lauderdale) **_city_**, not hex
* Get error noted above

Trial 2:
* Open https://18xx.games/game/63872?action=244
* Clone game
* Click on any buildable hex (without selecting a tile)
* Without selecting track, click on J27 (Fort Lauderdale) **_city_**
* Prompts for tile selection with no error

(I'm running MacOS with Safari.)
