### ISSUE TITLE
server-side error when loading dev environment

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#6609]
Unsure when it started, getting server-side 500 error when loading `localhost:9292` after running `make clean` and `make`:

This happens on commit 988c853834f27dcf3a200756a35a62ce31924c4d at least

> {"error":"  from <embedded>:1469:35:in `constructor.method_missing_stub'"}

This is using a local setup that seems sane, Linux using docker-compose, after a make clean and rebuild

**Comment by tobymao** [comment]
you should have seen that this was due to your 18fl commit right?

**Comment by benjaminxscott** [comment]
OK thanks I must have not checked against master
