### ISSUE TITLE
Relabel Chesapeake Stock Round header to "Sell then Buy Shares"

### ISSUE THREAD

**Issue by rthomp9595** [tobymao/18xx#661]
suggest small tweak to header for Stock Round in Chesapeake, more aligned with rules if the header reads "Sell then Buy Shares"...just help players intuitively navigate SR

**Comment by ryanespin** [comment]
Is this something for all games or specifically just for Chesapeake?

**Comment by tobymao** [comment]
all games right now but could be configurable

**Comment by ryanespin** [comment]
Cool, made the tweak then for all games. :)
