### ISSUE TITLE
[18Texas] Plain Yellow Track Should be Unlimited

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#6611]
The end of rule 12.2 stipulates that plain yellow track should be unlimited, but we've run out! (https://18xx.games/game/63174?action=405)

**Comment by scottredracecar** [comment]
Will fix later, but I need to know how many to include in the box and I
won't find out if I make them unlimited. So maybe a couple more.

**Comment by Maxwell-Frank** [comment]
I could see at least 5 more straight tiles reasonably being placed in this game.

**Comment by scottredracecar** [comment]
I suggested in PR #6612 that they be bumped up to 30 and then I can check
some completed games later to see how many are needed, around action
400-450.

This particular play is extremely heavy on the straight tiles.

**Comment by scottredracecar** [comment]
BTW, the most recent game change allowed two yellows from the beginning of
the game (rather than starting that in Phase 3), so the amount of yellow
tiles needed should naturally be a bit higher so I guess this is not
completely unexpected.

However, this play might be a bit of an outlier as usually the usage is
pretty even between 8/9--but in this game, the #9s are winning 2:1, even
with 2x#8s burned on the IGN private.

**Comment by scottredracecar** [comment]
I changed the rule so that the tile mix is a hard limit.

**Comment by Maxwell-Frank** [comment]
Did you set the hard limit to the tile manifest we were already using, or did you expand it at all?

**Comment by scottredracecar** [comment]
Left it for now, but open to changes if it is a persistent ”issue” and not just an outlier.

**Comment by scottredracecar** [comment]
@Maxwell-Frank I see that balance has been restored. The #9 tiles were short during 5.2 (of 2) but were available from 6.1 (midway) from then on. Do you think more than 20 #9 tiles need to be supplied? You seemed concerned about running out. I don't necessarily mind restoring the unlimited yellow tile rule for the final game. Still undecided about that.

The point in 6.1 where the tiles are available is here:
https://18xx.games/game/63174?action=474

**Comment by Maxwell-Frank** [comment]
@scottredracecar I _did_ run out of #9 tiles at one point.  I had to change a track lay due to a lack of tiles.  I think restoring the unlimited yellow tile rule would be good, unless you want plain track shortage to be a part of gameplay.  20 physical tiles is probably fine, if our game was truly an outlier in the number of straight track used.

**Comment by scottredracecar** [comment]
Okay, thanks. I see pros and cons of both ways. Probably will end up going with unlimited in the end (but not during playtesting) to be consistent with 18Chesapeake and 18NewEngland--though I'm pretty sure 18Carolinas will keep the limited tiles.
