### ISSUE TITLE
Can't load game of 1861

### ISSUE THREAD

**Issue by ulrichvonbek** [tobymao/18xx#6616]
https://18xx.games/game/63034
multiplayer game

browser - Microsoft Edge
Version 96.0.1054.43 (Official build) (64-bit)
Running on a desktop

Closing and reopening the browser didn't help; all my other games, including another 1861, seem just fine.

**Comment by tobymao** [comment]
@magnusrk-ch 

{"type"=>"program_merger_pass", "entity"=>10304, "options"=>[], "entity_type"=>"player", "corporations_by_round"=>{"MR"=>["KK", "MV"]}, "id"=>234, "user"=>10304, "created_at"=>1638417222}
deps.js:20164:143
Uncaught 
Object { name: "KeyError", message: "key not found: \"AR\"", cause: {…}, receiver: {…}, key: "AR", backtrace: [], stack: "" }
