### ISSUE TITLE
[Harzbahn 1873] Public mining company cannot buy a mine previously closed by a player

### ISSUE THREAD

**Issue by DarthIA** [tobymao/18xx#6618]
Mine 9 is listed in the entities tab as closed, but public mining company cannot choose any mine to add, even though it has enough money and a free slot. Previously in the game I could buy closed mines, but maybe in this case the difference could be that Mining Co. 9 was previously owned by another player who closed it before.

For reference, the concrete step where this is not allowed is https://18xx.games/game/61517?action=887

![image](https://user-images.githubusercontent.com/24686708/145591956-d6126458-ee9b-4d6b-88e7-dccf2a5de7db.png)

**Comment by roseundy** [comment]
HW can only form from and buy Vor-Harzer mines. Mine #9 is not a Vor-Harzer mine.
