### ISSUE TITLE
[18NY] Cannot purchase train despite having funds to do so after salvage

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#6620]
https://18xx.games/game/64096?action=751

I have just enough to purchase a D after salvaging my last 6H, however the game thinks I have $981 instead of $1004 as shown in the company treasury. No loans/shares were sold/issued. $981 is a particularly strange number given that pre-salavage I only had $929, unclear where it is getting that figure from.

**Comment by crericha** [comment]
I can't reproduce in a hotseat game, so I think its a rounding issue on the server side (Ruby and Javascript round different). Probably not related to the train salvage, but something earlier. I'll have to dig more.

**Comment by pstone1** [comment]
If helpful, here is what I see in game: 
![image](https://user-images.githubusercontent.com/13589848/145731530-f14beaa1-61b6-4e4a-b9c9-1d3fab0fc0bf.png)
It says that for a second or two, then reverts back to before the purchase.

**Comment by crericha** [comment]
The server doesn't think D&H got the Ottawa connection bonus. I'm looking into why.

**Comment by crericha** [comment]
string vs symbol issue as I suspected. Fix incoming.
