### ISSUE TITLE
[18NY] Game id: 64767 "Loading Game..." freeze after attempted 12H purchase.  2 player game.

### ISSUE THREAD

**Issue by g3lutz** [tobymao/18xx#6622]
**What's your Game ID?**
Game id: 64767

https://18xx.games/game/64767

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

"Loading Game..." freeze after attempted 12H purchase.  

Ipad Chrome
Tablet

**Comment by benjaminxscott** [comment]
last working action is `https://18xx.games/game/64767?action=573`
error:
> undefined method `choices' for <Engine::Game::G18NY::Step::BuyTrain

**Comment by crericha** [comment]
The crash happened because the stagecoach token was replaced during the merge. It should have been automatically transferred to the new company instead. I'm afraid the game won't be recoverable.

**Comment by crericha** [comment]
Actually, we may be able to undo your last action and then you can undo to just before the 5 merges into the NY&H. If you do that before the fix is deployed, you can continue the game from there.

**Comment by crericha** [comment]
@g3lutz, will you be around to undo your game prior to the 5 merging? If so, I will have Toby do it, but we'll need to coordinate so your game is back to that spot before the fix is deployed. Otherwise, your game will be broken.

**Comment by g3lutz** [comment]
Thanks guys, we started another.  I am glad you got it fixed.


Sent from Yahoo Mail for iPad


On Sunday, December 12, 2021, 6:42 PM, Chris Rericha ***@***.***> wrote:




@g3lutz, will you be around to undo your game prior to the 5 merging? If so, I will have Toby do it, but we'll need to coordinate so your game is back to that spot before the fix is deployed. Otherwise, your game will be broken.

**Comment by crericha** [comment]
Okay. Thanks for reporting the bug.
