### ISSUE TITLE
[1825] 4+4E trains aren't doubling correctly

### ISSUE THREAD

**Issue by DestrinStorm** [tobymao/18xx#6629]
https://18xx.games/game/60178?action=1877

Pick ANY 4 legal cities for the 4+4E, it will behave like an E in that it can run to an unlimited number of cities, but it's not correctly handling the + part of the train and doubling the resultant income

**Comment by roseundy** [comment]
D'oh! Typo in train definition:
`multipler: 2,`
should be:
`multiplier: 2,`
