### ISSUE TITLE
18NY unable to issue shares during EMR

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6642]
The 18NY rules are clear that you have to buy the cheapest train if the corporation takes loans or the president contributes. However, the company is allowed to sell its own shares from treasury to buy a more expensive train. In this example, the NYNH should be allowed to sell shares to buy the 5DE train.

https://18xx.games/game/64060?action=671

**Comment by crericha** [comment]
The rules state "A Share Company which is required to own a train but cannot afford it...undergoes Emergency Money Raising." Technically, you can afford a train and EMR doesn't apply; however, I do think you are correct and the rules need clarification. I will push the fix and also double check with Pierre.

**Comment by ChrisTheCat** [comment]
Yes, I've played with Pierre and I'm 95% (not 99%) sure my interpretation
is how he taught us.

**Comment by crericha** [comment]
In case anyone looks back, I did confirm with Pierre that the bug is correct. We are updating the rulebook.

**Comment by ChrisTheCat** [comment]
Ah, well, thanks for getting the rulebook updated, though it does mean that
instead of buying a 5DE I get to go bankrupt...

**Comment by crericha** [comment]
I mean that your interpretation is correct. The bug is a real bug.

**Comment by ChrisTheCat** [comment]
Oh, I completely misunderstood you. In that case, I think the rulebook is
already correct.

**Comment by crericha** [comment]
I think "A Share Company which is required to own a train but cannot afford it...undergoes Emergency Money Raising." is unclear. I can see people arguing that in your case, you can technical afford a game, so EMR doesn't apply; however, it is meant to say you can go to EMR if there is any train you can't afford that is available.

**Comment by ChrisTheCat** [comment]
Ah, I see.
