### ISSUE TITLE
1828 C&P private blocking of hex C15 not enforced

### ISSUE THREAD

**Issue by JEBrosius** [tobymao/18xx#6658]
In game https://18xx.games/game/64996?action=329, the program allows the OSH to upgrade C15 even though the C&P has not been bought in and the privates haven't gone away.

**Comment by benjaminxscott** [comment]
I can't repro on hotseat (trying to upgrade C15 states that it's blocked), but perhaps this is something that only happens on live?

**Comment by JEBrosius** [comment]
That may be.  We were of course playing live, as you suspected.

**Comment by crericha** [comment]
The game will show you the tile upgrades, but if you select one, you should get an error message like the one @benjaminxscott posted. @JEBrosius, did you select one and the game did not show an error?

**Comment by JEBrosius** [comment]
Thanks, Chris.  The game shows you the options but then provides an error message when you try to go through with the selection.  We stopped too soon.  However, it would be better if it displayed the error message when you tried to select an upgrade.

In a related situation, when you are operating the C&P, it allows you to choose a route that does not include the tile just placed, and then give you an error later.  Again, it would be better to display the error message sooner.

But the main issue is resolved.

**Comment by crericha** [comment]
@JEBrosius, both of your suggestions make sense. Please submit an enhancement request for each.

**Comment by tobymao** [comment]
they require games to process actions, i’d classify it as won’t fix

**Comment by crericha** [comment]
For routes, they are already preprocessed every time a new node is added to the route in the UI. @game.revenue_for and @game.revenue_str are called.

For blocked hexes, we should simply return false from available_hexes, so it is clear you can't build there.

I'll do both after I finish up what I'm currently working on. I need enhancement suggestions to remind me.
