### ISSUE TITLE
1870 crossing the Mississippi River before the bridge private is purchased

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6659]
https://18xx.games/game/64871?action=160#map

<img width="203" alt="Screen Shot 2021-12-22 at 06 48 29" src="https://user-images.githubusercontent.com/8732435/147110709-fe22dd26-ddfc-4289-82be-9a7aaf0539c1.png">

MP crossed the river while Hobie still owns the Mississippi River Bridge private company.

**Comment by JoeB989** [comment]
Probable duplicate of #6331, keeping open because this involves MP home city and first turn
