### ISSUE TITLE
UI color controls -- more granularity wanted

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#666]
The UI/map colour pane is a nice addition.  

Unfortunately, the current UI changes only affect the main background and text colours, which makes the light grey textboxes with black text quite bright against the UI.  

Feature request: add two more boxes for the 'secondary' background & text colour to be inherited by the various currently-grey boxes: The front page chat, the company banners, the game chat, and any other place currently using a medium-grey background.  

___
It would also be nice if the various map colour boxes were labelled with what they represent--it's not obvious which is the background/empty hex/etc. colour without paging back and forth into a game.  Perhaps a dummy map could be added to the screen?

**Comment by yzemaze** [comment]
> add two more boxes for the 'secondary' background & text colour to be inherited by the various currently-grey boxes: The front page chat, the company banners, the game chat, and any other place currently using a medium-grey background.

… and buttons. Already on my todo list.

> It would also be nice if the various map colour boxes were labelled with what they represent--it's not obvious which is the background/empty hex/etc. colour without paging back and forth into a game. Perhaps a dummy map could be added to the screen?

The info is given in the hover text, albeit white instead of plain and red instead of offboard isn’t ideal. I’ll change this.
A dummy-map right in the settings is still on my todo list – with low priority.
