### ISSUE TITLE
[18NY] Takeover share company

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#6661]
NYC should be able to take over RWO here: https://18xx.games/game/64556?action=985 However I get “0 is not a valid amount to spend” because for some reason it wants to pay Jin 0$ (Jin has no shares so should not be paid at all)

**Comment by crericha** [comment]
Apparently you can be a shareholder with zero shares. Who knew I had to handle that case lol. I tried to change the base logic to delete shareholders that have no shares, but it broke a bunch of other games, so patched it up here.
