### ISSUE TITLE
[18NY] Player can't sell up to 50% in market

### ISSUE THREAD

**Issue by mbolohan** [tobymao/18xx#6662]
**What's your Game ID?**

https://18xx.games/game/65204

Action where player could only sell two shares of NY&H but should be able to sell four:
https://18xx.games/game/65204?action=735

**How to Reproduce the Bug?**

Unsure, this is my first game of 18NY and I didn't try to reproduce.

**Which Browser / Platform?**
Chrome Desktop 96.0.4664.55 (Official Build) (x86_64)

**Comment by crericha** [comment]
18NY is a little different here from most 18xx games. The market cannot contain more shares than player held shares.

Thanks for reporting. It's better to get a bug report and find out that it isn't a bug than not know about a bug.

**Comment by mbolohan** [comment]
The rules read to me that a player can sell up to 50% in market, and only a company is restricted by the number of player-owned shares when selling [1]. Is there another rule I should find that clarifies this? I can leave a comment in the rules if it's an issue with understanding.

[1] A player may not sell shares to cause more than 50% of a company's stock to be in the Bank Pool, and a Company may not sell shares to cause more shares to be in the Bank Pool than are held by players

**Comment by dfannius** [comment]
Reopening to ensure this is resolved one way or another.

**Comment by dfannius** [comment]
Actually, selling 2 shares brought the market up to 50%, so the limit was correct (by that same rule).

**Comment by scottredracecar** [comment]
NY&H, not NYNH

**Comment by scottredracecar** [comment]
We got clarification from Pierre that the pool limit constraint is max shares in players' hands. I made a rule update suggestion in the linked rules.

So as far as I can tell, this issue can be closed now as selling more than two shares of NY&H will cause the limit to be exceeded. Feel free to comment more if this needs to be reopened.
