### ISSUE TITLE
Game 1930 - Ehime Railway purchase not allowing a second tile lay for UR

### ISSUE THREAD

**Issue by BooStGeorge** [tobymao/18xx#667]
I want to buy the Ehime Private, update C4 then as the company lay another piece of track. The game is not letting me lay the C4 piece on purchase (unless I'm missing something) and treating this lay as the corporation track lay for the turn. Thanks

**Comment by jenf** [comment]
Boo, got a game id?

**Comment by jenf** [comment]
You probably need to select the company, then go to map view to lay the special.
(It's not the best UI on this part)

**Comment by BooStGeorge** [comment]
Yes that worked ! PICNIC issue (Problem in Chair, Not in Code)
