### ISSUE TITLE
[1825] Unable to lay track, game reports error coercing a nil into an array. 

### ISSUE THREAD

**Issue by Tim-LaunchDarkly** [tobymao/18xx#6670]
**What's your Game ID?**
https://18xx.games/game/65812

https://gist.github.com/Tim-LaunchDarkly/1ce913ecf60d9600362f13a988b7b1dc

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Steps leading to this situation-
1st OR in set, LNWR ran ahead and paid out. GWR to run, elects to lay two tiles, S11 tile, submitted and accepted, and X12, laying a straight (#9, 3 remain in stock).

Expected behavior, it accepts the lay because it is not adjacent to previously laid track this round.
Actual behavior, ![image](https://user-images.githubusercontent.com/28875319/147372782-dc9e5d36-2c28-473d-901d-ff4261791d4e.png)

**Which Browser / Platform?**

 Chrome Version 96.0.4664.110 (Official Build) (64-bit) (tested on my computer, I turned on master mode. Win10) Also tested on an android phone.

**Comment by roseundy** [comment]
Unfortunately, this doesn't fail in hotseat. This will take me a bit to debug in server mode.

**Comment by roseundy** [comment]
I'm sorry, I can't reproduce this even in server mode.

**Comment by tobymao** [comment]
@roseundy to confirm, you have latest master and rebuilt everything clean?

**Comment by Tim-LaunchDarkly** [comment]
Can confirm that I was unable to reproduce in hotseat mode. :(

**Comment by roseundy** [comment]
Yes, pulled latest and did a make clean
