### ISSUE TITLE
[1862] Permit icons

### ISSUE THREAD

**Issue by chanmancan** [tobymao/18xx#6672]
**What's your idea?**
Add permit icons to map so you don’t have to memorize. Will improve parsing map at beginning of game.

**Comment by roseundy** [comment]
Are you talking about a legend? There are already icons on the map showing what types of permits each company starts with.

**Comment by chanmancan** [comment]
Yep a legend that has the word for each permit. If I don’t play a game for a while I have to go look it up. Would be nice if it was there near the map.

Chandler

**Comment by Maxwell-Frank** [comment]
It's in the implementation notes in the Wiki:

`The above icons on the map are coded with outlines to indicate starting permit type and availability for starting. Local permits have a diamond outline, express permits have a circular outline, and freight permits have a hexagonal outline. The outline is in white if the company is available for starting and black if not.`
