### ISSUE TITLE
[18SJ] Non E trains allowed to go through SJ token.

### ISSUE THREAD

**Issue by SLOFila** [tobymao/18xx#6676]
https://18xx.games/game/65110?action=656

My Corp has an E train and a 6 train. However if you look at the route, the 6 train is able to go through an SJ token while I believe that only the E train should be able to do it.

**Comment by perwestling** [comment]
You are correct. I think the implementation is so that the SJ-blocking-rule is temporarily disabled when a corporation owning an E train starts their OR. Which means that the 6 train will work as a 6E.
So the implementation is incorrect. 

Have to investigate if this can be solved in a better way.

**Comment by SLOFila** [comment]
I want to add to something to this.
I have also discovered that I can build through the SJ blocked city. For example in the same game above, the E22 tile. I can't find anything in the rules allowing me to build through an SJ blocked city even if I own an E. It only says the token blocks for the purposes of route laying.

So either there's something I'm missing in the rules or the implementation is tied to what you just mentioned where having an E in the corp suddenly makes the SJ tokens act like regular corp tokens.

**Comment by perwestling** [comment]
I believe SJ tokens should block builds, so, yes, the implementation is not correct. A fix should probably correct both these problems.

**Comment by perwestling** [comment]
Have made a bug fix which is submitted for approval.

Have now changed timing a bit, so the temporary making of SJ tokens passable, is done after tokening step. So this will not affect tile laying or tokening.

Also added check of non-E routes so that they do not passthrough cities which has been made passable.
