### ISSUE TITLE
Turn notification feature ideas: tab titles (1)

### ISSUE THREAD

**Issue by Suhar** [tobymao/18xx#668]
Feature idea - since the system does not send an email for turn notifications while a tab is left open, could we have a more prominent visual for when it is your turn? Ideas include:

1) Include a notification within the web page tab title, like gmail's "Inbox (1)" notification
2) Add color pane, or "it's your turn" button.
3) have setting for enabling a ding sound (like an IM coming in)

**Comment by tobymao** [comment]
we already do #1, a * is shown when it is your turn, notifications is already a ticket. 

the title used to flash your turn but someone claimed it was too distracting

**Comment by Suhar** [comment]
Oh! Thank you.
