### ISSUE TITLE
[1849] Allowed to not run trains while having valid routes

### ISSUE THREAD

**Issue by cheesinglee** [tobymao/18xx#6682]
**What's your Game ID?**
Multiplayer game id 66506. [Action 463](https://18xx.games/game/66506?action=463)

[gist](https://gist.github.com/cheesinglee/ac2645a71655e6c189ce408a45d8842d)

**How to Reproduce the Bug?**

In OR9.2, IFT had a train and a route, but was permitted to not run. This seems to be in contradiction to 10.5.2 in the AAG rules: 

```
The  highest  legal  revenue  that  can  be  demonstrated  must  be  collected, 
although sharp-eyed players are not required to point out a higher possible revenue than claimed.
```

**Which Browser / Platform?**
I'm on Firefox 91.4.1(esr). Don't know what the other players were on.

**Comment by dfannius** [comment]
There is intentionally no formal mechanism on 18xx.games for other players to insist on a set of routes that produce a higher revenue. You have to do it through chat and undo.
