### ISSUE TITLE
1867 - Must use 63 tile when possible?

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6687]
I don't know what the current intended rule is, but Steve and I were noticing that 1867's implementation (and therefore 1861 as well) may not have the rule that enforces the 63 tile to be used when possible. Here is the rule from the AAG 1861 rules at the end of 10.4.

Sorry for the lack of detail on this, but I don't want to get into rule edition differences and am making this stub issue with the hopes that someone else can take it on.

![image](https://user-images.githubusercontent.com/29106780/147783926-f21aadca-8f85-4e76-b62e-0799524386b3.png)

**Comment by roseundy** [comment]
This is listed as an errata on a 61/67 Kickstarter update: https://www.kickstarter.com/projects/joshuastarr/1861-russia-1867-canada/posts/3111682

**Comment by crericha** [comment]
Do you have a game link? I changed the max exits code recently and may have broken it.

**Comment by scottredracecar** [comment]
Turns out I can verify it working properly here:
https://18xx.games/game/66678?action=475

No bug
