### ISSUE TITLE
18Mag mining icons missing from map

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6689]
https://18xx.games/game/66478?action=43

Yesterday, the mining areas were marked with an icon. Today, they look like tokenable empty cities.

**Comment by roseundy** [comment]
??? They look fine to me.

**Comment by roseundy** [comment]
Loading your game shows this:
![18Mag_Mine_Pic](https://user-images.githubusercontent.com/8494213/147834349-a2e0ae05-73c9-4a04-b8a9-2d755445f55a.png)

**Comment by ChrisTheCat** [comment]
I see this

<img width="1121" alt="Screen Shot 2021-12-31 at 09 42 24" src="https://user-images.githubusercontent.com/8732435/147834369-76b81dad-cc2b-42e0-b9fc-606cbd56f7c7.png">

**Comment by ChrisTheCat** [comment]
Logging out and clearing the cache fixed it.

**Comment by roseundy** [comment]
Going to close.

**Comment by cfcurtis** [comment]
Checking "simple logos" causes the mine tokens to disappear for me, uncheck and they reappear. I can open a new issue if that would be better.
![image](https://user-images.githubusercontent.com/282731/157780385-29cc7ab2-8d92-42f7-9f70-d4cbcdbf7748.png)
![image](https://user-images.githubusercontent.com/282731/157780422-53bd6dde-e75f-4175-89bb-bc157d197390.png)

**Comment by ChrisTheCat** [comment]
Ah, that explains it!
