### ISSUE TITLE
[1870] - Missouri Pacific and Southern Pacific  Floating at top of board brought down to the same number on the right

### ISSUE THREAD

**Issue by Hylndur101** [tobymao/18xx#6692]
**What's your Game ID?**

66791

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

**https://18xx.games/game/66791**

**How to Reproduce the Bug?**

When these two railroads were set to fload upward, they were brought down to the next line, one row down (specifically for southern pacific - We were able to sell it out the turn it started.  It was started at 100. At the end of the stock round, and it went to float, it went to the right and down 1 to the 100 there. 
![image](https://user-images.githubusercontent.com/81931661/147843773-e04f9cae-efc5-419e-8109-d7e9bbbb7eb4.png)

What steps cause the unexpected behavior?

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**

Chrome is up to date
Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by crericha** [comment]
Per the rules, a sold out company at the top of the stock market move one spot right and one spot down. I think that's what you are describing and if so, that's correct behavior. Did I misunderstand?
