### ISSUE TITLE
Add BGStats Import button to finished games

### ISSUE THREAD

**Issue by secabeen** [tobymao/18xx#6693]
**What's your idea?**

It would be nice to have a [BGStats Import button](https://www.bgstatsapp.com/support/push-plays-to-bg-stats-from-other-apps-or-websites/) generated once games have finished.  Would help me track my 18xx plays greatly.

**Are there related ideas?**

Other similar play tracking sites (or BoardGameGeek directly) could also be supported, but BGStats is the most commonly used app/tool.

**Did you join the Slack?**

Yes, been there for a while.

**Comment by tobymao** [comment]
dup
