### ISSUE TITLE
Game 61125, able to run route through blocked token in Denver.

### ISSUE THREAD

**Issue by chanmancan** [tobymao/18xx#6695]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**
61125, 1817NA
If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/61125

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Was able to run route through Denver though the company was blocked. See images:

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by chanmancan** [comment]
![A3026B14-C013-44B0-AE52-23B4BE00DA24](https://user-images.githubusercontent.com/96640844/147865218-b8b55615-48df-49eb-b59e-81db26478efc.png)
![D12DE28D-7568-4471-9FA5-6FCA16A3FBE4](https://user-images.githubusercontent.com/96640844/147865220-3f91557d-81e2-46b0-87c8-96c8d91008e3.png)

**Comment by crericha** [comment]
Did you try to submit the routes? Did it work?

**Comment by chanmancan** [comment]
Yes it did work, but I hit undo when I realized I was able to go through the blocker. Usually it says route not connected, but this one allowed me to run and end my turn.

Chandler

**Comment by crericha** [comment]
I was able to reproduce in a hotseat game.

**Comment by scottredracecar** [comment]
I don't know how to reproduce this, please reopen if you know what action this happened on.
