### ISSUE TITLE
[1825] Tile 200 is incompletely implemented.

### ISSUE THREAD

**Issue by markgeary** [tobymao/18xx#6699]
A hex upgraded with tile 200 gets the extra piece of track, but the other properties of that tile don't appear to be implemented. The owner of the Base Station on the tile should be able to run through the hex without counting the Station.

The text in K6 (and D1) says: 

> Through Station Tiles [tile 200] become available in Phase 3. Trains may be run through a Base Station that has been promoted with one of these Tiles, if desired, without it being a revenue earning Station and Routes may be calculated with the promoted Base Station having no effect on either Route length or earnings. A Train passing through one of these Stations as part of a Route may consider it to be a Base Station with respect to Rule 4.5.2. irrespective of whether or not it is being counted for revenue earning purposes.

**Comment by roseundy** [comment]
Obviously I missed that section of the rules. This may take a bit to implement since I'll have to calculate whether to include the stop on a train route based on what other stops exist. It will likely interact with some of the train-specific code.

**Comment by roseundy** [comment]
Now I know why I missed this. I don't have a copy of K6, so I've been going off a picture of the kit on BGG. It turns out it was only a picture of the first page of the rules. I didn't realize there was a second page. The first page makes no reference to being able to run through the station without counting it.

**Comment by roseundy** [comment]
Example game with 200 tiles laid https://18xx.games/game/63391

**Comment by roseundy** [comment]
This isn't completely fixed. It won't work correctly in the the only base that is tokened by the company is on the 200 tile.
