### ISSUE TITLE
18Texas IGN private/blocked hexes--unable to lay

### ISSUE THREAD

**Issue by discoking7** [tobymao/18xx#6700]
Game 66785
https://18xx.games/game/66785

I hold IGN and presidency of currently operating company.  It is phase 3.  When I attempt to lay D3, I get message, "D3 is blocked by International-Great Northern."  I have verified that I should be able to place tiles in the blocked hexes, and there does not seem to be a way to do this.

Browser is Firefox version 95.0 (64 bit).

Thanks!

DK

**Comment by scottredracecar** [comment]
You will need to activate the private company to be able to lay there, but I see that isn’t showing up. We’ll look into it.

**Comment by scottredracecar** [comment]
Simple demo game where the private company owners are running companies that should be able to use the special private powers for testing later.
https://gist.github.com/scottredracecar/ed8e922eacb2587597e8359578597d41
