### ISSUE TITLE
Proposal for faster multi-train auto-routing on complex maps

### ISSUE THREAD

**Issue by JoeB989** [tobymao/18xx#6706]
I'm noticing that auto routing is slow with with multiple trains on a late-game map (1870 in my case).  I'm attaching a sample game state for reference.  It takes 55 seconds to auto-route MP with a 5 and 6 train!
https://gist.github.com/JoeB989/a6a6746ec57de438a1dcdae7a9f097ca

Coincidentally this is a problem I've spent effort optimizing in my own 1870 and 1856 games (in C#).  I took a look at your route.rb and auto_route.rb but of course they're very different than my procedural C# background.  Still I gather that walking lists of nodes is where the bulk of time is probably spent.

In my case I found that building the lists of possible routes was fast, but comparing routes to see if they conflict - for multiple trains - was where the bulk of the time was spent.  It's noteworthy that all possible routes must be compared, since the highest payout may come from running a shorter route on the longer train.

My optimizations focused on devolving route node lists into bit arrays (really dword arrays), each hex-to-hex track connection being represented by a bit, so instead of walking lists to see if routes A and B share a hexside track connection, I just AND two bit arrays and check for not 0.  This was a many-orders-of-magnitude improvement for severe cases like late-game 1856 CGR with multiple diesels, where most routes do conflict with the other trains' routes.

I have no idea what damage this change would do to your existing code :)  Is anyone up for an experiment?

Let me know if you'd like more details, or to see my C# code.  (Great platform by the way, I just discovered 18xx.games)

**Comment by tobymao** [comment]
closing for now as i don't think this will really make much of a difference, i'm happy to be proven wrong so if you want to make a PR feel free, I'm happy to help you out. you can also come to slack channel to discuss further in detail.

the main reason i believe auto routing is slow is because of the overhead of opal, opal is 4-5x slower than ruby and so anything compute intensive is pretty painful.
