### ISSUE TITLE
18NewEngland Map Fixes

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#672]
I loaded the 18NewEngland map. Several map changes that are needed.

- [ ] Hex B4 doesn't render. I have no idea why. It is the same design as A13 which renders fine.

- [ ] The "0" looks funny here. It is a "-" in the board game version. It is unrunnable, but is included for completeness sake. It would also be okay to just drop the yellow.
![image](https://user-images.githubusercontent.com/29106780/84207491-1cd87780-aa77-11ea-9bb8-188e20bb426e.png)

- [ ] Off-board cities have text labels that conflict with the city (F2, C19).

![image](https://user-images.githubusercontent.com/29106780/84207539-38dc1900-aa77-11ea-8cf3-0b1706b032e9.png)

- [ ] Additionally, F2 and C19 are supposed to render as spikes that go into a city. This is different than Pittsburgh in 18Chesapeake because there are 2 or 3 spikes to the cities and the spikes show that you cannot run through the city.

![image](https://user-images.githubusercontent.com/29106780/84207674-85bfef80-aa77-11ea-9715-5c0878b9b752.png)

- [ ] L4 and N4 are supposed to look like this, but the can't render in this configuration so I left them as basic city/town with no paths.

![image](https://user-images.githubusercontent.com/29106780/84207725-a720db80-aa77-11ea-8650-9f5ec4d33d17.png)

- [ ] These render a little too close for comfort--they are not supposed to connect to each other.

![image](https://user-images.githubusercontent.com/29106780/84207814-db949780-aa77-11ea-8e56-4c1146d8732f.png)

**Comment by roseundy** [comment]
I think most, if not all, of these rendering issues are fixed (or can be with suitable tile definition changes).

**Comment by scottredracecar** [comment]
@roseundy yes, I fixed these now with definition changes. Thanks for the work.
