### ISSUE TITLE
18NewEngland - IPO shares not capitalizing company

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6721]
Shares bought here should put money in the company treasury, but are not.
https://18xx.games/game/67676?action=235

**Comment by jtamplin** [comment]
We ran into that here as well - we had to roll back to that point and just not buy the additional share.

https://18xx.games/game/67683

**Comment by scottredracecar** [comment]
Buying shares from the IPO during an SR does work, as in this action:
https://18xx.games/game/67676?action=246

**Comment by jtamplin** [comment]
Sure, but then you have to wait until the SR to fund the company.

**Comment by scottredracecar** [comment]
Yeah, just trying to help Steve troubleshoot. It will be fixed.
