### ISSUE TITLE
18NewEngland - tiles X6 and X9 should have 3 slots

### ISSUE THREAD

**Issue by jtamplin** [tobymao/18xx#6724]
https://18xx.games/game/67683#tiles

The tiles show 2 slots, but the green tile they upgrade from and the tile manifest in the rules show 3 slots.

**Comment by jtamplin** [comment]
Once this is deployed, will existing games get the fix or are they toast?

**Comment by scottredracecar** [comment]
I think in this case, it will get fixed.

**Comment by roseundy** [comment]
They will just be fixed.
