### ISSUE TITLE
18NewEngland - buying an IPO share isn't an option when it should be

### ISSUE THREAD

**Issue by jtamplin** [tobymao/18xx#6726]
https://18xx.games/game/67683

https://18xx.games/game/67683?action=304

- if a company's par value is higher than your cash, you can't buy an IPO share even if the current price is less than your cash

**Comment by roseundy** [comment]
In addition to fixing this, I will rework how IPO shares appear on the corporate card. Right now it looks like you pay the par price when you buy it.
