### ISSUE TITLE
18MS - incorrect Shares count shown

### ISSUE THREAD

**Issue by jtamplin** [tobymao/18xx#6728]
https://18xx.games/game/67702?action=147

I have 70% L&N, 20% GMO, 10% Fr, and it shows 10 shares but should be 11.  The other players properly indicate the extra share from the presidency.

**Comment by scottredracecar** [comment]
I count 10:
6 L&N
2 GMO
1 Fr
1 private

**Comment by jtamplin** [comment]
Just realized that - the actual bug was showing the share count at 10/10, but that was because the private company was still open.
