### ISSUE TITLE
[1825] Unsold U3 trains incorrectly block purchase of 6

### ISSUE THREAD

**Issue by thepackrat** [tobymao/18xx#6733]
GameID; https://18xx.games/game/64648

**How to Reproduce the Bug?**

During a game of 1825 including phase 4 (K3) + advanced trains (K2) , having a company with enough cash to purchase a 6 (>650) while there was a U3 train left unsold, did not offer the 6 as a train available to purchase, blocking phase 4. In this particular game, the company is SECR.

From the printed 1825 K2.1 rules (it is identical in the K2 rules)

"Unsold trains of type '3T' and 'U3' do not prevent the purchse of a '6' train and the consequent introduction of Phase Four. Any unsold Trains of these types then remain available for purchase as alternatives"

**Which Browser / Platform?**

Mac and iOs, but this is a game logic bug.

**Comment by roseundy** [comment]
Sadly, this bug also affects which trains are offered for leasing. The good news is that the fix shouldn't cause games to be archived :-/

**Comment by thepackrat** [comment]
Yeah. I noticed that but didn't pay enough attention to go digging. I have a fix in flight.

**Comment by thepackrat** [comment]
I've got a fix which marks trains as non-blocking rather than reordering them.

**Comment by thepackrat** [comment]
https://github.com/tobymao/18xx/pull/6735
