### ISSUE TITLE
[1825] promotions over pre-printed green track treated as lays

### ISSUE THREAD

**Issue by thepackrat** [tobymao/18xx#6737]
I just managed to lay Bristol (russet over pre-printed green) and a yellow tile on the same turn. This conforms to the lay rule permitting two tiles laid. (local game, I don't have a gameid right now)

From my rules.

4.3.6 Some special green tiles are resevred for specific locations, These are the #52 green Tiles showing two separate large stations ... .Nnote that the use of these Tiles is a Tile 'lay' not a promotion and has to comply with rules 4.2.2 to 4.2.8

so, yellow OO hexes to green lay, is a 'lay' and can be combined with another yellow

4.3.7 "The green hexags on the Board are deemer to represent Tiles already i mplace. In Phase Three these green hexags by be replaced by overlaying them with speical russet Tiles . .... Because these actions are treated as promotions, they do not involve construction costs"

laying brown over green preprinted hexes counts as a promotion, so shouldn't be combinable with a yellow lay.

**Comment by roseundy** [comment]
So is it only some of the pre-printed yellow hexes that placing a green on is a lay and not an upgrade, or **all** pre-printed yellow hexes?

**Comment by slapphappyjazz** [comment]
IIRC, the only pre-printed yellow hexes are the OO hexes.  Note that with the expansion kits, there are two possible green OO tiles.

**Comment by thepackrat** [comment]
That's correct. The pre-printed hexes either brown (immutable apart from magic 200 tile), yellow (OOs), or a green locaton. greeion L, London, and BGM spots.

https://18xx.games/map/1825

**Comment by roseundy** [comment]
Unfortunately, the fix for this will break games. Perhaps they can be pinned as opposed to archived.

**Comment by thepackrat** [comment]
What's the process to? large 25 games tend to run for a while.

**Comment by roseundy** [comment]
When a fix is deployed, Toby will run a regression on all games. Any game that fails typically will be archived (for alpha quality) or pinned (for beta or production quality).

**Comment by roseundy** [comment]
Toby has pinned any game that fails with the bug fix.
