### ISSUE TITLE
[18CZ] Suggestions for minor cosmetic improvements

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#6739]
1. It would be helpful if the ATF's starting location were highlighted, as with the other companies.  It starts on an OO hex, which makes this more complicated. Perhaps both of the starting cities could be highlighted?  Or the "ATF" text could be given a green background?
2.  When highlighting the starting locations on the map, it may be helpful to use different colours for the different sizes of company, matching the colours on the stock market (small = pink, medium = blue, large = green).
3.  The train names might be clearer is the rank were listed first, e.g. d.3+3,  e.4,. f.4E etc.  This would avoid confusion between a 4e meaning a 4 train in rank e rather than a 4E train.  
4.   As noted elsewhere, there is no market in this game (or rather, there is no IPO).  I'm sure I've played another game on 18xx.games that implements this correctly.

**Comment by Zwergenpunk** [comment]
Do you know which game has the only Ipo/Market Option? I known1840 should also have it but I also did not implement it there

**Comment by slapphappyjazz** [comment]
I think it was 1893: Cologne.
