### ISSUE TITLE
ID #2003 crashed momentarily, but went back online after refresh

### ISSUE THREAD

**Issue by willbeplayin** [tobymao/18xx#674]
{
  "id": 2003,
  "description": "Live-ish",
  "user": {
    "id": 1328,
    "name": "jazz"
  },
  "players": [
    {
      "id": 1124,
      "name": "mroy"
    },
    {
      "id": 949,
      "name": "willbeplaying"
    },
    {
      "id": 24,
      "name": "Jac"
    },
    {
      "id": 1328,
      "name": "jazz"
    }
  ],
  "max_players": 6,
  "title": "18Chesapeake",
  "settings": {
    "seed": 2.1716169961682724e+38
  },
  "status": "active",
  "turn": 2,
  "round": "Stock Round",
  "acting": [
    949
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "message",
      "entity": "willbeplaying",
      "message": "^^",
      "entity_type": "player"
    },
    {
      "id": 2,
      "type": "message",
      "entity": "Jac",
      "message": "yay",
      "entity_type": "player"
    },
    {
      "id": 3,
      "type": "message",
      "entity": "jazz",
      "message": "Hey there",
      "entity_type": "player"
    },
    {
      "id": 4,
      "type": "message",
      "entity": "jazz",
      "message": "Still pretty new to 18XX so don't kill me too bad",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "message",
      "entity": "Jac",
      "message": "Hi Jazz.",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "message",
      "entity": "Jac",
      "message": "just ask if you have questions ",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "message",
      "entity": "Jac",
      "message": "matt and will are good players ",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "bid",
      "price": 105,
      "entity": "mroy",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 9,
      "type": "message",
      "entity": "willbeplaying",
      "message": "*average. Atleast I am. :P",
      "entity_type": "player"
    },
    {
      "id": 10,
      "type": "bid",
      "price": 110,
      "entity": "willbeplaying",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 11,
      "type": "message",
      "entity": "jazz",
      "message": "I know the basics",
      "entity_type": "player"
    },
    {
      "id": 12,
      "type": "bid",
      "price": 85,
      "entity": "Jac",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "bid",
      "price": 55,
      "entity": "jazz",
      "company": "Baltimore and Susquehanna Railroad",
      "entity_type": "player"
    },
    {
      "id": 14,
      "type": "message",
      "entity": "willbeplaying",
      "message": "I won my first game a week ago and after that I've had 5-6 wins :D",
      "entity_type": "player"
    },
    {
      "id": 15,
      "type": "message",
      "entity": "Jac",
      "message": "you are on a roll will ",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "bid",
      "price": 90,
      "entity": "mroy",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "bid",
      "price": 45,
      "entity": "willbeplaying",
      "company": "Columbia - Philadelphia Railroad",
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "bid",
      "price": 50,
      "entity": "Jac",
      "company": "Columbia - Philadelphia Railroad",
      "entity_type": "player"
    },
    {
      "id": 19,
      "type": "bid",
      "price": 205,
      "entity": "jazz",
      "company": "Cornelius Vanderbilt",
      "entity_type": "player"
    },
    {
      "id": 20,
      "type": "bid",
      "price": 20,
      "entity": "mroy",
      "company": "Delaware and Raritan Canal",
      "entity_type": "player"
    },
    {
      "id": 21,
      "type": "bid",
      "price": 55,
      "entity": "willbeplaying",
      "company": "Columbia - Philadelphia Railroad",
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "bid",
      "price": 65,
      "entity": "Jac",
      "company": "Columbia - Philadelphia Railroad",
      "entity_type": "player"
    },
    {
      "id": 23,
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player"
    },
    {
      "id": 24,
      "type": "bid",
      "price": 95,
      "entity": "Jac",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 25,
      "type": "bid",
      "price": 100,
      "entity": "mroy",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 26,
      "type": "bid",
      "price": 105,
      "entity": "Jac",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 27,
      "type": "bid",
      "price": 110,
      "entity": "mroy",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 28,
      "type": "bid",
      "price": 115,
      "entity": "Jac",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 29,
      "type": "bid",
      "price": 120,
      "entity": "mroy",
      "company": "Chesapeake and Ohio Canal",
      "entity_type": "player"
    },
    {
      "id": 30,
      "type": "message",
      "entity": "willbeplaying",
      "message": ":D",
      "entity_type": "player"
    },
    {
      "id": 31,
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 32,
      "type": "bid",
      "price": 115,
      "entity": "mroy",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 33,
      "type": "bid",
      "price": 120,
      "entity": "willbeplaying",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 34,
      "type": "bid",
      "price": 125,
      "entity": "mroy",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 35,
      "type": "bid",
      "price": 130,
      "entity": "willbeplaying",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 36,
      "type": "bid",
      "price": 135,
      "entity": "mroy",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 37,
      "type": "bid",
      "price": 145,
      "entity": "willbeplaying",
      "company": "Baltimore & Ohio Railroad",
      "entity_type": "player"
    },
    {
      "id": 38,
      "type": "pass",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 39,
      "type": "par",
      "entity": "jazz",
      "corporation": "PRR",
      "entity_type": "player",
      "share_price": "95,2,4"
    },
    {
      "id": 40,
      "type": "par",
      "entity": "willbeplaying",
      "corporation": "B&O",
      "entity_type": "player",
      "share_price": "80,3,3"
    },
    {
      "id": 41,
      "type": "par",
      "entity": "Jac",
      "corporation": "N&W",
      "entity_type": "player",
      "share_price": "70,4,2"
    },
    {
      "id": 42,
      "type": "pass",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 43,
      "type": "par",
      "entity": "mroy",
      "corporation": "PLE",
      "entity_type": "player",
      "share_price": "70,4,2"
    },
    {
      "id": 44,
      "type": "message",
      "entity": "willbeplaying",
      "message": "weird not starting the PLE :P",
      "entity_type": "player"
    },
    {
      "id": 45,
      "type": "message",
      "entity": "willbeplaying",
      "message": "It's been my first one in like 4-5 games",
      "entity_type": "player"
    },
    {
      "id": 46,
      "type": "buy_share",
      "share": "B&O_2",
      "entity": "willbeplaying",
      "entity_type": "player"
    },
    {
      "id": 47,
      "type": "message",
      "entity": "mroy",
      "message": "Jac starts it so often too",
      "entity_type": "player"
    },
    {
      "id": 48,
      "type": "buy_share",
      "share": "N&W_1",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 49,
      "type": "message",
      "entity": "willbeplaying",
      "message": "it's prob the best starting one alonside N&W",
      "entity_type": "player"
    },
    {
      "id": 50,
      "type": "pass",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 51,
      "type": "message",
      "entity": "Jac",
      "message": "N&W is good early game but you need to token the right place for it good late game ",
      "entity_type": "player"
    },
    {
      "id": 52,
      "type": "message",
      "entity": "Jac",
      "message": "PLE is my fav just bc",
      "entity_type": "player"
    },
    {
      "id": 53,
      "type": "buy_share",
      "share": "PLE_1",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 54,
      "type": "buy_share",
      "share": "B&O_3",
      "entity": "willbeplaying",
      "entity_type": "player"
    },
    {
      "id": 55,
      "type": "buy_share",
      "share": "N&W_2",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 56,
      "type": "message",
      "entity": "jazz",
      "message": "Game might be bugging",
      "entity_type": "player"
    },
    {
      "id": 57,
      "type": "pass",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 58,
      "type": "message",
      "entity": "mroy",
      "message": "Late game is a problem for someone else",
      "entity_type": "player"
    },
    {
      "id": 59,
      "type": "buy_share",
      "share": "PLE_2",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 60,
      "type": "buy_share",
      "share": "B&O_4",
      "entity": "willbeplaying",
      "entity_type": "player"
    },
    {
      "id": 61,
      "type": "message",
      "entity": "willbeplaying",
      "message": "It's 4AM here :P",
      "entity_type": "player"
    },
    {
      "id": 62,
      "type": "message",
      "entity": "Jac",
      "message": "as soon as 49 is on here, i’ll be only playing that lol",
      "entity_type": "player"
    },
    {
      "id": 63,
      "type": "buy_share",
      "share": "N&W_3",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 64,
      "type": "message",
      "entity": "jazz",
      "message": "49 seems pretty cool",
      "entity_type": "player"
    },
    {
      "id": 65,
      "type": "message",
      "entity": "Jac",
      "message": "you work nights, right will?",
      "entity_type": "player"
    },
    {
      "id": 66,
      "type": "buy_share",
      "share": "B&O_5",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 67,
      "type": "message",
      "entity": "Jac",
      "message": "49 is my fav!!!!! and 17",
      "entity_type": "player"
    },
    {
      "id": 68,
      "type": "message",
      "entity": "willbeplaying",
      "message": "ye, casino dealer. although haven't had any work in 2-3 months now :D",
      "entity_type": "player"
    },
    {
      "id": 69,
      "type": "buy_share",
      "share": "PLE_3",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 70,
      "type": "buy_share",
      "share": "N&W_4",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 71,
      "type": "message",
      "entity": "jazz",
      "message": "I've only played this, 46, and 30 tho",
      "entity_type": "player"
    },
    {
      "id": 72,
      "type": "message",
      "entity": "willbeplaying",
      "message": "I've played this, 1889 here on the site and in real life 1846, 62",
      "entity_type": "player"
    },
    {
      "id": 73,
      "type": "message",
      "entity": "willbeplaying",
      "message": "also 1830 on another site",
      "entity_type": "player"
    },
    {
      "id": 74,
      "type": "pass",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 75,
      "type": "buy_share",
      "share": "PLE_4",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 76,
      "type": "message",
      "entity": "willbeplaying",
      "message": "interesting passing start for jazz",
      "entity_type": "player"
    },
    {
      "id": 77,
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 78,
      "type": "message",
      "entity": "willbeplaying",
      "message": "the 40 dollar income is nice though",
      "entity_type": "player"
    },
    {
      "id": 79,
      "type": "buy_share",
      "share": "PLE_5",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 80,
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 81,
      "type": "message",
      "entity": "mroy",
      "message": "Played too many to count",
      "entity_type": "player"
    },
    {
      "id": 82,
      "type": "buy_share",
      "share": "N&W_5",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 83,
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 84,
      "type": "message",
      "entity": "Jac",
      "message": "lol i have a list of what i’ve played ",
      "entity_type": "player"
    },
    {
      "id": 85,
      "type": "message",
      "entity": "Jac",
      "message": "but matt’s played ",
      "entity_type": "player"
    },
    {
      "id": 86,
      "type": "message",
      "entity": "Jac",
      "message": "more",
      "entity_type": "player"
    },
    {
      "id": 87,
      "type": "pass",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 88,
      "hex": "G7",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "B&O",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 89,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "id": 90,
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "id": 91,
      "hex": "C13",
      "tile": "57-0",
      "type": "lay_tile",
      "entity": "N&W",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 92,
      "type": "buy_train",
      "price": 80,
      "train": "2-1",
      "entity": "N&W",
      "entity_type": "corporation"
    },
    {
      "id": 93,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "N&W",
      "entity_type": "corporation"
    },
    {
      "id": 94,
      "type": "pass",
      "entity": "N&W",
      "entity_type": "corporation"
    },
    {
      "id": 95,
      "type": "message",
      "entity": "Jac",
      "message": "will- we should play 49 sometime live on another site if",
      "entity_type": "player"
    },
    {
      "id": 96,
      "type": "message",
      "entity": "Jac",
      "message": "you want will ",
      "entity_type": "player"
    },
    {
      "id": 97,
      "hex": "B4",
      "tile": "69-0",
      "type": "lay_tile",
      "entity": "PLE",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 98,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 99,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 100,
      "type": "pass",
      "entity": "PLE",
      "entity_type": "corporation"
    },
    {
      "id": 101,
      "type": "pass",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 102,
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player"
    },
    {
      "id": 103,
      "type": "message",
      "entity": "willbeplaying",
      "message": "ye, gotta check out those other sites.",
      "entity_type": "player"
    },
    {
      "id": 104,
      "type": "buy_share",
      "share": "PLE_6",
      "entity": "Jac",
      "entity_type": "player"
    },
    {
      "id": 105,
      "type": "message",
      "entity": "willbeplaying",
      "message": "cant wait for this site to get more titles",
      "entity_type": "player"
    },
    {
      "id": 106,
      "type": "message",
      "entity": "Jac",
      "message": "the other sites are crap but i’d do it live ",
      "entity_type": "player"
    },
    {
      "id": 107,
      "type": "message",
      "entity": "Jac",
      "message": "with voice ",
      "entity_type": "player"
    },
    {
      "id": 108,
      "type": "message",
      "entity": "mroy",
      "message": "I'm not a huge fan of 89 or chessie, so ditto",
      "entity_type": "player"
    },
    {
      "id": 109,
      "type": "pass",
      "entity": "jazz",
      "entity_type": "player"
    },
    {
      "id": 110,
      "type": "message",
      "entity": "Jac",
      "message": "i’m not either just a fan of this amazing site ",
      "entity_type": "player"
    },
    {
      "id": 111,
      "type": "pass",
      "entity": "mroy",
      "entity_type": "player"
    },
    {
      "id": 112,
      "type": "message",
      "entity": "jazz",
      "message": "The real time is so much better than rr18",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "Jac",
      "entity_type": "player",
      "id": 115,
      "_client_id": "2a6aad35fc7b411da6813a58c6be3907"
    }
  ],
  "loaded": true,
  "created_at": "2020-06-10",
  "updated_at": "2020-06-10"
}

**Comment by willbeplayin** [comment]
"We're sorry this game cannot be continued due to GameError: It is not Jac's turn
Please raise a bug report and include the game id (2003) and the following JSON data
Copy Data
{
  "id": 2003,
  "description": "Live-ish","

**Comment by tobymao** [comment]
what was the crash?

**Comment by willbeplayin** [comment]
I don't know, it just showed that site. I had master mode enabled and though it was my turn. It was a live game so the turns went fast and I guess I was late. After going back to main menu, it was alright. Weird.

**Comment by tobymao** [comment]
looks like it got desynced, i'm not sure how that can happen
