### ISSUE TITLE
[18NewEngland] Not possible to sell shares during emergency money raising 

### ISSUE THREAD

**Issue by tomgi** [tobymao/18xx#6746]
**What's your Game ID?**

https://18xx.games/game/67925?action=208

**How to Reproduce the Bug?**

- CC minor company doesn't have any trains and can't afford to buy the cheapest one. 
- The president would like to conduct emergency money raising but doesn't have enough cash, so begins to sell shares. 
- Trying to sell any share displays a `Blocking step Buy Trains cannot process action 209` error.

---

My initial investigation:

In
https://github.com/tobymao/18xx/blob/1c27d4ca9ea41e8f55bc0b53b65de394a54d82af/lib/engine/round/base.rb#L84-L86 
`s.actions(action.entity) == []`, because in https://github.com/tobymao/18xx/blob/1c27d4ca9ea41e8f55bc0b53b65de394a54d82af/lib/engine/game/g_18_new_england/step/buy_train.rb#L13
`entity` is the current player (`Engine::Player - Blankasia`), but `current_entity` is the corporation (`#<Engine::Corporation:0x1016>`)

**Comment by scottredracecar** [comment]
Agree, bug. You should be able to sell shares in this situation.
