### ISSUE TITLE
[1862] Ignore first share sold when moving price (except president) - not working

### ISSUE THREAD

**Issue by beginetienne** [tobymao/18xx#6748]
See https://18xx.games/game/67900 

President of E&H in SR5 is selling one share at a time while price is in light green area at 210.

The price remains at 210 after each sale, it should go down one space as the president is making the sale.

Rule is "Ignore first share sold when moving price (except president)"

**Comment by roseundy** [comment]
It's hard to tell at what point you saw this, but after the LNER forms, stock price doesn't move on sales.
