### ISSUE TITLE
18Mag dividend +1/-1 arrows cover up amount

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6752]
The arrows to add/subtract from the dividend amount cover up the actual amount that will be paid.

https://18xx.games/game/66478?action=457

<img width="347" alt="Screen Shot 2022-01-10 at 15 40 19" src="https://user-images.githubusercontent.com/8732435/148856612-ecb20337-80ca-4377-892d-62db9d33fcd1.png">

**Comment by tobymao** [comment]
<img width="277" alt="Screen Shot 2022-01-10 at 3 43 51 PM" src="https://user-images.githubusercontent.com/8205034/148856816-ac61274b-78a0-4e25-a60f-7864a7552451.png">

works for me on os x chrome

**Comment by ChrisTheCat** [comment]
It's apparently a problem on Firefox. Looks fine in Chrome and Safari,
doesn't look right on Firefox even in Incognito mode with no extensions.
All on MacOS, I can't check on Windows.

**Comment by roseundy** [comment]
On my desktop, I can click on the text field and type a number in directly.

**Comment by ChrisTheCat** [comment]
Yes, I can do that too. I can also click the arrows. The problem is the
display, not the functionality.

**Comment by roseundy** [comment]
Yep, it's pretty atrocious on Firefox. I'm not sure how much control I have over this.

**Comment by roseundy** [comment]
Firefox seems to be ignoring the size property.

**Comment by ChrisTheCat** [comment]
Just noticed this occurs in 18NY as well. Could the fix be applied there too?

<img width="371" alt="Screen Shot 2022-01-10 at 22 52 32" src="https://user-images.githubusercontent.com/8732435/148895161-92d8b26f-4607-4134-9c96-1e9cb06971a7.png">

**Comment by ChrisTheCat** [comment]
Interestingly the same problem does not exist in 1817.

<img width="366" alt="Screen Shot 2022-01-11 at 06 14 12" src="https://user-images.githubusercontent.com/8732435/148958797-176fe7f0-24e2-40ed-a873-e60a02179e6c.png">

**Comment by roseundy** [comment]
I found the issue in seven additional files.
