### ISSUE TITLE
1822 game stuck

### ISSUE THREAD

**Issue by MikeBakken** [tobymao/18xx#6753]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "1822 game stuck, another player reported getting stuck laying home station for 26"

**What's your Game ID?**  68075

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/68075`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by roseundy** [comment]
https://18xx.games/game/68075?action=344

"undefined method `tokened_by?' for nil"

**Comment by outsidePasser** [comment]
This looks like a problem when a minor buys an L train but then doesn't lay a tile and isn't connected.  "visited_stops" contains a single null element, and revenue is trying to find out if the null stop is tokened.

**Comment by MikeBakken** [comment]
The person making that move is new to the game - a very unlikely situation for sure.
    On Tuesday, January 11, 2022, 09:24:28 PM EST, outsidePasser ***@***.***> wrote:  
 
 


This looks like a problem when a minor buys an L train but then doesn't lay a tile and isn't connected. "visited_stops" contains a single null element, and revenue is trying to find out if the null stop is tokened.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MikeBakken** [comment]
Thanks that works perfectly!
    On Friday, January 14, 2022, 10:07:10 PM EST, Toby Mao ***@***.***> wrote:  
 
 


Closed #6753 via #6791.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
