### ISSUE TITLE
[18New England] Emergency funds from President’s cash not available during forced purchase

### ISSUE THREAD

**Issue by RumpSK** [tobymao/18xx#6756]
Even though the president of the BAR has enough money to assist a forced purchase the game will not use that money. There is no way forward. Did have problems yesterday also with not being allowed to sell shares to finance a forced train purchase. 

hs_ybfzthrf_1641826129

**Comment by scottredracecar** [comment]
Hotseat games are local to your machine so you need to post the log on a public gist.
https://gist.github.com/

Luckily, I was about to report a similar issue in an online game. Jasonbartfast would like to declare bankruptcy, but is unable.
https://18xx.games/game/67662?action=405

**Comment by roseundy** [comment]
@RumpSK, can you share a gist of your game?

@scottredracecar, I think this is a separate bug.

**Comment by roseundy** [comment]
There are two bugs here:
1. Not all shares available to sell are being presented
2. Declaring bankruptcy has a typo in the code

**Comment by roseundy** [comment]
I can't debug until I have a case that shows the problem. @RumpSK

**Comment by mkkohls** [comment]
I just ran into the same issue. It is in game https://18xx.games/game/67635 which is a multiplayer game. I am trying to contribute money to the CN to by a 4 train from the depot.

If you need anything more let me know.

**Comment by roseundy** [comment]
OK, I was just able to reproduce the problem too. Stand by.

**Comment by RumpSK** [comment]
I have been at work all day. Do you need any more info from me? It’s ok to end my game as it was just a test play to see how things feel.

**Comment by scottredracecar** [comment]
It looks like the new patch will break your game anyway so nothing else needed for this one.

Gist is a website for posting text, such as a game log in our case. That can be copied from the tools tab (copy, then paste in the gist website). Then link to the gist to share it.
https://gist.github.com/

**Comment by RumpSK** [comment]
If I'm reading correctly you guy's don't need the log anymore, correct? I am happy to copy it if you do (other than you will see my ridiculous play 😆)

**Comment by scottredracecar** [comment]
Sure, go ahead. It will be good practice for next time and we might be able to use it to verify if there is an extra issue with share sales.

**Comment by roseundy** [comment]
Closed with #6765

**Comment by roseundy** [comment]
Closed with #6765
