### ISSUE TITLE
1822 Cannot use Adv. Tile Lay Private and Estuary Discount at the same time

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#6758]
I was at this point in this game: https://18xx.games/game/67888?action=357

Running company 24.  I wished to use the Advance TIle Lay private and the River/Estuary Discount privates at the same time to upgrade tile G34 to a brown tile that had a route heading south.  It seems I could only activate one of the choices at a time in the .games system (selecting the other de-activates the first).  I am not aware of a rule in 22 which prevents you from using 2 private powers in a single tile lay, but maybe I just can't find it?

**Comment by scottredracecar** [comment]
dup #4469
