### ISSUE TITLE
Error Building Development Version

### ISSUE THREAD

**Issue by andrewzwicky** [tobymao/18xx#6763]
**How to Reproduce the Problem?**

What steps cause the unexpected behavior?

- trying to build site for development

Please include screenshots (you can drag and drop or upload them into this issue)

```
pi@raspberrypi:~/Desktop/18xx $ make > fail.log
Building redis
Building db
Building queue
The command '/bin/sh -c if [ "$RACK_ENV" = "production" ];     then bundle config set without 'test development';     fi;     bundle install;' returned a non-zero code: 134
ERROR: Service 'queue' failed to build : Build failed
make: *** [Makefile:33: dev_up_b] Error 1
```

`fail.log`
```
rm -f docker-compose.override.yml
ln -s docker-compose.dev.yml docker-compose.override.yml
./scripts/data_dir.sh docker
docker-compose up --build
Sending build context to Docker daemon  2.048kB

Step 1/1 : FROM redis:latest
 ---> 41ace3cf1b63
Successfully built 41ace3cf1b63
Successfully tagged 18xx_redis:latest
Sending build context to Docker daemon  30.21kB

Step 1/6 : FROM postgres:13.1
 ---> 7417635b017d
Step 2/6 : RUN useradd --uid 1000 --user-group --create-home --home-dir /home/db db
 ---> Using cache
 ---> 17139b144ee8
Step 3/6 : RUN chown db:db /var/lib/postgresql/data &&     chown db:db /var/run/postgresql
 ---> Using cache
 ---> e5498b5320ae
Step 4/6 : USER db:db
 ---> Using cache
 ---> 21f2a6980580
Step 5/6 : COPY ./postgresql.conf /etc/postgresql/postgresql.conf
 ---> Using cache
 ---> d5c803eaf263
Step 6/6 : CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
 ---> Using cache
 ---> f499b72f2bed
Successfully built f499b72f2bed
Successfully tagged 18xx_db:latest
Sending build context to Docker daemon  24.57MB

Step 1/9 : FROM ruby:3.1
 ---> a7f4dfdd030b
Step 2/9 : ARG RACK_ENV
 ---> Using cache
 ---> 11ce26453bca
Step 3/9 : RUN mkdir /18xx
 ---> Using cache
 ---> 28b4f977404f
Step 4/9 : WORKDIR /18xx
 ---> Using cache
 ---> e1af1c45ce6e
Step 5/9 : RUN if [ "$RACK_ENV" = "development" ];     then       curl -s https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.14.8.tgz | tar xz;       mv package/bin/esbuild /usr/local/bin && rm -rf package;     fi;
 ---> Using cache
 ---> 6a8da4f4a643
Step 6/9 : COPY Gemfile Gemfile.lock ./
 ---> Using cache
 ---> 14fdd82486da
Step 7/9 : RUN if [ "$RACK_ENV" = "production" ];     then bundle config set without 'test development';     fi;     bundle install;
 ---> Running in 0aaaef4afa77
[ASYNC BUG] timer_settime (arm)
EPERM

ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm-linux-eabihf] Aborted (core dumped)
```

**Comment by roseundy** [comment]
I think you're the first person to try building on Raspberian.

**Comment by andrewzwicky** [comment]
I'm honestly not sure what the status of my ruby installation is here.  trying to run `ruby` or `which ruby` both fail, but it's all supposedly preinstalled.  I also see `ruby 3.1.0p0 (2021-12-25 revision fb4df44d16)` in the output which would be surprising to see if it wasn't finding it somewhere.

**Comment by tobymao** [comment]
@andrewzwicky some of the C dependencies of the project probably don't build on your system, not sure if there's much we can do to fix that, i feel like docker should abstract that away, but i guess rasberry pi's might not be fully compliant?

**Comment by tobymao** [comment]
we can discuss in this thread or slack to help you debug, but i think it's reasonable for the project to support the major linux / windows / os x distributions

**Comment by andrewzwicky** [comment]
Yeah it's failing on `bundle install`, but I can't manage to get more detailed debug info out of it.  Fair enough, thanks for taking a look.

**Comment by tobymao** [comment]
@andrewzwicky if you want to debug, in the container, you can bundle install each dependency or perhaps bundler saves errors somewhere

**Comment by andrewzwicky** [comment]
I've spent a bunch of time trying to get any useful error output, but between bundle, docker, and make I don't have the patience to try to get it working any longer.  I'll try on Windows.
