### ISSUE TITLE
[18CZ] Initial Stock round change to early

### ISSUE THREAD

**Issue by MarkOlree** [tobymao/18xx#6767]
https://18xx.games/game/67952?action=20

**How to Reproduce the Bug?**

- Buy some Local Railways, not all.
- After the last buy, pass up-to the last person who bought a Local Railways.

Game will pass to the Stock round.

![image](https://user-images.githubusercontent.com/6412346/149101096-66094896-0082-4356-904f-d6075afbc7f9.png)

**Expected:** Person (EmAitchOh) who performed the last action, but has not passed yet should be given the option to buy another Local Railways or pass. On a pass the round should change.

The rules describe in VI. Pre-Stock Round:

- The Pre-Stock Round ends if all players pass consecutively or if all Local Railways have been sold. Any remaining Local Railways are out of the game. 
- A player who has passed may buy a Local Railway on his next turn (unless all of the other players have also passed in turn.)

**Edit:**
**Expected:** Next Person (Pusher) should be given the option to buy another Local Railways or pass, up until the last in row (EmAitchOh). 

I previously didn't noticed that Nils bought a Local Railyways, but that still leaves unsold Local Railways.

**Comment by andypymont** [comment]
Having investigated this further: the 18CZ draft ends as soon as a player, on their turn, cannot afford any privates. Rather than them taking a forced Pass, instead the entire round is passed and SR1 begins.
