### ISSUE TITLE
[18NewEngland] Game crashed in OR5 and couldn't be finished

### ISSUE THREAD

**Issue by manolillo92** [tobymao/18xx#6772]
**What's your Game ID?**
https://18xx.games/game/68310

"We're sorry this game cannot be continued due to GameError: Blocking step Issue Shares cannot process action 461
Broken action: { "type": "buy_shares", "entity": "CN", "entity_type": "corporation", "id": 461, "created_at": 1642044853, "shares": [ "CN_2" ], "percent": 10 }
Please raise a bug report and include this link (https://18xx.games/game/68310?action=460)"

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

- Browser Version
  - On Chrome, see [chrome://version](chrome://version)

**Comment by tobymao** [comment]
game is pinned
