### ISSUE TITLE
Wrong trains are selected when using auto routing.

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#6774]
It seems the auto routing sometimes do not select the best train.

A variant of this was originally reported for 18TN (#6597) but that might also be due to how Civil War is implemented. So that might require a separate fix.

But it has been reported in other games, that has no special effect:

- 1889, for game, see : https://github.com/tobymao/18xx/issues/6597#issuecomment-1006774216
- 1830, for game, see:  https://github.com/tobymao/18xx/issues/6597#issuecomment-1011918181
 
 My suspicion is that this is a general issue, not just limited to these 2 (or 3) titles.

**Comment by tobymao** [comment]
dup
