### ISSUE TITLE
[18NewEngland 2] own 2 trains, can only route one

### ISSUE THREAD

**Issue by jemiahlee** [tobymao/18xx#6777]
**What's your Game ID?**
https://18xx.games/game/68297

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Taking this company's turn, you can see that it owns two trains but can only route one of them.

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
 Chrome  96.0.4664.110 (Official Build) (arm64)

- Platform (Mobile, Tablet, Desktop)
Mac OS Monterey 12.0.1

![Screen Shot 2022-01-13 at 10 30 04 AM](https://user-images.githubusercontent.com/1414428/149389865-fb547541-eedf-484d-a9b3-e4031eb8fab6.png)

**Comment by scottredracecar** [comment]
But there is a hidden enhancement request here to make this more clear to
the user. This will not be the last time it comes up.

**Comment by jemiahlee** [comment]
I agree with this. Even putting parens around the 2nd train might help.
