### ISSUE TITLE
[1846] Starting auction does not remove pass cards when down to one private

### ISSUE THREAD

**Issue by outsidePasser** [tobymao/18xx#6779]
https://18xx.games/game/68427

When the available private cards contain one private and multiple "pass" cards, the "pass" cards should be removed, the last private revealed.  From the rulebook:

3.22 If the deck is reduced to one Private Company, the player who draws the last Private Company reveals it and may either buy it at list price or pass it on to the next player with its price reduced by $10...

What actually happens is the active player is given a choice between the remaining "pass" cards and the last private.

**Comment by michaeljb** [comment]
The implementation is correct, in the situation you describe the deck has been reduced to some pass cards and the one Private Company, not just the one Private Company.

Quote from the designer:

> 3.22 shouldn't be read in isolation, it should be read in context with the rest of 3.2. The sentence immediately preceding 3.22 is:
> 
> "Continue until either a player draws all blanks, ending the distribution, or the deck consists of *no blank cards and one Private Company*." (emphasis added)
>
>3.22 then continues "If the deck is reduced to one Private Company, [...]"
>describing what to do in this case.

https://boardgamegeek.com/thread/1718747/article/24940018#24940018
