### ISSUE TITLE
[18 New England] Company Able to Cross-buy with Presidential Cash

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#6782]
https://18xx.games/game/68444?action=397

VC's president was allowed to contribute personal cash to a crossbuy which is not allowed.

**Comment by scottredracecar** [comment]
I don't think this is a bug. VC had 160, bought train for 160. I tried to buy for more in hotseat and it threw an error. Closing for now, feel free to reopen if I am missing something.

**Comment by Maxwell-Frank** [comment]
If you check the JSON, they definitly bought the train for $169.  
` {
      "type": "buy_train",
      "price": 169,
      "train": "3-3",
      "entity": "VC",
      "entity_type": "corporation",
      "id": 397,
      "user": 4281,
      "created_at": 1642132107,
      "skip": true
    },`

**Comment by scottredracecar** [comment]
Maybe it is a server vs hotseat problem. Steve will see this and will know
if this is possible. I definitely got the pink bar error in hotseat when I
tried to reproduce.

**Comment by Maxwell-Frank** [comment]
@scottredracecar I did too when I cloned it. But I definitely saw what I saw!

**Comment by roseundy** [comment]
OK. These are a paid to debug.

**Comment by roseundy** [comment]
There is a metric ton of undos in this game, I've seen state get corrupted in these cases.

**Comment by Maxwell-Frank** [comment]
https://18xx.games/game/68500?action=26

Here's a very simple example of the bug.

**Comment by roseundy** [comment]
EBUY_OTHER_VALUE was left at the default value of true. It needs to be set false for 18NewEngland

**Comment by scottredracecar** [comment]
EBUY_OTHER_VALUE default to true is not a great default, applies to very few games :-(
