### ISSUE TITLE
[18 New England] Merging with a company higher up in stock order causes the merger round to restart

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#6793]
https://18xx.games/game/68554?action=181

In the middle of the merger round, a merger took place, and then it went back to the top of the order.  BP and other companies had to pass twice in the merger round.

**Comment by roseundy** [comment]
Actually, merging with a minor higher up in order causes several problems, including skipping over the next minor.

In your case, GR should have been asked about merging, but never was.

The fix will invalidate any game that merges a minor with a minor higher in order.
