### ISSUE TITLE
[18NY] - Unconnected Minor Allowed to Merge to Form the NYC

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6799]
https://gist.github.com/OedipussyRex/6b2bb0189740e7dc1aeb85f23929c884.js

Minor #7 is unconnected to Albany by track, yet it is offered the opportunity to merge.

"Minor Companies #1 and #2, if they are operating, must merge into the NYC. All other Minor Companies which are connected to Albany by track (ignoring tokens) may choose to merge into the NYC." The implication here is that companies that are not connect may not choose to merge.

**Comment by crericha** [comment]
Which game? The gist is not a game file.

The game is implemented to not allow unconnected companies to merge. May be broken.

**Comment by OedipussyRex** [comment]
It was a hot-seat game.

**Comment by crericha** [comment]
Can you provide the game data, so I can import it?

**Comment by OedipussyRex** [comment]
Maybe this will work

https://gist.githubusercontent.com/OedipussyRex/0b8086a6df772d6cddd2058bda94d9fc/raw/50b25b62a22537fe4a757665fc802cf0d27bbd8a/18NY%2520Bad%2520Merge%25202

**Comment by crericha** [comment]
Perfect. Thank you.
