### ISSUE TITLE
[18NewEngland] Incorrect priority assignment after SR1

### ISSUE THREAD

**Issue by cheesinglee** [tobymao/18xx#6800]
After the first stock round, PD is supposed to be assigned to the player with the most leftover cash, but seating order is to be preserved otherwise. It appears the current implementation completely reseats the players in descending cash order after SR1.

**What's your Game ID?** https://18xx.games/game/67997?action=19

Gist: https://gist.github.com/cheesinglee/2b4e3a5bec6c41ecfde198b03561c982

**How to Reproduce the Bug?**

In the linked game, original seating order and remaining cash were as follows:

1. Arne (30)
2. KennyB (40)
3. zabergau (30)
4. cheesinglee (20)

Following the conclusion of SR1, order was

1. KennyB
2. Arne
3. zabergau
4. cheesinglee

**Which Browser / Platform?**
- Browser Version
  - Firefox 91esr on desktop

**Comment by scottredracecar** [comment]
Right, it's a bug. The order should not change, just the person with the most remaining cash should get priority, no other reordering.

If there is a tie for most cash, then break ties preferring the earliest in priority order from the start of the game.

Currently, it looks like it is reordering with most_cash
https://github.com/tobymao/18xx/blob/2440ead8c879a5d0bbc3ffe2bbf63abe34ad72e5/lib/engine/game/base.rb#L2361

**Comment by roseundy** [comment]
The fix will invalidate/pin all games :-(

**Comment by roseundy** [comment]
FYI, at the start, the player order was:

1. Arne (30)
2. KennyB (40)
3. cheesinglee (20)
4. zabergau (30)

After the fix, the order is:

1. KennyB
2. cheesinglee
3. zabergau
4. Arne
