### ISSUE TITLE
[18NY] - Typo in wiki

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6801]
"The Albany Stagecoach token is lost if not placed before the first 1H is purchased."

should be 

"The Albany Stagecoach token is lost if not placed before the first **12H** is purchased."

**Comment by scottredracecar** [comment]
It's a wiki. You can update it directly--even easier than posting an issue! :-)

**Comment by OedipussyRex** [comment]
Huh. Look at that. Closed.
