### ISSUE TITLE
Add players last ORs earnings to spreadsheet/player tab

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#681]
Clownfeet suggested it would be useful to see a players last complete ORs earnings. (While your in OR 7.2 you should see OR 7.1 earnings)
Seems like the sensible place to add this would be on player tab and spreadsheet tab

This could be useful to see how your doing relative to other players.

**Comment by PedroRCSequeira** [comment]
regarding the similar "Track player value at the end of each OR in the spreadsheet #1382"

please note that player value includes share value change, and at least near the end game, it is more relevant than $ earnings since cert limit becomes the limiting factor (in some games at least

**Comment by lordscarlet** [comment]
I would also like to see the value of a stock overtime. I would especially like to see unrealized gains (realized gains a bonus). This will allow me to see, for instance, That I bought B&O in SR1 for $95. In OR1.1 it depreciated by $10. In SR2 it depreciated by $5, in OR2.1 it appreciated by $5. I can then alos see that overall, my B&O stock is worth $5 less than it was worth when I bought it. (I think I did that math right, but hopefully you get the picture).

Essentially this type of data (some of this is only on my screenshot to explain what is going on at the bottom):

![image](https://user-images.githubusercontent.com/17951/91612096-aa2aba00-e94a-11ea-8969-7199da6efd96.png)

A bonus would be noting purchases, sales, and other singificant events on the graph

**Comment by benjaminxscott** [comment]
Is this covered now that we have the 'player value history' feature?
![Screenshot 2020-12-16 at 10 18 30 PM](https://user-images.githubusercontent.com/1711810/102451064-a5b70980-3fec-11eb-89b2-59798e99d7bd.png)

**Comment by jenf** [comment]
Technically there's no graphing. But good enough. People can raise a separate issue for graphs if they really want it.
