### ISSUE TITLE
18NewEngland: Not allowed to merge with minor in same hex

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#6811]
https://18xx.games/game/67962?action=187

HNH should be able to merge with NLN because it is co-located on the same hex, but isn't allowed to

**Comment by queroscia** [comment]
Rules say literally: "If the president decides to instead merge the company, the president selects another of their minor companies to which the active company has a route (**or if unconnected**, have home stations that are colocated in the same hex)."
The bug have been confirmed by Scott Petersen.
It is my first report and English is not my natural language. So, I prefer no misunderstandings. I have received two emails from Benjamin Scott. First says "dupe" and second "close". **I don't know who refers with word "dupe"**. Seen github I don't understand anything, sorry. However, the bug remains in the game.
I am a very analogue person and it is a real effort for me report this bug. Now, what about?
Thanks.

**Comment by scottredracecar** [comment]
It was marked “dupe” (duplicate) because there was already an issue for
this that Steve made when he closed the bug. Please continue to report via
this method. You made a good report. The only problem was that it got fixed
too fast! 🙂
