### ISSUE TITLE
18NY 2nd edition 

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#6822]
https://18xx.games/game/68725

I think that the 4DE owned by BA ran as a 5DE rather than a 4DE in OR6.3.   It might have in earlier rounds as well, but I just happened to notice in this one.

**Comment by crericha** [comment]
The BA 4DE runs I see in the log are:

[16:24]B&A runs a 4DE train for $600: G1-E3-(D4)-(D8)-(E11)-(D12)-(D14)-(D18)-(D20)-(E19)-F20-(G21)-F26
[19:09]B&A runs a 4DE train for $660: G1-(E3)-(D4)-(D8)-(E11)-D12-(D14)-(D18)-(D20)-(E19)-F20-(G21)-F26

As far as I can tell, both are only paying out for 4 stops. What makes you think it's 5 stops?

**Comment by crericha** [comment]
Also, don't forget that Toronto is a passthrough now. If you add it to your route, you can run for 740.

**Comment by fsaglio** [comment]
I thought it was paying more than 4 because I expected the run to be the
two endpoints so 100* 2 + 100 * 2 and then Syracuse (70 *2) and then $60
for one of the green cities that the company has a token in.   That totals
up to $600.   I didn’t see how it was getting to $660 without counting a
5th city.

**Comment by fsaglio** [comment]
Actually, now that I’m looking at it again, it looks like it is counting
Albany in the run isn’t it?  Which shouldn’t happen since I don’t have a
token there.

**Comment by crericha** [comment]
4DEs use the same rules as 5DEs, but they only count 4 stops. The relevant text from the rules is below. Perhaps you are thinking of the 5DE can only run stations and offboards variant? That wasn't carried over to the 2nd edition.

"5DE-trains may travel any number of hexes, score any 5 of the locations on the way (they do not need to be consecutive), and double the result. The route must have at least one of the company's station markers on it, but need not count it as one of the 5 locations."

**Comment by fsaglio** [comment]
Oh, whoops, Nevermind then.   I stand corrected.   I had only played with
the “5DE only running stations and off-boards”  rule.   Didn’t realize it
hadn’t carried over to 2nd edition.
