### ISSUE TITLE
18NY game crash

### ISSUE THREAD

**Issue by woodfeld** [tobymao/18xx#6824]
Hi, our 18NY game crashed and can't be ended.  It asked us to report the bug here along with this link - https://18xx.games/game/63362?action=634
Jerry

**Comment by nova0210** [comment]
I also encountered the same situation, and the game cannot be closed, it keeps prompting my turn to act 
 -https://18xx.games/game/63804?action=759

**Comment by crericha** [comment]
@woodfeld, @nova0210 are the games fine now? They load for me.

**Comment by crericha** [comment]
@tobymao, the connected_nodes vs reachable_nodes fix changed player cash for a few games and broke them. Can you please archive the games?

**Comment by crericha** [comment]
If you need a pin to archive, commit # 99f36d55488486bf9fb1967aa04dc4f1e5ad10b4 should work for the pin.
