### ISSUE TITLE
Price Protection in 1870 doesn't trigger if the sell action would close the company

### ISSUE THREAD

**Issue by jdbehan** [tobymao/18xx#6825]
https://18xx.games/game/67285?action=810

**Comment by benjaminxscott** [comment]
Could you clarify the issue and which action ID it's occuring at?

**Comment by jdbehan** [comment]
https://18xx.games/game/67285

On 20-Jan, Piramidion took over the presidency of the MKT by buying 4
shares in one stock action because it was in the brown area.  During
mb1898's turn, he sold three shares which would have closed the company by
pushing it into the black area of the market if Piramidion didn't price
protect.  The game didn't give him the option of price protecting.  That's
the bug.  We were able to work around it by having mb1898 sell 2 shares,
Pira price protecting, and then he sold the last share.  Two wouldn't have
closed the company so I think that's why the game let him.

Very rare situation, but we thought we'd report it.

Let me know if you have any other questions.

Thanks for all you do with this site!

Jeff B

**Comment by JoeB989** [comment]
Initial investigation notes here: https://app.slack.com/client/T67762LUR/C012K0CNY5C

**Comment by JoeB989** [comment]
Well you know what, this is working now.  I guess I must have fixed it with the prior price protect fixes.  Apparently the step rework is not needed here - maybe I'm confusing the scenarios.
