### ISSUE TITLE
[1860] Game 67306 - No tile available when company floats

### ISSUE THREAD

**Issue by rclyne** [tobymao/18xx#6831]
In this game the S&C floated https://18xx.games/game/67306?action=372 and it laid the last tile #115 as it's tile lay for floating.  When the BHIR floated there was no tile that could be laid in it's home hex.  The game was rewound and the S&C laid a different tile to allow the game to continue.

I know Mike Hutton and spoke to him about this situation and he said , as far as he knows, it is the first time it has happened.  He is thinking about the rules fix but is tending to allow infinite #115 tiles in yellow.

**Comment by roseundy** [comment]
I could have sworn this has come up before. I had to add the ability to pass on the tile placement because of this possibility.

**Comment by roseundy** [comment]
Yes, #2709 also hit this - and should have been fixed. It would be useful to have the game in the state you originally found the bug.

**Comment by roseundy** [comment]
Also, why does this even need to be fixed in the rules? There are times when a company is opened and can't create a route because it can't upgrade it's own home city. I don't see this as any different.

**Comment by rclyne** [comment]
The issue is that the rules for track laying in 1860 assume that there is track on the board to extend.  The initial tile lay is a special case.  So without a rules change the game cannot follow the rules!  I'll have a look at the draft AAG rules over the weekend and see if the wording is fixed in any way.  I'll be seeing Mike Hutton in a week or so and will make sure he is aware of the linked BGG thread

**Comment by roseundy** [comment]
Did the implementation not work? Was the BHIR not able to lay a tile when one became available? It seems simple change to the rules are needed, not modifying the tile set.

**Comment by rclyne** [comment]
BHIR was not able to lay a tile

**Comment by roseundy** [comment]
Yes, but did the game lock up? Was it not able to lay a tile when a suitable one became available? If there is an implementation bug here, I need more details.

**Comment by rclyne** [comment]
I've cloned the game and rolled it back.  I can see a Pass button for the BH&IR to skip playing a tile on their home station.
This is technically a change in the rules from the published rules of 1860 but makes a lot of sense as a way to cope with the issue.  It's exactly the rule change that I had suggested to Mike but he was not keen.  I'll have another go!
