### ISSUE TITLE
18NY game froze

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6849]
https://18xx.games/game/70009?action=601

Jim tried to undo his tile lay and the game locked up. We can't get back to action 602.

**Comment by crericha** [comment]
It appears the game completed. Did you have to do anything special to get it unstuck?

**Comment by ChrisTheCat** [comment]
When we checked on it the next morning, it was working fine so we finished
async.

**Comment by crericha** [comment]
It must have been a general bug by a commit unrelated to 18NY.
