### ISSUE TITLE
Firefox is interpreting the in-game chatbox as a username field

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#6856]
Using Mozilla Firefox 96.0 (64-bit) [desktop on Linux PC], the chatbox (input element with id _chatbar_) is being interpreted as a username field. (This could potentially be caused by the "@username" hint in the _placeholder_ attribute?)

If you have Firefox set to auto-populate saved logins and have saved your 18xx.games login details, then on loading any game it will immediately populate your saved username (thankfully not any password details) into this input element. If you disable automatic username population in Firefox's settings, it still recognises the box as a username and will prompt you about your saved logins whilst you are typing chat messages:
[Example](https://i.imgur.com/3PPLFIR.png)

(This is probably a bug in Firefox or overzealous behaviour on its behalf, given that no attribute on the input element except the placeholder hints at being a username field: however if this is affecting a large % of the user base and/or if other web browsers also replicate this behaviour, it could possibly be worth changing anyway?)

**Comment by benjaminxscott** [comment]
Possibly fixed by https://github.com/tobymao/18xx/pull/6857, once it's deployed
