### ISSUE TITLE
18NY - Cannot take loans during emergency fundraising 

### ISSUE THREAD

**Issue by goldencow2** [tobymao/18xx#6858]
https://18xx.games/game/69400
https://18xx.games/game/69400?action=291

My company is under the loan limit, has no train, and would have enough money to purchase a 4H-train if it took loans. No option to take loans pops up. There is a 2H train in the pool it can afford without any emergency fundraising, but [the rules do not require me to purchase it](https://docs.google.com/document/d/1Pz0f1Sr0uhlSpOuuXbu4OaDKIgteIyuGN55XOOLJrb0/edit#heading=h.os0t75atylt8).

![Untitled](https://user-images.githubusercontent.com/43799724/151463884-51af1df3-d224-49a2-8b97-33b9eae35fa3.png)

**Comment by crericha** [comment]
The cheapest train must be purchased if a loan is taken. Since the corporation can already afford the cheapest train, no loan option is offered.

From section 7.8.1 Emergency Money Raising
> A company can sell its shares during this process to buy any train; however, if any loans were used or the President contributed funds, the cheapest available train from either the Bank or Bank Pool must be purchased.
