### ISSUE TITLE
1817 Special Rules Summary

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#686]
### Map
 - [x] Some tiles are declared as water terrain when they are not water terrain causing problems with Bridge companies

### Initial auction

- [x] Choose and bid, with seed capital
- [x] PD should be player to the left of the last player to initiate a bid

### Market
- [x] Needs a liquidation and three acquisition spots

### IPO
- [x] When IPOing a company first place station location players choice
- [x] Then a bidding for that IPO
- [x] The winning bidder chooses if the company is 2, 5 or 10 shares depending on the phase
- [x] Currently a bug, once you've passed on the IPO bid you can rejoin
- [x] Currently a bug, if all other players pass, you still need to up the bid
- [x] Currently a bug, if you try to PAR a company without any privates it explodes.

### SR
- [x] Players can act as the corporations they own to take loans
- [x] Players can act as the corporations to purchase their own shares from the open market
- [x] Corps must buy their tokens before end of stock round.
- [x] Players can buy shorts on 5/10 share companies
- [x] New Companies need to buy their tokens
- [x] 2 Stock companies should not change stockprice when sold out.
- [x] Stocks in the market move share price one to the left

### Short selling
- [x] Players that holding shorts that declares a dividend must paying that amount to the bank.
- [x] Cash-Crisis if cannot, effectively EMR with the no-change-of-president variant.
- [x] Player bankruptcies if cannot.

### Interest/Loans

 - [x] All Actions should see if you have buying power to cover them (after taking out loans)
- [x] OR

- [x] Acquisitions

### OR
- [x] Lay one or two track tiles (one may be an upgrade)
- [x] A station marker may not be placed in Toronto.
- [x] Pay / Half Pay / Withhold Dividend - (see rules)
- [x] Public Companies are never required to purchase a train
- [x] Therefore, no EMR for trains, but see Cash-Crisis
- [x] Pay Loan Interest
- [x] Repay Loans
- [x] Liquidate companies without trains -> move to liquidation spot
- [x] End of every Operating Round - export a train
- [x] Companies cannot buy trains from companies in acquisition

## Conversion/Merge
- [x] Convert or merge companies in white section of the
stock market, in operating order
- [x] Companies converted must buy extra station markers
- [x] Must reduce down to 8 station markers as liquidate rules

## Liquidate, acquire, sell
- [x] Liquidate companies in the red liquidation area, in
reverse order they were placed in liquidation.
- [x] Acquire companies in the gray acquisition area, in
reverse operating order.
- [x] Offer for sale companies in the white section of the
stock market, in reverse operating order.
- [x] After an acquisition players need to reduce station markers down to 8.
- [x] Companies may need to take out loans to cover costs
- [x] Cash Crisis for presidents
- [x] Cash crisis for shorters
- [x] Treasury shares should be done as per 7.2.3.6
- [x] President can only bid $10 over

### Coal Mine
- [x] A train's route may not start or end at a Coal Mine.
- [x] Coal mines do not count against the train number.

### End Game
- [x] First 8 train is purchased/exported causes it to have 3 more ORs (potentially via a stock round)
- [x] All but 1 bankrupt, immediate end
- [x] Check bankrupcys end in all cash crisis conditions

### Privates
 - [x] Pittsburgh
 - [x] Mail contracts
 - [x] Mountain Engineers
 - [x] Coal Mines
 - [x] Bridges
 - [x] Train station

### Oddities to investigate
- [x] Belt doesn't show up on the market tab
- [x] Fix lawson track upgrades #1756
- [x] Find out why I can't run a route

**Comment by gchambers419** [comment]
A few additional items, major and minor

Initial privates auction: Active player selects item for auction or passes; once all players pass consecutively on selecting, unsold privates leave the game.  There is a "seed money" pot that provides purchasing assistance.

IPO: Available share counts vary based on phase: 2-share = 2, 2+, 3; 5-share = 3,4,5; 10-share = 5-8

Coal Mines: Placed while laying a yellow tile in a mountain hex while owning a coal-mine private.  Yellow tiles with a coal mine on them cannot be upgraded.

**Comment by jenf** [comment]
Laying a track without enough money causes an exception without an explaination.

**Comment by jenf** [comment]
Minor bug, if you skip run trains in acquisition area you do not move to the left

**Comment by jenf** [comment]
Problem on 4 player game, 1 and 2 bid, 3 passes jumps to 2 instead of 4.

**Comment by tobymao** [comment]
check boxed the shorts, seems like only one check box lieft?
