### ISSUE TITLE
[18Ireland] Incorrect number for 2H train

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#6860]
In AAG version, there is 7 2H trains and you can include one more 2H train and make it become 8
But in 18xx.games, there is only 6 2H trains

**Comment by benjaminxscott** [comment]
@scottredracecar can you confirm the train roster? The dropbox link doesn't seem to list the total train count for each type

**Comment by scottredracecar** [comment]
7+1 optional

**Comment by benjaminxscott** [comment]
OK so it should be this? 
![image](https://user-images.githubusercontent.com/1711810/151643085-6afc47de-004d-4a90-8729-8eb62e69ca35.png)
