### ISSUE TITLE
[Harzbahn 1873] Owner of U set to nil due to autopurchase issue

### ISSUE THREAD

**Issue by beorn7** [tobymao/18xx#6861]
**What's your Game ID?**

https://18xx.games/game/68415

**How to Reproduce the Bug?**

Go to the link. The game is stuck at "Loading game..."

This game worked just fine until right now, start of the last SR.

Javascript console says:
```
Object { name: "player?", message: "undefined method `player?' for nil", cause: {…}, args: [], backtrace: (13) […], stack: "  from https://18xx.games/assets/deps.js:1:14303:in `p'\n  from https://18xx.games/assets/main.js:2:27960:in `Opal.modules[\"engine/game/base\"]/<'\n  from https://18xx.games/assets/main.js:62:103394:in `Opal.modules[\"view/game/company\"]/<'\n  from https://18xx.games/assets/main.js:62:99091:in `Opal.modules[\"view/game/company\"]/<'\n  from https://18xx.games/assets/deps.js:25:61655:in `Opal.modules[\"snabberb/component\"]/<'\n  from https://18xx.games/assets/main.js:62:95323:in `l'\n  from https://18xx.games/assets/deps.js:1:16009:in `d.yield1'\n  from https://18xx.games/assets/deps.js:15:20262:in `Opal.modules[\"corelib/enumerable\"]/g/<'\n  from https://18xx.games/assets/deps.js:1:16009:in `d.yield1'\n  from https://18xx.games/assets/deps.js:15:67506:in `V'\n  from https://18xx.games/assets/deps.js:1:18347:in `d.send2'\n  from https://18xx.games/assets/deps.js:1:18173:in `d.send'\n  from https://18xx.games/assets/deps.js:1:21082:in `ne'" }
```

**Which Browser / Platform?**

Happens on Chrome and Firefox and both on desktop and mobile. So I guess it's not platform dependent. Can provide more details if there is new evidence that it is.

**Comment by benjaminxscott** [comment]
Last working action: https://18xx.games/game/68415?action=1343

Do you know what the final action taken in SR8 by Eckhart was that caused the issue?

**Comment by beorn7** [comment]
Almost certainly he passed.

**Comment by benjaminxscott** [comment]
Gotcha, looks like it repros with that action

**Comment by magnusrk-ch** [comment]
It happens in `render_company_on_card` when it calls `show_value_of_companies?(company.owner)` on U. U doesn't have an owner (it's nil), but `show_value_of_companies?` calls `entity.player?` and voila, nil deference.

Not clear to me right away whether the problem is the owner being nil (rather than e.g. an entity representing the bank), or if owner is allowed to be nil and the code should be `entity&.player?`.

**Comment by roseundy** [comment]
I'm looking at this now.

**Comment by roseundy** [comment]
Very odd. The owner of the "U Purchase Option" was set at the end of the concession auction round, but is nil at the start of the Stock Round.

**Comment by roseundy** [comment]
It looks like there was an auto-buy for U set up during the concession auction round by DSteiner even thought that player didn't win the concession.

The bug is that my code is not enforcing that only the winner of the purchase option can restart a company.

**Comment by roseundy** [comment]
Even enforcing the requirement doesn't fix the bug - the programmed purchase causes an infinite loop.

**Comment by beorn7** [comment]
Wow, awesome troubleshooting!

**Comment by magnusrk-ch** [comment]
The PR will not by itself fix the broken game. The last action in the game (1344) already has invalid auto actions attached. This action would have to be deleted or somehow manually undone.

**Comment by beorn7** [comment]
Is there a way how we as mere players can do that? Or do we require the intervention of a site admin? (In the latter case, we would be very grateful if it could be done for us. It's a very close finish in that game that we would love to play to the end.)

**Comment by roseundy** [comment]
The bug is that I didn't add a purchase option check to the "can_buy?" method. This is only needed for auto (programmed) actions. The corresponding "can_par?" for concessions is fine.

The fix will take care of the problem. Once deployed, your game will work fine.

**Comment by roseundy** [comment]
> The PR will not by itself fix the broken game. The last action in the game (1344) already has invalid auto actions attached. This action would have to be deleted or somehow manually undone.

Not true.

**Comment by roseundy** [comment]
OK, I've added to the fix to allow your game to proceed.

**Comment by roseundy** [comment]
We need to ask @tobymao to undo the last player action in the game.

**Comment by beorn7** [comment]
Thanks a million, everyone. Especially @tobymao for resurrecting our game.

However, now even the holder of the U purchase option cannot buy U. I'll file another bug report with all the details.

**Comment by beorn7** [comment]
See #6875
