### ISSUE TITLE
[Harzbahn 1873] Holder of purchase option cannot buy the respective stock.

### ISSUE THREAD

**Issue by beorn7** [tobymao/18xx#6875]
**What's your Game ID?**

https://18xx.games/game/68415

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Go to https://18xx.games/game/68415. Activate master mode, Let player beorn buy a market share of U.

This triggers the error message: "Cannot buy a share of U". However, beorn owns the U purchase option.

This is probably an unintended side effect of #6861.

Also interesting: An "undefined" has appeared now left of the "Upcoming Trains" box:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/5609886/151699971-50f584b9-4aaa-46b0-8bee-0c4b8db566c4.png">

**Which Browser / Platform?**

Pretty sure this happens on any platform.

**Comment by roseundy** [comment]
Bad on me - I didn't test the last edit on my fix. I just verified that it would fail the errant auto-action, not that the correct action would work :-(

**Comment by roseundy** [comment]
It was an ordering issue in process_buy_shares, and not the check I added to process_buy_shares - which is actually superfluous.

**Comment by beorn7** [comment]
Thank you very much once more.

**Comment by roseundy** [comment]
Hopefully, you can get farther this time.
