### ISSUE TITLE
Auto-routing gives invalid results

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#6882]
Given this game and the route for one 4T and the 3T already chosen:
![image](https://user-images.githubusercontent.com/1355029/151776192-261d23eb-a643-44b7-a1ba-ff9cadab52c5.png)
auto-routing yields a rather funny result:
![image](https://user-images.githubusercontent.com/1355029/151776389-c1549a7e-9af2-4784-a803-a3d53fefe01c.png)

Here is the link: https://18xx.games/game/68601?action=730

Without pre-choosing routes it now super quickly finds 10 more than I could find by hand, so that's awesome :D

**Comment by scottredracecar** [comment]
I tried again on a different machine (first was my phone) and got the same result as the phone. I suggest this be closed as "no bug" unless others can reproduce. If this is a problem, others should be along to report their findings shortly via other tickets or this one.

![image](https://user-images.githubusercontent.com/29106780/151836209-88ecb9ef-8aba-4f07-abf2-79e0ce255eae.png)

**Comment by kepakiano** [comment]
I'd appreciate if you didn't do that, as I can reproduce this behavior on two computers (Firefox + Chromium) and my phone.

**Comment by scottredracecar** [comment]
Some other discussion here:
https://github.com/tobymao/18xx/issues/6887#issuecomment-1026108613

**Comment by tysen** [comment]
I just tried locking in two of the trains as originally described and the auto button produced this result:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1501322/151860168-6a5bae2f-1928-4a80-a0d6-17d296f9a5a0.png">
