### ISSUE TITLE
18NewEngland 2 - Place the remaining minor tokens on the map at the conclusion of SR1

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6889]
I got a playtest suggestion that I would like to incorporate.

The perceived problem is that the map is a bit too open and due to the fact that the game is faster paced, the pinch points don't get closed like in the base game because there is less time to start late game minors.

The proposed change is:
- At the conclusion of SR1, place the unfloated minor tokens out on the board
- When a minor floats, don't place its token on the board (because it is already there)

**Comment by philcampeau** [comment]
There would obviously need to still be some way to indicate which minors were currently available and unopened.

**Comment by scottredracecar** [comment]
Yes, that is a wrinkle. For the board game, I would suggest to place both tokens on such spaces to mark unstarted minors. Here, it would be nice to gray them out or something like that (until floated, like the used tokens on the company cards), but I am keeping Steve busy enough as it is currently so I don't want to ask for too much here.

**Comment by roseundy** [comment]
I assume that _all_ unstarted minors do this, not just the ones available at the beginning of the game that didn't get started.

**Comment by scottredracecar** [comment]
Yes, all.

**Comment by roseundy** [comment]
I could make the unstarted minor tokens "flipped" (see 1860 and 1873 for examples)

**Comment by scottredracecar** [comment]
This is what flipped tokens look like, okay with me.
![image](https://user-images.githubusercontent.com/29106780/152543034-98f2a966-9270-48f5-8e6e-74d9bde23661.png)

In the case where available minors are not drafted (so some remain available before Phase 3 starts), those also can have the flipped status (this case should be fairly rare with good players). These would of course still show up as floatable in the game tab.
