### ISSUE TITLE
18CHES Mandatory Train Purchase Despite No Legal Route

### ISSUE THREAD

**Issue by Jonbone67** [tobymao/18xx#689]
Hi -- In a recent 18CHES game (#1797) a player was forced to purchase a train despite not having a route with two revenue centers.  The issue was PLE had purchased COO private and made the Berlin tile lay its first tile lay. This gave two revenue centers (PIttsburgh and Berlin) but without a route I don't believe a train purchase should have been required.  

Unless I'm missing something in the rules.  Thanks.

**Comment by jenf** [comment]
Could you double check you meant PLE
https://18xx.games/game/1797?action=137

PLE was connected Charleroi & Connellsville and the off board which is a valid route.

**Comment by Jonbone67** [comment]
Thanks.
To be clear, I laid the tile in Berlin intending not to buy a train. When
the game required me to buy a train, my fellow players let me rewind my
tile lay.

We couldn’t figure out why I was required to buy a train.

**Comment by jenf** [comment]
Ahh, got it.
https://18xx.games/game/1797?action=128
