### ISSUE TITLE
Autoroute chooses invalid route for two trains on local dit

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#6890]
When autorouting two 2 trains for a single city which has a dit on the same hex, it attempts to run both trains to the same dit, which is invalid

https://18xx.games/game/69695?action=135

https://gist.github.com/benjaminxscott/486b6bc834f215be477dbdb68477ca32

cc @JoeB989 
![IMG_5089](https://user-images.githubusercontent.com/1711810/151878168-dcd4da85-7585-489f-9082-c0b01ef1fd24.jpg)
![IMG_5090](https://user-images.githubusercontent.com/1711810/151878177-28cfc8b0-edf9-461e-93a2-7eda889c5c89.jpg)

**Comment by JoeB989** [comment]
Looks like an auto-router bug because the routes don't cross any hexsides.  I'll look into

**Comment by JoeB989** [comment]
Ok I can fix this.  But can you also send me a more developed map where there are longer routes through that tile?  I'm probably not handling city + dit inside a longer route

**Comment by benjaminxscott** [comment]
In this game, the tile will upgrade to a regular city so I don't think it's a good example

I can grab an 18Mex game where it should have longer routes through such "dit cities"

Here's a game where P13 +dit is the terminal of a train, which seems to work fine via Auto
https://gist.github.com/benjaminxscott/fe8a1642cb65487165e68f2e343b0df9

**Comment by JoeB989** [comment]
Ok, thanks, I'll add to my collection.
