### ISSUE TITLE
1840: "Upcoming trains" display on spreadsheet is "behind" by one round

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#6892]
The "Upcoming trains" display on the spreadsheet tab is "behind" by one round.  

Example: at this game point, the *upcoming* CR is CR5, which is the *last CR* where trains are purchased.  So the current "upcoming trains" should show PI3 and Pu2 (it incorrectly shows R3, Pi2 and Pu1). 
https://18xx.games/game/66610?action=939

This display should be updated to show the upcoming trains for the next CR _as soon as a CR ends_. Instead, it seems to not get updated until a CR _starts_, which sort of negates the purpose of an upcoming trains display.  :)

**Comment by Zwergenpunk** [comment]
I think this is a little bit confusing. 
This just shows the available trains. Maybe the naming is not correct. 1840 is just a special snowflage in that concern.

Do you know another game where this is working in the way you describe? (Is there a game where this is possible?)

**Comment by waaayback** [comment]
> I think this is a little bit confusing. This just shows the available trains. Maybe the naming is not correct. 1840 is just a special snowflage in that concern.

No, the name is correct, and it is a very useful chart.  The problem is just that it is wrong; it is updated incorrectly.  

Here is a picture of the train display from the Share Price Board (p3 of the rules, but hard to see):
![image](https://user-images.githubusercontent.com/66023744/152241753-d850b865-513a-4ada-a0e1-476fdfa4779e.png)

**IMMEDIATELY AFTER** each CR *finishes*, the trains are shifted to the right, so you can see what the prices will be NEXT round.  Unfortunately, 18xx.games leaves it in the 'old state' until just before the next round - hardly useful as a reference!!
> 
> Do you know another game where this is working in the way you describe? (Is there a game where this is possible?)

No. 1840 is an odd beast here....  the trains change in price every stock/company round.

Hope this helps.
