### ISSUE TITLE
18NY certificate limit calculated incorrectly?

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6893]
To the best of my knowledge, all certificates count against the limit in 18NY and there is no yellow zone. Thus, a player with 20 certificates and 3 presidencies should only have 23 shares. This appears to be incorrectly calculated in our game. Similarly, a players with 16 certificates and 2 presidencies should have only 18 shares.

https://18xx.games/game/69166?action=835

<img width="591" alt="Screen Shot 2022-01-31 at 14 06 30" src="https://user-images.githubusercontent.com/8732435/151881151-0801f0d0-893a-484f-b5c7-e67508b65d7b.png">

**Comment by dfannius** [comment]
President's certificates are 30%.

**Comment by dfannius** [comment]
Closing as not a bug.
