### ISSUE TITLE
Add async/live game setting and game card tag

### ISSUE THREAD

**Issue by marndt93** [tobymao/18xx#6899]
It is common for users to tag their games as "live" or "async" in the game description.  It can be confusing if a game is not tagged in the description whether the game is intended to be played live or async.  This could be solved by adding radio buttons to select live/async options when creating a new multiplayer game (default async).

example mock up:

![image](https://user-images.githubusercontent.com/28715646/151916417-47169213-1544-4d98-ac85-de0744f87cb5.png)

**Comment by scottredracecar** [comment]
Maybe even more apparent by coloring the yellow header instead and having the text under the Join button?

**Comment by marndt93** [comment]
> Maybe even more apparent by coloring the yellow header instead and having the text under the Join button?

Do you mean something similar to this?
![image](https://user-images.githubusercontent.com/28715646/151918852-ab73b0ad-9a31-48a4-9984-cbf10c71aeb3.png)

**Comment by tobymao** [comment]
oh god no

**Comment by marndt93** [comment]
> oh god no

lol, not a fan of doing it this way either.  The header looks too cluttered

**Comment by scottredracecar** [comment]
Well, conceptually, yes, but not those colors of course. The current yellow is fine for async and then for live, you could use #DAF7A6 for example. I can help pick different alternative colors too.

I don't like that the extra word makes the header bigger so I would suggest to put that in the button "Join Async" or "Join Live"

**Comment by marndt93** [comment]
So you're thinking like this:
![image](https://user-images.githubusercontent.com/28715646/152049956-3908346d-e6c3-4e49-bd9d-3bc9c3d76da3.png)

**Comment by scottredracecar** [comment]
Yes, but to pick a color that is a bit more distinct than yellow, perhaps
try #91F0FF?

**Comment by scottredracecar** [comment]
Could you show a screenshot using #91F0FF? I really like this idea.

**Comment by marndt93** [comment]
@scottredracecar 
![image](https://user-images.githubusercontent.com/28715646/152464068-4ccff715-3c7e-4304-996b-6ee38eabe4b1.png)

**Comment by scottredracecar** [comment]
Looks good to me.

**Comment by marndt93** [comment]
should I proceed with this design then?
@tobymao @scottredracecar

**Comment by scottredracecar** [comment]
yes
