### ISSUE TITLE
Blocked Hexes not blocked

### ISSUE THREAD

**Issue by Panzerlied7** [tobymao/18xx#691]
Hi,
I'm doing a hotseat of 18Chesapeake and doing OR2.1 and the LV is operating. All of the privates are still in players hands but it seems that LV is able to lay tiles in both I3 and K3 - which should be blocked. Or am I misunderstanding the rules? 

Not really sure if this is the proper method to report an issue and I really didn't have any interest in signing up for GitHub; but those seem to be the steps required. 

Panzerlied

**Comment by tobymao** [comment]
can you paste the game data here or provide the game id?

**Comment by Panzerlied7** [comment]
GameID:  hs_cizzijmx_1592015995

 

I’ve left things alone – didn’t expect this quick a response.

 

JimA

**Comment by tobymao** [comment]
this is a hot seat game and i don't have access to it, can you got to the tools tab, copy that blob of data and paste it here?

**Comment by Panzerlied7** [comment]
{

  "status": "active",

  "actions": [

    {

      "type": "bid",

      "entity": "Jim",

      "entity_type": "player",

      "id": 1,

      "company": "Columbia - Philadelphia Railroad",

      "price": 45

    },

    {

      "type": "bid",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 2,

      "company": "Baltimore & Ohio Railroad",

      "price": 105

    },

    {

      "type": "bid",

      "entity": "Lied",

      "entity_type": "player",

      "id": 3,

      "company": "Baltimore and Susquehanna Railroad",

      "price": 55

    },

    {

      "type": "bid",

      "entity": "Jim",

      "entity_type": "player",

      "id": 4,

      "company": "Delaware and Raritan Canal",

      "price": 20

    },

    {

      "type": "bid",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 5,

      "company": "Chesapeake and Ohio Canal",

      "price": 80

    },

    {

      "type": "bid",

      "entity": "Lied",

      "entity_type": "player",

      "id": 6,

      "company": "Cornelius Vanderbilt",

      "price": 200

    },

    {

      "type": "par",

      "entity": "Lied",

      "entity_type": "player",

      "id": 7,

      "corporation": "PRR",

      "share_price": "95,2,4"

    },

    {

      "type": "par",

      "entity": "Jim",

      "entity_type": "player",

      "id": 8,

      "corporation": "B&O",

      "share_price": "95,2,4"

    },

    {

      "type": "par",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 9,

      "corporation": "C&O",

      "share_price": "95,2,4"

    },

    {

      "type": "par",

      "entity": "Lied",

      "entity_type": "player",

      "id": 10,

      "corporation": "LV",

      "share_price": "80,3,3"

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 11,

      "shares": [

        "B&O_2"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 12,

      "shares": [

        "C&O_1"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Lied",

      "entity_type": "player",

      "id": 13,

      "shares": [

        "LV_1"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 14,

      "shares": [

        "B&O_3"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 15,

      "shares": [

        "C&O_2"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Lied",

      "entity_type": "player",

      "id": 16,

      "shares": [

        "LV_2"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 17,

      "shares": [

        "B&O_4"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 18,

      "shares": [

        "C&O_3"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Lied",

      "entity_type": "player",

      "id": 19,

      "shares": [

        "LV_3"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 20,

      "shares": [

        "B&O_5"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 21,

      "shares": [

        "C&O_4"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Lied",

      "entity_type": "player",

      "id": 22,

      "shares": [

        "LV_4"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 23,

      "shares": [

        "LV_5"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 24,

      "shares": [

        "LV_6"

      ]

    },

    {

      "type": "lay_tile",

      "entity": "B&O",

     "entity_type": "corporation",

      "id": 25,

      "hex": "G7",

      "tile": "9-0",

      "rotation": 1

    },

    {

      "type": "buy_train",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 26,

      "train": "2-0",

      "price": 80

    },

    {

      "type": "pass",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 27

    },

    {

      "type": "lay_tile",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 28,

      "hex": "G13",

      "tile": "57-0",

      "rotation": 2

    },

    {

      "type": "buy_train",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 29,

      "train": "2-1",

      "price": 80

    },

    {

      "type": "pass",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 30

    },

    {

      "type": "lay_tile",

      "entity": "LV",

      "entity_type": "corporation",

      "id": 31,

      "hex": "J2",

      "tile": "57-1",

      "rotation": 1

    },

   {

      "type": "buy_train",

      "entity": "LV",

      "entity_type": "corporation",

      "id": 32,

      "train": "2-2",

      "price": 80

    },

    {

      "type": "pass",

      "entity": "LV",

      "entity_type": "corporation",

      "id": 33

    },

    {

      "type": "pass",

      "entity": "Panzer",

      "entity_type": "player",

      "id": 34

    },

    {

      "type": "pass",

      "entity": "Lied",

      "entity_type": "player",

      "id": 35

    },

    {

      "type": "pass",

      "entity": "Jim",

      "entity_type": "player",

      "id": 36

    },

    {

      "type": "lay_tile",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 37,

      "hex": "F8",

      "tile": "X1-0",

      "rotation": 0

    },

    {

      "type": "place_token",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 38,

      "city": "X1-0-0",

      "slot": 0

    },

    {

      "type": "run_routes",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 39,

      "routes": [

        {

          "train": "2-0",

          "connections": [

            [

              "H6",

              "G7",

              "F8"

            ]

          ]

        }

      ]

    },

    {

      "type": "dividend",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 40,

      "kind": "payout"

    },

    {

      "type": "pass",

      "entity": "B&O",

      "entity_type": "corporation",

      "id": 41

    },

    {

      "type": "lay_tile",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 42,

      "hex": "F12",

      "tile": "8-0",

      "rotation": 3

    },

    {

      "type": "run_routes",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 43,

      "routes": [

        {

          "train": "2-1",

          "connections": [

            [

              "H14",

              "G13"

            ]

          ]

        }

      ]

    },

    {

      "type": "dividend",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 44,

      "kind": "payout"

    },

    {

      "type": "buy_train",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 45,

      "train": "2-4",

      "price": 80

    },

    {

      "type": "pass",

      "entity": "C&O",

      "entity_type": "corporation",

      "id": 46

    }

  ],

  "id": "hs_cizzijmx_1592015995",

  "players": [

    {

      "name": "Jim"

    },

    {

      "name": "Panzer"

    },

    {

      "name": "Lied"

    }

  ],

  "title": "18Chesapeake",

  "description": "",

  "max_players": "3",

  "mode": "hotseat",

  "user": {

    "id": 0,

    "name": "You"

  },

  "created_at": "2020-06-12",

  "loaded": true,

  "result": {}

}

**Comment by tobymao** [comment]
i see no issue. i try to lay those hexes and receive an error 

"I3 is blocked by Columbia - Philadelphia Railroad"

**Comment by Panzerlied7** [comment]
Hi Toby,

 

And thanks for looking in to the issue. I was able to click on the hex and choose a tile; I didn’t bother trying to check the box to lay the tile. I see now that it would stop me at that point. 

 

Sorry for muddling up your wonderful project. Seems to work great and I’m trying to get some friends signed up for accounts so we can play while quarantined. 

 

Who do I talk to about putting 1831 in the system? Or 18Africa? 

 

JimA

**Comment by tobymao** [comment]
You did not "muddle" up the project so no worries there. The first steps towards getting games into the system is permission. You'll need to contact whoever has the rights to those games and have them send me an email granting permission.

**Comment by Panzerlied7** [comment]
Hi Toby,

 

I was wondering who actually is doing the coding for these projects? 

 

If I talk with the 18Africa designer (in England) and he says go for it; who would actually “go for it”?

 

I have to say this is the greatest implementation of anything to do with 18xx. Discord and your site makes it seem like I am hosting my game group as we have for 30 years. 

 

JimA

**Comment by tobymao** [comment]
Hey Jim,

I and other contributors are coding these projects. We're getting new contributors every day. There are right now 2-3 core contributors and many more minor contributors. If the 18Africa designer says go for it, it would go into the queue, and then whoever wants to implement it can do so. 

Realistically, it will be a long time before it actually happens since I personally have little interest in it. You'd probably have to find someone who has the skills and interest to see it happen.

**Comment by Panzerlied7** [comment]
Hi Toby,

 

I’m trying 1889 and have the Duogo private that gives me a share of the Iyo from the IPO. However, I don’t get the opportunity to get that share if I wait too long during the initial stock round. Once the other player buys their last share needed to float (and no money to buy anything else) we are immediately moved to the OR phase. Rather than moving to my last turn of the stock round and being able to trade in Duogo for a share of Iyo. 

 

{

  "status": "active",

  "actions": [

    {

      "type": "bid",

      "entity": "Jim",

      "entity_type": "player",

      "id": 1,

      "company": "DR",

      "price": 65

    },

    {

      "type": "bid",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 2,

      "company": "SMR",

      "price": 55

    },

    {

      "type": "bid",

      "entity": "Jim",

      "entity_type": "player",

      "id": 3,

      "company": "ER",

      "price": 45

    },

    {

      "type": "bid",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 4,

      "company": "MF",

      "price": 35

    },

    {

      "type": "bid",

      "entity": "Jim",

      "entity_type": "player",

      "id": 5,

      "company": "TR",

      "price": 20

    },

    {

      "type": "par",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 6,

      "corporation": "AR",

      "share_price": "65,5,3"

    },

    {

      "type": "par",

      "entity": "Jim",

      "entity_type": "player",

      "id": 7,

      "corporation": "IR",

      "share_price": "70,4,3"

    },

    {

      "type": "buy_shares",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 8,

      "shares": [

        "AR_1"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 9,

      "shares": [

        "IR_1"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 10,

      "shares": [

        "AR_2"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Jim",

      "entity_type": "player",

      "id": 11,

      "shares": [

        "IR_2"

      ]

    },

    {

      "type": "buy_shares",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 12,

      "shares": [

        "AR_3"

      ]

    },

    {

      "type": "undo",

      "entity": "AR",

      "entity_type": "corporation",

      "id": 13

    },

    {

      "type": "buy_shares",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 14,

      "shares": [

        "AR_3"

      ]

    },

    {

      "type": "undo",

      "entity": "AR",

      "entity_type": "corporation",

      "id": 15

    },

    {

      "type": "buy_shares",

      "entity": "Alternate Jim",

      "entity_type": "player",

      "id": 16,

      "shares": [

        "AR_3"

      ]

    }

  ],

  "id": "hs_wlncidzb_1594867996",

  "players": [

    {

      "name": "Jim"

    },

    {

      "name": "Alternate Jim"

    }

  ],

  "title": "1889",

  "description": "GDoR",

  "max_players": "2",

  "mode": "hotseat",

  "user": {

    "id": 0,

    "name": "You"

  },

  "created_at": "2020-07-15",

  "loaded": true,

  "result": {}

}

**Comment by tobymao** [comment]
this is not the right place to report issues, this thread is reserved fro "Blocked hexes not blocked"

but to answer your question, that's intentional, you can exchange iyo at anytime, even in the operating round
