### ISSUE TITLE
18SJ Full Cap

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#6910]
Info tab says 

"Full Cap | New corporations will be capitalized for 10 x par price when 60% of the IPO is sold"

I "reserved" a presidency when on the 4T...next SR i floated the company based on this statement and only got Incrementally capitalized   70019

**Comment by perwestling** [comment]
Do you have a link to that game?

**Comment by perwestling** [comment]
The implementation do match the actual rules.
(§12.13)
"When phase 5 starts payment for sold
shares in corporations that have 100% of its shares
still in the initial offering is made from players to the
bank and the bank pays the corporation an initial
treasury equal to ten times its share value when
floating.

**Payment for any corporations with at least one cer-
tificate that has been acquired by a player is still
made to the corporation’s treasury if there is any
unsold stock remaining on the corporation’s char-
ter.**"

I will update the Event description to make it clearer.

Maybe something like:
Full Cap | Corporations completly with 100% in IPO at start of phase ...

Need to check how to best put in the description here.

**Comment by perwestling** [comment]
If you look up under trains you can see that there is a "Full Capitalization" there and the description:
"Unsold corporations becomes Full Capitalization and move shares to IPO"

But I will try to improve the Status text to make it clearer that the "10 x par price" only applies to the corporations that are turned into Full Cap when first 5 train is sold.

**Comment by perwestling** [comment]
@benjaminxscott Is this OK?
![image](https://user-images.githubusercontent.com/2631151/152649372-77002149-9862-463c-9cf4-321be8e3233e.png)
