### ISSUE TITLE
"undefined" rendered for games where bank is infinite

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#6918]
An `undefined` element is being created during stock rounds in games such as CZ or Harzbahn where the bank is infinite

In Harzbahn:
![image](https://user-images.githubusercontent.com/1711810/152255707-834984ec-cd12-42ca-9568-64d6e6c778f3.png)

https://18xx.games/game/68415?action=1343

In CZ:

![image](https://user-images.githubusercontent.com/1711810/152255771-5c81b119-16d6-4b28-8ad9-897b84c61896.png)

https://18xx.games/game/71275?action=154

This seems to be related to the recent change where the train roster and bank are included in stock rounds

**Comment by roseundy** [comment]
21Moon will have this problem, too.

**Comment by benjaminxscott** [comment]
I believe the fix is generic, so Moon should be fixed
