### ISSUE TITLE
1836Jr30 Special Rules

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#692]
This game is ostensibly supported already with just a config file.

A few necessary rules are currently unsupported.
- [x] OO yellow hex (Erie-style company) NBDS company needs to be implemented.
- [x] Allow NBDS to move it's token after upgrading from a tile without edges to a tile with edges [issue](https://github.com/tobymao/18xx/issues/801)
- [x] Allow GCB to trade for pool share [issue](https://github.com/tobymao/18xx/issues/804)
- [x] Paris/Dover/Harwich are all treated the same. They are not revenue centers, but instead add 20/30 to a company's run for each token they run. A company cannot run a 2T from a token to one of these offboards because it is not a revenue center.
- [x] Chemin de Fer de Lille à Valenciennes doesn’t automatically close when Nord buys a train.
- [x] Implement brown stock market zone.
- [x] NY tile has the correct definition, but doesn't render correctly so the second slot in each city can't be tokened.
![image](https://user-images.githubusercontent.com/29106780/84571217-77175800-ad57-11ea-9567-dc17dfecce94.png)

Other rules can be moderated by the players.

- [x] There are four impassible hexsides. (game is playable without this change as long as players are aware)
- [x] A corporation may only buy one of each train type per operating turn

Graphical glitches
- [x] OO tiles only show one city in the center

Here are the rules
https://boardgamegeek.com/filepage/114572/1836jr-30-rules

Here is the map. There are some symbols on the map that aren't used for the 30 version and are instead used for the 56 version.
![image](https://user-images.githubusercontent.com/29106780/84558942-40602400-acfc-11ea-8dbd-10a023e6b047.png)

**Comment by TheExcalabur** [comment]
- [ ] Fix orientation of pre-printed track (off by 60°)
- [ ] Fix display of multi-hex privates (not showing at all)
- [ ] Make it clear that this is 36jr 30. 
- [ ] Fix display for port/paris off-maps: it's not at all clear that they have funny rules.

**Comment by TheExcalabur** [comment]
- [ ] Phases not changing correctly upon purchase of 3-train.

**Comment by dennislaumen** [comment]
Chemin de Fer de Lille à Valenciennes doesn’t automatically close when Nord runs a train.

**Comment by scottredracecar** [comment]
Thanks @dennislaumen added that to the master list.

@TheExcalabur your comments are fixed. I don't know that we will do anything different with the display of Paris/ports, probably change to +20/+30, but adding "+" now will break the game.

**Comment by jenf** [comment]
I'll pick up the NY tile problem

**Comment by kodemaniak** [comment]
If I buy in the Enkhuizen-Stavoren Ferry I can not lay the free tile.

**Comment by scottredracecar** [comment]
Okay, I added the Enkhuizen-Stavoren Ferry tiles. It will be pushed to the site sometime soon, not sure exactly when.

**Comment by sorrellbo** [comment]
Could not purchase more than one cert of a company in the brown area of the market.

**Comment by scottredracecar** [comment]
@sorrellbo Yeah, it's the first game with a brown zone, so that's not implemented. I'll add it to the list.

**Comment by jenf** [comment]
all dev items done, now come the bugs

**Comment by webbtraverse08** [comment]
It would appear, based on the rules and a couple notes on BGG forums, that Nord should not be required to own a train until it connects with another revenue center other than Paris. At present, it’s required to purchase in OR1 with its connection to Paris, which is not a legal route.

**Comment by webbtraverse08** [comment]
Also, an issue above is checked as complete, but I’m not seeing/reading that fix on the board:

“ Fix display for port/paris off-maps: it's not at all clear that they have funny rules.”

Maybe implement a +20/+30 as on the printed map?

**Comment by jenf** [comment]
First issues known bug
Second create a bug for
