### ISSUE TITLE
[1850] - No link to rules

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6922]
I found this pdf online: https://www.tckroleplaying.com/bg/1850/1850-Rules.pdf

This is the site that links to the pdf: https://www.tckroleplaying.com/bg/1850/rules

**Comment by benjaminxscott** [comment]
This game isn't meant to be prod yet, fwiw

**Comment by scottredracecar** [comment]
I'm sure this will be added before it goes to prod.
