### ISSUE TITLE
[18NY] End of game loan stock value penalty is missing

### ISSUE THREAD

**Issue by dlpierce** [tobymao/18xx#6926]
https://18xx.games/game/69998

The 18NY rules say

> Each player's net worth is the sum of their cash plus the current stock value of each share they own (companies that hold loans have their stock value reduced by $5 per outstanding loan).

At the end of this game several corporations have outstanding loans, but the above rule seems to not be applied. For example my (Moofed) value is calculated as $9549, but should be $9369 when taking into account the market value loan penalties.

It would also be desirable to have any loan penalties announced in the game log.

**Comment by crericha** [comment]
Yup, missed this rule. I'm surprised no one noticed until now.
