### ISSUE TITLE
[18Rhl] p4 implemented incorrectly 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#6948]
https://18xx.games/game/70978

“ As director of a corporation the owner may upgrade *one* of the yellow hexes of Köln / Düsseldorf / Duisburg for free. This tile placement is in addition to the corporation's normal tile lay. The corporation may place a station token there in the same OR by paying the appropriate costs. There need not be a link to the corporation's network. If the station marker is not placed in the same Operating Round but later, the corporation must have a track connection to that hex. After the placement of the station token the corporation may not place a tile even when it has not used its normal tile lay (placing a station marker is always the step after the tile lay!). Note! Token can only be used together with the upgrade to green and not as a token-only action. If all applicable hexes are green the special ability is no longer usable.”

 p4 is supposed to allow you to upgrade for free and pay for a token, but it is charging for the upgrade and the token is free.

**Comment by discoking7** [comment]
Moreover, it's not allowing the upgrade after I lay my regular tile.  P2 is also behaving that way.  I get an error, "Upgrade not allowed."

**Comment by BellmakerSA** [comment]
the wording on both is poor, but I believe p2 and p4 are supposed to replace the normal tile lay.

**Comment by discoking7** [comment]
P4 expressly states that it does not.  P2 does not, but the last sentence implies it does not (I wouldn't argue that hard for it though).

**Comment by perwestling** [comment]
Have now corrected some problems with P2 and P4. Might revisit the text - the original game does use a reference to the rulebook.

I agree that the wording in the rule book does imply that P2 and P4 works in the same way - allowing to do a regular tile lay after the private has been used. Both P2 and P4, in the rule book, does mention that regular tile lay cannot be done after special tokening so this does indicate that the ability is "extra".

**Comment by perwestling** [comment]
I realize that the wording also have another affect:
- A player with both P2 and P4 can do P2-lay, P4-upgrade, regular lay. (Maybe even more P:s...)
- But if tokening is done as part of a P this stops any further tile lays / upgrades.

So I will revisit my fix above.

**Comment by perwestling** [comment]
Have now updated descriptions for P2 and P4, and added implementation to stop ANY tile lay/upgrade after a tokening. So if using e.g. P2 + token no more privates can use their lay tile abilities, and neither can regular.

Need to be approved, and deployed, so it might not appear in actual games for a couple of days.

**Comment by perwestling** [comment]
@BellmakerSA, @discoking7 Now the corrections are deployed. So please try them out again to see if there is any remaining problems.

**Comment by discoking7** [comment]
Looks good!  We're moving the game along to hunt for the next bug.
RB
   On Saturday, February 5, 2022, 05:28:10 AM EST, Per Westling ***@***.***> wrote:  
 
 


@BellmakerSA, @discoking7 Now the corrections are deployed. So please try them out again to see if there is any remaining problems.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
