### ISSUE TITLE
Crash in 18NY

### ISSUE THREAD

**Issue by Leepers500** [tobymao/18xx#6956]
https://18xx.games/game/69418?action=94

**Comment by crericha** [comment]
It is illegal to take loans during train buy phase and then not buy a train. Since someone in your game did that, your game is no longer valid.

@tobymao, please delete/archive the game.

**Comment by scottredracecar** [comment]
Is this not recovered with the new fix?

**Comment by crericha** [comment]
No, an illegal move was made earlier in the game. The game didn't catch it
before and now it does.
