### ISSUE TITLE
1862 Under obligation to buy stocks with max stocks

### ISSUE THREAD

**Issue by mattiasbpersson** [tobymao/18xx#6958]
https://18xx.games/game/67794

**How to Reproduce the Bug?**

During 1862: Phase B - Parliament Round I had maximum number of stocks but could still outbid other players. We I hade won the bid I was unable to buy the stocks when under obligation.

I guess the best solution should be to check that the player bidding has at least 2 stocks left to buy.

**Comment by Maxwell-Frank** [comment]
Rule 4.1 You can't place bids if you're at cert limit.

**Comment by scottredracecar** [comment]
Close?

**Comment by dfannius** [comment]
Seems like a real bug to me.

**Comment by Maxwell-Frank** [comment]
Definitely a bug. Players are allowed to bid when they are at cert limit and should not.  Sorry for the confusion.

**Comment by roseundy** [comment]
https://18xx.games/game/67794?action=316
