### ISSUE TITLE
During operating rounds, align map & other stuff side by side with CSS

### ISSUE THREAD

**Issue by Bastwood** [tobymao/18xx#697]
Currently, operating a company involves a lot of scrolling back and forth to check the map, check the company assets and click the various buttons. It'd be better if the map and "the rest" of page elements (basically everything after company order and before the map; can't refer to anything specific since the dividers are unnamed) were displayed side by side if there's enough screen real estate available. Preferably map on the left, controls on the right. Should be easily achievable in CSS with two separate inline-blocks/float or somesuch.

Of course this enhancement would not be something that mobile users really benefit from, but I reckon a considerable portion of users run the site on their computers and have plenty of screen width available.

**Comment by tobymao** [comment]
agreed, this is planned

**Comment by tobymao** [comment]
fixed
