### ISSUE TITLE
[1862] Placing a town / dit / small station should not require a route to the hex.

### ISSUE THREAD

**Issue by goldencow2** [tobymao/18xx#6976]
https://18xx.games/game/69479?action=389

The L&H wants to add a town to the green plain track near the bottom of the board, but I am getting the standard "Must use new track or change city value" message.

Rulebook:

> 7.6.4 Placing Small Stations
Instead of laying or upgrading track, a company may build
a small station on a stretch of plain track on a hex tile which
does not already contain a station. The hex and the small
station can be anywhere on the board; **the company does not need
to be able to trace a route to the hex tile or station in order to make
the build**.

![Untitled](https://user-images.githubusercontent.com/43799724/152653491-3b392a60-7db0-44a2-b7d3-cc6e534ecc41.png)

**Comment by roseundy** [comment]
It's amazing to me that this was just found now. A testament to the complexity of the rules.
