### ISSUE TITLE
Tailor the Allowed Number of Players to the Player Counts Defined in the Config

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#698]
18xx.games currently allows all games to be joined by 2-6 players. The latest game 1836Jr only supports 2-4 players. Starting cash and certificate limit are not defined for more than 4 players.

18xx.games should limit the number of players that can join a game to the max player count, for example by looking at the highest starting cash player count in the config.

**Comment by gchambers419** [comment]
1846 is 3-5 players.
