### ISSUE TITLE
18NewEngland phase 3 companies marked green

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6996]
At the beginning of the game, the companies that are eligible or claimed are marked with grey. However, once the game starts, there's no differentiation between available companies and those that may only be started beginning in phase 3.

https://18xx.games/game/71402?action=71#map

<img width="600" alt="Screen Shot 2022-02-06 at 07 39 18" src="https://user-images.githubusercontent.com/8732435/152688652-c72ca3bf-87c5-497d-9ca5-771f6de8eafb.png">

It would be nice if the phase 3 companies were marked in green, as you can see in 1861 (and 1867):

<img width="392" alt="Screen Shot 2022-02-06 at 07 42 54" src="https://user-images.githubusercontent.com/8732435/152688759-0b14b219-4246-49e6-bc0f-46bd7cb58227.png">

**Comment by scottredracecar** [comment]
While that sounds like a reasonable suggestion, I think it would make the experience worse because then there are a lot of city spots (most of which are typically integrated into the network) that will show green and look like tokens. In contrast, in 1861, the green minors are mostly disconnected from the network until they open so it is less invasive there.

**Comment by ChrisTheCat** [comment]
Is there any easy way to mark which companies are available then? At that
point in the game, I had to go to the spreadsheet, see which two companies
are available, go back to the map, search and find them, etc. And I almost
made the terrible mistake of thinking all the companies, which look
identical to each other, were available.

**Comment by ChrisTheCat** [comment]
Maybe look at the way 1862 manages available vs. unavailable?

**Comment by scottredracecar** [comment]
I am open to improvements here, but this is where I look for this information:
https://18xx.games/game/71402?action=75

The "Phase 3" minors aren't shown as available here.

![image](https://user-images.githubusercontent.com/29106780/152689550-f9a33f9d-5b0b-4cf7-b69d-710bc2b8ae60.png)

**Comment by scottredracecar** [comment]
I discussed briefly with @roseundy , he had some thoughts about value in showing available vs unavailable, but for a more general case.

Let's leave this alone for now and reopen if you still think it is a problem in a couple months. I'm sure if it's an ongoing problem there will be no problem remembering it. 🙂

**Comment by ChrisTheCat** [comment]
The issue isn't seeing which ones are available - that's clear on both the
entities tab and the spreadsheet. The problem is instead "visually finding
the available companies on the map." Unless you've memorized the locations
of all the companies, knowing that FRR and NYW is available doesn't help
much. When you glance at the map, you see seven company homes that all look
the same.

I think more people pick their company from the map than from a list on the
entities or spreadsheet.

**Comment by scottredracecar** [comment]
So then I would make an argument for showing the 1 or 2 unfloated "Phase 2"
minors in yellow until Phase 3 instead (zero in 5p). It's different than
the 1861 implementation, but it's less invasive.

**Comment by ChrisTheCat** [comment]
That works. The main thing is a visual indicator for either the available
or the unavailable, to differentiate them.

**Comment by scottredracecar** [comment]
Discussed a bit more with Steve, leaving this closed for now, but feel free to reopen if it is a persistent problem and we will address.
