### ISSUE TITLE
18Rhl - 6Ts available phase 3

### ISSUE THREAD

**Issue by discoking7** [tobymao/18xx#6999]
https://18xx.games/game/70978, but you can see this from the info tab.

After the first 3T, the game makes 6Ts available.

![image](https://user-images.githubusercontent.com/97008782/152692847-6655068c-d0d1-4f12-8f48-1d3930b2eef6.png)
![image](https://user-images.githubusercontent.com/97008782/152692903-30c603c6-2190-429b-b381-3636105fead7.png)

**Comment by discoking7** [comment]
Sorry, I didn't mean to add the triage label, and I can't figure out how to remove it.

**Comment by tobymao** [comment]
i think this is intentional? @perwestling

**Comment by BellmakerSA** [comment]
> i think this is intentional? @perwestling

They should be available with the first 5T, not 3T

**Comment by discoking7** [comment]
Yes, the rules state that 6s come available after the first 5, and 8s after the first 6.

    On Sunday, February 6, 2022, 12:37:43 PM EST, BellmakerSA ***@***.***> wrote:  
 
 



i think this is intentional? @perwestling


They should be available with the first 5T, not 3T

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benjaminxscott** [comment]
`needs triage` gets added automatically btw, to let us know that it's a new issue

**Comment by perwestling** [comment]
This was an error by me. Should have been from the first 5 train, not 3 train.
