### ISSUE TITLE
[1846] Tunnel Blasting not reducing hexside costs

### ISSUE THREAD

**Issue by JustinSCarter** [tobymao/18xx#7001]
(https://gist.github.com/JustinSCarter/6784557477ed2acbc66e05b439133a81)

-B&O buys tunnel blasting in 1.2 and lays track connecting Cincinnati to Louisville
-The total paid is $60 instead of $40.
-Tested out upgrading Wheeling and leaving and also not getting the discount on any hexside costs, but discounts are applying to mountain costs.

**Comment by benjaminxscott** [comment]
Tunnel blasting only reduces mountain costs, like the brown triangle hexes or the brown hexsides

The cinci-> louisville hexside is a "river" cost, so it's not reduced by tunnel blasting

Similarly with the blue river costs next to Wheeling

**Comment by JustinSCarter** [comment]
So I was missing a rule. I was digging through the rules for clarification, but couldn't find anything about blue vs brown triangles. After you mentioned this I checked the actual game board and I can see the difference clarified is printed on the actual game board. Thanks!
