### ISSUE TITLE
18Rhl town upgrades not quite right

### ISSUE THREAD

**Issue by discoking7** [tobymao/18xx#7009]
https://18xx.games/game/70978

Double dits should upgrade to green 4-spoke dits.  Single dits should upgrade to green 3-spoke dits.  Currently, double dit upgrades aren't allowed, and single dits are allowed to upgrade to 4-spokers.

RB

**Comment by discoking7** [comment]
Separate issue, but it also appears that Moers loses it's coal token when upgraded to brown.

**Comment by perwestling** [comment]
I split out the Moers issue to an issue of its own.

**Comment by discoking7** [comment]
Sorry for my laziness there.  Back to bug hunting!

**Comment by perwestling** [comment]
No worries, it was a great find @discoking7
