### ISSUE TITLE
18EU   GameError: Blocking step Exchange Connected Minors for a Share cannot process

### ISSUE THREAD

**Issue by ronaldau** [tobymao/18xx#7021]
We're sorry this game cannot be continued due to GameError: Blocking step Exchange Connected Minors for a Share cannot process action 651
Broken action: { "type": "pass", "entity": 6156, "entity_type": "player", "id": 651, "created_at": 1644227112 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/72034?action=650)

**Comment by ryandriskel** [comment]
Fix has been submitted. I'll keep an eye on it being deployed.

**Comment by ryandriskel** [comment]
Looks like you've already seen it is working. Have fun! :)
