### ISSUE TITLE
18Rhl 70982 6T availables before they should 

### ISSUE THREAD

**Issue by lbleicher** [tobymao/18xx#7023]
**What's your Game ID?**
https://18xx.games/game/70982

**How to Reproduce the Bug?**

I was normally operating RhE on OR5.2, and when entered the "buy trains" step, there was a 3T available (correct, as we're still in phase 3 and there are still two of them available) but also a 6T, which shouldn't be available this early. 
**Which Browser / Platform?**
Mobile, Chrome on android

**Comment by benjaminxscott** [comment]
Game is pinned to a version before this bug was fixed
