### ISSUE TITLE
[18Rhl] - Ratingen variant rules are missing

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#7030]
The rules available for the 18Rhl game do not include any rules (or indeed any mention) of the Ratingen variant.  The rules either need to be updated or the Ratingen variant rules need to be provided somewhere else.

**Comment by goldencow2** [comment]
Paraphrasing from my physical copy:

* Hex E10 and E12 have an overlay placed on them during setup.

* Private 1 is replaced with the Angertalbahn. It's power is to place the special yellow Ratingin tile on hex E12. This must be done after green, it DOES require a route, but it is an ADDITIONAL tile lay. This closes the private.

* Hex E14 is no longer blocked as the corresponding private is not in the game.

* The pre-printed track on hex E10 must be connected when a yellow tile is laid there.

* Only the owner of P1 may lay the yellow Ratingen tile on hex E12 unless it closes first. The yellow Ratingen tile must connect to the pre-printed track.

* Any route that includes hex E12 and at least one steel mill (not coal mine) gets +40 revenue. 8 trains (or, more specifically, the Rheingold Express -- I'm still not sure there's a difference) cannot get this bonus.

**Comment by ddaybell** [comment]
With this explanation,  it appears that the implementation is incorrectly
allowing the Ratingen file to be placed in E10.

**Comment by goldencow2** [comment]
The Ratigen tile -does- go on E10, P1 reserves E12 for a double-town tile as normal.

**Comment by ddaybell** [comment]
Hi goldencow2,

What you're saying appears to be contrary to the rules you paraphrased.
The paraphrased rules above state "Private 1 is replaced with the
Angertalbahn. It's power is to place the special yellow Ratingin tile on
hex E12."  This says that the special Ratingin  tile goes on E12, not E10.
Those rules then state "Only the owner of P1 may lay the yellow Ratingen
tile on hex E12 unless it closes first. The yellow Ratingen tile must
connect to the pre-printed track."  This also says that the Ratingin tile
goes on E12, not E10.

Those rules also state "The pre-printed track on hex E10 must be connected
when a yellow tile is laid there."  This appears to indicate that E10 can
have any yellow tile laid on it, but such tile must connect the pre-printed
track.

Don/Krongar

**Comment by goldencow2** [comment]
Again, you are reading my non-edited post in which I got it backwards but promptly fixed. Please see the actual post on github instead of reading it presumably through e-mail.

**Comment by perwestling** [comment]
As I understand it "8 train" and "Rheingold express" is the same. This means that the 8 train must start in an RGE off-board hex, and will never get any bonus related to raw materials, nor any non-RGE off-board hexes. But maybe the difference might be that Rheingold Express is it when it goes from RGE off-board to RGE off-board, as it then receives the RGE bonus(es), and otherwise it is "just" an 8 train. But besides the RGE bonus(es) they both follow the same restrictions and rules.

**Comment by perwestling** [comment]
I have been in contact with Marflow about getting access to online version of Ratingen rules. When this appear I will add the link for them to the wiki page.

I believe the update of the Wiki, adding summerized Ratingen rules, is sufficient for now, so I will close this issue.

Please try it out and report any problems with the implementation by writing new issue(s).
