### ISSUE TITLE
[18NY] Can't handle minor company in Pool during NYC formation

### ISSUE THREAD

**Issue by arroosen** [tobymao/18xx#7050]
Player bankruptcy left minors in the Pool. Gets an error whether preceding company declines or accepts the merge into NYC.
https://18xx.games/game/70598

**Comment by crericha** [comment]
The rules don't address this situation. I've reached out to the author for clarification.

**Comment by crericha** [comment]
I received clarification from the designer and will get a fix in tomorrow; however, it looks like your game is broken due to another bankruptcy fix I made and will be archived.
