### ISSUE TITLE
[18Rhl] - Tjt private allows me to place a free token in a different city than the one I upgraded.

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#7053]
https://18xx.games/game/72137

The game is allowing the Tjt private (#3) to upgrade one of the Rhine city tiles, and place a free token in a different city (i.e. a Rhine city that was not upgraded).  This appears to be contrary to the description printed on the private, which says that the owner can "upgrade *one* of the yellow hexes of Köln / Düsseldorf / Duisburg for free. This tile placement is in addition to the corporation's normal tile lay. The corporation may place a station token there in the same OR by paying the appropriate costs. "  By placing a token "there", this appears to mean the same city that was just upgraded.

((This part has been extracted to a new issue, #7058:)) _Also, in this same game, if I click on the Pass Token button after laying the free Rhine city tile upgrade, I get an "undefined method 'sym' for Engine::Corporation:CCE" error message and I cannot continue.  I already have a token in the upgraded city site, so I can't put a token there.  This is when I discovered the apparent bug above, that allowed me to put a token in a city I did not upgrade using this private._

To aid in troubleshooting this, I made a clone of the game state, pasted below:

https://gist.github.com/benjaminxscott/f0a06143ed5be6a64259c5c871d28368

**Comment by perwestling** [comment]
Tjt private is number 4, but yes, it does look like RHL is allowing things not according to the rules, so I will check that out.

I will clone this issue as well, to handle the sym error. I got a similar error in a pinned game, when using Private 2 teleport tile, but it seems this problem remains after correction of private 2/4.

Good findings, thanks.
