### ISSUE TITLE
[18Ireland] Unable to cross-buy a train 

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#7062]
GNRI is unable to purchase a train across from the MGWR or MRNCC (all three have the same president)

https://18xx.games/game/71415?action=692

https://gist.github.com/benjaminxscott/9cbb3570b45984bc20c2f775acc3f201

GNRI only has one train, and the train limit for majors is 2

Looks like it doesn't present the option to purchase a train across from *any* corporation, fwiw

**Comment by dfannius** [comment]
This may be due to #6955. I'll take a look.

**Comment by dfannius** [comment]
Someone else noticed this too but assumed it was user error and didn't report it :/ https://18xx.games/game/69781?action=917
