### ISSUE TITLE
18RHL: Company in recievership can lay tiles

### ISSUE THREAD

**Issue by lamaros** [tobymao/18xx#7064]
I'm afraid I'm a novice with the bug reports, but these two issues have popped up while playing around in hotseat mode.

The first is inconsistent, with it only happening to one of two companies in receivership. The second seems pretty consistent. I'm not 100% this is me reading the rules wrong, but I don't believe it's against the rules.

I've copied the hotseat game here:

https://gist.github.com/lamaros/b294ec57411d41c0544e7c4eb77b23a6.js

**How to Reproduce the Bug?**

The hotseat game is at the point where the receivership company can lay a tile (not allowed) and then not run a route between southern offboards Liege to Basel (should be allowed).

It also happened in another hotseat test with Frankfurt.

![image](https://user-images.githubusercontent.com/20588367/153355356-4aa41b44-6cb9-4368-bbd0-075802cce6a9.png)
![image](https://user-images.githubusercontent.com/20588367/153355373-68ba1b2b-0ac5-4a20-8a1b-f5e332345a14.png)
![image](https://user-images.githubusercontent.com/20588367/153355289-f2e5b18e-c306-47ad-8efe-79e739cb4ff4.png)

**Which Browser / Platform?**
- Browser Version
  - Firefox, 97.0, Build ID 	20220202182137
- Platform Desktop

**Comment by lamaros** [comment]
The general presentation of Hamburg/Berlin, Arnheim/Nimwegen, Basel/Frankfurt, not being being able to both be hit in one is difficult to convey, but I would suggest removing the rivers, and the joining hex line being a light colour other than black, as in say 1856 Canada West, might help.

My understanding is Liege is not linked to any offboard so that it being tagged like this is a bug?

**Comment by perwestling** [comment]
Thanks for finding the bugs.
I think this issue is 3 different issues, so I will create two new ones, putting some info from here in the two others.
