### ISSUE TITLE
18EU players who declined to initiate auction unable to bid in auction

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7071]
https://18xx.games/game/72018?action=44

nigelsandwich selected minor 15 and declined to initiate an auction
ChrisShaffer declined to initiate an auction
foklik initiated an auction with a bid of 100
Tarl passed on the auction
nigelsandwich passed on the auction
ChrisShaffer should have been offered the opportunity to bid in the auction, but was skipped

Declining to start an auction does not mean that you automatically get passed in an auction if one is initiated.

**Comment by joeyd4329** [comment]
For clarification, it seems like whoever initiated (clicked the Choose button) still gets included in the auction. But if any players thereafter also declines to start an auction, they will get skipped for the auction. For example a four player game. Player 1 chooses a minor up for auction with no bid, players 2 and 3 also decline to put it up for action, player 4 bids.

The bidding will only occur between players 1 and 4 while 2 and 3 will be skipped.

 I think we essentially need what is now called the "pass" button to function the same as the choose button, but (like Chris suggests) have it say decline.
