### ISSUE TITLE
18NewEngland - Just-Bankrupted Player Given Turn

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#7073]
https://18xx.games/game/71519?action=339

Evbapa has just gone bankrupt and the companies are closed, but they are still asked to operate one of them that would normally run next.

**Comment by roseundy** [comment]
Unfortunately, this game has been pinned.

**Comment by roseundy** [comment]
For some reason, close_corporations doesn't actually call Corporation::close!
