### ISSUE TITLE
Add a way to show all stock tokens in a selected cell of the stock market

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7077]
See e.g. the 75 cell in this game of 18NY:  https://18xx.games/game/71704?action=160#market.  There doesn't seem to be an easy way to view the tokens in this stack.  Perhaps selecting the cell could show all tokens in order, in a popup or at the side of the market?

**Comment by ryandriskel** [comment]
Game is archived and no screenshot of the issue.

**Comment by ryandriskel** [comment]
Duplicate https://github.com/tobymao/18xx/issues/5244
