### ISSUE TITLE
[18EU] Populate Minor Cities like 1822

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#7080]
As of right now all the minors have their tokens on the map.

Would it be possible to initially have none of the minors on the map, then when a minor is up for auction it's shaded green like 1822?

Once the minor is acquired by a player, then put its token on the map?

Would make it a little easier figuring out what minors are available and help with overall strategy.

Thanks for any consideration.

Joe

**Comment by ryandriskel** [comment]
I like it! Will get to it after the bugs.
