### ISSUE TITLE
[18 New England] Incorrect price for returned Minor home token during Merge

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7088]
It looks like returned Minor home token during Merge get the cost of $0.
See https://18xx.games/game/71118?action=228

The rule book state (at end of 4th paragraph of rule 12):
"If the two station markers are in the same hex, the president selects one
of them as a home station and returns the other one to its charter in
the $40 cost spot. Otherwise, only one station marker is available for
future use (at $80 cost)."

This is how the newly merged corporation look like after the Merge is completed, and one token was returned due to having 2 tokens in New York:
![image](https://user-images.githubusercontent.com/2631151/153550786-5dbfb300-ed22-43b1-9f10-7a76d3782ad1.png)

**Comment by scottredracecar** [comment]
Yes, returned token should be $40.
