### ISSUE TITLE
Clarify Text on 1889 Privates

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#709]
Takamatsu (private A) text should state “Blocks Takamatsu (K4) while owned by a player”. This is in the rules (15.1), but not clear from the card itself. Also true for Ehime Railway (private C), it should say also in addition say “...blocks Ozhu (C4) while owned by a player”. Just a minor QOL clarity improvement.

**Comment by scottredracecar** [comment]
I can do this, but can you just paste the entire updated text blob here for each one you are suggesting to change?

**Comment by pstone1** [comment]
For: 
![image](https://user-images.githubusercontent.com/13589848/84695502-8261b380-af10-11ea-8f6c-603574d454f8.png)
“Blocks Takamatsu (K4) while owned by a player.”

For:
![image](https://user-images.githubusercontent.com/13589848/84695578-a1f8dc00-af10-11ea-93f0-2639096e2aad.png)
"When this company is sold to a corporation, the selling player may immediately place a green tile on Ohzu (C4), in addition to any tile which it may lay during the same operating round. This does not close the company. Blocks C4 while owned by a player."

**Comment by scottredracecar** [comment]
This is submitted, just waiting on the next code push.
