### ISSUE TITLE
[18EU] Cannot end broken 18EU games

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#7092]
Hi, can someone please delete games 72623 and 72199? They are 18EU games that have been broken by the latest rollout and don't accept actions anymore, so we cannot end them. Here is the message at the top of the game:
`We're sorry this game cannot be continued due to GameError: Blocking step Lay Track cannot process action 398
Broken action: { "type": "run_routes", "entity": "7", "entity_type": "minor", "id": 398, "created_at": 1644429034, "routes": [ { "train": "2-6", "connections": [ [ "J5", "I6", "H7" ] ], "hexes": [ "J5", "H7" ], "revenue": 40, "revenue_str": "J5-H7" } ] }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/72199?action=397)`

**Comment by joeyd4329** [comment]
One can add game numbers 72510 and 72623 to that list of games to delete
