### ISSUE TITLE
18USA: Can you buy pullmans from the depot AFTER running trains?

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#7097]
The 1.4 rules say that pullmans may be bought from the bank ***before*** running trains for $200.
They also say pullmans may be bought from other companies for any price during the buy trains phase.
The rules say nothing about if pullman cars can be bought from the bank during the buy trains phase.
Can pullmans be bought after running trains?

**Comment by scottredracecar** [comment]
Shawn usually answers questions posted to BGG. Maybe not immediately.

Personally, I would play/code for rules as written.

**Comment by bridger15** [comment]
Jason B (who wrote the most recent rules) confirmed that the interpretation above is correct.  You can buy pullmans from the bank before running trains or during the "buy trains" step.

**Comment by ventusignis** [comment]
Thanks, it's now implemented so that a company may run it's trains, then buy a pullman
