### ISSUE TITLE
Disallow duplicate player names in solo mode

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#71]
In solo mode, the user can create players with identical names, which can confuse code that checks for player equality by comparing names.

**Comment by sparr** [comment]
Is there any other way to check player equality that might be more robust?

**Comment by strathmeyer** [comment]
Reproduction steps:
- go to https://www.18xx.games/new_game
- select "Hotseat"
- change all three player names to "Player"
- click "Create"
- click "Mitsubishi Ferry" and then click "Place Bid". Repeat this multiple times.

Expected: Multiple bids show up under Mitsubishi Ferry.
Actual: Only a single bid shows up, and it is incremented by the different players.

Possible solutions: I agree that making player equality more robust could have other benefits throughout the app, but even if we did that, we shouldn't permit two players to have the same name. So, I'm going to work on a PR that shows an error if you try to submit duplicate names in Hotseat mode.

**Comment by tobymao** [comment]
you can do store(:flash_opts, 'Cannot have duplicate player names') to show the error
