### ISSUE TITLE
[1870] Out of turn company closure doesn't work correctly

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7103]
**What's your Game ID?**

https://18xx.games/game/72300
https://18xx.games/game/72300?action=971

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Company SP reached 0 value out of turn do to shares being sold. If the owner didn't price protect, and the shares hit 0, the company still operated and was required to buy a train, even though it had closed.
If owner price protected, when it was it's turn to operate and it layed tracked, but then the game locked up.

![image](https://user-images.githubusercontent.com/20323908/153698173-eb550369-5363-4b6c-87be-15a763372e37.png)

only solution was to price protect and skip laying track.

**Comment by JoeB989** [comment]
In fact SP does close and go away, is not listed on Entities or Market, but is still in the operating order built at start of OR.

**Comment by xmunroe** [comment]
It's probably not clear from the game log. we had to go back and forth 3 times with different conditions until we could get it to correctly close without forcing the owner to purchase a train. it should have closed and not forced a train purchase without price protection.
