### ISSUE TITLE
Display a message on the Info page when there aren't any trains in the bank pool

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7105]
Display a message on the Info page when there aren't any trains in the bank pool.  E.g.

**Trains in Bank Pool**
None

Or 

**No Trains in Bank Pool**

The reason for this request is that it can be important in 18NY to know whether there are any trains in the bank pool, as this affects which trains can be bought when a company takes loans.    If there aren't any trains in the bank pool, the UI does not state this anywhere.  You have to infer the absence of this trains by knowing where information would be displayed if any trains were present.  If you don't know (or you've forgotten) where to look, it is non-obvious that the bank pool is empty.

In our recent game, we looked through several tabs to see if this information was there.  We thought the bank pool might be listed on the Entities tab, or on the Info tab, and couldn't find it.  We eventually looked back through the history to find where the information would have been, if there had been any trains in the pool.  This was a clunky way of finding the information we wanted.  It would have been much simpler if the message above had been displayed on the Info tab.  The Info tab is the right place to have the info, it just needs to show the bank pool even if it is empty.

We noticed this for 18NY.  Arguably, it could be useful for other games too, such as 1830-style games.  I guess it should be configured on a game-by-game basis?  E.g. some games never have trains in the bank pool, so this information would be redundant and possibly misleading for those titles.

**Comment by crericha** [comment]
Change the bank's entity display to display that it has no trains.
