### ISSUE TITLE
Require All Sellable Shares to be sold in order to press the Declare Bankruptcy button

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#711]
Right now, any player can declare bankruptcy anytime they are forced to buy a train. This is understandably a needed relief valve for cases where it is actually bankruptcy, but the button can be pressed ending the game even if it would not be legal for a player to do so. This can cause games to end prematurely, especially for new players who may not realize how much money they can actually raise by selling shares (despite the UI text telling them so) If players want to call the game after a near bankruptcy, there is still the end game button in tools, that should be used to end a game early. If a game ends due to bankruptcy, it really should only happen if the player is actually bankrupt.

A simple fix would be to just require that all shares that can be sold are sold, and there still not be enough money to buy the cheapest train, before the Declare Bankruptcy button can be pressed. This would avoid any confusion, as the button being makes it appear like bankruptcy is a choice not an outcome.

**Comment by tobymao** [comment]
dup
