### ISSUE TITLE
[1849] Blocking step Bankruptcy Choice cannot process action

### ISSUE THREAD

**Issue by zaxor0** [tobymao/18xx#7124]
https://18xx.games/game/64812?action=312

Blocking step Bankruptcy Choice cannot process action 313
Broken action: { "type": "lay_tile", "entity": "ATA", "entity_type": "corporation", "id": 313, "created_at": 1641668705, "hex": "J12", "tile": "23-0", "rotation": 5 }

**Comment by dfannius** [comment]
This looks like a pretty standard pinned game, although I'm not sure what code change caused it.

**Comment by scottredracecar** [comment]
There is a bug that was fixed recently and appears to have pinned your game. The game proceeds in hotseat so presumably this is no longer a problem for new games, but this is unrecoverable due to being pinned.

**Comment by dfannius** [comment]
It looks like the bug was #3899. SIdewynnder used to be just declared bankrupt, but now that #3899 is fixed, the fact that they own a private means that they have the choice to take an L. 500 loan, so the original sequence of actions is no longer valid.

**Comment by zaxor0** [comment]
thanks
