### ISSUE TITLE
[18Rhl] #2 tile missing?

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#7130]
![BCECA3BE-CCF8-4930-AD5F-75D0A3CC8087](https://user-images.githubusercontent.com/73144084/153754802-71e9a01b-9c02-4e5b-b6ed-3b381eecf939.png)

I can’t find a tile manifest online but there is only one #2 tile compared to the other double dit cities each having two, is this correct?

**Comment by thepackrat** [comment]
This is correct according to the manifest in my version 3.0 rules.
