### ISSUE TITLE
[1822] Minor offered 2 train to buy with insufficient money

### ISSUE THREAD

**Issue by thepackrat** [tobymao/18xx#7131]
With an early running minor with $60 in case, in standard 1822, it is offered a 2 train  and a exchange which it cannot afford. The game throws a red-banner error if you try to buy them, but them being offered is a confusing UI. 

<img width="359" alt="1822-wrong-trains-offered" src="https://user-images.githubusercontent.com/12235419/153754897-e3c8c2d0-a979-47c4-9a8a-bdf84076114f.png">

**Comment by benjaminxscott** [comment]
afaik this is due to the 2 being a variant of the L, so not sure how to fix this

**Comment by scottredracecar** [comment]
There are lots of situations where unbuyable trains are shown. For example, this case in 1846, just as a very easy example to find to demonstrate.
https://18xx.games/game/73110?action=369
