### ISSUE TITLE
In 18CZ auto pass in Share Dealing Round jumps over reduction down to certificate limit 

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#7142]
Game: 
https://18xx.games/game/70487
Action ID
https://18xx.games/game/70487?action=549

In game 70487 the player Zezzo sells shares and buys a UG. 
The Player I33twash0r automatically passes with 13 of allowed 12 certificates.

The correction of the certificate limit should disable auto pass in SDR.

We cannot correct this in master mode. If there is a possibility, please tell us.

**Comment by l33twash0r** [comment]
When I rollbacked to that moment it gave me option to pass normally. Should it hide the pass and autopass until the game state is legal again?

**Comment by Zwergenpunk** [comment]
Probably yes. I never saw a 18CZ game where a president swapped
