### ISSUE TITLE
GameID 1784 (1889) Cannot Buy Train

### ISSUE THREAD

**Issue by Darkmot** [tobymao/18xx#715]
As title mentioned, it is UR turn, after running and withold revenue, the Train Purchase step is skipped, suddenly straight to TR turn. 

Currently we leave the game on UR turn, during payout/withold step. We also tried payout, with the same results.

Could you please check what's wrong?

Thank you

**Comment by tobymao** [comment]
you are train tight and cannot buy trains

**Comment by Darkmot** [comment]
Sorry, didn't realize that, thank you for enlightening
