### ISSUE TITLE
Option to always send turn notifications 

### ISSUE THREAD

**Issue by jasonab** [tobymao/18xx#7150]
I  understand that many players play live on the site, and do not want to be emailed pointlessly when they are on the site. Personally, though, I've had many instances where I checked the site to see if a game had moved, noted that it was not my turn, then did not get emailed when it became my turn because it was too soon after I left the site.

As such, I would like to suggest an option to _always_ email a player when it is their turn, so this overlap is less of a problem.

Additionally, if possible, it would be nice to filter out any game that you are "actively" accessing, but I don't know how easy that would be.

**Comment by tobymao** [comment]
If you want to always be pinged, use discord or slack notifications.

Emails are extremely expensive. This "filter out games that are active" logic is already implemented and why you aren't receiving emails. But it's not trivial to implement perfectly.
