### ISSUE TITLE
[18Rhl] Private No. 4 allows placement of free station token

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7157]
**What's your Game ID?**

https://18xx.games/game/72882?action=96

Player uses private no. 4 to place tile and then a token and isn't required to pay for the token, even though the text for the private says token should be paid for.
Perhaps there is confusion with Private no. 2 which does allow a free token?

**Comment by perwestling** [comment]
It looks like I had switched token cost between private 2 and private 4. I have now fixed this which will correct private 2 as well.
