### ISSUE TITLE
[18EU] Some Minor Companies can't do anything in the Operations round.

### ISSUE THREAD

**Issue by hachi-18xx** [tobymao/18xx#7160]
**What's your Game ID?**
https://18xx.games/game/72624

**How to Reproduce the Bug?**
- No.1 Minor Company can't do anything in the Operations round.
- It looks like there is no home token.
- Similarly, 6, 9 and 11 do not have tokens on the board.
- 1, 6, 9 and 11 were  purchased at a discount on the Initial sale round.

**Comment by ryandriskel** [comment]
Fix has been submitted. Your game will work again once it is deployed.

**Comment by ryandriskel** [comment]
I checked your game and you should be good to resume play!
