### ISSUE TITLE
[21Moon] Missing private company max sale price on charters

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#7167]
The current rules have the values on pages six and seven, but except for the very first private, who has a max sale of 1 credit, the rest are 1.5x the value.

**Comment by roseundy** [comment]
Is there a bug here, or an enhancement request?

**Comment by KillerOrca** [comment]
I would say bug though it prevents no game play stops the rules indicate that these values are included on the cards, page six.

**Comment by roseundy** [comment]
So you are asking for the max price to be on the company cards?

**Comment by KillerOrca** [comment]
Yes, on the private companies it will be 1.5x the value, except the first one which is one credit.
