### ISSUE TITLE
[1852] - Attempted purchase of first 7T gives "undefined method 'tile' for nil" error

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#7172]
https://gist.github.com/OedipussyRex/d574cf6bd24f2a2b74b8a9904fa6f5a1

The game doesn't recognize the silver tiles would be my guess.

**Comment by scottredracecar** [comment]
Thanks again. It is due to not being able to remove markers that don't
exist. Another easy fix.
