### ISSUE TITLE
[18Rhl] Bridge stub between tiles C8-B9 needs to be made more clear

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7181]
The stub of bridge track in between hexes C8-B9 could be made more clear. it's tough to know that you're allowed to cross the river legally at this point, and then the track line disappears under the blue line when track is laid.
![image](https://user-images.githubusercontent.com/20323908/154166154-66480ee5-97da-4ba6-988f-4415a4277132.png)
![image](https://user-images.githubusercontent.com/20323908/154166288-2f636f4d-ff65-4c27-bd4b-651744548f3d.png)

**Comment by perwestling** [comment]
This is explained on the wiki:
![image](https://user-images.githubusercontent.com/2631151/154176014-e3d477be-0726-4691-8574-e55c5082266b.png)

Do you think a picture or two explaining this might be a good improvement that would help? 
Here is a link to the wiki page: 
https://github.com/tobymao/18xx/wiki/18Rhl%3A-Rhineland

It is possible to edit if you have a github login.

The stub is a general feature of 18xx.games. I do not know if it is possible to make it appear as a bridge on top of the blue. It is possibly quite a lot of work for the benefit of making it clearer. So updating the wiki page might be a good enough way.

**Comment by goldencow2** [comment]
I don't see a reason to include the blue border at all on that edge. The original map only has it because the river is drawn in full artistic detail.

**Comment by perwestling** [comment]
Updated map looks like this:
![image](https://user-images.githubusercontent.com/2631151/154805976-5fe47259-03b1-4c11-9080-a1ed2660e2b0.png)

**Comment by perwestling** [comment]
Merged - so it will be available soon.

**Comment by perwestling** [comment]
Should be available now.
