### ISSUE TITLE
[18Rhl]  Unclear from Info tab 8Ts can be bought once the first 6T is purchased.

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7182]
![image](https://user-images.githubusercontent.com/20323908/154166780-5475c92a-643b-46a9-969e-e91422f0e9bd.png)
It doesn't show anywhere that 8Ts are available for purchase.

**Comment by benjaminxscott** [comment]
You have to look at the "Available" column, which says that 8 is available on the 6

It's the same with other games as well

**Comment by perwestling** [comment]
This is a general thing. If you have a suggested improvement for how to display this, you can open an Enhancement issue.

I have currently no plan to change anything here (and besides I have promised *never* to do any GUI changes ;-) )
