### ISSUE TITLE
[1846 2P] corp is able to token past a "dropped" token, when it has no connectivity

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#7183]
The Erie is able to upgrade Toledo and then token Detroit , even though it has no route to Detroit due to the "dropped" GT token in Toledo.

https://gist.github.com/benjaminxscott/9a0b42eff80b579f4896f1e46ceef63d

edit: Erie is also able to token South Bend instead of Detroit under these same conditions

Note that these actions must be taken in strict sequence, refreshing the page or attempting to token elsewhere (such as South Bend) will result in correct behavior of "cannot token" when Detroit token is attempted.

Presumably the connectivity graph is not being updated after the token is dropped? And then any other action including refresh will update the graph?

Resulting state:
![Screenshot 2022-02-15 5 04 15 PM](https://user-images.githubusercontent.com/1711810/154176657-bd5c96f5-7541-4887-b105-de783913e836.png)

Before:
![Screenshot 2022-02-15 5 03 32 PM](https://user-images.githubusercontent.com/1711810/154176679-d420b13d-d977-4970-b411-9f53bd4a5285.png)

After:
![Screenshot 2022-02-15 5 04 01 PM](https://user-images.githubusercontent.com/1711810/154176694-bd93c415-edfd-4f29-863d-7991efbf0ed5.png)

**Comment by thepackrat** [comment]
That's a really interesting bug. I'll take a look.
