### ISSUE TITLE
1852 - Train that is buyable with the train discount private is not shown

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#7192]
https://gist.github.com/scottredracecar/8dba73378097fdad43ed0260fead79d0

<img width="370" alt="image" src="https://user-images.githubusercontent.com/29106780/154286471-3a429620-3293-45f0-b7bd-7dcd106e22e6.png">

ATSF should be able to buy the $540 6-train with the $60 discount, but since the train is not buyable without the discount, it is not offered as an option.

I don't know how to solve this.

**Comment by roseundy** [comment]
1846 overrides buyable_train_variants, but doesn't take abilities into account
