### ISSUE TITLE
Game ID 83: Can't upgrade Ohzu after corporation purchases Ehime Railway 

### ISSUE THREAD

**Issue by jaeisma08** [tobymao/18xx#72]
UR bought Ehime Railway from EisVrouw81 (president of UR) as the first action on their turn. Immediately went to the companies tab, clicked on Ehime Railway, and went back to the Game tab. The Ohzu tile is highlighted and all of the other tiles are muted, which seems to indicate that the Ehime Railway has been activated. However, when UR/EisVrouw81 clicks on the Ohzu tile, the upgrade tile options do not pop up. The user's browser is Chrome.

**Comment by tobymao** [comment]
fixed
