### ISSUE TITLE
[1852] - Train Discount doesn't with FTP and insufficient funds in treasury

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#7208]
https://gist.github.com/OedipussyRex/caa466b281b289be17d620e3995305b8

MoPac is $28 short of a 5T. Clicking on Train Discount does not make the 5T available.

**Comment by OedipussyRex** [comment]
Likely the same issue as this: https://github.com/tobymao/18xx/issues/7192

Didn't see it when posting. Leaving this open because there is a slight difference between the two where no trains are affordable without the private here, and a train can be bought without the private in the other issue.

**Comment by scottredracecar** [comment]
This works fine now, was fixed with #7203
