### ISSUE TITLE
[1861] Info tab links to 1867

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7212]
The "More info" link on the Info tab for 1861 links to the wiki entry for 1867 instead.

Also, please change "ipoed" to "started" in two locations (under "Events") in the Info tab for both games.  "ipo" is not a verb in any ruleset and "IPO" isn't used as a term at all in 1861/1867.

**Comment by benjaminxscott** [comment]
The wiki can be modified directly as you wish

**Comment by scottredracecar** [comment]
It think Dave is talking about the info tab in the game, not the wiki (separate issue than the wiki link).

**Comment by benjaminxscott** [comment]
ok made that change
