### ISSUE TITLE
Cachebusting for CSS and JS

### ISSUE THREAD

**Issue by dennislaumen** [tobymao/18xx#722]
@jenf  has been having some issues with regards to caching on the home page. Adding [cachebusting](https://www.keycdn.com/support/what-is-cache-busting) to our asset pipeline should fix these issues.

I'm not familiar enough with our current setup to know whether that's an issue configuration change to our asset pipeline or setting something more complicated up. Not a high priority right now as far as I'm concerned but this could also lower support overhead in the future.

**Comment by tobymao** [comment]
this is not the issue as discussed in slack it is due to new data format and hot seat games
