### ISSUE TITLE
18EU Unable to lay track for minor 15

### ISSUE THREAD

**Issue by MikeBakken** [tobymao/18xx#7224]
**What's your Game ID?**

https://18xx.games/game/73165

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

Attempting to lay track for minor 15.  Unable to lay track on home station.

**Comment by ryandriskel** [comment]
The game linked is 1817

**Comment by ryandriskel** [comment]
Issue is fixed on next deploy.
