### ISSUE TITLE
[18EU] company asked to place home token after a share from the market is bought

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#7234]
Can't really describe it: In this game: https://18xx.games/game/73766?action=547 when stepewe buys a share of AIRS from the market, AIRS can place a token anywhere.
AIRS had been floated very early on and had operated many times before. This did not happen for other RRs.

**Comment by ryandriskel** [comment]
I think this might be a side effect of / related to https://github.com/tobymao/18xx/issues/7235

Like the token selection is queud, maybe?
