### ISSUE TITLE
[1852:Mizzou] Train discount not working 

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#7238]
Game 73547

Trying to use the Train discount to buy a 4G and it says it is “not an available train”.

I can buy a 3G with the discount and a 4G without the discount, but not the 4G with the discount.

**Comment by scottredracecar** [comment]
It looks like it was this action, but it looks like it is working properly to me.
https://18xx.games/game/73547?action=150

Please reopen if necessary.
