### ISSUE TITLE
[18EU] Extra 3 train variant: last 3 trains cannot be ought

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#7245]
https://18xx.games/game/73879?action=319

Playing with the extra 3 train variant, the game errors out when minor 2 attempts to buy the last 3.

**Comment by ryandriskel** [comment]
What is the error you are receiving? I am not able to reproduce this problem so far.

<img width="768" alt="Screen Shot 2022-02-21 at 10 33 16 AM" src="https://user-images.githubusercontent.com/15675400/155003432-5cb08f05-eeb1-4a80-8482-96ec9c33b848.png">

**Comment by setrajonas** [comment]
This is the error message I get when I try to buy it.
![ss (2022-02-22 at 12 24 48)](https://user-images.githubusercontent.com/94334402/155185534-1cfff3d7-9e87-47f3-8ec2-7994883d7789.png)
