### ISSUE TITLE
[Harzbahn 1873] Inactive station in a village did not get active after it was serviced by a diesel railcar only

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#7247]
**What's your Game ID?**

https://18xx.games/game/73031

In OR 9.2 of the game one route of the GHE's diesel railcar was G12-H13. 
The GHE's station in G12 (a village) was invalid at that time, but should have become valid by being serviced by the diesel railcar despite the fact the GHE didn't run a standard train to G12.

**Comment by KlausKiermeier** [comment]
In OR 9.3 the GHE had an additional, new station at F11, a town.
The route F11-G12-H13 was again serviced by a diesel railcar only.
This time the station in G12 became active nevertheless.

**Comment by roseundy** [comment]
There is something fishy going on. The log shows G12-H13 being run, but the map doesn't show it during the dividend step.

**Comment by roseundy** [comment]
run_routes serialization for that diesel looks like:
```
        {
          "train": "D-14",
          "connections": [
            [
              "H13",
              "G12"
            ]
          ],
          "hexes": [
            "G12",
            "H13"
          ],
          "revenue": 10,
          "revenue_str": "G12-H13",
          "nodes": []
        }
```

**Comment by roseundy** [comment]
Root cause was due to the recent node serialization change. Diesel are handled specially, and may be unowned prior to process_run_routes
