### ISSUE TITLE
[18EU] Price dropped from 90 to 10 during 2nd round of passes.

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#7251]
Game 72786 - https://18xx.games/game/72786

The following sequence took place:

![image](https://user-images.githubusercontent.com/88008968/154861450-8ae52512-87c2-43a9-8561-f17f9adec757.png)

I could not get the actual text to copy/paste, so basically the image works.

To sum it up, Line 3 was offered for bid.  All 5 player declined and the price dropped from 100 to 90.  The first 4 players declined again, and the next thing that happened was the fifth player was able to buy the company for 10, not 90.

**Comment by edfactor29** [comment]
I think after the first round of passes it will allow you to edit the bid and you can put in 10 if you wish.

**Comment by ryandriskel** [comment]
Having written the code, I have no idea how this could happen :D

**Comment by ryandriskel** [comment]
Yeah, I think edf got it right. Should be an easy fix. I would undo the purchase for 10 action though, or the game risks breaking once the new code is in place.

**Comment by ryandriskel** [comment]
Fix is in the next deploy
