### ISSUE TITLE
Auto router gives suboptinal result on easy combo

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7258]
https://18xx.games/game/69079?action=949

The auto router finds this for 230
<img width="441" alt="Screen Shot 2022-02-21 at 06 55 40" src="https://user-images.githubusercontent.com/8732435/154979797-4f5df874-1471-46e8-8a2d-1f6df8cc7dee.png">
<img width="355" alt="Screen Shot 2022-02-21 at 06 55 33" src="https://user-images.githubusercontent.com/8732435/154979805-3e4879f1-3be2-4b94-b163-208a05295501.png">

It's trivial to find this for 260
<img width="415" alt="Screen Shot 2022-02-21 at 06 56 25" src="https://user-images.githubusercontent.com/8732435/154979887-3336be8a-2aee-408a-9991-4f3d56ea4888.png">
<img width="376" alt="Screen Shot 2022-02-21 at 06 56 16" src="https://user-images.githubusercontent.com/8732435/154979893-37f6b773-5203-4211-9c70-158b62cef11a.png">

My settings are high enough that it shouldn't have timed out.
<img width="858" alt="Screen Shot 2022-02-21 at 06 57 30" src="https://user-images.githubusercontent.com/8732435/154979974-69da0e2a-dfc0-4aad-a8d5-d0cf4a7c9f52.png">

**Comment by ChrisTheCat** [comment]
Another easy example - the 3 train should run to Leicester rather than Shrewsbury

https://18xx.games/game/69079?action=994

**Comment by JoeB989** [comment]
It misses the £50 for home-to-destination run

**Comment by JoeB989** [comment]
The destination_bonus logic wants to operate on a route collection, which the auto-router doesn't assemble until after route revenues have been calculated.  I think I can by with setting route.routes to a 1-route collection when testing standalone revenue.
