### ISSUE TITLE
[18EU] M1 unable to lay M2's home tile

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#7261]
https://18xx.games/game/74191?action=103

M1 and M2 owned by same player, M1 is unable to lay the M2's home tile for it.

Addendum: it seems like all of the reserved minor hexes can only be laid by the corresponding minor, eg M4 can't lay M7's reserved hex.

**Comment by ryandriskel** [comment]
Ah, the interpretation in https://github.com/tobymao/18xx/issues/7047 was not quite accurate then.

Here is the full rule:

_The hexes highlighted in grey that are adjacent to Minor Companies #2, #3, #7, and #10, may only have a tile placed there by either the owner of the adjacent Minor Company, or, if by another Minor Company or Corporation, with the consent of the Minor Company’s owner. For the purposes of this rule, both Florence and the tile immediately north of it are considered adjacent to Minor Company #10._

We'll need to add two things here:
A check if owner is the same **or** A consent check if not
