### ISSUE TITLE
18Ireland: Can propose merger between two companies despite them only being connected through narrow gauge.

### ISSUE THREAD

**Issue by goldencow2** [tobymao/18xx#7264]
https://18xx.games/game/73197?action=281

The EBSR can propose a merger with the CIR, despite the two not being connected by broad gauge.

Rules:
`The station marker of each of the merging companies must be connected by **broad gauge** track to the station marker of each of the other companies in the proposed merger. Intermediate stations blocked by other companies’ station markers are ignored for the purposes of this rule.`

![Untitled](https://user-images.githubusercontent.com/43799724/155025078-880b9ade-8029-4c76-b1c2-18765ef7ba5b.png)

**Comment by dfannius** [comment]
When I play that game in hotseat, back up to gc2's turn, and propose a merge with EBSR, CIR is not presented as an option. Can you double-check that you are seeing the behavior you describe?

<img width="528" alt="image" src="https://user-images.githubusercontent.com/1295244/155027768-2682ce58-68be-4d5d-8a09-70d20d23c680.png">

**Comment by goldencow2** [comment]
No, I'm just being dumb.
