### ISSUE TITLE
[18EU] Game not progressing anymore after bankrupcy

### ISSUE THREAD

**Issue by bearerer** [tobymao/18xx#7266]
* Game ID: 73117
* Game JSON: https://gist.github.com/bearerer/de2567b7c5b4e3bce399024790257293
* Link: https://18xx.games/game/73117

Player _stepewe_ was president of companies _RBSR_ and _AIRS_. They went bankrupt during OR 4.2 during _RBSR_'s turn. The game does not allow to transition to _AIRS_'s turn later (still during OR 4.2). Error message show in the red banner: `undefined method 'name' for nil`.

* _AIRS_ is closed, but still in the queue of companies to operate.
* Further more: if we go back and declare bankruptcy during _AIRS_ turn we can progress to the next SR. However restarting the now closed and newly available companies doesn't work either.

![Screenshot from 2022-02-21 22-50-22](https://user-images.githubusercontent.com/3775018/155030285-a37a6acb-3365-400b-ae5a-d36b736d7ac6.png)

**Comment by bearerer** [comment]
Oops. Didn't pay attention to the flags. Thanks.

**Comment by ryandriskel** [comment]
I dont think you have permission to set the flags - thats the devs job.

Fix is incoming and your game should be able to continue on next deploy.

**Comment by ryandriskel** [comment]
Deployed. Please verify!

**Comment by bearerer** [comment]
Seems to work. I really didn't expect we could continue the game 🙂 thanks
