### ISSUE TITLE
18MO - Show teleport ability on the map

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#7269]
Currently, the teleport abilities are not shown on the map. They are shown on the corporation's charter.

Since there is no reservation, we decided not to make them look like 1846 reservations.
<img width="133" alt="image" src="https://user-images.githubusercontent.com/29106780/155054198-75c631f4-8ed3-4e72-bb93-e3ad5414ab76.png">

Also, since the "punch through" symbol is used for the 2p 1846 "token drops on green tile," we thought that may be confusing as well. Also these symbols are tiny.
<img width="126" alt="image" src="https://user-images.githubusercontent.com/29106780/155054353-8ecc8283-2110-46a3-9f55-be1862c7f7e5.png">

Another suggestion that may work well and does not conflict with existing methods for displaying things in 1846 is to use the "reservation without a slot" text, like ERIE in 1830. (for now, this is the recommendation)
<img width="115" alt="image" src="https://user-images.githubusercontent.com/29106780/155054485-728c0c5f-8668-407d-84a0-03a7635a0ca8.png">

However, even this suggestion may be a little misleading since there is no reservations in this game if people are familiar with that symbology from other games (it appears this is generally not the case though).

If this is implemented, this text could be removed when the ability has been used and/or the tile has been upgraded to its maximum number of slots and those slots are occupied. StL when the "south SSW ability slot" is occupied, 3 tokens on a Z, and 2 tokens for else.

**Comment by roseundy** [comment]
Adding "reservation" labels to the St Louis tile overcrowds it.  Instead, I'm going to modify the location name to include the corporation that has that hex as a teleport destination:
![MO_teleport_dests](https://user-images.githubusercontent.com/8494213/155589234-75e8c536-e4e5-4d23-8a84-66ca0f89196a.png)

**Comment by scottredracecar** [comment]
Good enough until the tile rendering code works better (someday?). Thanks, Steve.
