### ISSUE TITLE
[1846] Private Draft doesn't show a player the companies they've drafted

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#727]
During the private draft (in a hotseat game), nothing shows the current player how much money they have already allocated for the privates they've already chosen, or what privates they've already chosen. I realize that's hidden information until the end of the draft, but a player should be able to see that information when they click "show".

**Comment by Qualm64** [comment]
Actually it's readable in the game code on the tools page.  You can see what you've drafted and unfortunately you can see what everyone else has drafted.

**Comment by wcraigtrader** [comment]
I'm pretty sure that if the player's selections were visible to the player in the UI, they wouldn't go hunting in the game data.

**Comment by scottredracecar** [comment]
I think it would be reasonable to have another button like "Show" called "Already Drafted" that toggles to reveal what the player has already drafted.

**Comment by wcraigtrader** [comment]
Why **wouldn't** you want a player to see what they've already drafted? 

After all, even for a hot seat game there shouldn't be any other players looking at the page, since what you have to choose from next is also private. Given that all of that data is equally private, why not show it and keep moving? (You don't have to show the full company card -- just the company name and the amount of money you've committed -- including Independent RR debt.)

**Comment by scottredracecar** [comment]
I think if you automatically show the drafted items, it will show for
everyone.

**Comment by Qualm64** [comment]
The 1846 draft can be very strategic, and there's good design reasons the choices are secret-ish.  Ideally you'd want to find a programmatic way to only show your own prior selections and not allow opponents to sniff them out of the json code.  I have no idea how hard that is to do though.

**Comment by jenf** [comment]
Fixed.
