### ISSUE TITLE
[18EU] Allow minor to lay blocked tile with consent

### ISSUE THREAD

**Issue by ryandriskel** [tobymao/18xx#7273]
May only have a tile placed there by either the owner of the adjacent Minor Company, or, **if by another Minor Company or Corporation, with the consent of the Minor Company’s owner.** For the purposes of this rule, both Florence and the tile immediately north of it are considered adjacent to Minor Company.

The first half of the rule is implemented. The second half is rare and needs implementation.

**Comment by andrewzwicky** [comment]
fixed in 670a7377408a6e72e59d9ddafa7039c021239c2a
