### ISSUE TITLE
[18NY] v2 update is paying a $30 bonus per token hit for 2H trains as well as diesel.

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#7275]
The v2 update is supposed to give a $30 bonus to each token hit by a diesel, but currently it appears to be giving the bonus to all trains hitting their company's token.

![Capture](https://user-images.githubusercontent.com/26125362/155232507-3c5bf32c-c685-47e6-bce9-657040be3e28.JPG)
![capture2](https://user-images.githubusercontent.com/26125362/155232509-a16f2c8c-b847-4884-bf4e-fc226ab9e53c.jpg)

we tested right up to the D&H running two trains, and it got 2x$30 bonus added to its run.

**Comment by philcampeau** [comment]
found the issue in line 779 of the game.rb file:

`          if second_edition? && (route.train.name == 'D' || route.train.name == '2H')`

**Comment by philcampeau** [comment]
So not all trains, but 2H and Diesel, instead of only diesel.

**Comment by crericha** [comment]
Oops that was test code.

**Comment by crericha** [comment]
Fixed by #7276
