### ISSUE TITLE
[21Moon] Error when OLS is on OO tile

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#7277]
https://18xx.games/game/74348

in the game we're playing, when attempting to lay a OO tile in hex E5, I get a massive full screen error. Reproduced in master mode by both other players:

![Capture](https://user-images.githubusercontent.com/26125362/155238727-5412e82d-5e30-4442-8461-8b6b82c70174.JPG)

**Comment by roseundy** [comment]
Wow, for some reason it's dumping the log on an error.

**Comment by roseundy** [comment]
OK, aside from the mind-numbing error message, this is due to missing code to handle the OLS token on a OO tile.
