### ISSUE TITLE
My Hotseat Next will not advance past =2 though I have 35 games

### ISSUE THREAD

**Issue by dmitton42** [tobymao/18xx#7280]
On the main page, if I press the Hotseat Games  "Next" button, I get =1, =2, and then it stops advancing. (Nothing changes)
If I put in https://18xx.games/?hotseat=3  I see 11 more games.   So I have 47 Hotseat games and can only see 36.

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see Version 98.0.4758.102 (Official Build) (64-bit)
- Platform Windows 10 Desktop

**Comment by dmitton42** [comment]
Feels like a mod or round off problem.  I currently have 49 hotseat games. Now it will advance to =3 but not =4.

**Comment by JoeB989** [comment]
I ran into something that may be related.  Try applying the change from PR #7353 and see if it helps

**Comment by JoeB989** [comment]
Also I've seen DB failures with too many hotseat games.  Try deleting the uneeded ones.

**Comment by dmitton42** [comment]
Right, I found the limit a few weeks ago.  The clone game button becomes unresponsive.
 Now I prune them down every so often.  That's why I'm paging through them.
I wish they were sorted by last access time.

**Comment by dmitton42** [comment]
Yes, this fixed the issue.  I had a old hotseat game, which has "become" unrenderable.  (software rot in action)
Whenever I advanced to that page, it had failed.
I deleted the offending game.
