### ISSUE TITLE
21Moon - Error on progressing game state 

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#7285]
https://18xx.games/game/73323

When I try upgrading G7 city I get an error:
![image](https://user-images.githubusercontent.com/11754021/155279053-a6f8ba58-875c-4868-acd5-388e5d1cac50.png)

**Comment by l33twash0r** [comment]
Seems like it happens on every tile upgrade or tile lay

**Comment by edfactor29** [comment]
https://18xx.games/game/73908
Same problem.  Happened during stock round. I can't even leave a message in game chat.

**Comment by pltnc** [comment]
same problem with https://18xx.games/game/73421
please delete thanks.

**Comment by mblandfo** [comment]
Same problem here: https://18xx.games/game/73907

**Comment by l33twash0r** [comment]
> Stand by. I can't reproduce in hotseat, so it will take a bit to debug.

AndyPy had similar problem with 18GB. Something about Javascript on frontend versus ruby on backend.
