### ISSUE TITLE
Someone broke this 18NY game

### ISSUE THREAD

**Issue by Trigo4** [tobymao/18xx#7295]
https://18xx.games/game/73743?action=292

Apparently one player tried to re-write history by going back several moves to better his position. Instead the game broke.

**Comment by philcampeau** [comment]
There was a problem with 2H trains paying an additional $30 when hitting the home station. This was corrected with an update earlier, but likely broke this game as a result.

**Comment by Trigo4** [comment]
Well, I can't even end the game in Master mode.Can you delete this game?
Thanks.
Ken Soo 

    On Wednesday, February 23, 2022, 07:50:59 PM CST, philcampeau ***@***.***> wrote:  
 
 


There was a problem with 2H trains paying an additional $30 when hitting the home station. This was corrected with an update earlier, but likely broke this game as a result.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by crericha** [comment]
I archived the game. All set.
