### ISSUE TITLE
[18Ireland] - Game allows autorouting to use narrow gauge track

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#7297]
https://18xx.games/game/72499

This game is letting the EBSR run a train route that uses narrow gauge track, for the actual train run.  See the 1H route for the EBSR, screenshot attached.

It appears that this may be a more general problem with the auto-router.  I have another 18Ireland game (https://18xx.games/game/72499)  where the auto-router will select narrow gauge track, but the human cannot select that same track manually.

![EBSR_narrow](https://user-images.githubusercontent.com/96210310/155418023-b3dd9dcf-d595-4b24-b20b-44acb2f7f458.png)

**Comment by dfannius** [comment]
I can't create this route by myself in hotseat, and it sounds like it was chosen by the autorouter, so I think this is an autorouting issue. Please tell us if you think it is possible to create this route manually.

**Comment by ddaybell** [comment]
Responding to dfannius, I believe this is an autorouting issue, as I noted in the (edited) second paragraph of my original post.

**Comment by JoeB989** [comment]
If you're not seeing a route error from the auto-routed routes, then as far as it knows this is a valid route.  AR uses route.revenue on individual routes and Game::check_other on a route collection.  If either of those Raises then AR won't use the route or combo.

Also, does this game match the screenshot?  What point should I undo to to see the problem?

**Comment by scottredracecar** [comment]
To reproduce, you can do auto on this action.
https://18xx.games/game/72499?action=426

**Comment by dfannius** [comment]
I guess that the UI is the only thing preventing this sort of route from being created.

**Comment by JoeB989** [comment]
Ok I see it.  Clearly the restrictions are enforced when manually building a route but not when checking route.revenue.  Suggestions:
1. Move 18Ireland track validation into one of the route.revenue checks, so that both manual and auto routing can use it.
2. Optionally, 18Ireland should override path.walk as well, to not walk trains through the wrong track types.  (Mainly important to reduce path timeout on large dense maps)
