### ISSUE TITLE
18USA - Iron & Rural Junction private descriptions are not clear

### ISSUE THREAD

**Issue by Antivamp** [tobymao/18xx#7304]
Coal marked track can be upgraded unlike 1817. Only iron cannot. Also, Iron markers cost an upgrade action to upgrade. May not upgrade another track or city with the same action.

**Comment by Antivamp** [comment]
Another issue is that rural junctions may not be placed next to each other.

**Comment by crericha** [comment]
All of these scenarios were tested and implemented. If they aren't working for you, please submit a gist or game link at the action where it failed.

**Comment by crericha** [comment]
I confirmed the first two and fixed them.

**Comment by Antivamp** [comment]
Its not that they failed. The wording on the privates is wrong. Sorry I did not state that.
