### ISSUE TITLE
18USA - 1817 trains

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#7319]
ID: 74614

https://18xx.games/game/74614

the optional 1817 trains, should only use the 1817 export mechanism. There should still be two 3+ trains and a 4+ (replacing regular trains of that size) and pullmans should be available.

**Comment by crericha** [comment]
I agree Pullman's should be available, but can you point to me where you see something about adding 3+ and 4+ trains? Here is what I see in the 1.4 rules.

> 9.1. Use 1817 Train Roster
18USA can be played using the same trains and exporting
rules as are used in 1817.

**Comment by edfactor29** [comment]
I wasn't aware Shawn had worded it that way, we always use the USA trains just with the 17 exporting. That sounds right by the rule you quoted.

**Comment by crericha** [comment]
The 1817 train variant now has Pullmans.
