### ISSUE TITLE
Move Rules and More Info links to top of Info tab

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7323]
Please move the "Rules" and "More Info" links from the bottom of the Info tab to the top. I suggest this layout, with a single line with two links as the first line of the Info tab:

[Rules] | [Info (wiki)]

Trains
blah blah blah

**Comment by scottredracecar** [comment]
I would also make a plug for a link to the publisher page being shown on that line with the label "Purchase".

**Comment by ChrisTheCat** [comment]
That makes sense, though I don't think all games are in print, so I'd
suggest linking the publisher name instead. Perhaps something like:

[Rules] | [Info (wiki)] | [*publisher name*]

**Comment by scottredracecar** [comment]
For AAG's titles, I'd much prefer "Purchase" vs a general link with no call to action. If I am new to the hobby or the game, I might not really care that much about learning more about the publisher and may not feel much incentive to click the link if it just says the publisher name.

I'd expect most of the other small companies like me (those linked in the homepage yellow box) would wish for similar. This covers the large majority of the current titles. Lonny/Golden Spike Game/GTG/Marflow/etc.

Some other games are only available PnP so maybe the link label can be "Print and Play" with a link to 18xx-maker or a BGG page that explains how to PnP (or similar).

I'd think it is best left up to the rightsholder.

The outlier is perhaps a company like Lookout who may not have a specific outlet, but in that case I think they may wish to have a link to the general company webpage and the publisher may be more appropriate, but I would think it would be good if they could choose. https://lookout-spiele.de/en/games/1830.html

**Comment by ChrisTheCat** [comment]
Sure, that makes sense.You might need more than one link, as some games are
both available for purchase and available for print and play.
