### ISSUE TITLE
[18EU] - 3 Trains not available

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#7330]
https://18xx.games/game/72738

We just started the 1st operating round.  When it came time for my corporation (number 2) to buy trains, the game says that the available train is the 4 train.  The info tab has the arrow pointing to the 4 trains as being available, even though it says that 7/7 3 trains are unbought.

**Comment by ryandriskel** [comment]
This will be fixed in the next deploy. Your game will be able to continue at that point.
