### ISSUE TITLE
18CO: unable to move bids

### ISSUE THREAD

**Issue by tomhoward87** [tobymao/18xx#7334]
https://18xx.games/game/73575

In the initial auction I believe it should be possible to move bids between private companies; I am given the option to do so but when I click the button I am told that the minimum bid is the minimum bid to stay on the current, not the one I am trying to move to.

There is an example in the game linked above, but to simplify:

Company A: current high bid 80, I have no bids on it
Company B: current high bid 130, my bid is 120

I am given a button to move my 120 bid from B to A but when I click it I get an error saying "the minimum bid for company A is 135” which is incorrect, that is the minimum bid for B.

**Comment by ryandriskel** [comment]
To move a bid, you must increase that bid by $5. When you tried to move to a lower valued private, you left the value at $85, which is less than 120.
