### ISSUE TITLE
18USA Force discard Pullmans during M&A

### ISSUE THREAD

**Issue by Narvinyar** [tobymao/18xx#7338]
Please fill out the bug report title with the game name and description

Pullmans are force discarded with no way to bypass during M&A rounds. Nowhere in the rulebook does it say that Pullmans must be discarded during M&A. 

**What's your Game ID?**

https://18xx.games/game/74773

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

https://18xx.games/game/74773?action=1353

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

https://gist.github.com/Narvinyar/dbd3f8bb98161cf13844b65dc971631f

**Comment by crericha** [comment]
The fix breaks your game. If you want to save it, undo to before action 1070. Otherwise, it will be archived.

**Comment by Narvinyar** [comment]
That's fine; we've already finished the game. Thanks for the update!
