### ISSUE TITLE
[18USA] Fox River Private

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#7343]
Game 74593:

Private power was enacted without being selected. Token placement after the fact seems to have no effect?

Power makes sense; chronology of events makes no sense to me.

**Comment by crericha** [comment]
Please link the game and where in history it happened.

**Comment by crericha** [comment]
In that game, P2's active power, the +10 bridge token, has not yet been used (it still shows 1/1). The river discount is a passive ability and the corporation gets that benefit for the entire game.
