### ISSUE TITLE
18USA payouts

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#7346]
Game 74593.

GN has share price of $90 and is paying out $180. Half pay is a double jump and a full pay is a quadruple jump.

Both of those seem like double what they should be. Half pay is only paying $90+$27, so not enough for a double and $180 is not even enough for a triple jump, much less a quadruple.

**Comment by crericha** [comment]
This is correct behavior. Here is the pertinent section from the rules:

"the share value will move forward by 1, 2, 3, or 4 steps when a company pays out at
least 50%, 100%, 150%, or 200% of its current share price"
