### ISSUE TITLE
[21Moon] Terminal bonus is not being calculated in routes to W offboard

### ISSUE THREAD

**Issue by MichaelDyrud** [tobymao/18xx#7358]
**What's your Game ID?**

Example game is https://18xx.games/game/75037, in OR 2.2 both the IPI and the DSE ran routes going from the Terminal to one of the West offboard sites, the routes paid out $100 instead of including the $30 Transport bonus.

**How to Reproduce the Bug?**

This has occurred in two other games, but could not find specific routes in logs to reference so I created a new game specifically to highlight these routes.

**Which Browser / Platform?**
- Chrome 98.0.4758.102 as well as Safari on iOS, issue occurs accross multiple devices

**Comment by scottredracecar** [comment]
It is a rules bug. Thanks for bringing it up.

I changed the rules to “Eastern” which is how it should be coded. Note the orange outline matching the orange eastern offboards.

**Comment by scottredracecar** [comment]
By the way, if you are trying to demonstrate a bug, it is often easiest to make a hotseat game, play each position up to the point of the bug, and then post and submit a link to a gist. (although this way worked fine too)
