### ISSUE TITLE
Consider labeling private cards "Pass" instead of just a number

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#736]
In the online interface, it seems less important that "pass on buying a private" cards have a particular number, since it's not used for anything besides making sure you shuffle the correct number of them in for a given player count

This would diverge from official labeling, but may be a bit easier to parse for new players

**Comment by dfannius** [comment]
One thing we'd lose if we made them indistinguishable is being able to tell whether the pass card you got this draft turn is the same as the pass card you got in an earlier draft turn, which can give you some information about what other players are doing.

**Comment by tobymao** [comment]
Can be solved with Pass (1), Pass(2)

**Comment by benjaminxscott** [comment]
I like the 'Pass' description as above

**Comment by tobymao** [comment]
How about Pass on Buying Privates (N)
