### ISSUE TITLE
1846 2p Variant game is in a broken state for some reason I don't understand

### ISSUE THREAD

**Issue by Lex137** [tobymao/18xx#7361]
Error message told me to share this: https://18xx.games/game/72616?action=262

I just got done buying the last unowned private company, using its power, and doing my normal turn with two tile actions. I tried it with the order swapped (use bonus upgrade first, then normal tile lay and upgrade OR use normal tile lay and upgrade followed by bonus) and neither option worked. I'm not sure if the use of the private company is actually important to the bug or not.

**Comment by thepackrat** [comment]
I'm a little unclear what the bug is here. I see three lays in the log.

15:51] GT spends $20 and lays tile #8 with rotation 2 on E15
[15:51] GT spends $20 and lays tile #296 with rotation 3 on E17 (Cleveland)
[15:51] NYC places a token on E17 (Cleveland) as the city is green
[15:51] GT buys Lake Shore Line from Kuzma137 for $40
[15:52] GT (LSL) lays tile #619 with rotation 3 on D14 (Toledo)

GT lays,  GT lays second, (which triggers NYC dropping a deferred token), GT buys in LSL , then GT(LSL) lays bonus lays. Three lays? What did you expect to happen?

**Comment by michaeljb** [comment]
The bug is there's a `pass` action on the Run Routes step in there somehow, see https://18xx.games/game/72616

**Comment by michaeljb** [comment]
I'll see if I can take a look at the db later tonight, if that `pass` is the only broken action and there are no actions after it, we could delete it and the game should work again. Of course that doesn't help explain how that invalid `pass` got in there in the first place. The log does seem to show that this part did work:

> use normal tile lay and upgrade followed by bonus

**Comment by Lex137** [comment]
Yeah. To be clearer about the user experience (sorry, I thought the game
log would include the error presented on the UI) I tried many permutations
of valid actions and all produced the same result: when setting routes and
clicking "pay out" the game would provide an error about the update being
rejected by the server because of something (it only showed up briefly and
then vanished as the game refreshed to undo my run calculations). I vaguely
recall the error saying that it was missing a required tile/token step or
something? Regardless, it was impossible to proceed.

I tried every possible ordering of: buy LSL, use LSL's bonus tile upgrade,
take my two normal tile upgrades.
Followed by various attempts at setting train routes including clearing
trains and setting routes manually, using the auto button, clearing only
the 4-train and setting it manually, or simply not changing routes from
last round.

In all cases, when I clicked "pay out" the game gave me the same error and
immediately refreshed the page back to an earlier state.

Finally I tried simply clicking through the steps following "pay out" fast
enough to get further and that's when I got the "this game is unplayable"
error that linked me to the bug report process.

Let me know if you have more questions and thanks for putting together this
really cool app,
Lex

**Comment by michaeljb** [comment]
> In all cases, when I clicked "pay out" the game gave me the same error and
immediately refreshed the page back to an earlier state.
>
> Finally I tried simply clicking through the steps following "pay out" fast
enough to get further and that's when I got the "this game is unplayable"
error that linked me to the bug report process.

I've deleted that `pass` action and I think the "this game is unplayable" error is gone now. In the current game state, it does look like the two tile lays and LSL tile upgrade have been used.

Could you try again and let us know if you're still getting errors at the "pay out" step? If that's still broken I can do some more debugging tomorrow.

**Comment by Lex137** [comment]
Game state is still broken. Here is the error I get:

The server did not accept this action due to: Illegal action: Blocking step
Place a Token or Lay Track cannot process action 263... refreshing page

By the way, it would be helpful if that error didn't immediately reload the
page every time. I had to act very quickly to select and copy it before the
page reloaded to the prior state again.

Anyway, thanks for your continued effort on this.

**Comment by michaeljb** [comment]
Seems to be affecting this game as well

https://18xx.games/game/75410

**Comment by michaeljb** [comment]
@Lex137 https://18xx.games/game/72616 should be fixed now

@MotoGymkhana https://18xx.games/game/75410 should be fixed now

**Comment by Lex137** [comment]
Confirmed. Thanks!
