### ISSUE TITLE
[21Moon] UI Issues on intra-corporation transport purchase

### ISSUE THREAD

**Issue by mggarofalo** [tobymao/18xx#7364]
https://18xx.games/game/73261?action=370

At this point, LP can purchase a transport from MA (same director). The train list shows up correctly, with 2 3s and a 4 available. But the 3s are at different locations (one LB and one SP). There are two issues with the UI at this point.

1) I see no reference in the rules to each base needing to have transport if it has a valid route. The rules only say that a company with a valid route and no transport must purchase a transport. Yet the UI does not allow me to buy a second train to the LB despite not thereby exceeding the LB transport limit.

2) The UI doesn't allow me to specify which 3 transport I want to purchase from MA. I would have preferred to purchase the 3 at MA's SP, but the game auto-selects the LB 3 for me and does not allow me to alter this selection.

**Comment by roseundy** [comment]
1. The rules state that you can only buy 1 train per base. Prior to the point in the game you've referenced, LP has already bought a train for the LB, so it cannot buy a second. So I don't think there is a bug here.
2. This is definitely an issue with the UI. It will take some work to solve. You can partially work around it by shuffling a train before MA's next run, but this needs to be fixed.

**Comment by scottredracecar** [comment]
Yes, both are UI bugs.

**Comment by scottredracecar** [comment]
Yes, one buy per base. But you still have the buy with the other base and you can transter it before it runs so you can still run both out of the local base within the rules.

**Comment by mggarofalo** [comment]
@roseundy The current rules doc says "Multiple transports may be bought in a single turn, but each base can only own up to two transports. When a transport is purchased it must immediately be given to a base that has room for it." @scottredracecar is there a rule I can't Ctrl-F for in the google doc?

**Comment by scottredracecar** [comment]
The "one transport per base" rule seems to have not made it into that rules
draft. I added a comment.

You should be able to search the document. Seemingly Google Docs' find
function takes over in most browsers.

**Comment by roseundy** [comment]
In my defense for point 1: one set of the rules I was working from had that rule.

**Comment by roseundy** [comment]
OK, so one rules bug and one code bug.

**Comment by mggarofalo** [comment]
@scottredracecar I meant more like "is there a term besides 'transport' I should be using to look or is there a section it should be in besides the Purchase Transports section, haha. Sorry if that didn't come across.

**Comment by mggarofalo** [comment]
@roseundy no problem. I figured, since it's still in alpha and the rules are still in active development, that it was probably a version difference.
