### ISSUE TITLE
[18USA] Frozen array error 

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#7366]
Game 74593:

First 6 train just lowered train limit. One player was able to drop a train to get down to two; the other player can’t as it brings up a “frozen array error”.

**Comment by crericha** [comment]
@SmithInMN, looking at the game, it is forcing you to discard "+" trains. Those should not count against the train limit. If you want the game to avoid being archived, make sure to undo to before the first 3+ was discarded.

**Comment by SmithInMN** [comment]
I went back and undid to before any trains were discarded. B&O discarded a 3+, but Katy still can’t discard a 3+ without the same error.

**Comment by crericha** [comment]
The fix hasn't been deployed yet. Keep the game to just before the B&O discarded a 3+. Once the fix is deployed, you will know because the B&O and Katy will no longer need to discard anything. Toby usually deploys around 10PM PST or so.

**Comment by SmithInMN** [comment]
Perfect. Thanks!
