### ISSUE TITLE
18NY: Lay any special city in Buffalo

### ISSUE THREAD

**Issue by 18xxperson** [tobymao/18xx#7374]
https://18xx.games/game/74452

What steps cause the unexpected behavior?
Have the Buffalo tile be a green K city (tile #15) and the game phase be in Brown or later. 
When you click on Buffalo to upgrade it, every single special brown tile will show up as options. The normal brown city does show up as an option as well.

This was noticed on the Microsoft Edge browser

**Comment by thepackrat** [comment]
This is an edge case for the NY where plain tiles and symbol tiles coexist in the. same phase and an early return skipped checks. Fix incoming.
