### ISSUE TITLE
21Moon - Blocking step Run Routes cannot process action 81

### ISSUE THREAD

**Issue by MattHesby** [tobymao/18xx#7377]
https://18xx.games/game/73261?action=80

We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 81
Broken action: { "type": "pass", "entity": "SM", "entity_type": "corporation", "id": 81, "created_at": 1645059480 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/73261?action=80)

https://18xx.games/game/73261

**Comment by roseundy** [comment]
This game needs to be archived or pinned due to a bug fix that went live a few days ago.  I'm collecting these games in this bug: #7371
