### ISSUE TITLE
1846: Privates not actually removed in <5 player game

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#738]
Chat box reports which companies are removed. 
Majors removed correctly, but privates still in the draft/in the game.

**Comment by benjaminxscott** [comment]
I presume [this loc](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1846.rb#L120) is the culprit, with the caveat that i have no idea what these ruby constructs are doing

**Comment by tobymao** [comment]
i have this fixed locally
