### ISSUE TITLE
18NY unable to lay brown Brooklyn tile

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7380]
https://18xx.games/game/73937?action=923

When trying to upgrade Brooklyn, the UI says out of tile 448. It doesn't offer the Brooklyn tile X21.

![Screen Shot 2022-03-03 at 12 39 21](https://user-images.githubusercontent.com/8732435/156649260-127eeb6f-aa0c-4c7a-b440-e39f607c55f7.png)

![Screen Shot 2022-03-03 at 12 39 32](https://user-images.githubusercontent.com/8732435/156649277-99f1ccba-55fc-4c34-9953-ec27d42d8dc8.png)

**Comment by thepackrat** [comment]
There's a symbol missing on the Brooklyn tile which is actually what's responsible for this. Looking.

**Comment by thepackrat** [comment]
Aha. The second edition rules change the map to move the brooklyn special hex around (and don't put a label on it)

**Comment by thepackrat** [comment]
Working on a fix now.
