### ISSUE TITLE
18RHL: Incorrect handling of green Rhine Metropolis cities

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7384]
This route is illegal according to the rules:
![image](https://user-images.githubusercontent.com/2631151/156796465-6b1748da-bfe4-4f77-8222-9dfae7c29b5a.png)

A longer discussion, and clarification based on answer from designer, can be found in this forum thread:
https://boardgamegeek.com/thread/2553217/clarification-river-crossing-rules

These cities need to be shown in a better way so one can see which side of the river the token is located. 

Have not look into this closely but a potential solution could be to make this a 2+1 or 1+2 green hex, where location of token is set depending on which side were tokened before upgrade. Code need to handle when both sides are visited (count this as one stop with 30 revenue), and of course also the upgrade from yellow to green and green to brown.
By using a 2+1/1+2 hex it would make routing work as it should.
It is possible that the ferry icon should still be used. Having the track between cities being rendered in a special way might be a possible enhancement.

Note! There is a difference between these cities and the 2+1/1+2 hexes - tokened out in one of the cities, but not both, does not block passage. See forum post for more details.

**Comment by thepackrat** [comment]
If you can get the river to render over the top, this looks like a reasonable placeholder for the rendering. For sure the route code is going to be fiddly and this may become a no-autorouter title.  

city=revenue:40,slots:1,loc:1;city=revenue:40,slots:2,loc:4;path=a:0,b:_0;path=a:3,b:_1;path=a:4,b:_1;path=a:5,b:_1;path=a:_0,b:_1,track:narrow;label=D

<img width="90" alt="image" src="https://user-images.githubusercontent.com/12235419/156803268-f78ef584-8c7c-4663-8df1-7b610bca28c8.png">

**Comment by perwestling** [comment]
Problem has not been fixed.

**Comment by perwestling** [comment]
@thepackrat : I have tried to get the implementation to work, but it is a bit messy. So I think I will pause that attempt and go back to the original.
The implementation do need to be corrected, and I think clarifications can be added to the wiki.

My tests during this implementation seems to indicate that there are some other bugs here. E.g. RGE bonus for hexes with traject.

**Comment by perwestling** [comment]
A fix was implemented and around September 3rd delivered to master.
As only one problem has been reported, and was fixed a couple of weeks ago, I believe this works as it should.
