### ISSUE TITLE
Game Broken         https://18xx.games/game/75410?action=281

### ISSUE THREAD

**Issue by MotoGymkhana** [tobymao/18xx#7385]
We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 282
Broken action: { "type": "pass", "entity": "C&O", "entity_type": "corporation", "id": 282, "created_at": 1646371546 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/75410?action=281)

**Comment by michaeljb** [comment]
I believe this is a dup of #7361, which I am looking into today
