### ISSUE TITLE
[18USA] Fox River discount does not apply when used with Rural Junction

### ISSUE THREAD

**Issue by skoomfest** [tobymao/18xx#7389]
Game id: 74523

In my reading of the rules, I can't see anything which doesn't allow these two companies abilities to be used in tandem, so I believe this is a bug.  When I try to lay track in Omaha without Rural Junction it allows me to do so without paying, but using rural junction makes me pay the 10 terrain fee.   I was also charged earlier in the game (https://18xx.games/game/74523?action=173) for rural junctioning St Louis, but I did not notice at the time.

**Comment by crericha** [comment]
The bridge company discounts are a passive ability and should apply.
