### ISSUE TITLE
(1849) Unable to go bankrupt

### ISSUE THREAD

**Issue by ferdnandoc** [tobymao/18xx#7390]
**What's your Game ID?**

https://18xx.games/game/66425

https://18xx.games/game/66425?action=56

**How to Reproduce the Bug?**

It happened after the player chose to stay in the game during a SR.

**Which Browser / Platform?**

99.0.4844.51 (Official Build) (64-bit) (cohort: 99_Win_51)  Windows

**Comment by dfannius** [comment]
@ferdnandoc Can you say specifically 1) what you expected to happen at this time and 2) what happened instead?

I went into hotseat mode with that game, clicked Leave Game, and the log said "Pedro Miranda chooses to leave game" and the game seemed to continue normally.

(It is a pinned game, FWIW)

**Comment by ferdnandoc** [comment]
@dfannius 1) the the quitting player should be "eliminated" but the game should resume. 1849 allows players to resign without the game ending according to 10.7 on the AAG rulebook. 

2) On our game the game just froze and no actions can be taken with the message "We're sorry this game cannot be continued due to GameError: Blocking step Bankruptcy Choice cannot process action 57
Broken action: { "type": "pass", "entity": "AFG", "entity_type": "corporation", "id": 57, "created_at": 1641512766 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/66425?action=56)"

And when i try to use master mode to do something it goes "This game is broken and can't accept new actions."

**Comment by dfannius** [comment]
Thanks. It looks like it's exactly the same deal as #7124; the site didn't handle bankruptcy correctly before, and now that it does, this game retroactively broke the rules, can't continue with the current codebase, and is pinned to an earlier version of the site. I thought you'd be able to continue with the old pinned version of the site but if that's not possible then I think you're out of luck.

**Comment by ferdnandoc** [comment]
No problems. Things like this happen. Any way that we can delete or end the game?

**Comment by dfannius** [comment]
I've asked someone with the appropriate permissions to delete it.
