### ISSUE TITLE
[18Ireland] Autoroute allowed a hex train to run narrow gauge

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#7394]
Run auto from this action: https://18xx.games/game/75061?action=134 and you'll see one of the trains running narrow gauge.
![image](https://user-images.githubusercontent.com/67359577/156869431-88801973-c2f5-4f1d-b954-29a975fdc42d.png)

**Comment by crericha** [comment]
@JoeB989 FYI

**Comment by dfannius** [comment]
Dup of #7297.
