### ISSUE TITLE
[18Ches] C&P (P2) should not allow a single tile to be laid (must be both)

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#7410]
https://gist.github.com/benjaminxscott/fe3dca9e3d76afc1ce622784495cb3d6

If I understand the rules, the C&P *must* lay both tiles at the same time, and cannot choose to lay a single tile

It looks like the implementation allows the C&P to lay a single tile in one of the reserved hexes

Perhaps `must_lay_all` is not functioning as expected

This probably extends to other privates in Ireland and Ches that have similar properties

**Comment by scottredracecar** [comment]
This used to be enforced after the tiles were laid revert if both not laid
and connected). Maybe something broke it.

**Comment by michaeljb** [comment]
This was fixed by #7990
