### ISSUE TITLE
18EU prompted to choose city incorrectly

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7414]
https://18xx.games/game/73809?action=604

ChrisShaffer just bought 10% of GSR and is now being prompted to select a city for its home token. However, GSR already has tokens and trains. Also, when ChrisShaffer chooses any hex, this error pops up:

<img width="733" alt="Screen Shot 2022-03-07 at 22 18 45" src="https://user-images.githubusercontent.com/8732435/157178514-fb3be1e4-5c51-422b-9fd3-ccb0ece26d24.png">

**Comment by ChrisTheCat** [comment]
p.s. the interface says it is still ChrisShaffer's turn.

<img width="418" alt="Screen Shot 2022-03-07 at 22 47 38" src="https://user-images.githubusercontent.com/8732435/157182468-5d2b3a99-c09a-4968-84b6-bf6046b82809.png">

**Comment by ryandriskel** [comment]
Fix incoming on next deploy. Game will be able to continue provided no further actions were taken.

**Comment by ChrisTheCat** [comment]
That works. It's impossible to take further actions, so we should be ok.
