### ISSUE TITLE
18NewEngland: Option to buy IPO Shares not provided even when player has enough money

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#7417]
I see in the notes that IPO shares show the current market value price instead of the par price. When you buy a share, the proper amount, which is the par amount, is deducted and given to the company. However, if the player has enough money for the IPO share, but not enough for the market share, it does not give the player the option of buying the IPO share.

I suspect the proper thing to do is to correct the shown IPO price so the normal checks, such as this one, work properly.

**Comment by scottredracecar** [comment]
All shares cost the same price. You'll probably want to check out the rules for the details of how this works.

**Comment by Jay-Davis** [comment]
Yup, sorry. Missed it, it was at the top of the column.
