### ISSUE TITLE
18USA Discard Pullman doesn't update train revenue

### ISSUE THREAD

**Issue by Narvinyar** [tobymao/18xx#7419]
During Run Trains step if Pullman is attached to a train and then Pullman is immediately discarded the revenue is still assuming Pullman still exists. 

If Pullman is discarded regardless of whether it was attached to a train previously or not the revenue should only consider the train is running without a Pullman. 

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.
 https://gist.github.com/Narvinyar/5a92186799e407fcc1dff2d968fea1a3

**Comment by crericha** [comment]
This one is a pain to fix and a "rules permissive" edge case that shouldn't ever happen. 

I tried fixing in the route step, but the revenue is cached in the view and apparently not checked on submission. Perhaps the easiest fix is to not allow pullman scrapping during the route step. If the player doesn't want to use the pullman, scrap before or don't attach.

**Comment by crericha** [comment]
There isn't any game value to fixing this edge case, other than it being technically correct. Since there isn't a straight-forward fix, I'm going to close it.

Good catch and thank you for submitting.
