### ISSUE TITLE
[18Rhl] RhE not parring correctly?

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#7420]
https://18xx.games/game/76129

I bid $180 on p6, but do not have the option to par RhE at $90.

![DB747AB0-3D4D-4550-B3A9-F9780CE49CE5](https://user-images.githubusercontent.com/73144084/157446609-9d84dc98-7fb2-493b-8929-497517451924.png)

**Comment by perwestling** [comment]
18Rhl wiki page at 18xx.games:
https://github.com/tobymao/18xx/wiki/18Rhl:-Rhineland

"RhE does receive the winning bid as starting treasury. The 3 shares that are moved to bank pool gets 3 times the par put aside next to it. The RhE president decide a par value, but can only choose 70, 75 or 80 mark. See [forum thread about this](https://boardgamegeek.com/thread/2754995/rhe-and-gve-capitalization)."

I see that the text of the private does not contain this information so I will add that.

**Comment by BellmakerSA** [comment]
Okay thanks. That is not listed anywhere in the attached rules either in the info tab 😕

**Comment by perwestling** [comment]
Here is the updated RhE corporation:
![image](https://user-images.githubusercontent.com/2631151/157499322-7e49fe66-2e25-4a4c-8993-756b463a732b.png)
