### ISSUE TITLE
18FL Track Runs

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#7426]
Game 75604.

Train allowed to take the sharp turn on brown "X" above Orlando without a dit at it's center to place token in Miami
(Plant before SR 6)

**Comment by ventusignis** [comment]
I read through sections 7.2 and 7.4 in the rules (Lay or Upgrade Track, Train Operation and Earnings Calculation) and I didn't see anything to indicate this is a rule, is the rule specified somewhere else? I haven't personally heard of this being a rule in 18FL

**Comment by scottredracecar** [comment]
I cannot understand what the suggested bug is here.

**Comment by dfannius** [comment]
The behavior looks correct to me.

**Comment by saxafras** [comment]
Sorry, saw floating cross and wasn't thinking lawson
