### ISSUE TITLE
[18EU] game reports it's broken

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#7428]
Game https://18xx.games/game/74219?action=518 is broken, prompting:
`We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action 519
Broken action: { "type": "place_token", "entity": "RPR", "entity_type": "corporation", "id": 519, "created_at": 1646358152, "city": "584-1-0", "slot": 1, "tokener": "RPR" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/74219?action=518)`

The game has also been reverted to where it was a week ago. I'll ask if one of us did that intentionally.

**Comment by ryandriskel** [comment]
There was a bug that allowed RPR to place two "home" tokens and none of the players noticed it had happened. It is impossible to recover from this point, I'm sorry.

**Comment by kepakiano** [comment]
Alright, thanks for looking into it! Can you remove the game, please?

**Comment by ryandriskel** [comment]
https://github.com/tobymao/18xx/issues/7414
