### ISSUE TITLE
During draft in 1846, you can't see anything unless you enable Master Mode

### ISSUE THREAD

**Issue by scientifics** [tobymao/18xx#743]
Title explains it all, when I clicked "Show" on my turn, I received the red banner that said Master Mode needed to be enabled. Once I enabled, I was able to click show to make my bid and see my player info panel.

**Comment by benjaminxscott** [comment]
I'm not able to repro this, unless it was stealthfixed in the intervening hours

**Comment by scottredracecar** [comment]
It probably only appears on the live site because in hotseat you are
automatically in master mode.

**Comment by tobymao** [comment]
i’m working on this, not sure the exact issue yet
