### ISSUE TITLE
[18USA] Company town block building and train running routes

### ISSUE THREAD

**Issue by alexpung** [tobymao/18xx#7430]
**Game ID**
https://18xx.games/game/75146

**Step to reproduce:**
1. A company with the Company town private lay the Company town tile. (NYC in this example)
2. Some other companies that is connected to the company town try to build a route through the company town, or run a train through it. (SR in this example)
See action 522 in this game
https://18xx.games/game/75146?action=522

**Actual behaviour:**
The company town act as if it is tokened out, other companies except the one owning the private cannot build or run a route through it.

**Expected behaviour:**
Other companies can build and run a route through it.

**discussion:**
https://boardgamegeek.com/thread/2828507/company-town-can-other-companies-run-and-build-thr

**Comment by crericha** [comment]
The -10 token is incorrectly not of type neutral.
