### ISSUE TITLE
18EU: Player doesn't win auction when they should

### ISSUE THREAD

**Issue by nigelsandwich** [tobymao/18xx#7432]
It appears that the the player bid 120 for this minor, but another player won it for 105. Not sure what's going on here.

https://18xx.games/game/76131

**Comment by dfannius** [comment]
The log says "akh911007 cannot afford 14" so I guess it accepted the next highest bid? It sounds like maybe the real bug is that akh911007 was allowed to bid all of their money but then wasn't allowed to use it.

**Comment by ryandriskel** [comment]
Fix will be available in next deploy. Watch for the winning bid to switch to akh911007

**Comment by nigelsandwich** [comment]
Awesome. Thank you Ryan
