### ISSUE TITLE
[18USA] Switch and Signal not functioning properly

### ISSUE THREAD

**Issue by skoomfest** [tobymao/18xx#7439]
Game id: 74523

In my reading of the rules, my understanding is that switch and signal should allow me to bypass a city on one train, regardless of whether the city has been blocked by others tokens.  In a previous playthrough (id: 74614) and in a hotseat of the current game mentioned above, I have been able to use switch and signal to bypass cities which are blocked by tokens, as intended.  However, I have been unable to get switch and signal to bypass a city which _is _not__ blocked out by tokens.  This includes both ordinary city tiles and the grey tiles of Toronto and Detroit (eg running a 3 train from Chicago to NYC via the grey tiles by using switch and signal to bypass Toronto)

**Comment by crericha** [comment]
Yes, that interpretation is correct. Fix incoming.
