### ISSUE TITLE
1825 Unit 1, no more actions after selling Shares

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#7440]
Gameid: 75350. ID 328
I was above share limit and had to sell shares.
After selling the C&W, the turn goes directly to the next player, no more actions like selling or buying Shares were possible.

Browser: Firefox, latest version.

**Comment by roseundy** [comment]
@volker18xxdev, it looks like you had auto-pass enabled, which is why you weren't able to take any other actions.
