### ISSUE TITLE
[18JP-T] error, game cannot continue 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#7445]
https://18xx.games/game/76294

![5EF75E05-B60C-4963-85AB-873F6ED79DDA](https://user-images.githubusercontent.com/73144084/157877886-c9776304-78f7-4fb3-91fe-bd0682e941cd.png)

game gives a message when I try to make my final buy in SR1

**Comment by vandamm** [comment]
This will be fixed when #7441 is merged. Hopefully today
