### ISSUE TITLE
[18USA] "undefined method `tokened_by' for <Engine::Part::Offboard: hex: A27>"

### ISSUE THREAD

**Issue by petersoncr1** [tobymao/18xx#7447]
Game Id: 76361 is currently not loading.

LHCper mentioned it was caused by a bug:

"Looks like a bug. Game throws the error:
"undefined method `tokened_by' for <Engine::Part::Offboard: hex: A27>"

**Comment by crericha** [comment]
Looks to be a switcher bug.
