### ISSUE TITLE
[1846 alpha] Showing available tile although it can't be reached or modified in Phase 1.

### ISSUE THREAD

**Issue by willbeplayin** [tobymao/18xx#745]
Local game. Had this happen when the game is still in the yellow tiles (phase 1). E19 can't be reached with PRR in any way (?) and yet it's highlighted.

https://i.ibb.co/nkwCP6D/1846bug1.png

**Comment by tobymao** [comment]
paste the json data

**Comment by tobymao** [comment]
nvm, this is fine, it's layable, just no tiles available for it
