### ISSUE TITLE
Games with no players

### ISSUE THREAD

**Issue by ryandriskel** [tobymao/18xx#7450]
I'm seeing this on the homepage for a couple games:

<img width="327" alt="Screen Shot 2022-03-11 at 12 46 09 PM" src="https://user-images.githubusercontent.com/15675400/157947782-5279f32d-42e4-4af3-af34-2a9ab6bfa4de.png">

<img width="335" alt="Screen Shot 2022-03-11 at 12 47 07 PM" src="https://user-images.githubusercontent.com/15675400/157947895-ec0bb4a0-a1e6-4176-b57d-2633ae1b3c63.png">

**Comment by ryandriskel** [comment]
Do people use that functionality legitimately? Right now they are just starting to clog up the interface.

**Comment by dfannius** [comment]
Is that how tournament games are created?

**Comment by tobymao** [comment]
yes it is

**Comment by ryandriskel** [comment]
Well, I guess we can close this then? Just bothers me :D
