### ISSUE TITLE
[1830] Something is Undefined

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#7456]
https://18xx.games/game/76457?action=47

On the game tab, between the player holdings and the train pool, something is "undefined."

**Comment by dfannius** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/1295244/158001630-3d4d799a-f268-4953-9f37-12df738e05fd.png">

**Comment by kelsin** [comment]
This is due to my tranches addition, fixing now.
