### ISSUE TITLE
[18VA]: The server did not accept this action due to: unknown keyword: :borrow_from... refreshing.

### ISSUE THREAD

**Issue by cjboyett** [tobymao/18xx#7457]
**What's your Game ID?**

https://18xx.games/game/73750

**How to Reproduce the Bug?**

This error occurs with any action I attempt to take, ranging from skipping track, laying track, undo, or even send a message in chat. This doesn't happen when I clone the game, however.

The error seems to have started when I was attempting to use auto-route. I had successfully skipped laying track and was checking to make sure not better route was available. That is when it first refreshed, and I have been stuck since.

**Which Browser / Platform?**

This happens on both mobile (Android - Chrome) and desktop (Windows - Firefox).

**Comment by kelsin** [comment]
`borrow_from` is a new keyword that I added to some functions that if overridden need to be added. I think I found the spot where this took place. PR incoming.
