### ISSUE TITLE
[18USA] Unable to place bridge tokens on rural junctions

### ISSUE THREAD

**Issue by Hushful** [tobymao/18xx#7458]
Private text explicitly says it can have a bridge, but unable to place bridge token on rural junction tile.

**Comment by crericha** [comment]
What game id? Was the hex a river hex?

**Comment by Hushful** [comment]
I can't find the game ID, it doesn't show up in the game list.  I tried Omaha (D14).  I can place the rural junction tile on the city, but afterwards it will not allow me to place the bridge token.  Both privates are in the same company.  Selecting the bridge token private highlights tiles where you can place a bridge, and it highlights Minneapolis (C17) where we had laid a regular city, but not Omaha (D14) where there is a rural junction tile.
