### ISSUE TITLE
[18GB] Cannot lay token

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#7461]
CR attempts to lay token in Preston(NW)(G14), but program wants to upgrade tile instead.
https://18xx.games/hotseat/hs_frydtzms_1647021391
OR4.2 last company to operate

**Comment by andypymont** [comment]
Unfortunately the URL for a hotseat game cannot be shared in this way (as the game data is saved in browser local storage).

Can you please copy the game data (from the Tools tab) and share in a gist? https://gist.github.com/

**Comment by ianwilson156** [comment]
My mistake - the company had insufficient funds to lay a token.
