### ISSUE TITLE
18MEX add indicator for 5% NdM shares like 18Rhl

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7463]
When one player owns both 5% shares, you can't tell which player has two 5% shares and which player has one 10% share.

https://18xx.games/game/74915?title=18MEX#entities

<img width="333" alt="Screen Shot 2022-03-12 at 06 58 34" src="https://user-images.githubusercontent.com/8732435/158023104-0dc27334-1d32-47b4-adfa-a4e0e9c32737.png">

In 18Rhl, there are 20% shares, which are indicated with a d.

https://18xx.games/game/74957?action=250#entities

<img width="331" alt="Screen Shot 2022-03-12 at 06 58 49" src="https://user-images.githubusercontent.com/8732435/158023115-a04eca67-502c-4c73-8232-29fd6dd63155.png">

It would be nice if 18MEX used the same type of indicator, perhaps h for half share?

**Comment by perwestling** [comment]
I created an issue some time ago (#3601) but closed it as it would indicate a GUI change, and I don't do those. I thought there would be an even older issue about this but could not find it. Maybe it was part of the 18MEX "road map"?

Oh well, I let someone else fix this.

**Comment by jasonab** [comment]
This would still be a good change to. have
