### ISSUE TITLE
[18GB] Cannot lay token in Carlisle(H9)

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#7470]
Hotseat 18GB: NBR is attempting to lay a token in Carlisle, director (player 5) having just closed the M&C, but gets error message "No token slots available on H9"

https://gist.github.com/ianwilson156/2d9fe4296f7d1a14a5da581c1d256097

Chrome Version 99.0.4844.51 (Official Build) (64-bit) on desktop.

**Comment by andypymont** [comment]
I am able to lay the token here - you need to click on the private company name button first, then click to place the token.

(This may be slightly unintuitive when you directly close the company because you will have to click twice - I will add something to the Implementation Notes on the wiki.)

**Comment by ianwilson156** [comment]
OK, understood. Unfortunately, there are a few features of 18GB which force some unintuitive solutions e.g. how to token a city when it is also upgradeable.
