### ISSUE TITLE
[18JP-T] TC 20% train discount not applied after tokening A93

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#7475]
https://18xx.games/game/76303?action=489

TC should have a 20% discount on trains if it tokens A93. Currently it has tokened A93, but the game is still requiring full price for the 6 train available. TC has more than enough money to make the discounted purchase, but is unable to make it, being told it doesn't have the full $630.

**Comment by philcampeau** [comment]
Issue seems to be resolved now.

**Comment by vandamm** [comment]
Resolved by #7464
