### ISSUE TITLE
[1871:TOP] No Rules of play

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7477]
There are no rules available for 1871:TOP, and clicking the rules link just leads to an error page.

**Comment by kelsin** [comment]
Already in master, just needs another deploy. @tobymao will do it soon I'm sure.

**Comment by kelsin** [comment]
They are here for those that come here looking: https://s3.amazonaws.com/public.valefor.com/TOP71_RULES_PROTOTYPE.pdf

**Comment by kelsin** [comment]
@tobymao you deployed my change so this is solved and can be closed.

**Comment by xmunroe** [comment]
Thank you!
