### ISSUE TITLE
1846 stuck on forced purchase -- can't sell saleable shares

### ISSUE THREAD

**Issue by dagibbs** [tobymao/18xx#7488]
Game: https://18xx.games/game/75943

PRR has $539.
stoi must contribute $261 for PRR to afford a train from the Depot.
stoi has $140 in cash.
stoi has $407 in sellable shares.
stoi must sell shares to raise at least $121

But, the game is not presenting any way to sell the shares. 
-- doesn't show the three companies that could be sellable 

Player in-game reported it in chat, I cloned the game, and found the cloned game ended up in the same place.

**Comment by dagibbs** [comment]
And game https://18xx.games/game/75946 seems to have just hit the same problem.

**Comment by ririspark** [comment]
Same problem in 76252. I click on buy for the train and it doesn’t give the option to sell shares for the missing amount.

**Comment by tobymao** [comment]
due to https://github.com/tobymao/18xx/commit/e0c44bf65f3f4a4dd18c7c20904335756de7c036, reverted
