### ISSUE TITLE
All prototype games should be in prototype section

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#7493]
In the game creation dropdown, some prototype titles are in the prototype section, while others are in the alpha section. That's because the sorting code in [`create_game.rb`](https://github.com/tobymao/18xx/blob/e2b672d9ce33569d8024461ddee1806ef8312338/assets/app/view/create_game.rb#L89) only puts titles in the prototype section if `DEV_STAGE == production` (which seems at odds with being a prototype anyway!).

I suggest that all prototype games be in the prototype section, and that those games' entries can get an additional `[alpha]` or `[beta]` (instead of the current `[Prototype]`) if additional information really needs to be conveyed (although honestly anyone playing a prototype already should know what they're in for).

**Comment by kelsin** [comment]
Prototype however is very different than alpha / beta. Prototype is a flag about the design state of the game, where alpha/beta is about the implementation status of a game. I don't care about however toby wants them to display but just wanted to be clear that Production/Beta/Alpha is not the same as Prototype/Non-Prototype. Two different categorizations.

**Comment by dfannius** [comment]
Yes, this issue is purely about the presentation and I don’t propose removing any information.
