### ISSUE TITLE
18USA:  Issues placing resource tokens

### ISSUE THREAD

**Issue by BobProbst** [tobymao/18xx#7501]
https://18xx.games/game/74515

I don't know if this is a bug or not.  I'm running IC and MKT.  MKT has the Standard oil private and don't get any options to place my token when I lay tile g15.  is this because it's not connected to a town?

Likewise with IC.  I own the Keystone bridge and saw no way to place a coal token on E19 nor on F16

An explanation would be helpful here or maybe it's a bug?

**Comment by crericha** [comment]
Looking at the game, I see that the oil resource is on G15. Does that mean you figured out how to lay resources? I'm going to close the issue, but if you think this is a still a problem, please reopen and let me know what didn't work for you.
