### ISSUE TITLE
18NewEngland: re-sorting operating order after force-selling shares doesn't keep minors first

### ISSUE THREAD

**Issue by jtamplin** [tobymao/18xx#7502]
**What's your Game ID?**
https://18xx.games/game/77411

Game data:
https://gist.github.com/jtamplin/d770d704140423b8ded4e9a4faa6b31c

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
After Peter sold shares to fund buying a 4 train, the B&A showed operating before the GR, which shouldn't be the case.  We went back and did things differently so the order was correct.

**Which Browser / Platform?**
Chrome 99.0.4844.74
Windows laptop

**Comment by jtamplin** [comment]
Just repeated again on selling shares to purchase a train later

https://18xx.games/game/77411?action=358

**Comment by dfannius** [comment]
Fixing this will pin affected games, since they have now run in the wrong order.
