### ISSUE TITLE
21Moon - allows illegal route created with autorouting

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#7507]
To reproduce: clone this game, clear trains, click auto.
https://18xx.games/game/77429?action=435

I get the following routing where the blue route does not pass through the SP. The system doesn't mark this as route as invalid, even though it does not pass through the SP.
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/29106780/159166872-02946017-acd5-44ab-a580-8efcc51558ef.png">

**Comment by roseundy** [comment]
This looks legal to me. Both trains are from the SP "home". One train runs through the SP, the other intersects it. Have I misunderstood the routing rules?

**Comment by scottredracecar** [comment]
The blue train does not look like it is running through the SP to me.

?

**Comment by scottredracecar** [comment]
Oh, sorry, forgot the intersecting trains rule!
