### ISSUE TITLE
[18USA] Unable to put bridge tokens on company town

### ISSUE THREAD

**Issue by Hushful** [tobymao/18xx#7514]
The company town private description explicitly states that you can put a bridge token on a company town as long as it's placed on a river.  Exact wording - 

"If the Company Town tile is placed on a $10 river hex, a bridge token may be used."

This does not work.  As evidence game [#77692](https://18xx.games/game/77692) where I had companies in portland (C3) and boise (d6) and neither company was able to place a bridge token on the company town laid on a river tile on B4. 

This may be related to the existing bug #7458 that bridge tokens cannot be placed on rural junction tiles.  My suspicion is that bridge tokens have not been updated to include 18USA's corner cases

**Comment by crericha** [comment]
It was more than one developer started the game and had logic to handle both these cases, so when I picked up the game to finish it, I thought that part worked, but apparently it wasn't complete. That's why we alpha test!
