### ISSUE TITLE
[1866] Tracklays in second to last OR.

### ISSUE THREAD

**Issue by H1llsman** [tobymao/18xx#7517]
**What's your Game ID?**
https://18xx.games/game/77529?action=1435

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
Game end condition 2, sale of 10T was triggered in OR10 (https://18xx.games/game/77529?action=1236) - Game ends at the conclusion of OR12
Companies are still allowed to lay tracks in OR11 when they shouldn't be allowed to (Rule: 8.2.2). - (https://18xx.games/game/77529?action=1424)
in the Final OR Track lays and tokens are skipped automatically as intended. (https://18xx.games/game/77529?action=1523)

**Comment by magnusstjarnhild** [comment]
This was a last change to the rules.

**Comment by dfannius** [comment]
@magnusstjarnhild Do you mean 1) the rules recently changed so that the current behavior is correct even though it seemed that it wasn't, or 2) the current behavior used to be correct but the rules recently changed and now it is incorrect? I'm not sure whether the bug should stay open or not.

**Comment by magnusstjarnhild** [comment]
Sorry been away, the rules have always said only last OR was restricted and thats how i did it. Then after some late face to face playtesting simon added the last 2 OR's are restricted in the rules. But there is a discussion about it now, and i think he will return the rules to only restricted to the last OR. But waiting on his answer before im closing this issue.

**Comment by magnusstjarnhild** [comment]
Simon have decided that the implementation is how it should be done. Closing this as it isnt any bug. Simon will update the rules when he can.
