### ISSUE TITLE
[1866] National companies get too many yellow tile lays

### ISSUE THREAD

**Issue by H1llsman** [tobymao/18xx#7518]
**What's your Game ID?**
https://18xx.games/game/77529?action=203

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

During operation of a National companies (first occurrence: https://18xx.games/game/77529?action=203), are permitted to lay 2 pieces of yellow track or 1 upgrade. according to rule 14.3.2 only 1 piece of yellow track or 1 upgrade is allowed.
![image](https://user-images.githubusercontent.com/85963784/159378793-c758f385-51f6-457e-b1b2-d43a26178dce.png)

**Comment by magnusstjarnhild** [comment]
The rules are wrong, nationals should be able to lay 2 yellow or 1 upgrade. Will tell Simon to update the rules,
