### ISSUE TITLE
Profile page: only 8 finished games are shown

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#752]
it would be nice to navigate to older games, posdibly via „next“/„prev“

**Comment by tobymao** [comment]
i believe we show 1000, you must only have 8 finished games

**Comment by tobymao** [comment]
i did a query and confirm you only have 8 games

**Comment by Herbert62** [comment]
my first game had the description „the tecklenburg take“. I cannot see it.

**Comment by tobymao** [comment]
must have gotten deleted

**Comment by Herbert62** [comment]
puh :-(
thanks for checking 👍
