### ISSUE TITLE
[1862] Liquidity false count

### ISSUE THREAD

**Issue by NoodleGuy2** [tobymao/18xx#7521]
![Screenshot_20220322-161918_UC](https://user-images.githubusercontent.com/102156539/159477681-b300b74e-b265-4857-98a9-5ef9ab0aa14f.jpg)
https://18xx.games/game/77690
I think I can sell all of my shares including the director 
certificate,so my liquidity should be 610 as well?

**Comment by dfannius** [comment]
I verified in hotseat that NoodleGuy can indeed sell all their EUR shares and get to £610 in cash, so it is just the display that is wrong.

**Comment by roseundy** [comment]
Actually, the bug is that your liquidity should just be your cash, since you can't sell shares during a Parliament Round.
