### ISSUE TITLE
[TOP 1871]  Union Bank's Bankruptcy ends game

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#7526]
I believe this may be an issue with the implementation of the rules.  As currently implemented, when Union Bank is the president of a company and is forced to declare bankruptcy due to a forced train purchase, the game ends.  See for example https://18xx.games/hotseat/hs_uanshnwr_77312.  However, according to the prototype of the rules as currently published, only players can declare bankruptcy -- "If a **player** fails to raise enough money to force purchase a train, they are declared bankrupt and the game ends."  I leave it to the designer to determine if ending the game on Union Bank's bankruptcy is as intended or if it an issue with the current implementation, I am reporting in case it's an implementation problem.

**Comment by ssansonwu2010** [comment]
UNION BANK: Acts exactly like another player. Net worth of UB applied to owner at the end of the game. UB cannot voluntarily sell shares. UB can be president of a company. UB must spend all its cash before president may act for it. All normal player rules apply for UB.
 ansonwu: All normal player rules apply for UB
 ansonwu: so whether UB is a player is question for the bankrupty ending
 ansonwu: but as I find The Union Bank can be the president of a company. The owner of the Union Bank acts as the president of any company the Union Bank is president of. **If required to force buy a train, the Union Bank must first contribute as much as possible and sell shares if needed before the owner of the Union Bank can contribute to the forced purchase.**
ansonwu: in lawyer interpret the contextual link, I assume the owner of UB is forced to contribute the train purchase
 ansonwu: i would say better post the question in bgg asking the author of this game
 
 
 As I said in the testing game 77312, I think the current implementation of the game derivated from the rules, the owner of UB should be forced to contribute for the obligation of forced purchase in case UB is the president of the required company.

**Comment by kelsin** [comment]
This is known. UB EMR is not working. It's the last feature that needs implementation. @tobymao can assign this to me to track.

**Comment by luigicoolGH** [comment]
Thank you!

**Comment by luigicoolGH** [comment]
I could not find a label for TOP 1871 to search by label, where is it?

**Comment by dfannius** [comment]
@luigicoolGH Hotseat games are stored locally so they're not viewable by anyone except the player. If you still have the game around, you could publish the stored game as a gist so that developers can see it and recreate the issue. Otherwise, it would help a lot you (or anyone else) could create or find a new game that demonstrates the problem.
