### ISSUE TITLE
[18USA] Illegal tile lay 

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#7529]
In this game of 18USA https://18xx.games/game/74762?action=743 placing a #6 tile (`MP lays tile #6 with rotation 0 on C29 (Boston)`) resulted in a tile which isn't present in the tile roster
![image](https://user-images.githubusercontent.com/72523908/159879317-6bd1312e-9ec8-4c12-9242-b4a1d92f2c3f.png)

**Comment by crericha** [comment]
Dup of another issue that has already been fixed.
