### ISSUE TITLE
18Chesapeake cert count wrong

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#753]
Mshaver is listed as 2 but it should be 3

{
  "id": 1648,
  "description": "J.K.M.G.",
  "user": {
    "id": 1296,
    "name": "Mshaver"
  },
  "players": [
    {
      "id": 1619,
      "name": "gregoire"
    },
    {
      "id": 1789,
      "name": "kraasn"
    },
    {
      "id": 1296,
      "name": "Mshaver"
    },
    {
      "id": 156,
      "name": "闯荡江湖"
    }
  ],
  "max_players": 4,
  "title": "18Chesapeake",
  "settings": {
    "seed": 1.9607613251226037e+38
  },
  "status": "active",
  "turn": 3,
  "round": "Stock Round",
  "acting": [
    156
  ],
  "result": {},
  "actions": [
    {
      "type": "message",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 1,
      "message": "I think Gregoire is first up."
    },
    {
      "type": "bid",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 2,
      "company": "B&OR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 3,
      "company": "CV",
      "price": 205
    },
    {
      "type": "bid",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 4,
      "company": "B&S",
      "price": 55
    },
    {
      "id": 5,
      "type": "bid",
      "price": 110,
      "entity": "闯荡江湖",
      "company": "B&OR",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "undo",
      "entity": "gregoire",
      "entity_type": "player"
    },
    {
      "type": "bid",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 7,
      "company": "C&OC",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 8,
      "company": "D&R",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 9,
      "company": "C-P",
      "price": 40
    },
    {
      "type": "par",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 10,
      "corporation": "PLE",
      "share_price": "95,2,4"
    },
    {
      "type": "par",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 11,
      "corporation": "B&O",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 12,
      "corporation": "N&W",
      "share_price": "70,4,2"
    },
    {
      "type": "pass",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "pass",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "B&O_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "N&W_1"
      ]
    },
    {
      "type": "par",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 17,
      "corporation": "LV",
      "share_price": "70,4,2"
    },
    {
      "type": "buy_shares",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "LV_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "B&O_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "N&W_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 21,
      "shares": [
        "LV_2"
      ]
    },
    {
      "type": "pass",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 23,
      "shares": [
        "B&O_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 24,
      "shares": [
        "N&W_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 25,
      "shares": [
        "LV_3"
      ]
    },
    {
      "type": "pass",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "B&O_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "N&W_4"
      ]
    },
    {
      "id": 29,
      "type": "pass",
      "entity": "gregoire",
      "entity_type": "player"
    },
    {
      "id": 30,
      "type": "undo",
      "entity": "kraasn",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "LV_4"
      ]
    },
    {
      "type": "pass",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "N&W_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 34,
      "shares": [
        "LV_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "N&W_6"
      ]
    },
    {
      "type": "pass",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 37,
      "hex": "G7",
      "tile": "9-0",
      "rotation": 4
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 38,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 39
    },
    {
      "type": "lay_tile",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 40,
      "hex": "C13",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 41,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 42,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 43
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 44,
      "hex": "J2",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 45,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "id": 47,
      "type": "buy_shares",
      "entity": "kraasn",
      "shares": [
        "N&W_7"
      ],
      "entity_type": "player"
    },
    {
      "id": 48,
      "type": "undo",
      "entity": "Mshaver",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 49,
      "shares": [
        "N&W_7"
      ]
    },
    {
      "type": "sell_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 50,
      "shares": [
        "B&O_2"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 51,
      "shares": [
        "N&W_8"
      ]
    },
    {
      "type": "pass",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "pass",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 53
    },
    {
      "type": "buy_shares",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 54,
      "shares": [
        "B&O_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "pass",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "pass",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 57
    },
    {
      "type": "pass",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 58
    },
    {
      "type": "lay_tile",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 59,
      "hex": "D12",
      "tile": "57-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 60
    },
    {
      "type": "run_routes",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 61,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "B14",
              "C13"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "C13",
              "D12"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 62,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "N&W",
      "entity_type": "corporation",
      "id": 63
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 64
    },
    {
      "type": "run_routes",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 65,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "K1",
              "J2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 66,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 68,
      "hex": "F8",
      "tile": "X1-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 70,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H6",
              "G7",
              "F8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 71,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 72,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 73,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 74,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 75,
      "company": "B&S",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 76
    },
    {
      "type": "sell_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 77,
      "shares": [
        "N&W_5",
        "N&W_8"
      ],
      "percent": 20
    },
    {
      "type": "sell_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 78,
      "shares": [
        "B&O_3",
        "B&O_4",
        "B&O_5"
      ],
      "percent": 30
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 79,
      "shares": [
        "PLE_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "闯荡江湖",
      "entity_type": "player",
      "id": 80,
      "shares": [
        "B&O_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "gregoire",
      "entity_type": "player",
      "id": 81,
      "shares": [
        "B&O_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 82,
      "shares": [
        "B&O_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Mshaver",
      "entity_type": "player",
      "id": 83,
      "shares": [
        "PLE_2"
      ]
    },
    {
      "type": "message",
      "entity": "kraasn",
      "entity_type": "player",
      "id": 84,
      "message": "seems there is an error in the system. it states Mike has 2 certs, but he has 3. "
    }
  ],
  "loaded": true,
  "created_at": 1591077325,
  "updated_at": 1592457023
}

**Comment by tobymao** [comment]
yellow shares don't count towards cert limit
