### ISSUE TITLE
[18USA] Illegal (third) tile lay on already placed tile

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#7531]
https://18xx.games/game/74695?action=301
After placing two tiles instead of moving to the place station step, the denver hex got highlighted and I was only able to place a tile in denver, even though denver already had its tile placed
https://18xx.games/game/74695?action=302
only after this "fake" tile laying step I was able to place stations

**Comment by crericha** [comment]
This behavior is correct. Here is the relevant rule:

> If a company begins in Denver, it may choose the orientation of
> the Denver metropolis city tile. If no company starts in Denver,
> the first company to lay a track connecting to the Denver hex may
> choose the tile’s orientation.
