### ISSUE TITLE
1866 Color Map Hexsides at Ferries Differently than Always Blocked Hexsides

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#7534]
For map hexisdes that are blocked until a certain phase of the game, I would use a different color than the one used to denote hexsides that are always blocked to minimize potential for confusion. For the ferry hexsides that will become passable, I would use a dark shade of the tile color that becomes available for use with that phase. So for ferries that become usable in phase 3, I would use a dark green, and for ferries that become usable in phase 5, I would use a dark brown.

**Comment by dfannius** [comment]
@fanman80 What title is this issue in reference to?

**Comment by fanman80** [comment]
This is in reference to 1866 by Simon Cutforth.

**Comment by fanman80** [comment]
I am just referring to the hexsides that will become passable at some point in the game.  The ferry hexsides that will always be unpassable should remain the same color as the other unpassable hexsides.

Also, another color option for the hexsides that become passable is to make them a dark shade of the tile color corresponding to the color of the most advanced tile available just before the hexsides become passable.  So for phase 3 ferries the hexsides that become passable in phase 3 would be a dark yellow.  This would be consistent with the pre-printed "tiles" on some hexes in various 18xx titles.

**Comment by fanman80** [comment]
I posted this suggestion on BoardGameGeek.com ( [url=https://boardgamegeek.com/thread/2837735/suggestion-map-hexsides-ferries][/url]), and received the idea that rather than use a different color, the line could have a different symbol such as a dash.

**Comment by fanman80** [comment]
I hadn't played a game into phase 3.  Now that one of the games I am playing has made into phase 3, I see the red hexsides at each end of the ferries that opened at phase 3 turn to normal appearance for passable hexsides.  I think this is better than what I suggested.

**Comment by fanman80** [comment]
I hadn't played a game into phase 3.  Now that one of the games I am playing has made into phase 3, I see the red hexsides at each end of the ferries that opened at phase 3 turn to normal appearance for passable hexsides.  I think this is better than what I suggested.  I am closing this issue.
