### ISSUE TITLE
[18GB] Implement 2nd-edition playtest changes

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#7542]
We'd like to try out some potential rules changes for the All-Aboard Games 2nd edition of 18GB, before the game is moved to production.

Intent is to create a package of the below changes (and make this the default) so that it can be play-tested:
- Route bonuses: make the NS bonus the same as the EW bonus
- Trains: replace 3+1 with 3+2 and 5+2 with 3X trains (same rule for 3X as other X trains: the first 3X makes 4X trains available)
- Place home tokens at the start of the game (for companies in play). (For XX and OO hexes, when another company lays a yellow tile in the hex, the home markers should be placed on the unattached station.)
- Private companies: GN & MC grant a station marker additional to the company's normal set. (And therefore the CR using this will not get the token for free.)
- End-game variant as per 2E rulebook
- Special coloured area of stock market: change effect to be that the director can buy 2 shares/turn (but only if director already, not if not director before 1st purchase) rather than the existing effect

**Comment by pstone1** [comment]
One additional fix, the Liverpool Manchester private bonus should be +20 for running to Liverpool, its currently +10. See: https://boardgamegeek.com/thread/2825901/article/40150604#40150604

(this is not really part of the playtest changes, it should be 20 regardless of start option, just something that may have been overlooked in the original implementation)

**Comment by andypymont** [comment]
> One additional fix, the Liverpool Manchester private bonus should be +20 for running to Liverpool, its currently +10. 
Already waiting for merge into the codebaae as part of #7838
