### ISSUE TITLE
[1871] Union Bank Value not added at game end

### ISSUE THREAD

**Issue by Corvus-IRL** [tobymao/18xx#7544]
Game ID - 77670

Description above. At game end the value of cash & share value was not added to the owner of the Union Banks final total.

**Comment by philcampeau** [comment]
Union Bank value is always included in the owning player's value from the beginning of the game. The Player who owns UB has a total value of $3133 not including the UB. Adding the $1701 value of the UB gives you a total of $4834, which is the value showing for that player. 

No bug here.

**Comment by Corvus-IRL** [comment]
Thanks. That makes a lot more sense now. It might be worth adding a note to
the implementation stating that as its not explicit from the spreadsheet.
[image: image.png]

**Comment by dfannius** [comment]
Anyone can edit the wiki to add this information. Since no one had yet, I just did, and will close the issue now.
