### ISSUE TITLE
[1866] Company Reaches $0 but Still Needs to Buy a Train?

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#7546]
https://18xx.games/game/78376?action=814

Rule 16.0: "If a stock hits $0, the company closes." The GL hit $0 when it did not have a train, but then did not close and I was forced to buy a train.  

Players in the game where convinced this was not a bug, but then the rules need to be updated.

**Comment by Maxwell-Frank** [comment]
Relevant BGG thread for rules clarification: https://boardgamegeek.com/thread/2839227/when-does-company-close

**Comment by magnusstjarnhild** [comment]
The game is implemented as Simon wanted it. You have to buy a train and then the company closes as the last step in the OR. This also means if you have a train and take a loan and enters 0 it doesnt close if you run the train and goes up in value. Or repay loans to jump to the right.

Sure its punishing. I will wait to close this until i get a final ruling from simon that he wants it as is.

**Comment by magnusstjarnhild** [comment]
@Maxwell-Frank Yes we have changed way it works. The corporation still need to buy a train, but the player isnt any long liable for the loans. The bank settle thoose.

I will push a big update later this week, this change will be in there. I have hold of on pushing an update beacause it will break all the 1866 games, so we wanted to make sure all the small changes was in it.

Will close this for now.
