### ISSUE TITLE
[TOP 1871] UB unable to buy certain company shares during SR

### ISSUE THREAD

**Issue by waymost** [tobymao/18xx#7549]
**What's your Game ID?**

https://18xx.games/game/76984?action=397

**How to Reproduce the Bug?**

Beginning of SR7, I and the next player each bought a share as normal. The third player then split a company, starting the first company of the last tranche.

Action is back on me. As the owner of UB, I should be able to buy a share of the mainline as there are shares available, UB and I together have enough money, and UB hasn't taken an action this SR. However, when clicking on the company, the option for the UB to buy a treasury share isn't present. Any other company that has shares available to buy, the option for the UB to purchase does show up. It's just the mainline company where that option should be available and isn't.

**Which Browser / Platform?**
macOS Monterey 12.1
Chrome 99.0.4844.84

**Comment by dfannius** [comment]
Same as #7658, fixed by $7979.
