### ISSUE TITLE
5E train appears in 18CZ from nowhere

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#7550]
in game
https://18xx.games/game/74258
the kk was offered a 5E train from the bank pool but there should be none in the bank.

Action:
https://18xx.games/game/74258?action=734
and then go to purchase trains.

We suppose the 5E is the discarded 5h from the BTE.
Action:
https://18xx.games/game/74258?action=793

We are finishing the game without the pool 5E and the kk bought a 8E as it should have been. So there is no problem in the game 74258 but it should be clarified from where the 3rd 5E appeared.

**Comment by Zwergenpunk** [comment]
In the prevoius turn of BTE, BTE discarda a 5h train. That train is buyable as a 5Eh train.
