### ISSUE TITLE
[TOP 1871] Mainline Concession doesn't bestow presidency if someone else already has 20%

### ISSUE THREAD

**Issue by vantdog** [tobymao/18xx#7552]
In SR7, a player was unable to purchase a single MR share (2 remained in the market) but was able to make a single purchase for what became a 20% share (double share) in MR - buying up the final 2 shares in one transaction. We can't find anywhere in the rules where it makes reference to companies having double shares in addition to the presidency share.

Game #77966 for reference - game data related to the action:

https://18xx.games/game/77966?action=572 

          "type": "pass",
          "entity": 797,
          "entity_type": "player",
          "created_at": 1648580871
        }
      ],
      "shares": [
        "MB_7"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": 128,
      "shares": [
        "C_1",
        "C_4"
      ],
      "percent": 20,
      "entity_type": "player",
      "id": 565,
      "user": 128,
      "created_at": 1648581069,
      "skip": true
    },
    {
      "type": "message",
      "entity": 128,
      "entity_type": "player",
      "id": 566,
      "created_at": 1648581254,
      "message": "Trying to sell and buy MR, not sure why I can't do it"
    },
    {
      "skip": true,
      "type": "undo",
      "entity": 128,
      "entity_type": "player",
      "id": 567,
      "user": 128,
      "created_at": 1648581269
    },
    {
      "type": "sell_shares",
      "entity": 128,
      "shares": [
        "C_1",
        "C_4"
      ],
      "percent": 20,
      "entity_type": "player",
      "id": 568,
      "user": 128,
      "created_at": 1648581309,
      "skip": true
    },
    {
      "skip": true,
      "type": "undo",
      "entity": 128,
      "entity_type": "player",
      "id": 569,
      "user": 128,
      "created_at": 1648581504
    },
    {
      "type": "sell_shares",
      "entity": 128,
      "entity_type": "player",
      "id": 570,
      "created_at": 1648581509,
      "shares": [
        "C_1",
        "C_4",
        "C_6"
      ],
      "percent": 30
    },
    {
      "type": "sell_shares",
      "entity": 128,
      "entity_type": "player",
      "id": 571,
      "created_at": 1648581615,
      "shares": [
        "MB_6"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": 128,
      "entity_type": "player",
      "id": 572,
      "created_at": 1648581635,
      "auto_actions": [
        {
          "type": "program_disable",
          "entity": 341,
          "entity_type": "player",
          "created_at": 1648581634,
          "reason": "Shares were sold"
        }
      ],
      "shares": [
        "MR_0"
      ],
      "percent": 20
    },
    {
      "type": "message",
      "entity": 128,
      "entity_type": "player",
      "id": 573,
      "created_at": 1648581648,
      "message": "Ah ok... It's a double share??"
    },

**Comment by philcampeau** [comment]
I had a similar bug come up in our game: https://18xx.games/game/78716?action=311

on this action, Sumerside just split and it's giving me an option to buy a 20% treasury cert. What's very weird is to start, I have 1 share and Jason has 2, but if I buy the 20% it charges me for 2 shares, gives one to me and one to jason, and then says I have the presidency even though jason has more shares.

**Comment by kelsin** [comment]
These are probably all bugs with distributing the pres share during the split. Will be trying to track them all down soon. Can assign over to me.

**Comment by dfannius** [comment]
The problem with @vantdog's game seems to have started during the opening auction (it's even mentioned in the chat). nigelsandwich won two companies that each came with a 10% share of MR. This immediately (incorrectly) gave them the presidency even though the 20% president's certificate attached to the Mainline Concession was still outstanding. When czlam won the auction for the Mainline Concession, they received the 20% share but the game didn't give them the presidency. So not only was the presidency incorrectly denied to czlam, but there was also a 20% non-president share kicking around, which eventually caused the above problem down the road.

@philcampeau's game is now archived, but @skizelo's game has exactly the same issue as @vantdog's.
