### ISSUE TITLE
[1871] game crashed

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#7553]
https://18xx.games/game/78716

Unable to lay any tiles, we get an error in the top bar and it resets.

**Comment by philcampeau** [comment]
We were able to progress the game by undoing the end of the previous  corp's turn (PEIR) and redoing. Later we ran into the same issue going into a stock round, again right after the PEIR acted. It seems to have something to do with PEIR buying a train out of MR

**Comment by kelsin** [comment]
Hopefully this is same as #7594 I think I have the game doing a invalid auto action at some point.

**Comment by dfannius** [comment]
Game was archived on May 12 so there's no way to debug it anymore.
