### ISSUE TITLE
[1846] Private Draft is broken in Hotseat

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#756]
Started a new 3-player hotseat game. When I clicked on the "show" button so that Player 3 could choose a private, instead of seeing his choices, I got a message:

"Enter master mode to reveal other hand. Use this feature fairly."

![1846-test-2020-06-18](https://user-images.githubusercontent.com/972263/85019165-60e50f80-b13c-11ea-8c05-fbff4e82d937.png)

Game data:
[1846-test-2020-06-18.txt](https://github.com/tobymao/18xx/files/4798448/1846-test-2020-06-18.txt)

**Comment by wcraigtrader** [comment]
As others have noted in Slack, you have to use Master Mode for every single draft, but it can be worked through.

**Comment by tobymao** [comment]
i think this is fixed now
