### ISSUE TITLE
1862 Train route connection problem

### ISSUE THREAD

**Issue by NoodleGuy2** [tobymao/18xx#7560]
The connecting point of two train routes of one company doesn't need to be occupied by a station marker,according to the rules.
But during a hotseat game today, I find that it is not allowed to connect two train route with an empty station.

**Comment by NoodleGuy2** [comment]
https://18xx.games/hotseat/hs_nwkatnrg_1648707438

**Comment by NoodleGuy2** [comment]
By an empty station,I was talking about station in Witham.I failed to run my freight from Colchester to Witham,and then run a local from Witham to Sudbury.

**Comment by roseundy** [comment]
The code is not designed to care whether an intersecting city has a token, so there must be more to this.

Unfortunately, hotseat games are local to your computer only - I have no way of seeing them. Please follow the instructions on the bug submission page to create a gist and link it here.

**Comment by roseundy** [comment]
It's not clear from your description, and I apologize if this is obvious, but you are aware that each route segment (train) does need to connect to one of your tokens?
