### ISSUE TITLE
[1871]: Autobuy not working properly

### ISSUE THREAD

**Issue by cjboyett** [tobymao/18xx#7561]
**What's your Game ID?**

https://18xx.games/game/78297

**How to Reproduce the Bug?**

Steps to reproduce:
 1. During a stock round before a company other than the mainline or shortline have float, start a new company
 2. Set an automatic action to buy until floated for that company
 3. After other players have taken their turns, programmed action is cancelled with error "Disabled programmed action 'Buy S from IPO until floated' due to 'Cannot buy S from Treasury'"

**Which Browser / Platform?**

Tested on Firefox browser on Windows 10 PC and Chrome browser on Pixel 3 phone.

**Comment by luigicoolGH** [comment]
The reason for the error is that all S shares are in the market, not the treasury.  Would require additional option to buy from market until floated.

**Comment by kelsin** [comment]
Can assign this to me. That is the reason, currently the autobuy is only from IPO and all shares in 71 start in the market.

**Comment by philcampeau** [comment]
This was fixed with #9299
