### ISSUE TITLE
[1862] Acquisition stuck, player unable to sell or redeem share in non-surviving company (both give no share in market error)

### ISSUE THREAD

**Issue by simon-r-white** [tobymao/18xx#7562]
**What's your Game ID?**

https://18xx.games/game/78087

Player (isaacbf) is stuck, cannot sell or redeem the option-share - attempting either option results in an error (Y&N share not in market)

See https://18xx.games/game/78087?action=172

**How to Reproduce the Bug?**

There is something wrong with the share exchanging during the merge.

As an aside, if you backtrack and set the EUR as the surviving company the merge goes through without any issue (isaacbf can redeem the option-share as expected). Game gets stuck if you select Y&N as the surviving company.

I believe there is something wrong with the sequence of share exchanges and the "location" of the shares to be exchanged.

**Comment by roseundy** [comment]
When I originally wrote this, I had convinced myself (and added a check for) that after all the swapping was done, if a player had the most shares, but not the director's certificate, the director's certificate would be in the bank pool. Not true in this case.

Fortunately, the fix is easy.
