### ISSUE TITLE
[1861] Can't float minor in phase 3 stock round

### ISSUE THREAD

**Issue by Hepworthnot** [tobymao/18xx#7567]
https://18xx.games/game/78072

Stock round 3
'Heppy' on turn. Attempts to float any minor and gets message 'Nikolaev must be the first corporation'

![Screenshot 2022-04-02 073420](https://user-images.githubusercontent.com/43420560/161370286-df3feac5-ad79-4d66-8bd1-a67facdc36d9.jpg)

Chrome Version 100.0.4896.60 (Official Build) (64-bit)

Microsoft Surface pro

**Comment by SwanofTrumpeter** [comment]
I have the same issue in my game.

The 5s aren't out and there's 4 minors left to start but I get that _Nikolaev must be the first corporation_ text.

**Comment by dfannius** [comment]
Same as #7558?
