### ISSUE TITLE
[1866] Auction rounds uses next to auctioneer instead of next to winner

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#7571]
https://18xx.games/game/79163
In the initial auction round after an auction is won the next player is the one next in player order from the auctioneer instead of from the winner of the auction.  The rules in Section 10 say "The player next in player order number **to the auction winner** then auctions the next certificate"

**Comment by magnusstjarnhild** [comment]
Thank you for testing. The rules is wrong, simon will change the rules to relfect that the next in order is the next one in order, not the winning bid. The rules reflect an old revision of the game.
