### ISSUE TITLE
[18CO] "Must have a route to access existing track"

### ISSUE THREAD

**Issue by LefteyeFalconeer** [tobymao/18xx#7575]
Company CM cannot upgrade hex D18 even though there seems to be a clear route to it through E15 and E17. See screenshot.

![CM route](https://user-images.githubusercontent.com/103027528/161706037-d03eecf6-61f8-4e06-836a-60ac2c138a97.png)

**Comment by benjaminxscott** [comment]
I believe this is intended based on [rules in the wiki](https://github.com/tobymao/18xx/wiki/18CO:-Rock-&-Stock#operating-round)

Note that I think 18CO is the only game with this rule

> Corporations must be able to 'see' existing track on a plain track tile in order to connect to it. This prevents corporations from branching into a line that they cannot currently access. Note that corporations may upgrade a tile to create a "bridge" that does not connect to existing track, and may always upgrade cities, towns, and villages.

**Comment by LefteyeFalconeer** [comment]
My bad then. Sorry about it, and thanks for the clarification.
