### ISSUE TITLE
[1828] Merging floated with unfloated doesn't discard treasury

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#7576]
https://18xx.games/game/75459?action=769

Per @JEBrosius on a Discord server:

> I think 1828.games is at least doing something in the wrong order.  If one of the companies that are merging has not been floated, Rule 7.5.2.3 says that all money in treasury is returned to the bank.  Then, once the system is floated, which means no more than 40% remains in the IPO, the system is capitalized at 10 times its new price.  In our current game, Len merged the NKP into the WAB, and the WAB had not floated, so the $940 in the NKP treasury should be discarded.  Then once the WAB system is down to 40% in its IPO, it will get 10 times its price at that time.  This is not what 18xx.games is doing.
> I’m looking at the rules on JC’s website.  https://kanga.nu/~claw/1828/1828-Rules.pdf#page9

**Comment by dfannius** [comment]
I just verified that it's just a timing issue; the treasury is discarded after everyone's shares are dealt with, rather than before.

**Comment by JEBrosius** [comment]
Thank you, Dan.  It still would be preferable to follow the order in the rules, since new players will look at what happens on 18xx.games to validate that they are understanding the rules properly.

Eric
