### ISSUE TITLE
[18CZ] Acquisition of smaller company

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#7585]
In the rules, it states that "The Director of the larger company must announce a price per share for the smaller company that
is between 50% and 150% of its actual Share Price, inclusive."
for example, if the smaller company get a share price of 75K, 50% should be 37.5K and 150% should be 112.5K
in 18xx.games, the system will let u choose from 37 to 113, but from the rules, i think it should be 38 to 112

**Comment by Zwergenpunk** [comment]
the lower price was always correct, or do you have a gist/game where 37 was selectable? From the code and from testing I only could select 38 =/

The max value was always rounded up, which is not correct
