### ISSUE TITLE
[18CZ] 40K station after Acquisition

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#7586]
After Acquisition, the 40K station of the company kk become 100K

**Comment by Zwergenpunk** [comment]
This is correct. There are several bgg threads for that. And multiple issues here.

**Comment by familiar-hk** [comment]
i mean the 40K station for the bigger company, not the 40K station for the smaller company

**Comment by familiar-hk** [comment]
i get it from the bgg post now, thx very much :)
