### ISSUE TITLE
[18USA] Resource Subsidy track lay is not free, and not being offered in addition to normal track lays

### ISSUE THREAD

**Issue by arcanor** [tobymao/18xx#7590]
https://18xx.games/game/78405?action=252

- NP owns the Resource Subsidy, as well as P17 Great Northern Railroad, as well as P3 Reece Oil & Gas
- on its first turn, starting in Fargo, it builds its home track tile, pointing northeast to Winnipeg, and west towards B12
- intention is to next use the Resource Subsidy's free extra track lay to place B12 with Coal, and simultaneously placing the Oil using P3 Reece Oil & Gas
- problem is that when choosing the straight tile with Oil and Coal on it, it costs $20 (should be free), and it uses up my extra track build, which I still want to take afterwards
- I'd like to continue on from there by laying B10 for free using the P17 Great Northern Railroad ability, and THEN finally lay my "normal" extra track lay on Helena (B10) for the usual $20

Expected result: pay $20 for 4 track lays, using subsidy and GNR abilities.

**Comment by dfannius** [comment]
Related to #7568?

**Comment by arcanor** [comment]
Ticket #7568 looks similar, yes. Maybe a fix there will resolve this issue.
