### ISSUE TITLE
[TOP 1871] Broken Action

### ISSUE THREAD

**Issue by garretwehrman** [tobymao/18xx#7594]
**What's your Game ID?**

https://18xx.games/game/77027?action=384

**How to Reproduce the Bug?**

Cannot go forward, possibly tied to PIER purchasing a train from SO.

**Comment by setrajonas** [comment]
I think we have a similar error here: https://18xx.games/game/79880?action=637

A is unable to do any action after the PEIR bought a train down from the SO.

**Comment by kelsin** [comment]
Ok, I bet I have the game trying to autopass the PEIR when they aren't an active player in the stock round or something. Will look into it.

**Comment by dfannius** [comment]
All of these cases seem to happen right after PEIR cross-buys a train.

**Comment by dfannius** [comment]
FWIW, I ran a local multiplayer game, had the PEIR cross-buy a train, and things were fine. So if this still happens to anyone it would be great to know.

**Comment by dfannius** [comment]
If no one sees this for another month I'm going to close it.

**Comment by philcampeau** [comment]
Issue has been dormant for a long time with no similar reports. 

Closing, we can always reopen if the problem comes up again.
