### ISSUE TITLE
[TOP 1871] Union Bank unable to start company / buy presidents share

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7596]
**What's your Game ID?**

https://18xx.games/game/79474?action=269

**How to Reproduce the Bug?**

Union Bank should be able to start the C company, but the only option provided is to buy it for the player and not for the bank.

**Comment by dfannius** [comment]
I don't see any support for parring on behalf of other entities, as opposed to the support for buying and selling shares on behalf of other entities. So I think the feature of the Union Bank being able to start a company is missing, not just broken.
