### ISSUE TITLE
1822 Tax Haven Bug

### ISSUE THREAD

**Issue by DelmKorval** [tobymao/18xx#7597]
Can't bid on Tax Haven (which doesn't count against certificate limit), if you are at your certificate limit.
Since it doesn't count against cert limit, you *should* be able to bid on it even if at limit...

**Comment by Maxwell-Frank** [comment]
`4.10.8 A player may not place or move a bid on an item if they are at the certificate limit. Each item on which a player currently has the highest bid counts as a certificate against the certificate limit. (This applies to P16 tax haven as well.)`
