### ISSUE TITLE
[Rolling Stock] Add recommended v1 variants (6 players, always use best company of each color)

### ISSUE THREAD

**Issue by beorn7** [tobymao/18xx#7600]
@roseundy First of all, many thanks for implementing Rolling Stock on 18xx.games.

I would like to suggest adding two officially endorsed variants to the v1 implementation, which should be very easy because they are regular parts of v2 anyway. (Those variants are well hidden in the player's guide of the All Aboard version but I recommend them highly. I have now also updated the [web-published player's guide](http://rabenste.in/rollingstock/players_guide.pdf) so that its content more or less matches the printed version and includes these variants.)

1. 6-player variant: Works the same as in v2. Simply use all companies and reduce the start money to $25. It's a very long but also very fun game, and with online async play, it's totally doable. (rollingstock.net had already allowed this variant even for v1.)
2. Guarantee that the most expensive company of each color is always in the mix. With all the lessons learned over time, I _highly_ recommend to always play with this variant (which is the reason it became standard in v2).

Even though I personally think that suggestion #2 is just better than the published standard rules, I think it should still be optional in v1 to not confuse anyone.

**Comment by tobymao** [comment]
I didn’t catch this. @roseundy , can we make stars the default. and original the optional rule. additionally just leave 6 players in as standard, no need for a variant, 

and like rolling stock.net just always include the top company in setup.

**Comment by roseundy** [comment]
I didn't make Stars the default for Rolling Stock, since I created a separate Rolling Stock Stars game entry.

I apologize, I was going off the copy of Rolling Stock that I have. I didn't check to see if the written rules were different from the online version.  I will just make Rolling Stock go to 6 players (what about about 2?) and add another optional rule for Rolling Stock.

**Comment by beorn7** [comment]
I think you can let RS go down to 2 players, same as RSS.

The history behind the 2-player capability is that I don't really think the game works as a regular 2-player game. However, it turned out that some players still liked it, among them @scottredracecar, so RSS got officially blessed for 2 players. But the same line of argument can be used to bless RS for 2 players.

To go even deeper down the rabbit hole: The "true" 2 player version is the one where each player plays two "hands", and you win if your lower-scoring hand scores better than the lower-scoring hand of your opponent. That's also in the player's guide. But I think it is still pretty niche and doesn't need to be explicitly implemented on 18xx.games. (You could just play a 4-player game in hotseat mode, or create secondary accounts for your second hand, playing the latter from a separate browser session or an incognito tab.)
