### ISSUE TITLE
[Rolling Stock] https://18xx.games/game/79973 doesn't load

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#7601]
See headline.

**Comment by roseundy** [comment]
Arrgh! I can't reproduce this on my development server.  I see this when running on the production server:

**Comment by roseundy** [comment]
I have found the root cause - I'm trying to show a player color for the Foreign Investor (which isn't really a player). A workaround exists: Go to any other game on the site, go to the map tab and disable "show player colors". Then Rolling Stock should work

**Comment by KlausKiermeier** [comment]
I've done what you said, and the game loaded!
Has every player of every RS game to do this workaround?

**Comment by roseundy** [comment]
Until I can get the fix out, yes. However, you should only have to disable player colors once.

**Comment by waaayback** [comment]
Obviously, I'm having this problem as well.   Came here to file a bug and saw it was already submitted.  :)

**Comment by ChrisTheCat** [comment]
Same problem, same solution, but note that I don't have to disable player colors once. My workflow is:

Open RS, load hangs
Open another game, disable player colors
Take RS turn
Open another game, enable player colors
Take turns in other games

Rinse repeat

**Comment by roseundy** [comment]
Well, yes, if you re-enable player colors on another game, you will have to disable them again before you go back to Rolling Stock. I know this isn't ideal, but we'll get a fix pushed out soon.
