### ISSUE TITLE
Rolling Stock Stars rules with legible images

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7604]
The link to the Rolling Stock Stars rules leads to a file with images that are so low resolution they cannot be read. It would be great if a better copy of the rules could be linked.

**Comment by roseundy** [comment]
???? They look fine to me. What link are you using?

**Comment by roseundy** [comment]
OK, you are referring to the BGG version of the rules.

**Comment by beorn7** [comment]
See also https://boardgamegeek.com/thread/2887062/rulebook-readable-pictures . This seems to be a problem beyond 18xx.games. @scottredracecar is there any chance you could publish a version with higher-resolution images?

**Comment by beorn7** [comment]
https://boardgamegeek.com/filepage/206631/rolling-stock-stars-rules has a much nicer version now. Thanks @scottredracecar !

**Comment by ChrisTheCat** [comment]
On this page:

https://github.com/tobymao/18xx/wiki/Rolling-Stock

the link that I just re-titled (previously, both links were just "Rules,
Rules"

BGG Stars Rules with images
<https://boardgamegeek.com/filepage/206631/rolling-stock-stars-rules>

**Comment by ChrisTheCat** [comment]
Yes, the rules file that is linked from the info page.
