### ISSUE TITLE
[Rolling Stock] Make the companies available for auction visible all the time

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#7608]
**What's your idea?**

Let us know your proposed changes.

Playing Rolling Stock, it is crucial to have at any time the information available which companies are in the "offering for companies", i.e., which are/will be available in the next auction. Presently, this information is only displayed during "Investment". Of course you can keep track of this, e.g. by taking notes, but for playability such a display would be a great help.

**Comment by roseundy** [comment]
They are displayed on the Info tab.
