### ISSUE TITLE
[1846] Unable to upgrade D20 (Erie) to green

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#7612]
If the B&O attempts to upgrade D20 (Erie) to green at this state of the game, it results in `no implicit conversion of NilClass into Integer` error

I believe what's happening is it's trying to drop an Erie token into the city, but both slots are already tokened out (game is in gray phase so the Erie reservation is gone)

I think Erie (if removed) should drop a token in that city when the game starts, rather than dropping when it's upgraded to green

cc @thepackrat 

https://18xx.games/game/79850?action=303

https://gist.github.com/benjaminxscott/e780aa2fdb31ef57187b69bfe5490a89

**Comment by thepackrat** [comment]
Thanks. I'll take a look. The in green is needed to avoid wedging open a token hole on tiles but corner cases abound.
