### ISSUE TITLE
[Rolling Stock] IPO phase happens in wrong order.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#7615]
https://18xx.games/game/80435?action=8

Forming corps in IPO phase should happen from high to low company value.

In the above game, BSE (2) gets to form before AKE (6).

**Comment by roseundy** [comment]
Burned yet again by the fact that sort always goes low-to-high

**Comment by KlausKiermeier** [comment]
Does it make sense to start new games before this bug is fixed?

**Comment by roseundy** [comment]
Apparently, I forgot to link this issue to my PR. This is now fixed.
