### ISSUE TITLE
[Rolling Stock] Priority order for next stock round needs to be visible.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#7616]
https://18xx.games/game/80435?action=8

Notice that the player cards, eg in the entities tab, do not indicate priority for the upcoming investment round.

Either list players in priority order on Entities, or add a field to the player card, explicitly stating the order.

**Comment by physic** [comment]
I don't know if a commit came in this morning, but this looks fixed. I'm seeing "Priority Deal" on the player with priority now.

**Comment by roseundy** [comment]
I didn't change anything here. The last commit to change Rolling stock was 3 days ago.
