### ISSUE TITLE
Cannot find finished games

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#7617]
I recently finished two games of 1861, of which I was the owner. One game finished in the last 12 hours.

I can't find either game to review them: they're not in 'your games', 'active games', nor in 'finished games'.

**Comment by ianwilson156** [comment]
Latest game ID was 75276

**Comment by ianwilson156** [comment]
The other game was 78133

**Comment by dfannius** [comment]
They are (or should be) at the bottom of your profile page.

**Comment by ianwilson156** [comment]
OK, found them there, thanks!
