### ISSUE TITLE
clicking Next on last page of games_row => it disappears

### ISSUE THREAD

**Issue by yzemaze** [tobymao/18xx#762]
open https://www.18xx.games/?finished=2000 (exact number is irrelevant, just needs to be bigger than actually available pages to show last page of games)
hit "Next" on finished games

=> game_row disappears

Works across browsers and for other categories, too.

PS: Usually there’s no "Next" button on the last page. But if you click Next in quick succession (think FPS-style) the effect is reproducible without URL-manipulation.

**Comment by scottredracecar** [comment]
I can't even tell how to get to the last page anymore. The provided link does not show finished games.
