### ISSUE TITLE
[Rolling Stock] Shares Display incorrect percentage

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#7624]
All company shares display as 10% when owned by a player, despite there being no 10 share companies in rolling stock. The percentage shown should really be the percentage of issued shares. When a company is started a player owns 50% and a 50% share is put on the market. Upon issuing the third share, all shares would change to 33% shares, etc.

Similarly, IPO shares should be renamed. They cannot be bought so are certainly not initial, public, or an offering. "Unissued" is probably the best term.

**Comment by roseundy** [comment]
I'm not going to change the percentages shown as stock is issued. Not only is that extremely difficult technically, I feel it would be very confusing. It would be better to just show the number of shares owned.

Are people confused by the "IPO" name?

**Comment by pstone1** [comment]
Number of shares owned would work fine. Just seeing the 10% increments that mean nothing now is strange. 

Confusion around IPO is that these shares cannot be purchased from an IPO, they really do not exist until they are issued. Market vs Treasury vs IPO terms are already a bit all over the place on different titles on the site, but this is a case where IPO is really far off and its a unique behavior, so it could use an accurate label instead of further diluting the default name.
