### ISSUE TITLE
1825 (maybe others) won't load, possibly my fault

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#7625]
I'm afraid my recent PRs have broken 1825 (with variant DB2). I also seem to have stoated up my local copy of the whole thing and I don't know how, but I'm pretty sure doing PAR_BY_CORPORATION['SECR'] = 67 in entities.rb is to blame since it complains about not modifying that frozen hash when I go to start game 80670.

I _guess_ 5e32c7401fd4314e4e753402fee9557d8e0d65 bumped the version of something making this a runtime error (and maybe the same in other games?)

If I apply that to my local copy I get "TypeError: $return_ivar is not a function" at localhost:9292 so I'm completely at sea here; I can't provoke the error locally, I can't run the version of the site where I think maybe I could produce it, and I certainly have no chance at all of getting a patch to not modify a frozen hash to work first time.

Sorry about all this.

**Comment by damerell** [comment]
https://18xx.games/game/80670 won't start.

80699 was created today and also wouldn't start, but I've deleted it.

'make clean' makes my dev system work - thanks, sorry - but it all seems to work there.

**Comment by roseundy** [comment]
OK, I was able to reproduce. It needs to be a multiplayer game, not hotseat. Makes sense if you are trying to modify a frozen object, since javascript doesn't support that and JS is the only thing running in hotseat.
