### ISSUE TITLE
Game 2420 Game Error

### ISSUE THREAD

**Issue by mhrabak** [tobymao/18xx#763]
{
  "id": 2420,
  "description": "Host is EST Time--Experienced Players--Super Fast Game--Multiple Moves a Day--Finish in 2-3 Days Max.",
  "user": {
    "id": 732,
    "name": "mhrabak"
  },
  "players": [
    {
      "id": 287,
      "name": "Danno"
    },
    {
      "id": 732,
      "name": "mhrabak"
    },
    {
      "id": 399,
      "name": "timox"
    },
    {
      "id": 300,
      "name": "mindphaser"
    },
    {
      "id": 21,
      "name": "Domerhoo"
    }
  ],
  "max_players": 5,
  "title": "1846",
  "settings": {
    "seed": 4.8926101676269445e+37
  },
  "status": "active",
  "turn": 1,
  "round": "Stock Round",
  "acting": [
    399
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 0,
      "entity": "Domerhoo",
      "company": "Pass (2)",
      "entity_type": "player"
    },
    {
      "id": 2,
      "type": "message",
      "entity": "Domerhoo",
      "message": "Hey I chose a company and it’s still my turn? Bug?",
      "entity_type": "player"
    },
    {
      "id": 3,
      "type": "message",
      "entity": "Domerhoo",
      "message": "No bug",
      "entity_type": "player"
    },
    {
      "id": 4,
      "type": "bid",
      "price": 80,
      "entity": "mindphaser",
      "company": "MAIL",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "bid",
      "price": 60,
      "entity": "timox",
      "company": "TBC",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "bid",
      "price": 60,
      "entity": "mhrabak",
      "company": "C&WI",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "bid",
      "price": 40,
      "entity": "Danno",
      "company": "LSL",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "bid",
      "price": 0,
      "entity": "Domerhoo",
      "company": "Pass (4)",
      "entity_type": "player"
    },
    {
      "id": 9,
      "type": "bid",
      "price": 60,
      "entity": "mindphaser",
      "company": "MS",
      "entity_type": "player"
    },
    {
      "id": 10,
      "type": "bid",
      "price": 40,
      "entity": "timox",
      "company": "SC",
      "entity_type": "player"
    },
    {
      "id": 11,
      "type": "bid",
      "price": 0,
      "entity": "mhrabak",
      "company": "Pass (0)",
      "entity_type": "player"
    },
    {
      "id": 12,
      "type": "bid",
      "price": 0,
      "entity": "Danno",
      "company": "Pass (1)",
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "bid",
      "price": 0,
      "entity": "Domerhoo",
      "company": "Pass (3)",
      "entity_type": "player"
    },
    {
      "id": 14,
      "type": "bid",
      "price": 60,
      "entity": "mindphaser",
      "company": "MPC",
      "entity_type": "player"
    },
    {
      "id": 15,
      "type": "bid",
      "price": 40,
      "entity": "timox",
      "company": "MC",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "bid",
      "price": 40,
      "entity": "mhrabak",
      "company": "O&I",
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "bid",
      "price": 40,
      "entity": "Danno",
      "company": "BIG4",
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "par",
      "entity": "Danno",
      "corporation": "PRR",
      "entity_type": "player",
      "share_price": "80,0,8"
    },
    {
      "id": 19,
      "type": "par",
      "entity": "mhrabak",
      "corporation": "NYC",
      "entity_type": "player",
      "share_price": "80,0,8"
    }
  ],
  "loaded": true,
  "created_at": 1592478026,
  "updated_at": 1592493350
}

**Comment by tobymao** [comment]
old version
