### ISSUE TITLE
[Rolling Stock Stars] - "double-shift" stock values calculated in error at either extreme

### ISSUE THREAD

**Issue by dirksteiner66** [tobymao/18xx#7632]
Link:  https://18xx.games/game/80850

After the last Action during Turn 12 Phase 4 (Closing) the game is frozen for some reason. I tried to refresh the browser (chrome) session by hitting F5 without any luck (the loading page came up but nothing more happend).

**Comment by roseundy** [comment]
Bug when calculating new share price when "going up 2" from next to last price.  Used `||` instead of `&&`

**Comment by roseundy** [comment]
This bug can also cause wild behavior when a corporation has a share value of $5 and does a "double" shift left when paying a dividend. Instead of bankrupting, it will trigger the end of the game because it rotates around and hits the max stock price.
