### ISSUE TITLE
18USA - resource subsidy not working

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#7647]
Game ID:  75065

https://18xx.games/game/75065

The UP has the resource subsidy and it is treating it as a normal tile lay. - it should be a free tile lay - so the second tile should not cost 20.

After investigating this some more i discovered that the 2nd resource is causing the problem, when i try to lay a coal by itself i can lay the oil next to it for free. However when i try to use the coal + iron tile it will not allow the placement of the tile without spending 20 and when i lay the iron and try to use the resource subsidy to lay coal + oil it tries to charge me an extra 20 that it shouldn't.

I have also noticed that having the hendrixson iron prevents me from using the subsidy to lay an iron, it automatically used the regular iron instead of the subsidy (which i want to use because its free.

**Comment by dfannius** [comment]
Sounds like the same thing as #7568 and/or #7590. I'm not familiar with 18USA so I'm not going to mark it as a duplicate myself.

**Comment by arcanor** [comment]
sounds like the same issue to me

**Comment by crericha** [comment]
Closing as a duplicate. If there is any additional information in this ticket that isn't covered in #7590, please add it there as a comment.
