### ISSUE TITLE
[Rolling Stock] Junkyard Scrappers unable to close companies

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#7650]
https://18xx.games/game/81288?action=295

The player with Junkyard Scrappers is unable to close any companies. Attempting to do so results in the error: "Engine::Corporation can't be coerced into Numeric"

Reproduceable in hotseat.

**Comment by roseundy** [comment]
Unfortunately, the fix for this is lumped in with the player order fix. Which means that this game will either be archived or pinned and in either case, you won't see the fix for the Junkyard Scrapper bug :-( for this particular game.
