### ISSUE TITLE
[Rolling Stock] Player Order is not being determined correctly

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#7651]
https://18xx.games/game/81288?action=273

Priority Deal is given to the correct player (the player with the most money).
But player order is incorrect. The game is incorrectly preserving a constant "table order" as in 1830, rather than a re-sort by money as in 1822 or Harzbahn.

Per the Canonical Rules:
>Phase 2: Wrap-up. Determine the new Player Order by descending
>remaining Money. Ties are broken by the old Player Order

**Comment by roseundy** [comment]
Arrrg! This is what comes of mainly doing 2P testing. Thank you for catching this.

**Comment by roseundy** [comment]
This bug will invalidate almost every multiplayer game. I'll see if I can get Toby to pin instead of archive them.
