### ISSUE TITLE
[TOP 1871] UB can't purchase company share because UB owner already owns 60% of said company.

### ISSUE THREAD

**Issue by garretwehrman** [tobymao/18xx#7658]
**What's your Game ID?**

https://18xx.games/game/81134?action=501

**What steps cause the unexpected behavior?**

Lemem, owner of UB, owns 60% of C. UB cannot buy a share of C, despite having enough money to do so and not taking an action this SR. If Lemem sells a share of C, UB can then purchase a share of C.

**Comment by luigicoolGH** [comment]
I confirm this also happened in one of the games I played, owner of UB had 60% of the shares in the company and UB could not use its action to buy a share of that company in spite of having action and $ to do so.
