### ISSUE TITLE
[18USA] Liquidation completely broken

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#7662]
https://18xx.games/game/74695?action=2107
In the liquidation these game breaking bugs happened:
- the company in liquidation, after being acquired, remained in game, the ATSF, even though the company the bought it replaced the stations and acquired its trains 
- all the short holders didn't close their short position, since the company is still in play
- all the following events (forced share selling for the cash crisis, etc.) didn't happen

**Comment by giovandc** [comment]
We stopped the game at action # 2121 so that hopefully the bug can be fixed and the game can continue without breaking

**Comment by crericha** [comment]
I found the issue and fixed it, but since your game is pinned, the fix will not be available to you.

**Comment by crericha** [comment]
@giovandc, I was able to unpin your game. You can now continue.

**Comment by giovandc** [comment]
That's really a good news to hear. Thank you!!
