### ISSUE TITLE
[TOP 1871] Player not given the option to purchase a market share despite being legally able to do so 

### ISSUE THREAD

**Issue by Rontuaru** [tobymao/18xx#7667]
**What's your Game ID?**
`https://18xx.games/game/80844

**What steps cause the unexpected behavior?**

Player RJ_E is attempting to buy the final share of MR from the market. They have not sold MR in the same stock round, they have sufficient money to pay for it, and they have certificate space. The attempt generates no error - it simply does not show the option to buy the MR share, when clicking on the company placard.

Other notes:
- During OR 5.1, the MR share held by Shipbuilding was automatically exchanged upon purchase of the 4+ train (when the private closed). It's possible this has something to do with the issue? 

- When re-doing actions in the current stock round to allow RJ_E to take MR presidency before drstclair can defend it, then drstclair cannot buy the final share. Somehow the final MR share is bugged.

Update Apr 26 2022:
- In the subsequent SR 7, no players can purchase the aforementioned MR shares. RJ_E sold down his held shares in SR6, and they are all presently "locked" in the market.

**Comment by dfannius** [comment]
Same as #7734, fixed by #7978.
