### ISSUE TITLE
[TOP 1871] Union Bank Can't Buy Shares from Treasury Unless Owning Player also has enough cash on hand.

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#7673]
Game:

https://18xx.games/game/81198?action=489

Union Bank is only given the choice to buy Market Shares, and cannot buy any shares from Treasuries (MR or So in this case). If I sell a share so the Player Owner has enough cash to buy the Treasury share, it only then allows the Union Bank to buy a Treasury share.

**Comment by dfannius** [comment]
Same as #7658, fixed by $7979.
