### ISSUE TITLE
18Rhl - game not allowing a player to declare bankruptcy

### ISSUE THREAD

**Issue by glomzig** [tobymao/18xx#7674]
https://gist.github.com/glomzig/677f1a1a0d5647952f8fbc9b9a24c750

How to reproduce the bug: the player operating RhE needs to purchase a train out of pocket but does not have the cash. They must sell all sellable shares which leaves them with 3 CME and 4 RhE due to shares in the market. They do not have enough money for a train and the only option is to declare bankruptcy. When clicked, the error message: "0 is not valid to spend" is shown. The game cannot advance further until the player is able to declare bankruptcy, which should be allowed at this point.

**Comment by perwestling** [comment]
A bug in 18Rhl handling of what happens after a player have declared bankruptcy and the corporation is put into receivership.
Good that this situation occured, so now I have a chance to try out the implementation.

Have fixed this bug but encountered a new one so I will continue to try to fix it. Hopefully a fix will be available soon so I can deploy a fix in a couple of days.

**Comment by perwestling** [comment]
Fix has now been delivered. Will be made available for 18xx.games next time a new version is deployed.

**Comment by glomzig** [comment]
Great thanks. Is there a way for us to continue on with the game?

**Comment by perwestling** [comment]
@glomzig This was a bug that caused the game to get stuck, making it impossible to complete the bankruptcy. When bug fix is delivered it should be possible to get passed by that stuck, and continue the game. So yes, it should be possible to continue, and hopefully, complete the game.

**Comment by perwestling** [comment]
@glomzig Now it has been deployed so bankruptcy button should work.
