### ISSUE TITLE
18USA: Company remains after acquisition

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#7689]
https://18xx.games/game/80229?action=1433

Here the DRG is acquired, but it is not reset. Furthermore, the M&A round ends prematurely leaving the C&O in acquisition in the SR

**Comment by crericha** [comment]
@ventusignis, the pullman code for MA rounds is not correct. I've already fixed it a couple of times for other bugs reported. I'll take a look, but it would be good if you did too since this is something you implemented.
