### ISSUE TITLE
1822 - 'sold-out' stock price movement 

### ISSUE THREAD

**Issue by JDesmond-NewarkNJ** [tobymao/18xx#7694]
https://18xx.games/game/80627 - at end of stock round 9 - GWR should have moved a row upward (per Rule 4.12.1) but stock price stayed the same, although prices for other RRsdid increase.  Please check

**Comment by Maxwell-Frank** [comment]
@JDesmond-NewarkNJ The stock price did move. When it can't go up due to the ceiling, it moves down and right, which just happened to be the same number.
