### ISSUE TITLE
18Ireland: Is it allowed to put non-connected tiles for Tralee & Dingle Railway?

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7696]
It was possible for the private to place tiles like this:
![image](https://user-images.githubusercontent.com/2631151/167136677-9f92d2f6-7064-47c3-a72d-3fd8081690bd.png)

Is that allowed?

**Comment by benjaminxscott** [comment]
Hmm, [the "must connect" `connect`](https://github.com/tobymao/18xx/blob/master/lib/engine/ability/README.md#tile_lay) flag is enabled by default, so it probably is something about those tiles (or narrow gauge) that isn't handlingconnectivity

**Comment by dfannius** [comment]
https://18xx.games/game/79537?action=516
