### ISSUE TITLE
[18NewEngland] Game becomes unresponsive

### ISSUE THREAD

**Issue by FlandersBurger** [tobymao/18xx#7698]
**What's your Game ID?**
68247

https://18xx.games/game/68247

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
Trying to lay track on my turn, The page becomes unresponsive for a while and then doesnt accept my the track I layed.
I tried several different locations for my track but it didn't make a difference
Operating Round 9.2. The bank has broken

Please include screenshots (you can drag and drop or upload them into this issue)
![image](https://user-images.githubusercontent.com/8195826/167237802-ac9eb55b-210d-4dd2-aff2-aeb2bff067b0.png)

**Which Browser / Platform?**
On Chrome 100.0.4896.127

**Comment by crericha** [comment]
The game takes about 20 seconds to load. The load performance needs to be analyzed.

**Comment by tobymao** [comment]
@roseundy maybe you’re calling graph or something

**Comment by crericha** [comment]
Looks like the last changes were from you, Steve, in February. If those changes had performance problems, it probably would have been reported before now. Maybe there was a common code change that is impacting the game?

**Comment by roseundy** [comment]
I'll take a look. I fixed a graph issue in 21Moon recently, maybe this will have a similar fix.

**Comment by roseundy** [comment]
A single call to Graph::compute when displaying the map (not loading) is taking 20 seconds to complete. Still investigating.

**Comment by roseundy** [comment]
I have been working on performance improvements to Graph. I have identified one optimization that will speed up loading this specific game by a factor of two. Sadly, it's only a 5% improvement in the general case.

**Comment by roseundy** [comment]
I now currently have an optimization that cuts the load time for this case by a factor of 5.

**Comment by roseundy** [comment]
I now have code that cuts the load time by close to a factor of 10. 34 seconds vs. 3.5 seconds.

**Comment by roseundy** [comment]
The last performance improvements were a mirage due to JavaScript faking me out.

Back to 19s (still better than nothing).
