### ISSUE TITLE
[18zoo] Game 81965 locked

### ISSUE THREAD

**Issue by serpentium** [tobymao/18xx#7699]
https://18xx.games/game/81965 doesnt open, I’m using safari on ipad

**Comment by perwestling** [comment]
I get the same effect when trying to open the game on Chrome. Looks like a bug, so a designer need to have a look at it.

**Comment by crericha** [comment]
'undefined method `<\' for [{"nodes"=>["city", "offb…>1}, {"nodes"=>["town"], "pay"=>99, "visit"=>99}]'
