### ISSUE TITLE
[1862] [wishlist] don't offer warranties on permanent trains

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#7717]
In 1862 the interface offers warranties (which delay rusting) even when purchasing permanent trains. It would be nice if it didn't.

**Comment by damerell** [comment]
I thought this over in view of @Maxwell-Frank's comment and while warranties are non-transferable, I agree it's not prohibited, and I sat here and thought about it and thought of such a scenario; I expect a hostile takeover next stock round and want to waste as much company money as possible (and, presumably, am doing a forced train purchase, or I'd just buy nothing and waste a train-OR). I'm not yet closing this issue since I'm kind of hoping I can get Mike Hutton to say it's not allowed.

**Comment by Maxwell-Frank** [comment]
@damerell The rules explicitly say that it's allowed.  I could see wanting to spend money on warranties on a permanent train if you could buy the train out and leave the company with just enough money to force a re-fi and get two permanent trains out of the deal or something. 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/75334833/167902160-aca2c3e6-66f2-456b-810e-69772726258c.png">

**Comment by damerell** [comment]
The edition of the rules (8.4) I have does not have that italicised note. In view of it I am closing this issue. Thanks for digging that up.
