### ISSUE TITLE
Show possible upgrades for unconnected hexes, similar to upgrades for later phases

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7718]
Sometimes, I want to see the possible upgrades for another hex, even if the operating company isn't connected to it.  An example might be if the hex has special upgrades, or if I might want to build connecting track and need to check that I'll be able to upgrade the target tile when I reach it.

I suggest that the UI could show upgrades for hexes that can't be reached, displaying them in the same way that it already shows upgrades for future phases - semi transparent and with a suitable message over the top, e.g. "not connected".
Clicking on the hex again could cycle through future phases.

I assume this would be fairly easy to implement, because all the logic for upgrades is already done, and there is already the logic for displaying future phases.

This would mimic what happens sometimes in face-to-face games.  Often, we sometimes put special tiles next to their corresponding cities, to make it easy to see the future upgrades.  For ordinary hexes, we may compare tiles from the stock pile with the track already on the map.  In the current UI, you can't see the tiles and the map at the same time.  This enhancement would make that possible.

**Comment by tobymao** [comment]
no plans to implement this. i think this would be difficult because the UI looks at connections
