### ISSUE TITLE
1889 : Auto Pass player who owns Dougo Railways but player could exchange

### ISSUE THREAD

**Issue by McDood** [tobymao/18xx#772]
When a player has the Dougo Railways private but not enough money to perform a buy action in the first OR, the game Auto Pass the player, preventing him from exchanging his private for a share of Iyo Railways.

Here is a hot-seat clone data where the issue is shown

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "TR",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "MF",
      "price": 30
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "ER",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "SMR",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "DR",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "SIR",
      "price": 80
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "corporation": "UR",
      "share_price": "65,5,3"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "corporation": "IR",
      "share_price": "75,3,3"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "corporation": "SR",
      "share_price": "65,5,3"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "UR_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "IR_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "SR_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "UR_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "IR_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "UR_3"
      ]
    }
  ],
  "id": "hs_hhphvzdp_1592562892",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1889",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-19",
  "loaded": true,
  "result": {}
}

**Comment by jenf** [comment]
dup of #427. Player can exchange at any time even if it's not their turn
