### ISSUE TITLE
[1822MX] Typo - "notmal" instead of "normal" in P1-BLWC

### ISSUE THREAD

**Issue by cjboyett** [tobymao/18xx#7721]
![Screenshot_20220510-004455](https://user-images.githubusercontent.com/12616942/167556944-be6f05d8-cb3d-4e1d-ba72-20ced3d25fa3.png)

Very minor typo in description of P1-BLWC. Actually, looking again it looks like there is an "as" instead of "is" near the end.

...

One more. "it's" instead of "its" in the middle.

**Comment by perwestling** [comment]
Deployed
