### ISSUE TITLE
[1822MX] Initial auction is for M18+FCM in Concession #1 plus four minors in Minor boxes #1-4

### ISSUE THREAD

**Issue by AlejandroPrudente** [tobymao/18xx#7724]
I started a hotseat game to see if there were any problems at it was the first thing I saw: M18 in minor bid box #1.
![image](https://user-images.githubusercontent.com/25345736/167665845-e8ddfbda-6546-4e4b-8d10-f0eacb3a95a2.png)

I was even able to bid on it separately and finishing the SR is impossible at the reception of an error: undefined method 'to_bundle' for nil.

**Comment by outsidePasser** [comment]
Can you download the game data and attach it?
