### ISSUE TITLE
22MX - can’t build on tile w build cubes 

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#7731]
M17 laid 2 build cubes on the mountain hex between its base and Mexico City.   In a subsequent OR it tried to lay track in that hex and got an error that the minor did not have the requisite $80, which should have been discounted by cubes.   

https://18xx.games/game/83635

- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by outsidePasser** [comment]
Likely the same issue as #7728
