### ISSUE TITLE
[22MX] cannot sell share when emergence finance

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#7736]
As title

**Comment by outsidePasser** [comment]
Do you have a game where this occurred?

**Comment by familiar-hk** [comment]
hotseat game

**Comment by familiar-hk** [comment]
![image](https://user-images.githubusercontent.com/98611238/167809596-a5e740db-d851-401f-85f6-22d97963c428.png)

**Comment by outsidePasser** [comment]
Can you dump out the game data and post a link to it?

**Comment by familiar-hk** [comment]
[hs_rlruzqrm_1652241896.zip](https://github.com/tobymao/18xx/files/8681669/hs_rlruzqrm_1652241896.zip)

**Comment by outsidePasser** [comment]
Thank you for the game data.  Fix incoming.
