### ISSUE TITLE
1822MX bug

### ISSUE THREAD

**Issue by herrailu** [tobymao/18xx#7737]
https://18xx.games/game/83518?action=22

Game couldn't proceed after $235 bidding in Concession bidding.

**Comment by herrailu** [comment]
Hmm. We proceeded from the current state of the game successfully and played few turns after that but now it shows at the lobby screen that it is not my (Ilzu) turn but when i get into the game it shows that it is my turn and cannot proceed because of the report. I also cannot write anything to the log/chat box. It feels like the game somehow found out later that something went wrong and rewinded back to this crashed situation. I think we played correctly and i for example didn’t try to bid over three times at that turn. I am sorry that i cannot give anything more detailed feedback because i cannot investigate the log after my $125 bidding for MINOR 13 which obviously happened before the faulty 235 bidding. Lets hope this will get solved:)

**Comment by outsidePasser** [comment]
Ah!  There was a bug where everyone started with too much cash.  That has now been fixed.  You started this game before that fix was rolled out.  In a 3-player game, each player starts with $500.  Ilzu has spent $100 on an NdeM share and has outstanding bids of $125 on M13 and $60 on P1, total of $285.  You don't have $235 left to spend on bidding for the FCM.  

This game should be ended, and this bug should be closed.

**Comment by herrailu** [comment]
Great! How can I end this game because it won’t accept any commands due to bug? I tried to end it via tools-> end game but it doesn’t allow it.

**Comment by outsidePasser** [comment]
I cannot end the game, but I can find someone who can.

**Comment by outsidePasser** [comment]
Dup of #7723

**Comment by dfannius** [comment]
It looks like the game has been deleted.
