### ISSUE TITLE
1846 Mail Contract assigned wrong, I think

### ISSUE THREAD

**Issue by svenn71** [tobymao/18xx#7744]
**What's your Game ID?**
https://18xx.games/game/82060

Look at the assignment of mail contract which will reduce the total revenue from expected 400 to 370

![image](https://user-images.githubusercontent.com/1207110/167929925-94b15d46-9f1b-4835-a338-7da9da5d7ef1.png)

Adding Cincinnati swaps the mail contract to the 3/5 train and total revenue goes down
![image](https://user-images.githubusercontent.com/1207110/167930184-f3f1d87c-c2b5-433c-83bc-e5949a61f4b3.png)

I think the 4 train should keep the mail contract and give 220 revenue and the 3/5 train should have G21-F20-E17-(G13)-(H12) giving 70 + 60 + 50 = 180

Then the actual result should be 220 + 180 = 400

Or is there some rule about the mail contract must be assigned to the longest running train or something else I haven't understood?

**Comment by dfannius** [comment]
The route G21-F20-E17-(G13)-(H12) that you propose has a revenue of 70 + 10 + 60 = 140. The cities without parentheses are the ones that are counted.

**Comment by dfannius** [comment]
Perhaps you are forgetting the rule that at least one of the three cities in a 3/5 train's route must have the corporation's token on it?

**Comment by svenn71** [comment]
> Perhaps you are forgetting the rule that at least one of the three cities in a 3/5 train's route that count for revenue must have the corporation's token on it?

Ok, my bad. First time I play with N/M trains. Thanks a lot for pointing that out.
