### ISSUE TITLE
1822MX - Forced train purchase fails with Pullman in boneyard

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#7746]
https://18xx.games/hotseat/hs_twqzyzsd_1652263653

1822MX - In a hotseat game I had an issue where the same company wound up with both Pullman trains and one had to be discarded.  It went into the boneyard and was available for purchase for $0

The game indicated $0 was not a valid purchase price and would not let anyone purchase the Pullman

Forced train purchases resulted in the player being told they could not purchase a regular numbered train because a cheaper train (the pullman) was available

https://18xx.games/hotseat/hs_twqzyzsd_1652263653
https://gist.github.com/ScottDrone/39def40555cc68272f17419e27d70b47

A separate issue that popped up is that both IRM and FCM destinated at Veracruz (N28 I believe) while 19 was open and had a token there.  When 19 closed the owner chose to receive an exchange token instead of replacing the 19 station.  This resulted in the city having a 3rd open station slot that could be filled by anyone with a station.  I don't think this is expected behavior.

I still have the hotseat game open if I copied the link wrong... not sure at all if I have done this right.

Thanks for all you do with 18xx!!

**Comment by outsidePasser** [comment]
Excellent bug report.  I can recreate both issues and am working fixes.

**Comment by outsidePasser** [comment]
First issue (Pullmans should not go to the boneyard) is fixed and deployed.  Second issue is still being worked.
