### ISSUE TITLE
1822MX can’t upgrade L to a 2

### ISSUE THREAD

**Issue by PeteC66** [tobymao/18xx#7748]
Was unable to upgrade an L to a 2 in game 83699.  5/12/22, roughly 12:06 time.  Was M6.  The minor got to $80 because I had assigned a private company paying $10 at the beginning of the SR, otherwise I would have been short.  Other minors were able to upgrade Ls to 2s with no problem.

**Comment by dfannius** [comment]
https://18xx.games/game/83699?action=310, I assume. FWIW, when I proceed in hotseat from that point I can upgrade the L to a 2.

**Comment by outsidePasser** [comment]
This problem is caused by the server not giving a discount for builder cubes.  According to the server, M6 did not have the money to flip the train.  

Dup of #7728.
