### ISSUE TITLE
1846: Autopass not disabled after the sale of a share

### ISSUE THREAD

**Issue by santouryuu3** [tobymao/18xx#7757]
Game link https://18xx.games/game/83367 

Not upset by the continued autopass, but wanted to report in case of a future problem for others

**Comment by philcampeau** [comment]
Went through the full game log, autopass was disabled after every sale.
Given that the issue hasn't reproduced elsewhere in months, unless you can point to exactly where it happened in this game I'll assume it was a misunderstanding.
