### ISSUE TITLE
NY Bug

### ISSUE THREAD

**Issue by mzylinski21** [tobymao/18xx#7758]
**What's your Game ID?**Id: 63509

 Game wont load

Please include screenshots (you can drag and drop or upload them into this issue)
![image](https://user-images.githubusercontent.com/105517930/168374005-661b8280-b5d2-4ec8-9bbf-fe46f080b231.png)

 All Platfomrs

**Comment by crericha** [comment]
The bug has been fixed already, but since this game is pinned, there isn't anyone to apply the fix. I will delete the game.
