### ISSUE TITLE
unable to pass after floating third company

### ISSUE THREAD

**Issue by ddholstad** [tobymao/18xx#7771]
In round 7 cant pass after floating FNM (third company that round). undefined method locations remove_reservation for nil

https://18xx.games/game/84217

**Comment by outsidePasser** [comment]
This problem is because the city for M16 changed when the tile it is on merged cities.  Working on a solution.

          city = hex_by_id(corporation.coordinates).tile.cities[corporation.city] 
          city.remove_reservation!(corporation)

**Comment by outsidePasser** [comment]
Problem fixed, however, other fixes have broken this game due to the Mail Contract payout being fixed.  Game 84217 will have to be deleted.

**Comment by ddholstad** [comment]
Thanks for your quick response. I will ask Eric_Tama to delete the game.
