### ISSUE TITLE
1822MX: Ferry connections missing from map

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#7781]
The dashed ferry connection lines to Baja California per rule 6.4.7 are not on the map.

You might also want to check if these connections (for minor acquisition) have been coded (i.e. is it just a map oversight)

**Comment by outsidePasser** [comment]
The connections have been coded.  It is just a map oversight, because nothing exists yet to make these lines easily.

**Comment by outsidePasser** [comment]
Anchor icons are being added to the map to signify the connections instead of the dashed lines.  Note added to wiki
