### ISSUE TITLE
Add a filter on the lists of "New Games" and "Active Games"

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7782]
I'd like to be able to find all games of 18GB (or any other title) either in progress or waiting to be played.  Could we have a filter on the 18xx.games home page?

**Comment by scottredracecar** [comment]
This is already implemented. Scroll all the way down to the bottom of the homepage.

**Comment by slapphappyjazz** [comment]
Cool!  Thanks.
