### ISSUE TITLE
1846

### ISSUE THREAD

**Issue by santouryuu3** [tobymao/18xx#7784]
In game https://18xx.games/game/83970 Big 4 was auto selected at the end of the draft following a pass by the previous person

**Comment by crericha** [comment]
The value of the Big 4 was down to $0, so you were forced to buy it and pay the debt. The designer has confirmed this is correct behavior. Please see #2610 for more information.

**Comment by santouryuu3** [comment]
Thank you! I was thinking it was just the price hitting zero, but this makes sense!
