### ISSUE TITLE
[1822MX] Except possibly in its final operation, the NdeM runs last in each operating round.

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#7786]
Seem the order follow stock price now

**Comment by familiar-hk** [comment]
maybe just my old hotseat file

**Comment by familiar-hk** [comment]
[hs_rlruzqrm_1652241896 .zip](https://github.com/tobymao/18xx/files/8710312/hs_rlruzqrm_1652241896.zip)

**Comment by outsidePasser** [comment]
The problem is if someone has to sell shares to emergency fund raise for a train, the companies are re-ordered for that OR.  This re-ordering is done incorrectly.  Fix in progress.

**Comment by fanman80** [comment]
The NdeM is running in stock price order rather than last in game #84663.  https://18xx.games/game/84663

The NdeM was first major to operate in OR6.1 in this game.  It also had the highest stock price then.

**Comment by fanman80** [comment]
In operating rounds 6.2 & 7.1, the NdeM operated last as it is supposed to.
