### ISSUE TITLE
[Harzbahn 1873] Game stuck in loading loop forever

### ISSUE THREAD

**Issue by emknell** [tobymao/18xx#7787]
Hi,

Game 78782 won't load - it just sits in "Loading game..." forever.  Is there any way to rescue this game?

Thanks,
Eric

https://18xx.games/game/78782

**Comment by roseundy** [comment]
Yes. We just need to deploy.

**Comment by roseundy** [comment]
I take that back. This is a new bug.

**Comment by roseundy** [comment]
This was broken by @ventusignis in https://github.com/tobymao/18xx/pull/7564

Fix is on the way.

**Comment by roseundy** [comment]
Your game will be rescued once the fix is deployed.

**Comment by emknell** [comment]
Wonderful - thanks!
