### ISSUE TITLE
[1822MX] NDEM cant run two L train in Mexico City (different station)

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#7789]
NDEM get both minor 14 & 15, so it gets 2 station in Mexico City.
But it cannot run two L train at different station.
Is it a bug?

**Comment by familiar-hk** [comment]
From the rules
6.5.3 Only one L-train may operate on each station token.

So probably it is a bug?

**Comment by outsidePasser** [comment]
Same hotseat game as before?

**Comment by familiar-hk** [comment]
[hs_hoeapnaw_1652806893.zip](https://github.com/tobymao/18xx/files/8714437/hs_hoeapnaw_1652806893.zip)

**Comment by familiar-hk** [comment]
another hotseat game

**Comment by outsidePasser** [comment]
Base 1822 assumes that L-trains running in the same hex are running from the same city and prevents them.  Fix in progress.
