### ISSUE TITLE
[1822MX] Broken Game 83499

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#7792]
Received this message:

We're sorry this game cannot be continued due to GameError: Cannot lay a builder cube now
Broken action: { "type": "lay_tile", "entity": "9", "entity_type": "corporation", "id": 223, "created_at": 1652658493, "hex": "H11", "tile": "BC-0", "rotation": 0 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/83499?action=222)

**Comment by dfannius** [comment]
I assume this is due to a fix and the game has to be deleted.

**Comment by outsidePasser** [comment]
That is correct.

**Comment by fanman80** [comment]
Could somebody please close the game?
