### ISSUE TITLE
1822 minor 20 connectivity  bug - through Merthyr Tydfil and Pontypool

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#7799]
https://18xx.games/game/79306?action=1309

I was running the LNWR and the game offered me the 20 to buy in after running trains.  As I did it I double checked the city values to decide about the token and noticed that it is not connected except through MT&P which is not supposed to be sufficient for connecting to roll in.
Thank you for all you do!!!
Jen

**Comment by michaeljb** [comment]
Dup of #10524
