### ISSUE TITLE
1822MX: Extra Tile Lay Private does not allow laying of builder cubes

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#7804]
https://18xx.games/game/84855?action=688

(I undid the actions, so it might require some redos or manual input to replicate)

Minor 19 (and FCM later, just to double-check) acquired the Extra Tile Lay private but was unable to use it to lay builder cubes. Only tile lays showed up when a hex was clicked.

**Comment by scottredracecar** [comment]
I think that should be allowed as cube lays replace a yellow tile build
action.
