### ISSUE TITLE
1822MX: Turn Order Bar is Orange for all Players in Token Auction

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#7806]
https://18xx.games/game/84855?action=973

In the NdeM token auction, the top bar was orange for all players throughout the entirety of the auction. It confused our poor little brains.

**Comment by andypymont** [comment]
I saw the same in game 84867.

In addition to this, you also can’t see on-screen during this token auction or the NDEM tile laying who is the currently acting player. It would be useful if this was visible at the very least as a log entry. (For tile lays there is a log entry after the player lays their tile for the NDEM but it would be better if it was just before each player’s opportunity to lay track.)
