### ISSUE TITLE
1889 - can't use Dougo last turn in SR1

### ISSUE THREAD

**Issue by raynmanas** [tobymao/18xx#7811]
in SR1, if you don't exchange the Dougo private before you run low on cash, the game autopasses you due to no valid actions.  but exchanging dougo should be considered a valid action.  also not sure if this is an issue in other titles with an exchange private?

not a big deal under almost all circumstances, but happened to a newbie player i am introducing to the site and we didnt realize until we already finished OR1.

**Comment by tobymao** [comment]
no plans to fix this as you can exchange on someone else’s turn
