### ISSUE TITLE
1822MX: Mexico City adjoining hexes rule not properly enforced

### ISSUE THREAD

**Issue by Bastwood** [tobymao/18xx#7812]
https://18xx.games/game/84867?action=541#map

In the game above, a double dit tile in hex M22 is being laid in a way that doesn't connect the station of (director/concession-less) Mexican Central Railway (MC) to existing track.

Rulebook, 6.9.2 states that _"If the company that controls such a hex
has no director or concession holder, then a tile may only be laid if it connects the associated Mexico City station to existing track."_

**Comment by outsidePasser** [comment]
I do not believe this is the intention of this rule.  @scottredracecar to confirm.  Before the tile is placed on M22, the map looks like this:

![image](https://user-images.githubusercontent.com/11219077/170037243-641be717-e529-417d-9da0-b9f52670f91c.png)

And after it looks like this:

![image](https://user-images.githubusercontent.com/11219077/170037409-1a1cb6d3-fbe3-4caa-9798-1e54fafab917.png)

The game does enforce that the stub coming out of MC is connected to the new tile.

**Comment by scottredracecar** [comment]
I think it is okay to lay the tile like that. This was discussed in playtesting a bit. The main purpose of that rule is that the MC home (in this example) does not get permanently blocked from any possible track by placing a blank side facing its track stub.
