### ISSUE TITLE
Game state not fully reset after GameError for the player taking the illegal action

### ISSUE THREAD

**Issue by RockCartel** [tobymao/18xx#7813]
https://18xx.games/game/84989
Was placing a token in NY. It said the cost was $80 and failed
Placed a token in Albany and it worked but the game hung and now won't load
We have stopped playing the game, so don't need it recovered or working

**Comment by crericha** [comment]
If a GameError happens, then the player takes another action, that second action does not have auto actions applied.

It doesn't seem like the local client, for the player taking the illegal action, is completely reset to the state before the GameError.

**Comment by RockCartel** [comment]
Is it possible to delete game 84989 ?
https://18xx.games/game/84989

**Comment by crericha** [comment]
This is the only way to reproduce right now. Bear with me while I fix the root issue, so it doesn't happen again. I will delete the game after that.

**Comment by RockCartel** [comment]
Al good. If you need the game to work on take as long as you need.

**Comment by crericha** [comment]
Thank you. Appreciated!

**Comment by crericha** [comment]
@RockCartel, the game has been restored to just before it broke. You can continue or manually end the game.

**Comment by dfannius** [comment]
@crericha Can this be closed now or should it stay open?
