### ISSUE TITLE
[1893] Cannot buy Bond

### ISSUE THREAD

**Issue by tomdeakin** [tobymao/18xx#7819]
**What's your Game ID?**
84747

https://18xx.games/game/84747

[Game data](https://gist.github.com/tomdeakin/2f0be4b9afddf0c30ea6d7d37205abb4)

**How to Reproduce the Bug?**

In my turn, I cannot buy a Bond. When I click, the "charter" turns blue, but doesn't show the buy button.

<img width="379" alt="Screenshot 2022-05-24 at 09 57 10" src="https://user-images.githubusercontent.com/1379598/169992702-2bb58f69-8cf9-4b34-9114-d7c1865c0cd9.png">

Please include screenshots (you can drag and drop or upload them into this issue)
**Which Browser / Platform?**
- Browser Version
  - On Chrome, see 101.0.4951.64 (Official Build) (arm64)
  - On Safari, Desktop Version 15.5 (17613.2.7.1.8)
- Platform all

**Comment by dfannius** [comment]
https://18xx.games/game/84747?action=360
