### ISSUE TITLE
Ability to search for game type/user (New Feature for the site)

### ISSUE THREAD

**Issue by HarderCorer** [tobymao/18xx#782]
I would like to request the ability to search/filter games by user or game.  Both would be very helpful in joining new games and to review old games.

**Comment by jenf** [comment]
I'd like to be able to search for games generally e.g. 1889 games involving the word TGG1 also search users and point in the game 'Stock 1'

**Comment by HarderCorer** [comment]
Related to this, when creating a new game, maybe have a checklist of common tags people include also for searching.  E.g. Private, Fast Play, Beginner Friendly

**Comment by yzemaze** [comment]
Filtering by at least game title (and private/password set) will become a necessity pretty soon to find games to join.

A variable number of filters and the possibility to combine them with operators would be the way to go. For starters a simple filter category dropdown + field for value might be better than nothing.

**Comment by magnusrk-ch** [comment]
#6473 adds a way to filter by title.

**Comment by tobymao** [comment]
solved for better or worse by #6473
