### ISSUE TITLE
[18NY v2] Can't take loans after salvaging last train

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#7825]
https://gist.github.com/l33twash0r/e984b93cd502a786793eacd44bc235ee

**What's your Game ID?**
https://18xx.games/game/85175

After NYC salvaged it's last train it should be able to take loans as EMR steps allow, but there is no take loans button available.

**Comment by crericha** [comment]
"While a Company may salvage a train to make room to buy another one, it may not voluntarily salvage its last train unless it will be able to buy another one without taking loans or undergoing Emergency Money Raising."

**Comment by l33twash0r** [comment]
Should the salvage train be hidden when it's the last train company has?

**Comment by crericha** [comment]
You can salvage and then buy a train (from another company, the bank pool, or the bank), so it is valid to salvage your last train.
