### ISSUE TITLE
[18NY v2] NYC wrong token price on charter

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#7826]
https://gist.github.com/l33twash0r/e984b93cd502a786793eacd44bc235ee

What's your Game ID?
https://18xx.games/game/85175

NYC charter shows the token price as '20', but when trying to lay tokens with less than 80 money you will get an error about not having enough money.

**Comment by crericha** [comment]
Its $20/hex. This is the standard way that per hex token costs are shown for all 18xx.games games.
