### ISSUE TITLE
Incorrect revenue for route from Cleveland to Holland

### ISSUE THREAD

**Issue by Eyswein** [tobymao/18xx#7829]
https://18xx.games/game/83982

In OR 2.1 and 2.2 PRR during phase 2 ran a 3/5 train from Cleveland(50)-Toledo(30)-Detroit(50)-Holland(40) and received a 130 value instead of 140.

**Comment by dfannius** [comment]
The implementation is correct. At least one of the N stops in an N/M train needs to have a token in it, so you need to use Toledo.
