### ISSUE TITLE
Ability to direct message other players

### ISSUE THREAD

**Issue by HarderCorer** [tobymao/18xx#783]
Chat messages can sometimes be missed if in game if a lot happens between a player's turn.  Having a separate box in games just for player communication or a way to directly message another player would be helpful.

**Comment by jenf** [comment]
hidden messages to other users would be frowned upon generally

**Comment by tobymao** [comment]
you can already do this with @playername message

**Comment by playername** [comment]
What

**Comment by tobymao** [comment]
sorry, didn't mean to message you

**Comment by playername** [comment]
It's ok
