### ISSUE TITLE
[1866] player cannot pass IAR action

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#7830]
In https://18xx.games/game/85038 player HerbalTea cannot Pass on the minor being auctioned. The option to pass is shown, but clicking it doesn't pass. I also cannot pass for them in Master Mode.

I don't think this is the consequence of some edge case in the rules that doesn't permit it, both because I can't find one and because there's a chunk of error spew in the browser console:

Uncaught InternalError: too much recursion
    a https://18xx.games/assets/deps.js:15
    Opal.modules["engine/game/base"]/< https://18xx.games/assets/main.js:1
    Opal.modules["engine/game/base"]/< https://18xx.games/assets/main.js:1
    Opal.modules["engine/round/base"]/< https://18xx.games/assets/main.js:2
    Opal.modules["engine/game/g_1866/step/single_item_auction"]/< https://18xx.games/assets/g_1866.js:1
    Opal.modules["engine/game/g_1866/step/single_item_auction"]/< https://18xx.games/assets/g_1866.js:1
    Opal.modules["engine/game/g_1866/step/single_item_auction"]/< https://18xx.games/assets/g_1866.js:1
    Opal.modules["engine/game/g_1866/step/single_item_auction"]/< https://18xx.games/assets/g_1866.js:1
    Opal.modules["engine/game/g_1866/step/single_item_auction"]/< https://18xx.games/assets/g_1866.js:1
    Opal.modules["engine/game/g_1866/step/single_item_auction"]/< https://18xx.games/assets/g_1866.js:1

I am using Firefox 100.2 on Windows 7 (yes, I know; no, it isn't). I don't know what HerbalTea is using.

**Comment by damerell** [comment]
I didn't (intentionally, anyway) add that label but perhaps it happens automagically.

**Comment by magnusstjarnhild** [comment]
You can continue your game as soon as the fix is deployed to live.

**Comment by damerell** [comment]
Thanks.
