### ISSUE TITLE
1856 Seahorse Laser Design has not published 1856

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7831]
Seahorse Laser Design purchased the rights to 1856, but has not published it. I don't think they should be listed as the publisher, and certainly not with a link to their Etsy shop that doesn't have any 1856 content at all.

**Comment by tobymao** [comment]
@ChrisTheCat can you just change it then? i'm going to close this issue, but will incorporate your fix https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1856/meta.rb#L19

**Comment by ChrisTheCat** [comment]
I wasn't sure if you would agree, so didn't want to arbitrarily make the change.

I can change the wiki, I assume your fix will change the Info tab?

**Comment by tobymao** [comment]
i don't care, you can be the decision maker on this. i'm proposing you change both the wiki and make the PR to change the meta which will change the info tab

**Comment by ChrisTheCat** [comment]
ok, will do
