### ISSUE TITLE
Using autorouter doesn't update selected_route in UI::RouteSelector

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#7843]
**What's your Game ID?**

https://18xx.games/game/85075

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
- During OR5.2 the FYN tries to run its 4+2-train. 
- The auto tool gives a suboptimal route.
- Trying to create the desired route manually doesn't work.

**Which Browser / Platform?**
- On Firefox
- Platform: Desktop

**Comment by roseundy** [comment]
Not sure how well 1860 will ever be supported by autorouting.

**Comment by KlausKiermeier** [comment]
The problem is not so much that autorouting delivered a suboptimal route, but that afterwards I was unable to define a route manually at all.

**Comment by benjaminxscott** [comment]
Did you hit `Clear All` after the attempted autoroute?

**Comment by KlausKiermeier** [comment]
Yes, I did.

**Comment by dfannius** [comment]
What happened exactly? You clicked on a hex to define the beginning of a route and the site did not react?

**Comment by KlausKiermeier** [comment]
I tried "Clear Train" as well as "Clear All". Where, by the way, the FYN had only one train. So, "Clear Train" should have worked in any case.

**Comment by KlausKiermeier** [comment]
@dfannius 
Yes, I clicked on the home hex to define the beginning of a route and the site did not react.
And I tried this a couple of times.

**Comment by dfannius** [comment]
Thanks. A couple more questions:

- What happens if you refresh the whole page and try again?
- What happens if you clone the game and try to run a route in hotseat mode? (This worked for me.)

**Comment by dfannius** [comment]
I'm removing the autorouting label because we know that autorouting doesn't work for 1860 and that's a separate issue from the interesting thing here.

**Comment by KlausKiermeier** [comment]
I just refreshed the site, and then I was actually able to trace the desired route manually.
:-)

**Comment by dfannius** [comment]
OK, good. I admit that this has happened to me occasionally in the past, and I always just refresh the page and continue and don't bother to report it. We should probably make an issue about it, although I'm not sure this is the one for it. Unfortunately the problem is hard to duplicate by its nature.

**Comment by KlausKiermeier** [comment]
Nevertheless, the "Clear Train" and "Clear All" buttons did not work properly, which I recognised before but was every time somehow able to circumvent this non-functioning.

**Comment by dfannius** [comment]
Sorry to keep interrogating you, but what do you mean when you say that Clear Train and Clear All did not work properly? Did they not clear the current route? Or do you just mean that you weren't able to create a route afterwards?

**Comment by KlausKiermeier** [comment]
After having tried autorouting, the route created by autorouting could not be cleared by "Clear Train". 
But "Clear All" did clear the the route delivered by autorouting. Nevertheles, since only one train was involved, "Clear Train" should have been working.

Sorry for having been not precise.

**Comment by roseundy** [comment]
I was definitely able to reproduce this in hotseat. No idea how it got into this state.

**Comment by roseundy** [comment]
The solution may be to remove the Autoroute button entirely from 1860

**Comment by KlausKiermeier** [comment]
Hi Steve,

I think you are right. This would be the best solution.

Actually, I have not the slightest idea how autorouting is programmed (and I'm no programmer either), but I can imagine that it is particularly difficult to get the maximum revenue via autorouting with the rule that a maximum of one blocked station may be run through, at least in the case that a company has more than one train.

Klaus
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [1860] Was not able to trace a route (Issue #7843)
Datum: 2022-07-13T17:44:27+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
The solution may be to remove the Autoroute button entirely from 1860
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/7843#issuecomment-1183386056", "url": "https://github.com/tobymao/18xx/issues/7843#issuecomment-1183386056", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿

**Comment by roseundy** [comment]
Investigating further shows that the problem is that the "Autoroute" button doesn't update `@selected_route` in RouteSelector even though it completely overwrites `@routes`

This is NOT specific to 1860. Updating `@selected_route` after calling the auto-router fixes this issue.
