### ISSUE TITLE
1822MX - NdeM Operated out of order.  Game continued OK until it broke.

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#7849]
https://18xx.games/game/85728?action=555

NdeM operated here at the incorrect time after the Minors before the Majors in the wrong location.  We actually were able to play the end of OR 6.2, SR7, and the Minors of 7.1 OK until the first Major started to run (laid a track, started to pay out and then gave the broken error).

Retroactively, it now looks like the NdeM operates when it should.  But when we were playing it, we did it's actions first before the majors.

**Comment by jerryyeti** [comment]
OK, and retroactively, it now looks like the NdeM operates when it should.  But when we were playing it, we did it's actions first before the majors.

**Comment by jerryyeti** [comment]
Nevermind. Closed. Looks like there was a fix that broke them game. (I thought I was hallucinating opening the prev report it was closed so fast).

https://github.com/tobymao/18xx/issues/7848

**Comment by outsidePasser** [comment]
Sorry about that.  I'll be slower next time. ;)

The wrong order was one of the things that was fixed in the latest rollout.
