### ISSUE TITLE
[1822MX] Game got broken during NDeM privatization

### ISSUE THREAD

**Issue by darkbtf** [tobymao/18xx#7854]
**What's your Game ID?**
https://18xx.games/game/85524?action=794

**How to Reproduce the Bug?**

- During Operating Round 8.1 (of 2) - NDEM Privatization
- After 3 token got bought, the game was stuck and players can't even enter the game by the link https://18xx.games/game/85524

**Which Browser / Platform?**
Not a client issue

**Comment by outsidePasser** [comment]
This game was broken by the fix for NDEM operating order (PR #7845) and must be deleted.

**Comment by darkbtf** [comment]
Hi @outsidePasser,

could you pls remove game [85524](https://18xx.games/game/85524) for us?
