### ISSUE TITLE
[22MX] p8 not working

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#7865]
https://18xx.games/game/84661

IRM cannot use p8 for some reason.

![4D79F22D-DE0D-47A2-AAE5-5E57C1699284](https://user-images.githubusercontent.com/73144084/171511021-6281aae7-2d07-416d-a6d9-ac4a7dd91568.png)

**Comment by ChrisTheCat** [comment]
Appears to me it's happening at this action https://18xx.games/game/84661?action=896

I cloned the game, acquired the P8 with IRM, and verified that using the private action it does not allow laying the brown tile.

**Comment by outsidePasser** [comment]
This was broken by refactoring to use 22MX tracker.

**Comment by philcampeau** [comment]
Also happening here: https://18xx.games/game/86208?action=492
