### ISSUE TITLE
1822MX port replaced by port

### ISSUE THREAD

**Issue by magnissimus** [tobymao/18xx#7872]
The game allows replacing small port with large port (don’t know if it allows it the other way around) 
https://18xx.games/game/85444?action=717

This is not allowed.
![C76D7CFA-87E5-41E1-B13F-C9822A56A05D](https://user-images.githubusercontent.com/106030682/171713748-8c6e1368-ffe2-441a-a464-31e88ad5d5d1.jpeg)

**Comment by outsidePasser** [comment]
I'm quite sure it allows it the other way around too...
