### ISSUE TITLE
1822MX - Major can't acquire Minor

### ISSUE THREAD

**Issue by BranislavBerec** [tobymao/18xx#7883]
Major FCM can't acquire Minor 18.
Game ID: 84133
Looking at the rules all the requirements for the acquisition have been met - it's the second OR for FCM, 18 has been already running for a while. 

Thanks,
Branislav

**Comment by crericha** [comment]
Minor 18's market value is $150, so FCM needs to contribute $300 to execute the merger. 2 shares of FCM ($70 each) and its $59 in cash is only $199, which is not enough.
