### ISSUE TITLE
Grand Junction and Grand River Valley Railroad bug

### ISSUE THREAD

**Issue by drobinder** [tobymao/18xx#7888]
I was unable to use this ability to upgrade a yellow city to a green in South Park. The town had been connected during this same turn by placing a yellow tile in E14, but the ability should work even if it's not connected.

**Comment by drobinder** [comment]
Sorry, yes this was an 18CO game. I didn't get the state of the game at the time, so I'm not sure how to tell you how to recreate the issue.

**Comment by philcampeau** [comment]
Since we don't have the game info, or the log, I'll close this. If the issue occurs again a new report with more info can be submitted.
