### ISSUE TITLE
Access rules via invite card

### ISSUE THREAD

**Issue by berv63** [tobymao/18xx#7889]
**What's your idea?**

Sometimes when waiting for a game to start it's good to get to know the rules a bit better. It would be nice if the info tab was accessible from the invite card or some master list of game rules to be able to read through them at my own leisure.

**Are there related ideas?**

No related ideas. However there is a workaround. I can create a dummy game with just myself to access the info tab.

**Did you join the Slack?**

No

**Comment by berv63** [comment]
I see there is a link that relates to the game when creating the game. Something like this should be relatively easy using the same relation logic.

![image](https://user-images.githubusercontent.com/4182782/172455391-c399685a-0100-4ffa-b3b7-b57802499fb7.png)

**Comment by tobymao** [comment]
Thanks for the suggestion but we probably won't implement this. You can just go to an existing game and look at the rules there.
