### ISSUE TITLE
[1867] discount for trade-in trains is 50%, should be 25%

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#7890]
Game ID:
https://18xx.games/game/84802

When CPR came to buy trains in OR5.2, it was offered an upgrade of a 5 to a 2+2 for $325, for example. This is $375 discount i.e. 50%, but the AAG rules say 25%. (This rule is missing from the GTG rulebook.)

**Comment by Maxwell-Frank** [comment]
@ianwilson156 You should get a discount of $275 for your 5T (50% of the old train cost, which was $550).  $600 (the cost of a 2+2) - $275 = $325

**Comment by ianwilson156** [comment]
Sorry, getting confused between 1867 & 1812 rules - it should be 50% in 1867.

**Comment by ianwilson156** [comment]
My mistake, apologies.
