### ISSUE TITLE
Destination tokens do not support simplified logos

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7891]
Trying out 1822MX. When I toggle simplified logos it is still very hard to make out what some of the tokens are. Is it possible to improve?

![image](https://user-images.githubusercontent.com/2631151/172637465-ddf23928-72d1-4070-8560-3a94aa5e88a4.png)

**Comment by crericha** [comment]
Destination tokens in all games do not support simplified logos.

**Comment by andrewzwicky** [comment]
This can get the 18JP-T label if that matters.  I think the 1822 stuff will benefit from someone more familiar with those games, I'm not sure how the destination tokens work and because those games don't have simplified logos yet, that's probably the first step.
