### ISSUE TITLE
The game of 18NY - 84929 seems to have frozen.  All the players get the "Loading game..." screen and no further action.

### ISSUE THREAD

**Issue by charliewilsonstaindrop** [tobymao/18xx#7893]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by charliewilsonstaindrop** [comment]
I am not sure how to fill this form in correctly - sorry.

The (Multiplayer) game ID is https://18xx.games/game/84929.

I have no idea what triggered the problem so cannot reproduce the bug.

It is affecting all players irrespective of browser/platform so I would expect Safari, Edge at least on laptops, smartphones, tablets.

Hope that this helps.

**Comment by roseundy** [comment]
It's getting a NotImplementedError for re

backtrace: Array(10)
0: "https://18xx.games/assets/deps.js:1:18715:in `m.send2'"
1: "https://18xx.games/assets/deps.js:1:18534:in `m.send'"
2: "https://18xx.games/assets/deps.js:4:24370:in `Function.<anonymous>'"
3: "https://18xx.games/assets/deps.js:4:18655:in `re.<anonymous>'"
4: "https://18xx.games/assets/main.js:2:321843:in `re.<anonymous>'"
5: "https://18xx.games/assets/main.js:2:253819:in `re.<anonymous>'"
6: "https://18xx.games/assets/main.js:64:85625:in `re.<anonymous>'"
7: "https://18xx.games/assets/main.js:64:88419:in `re.<anonymous>'"
8: "https://18xx.games/assets/main.js:64:77103:in `re.<anonymous>'"
9: "https://18xx.games/assets/deps.js:31:36399:in `re.<anonymous>'"

**Comment by crericha** [comment]
Client side state gets out of sync and adds incorrect auto actions. Since the server doesn't verify the auto actions are valid, the game winds up in a bad state. This is a dup of #7813.

Game state is fixed and the game can continue on.

**Comment by charliewilsonstaindrop** [comment]
Thank you very much for sorting it out. 

All the best
Charlie Wilson
"From the Sea, Freedom."





----- Original Message -----
From: Chris Rericha ***@***.***>
Reply-To: tobymao/18xx 
***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author 
***@***.***>
Sent: 10/06/2022 05:42:33
Subject: Re: [tobymao/18xx] The game of 18NY - 84929 seems to have frozen. All 
the players get the "Loading game..." screen and no further action. (Issue 
#7893)



Client side state gets out of sync and adds incorrect auto actions. Since the 
server doesn't verify the auto actions are valid, the game winds up in a bad state. This is a dup of #7813.
Game state is fixed and the game can continue on.
