### ISSUE TITLE
[1822MX] Failed to auto route for NdM (multiple L-trains)

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7902]
NdM owned 4 L trains, and had 2 tokens, one of them in N25, and no track built besides the two cities.
When I click on auto all 4 L trains fail to find route and all give the same error:
![image](https://user-images.githubusercontent.com/2631151/173156772-d0919be8-864d-47ea-885c-c2a190d00101.png)

Map looked like:
![image](https://user-images.githubusercontent.com/2631151/173156822-ee0ccb51-5bf7-44db-9afc-61ad55d0655d.png)

**Comment by michaeljb** [comment]
https://gist.github.com/michaeljb/0b0b07967e60f301856de9bdfe0f9da5
