### ISSUE TITLE
Brown tile crash in Volatility

### ISSUE THREAD

**Issue by Foxrik** [tobymao/18xx#7908]
https://18xx.games/game/87346?action=878

https://gist.github.com/benjaminxscott/b6d29a1238777ab8940a84d16fb3c7ba

**Comment by Foxrik** [comment]
Tried to brown Toledo (was the Pittsburgh city) and got error message.  Same for any other track attempt.  We abandoned the game.  #??  (it has vanished from the site)

**Comment by Foxrik** [comment]
Game 87346

**Comment by benjaminxscott** [comment]
I wasn't able to repro this in hotseat, fwiw

![image](https://user-images.githubusercontent.com/1711810/173201142-119cb819-24b5-4537-8cb7-d00045762651.png)

**Comment by Foxrik** [comment]
Huh, thanks.  We went through full reboot, master mode, tried laying multiple different tiles and got an error every time

Chief Quality Officer, US Anesthesia Partners




Richard Dutton

Chief Quality Officer

O: 972-776-3132<tel:972-776-3132>

***@***.******@***.***>

www.USAP.com<http://www.USAP.com>

[cid:33457fa725e7c020be43c00c7c0a4b72904efeb4] <http://www.USAP.com>

[cid:69fdb15eebef9c189c3c6c730fa987f676c7f466] <https://www.linkedin.com/company/us-anesthesia-partners>

[cid:4102b6145dc8c5d363932ab5fc6e25f234d6b20c] <https://www.facebook.com/usanesthesiapartners/>

[cid:ae85a7520c93b456077998651edd34fd0522ffc4] <https://twitter.com/usap_updates>

________________________________

**Comment by crericha** [comment]
The server thinks UR should run before H.
