### ISSUE TITLE
Show who is doing the NdM action

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7909]
It is hard to tell who should be doing the NdM action in 1822MX. Could one write this in the log, maybe? As it is now no one knows who is to build, or run trains, but when the player who's turn it is makes the order it appears in the log.

**Comment by dfannius** [comment]
I think the log is totally the place to do things like this (see 817553c22503fcc3b3fe165a0fd839e8abca8210 for an example of a similar issue).

**Comment by perwestling** [comment]
It would be preferable if active player was shown in a clear way.
But as a minimum writing in log something like as soon as it is NdM's turn:

**NdM to do build actions, followed by train operation.**
- Player 1 will do 1 yellow/cube for NdM.
- Player 3 will do 1 yellow/cube for NdM.
- Then Player 1 will run the NdM trains.
