### ISSUE TITLE
1830: GameError: An entity cannot buy a train from itself

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#7915]
We're sorry this game cannot be continued due to GameError: An entity cannot buy a train from itself
Broken action: { "type": "buy_train", "entity": "NYNH", "entity_type": "corporation", "id": 70, "created_at": 1652172226, "train": "2-1", "price": 80, "variant": "2" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/82566?action=69)

**Comment by tobymao** [comment]
archived

**Comment by dagibbs** [comment]
This game would have been created on or around  2022-05-02 (May 5th) as part of the league -- it can't be an action that was taken 4 months ago.

**Comment by dfannius** [comment]
Despite the title of the bug that this is a duplicate of, the bug is not about four-month-old actions, it's about corporations managing to buy trains from themselves, which apparently somehow happened in this game.

**Comment by heliopolix** [comment]
Yeah, my game was the one in #7916. We'd been playing for months, when it suddenly bugged and reported an action taken months ago as the reason the game was now invalid.
