### ISSUE TITLE
1870: Game 84674 "Cannot buy a train from itself" error

### ISSUE THREAD

**Issue by tgg18xx** [tobymao/18xx#7917]
We're sorry this game cannot be continued due to GameError: An entity cannot buy a train from itself
Broken action: { "type": "buy_train", "entity": "MKT", "entity_type": "corporation", "id": 37, "created_at": 1653261811, "train": "2-2", "price": 80, "variant": "2" }

https://18xx.games/game/84674?action=36

**Comment by tobymao** [comment]
dup #7915
