### ISSUE TITLE
Allowing brown tile before brown phase Harzbahn 1873

### ISSUE THREAD

**Issue by mrouser** [tobymao/18xx#7919]
In this game https://18xx.games/game/84404 the HBE was allowed to place the brown tile in Blankenburg before the brown phase.  The game correctly did not let me place other brown tiles.  I left the game in the state after I made the illegal tile placement.

**Comment by roseundy** [comment]
FYI, I've cloned and copied the game. You can continue with your game without the illegal move.

**Comment by roseundy** [comment]
This is part of the convoluted code used to allow a tile that is needed to complete a concession route to be reserved for use later. On one of the paths through this logic, I failed to check to see if the tile was of the correct color.  Interestingly, if the tile had been rotated differently, it would not let you lay it.
