### ISSUE TITLE
21Moon - some privates are not closing when they should

### ISSUE THREAD

**Issue by bggtool** [tobymao/18xx#7928]
https://18xx.games/game/87109

Per the linked rules on the Info page, all privates except P3 close when certain things happen, prior to all privates closing in OR4.1.

In this game P1 correctly closed when it was purchased and P5 correctly closed when the Terminal tile was placed. However, as of https://18xx.games/game/87109?action=258 both P4 and P6 should have closed - P4 has placed its token and P6 has taken a share from the pool - but neither has.

**Comment by roseundy** [comment]
The fix will break most existing games.
