### ISSUE TITLE
Public Profile Pages

### ISSUE THREAD

**Issue by alistaircom** [tobymao/18xx#7929]
For each player in 18xx.Games, a player profile could be generated with a combination of gameplay, system, and user-entered information. This information would give other users a sense of gameplay experience, timezone, last active, and a brief bio statement.

The main UI change would be to turn each username (in chat, game cards, game interfaces) into a clickable link that would take users to their profile. Similarly, in **Active games**, users can click on the game ID or associated username to be taken to that game or profile page. URLs would be friendly, such as: https://18xx.games/profile/alistaircom

**About** and **Timezone** could be options for users to customize in their own profile page. 

A rough example would be:

## Player Profile for alistaircom
**Member since:** 2022-05-15
**Last Active:** 2022-06-15
**Timezone:** -7 UTC (Mountain Standard Time)

### About alistaircom

Ex-pilot, current astronaut, husband, dad. Play 18xx games more than I probably should. 

### Games Played
|Game Title| Number of Plays|Games Won|
|--|:--:|:--:|
|18Chesapeake|8|2|
|Shikoku 1889|4|2|
|18Mex|4|1|
|21Moon|7|3|

### Active Games

|Game ID|Game Title|Owner|
|:--:|--|--|
|[12345]()|18Chesapeake|[alistaircom]()|
|[23456]()|18Mex|[johnsmith]()|
|[34567]()|Shikoku 1889|[bettyrubble]()|

**Comment by tobymao** [comment]
i don’t want to have stats on players

**Comment by alistaircom** [comment]
Are games currently playing and location something you would like to see?

**Comment by tobymao** [comment]
i have no interest in any of this, but i will accept a PR with a nice simple design implementing something like that

**Comment by outsidePasser** [comment]
My opinion is that player pages that have even that information should be opt-in.

**Comment by alistaircom** [comment]
As a new player to the site, I found it very challenging to understand the strength of players, the TZ people are in, or even the games that are likely to run (some games in the new list are months old).

However, it doesn't look like there is any support for the idea, so I'll close it.
