### ISSUE TITLE
[RSS] Use total cash that could be raised in investment phase for liquidity

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#7935]
It'd be more helpful to know the total amount of money a player can raise in the investment phase (given the current game state) than what is currently shown as liquidity, which I believe currently shows amount of cash when not in the investment phase and cash + one share sold when in the investment phase.

**Comment by roseundy** [comment]
Liquidity is going to be only an approximation if you have multiple shares of a corporation since you are only allowed to sell one share at a time. Each sale will drop the price.
