### ISSUE TITLE
[1849] Unexpected change in stock market order

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#7937]
See https://18xx.games/game/87636?action=45

**Situation during Stock Round:**
* AFG share price is L.116, two boxes above the IPO L.100.
* No other companies have been started.
* Player Files sells two shares of AFG, so price drops to L.100 (in the IPO space).
* Player Files floats IFT at L.100.  Marker is put at bottom of the stack per standard 18xx rules.
* Game flips order of IFT and AFG to put IFT on top.

**Log Message:**
> [07:28] Updating operating order for sold (and moved) corporations now on same share value space to maintain relative order before sales.
> [07:28] AFG,IFT --> IFT,AFG

**Issue:**
While 1849 has an unusual rule (that the order of selling shares of multiple companies does not affect share order [Rule 9.2, step 3]), I do not see any special rule relating to starting a new company.
Why was the new company [IFT] placed on top of the company where a share was sold [AFG]?

Compare action 47 of the game (just after this), KevinR floated SFA at L.100 and the token was placed at the bottom of the L.100 stack, as expected.

**Relevant rules excerpts:** (using pdf of AAG mass-printing rules)
Rule 5: "A token that is moved to a space already containing one or more tokens of other corporations is always placed on the bottom of the stack, underneath the tokens already there."
Rule 9.3:  "3. The banker moves the stock market token(s) of the corporation(s) whose stock has been sold one row down for each share sold. **When stock in more than one corporation is sold, the banker moves the stock market token of the corporations whose stock has been sold in current market value order.** This means that if three shares are being sold (in corporations A, B, and C) and they are all on currently the same price (with A on top and C at the bottom of the stack), after the sale the order of the stack remains unchanged."
Rule 9.4:  "After choosing the initial market value, the president puts a stock market token in the appropriate position on the stock market."

**Comment by dfannius** [comment]
I have a PR in to fix this, so if you wait to do anything further until it is accepted and deployed, you will be able to continue the game without the corporations being reordered.

**Comment by epigamic** [comment]
This still seems to be an issue with both 1849 and 1849: Kingdom of the Two Sicilies.
See game https://18xx.games/game/244224?action=320
