### ISSUE TITLE
Display the total revenue at dividend-payment step

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#794]
When deciding to pay or withhold dividends, it would be nice to see the total revenue 
(currently the user has to manually sum up the revenues from each train in the logs)

Perhaps show `Total revenue of $X ($Y per share)` above the buttons

The per-share amount is useful in '46 since stock value is adjusted by per-share revenue, and should also be useful in games with 5-share companies like CZ or Ireland

**Comment by ChrisTheCat** [comment]
+1. The previous button is "Submit [amount]" and it would make sense for the interface to offer "Pay out [amount]" or "Withhold [amount]."

This will be even more useful in games where players are deciding whether to half-pay.

**Comment by jenf** [comment]
covered and improved by #886
