### ISSUE TITLE
[21Moon] Issuing stock gives error

### ISSUE THREAD

**Issue by bc2012** [tobymao/18xx#7941]
**What's your Game ID?**
https://18xx.games/hotseat/hs_gzhnpyyu_1654584996

https://18xx.games/hotseat/hs_gzhnpyyu_1654584996?action=98

A link to your raw game data:
https://gist.github.com/bc2012/6042c92e0d34ac733e3d47cb039a96f5

**How to Reproduce the Bug?**
Corporate Round 2
ME wants to issue 1 x IPO share
Error

**Which Browser / Platform?**
- Browser Version
  - Firefox 101.0
- Platform Desktop, Mac OS 12.3.1
![21Moon_1](https://user-images.githubusercontent.com/2817945/173940580-091e8f0c-e5d2-4e5d-bf85-0ddda6e43c98.jpg)
![21Moon_2](https://user-images.githubusercontent.com/2817945/173940596-06455743-0f8c-4bbe-9b12-ed8702efe455.jpg)

**Comment by roseundy** [comment]
This is an edge case where issuing a share in the corporate round causes the company to close. I didn't have the proper code for this event.

**Comment by bc2012** [comment]
Hmmmm, maybe I have got the rules wrong but ME has 5 shares in the IPO, so should be able to issue 1 to 5 shares.
Issuing shares shouldn’t cause ME to close.


On 16 Jun 2022, at 1:56 pm, Steve ***@***.***> wrote:


This is an edge case where issuing a share in the corporate round causes the company to close. I didn't have the proper code for this event.

**Comment by bc2012** [comment]
Ah, sorry my bad didn't realise where ME's SP was sitting on the stock market.
