### ISSUE TITLE
Colored tokens on start map might be confusing

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#7947]
Here is the start map:
![image](https://user-images.githubusercontent.com/2631151/174230609-8067392a-d4eb-40a7-b46b-bba6ce735b91.png)

I wonder if the green and brown tokens will be confusing? It is not obvious that these will be available at different phases of the game, and not active/blocking before that.

Compare how it looks in 1822MX:
![image](https://user-images.githubusercontent.com/2631151/174230851-80f7b04e-8228-4501-ba3d-5df14c426c57.png)

Light green for minors that will be available in the upcoming/current SR, and the future ones is just shown as black on white. Now future is not known when they will appear by Entities tab will give order.

So maybe there need to be a way to show future corporations without conflicting with existing way of shown active/floated corporations? 
And also, I do not know if color blindness will be a problem?

Some possible ways (but you can probably come up with more):

- Using a very light greenish, brownish color on future tokens
- Maybe use some light color on active non-floated corporations a la 1822MX? (Having it light yellow on the start ones would make it consistent - future ones can continue to be light greenish, brownish.)
- Using a green icon (compare 18Rhl) on the hex just to show this future status
- If using icon brown could be a different size to separate it from green
- Add a dummy ability to future corporations which says "Available in green phase" or something  similar. (This can be done by adding a Base attribute with a suitable description [possible with a long alternative text explaining things] to the corporation during setup. And then the Base attribute can be removed when corporation becomes available.)
- Adding a green/brown icon to corporation charter (do not know if this is possible?)

**Comment by BellmakerSA** [comment]
I don’t find the phases confusing but RF’s color needs to be changed as it’s too close to/the same as the green phase companies
