### ISSUE TITLE
[1860] Stock price not being adjusted after sales of multiple shares for insolvent company in yellow stock area

### ISSUE THREAD

**Issue by ChrisNord** [tobymao/18xx#7948]
https://18xx.games/game/85124

**How to Reproduce the Bug?**
During Stock Round 11 while selling 3 shares of VYSC the stock price of VYSC was not adjusted. 
![image](https://user-images.githubusercontent.com/67314474/174241176-8cfd3a5a-2600-44c4-9364-59b422278efd.png)

Please include screenshots (you can drag and drop or upload them into this issue)
- On Chrome, Version 102.0.5005.115 
- Platform (Desktop)

**Comment by andypymont** [comment]
This game is in phase 9 at the time of selling these shares.

Stock sales from phase 8 onwards do not drop the price: see the phase table on page 7 of the rulebook (which is linked in the Info tab in-game).
