### ISSUE TITLE
[1877 Stockholm Tramways] Indicate on company card which phase they are available for auction

### ISSUE THREAD

**Issue by gloinul** [tobymao/18xx#7949]
**What's your idea?**

In 1877 Stockholm Tramways there are no indication on the company card in which phase the company will be available for auction. To my understanding the only place this is evident is on the map. I would request that one tries to add an indicator on the company card for the phase it becomes available. I think it is especially important on the entities tab, so maybe a listing on available and phases could be an alternative to better indicate when this happens. However, if it can fit on the company card it will be evident also in the case they are shown on the game tab. 

Also the result of the randomization is not written out in the game log, maybe it should?

**Are there related ideas?**

https://github.com/tobymao/18xx/issues/7947

**Did you join the Slack?**

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ) and meet your fellow contributors!

**Comment by lbrande** [comment]
Thanks for the suggestion, this will be fixed with the next update along with #7947.
