### ISSUE TITLE
1849

### ISSUE THREAD

**Issue by jesperpunktkarlsson** [tobymao/18xx#7950]
We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action 258
Broken action: { "type": "pass", "entity": "AFG", "entity_type": "corporation", "id": 258, "created_at": 1654013323 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/84745?action=257)

**Comment by dfannius** [comment]
Seems fine now.
