### ISSUE TITLE
[18ny] Trainless minor can't issue loans if it salvaged train to become trainless

### ISSUE THREAD

**Issue by Picklesgrr** [tobymao/18xx#7955]
**What's your Game ID?**

Missing for now - hot seat and on phone prevent the gist thing working

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

The above locks my phone. I'll update when my pc is here or when it happens in an online game. 

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Being trainless after salvaging a train does not provide the option to take out loans to buy a new one.

**Comment by dfannius** [comment]
Waiting on a gist.

**Comment by Picklesgrr** [comment]
My apologies for wasting time.  It came to light that this was in fact
working correctly.

Pickles

**Comment by dfannius** [comment]
No problem, thanks for the update.
