### ISSUE TITLE
[18usa] On forming TP, corp ends up with $60 too much 

### ISSUE THREAD

**Issue by Anzelak** [tobymao/18xx#7957]
https://18xx.games/game/87554

In this game, TP has ended up with the the oil private giving it $60 incorrectly at formation. I think it should have $40 rather than $100 when it's formed.

**Comment by H1llsman** [comment]
Issue occurred here: https://18xx.games/game/87554?action=116
Issue seems to be related to the P12 Private.
Bid was won at $140
$40 subsidy awarded.

Player Anzelak needs to contribute $100.
Privates: P12 ($60) and P8 ($40) are used to float.

Expected result:
Player Anzelak loses private P12 and P8, spends no money.
TP (valued at 70) has $40 in treasury and owns P12 and P8,

Observed result:
P12 has somehow contributed $60 to treasury of TP:
![image](https://user-images.githubusercontent.com/85963784/174458816-dffc4fe3-6e33-4ce8-9812-57f08d408009.png)
TP has $100 in treasury, and owns P12 and P8.

**Comment by dfannius** [comment]
The 1817 code, from which 18USA derives, identifies P12 as the Loan Shark private without checking that it's an 1817 game with the Volatility expansion.
