### ISSUE TITLE
[18LA2] 2 player games should not remove corps during setup

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#7974]
During the setup of a 2P game, it looks like corps are removed:

![image](https://user-images.githubusercontent.com/1711810/174863383-103a0218-d776-45a9-9d06-9f8b06aa46af.png)

This seems to conflict with the rule changeset [BGG link here](https://boardgamegeek.com/filepage/240633/18-los-angeles-changes-punch-list)

```
Unlike 1846, no Railroad Companies are removed prior to play. 
At lower player counts, the players may only start a limited number of Railroad Companies. 
If there are 2, or 3 players, players may only start 5 of the 7 available Railroad Companies.
```

cc @michaeljb

**Comment by michaeljb** [comment]
The end of the BGG file you linked says this:

> Two-Player Rules Changes
>
> Updated two-player rules are still in flight because of the changes to how public companies are removed from the game.
>
> For now, randomly select two public companies for removal from the game and place their two station tokens on the
map as defined in the original two-player rules

As this was brought up again recently in Slack, I've reached out to Tony to see if there has been any further development on the 2 player rules. Until I hear of new changes, I'll consider 18LA2 to be working as intended.
