### ISSUE TITLE
[18NewEngland] Autopass Turns Off Needlessly

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#7980]
https://18xx.games/game/87892?action=149

Here, TIE53's autopass was turned off because "ventusignis bought on corporation CVT and is unsecure."  That player bought a single share of the company and does not even have the liquidity to take it over.  Autopass should not turn off because a player bought a single share in a company you control.

**Comment by philcampeau** [comment]
The issue I see with the scenario ventusignis presented is you could end up in a situation where I have 3 shares of CVT, and player 2 buys up to 3 shares. Autopass checks, they still don't have the liquidity to buy a 4th, so the system autopasses me. Then, the player after me buys a share from the market that frees up player 2's liquidity, and they steal CVT from me as a result. 

I don't really see how this could be implemented without situations like this arising.
