### ISSUE TITLE
18EU - cannot finish Minor Exchange = GameID: 86778

### ISSUE THREAD

**Issue by efwin** [tobymao/18xx#7981]
Game link: https://18xx.games/game/86778

We are in Minor Exchange part of the game... I was able to assign Minors 9 + 14 to one of my corps. My minor 10 does not have rail in connection with a major. I could see the Discard Minors button as available but it did not correctly function, rendering our game in a stuck situation. One of the other players on the board copied to Hotseat and found the same to be true in the copied version.

**Comment by philcampeau** [comment]
game is archived, no way to see what happened at this point.
