### ISSUE TITLE
[18NY] NotImplemented error when taking action

### ISSUE THREAD

**Issue by chrisdoob** [tobymao/18xx#7984]
[Click on game 79741](https://18xx.games/game/79741)

[Last working action](https://18xx.games/game/79741?action=412)

https://gist.github.com/benjaminxscott/d740b7ad8f5802c8869e2c4f6c47623b

`NotImplementedError at m.send2`

<img width="959" alt="image" src="https://user-images.githubusercontent.com/108012476/175065057-3b658c5a-9a9e-4faa-8138-0fca6cf51c4c.png">

- Browser Version
  - Chrome Version 103.0.5060.53 (Official Build) (64-bit) Windows 11
  - also on Safari iPhone 13 iOs 15.6

**Comment by benjaminxscott** [comment]
Could you examine the game at [its last-working state](https://18xx.games/game/79741?action=412) and clarify which action was taken that might be causing this issue?

The [default game link](https://18xx.games/game/79741) takes you to the most recent action, which is a broken action but it's not clear what that action was

**Comment by chrisdoob** [comment]
I'm asking the players to run it back, but as of now, same issue.

**Comment by crericha** [comment]
Game fixed. Dup of #7621.
