### ISSUE TITLE
Old Game Won't Disappear

### ISSUE THREAD

**Issue by Foxrik** [tobymao/18xx#7985]
Game 85881  is on my active list but long finished.  When I click on it, a blank game screen appears and the computer hangs.  How do I get rid of this one?  I am not the owner who started the game.

Thanks,

Rick

**Comment by benjaminxscott** [comment]
This is due to the server code for 1866 being updated, so the game data no longer works with the current server code.

It looks like @crericha has access to delete games (hope that pinging them is OK!)

**Comment by tobymao** [comment]
archived
