### ISSUE TITLE
[18GB] Error during review of finished hotseat game

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7989]
I was reviewing a finished hotseat game when I encountered the following error:

"We're sorry this game cannot be continued due to GameError: Blocking step Place a Token or Lay Track cannot process action 278
Broken action: { "type": "run_routes", "entity": "LYR", "entity_type": "corporation", "id": 278, "created_at": 1655651308, "routes": [ { "train": "5+2-0", "connections": [ [ "J17", "J19", "I20" ], [ "I20", "I18", "I16" ], [ "I16", "H15" ], [ "H15", "G16" ], [ "G16", "H17" ], [ "H17", "H19" ] ], "hexes": [ "J17", "I20", "I16", "H15", "G16", "H17", "H19" ], "revenue": 190, "revenue_str": "J17-I20-I16-H15-G16-H17-H19", "nodes": [ "J17-2", "I20-0", "I16-0", "H15-0", "G16-1", "H17-0", "H19-0" ] } ] }"

https://gist.github.com/slapphappyjazz/ecc58fdf101b247cad85fc0787941bd1

**Comment by andypymont** [comment]
I can’t currently reproduce this (I created a new hotseat game with the data from the gist and it shows no error message) but will investigate further.

@slapphappyjazz If you create a new game, “Import hotseat game”, and paste the game data, does the resulting new hotseat game copy also show the error?

**Comment by slapphappyjazz** [comment]
@andypymont If I import the data into a new game, as you suggest, I can't recreate the error.  I can still reliably recreate the error in the original hotseat game.  Which is weird.

**Comment by slapphappyjazz** [comment]
I may have copied the original game data instead of the data from the game at the point that it broke.  Let me upload a different data file and try that.

**Comment by slapphappyjazz** [comment]
Try this: https://gist.github.com/slapphappyjazz/a707fc1c33c302bf03f129fa4ea182a1
