### ISSUE TITLE
18Chesapeake: Off the Rails Incorrect revenue for route from Strasburg to Allentown

### ISSUE THREAD

**Issue by sunris0315** [tobymao/18xx#7992]
**What's your Game ID?:sunris

Gamelink:https://18xx.games/game/87852?action=183

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the SRR buys Columbia - Philadelphia Railroad from Canadian for $80,
then SRR (C-P) lays tile #9 with rotation 1 on I3 without another tile
then the game broken and can't accept any new actions

Please include screenshots (you can drag and drop or upload them into this issue)

![图片](https://user-images.githubusercontent.com/108049517/175226881-acda6f76-63da-4307-b075-e5f6eb4a4eed.png)

**Comment by tobymao** [comment]
pinned

**Comment by dfannius** [comment]
The Columbia - Philadelphia Railroad broke a game rule by laying only one hex. This rule only just started being enforced so now the game can't be continued with the current version of the site, and is pinned to an old version. You can continue it now, although there will be a warning in the log.
