### ISSUE TITLE
[1822MRS] Incorrect Tile Manifest - missing 207 tile from tile manifest.

### ISSUE THREAD

**Issue by TheTagoreler** [tobymao/18xx#7993]
Can be seen in game here: https://18xx.games/game/87171

there is only one 207 (Y) K-shaped tile in the tile manifest. According to the rulebook, there should be 2 of these avaliable.  The MRS rules do not mention removing one of these tiles

**Comment by benjaminxscott** [comment]
Confirmed

http://www.fwtwr.com/18xx/info/inv-1822mrs.asp

![Screenshot 2022-06-23 5 03 15 PM](https://user-images.githubusercontent.com/1711810/175434711-62bec981-727e-46c5-8d52-07e8636ef7ee.png)
