### ISSUE TITLE
Bug: required to buy a train without a valid route

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#80]
Game id 75
Tosa Kuroshio railway: I cant pass on 6.2 buy trains phase even though I dont have a valid route and thereby am not obligated to buy a train. The [pass] button does not appear. Only the [undo] button is available

**Comment by MoshiMaro** [comment]
I can't buy a diesel from the bank either. Apparently I am not forced to buy a train because I don't have a valid route...

**Comment by tobymao** [comment]
yea i haven’t implemented that yet... been avoiding it might have to do it today
