### ISSUE TITLE
1836jr: We're sorry this game cannot be continued due to GameError: It is not B's turn

### ISSUE THREAD

**Issue by dennislaumen** [tobymao/18xx#800]
{
  "id": 2145,
  "description": "",
  "user": {
    "id": 192,
    "name": "dennislaumen"
  },
  "players": [
    {
      "id": 1795,
      "name": "sleep"
    },
    {
      "id": 131,
      "name": "Iyidin_Kyeimo"
    },
    {
      "id": 310,
      "name": "Sly wilbur"
    },
    {
      "id": 192,
      "name": "dennislaumen"
    }
  ],
  "max_players": 4,
  "title": "1836Jr30",
  "settings": {
    "seed": 1.0794044222685033e+38
  },
  "status": "active",
  "turn": 4,
  "round": "Operating Round",
  "acting": [
    192
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 225,
      "entity": "sleep",
      "company": "CFLV",
      "entity_type": "player"
    },
    {
      "id": 2,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Please note that a couple of rules aren't enforced in this implementation. I asked on Slack for a list of these missing rules.",
      "entity_type": "player"
    },
    {
      "id": 3,
      "type": "bid",
      "price": 165,
      "entity": "Iyidin_Kyeimo",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 4,
      "type": "message",
      "entity": "dennislaumen",
      "message": "https://github.com/tobymao/18xx/issues/692",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "bid",
      "price": 75,
      "entity": "Sly wilbur",
      "company": "CdH",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "bid",
      "price": 45,
      "entity": "dennislaumen",
      "company": "E-SF",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "bid",
      "price": 50,
      "entity": "Iyidin_Kyeimo",
      "company": "E-SF",
      "entity_type": "player"
    },
    {
      "id": 9,
      "type": "bid",
      "price": 20,
      "entity": "Sly wilbur",
      "company": "ACC",
      "entity_type": "player"
    },
    {
      "id": 10,
      "type": "bid",
      "price": 55,
      "entity": "dennislaumen",
      "company": "E-SF",
      "entity_type": "player"
    },
    {
      "id": 11,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 12,
      "type": "bid",
      "price": 170,
      "entity": "dennislaumen",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Let’s pause before or1 of this isn’t fixed. ",
      "entity_type": "player"
    },
    {
      "id": 14,
      "type": "message",
      "entity": "dennislaumen",
      "message": "06/13 18:05:00 scottredracecar: If you're playing 36, wait for Toby to push the map fix before you lay any tiles. You will know it's updated when Lille connects to Paris",
      "entity_type": "player"
    },
    {
      "id": 15,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "bid",
      "price": 110,
      "entity": "Iyidin_Kyeimo",
      "company": "GCB",
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "bid",
      "price": 175,
      "entity": "Iyidin_Kyeimo",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "bid",
      "price": 180,
      "entity": "dennislaumen",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 19,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 20,
      "type": "par",
      "entity": "sleep",
      "corporation": "Nord",
      "entity_type": "player",
      "share_price": "67,5,6"
    },
    {
      "id": 21,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "Nord_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 23,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 24,
      "type": "par",
      "entity": "Iyidin_Kyeimo",
      "corporation": "GCL",
      "entity_type": "player",
      "share_price": "67,5,6"
    },
    {
      "id": 25,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "Nord_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 26,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "GCL_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 27,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 28,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "GCL_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 29,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "Nord_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 30,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "Nord_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 31,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_7"
      ],
      "entity_type": "player"
    },
    {
      "id": 32,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "Nord_8"
      ],
      "entity_type": "player"
    },
    {
      "id": 33,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 34,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "GCL_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 35,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 36,
      "hex": "I5",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 37,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 38,
      "type": "buy_train",
      "price": 80,
      "train": "2-1",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 39,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 40,
      "hex": "I9",
      "tile": "57-0",
      "type": "lay_tile",
      "entity": "GCL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 41,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 42,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 43,
      "type": "message",
      "entity": "Iyidin_Kyeimo",
      "message": "Hang on, do we need to rewind? Can only buy one train in 36jr unless its last and first of two different trains i.e. 2,3 isn't that right? Not enforced yet",
      "entity_type": "player"
    },
    {
      "id": 44,
      "type": "message",
      "entity": "Iyidin_Kyeimo",
      "message": "Never played this before but I think I read that somewhere",
      "entity_type": "player"
    },
    {
      "id": 45,
      "type": "message",
      "entity": "Sly wilbur",
      "message": "Yes you are limited to a single train purchase",
      "entity_type": "player"
    },
    {
      "id": 46,
      "type": "undo",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 47,
      "type": "undo",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 48,
      "type": "undo",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 49,
      "type": "undo",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 50,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 51,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 52,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 53,
      "hex": "I5",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 54,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 55,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 56,
      "hex": "I9",
      "tile": "57-0",
      "type": "lay_tile",
      "entity": "GCL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 57,
      "type": "buy_train",
      "price": 80,
      "train": "2-1",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 58,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 59,
      "type": "message",
      "entity": "Sly wilbur",
      "message": "I changed the round so that only one train was bought",
      "entity_type": "player"
    },
    {
      "id": 60,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 61,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Yeah we just enforce the train thing manually",
      "entity_type": "player"
    },
    {
      "id": 62,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 63,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 64,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 65,
      "hex": "H4",
      "tile": "57-1",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 66,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 67,
      "type": "run_routes",
      "entity": "Nord",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "I3",
              "I5",
              "H4"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 68,
      "kind": "payout",
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 69,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 70,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 71,
      "type": "buy_shares",
      "entity": "GCB",
      "shares": [
        "B_1"
      ],
      "entity_type": "company"
    },
    {
      "id": 72,
      "type": "undo",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 73,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 74,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 75,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 76,
      "type": "message",
      "entity": "Sly wilbur",
      "message": "Should the F220 private not be closed when the Nord bought its first train?",
      "entity_type": "player"
    },
    {
      "id": 77,
      "type": "sell_shares",
      "entity": "Sly wilbur",
      "shares": [
        "Nord_3",
        "Nord_5"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 78,
      "type": "par",
      "entity": "Sly wilbur",
      "corporation": "HSM",
      "entity_type": "player",
      "share_price": "67,5,6"
    },
    {
      "id": 79,
      "type": "message",
      "entity": "dennislaumen",
      "message": "@Sly Wilbur, yes according to the company text it should... can we fix this ourselves?",
      "entity_type": "player"
    },
    {
      "id": 80,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Or, fix, I mean work around it...",
      "entity_type": "player"
    },
    {
      "id": 81,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "Nord_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 82,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 83,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 84,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 85,
      "type": "message",
      "entity": "Iyidin_Kyeimo",
      "message": "Don't see how we can fix that using the normal player tools",
      "entity_type": "player"
    },
    {
      "id": 86,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 87,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "HSM_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 88,
      "type": "message",
      "entity": "Sly wilbur",
      "message": "The game is still in development so we just go with it I think.",
      "entity_type": "player"
    },
    {
      "id": 89,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 90,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Yeah I logged the bug after discussing with toby.",
      "entity_type": "player"
    },
    {
      "id": 91,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 92,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 93,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 94,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "HSM_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 95,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 96,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 97,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Idea I saw on the homepage here, maybe track money the Nord private gave you and \"vow\" to not spend it? Just thinking how we can make this most fair, but that's probably too much bookkeeping?",
      "entity_type": "player"
    },
    {
      "id": 98,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Anyway, let's just try to break this and see what we find :-).",
      "entity_type": "player"
    },
    {
      "id": 99,
      "type": "message",
      "entity": "dennislaumen",
      "message": "As spending it could break the game ->",
      "entity_type": "player"
    },
    {
      "id": 100,
      "type": "message",
      "entity": "dennislaumen",
      "message": "06/16 11:18:57 Jen Freeman: when we fix it, the money will disappear or your game will break if you spent money you couldn't have ",
      "entity_type": "player"
    },
    {
      "id": 101,
      "type": "message",
      "entity": "dennislaumen",
      "message": "I'm guessing then @sleep has already spent too much right? Maybe just ensure you have the money set aside after the next ORs?",
      "entity_type": "player"
    },
    {
      "id": 102,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 103,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 104,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "HSM_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 105,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 106,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 107,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 108,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 109,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "HSM_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 110,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 111,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 112,
      "type": "message",
      "entity": "dennislaumen",
      "message": "autopass for me until someone sells",
      "entity_type": "player"
    },
    {
      "id": 113,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 114,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 115,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 116,
      "hex": "G3",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 117,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 118,
      "type": "run_routes",
      "entity": "Nord",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "I3",
              "I5",
              "H4"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "I3",
              "J2"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 119,
      "kind": "payout",
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 120,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 121,
      "hex": "E7",
      "tile": "57-2",
      "type": "lay_tile",
      "entity": "HSM",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 122,
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 123,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 124,
      "type": "buy_train",
      "price": 180,
      "train": "3-0",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 125,
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 126,
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 127,
      "type": "buy_company",
      "price": 220,
      "entity": "GCL",
      "company": "GCB",
      "entity_type": "corporation"
    },
    {
      "id": 128,
      "hex": "H10",
      "tile": "59-0",
      "type": "lay_tile",
      "entity": "GCL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 129,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 130,
      "type": "run_routes",
      "entity": "GCL",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "I9",
              "H10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 131,
      "kind": "payout",
      "type": "dividend",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 132,
      "type": "buy_train",
      "price": 180,
      "train": "3-1",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 133,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 134,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 135,
      "type": "message",
      "entity": "dennislaumen",
      "message": "@sleep pls set aside your private money so we can continue playing 😅",
      "entity_type": "player"
    },
    {
      "id": 136,
      "type": "sell_shares",
      "entity": "dennislaumen",
      "shares": [
        "GCL_1",
        "GCL_2"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 137,
      "type": "sell_shares",
      "entity": "dennislaumen",
      "shares": [
        "Nord_1",
        "Nord_6",
        "Nord_3"
      ],
      "percent": 30,
      "entity_type": "player"
    },
    {
      "id": 138,
      "type": "par",
      "entity": "dennislaumen",
      "corporation": "B",
      "entity_type": "player",
      "share_price": "76,3,6"
    },
    {
      "id": 139,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "HSM_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 140,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 141,
      "type": "sell_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "Nord_8"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 142,
      "type": "sell_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "GCL_3",
        "GCL_4"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 143,
      "type": "par",
      "entity": "Iyidin_Kyeimo",
      "corporation": "NBDS",
      "entity_type": "player",
      "share_price": "82,2,6"
    },
    {
      "id": 144,
      "type": "buy_shares",
      "entity": "Sly wilbur",
      "shares": [
        "GCL_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 145,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 146,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "B_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 147,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 148,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Please note everyone that there’s an impassable border under F4 and F6 and another one in-between B8 and B10.",
      "entity_type": "player"
    },
    {
      "id": 149,
      "type": "message",
      "entity": "dennislaumen",
      "message": "not visible on the map her",
      "entity_type": "player"
    },
    {
      "id": 150,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "GCL_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 151,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 152,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "NBDS_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 153,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 154,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 155,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "B_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 156,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 157,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 158,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "NBDS_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 159,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 160,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 161,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "B_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 162,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 163,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 164,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "NBDS_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 165,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 166,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 167,
      "type": "buy_shares",
      "entity": "dennislaumen",
      "shares": [
        "B_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 168,
      "type": "message",
      "entity": "dennislaumen",
      "message": "@sleep pls set aside cash you incorrectly received next SR. If the game is updated and you don’t have enough cash on hand it will most likely be deleted automatically (as communicated by the devs). ",
      "entity_type": "player"
    },
    {
      "id": 169,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 170,
      "type": "message",
      "entity": "dennislaumen",
      "message": "I know this implementation isn’t complete so everything is testing anyway and not serious but it’d be fun to be able to finish the game 😅. ",
      "entity_type": "player"
    },
    {
      "id": 171,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 172,
      "type": "buy_shares",
      "entity": "Iyidin_Kyeimo",
      "shares": [
        "NBDS_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 173,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 174,
      "type": "pass",
      "entity": "Sly wilbur",
      "entity_type": "player"
    },
    {
      "id": 175,
      "type": "pass",
      "entity": "dennislaumen",
      "entity_type": "player"
    },
    {
      "id": 176,
      "type": "message",
      "entity": "dennislaumen",
      "message": "Autopass ",
      "entity_type": "player"
    },
    {
      "id": 177,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 178,
      "type": "pass",
      "entity": "Iyidin_Kyeimo",
      "entity_type": "player"
    },
    {
      "id": 179,
      "hex": "E11",
      "tile": "59-1",
      "type": "lay_tile",
      "entity": "NBDS",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 180,
      "type": "pass",
      "entity": "NBDS",
      "entity_type": "corporation"
    },
    {
      "id": 181,
      "type": "pass",
      "entity": "NBDS",
      "entity_type": "corporation"
    },
    {
      "id": 182,
      "hex": "H4",
      "tile": "14-0",
      "type": "lay_tile",
      "entity": "B",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 183,
      "type": "buy_company",
      "price": 320,
      "entity": "B",
      "company": "CFL",
      "entity_type": "corporation"
    },
    {
      "id": 184,
      "type": "buy_company",
      "price": 80,
      "entity": "B",
      "company": "E-SF",
      "entity_type": "corporation"
    },
    {
      "id": 185,
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 186,
      "type": "buy_train",
      "price": 180,
      "train": "3-2",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 187,
      "type": "buy_train",
      "price": 180,
      "train": "3-3",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 188,
      "hex": "I5",
      "tile": "27-0",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 189,
      "city": "14-0-0",
      "slot": 1,
      "type": "place_token",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 190,
      "type": "run_routes",
      "entity": "Nord",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H4",
              "I5",
              "I3"
            ]
          ]
        },
        {
          "train": "2-2",
          "connections": [
            [
              "H6",
              "H4"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 191,
      "kind": "payout",
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 192,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 193,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 194,
      "hex": "E7",
      "tile": "14-1",
      "type": "lay_tile",
      "entity": "HSM",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 195,
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 196,
      "type": "run_routes",
      "entity": "HSM",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 197,
      "kind": "payout",
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 198,
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 199,
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 200,
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 201,
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 202,
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 203,
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 204,
      "type": "buy_company",
      "price": 40,
      "entity": "HSM",
      "company": "ACC",
      "entity_type": "corporation"
    },
    {
      "id": 205,
      "type": "buy_company",
      "price": 140,
      "entity": "HSM",
      "company": "CdH",
      "entity_type": "corporation"
    },
    {
      "id": 206,
      "hex": "J8",
      "tile": "57-3",
      "type": "lay_tile",
      "entity": "HSM",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 207,
      "city": "57-3-0",
      "slot": 0,
      "type": "place_token",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 208,
      "type": "run_routes",
      "entity": "HSM",
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        },
        {
          "train": "3-0",
          "connections": [
            [
              "I9",
              "J8"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 209,
      "kind": "payout",
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 210,
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "id": 211,
      "hex": "I9",
      "tile": "15-0",
      "type": "lay_tile",
      "entity": "GCL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 212,
      "type": "undo",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 213,
      "hex": "I9",
      "tile": "15-0",
      "type": "lay_tile",
      "entity": "GCL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 214,
      "city": "59-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 215,
      "type": "run_routes",
      "entity": "GCL",
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "H10",
              "I9"
            ]
          ]
        },
        {
          "train": "3-1",
          "connections": [
            [
              "J8",
              "I9"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 216,
      "kind": "payout",
      "type": "dividend",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 217,
      "type": "pass",
      "entity": "GCL",
      "entity_type": "corporation"
    },
    {
      "id": 218,
      "hex": "F10",
      "tile": "4-0",
      "type": "lay_tile",
      "entity": "NBDS",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 219,
      "type": "buy_train",
      "price": 450,
      "train": "2-1",
      "entity": "NBDS",
      "entity_type": "corporation"
    },
    {
      "id": 220,
      "type": "pass",
      "entity": "NBDS",
      "entity_type": "corporation"
    }
  ],
  "loaded": true,
  "created_at": 1592039180,
  "updated_at": 1592587603
}

**Comment by jenf** [comment]
Yeah, NBDS is an erie style token lay.

@tobymao should we pin or delete these games?

**Comment by dennislaumen** [comment]
@jenf not sure I understand, did we make a move which wasn't allowed but is enforced after an update?

**Comment by jenf** [comment]
Yesterday we added that NBDS must choose it's home token spot as per the rules, unfortunately this means that the lay token action is was expecting has not actually occur.

**Comment by tobymao** [comment]
either that or delete them

**Comment by tobymao** [comment]
pinned the games
