### ISSUE TITLE
Unable to write in chat on mobile (android)

### ISSUE THREAD

**Issue by gardir** [tobymao/18xx#8014]
I think I am unable to send a chat message on mobile phone. Both in general and in games. Happened after the recent update.

**Comment by mamitsch** [comment]
Seems to be the same issue on iPhone, see:

Chat not working on IOS anymore #8013

**Comment by gardir** [comment]
Also not working on my computer, so I guess it's a general problem with catching the "enter/submit" event.

**Comment by tobymao** [comment]
dup
