### ISSUE TITLE
Game 85801 is no longer accessible.

### ISSUE THREAD

**Issue by Thistlegorm** [tobymao/18xx#8027]
**How to Reproduce the Problem?**

Game 85801 remains in my list of active games, despite being inaccessible. When I click on view, the browser hangs. It doesn’t matter which browser I use. 
I believe this has happened because the game has been archived (or something similar) while we were playing. 

I cannot find a way to remove this from my active game list. Please help.

**Comment by roseundy** [comment]
Not an archived game.

This is a Harzbahn game. Error on action 195. Still trying to root cause.

**Comment by roseundy** [comment]
This looks like corrupted game state. The Destinate auto-action after the pass action (195) somehow got lost.

What the action should look like:
![good](https://user-images.githubusercontent.com/8494213/176520280-ac234a7c-3c99-4f69-ade9-9cc30c46c993.png)

What it actually looks like:
![failure](https://user-images.githubusercontent.com/8494213/176520314-48664b66-6a08-4150-a485-b35a8a073107.png)

**Comment by crericha** [comment]
Likely a dup of #7813 

I have a potential fix that will verify that the correct auto actions are present on the server-side.

**Comment by crericha** [comment]
For now, what I do is delete the last action from the db. When the player takes that action again, it'll include the auto action like it should normally.

**Comment by roseundy** [comment]
Great, thanks Chris.
How does one go about deleting the last action from the db?

**Comment by crericha** [comment]
From the server's prod_irb, you can do Game[id].actions.last.delete.

Note: You'll need to load up the db environment first within the prod_irb instance.

**Comment by tobymao** [comment]
don't use delete, use destroy

**Comment by crericha** [comment]
![image](https://user-images.githubusercontent.com/67359577/176561781-bf5c7185-a89c-4620-9ce8-f6ff860fe76c.png)

**Comment by Thistlegorm** [comment]
﻿What am I to do with these messages? This last one was blank and the one before was beyond my comprehension. Thanks

**Comment by dfannius** [comment]
You do not need to do anything with them. The developers are talking to each other about how to resolve the issue.

**Comment by roseundy** [comment]
@crericha: Another dumb question how do I "load up the db environment"?

**Comment by crericha** [comment]
@roseundy, I don't know if you need all of this, but this is what I use.

> Dir['./models/**/*.rb'].sort.each { |file| require file }
Sequel.extension :pg_json_ops
require './lib/engine'
require 'etc'

**Comment by Thistlegorm** [comment]
There has been no change as yet.

**Comment by Thistlegorm** [comment]
Thanks
