### ISSUE TITLE
[1877 Stockholm Tramways] Can't run trains of acquired company

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#8028]
https://gist.github.com/dfannius/5d1a678605475fd561aa15f24945956f

SNS had no trains at the start of if its turn in OR4.1. It started its turn by acquiring SF, which had two trains. Now it has two trains, but is not given the opportunity to run them ("SNS skips run routes" happens automatically).

This didn't seem correct from the rules (I looked at sections 6.4 "Run trains" and 6.7 "Acquire a company"), but the rules are pretty terse so I certainly could have missed something.

**Comment by lbrande** [comment]
I've looked at the situation and can confirm it's a bug.
