### ISSUE TITLE
1822 end of game bug

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#8039]
https://18xx.games/game/84384

Bank Broke during OR 10.1 triggering end condition of ‘End of set of OR’ 
Then a company hit 700 which should have changed it to the end condition of ‘End of this OR’ 
The second did not override the first and I believe it should.  :)

**Comment by dfannius** [comment]
> 10.1.2 Once the game end has been triggered, the game will end at the indicated time, even if another end condition is triggered after the first.

So I don't think this is a bug. But I don't know 1822 so I will leave this open for others to confirm.

**Comment by Eludyan** [comment]
Oh interesting. I never noticed that. Thanks!
