### ISSUE TITLE
1836jr - Unable to exchange GCB for a 10% share in B (Chemins de Fer de L'État Belge)

### ISSUE THREAD

**Issue by Laxen123** [tobymao/18xx#804]
Owner is unable to exchange Private Company "Grand Central Belge" for  an available share in the bank pool. during a Stock Round  There is no button for this option.

Game 2304

{
  "id": 2304,
  "description": "sthlm (private test)",
  "user": {
    "id": 895,
    "name": "Lindeberg"
  },
  "players": [
    {
      "id": 451,
      "name": "MICKE"
    },
    {
      "id": 895,
      "name": "Lindeberg"
    },
    {
      "id": 901,
      "name": "Laxen"
    },
    {
      "id": 826,
      "name": "MrPoison"
    }
  ],
  "max_players": 4,
  "title": "1836Jr30",
  "settings": {
    "seed": 5.525940124042331e+37
  },
  "status": "active",
  "turn": 2,
  "round": "Stock Round",
  "acting": [
    901
  ],
  "result": {},
  "actions": [
    {
      "type": "bid",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 1,
      "company": "CFL",
      "price": 180
    },
    {
      "type": "bid",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 2,
      "company": "CdH",
      "price": 75
    },
    {
      "type": "bid",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 3,
      "company": "GCB",
      "price": 115
    },
    {
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 4
    },
    {
      "type": "bid",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 5,
      "company": "E-SF",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 6,
      "company": "ACC",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 7
    },
    {
      "type": "bid",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 8,
      "company": "CFLV",
      "price": 220
    },
    {
      "type": "par",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 9,
      "corporation": "Nord",
      "share_price": "90,1,6"
    },
    {
      "id": 10,
      "type": "par",
      "entity": "MICKE",
      "corporation": "GCL",
      "entity_type": "player",
      "share_price": "90,1,6"
    },
    {
      "id": 11,
      "type": "undo",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "type": "par",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 12,
      "corporation": "GCL",
      "share_price": "67,5,6"
    },
    {
      "type": "par",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 13,
      "corporation": "B",
      "share_price": "76,3,6"
    },
    {
      "type": "pass",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 15
    },
    {
      "id": 16,
      "type": "buy_shares",
      "entity": "MICKE",
      "shares": [
        "GCL_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 17,
      "type": "undo",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "B_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "GCL_2"
      ]
    },
    {
      "id": 20,
      "type": "pass",
      "entity": "Laxen",
      "entity_type": "player"
    },
    {
      "id": 21,
      "type": "undo",
      "entity": "MrPoison",
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "buy_shares",
      "entity": "Laxen",
      "shares": [
        "B_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 23,
      "type": "undo",
      "entity": "MrPoison",
      "entity_type": "player"
    },
    {
      "type": "buy_shares",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 24,
      "shares": [
        "B_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 25,
      "shares": [
        "B_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "B_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "B_5"
      ]
    },
    {
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 28
    },
    {
      "id": 29,
      "type": "pass",
      "entity": "Laxen",
      "entity_type": "player"
    },
    {
      "id": 30,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "type": "buy_shares",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "B_6"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "B_7"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "B_8"
      ]
    },
    {
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "lay_tile",
      "entity": "B",
      "entity_type": "corporation",
      "id": 35,
      "hex": "H4",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "buy_train",
      "entity": "B",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation",
      "id": 38
    },
    {
      "id": 39,
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player"
    },
    {
      "id": 40,
      "type": "undo",
      "entity": "MICKE",
      "entity_type": "player"
    },
    {
      "id": 41,
      "type": "buy_shares",
      "entity": "MrPoison",
      "shares": [
        "GCL_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 42,
      "type": "undo",
      "entity": "MrPoison",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 43
    },
    {
      "type": "pass",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "buy_shares",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 45,
      "shares": [
        "GCL_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "Laxen",
      "entity_type": "player",
      "id": 47
    },
    {
      "type": "pass",
      "entity": "MrPoison",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "sell_shares",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 49,
      "shares": [
        "B_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 50,
      "shares": [
        "GCL_4"
      ]
    },
    {
      "type": "pass",
      "entity": "MICKE",
      "entity_type": "player",
      "id": 51
    },
    {
      "id": 52,
      "type": "sell_shares",
      "entity": "Lindeberg",
      "shares": [
        "GCL_2"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 53,
      "type": "buy_shares",
      "entity": "Lindeberg",
      "shares": [
        "B_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 54,
      "type": "pass",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "id": 55,
      "type": "undo",
      "entity": "Laxen",
      "entity_type": "player"
    },
    {
      "id": 56,
      "type": "undo",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "id": 57,
      "type": "undo",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "id": 58,
      "type": "redo",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "id": 59,
      "type": "undo",
      "entity": "Lindeberg",
      "entity_type": "player"
    },
    {
      "type": "pass",
      "entity": "Lindeberg",
      "entity_type": "player",
      "id": 60
    },
    {
      "id": 61,
      "type": "sell_shares",
      "entity": "Laxen",
      "shares": [
        "B_6"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 62,
      "type": "undo",
      "entity": "Laxen",
      "entity_type": "player"
    }
  ],
  "loaded": true,
  "created_at": 1592303373,
  "updated_at": 1592670412
}

**Comment by jenf** [comment]
seems to be present now, however you cannot exchange it as the first action in a stock round, investigating that bug.

**Comment by jenf** [comment]
fixed
