### ISSUE TITLE
[1871 TOP] Unable to buy share

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#8040]
Ariel is unable to buy a So share. Not sure why

https://18xx.games/game/89749?action=367

**Comment by joeyd4329** [comment]
and LoveShard was unable to buy a share of S as well.

**Comment by dfannius** [comment]
https://18xx.games/hotseat/hs_aezfudbq_89749?action=368

I assume this is another instance of #8004. At this moment Ariel had $71 and So shares cost $69. I don't know when LoveShard's attempted purchase of S was but they also had been paid dividends by the PEIR.

**Comment by joeyd4329** [comment]
What I find even stranger is when I go back and clone the game info in hotseat, I can buy the So share for Ariel and cannot replicate the problem. I thought it maybe had something to do with the PEIR shares getting exchanged (I think the PEIR closed that SR).

**Comment by dfannius** [comment]
Yes, that's because in hotseat you're executing the code entirely on the client, so there's no opportunity for the client and server to get out of sync.
