### ISSUE TITLE
[18NY] game cannot continue 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#8047]
Seems like auto actions is causing an error in the OR??

https://18xx.games/game/88940
![D6E430B7-0C94-4197-B164-7E8743B1FE51](https://user-images.githubusercontent.com/73144084/177415502-bf073298-dd33-42e7-b70a-2e889996d793.png)

**Comment by crericha** [comment]
@BellmakerSA did it happen only once or does it continue to happen after you refresh the page and try the action again?

**Comment by BellmakerSA** [comment]
> @BellmakerSA did it happen only once or does it continue to happen after you refresh the page and try the action again?

Yes,, and I tried to master mode if for them and got the same error

**Comment by crericha** [comment]
Okay, thanks. Fix coming in a few minutes.
