### ISSUE TITLE
[1846] All stock sales happen in one batch

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#805]
Re: #802 T[om Lehmann](https://boardgamegeek.com/thread/2450447/article/35143438#35143438) says:

> > During a single turn in the Stock Round, can the president of a company sell a share, drop the price, then sell another share, and drop the price a second step?

> No. See 5.1. Step A is "sell one or more shares", not "make any number of sales".

**Comment by scottredracecar** [comment]
It also doesn't say sell them all in one batch, but if Tom says, then so be
it!

**Comment by XB-AU** [comment]
Since sales are not "any number of sales" it must also mean sales are limited to one company rather than any number of companies and in any order?  That is we assume the words "in any one company" follow thew words "sell one or more shares" in the rules?
