### ISSUE TITLE
[18Ireland] Illegal mergers produce Javascript (I assume) errors when executed

### ISSUE THREAD

**Issue by daytonwilliams-okta** [tobymao/18xx#8060]
**What's your Game ID?**

https://18xx.games/game/88791?action=374

**How to Reproduce the Bug?**

1.  Propose an illegal-because-already-rejected merge (in this case, attempt to merge the KJR and the GNWR)
2. The game correctly refused: [player] already proposed the same exact merger [foo, bar].  This is against the rules, clearing proposal.
3. The "start voting on proposal" button is, however, clickable.  (This is the bug: voting on an illegal proposal should not be possible.)
4. Clicking on it produces an error.  See attached screenshot:

![I-will-make-it-legal](https://user-images.githubusercontent.com/14828956/178128093-97f1ceb0-d8a7-45a7-baee-e02d39a820c4.png)

**Which Browser / Platform?**
Desktop Firefox 102.0.1

**Comment by bentziaxl** [comment]
what's the correct behaviour after the bad proposal? is it similar to a pass, and the it's the next player's turn, or does it stay with the same player?

**Comment by dfannius** [comment]
I assume the action should just be rejected as if you didn't make it (like if you tried to lay a tile you didn't have the money for). It shouldn't even show up in the log as an attempted action.

**Comment by daytonwilliams-okta** [comment]
Without debugging the issue, it seems to me that it's correctly clearing the illegal proposal, but _not_ resetting the state fully (you don't see 'begin voting' at the start of your turn, because there is no proposal to vote on).

The bug is you're the wrong UI state and have access to the "vote on proposal" button when there _is_ no proposal (because it was cleared for being illegal).  Thus the attempt to convert nothing (`NilClass` I presume) into an integer.

I.e. I think the bug is the game state is reset to "no proposal submitted" but the UI is still in the "ready to submit proposal" state, so you are given the option to perform illegal actions.

I agree with dfannius.  An illegal action is not an action at all, so it should be treated as if it never happened.  So it remains the same player's turn to propose a legal merger.

**Comment by bentziaxl** [comment]
a quick a dirty fix is to just add @round.vote_outcome = :against, it would treat it as a rejected merge, but it then moves the turn to the next player. That's why i asked what the expected behaviour is

**Comment by bentziaxl** [comment]
fixed, @round.merging was incorrectly set to an empty array instead of nil
