### ISSUE TITLE
1866 - port bonus not being paid

### ISSUE THREAD

**Issue by retterermoore** [tobymao/18xx#8066]
In phase 4, running a 3 train from a tokened Rotterdam to 2 other cities, with Rotterdam being the end point, just pays out the sum of the cities and doesn't give the port bonus for Rotterdam.

Occurred in game https://18xx.games/game/90470, although I submitted a different route when the port bonus was not paying out.

**Comment by magnusstjarnhild** [comment]
Which company did you run the 3 train, and around what action did you do this. Scroll back in the log and click on a line and choose "Review from here" and look and compy the URL here. Since i cant find where you mean, and tested a few option and they worked.

**Comment by retterermoore** [comment]
https://18xx.games/game/90470?action=664 
GL

**Comment by philcampeau** [comment]
The port bonus is added as a subsidy to the treasury. 

You can see the 20 subsidy indicated on the Submit button. It seems to be calculated correctly.

![image](https://user-images.githubusercontent.com/26125362/181349799-77b2015b-2544-428d-994d-f82a76c200ab.png)

**Comment by retterermoore** [comment]
Hmm, I don't think it was showing up like that in game.  In any case, I guess that either means I was reading something wrong back then, or there was an issue and it has been fixed inadvertently, so this can be closed out.
