### ISSUE TITLE
[18Carolinas] Cost of train power when during emergency purchase is incorrect

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#8073]
Read the rules for this a couple of times, but I believe that during an emergency purchase, a company has to buy up to the power level equal to the current phase number, and pay double the current cost.

In this example from a completed game:
https://18xx.games/game/89948?action=309

It shows a cost of $540 needed for the emergency purchase of 4 power points in phase 8 (which has a normal cost of 90 per point). However, I believe this cost should have been 720 (4 points x 90 per point x 2 for emergency purchase).

**Comment by roseundy** [comment]
Scott changed this from 2x to 1.5x, but the rules haven't been updated.
