### ISSUE TITLE
Time zone correction on front page takes place after times are rendered

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#8078]
All the times on the game cards on the front page are displayed in UTC for a moment when the page loads (less than a second but enough to be noticeable), then switch to the user's time zone. Observed in Firefox and Chrome on macOS.

**Comment by benjaminxscott** [comment]
Is this still something we want to work on?

**Comment by philcampeau** [comment]
I don't believe so. I just tested a few times with different browsers and machines, didn't see it. Will close.
