### ISSUE TITLE
 GameError: Cannot buy a share of NFL

### ISSUE THREAD

**Issue by chrisdavis103** [tobymao/18xx#809]
We're sorry this game cannot be continued due to GameError: Cannot buy a share of NFL
Please raise a bug report and include the game id (2143) and the following JSON data

{
  "id": 2143,
  "description": "public",
  "user": {
    "id": 91,
    "name": "agrajag"
  },
  "players": [
    {
      "id": 1795,
      "name": "sleep"
    },
    {
      "id": 91,
      "name": "agrajag"
    },
    {
      "id": 9,
      "name": "spobster"
    },
    {
      "id": 1452,
      "name": "chrisdavis103"
    }
  ],
  "max_players": 4,
  "title": "1836Jr30",
  "settings": {
    "seed": 1.544622896807159e+37
  },
  "status": "active",
  "turn": 5,
  "round": "Stock Round",
  "acting": [
    1452
  ],
  "result": {},
  "actions": [
    {
      "id": 1,
      "type": "bid",
      "price": 225,
      "entity": "sleep",
      "company": "CFLV",
      "entity_type": "player"
    },
    {
      "id": 2,
      "type": "bid",
      "price": 165,
      "entity": "agrajag",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 3,
      "type": "bid",
      "price": 170,
      "entity": "spobster",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 4,
      "type": "bid",
      "price": 45,
      "entity": "chrisdavis103",
      "company": "E-SF",
      "entity_type": "player"
    },
    {
      "id": 5,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 6,
      "type": "bid",
      "price": 75,
      "entity": "agrajag",
      "company": "CdH",
      "entity_type": "player"
    },
    {
      "id": 7,
      "type": "bid",
      "price": 115,
      "entity": "spobster",
      "company": "GCB",
      "entity_type": "player"
    },
    {
      "id": 8,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 9,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 10,
      "type": "bid",
      "price": 20,
      "entity": "agrajag",
      "company": "ACC",
      "entity_type": "player"
    },
    {
      "id": 11,
      "type": "bid",
      "price": 180,
      "entity": "agrajag",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 12,
      "type": "bid",
      "price": 185,
      "entity": "spobster",
      "company": "CFL",
      "entity_type": "player"
    },
    {
      "id": 13,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 14,
      "type": "par",
      "entity": "sleep",
      "corporation": "Nord",
      "entity_type": "player",
      "share_price": "67,5,6"
    },
    {
      "id": 15,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 16,
      "type": "par",
      "entity": "chrisdavis103",
      "corporation": "NFL",
      "entity_type": "player",
      "share_price": "67,5,6"
    },
    {
      "id": 17,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 18,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "NFL_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 19,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "NFL_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 20,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "NFL_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 21,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 22,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "NFL_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 23,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "NFL_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 24,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "NFL_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 25,
      "type": "undo",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 26,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "NFL_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 27,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 28,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "NFL_7"
      ],
      "entity_type": "player"
    },
    {
      "id": 29,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "Nord_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 30,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "NFL_8"
      ],
      "entity_type": "player"
    },
    {
      "id": 31,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "Nord_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 32,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 33,
      "hex": "B10",
      "tile": "57-0",
      "type": "lay_tile",
      "entity": "NFL",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 34,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 35,
      "type": "buy_train",
      "price": 80,
      "train": "2-0",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 36,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 37,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 38,
      "type": "buy_train",
      "price": 80,
      "train": "2-1",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 39,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 40,
      "hex": "I5",
      "tile": "8-0",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 5,
      "entity_type": "corporation"
    },
    {
      "id": 41,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 42,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 43,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 44,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 45,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 46,
      "type": "buy_train",
      "price": 80,
      "train": "2-3",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 47,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 48,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 49,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 50,
      "type": "message",
      "entity": "spobster",
      "message": "@sleep, your company should have closed",
      "entity_type": "player"
    },
    {
      "id": 51,
      "type": "message",
      "entity": "spobster",
      "message": "the private one",
      "entity_type": "player"
    },
    {
      "id": 52,
      "type": "message",
      "entity": "spobster",
      "message": "which makes this game non-valid from here on :)",
      "entity_type": "player"
    },
    {
      "id": 53,
      "type": "message",
      "entity": "spobster",
      "message": "and since we are not allowed to file bugs...",
      "entity_type": "player"
    },
    {
      "id": 54,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 55,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 56,
      "hex": "C11",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "NFL",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 57,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 58,
      "type": "run_routes",
      "entity": "NFL",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 59,
      "kind": "payout",
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 60,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 61,
      "hex": "J6",
      "tile": "57-1",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 62,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 63,
      "type": "run_routes",
      "entity": "Nord",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "I3",
              "J2"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "I3",
              "I5",
              "J6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 64,
      "kind": "payout",
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 65,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 66,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "Nord_6"
      ],
      "entity_type": "player"
    },
    {
      "id": 67,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 68,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "Nord_7"
      ],
      "entity_type": "player"
    },
    {
      "id": 69,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 70,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "Nord_8"
      ],
      "entity_type": "player"
    },
    {
      "id": 71,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 72,
      "type": "message",
      "entity": "spobster",
      "message": "@sleep, I propose you sell the CFLV to your company for 1 to enable the blocked hexes on the map and don't use the money that you received in your private wallet and also not the money you will receive in your companies treasury",
      "entity_type": "player"
    },
    {
      "id": 73,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 74,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 75,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 76,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 77,
      "type": "undo",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 78,
      "type": "undo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 79,
      "type": "redo",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 80,
      "type": "redo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 81,
      "hex": "B12",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "NFL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 82,
      "type": "undo",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 83,
      "type": "undo",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 84,
      "type": "redo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 85,
      "hex": "B12",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "NFL",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 86,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 87,
      "type": "run_routes",
      "entity": "NFL",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 88,
      "kind": "payout",
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 89,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 90,
      "hex": "K7",
      "tile": "8-1",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 91,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 92,
      "type": "run_routes",
      "entity": "Nord",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "I3",
              "J2"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "I3",
              "I5",
              "J6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 93,
      "kind": "payout",
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 94,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 95,
      "type": "sell_shares",
      "entity": "chrisdavis103",
      "shares": [
        "Nord_4",
        "Nord_5"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 96,
      "type": "par",
      "entity": "chrisdavis103",
      "corporation": "B",
      "entity_type": "player",
      "share_price": "76,3,6"
    },
    {
      "id": 97,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 98,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 99,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "Nord_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 100,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 101,
      "type": "sell_shares",
      "entity": "spobster",
      "shares": [
        "NFL_2",
        "NFL_5"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 102,
      "type": "undo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 103,
      "type": "sell_shares",
      "entity": "spobster",
      "shares": [
        "NFL_2",
        "NFL_5"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 104,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "B_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 105,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 106,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "NFL_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 107,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 108,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 109,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 110,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "B_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 111,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 112,
      "type": "undo",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 113,
      "type": "redo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 114,
      "type": "sell_shares",
      "entity": "chrisdavis103",
      "shares": [
        "NFL_3",
        "NFL_6",
        "NFL_2",
        "NFL_0"
      ],
      "percent": 40,
      "entity_type": "player"
    },
    {
      "id": 115,
      "type": "undo",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 116,
      "type": "sell_shares",
      "entity": "chrisdavis103",
      "shares": [
        "NFL_3"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 117,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "B_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 118,
      "type": "buy_shares",
      "entity": "GCB",
      "shares": [
        "B_4"
      ],
      "entity_type": "company"
    },
    {
      "id": 119,
      "type": "undo",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 120,
      "type": "undo",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 121,
      "type": "undo",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 122,
      "type": "sell_shares",
      "entity": "chrisdavis103",
      "shares": [
        "B_0"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 123,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 124,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 125,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 126,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "B_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 127,
      "type": "sell_shares",
      "entity": "spobster",
      "shares": [
        "Nord_8"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 128,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 129,
      "type": "par",
      "entity": "chrisdavis103",
      "corporation": "GCL",
      "entity_type": "player",
      "share_price": "76,3,6"
    },
    {
      "id": 130,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 131,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "NFL_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 132,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 133,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 134,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "B_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 135,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 136,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 137,
      "type": "undo",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 138,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 139,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 140,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 141,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 142,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 143,
      "city": "57-0-0",
      "slot": 0,
      "type": "place_token",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 144,
      "type": "run_routes",
      "entity": "NFL",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "A9",
              "B10"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "A13",
              "B12",
              "C11",
              "B10"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 145,
      "kind": "payout",
      "type": "dividend",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 146,
      "type": "pass",
      "entity": "NFL",
      "entity_type": "corporation"
    },
    {
      "id": 147,
      "hex": "K9",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "Nord",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 148,
      "city": "57-1-0",
      "slot": 0,
      "type": "place_token",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 149,
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 150,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 151,
      "type": "run_routes",
      "entity": "Nord",
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "I3",
              "J2"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "I3",
              "I5",
              "J6"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 152,
      "kind": "payout",
      "type": "dividend",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 153,
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation"
    },
    {
      "id": 154,
      "hex": "H4",
      "tile": "57-2",
      "type": "lay_tile",
      "entity": "B",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 155,
      "city": "57-2-0",
      "slot": 0,
      "type": "place_token",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 156,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 157,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 158,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 159,
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 160,
      "type": "buy_train",
      "price": 80,
      "train": "2-4",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 161,
      "type": "buy_train",
      "price": 180,
      "train": "3-0",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 162,
      "type": "buy_company",
      "price": 320,
      "entity": "B",
      "company": "CFL",
      "entity_type": "corporation"
    },
    {
      "id": 163,
      "type": "buy_company",
      "price": 139,
      "entity": "B",
      "company": "GCB",
      "entity_type": "corporation"
    },
    {
      "id": 164,
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 165,
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 166,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 167,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "B_5"
      ],
      "entity_type": "player"
    },
    {
      "id": 168,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 169,
      "type": "sell_shares",
      "entity": "agrajag",
      "shares": [
        "Nord_7",
        "Nord_4"
      ],
      "percent": 20,
      "entity_type": "player"
    },
    {
      "id": 170,
      "type": "sell_shares",
      "entity": "agrajag",
      "shares": [
        "NFL_1",
        "NFL_4",
        "NFL_7",
        "NFL_8"
      ],
      "percent": 40,
      "entity_type": "player"
    },
    {
      "id": 171,
      "type": "par",
      "entity": "agrajag",
      "corporation": "HSM",
      "entity_type": "player",
      "share_price": "100,0,6"
    },
    {
      "id": 172,
      "type": "par",
      "entity": "spobster",
      "corporation": "NBDS",
      "entity_type": "player",
      "share_price": "100,0,6"
    },
    {
      "id": 173,
      "type": "undo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 174,
      "type": "sell_shares",
      "entity": "spobster",
      "shares": [
        "GCL_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 175,
      "type": "undo",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 176,
      "type": "par",
      "entity": "spobster",
      "corporation": "NBDS",
      "entity_type": "player",
      "share_price": "100,0,6"
    },
    {
      "id": 177,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 178,
      "type": "buy_shares",
      "entity": "chrisdavis103",
      "shares": [
        "GCL_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 179,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 180,
      "type": "buy_shares",
      "entity": "sleep",
      "shares": [
        "NFL_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 181,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 182,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "HSM_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 183,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 184,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "NBDS_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 185,
      "type": "sell_shares",
      "entity": "spobster",
      "shares": [
        "GCL_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 186,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 187,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 188,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 189,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "HSM_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 190,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 191,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "NBDS_2"
      ],
      "entity_type": "player"
    },
    {
      "id": 192,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 193,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 194,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 195,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "HSM_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 196,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 197,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "NBDS_3"
      ],
      "entity_type": "player"
    },
    {
      "id": 198,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 199,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 200,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 201,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "HSM_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 202,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 203,
      "type": "buy_shares",
      "entity": "spobster",
      "shares": [
        "NBDS_4"
      ],
      "entity_type": "player"
    },
    {
      "id": 204,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    },
    {
      "id": 205,
      "type": "pass",
      "entity": "chrisdavis103",
      "entity_type": "player"
    },
    {
      "id": 206,
      "type": "pass",
      "entity": "sleep",
      "entity_type": "player"
    },
    {
      "id": 207,
      "type": "sell_shares",
      "entity": "agrajag",
      "shares": [
        "HSM_1"
      ],
      "percent": 10,
      "entity_type": "player"
    },
    {
      "id": 208,
      "type": "buy_shares",
      "entity": "agrajag",
      "shares": [
        "B_1"
      ],
      "entity_type": "player"
    },
    {
      "id": 209,
      "type": "pass",
      "entity": "agrajag",
      "entity_type": "player"
    },
    {
      "id": 210,
      "type": "pass",
      "entity": "spobster",
      "entity_type": "player"
    }
  ],
  "loaded": true,
  "created_at": 1592033855,
  "updated_at": 1592690538
}

**Comment by scottredracecar** [comment]
There were some updates today to fix rules and your game might have broken due to that.

**Comment by chrisdavis103** [comment]
no worry   thx.for.the.update
