### ISSUE TITLE
[1822MX] Liquidity Calculations do not include sellable NDEM Shares

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#8094]
https://18xx.games/game/90935?action=107

Mineshaft_Canary's liquidity does not include his sellable NDEM share.

**Comment by michaeljb** [comment]
Unfortunately the originally shared game has been archived. I've looked at a handful of completed 1822MX games and can't find this issue occurring anywhere. NDEM shares don't count toward liquidity until after OR1.1 is complete, so maybe that was the source of the confusion here. Closing this until the bug can be reproduced.
