### ISSUE TITLE
[1862] Liquidity Calculations Incorrect in Parliament Round (but correct in SR)

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#8095]
Liquidity calculations in a parliament round do not include all sellable shares (including presidencies): https://18xx.games/game/90389?action=249

But this gets magically fixed when entering the SR: https://18xx.games/game/90389?action=275

**Comment by roseundy** [comment]
Odd, it should be just the player cash since you can't sell during a PR.

**Comment by roseundy** [comment]
OK, found it. The PR step 'charter_auction' inherits from the 'buy_sell_par_shares' step, which has the can_sell? method. This throws off the liquidity calculations for PRs.

**Comment by roseundy** [comment]
Turns out this is a dup of #7521
