### ISSUE TITLE
1822MX: Extraneous confusing log entries during NDEM token auctions

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#8096]
During the NDEM token auction step, the game generates extraneous "NDEM skips lay/upgrade track" messages after every person's pass/bid action:

https://18xx.games/game/89531?action=818

This is really annoying to read, and takes up a bunch of space in the log window when you're trying to follow the auction.

**Comment by perwestling** [comment]
Still remains

![image](https://user-images.githubusercontent.com/2631151/225933547-7ee18d69-0ae5-414b-ba2f-2dc8dfe6849e.png)
