### ISSUE TITLE
[Rolling Stock Stars] Was not able to propose deals between different players during Phase 3

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#8099]
**What's your Game ID?**

https://18xx.games/game/90914

What steps cause the unexpected behavior?

During Turn 3, Phase 3, I wanted to offer my company WT to the corporation PR of which another player is the president. The program did not let me do this. Later, I saw that the other player bought with the PR two companies from himself. Maybe the program was busy with performing these transactions so that this may be the reason why I could not place my offer. Then, after his purchases, the player passed, and, OK, it's clear that the time window for my offer was then closed....

In the same phase, I wanted to buy  with "my" corporation DA the companies OL and MS from a third player. Here I was also not able to propose such a purchase. Maybe the reason was here too that the respective player had passed. BUT: this pass was automatic because "Ynnus controls no corporations and must pass". But it is not true that he "must pass" in this situation since he should have the opportunity to offer his companies for purchase to corporations of other players.

This "marketplace" situation in Phase 3 is at the core of Rolling Stock and should be adequately supported.

Klaus Kiermeier

**Comment by roseundy** [comment]
FWIW, I knew this was a core part of RS and I spend a great deal of time working on this. I'll take a look and see what's going on.

**Comment by roseundy** [comment]
My implementation only allows you to only offer to **buy**, not to **sell**, right?

**Comment by roseundy** [comment]
Also, as long as _any_ player has not passed in the Acquisition Round, any player may still receive a purchase offer - even if they have passed.

**Comment by roseundy** [comment]
I just talked to Toby. The rollingstock.net implementation also had the same restriction of offers only being offers to buy, not sell. You can you the chat window to negotiate a sales.

**Comment by KlausKiermeier** [comment]
I never played with the rollingstock.net implementation, but I did play a couple of times at the table with Björn Rabenstein himself, and there it was often the case that that players possessing a company offered them for sale to corporations controlled by other players.
Of course you may use the chat window to negotiate, but this is really not the same since players seem not to be used to wait until a chat is going on.

**Comment by roseundy** [comment]
Changing how offers work represents a substantial amount of work. Since using chat is a viable work-around, I am closing this.
