### ISSUE TITLE
18USA Friendly Sale Amount Mismatch

### ISSUE THREAD

**Issue by Narvinyar** [tobymao/18xx#8103]
MP goes up for sale for $120, but it's share price is only $59 so it should be going for $118 instead. Same goes for UP that is worth $46 but is only put up for $90 as the minimum bid; it should be $92. 

Chapter 14.2.3 states that minimum bid is current share price x company size 

**What's your Game ID?**

https://18xx.games/game/89952

**Comment by bentziaxl** [comment]
see #2165 , bids have to be multiple of 10 above the minimum bid in 1817/18usa.
Therefore if MP is valued at 118, the lowest legal bid 120, so the game handled this correctly.

However, UP opening bid should be 100 (multiple of $10 that is at least the minimum bid of 92)
