### ISSUE TITLE
[1871 TOP] union bank does not get added to owners total at end of game

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#8106]
https://18xx.games/game/88660

Like it says above.

**Comment by dfannius** [comment]
@BellmakerSA It looks correct to me. What do you think your total value should be?

**Comment by dfannius** [comment]
(See #7544 and https://github.com/tobymao/18xx/wiki/The-Old-Prince-1871)

**Comment by dfannius** [comment]
I think everything is working fine. Please reopen if you disagree.
