### ISSUE TITLE
Rolling Stock Stars game ID 87919

### ISSUE THREAD

**Issue by charliewilsonstaindrop** [tobymao/18xx#8108]
In turn 13 phase 3 Acquisition the company SM in receivership purchased MAD from a player without the permission of the player.  Furthermore somehow the company MAD now appears as being owned by SM and the Foreign Investor.  Looking at the time-stamps for the actions the system would seem to have carried out the purchase as soon as the phase started when the player concerned was not even logged on.  There would seem to be no reference as to how the FI managed to acquire a clone of MAD!

**Comment by roseundy** [comment]
Yep, that's weird. Investigating...

**Comment by roseundy** [comment]
I think the problem started at action=353, when charliewilsom somehow managed to put the MAD up for auction even though it was owned by the FI.
![MADx2](https://user-images.githubusercontent.com/8494213/180463147-6c526f25-b053-410f-99d2-b840a4b18847.PNG)

**Comment by roseundy** [comment]
I think I know what happened.

I recently fixed a bug where the FI wasn't being paid income correctly. I suspect that MAD was auctioned before the fix was made. After the fix was made the FI had enough cash to buy the MAD, which happens automatically. Unfortunately, the game record still had the auction and purchase in it.

I need to put checking into the code to catch this earlier. The bad new, if I did your game would fail.

At this point, your best bet is to "undo" the game until before action 353

**Comment by charliewilsonstaindrop** [comment]
Hi Steve

Thank you looking into the glitch.
Some novel activities! ;-)

I've passed the information to the other players to decide what they want to do.
Given that we are almost at the end we may decide to call the game at this point.

All the best
Charlie
"From the Sea, Freedom."


----- Original Message -----
From: Steve ***@***.***>
Reply-To: tobymao/18xx ***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author ***@***.***>
Sent: 22/07/2022 15:45:05
Subject: Re: [tobymao/18xx] Rolling Stock Stars game ID 87919 (Issue #8108)



I think I know what happened.
I recently fixed a bug where the FI wasn't 
being paid income correctly. I suspect that MAD was auctioned before the fix 
was made. After the fix was made the FI had enough cash to buy the MAD, which 
happens automatically. Unfortunately, the game record still had the auction and 
purchase in it.
I need to put checking into the code to catch this earlier. The bad new, if I 
did your game would fail.
At this point, your best bet is to "undo" the game until before action 353
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by charliewilsonstaindrop** [comment]
We have gone with rolling back the game to where I (charliewilson) managed to 
auction/buy the MAD and 
I've bought LHR instead!

Thanks again for looking into this for us.

All the best
Charlie
"From the Sea, Freedom."


----- Original Message -----
From: Steve ***@***.***>
Reply-To: tobymao/18xx ***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author ***@***.***>
Sent: 22/07/2022 15:45:05
Subject: Re: [tobymao/18xx] Rolling Stock Stars game ID 87919 (Issue #8108)



I think I know what happened.
I recently fixed a bug where the FI wasn't 
being paid income correctly. I suspect that MAD was auctioned before the fix 
was made. After the fix was made the FI had enough cash to buy the MAD, which 
happens automatically. Unfortunately, the game record still had the auction and 
purchase in it.
I need to put checking into the code to catch this earlier. The bad new, if I 
did your game would fail.
At this point, your best bet is to "undo" the game until before action 353
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>
