### ISSUE TITLE
[1866] add palace car description to info

### ISSUE THREAD

**Issue by sqookmcbat** [tobymao/18xx#8109]
The Info tab in 1866 describes what Hubs and Mail Contracts do, but not what Palace Cars do. It would be great if this could be added somewhere.

**Comment by benjaminxscott** [comment]
![Screenshot 2022-08-09 5 19 48 PM](https://user-images.githubusercontent.com/1711810/183783699-a22a9454-9d36-46cb-9e80-ba24a1c33692.png)

It looks like this was implemented at some point
