### ISSUE TITLE
[21Moon] Cannot upgrade city tile, but upgrades always permitted

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#8111]
In game https://18xx.games/game/91299 (action 419) SM cannot upgrade tile K5 (and DSE has encountered the same problem) being told "Tile must add new track connected to SP or LB"; rule 11.2.2 says "Depot tiles may be upgraded so long as the base has a route to the tile, not necessarily to new road on the tile".

I notice both the possible upgrades add no new track at all and wonder if this is related.

**Comment by roseundy** [comment]
Yep, missed this rule.

**Comment by roseundy** [comment]
OK. This is a problem with my last bug fix. That fix didn't take the 21 Moon tile laying rules into full account.

**Comment by roseundy** [comment]
This is a critical bug preventing city upgrades.
