### ISSUE TITLE
1822MX Ndem operating

### ISSUE THREAD

**Issue by magnissimus** [tobymao/18xx#8122]
https://18xx.games/game/91496

NDEM lays cube SE of Guadalajara, does not have a route after first tile placement , runs for $0 goes back before the second tile placement which would give it a route.

![89A10046-B520-4AFD-8ADA-1C8A23A6C5F7](https://user-images.githubusercontent.com/106030682/180980968-bc8d000d-85f8-49e2-8063-2b10e93a04c7.png)

**Comment by bentziaxl** [comment]
the issue not clear. What action was done? what went wrong? what's the expected behaviour?

**Comment by magnissimus** [comment]
Sorry
1: the NDEM had 4x2T and no route at the beginning of its OR, two
shareholders (Equilibrium + magnissimus). Equilibrium has PD
2. Equilibrium lays a builder cube on M18
3. The NDEM still has no route, so BEFORE magnissimus lays the track on M18
to connect to L17, NDEM runs for 0 and goes back in share value
(automatically).
4. THEN magnissimus gets his track action.

The action was undone in the linked game so that Equilibrium connected
something else giving it a route

So, I guess NDEM checks if it has a route before all track actions are done.

tir. 26. jul. 2022 kl. 15:49 skrev bentziaxl ***@***.***>:

**Comment by outsidePasser** [comment]
To view this issue "live":

Go to https://18xx.games/game/91496?action=218, clone the game to a hotseat game, then place a cube in M18.  

I will look at this shortly.  Thank you for the report.
