### ISSUE TITLE
Option to Split Chat and Log into two side-by-side windows.

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#8126]
I would love to see an option to split the very wide log/chat window on the main game screen into two side by side windows, one with chat and one with the log.  Here's an mockup of what I mean:

![Like this](https://i.imgur.com/Cuomi1K.png)

I believe this would significantly increase the quality and quantity of chatting within async games, as it creates a 'default' view where you won't miss something someone said just because you failed to scroll up.  I would go so far as to say it should be the default option for desktop users.

Obviously for Mobile there is a space constraint and so the default should be to have them combined.

**Comment by tobymao** [comment]
probably won’t due this because we have the same view in mobile as desktop

**Comment by tobymao** [comment]
https://github.com/tobymao/18xx/issues/8126

duplicate
