### ISSUE TITLE
Game in Game list is broken - can it be removed?

### ISSUE THREAD

**Issue by Witzman** [tobymao/18xx#8127]
I tried to enter Admin mode to lode the game, but its not possible and stying idle in my game list. can it be cancelled/removed?

We're sorry this game cannot be continued due to GameError: Blocking step Merger - Select corporation to merge with IC cannot process action 536
Broken action: { "type": "choose", "entity": 8923, "entity_type": "player", "id": 536, "created_at": 1654363243, "choice": "IC ($59)" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/79511?action=535)
Game Data

**Comment by dfannius** [comment]
@Witzman I see that the game has been pinned. Are you able to continue it now?

**Comment by Witzman** [comment]
@dfannius nope, i cant continue and cant close it in master mode.
Whatever i do, i get the message "This game is broken and cannot accept new actions"

**Comment by Witzman** [comment]
No. It says „game cannot take any new actions“ also when i try to close it in the tools tab.

Von meinem iPad gesendet
