### ISSUE TITLE
Profile page not working

### ISSUE THREAD

**Issue by l33twash0r** [tobymao/18xx#8142]
I tried to look up on games I have played in the past, but when I click on the Profile page I just get an error:

{"error":"User does not exist"}

**Comment by tobymao** [comment]
what's your user name?

**Comment by l33twash0r** [comment]
https://18xx.games/profile/l33twash0r

Forgot to add that to the issue.

**Comment by crericha** [comment]
Your username has a space at the end. I removed it and your profile page loads now.

**Comment by tobymao** [comment]
@crericha we should add strip() to name creation / editting

**Comment by crericha** [comment]
Yes, my thoughts exactly.
