### ISSUE TITLE
[18Rhl] Game does not load

### ISSUE THREAD

**Issue by kodemaniak** [tobymao/18xx#8147]
**What's your Game ID?**

https://18xx.games/game/92469

**How to Reproduce the Bug?**

The game does not load at all.

**Which Browser / Platform?**

I tested it on Firefox on Linux and Firefox on Android, but others have the same problem, so itś probably not a platform specific issue.

**Comment by bentziaxl** [comment]
The issue is this line https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_rhl/game.rb#L499

In this instance entity is player, so the method fails.
adding `return entity if entity.player?`  prevents this, but i'm not sure how this will behave in other instances.
@perwestling ?
