### ISSUE TITLE
Orientaion option not available

### ISSUE THREAD

**Issue by nwhyman** [tobymao/18xx#8148]
18FL
2 player, OR2, Southern RR
With rail head on the hex side between B19 and C18, the only tile option offered for C18 was gentle curve to C16. A gentle curve to D19 should also have been offered.

**Comment by dfannius** [comment]
https://18xx.games/game/92671?action=46

Worked for me in hotseat mode.

Just to be certain: you tried clicking on the hex after choosing the gentle curve, and it didn't change orientation?

**Comment by nwhyman** [comment]
Sorry, I gave you incomplete information. Yes I subsequently found that the
other orientation was possible when using a laptop, but the problem
occurred when using an android phone.
Thanks, NGW

**Comment by crericha** [comment]
Not reproducible
