### ISSUE TITLE
1822 MX bug for loans in the game end

### ISSUE THREAD

**Issue by ssansonwu2010** [tobymao/18xx#8152]
hi devs, looks like current 1822MX does not deduce loans from portfolio value in the game end.
Please also check 1822 and its small map scenario.

https://18xx.games/game/84248

![image](https://user-images.githubusercontent.com/19909099/183307063-da97d9e3-9691-4a41-8fe3-076ee963ac44.png)

![image](https://user-images.githubusercontent.com/19909099/183307077-d805572e-736c-4241-9199-93af77cff141.png)

**Comment by dfannius** [comment]
@ssansonwu2010 Which player's value do you think is calculated incorrectly and what do you think it should be instead?

**Comment by dfannius** [comment]
Oh, never mind, you closed it.
