### ISSUE TITLE
game history showing a lot of undefined games

### ISSUE THREAD

**Issue by bentziaxl** [tobymao/18xx#8157]
got to any player profile, for example this: https://18xx.games/profile/10753

Scroll down. You'll see a lot of games listed as undefined:
![image](https://user-images.githubusercontent.com/108803147/183392145-2de381a1-8602-4038-900f-4a6e6c5fc700.png)

also visible in finished games in the first page.

**Comment by crericha** [comment]
Probably due to my changes to game card rendering

**Comment by bentziaxl** [comment]
as designed? or are you planning on fixing eventually?

**Comment by dfannius** [comment]
Definitely not as designed (and he would have closed it if so)! He was just adding information to the ticket.
