### ISSUE TITLE
[1848] Game not allowing to take loans in compulsory train purchase

### ISSUE THREAD

**Issue by mrouser** [tobymao/18xx#8163]
https://18xx.games/game/93126

CAR must buy a train, and does not want to buy one over from VR.  CAR took one loan voluntarily, but needs to take out more to either buy train or go into receivership.

**Comment by bentziaxl** [comment]
fixed by #8159.
If you click on one of the trains, it will do the compulsary loans needed to buy that train.
(currently it's showing an error when doing that, but it's fixed by #8159)
