### ISSUE TITLE
[1848] Unable to trade in for a D train

### ISSUE THREAD

**Issue by ronaldau** [tobymao/18xx#8166]
https://18xx.games/game/93744?action=581
CAR has 810 and a 4+ but unable to trade in D train with $300discount

**Comment by bentziaxl** [comment]
will be fixed once #8168 is merged

**Comment by bentziaxl** [comment]
![image](https://user-images.githubusercontent.com/108803147/184281526-a2c4730b-7a8d-456b-98e6-e673fb71d37b.png)
