### ISSUE TITLE
1848 Error

### ISSUE THREAD

**Issue by Nikadim86** [tobymao/18xx#8169]
Hello, game not loading. Error. 
![Screenshot_20220811_215116](https://user-images.githubusercontent.com/111071007/184163115-fa3dee6f-c2e1-4af5-b8b2-3abbc773a47b.jpg)
game https://18xx.games/game/93120

**Comment by bentziaxl** [comment]
fixed in #8161

**Comment by Nikadim86** [comment]
Thanks!
