### ISSUE TITLE
All games - Reviewing completed games breaks

### ISSUE THREAD

**Issue by bentziaxl** [tobymao/18xx#8174]
Steps to reproduce:
1- go to any completed game, for example: https://18xx.games/game/93793
2a- click on << a few times, nothing happens
2b - click on |< to go to action 0
3 - click on >> a few times
you'll get a JS error (see bellow)
4- click on >> again. The game breaks:
We're sorry this game cannot be continued due to GameError: Blocking step Place a Token or Lay Track cannot process action 117
Broken action: { "type": "assign", "entity": "MPC", "entity_type": "company", "id": 117, "created_at": 1660232987, "target": "D6", "target_type": "hex" }

JS error from step 3:

{
    "name": "id",
    "message": "undefined method `id' for nil",
    "cause": {
        "$$id": 4
    },
    "args": [],
    "backtrace": [
        "https://18xx.games/assets/deps.js:1:14686:in `re.p'",
        "https://18xx.games/assets/main.js:1:56021:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:1:32322:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:1:213384:in `re.<anonymous>'",
        "https://18xx.games/assets/main.js:1:218378:in `F'",
        "https://18xx.games/assets/deps.js:15:51864:in `e.$each.$$p'",
        "https://18xx.games/assets/deps.js:1:16401:in `m.yield1'",
        "https://18xx.games/assets/deps.js:15:71094:in `Array.O'"
    ]
}

**Comment by bentziaxl** [comment]
Work on commit 3c5bcf297 FYI

**Comment by slapphappyjazz** [comment]
This seems similar to a bug I reported in a HotSeat game of 18GB - https://github.com/tobymao/18xx/issues/7989 - although that may just have been that the codebase was updated after the game was finished.

**Comment by bentziaxl** [comment]
looks like as designed, game review  is broken for users not in the game due to recent change that hides logs.
