### ISSUE TITLE
[18USA Broken Game] GameError: Blocking step Buy Trains cannot process action 302

### ISSUE THREAD

**Issue by ozgurbulbul** [tobymao/18xx#8175]
Got the message “We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 302
Broken action: { "type": "lay_tile", "entity": "ATSF", "entity_type": "corporation", "id": 302, "created_at": [1649628486](tel:1649628486), "hex": "D24", "tile": "57-0", "rotation": 1 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/75721?action=301)”

Unfortunately I cannot undo to see what caused this issue.

**Comment by crericha** [comment]
Can you please include the game data? Under the error, there is a copy button. Use that to copy the game data and paste it here as a file or gist.

**Comment by ozgurbulbul** [comment]
> Can you please include the game data? Under the error, there is a copy button. Use that to copy the game data and paste it here as a file or gist.

https://gist.github.com/ozgurbulbul/1d02e93945a137cab9530c91fb49154c

**Comment by crericha** [comment]
Thanks @ozgurbulbul. Should be fixed.
