### ISSUE TITLE
[1866 Broken Game] GameError: Blocking step Run Routes cannot process action 317

### ISSUE THREAD

**Issue by ozgurbulbul** [tobymao/18xx#8176]
This happened at the same time with #8175, and might be related. 

We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 317
Broken action: { "type": "lay_tile", "entity": "LV", "entity_type": "corporation", "id": 317, "created_at": [1659618812](tel:1659618812), "hex": "O17", "tile": "58-1", "rotation": 3 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/79410?action=316)

Cannot undo, and see what caused the problem.

**Comment by ozgurbulbul** [comment]
https://gist.github.com/ozgurbulbul/3e719a808c49c2960dc8b1cd102a4022

**Comment by crericha** [comment]
Should be fixed
