### ISSUE TITLE
1848 Perth / WA route problem

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8192]
It should not be possible to run a train through Perth - it should only be an endpoint.

https://18xx.games/game/93480?action=122

<img width="562" alt="Screen Shot 2022-08-13 at 22 28 48" src="https://user-images.githubusercontent.com/8732435/184523883-9bf2ee06-1aec-47c3-bbb3-b6969994b1b4.png">

Below is from the rules:

<img width="301" alt="Screen Shot 2022-08-13 at 22 29 56" src="https://user-images.githubusercontent.com/8732435/184523909-50e4f38b-cdab-4077-879b-2d680b176eb0.png">

**Comment by bentziaxl** [comment]
dup of #8186

**Comment by ChrisTheCat** [comment]
Ah, I only searched open issues
