### ISSUE TITLE
[1870 and 18JP-T]  Cannot lay tiles after undo

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#8193]
Games 91433 and 92219 are both having problems laying tiles, after an undo.  In each game, I undid a tile lay, and then I could not lay any more tiles.  It seemed to take a bit longer than usual to display the tile choices, when I clicked on the new tile.  It would let me select the tile I wanted, but when I hit the green check box, I got the error message "Blocking Step Lay Tile cannot process action ###"

Didn't matter what tile I was laying.  And the same error happened in Chrome on my computer, and in Chrome on my phone.

Perhaps this is related to the 1822MX bug report about being unable to bid after an undo?

Update...other users reporting the same bug across multiple other games.

Game 93461 as well.

**Comment by luigicoolGH** [comment]
Same problem in 1848 at https://18xx.games/game/93461.  After undo not possible trip do tile lays, error message when attempting
