### ISSUE TITLE
Can't open profile after enabling statistics

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#8202]
**How to Reproduce the Problem?**
I enabled statistics on my profile and I can't open my profile anymore.

This is my profile: https://18xx.games/profile/164

What steps cause the unexpected behavior?
1. Get excited about statistics in profile
2. Go into profile and enable statistics check box
3. Re open profile and see no changes...
4. recheck the statistics box and then locate and press Save Settings button
5. Re open profile and find error response: 

`{"error":"no implicit conversion of nil into String"}`
Don't know if it matters, but I haven't participated in any moves or games for 4+ months.  I am not sure what time period the stats are gathered from.

It seems to also happen from an Incognito window in which Im not logged in.

**Which Browser / Platform?**
Windows Chrome Desktop, up-to-date (Version 104.0.5112.81 (Official Build) (64-bit))

**Comment by crericha** [comment]
The scripts to generate statistics are still running. I'll let you know when they are done and you can try again.

**Comment by crericha** [comment]
All set. I verified your profile works.

**Comment by yoyoson** [comment]
Fantastic, thank you for the stats!
