### ISSUE TITLE
[1848] train issues

### ISSUE THREAD

**Issue by ArielAyanna** [tobymao/18xx#8203]
Trade in should be 800, not 500.
Don't think you can trade up Ghan to D.
Cannot cross buy Ghans.
EMR with multiple loans is not intuitive (should not have to click "buy" on unaffordable train.).

**Comment by bentziaxl** [comment]
do you have a link to the game with these issues?

**Comment by zexine** [comment]
I've got an example in one of my game

Game 93555

In OR 4.2, CAR trade in the 4 to D with 500. Subsequently, SAR has the bottom to trade in 2E to D

**Comment by bentziaxl** [comment]
PR fixes Cross buying 2e, and the trade in logic.

For the EMR I'm thinking of adding text with explanation instead of an additional button, would that work?
