### ISSUE TITLE
[1848] GameError: Blocking step Run Routes

### ISSUE THREAD

**Issue by barakatak01** [tobymao/18xx#8204]
We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 292
Broken action: { "type": "pass", "entity": "CAR", "entity_type": "corporation", "id": 292, "created_at": 1660617944 }

Room link https://18xx.games/game/93746?action=291

**Comment by bentziaxl** [comment]
As expected. Perth (D1) was wrong. It's an offboard city, so you can't run through it.
The COM 3 train run in your game is wrong. 
see #8186
