### ISSUE TITLE
[1817: Volatility] Loan Shark interest is skipped in liquidation

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#8211]
A company with the loanshark that goes into liquidation because it does not own a train should still pay interest to the loanshark, but it gets off free.

The loanshark private states: 

> "The owning corp must pay $10 during the "Pay Loan Interest" phase of each operating round. Failure to pay the $10 results in liquidation. The loan shark remains in force for the entire game, unless the bank purchases the owning corp's assets through liquidation."

I put the company into liquidation by not buying a train here: https://18xx.games/game/91261?action=890 and left $10 to cover the loanshark interest. Expected behavior was that the loanshark interest would still be due in the liquidation phase, here: https://18xx.games/game/91261?action=915 However, the pay interest step appears to have been skipped due to liquidation, and when the bank acquired the company it still had the $10 and distributed it back to me as president.

Now I am concerned that I jipped the loanshark, and those seem like the wrong kind of people to cross.

**Comment by crericha** [comment]
Watch out for their goons. They come out swinging and ask questions later.
