### ISSUE TITLE
Keep logs even for undone moves

### ISSUE THREAD

**Issue by mfabbri77** [tobymao/18xx#8214]
The website allows a player to undo moves even when other players have already played their moves. The undone moves leave no traces and it is sometimes difficult to understand what was done. So maybe it is possible to keep these moves recorded as well (with a different color?).

**Comment by giovandc** [comment]
It would clutter the log so much, given how often people undo actions even in their own turn.

**Comment by benjaminxscott** [comment]
Perhaps we could log undos when a user takes undo actions that affect another player's turn?

(totally agree w/ undos during a players turn being too noisy)

**Comment by mfabbri77** [comment]
It could be a good compromise.

**Comment by dfannius** [comment]
Keep in mind that logging undone actions would require actually executing them, not just ignoring them as is done now, since we need to execute actions and update the game state to know what to output in the log. So we'd have to execute the obsolete actions and then rewind to a previous state, which I'm not even sure we currently have the capability to do.

**Comment by mfabbri77** [comment]
Even better, it could be to require the approval of the player whose turn will be canceled and / or deny the "undone" beyond their turn at all (perhaps the "owner" of the game may have the right to rewind, beyond their turn, but not everyone in the game).

**Comment by dfannius** [comment]
That is a very different feature (even if it is about the same general subject) and deserves its own issue if you want to advocate for it. However you should be aware that generally requests for features of the form "require the permission of another player to perform an action" get turned down.

**Comment by mfabbri77** [comment]
Not generically "to perform an action" but to "undone an action already played by another player". Or, at least, give such permission to the game owner only. Btw, it could be enough to have a complete log, so that all the players can understand what has been done and eventually (manually) restore the game state.

**Comment by outsidePasser** [comment]
There is a "complete log", it's just difficult to read.  If you go under tools and click Show for game data, it will show the json for the game.  The undo actions can been seen in there.

**Comment by dfannius** [comment]
Yes, I meant any sort of action that requires permission when you play in person (for example, buying a train from another player).

Generating a complete log is not easy for the reasons I gave in [this comment](https://github.com/tobymao/18xx/issues/8214#issuecomment-1219680021).

**Comment by tobymao** [comment]
closing this as won't fix for now as it's too complicated to achieve given undos are completely scrubbed from the state
