### ISSUE TITLE
[1822MX] Company placed destination token even though there is no tile whatsoever in its home hex

### ISSUE THREAD

**Issue by dmitryleskov** [tobymao/18xx#8216]
https://18xx.games/game/94107?action=1157

CHP previously won a NdeM station during the privatization auction, and there is a connection to that station, but not to the home station as the rules prescribe.

**Comment by outsidePasser** [comment]
I suspect that this is the case for all the '22' games.  It's very possible for a company to have one token that connects to their destination while their home cannot.

**Comment by michaeljb** [comment]
Saved the game data to a gist - https://gist.github.com/michaeljb/d1d4b3cab89fc9440fe7eab85b83f47b

**Comment by michaeljb** [comment]
This was fixed by #8506
