### ISSUE TITLE
Profile tab leads into an error screen

### ISSUE THREAD

**Issue by notnorb** [tobymao/18xx#8217]
Post ELO update, clicking on the profile tab leads to an "error" page.

`{"error":"  from <embedded>:1:14509:in i._'"}`

Happens on Safari 15.6 (17613.3.9.1.5) and Chrome 92.0.4515.159 (Official Build) (x86_64 translated)

![Screen Shot 2022-08-18 at 17 10 58](https://user-images.githubusercontent.com/111465770/185515879-c7b06af0-e609-45ac-845c-8bdbd58bdfda.jpg)
.

**Comment by dfannius** [comment]
What is your 18xx.games username?

**Comment by ozgurbulbul** [comment]
I am also having this issue (username is oz). 

{"error":"  from <embedded>:1:14509:in `i._'"}

**Comment by dfannius** [comment]
I got the same error when looking up captainobi's profile: https://18xx.games/profile/3158

**Comment by jrt1817** [comment]
my id is daroj, and my profile has this error message:

{"error":"  from <embedded>:1:14509:in `i._'"}

**Comment by crericha** [comment]
The error message doesn't really give any detail as to what's going on and so far I am unable to reproduce in the development environment or by hand on the production server. This may be a difficult one to find.

**Comment by darkotuskan** [comment]
i get the same error, my id is darkotuskan. notably daroj (above) and i were in a game of 18usa that seems to have disappeared, not sure if that helps

**Comment by crericha** [comment]
It ended up being an unpopulated field in the database. h/t @tobymao for helping find it.

The field has been populated and the profiles should work again. Please reopen if they don't.

**Comment by jrt1817** [comment]
Thank you!

**Comment by darkotuskan** [comment]
Mine is giving me the error again, user id is darkotuskan

**Comment by ondrejbilcik** [comment]
Throwing the same error for me too, profile 12063

**Comment by jrt1817** [comment]
Error fixed, then returned :(

https://18xx.games/profile/605
