### ISSUE TITLE
Winner-take-all Elo

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#8218]
The Elo ratings are currently calculated by treating each n-player game as a collection of n-choose-2 2-player games, and rating each of those games according to the players' relative placement in the larger real game. For example, the player who finishes in second place in a four-player game has one virtual loss to the overall winner, and two virtual wins over the other two players.

I assume it would be straightforward to calculate another rating in which the all the non-winners are treated as having tied for second place as far as the virtual games go. So in the above example, the player in second place would have one virtual loss and two virtual ties. This winner-take-all Elo rating could be displayed along with the normal place-matters Elo rating.

Some people think that winning or not is the only relevant criterion for a game of 18xx, and this would allow them to look at a rating that reflected the values they play with. These players would no longer feel unduly penalized for taking risks that resulted in bankruptcy. It would also be interesting to see how well winner-take-all ratings are correlated with place-matters ratings.

**Comment by tobymao** [comment]
i don't want to complicate this with per game custom calculations, closing as won't do for now
