### ISSUE TITLE
Additional Statistics

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#8220]
I did not see a collected list of suggestions for statistics feedback, so I thought I would make one here, in no particular order.

**AVERAGE MOVE TIME** 
When it is your turn (preferably, split into different categories for live and async games)

**HEAD TO HEAD** 
When you click on another players profile, have a section that only displays games both you and the player were in, with a win/loss ratio between the two of you. 

**BANKRUPTCY COUNTER**
Adds one each time you bankrupt in any game. (mostly as a fun stat, not to be taken seriously). Could be a total of all bankruptcies on the site shown in a corner of the main page, not split off individually for players if there was real concern players would somehow avoid bankruptcy more than they already do because of a number on their profile.

**TITLE SPECIFIC STATS PAGES** 
Just as we have player profiles, it would be great to see a single page with all 1817 games played on the site by clicking on "1817". Here you could also see the total games played, average play time (live/async), average OR count, average score by player count, the highest recorded value, and even a game specific Elo leader board. 

**OVERALL ELO LEADER BOARD** 
Personally less convinced this is helpful, as it veers a bit too closely to making Elo a competition instead of a statistic, but it seems an obvious thing players might want to see. 

**COLUMN FOR TOTAL PLAYS**
Count of all plays, including ones that are archived or manually ended

**ELO RANGE INFORMATION**
Highest and lowest ELO overall or percentile

**Comment by volker18xxdev** [comment]
personal statistics,
overall and for each title display average, maximum, minimum Score.
Just to see, where i am in the 18xx-community

**Comment by kepakiano** [comment]
Chiming in on the average move time: I would also really appreciate having a means to show other players how long it takes me to make a move. Maybe it could be a rough histogram (p25/p50/p75/p99).

**Comment by volker18xxdev** [comment]
@kepakiano : yes i see them. but is 1400 Points good or bad. without comparison to best, poorist or medium no chance to identify my ranking.

**Comment by dfannius** [comment]
For each title, and also for the overall rating, the average rating is 1200.

**Comment by crericha** [comment]
@pstone1 thank you for compiling the list from Slack.
