### ISSUE TITLE
[The Old Prince 1871] Auto buy shares does not work when shares are in market

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#8224]
https://18xx.games/game/93718?action=230

When floating a company the game displays the percentage needed to float. The shares are located in the market not the IPO. When enabling auto buy until float the action fails due to the shares being in the wrong place.

Instead of trying to buy from the IPO to float the game should buy from the market first, then if no shares end the action.

**Comment by gloinul** [comment]
In an ongoing game I notice one more aspekt of this issue. If you own union bank it will attempt to buy for union bank rater than the player. From my perspektivet there are no reason to automate a purchase for union bank and it should default to do it for the player.

**Comment by gloinul** [comment]
> If you own union bank it will attempt to buy for union bank rater than the player.

This appear to be a missunderstanding from my perspective of the log. When fixing this, just keep Union Bank in mind as that is another path of possible buys that needs to be handled when enabling auto.

**Comment by ChrisTheCat** [comment]
Replicated this bug https://18xx.games/game/117887?action=247#auto

**Comment by philcampeau** [comment]
Fixed by #9299
