### ISSUE TITLE
1848 suggestions

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#8228]
- Could you move the "K" in the Perth hex from the right side to the left side, so it is away from the hex ID?
- Could you add "Tasmania" name to the Tasmania tile?

Thanks, Paul

**Comment by benjaminxscott** [comment]
Is it OK if the tasmania tile says `TAS` ?
(the tile labeling logic only really supports short names)

![image](https://user-images.githubusercontent.com/1711810/186815266-a2f8eef7-5981-45c4-9d6f-ba9e644ab7d8.png)

**Comment by pzieske** [comment]
Okay with me.
Paul
