### ISSUE TITLE
1836Jr Train buying bug

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#823]
To reproduce, have B buy the depot 2T, game won't advance. cc @jenf 

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "ACC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "E-SF",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "CdH",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "GCB",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "CFL",
      "price": 160
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "CFLV",
      "price": 220
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "corporation": "Nord",
      "share_price": "67,5,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "shares": [
        "Nord_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "shares": [
        "Nord_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "Nord_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "Nord_4"
      ]
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "corporation": "B",
      "share_price": "67,5,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "B_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "B_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "B_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "B_4"
      ]
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17,
      "corporation": "HSM",
      "share_price": "67,5,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "HSM_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "HSM_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "HSM_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21,
      "shares": [
        "HSM_4"
      ]
    },
    {
      "type": "lay_tile",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 22,
      "hex": "I5",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 23,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "lay_tile",
      "entity": "B",
      "entity_type": "corporation",
      "id": 24,
      "hex": "H4",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation",
      "id": 25
    }
  ],
  "id": "hs_snzcqfng_1592775398",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1836Jr30",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-21",
  "loaded": true,
  "result": {}
}

**Comment by jenf** [comment]
odd, that's exactly the situation i was testing, looking now.

**Comment by tobymao** [comment]
already fixed it

**Comment by jenf** [comment]
just spotted the ui bug
