### ISSUE TITLE
[18SJ] can't exchange a 5 for E train

### ISSUE THREAD

**Issue by dolfyner** [tobymao/18xx#8232]
https://18xx.games/game/92256 
I have sufficient funds to exchange a 5 for a E train but the option doesn't come up. 
![Screenshot_20220821-223141_Chrome](https://user-images.githubusercontent.com/72355011/185844532-53dffc27-236d-45bd-9090-9921b3a4232e.jpg)
Regards
Michal

**Comment by perwestling** [comment]
This was easily fixed when I looked into it. Good catch!

**Comment by dolfyner** [comment]
Hi! How long before the implementation of the fix? It's not working as yet ☺️
Regards
Michal

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dfannius** [comment]
The fix has been merged but the new code has not been deployed yet. Deploys happen every few days. https://18xx.games/about currently says "Current version [e2db5deb8](https://github.com/tobymao/18xx/commit/e2db5deb8)"; when that tag changes, the fix has been deployed.
