### ISSUE TITLE
Profiles - (At least) one player profile yields an error [not a game bug]

### ISSUE THREAD

**Issue by nienart** [tobymao/18xx#8237]
Reviewing profiles of other players in a game I joined, several display as expected. However, https://18xx.games/profile/11966 sends back this response:
```
{“error”:”  from <embedded>:1:14509:in `i._‘“}
```
I have not seen this for other profiles

**What's your Game ID?**

N/A

**How to Reproduce the Bug?**

Click the link above.

**Which Browser / Platform?**

Firefox  103.0.1 / desktop

**Comment by darkotuskan** [comment]
Same as recently closed thread #8217 (issue also is happening again with my profile darkotuskan)

**Comment by crericha** [comment]
All currently broken profiles should now be fixed. I am working on a long-term solution and will leave this issue open until that is in place.

**Comment by crericha** [comment]
All set
