### ISSUE TITLE
Action id's get reassigned when messages are hidden

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#8242]
Removing the message actions from the array makes the code reassign action numbers, which then become inconsistent. At the very least it is breaking the history, but it is very likely also breaking games with targeted undos.

It is also breaking some important stuff over at 18xx.tools, because the 18xx.games code starts behaving haphazardly.

Try navigating in the history here: https://18xx.games/game/94459?action=6

**Comment by daniel-sousa-me** [comment]
@crericha Did you have a chance to look at this?

**Comment by crericha** [comment]
I'm on vacation. Will look at it when I'm back.

**Comment by daniel-sousa-me** [comment]
Ok, I've temporarily removed the features that stopped working.

Enjoy your vacation!

**Comment by crericha** [comment]
Thanks! I have a fix. Please test out the 18xx.tools features once it is deployed.

**Comment by crericha** [comment]
I fix action ids in my method, so however they are temporarily assigned in process_action does not matter.

What games are failing?

There is a different bug where I think it includes undone steps in history movement (so the game looks stuck until you get to the next not-undone step). Is that what you are seeing or something else?

**Comment by daniel-sousa-me** [comment]
No, everything is working on 18xx.games.

I'm running an instance in my server with some modifications to extract some data. In that I'm grabbing the id while the action is being executed and that was causing problems.

I just suggested the change here, because the code may be cleaner. It's not for fixing any bug, so everything can stay as is, if you think that's better.

**Comment by crericha** [comment]
The reason I didn't do that is because I don't want to take action_ids from players submitting an action. I want the server to verify what the action_id should be. 

There is probably some logic that could be written where it detects if this is a previous action and ignores reassigning.

**Comment by crericha** [comment]
If you want to submit a PR for detecting if the action_id needs to be reassigned or not, I'm not opposed to that.

**Comment by daniel-sousa-me** [comment]
Nah, everything is fine.

Thanks for the clarification. I understand very poorly this part of the code.
