### ISSUE TITLE
[1848] Display: P1 description lists buy-in from 1-60, should be 1-40.

### ISSUE THREAD

**Issue by Akado05** [tobymao/18xx#8252]
P1 description in-game:  "No special abilities.  Can be bought in for E1-60"
P1 description in rules: "Can be bought by a Public Company for between E1-40."
P1 implementation:  "Price must be between 1 and 40"

I don't mind the "No special abilities", since that's consistent with other privates in other titles, and makes it clear, but the 60 vs 40 is confusing.  Can we fix the text to say E1-40?

**Comment by benjaminxscott** [comment]
This is fixed may not be deployed yet 

https://github.com/tobymao/18xx/pull/8246/files
