### ISSUE TITLE
[1862] - suggested new feature for stock market (house rule variant)

### ISSUE THREAD

**Issue by slemenda** [tobymao/18xx#8255]
In a Real board game played many times during past 2 yrs we start dealing Stocks for Phase B and C in a "hidden mode" (incl. permits) and these are revealed only after the purchase of the first train B and for the Phase C only after purchase of the first train C respectively so that all players do not know (and calculate or speculate) for the future companies to be open in advance.

I could write this variant during next month and push it as a version that does not affect original game.

**Comment by tobymao** [comment]
we don't accept house rules, sorry
