### ISSUE TITLE
[1848] unable to upgrade 4 to D

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#8256]
https://18xx.games/game/95369?action=632

Corp has enough cash for upgrade, all 6s are sold, but when he clicks the button to upgrade the 4 to a D, he gets an error saying "not a buyable train".

![image](https://user-images.githubusercontent.com/26125362/187461629-de158aa3-bd5a-4584-a2fd-12dc99712728.png)
![image](https://user-images.githubusercontent.com/26125362/187461750-e633475b-2a2a-42e1-a4aa-416529cdb451.png)

**Comment by bentziaxl** [comment]
upgrading is broken when at train limit, this is the root cause of the bug. Looking into how to fix

**Comment by philcampeau** [comment]
Issue still persists in our game.

**Comment by crericha** [comment]
Probably not deployed yet

**Comment by bentziaxl** [comment]
yep, about page is showing this:
Current version [f166a0de3](https://github.com/tobymao/18xx/commit/f166a0de3)

This version is prior to this fix.
