### ISSUE TITLE
[1822MX] - Stock Drop private doesn't count against certificate limit

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#8257]
https://18xx.games/game/93777#entities

As can be seen in this game, the Stock Drop private is not being counted against the certificate limit.  I can find nothing in the rules that makes an exception for this private, from the standard rule that all privates count against the limit.  For this private in particular, it seems pretty silly for it not to count against the limit, as that is the whole purpose behind the private.  The owner has to decide whether they want their company to pay $10/round, or alternatively to keep a low-paying private in their hand instead of a higher-paying share.

**Comment by outsidePasser** [comment]
This is being caused because the stock drop private is "P16", and the "P16" in base 22 doesn't count against the share limit.  A fix will come shortly.
