### ISSUE TITLE
1848 incorrect EMR message

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8263]
The EMR message should not even mention how much cash the president has, nor should it say how much cash the president needs to contribute.

https://18xx.games/game/93503?action=512

<img width="329" alt="Screen Shot 2022-08-31 at 18 37 05" src="https://user-images.githubusercontent.com/8732435/187813836-563c88f0-e795-4928-b54b-429999d4fc3b.png">

**Comment by benjaminxscott** [comment]
This is b/c the president is obligated to take loans until either the company can afford a train or it goes into receivership?
and president cannot contribute funds for this

(I think this output is based on boilerplate fwiw)

**Comment by ChrisTheCat** [comment]
The president cannot take out loans. Only the company can take out loans.
There is no mechanism for presidential contribution to EMR.
