### ISSUE TITLE
[22PNW] Inidcate minor-major company associations on the map?

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#8271]
The destinations are easily visible, but it would be nice to look at the map and see which minor company is normally associated with each major. Something as simple as changing the city name from "Newport" to "Newport (GNR)" would be more than enough. I know one of the private companies can change this but knowing where it would normally be 95% of the time would be helpful.

**Comment by outsidePasser** [comment]
I'm certainly open to having this more easily viewable - it is confusing.  I'm trying to figure out what the best way would be.

**Comment by Saintis** [comment]
Any update on this? I find it annoying having to toggle "starting map" to see where are the majors will start on the map.

Maybe a solution would be to leave the home marker visible on track, while the major is not created.

**Comment by scottredracecar** [comment]
The physical game has them color coded to their associated major.
