### ISSUE TITLE
Add statistic for number of games won

### ISSUE THREAD

**Issue by kevind1402** [tobymao/18xx#8278]
**Number of games won**

The new Elo rating is great, but a complementary and simple statistic to display in each player's profile is number of games won / number of games played. Reported per flavour (e.g. 1830, 1846 etc) as well as overall, just as it is for the Elo.

This simple stat would be very helpful, and more intuitive than Elo. (Though I accept that Elo is more sophisticated.)

I note that it is biased towards "winner-takes-all" and there are mixed views on that, but it is still one of most basic and universal stats reported in games & sports.

[For those who prefer to account for 2nd, 3rd, 4th place etc, then the count could be fractional for place. I'd be happy with that too, but it would lose the simplicity. So I'd stick with: number of games won / number of games played.]

**Comment by tobymao** [comment]
closing as we won’t be doing this
