### ISSUE TITLE
1822PNW show homes of majors on starting map

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8279]
In other 1822 games, you can easily see the home and destination of major companies on the starting map. In 1822PNW on 18xx.games, it would be great if the Associated Minors were somehow indicated - both "this is an associated minor" and also "this is the associated minor for ORNC."

(It would also be nice if this was true in the printed game, of course)

**Comment by outsidePasser** [comment]
There is a change for this in the latest PR that is waiting to roll out.  I'll keep this open until it does - then take a look and if it addresses the issue.

**Comment by outsidePasser** [comment]
@ChrisTheCat how does it look now?

**Comment by ChrisTheCat** [comment]
I like the icons, but I can't figure out why the home icons disappear when I click the "starting map" button under the map.

**Comment by BellmakerSA** [comment]
To add to what fanman80 mentioned, Minor company 20 (Walla Walla Valley Railway) would benefit from white lettering as it now has a black background.

**Comment by fanman80** [comment]
Also, I just wrote to Ken Kuhn and Scott Petersen about the color scheme for the charters and tokens as you may just be following their printing plans.  For the CPR the color makes sense to me and is easy to follow.  The others are confusing because 1) the charter has one color and the tokens are another, and 2) many companies have tokens of a similar color to the charter of another company.

**Comment by outsidePasser** [comment]
I don't see what you are saying.  ORNC:

![image](https://user-images.githubusercontent.com/11219077/188511285-3d18993f-709a-4d57-9624-18a43ef23869.png)
![image](https://user-images.githubusercontent.com/11219077/188511291-b253bcef-03cc-4bee-a76a-0f33c6bd2c31.png)
![image](https://user-images.githubusercontent.com/11219077/188511317-84bd2f94-fe63-4cc0-925e-4f0301044ff9.png)

**Comment by outsidePasser** [comment]
GNR:
![image](https://user-images.githubusercontent.com/11219077/188511444-c9629062-3f3c-4ba3-8b87-2b620a65ffe0.png)
![image](https://user-images.githubusercontent.com/11219077/188511452-b95c8802-98b5-4d96-8270-b9704ca4055c.png)
![image](https://user-images.githubusercontent.com/11219077/188511478-9120f30f-c409-4d76-9213-0294a282fc48.png)

**Comment by outsidePasser** [comment]
The color scheme came from Ken

**Comment by ChrisTheCat** [comment]
Colors look fine to me. I did notice this overlapping text.

<img width="106" alt="Screen Shot 2022-09-05 at 14 06 50" src="https://user-images.githubusercontent.com/8732435/188512516-fe12be40-2814-4418-a1cc-802c2a01db77.png">

**Comment by outsidePasser** [comment]
Yeah, I'm not really sure what can be done about that, unfortunately.

**Comment by BellmakerSA** [comment]
> I don't see what you are saying. ORNC:
> 
> ![image](https://user-images.githubusercontent.com/11219077/188511285-3d18993f-709a-4d57-9624-18a43ef23869.png) ![image](https://user-images.githubusercontent.com/11219077/188511291-b253bcef-03cc-4bee-a76a-0f33c6bd2c31.png) ![image](https://user-images.githubusercontent.com/11219077/188511317-84bd2f94-fe63-4cc0-925e-4f0301044ff9.png)

It's fixed now, it was different earlier for some reason.

**Comment by outsidePasser** [comment]
The colors were changed yesterday.  Possibly your browser had cached the old ones and hadn't refreshed it yet.

**Comment by fanman80** [comment]
OK I had a confused browser cache.  I cleared it and now things look like what you are showing.

Here's what I WAS seeing:

![Portland](https://user-images.githubusercontent.com/70117294/188518126-d18e404b-811b-4a37-9e66-5e97619b69bf.png)
![Wallula](https://user-images.githubusercontent.com/70117294/188518145-68ce4b3e-6d33-47d5-b018-017123b40ca5.png)
![Spokane](https://user-images.githubusercontent.com/70117294/188518162-6a7ee7f2-4078-4a11-aa04-3caf6502cd28.png)
![Seattle-Tacoma](https://user-images.githubusercontent.com/70117294/188518179-657aa62f-a384-42b4-95a9-e15825eb00f1.png)
![Walla Walla](https://user-images.githubusercontent.com/70117294/188518189-e6269316-ccd0-4efc-a198-efa3ce158486.png)
![Newport](https://user-images.githubusercontent.com/70117294/188518198-6cad456e-981e-4ebe-b027-b3cfaa23c007.png)
![Bellingham](https://user-images.githubusercontent.com/70117294/188518202-09065930-8e96-47c2-9c15-18265f49d7bd.png)

![Charters](https://user-images.githubusercontent.com/70117294/188518215-4bc23776-3095-433e-8561-2741471268c6.png)

But it doesn't look that way any more!  It looks good now.

Thanks!

**Comment by outsidePasser** [comment]
Icons added and colors changed

**Comment by ChrisTheCat** [comment]
Something with weights, I presume.
