### ISSUE TITLE
18LA-2 Incorrect charge for reserved token for ELA ability 

### ISSUE THREAD

**Issue by keperamaven** [tobymao/18xx#8280]
https://18xx.games/game/96245?action=267

When placing the ELA token in Culver city (C4) not connected ELA is being charge $100. the special ability is $40/$60. This has been caused at the start of OR1,1, 1.2 before track lay and after track ley at the token lay step.

**Comment by benjaminxscott** [comment]
I was able to repro this at the following game state

https://gist.github.com/benjaminxscott/43eb3ba7f34710ceaf214b3c63195f09

Note that the game referenced above did not have ELA teleporting so it did not repro the action
