### ISSUE TITLE
1822PNW issues P19, Minor Acquisition 

### ISSUE THREAD

**Issue by Avemo3** [tobymao/18xx#8286]
In our game I couldn't use P19 on either legal spot and we could not Acquire Regional or Non-Associated minors after creating a Major.

Game 96611.

When I copy/paste game code it says my post is too long
https://18xx.games/game/96611

**Comment by outsidePasser** [comment]
I need more information - at what point of the game were you trying to use P19, and which tile(s) were you attempting to use it on?  At what point were you unable to acquire regional or non-associated minors?  If you could go that point in the history and paste the URL from that point (including the "action=xxx" at the end) I would appreciate it.

**Comment by Avemo3** [comment]
It looks like the minor issue was because the major had not already operated a full OR (Trying to eat a minor in OR 3.2 and merging during merger round after 3.1). So that's likely not an issue.

Trying to lay P19 as the first track lay during phase 3 attempting to point across K19

**Comment by outsidePasser** [comment]
Do you mean K16?

**Comment by outsidePasser** [comment]
I see the problem.  Working on it.

**Comment by Avemo3** [comment]
Yes K16
