### ISSUE TITLE
1822PNW major formed after phase 5 allowed player to choose par value

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8291]
https://18xx.games/game/96627?action=1136

The rules say that 18xxperson should convert the M5 into the GNR and the par price should be 180. Instead, par prices from 55 to 100 are offered.

**Comment by outsidePasser** [comment]
I completely missed this section of the rules.  Oops,

**Comment by ChrisTheCat** [comment]
Well, that's why we have alpha tests :)
