### ISSUE TITLE
game broken 1822PNW

### ISSUE THREAD

**Issue by 18xxperson** [tobymao/18xx#8299]
The game was at a state much further than this one earlier. At some point, the game rolled back to stock round 5 and game a message of cannot proceed. The point where it went back to is https://18xx.games/game/96627?action=533s.

**Comment by outsidePasser** [comment]
A recent bug fix broke this game.  We can either delete it or roll it back to the action before that one and you can continue from there.  Which would you prefer?

**Comment by 18xxperson** [comment]
go ahead and delete it
