### ISSUE TITLE
[1871 TOP] Union Bank unable to cross buy train

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#8300]
When I click “Show trains from other players” while acting for S owned by UB, nothing happens and I’m forced to buy train from the bank instead of GT. 

https://18xx.games/game/96010?action=505

**Comment by benjaminxscott** [comment]
The console error on-click is `"undefined method `name' for nil"`

**Comment by philcampeau** [comment]
This issue is similar to one reported in issue #10997. But the issue in 10997 couldn't have happened if this issue was still occurring, so I suspect this is resolved. 

I'll close this case for now, and the investigation can continue on 10997.
