### ISSUE TITLE
[1846?] Someone sending chat while you are setting train routes resets it

### ISSUE THREAD

**Issue by jcoveney** [tobymao/18xx#8301]
I experienced this in this game: https://18xx.games/game/95014 though I suspect it may appear in other titles?

Regardless, I was trying to set the routes for my trains and it kept resetting. Very odd! I realized it was because someone was sending chats, and every time I received a message, the routes reset.

**Comment by benjaminxscott** [comment]
This is across all games and is an artifact of how the site is implemented
(I can go into detail if you want)
