### ISSUE TITLE
[1848] - Companies able to buy trains at train limit

### ISSUE THREAD

**Issue by retterermoore** [tobymao/18xx#8303]
Occurred in https://18xx.games/game/96826?action=277
https://gist.github.com/benjaminxscott/b480c563d8ef9ac2c08fcbc16f70d35c

While in phase 5, SAR and FT were able to buy a 3rd train that would put them over the train limit of 2, and then were forced to discard a train.

_The rulebook doesn't mention a train limit of 2 starting in phase 5, only a train limit of 3 starting in phase 4.  So there shouldn't be any discarding of trains.  (Although even if the train limit of 2 were accurate, the bug would instead be that SAR should not be able to buy a train if it's at the train limit)_

Edit: based on player aids it seems like the train limit of 2 is accurate.  So then there are 2 issues;
- Rulebook should be updated to have the correct information
- Companies at train limit should not be able to buy another train and then discard 1.

**Comment by retterermoore** [comment]
It may be related, but it sounds like 2Es are inaccurately counting towards the train limit as well (if not related, maybe this should be branched out into its own thread)

**Comment by benjaminxscott** [comment]
It looks like the game linked above did not contain the actions described, as they were Undone - the gist above has a repro state

--
Can't repro the 2nd reported issue, SAR was able to buy a 2E when the train limit was two (please confirm that I'm testing this correctly)
![image](https://user-images.githubusercontent.com/1711810/189235697-8acad109-84a9-4983-9188-e2b53a429dfb.png)

**Comment by retterermoore** [comment]
The 2E issue was reported to me by someone else (while discussing that bug during the game), so it's possible they were remembering it from an earlier version of the alpha.

**Comment by bentziaxl** [comment]
The code that handles upgrades, train limits and 2E is complex and went through multiple iterations to fix different bugs. 
At points it felt like putting up a tent in the wind, fixing one issue broke something else. 

hopefully I fixed all of these issues in the latest PR.
