### ISSUE TITLE
Unable to view profile

### ISSUE THREAD

**Issue by GeneralConfusion** [tobymao/18xx#8306]
**How to Reproduce the Problem?**

Attempting to access my [18XX profile](https://18xx.games/profile/9857) displays a plaintext page stating
`{"error":"  from <embedded>:1:14509:in `i._'"}`

![image](https://user-images.githubusercontent.com/42755593/189018966-7d1b38db-1c5e-4bdd-b88a-fcc8a0b2f94f.png)

**Which Browser / Platform?**
- Chrome 104.0.5112.102 (Incognito and regular)
- Desktop

**Comment by crericha** [comment]
It should be fixed. I can't find any code path that would let this happen. Unless someone else sees something, these may have to be fixed manually until pins catch-up.

**Comment by crericha** [comment]
@GeneralConfusion please confirm this is fixed

**Comment by crericha** [comment]
I just noticed the link and was able to confirm myself. The issue has been resolved.
