### ISSUE TITLE
Allow edit of game description before start

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#8310]
It would be helpful to be able to modify a game description if a game is not attracting the needed number of players. For example, one may want to change the listed timezones or suggested moves per day, Edits should not be allowed after the game start.

**Comment by saccenti** [comment]
I'd like this enhancement as well.

Curious what the reason for not allowing an edit after game start? That could be helpful sometimes as well (I use game descriptions to help organize things in my game group). Is there a downside to allowing it that is more important than the flexibility?

**Comment by 8bg** [comment]
The thought behind not allowing comment after start is to prevent the game owner from suddenly deciding they will require more turns per day and will auto-pass people who can't maintain that pace. Not sure anyone would do that, but...
