### ISSUE TITLE
1822PNW a town with no name...

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8315]
F5, L3, and O12 are missing their names. H19 might also need a name?

**Comment by outsidePasser** [comment]
F5 has a name on the official map, however, L3, O12, and the town in H19 do not.  Fixing F5.

**Comment by ChrisTheCat** [comment]
Might be nice to ask the designer if they'd like to add names to those
hexes.

**Comment by outsidePasser** [comment]
I asked him - he said he would not like to name them.  @ChrisTheCat
