### ISSUE TITLE
Shikoku 1889 - Natuto & Awaji Awarding Incorrect Amount 

### ISSUE THREAD

**Issue by Maudova** [tobymao/18xx#8318]
**Game:** Shikoku 1889
**Description:** Naruto & Awaji only produce 40 yen in stage 5+ when it should award 80 yen. 

**What's your Game ID?**
HOT SEAT GIST: https://gist.github.com/Maudova/759b850e4264fa0f9eaa432385aa9642

**How to Reproduce the Bug?**
In Operating Phase 5+ any train going to or from Naruto & Awaji produce 40 yes, when it should produce 80 yen. 

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
Google Chrome | 105.0.5195.102 (Official Build) (64-bit) (cohort: Stable)
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)
JavaScript | V8 10.5.218.7
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

</body>
</html>

**Comment by tobymao** [comment]
Only diesels produce 80 from Naruto & Awaji, notice that the gray box shows D80.
