### ISSUE TITLE
1822 PNW can't run train through Coal Mine token

### ISSUE THREAD

**Issue by Avemo3** [tobymao/18xx#8322]
https://18xx.games/game/97103

Could not run track through the $30 Coal Mine token

Could move it through the $50

**Comment by outsidePasser** [comment]
I looked at this game.  Only the CMPS is allowed to run through the token.  There wasn't a time where there was a route connected on both sides before the $50 space was there.  I backed up to about action 916 stopped the CMPS from laying the $50 token, and was able to run a 3+ train through it.  I cannot reproduce this problem.  Do you have an example of this issue?

![image](https://user-images.githubusercontent.com/11219077/189560197-9c2273d9-dd93-4bab-9344-4af54977185b.png)

**Comment by outsidePasser** [comment]
Not reproduced
