### ISSUE TITLE
1822MX Cannot Finish Game

### ISSUE THREAD

**Issue by mggarofalo** [tobymao/18xx#8325]
Gist: https://gist.github.com/mggarofalo/e7929ba1e12b91eaf220c5874365ceb8

GameID: 88288, multiplayer (pinned to f166a0de3)
Error: "finished_at is not a valid time or datetime"

Replication:
https://18xx.games/game/88288?action=1365
Click "Skip (Trains)"

**Comment by benjaminxscott** [comment]
It looks like it was able to finish? There was a temporary issue where a timestamp was in the wrong format, which probably is why it couldn't write the correct `finished_time` when the game ended

**Comment by benjaminxscott** [comment]
Sorry I think I mis-understood, it sounds like the game is technically finished but for some reason it still shows as Active? I see it listed as such

![image](https://user-images.githubusercontent.com/1711810/189552445-3ee866a9-0f6d-48ba-9777-6d78be073841.png)

**Comment by mggarofalo** [comment]
You got it. The Game Finished log message shows up but the game can’t be archived and is sitting in my Active Games list.

**Comment by mggarofalo** [comment]
@tobymao or @benjaminxscott I'm not sure which of you can do this. A handful of games like this need to be closed manually, apparently. The issue was also reported here: https://github.com/tobymao/18xx/issues/8370.

Could somebody close these games manually?

**Comment by crericha** [comment]
@mggarofalo Undo the last action and redo it.

**Comment by mggarofalo** [comment]
Thanks @crericha. Need some more coffee haha.
