### ISSUE TITLE
1822PNW 2 NP Tokens in Tacoma Game 97196 Rules Question

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#8326]
I was browsing open games and noticed in game 97196, [https://18xx.games/game/97196](url) that the NP had two tokens in Tacoma, a regular token and destination token.

![Game97196TwoNPTokensTacoma](https://user-images.githubusercontent.com/70117294/189542870-eaad86ce-da59-48fb-a720-8c00d72372ce.png)

The last sentence of rule 5.10.6 says "No more than one station token of any company may be placed in a single station."  Tacoma has a single station with spaces for three tokens.

Looking through the game log, I found that the NP was formed by merging minors 10 (home Tacoma, I12) and 20 (home Wallula, O20).  The NP placed its home token in O20 and an exchange token in I12 in merger round 6. In operating round 6.2 the NP placed its destination token in I12.

The first sentence of rule 5.10.6 refers to placing available tokens.  Does the second sentence of rule 5.10.6 not apply to placing exchange and destination tokens?

**Comment by outsidePasser** [comment]
The rulebook doesn't seem to be clear about what should happen in this case.  I have sent a question to the game designer.

**Comment by outsidePasser** [comment]
Ken responded on board game geek - I will implement what he suggested there.
