### ISSUE TITLE
1822: Minor acquisition wouldn't allow 2 shares as payment

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#8333]
In the game below, the CR is about to acquire M4.  The CR has 3 shares in treasury, but the only action the game would allow is "Receive 1 share and $130 from the CR".   The (allowable) choice of receiving 2 shares and $20 was not presented.

https://18xx.games/game/94490?action=1052

Note that I am at share limit; however, that should not affect this acquisition (I would be required to sell shares in the next SR).

**Comment by outsidePasser** [comment]
From the rules:

5.18.4 A player who is at the certificate limit may exchange a maximum of one share certificate for the acquired company president’s certificate since exchanging two shares would put the player over the certificate limit.
