### ISSUE TITLE
[1822PNW] p20 closed without option to select associated minor

### ISSUE THREAD

**Issue by RedBrand88** [tobymao/18xx#8334]
**What's your Game ID?**
96322

https://18xx.games/game/96322

https://18xx.games/game/96322?action=192

- During Operating Round 2.1 Minor 20 acquired p20 backroom deal and the private was closed but the user did not get to choose an associated minor
- the game is in Phase 2 and there are associated minors that are available to select
- there was no way to select an associated minor not in use

Here I'm given the option to acquire the minor
<img width="1792" alt="Screen Shot 2022-09-12 at 3 10 34 PM" src="https://user-images.githubusercontent.com/22983990/189760008-80f8d65f-e778-4453-a348-60332b380e0c.png">

Here the private is closed with no option to select an associated minor
<img width="1792" alt="Screen Shot 2022-09-12 at 3 10 49 PM" src="https://user-images.githubusercontent.com/22983990/189760138-0bf4c2c5-ee17-47bf-8eb1-cdd375ea3079.png">

- On Safari Version 15.5 (17613.2.7.1.8)
- macbook pro 16 inch 2019 intel chip

**Comment by outsidePasser** [comment]
This happened because the purchase of privates resolved before the purchase of minors.  I suspect the designer will want to allow you to do what you intended - I will find out and work on it.

**Comment by RedBrand88** [comment]
The game let me acquire an associated minor for minor 21 but I can't for minor 20.

**Comment by outsidePasser** [comment]
My last comment was mistaken.  The reason you didn't get to choose an association for minor 20 is that minor 20 is already associated with the NP.  Per designer, if an associated minor pulls in private 20, the private closes with no effect.  I will update what is put in the log for this case.

**Comment by RedBrand88** [comment]
I'm closing this issue because I believe minor 20 is associated with the NP major. It wasn't obvious to me because it was just a black header color instead of a white one. It looks like the non-associated minors use a white header it might be helpful to add the major's logo to the associated minors header. Apologies for the false bug report.
