### ISSUE TITLE
18Ches C-P tile lay

### ISSUE THREAD

**Issue by akh911007** [tobymao/18xx#834]
Is this a legal tile lay using the C-P private power? If he only lays 1 tile using the power, is it required to connect to the edge between H2 and I3?

Marc McDood operates LV
LV buys Columbia - Philadelphia Railroad from Marc McDood for $80
Columbia - Philadelphia Railroad lays tile #9 with rotation 1 on I3

Full game data below:

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 1,
      "company": "CV",
      "price": 205
    },
    {
      "type": "bid",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 2,
      "company": "B&OR",
      "price": 105
    },
    {
      "type": "bid",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 3,
      "company": "B&S",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 4,
      "company": "C-P",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 5,
      "company": "C-P",
      "price": 50
    },
    {
      "type": "pass",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 6
    },
    {
      "type": "bid",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 7,
      "company": "D&R",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 8,
      "company": "C-P",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "pass",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "pass",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "pass",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 13
    },
    {
      "type": "pass",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "pass",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 15
    },
    {
      "type": "pass",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 16
    },
    {
      "type": "bid",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 17,
      "company": "C&OC",
      "price": 80
    },
    {
      "type": "par",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 18,
      "corporation": "C&A",
      "share_price": "70,4,2"
    },
    {
      "type": "buy_shares",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "C&A_1"
      ]
    },
    {
      "type": "par",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 20,
      "corporation": "B&O",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 21,
      "corporation": "PRR",
      "share_price": "70,4,2"
    },
    {
      "type": "par",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 22,
      "corporation": "LV",
      "share_price": "70,4,2"
    },
    {
      "type": "buy_shares",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 23,
      "shares": [
        "B&O_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 24,
      "shares": [
        "C&A_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 25,
      "shares": [
        "B&O_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "PRR_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "LV_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "B&O_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "C&A_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "B&O_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "PRR_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "LV_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "B&O_6"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 34,
      "shares": [
        "B&O_7"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "PRR_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "LV_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 37,
      "shares": [
        "B&O_8"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 38,
      "shares": [
        "PRR_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 39,
      "shares": [
        "LV_4"
      ]
    },
    {
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 40
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 41,
      "hex": "G7",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 42,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 43
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 44,
      "hex": "F2",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 45,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 47,
      "hex": "J2",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 48,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 49
    },
    {
      "type": "buy_shares",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 50,
      "shares": [
        "LV_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 51,
      "shares": [
        "C&A_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "pass",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "pass",
      "entity": "jsterphone",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "pass",
      "entity": "jchipr",
      "entity_type": "player",
      "id": 56
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 57,
      "hex": "F8",
      "tile": "X1-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 59,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H6",
              "G7",
              "F8"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 60,
      "kind": "withhold"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "lay_tile",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 62,
      "hex": "J6",
      "tile": "57-2",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 63,
      "city": "J4-0-0",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 64,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "C&A",
      "entity_type": "corporation",
      "id": 65
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 66,
      "hex": "E3",
      "tile": "57-3",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 68,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "F2",
              "E3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 69,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 70,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 71,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 72,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "buy_company",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 73,
      "company": "B&S",
      "price": 100
    },
    {
      "type": "lay_tile",
      "entity": "B&S",
      "entity_type": "company",
      "id": 74,
      "hex": "G5",
      "tile": "9-1",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "B&S",
      "entity_type": "company",
      "id": 75,
      "hex": "F4",
      "tile": "8-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 76
    },
    {
      "type": "buy_company",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 77,
      "company": "C-P",
      "price": 80
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 78,
      "hex": "J2",
      "tile": "15-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "C-P",
      "entity_type": "company",
      "id": 79,
      "hex": "I3",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 80
    },
    {
      "type": "run_routes",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 81,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "J4",
              "J2"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 82,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 83,
      "train": "3-1",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 85
    },
    {
      "type": "message",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 86,
      "message": "Wow, does it let you lay the tile 9 there?"
    },
    {
      "type": "message",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 87,
      "message": "I think that's a bug - I believe they have to be connected?"
    },
    {
      "type": "message",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 88,
      "message": "Not actually sure of the rules when you only lay 1 of the 2 tiles that the private allows"
    },
    {
      "type": "message",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 89,
      "message": "I don't know, If anyone has a proper ruling I can undo"
    },
    {
      "type": "message",
      "entity": "Marc McDood",
      "entity_type": "player",
      "id": 90,
      "message": "I'll undo, the way I read the minor, it shouldn't let me place only one, it says two connected, no mention of only 1 tile"
    },
    {
      "type": "undo",
      "entity": "Andy008",
      "entity_type": "player",
      "id": 91
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 92
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 93
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 94
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 95
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 97
    },
    {
      "type": "message",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 98,
      "message": "I'll clone the game and put in a bug ticket"
    },
    {
      "type": "undo",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "message",
      "entity": "akh911007",
      "entity_type": "player",
      "id": 100,
      "message": "seems like int shouldn't allow it?"
    },
    {
      "type": "lay_tile",
      "entity": "C-P",
      "entity_type": "company",
      "id": 101,
      "hex": "I3",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 102,
      "hex": "J2",
      "tile": "15-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "LV",
      "entity_type": "corporation",
      "id": 103
    }
  ],
  "id": "hs_jnnnilkc_2449",
  "description": "Cloned from game 2449",
  "user": {
    "id": 0,
    "name": "You"
  },
  "players": [
    {
      "id": 121,
      "name": "jchipr"
    },
    {
      "id": 1408,
      "name": "Andy008"
    },
    {
      "id": 1760,
      "name": "akh911007"
    },
    {
      "id": 1554,
      "name": "Marc McDood"
    },
    {
      "id": 2022,
      "name": "jsterphone"
    }
  ],
  "max_players": 6,
  "title": "18Chesapeake",
  "settings": {
    "seed": 1.931216787134132e+37
  },
  "turn": 3,
  "round": "Stock Round",
  "acting": [
    1408
  ],
  "result": {},
  "loaded": true,
  "created_at": "2020-06-22",
  "updated_at": 1592852313,
  "mode": "hotseat"
}

**Comment by tobymao** [comment]
it's only required to connect with the other lay

**Comment by scottredracecar** [comment]
You have to lay both tiles. The rule says lay two tiles, not up to two
tiles.

**Comment by akh911007** [comment]
Should this be reopened and looked into more?

**Comment by tobymao** [comment]
no i'm not going to fix it anytime soon

**Comment by wcraigtrader** [comment]
Per the rules I have to lay two tiles; that's fine. There's nothing in the rules that says they have to be connected, and I'd like to lay two #8 tiles on H2 and I3 connecting Harrisburg and Philadelphia to Strasburg.

![18chesapeake-otr-c-and-p](https://user-images.githubusercontent.com/972263/204095564-5f1cce1c-bb35-42d3-89bb-70618c30fa13.png)

Alas, the game insists that they be connected.

[18chesapeake-otr-c-and-p-json.txt](https://github.com/tobymao/18xx/files/10096490/18chesapeake-otr-c-and-p-json.txt)
