### ISSUE TITLE
 [1848] 2E should not count towards train requirements when e-buying

### ISSUE THREAD

**Issue by plfires** [tobymao/18xx#8343]
**What's your Game ID?**
https://18xx.games/game/94054?action=793

https://gist.github.com/benjaminxscott/703e76309243ccb6866a43c377c8e09a

In OR8.2，the VR has no train and only has 100 bucks
It is able to take a loan and ends up with 200 bucks, enough to buy a Ghan (2E) 

Possible Issues
1 2E should not count as a train pursuant to 8.1 in the rules
2 The VR president indicated that after he took a regular loan, it forced him to buy a 2E

**Comment by benjaminxscott** [comment]
I was able to repro the first issue (1) 

I was not able to repro (2) , if the president clicks the 'buy' button on a 6 train then it behaves as intended where it auto-takes loans until the company either is thrown into receivership or has enough to buy the 6 train

**Comment by benjaminxscott** [comment]
Another issue (3), if a company is thrown into receivership when it tries to buy a train, that train does not leave the depot

**Comment by plfires** [comment]
> edit: nope i'm wrong, 5.4.4. dictates that when the 2nd company is thrown into the BoE it exports the cheapest permanent
> 
> Another issue (3), if a company is thrown into receivership when it tries to buy a train, that train does not leave the depot
> 
> Repro'd with the same game state



> I was able to repro the first issue (1)
> 
> It's not clear to me from the rules whether the president of VR should even be able to buy a 2E in that situation, so presumably it's OK for them to buy a 2E and then buy a different train
> 
> I was not able to repro (2) , if the president clicks the 'buy' button on a 6 train then it behaves as intended where it auto-takes loans until the company either is thrown into receivership or has enough to buy the 6 train

benjaminxscott，hi
my meaning is a little difference
1 in normal issue, 2e do not count as train. i try touse hotseat game and confirm it. the bug only happened when force buying. after buy a 2e. program think is ok and let turn pass.

so i means bug is "2e count as train at force buying"
2 .maybe vr president do not know should click bought 6 train. that  is fine.
