### ISSUE TITLE
[Harzbahn 1873] Enabling Pass in Draft while winning Initial Auction prevents other players from passing in the auction.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#8345]
https://18xx.games/game/97726?action=8

Harzbahn begins with a bid for turn order, followed by a draft of mines and concessions.

Scenario: physicssquirrel bid 90 in the initial auction, and then enabled "Pass in Draft until premium is 20"

Expected: physicssquirrel should be forbidden from setting "Pass in Draft" because he is currently winning the auction and if he wins the auction, he may not pass; he must buy something. 

Actual: Skanadron is presented the option to overbid or pass, but the pass button does nothing and hangs the browser tab.

**Comment by magnusrk-ch** [comment]
The autopass action shouldn't actually pass if the user isn't allowed to pass, should be a simple fix.
