### ISSUE TITLE
[1822PNW] Starting a major directly in Phase5+ does not remove associated minor token reservation

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#8352]
https://18xx.games/game/97938?action=988

GNR was started directly in the previous SR, but the M5's token reservation was not subsequently removed. If the GNR's home had not been already upgraded, it's home token would not have gone down and would not have been able to lay track or do anything other than being forced to buy a train.

**Comment by ChrisTheCat** [comment]
In this game, SWW is unable to lay track because the M8 reservation was not relinquished. Also, the M20 token reservation is still blocking, even though M20 was removed via Back Room Dealing.
