### ISSUE TITLE
[1822PNW] 4 bugs

### ISSUE THREAD

**Issue by GregH87** [tobymao/18xx#8353]
[18xx.games/game/97996](url)

1. CPR wasn’t able to absorb M6 through ferry connection (rule 5.7.14), even after building appropriate track.
2. shares in majors not floating up for sold out at end of SR
3. Started majors in phase 6 (SWW, GNR), floated on presidency as opposed to after 50% sold
4. GNR first operating turn, home token didn’t come out, couldn’t lay track. This forced us to end the game

**Comment by benjaminxscott** [comment]
fwiw (2) and (3) are fixed but not deployed yet

**Comment by outsidePasser** [comment]
(1) CPR never built the appropriate track in that game - it needs to have track that exits out to the west of D11.
(4) is a duplication of #8352

**Comment by outsidePasser** [comment]
I see that the tile in D11 for (1) was built and then undone.  Looking further.

**Comment by outsidePasser** [comment]
Fixed, waiting deployment
