### ISSUE TITLE
1822PNW - more phase 5 issues

### ISSUE THREAD

**Issue by jrt1817** [tobymao/18xx#8369]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

https://18xx.games/game/98394

**[18:28] EdFactor buys a 10% share of SWW from the Treasury for $100**

SWW was formed in merger round after 5s were bought.  It started the SR w/ $600 and 6 shares in the treasury.  But when shares were purchased during the SR, $0 went into the company treasury.

Sorry, I don't understand how to do all this below.  I hope this is enough info.
==========================================

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by outsidePasser** [comment]
I see the bug in the game on 18xx.games, but I cannot reproduce it yet.  It may already be fixed - I will continue to investigate.

**Comment by outsidePasser** [comment]
Found it - fix incoming.
