### ISSUE TITLE
[21moon] Revenue between 0 and half share price causes failure

### ISSUE THREAD

**Issue by Snotty128** [tobymao/18xx#8376]
https://18xx.games/game/92278

I’m trying to get my LB trains to intersect at e5 but the game throws a “undefined method ‘[]’ for nil” error and rearranges my trains into an illegal run. It the warns me that “ Must visit LB or intersect with another LB route that does” 

As far as I understand the rules, one LB train needs to run through the LB, and the other LB train needs to meet it at another station/depot. I can get the game to continue if they both run out of the LB, but not if they meet at another depot.

I’m on iPadOS 15.7.
![IMG_4072](https://user-images.githubusercontent.com/114303347/192108102-21954f9f-833b-467a-9150-a5ad60f2353c.png)

![IMG_4074](https://user-images.githubusercontent.com/114303347/192108117-d1f2f287-8bc1-49e3-a9fa-09c779f89d26.png)

![IMG_4077](https://user-images.githubusercontent.com/114303347/192108120-9abac1b5-b056-4693-9c4a-acf862692f43.png)

**Comment by roseundy** [comment]
I can't reproduce this in hotseat mode. I will investigate more.

**Comment by Snotty128** [comment]
I get the same problem in hotseat/clone game mode.

I try to run:
![IMG_4078](https://user-images.githubusercontent.com/114303347/192109141-43e172b8-ee4c-4782-8890-df474800fd54.png)

but it gives me an error and rearranges my trains to:


![IMG_4079](https://user-images.githubusercontent.com/114303347/192109175-e123befe-03b2-4921-8b75-d8f5b876cdef.png)

curiously, if I auto route it gives me what looks like an illegal route, but actually let’s me run it:

![IMG_4080](https://user-images.githubusercontent.com/114303347/192109193-020312cf-0605-4ff8-8ecb-6df4a88da949.png)

I’ll go try this on pc in case it’s safari that’s the problem

**Comment by roseundy** [comment]
OK. A different route worked, so it's specific to the one you selected. Debugging now.

**Comment by roseundy** [comment]
The bug doesn't have anything to do with the specific route, but occurs any time the revenue is between 0 and half the share price. I was missing an "else" statement.

I can't believe this is the first time this has been encountered. I suspect people ran into this but didn't bother telling anyone.

**Comment by Snotty128** [comment]
That fixed it. Absolute legend
