### ISSUE TITLE
Fort Wayne "not connected"

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#838]
Can't lay a tile on Fort Wayne in the attached hotseat 1846 due to getting "not connected" error.

Problem persists after reloading the page.

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 1,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 3,
      "company": "SC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 4,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "corporation": "PRR",
      "share_price": "100,0,10"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "corporation": "IC",
      "share_price": "100,0,10"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "corporation": "GT",
      "share_price": "100,0,10"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 11,
      "hex": "B16",
      "tile": "6-0",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 12,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 13,
      "hex": "G9",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 14,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 15,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "sell_shares",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 16,
      "shares": [
        "PRR_1",
        "PRR_2"
      ],
      "percent": 20,
      "share_price": 90
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 17,
      "hex": "E19",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 18,
      "hex": "E17",
      "tile": "293-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 19
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 20,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 21,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 22
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 23
    },
    {
      "type": "sell_shares",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 24,
      "shares": [
        "IC_1",
        "IC_2"
      ],
      "percent": 20,
      "share_price": 90
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 25,
      "hex": "J4",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 26,
      "hex": "I3",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 27,
      "city": "I5-0-0",
      "slot": 1
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 28,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 29,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 30,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 31
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 32
    },
    {
      "type": "sell_shares",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 33,
      "shares": [
        "GT_1",
        "GT_2"
      ],
      "percent": 20,
      "share_price": 90
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 34,
      "hex": "C13",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 35,
      "hex": "C11",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 37,
      "train": "4-0",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 38,
      "train": "4-1",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 39,
      "hex": "C9",
      "tile": "6-2",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 40,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 41,
      "hex": "H6",
      "tile": "9-4",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 42,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 43
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 44,
      "hex": "E17",
      "tile": "295-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 45,
      "hex": "E15",
      "tile": "9-5",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "type": "run_routes",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 47,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "F20",
              "G21"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "F20",
              "E19",
              "E17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 48,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 49
    },
    {
      "type": "pass",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 50
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 51
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 52,
      "hex": "G9",
      "tile": "14-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 53,
      "hex": "G11",
      "tile": "9-6",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 55,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "I5",
              "I3",
              "I1"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "G7",
              "H6",
              "I5"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 56,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 57
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 59,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "B18",
              "B16"
            ]
          ]
        },
        {
          "train": "4-1",
          "connections": [
            [
              "C15",
              "C13",
              "C11",
              "C9"
            ],
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 60,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 62
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 63,
      "shares": [
        "PRR_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 64,
      "shares": [
        "IC_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 65,
      "shares": [
        "PRR_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 66
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 67
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 68
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 69,
      "hex": "D8",
      "tile": "7-0",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "MS",
      "entity_type": "minor",
      "id": 70
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 71,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 72,
      "hex": "G13",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 73,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G7",
              "G9"
            ]
          ]
        }
      ]
    },
    {
      "type": "sell_shares",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 74,
      "shares": [
        "PRR_5",
        "PRR_6"
      ],
      "percent": 20,
      "share_price": 80
    },
    {
      "type": "lay_tile",
      "entity": "PRR",
      "entity_type": "corporation",
      "id": 75,
      "hex": "E13",
      "tile": "9-7",
      "rotation": 1
    }
  ],
  "id": "hs_nnzpehar_1592868384",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1846",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-22",
  "loaded": true,
  "result": {}
}

**Comment by tobymao** [comment]
it's because you're trying to lay a token there
