### ISSUE TITLE
[18SJ] Full cap company gets revenue from IPO shares instead of treasury

### ISSUE THREAD

**Issue by magnusrk-ch** [tobymao/18xx#8381]
Example: https://18xx.games/game/93437

KFJ is a full cap company with 4 shares in IPO. When it runs, those 4 shares pay to KFJ's treasury. They should not.

Additionally, if KFJ redeems a share, so it has 3 shares in IPO and 1 share in treasury, it gets revenue for 3 shares, meaning the treasury share does *not* pay. It should.

> Dividends for shares in a corporation’s treasury are paid to the treasury. Dividends for shares in the Bank Pool or initial offering are kept by the bank.

**Comment by magnusrk-ch** [comment]
I don't think this is quite right. The commit makes it so full-cap companies can never gain dividends, but the rules allow any company to redeem shares, so a full-cap company could acquire treasury shares that should then pay dividends.

**Comment by perwestling** [comment]
You are right. Now corrected so that in base games treasury shares do pay, IPO/Bank do not.
