### ISSUE TITLE
[1849] Auto-pass should not disable when double share available in stock I've previously sold

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#8384]
See for example complete game https://18xx.games/game/94678?action=455

This occurred several times in the recent round of the 1849 tournament.  I selected auto-pass in the stock round and the auto-pass was disabled when a double share became available, even though I wasn't able to buy that share because I'd previously sold stock in that company earlier in that stock round.  This kept slowing down the game because I had to log on and reselect the auto-pass option.  

The simple fix would be to add a test to the code that checks for a double share being available, to additionally check that the player hasn't previously sold stock in that company earlier in the SR.

Thinking about edge cases, I guess a player could have an option to act if the double-share had been in the market and they have another share in the company that they could sell to make the double share unavailable for the next player.  I'm not sure that would be worth coding for.  

If you do want to code for this, then I think the pseudocode would be:
```
if a double share available
      if the player has not previously sold stock in that company then autopass=off
      else if the double share is in the treasury then autopass=remain
             else if the player owns stock in the company then autopass=off
                   else autopass=remain
```

**Comment by michaeljb** [comment]
Probably related #6940
