### ISSUE TITLE
Autopass in Merger Round (1822PNW)

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#8389]
Obviously this is lower priority than bug fixes or rule implementation issues - however, it would be nice to have an autopass option for the merger round, similar to what is available for 1817.

**Comment by roseundy** [comment]
Is there a specific title you are referring to, or all games with merger rounds?

**Comment by outsidePasser** [comment]
Merger rounds tend to be quite a bit shorter in PNW than in 1817.  I'm very unlikely to implement this.
