### ISSUE TITLE
[1846] C&O can't buy the Big4 2T from IC

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#839]
Player 3 opened the IC in SR1, bought in the Big4 in OR1.1, and also bought a 3/5 and a 4T. In SR3, Player 3 opened the C&O. The C&O is offered many trains to buy (including 2Ts from other companies), but only the 3/5 and the 4T from the IC -- the 2T that IC acquired when it bought in the Big4 is not available for sale to C&O, and it should be.

Game data: [CO-cannot-buy-Big4-2T-from-IC.txt](https://github.com/tobymao/18xx/files/4816177/CO-cannot-buy-Big4-2T-from-IC.txt)

**Comment by tobymao** [comment]
isn’t that in the rules?

**Comment by wcraigtrader** [comment]
Once the minors have been bought in, their trains are just regular 2Ts, and can be bought/sold between companies, the same as any other 2T.

**Comment by tobymao** [comment]
really? ok
