### ISSUE TITLE
1822PNW Game End Max Stock Price Didn't Work

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#8393]
In game 97393, https://18xx.games/game/97393 , the bank broke in OR 10.1 which triggered game end at the end of OR 10.2.  However, the SWW hit the end game trigger stock price in OR 10.1 which should have triggered the end of game at the end of that OR.  The game continued to OR 10.2.

**Comment by outsidePasser** [comment]
According to the rules, this is correct behavior:

7.1.7 Once the game end has been triggered, the game will end at the indicated time, even if another end condition is triggered after the first.

**Comment by fanman80** [comment]
OK.  Thanks.
