### ISSUE TITLE
[Shikoku 1889] Skips option to convert Dougo for a share

### ISSUE THREAD

**Issue by Boomcoach** [tobymao/18xx#8396]
https://18xx.games/game/99440

I purchased the Dougo Railway during the initial auction.  I had enough money to buy 4 shares of the Iyo Railway and was going to use the power of the Dougo to get a 5th share and float the Iyo.  After I purchased the 4th share, I was automatically skipped during the next stock action with the message "Boomcoach has no valid actions and passes".

I cloned the game, and undid the game to my 4th stock action.  I was allowed to convert the Dougo at this time, so it is handling the conversion correctly.  It simply does not recognize that owning the Dougo means that the player does have a valid stock action available.

**Comment by Maxwell-Frank** [comment]
A bug as old as time... It's unlikely to ever get changed at this point.
