### ISSUE TITLE
18EU - pullman vanished

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#8398]
game ID :  97778

https://18xx.games/game/977787`

During the final merger round after the 5 train was purchased the SNCF lost a pullman when the 10 merged into the FS and was forced to discard its 3 train (because the FS had a 3 and a 4 already)

the action that caused it is here
https://18xx.games/game/97778?action=460

**Comment by philcampeau** [comment]
Game is archived, unable to verify. If the problem still exists, it'll be reported again.
