### ISSUE TITLE
[18GB] Sub-optimal auto-routing with OO cities?

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#8410]
https://18xx.games/hotseat/hs_pjdayupb_99513?action=279

At this point in the game, LNWR is running a 4+2 and 3+1.  Auto-routing suggests a route for the 4+2 that doubles back through the OO tile on Bristol.  The potential E-W bonus for running to Plymouth is not included.  This gives a final income of 300, which is sub-optimal.

A better route would be to run the 4+2 from London-Birmingham-Bristol-Plymouth and the 3+1 London-Bristol-Taunton.  This would score 350 instead of 300.

I wonder whether the auto-routing algorithm is not taking account that a run back through different stations on an OO tile will only generate income from one of the stations.  The algorithm that calculates the actual income is correct but I'm wondering whether the route-finding algorithm isn't "aware" of this rule?    I could of course be wrong and the bug may be something else entirely.

**Comment by andypymont** [comment]
The hotseat game is saved in your browser's local storage and so not accessible to other users. Can you please copy the game data (from Tools tab), [paste it into a gist](https://gist.github.com/) and share here? Then I can use your example to explore what is happening. Thanks!

**Comment by slapphappyjazz** [comment]
Try this action in the currently live game: 
https://18xx.games/game/99513?action=188

I took a clone when looking back to find the bug and then forgot to 
switch back to the live game.

Dave.

**Comment by slapphappyjazz** [comment]
Not a bug - the auto-routing algorithm is working OK, the routes shown were left over from the previous turn when the LNWR token wasn't on the board and the player didn't clear the existing routes.
