### ISSUE TITLE
[18GB] Text for GN and MC privates

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#8411]
The text for the GN and MC privates should make clear that they give an additional station token, i.e. they don't use one of the corporation's existing tokens.

A possible change would be to replace "allows a corporation to lay a Station Marker" with "allows a corporation to lay an additional Station Marker".

**Comment by andypymont** [comment]
As discussed by email earlier, I had drafted this change:
https://github.com/andypymont/18xx/commit/666dd1b58509c6431895fe440e8a9e5e5d97e221

Let me know if there are any issues with this wording.

**Comment by slapphappyjazz** [comment]
The new wording looks fine to me. But while you're changing this text, 
let's take the opportunity to change "Station Marker" to "station token" 
(and "marker" to "token" throughout), as this is the term used in the 
2nd edition rulebook.

Also, the fourth sentence should begin "The token is free" instead of 
"The station is free".

Thanks,

Dave.
