### ISSUE TITLE
 [1822PNW] Cannot buy 2T directly as a minor company's first train

### ISSUE THREAD

**Issue by GAFBlizzard** [tobymao/18xx#8415]
For a minor company's first train, the depot only shows L-trains, not the 2T version.

https://18xx.games/game/98918

From the rules:
5.14.8 The L and 2-trains are printed double-sided. When buying an L/2-train, the company’s president chooses which to buy.

Rule 5.15.3 says for a forced train purchase, a company must buy the cheaper version (L-train).  However that rule begins with "If such a company cannot afford to buy a train from the bank pool or bank..."  That does not seem to apply in this case, since a minor company has $140 and could afford a $120 2T directly.

**Comment by outsidePasser** [comment]
In that game, you are stopped during 16's first run, which is I assume what you are referring to.  You cannot purchase anything except for an L-train during housekeeping.

5.5.3 A minor company (only) may buy an L-train, if any remain available for purchase from the bank or bank pool.

**Comment by GAFBlizzard** [comment]
Rule 5.5.3 says "A minor company (only) may buy an L-train, if any remain available for purchase from the bank or bank pool."

I am not sure if this "only" means "only minor companies may buy an L-train", or "minor companies can only buy L-trains and never 2T's on their first turn".


However if the intent were to ban buying a 2T on a minor company's first turn, rule 5.5.4 does not make sense to me:


"5.5.4 Note that when emergency money raising to buy a train from the bank or bank pool, the cheapest available train must be purchased (see section 5.15 Emergency Money Raising). Thus, a minor company starting with $100 in its treasury (for example) cannot choose to buy a 2-train at the end of its turn using emergency money raising, but must buy an L-train."


If a minor company could NEVER buy a 2T on its first turn, there would be no need for the above paragraph.

**Comment by outsidePasser** [comment]
Buying a train during housekeeping is not an "emergency train purchase".  Those rules do not apply to housekeeping.  Rule 5.5.4 talks about buying "at the end of its turn", which is not housekeeping.  Admittedly, that is a poor example, because it would mean that the minor didn't purchase an L-train during housekeeping for some reason.  

Minor companies absolutely can buy a 2T on their first turn - but if they want to do that, they have to do it at the end of the turn, not during hosuekeeping.

**Comment by GAFBlizzard** [comment]
Thank you for your patience.  I understand now.  The part I missed was that an L-train is the ONLY type of train that can be purchased during housekeeping.

However I agree, 5.5.4 is a bit misleading because the emergency fundraising situation applies to the end of the turn, not housekeeping, as far as I can tell.

**Comment by outsidePasser** [comment]
Thanks for reporting it anyway, just in case. :)
