### ISSUE TITLE
1848 Additional Information Reques

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#8417]
1. Can the Information tab under "Game Phases" and "Status" list the Basic Income for the Bank of England? (0 / 100 / 200 / 300). I can never remember without pulling out the rules what those are.

2. Can the Spreadsheet tab list what the BOE's OR History is and what it paid out in Revenue? 

3. Can the Market Page list the Stock Price Movements? Something similar to 1849's implementation on 18xx.games...  just as a reminder.

**Comment by bentziaxl** [comment]
1- there's a tile on the map, bottom right corner:
![image](https://user-images.githubusercontent.com/108803147/194498452-3f48ef61-08cc-4b52-bf75-855af8244fcb.png)

**Comment by bentziaxl** [comment]
3-> Wow, cool. Yes that should be there for every game, so useful!
