### ISSUE TITLE
18VA train buying problem

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#8418]
Game 97389, Virginia 11Sept
https://18xx.games/game/97389
The WMR wants to buy a 4G with its $400 plus $100 from Rich. But the game says that WMR cannot buy the train because it only has $400.  Also note that above the Available Trains for the WMR it shows the Tredegar Iron Works, which actually belongs to the VR.  And that if you "Skip (Trains)" it lets you, but the rules require companies to have a train.

**Comment by pzieske** [comment]
In order for the game to proceed, we had the WMR buy a 3G over from Rich's VR, and then the VR buy a 4G.  Not what was desired, but we didn't know how long it would take to fix the problem (or if the fix would break the game).

**Comment by philcampeau** [comment]
This would have been at [action 417](https://18xx.games/game/97389?action=417)

WMR did not have a legal route, it wasn't allowed to emergency fund since it didn't require a train.

**Comment by pzieske** [comment]
This is not correct - rules 4.6 says each corporation must have a train,
whether it has a legal route or not.

Paul

**Comment by philcampeau** [comment]
Ah yes. That's a different issue then. 

I'll take a look.
