### ISSUE TITLE
[1848] game terminated prematurely 

### ISSUE THREAD

**Issue by adambaig** [tobymao/18xx#8426]
https://18xx.games/game/96726?action=124

The game was advancing to near the end but it reverted to an early OR on a turn for an out of commission company.   This message is displayed at the top of the page:

We're sorry this game cannot be continued due to GameError: 57 is not upgradeable to 238
Broken action: { "type": "lay_tile", "entity": "SAR", "entity_type": "corporation", "id": 125, "created_at": [1663594195](tel:1663594195), "hex": "G6", "tile": "238-0", "rotation": 5 }

**Comment by Bmore84** [comment]
Same error here https://18xx.games/game/96062?action=112
