### ISSUE TITLE
1825 can't create games with less than 4 players

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#8427]
i want to create a game 1825 with unit 2+3, the checkbox was not available. 
All units with less than 4 players weren't accessable, see screenshot from today.
![grafik](https://user-images.githubusercontent.com/80693707/194308978-e67582a1-e719-433b-846f-de74cb91d7d7.png)

**Comment by roseundy** [comment]
Those options were filtered out since Max Players was set to 9. If you reduce that number, more options - including Units +3 - become available.
