### ISSUE TITLE
[1862] - Insufficient monies to par company but bid during Parliament Phase isn't disallowed

### ISSUE THREAD

**Issue by CHDJHub** [tobymao/18xx#8432]
[1862] - Insufficient monies to par company but bid during Parliament Phase isn't disallowed

Id: 99160 (We undid to the point before I bid so I could pass)
Description: I can't par but still able to bid for company during parliament phase (buttons do not show up).
https://imgur.com/a/SKDcUyI

Rules:
"A player who has less than £162 (i.e. three times the lowest available par price) plus the amount of the smallest legal bid must pass. A player who is on or above the certificate limit must pass. A player who has obtained a Parliamentary Charter in this round may not start an auction, but may bid in an auction started by another player."

**Comment by roseundy** [comment]
min_bid is not being calculated correctly
