### ISSUE TITLE
[1822PNW] Cannot use Boom Town to replace yellow straight hex on H13 river crossing

### ISSUE THREAD

**Issue by GAFBlizzard** [tobymao/18xx#8436]
In OR 8.1 here, though the game has moved on:  https://18xx.games/game/98918

I wanted to use Boom Town to replace the yellow straight hex on H13.  This is the hex with a river crossing fee, but Boom Town just says "Close this private company to upgrade any plain yellow track tile to the special boom town tile (PNW3). This tile ignores any tile's normal tile placement restrictions."

After the game lags for a bit, I get a very strange error:  "undefined method 'spend' for <Engine::Company: P18>"

Any other yellow hex seems to upgrade with Boom Town without issue.

**Comment by outsidePasser** [comment]
I'm not sure if the river crossing fee is considered a "normal tile placement restriction".  In either case, the game shouldn't behave like this.  Asking the game author.

**Comment by GAFBlizzard** [comment]
Awesome, thanks!

**Comment by outsidePasser** [comment]
The game author agrees that boomtown can mitigate the river crossing fee.  Fix incoming.
