### ISSUE TITLE
[1856] Shares in spreadsheet for CGR are wrong

### ISSUE THREAD

**Issue by zeitlinger** [tobymao/18xx#8438]
https://18xx.games/game/98691

![image](https://user-images.githubusercontent.com/2832627/194863650-e4194947-22eb-4012-b4c4-741499386d78.png)

"Shares" should show the total percentage a player has, so 8 means 80%.

For player "Gerd" for example, this should be 2 (20%), because the player owns the 10% director and 2 5% certificates (which count as 0.5 certificates) - but "Shares" actually say "4".

**Comment by outsidePasser** [comment]
The rulebook calls them "5% shares".  I believe what is currently implemented is accurate.

**Comment by zeitlinger** [comment]
In my understanding, shares describes the percentage you  own, and certificates is about the certificate limit.
The rules refer to 5% and 10% shares, which is naturally summed up as 20%.
The fact that shares don't have a unit in the ui leaves room for interpretation. 
The strongest argument is to use the principle of least surprise - which suggests that shares of different corporations should be comparable - and a percentage can easily be compared.

**Comment by andypymont** [comment]
>The strongest argument is to use the principle of least surprise - which suggests that shares of different corporations should be comparable - and a percentage can easily be compared.

Whilst the percentage may be best for comparing players' relative receipt of dividends, the number of shares is a better comparison when considering how much share price appreciation each player is getting, so there's an argument for either approach.

The current implementation is consistent across games - for example in 1861/67 and the 1822 games, minor railways are reflected as 2 shares in the player's total (which is 100% ownership of the minor railway, and 50% receipt of dividends - presumably you would prefer 0.5 here, however the player is getting two shares worth of stock price appreciation which is one of the main factors in minor railway ownership, especially in the 1822 games).

**Comment by zeitlinger** [comment]
That's a good point - I guess adding another row for "Shares %" is what I'm asking for.

**Comment by philcampeau** [comment]
Since the associated pull request to implement this was rejected a year and a half ago, I'm going to close this bug report.
