### ISSUE TITLE
1822PNW better description of Paper Mill

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8439]
It would be nice if the Paper Mill private company description specifically stated that the bonus applies to all corporations that run a train to the city, not just the corporation that acquired the private company and placed the Paper Mill token.

**Comment by outsidePasser** [comment]
I made an assumption about that one - although I can see it the other way.  The wording comes directly from the rulebook.  Going to get clarification from the author.

**Comment by ChrisTheCat** [comment]
The same suggestion applies to the Ski Haus P17
