### ISSUE TITLE
1822PNW  Capitalization issue when converting to major in later phase

### ISSUE THREAD

**Issue by jamesbloom** [tobymao/18xx#8442]
https://18xx.games/game/97490

in SR9, player Twiston converts the M6 to form the ORNC (the M6 previously used backroom dealings to convert the M6 to be the associated minor for ORNC).

The major does not list itself as needing to float. Upon reaching 5+ shares, no floatation happens. Money for purchased treasury shares is added to the bank, and does not make it to the treasury by any means.

**Comment by outsidePasser** [comment]
Per 4.7.2, the company does not need to float - it is immediately operational.  It is a bug that the money from selling shares does not go into the treasury.

**Comment by Remyby** [comment]
Same kind of issue in game https://18xx.games/game/98975 I bought a share of the newly converted CMPS from the Treasury, but the company’s cash doesn’t change.

**Comment by outsidePasser** [comment]
Fix has already been submitted.
