### ISSUE TITLE
[1825] Distance graph prunes too aggressively 

### ISSUE THREAD

**Issue by cavedogpdx** [tobymao/18xx#8444]
https://18xx.games/game/88966

No change in game link when submitting tile lay on hexes V-8 or V-10, only error message.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

![1825 LNWR error](https://user-images.githubusercontent.com/115740780/195699265-569ecd8e-e14c-4257-b8f7-1430999bc6b8.jpg)
In operating round 10.1 the LNWR has a 3 train and a 5 train. When trying to upgrade the tiles in hexes V-8 Cardiff or V-10 Bristol the error message pops up and says _unable to reach city/town on upgraded tile with any train_ . However, the 5 train can go T-16->R-16->S-15->S-13 and reach either V-8 or V-10.

**Comment by roseundy** [comment]
This exposes a fundamental flaw in distance_graph. I am pruning walks if I reached a node that had been visited before with a smaller or equal distance. I think I can only prune if I reached that node before from the _same path_.
