### ISSUE TITLE
1822PNW - port tile on E8 blocks merger connection from 1 to 6

### ISSUE THREAD

**Issue by mnfuller2** [tobymao/18xx#8448]
seems to be the case that if a port tile is laid of E8 (and im guessing D9) the connection from 1 to 6 via that route is no longer allowed for merger purposes

**Comment by outsidePasser** [comment]
Do you have a game where you see this issue?

**Comment by mnfuller2** [comment]
oops - forget this - i misread the rule - you cannot acquire on the first operating turn - but you can merge 
sorry :(
