### ISSUE TITLE
1822PNW - Minors showing pound symbols in payment calculations

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#8449]
https://18xx.games/hotseat/hs_htgmtiuq_1665925388

Encountered an issue with 1822PNW where minor companies, when calculating a revenue amount that results in a half, ie 6 pays out $25 = $12.5 per share, the 12.5 is displayed in pounds instead of dollars in the game transcript.  

https://gist.github.com/ScottDrone/1c0fcedaa61f84b7e8a05b9cd74719e8

**Comment by navaneethkp36** [comment]
hi @ScottDrone I would like to contribute to this.
