### ISSUE TITLE
[1873] Reassign switchers skipped

### ISSUE THREAD

**Issue by renaudgermain** [tobymao/18xx#8454]
problem: "SN skips reassign switchers" executed automatically
expected behavior: game allows for re-assignment of switchers before SN turn

Game ID: https://18xx.games/game/98793

- Browser Version: Firefox 102.3.0esr

**Comment by roseundy** [comment]
An action number would be helpful.

**Comment by roseundy** [comment]
Right, so the situation looks like this:
![swicher_reassign](https://user-images.githubusercontent.com/8494213/196221474-23041407-ce90-4c97-9bb9-4608c3e96216.PNG)
