### ISSUE TITLE
[1822PNW] No Par Options for Merger

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#8457]
Game 98304, https://18xx.games/game/98304?action=683, after clicking on Merge button to merge the 7 and 12, the interface failed to show any options for the par price:

![image](https://user-images.githubusercontent.com/70117294/196306964-c3161e4b-d000-4006-aaa4-1bace7eba761.png)

Same problem on my android phone and Dell PC running windows 11, both in the Brave browser.  I've played many games of 1822PNW on these devices with these platforms, and this is the first time I have had this problem.

**Comment by fanman80** [comment]
The issue does not seem fixed in game 98304.  After restarting the turn and
trying to merge again, I still get no par choices for the new company.

**Comment by crericha** [comment]
It's not deployed yet.
