### ISSUE TITLE
1846 GameError: Cannot pass game id (hs_nppmegeg_1592491508)

### ISSUE THREAD

**Issue by ChrisNord** [tobymao/18xx#846]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 1,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "undo",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 2
    },
    {
      "type": "redo",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 3
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 4,
      "company": "SC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 5,
      "company": "TBC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 6,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 8,
      "company": "Pass (0)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 9,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "company": "MC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 12,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 13,
      "company": "Pass (2)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 14,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 16,
      "company": "Pass (4)",
      "price": 0
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "pass",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 20,
      "company": "LSL",
      "price": 40
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21,
      "corporation": "GT",
      "share_price": "70,0,7"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 22,
      "corporation": "IC",
      "share_price": "100,0,10"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "par",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 24,
      "corporation": "B&O",
      "share_price": "100,0,10"
    },
    {
      "type": "par",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 25,
      "corporation": "NYC",
      "share_price": "100,0,10"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 26,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "IC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "GT_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "B&O_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "NYC_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 31
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "GT_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "buy_shares",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "B&O_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 38
    },
    {
      "type": "pass",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 40,
      "hex": "C13",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 41,
      "hex": "C11",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 42,
      "hex": "G9",
      "tile": "6-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 43,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "undo",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 44
    },
    {
      "type": "undo",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 45
    },
    {
      "type": "undo",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 46
    },
    {
      "type": "undo",
      "entity": "MS",
      "entity_type": "minor",
      "id": 47
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 48,
      "hex": "B16",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "MS",
      "entity_type": "minor",
      "id": 49
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 50,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 51,
      "hex": "G9",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 52,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 53,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 55,
      "hex": "C13",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 56,
      "hex": "C11",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 57
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 58,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 59,
      "company": "MS",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 60
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 62
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 63,
      "hex": "J4",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 64,
      "hex": "I3",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 65,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 67,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 68,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 70
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 72
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 73,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 74,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 75,
      "company": "SC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 76
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 78
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 79,
      "hex": "E19",
      "tile": "8-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 80,
      "hex": "E17",
      "tile": "291-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 81
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 82,
      "train": "2-7",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 83,
      "train": "2-8",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 85
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 86,
      "hex": "G11",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 87,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 88
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 89,
      "hex": "D10",
      "tile": "8-3",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 90,
      "hex": "D8",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 91
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 92,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        },
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 93,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 94,
      "train": "4-0",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 95
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 96,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 97
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 98
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 99,
      "hex": "H6",
      "tile": "9-4",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 100,
      "hex": "G7",
      "tile": "619-0",
      "rotation": 0
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 101
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 102
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 103
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 104
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 105
    },
    {
      "type": "sell_shares",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 106,
      "shares": [
        "IC_2"
      ],
      "percent": 10,
      "share_price": 80
    },
    {
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 107,
      "city": "I5-0-0",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 108
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 109,
      "hex": "H6",
      "tile": "9-4",
      "rotation": 0
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 110
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 111,
      "hex": "H6",
      "tile": "9-4",
      "rotation": 0
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 112
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "sell_shares",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 114,
      "shares": [
        "IC_2"
      ],
      "percent": 10,
      "share_price": 80
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 115,
      "hex": "H6",
      "tile": "9-4",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 118,
      "hex": "G7",
      "tile": "619-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 119,
      "city": "619-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 120,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "I5",
              "H6",
              "G7"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 121,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 122
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 123,
      "company": "MC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 124
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 125
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 126,
      "hex": "G19",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 127
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 128,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "G21",
              "G19"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "H20",
              "G19"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 129,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 130
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 132
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 133
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 134
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 135,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 136
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 137,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "G21",
              "G19"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "H20",
              "G19"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 138,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 139
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 140
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 141
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 142,
      "hex": "D18",
      "tile": "8-4",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 143,
      "hex": "D20",
      "tile": "14-1",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 144,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "E17",
              "D18",
              "D20"
            ]
          ]
        },
        {
          "train": "2-8",
          "connections": [
            [
              "E17",
              "E19",
              "D20"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 145,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 146
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 147
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 148
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 150
    },
    {
      "type": "pass",
      "entity": "Player 4",
      "entity_type": "player",
      "id": 151
    },
    {
      "type": "pass",
      "entity": "Player 5",
      "entity_type": "player",
      "id": 152
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 153,
      "hex": "H12",
      "tile": "292-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 154,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G11",
              "H12"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 155
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 156,
      "hex": "F6",
      "tile": "9-5",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 157,
      "hex": "E5",
      "tile": "8-5",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 158,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "I5",
              "H6",
              "G7"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 159,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 160
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 161
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 162
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 163,
      "hex": "F18",
      "tile": "9-6",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 164,
      "hex": "E17",
      "tile": "296-0",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 165,
      "city": "296-0-0",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 166,
      "routes": [
        {
          "train": "2-5",
          "connections": [
            [
              "D20",
              "D18",
              "E17"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "G19",
              "F18",
              "E17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 167,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 168,
      "train": "4-1",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 169
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 170
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 172,
      "hex": "E15",
      "tile": "9-7",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 173,
      "hex": "E13",
      "tile": "9-8",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 174,
      "city": "296-0-0",
      "slot": 1
    },
    {
      "type": "run_routes",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 175,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "D20",
              "D18",
              "E17"
            ]
          ]
        },
        {
          "train": "2-8",
          "connections": [
            [
              "D20",
              "E19",
              "E17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 176,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 177
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 178
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 179
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 180,
      "hex": "D6",
      "tile": "298-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 181
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 182,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "C5",
              "D6"
            ],
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ],
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 183,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 184
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 185
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 186,
      "hex": "I11",
      "tile": "9-9",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 187,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G11",
              "H12"
            ]
          ]
        }
      ]
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 193
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 194
    }
  ],
  "id": "hs_nppmegeg_1592491508",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    },
    {
      "name": "Player 4"
    },
    {
      "name": "Player 5"
    }
  ],
  "title": "1846",
  "description": "1846_20200618",
  "max_players": "5",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-18",
  "loaded": true,
  "result": {}
}

**Comment by tobymao** [comment]
can't repro can you try to recreate this game?
