### ISSUE TITLE
[1822+] Acquired M3 into the NER and NER's destination token disappeared from M3's home hex

### ISSUE THREAD

**Issue by Orvin2000** [tobymao/18xx#8461]
https://18xx.games/game/98155

I did not notice until a few turns later, but the destination token for the NER was missing from the map. The company charter shows the destination token as on the H5 space, but the spot is open on the map. 

When running a train between its home in L19 and destination in H5, the H5 location does not get doubled. 

I believe this occurred when the NER acquired the #3 minor. I chose to move a token to the available token space on the charter, rather than place on the map, as the destination token was already there, and a second token would not be useful.

**Comment by michaeljb** [comment]
Can't repro this, here's a gist where NER acquires 3 without issue - https://gist.github.com/michaeljb/ab60a05ab1046c653c2502defbb5329a

Will reopen if this occurs again.
