### ISSUE TITLE
[1822PNW] Game End -Does not end on round of Max Share Value

### ISSUE THREAD

**Issue by Hewhite2003** [tobymao/18xx#8472]
Game101760

https://18xx.games/game/101760

SPS hit max share value on OR1. Game went through OR2.

**Comment by andypymont** [comment]
In the linked game, the bank was broken before the corporation hit the blue section of the stock market.

Rule 7.1.7 in the rulebook (linked from the Info tab) says:
> Once the game end has been triggered, the game will end at the indicated time, even if another end condition is triggered after the first.

Therefore I believe it is correct that the set of ORs was finished in this case.
