### ISSUE TITLE
[1822MX, 1822PNW] LP not getting mail contract subsidy

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#8479]
https://18xx.games/game/101798

What is says on the tin

**Comment by outsidePasser** [comment]
From what I can tell on boardgamegeek, it seems that the consensus is that an LP should be able to run the mail contract, but it's not at all clear how much it should actually run for.

**Comment by BellmakerSA** [comment]
> From what I can tell on boardgamegeek, it seems that the consensus is that an LP should be able to run the mail contract, but it's not at all clear how much it should actually run for.

The subsidy should be either home city + town divided by 2, or home city divided by 2.

**Comment by michaeljb** [comment]
The 1822MX rules linked from[ AAG's site](https://all-aboardgames.com/pages/rules) and the [draft 1822PNW rules](https://boardgamegeek.com/thread/2890404/1822pnw-public-rules-review) allow the L to be used in this way (pg 31):

> An L-train may deliver mail within a single city. 

The 1822 and 1822CA rules don't call this interaction out, but in the [1822 BGG forums](https://boardgamegeek.com/thread/2640241/article/40423428#40423428), Simon Cutforth has commented the opposite:

> My view is that the Main Contract private CANNOT be used with the LP train.
