### ISSUE TITLE
[1825] Minor UI issue - GER start obscured by tile name

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#8483]
Hex V20 - the "London" text obscures the "GER" start city text. "London" should be moved to fit into the bottom of the hex, or otherwise placed to obscure an open token spot rather than GER. 

![image](https://user-images.githubusercontent.com/33561233/198836932-a5edf7ab-1976-4591-a68a-ec4e6f425c59.png)

**Comment by roseundy** [comment]
Bugs with these very crowded tiles are very difficult to fix. The workaround is to turn off location names in the UI.
