### ISSUE TITLE
[1822MX] Incorrect Tile Roster

### ISSUE THREAD

**Issue by zexine** [tobymao/18xx#8489]
There should be 3 "X18" tiles instead of 2

**Comment by benjaminxscott** [comment]
[Confirmed](https://cdn.shopify.com/s/files/1/0252/9371/7588/files/1822MX.pdf?v=1597256866)
![Screenshot 2022-11-02 7 32 40 PM](https://user-images.githubusercontent.com/1711810/199637409-836215b2-65c3-4fd4-a1ea-48d11ee8af1a.png)
