### ISSUE TITLE
[1822MX] Ferry connection not working when major acquiring minors

### ISSUE THREAD

**Issue by zexine** [tobymao/18xx#8492]
https://18xx.games/game/101662

If FCP chooses to half-pay at
https://18xx.games/game/101662?action=1066
then, it should have enough money to acquire minor 8 for 120 bucks
however, in subsequent minor acquire step, only minor 6 is available. Minor 8 should also be available through ferry connections.
![image](https://user-images.githubusercontent.com/109436164/199293949-7c5370e6-13f8-40c6-841e-769488af52b1.png)

![image](https://user-images.githubusercontent.com/109436164/199294182-d7f1aa54-e8f1-4c76-b056-06535486074f.png)

**Comment by Mauler78** [comment]
I ran into a similar issue.
![18xx bug 1](https://user-images.githubusercontent.com/81341165/199849547-87d732a8-92fe-482e-8285-9c494a2725c9.PNG)
![18xx bug 2](https://user-images.githubusercontent.com/81341165/199849572-4bbce362-05b5-4f2e-b72b-122b420d6c43.PNG)
