### ISSUE TITLE
[1822PNW] Paper Mill private cannot be used on eligible cities

### ISSUE THREAD

**Issue by cheesinglee** [tobymao/18xx#8496]
https://18xx.games/game/100823?action=889

M11 has acquired the Paper Mill private, but cannot use its ability to place the token in Aberdeen, even though it is connected to an adjacent timber hex.

It looks like hexes H21 and J5 are absent from this entity definition: https://github.com/tobymao/18xx/blob/6335fb2c4f5f122ecd3315a955ce24d5855f934c/lib/engine/game/g_1822_pnw/entities.rb#L305

**Comment by michaeljb** [comment]
Fixed by #8497
