### ISSUE TITLE
1822PNW better marking for port locations

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8502]
More than one person thought they could use the port in a location like hex O18 adjacent to M20. This is very clear on the prototype maps shown on BGG, but the distinction between large arrows and small arrows in the blue water on 18xx.games is too subtle. It would be better if the potential locations to ports were more obvious. Maybe in a different color for the arrows?

**Comment by ChrisTheCat** [comment]
Also, the text doesn't actually say "only large spikes"

<img width="319" alt="Screen Shot 2022-11-13 at 11 02 40" src="https://user-images.githubusercontent.com/8732435/201534244-95ff867d-ac1a-44c7-89d3-123f3aa8bee6.png">

**Comment by slapphappyjazz** [comment]
Oh my, that is completely non-obvious.  I didn't realise this limitation at all.
