### ISSUE TITLE
[18EU] Reserved hexes should be able to be built by other minors/corps with consent.

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#8508]
https://18xx.games/game/102654

https://18xx.games/game/102654?action=275

hex F21 is marked as minor 10 only but minor 5 is able to place a tile there.

**Comment by philcampeau** [comment]
As per the rules, another minor can lay on a reserved hex if the owner of the other minor consents. 

In this game, Minor 5 is owned by the same player as minor 10, so consent is implied. 

That said, the current implementation doesn't offer the ability to check consent from a different owner. This should be fixed.
