### ISSUE TITLE
1840 bug - Company Round payout - #102173

### ISSUE THREAD

**Issue by BranislavBerec** [tobymao/18xx#8511]
In 1840 we have the 3rd company round, 2 players have paid out the dividens without any issues, another player is trying to pay dividends but gets an error message: "Route must contain token." There's no route for companies in 1840, this is a strange error. 

Game: https://18xx.games/game/102173

**Comment by BranislavBerec** [comment]
Hi Toby,
I still get the same error message in our game.
Or do we need to quit our game and start a new one?

Thanks!
Branislav

**Comment by Zwergenpunk** [comment]
It worked on my local machine. I did not test it in server mode. Will look again the next days.

**Comment by Zwergenpunk** [comment]
Should work now as new version is deployed
