### ISSUE TITLE
[Harzbahn] Semi-vanished game

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#8518]
json: https://gist.github.com/benjaminxscott/6fb20ef252b9a4cb312475a92484c53d

https://18xx.games/game/102218 no longer appears on the front page for me, or in https://18xx.games/profile/11056 (my profile). A fellow player, Eliab, reports that "I’m getting the game in orange text, as if was me to play, and when I select that game, it’s you"; I got the game number from him. If I then go to that URL, I see it as me to operate HW. I have cloned the game in hotseat mode but will take no further action while you investigate.

The behaviour is identical on Firefox (Linux, 102.3.0esr (64-bit)), Chromium (Linux, Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.0 (64-bit)), and Firefox (Windows 10 Education, 106.0.3 (64-bit)).

**Comment by roseundy** [comment]
This is very strange. The game does appear in your profile, but as being way back in "Auction 1".

**Comment by damerell** [comment]
Goodness me, my mistake! I did not even spot that was the same game - I thought my friends had started an entirely new game which was in Auction 1. Sorry for the inaccurate bug report.

**Comment by damerell** [comment]
This has been closed as completed but there is no indication if we can continue the stricken game.

**Comment by roseundy** [comment]
I'm reopening this. David, are you unable to make a move in the game?

If nothing else there is a problem with the game state that is causing it to not appear correctly on David's profile page.

**Comment by damerell** [comment]
I think it is almost certain that Eliab saw the same thing from what he wrote. (Unfortunately, he has medical issues which make it challenging for him to report in more detail.)

I had not taken a move until now because I wanted you to be able to see the state of affairs as it was. I have just taken HW's turn. It is now NWE to move, of which I am also the Director. The front page now appears normal.

**Comment by michaeljb** [comment]
@damerell it appears you were able to finish this game a few days after your last comment here? And In your profile it looks like it's reporting as complete.

I see an undo action that went back several actions that was redone around the time this was reported, but it didn't go back to the start so I don't think it's a real lead.

I'll close this but we can re-open if this kind of issue surfaces again.
