### ISSUE TITLE
18GB: Getting "undefined method 'include' for nil" after buying 6X, when clicking Done.

### ISSUE THREAD

**Issue by alexarnon** [tobymao/18xx#8526]
This is for 18GB, 2P game.
Bought the 6X, now the following error is raised when clicking `Done (Trains)`:
```
undefined method 'include' for nil
```
The 6X was the immediately preceding action.
Browser: Firefox.

Game ID: [102678](https://18xx.games/game/102678)
Game state gist: https://gist.github.com/alexarnon/803a7415a3845a7def6b435ad1d79240

**Comment by andypymont** [comment]
With this being the last corporation to operate in the OR and some corporations being in the green zone of the market, I suspect this is going to be related to #8402 and the checks for multi-buying stock in the green zone. I'll investigate shortly.
