### ISSUE TITLE
Show a city and town on the same hex

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#853]
This is going to come up a fair amount for upcoming games including 18MEX and 18NewEngland, others I'm sure, 1822, 1822CA if we ever get there. Currently the app can't parse the json if a hex includes both a city and a town like this.
![image](https://user-images.githubusercontent.com/29106780/85433286-d04a6d00-b549-11ea-91f4-757ff543c6f2.png)

It would be nice if the system also handled this case, but probably not a big deal and could be hacked around with an icon.
![image](https://user-images.githubusercontent.com/29106780/85433404-038cfc00-b54a-11ea-85bb-d2deeb87f19d.png)

cc @michaeljb

**Comment by tobymao** [comment]
this is going to be a really big change to routing
