### ISSUE TITLE
18GB: NS/EW bonus not tracked properly while tracing routes.

### ISSUE THREAD

**Issue by alexarnon** [tobymao/18xx#8532]
18GB: tracing NS bonus with train, then removing it and tracing another bonus will keep the NS on the route display.
Instead, the NS bonus stays on the route.

In detail: 
- A NS route was done with the red train, which was then cleared.
- Then the blue train was used to trace a NS route, and red traced an EW route, as in the image.
- NS remained on the red train, blue train does not have a bonus.

Game: https://18xx.games/game/102678

See gist and attached image: https://gist.github.com/alexarnon/a0deed9d5ea5b7eac0eb8720a7903e71

![102678_route_problem](https://user-images.githubusercontent.com/1048608/203097988-ca100d94-6ade-49d6-9cf6-beadf6d96afd.jpg)

**Comment by alexarnon** [comment]
I have tested further - it seems that EW is not tracked here.
In the reported scenario, NS will snap to the red line once blue manages the NS.

![18gb_ew_not_tracked](https://user-images.githubusercontent.com/1048608/203102230-4228926f-7950-44ab-b5aa-ed1426f8216c.jpg)

**Comment by andypymont** [comment]
Because you are allowed to use multiple trains for a NS or EW connection, the bonus will appear on one train that is part of a network satisfying the NS or EW route and not necessarily the specific train you expect. This is working as intended as it allows trains to be chained together to satisfy these connections.

If a bonus is missing however then this is a bug and I'll need to investigate.

**Comment by alexarnon** [comment]
Ah, I understand!
It seems that the EW bonus is missing, though.

**Comment by alexarnon** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/1048608/204159511-00d5d202-9b4b-442d-940b-1278855359e9.png">

Looks almost right - here the trains meet at an offboard (which does not enable passage, so illegal in this case).
Another thing - once this is fixed, you should note that due to the trains routes auto-concatenating, bonuses will be marked on the first one, in case more than one bonus is received.

**Comment by andypymont** [comment]
Thanks Alex. I'm not at a PC until Tuesday but it should be possible to only combine trains for compass bonuses if they intersect at non-offboards: I'll take a look at this.
