### ISSUE TITLE
[1817] Stock moves show "1 right" when at end of stock market

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#8536]
![image](https://user-images.githubusercontent.com/67359577/203624810-5ebebb12-ebca-4873-a2fb-638aa2cdb0a8.png)

https://18xx.games/game/86792?action=1835

**Comment by michaeljb** [comment]
gist link for that game before it gets archived - https://gist.github.com/michaeljb/fff1be9989dc5432fd7a088868b68ee7
