### ISSUE TITLE
18Mag round missing from spreadsheet

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8537]
OR5.2 is missing from the spreadsheet, both on the right where companies are listed and below where players are listed.

https://18xx.games/game/102365?action=995#spreadsheet

<img width="1294" alt="Screen Shot 2022-11-24 at 08 50 54" src="https://user-images.githubusercontent.com/8732435/203834798-81813e8d-9180-4f22-9c38-908c90f12f37.png">

**Comment by magnusrk-ch** [comment]
There's no bug here as far as I can tell. Phase changes in 18Mag end the OR set early. There was no OR 5.2 because a phase change happened in OR 5.1.

**Comment by roseundy** [comment]
Thanks!
