### ISSUE TITLE
[1822PNW] NP's origin marker disappears after tile lay on O20

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#8540]
In 1822PNW, the NP's origin marker disappears immedately after a tile lay on O20, as in https://18xx.games/game/104804?action=81 (action 82 makes it vanish). I've been able to reproduce this in hotseat mode, but I don't know if it happens every time.

**Comment by michaeljb** [comment]
Hmm I'm not able to reproduce this anywhere. @outsidePasser maybe you'll be able to?

**Comment by damerell** [comment]
https://18xx.games/game/104885?action=1338 shows it too (I got lucky and found it first time; NP unstarted, origin marker unshown).

**Comment by outsidePasser** [comment]
I have not been able to reproduce this either.
