### ISSUE TITLE
[1848] Game reported turn error after it had already proceeded to next OR

### ISSUE THREAD

**Issue by nienart** [tobymao/18xx#8563]
Received the following error message in 1848 (game 104781)

```
We're sorry this game cannot be continued due to GameError: Blocking step Place a Token cannot process action 211
Broken action: { "type": "run_routes", "entity": "CAR", "entity_type": "corporation", "id": 211, "created_at": 1670111909, "routes": [ { "train": "3-2", "connections": [ [ "D1", "D3" ], [ "D3", "D5", "E6", "F5" ], [ "F5", "G6" ] ], "hexes": [ "D1", "D3", "F5", "G6" ], "revenue": 170, "revenue_str": "D1-D3-F5-G6 + k-k", "nodes": [ "D1-0", "D3-0", "F5-0", "G6-0" ] }, { "train": "2-0", "connections": [ [ "E4", "F5" ] ], "hexes": [ "E4", "F5" ], "revenue": 60, "revenue_str": "E4-F5", "nodes": [ "E4-0", "F5-0" ] }, { "train": "2-4", "connections": [ [ "E4", "E2" ], [ "E2", "D3" ] ], "hexes": [ "E4", "E2", "D3" ], "revenue": 70, "revenue_str": "E4-E2-D3", "nodes": [ "E4-0", "E2-0", "D3-1" ] }, { "train": "2-3", "connections": [ [ "D1", "E2" ], [ "E2", "F3" ] ], "hexes": [ "D1", "E2", "F3" ], "revenue": 80, "revenue_str": "D1-E2-F3", "nodes": [ "D1-0", "E2-0", "F3-0" ] } ] }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/104781?action=210)
```

The odd thing is the action in question appears to have been in OR 5.1, but the game had already proceeded into OR 5.2, and I was taking the second turn with the FT, not the CAR, which is apparently going here.

**What's your Game ID?**

https://18xx.games/game/104781?action=210

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

The error header offered me a download of game data. I've placed it in [this gist](https://gist.github.com/nienart/302e1e0d1fc6969a906f6151d57ada75.js)

**How to Reproduce the Bug?**

I don't believe my actions triggered the bug. As noted above, I was taking a turn for a different company, in a later OR. Presumably this was due to implementation on the server changing during this time. FWIW, there was nothing obviously illegal about any turns here.

Please include screenshots (you can drag and drop or upload them into this issue)
![Screen Shot 2022-12-04 at 19 43 47](https://user-images.githubusercontent.com/20801394/205544903-9f39e449-8c9e-4254-8943-a818d508510a.png)

**Which Browser / Platform?**

Firefox 105.0.3 / Desktop (MacOS)

**Comment by michaeljb** [comment]
The game is now pinned to the previous deployed version due to #8552. Thanks for reportin!
