### ISSUE TITLE
[TOP 1871] Not given the option to purchase additional shares after split

### ISSUE THREAD

**Issue by davidlaughlin** [tobymao/18xx#8568]
**What's your Game ID?**

Multiplayer game is: https://18xx.games/game/104115

I cloned to a hot seat game where I made additional moves and uncovered what I think is a bug: https://gist.github.com/davidlaughlin/de17beb4672089249f6216d6ad9bf914

**How to Reproduce the Bug?**

- I (David) passed while other players opened and started 2 companies and bought all shares for the 2 companies 
- Once all shares are sold, final tranche opens
- I split Summerdale
- Opponents all pass
- OR begins, I am not able to make any additional moves in the SR

**Expected Behavior**

- I expect to be able to buy additional shares since I took an action on my previous turn (splitting the company)
- Instead the OR begins

**Comment by philcampeau** [comment]
Same issue happened in this game, where I even sold and split: https://18xx.games/game/110587

it seems to not recognize that as an action for some reason.
