### ISSUE TITLE
Allow Upgrades Where the Predecessor Tile is Not Lettered

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#857]
A common mechanism is that certain cities follow a standard tile progression 5/6/57 tile, but then at a certain point become a special tile with the city name printed on it. For example in 18MEX, Guadalajara is a standard city.
![image](https://user-images.githubusercontent.com/29106780/85505059-0a9c2480-b5b3-11ea-980f-5716a84c00e2.png)

However, in brown, it gets its own tile that is 10 more than the standard 63 tile.
![image](https://user-images.githubusercontent.com/29106780/85505120-34554b80-b5b3-11ea-8476-3e46d932f3c8.png)

My idea for solving this issue is that when the green tile is laid in its hex O8, it automatically gains the letters "Gua" or something similar. Then the 480 brown Guadalajara tile also has the Gua letters and it takes on the normal upgrade process.

This should allow the tiles to be set up in a conventional way and only this letter adding would be a custom process.

To show a similar example, the Memphis hex (left side of the board) has a P notation. However, there are no yellow or green P tiles. So in this case, I think we would want to not show the normal letter on the base hex to allow 5/6/57, but then add it when the green tile is laid. 
![image](https://user-images.githubusercontent.com/29106780/85505701-86e33780-b5b4-11ea-8a67-5ebd4b50ab23.png)

Board: https://boardgamegeek.com/image/156134/18tn
Tiles: http://www.18xx.net/tiles/18TN.htm

An extra enhancement would be to have a semi-sticky P icon in the hex to show that it becomes a P later and then remove the icon when the green tile is laid and we get the normal P letter.

cc @michaeljb

**Comment by perwestling** [comment]
I have solved this in 18AL (for Montgomery) to add an M label to the tile layed:
- If it is in the Montgomery hex
- If it does not have a label

It is implemented in lib/engine/step/g_18_al/track.rb in #961 and is pretty straight forward. I think this will be good enough.

**Comment by perwestling** [comment]
@scottredracecar, do you think the 18AL solution is good enough?

**Comment by perwestling** [comment]
In a recent commit (available on master) the upgrades_to? was moved from Tile to Game, so that now the game can handle the checks if it want.

For 18TN this is done so that Chattanooga has a C label from the start and when upgrading to brown it allows (only) P tile. Nashville is similar to Chattanooga but starts with an N label.
Memphis, finally, has no label. When upgrading to brown game allows for either non-label brown or to P label one.

So by using the add-label-during-upgrade or controlling upgrades-to? there are now two methods to handle this issue. 

I think using the controlling upgrades-to? might work for Guadalajara as well.

@scottredracecar Do you think this is good enough?

**Comment by perwestling** [comment]
It turn out that adding a label is no good, unless it is cleaned up when tile is returned. Having the label remains makes the labeled tile unusable for non labeled upgrades.

Instead I have implemented tile upgrade checks in upgrades_to? and all_potential_upgrades methods that 18AL and 18TN overrides in their game class.

**Comment by perwestling** [comment]
The tile upgrade, both on board and for tile manifest have now been completed for 18AL, 18GA and 18TN. 

Question is if this is good enough of if there should be some other solution. See #1526 

Otherwise I suggest we close this ticket.

**Comment by jenf** [comment]
Good enough to close I think.
