### ISSUE TITLE
[1848] GameError: Blocking step Place a Token cannot process action

### ISSUE THREAD

**Issue by Aposky** [tobymao/18xx#8570]
Game link: https://18xx.games/game/104198

Error: We're sorry this game cannot be continued due to GameError: Blocking step Place a Token cannot process action 457
Broken action: { "type": "run_routes", "entity": "CAR", "entity_type": "corporation", "id": 457, "created_at": 1670085742, "routes": [ { "train": "4-2", "connections": [ [ "G6", "F7", "E6", "E4" ], [ "E4", "D3" ], [ "D3", "E2" ], [ "E2", "D1" ] ], "hexes": [ "G6", "E4", "D3", "E2", "D1" ], "revenue": 250, "revenue_str": "G6-E4-D3-E2-D1 + k-k", "nodes": [ "G6-0", "E4-0", "D3-1", "E2-0", "D1-0" ] } ] }

- Browser Version
Firefox 107.0.1
- Platform Windows 10

**Comment by benjaminxscott** [comment]
@michaeljb 

Is the `pins` label something that denotes that extant games on the old version should be pinned? I haven't done that before and don't have prod DB access (which is fine)
https://github.com/tobymao/18xx/pull/8552

**Comment by michaeljb** [comment]
Yep, I've just pinned this one, and a few more, shouldn't be any left now. When I first pinned I only used my recent copy of the prod DB so there were several newer games I should have pinned but didn't.

Thanks!
