### ISSUE TITLE
1861: wrong order of minor nationalisation

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#8572]
Latest game of 1861
https://18xx.games/game/105949

At the rusting event at the purchase of the first 4T (by K-R), in OR3.1, eight minors were nationalised. The program nationalised them in descending price order from the KR, so OK first then wrapped around. This is wrong - the rule is (section 10, Trainless at the start of Phases 4, 6 and 8)
"...nationalized in descending stock price order".

I've always interpreted this to mean "from the highest to the lowest".

Normally, it doesn't matter, but in this case - when the RSR runs out of tokens - it affects where the RSR ends up with tokens. This may affect where routes get blocked later on.

**Comment by ollybh** [comment]
The minors are being nationalised in the order they are defined in the game file (with yellow minors first, then green minors). This happens for both the nationalisation of the trainless minors at the start of phases 4 and 6, and all remaining minors at the start of phase 8.

The order of major nationalisation is also wrong, this is happening in reverse stock market order.

I've submitted a pull request (#8633) to fix these.
