### ISSUE TITLE
Possible Bug Report (or rules conflict) for 1822MEX concerning auction for NdeM tokens in Mexico City

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#8574]
16:30:41[WayneWilliams](https://18xx.games/profile/8040)Possible Bug Report for 1822MEX -- When NdeM tokens are up for auction, a player with no eligible company was allowed to bid: Player had 2 companies with available exchange tokens, but both had tokens in Mexico City (IRM and FNM). The player was allowed to bid on the NdeM token in 14's home -- a token which could not be legally placed.
16:33:26[ChrisShaffer](https://18xx.games/profile/233)sounds like a bug to me - you should report it - see yellow "GitHub" link to the left of this chat ... oh, wait, not a bug ... in 1822 (and 1822 derived games) you're allowed to have more than one token in London / Mexico City / etc.
16:35:30[WayneWilliams] Rule 6.22.3 At least one of the companies for which they are director must have the cash for the bid and an “Exchange” (not “Available”) token that may be placed in that location. The company does not need a track connection. **Companies may not place a second token in a hex.**
16:36:41[ChrisShaffer] that conflicts with 6.11.6 so I think it's a rules errata, not a bug
16:37:27and 6.11.7

**Comment by ChrisTheCat** [comment]
Confirmed that this is a bug. On BGG, Scott says that the privatization auction restriction of one token per hex (rule 6.22.3) overrides the allowance of more than one token in a hex in 6.11.6 and 6.11.7.

Just to be clear, during the privatization auction only, a corporation may not bid on an NdeM token if it already has a token in the same hex, even if the tokens are on separate revenue centers. 18xx.games needs to be updated to enforce this restriction and prevent the bid reported by WayneWilliams.

**Comment by WayneWWms** [comment]
Thanks.

Wayne

**Comment by michaeljb** [comment]
https://18xx.games/game/106103?action=944

https://gist.github.com/michaeljb/821cfa43b1650f7232299dfe2290ebba
