### ISSUE TITLE
18NY Update tile counts

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#8576]
v1 DTG
Should have 3x tile 43 (possibly from a typo on the DTG tile manifest), but FWTWR has a count of three of tile 43 and also the tiles file John provided me for v2 has three of them.
DTG v1 tile count: http://www.fwtwr.com/18xx/info/inv-18ny.asp

v2 AAG (currently listed as prototype), is updated to have the following tile adjustments
Should have 3x tile 43
Should have 9x tile 15
Should have 5x tile 63 (one less to compensate for adding the brown K 448 tiles)

**Comment by crericha** [comment]
Reminder for me: Also update Staten Island hex in v2 from multiple bridges to a flat $80 upgrade cost
