### ISSUE TITLE
[1846] Tried to use C&WI ability in OR1.1 and got not connected error

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#858]
Bought in C&WI in OR1.1. Clicked on the corporation and then D6 and received "Cannot place token on D6 because it is not connected". I also went to the companies page and clicked on C&WI and then tried to place D6 from both the game and map pages and received the same error.

Note: Once C&WI was purchased, it disappeared from the game page. I'm not sure if that is intended or not. I had to go to the companies page to see it again.

[game_data.txt](https://github.com/tobymao/18xx/files/4823490/game_data.txt)

**Comment by tobymao** [comment]
not implemented yet dup
