### ISSUE TITLE
Harzbahn: Game blocked because diesel tokened out on concession route

### ISSUE THREAD

**Issue by beableandobservable** [tobymao/18xx#8586]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Bug blocking the game from continuing :

Game ID 98200

https://18xx.games/game/98200

We are currently in Operating round 9.2 (game to end at end of 9.3).
The NWE player is unable to complete his route , he has a 4T , a 5T and a Diesel.
HE can enter the 4T / 5T routes without problems, but cannot enter valid Diesel routes and the game will also not allow him to submit the routes without using the diesel at all.

The NWE concession route is tokened out at F7 and D7, and both he and I (via master mode) have tried to select through the route but the E6 tile (blocked on either side is greyed out - cannot be selected for routing.

**Comment by beableandobservable** [comment]
I meant F5 and D7 not F7 and D7 but it's an issue either way (the E6 being greyed out and unable to be selected to continue the diesel on the concession route)

**Comment by roseundy** [comment]
Definitely a bug in route selection. TBH, either this is the first time a concession route was tokened out or a bug was introduced in route selection. I will need to investigate.

Unfortunately, I will not have time until this weekend to work on this.

**Comment by beableandobservable** [comment]
That's no problem and thank you.
Technically we the players exist to find bugs, right? ;)

**Comment by beableandobservable** [comment]
I think that's what we were speculating was the issue in the site chat .   Happy to be inadvertantly QA and if you fixing it this weekend means we don't have to nuke the game that's awesome

**Comment by beableandobservable** [comment]
Good evening!
Wondering if there is a chance on a fix? If not I'll just end the game manually as unresolveable.

**Comment by roseundy** [comment]
Looking at a fix now.

**Comment by roseundy** [comment]
I'm very sorry for not getting to this sooner.

**Comment by roseundy** [comment]
I've got a fix for not being able to select routes through tokened-out concession route hexes.

There is a related issue with diesel routes. I have to check if a diesel never visits a node not connected to the concession route, but the double-token scenario breaks that check too. I think I know a solution.
