### ISSUE TITLE
1861 duplicate tokens during merge

### ISSUE THREAD

**Issue by Dave4B** [tobymao/18xx#8589]
In 1861 (possibly 1867 - not tested), if two minors with tokens in the same hex (Moscow or Kiev) merge, the player is prompted to remove all but one of the duplicates.
The program then places a token on the major's charter as a zero cost token.
The published rules are unclear as to what should happen in this case, but the designer (Ian D. Wilson) has stated that the second token should cost 20R per hex, the same as forming a major by converting a single minor,

**Comment by Dave4B** [comment]
Just tried this in 1867 with three minors; two in Montreal and one other.
Program required me to remove one of the three tokens; I removed the non-Montreal one.
No response so I removed a Montreal one.
Program continued with one token on the map (Montreal) and a zero price one on the charter.
This is wrong; the non-duplicate token should not be removable.

**Comment by Dave4B** [comment]
Not quite sure whether this should be a separate issue, but the message which appears when you merge exactly two minors in the same hex is "When merging more than 2 minor corporations the new corporation can only keep 2 tokens. Choose which tokens to remove. After merging an additional token will be available on the charter."
This should be a different (new?) message about a corporation not being allowed to have more than one token in a hex/tile.

**Comment by ollybh** [comment]
There are three separate problems here, all related to having more than one token in the same hex:

1. If two tokens are in the same city (not just the same hex) then one gets put back on the minor's charter, and then moved across to the new public company as a zero-cost token.
2. If three or more minors merging it is possible to remove all but one of the tokens.
3. The help message is misleading.

I've got fixes for (1) and (3), I'll submit a pull request  when I've done (2) as well.

**Comment by Dave4B** [comment]
I think that the logic to be applied when two or more minors merge is:If there are two tokens in the same city, remove one. Repeat if necessaryIf there are now more than two tokens on the map, remove one. Repeat if necessaryIf there are now two tokens on the charter, they are R20 and R40. Sent from Mail for Windows From: Oliver Burnett-HallSent: 19 January 2023 23:08To: tobymao/18xxCc: Dave4B; AuthorSubject: Re: [tobymao/18xx] 1861 duplicate tokens during merge (Issue #8589) There are three separate problems here, all related to having more than one token in the same hex:If two tokens are in the same city (not just the same hex) then one gets put back on the minor's charter, and then moved across to the new public company as a zero-cost token.If three or more minors merging it is possible to remove all but one of the tokens.The help message is misleading.I've got fixes for (1) and (3), I'll submit a pull request when I've done (2) as well.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ollybh** [comment]
I was planning on a simpler implementation: whenever a player removes a token, count the number of hexes that will be left with tokens. If it is just one then throw an error and prevent the token from being removed, unless there was already only a single hex with tokens.

(BTW, @Dave4B if you're commenting on an issue by email, can you please ensure that you're sending plain text messages. Otherwise your comment is garbled and mostly consists of formatting codes.)

**Comment by Dave4B** [comment]
Yes, that would work. Sent from Mail for Windows From: Oliver Burnett-HallSent: 19 January 2023 23:56To: tobymao/18xxCc: Dave4B; MentionSubject: Re: [tobymao/18xx] 1861 duplicate tokens during merge (Issue #8589) I was planning on a simpler implementation: whenever a player removes a token, count the number of hexes that will be left with tokens. If it is just one then throw an error and prevent the token from being removed, unless there was already only a single hex with tokens.(BTW, @Dave4B if you're commenting on an issue by email, can you please ensure that you're sending plain text messages. Otherwise your comment is garbled and mostly consists of formatting codes.)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Dave4B** [comment]
Tried it on Obsidian and I can't break it. looks good.
[hs_nshophxi_1674316264.json.txt](https://github.com/tobymao/18xx/files/10472539/hs_nshophxi_1674316264.json.txt)

**Comment by Dave4B** [comment]
@ollybh Spoke too soon. Four companies in three cities, removed odd two and one of pair.
[hs_qpphryet_1674373578.json.txt](https://github.com/tobymao/18xx/files/10473976/hs_qpphryet_1674373578.json.txt)

**Comment by ollybh** [comment]
> @ollybh Spoke too soon. Four companies in three cities, removed odd two and one of pair. [hs_qpphryet_1674373578.json.txt](https://github.com/tobymao/18xx/files/10473976/hs_qpphryet_1674373578.json.txt)

Yesterday I left a code branch checked out that didn't include these fixes. This game export fails when I try and import it using the fixed code, complaining about GRR not having two tokens in different hexes.

**Comment by Dave4B** [comment]
Let me know when you want me to try it again (just to be sure) @ollybh

**Comment by ollybh** [comment]
@Dave4B Should be OK to go now.

**Comment by Dave4B** [comment]
@ollybh Yes, it stops me removing tokens to leave just an illegal pair.

**Comment by ollybh** [comment]
These fixes have been submitted as pull request #8689.
