### ISSUE TITLE
Grand Trunk - 2 issues

### ISSUE THREAD

**Issue by spiderbanjo** [tobymao/18xx#859]
1 - When Grand Trunk bought in the MS minor, the MS token was not replaced by a GT token

2-Same game, when attempting to trace a route for Grand Trunk, got the 'route invalid - no token' response regardless of route.

**Comment by tobymao** [comment]
data?

**Comment by tobymao** [comment]
i'll reopen this if you provide game data

**Comment by spiderbanjo** [comment]
Hi Toby,

I’m doing my best to help, but I’m a retired 60-something with no programming experience whatever.  What is ‘game data’?  

Cheers
T

**Comment by tobymao** [comment]
go to the tools tab and click copy data and paste that here do i can reproduce 

thank you for your help.
