### ISSUE TITLE
[1870] Destination run does not change order of corporations

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#8593]
This might be a rules misunderstanding, but I think that if a company pays out its destination run before its turn in an OR, its operating order should be based on the new stock price, not the one at the beginning of the OR.

As a particular example, look at the destination run here:  https://18xx.games/game/104973?action=956

SSW paid out its destination run, and the stock price moved from the top row $120 to the top row $140.  However, it is still running ninth, after four corporations with $120 stock prices.
If the operating order were recalculated, SSR at $140 would run after SLSF (done), GMO ($225), ATSF ($200), and TP ($180), but before IC, MKT, SP, and MP (all $120).

**Comment by philcampeau** [comment]
Well this was an embarrassingly easy fix!
