### ISSUE TITLE
Harzbahn 1873 - public mining company not offered opportunity to transfer switchers

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8602]
https://gist.github.com/ChrisTheCat/de4e9245501eca67269d07b00873eb68

When the HBE clicks "Do not convert" the game immediately advances to the MO making a decision about pay, half-pay, withhold. Rule 4.3.1 states "If the company possesses switchers, they can be freely transferred between the mines for production." The game does not offer the president of the MO the opportunity to transfer switchers between the mines.

**Comment by roseundy** [comment]
Note that my implementation skips this step if it could have no material impact on the game. The game is already long enough without asking to move switchers that don't affect revenue.

**Comment by ChrisTheCat** [comment]
In that case, why not automatically transfer the switches when it will improve the route?

**Comment by roseundy** [comment]
Because the removes agency from the player.
I only skip reallocation if it can have no effect

**Comment by ChrisTheCat** [comment]
Maybe the language could be revised to say something like "You could increase your revenue by transferring switchers, would you like to do so?" That's effectively what asking only when an improvement could be made does, and it would be nice to be more explicit/transparent about it.
