### ISSUE TITLE
[1848] Private company values are displayed as negative.

### ISSUE THREAD

**Issue by alexarnon** [tobymao/18xx#8604]
Game ID: 105080
[https://18xx.games/game/105080](https://18xx.games/game/105080)

During ORs, Private companies' value appears as a negative number.

Cloned game: [gist](https://gist.github.com/alexarnon/b2005ed051e484fd9ad13cc3df81d3b3)

**Comment by bentziaxl** [comment]
Very minor bug, no impact on playability. Will fix
