### ISSUE TITLE
[1836Jr56] Error when attempting to place tiles

### ISSUE THREAD

**Issue by broodstar258** [tobymao/18xx#8605]
Game ID: https://18xx.games/game/107429?action=32

I simply cannot place any tiles without receiving an error. "The server did not accept this action due to: wrong number of arguments (given 0, expected 2)... refreshing."

**Comment by michaeljb** [comment]
Reproduced locally on server, not reproduced in hotseat

**Comment by philcampeau** [comment]
This could have been due to an update I tried to do to 1836jr56 around that time. I had a couple of errors in my code, and we had to revert back. 

If so, it's likely an isolated incident.

**Comment by michaeljb** [comment]
SG, I'll close this then, we can reopen or open a new one if it comes up again.
