### ISSUE TITLE
Title groupings/descriptions

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#8607]
On a daily basis i read questions in the open forum for suggestions of which titles are like what other titles.

On the games list I suggest some sort of flagging and or color code which would broadly categorize each game.  Better yet, why not have, for example all the 17s together. in the "17 system" box and maybe a minors games grouping.  46 grouping, 49 grouping, heck Rhl 56 SJ with the inc-to-full could be a subset of the "30" category.  Of course the very different titles need skulls and crossbones on them, just kidding.

There could be as well a complexity marker of some sort.   This list of games is growing and overwhelming...that's a lot of rules to read and or clones to run :)

**Comment by michaeljb** [comment]
On the create game page, in the "search by keyword" box, you can get some of what you're looking for by typing in things like "1817" or "1846".

https://18xx.games/new_game

**Comment by saxafras** [comment]
That DOES work for 46 and 17–excellent!  It's a start and thanks for all you do!

    Le jeudi 22 décembre 2022 à 09:23:16 UTC−9, Michael Brandt ***@***.***> a écrit :  
 
 


On the create game page, in the "search by keyword" box, you can get some of what you're looking for by typing in things like "1817" or "1846".

https://18xx.games/new_game
