### ISSUE TITLE
Corps with only a route to a port/Paris do not have a valid route requiring a train purchase

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#861]
_(note: this really only applies to Paris because the ports have other revenue centers in the way so it is impossible to run a home token to a port)_

It is the train buying step and Nord does not have a valid route requiring a train purchase, but the system is prompting me to buy a train and will not allow me to skip trains.

![image](https://user-images.githubusercontent.com/29106780/85589451-334f0900-b609-11ea-8eed-8ee9be860a55.png)

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "ACC",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "E-SF",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "CdH",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "GCB",
      "price": 110
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "CFL",
      "price": 160
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "CFLV",
      "price": 220
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "corporation": "Nord",
      "share_price": "100,0,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 8,
      "shares": [
        "Nord_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 9,
      "shares": [
        "Nord_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "Nord_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "Nord_4"
      ]
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "corporation": "B",
      "share_price": "100,0,6"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "B_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "B_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "B_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "B_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 18
    }
  ],
  "id": "hs_qlzbbhaf_1593013856",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1836Jr30",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-24",
  "loaded": true,
  "result": {}
}

**Comment by luigicoolGH** [comment]
Same problem happened here, https://www.18xx.games/game/2986.  
From Kovacs' rules : "Such a run must include at least two other scoring locations (e.g., a run from Lille to Paris is not legal) and thus requires at least a 3 train."
Yet the game forced the president of Nord to purchase a train after laying the first tile (#7 with rotation 1 on I5, not connecting a city)
