### ISSUE TITLE
[1822PNW] Game stuck when choosing token

### ISSUE THREAD

**Issue by 18xxperson** [tobymao/18xx#8615]
**What's your Game ID?**
107450
https://18xx.games/game/107450

Selecting one of the two button results in a "NilClass can't be coerced to Numeric" error message.

**Comment by perwestling** [comment]
@18xxperson Is it still stuck? I had no problem opening this game.

**Comment by 18xxperson** [comment]
I can't make a move

**Comment by 18xxperson** [comment]
I am no longer stuck

**Comment by outsidePasser** [comment]
Problem is gone and cannot be reproduced.

**Comment by outsidePasser** [comment]
See above
