### ISSUE TITLE
[1870] Company names on Entity cards and on Privates are not the same when referring to the same company.

### ISSUE THREAD

**Issue by edvinvoneuler** [tobymao/18xx#8622]
The names of companies on the "Entity" tab, the privates, and their abbrevations are mismatched. 

The abbrevations are of their "real name" and on the privates the "real names" are used but on the entity cards the name of the company is its starting location.

That means that the only connection between the nomenclature on the privates and the company entities is the abbrevation (only present on the entity cards).

That is confusing.

I would suggest either changing the privates so they use the naming convention of the entities or use the "real" names for the entities.

**Comment by benjaminxscott** [comment]
Could you clarify:

> on the entity cards the name of the company is its starting location.

Do you mean the `GSC` icon here, or the `Privates` list?

![Screenshot 2023-01-21 10 14 38 AM](https://user-images.githubusercontent.com/1711810/213882040-230f4293-9787-4384-adec-d4d02d73c54f.png)
