### ISSUE TITLE
Alternative column order in spreadsheet

### ISSUE THREAD

**Issue by Galatolol** [tobymao/18xx#8623]
**What's your idea?**

To make the spreadsheet more usable, especially on mobile, I propose to introduce an alternative order of columns, inspired by the rr18xx's spreadsheet. A new button ("Players/Corposrations first") would let you switch between two orders. "Players first" would be default and exactly the same as the current one.

The proposition:

![1](https://user-images.githubusercontent.com/10097748/208253075-00738781-0bb5-400b-9f38-4e46803f0675.png)

![2](https://user-images.githubusercontent.com/10097748/208253077-c1c0cfdc-8716-4c9f-8263-ed7a6d8030b9.png)

How the spreadsheet currently looks on mobile (the most important information related to corporations aren't visible):

![image](https://user-images.githubusercontent.com/10097748/210252995-f7a53741-61f1-4180-a8de-5178052db2c0.png)

Spreadsheet on rr18xx:

![Screenshot_20221114-170737](https://user-images.githubusercontent.com/10097748/210253195-4389fabf-237d-4509-b705-766ed117b28e.png)

**Comment by dfannius** [comment]
I prefer this layout to the current one (which I don't think had any deep design behind it).

**Comment by tobymao** [comment]
if this is preferred, reopen the PR and remove the option, only have this variant

**Comment by Galatolol** [comment]
I went with the option in case a hypothetical someone was used to the current view and preferred it. But wherever I presented the change, no one was defending the current view, so indeed we may try making the new one default.

**Comment by tobymao** [comment]
implemented
