### ISSUE TITLE
[18USA] Switch and signal (P19) not billing coal next to skipped city

### ISSUE THREAD

**Issue by bubba0077** [tobymao/18xx#8627]
**How to Reproduce the Problem?**
In a game of 18USA, during phase 5 (and possibly earlier), a company with the Switch and Signal (P19) private attached to a 3T ran Chicago (60)-Detroit (50)-Toronto (X)-D26 Coal (10)-NYC (80), skipping Toronto with P19. However, the mine is not included the in the total revenue, yielding only $190 instead of $200. (As shown in the screenshots, it may instead skip the higher-valued Detroit and keep Toronto and the mine, yielding the same total.)

Game copied to [hotseat game 106536](https://18xx.games/hotseat/hs_lrzkunke_106536)

![image](https://user-images.githubusercontent.com/4951788/210477472-53cfe412-3ba2-4adc-9afe-714e134f9289.png)
![image](https://user-images.githubusercontent.com/4951788/210477490-9fe4b005-e480-4e8a-a030-054e27a6ab07.png)

Suspect the game engine is determining whether to bill the mine based on whether the connecting cities are billed, so when one isn't billed it doesn't get counted. This bug may extend to other resource tokens and P19, and maybe any other games that have a private that allows skipping of a city and resource tokens (if any).

**Which Browser / Platform?**
Chrome 108.0.5359.125
Window 10 22H2

**Comment by crericha** [comment]
Hotseat games are local to your computer. I cannot see them. Please go to tools -> Game Data -> Download and attach that file.

**Comment by bubba0077** [comment]
Oops, sorry. Here's a gist: https://gist.github.com/bubba0077/7019e0b687132cd9a995744a83796493

**Comment by crericha** [comment]
The bug is that it is skipping Detroit and counting Toronto instead, which is why C23 is in parenthesis.

**Comment by bubba0077** [comment]
> The bug is that it is skipping Detroit and counting Toronto instead, which is why C23 is in parenthesis.

I noted it sometimes does that in the OP. I've seen it do both, and either way it is likely to ultimately be the same root cause, since with it not counting the mine if Toronto is skipped, the two are the same value.
