### ISSUE TITLE
[1846] Cannot skip trains without sending game out of sync

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#863]
Game ID 2648 B&O cannot skip buying trains. Has trains and there is no prompt regarding them. Pictured below is what happens after clicking skip trains. Attached is game data

https://gist.github.com/KillerOrca/6be011775f44fdbd34bdc5d3fe773491

![image](https://user-images.githubusercontent.com/67166181/85625476-5cc75f00-b620-11ea-9e07-6767cd52a705.png)

**Comment by tobymao** [comment]
looks like it got fixed according to your game log
