### ISSUE TITLE
See full upgrade path on the tiles view

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#865]
Hi, I think it would be nice to see which tile is an upgrade for which other one. For example in the "tile-tab", if you would click on green tile #28, that you would shade out all the brown tiles that don't fit on this green tile and keep for example #46 highlighted. Or alternatively, clicking on a tile in the "tile-tab" would make it turn around.
Furthermore, it would also be nice to be able to play around in the map a bit more with tiles, even though you may not have a legal connection, it is sometimes important to sort out which routes are possible in the long run, or which tiles may be used by your opponents, so you can anticipate better. I haven't really sorted out how this could be nicely implemented, but I would definitely use a feature like that.
Thanks for all the great work!

**Comment by jenf** [comment]
Separating the part on the map to #1279

This would being able to click on the tile and seeing the full upgrade path from yellow to grey.
