### ISSUE TITLE
[Rolling Stock Stars] Corporation in receivership closing -ve company

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#8666]
In -- Turn 8, Phase 4 - Closing --
PR close all other company and keep BME, but actually it should keep PR and close BME.

From the rules
If, following these rules, the corporation needed to close all its companies, keep the one with the highest face value. 
[hs_punztobr_1673865046.zip](https://github.com/tobymao/18xx/files/10435314/hs_punztobr_1673865046.zip)

**Comment by roseundy** [comment]
Dup of #8585
