### ISSUE TITLE
[Rolling Stock Stars] Investment Phase end even when player get legal action to do

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#8667]
In turn 2 phase 1
after horace win bids and buy AKE, he still get $13 to open auction for WT, but the system just directly pass to phase 2
[hs_punztobr_1673865046 (2).zip](https://github.com/tobymao/18xx/files/10435374/hs_punztobr_1673865046.2.zip)

**Comment by roseundy** [comment]
This is odd. I'll dig into it.

**Comment by roseundy** [comment]
The bug was a result of adding an auction to a "regular" 18xx stock round. Starting an auction didn't "unpass" that player for the purpose of determining when the round ends.
