### ISSUE TITLE
Running Routes on 1862

### ISSUE THREAD

**Issue by Voukwni** [tobymao/18xx#8670]
https://gist.github.com/Voukwni/73ecc07ab34614b7f30f49a3b17fa3a2

When i run 2 F1 trains, they must run as 1 F2. This doesn't happen there. I missing something or there is a problem?

**Comment by roseundy** [comment]
Both F1 trains need a token. You can't just string them together, which is why it gives you the message "Route must contain token"

**Comment by Voukwni** [comment]
Got it! Thanks a lot!
