### ISSUE TITLE
[1862] Unhandled error when trying to buy a train and warranties with unsufficient funds

### ISSUE THREAD

**Issue by Galatolol** [tobymao/18xx#8677]
**What's your Game ID?**

https://18xx.games/game/110458?action=77

**How to Reproduce the Bug?**

Buy a train with warranties in such a way that the total cost exceeds the treasury. An unhandled error appears:

![error](https://user-images.githubusercontent.com/10097748/213585290-c432fbd2-5881-4b4e-b5ae-e5b6c4f0057e.png)

**Which Browser / Platform?**
Firefox 103.1

**Comment by roseundy** [comment]
Missed a comma. Not sure why rubocop didn't flag it. The bug has been there since I originally coded 1862.
