### ISSUE TITLE
[1847 AE] Rules implementation

### ISSUE THREAD

**Issue by Galatolol** [tobymao/18xx#8688]
**General**
- [x] Trains
- [x] Phases
- [x] Stock market
- [x] Map
- [x] Tiles
- [x] Money, cert limit
- [x] Logos

**Private auction**
- [x] Draft
- [x] First round of draft in reverse order
- [x] Blue corporation operates in "short OR" if 50% bought
- [x] P1 "ignored" in "short OR" if not owned by player
- [x] May buy a quarry or investor company from another player for "any agreed upon" price

**Entities**
- [x] P0 - blue presidency
- [x] P1 - Locomotive Firm description, values etc.
- [x] P1 - stock marker, dividend
- [x] P2 - Rammelsbach Quarry
- [x] P3 - red presidency
- [x] P4, P5 - free mountain build
- [x] P6 - token for  half price 
- [x] P2, P4, P5, P6 - correct sale values
- [x] P4, P5, P6 - close in Phase 6E
- [x] P7, P8, P9 - investor
- [x] Corporations
- [x] Corporations' "ability" - may only build in hexes of X color in yellow phase
- [x] Corporations' "ability" - may be started only after the company X has floated
- [x] HLB - two homes

**SR**
- [x] Sell - buy
- [x] Price goes down always one space when selling
- [x] May not sell corporation that hasn't operated
- [x] Double shares
- [x] May sell/buy P1
- [x] Start corporations in order
- [x] Fixed par prices
- [x] 50% float
- [x] Home token upon floating
- [x] Incremental capitalization
- [x] Investor shares count towards floating and capitalization
- [x] May own over 60%
- [x] Exchange investor private companies for shares instead of a buy action (from phase 3+3 and if related corporation has floated)
- [x] Obligatory exchange of investor private companies in brown phase. Make sure that float percent is correct.
- [x] Nationalization

**OR**
- [x] Build 2 yellow tracks in yellow phase
- [x] Build 2 tracks on first operation
- [x] Build only on hexes of given color in yellow phase
- [x] Remove color icons in green phase
- [x] Double towns upgrade
- [x] 14 and 15 green cities don't upgrade
- [x] E9 - can't build in yellow and green phase, including P4 and P5 power
- [x] Semi-restrictive building
- [x] A-B route bonus (+40)
- [x] Mine-Z route bonus (+70, not if 6E train)
- [x] Market shares pay, IPO shares don't
- [x] Can't buy more than one train of given type
- [x] Train trading not allowed in first phase

**Game wiki**
- [x] Note that the rule saying that a given quarry may be bought by player only once per SR is not implemented
- [x] Presidency change - the new president decides the split - not implemented; they always give up two 10% shares if possible

**Comment by tobymao** [comment]
we don't have permission for this game yet

**Comment by Galatolol** [comment]
@tobymao We do, I wrote it on Slack.

**Comment by Galatolol** [comment]
Closing it - everything is implemented.
