### ISSUE TITLE
1822PNW - unable to upgrade Seattle hex 

### ISSUE THREAD

**Issue by cavedogpdx** [tobymao/18xx#8690]
https://18xx.games/game/107772 

The SWW has the money available to pay for the green tile #x21 for Seattle but no option pops up when I click on the hex. The company can upgrade other yellow tiles to green.
![1822pnw1](https://user-images.githubusercontent.com/115740780/213945249-adcfb6f1-f2a1-4fd8-8963-907944f539a4.jpg)
![1822pnw2](https://user-images.githubusercontent.com/115740780/213945255-d9fd0a24-3ee1-4845-8334-8b4d35fee448.jpg)

**Comment by outsidePasser** [comment]
Per the rules, Seattle cannot be upgraded to green, because Portland has already been upgraded to green.  Only one of the cities is allowed to be each color.
