### ISSUE TITLE
Spreadsheet tab

### ISSUE THREAD

**Issue by ArielAyanna** [tobymao/18xx#8695]
Please god revert the spreadsheet tab.  The new one is extremely bad for usability on phones. Player column is redundant,  and price and share distribution information too far away from company.  I play mostly in the spreadsheet tab.  My turns will take twice as long now at least.

**Comment by Galatolol** [comment]
Related issue: #8623

Having the button like initially proposed seems like a perfect solution to me.

**Comment by mb1898** [comment]
Please go back to the old spreadsheet. I need the player holdings and the player money one below the other. I have even on a pc screen to look right for the player holdings and then look below left to see the players' cash.
Terrible
