### ISSUE TITLE
[TOP1871] selling and splitting a corp did not count as an action in SR

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#8697]
https://18xx.games/game/110587 (pinned version 6636cbda4)

In this game, I split Summerside - ML into two corps. 
The previous player had passed, and when the next player passed, we immediately moved to the OR. 
I also tried backing up and selling shares before performing the split, no difference. 

possibly related to being a pinned game?

**Comment by tobymao** [comment]
don’t file issues for pinned games as they are no longer relevant or debugfabpe
