### ISSUE TITLE
[TOP1871] Using a starting seed doesn't maintain the assigned privates at game start, nor the Mainline and Shortline corps.

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#8698]
I tried recreating game 110587 with the same players using its seed 1111661112, but while our priority order in the auction remained the same, the privates assigned to each of us changed, which defeats the point to us. It also had different companies selected for the Mainline and Shortline.

My assumption was that using that seed, we would have the exact same starting setup as the previous game, not just the same turn order. Is my expectation wrong?

**Comment by tobymao** [comment]
seeds may not persist across games that got pinned because the logic has changed
