### ISSUE TITLE
Suggestions: Log, Game Mode, Timer & Player Stat 

### ISSUE THREAD

**Issue by Halekio** [tobymao/18xx#870]
There has been discussions of late concerning the annoyance created by people leaving games and/or taking a longer than expected amount of time playing their turn. 

In my opinion, any solution to this issue must be careful not to marginalize people nor force them to play at an imposed pace, but rather incentivize everyone to join games best suited to their own pace and to strive to respect other people's wishes for pace.

1) Game modes to indicate creator's intended pace for the game.
People usually specify this information on some way in the description for the game.
This would simply formalize a standard for communicating this intent and free the description field for its intended purpose.
  - Default : No expectation of pace
  - Fast: Expected 2+ or more moves per day
  - Semi-live: Expected 10+ moves pas day
  - Live: Game expected to be played in 1 sitting
  - Custom ? (specify min number of moves per day)

2) Time stamp for actions in the log
A way to show a player's idle time:
  a) [hh;mm;ss] + message, for each line added to the game log
  b) "Action has been on you for hh;mm;ss" when the player first acts on his/her turn

3) Player's statistics
Different stats could be compiled during a game and/or overall for a player
  a) Running total amount of idle time displayed next to the player's name
  b) Number of moves made per day / this day in this game (displayed next to player's name)
  c) % of games where the expected number of moves per days was (or was mostly) respected (displayed next to player's name) 

Someone constantly not respecting the game's expected pace would see his rating lowered and would self correct or eventually have a hard time finding players to play with in games other than "Default / No pace requirement".

Anyway, just my 0.02$ on the subject.

**Comment by benjaminxscott** [comment]
ELO and karma would be cool

Perhaps have (configurable) settings for "action clock": either 5m for "live" games, or 24h for "async games"
(The latter accommodates time zones)

The penalty could be off the ending score, for instance $1 or $10 per interval missed
so in a live game, if I take 15m for a turn I get a $2 penalty at the end
or in an async game if I take 72 hours to take a turn I get $20 penalty at the end

with a one-time grace period of 1 interval or something, if someone needs 10m to eat during a live game

**Comment by yraelrocks** [comment]
ELO would be great!
