### ISSUE TITLE
[1828.games] Illegal route for C&P

### ISSUE THREAD

**Issue by 8bg** [tobymao/18xx#8709]
**What's your Game ID?**
110756

https://18xx.games/game/110756

- Bug can be seen from here https://18xx.games/game/110756?action=132 -- clear train and choose Auto Route. It allows a route not connected to C&P tile: 
![image](https://user-images.githubusercontent.com/33561233/214608492-7c856d3b-a2b0-4536-894b-41291e8b394b.png)

**Comment by crericha** [comment]
C&P runs a route that includes the tile laid by the C&P, not it's token.
