### ISSUE TITLE
Game 104478 won't load

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#8713]
The game page hangs with "Loading game...".

**Comment by roseundy** [comment]
"no implicit conversion of NilClass into String"

**Comment by chapel** [comment]
Having the same issue (same error as well) on game 110731

This is an 18cz game.

My 1817na game is working fine currently.

**Comment by dfannius** [comment]
@scottredracecar 1828, as the label says. Anyway it has been closed as completed and it works again now, thanks to whoever fixed it!

**Comment by dfannius** [comment]
Looks like it was fixed by #8714.
