### ISSUE TITLE
[1880] Reverse the order of market legend

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#8715]
Given that these bonuses increase from left to right in the market, it would make more visual sense if they did in the Legend too. 

![1880](https://user-images.githubusercontent.com/26125362/214676093-59dd9101-1338-4b7c-9cc9-39e482a6abb4.png)

**Comment by benjaminxscott** [comment]
For some reason we reverse the list, unless it's a 1D market
https://github.com/benjaminxscott/18xx/blob/master/assets/app/view/game/stock_market.rb#L359

if that LoC is removed, we get:
![Screenshot 2023-01-25 5 31 35 PM](https://user-images.githubusercontent.com/1711810/214735862-964c1a66-34bc-45bc-8984-2c50a68a5b52.png)

Not sure if a 1D market is meaningfully different with that approach, it looks like

![Screenshot 2023-01-25 5 31 46 PM](https://user-images.githubusercontent.com/1711810/214735858-03883f69-2869-4f6f-89e2-79d178473c3e.png)

**Comment by bentziaxl** [comment]
Chris proposed ordering the map legends by their order in MARKET_TEXT. 
After this changes goes in, each game can fine tune which order they want the map legend entries to be
