### ISSUE TITLE
[1880] SCR, QSR error on place_home_token when floating in SR 2 and later

### ISSUE THREAD

**Issue by Dave4B** [tobymao/18xx#8720]
Hotseat game. The final pass in a stock round resulted in a pink full-screen message about Undefined Method for pending_tokens... Then returns to ask the player to pass again. Screenshot and Json attached.
![_001_25012023_212506](https://user-images.githubusercontent.com/76797371/214696805-679298a5-e609-4bad-b5ac-587649738acc.jpg)
[hs_yrdcazwe_1674672365.json.txt](https://github.com/tobymao/18xx/files/10503922/hs_yrdcazwe_1674672365.json.txt)

**Comment by bentziaxl** [comment]
it has to do with opening QSR and/or SCR in a any SR other than the first. Real issue, will be fixed later
