### ISSUE TITLE
[1822PNW] GameError: 63 is not upgradeable to 455

### ISSUE THREAD

**Issue by Lochdur** [tobymao/18xx#8721]
Went to conduct my turn and received this message:

We're sorry this game cannot be continued due to GameError: 63 is not upgradeable to 455
Broken action: { "type": "lay_tile", "entity": "CPR", "entity_type": "corporation", "id": 1292, "created_at": [1673662444](tel:1673662444), "hex": "D19", "tile": "455-0", "rotation": 0 }

https://18xx.games/game/104443?action=1291

**Comment by benjaminxscott** [comment]
I suspect this commit broke the game https://github.com/tobymao/18xx/commit/5e5acb67be8e15378f65a3e784e22b15d0b4fcf7

PNW is in alpha so we don't pin to a 'working old version', so I think it's unrecoverable TBH
