### ISSUE TITLE
[1866] Blocking step Stock Turn Token cannot process action 438

### ISSUE THREAD

**Issue by woodfeld** [tobymao/18xx#8722]
https://18xx.games/game/108007?action=437

Got this error when entering game.  We'd actually been much further along in game than where it currently shows.  Not sure what happened.

**Comment by benjaminxscott** [comment]
There's some bug that was triggered, which means it will only be able to load a previous action (437) that is older than your most recent action

> GameError: Blocking step Stock Turn Token cannot process action 438
Broken action: { "type": "pass", "entity": "GL", "entity_type": "corporation", "id": 438, "created_at": 1674140928 }

**Comment by woodfeld** [comment]
One thing I do notice is that the GL company was in our game (& NRS was removed during initial setup), but now it shows that GL isn't available, but NRS is.  So it seems to be going back in time to when a player started the GL.  No idea how/why this happened though.
