### ISSUE TITLE
[1880] No visibility of sold shares , pay dividend for bank shares and not more income depending on market price

### ISSUE THREAD

**Issue by Voukwni** [tobymao/18xx#8728]
https://18xx.games/game/111331

There are 3 problems:
1. When someone sell some shares to the bank, these shares aren't visible anymore. Although, they aren't visible, the game gives you the ability to buy these shares.
2. The sold shares pay dividends to the company for some reason. Not the shares that are on the IPO but the shares that are on the market.
3. The dividend for each share isn't increased if the market price is on the yellow zone(don't know for the other zones)

**Comment by bentziaxl** [comment]
1, 2 are related. It fails when presidency changes, it goes to the market instead of IPO.

3 -> where do you see that it's not being added. it should be 50 to the toal run amount for the company

**Comment by Voukwni** [comment]
> 1, 2 are related. It fails when presidency changes, it goes to the market instead of IPO.
> 
> 3 -> where do you see that it's not being added. it should be 50 to the toal run amount for the company

you are right. I did mistake with 3.
