### ISSUE TITLE
Restrict or Remove END GAME button on Tools

### ISSUE THREAD

**Issue by Qualm64** [tobymao/18xx#873]
Currently anyone can just abort a game at apparently any point they feel like it.  There are many different ways it could be programmatically restricted (ex: boardgamearena requires confirmation from all players to end a game without penalties), but maybe it can simply be removed on games out of beta until that is solved?

Just had someone END GAME on 1748 for no apparent reason, without discussion.

**Comment by tobymao** [comment]
that's intentional, if someone doesn't want to play, they should be able to end the game. if you want to continue without them, you can undo and master mode them.

**Comment by scottredracecar** [comment]
Possibly the system killed this game, not a player.

**Comment by tobymao** [comment]
nope there is no such system

**Comment by scottredracecar** [comment]
I meant the Toby system...

**Comment by tobymao** [comment]
we have confirmed that a player did indeed end the game
