### ISSUE TITLE
1888  111096

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#8737]
No Destination Bonus given for JHR

**Comment by roseundy** [comment]
Gist or Game id, preferably with action number?
I can't debug without details.

Please look at https://github.com/tobymao/18xx/issues/new?assignees=&labels=needs+triage&template=bug_report.md&title=

**Comment by saxafras** [comment]
Game ID as in title  111096.  How do i find the action number?

    Le vendredi 27 janvier 2023 à 08:01:07 UTC−9, Steve ***@***.***> a écrit :  
 
 


Gist or Game id, preferably with action number?
I can't debug without details.

Please look at https://github.com/tobymao/18xx/issues/new?assignees=&labels=needs+triage&template=bug_report.md&title=

**Comment by saxafras** [comment]
45 minutes ago the JHR ran this morning...the minute is "23" after the hour if that helps

    Le vendredi 27 janvier 2023 à 08:01:07 UTC−9, Steve ***@***.***> a écrit :  
 
 


Gist or Game id, preferably with action number?
I can't debug without details.

Please look at https://github.com/tobymao/18xx/issues/new?assignees=&labels=needs+triage&template=bug_report.md&title=

**Comment by roseundy** [comment]
https://18xx.games/game/111096?action=167

**Comment by roseundy** [comment]
To receive the bonus, a single train must reach both the home and destination hexes. In this case, two 2T trains were run.
