### ISSUE TITLE
[Shikoku 1889]: GameError: Blocking step Place a Token cannot process action

### ISSUE THREAD

**Issue by olsonm16** [tobymao/18xx#8744]
- Game:  https://18xx.games/game/110147
- Action: https://18xx.games/game/110147?action=356

**How to Reproduce the Bug?**

Honestly not sure what happened. A past action (356) where TR ran routes seems to have somehow broken the current game state on their next turn. Really strange!

**Comment by michaeljb** [comment]
TR was supposed to be charged ¥80 for this tile lay https://18xx.games/game/110147?action=173

I haven't found the code in #8679 that broke this, but I did verify it works correctly at e1ba6ca66 (just before #8679 was merged) and not at 1a4487861

**Comment by tobymao** [comment]
we should fix this soon or revert #8679 

@crericha @bentziaxl
