### ISSUE TITLE
[Rolling Stock Stars]IPO Phase : incorrect logs 

### ISSUE THREAD

**Issue by Unless4934** [tobymao/18xx#8747]
STEPS 
Invest  in a private company
In IPO phase, convert Private to corporation of your choice.
Check the consistency and compliance of the logs related to the company's treasury

EXPECTED RESULTS
For an MS converted to corporation SM of a value of 20, the expected logs should be : 
_MS converts to a corporation: Stock Masters
SM share price is set to $20
[player] pays difference of $3 to SM and receives 1 share
[player] becomes the president of SM
SM floats
SM issues 1 share and receives $23_

ACTUAL RESULTS 
MS converts to a corporation: Stock Masters
SM share price is set to $20
[player] pays difference of $3 to SM and receives 1 share
[player] becomes the president of SM
SM floats
SM issues 1 share and receives **$60**

Seems to come from the fact that the logs (value*3) are hard coded in this part of the code : 
`@log << "#{corporation.name} issues #{num_to_buy} share#{num_to_buy > 1 ? 's' : ''} and receives "\                    "#{@game.format_currency(share_price.price * 3)}"`

GAMES IDs
Can be seen in 107191?action=104, but can be found in any game.

**Comment by roseundy** [comment]
I left a number hard-coded after a refactoring when I should have used in the log the variable I created.
