### ISSUE TITLE
1880 Unable to buy 2P train and wrong ending company selected

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#8748]
copied and pasted 

[Kenneth Kuehner]

This is for game Id: 111550  The first thing I noticed is the 6E train is selling for 600 and it's supposed to be 700.  A player wanted to buy a 2 train when they became available and was unable to, he did meet all requirements had money and a train space, when the game end was activated instead of the player who activated being the one who trigger the next round it put it on the next player in this case QSR player when the WNR player activated game end and then when the game should of ended it lets players keep playing infinitely. Those are the things I noticed. As far as game play help, it would be nice it the chat would tell how much each player got for the bonus run amounts when they run. That's all I have. Thanks for putting 1880 on the website and the work you do for the website, I know it's a lot of work!

**Comment by crericha** [comment]
6E price was fixed yesterday and deployed
