### ISSUE TITLE
[1846][hotseat] Missing error message

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#875]
Running a hotseat game of 1846, tried to lay a tile with a company that could pay the $20 but couldn't cover the $40 hexside fee.  Clicking the checkmark didn't appear to do anything.  Tried to reload and got the game error it failed to properly display

https://gist.github.com/gchambers419/626650a171b69e0dab003c6e4a07a817

**Comment by tobymao** [comment]
can't repro game is broken
