### ISSUE TITLE
[1880: China] Renenue at JHU not correct 40+40=130

### ISSUE THREAD

**Issue by VerspaetungDB** [tobymao/18xx#8765]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by bentziaxl** [comment]
The issue is missing links, json, info on how to reproduce. 
Based on the title, it seems that the total run was 50 more than expected, was JHU stock in the +5/share bonus section of the stock market?
If so, that is as expected and per rules.
![image](https://user-images.githubusercontent.com/108803147/215351868-cf3adf6c-b808-4de4-a280-f495e478855b.png)

**Comment by VerspaetungDB** [comment]
Hi Ben,you are right. That is exactly what happened. So sorry for wasting your time. Everything is as it should be.Thanks for the great work.Cheers MirkoGesendet mit der mobilen Mail AppAm 29.01.23 um 20:44 schrieb BenA
                
            
            
                
                    Von: "BenA" ***@***.***>Datum: 29. Januar 2023An: "tobymao/18xx" ***@***.***>Cc: "Author" ***@***.***>,"VerspaetungDB" ***@***.***>Betreff: Re: [tobymao/18xx] [1880: China] Renenue at JHU not correct 40+40=130 (Issue #8765)
                
                
The issue is missing links, json, info on how to reproduce.
Based on the title, it seems that the total run was 50 more than expected, was JHU stock in the +5/share bonus section of the stock market?
If so, that is as expected and per rules.
