### ISSUE TITLE
[1822MX] Page freeze when closing Stock Drop P16 while acquiring minor

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#8767]
**How to Reproduce the Bug?**
This bug is seen from a hotseat off of game [109442](https://18xx.games/game/109442), but I'm not able to reproduce the bug from the actual real timeline of that one. 

I've got the stock drop private (P16-VTPN) in the MC. I'm about to acquire Minor 13. In the middle of those action steps, there's the ability to close P16 and drop the stock price. 

I think it happens because stock plus remaining cash is exactly the right amount to compensate me for the 13. MC needs to give me $220 in stock + cash. Stock price is at $30, cash at $160. By dropping the price, it's $10 short and no longer possible to compensate me, but I'm already in the middle of the acquisition steps. 

I'm posting a gist containing the json for penultimate step; if this is loaded up, I think if the next action take is "Close P16" then the webpage will freeze. 

The gist: https://gist.github.com/yoyoson/5582519912fd41f26d4575b75ccfd493

I could just do it ~~before starting the acquisition steps~~, or immediately after. But dropping the stock price is possibly more beneficial for me or for MC, since the stock price figures into single vs double jumping and for the cash needed to compensate me (the owner of 13). 

  -Desktop Chrome, 109.0.5414.120 (Official Build) (64-bit) (cohort: Stable)

**Comment by michaeljb** [comment]
> I'm posting a gist containing the json for penultimate step; if this is loaded up, I think if the next action take is "Close P16" then the webpage will freeze.
>
> The gist: https://gist.github.com/yoyoson/5582519912fd41f26d4575b75ccfd493

I was able to reproduce the issue in hotseat with these instructions.

**Comment by outsidePasser** [comment]
My assumption is the correct way to fix this is to not allow actions from privates during the middle of an acquisition.

**Comment by outsidePasser** [comment]
I was wrong with my assumption - you can do the actions from privates in the middle.  There was a bug in minor_acquisition auto_actions.
