### ISSUE TITLE
Sandbox error - terminated after license selection of BCR

### ISSUE THREAD

**Issue by AbnRgr1978** [tobymao/18xx#8768]
Sandbox game to check and remember how to play 3 players.

After Start of BCR, after selecting licence interrupted connection to check games and came back to this error.
[Error.txt](https://github.com/tobymao/18xx/files/10531721/Error.txt)

**Comment by AbnRgr1978** [comment]
We're sorry this game cannot be continued due to GameError: Invalid building permit (30). Choices are ABC,BCD.
Broken action: { "type": "choose", "entity": 0, "entity_type": "player", "id": 25, "created_at": 1675046298, "choice": 30 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include

**Comment by AbnRgr1978** [comment]
After reading the rules (for the first time in many years)  I think the error was that the BCR was offered the option of  selecting a ABC permit which I took.  I think that was after I took the AB permit.

**Comment by crericha** [comment]
Yes, I've seen this too in hotseat mode. There is a bug somewhere in the frontend cache used for parring, where it isn't updating correctly. To work around the issue, refresh your page before parring a company.
