### ISSUE TITLE
[18Rhl] Illegal route allowed

### ISSUE THREAD

**Issue by Galatolol** [tobymao/18xx#8774]
**What's your Game ID?**

https://18xx.games/game/111564?action=95 - got to the Run trains step and hit Auto.

A route going from one part of a Rhine Metropolis to another is allowed which shouldn't be the case.

> **A route comprises of at least two different cities** or off-board destinations that are connected by track.
> Each route must contain somewhere on it a station marker of the corporation using the route. A route may
> neither start nor end at a town. 
> (....)
> When the hexes of the “Rhine Metropolis” have been upgraded in green the Rhine can be crossed there by
> a “Trajekt“ (railroad ferry). The three station spaces on the green Metropolis tiles are regarded as one
> city tile with three station spaces
> {...}
> As long as the “Rhine Metropolis“ hexes have not been upgraded (they show still the yellow base) the two
> sides of the river are treated as separate cities on the same tile.

**How to Reproduce the Bug?**

Have a corporation with a station in a green "Rhine Metropolis". Run a train from one city part to another, through the ferry link.

**Which Browser / Platform?**
Firefox 103.1

**Comment by Galatolol** [comment]
@perwestling I assume you don't have time for this - can I fix it instead?

**Comment by perwestling** [comment]
@Galatolol Sure. I have been very busy the last couple of months.
