### ISSUE TITLE
[18USA] Great Northern Railway private doesn't give bonus for 2nd train.

### ISSUE THREAD

**Issue by jrt1817** [tobymao/18xx#8776]
https://18xx.games/game/109721

The GNR private reads "+$30 revenue bonus per train that runs Fargo - Helena."

The UP is running two trains in OR 2.1, but the bonus is only applied once. I tried it several times.

I suspect it hasn't been caught b/c it's pretty rare for someone to build a second route w/ this private.

**Comment by crericha** [comment]
Per the rules, the bonus can only be received by one train.

**Comment by jrt1817** [comment]
So the text on the card is wrong, then?

**Comment by crericha** [comment]
Sure, that would be helpful. Please submit that issue.

**Comment by jrt1817** [comment]
Done.

**Comment by crericha** [comment]
Thank you!
