### ISSUE TITLE
[1880] Game locks after the 4 trains when rocket is unused, and all 4 trains need to be exported

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#8781]
We're unable to load the game after the 4s were exported: https://18xx.games/game/111402
It just sits on a Loading Game screen.

There was another report in chat with a similar issue, but i don't know if anything was filed.

**Comment by bentziaxl** [comment]
this is due to an edge case:
rocket of china hasn't been traded into a train AND
no one bought the 4 train, and it was exported

**Comment by bentziaxl** [comment]
you ran into this: https://boardgamegeek.com/thread/1042314/forced-exchange-p7-rocket-and-removal-unpurchased
