### ISSUE TITLE
don't need master mode to pass (main page text)

### ISSUE THREAD

**Issue by arcee1986** [tobymao/18xx#8784]
"In multiplayer games, you'll also be able to make moves for other players, this is so people can say 'pass me this SR' and you don't need to wait. To use this feature in a game, enable "Master Mode" in the Tools tab. Please use it politely!"

Given the existence of autopass, this can probably be removed.  I'm not sure Master Mode needs to be prominently displayed these days but if it does it should have a more relevant example.

**Comment by benjaminxscott** [comment]
Good idea, could you reply with preferred wording?

In case it's relevant, here's the file where that text lives:
https://github.com/tobymao/18xx/blob/master/assets/app/view/welcome.rb#L49

**Comment by arcee1986** [comment]
perhaps replace just this clause:

this is so people can say 'pass me this SR' and you don't need to wait. 

with: 

for example somebody can say 'just run my trains and pay out' and you don't need to wait.

     On Saturday, February 4, 2023, 11:00:08 p.m. NST, Benjamin Scott ***@***.***> wrote:  
 
 


Good idea, could you reply with preferred wording?

In case it's relevant, here's the file where that text lives:
https://github.com/tobymao/18xx/blob/master/assets/app/view/welcome.rb#L49

**Comment by benjaminxscott** [comment]
I have another larger change that would incorporate these changes, in case someone gets to this before me

**Comment by tobymao** [comment]
closed as stale
