### ISSUE TITLE
1856 - the best route is not found

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#8785]
Game: 1856 - 109261
https://18xx.games/game/109261
action
https://18xx.games/game/109261?action=901

the former auto-routes in OR8.1 were with (a sum of 1160):
6 train: J15-L13-N11-M10-L9-K8
Diesel:  Q10-P9-N11-N9-N3-M4-M6-M10-L13-L15-N17-O16-O18-N17-K16-J17-I14-J13-J11-I12-J9-K8

the auto-routes in OR8.2 are with (a sum of 1120):
6 train: L13-N11-M10-L9-K8 (only 5 stations)
Diesel: Q10-P9-N11-N9-N3-M4-M6-M10-L13-L15-N17-O16-O18-N17-K16-J17-I14-J13-J11-I12-J9-K8

This happened on a mobile phone, a laptop and a pc.

**Comment by tobymao** [comment]
auto router doesn’t always give best route

**Comment by scottredracecar** [comment]
I tested on an M1 iMac and autorouter found the 1160 route in 10 seconds. I
think in this case, more powerful hardware will perform better. Lesser
hardware will timeout before it tests all routing.
