### ISSUE TITLE
1866 - Disappearing company KPS

### ISSUE THREAD

**Issue by deeseja** [tobymao/18xx#8799]
**What's your Game ID?**
111705

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like https://18xx.games/game/111705

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`
https://18xx.games/game/111705?action=90
Not 100% sure this triggered it as if I undo back to here and undo this action, I cannot find KPS to float again as it is completely gone from the roster.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
Just noticed later in the game that KPS was no where to be found but still shows me owning 40% of it.

**Which Browser / Platform?**
- Browser Version
Version 109.0.5414.119 (Official Build) (x86_64)
- Platform (Mobile, Tablet, Desktop)
Mac OS Desktop

**Comment by scottredracecar** [comment]
Possibly the just-deployed code affected the companies determined by the
initial randomization process. If this significantly impacts the game, I'd
suggest a restart. I don't think this code is going to change significantly
again for many months. It has been playtested for the last few months.

**Comment by deeseja** [comment]
That makes sense, thanks @scottredracecar.  We backed it up to try floating a different company and just ignore the KPS.  If that doesn't pan out, will just restart.
