### ISSUE TITLE
1846 - upgrading G19/Wheeling should preserve both port icons

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#880]
This was caused by this line, but I haven't looked at 1882 or that PR enough to know that line was fixing - https://github.com/tobymao/18xx/pull/826/files#diff-489105431840138935ce969dd570ab2cR127

Before the upgrade:
![Screenshot from 2020-06-25 23-53-37](https://user-images.githubusercontent.com/1045173/85825322-26cccc80-b73f-11ea-8b3e-260cf86aff20.png)

Current behavior:
![Screenshot from 2020-06-25 23-51-57](https://user-images.githubusercontent.com/1045173/85825221-e705e500-b73e-11ea-9f72-3b7377de5fc9.png)

Desired behavior:
![Screenshot from 2020-06-20 15-38-49](https://user-images.githubusercontent.com/1045173/85825278-069d0d80-b73f-11ea-8e41-423204ee8cab.png)

**Comment by benjaminxscott** [comment]
To note that green Wheeling erroneously gets a $20 bonus instead of $40 due to this bug 
[repro](https://github.com/tobymao/18xx/files/4839804/cwi_bo.json.txt)
