### ISSUE TITLE
1880 companies float as soon as shares owned hits threshold - not at the end of the SR

### ISSUE THREAD

**Issue by steve-yu** [tobymao/18xx#8801]
When starting new companies in 1880, as soon as number of shares needed to float is reached, the company floats even if the share is immediately sold afterwards.

Rules state that the requisite number of shares need to be owned at the end of the SR.

**Comment by crericha** [comment]
Please link a game where the problem happens.

**Comment by steve-yu** [comment]
https://18xx.games/game/112641 

Action was undone, but cloning during the last stock round should show the problem.

**Comment by crericha** [comment]
Thank you!

**Comment by crericha** [comment]
Link to the end of the SR: https://18xx.games/game/112641?action=915

**Comment by jemiahlee** [comment]
I think it is actually here (2nd-to-last SR): https://18xx.games/game/112641?action=801
