### ISSUE TITLE
Error in 1880

### ISSUE THREAD

**Issue by Trigo4** [tobymao/18xx#8803]
https://18xx.games/game/111314?active=1

I'm running into an error exchanging the Rocket for a T4. "The server does not accept this action due to wrong number of argument. Given 2, expect 3"

**Comment by bentziaxl** [comment]
I can't reproduce, is it happening at the forced exchange step? or earlier in the game?

**Comment by Trigo4** [comment]
Forced exchange for the 2nd T4.\\

Ken Soo 

    On Tuesday, February 7, 2023 at 01:02:42 AM CST, BenA ***@***.***> wrote:  
 
 


I can't reproduce, is it happening at the forced exchange step? or earlier in the game?
