### ISSUE TITLE
[1822PNW] GameError: Blocking step Buy Trains cannot process action 262

### ISSUE THREAD

**Issue by jaysonwhaley** [tobymao/18xx#8809]
**What's your Game ID?**
Redbeard
https://18xx.games/game/111928

**How to Reproduce the Bug?**

Timpe was playing Minor 20 and bought a 2 train which resulted in the following error showing up in the top of the browser:

We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 262
Broken action: { "type": "pass", "entity": "8", "entity_type": "corporation", "id": 262, "created_at": 1675795049 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/111928?action=261)

**Comment by michaeljb** [comment]
I've pinned your game to the previous version, so you should be able to finish it now. Thanks!

**Comment by jaysonwhaley** [comment]
Thank you!
