### ISSUE TITLE
[1866] Broken game: Blocking step Lay Track cannot process action 1113

### ISSUE THREAD

**Issue by shamblen** [tobymao/18xx#8810]
https://18xx.games/game/110697
Crashed, unrecoverable game.  Not sure what triggered it... tokening Berlin?  Laying track in Brussels?

https://18xx.games/game/110697?action=1112

Error message:
We're sorry this game cannot be continued due to GameError: Blocking step Lay Track cannot process action 1113
Broken action: { "type": "place_token", "entity": "NRS", "entity_type": "corporation", "id": 1113, "created_at": 1675628475, "city": "207-2-0", "slot": 0, "tokener": "NRS" }

**Comment by magnusstjarnhild** [comment]
This is a pinned game and sorry to say no way to fix it.

**Comment by shamblen** [comment]
Would then be possible to end/close the game?  It's sitting open for all of us, and we can't end it on our own.
