### ISSUE TITLE
[1852] 3E is counting all stops

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#8820]
https://18xx.games/game/112806?action=392

3E is counting all stops toward its revenue (like an 1830 Diesel) rather than just the 3 best stops.

Worked fine before latest code changes to this game.

**Comment by roseundy** [comment]
I must have messed this up with my East St. Louis change.

**Comment by roseundy** [comment]
>           # if no dit stops
>           return visits if dit_stops.empty?

Needs to be:
return super if dit_stops.empty?
