### ISSUE TITLE
1848 game 108717 - Placing Tasmanian Tile problem

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#8827]
https://18xx.games/game/108717

https://gist.github.com/benjaminxscott/7a32c1952e850cd6756d5282ee8ec36b

The 1848 game wants me to place the Tasmanian tile.  When I do so, the program displays about 10 lines of gibberish for a few seconds instead of placing the tile on the board.  It appears to be a malfunction.  The game number is 108717.

![Screenshot 2023-02-11 9 20 19 AM](https://user-images.githubusercontent.com/1711810/218271899-56f79b16-275d-4772-9da2-224f338a0377.png)

**Comment by Rupre** [comment]
I have just tried to place the tile and the problem continues to exist.

**Comment by dfannius** [comment]
The fix has not been deployed yet.

**Comment by Rupre** [comment]
Thank you for fixing this problem.  The tile is placed and the game has
resumed!
