### ISSUE TITLE
See operating order on Spreadsheet during Stock round

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#883]

**Comment by ChrisTheCat** [comment]
This should be closed, is already implemented @jenf

**Comment by dfannius** [comment]
It doesn't look implemented to me, unless it's functional in some cases and not others.

**Comment by jenf** [comment]
Nope, it's not, while it's now sorted by operation order, it doesn't show this as a number.

**Comment by ChrisTheCat** [comment]
Maybe I am confused - isn't this sorted by order, with numbers?

<img width="1440" alt="Screen Shot 2020-10-26 at 10 10 18 AM" src="https://user-images.githubusercontent.com/8732435/97204591-7f56b980-1773-11eb-9172-8e2f7156a9f3.png">

**Comment by dfannius** [comment]
I do indeed see numbers there. That's during the stock round? This is what the spreadsheet of my current 1882 game looks like during SRs:
<img width="531" alt="Screen Shot 2020-10-26 at 13 13 31" src="https://user-images.githubusercontent.com/1295244/97204976-2bf16500-178d-11eb-993c-fc997021b645.png">

**Comment by jenf** [comment]
In a SR it looks like https://www.18xx.games/game/13323

**Comment by dfannius** [comment]
Oh, it must be during an OR because there are some payouts in the OR History. This issue is about stock rounds.

**Comment by jenf** [comment]
It needs the order moving from the operating round to the game, so that it can be called at any time.

**Comment by ChrisTheCat** [comment]
Ah, I see, sorry for injecting confusion into the request.

**Comment by tobymao** [comment]
is this fixed?

**Comment by jenf** [comment]
Nope the limitation of not seeing the or order in stock round still exists. Itd need some refactorin so not a good first issue any more
