### ISSUE TITLE
[Harzbahn 1873] Hex F7 should cost 100 M to build, not 50 M

### ISSUE THREAD

**Issue by orome** [tobymao/18xx#8830]
On the physical game map hex F7 costs 100 M to build, but 18XX.games shows it costing 50 M.

**Comment by scottredracecar** [comment]
This is a difference between first and second edition. This should probably be updated to the second edition cost.
https://docs.google.com/document/d/1puHQJV4eLeunOtu_RyqAT-_mBCI93u8dqSBNwWMsAiE/edit

**Comment by KlausKiermeier** [comment]
I disagree. In the first edition the building cost for this  hex was 50M. And I, as the developer, still prefer it this way. I suggest to offer as an alternative a choice between 50M (1st edition) and 100M (2nd edition).

**Comment by orome** [comment]
Either way: change or user option would be great.

**Comment by scottredracecar** [comment]
I added a note to the wiki.

**Comment by KlausKiermeier** [comment]
Where is it? I didn't find it.

**Comment by scottredracecar** [comment]
https://github.com/tobymao/18xx/wiki/Harzbahn-1873
Implementation Notes

**Comment by KlausKiermeier** [comment]
Thanks, Scott!

**Comment by roseundy** [comment]
Given the designer prefers it this way, I'm going to close this bug.

**Comment by orome** [comment]
Agreed: Not a bug, but a suggestion: #8837
