### ISSUE TITLE
1848 - Possibly incorrectly allows Upgrade Discount for 5s and 6s.

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#8844]
Rules mention only the first 4T or 4+T can upgrade to a D train for a $300 discount. It does not mention any other upgrades for discounts are possible.

> When the first train (8/D) is purchased in Phase 7, the purchaser
> can trade in a 4/4+ train and get a discount of 300 pounds from
> the cost of a D train.

**Comment by ChrisTheCat** [comment]
<img width="1097" alt="Screenshot 2023-02-15 at 07 56 23" src="https://user-images.githubusercontent.com/8732435/219081344-6f615518-04e3-4205-ac62-791eb1dca61a.png">
