### ISSUE TITLE
18Chesapeake: Illegal tile lay for P3 (B&S on F4 and G5) allowed by interface.

### ISSUE THREAD

**Issue by hamigua2000** [tobymao/18xx#885]
A player laid two unconnected tiles for P3. See game id 2468, OR4.1, player columbria operating the C&A.

**Comment by jenf** [comment]
The action it occured
18xx.games/game/2468?action=210

**Comment by tobymao** [comment]
i'll fix it in my rewrite probably

**Comment by jenf** [comment]
Still an issue post rewrite, after undos removed action is
https://18xx.games/game/2468?action=190
