### ISSUE TITLE
[1880] Token Placement allowed on D12 (Shenyang & Fushun - QSR Home) before QSR started

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#8853]
GameID: https://18xx.games/game/111286

Specific Action Link: https://18xx.games/game/111286?action=379

JHA was able to place a token on D12, which is QSR's home. QSR has not yet started. 1880 rules prohibit placing a token on either the QSR or SCR home until the associated company's home token has been placed (see bottom of page 13 of rules pdf linked in the game Info section).

**Comment by philcampeau** [comment]
Helmut Ohley confirmed the reservation is only in yellow/green. https://boardgamegeek.com/thread/3030201/article/41751358#41751358
