### ISSUE TITLE
[1846] Payout / Withhold / Half Pay UI enhancement

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#886]
While selecting routes, the **submit** button name changes to reflect the total amount of the run(s). Once you submit the runs, the individual runs and their values are logged but not the total value. After the submit, the screen changes to offer **Payout** / **Withhold** / **Half Pay** buttons, but at this point there is no indication of the value that would go to stock holders or the company, or what that would do to the stock price.

It would be nice if the UI displayed more information.

Assume that a company is going to pay out $430, and its current share price is $150: 
* If it pays in full, that's $43/share and a double jump to $180. 
* If it half-pays, that's $210 to the company, and $22/share, and a single jump to $165. 
* If it withholds, thats $430 to the company and it falls back to $137.

### Idea 1: Change the button text to reflect the effects

**[ Full pay, $43/share ]** **[ Half pay, $210 + $22/share ]** **[ Withhold $430 ]**

### Idea 2: Create a table that describes the effects, with a plain button for each section

| [ Full Pay ] | [ Half Pay ] |[  Withhold ] |
| --- | --- | --- |
| Pay $43/share | Pay $23/share |  |
| | Keep $210 | Keep $430 |
| Right 2 ($180) | Right 1 ($165) | Left 1 ($137) |

**Comment by wcraigtrader** [comment]
Also, IMO, the current button ordering ( Payout | Withhold | Half Pay ) would be better rendered as ( Full Pay | Half Pay | Withhold ), even if you didn't make the other changes.

**Comment by benjaminxscott** [comment]
related? https://github.com/tobymao/18xx/issues/794

**Comment by wcraigtrader** [comment]
@benjaminxscott Basically the same issue, though this proposes different solutions.

**Comment by benjaminxscott** [comment]
+1 for (2) since it helps users understand the side effects of each decision
