### ISSUE TITLE
1866 game stuck - 110695

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#8861]
https://18xx.games/game/110695?action=1377

"We're sorry this game cannot be continued due to GameError: Blocking step Place a Token cannot process action 1378
Broken action: { "type": "sell_shares", "entity": "SSFL", "entity_type": "corporation", "id": 1378, "created_at": 1676474008, "shares": [ "SSFL_7", "SSFL_8" ], "percent": 20 }
Please raise a bug report and include this link (https://18xx.games/game/110695?action=1377)"

All players see this message regardless of OS/browser.

**Comment by michaeljb** [comment]
game is already pinned and is still broken, closing

**Comment by Aznd4u69** [comment]
Stop emailing me!
