### ISSUE TITLE
[1861] Game incorrectly ending when bank broke

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#8862]
Not a game I was in, but https://18xx.games/game/112652 ended at the end of the OR when the bank broke before the first 8T was purchased, even though the RSR had the funds to buy the first 8T.

Relevant rule from the A-A edition rules:
"The game may also end if the Bank runs out of money
before the purchase of the first 8-train. If the Bank runs
out of money in a Stock Round, complete the Stock
Round and one Operating Round. If the Bank runs out of
money in an Operating Round, complete that Operating
Round. __In either case, if the 8-train is purchased before
the end of the Operating Round, continue with the extra
Rounds as described above.__"
(emphasis mine)

**Comment by ianwilson156** [comment]
Actually, the GRR bought the first 8T in the same round (OR7.2).
There was a correct message about the game ending after OR8.3, but it ended immediately instead.

This is a repeat of issue #8541

**Comment by ollybh** [comment]
This is slightly different from #8541, that was the bank breaking after the first 8T has been bought, this is the 8T being bought after the bank has broken.

@ianwilson156 From my reading of the AAG rules, the same behaviour should apply to 1867 as well as 1861, with the purchase of the 8T overriding the bank breaking. Right?

**Comment by ianwilson156** [comment]
Yes, 1867 should be the same.

**Comment by ollybh** [comment]
I've got a fix for this (ollybh/18xx@5705f27), but I need to test it more before I push this upstream, to make sure I'm not breaking any other game end conditions. I'll try and get this done in the next couple of days.
