### ISSUE TITLE
1856

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#8864]
1856:  buying GT share...#1 REDUCED my value 20 instead of raising it 20 when IPO 80 and market 100.
ALSO, the $80 didn't go into the company's treasury.

(https://18xx.games/game/112823)

The game is stopped just after this action currently

**Comment by michaeljb** [comment]
Loans held by companies reduce their value in endgame scoring, which is reflected before the end of the game in the value calculation:

https://github.com/tobymao/18xx/blob/2bcc7a7fec38eeafe1e607662ec5c8cefeaff717/lib/engine/game/g_1856/game.rb#L1390-L1394

So, there is no bug, you can continue your game.
