### ISSUE TITLE
Collapse the JSON representation for the game data in Tools tab

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#888]
When a user goes to the Tools tab, the game data is display in JSON form. For a new game, this is a fairly short list, but later in the game, the rendered JSON can be quite long. Also, with some games, some of the game data should be private information, at least initially (yes, I'm thinking of the 1846 private draft).

I think it would be better when a user goes to the Tools tab, the JSON game data is not displayed until the user clicks a button. This would speed up page rendering and avoid inadvertently revealing private game information.

**Comment by ChrisTheCat** [comment]
I support this enhancement suggestion. However, it shouldn't be used to "hide" secret information if users can simply click the button and see the JSON with that secret information in it. The secret information should stay secret until the draft is complete.

**Comment by jenf** [comment]
While we could hide them in the UI in the draft phase, an unscrupulous user could just look at the json coming from the server anyway.

**Comment by tobymao** [comment]
my philosophy is to make it so that if you want to play honestly you can, rather than trying to stop cheaters.

**Comment by ChrisTheCat** [comment]
If the system allows cheating, I would either not use it or only play games
with people I already know and trust. I have way too much cynicism about
how game players will behave to operate on trust with unknown opponents.

**Comment by ChrisTheCat** [comment]
If you don't want to prevent cheating in the 1846 draft, may I offer an
alternate suggestion?

Allow players to use an external tool to run the draft, and then start a
game on 18xx.games and distribute the private companies manually.

**Comment by wcraigtrader** [comment]
As a game player, I would prefer that all of the aspects of game play be handled through a single site / application. In particular, the various drafting applications for 1846 have been awkward to use, and prone to failing due to lack of maintenance/interest on the part of their author(s).

As for security, any system can be beaten if someone has enough incentive and time. Locks exist to keep honest people honest, and to encourage the dishonest to pick an easier target, elsewhere. We use HTTPS for communication to protect from third-party snooping, even though packet sniffers exist. We use code obfuscation even through code can be deobfuscated. By doing these things, we increase the amount of work necessary to crack the system beyond the point where its worth cracking it -- the payoff is too low for the work involved.

For more 18XX games, there is no hidden information within the game itself, and so having the entire game state recorded in a single portable data structure makes sense. The 1846 private draft is different, in that there may be a modicum of advantage to be gained by knowing which privates other players have drafted when making your selection. 

It would seem to me that the correct trade-off would be to continue to store the private draft status in the game data structure, but to obscure the intermediate state of the private draft during the draft itself. Once the draft is complete, then the data could revealed for the sake of debugging. I don't think its necessary to use a truly secure encryption mechanism, just enough to make breaking it too much effort for 99% of players.
