### ISSUE TITLE
South Iyo (private F) not supposed to be used in 3p game?

### ISSUE THREAD

**Issue by jchipr** [tobymao/18xx#89]
The Uno-Takamatsu Ferry (private G) does not appear in a three player game, as it should not, but the South Iyo RR (private F) DOES appear in a three player game, which it should not.

**Comment by hcarver** [comment]
I believe that's incorrect.

![Screen Shot 2020-04-18 at 19 52 13](https://user-images.githubusercontent.com/1674771/79668236-24ce1680-81ae-11ea-8b99-3bc539277da1.png)

**Comment by tobymao** [comment]
thanks for checking @hcarver

**Comment by jchipr** [comment]
thanks. I was looking at a poor player aid, not the actual rules...
