### ISSUE TITLE
1846 error message running trains 

### ISSUE THREAD

**Issue by MoshiMaro** [tobymao/18xx#890]
I receive an error message when running trains with my corporation.

At the same time I think the w-w connection bonus is also not counted correctly 

Game id 2441
Version id 8a10c3d

![11F34AA0-3F8D-4471-8CD6-278127411AC4](https://user-images.githubusercontent.com/63635335/85884936-bf1c8d00-b7e3-11ea-8a50-c130cbb25d6a.png)
![EDBC6491-41AF-47F5-8AC9-F9BD9F45CC65](https://user-images.githubusercontent.com/63635335/85884941-c2177d80-b7e3-11ea-9d3b-2fc868016b32.png)

**Comment by tobymao** [comment]
no point in posting bugs for a pinned game
