### ISSUE TITLE
1862 President sale of share

### ISSUE THREAD

**Issue by HogueEric** [tobymao/18xx#8901]
In [game 113371](https://18xx.games/game/113371?action=435), I was President of the L&H in SR4.  It was valued at 220.  I sold a share, and the value did not drop.  My understanding is that when the President sells shares, the price drops regardless of the zone.

https://gist.github.com/benjaminxscott/341a7dac1792d3abab743a5677964399

**Comment by roseundy** [comment]
The fix from @benjaminxscott was incorrect. I'm submitting the correct fix now.
