### ISSUE TITLE
[1822PNW] Error during minor conversion in SR

### ISSUE THREAD

**Issue by DanATXX** [tobymao/18xx#8908]
GameError: Blocking step Bid, convert concession or buy/sell shares cannot process action 1065
Broken action: { "type": "pass", "entity": 9793, "entity_type": "player", "id": 1065, "created_at": 1677287219 }

https://18xx.games/game/112365?action=1064

What steps cause the unexpected behavior?

During SR8 Kronger converted the 20 to the NP. This seemed to be fine because other players took actions to buy stocks. Then ~3 hours later the page updated to this game error.

**Comment by tobymao** [comment]
archived
