### ISSUE TITLE
[18CO] - Game is reporting liquidity incorrectly

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#8914]
https://18xx.games/game/112858?action=741

In this 18CO game, a player is reported as having $1203 in liquidity, but the game is forcing him to go bankrupt saying that he has $0 in sellable shares.  One of those must be wrong.  Not sure which one.

**Comment by benjaminxscott** [comment]
This seems to be functioning as expected, the C&S must emergency-issue before the player can assist in e-buying (incl player selling shares)

```

5.10.6.1. If a Corporation cannot afford a train to satisfy a mandatory purchase, it must buy the cheapest available train in
the Bank or Market, raising only as much money as necessary through the following means, in order:

5.10.6.1.1. Sell (issue) the Corporation’s own certificates one at a time, moving the stock down for each share sold. Corporate Certificates cannot be sold.

5.10.6.1.2. If the Corporation still cannot afford a train, the President contributes enough of their personal cash to purchase the train.

5.10.6.1.3. If the Corporation still cannot afford a train, the President must sell their own certificates

...
```

https://drive.google.com/file/d/16W5v3w__GW4CzXQ9QeQERYVnbkdRDqg1/view
