### ISSUE TITLE
1850 game 114218

### ISSUE THREAD

**Issue by HelenCheale** [tobymao/18xx#8915]
Game will not load

**Comment by philcampeau** [comment]
looks like the game is pinned. It will likely not be salvageable.

**Comment by BellmakerSA** [comment]
If they are unsalvageable I would appreciate it if 114127 and 114167 could be closed/ended in some way as they cannot be loaded

**Comment by HelenCheale** [comment]
Hi is there any way to end this game if it is not salvageable?

**Comment by HelenCheale** [comment]
Hi is there any way this game can be ended?
