### ISSUE TITLE
share bundle re-cast from ShareBundle to SharePool after SharePool.sell_shares()

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#8916]
Not sure why this occurs, but when a ShareBundle `bundle` is passed to `SharePool.sell_shares()` - 
(edit: `bundle.owner`) is re-cast as a SharePool after the function returns

https://github.com/benjaminxscott/18xx/blob/master/lib/engine/game/g_1862/game.rb#L1198

Doesn't seem to be breaking anything, but seems like unintended behavior of that function

**Comment by roseundy** [comment]
That's odd. I would have expected SharePool to be the bundle.owner after sell_shares()

**Comment by benjaminxscott** [comment]
Gotcha I mis-understood, this does seem like expected behavior
