### ISSUE TITLE
18CO rules require permission

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#8918]
Rules for 18CO are currently inaccessible without additional permissions:

![image](https://user-images.githubusercontent.com/26125362/221388198-f58cec26-920a-4823-bc2c-83ca39507def.png)

**Comment by benjaminxscott** [comment]
Looks like the current link is to a gdrive folder with a bunch of pdfs in it

The specific rules pdf seems to be accessible anonymously at:

https://drive.google.com/file/d/16W5v3w__GW4CzXQ9QeQERYVnbkdRDqg1/view

There's also a player aid that may be helpful to link in the meta as well
https://drive.google.com/file/d/1A6l6BgMb7ENu9_TSXskKmPsYfBuzbrU3/view?usp=drive_open
