### ISSUE TITLE
[1846] LSL allows invalid upgrade tiles for Cleveland

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#892]
Cleveland is a Z-city, so upgrading from yellow to green only allows upgrading to a green Z-city (294, 295, 296), but when I bought in the LSL and chose to upgrade Cleveland, I was given the option to select from 6 city tiles: 14, 15, 619, 294, 295, 296. Actually selecting one of the illegal tiles results in an error bar message (291 is not upgradeable to 14).

![1846-LSL-allows-invalid-upgrades](https://user-images.githubusercontent.com/972263/85892234-8cac6900-b7be-11ea-8604-577db51b93b5.png)

Game data:
[1846-LSL-allows-invalid-upgrades.txt](https://github.com/tobymao/18xx/files/4838812/1846-LSL-allows-invalid-upgrades.txt)

**Comment by tobymao** [comment]
yep, a limitation of the current configuration, low priority though since it doesn't actually let you lay it
