### ISSUE TITLE
[1846] Tunnel Blasting Company discount not applied to track lays/upgrades

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#894]
The B&O bought in the TBC at the end of OR1.1. In OR1.2, it upgrades Wheeling with #14, but is charged the normal rate of $40 ($20 + $20 for the tunnel to Pittsburgh) instead of just $20 (discounted for owning the TBC). Likewise, laying #9 on G17 should cost $40, not $60.

> B&O spends $40 and lays tile #14 with rotation 1 on G19
> B&O spends $60 and lays tile #9 with rotation 1 on G17

[1846-TBC-discount-not-applied.txt](https://github.com/tobymao/18xx/files/4838904/1846-TBC-discount-not-applied.txt)

**Comment by pence** [comment]
We just encountered this in game 2924 - B&O with Tunnel Blasting getting charged $40 for upgrading wheeling.

**Comment by benjaminxscott** [comment]
I can slap together an implementation for this, now that my ruby env is up
