### ISSUE TITLE
[18USA] Building and undoing cause error messages and are not accepted by server

### ISSUE THREAD

**Issue by Akuusi** [tobymao/18xx#8948]
In game 114122 (https://18xx.games/game/114122) any builds by MP on C7 (all legal) caused error message "Illegal action: Blocking". Trying to undo or restart the company turn results in different error messages and is never accepted.

**Comment by Akuusi** [comment]
Seemed to clear (at least for now) after half an hour or so.

**Comment by benjaminxscott** [comment]
Sounds like the issue was fixed by a recent commit
