### ISSUE TITLE
[1846] bug - able to token any slot in CHI using C&WI private 

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#895]
[repro, B&O owns CWI and is about to teleport to CHI](https://github.com/tobymao/18xx/files/4839804/cwi_bo.json.txt)

B&O is able to token any open slot in CHI, rather than being limited to the southeast slot

Related: I wasn't able to reproduce #891 , since I was able to teleport to CHI by clicking the city slot

**Comment by michaeljb** [comment]
This fix will probably require changing some tile definitions.

These are the current definitions:

edge => city

yellow
0 => 0 
3 => 1
4 => 2
5 => 3

the others:
0 => 3
3 => 0
4 => 1
5 => 2

A `city` option will likely need to be added to the token schema, and it will need to know which city the token can go in whether it's the yellow or green tile.

**Comment by benjaminxscott** [comment]
It looks like the [private ability data structure](https://github.com/tobymao/18xx/blob/master/lib/engine/config/game/g_1846.rb#L188) knows which city it belongs in 

perhaps an optional data member in [the token ability](https://github.com/tobymao/18xx/blob/master/lib/engine/ability/token.rb#L10) that includes the city it's limited to?

**Comment by michaeljb** [comment]
Yep, that's what I meant by adding a city option to the token schema.

The main complication is that in yellow, the C&WI's city is 3, while in green the C&WI's city is 0. The tile definitions need to be made consistent so that both are city 3.
