### ISSUE TITLE
Request to delete game 110697

### ISSUE THREAD

**Issue by shamblen** [tobymao/18xx#8953]
Posted the below in an earlier issue, and the game was abandoned as broken.  But we cannot delete the game, and I really would like to remove the game from my active games.
-Spencer

%%%%%%%%%%%%%%%%%%%

https://18xx.games/game/110697
Crashed, unrecoverable game. Not sure what triggered it... tokening Berlin? Laying track in Brussels?

https://18xx.games/game/110697?action=1112

Error message:
We're sorry this game cannot be continued due to GameError: Blocking step Lay Track cannot process action 1113
Broken action: { "type": "place_token", "entity": "NRS", "entity_type": "corporation", "id": 1113, "created_at": 1675628475, "city": "207-2-0", "slot": 0, "tokener": "NRS" }

**Comment by benjaminxscott** [comment]
@tobymao
