### ISSUE TITLE
[21Moon] Bankruptcy, corp in Receivership, game stuck, can't progress

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#8956]
https://18xx.games/game/112225?action=452
The above link takes you to the penutimate stuck step. From there, press "Declare Bankruptcy" for MA president to see the stuck state.

What steps cause the unexpected behavior?

- A player with 2 corps (MA and ME) and one perm train, chooses to declare bankruptcy in MA
- The 2nd corp (ME) goes into Receivership 
- Other Players are given control of the game to pick route for ME's perm train, a 10T 
- Game doesn't accept any moves. AFter picking a route and pressing "Submit" on the button that displays the route revenue, it doesn't accept the action. Instead there's a red banner error that says:
`undefined method 'to_bundle' for nil` 

Other notes:
- Enabling master mode doesn't make any difference
- "End Game" button still works
- This gist has a hotseat taking you to the same action above (452)  https://gist.github.com/yoyoson/5ff5abefb5fceedb6d378a161aef34c4

**Comment by roseundy** [comment]
Bug with disposing of shares owned by a closing corporation.
