### ISSUE TITLE
1822MX company with special train prohibited from acquiring another special train

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8964]
The rules make it clear that a company with a special train may acquire another and must then discard one. I was prevented from doing so in https://18xx.games/game/112299?action=1014

**1822MX rules** _6.5.15 There are three special trains that are bought as private companies (in addition to the private company P1 5-train, which is a normal 5-train). A company may only own one of these special trains at a time. If a company has one of them and acquires another, it must select one to discard from the game._

<img width="814" alt="Untitled" src="https://user-images.githubusercontent.com/8732435/222864520-0aa44f53-16b8-49d0-a4c1-26e4efaaede1.png">

**Comment by ChrisTheCat** [comment]
This might apply to all games in the 1822 family, I haven't checked all the other rule books.

**Comment by michaeljb** [comment]
Possibly related #8558

**Comment by michaeljb** [comment]
This does apply to all 1822 games (so far). References for other titles, matching 1822MX's 6.5.15:

* 1822 - 5.10.3
* 1822CA - 5.10.4
* 1822PNW (Draft 2023-02-22) - 5.11.4
