### ISSUE TITLE
[1846] C&WI private should provide an additional token action

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#897]
[repro, B&O owns CWI and is about to teleport to CHI](https://github.com/tobymao/18xx/files/4839804/cwi_bo.json.txt)

Since CW&I provides an additional token + token laying action, B&O should be able to lay a token in Detroit as well

Technically the token is laid when the private is bought in, so a strict rules interpretation would only allow a token to be laid at purchase-time, which would obliviate the need to create an edge case in the existing "token laying step" logic

```
Rules: Upon being purchased, place an additional token of its purchasing corporation at no cost
```

**Comment by michaeljb** [comment]
I updated the title to clarify the token lay is in addition to the corporation's normally allowed tile lay; the ability does already have an `extra` property, but that's in reference to how the token doesn't come from the corporation's supply of tokens.
