### ISSUE TITLE
[1862] Game that was previously working is now failing to parse previous actions.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#8972]
We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action
Broken action: { "type": "pass", "entity": "I&B", "entity_type": "corporation", "created_at": [1674441517](tel:1674441517) }
Please [raise a bug report] and include this link (https://18xx.games/game/109255?action=204)

**Comment by michaeljb** [comment]
@crericha I bisected and looks like https://github.com/tobymao/18xx/pull/8959 caused this

**Comment by crericha** [comment]
Okay, I'll take a look.

**Comment by physic** [comment]
This game is still broken, with the same error.
