### ISSUE TITLE
[1848] Game cannot continue due to broken step

### ISSUE THREAD

**Issue by klfduncan** [tobymao/18xx#8973]
Here is the text:

We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 673
Broken action: { "type": "pass", "entity": "FT", "entity_type": "corporation", "id": 673, "created_at": [1677584384](tel:1677584384) }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1848,%22needs%20triage%22) and include this link (https://18xx.games/game/111903?action=672)

**Comment by michaeljb** [comment]
@crericha I bisected and looks like https://github.com/tobymao/18xx/pull/8959 caused this
