### ISSUE TITLE
[1862] Error occurred in Merge.

### ISSUE THREAD

**Issue by motoi-sano** [tobymao/18xx#8974]
https://18xx.games/game/113619

We're sorry this game cannot be continued due to GameError: Blocking step Merge cannot process action 594
Broken action: { "type": "pass", "entity": "L&H", "entity_type": "corporation", "id": 594, "created_at": 1678040668 }
Please raise a bug report and include this link ([https://18xx.games/game/113619?action=593](https://18xx.games/game/113619?action=593))

**Comment by roseundy** [comment]
Dup of #8972 ?
@crericha

**Comment by crericha** [comment]
Yes. Same issue as #8972. Fix in flight.
