### ISSUE TITLE
[1862] GameError: Blocking step Acquire cannot process action

### ISSUE THREAD

**Issue by f-prettyland** [tobymao/18xx#8978]
Hi, I'm encountering the following message: 
```
GameError: Blocking step Acquire cannot process action 245
Broken action: { "type": "pass", "entity": "I&B", "entity_type": "corporation", "id": 245, "created_at": 1677765359 }
```

**What's your Game ID?**
https://18xx.games/game/114714
Bug: `https://18xx.games/game/114714?action=245`

**How to Reproduce the Bug?**
Uncertain, have not reproduced. Broken game state makes it difficult to navigate or attempt other actions.

**Which Browser / Platform?**
Server side break. Across all players platforms.
I am on Firefox 110.0.1

**Comment by roseundy** [comment]
Likely dup of #8972
