### ISSUE TITLE
this game cannot be continued due to GameError: Cannot buy a share of B&O (hs_lsaqoqhe_1593251191

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#898]
We were in the OR, and I think I was trying to buy a private

{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 1,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 3,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 4,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Pass (2)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 6,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 7,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 10,
      "company": "MC",
      "price": 40
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 11,
      "corporation": "IC",
      "share_price": "112,0,11"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 12,
      "corporation": "NYC",
      "share_price": "70,0,7"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 13,
      "corporation": "GT",
      "share_price": "40,0,4"
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "IC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "NYC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 17
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "GT_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 23,
      "hex": "C13",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 24,
      "hex": "D12",
      "tile": "8-1",
      "rotation": 1
    },
    {
      "type": "undo",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 25
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 26,
      "hex": "B16",
      "tile": "6-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 27,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 28,
      "hex": "G9",
      "tile": "6-1",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 29,
      "hex": "G7",
      "tile": "6-2",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 30,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 31
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 32,
      "hex": "D12",
      "tile": "8-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 33
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 35
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 37
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 38
    },
    {
      "type": "sell_shares",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 39,
      "shares": [
        "GT_3",
        "GT_4"
      ],
      "percent": 20,
      "share_price": 30
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 40,
      "hex": "D12",
      "tile": "8-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 41
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 42,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 43,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 44
    },
    {
      "type": "sell_shares",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 45,
      "shares": [
        "NYC_2",
        "NYC_3",
        "NYC_4"
      ],
      "percent": 30,
      "share_price": 60
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 46,
      "hex": "D18",
      "tile": "8-2",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 47,
      "hex": "E17",
      "tile": "291-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 48
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 49,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 50,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 51,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 52
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 55,
      "hex": "J4",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 56,
      "hex": "H6",
      "tile": "9-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 57
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 58,
      "train": "4-0",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 59,
      "train": "4-1",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 60
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 62,
      "hex": "D10",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 63,
      "hex": "D8",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 64,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 65,
      "hex": "I3",
      "tile": "9-4",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 66,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 67
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 68
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 69
    },
    {
      "type": "redo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 70
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 71,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "I5",
              "I3",
              "I1"
            ],
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 72,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 73
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 74,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 75,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 76
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 77
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 78,
      "hex": "E19",
      "tile": "8-3",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 79,
      "hex": "D20",
      "tile": "14-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 80,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "E17",
              "D18",
              "D20"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "E17",
              "E19",
              "D20"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "C21",
              "D20"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 81,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 82
    },
    {
      "type": "buy_company",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 83,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 85
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 86
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 88
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 89
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 90
    },
    {
      "type": "sell_shares",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 91,
      "shares": [
        "GT_5",
        "GT_6"
      ],
      "percent": 20,
      "share_price": 20
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 92,
      "city": "D6-0-2",
      "slot": 0
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 93
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 94,
      "city": "D6-0-2",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 95,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "C15",
              "C13",
              "D12",
              "D10",
              "D8",
              "D6"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 96,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 97
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 98,
      "company": "MS",
      "price": 22
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 100,
      "shares": [
        "NYC_5"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 101,
      "shares": [
        "IC_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 102,
      "shares": [
        "NYC_6"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 103
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 104,
      "shares": [
        "NYC_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 105,
      "shares": [
        "IC_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 106
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 107
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 108
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 109
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 110,
      "hex": "H10",
      "tile": "8-4",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 111,
      "hex": "I9",
      "tile": "8-5",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 112
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 113,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "I5",
              "I3",
              "I1"
            ],
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "4-1",
          "connections": [
            [
              "G7",
              "H6",
              "I5"
            ],
            [
              "G9",
              "G7"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "J10",
              "I9",
              "H10",
              "G9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 114,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 115
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 118,
      "hex": "E17",
      "tile": "294-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 119
    },
    {
      "type": "run_routes",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 120,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "D20",
              "D18",
              "E17"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "D20",
              "E19",
              "E17"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "C21",
              "D20"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 121,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 122,
      "train": "4-2",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 123
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 124
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 125
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 126,
      "hex": "D6",
      "tile": "298-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 127
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 128,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "C15",
              "C13",
              "D12",
              "D10",
              "D8",
              "D6"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        },
        {
          "train": "2-0",
          "connections": [
            [
              "C5",
              "D6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 129,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 130
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 132
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 133
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 134
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 135,
      "hex": "G7",
      "tile": "619-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 136,
      "hex": "F6",
      "tile": "9-5",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 137
    },
    {
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 138
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 139
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 140,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "I5",
              "I3",
              "I1"
            ],
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "4-1",
          "connections": [
            [
              "I5",
              "H6",
              "G7"
            ],
            [
              "G9",
              "G7"
            ]
          ]
        },
        {
          "train": "2-1",
          "connections": [
            [
              "J10",
              "I9",
              "H10",
              "G9"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 141,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 142
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 143
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 144
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 145,
      "hex": "E15",
      "tile": "8-6",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 146,
      "hex": "D14",
      "tile": "6-3",
      "rotation": 3
    },
    {
      "type": "run_routes",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 147,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "C21",
              "D20"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "D22",
              "D20"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "D20",
              "D18",
              "E17"
            ]
          ]
        },
        {
          "train": "4-2",
          "connections": [
            [
              "E17",
              "E15",
              "D14"
            ],
            [
              "D20",
              "E19",
              "E17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 148,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 149
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 150
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 151
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 152,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "C15",
              "C13",
              "D12",
              "D10",
              "D8",
              "D6"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        },
        {
          "train": "2-0",
          "connections": [
            [
              "C5",
              "D6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 153,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 154
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 155
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 156
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 157,
      "corporation": "B&O",
      "share_price": "150,0,14"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 158
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 159
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 160
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 161
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 162
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 163,
      "train": "4-3",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 164,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 165
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 166
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 167
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 168
    }
  ],
  "id": "hs_lsaqoqhe_1593251191",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1846",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-27",
  "loaded": true,
  "result": {}
}

**Comment by michaeljb** [comment]
I wound back to just before the B&O was parred at $150, and the would-be president only had $288, not the needed $300. This means that after you had got that far in your game, some rules/config change was pushed that changed earnings in some way. IIRC Chicago Connections had an extra port tile that got removed, that may account for it.

Here's your game file, wound back to just before the B&O was started - [898.json.txt](https://github.com/tobymao/18xx/files/4841281/898.json.txt)

Just for fun, I tried parring the B&O at $137, and it seems the rest of the actions so far were valid with that, so you wouldn't have to replay everything - [898_137.json.txt](https://github.com/tobymao/18xx/files/4841285/898_137.json.txt)

If the game just needs to be pinned, I think it can be pinned at 73728b54
