### ISSUE TITLE
1867: Nowhere to place home station for new company

### ISSUE THREAD

**Issue by Dave4B** [tobymao/18xx#8980]
Started a new major company when all available slots already had a company in them.
The program should not allow the company to be started if there is nowhere for its home station.
[hs_vqjfhprb_1678131451.json.txt](https://github.com/tobymao/18xx/files/10902756/hs_vqjfhprb_1678131451.json.txt)

**Comment by Dave4B** [comment]
Tested this in 1861 and it refused to allow a new company to be started when no home locations were available.

**Comment by benjaminxscott** [comment]
Was there a live game associated with this? Makes it a lot easier to debug

**Comment by Dave4B** [comment]
Sorry no, I was testing extreme cases in hotseat mode.

**Comment by Dave4B** [comment]
recreated the problem in live game!
[115992.json.TXT](https://github.com/tobymao/18xx/files/10913815/115992.json.TXT)

**Comment by Dave4B** [comment]
@benjaminxscott I spoke to Ian D Wilson this weekend.
He confirmed that in 1867 (but not 1861), you should be able start a company in a city with a token in it if there are no empty cities left.

**Comment by ollybh** [comment]
@Dave4B Did @ianwilson156 check the rulebooks when he said this? I can't find this in either the AAG 1867 expansion rules or the GTG rules.

**Comment by ianwilson156** [comment]
I'm pretty sure I've been misquoted! I think I said: in 1867 (but not 1861) you can start in a connected city if no unconnected cities are available, as long as you start in an empty city. I believe that's what it says (effectively) in the rulebook.

So Dave is right - if all cities have a token in them, you cannot start a new major company. (That includes CN tokens, btw.) I've never seen it happen in a real game, but there are only 15 cities, so a mere 5 companies could arrange to have one token in every one.

**Comment by Dave4B** [comment]
@ollybh I have tested this with a game in which there are connected but unoccupied sites and was allowed to place the home token.  So the "feature" appears to be only when there are city spots but none are legal.
[116910.json.txt](https://github.com/tobymao/18xx/files/10995347/116910.json.txt)

**Comment by ianwilson156** [comment]
In #116910, the C&O illegally places its home token in Toronto. There are several legal sites available e.g. Quebec.
Could the special rule for placing minor companies in Toronto & Montreal being applied to majors too?

**Comment by ianwilson156** [comment]
OTOH, #115992 has no legal places to start a major, and illustrates the issue in hand.

**Comment by ollybh** [comment]
> In #116910, the C&O illegally places its home token in Toronto. There are several legal sites available e.g. Quebec. Could the special rule for placing minor companies in Toronto & Montreal being applied to majors too?

Which special rule for minors? The wording for starting minor companies (in the AAG rules) says "… place its token on an empty city circle on the map. This must be in Toronto, Montreal, or a city which does not already have a token in it". There are no unconnected cities for C&O to start in, so can't it start in Toronto or Montreal?

**Comment by ianwilson156** [comment]
The special rule for minors is that they can start in Toronto & Montreal, even if there are tokens already in those cities (Toronto starts with the CN).

The GTG rules say "If no unconnected cities exist: ... the major may then place the station token in a connected city that is unoccupied. If no cities meet these criteria, a major may not be started in this way."
(The AAG rules don't say about it needing to be unoccupied, this was a later clarification.)

**Comment by michaeljb** [comment]
> In #116910, the C&O illegally places its home token in Toronto. There are several legal sites available e.g. Quebec. Could the special rule for placing minor companies in Toronto & Montreal being applied to majors too?

Hi @ianwilson156,

To clarify something here, C&O may not start in Toronto because the National already has a token in Toronto, even though the stations are not connected? From the GTG rules on page 17:

> Some hexes like Moscow or Toronto have multiple, unconnected cities.

Should the unconnected revenue centers be considered the same city for purposes of starting a major in Toronto and Montreal?

**Comment by ianwilson156** [comment]
Hi @michaeljb In all cases, unconnected revenue centres in the same hex are considered the same city.

In 1867, minors may start in unconnected revenue centres in the same hex, but majors may not (if one such centre is occupied). Therefore, it should be impossible to start a major in Toronto since there is always a CN token in it. In principle, a major could start in Montreal (but that would be a bizarre situation).
