### ISSUE TITLE
[1862] GameError: Blocking step Run Routes cannot process action

### ISSUE THREAD

**Issue by nightflyerkilo** [tobymao/18xx#8986]
**What's your Game ID?**

https://18xx.games/game/106820?action=938

**How to Reproduce the Bug?**

Unknown, game just broke in phase H. Stepping back the game log and undoing are also not working.

There's a second, minor issue in this game that *could* be related, but might not be. A couple turns prior to the game breaking, when WStI ran, its share price moved from 375 to 570 which was reported in the transcript as "1.5 steps" though it is actually 3 steps.

**Which Browser / Platform?**

Chrome 110.0.5481.177
Desktop

**Comment by nightflyerkilo** [comment]
Looking at the game log, it seems like L&E skipped ahead of EUR in operating order for some reason although EUR was higher priced at the beginning of the round.

**Comment by nightflyerkilo** [comment]
I think maybe https://github.com/tobymao/18xx/commit/00733f8338beb27a94bf64cf72c022fd68eb9506 changed the relative ordering of L&E and EUR and caused the breakage.

**Comment by benjaminxscott** [comment]
seems fixed by https://github.com/tobymao/18xx/pull/8971

**Comment by crericha** [comment]
Fixed
