### ISSUE TITLE
[1817] Volatility-variant private "Inventor" pays too much on 6 train purchase

### ISSUE THREAD

**Issue by 18xxgit** [tobymao/18xx#8988]
**What's your Game ID?**
https://18xx.games/game/106175
https://18xx.games/game/99154

https://18xx.games/game/106175?action=1524
https://18xx.games/game/99154?action=1119

https://gist.github.com/benjaminxscott/d313d464aa2505f14915e475ffc20876

The inventor company should only pay out $60 for the first 6 train purchase/export. Instead it pays $60 and then makes another payment of $30.

**Comment by benjaminxscott** [comment]
I believe this is happening b/c the train limit changes from 3 to 2, so the companies that are train-tight end up discarding their 3's to the pool (depot) which then are "removed"

The 'bonus' gets paid out on `remove_train`, so I think it's getting called twice, once for the 6 getting exported and once for the "3 in the pool" getting removed from the game

https://github.com/tobymao/18xx/blob/ed5a558bc99d2b6567f3e9be93fb1be38c8b017f/lib/engine/game/g_1817/game.rb#L880
