### ISSUE TITLE
1889 - Exchange Dougo for IR share - initial stock round

### ISSUE THREAD

**Issue by OrcaWilly** [tobymao/18xx#8989]
Player has enough cash to buy 4 shares at 75 and also owns Dougo Private.

Initial Stock Round - Player buys 4 shares of IR.  When it gets to the 5th turn it automatically passes the player because player has no valid actions and passes.

But player CAN convert Dougo Private to float IR.

Nothing in the rulebook says you are forced to autopass if you still can convert a share.

**Comment by tobymao** [comment]
won't fix
