### ISSUE TITLE
Auto Route clearing first, then rerouting 

### ISSUE THREAD

**Issue by briguy54** [tobymao/18xx#8994]
**What's your idea?**

Not sure if it is a bug or not, but Auto doesn't set the best routes because it won't replace lower earning routes with better routes. We had to always click Clear All first, then Auto. I'd think Auto should be able to clear, then reroute the best earning routes to always give you the highest income. We went a few rounds without realizing this as pressing Auto doesn't update the Last Run income, even when better income became available.

**Are there related ideas?**

I searched and could not find this as feedback or a bug.

**Did you join the Slack?**

I did not, this was my first play through and an observation we had.

**Comment by tobymao** [comment]
by design. this is do autoroute safes time

**Comment by crericha** [comment]
It's a feature, not a bug. This allows you to puck routes you want to keep
and routes you want auto routed.

**Comment by briguy54** [comment]
Understood, thanks for the quick response! However, I'm not sure the scenario where you wouldn't always want the highest income routes. Any way to include a clear/auto combo button? We're constantly clicking clear before auto, and would love to save the click (and time) by having to constantly click both buttons. It doesn't feel intuitive.
