### ISSUE TITLE
[1862] Incorrect distance calculation for freights to offboard hexes

### ISSUE THREAD

**Issue by nightflyerkilo** [tobymao/18xx#8995]
**What's your Game ID?**

https://18xx.games/game/106820?action=954

**How to Reproduce the Bug?**

Run one of the 9F trains from the Harwich Port to the northenmost hex of the West. Revenue is 400 (correct).
Run the same train from the Harwich Port to the southernmost hex of Midlands (note: same hex as before, different entrance and off-board value). The calculated revenue is 450, but to my eye it should be 420, since the difference between the Midlands and West value is 20. 140 (Midlands) + 130 (Port) + 5 intervening hexes * 30 = 420

![Screenshot from 2023-03-09 11-52-15](https://user-images.githubusercontent.com/1767452/224126215-3515e9f0-3114-4ddd-90f7-7ddd91c29dc1.png)

![Screenshot from 2023-03-09 11-52-45](https://user-images.githubusercontent.com/1767452/224126234-ea673157-49c0-4cc0-b265-c61d8f3523be.png)

**Which Browser / Platform?**
Chrome 110.0.5481.177
Desktop

**Comment by outsidePasser** [comment]
Because you are exiting to the Midlands from hex B7, you have to count the distance including B7.  The game is implemented correctly.

**Comment by nightflyerkilo** [comment]
I don't see that interpretation supported by the rules. The distance is counted as the crow flies, not following the route of the train. For the London example in the rules, my understanding is that it makes a difference because there the train is ending in a different hex, not just at a different entrance.

Also I don't think the barrier between West and Midlands should have any impact because:

> When tracking the direct route for this, barriers such as those around Harwich are ignored.

**Comment by nightflyerkilo** [comment]
Okay, based on [this thread](https://boardgamegeek.com/thread/966793/article/12090736#12090736) it appears you are correct.

**Comment by roseundy** [comment]
There was a **lot** of discussion about this when I first implemented 1862. Unfortunately, Mike Hutton's rules can leave some room for interpretation.
