### ISSUE TITLE
[1849] Breaking error in game

### ISSUE THREAD

**Issue by m4th13u79** [tobymao/18xx#8997]
https://18xx.games/game/114870

message : "undefined method `name' for nil"

from https://18xx.games/assets/deps.js:1:14686:in `re.p'
  from https://18xx.games/assets/g_1849.js:7:1182:in `re.l'
  from https://18xx.games/assets/main.js:2:517740:in `g'
  from https://18xx.games/assets/deps.js:1:16401:in `m.yield1'
  from https://18xx.games/assets/deps.js:15:71094:in `Array.O'
  from https://18xx.games/assets/deps.js:1:18715:in `m.send2'
  from https://18xx.games/assets/deps.js:1:18534:in `m.send'
  from https://18xx.games/assets/main.js:2:517596:in `re.<anonymous>'

**Comment by crericha** [comment]
What game title?

**Comment by m4th13u79** [comment]
1849
