### ISSUE TITLE
Floating company after last 2+2 bought

### ISSUE THREAD

**Issue by tommccorry** [tobymao/18xx#9003]
Game reference: 11407

A new company is started in the SR after the last 2+2 was exported. We are not yet in Phase 3 since a three train has not been purchased however the company is not floating with only two shares bought which it should per the rule book.

**Comment by roseundy** [comment]
What game? What title? 11407 is not a valid game.

**Comment by philcampeau** [comment]
Presumably he meant this game https://18xx.games/game/114074

But from what I can see at the described moment in the game, JHU was listed as Ready To Float with 20% sold, so it looks like everything is functioning properly: https://18xx.games/game/114074?action=297

In 1880 companies don't float unless the required amount of shares are still in players' hands at the end of the stock round, so a float doesn't happen until the stock round ends.

**Comment by tommccorry** [comment]
The “Ready to Float” was the confusing part given the context. I understand what was done now just didn’t register at the time.Maybe a “Float at end of SR” would be more descriptive.--------------------------------------------Tom McCorryOn Mar 13, 2023, at 16:24, philcampeau ***@***.***> wrote:﻿
Presumably he meant this game https://18xx.games/game/114074
But from what I can see at the described moment in the game, JHU was listed as Ready To Float with 20% sold, so it looks like everything is functioning properly: https://18xx.games/game/114074?action=297
In 1880 companies don't float unless the required amount of shares are still in players' hands at the end of the stock round, so a float doesn't happen until the stock round ends.
