### ISSUE TITLE
[1880] Size of president's share should be indicated on either player's card or company's card

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#9014]
Subject says it all.  You may say this is an enhancement and not a bug, as the size of the president's share can be deduced from the building permit.   I consider it a bug, because when I'm sitting at the table, this is available as primary information (the # of stripes on the certificate) and it's annoying to have to infer it.  Also, once a building permit expires, that info is no longer available.  

I would suggest it could be put in one of two places... on a player's card, or alternatively, on the company's card. I prefer the player's card, as that's where you would see at the table, even for multiple companies (see attached markup)

<img width="550" alt="1880-cert" src="https://user-images.githubusercontent.com/66023744/225139919-235569e8-c501-4501-9988-f2f5f99567d5.png">

**Comment by benjaminxscott** [comment]
We have a UI element with a `d` for 'double' shares that is used in '49 et. al, would that work?

With say a `t` for triple shares

![Screenshot 2023-03-14 8 59 23 PM](https://user-images.githubusercontent.com/1711810/225202868-6822c9b5-fc4a-41a1-ab9a-1469ba5142f6.png)

**Comment by crericha** [comment]
If @bentziaxl decides to implement, we already discussed that it would appear at the bottom for the corporation charter.

**Comment by bentziaxl** [comment]
Would this be ok? I'm replacing the par price info (redundant as it can be seen in the order view in market and game tabs)
![image](https://user-images.githubusercontent.com/108803147/225256657-ee0ad3f1-47cd-4d13-bdb1-10ec15950c11.png)

**Comment by BellmakerSA** [comment]
I would just say Presidency over Density but that's a minor quibble.
Having the Building Permits line change color or be highlighted when they can no longer lay track would also be helpful.

**Comment by waaayback** [comment]
Bentziaxl's approach seems OK.  I would agree with "Presidency" rather than "Density".
