### ISSUE TITLE
[1825] wrong train limit for phase 4/4a when using all units and expansions

### ISSUE THREAD

**Issue by JDavidson59** [tobymao/18xx#9019]
I recently played a five player game of 1825 (game number 110057) with the full set of units and expansions.  The train limit for Phases 4 and 4a is set at 99, which is clearly a mistake.  I think it should be 2.  Thanks so much for doing all thus stuff.  It's a great resource.  John Davidsontrain limit in Phase 4

https://18xx.games/game/110057

The train limit for Phases 4 and 4a is set at 99,  s.b. 2

**Comment by benjaminxscott** [comment]
The implementation seems correct as the train limit is infinite (99 for ease of coding) during phase 4 when using `kit 3 - phase 4`

https://boardgamegeek.com/image/754825/1825-extension-kit-k3-phase-four
