### ISSUE TITLE
[1849] Error after running routes

### ISSUE THREAD

**Issue by pampy74** [tobymao/18xx#9022]
Trying to enter game Id: 115564.  "Loading game ..." indefinitely.  I can enter my other game.  Desktop, Safari.

**Comment by benjaminxscott** [comment]
Last working action https://18xx.games/game/115564?action=460

**Comment by pampy74** [comment]
I can restart my turn, but can’t submit a route. I’ll keep trying. Sent from my iPhoneOn Mar 16, 2023, at 10:57 PM, Benjamin Scott ***@***.***> wrote:﻿
Last working action https://18xx.games/game/115564?action=460

**Comment by garretwehrman** [comment]
Getting the same error in https://18xx.games/game/116000

**Comment by pampy74** [comment]
I'm still unable to submit my route.
