### ISSUE TITLE
[1850] Mesabi token and Gant private

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#9024]
https://18xx.games/game/115354

Phase 5 just began, GN on its turn is unable to buy a Mesabi token, whether it connects to Mesabi on its turn or not, and is also unable to buy in the Gant private from its owner.

**Comment by bentziaxl** [comment]
Rules:
1- mesabi token can only be purchased if a corporation is connected to the mesabi range. Buying a token is a tile lay action so it can't be done in one turn (connect to the range + buy token). On the next OR, GN can buy a mesabi token
2- private companies are no longer buyable in phase 5:
rule 4.2.4: 
![image](https://user-images.githubusercontent.com/108803147/225550571-c3d2f370-ef64-46ea-94c5-14e70dee7d8b.png)
