### ISSUE TITLE
18Mag Minor 12 cannot run through or upgrade H25

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9026]
https://18xx.games/game/115149

**Comment by bentziaxl** [comment]
hmm,
https://18xx.games/game/115149?action=1766 
the tile lay on I6, also lays the tile on H25 and converts it into I6

**Comment by BellmakerSA** [comment]
![CCB69AD8-963A-46FC-8990-F6E1F1754EEC](https://user-images.githubusercontent.com/73144084/225675723-4a97bae2-f2df-489f-9c3d-2265a3c3c7fd.png)

**Comment by michaeljb** [comment]
I think this was caused by #8951 and  #8996, I'll take a look.

**Comment by michaeljb** [comment]
@BellmakerSA unfortunately I don't think I'll be able to fix your game, but #9029 adds the error check that should be able to prevent this from happening again.

**Comment by BellmakerSA** [comment]
> @BellmakerSA unfortunately I don't think I'll be able to fix your game, but #9029 adds the error check that should be able to prevent this from happening again.

All good thanks for the update
