### ISSUE TITLE
1846 incorrect revenue for 3/5 train route Detroit to Buffalo

### ISSUE THREAD

**Issue by Hepworthnot** [tobymao/18xx#9031]
**What's your Game ID?**
Id: 116881

https://18xx.games/game/116881

https://18xx.games/game/116881?action=341

**Problem**
The 3/5 train should score $60 (Detroit) + $60 (Cleveland) + $60 (Buffalo) = $180 but the game calculates it at $160

![image](https://user-images.githubusercontent.com/43420560/225975813-bf9166ae-2d1a-43fb-b163-0e63d33aa3dd.png)

**Which Browser / Platform?**

Chrome is up to date
Version 111.0.5563.65 (Official Build) (64-bit)

- Platform - Microsoft Pro 7

**Comment by scottredracecar** [comment]
You have to count one of your tokened cities.
