### ISSUE TITLE
1850 Mesabi Range Token - Alpha Build game 114806

### ISSUE THREAD

**Issue by jdbehan** [tobymao/18xx#9033]
New 1850 game set.

The Mesabi Range private has four tokens that can be purchase allow running to this area.  Once the private is closed, you can purchase these tokens from the bank.  Right now, the mechanism to do that doesn't exist in the game box.

I am unsure how to say how point out exactly where this can be seen.   There's nothing explicit on the game sequence.  They can be purchased at on time.

Game ID is 114806

**Comment by scottredracecar** [comment]
A good way to do that would be to make a hotseat game and play it up to the
point where you want to do the action, but it's not possible to do (doesn't
need to be realistic play, just create the scenario).

You'll have to upload the hotseat file like this:

If your game is "Hotseat", provide a link to your raw game data by using
the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share
the resulting link which will look something like `
https://gist.github.com/[your_name]/[some_letters]`.

**Comment by jdbehan** [comment]
I forgot that buying the Mesabi token was a track action!  We are all good.
