### ISSUE TITLE
[1880] 6E train seem cannot run the northern route (the one with $50 bonus)

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#9034]
As title
please check in the last OR of BZU run in the hotseat file
[hs_qekzcoeg_1679043717.zip](https://github.com/tobymao/18xx/files/11010360/hs_qekzcoeg_1679043717.zip)

**Comment by philcampeau** [comment]
Confirmed the problem. When you attempt to click on Vladivostok, the route does not continue to there. Route has a token, should be able to legally. 

No idea how to fix this, and not taking on the case. Just wanted to confirm that there's definitely an issue.
