### ISSUE TITLE
[18MS] - game not loading

### ISSUE THREAD

**Issue by Psylvania** [tobymao/18xx#9035]
I'm unable to access the game at all.  After I click on it from the homepage it says 'loading game' but doesn't do so. I've tried from two laptops and my phone.

**What's your Game ID?**

https://18xx.games/game/116812

**How to Reproduce the Bug?**

it may be that others trying to load the game from the homepage experience a similar problem.[https://18xx.games/game/116812]() 

**Which Browser / 
I've been using chrome.

**Comment by dolfyner** [comment]
Hi!
The game is stuck on loading for me too
Chrome on phone
Dolfyner

**Comment by benjaminxscott** [comment]
dupe of #9042
