### ISSUE TITLE
1880:  A few minor display bugs

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#9038]
Some UI things I've noticed in my current game (116522):

1)  During the SCR par selection at action (https://18xx.games/game/116522?action=400) the game is telling me I can afford 11 shares:  :)

![image](https://user-images.githubusercontent.com/66023744/226198945-ff846356-0ac1-4ddd-9cc3-93d38104bc2b.png)

2) On the Info tab, the Train display has two errors:
  a) The "B permit" event is missing (in two places)
  b) The "40% float" event is on the 4's, NOT the 4+4's

![image](https://user-images.githubusercontent.com/66023744/226199228-1095ee0e-ebb4-4ec3-ac4c-3fb95b0e6d6b.png)

**Comment by waaayback** [comment]
Follow-up on #2:  The 40% event is also wrong in the game log.
![image](https://user-images.githubusercontent.com/66023744/226205703-fde1fff0-1345-4ddb-b147-057ca5c26c58.png)

**Comment by bentziaxl** [comment]
1-> 
The B permit event is not missing, If you go back to the start of the game, this is the event listing:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/108803147/226205856-c72a53d9-ef7c-413e-8ca2-43b112fe04e2.png">


When you're in a later phase, the game removes the events that already happened from this view. This exists for every game on the site not just 1880

2-> the 40% event shows up for both the 4+4 and the 4, you can see in the logs as well:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/108803147/226205927-36e85e9e-ee15-4b1e-992a-2f16cbe28c8d.png">

**Comment by waaayback** [comment]
haha thanks for the reply.  Guess I hadn't noticed that and it seemed odd when you delete the prior events.   all good I guess

**Comment by crericha** [comment]
These are events, not state information, so 30% applies until it doesn't. That is how all games on the platform work.

**Comment by ChrisTheCat** [comment]
Then why is 40% repeated? By that logic, it should only appear once.

Either 30% and 40% should appear once, or they should appear twice. It
doesn't make sense to have one appear once and the other appear twice.

**Comment by waaayback** [comment]
I agree with Chris Shaeffer.  We both get they’re events, but be consistent in their display.  And actually, if it’s an event (one-time!) then the 40% event should NOT be repeated on the 4+4 line.
