### ISSUE TITLE
DEVELOPMENT.md - Need Postgres Configured or Not?

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#904]
I have just begun to try to get this to run locally for me.  After some initial weirdness "make dev_up_b" appears to be creating/running the game.  (From a browser I can definitely get to the mainpage of the site, but didn't actually try to start a game.)

The next step in the Dev/Readme appears to be to run "make prod_up".  However, this generates what look like genuine issues indicating that I need Postgres installed and properly configured on my box.

I think what is confusing me is that the steps are presented sequentially (indicating do this then this then this), and it may be that these actions are really independent of each other.

I think a few minutes of additional dress up for the Dev/Readme might be beneficial to the community.

**Comment by tobymao** [comment]
you don't need to run prod_up, make dev_up_b is sufifcient

the documentation says to run prod_up if you want the production stack which you don't.
