### ISSUE TITLE
(1850) Price protection

### ISSUE THREAD

**Issue by webbtraverse08** [tobymao/18xx#9041]
Rule 5.9.10 indicates a president can price protect even if they sold shares that stock round. Game 116181 disallowed that action.

https://18xx.games/game/116181

**Comment by bentziaxl** [comment]
I didn't touch the price protection mechanism and copied it exactly from 1870. Is this broken there as well? or is it different from 1870?

**Comment by bentziaxl** [comment]
Also, which action in particular in this game?

**Comment by webbtraverse08** [comment]
I believe it was action 368. Sale of 1 share of GN by player ManWithManyCheeses.

Rules of 1870 are different, as price protection is not available if president has sold that stock round. A weird little difference between the rulesets.

**Comment by bentziaxl** [comment]
Great!, thanks for alpha testing and opening bugs. I'll fix it
