### ISSUE TITLE
[18MS] stuck - bad track?

### ISSUE THREAD

**Issue by BobProbst** [tobymao/18xx#9042]
https://18xx.games/game/116812

can’t load game.  I placed a curve at f4 a couple ors ago and when I went back into the game it appeared turned in an illegal fashion.  The track was not connected to any other track. Weird but I just upgraded it on the next or and now it seems the game is unable to load

**Comment by benjaminxscott** [comment]
`Uncaught in re.p: Undefined method `id' for nil"`

**Comment by Psylvania** [comment]
Can we rewind back to the turn before the invalid tile lay and just play from there?

**Comment by michaeljb** [comment]
Found this while validating #9029:

Tile 8-7 was placed on F4 ([action 123](https://18xx.games/game/116812?action=123)), and then also incorrectly placed on B4 ([action 126](https://18xx.games/game/116812?action=126)), which is when the illegal orientation on F4 appeared.

I rewound the game back to before action 126, you could still look at the game log produced at [action 225](https://18xx.games/game/116812?action=225) if you want to recreate the same actions from there.
