### ISSUE TITLE
[1866] Broken '66 game

### ISSUE THREAD

**Issue by sqookmcbat** [tobymao/18xx#9044]
I have a wedged '66 game; pinned to an older version so I appreciate this may be Old News but it would be fantastic if someone could end and archive it for me please.

https://18xx.games/game/110695?action=1377

Broken action: { "type": "sell_shares", "entity": "SSFL", "entity_type": "corporation", "id": 1378, "created_at": 1676474008, "shares": [ "SSFL_7", "SSFL_8" ], "percent": 20 }

pinned to version 6636cbda4

Thanks!

**Comment by benjaminxscott** [comment]
It seems to load now, if that works?

**Comment by benjaminxscott** [comment]
Pinned games get deleted automatically so I don't think there's an action on the maintainer's side
