### ISSUE TITLE
18Mag +1 engineer not working 

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9045]
https://18xx.games/game/116943
 
 doesn’t count the town when you use the power, does with autoroute but then there’s a “nil can’t be an integer” error?

**Comment by BellmakerSA** [comment]
Also MAVAG has 2.5 bucks in it somehow now

**Comment by mb1898** [comment]
same in 
https://18xx.games/game/117186?action=199

**Comment by adambaig** [comment]
Also here:  https://18xx.games/game/118623

**Comment by jasonab** [comment]
also here: https://18xx.games/game/119173
