### ISSUE TITLE
1889 Bullet

### ISSUE THREAD

**Issue by JGovernor** [tobymao/18xx#9046]
We’ve been playing 1889-bullet (a variant of 1889) enough that it’s time I send in to you folks to add.

1889-bullet rules:
-remove 1 of each train prior to game start 
-no more tile or tokens after the 2nd diesel is bought.

Impact:
This game is notably faster, particularly in late game, however the biggest impact, by far, is the elimination of the (typical) requirement to open all companies to before the 4s can rust.  

History:

I created this mod as a teach game (I end at the OR where the last 2 is purchased though).  

After playing both the “intro/bullet” game and the standard 1889, everyone preferred 1889-bullet (8 of 8 people, made up of 3 separate play groups).

So try out 1889-bullet and with end at the OR that 2nd deisel is bought, or restrict tiles (we also tried with a 5k pool, which worked ok).

1889-bullet, as we call it now (it’s the variant we typically play now) is sweet. Try it out and add it as a variant option in 1889.

(Ps. I’m the guy on bgg with the $200+ cost-to produce 1889 map.   Neoprene map. All wood tiles and oiled-bronze tokens.  Certs at pie-slices @32 degrees, president is 72 degrees (10%/20% of a Circe)).  I’m pretty sure I have the most overproduced 1889 in the world!

**Are there related ideas?**
Didn’t find any
Other contributors may be working on something similar, [check out the list of open feature requests](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to see if there's opportunity to collaborate.

**Did you join the Slack?**
Nope. I’ll check it out.
Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ) and meet your fellow contributors!

**Comment by michaeljb** [comment]
Sorry, we only implement officially-endorsed variants. 18xx.games does have 18Chesapeake: Off the Rails which has the same train roster as your bullet game.
