### ISSUE TITLE
[1822] Incorrect revenue for 2p train with pullman from france to london

### ISSUE THREAD

**Issue by nannerwhgreene** [tobymao/18xx#9056]
**What's your Game ID?**
https://18xx.games/game/116981

**How to Reproduce the Bug?**

attach a pullman to 2p train.
mr token in english channel
track through folkstone dit
game tracks the stops correctly, but doesn't include the revenue for london, or any other station.

![image](https://user-images.githubusercontent.com/93997558/227807379-93bda415-cfe0-46b2-a749-ad08f68099ff.png)

![image](https://user-images.githubusercontent.com/93997558/227807404-ff08e3a1-22f7-4d54-b560-5b7b12efd420.png)

**Which Browser / Platform?**
Both edge and safari have the same issue.  revenue calculation incorrect in game.

**Comment by michaeljb** [comment]
Can't reproduce, and the linked game has been archived, no data in a gist. We can reopen if this reoccurs.
