### ISSUE TITLE
[1822PNW] Unable to lay a tile

### ISSUE THREAD

**Issue by DarthIA** [tobymao/18xx#9057]
**What's your Game ID?**

https://18xx.games/game/105341

**How to Reproduce the Bug?**

During the first operating round of M12, I cannot lay any city tile, no matter the type and orientation of the city tile I choose. There are plenty of tiles available, and the error message doesn't make any sense:

![image](https://user-images.githubusercontent.com/24686708/227807541-9a1d2c3a-0c10-436e-b333-2ed8441a02a1.png)

**Which Browser / Platform?**
Tried on Chrome in MacOS and also in Android with the same result.

**Comment by DarthIA** [comment]
Another player just used Master mode to lay the tile correctly. Not sure if this should be investigated anyway as there are similar reports on other games.

**Comment by benjaminxscott** [comment]
This should be fixed and deployed https://github.com/tobymao/18xx/commit/33c032ba9
