### ISSUE TITLE
[18CZ] On acquisition, 40K token of acquiring company becomes 100K

### ISSUE THREAD

**Issue by zachcd** [tobymao/18xx#9059]
**What's your Game ID?**

[game -117931](https://18xx.games/game/117931)

Link to game action: [game action - 117931@385](https://18xx.games/game/117931?action=385)

**How to Reproduce the Bug?**

During a Medium or Large companies operation, if the company has a 40K token on its charter and acquires a smaller company, the 40k token will be replaced with a 100k token.

Screenshots:
Medium company with an available 40 token prior to any acquisitions

![image](https://user-images.githubusercontent.com/6234996/227809588-20b133c9-ca5d-43a7-b567-dbd4e0da0713.png)

Medium Company after acquiring a Small company with no 40 tokens anymore.

![image](https://user-images.githubusercontent.com/6234996/227809602-a01eb307-46a0-42fa-b662-13e4359622cd.png)

**Comment by michaeljb** [comment]
Found a link to this BGG post in the comments, this is actually working correctly - https://boardgamegeek.com/thread/2405214/article/34514502#34514502 

> When a company places a token, it first counts all tokens it already has on the board, no matter if they are it's original tokens or tokens earned by acquisitions. If it's only the home token, then the next token cost $40. If it's two or more tokens then each additional token cost $100.
