### ISSUE TITLE
[1880] Cannot upgrade any yellow tile to green - "already in use on hex A1"

### ISSUE THREAD

**Issue by MarkS-choochoo** [tobymao/18xx#9061]
**What's your Game ID?**

https://18xx.games/game/111294

**How to Reproduce the Bug?**

Attempting upgrade any yellow tile to green with company NXR in the current OR (OR4.6) triggers an error "Cannot lay tile XX-X; it is already on hex A1". NXR has a building permit for the current phase. Also, as can be seen from the map hex A1 does not actually exist in the game.

**Which Browser / Platform?**
- Browser Version
Google Chrome | 111.0.5563.66, desktop
but have also reproduced the error in Firefox desktop

**Comment by MarkS-choochoo** [comment]
I see now that #9057 and #9058 are about the same issue in different games as well.

**Comment by Bmore84** [comment]
I am having this same issue in a game of 1822.

**Comment by DarthIA** [comment]
FWIW, another player in my game was able to lay the tile I was trying to lay in #9057 when activating the Master mode.

**Comment by MarkS-choochoo** [comment]
It seems to be resolved, at least on my game, so I'm going to close this.
