### ISSUE TITLE
18Mag: cannot lay any tiles or upgrade tiles, tile already in use in A1

### ISSUE THREAD

**Issue by dfwinfinitejest** [tobymao/18xx#9062]
Hi,

This is my first bug report for 18XX so please forgive me if I have left anything out.

Game #117151: 4p 18Mag with new expansion (minors and major). Currently, in 3rd operating round with minor #11 to play. #11 cannot upgrade D7, E6, or F7. After selecting an green upgrade tile, the game reports that the tile cannot be played due the fact that it is already in use on tile A1.

I am playing on Safari, iOS 16.3.1 on an iPad 12.9” Pro.

https://18xx.games/game/117151

**Comment by benjaminxscott** [comment]
This should be fixed and deployed https://github.com/tobymao/18xx/commit/33c032ba9
