### ISSUE TITLE
1822 cannot upgrade or lay track

### ISSUE THREAD

**Issue by Bmore84** [tobymao/18xx#9063]
![Screenshot_20230326_190636_Samsung Internet](https://user-images.githubusercontent.com/115173892/227813494-1890b865-c43f-4aad-954a-181d8bf0ddc2.jpg)
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

**What's your Game ID?**

https://18xx.games/game/112768
1822

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
Upgrading or laying track causes an error.  I have back to back companies and it affected both. As did the company after me. Screenshot included

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by drath3000** [comment]
I had the same issue just recently with 1848. No matter what tile I tried to lay or upgrade would give me an error of ‘cannot lay tile X; it is already on A1’ where ‘X’ would change depending on the tile I was trying to lay/upgrade.

I was eventually able to lay track however only after reloading the game multiple times and switching tabs. I am running safari on an iPad.

**Comment by benjaminxscott** [comment]
This should be fixed and deployed https://github.com/tobymao/18xx/commit/33c032ba9
