### ISSUE TITLE
18FL - Tile 15-0 cannot lay

### ISSUE THREAD

**Issue by bjstover** [tobymao/18xx#9064]
I am trying to upgrade Mobil (B-5) from yellow to green and I get the error "Cannot lay tile 15-0; it is already on hex A1" We are in phase 3 and there are no other green tiles in play. 

.json of the game at https://drive.google.com/file/d/1wZ-EvcgshzHJ87LwM_K-39YRQlKUqRLV/view?usp=sharing

**Comment by benjaminxscott** [comment]
This should be fixed and deployed https://github.com/tobymao/18xx/commit/33c032ba9
