### ISSUE TITLE
[1850] Mesabi token/range

### ISSUE THREAD

**Issue by rstites25** [tobymao/18xx#9066]
https://18xx.games/game/117558

-The rules implementation for the Mesabi range appears to be incorrect. 

"Ownership of a Mesabi Range token is required to trace a route to or through the Mesabi Range." (back of private)

Moreover, the rules state "No company may connect to the Mesabi Range until the Mesabi Mining private company has been purchased by a public company." (description of P5 on p. 16 of version 4.0e)

In the above game, in OR1.1, a player was able to lay the Duluth yellow city to go into the Mesabi hex (I believe this is legal) but then placed his second tile to the west of Mesabi, with no connection other than _through_ Mesabi--which is illegal until the private has been purchased (or closed) since there is no legal route through that hex. 

In a previous game-- https://18xx.games/game/114287#entities -- 6 companies were able to buy Mesabi tokens when there are a max of 4 tokens available. 

I am unsure of how the module currently handles the connectivity requirement for purchasing one of the four tokens. But conceptually, buying the token is a yellow track lay on the Mesabi hex--i.e., you have to be able to trace a legal route to the mesabi hex before a company may purchase a token allowing the "connection."

**Comment by benjaminxscott** [comment]
related to https://github.com/tobymao/18xx/issues/8885 ?
