### ISSUE TITLE
1846 run a 7/8, a 4/6, and a 4 train in one turn -> train limit exceeded

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#9071]
https://18xx.games/game/117706?action=443

game 117706

move 443

The IC runs 3 trains after the first 7/8 has been bought. Delayed obselence ok, but train limit violated.

Rule 6.57 (deep thought games) says that excess trains of the train limit have immediately to be returned to the bank.

**Comment by mb1898** [comment]
rule 6.54 says phased out trains do not count against the train limit

**Comment by Aznd4u69** [comment]
Stop fucking emailing me
