### ISSUE TITLE
1850 game Id 114218

### ISSUE THREAD

**Issue by HelenCheale** [tobymao/18xx#9074]
If this game can’t be fixed can it be manually ended somehow?

**Comment by benjaminxscott** [comment]
since it's pinned it'll get deleted after about a week

**Comment by HelenCheale** [comment]
Still not deleted

**Comment by HelenCheale** [comment]
Still not deleted

**Comment by HelenCheale** [comment]
Still not deleted

**Comment by HelenCheale** [comment]
Still not deleted yet

**Comment by HelenCheale** [comment]
Still not deleted
