### ISSUE TITLE
1880 end game trigger missed 

### ISSUE THREAD

**Issue by MatthewDeKoning** [tobymao/18xx#9081]
https://18xx.games/game/111308

NXR should have both run and triggered the end of the game, it did neither. 

Thanks!

**Comment by crericha** [comment]
NXR did indeed trigger the end game as indicated in the final rounds `1880: Phase D3 - Operating Round 10.15 - Run Routes - Last 8 train was purchased : Game Ends at conclusion of OR 10.14 NXR's turn`.

NXR's home had no track and the company did not have a D building permit to build track, so it had no runs.

What were you expecting instead?

**Comment by ChrisTheCat** [comment]
burmer accidentally chose an A building permit in SR9 when he set the par for NXR. It could not lay track in phase D without a D permit.

**Comment by crericha** [comment]
Okay, I missed the game was manually ended because the end didn't trigger. Looks like there is a corner case where if the last company can't operate, the end game trigger is missed. @bentziaxl

**Comment by crericha** [comment]
@bentziaxl I think this case needs to also `call after_end_of_turn` https://github.com/tobymao/18xx/blob/master/lib/engine/round/operating.rb#L70

**Comment by MatthewDeKoning** [comment]
Thanks for looking at that - I thought the game would end at the end of NXR’s turn in OR 10.14 but it continued to OR 10.15, so I thought there was a bug due to NXR being in a goofy state.

Thanks, Matthew

Sent from my iPhone

On Apr 4, 2023, at 7:06 PM, Chris Rericha ***@***.***> wrote:

﻿
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe

NXR did indeed trigger the end game as indicated in the final rounds 1880: Phase D3 - Operating Round 10.15 - Run Routes - Last 8 train was purchased : Game Ends at conclusion of OR 10.14 NXR's turn.

NXR's home had no track and the company did not have a D building permit to build track, so it had no runs.

What were you expecting instead?
