### ISSUE TITLE
(1849) President's certificate counting for 2 certificates

### ISSUE THREAD

**Issue by mattk-ce** [tobymao/18xx#9083]
The president's certificate, when acquired via the acquisition of Reale Società d'Affari, resulted in the owning player's cert count to increase by 2 rather than by 1.  We did notice, however, that the cert count correctly increased by only 1 when the "last certificate" was acquired.

**What's your Game ID?** https://18xx.games/game/118644

**How to Reproduce the Bug?** See above

![image](https://user-images.githubusercontent.com/68982643/230179092-8b9072d2-0396-4b27-8c95-49ed6408c622.png)

**Comment by crericha** [comment]
The company is the fourth cert.

**Comment by dfannius** [comment]
The cert count of 4 looks correct to me: 1 president's share of RCS + 2 normal shares of RCS + 1 private = 4.

**Comment by mattk-ce** [comment]
Ah, good catch.  That's what I get for multitasking.  Sorry for the noise!
