### ISSUE TITLE
1880 crashed (GameError: Blocking step Lay/Upgrade Track cannot process action)

### ISSUE THREAD

**Issue by arcee1986** [tobymao/18xx#9089]
game crashed and requested a report, so here it is:

We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action 947
Broken action: { "type": "pass", "entity": "JLR", "entity_type": "corporation", "id": 947, "created_at": 1680761830 }

https://18xx.games/game/113706?action=946

**Comment by bentziaxl** [comment]
old game that broke after some implementation changed. WNR bought a 10 train without money, while the 10 wasn't available yet. nothing to fix.

**Comment by arcee1986** [comment]
Can you kill the game please? stops me from seeing when a turn comes up, since it's always my turn in this one.

**Comment by michaeljb** [comment]
I have archived the game.
