### ISSUE TITLE
[1846] Bug: Game error when trying to lay tile with B&O

### ISSUE THREAD

**Issue by g18xxgit** [tobymao/18xx#909]
`We're sorry this game cannot be continued due to GameError: IC has 172 and cannot spend 180
Please raise a bug report and include the game id (hs_cisqosnl_1593337951) and the following JSON data`

Oddly, I was trying to lay track with the B&O, making use of the O&I to lay free tiles.  However, it doesn't appear the O&I "freebie" had been applied.  When I pressed "Undo" in order to try how to do this again, this error came up - oddly referring to the IC who were not the currently operating company.

**Comment by g18xxgit** [comment]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 1,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 2,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 3,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 4,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 5,
      "company": "TBC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 6,
      "company": "Pass (2)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 7,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 8,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 9
    },
    {
      "type": "pass",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "bid",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 11,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "par",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 12,
      "corporation": "GT",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 13,
      "corporation": "B&O",
      "share_price": "50,0,5"
    },
    {
      "type": "par",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 14,
      "corporation": "IC",
      "share_price": "100,0,10"
    },
    {
      "type": "buy_shares",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "B&O_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 17,
      "shares": [
        "IC_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 21,
      "hex": "C13",
      "tile": "7-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 22,
      "hex": "D14",
      "tile": "5-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 23,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "C13",
              "D14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 24,
      "hex": "G9",
      "tile": "6-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 25,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 2
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 26,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 27,
      "company": "TBC",
      "price": 60
    },
    {
      "type": "sell_shares",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 28,
      "shares": [
        "B&O_2"
      ],
      "percent": 10,
      "share_price": 40
    },
    {
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 29
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 30
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 31
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 32,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 33
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 34
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 35,
      "hex": "B16",
      "tile": "6-2",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 36
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 38,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 39
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 40
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 41
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 42,
      "hex": "J4",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 43,
      "hex": "I3",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 44,
      "city": "I5-0-0",
      "slot": 0
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 45,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 46,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 47,
      "train": "4-0",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 48
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 49
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 50,
      "hex": "B16",
      "tile": "619-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 51,
      "hex": "B14",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 52,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 53,
      "hex": "F10",
      "tile": "8-0",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 54,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "sell_shares",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 55,
      "shares": [
        "IC_2"
      ],
      "percent": 10,
      "share_price": 80
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 56,
      "hex": "I7",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 57,
      "hex": "I9",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 58,
      "company": "MAIL",
      "price": 60
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 59,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "I5",
              "I3",
              "I1"
            ],
            [
              "I5",
              "I7",
              "I9",
              "J10"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 60,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 62
    },
    {
      "type": "sell_shares",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 63,
      "shares": [
        "GT_2"
      ],
      "percent": 10,
      "share_price": 60
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 64,
      "hex": "B12",
      "tile": "9-4",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 65,
      "hex": "B10",
      "tile": "9-5",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 66,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "B16",
              "B14",
              "B12",
              "B10",
              "B8"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 67,
      "kind": "payout"
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 68
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 69,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 70
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "sell_shares",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 72,
      "shares": [
        "B&O_2",
        "B&O_3",
        "B&O_4"
      ],
      "percent": 30,
      "share_price": 30
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 73,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 74,
      "hex": "G19",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 75
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 76,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "G21",
              "G19"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 77,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 78
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 79
    },
    {
      "type": "buy_shares",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 80,
      "shares": [
        "GT_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 81,
      "shares": [
        "B&O_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 82,
      "shares": [
        "IC_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 83
    },
    {
      "type": "buy_shares",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 84,
      "shares": [
        "B&O_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 85
    },
    {
      "type": "pass",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "buy_shares",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 87,
      "shares": [
        "B&O_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "buy_shares",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 90,
      "shares": [
        "GT_3"
      ]
    },
    {
      "type": "pass",
      "entity": "Carole-IC",
      "entity_type": "player",
      "id": 91
    },
    {
      "type": "pass",
      "entity": "Alice-GT",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "undo",
      "entity": "MS",
      "entity_type": "minor",
      "id": 94
    },
    {
      "type": "pass",
      "entity": "Bob-C&O",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 96,
      "hex": "D12",
      "tile": "9-6",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 97,
      "hex": "D10",
      "tile": "9-7",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 98,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 99,
      "hex": "F12",
      "tile": "9-8",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 100,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 101
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 102,
      "hex": "H6",
      "tile": "9-9",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 103,
      "hex": "G7",
      "tile": "619-1",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 104,
      "routes": [
        {
          "train": "4-0",
          "connections": [
            [
              "I5",
              "I3",
              "I1"
            ],
            [
              "I5",
              "I7",
              "I9",
              "J10"
            ]
          ]
        },
        {
          "train": "2-6",
          "connections": [
            [
              "I5",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "I5",
              "H6",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 105,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 106,
      "train": "4-1",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 107
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 108
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 109,
      "hex": "C15",
      "tile": "294-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 110,
      "hex": "D8",
      "tile": "9-10",
      "rotation": 1
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 111,
      "city": "D6-0-2",
      "slot": 0
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 112,
      "routes": [
        {
          "train": "2-3",
          "connections": [
            [
              "B16",
              "B14",
              "B12",
              "B10",
              "B8"
            ]
          ]
        },
        {
          "train": "2-4",
          "connections": [
            [
              "B16",
              "C15"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 113,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 114
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 115
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 116
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 117,
      "hex": "F18",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 118,
      "hex": "F16",
      "tile": "9-11",
      "rotation": 1
    }
  ],
  "id": "hs_cisqosnl_1593337951",
  "players": [
    {
      "name": "Alice-GT"
    },
    {
      "name": "Bob-C&O"
    },
    {
      "name": "Carole-IC"
    }
  ],
  "title": "1846",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-28",
  "loaded": true,
  "result": {}
}

**Comment by wcraigtrader** [comment]
FWIW, I've seen similar errors; typically its a result of undoing the first action in an OR for a company that is not the first in the round. An undo to a previous company's actions will show this error. Once it pops up, there's nothing that can be done with that game, because the game state is out of sync with the game data. Unfortunately, I haven't been able to reproduce it reliably, so I don't have simple steps to help you debug.

**Comment by tobymao** [comment]
can't reproduce this, game is broken now
