### ISSUE TITLE
1850 - GameError: Blocking step Run Routes cannot process action 798

### ISSUE THREAD

**Issue by Bearcat89** [tobymao/18xx#9090]
Broken action: { "type": "pass", "entity": "NP", "entity_type": "corporation", "id": 798, "created_at": 1680803061 }
https://18xx.games/game/115410?action=797

**Comment by Bearcat89** [comment]
Cannot delete this broken game.  Can management please delete it?

**Comment by michaeljb** [comment]
This game has been archived.
