### ISSUE TITLE
18Mag: train missing after purchase, $$ balance incorrect, and extra terrain tokens

### ISSUE THREAD

**Issue by dfwinfinitejest** [tobymao/18xx#9092]
Hi.

In a 4p 18Mag game ([#118950](https://18xx.games/game/118950)), I operated minor #12 in OR2.1 After running my route I had $90 and purchased a second 2 train with $10 leftover. When I got to minor #12 in OR3.1, that second train had disappeared. Minor #12 now had one 2 train, a balance of $11, and two new terrain tokens (I used the initial token in OR 1.1).

I hope this is sufficient detail. Thanks.

**Comment by philcampeau** [comment]
-In OR 1.1, Minor 12 did not use it's terrain token: 
![image](https://user-images.githubusercontent.com/26125362/232806308-e315cfba-853f-47a2-8c82-2cccea601836.png)

Currently, when I scroll back in the log to OR 3.1, Minor 12 still has 2x2 trains, but it only ran one of them. 

![image](https://user-images.githubusercontent.com/26125362/232807518-cd67442e-9fdd-475a-8eec-8d0cf39aaaaa.png)

It looks like previously Minor 5 had bought a train across from M12  for $1, which would have left M12 with $11 and one train, but that was undone. 

![image](https://user-images.githubusercontent.com/26125362/232810822-0aa35bde-c6d7-4f64-ab59-0c301d5cb56c.png)

My assumption would be that we can close this issue, if @dfwinfinitejest has more to add, they can always reply and we'll reopen this.
