### ISSUE TITLE
[1850] stuck on… tile lay? But current player says someone else.

### ISSUE THREAD

**Issue by devslashlol** [tobymao/18xx#9095]
Link:

https://18xx.games/game/115965?action=508

This is my oldest game, not sure it happened on my turn exactly.

**Comment by devslashlol** [comment]
Error: We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 509
Broken action: { "type": "choose", "entity": "NP", "entity_type": "corporation", "id": 509, "created_at": [1679670614](tel:1679670614), "choice": "Place Edge Token" }

**Comment by michaeljb** [comment]
The game has been archived.
