### ISSUE TITLE
Database problem when trying to launch fresh development environment of 18xx.games

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#910]
Did install the needed requirements (accoriding to 18xx/blob/master/DEVELOPMENT.md) and then tried to do 

- make
- make prod_up
This was done in an empty Linux Mint 19 environment.
The first make did produce a couple of errors and after a long time it had not shown that it was running something so I did Ctrl-C.
When trying the second command I got error messages about missing environment variables. So maybe some instructions might be missing?

I include a text file with my session.

Example of errors for the first command (which gave a VERY verbose printout):
`db_1     | 2020-06-28 10:01:39.280 UTC [65] ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"`

Errors for the second command:
`per@per-Linux-Mint-19:~/my-18xx/18xx-games-repo$ make prod_up
rm -f docker-compose.override.yml
ln -s docker-compose.prod.yml docker-compose.override.yml
./scripts/data_dir.sh
./scripts/ensure_prod_env.sh
ERROR: no values found for the following environment variables:

- DATABASE_URL
- MAIL_JET_KEY
- MAIL_JET_SECRET
- POSTGRES_USER
- POSTGRES_PASSWORD
- POSTGRES_DB
Makefile:10: recipe for target 'ensure_prod_env' failed
make: *** [ensure_prod_env] Error 1`

After doing this I also tried "make" again, and now I did connect to localhost:9292 and it seem to be running fine.

[18xx.problems.txt](https://github.com/tobymao/18xx/files/4842084/18xx.problems.txt)

**Comment by tobymao** [comment]
you don’t have the necessary settings to run prod . dev will give you everything you nrrd

**Comment by tobymao** [comment]
just run make dev_up_b. let me know if this doesn’t work
