### ISSUE TITLE
M1 cannot place a tile in F7 Game 118272

### ISSUE THREAD

**Issue by F8Crusader** [tobymao/18xx#9105]
M1 is unable to place a tile on F7, even though it can run a route through Glasgow.

**Comment by dfannius** [comment]
Update from #9106:

> Previous post had the wrong minor listed. It's M2, Higlands, that cannot lay a tile in F7.

**Comment by dfannius** [comment]
https://18xx.games/game/118272?action=196 I guess, although it worked for me in hotseat.

**Comment by F8Crusader** [comment]
Thanks.  My mistake.  Got my minors confused.  Thanks for looking at.
    On Saturday, April 15, 2023 at 11:00:31 AM CDT, Dan Schmidt ***@***.***> wrote:  
 
 


https://18xx.games/game/118272?action=196 I guess, although it worked for me in hotseat.

**Comment by F8Crusader** [comment]
Thanks!  No problem.  I got my minors mixed up.  No error.
    On Sunday, April 16, 2023 at 04:17:33 AM CDT, Michael Brandt ***@***.***> wrote:  
 
 


Closed #9105 as not planned.
