### ISSUE TITLE
[1846] MC tile lays are not "extra"

### ISSUE THREAD

**Issue by g18xxgit** [tobymao/18xx#911]
1846 Hotseat test game - hs_whsgcrnd_1593340772

Michigan Central (MC) has been bought into the Grand Trunk (GT).  However, the tile lay by the GT in the eastern MC space takes up one of the two available actions, when under the GMT rules it should be a free ($0) and extra tile lay.

Data below just after move made with problem.  End of log is:

> Alice operates GT
GT passes
GT spends $20 and lays tile #30 with rotation 4 on C13
GT lays tile #8 with rotation 5 on B12

**Comment by g18xxgit** [comment]
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Doug",
      "entity_type": "player",
      "id": 1,
      "company": "SC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Carole",
      "entity_type": "player",
      "id": 2,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Bob",
      "entity_type": "player",
      "id": 3,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Alice",
      "entity_type": "player",
      "id": 4,
      "company": "MC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Doug",
      "entity_type": "player",
      "id": 5,
      "company": "Pass (4)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Carole",
      "entity_type": "player",
      "id": 6,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Bob",
      "entity_type": "player",
      "id": 7,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "Alice",
      "entity_type": "player",
      "id": 8,
      "company": "Pass (2)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Doug",
      "entity_type": "player",
      "id": 9,
      "company": "Pass (3)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Carole",
      "entity_type": "player",
      "id": 10,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Bob",
      "entity_type": "player",
      "id": 11,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Alice",
      "entity_type": "player",
      "id": 12
    },
    {
      "type": "bid",
      "entity": "Doug",
      "entity_type": "player",
      "id": 13,
      "company": "TBC",
      "price": 60
    },
    {
      "type": "par",
      "entity": "Alice",
      "entity_type": "player",
      "id": 14,
      "corporation": "GT",
      "share_price": "112,0,11"
    },
    {
      "type": "par",
      "entity": "Bob",
      "entity_type": "player",
      "id": 15,
      "corporation": "NYC",
      "share_price": "70,0,7"
    },
    {
      "type": "par",
      "entity": "Carole",
      "entity_type": "player",
      "id": 16,
      "corporation": "IC",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "Doug",
      "entity_type": "player",
      "id": 17,
      "corporation": "B&O",
      "share_price": "100,0,10"
    },
    {
      "type": "buy_shares",
      "entity": "Alice",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Bob",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "NYC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Doug",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "B&O_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Alice",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Bob",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "pass",
      "entity": "Doug",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 24,
      "hex": "C13",
      "tile": "7-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 25,
      "hex": "D14",
      "tile": "5-0",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 26,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "C13",
              "D14"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 27,
      "hex": "G9",
      "tile": "6-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 28,
      "hex": "G7",
      "tile": "6-1",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 29,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "sell_shares",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 30,
      "shares": [
        "NYC_2",
        "NYC_3",
        "NYC_4"
      ],
      "percent": 30,
      "share_price": 60
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 31,
      "hex": "E19",
      "tile": "8-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 32,
      "hex": "E17",
      "tile": "291-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 33
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 34,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 35,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 36,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 37,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "NYC",
      "entity_type": "corporation",
      "id": 38
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 39,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 40
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 41,
      "hex": "H10",
      "tile": "9-0",
      "rotation": 2
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 42,
      "hex": "I11",
      "tile": "8-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 43
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 44,
      "train": "2-6",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 45,
      "train": "2-7",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 47
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 48,
      "company": "SC",
      "price": 40
    },
    {
      "type": "assign",
      "entity": "SC",
      "entity_type": "company",
      "id": 49,
      "target": "G19",
      "target_type": "hex"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 50
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 51
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 52,
      "train": "4-0",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 54
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 55,
      "company": "MC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 56
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 57,
      "hex": "B16",
      "tile": "6-2",
      "rotation": 4
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 59,
      "train": "4-1",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 60
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 62,
      "hex": "D12",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 63,
      "hex": "D10",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 64,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "C13",
              "D14"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 65
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 66,
      "hex": "C13",
      "tile": "30-0",
      "rotation": 4
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 67,
      "hex": "B12",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 68
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 69,
      "hex": "B12",
      "tile": "8-2",
      "rotation": 5
    }
  ],
  "id": "hs_whsgcrnd_1593340772",
  "players": [
    {
      "name": "Alice"
    },
    {
      "name": "Bob"
    },
    {
      "name": "Carole"
    },
    {
      "name": "Doug"
    }
  ],
  "title": "1846",
  "description": "test 2 20200628",
  "max_players": "4",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-06-28",
  "loaded": true,
  "result": {}
}

**Comment by tobymao** [comment]
did you click on the comps to activate the ability?

**Comment by wcraigtrader** [comment]
I saw this, because its too easy to click on the private, lay a tile, then lay the next tile without remembering to click on the private a second time.

**Comment by tobymao** [comment]
this works fine for me, you need to click on the company
