### ISSUE TITLE
1871 TOP Game broken 

### ISSUE THREAD

**Issue by dtschirmer** [tobymao/18xx#9120]
https://18xx.games/game/118904?action=451

https://gist.github.com/benjaminxscott/2d183a4b77de8e7e52074b516fb89eb8

**Comment by benjaminxscott** [comment]
Does it let you hit `Undo` ?

**Comment by dtschirmer** [comment]
No, it says "this game is broken and cannot accept any new actions."

**Comment by benjaminxscott** [comment]
I asked if we can back out the last action (train purchase) in the DB so it can continue, the player was one dollar short

**Comment by michaeljb** [comment]
I removed that action from the DB, you should be able to continue now.

**Comment by dtschirmer** [comment]
It still seems broken. It's my turn, and it won't let me seel any
shares to get more funds, or buy the 7 train. It says I must sell
shares to generate 1 dollar, but it won't let me sell any more.

**Comment by dtschirmer** [comment]
OK, never mind, I hit Undo again and sold shares and it let me. All good!
