### ISSUE TITLE
[1822MX] Mexico City Adjacent Track not reserved for Concession/minor company holders.

### ISSUE THREAD

**Issue by TheTagoreler** [tobymao/18xx#9129]
GameID: https://18xx.games/game/119429

Minor 20 lays hex O24 during OR3.  Hex O24 is one of the 5 unbuilt hexes next to Mexico City, which is covered by 6.9.2. which states that hexes adjacent to Mexico city may not have yellow track placed on them without the consent of the owner of the associated minor, or concession.  I am the owner of the IRM concession that points to hex O24 and would not have consented to this placement.  There did not seem to be a prompt or a restriction for this. 

Looking at the replay, there seems to be no prompt stopping this illegal tile lay.

![image](https://user-images.githubusercontent.com/78515638/233191923-4bdec598-bc1b-407d-bd54-6bdc3c786370.png)

![image](https://user-images.githubusercontent.com/78515638/233192010-33640d44-1937-4610-b200-87b91ed3a1c8.png)

**Comment by michaeljb** [comment]
Possibly related: #7812 and #8071
