### ISSUE TITLE
1850 Western Land Grant Private

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#9130]
error says "Paths must be connected"  Have tried Sioux Falls, beyond Sioux Falls on Clone, and other locations...

[119753  ](https://18xx.games/game/119753)

**Comment by bentziaxl** [comment]
which action id? when did the error happen?

**Comment by philcampeau** [comment]
@saxafras Are you able to tell us when the issue occurred in the game? With which corp? On whose turn? 

The ticket has already been open for over a month with no reply from the reporter. I'll close it, if they reply with more info we can always reopen later.
