### ISSUE TITLE
1850 Gant Brothers Private

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#9131]
https://18xx.games/game/119753

Gant Brothers lasts through the 5T as a non-paying entity but is no longer buyable into the company and it's function serves merely as value in case someone bankrupts specifically on the 5T.  It would be nice to get a clarification on this from the designer.  Seems like it should still be buyable into the company.

**Comment by philcampeau** [comment]
Rule 4.2.4 seems as clear as possible about this. 

![image](https://user-images.githubusercontent.com/26125362/233514405-23738f25-cd16-4534-b153-1fdd63cd44d3.png)
