### ISSUE TITLE
[1822PNW] E-Trains not using same stations as other normal trains in autoroute

### ISSUE THREAD

**Issue by DavekeC** [tobymao/18xx#9133]
**What's your Game ID?**
All 1822PNW games seem to have this issue

What steps cause the unexpected behavior?
- Play 1822PNW , Buy an E-Train while having another train and try to autoroute it ...
- It will take forever and the E-Train will not use same track as used for other normal trains

**Which Browser / Platform?**
- ALl

**Comment by michaeljb** [comment]
Dupe of #7982
