### ISSUE TITLE
[18NY] 

### ISSUE THREAD

**Issue by dawgamer60** [tobymao/18xx#9137]
The game got to the salvaging trains and the closing of the privates.  It worked for a couple of days and then crashed and reset us back nearly a week.

18NY 120048
(https://18xx.games/game/120048?action=276)

Error message is no longer coming up, but if crashed on 4/21 and reset up back to 4/14.

DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by michaeljb** [comment]
@dawgamer60 I reverted the change that broke your 18NY game, thanks for the report!

**Comment by michaeljb** [comment]
For @benjaminxscott to fix this and bring back the changes in #9136:

> We're sorry this game cannot be continued due to TypeError: NilClass can't be coerced into Numeric
> Broken action: { "type": "scrap_train", "entity": "D&H", "entity_type": "corporation", "id": 277, "created_at": 1682022082, "train": "2H-8" }
