### ISSUE TITLE
[18Chesapeake] bug: Susquehannah + undo/redo allows tile lay

### ISSUE THREAD

**Issue by philihp** [tobymao/18xx#914]
just had a weird thing happen to me in game 3023 in OR 5.1 during the PRR's turn. i got to the end of the turn after selling in the Susquehannah and placing the two tiles, then undo'ed back the whole turn to the previous company, then back into the PRR's turn and it allowed me to place the tiles that were reserved at F4 and F5.

**Comment by philihp** [comment]
Possible duplicate of #885

**Comment by jenf** [comment]
very likely, closing as dup
