### ISSUE TITLE
18USA Game 116805 WP cannot lay coal token on tile B6

### ISSUE THREAD

**Issue by F8Crusader** [tobymao/18xx#9142]
WP trying to lay east/west tile pointing toward Helena using P1 to place the coal tile.  No special ability button shows up.

**Comment by crericha** [comment]
In 18USA, the coal tile will automatically be shown in the tile options when the hex is selected. Look for the one with the pick axe.

**Comment by F8Crusader** [comment]
Awesome!    Thanks!
    On Sunday, April 23, 2023 at 09:35:41 PM CDT, Chris Rericha ***@***.***> wrote:  
 
 


In 18USA, the coal tile will automatically be shown in the tile options when the hex is selected. Look for the one with the pick axe.
