### ISSUE TITLE
elo-Rating, Overall differs from game

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#9144]
User "Grinch" has played 6 1861 games.
The rating from Overall and 1861 differs by 43 Points.
![grafik](https://user-images.githubusercontent.com/80693707/234300585-10cc631b-e8f3-4326-b197-aa08028933f6.png)

My expectation is: both numbers should be equal.

**Comment by philcampeau** [comment]
Not unexpected. Elo is rating your skill versus that of others. Your rating vs all plays of 1861 will be different than your rating vs all games.

**Comment by dfannius** [comment]
To make that even more clear (hopefully), Grinch's opponents probably had Overall ratings that were on average about 43 points higher than their 1861 ratings.
