### ISSUE TITLE
[Harzbahn 1873] Game UX doesn't allow me to lay the correct concession tile for WBE

### ISSUE THREAD

**Issue by Rumbleman3** [tobymao/18xx#9149]
**What's your Game ID?**
[118077](https://18xx.games/game/118077)

**How to Reproduce the Bug?**

Just trying to lay a tile

![image](https://user-images.githubusercontent.com/20756622/234999386-c1771ee8-9a98-450e-a35f-dc83d6dace72.png)

Edge Desktop.  This also repros on Safari Mobile

**Comment by ollybh** [comment]
@Rumbleman3  What tile were you hoping to place in this situation? The one that has appeared (76) is the correct tile to finish the concession route, though it has to be laid in a different orientation, connecting Heimburg (C14) to Blankenburg (D15).

I've cloned this game and can complete the concession route, and from the log of game 118077 you managed to do this as well.

**Comment by Rumbleman3** [comment]
Sorry for the noise.  You can close this.  I was just confused.
