### ISSUE TITLE
[18Mag] undefined method error when paying dividends

### ISSUE THREAD

**Issue by oliverheck** [tobymao/18xx#9154]
In game 120522 I am not able to pay dividends. No matter what amount I choose, I get 'undefined method' error.

`undefined method `player' for nil`

**What's your Game ID?**
https://18xx.games/game/120522

**Which Browser / Platform?**
- Browser Version
  - Safari Browser on iOS 16.4.1

**Comment by dolfyner** [comment]
Hi I have the same problem in https://18xx.games/game/121759 
Kind regards
Michal

**Comment by hast18xx** [comment]
similar issue in game 123256 after submit the server is rejecting with error  ----> see SC
![18xx sup](https://github.com/tobymao/18xx/assets/64490299/aa2070eb-01e7-4f62-803c-f75cf55be26a)

**Comment by hast18xx** [comment]
Hi Michael
it is still not working, same error. May be it is not deployed yet?
game id are:
123256
124154
 
https://18xx.games/game/124237   https://18xx.games/game/124237
if you like you can join the game and I will reproduce the issue by doing mastermode
 
mit freundlichen Grüßen
 
Harald Stieling
