### ISSUE TITLE
[18SJ] Cannot buy (Treasury) shares from a corporation in the brown segment while player is at max certificates.

### ISSUE THREAD

**Issue by gardir** [tobymao/18xx#9155]
**What's your Game ID?**
https://18xx.games/game/108393

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- Have a corporations with available shares in the Treasury (untested with IPO shares)
- That corporation market value is in the brown segment of stock chart
- Have max shares a player
- Try to buy shares from that corporation

**Which Browser / Platform?**
1. Desktop
  - Firefox 112.0.1
2. Mobile 
  - Chrome 112.0.5615.136

**Comment by philcampeau** [comment]
According to the rules, players should be allowed to buy shares in the brown zone of the market (maroon in the rules) from both the treasury and market, even past cert limit and ownership limit: 

![image](https://user-images.githubusercontent.com/26125362/236003429-c8981b01-f97b-4241-835f-eb5feceb115a.png)

**Comment by scottredracecar** [comment]
The wording in this section is slightly updated in the latest version to make it easier to parse. I'll update the rules link now too.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/29106780/236004908-8c89b08f-1754-4582-924b-54aa7a841eb9.png">

**Comment by gardir** [comment]
Thanks for confirming! Could I/we continue the game now? The shares aren't important, I stopped in order to submit this bug-report :)

**Comment by perwestling** [comment]
After studying the situation I think the implementation does the right thing when it comes to "brown".

The bug seem to be that a player that has exceeded cert limit cannot buy shares, even after selling down to allowed cert limit. I need to check if this is a general, non 18SJ specific bug, or if it is just 18SJ. It is possible that this has never come up in any other title as the situation is a bit rare.
