### ISSUE TITLE
[18QC] Rules Implementation -Looking for a developper

### ISSUE THREAD

**Issue by richardtempura** [tobymao/18xx#9161]
Here's a preview of the rules for 18QC.
I'm looking for someone to code it, so I can finalize testing.

I'll be happy to send the full rules, with all graphic files.

 18QC has one major wrinkle: the MLW.

The MLW (Montreal Locomotive Works) is a Private Company that has 10 shares.
This Private produces the Trains and decides on the price for them.
Depending on the relative amount that it produces, compared to demand, its share value will fluctuate.
When no trains are bought in an OR, the price for the available trains will drop (following the current phase chart)

Another wrinkle: the market. It's linear but with slots for each price value. So if a new company enters a price point, those already there will move up, pushed by the new ones.

8 companies have 40-20-20-20% shares

5 companies have 20-10-10-10-10-10-10-10-10% shares.

Not all companies will be in the game; the unused ones are removed from the game.

Full/Half/non Dividends.

The MLW can do ONE refinancing per game.

The MLW can go into bankruptcy, if it cannot produce any trains (because of lack of unds). Then it is removed and only 2 trains per type are produced.

**Comment by tobymao** [comment]
please find a dev on slack or through another avenue
