### ISSUE TITLE
[1846] Mail contract / 3/5 Bug?

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#917]
Running a 3/5 with the mail contract E-W there was a persistent issue with the run being recorded/calculated wrong.  

Worse, the display on different players' screens was different at the same time -- see attached images.  

Definitely the run shown was incorrect, I'm not sure if we missed other occurances of runs being miscalculated.  

JSON at https://gist.github.com/TheExcalabur/26cb097aae63e970dd430a5af069fa9d

![](https://cdn.discordapp.com/attachments/381107547785920512/726869360299212870/unknown.png)

![](https://cdn.discordapp.com/attachments/381107547785920512/726869474107457597/Screenshot_2020-06-28_at_11.39.05_AM.png)

**Comment by benjaminxscott** [comment]
Just to note that I had encountered this in game `2880`, and in that case undo'ing and re-choosing the routes seemed to fix it
(however I was in the game mentioned above and those actions didn't fix in this case)
