### ISSUE TITLE
[18USA] Switch and signal (P19) not billing coal next to skipped city

### ISSUE THREAD

**Issue by ojuang** [tobymao/18xx#9176]
https://18xx.games/game/119708

https://18xx.games/game/119708?action=1341

https://gist.github.com/ojuang/f66968c6ffe650f5cd5007d33a28aada

**How to Reproduce the Bug?**
attach switcher to train (3), click route including a hex with city full of tokens and a hex with a coal.

What steps cause the unexpected behavior?
- OR 4.1, running trains for ATSF
- ATSF has P19 allowing it to treat a city hex as empty track.
- Revenue was was 170 (did not include the coal on hex D26)

Please include screenshots (you can drag and drop or upload them into this issue)
<img width="1269" alt="Screenshot 2023-05-11 at 3 49 55 PM" src="https://github.com/tobymao/18xx/assets/30451059/17a24b2a-f5b5-437e-be74-d6d17770e6e1">
<img width="335" alt="Screenshot 2023-05-11 at 3 49 44 PM" src="https://github.com/tobymao/18xx/assets/30451059/235cae76-3aa3-4069-9408-e1006a432f3e">

**Comment by crericha** [comment]
Example game no longer exists. If the issue comes up again, please file another issue.
