### ISSUE TITLE
1861/67: add proper consent for multiplayer mergers

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#9177]
In 1861 & 67, if a player wishes to merge his/her minor with a minor owned by another player, the program just lets it happen - but the rules stipulate that both players must consent to such a merger. In practice, either the players must agree (via chat, for example) beforehand, or the target owner has to undo the action if they don't consent. It's not something which happens very often, but it caused some confusion in a recent game of 67.

My suggestion is to add a step into the program to ask the target player(s) consent before proceeding with such a merger.

**Comment by ianwilson156** [comment]
Mmm. In the latest case, the player became confused and clicked 'confirm' without gaining my consent. Given that (almost) everything else on 18xx.games enforces the rules strictly, it seems counter-intuitive to suddenly be given an option to cheat!

Bearing in mind that many players' command of English is far from perfect, perhaps the wording of the confirmation question could be simpler? e.g. "Does Dave agree to this action?" with a YES button. Or maybe add a bit of rules explanation: "Dave has to give consent to this action...."

**Comment by tobymao** [comment]
working as intended. 18xx.games is not intended for high level competitive play. that’s why there’s master mode which lets others make moves for yoy
