### ISSUE TITLE
[18Mag] train discount does not seem to apply correctly

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#9183]
https://18xx.games/game/121089?action=261

Company #2 has 70 forints, and the 2s cost 80 forints. ceb's "supporter card" KK is expected to provide a 10 forint discount. It is not apparent to us how to receive the discount. Clicking the box next to "Abilities" does nothing.

**Comment by roseundy** [comment]
@bena can you please update the wiki with the optional rules you implemented?
