### ISSUE TITLE
[18NY] Can lay illegal tile into impassable terrain edge

### ISSUE THREAD

**Issue by zachcd** [tobymao/18xx#9189]
**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/119017`

`https://18xx.games/game/119017?action=572`

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

During an Operating Round where a company has access to a tile that borders impassable terrain, upgrade a tile into green that adds additional track pointing into said impassable terrain.

![image](https://github.com/tobymao/18xx/assets/6234996/6866020d-88bb-4237-88f3-79fb1be4c800)

**Comment by philcampeau** [comment]
Code for hex I21 didn't list border 5 as impassable.
