### ISSUE TITLE
Paris not working correctly in '36jr

### ISSUE THREAD

**Issue by TheExcalabur** [tobymao/18xx#919]
The nord can neither run a 2T paris-lille-charleroi nor paris-lille.  
![image](https://user-images.githubusercontent.com/13547728/85957336-6506fd80-b984-11ea-84ca-3ed57f22abdd.png)
![image](https://user-images.githubusercontent.com/13547728/85957343-6df7cf00-b984-11ea-8a7f-0e8cd991ec3f.png)

Data: https://gist.github.com/TheExcalabur/2188c1bdd6db1442b6a86c77371f588b

**Comment by tobymao** [comment]
@jenf

**Comment by jenf** [comment]
Correct behaviour

 Such
a run must include at least two other scoring locations (e.g., a run from Lille to Paris is not legal) and thus requires at
least a 3 train. A train may include both an Off-Map Location and a Paris/Port Location in its run, one at each end.
