### ISSUE TITLE
Add an option to declare winner when ending a game manually

### ISSUE THREAD

**Issue by petersoncr1** [tobymao/18xx#9191]
**What's your idea?**
Allow the optional option for participants to select a winner when manually ending a game early, allowing the game results to be recorded on the players profile and affect the players elo. I find that a large percentage of live games either end early/ could end early due to a run away winner. Sometimes players want to play out games for the sole purpose of improving their elo.  This enhancement would allow more games to be ended early when a clear winner is found if the group agrees. 

I  am not 100% sure how elo is calculated so I and unsure how you would weight a called win to a finished win.

Suggestions
-Don't allow master mode of the vote 
-Optional
-Requires 100% acceptance from participants
-Maybe have a End Game: Draw button under tools and an End Game Winner determined button

**Comment by tobymao** [comment]
all of these are too complicated. i don't really see this being done. if there ever is a system, it'd have to be master moded, creating a system of 100% acceptance is too complicated, there's no existing framework for that kind of functionality on the site.

so i'm open to someone implementing a master mode version of this, but going to close this for now
