### ISSUE TITLE
[18MS] Not being able to get apply the Mobile and Ohio private company ability

### ISSUE THREAD

**Issue by Velgarath** [tobymao/18xx#9192]
Hi!
I am not being able to apply the discount, There is a special button that you can click before the train purchase, but the discount is not applied in the purchase
![pic](https://github.com/tobymao/18xx/assets/134040689/4b7c002a-b73b-48ba-aa87-03ca6a51ea3a)

Just in case you need it, I experienced the problem in game 123063
Thanks

**Comment by michaeljb** [comment]
* https://18xx.games/game/123063?action=74
* [gist](https://gist.github.com/michaeljb/ceae160d1042ea41a39d6125046f6a16)

**Comment by JH445** [comment]
Experiencing the same issue in my current 18MS game (https://18xx.games/game/135267). I'm trying to buy a 4+ train, but there doesn't seem to be an option to apply the private company's discount.
![18ms-clip](https://github.com/tobymao/18xx/assets/11559050/96a05b9a-fb46-498e-b07d-17474bc8c695)

**Comment by Yuki-yao** [comment]
triggered same bug in [gist](https://gist.github.com/Yuki-yao/967d6d5669c1925554e73a37faf09f79)

**Comment by jtamplin** [comment]
This impacted https://18xx.games/game/145138 - at 12:35 in OR 2/10, FR tried to use the discount on a 4+ train.

**Comment by saccenti** [comment]
This bug is still present as of January 2024. Here's an example:

https://18xx.games/game/150322?action=59
