### ISSUE TITLE
[18 Mag] Illegal action: nil cannot be coerced into Integer

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#9198]
![18xx sup](https://github.com/tobymao/18xx/assets/64490299/0660a46f-091d-4d84-a5a4-223eb64a088d)
server is rejecting submitted value

`Illegal action: nil cannot be coerced into Integer`

https://18xx.games/game/123256

**Comment by benjaminxscott** [comment]
Doesn't repro on hotseat, may be a server-side mismatch?

Is the game still broken?

related? https://github.com/tobymao/18xx/pull/9055#issuecomment-1486164536

**Comment by hast18xx** [comment]
Hi Benjamin,
yes, on hotseat it's working, on the server  still rejecting.
What can we do?
 
mit freundlichen Grüßen
 
Harald Stieling

**Comment by benjaminxscott** [comment]
We'd have to fix the bug and deploy the fix in order for game to continue, I don't personally know how to fix it fwiw

**Comment by hast18xx** [comment]
Hi,
I am going to reproduce the issue by  a new game and  replaying the moves.
I will let you know soon how it works
 
mit freundlichen Grüßen
 
Harald Stieling

**Comment by hast18xx** [comment]
Hi Benjamin,
I am able to reproduce the error.
 
So I have setup a third game which you and/or other engineers can join, if you like.
Then I will enter the moves again, until the point it fails
 
https://18xx.games/game/124237
 
let me know how to proceed
 
mit freundlichen Grüßen
 
Harald Stieling

**Comment by philcampeau** [comment]
Second example of this issue reported in issue #9313

**Comment by Lopside1** [comment]
https://18xx.games/game/144342 if it helps this is still an issue with this game

**Comment by philcampeau** [comment]
I've just run some tests and it looks like this issue has been resolved. I'm unable to reproduce the error when importing these games and running them (not in hotseat mode) .

There must have been an update that fixed it, and this report was never closed.
