### ISSUE TITLE
1880 Sell Shares Problem

### ISSUE THREAD

**Issue by latindog** [tobymao/18xx#9201]
https://18xx.games/game/120160

I was playing recently on 18xx.games in the game listed above and wanted to sell my 7 shares of a company because I intended to drop the company on another player who had 30% of the shares. The buttons to sell only offered me the ability to sell 1,2,3,4 or 5 shares. When I click to sell 5, I am then able to take another action and sell the other two shares (which I did) but, of course, I am selling the final two shares at a lower price. The issue is why I was only offered buttons to sell up to 5 shares in a game where it should have been possible to sell all 7 shares at once.

**Comment by michaeljb** [comment]
Dup of #9185, will be fixed when #9188 is deployed
