### ISSUE TITLE
[18CO] - "Must have route to access existing track" on obviously valid track lay

### ISSUE THREAD

**Issue by Breich90** [tobymao/18xx#9203]
https://gist.github.com/Breich90/9d0a17adf91f6430742ba1f61e80f35f

MP game ID 124203

Exact game-state where CBQ is unable to lay in F14 w/ valid upgrade to brown `#43`

CBQ was started after phase 5, where reservations were vacated, but the token slot was available in `B26`.  This same error occurred on CBQ's first OR, where it was unable to upgrade either yellow tile in `B24` or `C25` to valid green tile placements.  

Feel free to master mode the game, we called it anyways

**Comment by dlpierce** [comment]
@Breich90 18CO has more restrictive track laying rules than usual:

> Corporations must be able to 'see' existing track on a plain track tile in order to connect to it. This prevents corporations from branching into a line that they cannot currently access. Note that corporations may upgrade a tile to create a "bridge" that does not connect to existing track, and may always upgrade cities, towns, and villages.

**Comment by Breich90** [comment]
Oh wow, interesting.  That seems overtly restrictive/different, but so is companies owning shares in companies.
