### ISSUE TITLE
Crash when starting dev environment

### ISSUE THREAD

**Issue by labria** [tobymao/18xx#9204]
I'm trying to run the code locally to try contributing, but the app crashed after compiling assets with the following error (when running `make`):
```
18xx-rack-1   | Compiling engine/game/g_rolling_stock_stars/game.rb - 0.342431
18xx-rack-1   | terminate called after throwing an instance of 'std::bad_alloc'
18xx-rack-1   |   what():  std::bad_alloc
18xx-rack-1   | E, [2023-05-26T12:55:07.907157 #15] ERROR -- : reaped #<Process::Status: pid 26 SIGABRT (signal 6)> worker=0
18xx-rack-1   | I, [2023-05-26T12:55:08.034006 #43]  INFO -- : worker=0 ready
```
I'm on a M1 mac, but I followed all the related instruction.
Any ideas what might be causing this?

**Comment by crericha** [comment]
Bad alloc likely means the container ran out of memory. Try increasing how
much ram docker can use.
