### ISSUE TITLE
[18USA] Player winning auction for company goes negative cash instead of using privates to fund company

### ISSUE THREAD

**Issue by ojuang** [tobymao/18xx#9205]
https://18xx.games/game/119875

https://18xx.games/game/119875?action=219

https://gist.github.com/ojuang/5fd9bfa6191eaa4b04782ddfa402c5f3

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
- Stock Round 1, player WaltzTangoFoxtrot starts auction for TP at 118
- everyone else passes and WaltzTangoFoxtrot wins bid
- no option of which privates to use to fund is given, instead 118 is deducted from cash and they have -113
- expected behavior is that player WaltzTangoFoxtrot chooses which of their 4 privates P28, P21, P10, P6 + $5 cash is used to fund.

(tried undo/redo in hotseat mode there is still no choice)
<img width="324" alt="Screenshot 2023-05-26 at 11 16 17 AM" src="https://github.com/tobymao/18xx/assets/30451059/6be22610-60e4-4111-9f8b-79c6d2a18b2e">
<img width="326" alt="Screenshot 2023-05-26 at 11 16 26 AM" src="https://github.com/tobymao/18xx/assets/30451059/709e9e2a-924b-4335-8c2a-ca410e9d172d">
<img width="612" alt="Screenshot 2023-05-25 at 9 22 17 PM" src="https://github.com/tobymao/18xx/assets/30451059/903a7157-38dd-42d5-9ce8-bb84dcdedbea">

**Comment by crericha** [comment]
$118 was an illegal bid because there is no company + cash combination that WaltzTangoFoxtrot could use to pay that amount.

**Comment by crericha** [comment]
You can continue the game by going back to the initial bid and instead making a legal bid amount.

**Comment by ojuang** [comment]
118 was not illegal, WaltzTangoFoxtrot should be able to use privates to overpay $120 or more, and then 0 is in the Treasury of the floated company

**Comment by crericha** [comment]
@ojuang thanks for clarifying. I was assuming 1817 rules.

**Comment by crericha** [comment]
To make sure I fully understand. If a player wins with a bid of $100 and they have $300 worth of privates, they can put all $300 into the company and then the company receives $0  in cash?

**Comment by ojuang** [comment]
By my reading of the rules, yes they could put in $300 of privates for a winning $100 bid, and have $0 cash in company treasury (it is legal but probably not a good strategy). 18USA section 11.6, point 7:
7. The company must now be funded. The president first decides which of their private companies, if any, they will give to the new company. The player then gives the bank an amount equal to the winning bid minus the private companies contributed. The bank then gives the company treasury twice the share price minus the combined face value of all private companies given. If this amount is negative, the starting treasury is $0.
[ this differs from 1817 rules section 5.5 New IPO, where it says "The player must contribute equity (cash + private company values) that exactly total the winning bid." ]
