### ISSUE TITLE
Map moves around on screen as one clicks stops on a route

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#921]
On the Game tab as the the text that describes the route changes it appears to push the map around.

See the two photos below - where the map is shifted - this is between one click on the map.  This can make clicking along your route pretty difficult as the map hops around the screen between clicks.  It can also make the map jump down off screen (which you then scroll down to) and another click later it might hop back up.

![screen1](https://user-images.githubusercontent.com/1738619/85958228-00d34200-b962-11ea-94ba-820229fa0eee.png)
![screen2](https://user-images.githubusercontent.com/1738619/85958230-016bd880-b962-11ea-8aa9-9c24b11087f0.png)

**Comment by tobymao** [comment]
@yzemaze

**Comment by yzemaze** [comment]
Known issue. Texts are too long, especially for invalid routes. The submit button is the worst offender and the root of the issue presented here. So you might want to avoid invalid routes ;)
It will be fixed in coming weeks.

**Comment by eheiden** [comment]
Cool, just wanted to make an official issue.  I think this interface (having the map and shares share screen real estate) is a big improvement btw - thanks for your work @yzemaze!
