### ISSUE TITLE
Rolling Stock v1 Floating and Issuing 4 Shares

### ISSUE THREAD

**Issue by trumpsc** [tobymao/18xx#9212]
Daniel18xx wanted to use RU ($85) to par at 28.  28x3 = 84, which wouldn't be enough to float the company, so there should have been an option to par at 28 and issue 4 shares.  This is a very specific Rolling Stock v1 par a high value private company at a low par price issue.

https://18xx.games/game/121617?action=475

The specific action and situation is above.

This was previously addressed in #https://github.com/tobymao/18xx/issues/8522 where the issue was fixed when trying to par a new company and receive 3 shares (thanks!).  I didn't forsee that there could be a case where a company could be parred and have 4 shares issued, but there you have it.

**Comment by roseundy** [comment]
Well, it should be easier to fix now that I refactored the code for the prior bug.
