### ISSUE TITLE
[1822NRS] Game pinned and broken. Need manual closing

### ISSUE THREAD

**Issue by JokinGonzalez** [tobymao/18xx#9216]
Our game [118350](https://18xx.games/game/118350?action=908) got pinned to version **cec86951a**, but it crashed today, not allowing us to end the game nor close it.
Please, can an admin close/purge/finish it? Thank you 🙂

**Comment by michaeljb** [comment]
The game has been archived, It was likely broken by #9196 -- sorry about that!
