### ISSUE TITLE
[1817] Payment displayed with decimal value when liquidating short at $0

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#9218]
See https://18xx.games/game/112604?action=1492

The relevant portion of the log reads:

> [13:17] -- R enters liquidation (it has no president) --
> [13:17] jlbrooks sells -1 shares of A&S and receives $-55
> **[13:17] jlbrooks sells -1 shares of Belt and receives $-0.0**
> [13:17] Market closes 1 shorts for Belt
> 

Note that the highlighted line states a payment of "-0.0" when the typical format would be "-0", for selling -1 shares at $0.

**Comment by crericha** [comment]
This is an opal bug.
