### ISSUE TITLE
1822PNW Pullman problem

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#9220]
Just finished a game of 1822PNW.  One of my companies had a Pullman.  It worked properly - towns not counting against train limit - with shorter trains (e.g. 3-train), but stopped working with longer trains (e.g. 6-train) - counted towns against train count even though the Pullman was attached.

**Comment by michaeljb** [comment]
Closing this for now.

No game ID or link provided, I cannot find a user with the name `pzieske` and even if I could at this point the affected game would have been auto-archived anyway.

We can reopen if this reoccurs and an example game can be captured.
