### ISSUE TITLE
1822PNW, NP auto skips buy minor and issue shares in OR 6.1

### ISSUE THREAD

**Issue by devslashlol** [tobymao/18xx#9229]
https://18xx.games/game/122906

NP should have had the option to acquire a minor (had path, funds, and was not first OR). This phase was auto skipped. Also, issue shares was auto skipped too. No reason for it to have done either thing.

**Comment by outsidePasser** [comment]
When I just looked, OR 6.2 had just started, so I'm assuming you are talking about OR 6.1.

NP was formed during merger round 5.2.  OR 6.1 was the first OR for the NP.  NP should not have those options in OR 6.1.

**Comment by devslashlol** [comment]
Thank you!
