### ISSUE TITLE
I cannot login via main page, though I'm logged in my games

### ISSUE THREAD

**Issue by lemonhopogatari** [tobymao/18xx#923]
I am currently playing 18Chesapeake and it's going smoothly. However, when I return to the main page, I'm signed out, cannot sign in, , there's no chat and the buttons do not do anything. I can go to the sign in page but the buttons there do nothing when I click them. 

However, I'm still signed in if I return to the game or if I click on settings. It's only on the main page and sign in page that I'm seeing these issues.

![Capture](https://user-images.githubusercontent.com/59164521/85960547-3137d200-b99c-11ea-9c9a-2d2dc0634dd0.JPG)

**Comment by tobymao** [comment]
clear your local storage / cache

in the web console, do

localStorage.clear()

**Comment by tobymao** [comment]
let me know if that fixes the issue
