### ISSUE TITLE
[all?] Able to create games with invalid player count

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#9233]
Repro'd on multiplayer/hotseat games on live server as well as local dev server w/ latest master

## Issue

It looks like users are able to create games with invalid player counts, such as one-player or two-player (if the game isn't supported for 2P) or negative player counts

Such games can't be started / loaded, generally they fail with an error when the bogus player count is referenced as it seems to be set to `nil` in such cases

e.g. In '46, this allows 2-player games to be created without the optional 2P rules, so the game fails to start on a `Player count not supported` error

For a multiplayer game, set the `max_player` to the desired bogus value, which will set `min_players` to that value as well

For a hotseat game, set number of players to the bogus value

## Possible Approach

Perhaps we can modify the guard checks in [create_game.rb](https://github.com/tobymao/18xx/blob/97a703f3e5914285473de9309fed1889dd944a20/assets/app/view/create_game.rb#L485)

**Comment by michaeljb** [comment]
huh, I did mess with game creation stuff in https://github.com/tobymao/18xx/pull/9206/files, maybe that broke it?

**Comment by benjaminxscott** [comment]
I *think* those changes look OK, the issue seems to be w/ this line 

Before this line, the `min_players` is correct, after it `min_players` is incorrect
(e.g. for a multiplayer game, set `max_players` to 2 and then to 1, which will set `min_players` to 1)

https://github.com/tobymao/18xx/blob/97a703f3e5914285473de9309fed1889dd944a20/assets/app/view/create_game.rb#L513

For hotseat games, you can set players to 1 directly and the checks don't seem to work at all
