### ISSUE TITLE
[1862] Cannot lay track

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#9237]
'B' trains have been bought so yellow->green upgrades are allowed, but WNR cannot upgrade either hex it is connected to in OR2.1

https://18xx.games/game/124398

**Comment by ianwilson156** [comment]
If I continue in hotseat mode, the next company L&H can't even lay yellow track either!

**Comment by michaeljb** [comment]
I rolled back the change that broke this, so your game should be unbroken now. I'm working on remaking that change in a way that won't break 1862. Thanks for reporting!

**Comment by ianwilson156** [comment]
Thanks for fixing it!
