### ISSUE TITLE
1822MRS

### ISSUE THREAD

**Issue by Sleipmaersk** [tobymao/18xx#9238]
We're sorry this game cannot be continued due to combo_entities: undefined method `combo_entities' for #<Engine::Action::LayTile:0xce04 @entity=<Engine::Company: P12> @created_at=1685777028 @auto_actions=[] @hex=<Engine::Hex: M42, tile: 5> @tile=<Engine::Tile: 405, hex: > @rotation=3 @id=397 @_h={"type"=>"lay_tile", "entity"=>"P12", "entity_type"=>"company", "id"=>397, "created_at"=>1685777028, "hex"=>"M42", "tile"=>"405-0", "rotation"=>3}>
Broken action: { "type": "lay_tile", "entity": "P12", "entity_type": "company", "id": 397, "created_at": 1685777028, "hex": "M42", "tile": "405-0", "rotation": 3 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822,%22needs%20triage%22) and include this link (https://18xx.games/game/123822?action=396)

**Comment by michaeljb** [comment]
I rolled back the change that added `combo_entities`, so this game should be unbroken now.  Working on remaking that change in a way that won't cause this breakage. Thanks for reporting!
