### ISSUE TITLE
[1856] Cannot lay Tile

### ISSUE THREAD

**Issue by BluestBlood** [tobymao/18xx#9241]
**What's your Game ID?**

https://18xx.games/game/123461

**How to Reproduce the Bug?**

During OR 6.1, GW is unable to lay or upgrade track.  Clicking on the hexes does not bring up the popups of available tiles to place, therefore, no tiles can be placed.

-->

**Which Browser / Platform?**

Chrome 113.0.5672.129

**Comment by michaeljb** [comment]
I rolled back the change that broke this, so your game should be unbroken now. Working on remaking that change in a way that won't break 1856. Thanks for reporting!
