### ISSUE TITLE
1848 - Companies cannot buy trains from bank after cross buying trains from other companies

### ISSUE THREAD

**Issue by DrPooter** [tobymao/18xx#9244]
Game ID: https://18xx.games/game/125026

Hello! A legit thank you for the time you all put in on the site.

This is a repeatable bug where companies cannot buy a train from available trains after buying a train across from another company.

It typically happens right as the permanent trains are about to break and companies are doing the normal shuffle/buy.

Cheers!

**Comment by benjaminxscott** [comment]
This is working as intended based on rules 
(the "last thing" that a company can do on their turn is buy across from another company, so they can't buy from Depot after that)

https://github.com/tobymao/18xx/issues/9145

**Comment by DrPooter** [comment]
We learn something new everyday, even the things we were told before. ;) Thank you again.
