### ISSUE TITLE
[1822PNW] Undefined combo_entities

### ISSUE THREAD

**Issue by gloinul** [tobymao/18xx#9246]
Game reports above log window:

We're sorry this game cannot be continued due to combo_entities: undefined method `combo_entities' for #<Engine::Action::LayTile:0x13ca0 @entity=<Engine::Company: P7> @created_at=1685354192 @auto_actions=[] @hex=<Engine::Hex: G8, tile: 4> @tile=<Engine::Tile: 82, hex: > @rotation=0 @id=691 @_h={"type"=>"lay_tile", "entity"=>"P7", "entity_type"=>"company", "id"=>691, "created_at"=>1685354192, "hex"=>"G8", "tile"=>"82-0", "rotation"=>0}>
Broken action: { "type": "lay_tile", "entity": "P7", "entity_type": "company", "id": 691, "created_at": 1685354192, "hex": "G8", "tile": "82-0", "rotation": 0 }

**What's your Game ID?**

https://18xx.games/game/121256?action=690

-->

**How to Reproduce the Bug?**

Don't know.

**Which Browser / Platform?**

Name 	Firefox
Version 	113.0.2
Build ID 	20230522134052

**Comment by michaeljb** [comment]
Hi @gloinul, your game loads fine in my browser, does it work if you hard refresh (ctrl+shift+R or command+shift+R on macOS)?

**Comment by gloinul** [comment]
Yes, appears to be a temporary glitch, can't get the error to show up on either of my units now. It showed up on both Mobile Firefox on iOS and on Firefox on Win10.

**Comment by michaeljb** [comment]
Thanks, I just rolled out a change for combo_entities in the 1822 games, if refreshing solved it then it’s working as expected and shouldn’t happen again 🙂

**Comment by gloinul** [comment]
Thanks, for your work!
