### ISSUE TITLE
[1836Jr56 ] Can't place tile

### ISSUE THREAD

**Issue by dolfyner** [tobymao/18xx#9256]
https://18xx.games/game/125585 

When I clone the game I can place a tile and continue. But in the actual game I get an error message (see screenshot) when laying a tile or passing

![Screenshot_20230611_125100_Chrome](https://github.com/tobymao/18xx/assets/72355011/7a16c2df-7408-4be0-b901-bcae4e0b2a12)

Kind regards
Michal

**Comment by dolfyner** [comment]
Yes tried on my computer as well (play on my phone normally on Chrome) on Chrome and Edge with the same result same result unfortunately.
Something else weird:
2023-06-12 --
[16:37] LeeGamer: Something definitely hosed. I look at the game, and I can place track for HSM despite not owning it
[16:42] Michal(UTC): @LeeGamer Ok! But did it work? Or did you get an error message too?
[19:12] LeeGamer: I also got some weird error message

**Comment by ventusignis** [comment]
It looks like there was a discrepancy between the server and browser (hence why cloning the game worked fine); since the game is ended I'm going to close this for now
