### ISSUE TITLE
Unlimited basic tiles

### ISSUE THREAD

**Issue by sergiomoreiraf** [tobymao/18xx#9259]
**What's your idea?**

Make a global variant of unlimited basic yellow tiles, for all games.

It really is very annoying to not be able to build from point A to point B because there is no basic straight line or the simplest curve.

I understand this limitation for the printed version, but the online version can fix this pain.

This is not an official variant, for obvious reason, but I think this is a welcome extra feature to add, unique to online.

**Comment by tobymao** [comment]
we don't implement unofficial variants
