### ISSUE TITLE
[1836jr] falsely calculated liquidity.

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#926]
I had 2 shares of the Nord@100 each and one unparred GCL share. The liquidity was showing that I had 67 franks more than I had according to my own calculation. I think the game was somehow interpreting the GCL share as liquidity.

![image](https://user-images.githubusercontent.com/64785010/85984406-d204ac80-b9f1-11ea-8a29-c0ebb08992be.png)

{
  "status": "active",
  "actions": [
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 1,
      "message": "Oki, perhaps this time we'll know more. xD"
    },
    {
      "type": "message",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 2,
      "message": "same. ^^"
    },
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 3,
      "message": "A note, the port/Paris tiles are sorta extra locations. They count as stop, but need 2 more stops. Also the revenue is value times your personal tokens you have on the route."
    },
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 4,
      "message": "Ok, I'll let you scheme. Gonna take a shower and clear my head a little. :P"
    },
    {
      "type": "bid",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 5,
      "company": "CFL",
      "price": 165
    },
    {
      "type": "bid",
      "entity": "Navor",
      "entity_type": "player",
      "id": 6,
      "company": "GCB",
      "price": 115
    },
    {
      "type": "message",
      "entity": "Navor",
      "entity_type": "player",
      "id": 7,
      "message": "thanks!"
    },
    {
      "type": "bid",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 8,
      "company": "CFL",
      "price": 170
    },
    {
      "type": "bid",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 9,
      "company": "CFLV",
      "price": 225
    },
    {
      "type": "pass",
      "entity": "Navor",
      "entity_type": "player",
      "id": 10
    },
    {
      "type": "bid",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 11,
      "company": "CdH",
      "price": 75
    },
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 12,
      "message": "Phew... 1870 played. Ugh... too long and vast."
    },
    {
      "type": "bid",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 13,
      "company": "ACC",
      "price": 20
    },
    {
      "type": "pass",
      "entity": "Navor",
      "entity_type": "player",
      "id": 14
    },
    {
      "type": "bid",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 15,
      "company": "E-SF",
      "price": 40
    },
    {
      "type": "message",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 16,
      "message": "sorry, busy day at work"
    },
    {
      "type": "message",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 17,
      "message": "also on sunday and monday. :S dont know how able I am to play at work. ;D"
    },
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 18,
      "message": "Don't worry. You're still faster than most players here. xD"
    },
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 19,
      "message": "Hmm, I'm not sure I want the private, but I think it's still too cheap. "
    },
    {
      "type": "bid",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 20,
      "company": "CFL",
      "price": 175
    },
    {
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "par",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 22,
      "corporation": "Nord",
      "share_price": "100,0,6"
    },
    {
      "type": "pass",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "par",
      "entity": "Navor",
      "entity_type": "player",
      "id": 24,
      "corporation": "B",
      "share_price": "76,3,6"
    },
    {
      "type": "par",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 25,
      "corporation": "HSM",
      "share_price": "76,3,6"
    },
    {
      "type": "message",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 26,
      "message": "HSM for me onmy turns thanks, until float"
    },
    {
      "type": "buy_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 27,
      "shares": [
        "HSM_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Navor",
      "entity_type": "player",
      "id": 28,
      "shares": [
        "B_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 29,
      "shares": [
        "HSM_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 30,
      "shares": [
        "B_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Navor",
      "entity_type": "player",
      "id": 31,
      "shares": [
        "B_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 32,
      "shares": [
        "HSM_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Navor",
      "entity_type": "player",
      "id": 33,
      "shares": [
        "B_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 34,
      "shares": [
        "HSM_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Navor",
      "entity_type": "player",
      "id": 35,
      "shares": [
        "Nord_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 36,
      "shares": [
        "B_5"
      ]
    },
    {
      "type": "lay_tile",
      "entity": "B",
      "entity_type": "corporation",
      "id": 37,
      "hex": "H4",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation",
      "id": 38
    },
    {
      "type": "buy_train",
      "entity": "B",
      "entity_type": "corporation",
      "id": 39,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 40,
      "hex": "E7",
      "tile": "57-1",
      "rotation": 2
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 41
    },
    {
      "type": "buy_train",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 42,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 43
    },
    {
      "type": "message",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 44,
      "message": "Ill pass"
    },
    {
      "type": "pass",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "pass",
      "entity": "Navor",
      "entity_type": "player",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 47
    },
    {
      "id": 48,
      "hex": "H2",
      "tile": "58-0",
      "type": "lay_tile",
      "entity": "B",
      "rotation": 2,
      "entity_type": "corporation"
    },
    {
      "id": 49,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "type": "buy_shares",
      "entity": "GCB",
      "entity_type": "company",
      "id": 50,
      "shares": [
        "B_6"
      ]
    },
    {
      "id": 51,
      "hex": "G7",
      "tile": "57-2",
      "type": "lay_tile",
      "entity": "B",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 52,
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 53,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 54,
      "city": "57-2-0",
      "slot": 0,
      "type": "place_token",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 55,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 56,
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "B",
      "entity_type": "corporation",
      "id": 57,
      "hex": "G7",
      "tile": "57-2",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation",
      "id": 58
    },
    {
      "type": "run_routes",
      "entity": "B",
      "entity_type": "corporation",
      "id": 59,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "H6",
              "H4"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B",
      "entity_type": "corporation",
      "id": 60,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "B",
      "entity_type": "corporation",
      "id": 61,
      "train": "2-2",
      "price": 80
    },
    {
      "id": 62,
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation"
    },
    {
      "id": 63,
      "type": "undo",
      "entity": "HSM",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "B",
      "entity_type": "corporation",
      "id": 64
    },
    {
      "type": "lay_tile",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 65,
      "hex": "F8",
      "tile": "8-0",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "run_routes",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 67,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "D6",
              "E7"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 68,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 69,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "HSM",
      "entity_type": "corporation",
      "id": 70
    },
    {
      "type": "sell_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 71,
      "shares": [
        "B_2"
      ],
      "percent": 10
    },
    {
      "type": "sell_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 72,
      "shares": [
        "HSM_1"
      ],
      "percent": 10
    },
    {
      "type": "buy_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 73,
      "shares": [
        "Nord_2"
      ]
    },
    {
      "type": "pass",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "buy_shares",
      "entity": "Navor",
      "entity_type": "player",
      "id": 75,
      "shares": [
        "HSM_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Navor",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "message",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 77,
      "message": "You can buy Nord on my turns"
    },
    {
      "type": "buy_shares",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 78,
      "shares": [
        "Nord_3"
      ]
    },
    {
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 79
    },
    {
      "type": "buy_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 80,
      "shares": [
        "Nord_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 81
    },
    {
      "type": "message",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 82,
      "message": "Pass for me"
    },
    {
      "type": "pass",
      "entity": "Navor",
      "entity_type": "player",
      "id": 83
    },
    {
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 84
    },
    {
      "type": "buy_shares",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 85,
      "shares": [
        "Nord_5"
      ]
    },
    {
      "type": "pass",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 86
    },
    {
      "type": "pass",
      "entity": "Navor",
      "entity_type": "player",
      "id": 87
    },
    {
      "type": "pass",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 88
    },
    {
      "type": "pass",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 89
    },
    {
      "type": "lay_tile",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 90,
      "hex": "I5",
      "tile": "8-1",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 91,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 92,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "buy_company",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 93,
      "company": "CFL",
      "price": 320
    },
    {
      "type": "buy_company",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 94,
      "company": "ACC",
      "price": 40
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "undo",
      "entity": "B",
      "entity_type": "corporation",
      "id": 97
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 98
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 99
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 101
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 102
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 103
    },
    {
      "type": "undo",
      "entity": "Nord",
      "entity_type": "corporation",
      "id": 104
    },
    {
      "type": "undo",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 105
    },
    {
      "type": "undo",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 106
    },
    {
      "type": "undo",
      "entity": "Navor",
      "entity_type": "player",
      "id": 107
    },
    {
      "type": "undo",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 108
    },
    {
      "type": "undo",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 109
    },
    {
      "type": "undo",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 110
    },
    {
      "type": "undo",
      "entity": "Navor",
      "entity_type": "player",
      "id": 111
    },
    {
      "type": "undo",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 112
    },
    {
      "type": "undo",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 113
    },
    {
      "type": "undo",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 114
    },
    {
      "type": "undo",
      "entity": "willbeplaying",
      "entity_type": "player",
      "id": 115
    },
    {
      "type": "undo",
      "entity": "Navor",
      "entity_type": "player",
      "id": 116
    },
    {
      "type": "undo",
      "entity": "Navor",
      "entity_type": "player",
      "id": 117
    },
    {
      "type": "undo",
      "entity": "Azureth",
      "entity_type": "player",
      "id": 118
    }
  ],
  "id": "hs_jhjxmcwd_2894",
  "description": "Cloned from game 2894",
  "user": {
    "id": 0,
    "name": "You"
  },
  "players": [
    {
      "id": 175,
      "name": "Azureth"
    },
    {
      "id": 2225,
      "name": "Navor"
    },
    {
      "id": 949,
      "name": "willbeplaying"
    }
  ],
  "max_players": 3,
  "title": "1836Jr30",
  "settings": {
    "seed": 3.3517720556772715e+38
  },
  "turn": 3,
  "round": "Operating Round",
  "acting": [
    2225
  ],
  "result": {},
  "loaded": true,
  "created_at": "2020-06-29",
  "updated_at": 1593413615,
  "mode": "hotseat"
}

**Comment by Azuureth** [comment]
I mean, it kinda is 67F liquidity, IF I want to start GCL and IF I want to PAR it 67. 

So I can see the argument why it might be intended behaviour, but personally I was confused with it and the liquidity is not real liquidity if it's contained to one case.

**Comment by tobymao** [comment]
fixed
