### ISSUE TITLE
[18GB] Company uses GN power without closing it (rules infraction)

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#9262]
In a current game of GB, the LYR used the GN power to lay a token in York without closing the private. (It did not 'parachute' into York, so no fee needed to be paid.) This was in OR2.1
https://18xx.games/game/123733

The rules say (section 9):
P3: Great Northern (GN) Cost: £70 Income: £25/OR
The GN allows a company to lay the GN station token in York (I14) [9.2]. The GN owner may use this ability once per game, **after the GN has closed**, for any company which they control

**Comment by Tagoreler** [comment]
I believe there is a similar issue with the Maryport and Carlisle, which has a similar functionality: https://18xx.games/game/131120?action=86
