### ISSUE TITLE
[1822MRS] Continuous Hill Discount is applied to rough terrain, but shouldn't be

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#9268]
The Hill Discount seems to discount rough terrain, when it shouldn't. 
My assumptions are that tile I24 (green dome costing 40) is rough terrain and green domes costing 60 are hills.

**How to reproduce:**
In game: https://18xx.games/game/125682?action=389 LYR acquires the Hill Discount, chooses the continuous discount and lays H23 for the regular 40.
Afterwards, it can lay a tile on I24 for 20. However, this should be 40 as I24 is rough terrain and the continuous discount doesn't apply.

**Comment by philcampeau** [comment]
> My assumptions are that tile I24 (green dome costing 40) is rough terrain and green domes costing 60 are hills.

This assumption is wrong. All green domes are hills. Rough terrain looks like this:
![image](https://github.com/tobymao/18xx/assets/26125362/2216f865-06ce-49e7-9fea-9fb24feec62e)

Closing bug report.

**Comment by kepakiano** [comment]
Thanks for the reply! Then I'd like to file a different bug:
The Hill discount one time token cannot be used for rough terrain.
Assumption: Tile H23 is rough terrain.

Using the same link as above, acquire the Hill Discount, this time choose the token and try to use it. It won't let you lay track for free on H23.

**Comment by philcampeau** [comment]
Actually, I'm going to review the rules. My initial read may have been wrong. I'll get back to you later.

**Comment by kepakiano** [comment]
Seeing your pull request: So the implementation was actually correct, just the wording combined with the depiction of the terrain types was a little misleading :)

**Comment by philcampeau** [comment]
yeah. your initial report was actually  correct. I'm surprised  it took someone this long to notice the issue!

**Comment by kepakiano** [comment]
Ah, ok. So I24 actually is rough terrain, but tiles like G24 are "Large rivers"?

**Comment by philcampeau** [comment]
Yep. The image I included above is actually rivers, and the £40 hills are the rough terrain. I think the programmer used those icons to have the digital implementation look closer to the physical game board.
