### ISSUE TITLE
[1850] An error is displayed and the game cannot proceed.

### ISSUE THREAD

**Issue by hachi-18xx** [tobymao/18xx#9274]
https://18xx.games/game/120791

At the timing of whether to price protect immediately after bank broken,
No matter what I choose ( either protect or pass ), I get an error message and I can't advance the game any further.

Error message displayed
> The server did not accept this action due to: Illegal action: wrong number of arguments (given 2,expected 0)... refreshing.

**Which Browser / Platform?**

Happens in both Chrome and Edge.

**Comment by philcampeau** [comment]
This game is now pinned and the issue was likely fixed with one of the updates done over the last few months. Will close for now since no other errors of this type have been reported recently.
