### ISSUE TITLE
1822MX wrong tile offered when selecting a hex

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9276]
https://18xx.games/game/126032?action=264

The only legal placement for M12 when using the power of P11-SMB (Three Builder Cubes) is a builder cube. The greyed out unavailable tile 2 should not be visible.

<img width="386" alt="Screenshot 2023-06-20 at 20 04 42" src="https://github.com/tobymao/18xx/assets/8732435/e38213b8-d51a-4a1d-bc5c-a56598612c42">

Note that the problem doesn't occur if M12 is not using the builder cube from the P11.

<img width="457" alt="Screenshot 2023-06-20 at 20 07 58" src="https://github.com/tobymao/18xx/assets/8732435/64545ad6-e31c-4107-98b2-a0a9962c039e">

**Comment by michaeljb** [comment]
https://gist.github.com/michaeljb/ad5db18a1ddc9f7ebd3a6ed851111162
