### ISSUE TITLE
1822 PNW P20 Backroom Negotiations home token not on charter

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9277]
https://18xx.games/game/122061?action=621

The CPMS charter shows the home token at Spokane (F23). P20 Backroom Negotiations was used to move the home token to Bellingham (D11).
 
<img width="333" alt="Screenshot 2023-06-20 at 22 41 05" src="https://github.com/tobymao/18xx/assets/8732435/c279a751-80d6-4250-afc9-1eeb83413faf">

**Comment by michaeljb** [comment]
fixed by #10866
