### ISSUE TITLE
In 18Chesapeake when the player is at the limit of trains and do not have money to buy a train for depot the game jumps to next player without asking if I want to buy train for a company

### ISSUE THREAD

**Issue by Djeefther** [tobymao/18xx#928]
In 18Chesapeake (could be happing in other games as also) when the player is at the limit of trains and do not have money to buy a train for depot the game jumps to next player without asking if I want to buy train for a company

**Comment by Djeefther** [comment]
State of the game: https://gist.github.com/Djeefther/522b1a07af2164ced3fe886ab358bfd4

**Comment by tobymao** [comment]
@Djeefther what's the issue? you can't buy trains if you're tight

**Comment by Djeefther** [comment]
Exactly, after "payout" or "withhold" if I am at the limit of the trains the game just passes to next player without asking me if I want to buy a new train (and of course discard one)

**Comment by dfannius** [comment]
It is a rule of 18Chesapeake (and most 18xx games) that you are not allowed to buy a train if you are at the train limit.

**Comment by Djeefther** [comment]
Nice, bad understanding of the rules from my part.
