### ISSUE TITLE
1871 TOP auto buy until float broken

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9282]
https://18xx.games/game/126153?action=417

When choosing "until float"

<img width="638" alt="Screenshot 2023-06-27 at 07 19 14" src="https://github.com/tobymao/18xx/assets/8732435/9c8c14db-ccfb-4284-984f-04d670f3cab0">

you get this error

<img width="807" alt="Screenshot 2023-06-27 at 07 19 33" src="https://github.com/tobymao/18xx/assets/8732435/f371d118-d273-49e8-89ff-bee6f08b4823">

In this case, "until float" should buy the shares from the market.

**Comment by benjaminxscott** [comment]
Discussion on Slack -> not planned

**Comment by ChrisTheCat** [comment]
I did not see the discussion on Slack and can't find it in 18xxgames or 18xxgamedev channels. Can you provide a link to the conversation?

**Comment by ChrisTheCat** [comment]
Also, at a minimum, if the "Until float" is broken and will never be fixed, it should be removed from the form, leaving it broken and still available with wontfix isn't right.

**Comment by philcampeau** [comment]
It was discussed quite a while ago, probably lost to the slack archive at this point.

**Comment by ChrisTheCat** [comment]
Would it be possible to suppress that option button in the Auto orders for TOP?

**Comment by benjaminxscott** [comment]
I'll look into whether it's feasible to dynamically remove 'buy from ipo until float' as an option, since it's broken for all corps in this game (I typically would want to not present the user with that option if it's broken)
