### ISSUE TITLE
[18EU] can't merge minor while holding 60% of major

### ISSUE THREAD

**Issue by arcanor** [tobymao/18xx#9283]
**What's your Game ID?**

Id: 125117
https://18xx.games/game/125117

how to reproduce:
https://18xx.games/game/125117?action=412

If WCollins buys GSR (will then have 60%), next turn, can't merge Minor 13 (to get to 70%). The button to merge does not appear.

platform: windows 10 desktop
browser: Chrome Version 114.0.5735.134 (Official Build) (64-bit)

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
I'm 99% sure that the issue here is that there's a max ownership of 60% in the coding of the game, but you are supposed to be able to ignore that when exchanging minors, until the subsequent stock round.

I'll dig around and see what I can find.
