### ISSUE TITLE
[1856] -  Incorrect calculation of the number of certificates held

### ISSUE THREAD

**Issue by gugvib** [tobymao/18xx#9287]
**What's your Game ID?** 124953

**How to Reproduce the Bug?**
1856-There is an error in calculating the number of certificates when a player is the president of the CGR. The presidency certificate is considered as equal to 1, instead it should be considered as equal to 0.5.
If I'm not wrong!
Thanks.

**Which Browser / Platform?**

**Comment by ollybh** [comment]
It's not just the president's certificate that is being counted incorrectly, it is all CGR shares. In game [124953](https://18xx.games/game/124953?action=966) the CGR has formed as a 20-share company, but each 5% share and the 10% presidency is being counted as half a certificate. According to the Mayfair rules these should each be counted as a certificate.

This is allowing players to go over the (correct) certificate limit, so fixing this will need some games to be pinned.

**Comment by ollybh** [comment]
@philcampeau I had missed that section in the rules. I was looking at the 'Share and certificate limits' section on page 6, which says:

> For the public companies, a single certificate can represent 5%, 10% or 20% ownership. The president's certificate, whether 10% or 20%, is considered a double share, but counts as a single certificate.

The later section you've highlighted clarifies this (or, IMHO, contradicts it) and says that each share counts as half a certificate. So a 5% share is half a certificate, and the 10% presidency so one certificate. Which is what is currently being counted, so I think that this is not a bug after all.

**Comment by philcampeau** [comment]
This old thread on the 18xx.groups.io seems to confirm that the CGR presidency does count as a full certificate whether it is 10 or 20%. Bill Dixon was always fairly active on those threads when needed, I'm sure he would have jumped in if that ruling was incorrect.

https://groups.io/g/18xx/topic/40520773?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Acreated%2C1%2C1856+cgr+president%2C20%2C2%2C0%2C40520773%2Cct%253D1&ct=1
