### ISSUE TITLE
[1860] Re-float a bankrupted company in the same SR

### ISSUE THREAD

**Issue by zexine** [tobymao/18xx#9291]
(https://18xx.games/game/126044?action=504)

According to the rules:

"When a company becomes bankrupt, all the share
s in the company are returned to the IPO without compensation, and are available for sale,
starting with the director’s share. The company’s shares become available for purchase **at the start of the following stock round**"

If I understand the rules correctly, when a company bankrupts due to shares sold, then this company should not be available for floatation for the current SR. It should be available at the start of the next SR.

In the game mention above, a player manage to bankrupt NGStL the re-float it in the same SR.

**Comment by benjaminxscott** [comment]
Hmm I'm not sure I see that [in the rules](https://www.dropbox.com/s/usfbqtdjzx6ug8f/1860-rules.pdf) (`bankruptcy` section)

```
When a company becomes bankrupt, [...] the company’s shares become available for purchase at the start of the following stock round
```

```
If the bankruptcy occurs in the middle of a stock round, the stock round ends immediately. Play now continues with a new stock round
```

My reading is that if bankruptcy occurs in an OR, it can be refloated in the next SR

If it occurs in an SR, it triggers a new SR where it can be refloated
(the code implements a new SR)

**Comment by zexine** [comment]
I see, should have finished reading the whole section.
