### ISSUE TITLE
[1822+] bids not showing up

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9295]
Bid have been placed but are not visible 

https://18xx.games/game/127203

**Comment by benjaminxscott** [comment]
It looks like the two bids are showing up, unless it was a temporary rendering glitch?

![Screenshot 2023-07-08 10 22 42 AM](https://github.com/tobymao/18xx/assets/1711810/e68a5cac-9de9-4bb3-aca2-28b2f33d58ba)

**Comment by BellmakerSA** [comment]
It seems to have been a temporary issue I guess? It was multiple folks having it not just me 🤷‍♂️

**Comment by kepakiano** [comment]
I know I'm a little late to the party, but still: Bids don't show up for players with outstanding loans. Looks like that was the case whenever it was Shaw80's turn.
