### ISSUE TITLE
[1846] route yield calculation off?

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#930]
Out of curiosity, I was just checking how a finished 1846 game would look like. In game with ID 3032, I just randomly noticed that in the last OR (6.2), the 4/6 run of PRR should have given $260 instead of the $250 that was awarded.

PRR runs a 4/6 train for $250 (J10, H12, E11, C15, C17)

J10 - $70
H12 - $60
E11 - $50
C15 -$70
C17 -$60

I can randomly guess that the algorithm is choosing E11 over H12 as it is grey compared to brown?

**Comment by benjaminxscott** [comment]
I was in this game, we opened this bug https://github.com/tobymao/18xx/issues/917 which I think fixes this issue in lateset code
(the game is pinned to commit `09ecaf44` so it doesn't reflect the latest code)

**Comment by Spobster** [comment]
Ok, that would be nice! The error with PRR does not the same as the mail contract / NYC issue, so I am curious to see whether it was fixed indeed. It will pop up definitely again if calculations are still off for specific situations.

**Comment by michaeljb** [comment]
Like #917, I believe this was fixed by 73dc9d9
