### ISSUE TITLE
[1825] no further action possible in game https://18xx.games/game/127014

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#9303]
**What's your Game ID?**

https://18xx.games/game/127014

**How to Reproduce the Bug?**

Any action taken leads to an error message (too short to be seen to identify the wording).
The actions I tried:
- to buy a share (there was a share available, I had enough money and also space for it + I hadn't sold shares in this company before)
- to write a chat message
In both cases the error message was briefly to be seen, before the game automatically started to reload.
After the reload the game was in the very state it was before I tried the respective action.

Browswe: Firefox

**Comment by KlausKiermeier** [comment]
Now it worked again. Don't know what it was.

**Comment by benjaminxscott** [comment]
might have been the client was out of sync w/ the server
