### ISSUE TITLE
[18MT] Share value is not double bumping when at the top of the stockmarket

### ISSUE THREAD

**Issue by UnrulyDuck** [tobymao/18xx#9304]
**[What's your Game ID?](https://18xx.games/game/127155)**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment]
Which action # / company?

**Comment by philcampeau** [comment]
My guess would be here: http://18xx.games/game/127155?action=783

This doesn't strike me as a bug. The rules say that if a dividend of 2x the current share price is paid, the stock market token is moved up in addition to right. As with almost all 18xx games, if a token is meant top move up but is already at the ceiling, that movement is forfeit.

**Comment by UnrulyDuck** [comment]
The reason I was thinking it isn't is because the designer described MT as
a slightly more streamlined version of 18CO. In 18CO it mentions
doublebumping if at the top of the market. There's no complete ruleset of
18MT that I can find. Just a list of what's different from 18CO

**Comment by philcampeau** [comment]
[Posted question](https://18xxgames.slack.com/archives/C67AHM6JC/p1689703581632269) for the designer in the 18xx slack. Will update when he replies.

**Comment by philcampeau** [comment]
@ryandriskel any chance you can chime in on this question?

**Comment by ryandriskel** [comment]
You are correct Phil. This is not a bug.

@UnrulyDuck I apologize for doing a disservice and not posting a complete ruleset!
