### ISSUE TITLE
[18NewEngland] Not letting us run two trains

### ISSUE THREAD

**Issue by philcplaygames** [tobymao/18xx#9306]
[18NewEngland] not letting us run two trains on phone

Id: 127603

[`https://18xx.games/game/31337`](https://18xx.games/game/127603)

I was playing on my phone (browser Safari) and it only shows one train in running routes even when I have two. Just checked and on my computer (in Safari) it shows both.

**Comment by philcplaygames** [comment]
Correction. with two E trains it only shows the lower value one in selecting routes on both computer and safari

**Comment by scottredracecar** [comment]
That is the rule. Looks correct to me.
