### ISSUE TITLE
[1860] Launching corporation after formation of the southern railway

### ISSUE THREAD

**Issue by ViennaTramways** [tobymao/18xx#9314]
Game ID: 126962

I have a rule question: 
The rules say that after the Southern Railway was formed: From the start of the following stock round, no track may be laid, or upgraded, and no more company bases may be placed on the board. 
So I can't launch a company during this last share round because no home base token may be placed on the board? I can buy shares of unlaunched companies, but it will never be launched? This is how it is played on 18xx.games. Is this correct?

**Comment by roseundy** [comment]
Lonny, I believe there is a question about this very issue for 1862 on BGG.

I'm going to say it's correct, since I don't want to have to change my code :-)

**Comment by roseundy** [comment]
It appears to be a hole in the rules. I agree it's odd that the company doesn't launch, but the alternative is that it does an incomplete launch (since it can't lay its home token) and it will fall back one space every OR.

**Comment by ViennaTramways** [comment]
Steve,
thank you very much. I trusted your programming skills, therefore I asked
for a "rule clarification" :-) Thank you for clarifying this.
Lonny

Am Mo., 24. Juli 2023 um 00:21 Uhr schrieb Steve ***@***.***>:
