### ISSUE TITLE
[1888] The share price board

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#9319]
<img width="185" alt="image" src="https://github.com/tobymao/18xx/assets/98611238/5a1eff86-ef84-4372-95f4-2520e5cf9c0f">
<img width="232" alt="image" src="https://github.com/tobymao/18xx/assets/98611238/e6ea2b2b-10bf-4169-aec4-5d024e39c411">

The board is different for 18xx.games and the real game.

**Comment by roseundy** [comment]
Interesting. I missed this change. Lonny's original files correspond to what I implemented.
