### ISSUE TITLE
[1841] the lite map overlay is incorrectly placed

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#9327]
We believe the map overlay for the lite version is incorrectly placed in this implementation.
It appears to be shifted 1 hex to the right.

Below is what the bottom part of the map looks like when playing on board18 which we believe to be correct.
![image](https://github.com/tobymao/18xx/assets/20323908/c9c7087e-2459-4e78-a392-0c3ffebf273c)

**Comment by roseundy** [comment]
I was given this picture, it's very possible whoever took it misplaced it.
![41_lite_closeup](https://github.com/tobymao/18xx/assets/8494213/95910c4b-0b12-451c-a472-fe4209c435c1)

**Comment by roseundy** [comment]
I've found more images that correspond to board18, so I will make it match.

**Comment by roseundy** [comment]
Here is my new Lite map:
![new_41Lite_map](https://github.com/tobymao/18xx/assets/8494213/3a7ab6c8-deaa-4bae-a76f-dde7efec8079)

**Comment by xmunroe** [comment]
Looks good, thanks!
