### ISSUE TITLE
[1866] GameError: Blocking step Run Routes cannot process action 194

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#9328]
[18xx . Games](https://18xx.games/)
[About](https://18xx.games/about)[Profile (Herbert (utc+2))](https://18xx.games/profile/765)
We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 194
Broken action: { "type": "pass", "entity": "SSFL", "entity_type": "corporation", "id": 194, "created_at": [1689577211](tel:1689577211) }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1866,%22needs%20triage%22) and include this link (https://18xx.games/game/127606?action=193)

**Comment by philcampeau** [comment]
Can you try this action again? It worked on my end when I cloned the game.

**Comment by Herbert62** [comment]
> Can you try this action again? It worked on my end when I cloned the game.

Activated master mode. After that auto routing was possible, but no action („this game is broken and cannot accept new actions“)

**Comment by magnusstjarnhild** [comment]
Game archived, so cant debug.
