### ISSUE TITLE
[1841] Illegal run out of yellow Milan tile.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9330]
https://gist.github.com/physic/a70cfe28438e69ac858c0ffa61afbc8b

The yellow Milan tile contains a single track segment leaving Milan, which then splits to head to Cosmo (D8) and Bergamo (E9). Running two 2Ts out of Milan would reuse track.

In the game file gist above, you can see Milan running two 2Ts out of Milan for 170L, which is not allowed.

**Comment by roseundy** [comment]
The Milano tile doesn't fit with any of the tile rendering (or restriction) schemes in our code. My solution was to make Milano a "terminal". This prevents a train from running through Milano, but I completely missed the case of two trains using Milano as an end point. I will have to special case this in my route checking code.
