### ISSUE TITLE
[1848] Option to buy 6 from the bank goes away after buying a train from another player.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9331]
https://18xx.games/game/130162?action=369

The active player wants to buy a 3+ from the QR and then buy a 6. However, after buying either any train from another company, the option to buy the 6 disappears, even though the corporation has enough funds. Buying the Ghan still allows buying a 6, but buying a train from another corporation does not.

A corporation should always be able to buy the next train from the bank if it has enough money and is under the train limit.

**Comment by damerell** [comment]
Rule 8.3.4 "When a company buys a train from another, the transaction takes place at the end of the purchasing company's turn"; commit 3a647e4627ac42d7a319c801fe1abac34646585d and issue 9145 seem to think this is to say it must be the last purchase.

However, as @physic noted in .games chat, it also could be intended to make it clear that trains are bought during the purchaser's turn, not sold during the seller's turn.

I've had a look in the Rules forum on the geek and cannot find a definitive answer.

**Comment by physic** [comment]
I found the german rules. The same line in the original is: Der Handel mit Loks kann immer nur stattfinden, wenn die
kaufende Gesellschaft in der OR agiert.

There is no mention of "end of turn"

This is a mildly ambiguous mistranslation, but it seems clear that "end of the buying corp's turn" only meant "during the buying corp's turn" and not "This ends your turn when you do it"

**Comment by physic** [comment]
Verbatim: The trade of trains can always only take place, when the purchasing company acts in the OR

**Comment by damerell** [comment]
In https://boardgamegeek.com/thread/3130473/timing-train-purchases-rule-834-not-question-fyi-o the designer confirms the intention here (and in 1880) was just to establish the usual 18xx rule that trains are bought during the purchaser's turn, not sold during the seller's.

**Comment by benjaminxscott** [comment]
Thanks for checking on this!
