### ISSUE TITLE
[1841] Auction UI code breaks 1846

### ISSUE THREAD

**Issue by motoi-sano** [tobymao/18xx#9333]
**What's your Game ID?**
https://18xx.games/game/130620
https://18xx.games/game/130643

**How to Reproduce the Bug?**
Game screen is not displayed.
It remains Loading game... and does not move.

**Which Browser / Platform?**
Mac OS, iOS and iPad OS Safari and Chrome.
Newest version.

**Comment by roseundy** [comment]
Bug created when adding blind auction for 1841 version 1.
