### ISSUE TITLE
[1841] Missing dup when transferring shares

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#9334]
Link to game: https://18xx.games/game/130772

when I try to merge AFTA and SFTG I get an error message “undefined method ‘to bundle’ to nil.   

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Missing dup of share list.

@fsaglio: when this is fixed and released, you should be able to continue your game.
