### ISSUE TITLE
1846 Game ID 130631 Frozen Can You please kill the game?

### ISSUE THREAD

**Issue by latindog** [tobymao/18xx#9335]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by latindog** [comment]
Game ID 130631
The error is occuring across multiple device Iphone, google chrome on mac, pc

**Comment by roseundy** [comment]
Dup of #9333

**Comment by roseundy** [comment]
No need to kill. A fix is in flight.
