### ISSUE TITLE
[18Mag] Game ID 130449 Unable to load game (probable dup of 1841 bug)

### ISSUE THREAD

**Issue by AmauSky** [tobymao/18xx#9336]
**What's your Game ID?**
ID 130449
https://18xx.games/game/130449

**How to Reproduce the Bug?**
The Game Mode is New major ; New minors - challenging; Supporter Cards
We are half-way through the Draft Phase but I am unable to load into the game at this moment.

**Which Browser / Platform?**
Chrome and Safari

**Comment by roseundy** [comment]
Likely a dup of #9333

**Comment by roseundy** [comment]
Yep, a dup. And now fixed.
