### ISSUE TITLE
Use simplified logos in all games, not just 1889

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#934]
Although attractive, the train company logos in 1889 were just another thing to memorise. I found the 1889 implementation became more accessible when it switched to using colour-coded acronyms (e.g. the Iyo Railway logo below). 

![image](https://user-images.githubusercontent.com/15707007/86092787-e904d680-baa5-11ea-8a17-205632ecf30d.png)
 
Can we change them in 1846 and 1836jr as well? Even the logos which contain acronyms can be really hard to read: 

![image](https://user-images.githubusercontent.com/15707007/86093000-35e8ad00-baa6-11ea-893d-d4ff63dbf7db.png)

**Comment by dfannius** [comment]
This would be a nice thing to have as a profile option (probably one option that would apply to all titles). I really like the more interesting logos; I was sad when they were removed from 1889 and would be sadder if they were removed from the other titles too.

**Comment by tobymao** [comment]
no plans to change this
