### ISSUE TITLE
[1822] GameError: SECR may not spend £58 on SWR's 3 train; may only spend between £1 and £40

### ISSUE THREAD

**Issue by cwebblax** [tobymao/18xx#9345]
Game crashed

Game ID is 128665
https://18xx.games/game/128665?action=921

**Comment by philcampeau** [comment]
To be clear, the bug isn't that SECR can't buy the train for £58, since it only has 40. It's that the site seems to have allowed the purchase, but then threw up this error:

![Screenshot_20230806_222315_Chrome](https://github.com/tobymao/18xx/assets/26125362/905a15bf-5d86-4d44-a0a6-b617f71bd250)

**Comment by roseundy** [comment]
This is likely due to PR #9269 . I suspect this was a game that should have been pinned.

**Comment by cwebblax** [comment]
I had never submitted a bug report before so I just copied the error message that was stated in the game. Sorry if there was confusion.

**Comment by cwebblax** [comment]
Is it possible to delete the game somehow? It won't allow me to.

**Comment by michaeljb** [comment]
The game has been archived, sorry I missed this!
