### ISSUE TITLE
[1841] merger with share price over 250 fails

### ISSUE THREAD

**Issue by ArielAyanna** [tobymao/18xx#9351]
https://18xx.games/game/130968

**Comment by roseundy** [comment]
Can you tell me which action? (use the history to find the merge step that wasn't working, then look at the URL at the top for the action number).

**Comment by roseundy** [comment]
It looks like it was around action 471.

I can't reproduce it in hotseat.

**Comment by ArielAyanna** [comment]
Hm, that's weird. It gave me a long red error message. Hopefully the problem recurs soon.

**Comment by roseundy** [comment]
Just reproduced it. Action = 746

**Comment by roseundy** [comment]
Found the bug. Apparently, I never tried merging a corporation with a share value over 250.

Nice catch, @ArielAyanna
