### ISSUE TITLE
[Site/interface] Unable to select 1841Lite if the max player count is currently set to above 6

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#9352]
**How to Reproduce the Problem?**

When you get to the game creation page, the site defaults to min 3 max 8 players. This prevents you from selecting 1841Lite until you lower the max players to 6 or below. This would likely also affect any other games with variants that support a lower player count.

Ideally, it would be nice if the site automatically shifted the max player count to 6 when you click on the box for 1841Lite

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**

This happens on Chrome, Firefox, and Edge browsers on my Windows 11 PC, as well as on Chrome on my Android phone.

**Comment by roseundy** [comment]
This isn't a 1841-specific bug. Any option that reduces the player count on any game will have this issue.

**Comment by philcampeau** [comment]
True. That's why I opened it as an "Interface or Site Problem". I put 1841 in the title because that's where I first noticed it. I can remove that part if it's clearer.
