### ISSUE TITLE
[18EU] Hamburg counting for Red to Red bonus

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#9353]
Game 128026.  When using Automatic route calculations,  Hamburg is being considered a terminus for the red-to-red bonus.  It should not be, unless there was a rule change of which I'm unaware.

**Comment by philcampeau** [comment]
Game is 18EU, not 1856.

**Comment by JEBrosius** [comment]
This correction is based on an incorrect reading of the Red-to-Red bonus rules.

Hamburg is an Off-Map Location.  Unlike other Off-Map Locations, Hamburg may be part of a route without being at the end of the route.  The statement "A route with an Off-Map Location at one end that runs through Hamburg and has other than an Off-Map Location at the other end of the route does not receive this bonus" does not disqualify Hamburg as an Off-Map Location that can generate a Red-to-Red bonus; it merely states that if Hamburg is not one of the ends of the route, it does not in itself trigger the bonus (though the bonus may still apply if two other Off-Map Locations are at the ends of the route.)
