### ISSUE TITLE
1850 error on price protect 

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#9354]
we get the following message when the player whose option it is to price protect does anything: 

the server did not accept this action due to: Illegal action: wrong number of arguments (given 2, expected 0)... refreshing."

link to game: 

https://18xx.games/game/130535

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by bentziaxl** [comment]
when in the game did this bug happen?

**Comment by philcampeau** [comment]
If we don't get an update on this from the original reporter in the next week, we should close this. It's just not possible for us to find where they encountered this problem otherwise.

**Comment by fsaglio** [comment]
Unfortunately this was long ago enough that I can't remember where/when it happened.  My apologies for missing the question a few weeks ago.
