### ISSUE TITLE
[1880] trains should be purchasable from depot / other corps interchangeably

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#9358]
Ref: https://github.com/tobymao/18xx/issues/9331, a translation error resulted in a mis-implementation of the timing when corps may buy trains "across" or from depot

Corps may buy trains interchangeably from other corps or from the depot

**Comment by crericha** [comment]
@benjaminxscott can you provide more context here? The referenced game is 1848.

**Comment by philcampeau** [comment]
This appears to have been resolved. I'm able to buy trains in either order now. Closing.
