### ISSUE TITLE
1822 game ended with bug https://18xx.games/game/127172?action=1248

### ISSUE THREAD

**Issue by Randy3535** [tobymao/18xx#9361]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by michaeljb** [comment]
Looks like GWR bought a train and then passed on acquiring a minor/redeeming shares, but now the pass action cannot be processed as the rest of the turn after the train buying is automatically skipped. https://18xx.games/game/127172?action=1249

Looks like at the broken pass action, GWR did not have enough cash to acquire a minor, and no shares were in the bank pool to redeem. I don't know how it was able to pass. The game is also broken with 27b9ab954 from 5 days ago checked out, but deleting the action from my local DB fixes it. I'll delete the action from the prod DB and that should fix the game.

**Comment by michaeljb** [comment]
GWR did acquire P8 in this game, so this was probably caused by #9269--GWR ended up with a different cash amount after that change was deployed.

The broken pass action has been deleted, and the game can resume.

**Comment by Randy3535** [comment]
Thanks so much for detailed and prompt response! 😊- RandySent from my iPhoneOn Aug 8, 2023, at 8:11 PM, Michael Brandt ***@***.***> wrote:﻿
GWR did acquire P8 in this game, so this was probably caused by #9269--GWR ended up with a different cash amount after that change was deployed.
The broken pass action has been deleted, and the game can resume.
