### ISSUE TITLE
[1841Lite] "undefined method ‘tile‘ for nil" when attempting to start a minor.

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#9364]
**What's your Game ID?**

https://18xx.games/game/131025?action=156

**How to Reproduce the Bug?**

Attempting to start a minor corp gives the error below, reproduced in other browsers and in cloned game:

![Screenshot_20230809_114342_Photos](https://github.com/tobymao/18xx/assets/26125362/1cbf797f-6fd0-42c3-851e-177ec5356140)

**Which Browser / Platform?**

Chrome, windows 11
Firefox, Android OS

**Comment by roseundy** [comment]
Apparently, I never tried starting a non-historical minor company with the "lite" map.
