### ISSUE TITLE
[1841] Blocking step Sell then Buy Shares or Concessions cannot process action

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#9370]
We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares or Concessions cannot process action 82
Broken action: { "type": "buy_shares", "entity": 6167, "entity_type": "player", "id": 82, "created_at": [1691430284](tel:1691430284), "shares": [ "IRSFF_3" ], "percent": 10 }

Please [raise a bug report]and include this link (https://18xx.games/game/130759?action=81)

**What's your Game ID?**
130759

**How to Reproduce the Bug?**

Not sure. Game was killed

**Which Browser / Platform?**
safari

**Comment by roseundy** [comment]
I'm very sorry, but a bug fix that I made yesterday invalidated this game. I will archive this game.
