### ISSUE TITLE
[1841] Tuscan Merge with only 2 corporations crashes server

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9372]
Game link: https://18xx.games/game/130760

First 4T was purchased, triggering all the things

President of IRSFF had 3 shares, no one else has any shares of IRSFF. On the succession, the president opts to exchange two shares for the SB presidency, and the remaining 3rd share for an SB share. SFL presidency is placed in the pool. SB President opts to buy 1 more share of SB, and have SB buy 2 additional tokens. We are now at the SFL buy additional tokens step - there is a button present for buying 0 (SFL can't afford more), but no one can get the game to allow them to press it and proceed. Former IRSFF president is unable, other players using master mode are unable (I am not IRSFF president - when I try in master mode I get the error message: "Illegal action: comparison of NilClass with 105 failed... refreshing.")

**Comment by roseundy** [comment]
Main bug is in the code that figures out best price of SSFL, SFLP and SFMA. It didn't handle one of those corps not having been started. It worked in hotseat (which is how I tested it), but not on the server (i.e. a live MP game). Easy fix.

Incidentally, SFL should have been able to buy up to 2 tokens. That is now fixed too.
