### ISSUE TITLE
1841 error after with the first 4 train

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#9378]
1841
# 131395
(https://18xx.games/game/131395?action=194)

error message "undefined error player for nil"

as an experienced player I tried out starting companies with companies: the IRSFF which is splitted with the first 4 train, owns 60 % of a new started minor

same error appears when the IRSFF doesn't buy a 4 train but in move 222 the SFTN tries to buy the first 4 train

**Comment by roseundy** [comment]
I'm sorry, the link you shared doesn't have an error. Exactly how was the error caused?

**Comment by roseundy** [comment]
Ignore my last comment. I've reproduced the error.

**Comment by roseundy** [comment]
The bug was my code didn't handle the Ferdinandea Secession if players/corporations only owned pairs of shares of IRSFF. Apparently I only tested cases where there was a least one entity holding a single share.
