### ISSUE TITLE
[1841] Child Company Share Disappeared During Tuscan Merge

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9389]
Game ID, with action: https://18xx.games/game/130760?action=349

Entering Tuscan Merge: SSFL owns 30% of IFAI, no other shareholders of IFAI; SSFL is started, but SFMA is not (status as of action 348). On Tuscan merge, 2 shares of IFAI are moved into SFLi - this should be 3, since SSFL owns 3. After the Tuscan Merge, 2 shares of IFAI are in SFLi, 7 are in IFAI IO, and that's it - one share is missing from the game.

Side note: "dropped a share on the ground and kicked it under the sofa during the Tuscan merge" is a very realistic feature to have in the game, but I'm guessing it was not intended :)

**Comment by roseundy** [comment]
First time a merger included a corporation that owned a president's cert? Hard to believe, but
share_pool.transfer_shares didn't like simply moving a president's cert from one corporation to another.

**Comment by roseundy** [comment]
This bug is taking longer to release, because I need to make sure my change doesn't break any of the other titles on 18xx.games
