### ISSUE TITLE
[1846] Phased out trains should rust whether run or not

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#939]
Game ID 2495, GT runs a 2 and 3/5 but has a 2,2,3/5. After running GT has a 2 and 3/5. Should only have a 3/5. From the rules: 6.69 After a corporation’s run routes step, remove any phased out trains belonging to it (whether or not they ran routes), see 6.82.

Game data linked

https://gist.github.com/KillerOrca/9ae06ff2efe2037703fa3e8f3d573267

**Comment by benjaminxscott** [comment]
repro'd, [this seems like the relevant loc](https://github.com/tobymao/18xx/blob/master/lib/engine/round/operating.rb#L357)
