### ISSUE TITLE
1822MX auto routing not calculating rotes with multiple trains with LP

### ISSUE THREAD

**Issue by akoewler** [tobymao/18xx#9390]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
Can you provide a link to the game, preferably on an action where this occurred?

**Comment by michaeljb** [comment]
Probably related to #7902

**Comment by michaeljb** [comment]
Closing as duplicate of #7902
