### ISSUE TITLE
[1841] Major Company Merge Share Price incorrect

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9395]
Game/Move ID: https://18xx.games/game/130760?action=440

SFTG (share price 93) merges with SFL (share price 106). Per 4.7.4 "For a  merge of major Corportations, the new value... will be the rightmost value which is less than the sum of the market values of the old Corporations." 93 + 106 = 199, so presumably merger price should be 198 (13th column from the left, 5th row down from the top). Instead, the merger price in action 441 is set to 180 (13th col, 6th row down).

**Comment by roseundy** [comment]
This was surprisingly difficult to code. I thought I had tested this, but apparently not well enough.

**Comment by roseundy** [comment]
The fix may break games.

**Comment by roseundy** [comment]
In my defense, the rules say "the rightmost value which is less than the sum of the market values of the old Corporations". This is what I implemented. Note that 180 is more right that 198. However, the table at the back of the rules contradicts this.

So apparently the rule is: "The largest value which is less than the sum of the market values of the old Corporations, with ties being broken by the rightmost value"

**Comment by roseundy** [comment]
Now I'm confused. My tie-breaker rule doesn't help since 198 and 180 are in the same column. I'm not sure what rule actually get you to the table at the back of the rules.

**Comment by djanyreason** [comment]
I am not sure I follow how 180 is more rightward than 198, as they are in
the same column.

If one were to re-word the rule, I think the most accurate way would be "a
value in a column as far to the right as possible such that the value is
less than the sum, and the greatest value in that column less than the
sum". If a company at 100 and 105 merge, they should end up at 198, not at
202.

**Comment by djanyreason** [comment]
Or, to restate, first identify the column - SUM_SHARES <= Min(COLUMN) -
then identify the row in that column

**Comment by roseundy** [comment]
For example, if the sum of the corporate prices was 188, the table doesn't say the new value is 187, but 180. This seems to imply my coding of this is correct and only breaks when there are two prices less than the total that are rightmost.

It think the actual rule is: "the rightmost value which is less than the sum of the market values of the old Corporations with ties broken with the higher value".

**Comment by roseundy** [comment]
My code currently searches from bottom to top within a column, when it should be searching from top to bottom.

**Comment by roseundy** [comment]
I still claim that this is a hole in the rules, whose resolution is implied by the table.
