### ISSUE TITLE
[1841] no shares visible in the bank, neither IPO nor market

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#9396]
https://18xx.games/game/131664?action=238

There have never any shares been displayed in the spreadsheet for the bank. Just thought t would appear after the first 4 train but after the IRSFF split and the Tuscan merge there are no shares shown

**Comment by roseundy** [comment]
The spreadsheet view has issues in 1841. Shares owed by corporations are not shown either.

**Comment by roseundy** [comment]
Market shares show up fine, just not IPO shares.

**Comment by roseundy** [comment]
The quick fix is to show IPO shares on the spreadsheet.

A longer term fix is to figure out how to show corporate owned stock shares without having to create a giant two-dimensional matrix of corporations.
