### ISSUE TITLE
Action buttons for company special powers

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#940]
It would be nice if there were action buttons on the companies that have special powers that can be activated. Lots of new users get confused about the "click a company, then go to the map to use the ability." This would also apply to special abilities that let users assign bonuses or discounts (e.g. named train bonuses and half price train in 18AL).

**Comment by eheiden** [comment]
Would it be appropriate to enumerate specific instances of private company abilities that are "quirky" (like the steamboat in #1043 or is the existence of those issues sufficient to capture the details?

**Comment by tobymao** [comment]
i don't think it's necessary, we just need a dedicated ability view that lists everything they can do more explicitly

**Comment by jenf** [comment]
Can we make the text wider, the '...' is quite annoying

**Comment by yzemaze** [comment]
@jenf It should be wider, side-effect of another change. I’ll fix it.

**Comment by Azuureth** [comment]
How about buy-in powers (like C&WI and Ehime railways) prompt a new "private action phase" where it lays out what you can do or it asks you to skip using the company's power. Once completed or skipped, it would return the player back to previously active phase.

Powers that are more "during your turn" like the track lays from Chesa... that's more tricky. I kinda liked when the privates were shown next to company charter, implying clicking them did something. Still, we'd need to tie in the double lay somehow.

Or perhaps some kind of "activate private company power" button?

**Comment by ChrisTheCat** [comment]
I think anything that requires specific activation should be a button that looks just like the other buttons (grey, rounded edges, etc.)

**Comment by benjaminxscott** [comment]
I suspect this commit resurfaced an issue with SBC in 46, it seems like it can't be assigned to a corporation (unless pebcak)

https://github.com/tobymao/18xx/issues/1041#issuecomment-664511097

 @tobymao
