### ISSUE TITLE
(Rules Clarificaltion) Cannot visit Yellow Milano more than once

### ISSUE THREAD

**Issue by qwerlancer** [tobymao/18xx#9400]
Game ID: hs_fmkwlzvh_1692055395

Am I missing something on rulebook?
As IRSFF I cannot visit Yellow Milano more than once as the system do not allow me to do it. According to the rulebook the game provided it does not prohibit players to do it. 

![231412341325](https://github.com/tobymao/18xx/assets/32906266/9cd41090-a957-46dc-8540-c3b545051ca7)

**Which Browser / Platform?**
Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)

**Comment by roseundy** [comment]
It's not in the rulebook, but int the map.

The physical game Milano tile looks like this:
![milano](https://github.com/tobymao/18xx/assets/8494213/72a0fb95-a6b2-459e-aa58-8d0a2086115c)

For various reasons, the 18xx.games code doesn't support a tile with both a city and track such as this. The best I could do was to render Milano as you see it, but with the restriction that you can't run two trains to or from it.
