### ISSUE TITLE
[1841] Option to remove SFLi tokens from the map is given to the wrong player.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9401]
https://18xx.games/game/131796?action=242

The President of the SFLi gets to choose which tokens on the map to keep, and which to receive as loose tokens. The game was offering the President of one of the intermediate companies (who did not end up becoming President) the choice. This choice should come after the final merger and exchange of share options.

Rules reference:
The rules don't explicitly say who chooses, but the fourth bullet of Section 4.6.10 implies that the new President chooses, because it outlines how to choose if there is no President.

**Comment by roseundy** [comment]
I followed the third bullet when I implemented it.
"The merges are always performed by the President of the Corporation currently having the greater value."
What is the purpose of this bullet?

For normal merges, the rules also seem vague about who does exactly what during merges. It just says "the President" without specifying whether it is the President of the corporation that triggered the merge, or the President of the newly formed corporation.

**Comment by roseundy** [comment]
Assuming that the third bullet just specifies who physically moves the paper around, I will fix this.

**Comment by physic** [comment]
I see what you're saying.

"The merge is performed" is important because it determines which player gets to exchange shares first.

**Comment by roseundy** [comment]
OK, that makes sense. I'll modify the code so that the president of the SFLi will make the token decision.

I had just assumed this was just another way for 41 to provide a knife to twist in someone's back.

**Comment by roseundy** [comment]
I will fix this for non-Tuscan mergers too in the same way (the new president decides not the president of the corporation that triggered the merger).
