### ISSUE TITLE
[1841v1] Cannot select SFL or SFV share

### ISSUE THREAD

**Issue by Hewhite2003** [tobymao/18xx#9402]
https://18xx.games/game/131345

The game will not allow the SFTG to select a share.

Error is that "the first sahre was not a 40% share."

**Comment by roseundy** [comment]
Bug was in code that handled merger of minors (in Tuscan Merge). It assumed first shareholder to exchange shares was the president of the corp that triggered the merge - which isn't always true for the Tuscan Merge.
