### ISSUE TITLE
[1841] A merger whose result is a frozen company is not allowed.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9404]
https://18xx.games/game/131796?action=795

4.7.4.1 Share Exchange for a Merge. Paragraph 3. Any merge other than the Tuscan merge is backed out if no player trades up to the Presidency.

**Comment by roseundy** [comment]
Odd. I coded up a check for this. Not sure what happened.

**Comment by roseundy** [comment]
This has been fixed.
