### ISSUE TITLE
1841 Tuscan Merger round with just the major started

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#9407]
**What's your Game ID?** 131534

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by WayneWWms** [comment]
https://18xx.games/game/131534?action=183

During Secession/Merge something came up about an undefined action with instructions to report it.

**Comment by roseundy** [comment]
Your game runs fine. I need more info do debug this.
