### ISSUE TITLE
1841 merger prices seem calculated incorrectly

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#9409]
https://18xx.games/game/130947?action=314 is just after the Tuscan Merge. Here, SFLP and SFMA (with share prices of 100 and 93) merge to give a new price of 76.

I think this is because find_rightmost_share_price() picks the lowest price in a column by iterating down through the rows.

Rule 4.7.4 says "For minor Corporations, the new value will be the rightmost value which is less than half the sum of the market values of the old Corporations". I have seen this interpreted such that the new value must be at the bottom of a column next to a ledge (because these are the only "rightmost" values). However, table 14 in the rules appears to say that the value should be 95 in this case and appears instead to say that the new value should be, in the rightmost column with any value less than half the sum, the highest value which is less than half that sum.

**Comment by roseundy** [comment]
Dup of #9395

The fix has been made but not deployed.
