### ISSUE TITLE
Request:  Please Swap Enter and Delete Buttons

### ISSUE THREAD

**Issue by gamergeek65** [tobymao/18xx#941]
Just a minor ask.  The "Enter" game button is typically on the far right.  If you are the owner of the game, then the "Delete" button is far right, and the Enter is to the left of it.  Could you possibly keep the "Enter" button in the same static location.  I absently almost deleted my game by clicking Delete because I thought it was the Enter button.  I know this was stupid of me, but hope this might be a simple change, and keeping buttons in a constant spot is helpful.

**Comment by tobymao** [comment]
sounds reasonable
