### ISSUE TITLE
1841 end of turn button

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#9411]
**What's your idea?**

In 1841 I would really appreciate a final "OK, I've finished my turn" button at the end of each company's action in an OR. I'm finding that I'm, for example, doing a merge and by the time I see the consequences it's moved on to the next company. I appreciate I could clone the game each time, but an "OK, I'm done" button would be really helpful. 

And, thank you for implementing 1841. 

**Are there related ideas?**

Other contributors may be working on something similar, [check out the list of open feature requests](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to see if there's opportunity to collaborate.

**Did you join the Slack?**

Check out `#18xxgamesdev` [on the slack](https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ) and meet your fellow contributors!

**Comment by roseundy** [comment]
I understand the sentiment, but players are already having to click a bunch in this game just to get through an OR (e.g. cross-company tokens, corporate stock sales/purchases, merging/transforming).
