### ISSUE TITLE
1841 Version 1, Player Reordering After Initial Bids

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#9418]
**What's your Game ID?**  132025

https://18xx.games/game/132025

**How to Reproduce the Bug?**

**Which Browser / Platform?**

In Version 1 of 1841, player order is completely changed based on starting bids.  Rule 2.2:  "Priority Deal Card to the owner of the sheet at the top of the stack, then assigns the seat at his / her left to the second bidder, the other to the third, and so on."

The program correctly assigned the priority to the first person, but did not readjust the other positions.  

Part of the game design was to reward those who bid more.  It can make a difference in starting companies, particularly since the SFMA can be blocked.

Thanks for making this great game available.  I know it was more complex than many others.

**Comment by WayneWWms** [comment]
The example in 2.5 uses the complete reordering as well, with the resulting order being BEDAC.

**Comment by roseundy** [comment]
My code does sort based on total starting bids, with all the tie-breaking done based on the rules. I'll have to poke into your game to see what happened.

**Comment by roseundy** [comment]
Not seeing a problem. Chuck10 bid a total of 290, WayneWilliams bid a total of 251, and Seraphin bid a total of 245. The player was changed correctly according to this.

You are aware that player order is based on the total amount bid, not paid, correct?

**Comment by WayneWWms** [comment]
I wasn't aware of that.  I thought it was paid.
