### ISSUE TITLE
Color match stock market to yellow/orange/brown zone indicators

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#942]
The stock market yellow and orange are clearly yellow and orange. The charter yellow looks more like a yellowish chartreuse and the orange looks more like brown. It would be better if the colors were a closer match. In the screenshot below, it isn't hard to see that UR's orange is different than TR's yellow, but when only one of the colors is displayed on the charter (if the UR wasn't in the zone, for example), the colors are ambiguous.

<img width="979" alt="Screenshot 2020-06-30 12 44 46" src="https://user-images.githubusercontent.com/8732435/86170136-888a8f00-bacf-11ea-888f-32f5ede8a33d.png">
<img width="153" alt="Screenshot 2020-06-30 12 42 34" src="https://user-images.githubusercontent.com/8732435/86170140-8a545280-bacf-11ea-89cf-f2f6634a45d4.png">

**Comment by jenf** [comment]
Technically they're the same color, but they are slightly transparent as done with the spreadsheet.

**Comment by ChrisTheCat** [comment]
Why are they slightly transparent? Is there a reason for doing that, since
it makes the colors harder to distinguish/understand?

**Comment by jenf** [comment]
It was copied and paste to keep the same format as the spreadsheet.

The biggest question is should it be 0.4 or should it be fully opaque. How does that interact with dark mode.

**Comment by ChrisTheCat** [comment]
I'd argue the spreadsheet colors also need to be changed to look more like
the colors on the stock market.

Or, perhaps the entire stock market should use transparency and have a dark
mode option (no white spaces, only black...) but that might cause problems
with distinguishing the tokens.

If the purpose of the color is to say "your stock is in this color on the
market" then they should render as the same color on the screen.

**Comment by scottredracecar** [comment]
Assuming the most prominent background colors are white and black, any
amount of transparency will make the highlights display differently than
the stock chart--which to my eye appears to possibly have 100% opacity.

So probably the baseline should be to use 100% opacity for these colors
everywhere.

**Comment by yzemaze** [comment]
> The biggest question is should it be 0.4 or should it be fully opaque. How does that interact with dark mode.

1.0 might be too harsh on dark bgs, but 0.8 or 0.9 should work well.
You’d have to explicitely set (font) color of the market row to black or maybe color_for(:font2) [== alternative font color, which is used on stockmarket, too] to work along nicely with user defined colors (aka "dark mode").

**Comment by ryanespin** [comment]
So with a background at 0.8 opacity, it looks like this:
![image](https://user-images.githubusercontent.com/3648402/86503760-17710300-bd7f-11ea-92ce-a5c98766a46b.png)

Maybe consider doing just the font color the yellow/orange?
![image](https://user-images.githubusercontent.com/3648402/86503707-826e0a00-bd7e-11ea-8ff7-350358be70ee.png)

**Comment by yzemaze** [comment]
Font color doesn’t work on light bg (yellow on white!)

**Comment by ryanespin** [comment]
> Colored font doesn’t work on light bg (yellow on white!)

Yup sorry, I meant specifically for dark mode only on the font color.
