### ISSUE TITLE
[1841] Unable to freeze SFLi during Tuscan Merge

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9422]
https://18xx.games/game/132093

No player has 20% to take presidency of SSFLi during the Tuscan merge.  Gives error when last player attempts to sell their share and not take presidency.

**Comment by roseundy** [comment]
Untested (until now) branch of my code had cut-and-paste issues.

Also completely missing "automatic" token placement for frozen SGLi.
