### ISSUE TITLE
[1848] corp should be able to take a loan to buy a 2E (Ghan) after paying out

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#9426]
reported by @ZakisanGithub

When a company is at the train limit in phase 5 and does not yet own a 2E, it is only offered purchasing one if is has £200 at that time. If the company has to take a loan to do so, the latest opportunity is before deciding whether to pay out, otherwise train buying is skipped automatically.

In most cases, the director can just get the loan beforehand. But two steps from receivership "take loan" -> "pay out" -> "buy 2E" would close the company before being able to pay out while the order "pay out" -> "take loan" -> "buy 2E" would not. But when attempting the second option for a company with less than £200, instead you get "pay out" -> "skip buying trains".

I downloaded game data from a game right before this moment 

https://18xx.games/game/131675

[hs_jxnwvkvk_131675.json.txt](https://github.com/tobymao/18xx/files/12375918/hs_jxnwvkvk_131675.json.txt)

**Comment by philcampeau** [comment]
I've got the fix, but it kills both the fixture games so I need to create one or two more. 

We'll also need to pin a lot of active games of 48 to implement it.
