### ISSUE TITLE
1822PNW Can't place a builder cube in Seattle.

### ISSUE THREAD

**Issue by gargoyleking** [tobymao/18xx#9431]
1822PNW Can't place a builder cube in Seattle.

**What's your Game ID?**

https://18xx.games/game/131488?action=201

**Describe how you produced the bug/issue.**

Attempt to place a builder cube on Seattle.  You can upgrade the city for a cost of 20, but cannot place a cube to upgrade it later.
During OR 2.1 Tacoma, Olympia and Grays Harbor Railroad Company (10) attempted to place a builder cube on Seattle so that it could later upgrade the city in the same turn that it could upgrade it's L train to a 2 train.  Clicking on the city produces the yellow tile for the city, but no 'tile' to add a cube.

**Which Browser / Platform?**

Firefox v. 116.0.3 (64-bit)

**Comment by outsidePasser** [comment]
The 20 cost to upgrade Seattle is not a terrain cost - it is the cost for every upgrade (plan -> yellow, yellow->green, green->brown, etc.)  Cubes cannot be placed to offset this cost.

**Comment by gargoyleking** [comment]
Got it then.  Might be an idea to find some way to delineate that so people are able to understand the difference between the two types of costs more easily.  Maybe an up arrow instead of a water/mountain symbol with a quick explanation tagged in the info section of which works how?
Thanks,
Gargoyleking 
aka Gerald Stacy

    On Sunday, August 20, 2023 at 05:52:52 PM MDT, Michael Alexander ***@***.***> wrote:  
 
 


The 20 cost to upgrade Seattle is not a terrain cost - it is the cost for every upgrade (plan -> yellow, yellow->green, green->brown, etc.) Cubes cannot be placed to offset this cost.
