### ISSUE TITLE
[1841] Can't EMR to pay for tokens when parring a company

### ISSUE THREAD

**Issue by rrokkam** [tobymao/18xx#9432]
**What's your Game ID?**
https://18xx.games/game/132346

Bug happened at https://18xx.games/game/132346?action=645 when Titanrich tried to par the CTDA at 68, then EMR to pay 400 for two tokens.

The same action is allowed in a hotseat game: https://gist.github.com/rrokkam/018bf5dd6cd7edd8979202ef46a76a6f

**How to Reproduce the Bug?**
In a multiplayer game, par an ahistorical company at a low value on a track, so it doesn't have enough money to pay for its tokens. A button to EMR will show up, but clicking it results in an error saying that the server doesn't accept the action.

In a hotseat game, do the same, and the action is allowed.

I'd post a screenshot, but I don't want to undo in the multiplayer game and the bug doesn't reproduce in hotseat mode.

**Which Browser / Platform?**
Chrome 116.0.5845.96

**Comment by roseundy** [comment]
OK, thanks. I should have enough to go on. I couldn't reproduce this in hotseat, but now that I know it's a server error, that should help.

**Comment by roseundy** [comment]
Integer to floating point rounding difference between javascript and ruby.
