### ISSUE TITLE
1846 cant get meat packing to add value to route (green)

### ISSUE THREAD

**Issue by cw67q** [tobymao/18xx#944]
Hi,

We are having difficulty getting meat packing to add value to a route. We are in Greens and GT just bought MP in. This is our first game on 188xx.games and we are unsure if we are doing something wrong. Any help would be appreciated.

We have previously used the steamboat token and it seems to have added value to the relevant routes.

Game ID is 3167.

Thanks, chris

**Comment by tobymao** [comment]
can you paste the game data in a gist?

**Comment by cw67q** [comment]
Hi Toby, thanks for getting back to me. I'm afraid I dont know how to do that, but I can probably get one of the other more tech savvy guys in our game to  pass it on to me. Cheers, Chris 

We are all very impressed with the implementation btw.

**Comment by cw67q** [comment]
Actually is this what you meant? (Apologies if it wasnt)

{
  "id": 3167,
  "description": "Clyde valley",
  "user": {
    "id": 2488,
    "name": "Gamebhoy"
  },
  "players": [
    {
      "id": 2488,
      "name": "Gamebhoy"
    },
    {
      "id": 2582,
      "name": "FloT"
    },
    {
      "id": 2583,
      "name": "Kain00"
    },
    {
      "id": 1805,
      "name": "Pitchfork"
    }
  ],
  "max_players": 4,
  "title": "1846",
  "settings": {
    "seed": 9.631332270114109e+37
  },
  "status": "active",
  "turn": 2,
  "round": "Operating Round",
  "acting": [
    2488
  ],
  "result": {},
  "actions": [
    {
      "type": "message",
      "entity": "FloT",
      "entity_type": "player",
      "id": 1,
      "message": "Hello"
    },
    {
      "type": "message",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 2,
      "message": "Greetings"
    },
    {
      "type": "message",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 3,
      "message": "welcome"
    },
    {
      "type": "message",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 4,
      "message": "Hi"
    },
    {
      "type": "bid",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 5,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 6,
      "company": "MAIL",
      "price": 80
    },
    {
      "type": "bid",
      "entity": "FloT",
      "entity_type": "player",
      "id": 7,
      "company": "O&I",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 8,
      "company": "MS",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 9,
      "company": "Pass (1)",
      "price": 0
    },
    {
      "type": "bid",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 10,
      "company": "C&WI",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "FloT",
      "entity_type": "player",
      "id": 11,
      "company": "MC",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 12,
      "company": "MPC",
      "price": 60
    },
    {
      "type": "bid",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 13,
      "company": "SC",
      "price": 40
    },
    {
      "type": "par",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 14,
      "corporation": "GT",
      "share_price": "100,0,10"
    },
    {
      "type": "par",
      "entity": "FloT",
      "entity_type": "player",
      "id": 15,
      "corporation": "ERIE",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 16,
      "corporation": "IC",
      "share_price": "90,0,9"
    },
    {
      "type": "par",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 17,
      "corporation": "B&O",
      "share_price": "80,0,8"
    },
    {
      "type": "par",
      "entity": "FloT",
      "entity_type": "player",
      "id": 18,
      "corporation": "C&O",
      "share_price": "80,0,8"
    },
    {
      "type": "pass",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "buy_shares",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "B&O_1"
      ]
    },
    {
      "type": "pass",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 23,
      "hex": "B16",
      "tile": "6-0",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 24,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 25,
      "hex": "G9",
      "tile": "57-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 26,
      "hex": "G7",
      "tile": "57-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 27,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "id": 28,
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 29,
      "hex": "E19",
      "tile": "9-0",
      "type": "lay_tile",
      "entity": "ERIE",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 30,
      "hex": "E17",
      "tile": "293-0",
      "type": "lay_tile",
      "entity": "ERIE",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 31,
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 32,
      "type": "buy_train",
      "price": 80,
      "train": "2-2",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 33,
      "type": "undo",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 34,
      "type": "undo",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 35,
      "type": "undo",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 36,
      "type": "undo",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 37,
      "type": "undo",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "type": "sell_shares",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 38,
      "shares": [
        "ERIE_1"
      ],
      "percent": 10,
      "share_price": 70
    },
    {
      "id": 39,
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "id": 40,
      "type": "undo",
      "entity": "ERIE",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 41,
      "hex": "E19",
      "tile": "9-0",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 42,
      "hex": "E17",
      "tile": "293-0",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 43
    },
    {
      "type": "buy_train",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 44,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 45,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 46
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 47
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 48
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 49,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 50,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 51
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 52
    },
    {
      "type": "sell_shares",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 53,
      "shares": [
        "C&O_1",
        "C&O_2"
      ],
      "percent": 20,
      "share_price": 70
    },
    {
      "type": "lay_tile",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 54,
      "hex": "H16",
      "tile": "8-0",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 55,
      "hex": "G15",
      "tile": "6-1",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 56
    },
    {
      "type": "buy_train",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 57,
      "train": "2-6",
      "price": 80
    },
    {
      "id": 58,
      "type": "buy_train",
      "price": 80,
      "train": "2-7",
      "entity": "C&O",
      "entity_type": "corporation"
    },
    {
      "id": 59,
      "type": "undo",
      "entity": "C&O",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 60
    },
    {
      "type": "pass",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 62
    },
    {
      "id": 63,
      "city": "I5-0-0",
      "slot": 1,
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 64,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 65,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 66,
      "hex": "I3",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 67,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 68,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 69,
      "hex": "J4",
      "tile": "8-1",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 70,
      "hex": "I3",
      "tile": "8-2",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 71
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 72,
      "train": "2-7",
      "price": 80
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 73,
      "company": "MAIL",
      "price": 10
    },
    {
      "type": "buy_train",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 74,
      "train": "4-0",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 75
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 76,
      "hex": "B16",
      "tile": "619-0",
      "rotation": 4
    },
    {
      "id": 77,
      "hex": "B14",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 78,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 79,
      "type": "buy_train",
      "price": 160,
      "train": "4-1",
      "entity": "GT",
      "variant": "3/5",
      "entity_type": "corporation"
    },
    {
      "id": 80,
      "hex": "C13",
      "tile": "9-2",
      "type": "lay_tile",
      "entity": "MS",
      "rotation": 1,
      "entity_type": "minor"
    },
    {
      "id": 81,
      "type": "undo",
      "entity": "MS",
      "entity_type": "minor"
    },
    {
      "id": 82,
      "type": "undo",
      "entity": "MS",
      "entity_type": "minor"
    },
    {
      "id": 83,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 84,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 85,
      "hex": "C13",
      "tile": "9-1",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 1,
      "entity_type": "corporation"
    },
    {
      "id": 86,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 87,
      "hex": "C13",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 88
    },
    {
      "type": "buy_train",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 89,
      "train": "4-1",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 90,
      "hex": "C11",
      "tile": "8-3",
      "rotation": 4
    },
    {
      "id": 91,
      "type": "run_routes",
      "entity": "MS",
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ],
      "entity_type": "minor"
    },
    {
      "id": 92,
      "type": "undo",
      "entity": "BIG4",
      "entity_type": "minor"
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 93,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 94,
      "hex": "G7",
      "tile": "619-1",
      "rotation": 4
    },
    {
      "type": "run_routes",
      "entity": "BIG4",
      "entity_type": "minor",
      "id": 95,
      "routes": [
        {
          "train": "2-1",
          "connections": [
            [
              "G9",
              "G7"
            ]
          ]
        }
      ]
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 96
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 97,
      "routes": [
        {
          "train": "4-1",
          "connections": [
            [
              "C15",
              "B16"
            ],
            [
              "B18",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "id": 98,
      "kind": "payout",
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 99,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 100,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 101
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 102,
      "company": "MC",
      "price": 40
    },
    {
      "id": 103,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 104,
      "type": "sell_shares",
      "entity": "IC",
      "shares": [
        "IC_1"
      ],
      "percent": 10,
      "entity_type": "corporation",
      "share_price": 70
    },
    {
      "id": 105,
      "type": "buy_company",
      "price": 30,
      "entity": "IC",
      "company": "C&WI",
      "entity_type": "corporation"
    },
    {
      "id": 106,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 107,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 108,
      "city": "D6-0-3",
      "slot": 0,
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 109,
      "hex": "E7",
      "tile": "8-4",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 110,
      "hex": "F6",
      "tile": "8-5",
      "type": "lay_tile",
      "entity": "IC",
      "rotation": 3,
      "entity_type": "corporation"
    },
    {
      "id": 111,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 112,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 113,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 114,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 115,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 116,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 117
    },
    {
      "type": "sell_shares",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 118,
      "shares": [
        "IC_1"
      ],
      "percent": 10,
      "share_price": 70
    },
    {
      "type": "buy_company",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 119,
      "company": "C&WI",
      "price": 50
    },
    {
      "id": 120,
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "id": 121,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "type": "place_token",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 122,
      "city": "D6-0-3",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 123,
      "hex": "E7",
      "tile": "8-4",
      "rotation": 0
    },
    {
      "type": "lay_tile",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 124,
      "hex": "F6",
      "tile": "8-5",
      "rotation": 3
    },
    {
      "id": 125,
      "type": "run_routes",
      "entity": "IC",
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "I1",
              "I3",
              "J4",
              "K3"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 126,
      "type": "undo",
      "entity": "IC",
      "entity_type": "corporation"
    },
    {
      "type": "run_routes",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 127,
      "routes": [
        {
          "train": "2-7",
          "connections": [
            [
              "I1",
              "I3",
              "J4",
              "K3"
            ]
          ]
        },
        {
          "train": "4-0",
          "connections": [
            [
              "G9",
              "G7"
            ],
            [
              "G7",
              "F6",
              "E7",
              "D6"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 128,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 129
    },
    {
      "type": "pass",
      "entity": "IC",
      "entity_type": "corporation",
      "id": 130
    },
    {
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 131
    },
    {
      "type": "lay_tile",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 132,
      "hex": "E17",
      "tile": "294-0",
      "rotation": 0
    },
    {
      "type": "run_routes",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 133,
      "routes": [
        {
          "train": "2-2",
          "connections": [
            [
              "E21",
              "E23"
            ]
          ]
        },
        {
          "train": "2-3",
          "connections": [
            [
              "E21",
              "E19",
              "E17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 134,
      "kind": "half"
    },
    {
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 135
    },
    {
      "type": "pass",
      "entity": "ERIE",
      "entity_type": "corporation",
      "id": 136
    },
    {
      "id": 137,
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "id": 138,
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "type": "sell_shares",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 139,
      "shares": [
        "B&O_2",
        "B&O_3",
        "B&O_4"
      ],
      "percent": 30,
      "share_price": 60
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 140,
      "company": "SC",
      "price": 40
    },
    {
      "type": "buy_company",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 141,
      "company": "BIG4",
      "price": 40
    },
    {
      "type": "lay_tile",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 142,
      "hex": "G19",
      "tile": "14-0",
      "rotation": 1
    },
    {
      "id": 143,
      "hex": "G11",
      "tile": "7-0",
      "type": "lay_tile",
      "entity": "B&O",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 144,
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "id": 145,
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "id": 146,
      "type": "undo",
      "entity": "B&O",
      "entity_type": "corporation"
    },
    {
      "type": "assign",
      "entity": "SC",
      "entity_type": "company",
      "id": 147,
      "target": "G19",
      "target_type": "hex"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 148
    },
    {
      "type": "run_routes",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 149,
      "routes": [
        {
          "train": "2-4",
          "connections": [
            [
              "G21",
              "G19"
            ]
          ]
        },
        {
          "train": "2-5",
          "connections": [
            [
              "H20",
              "G19"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 150,
      "kind": "half"
    },
    {
      "type": "buy_train",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 151,
      "train": "4-2",
      "price": 180,
      "variant": "4"
    },
    {
      "type": "pass",
      "entity": "B&O",
      "entity_type": "corporation",
      "id": 152
    },
    {
      "type": "pass",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 153
    },
    {
      "type": "pass",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 154
    },
    {
      "type": "run_routes",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 155,
      "routes": [
        {
          "train": "2-6",
          "connections": [
            [
              "I15",
              "I17"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 156,
      "kind": "half"
    },
    {
      "type": "buy_train",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 157,
      "train": "4-3",
      "price": 160,
      "variant": "3/5"
    },
    {
      "type": "pass",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 158
    },
    {
      "type": "buy_company",
      "entity": "C&O",
      "entity_type": "corporation",
      "id": 159,
      "company": "O&I",
      "price": 32
    },
    {
      "type": "buy_shares",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 160,
      "shares": [
        "GT_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "FloT",
      "entity_type": "player",
      "id": 161,
      "shares": [
        "ERIE_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 162,
      "shares": [
        "IC_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 163,
      "shares": [
        "B&O_5"
      ]
    },
    {
      "type": "pass",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 164
    },
    {
      "type": "buy_shares",
      "entity": "FloT",
      "entity_type": "player",
      "id": 165,
      "shares": [
        "C&O_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 166,
      "shares": [
        "B&O_6"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 167,
      "shares": [
        "B&O_7"
      ]
    },
    {
      "type": "pass",
      "entity": "Gamebhoy",
      "entity_type": "player",
      "id": 168
    },
    {
      "type": "pass",
      "entity": "FloT",
      "entity_type": "player",
      "id": 169
    },
    {
      "type": "pass",
      "entity": "Kain00",
      "entity_type": "player",
      "id": 170
    },
    {
      "type": "pass",
      "entity": "Pitchfork",
      "entity_type": "player",
      "id": 171
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 172,
      "hex": "D10",
      "tile": "8-6",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MS",
      "entity_type": "minor",
      "id": 173,
      "hex": "D8",
      "tile": "9-2",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "MS",
      "entity_type": "minor",
      "id": 174,
      "routes": [
        {
          "train": "2-0",
          "connections": [
            [
              "C15",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "company",
      "id": 175,
      "hex": "B10",
      "tile": "9-3",
      "rotation": 1
    },
    {
      "type": "lay_tile",
      "entity": "MC",
      "entity_type": "company",
      "id": 176,
      "hex": "B12",
      "tile": "9-4",
      "rotation": 1
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 177,
      "company": "MS",
      "price": 1
    },
    {
      "type": "buy_company",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 178,
      "company": "MPC",
      "price": 1
    },
    {
      "type": "assign",
      "entity": "MPC",
      "entity_type": "company",
      "id": 179,
      "target": "D6",
      "target_type": "hex"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 180
    },
    {
      "id": 181,
      "city": "D6-0-2",
      "slot": 0,
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 182,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 183,
      "hex": "B14",
      "tile": "9-5",
      "rotation": 1
    },
    {
      "id": 184,
      "hex": "C15",
      "tile": "294-1",
      "type": "lay_tile",
      "entity": "GT",
      "rotation": 0,
      "entity_type": "corporation"
    },
    {
      "id": 185,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "lay_tile",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 186,
      "hex": "D6",
      "tile": "298-0",
      "rotation": 0
    },
    {
      "id": 187,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 188,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 189,
      "city": "298-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 190,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 191,
      "city": "298-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 192,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 193,
      "city": "298-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 194,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 195,
      "city": "298-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 196,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 197,
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 198,
      "type": "run_routes",
      "entity": "GT",
      "routes": [
        {
          "train": "4-1",
          "connections": [
            [
              "C5",
              "D6"
            ],
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ],
            [
              "C15",
              "B16"
            ],
            [
              "B18",
              "B16"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 199,
      "kind": "payout",
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 200,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 201,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 202,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 203,
      "city": "298-0-1",
      "slot": 0,
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "id": 204,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "pass",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 205
    },
    {
      "id": 206,
      "type": "run_routes",
      "entity": "GT",
      "routes": [
        {
          "train": "4-1",
          "connections": [
            [
              "C5",
              "D6"
            ],
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ],
            [
              "C15",
              "B16"
            ],
            [
              "B18",
              "B16"
            ]
          ]
        }
      ],
      "entity_type": "corporation"
    },
    {
      "id": 207,
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation"
    },
    {
      "type": "run_routes",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 208,
      "routes": [
        {
          "train": "4-1",
          "connections": [
            [
              "C5",
              "D6"
            ],
            [
              "C15",
              "C13",
              "C11",
              "D10",
              "D8",
              "D6"
            ],
            [
              "C15",
              "B16"
            ],
            [
              "B18",
              "B16"
            ]
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 209,
      "kind": "payout"
    }
  ],
  "loaded": true,
  "created_at": 1593541227,
  "updated_at": 1593548941
}

**Comment by tobymao** [comment]
yep thanks

**Comment by michaeljb** [comment]
@cw67q I took a look at this game, and the site has the correct behavior.

Grand Trunk runs a 3/5 train visiting 5 locations (C5/Chicago Connections, D6/Chicago, C15/Detroit, B16/Port Huron, and B18/Sarnia), earning in 3 locations and skipping 2; at least one of the locations it earns in must have a Grand Trunk token in it.

Because of East-West bonuses, the three locations that together earn the most money for Grand Trunk's 3/5 train are Chicago Connections, Detroit, and Sarnia.

The Meat Packing Company in Chicago only adds revenue if the train earns in Chicago, rather than skipping it.

**Comment by cw67q** [comment]
Hi Michael, thanks for your reply I missed it at the time but the GT player mentioned it today when we got together for another game. He was surprised as he thought he'd run to Chicago but it was first time that we used the website. 
Regards, chris
