### ISSUE TITLE
[1841] priority_deal_player needs to be overridden

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9448]
Frozen game to be deleted.

Thank you.

**Comment by roseundy** [comment]
https://18xx.games/game/132487?action=837 is the last valid action. Seems to be starting a merger.

**Comment by roseundy** [comment]
Bug is that the default Game method `priority_deal_player` couldn't deal with the combination of a player bankruptcy and players becoming the current_entity in an operating round.

**Comment by roseundy** [comment]
Deployed, you should have access to your game now.
