### ISSUE TITLE
[1841] Incorrect Forced Train Purchase

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9462]
Link to game and move: https://18xx.games/game/130763?action=808

CGTF has tokens in two cities without any track, thus has no legal route on which it may run a train. However, game is requiring CGTF to purchase an available train.

**Comment by roseundy** [comment]
Thanks for the report. I'll take a detailed look in a bit, but I suspect the problem is that my code doesn't handle the "recycling" of a corporation completely. I needs to forget that CGTF had a legal route in its prior life.

**Comment by roseundy** [comment]
My suspicion was confirmed.
