### ISSUE TITLE
[1848 Australia] Rulebook link leads to incorrect version

### ISSUE THREAD

**Issue by NikoC75** [tobymao/18xx#9464]
**GAME ID: 131861 (but no specific configuration needed)**
https://18xx.games/game/131861?action=556 (or any starts of SR (but the 1st one))

The rulebook states, at 12.4.1 (12.14.1 CORRECTED) , first point; "In the first round of each SR you are not allowed to sell any
shares." 

Except on first SR, where no sells at all are allowed (5.1.6), the interface lets us sell shares as soon as a SR starts

**Comment by scottredracecar** [comment]
Weird rule, someone should check the original German rules for this. Could be another translation error?

**Comment by philcampeau** [comment]
This rule doesn't appear in the original rules. I suspect it's an error in the GMT rules: 
http://www.ohley.de/english/1848/1848-rules.pdf

**Comment by philcampeau** [comment]
There is no rule 12.14.1 in the GMT rules, and that sentence doesn't appear in the rules. Where did you see this?

**Comment by philcampeau** [comment]
No such rule exists. Closing unless further evidence of this rule is provided.

**Comment by NikoC75** [comment]
I opened the document linked on the info tab of any 1848 games, page 14

**Comment by philcampeau** [comment]
Section 12 ends with 12.7, there is no 12.14.1

**Comment by NikoC75** [comment]
12.4.1... sorry!!!!

**Comment by philcampeau** [comment]
Those look like a pre-final version of the rules. Here is rule 12.4.1 from the final rules on GMT's site: 

![image](https://github.com/tobymao/18xx/assets/26125362/35cce59a-720c-40e3-b777-762353a39f92)

https://gmtwebsiteassets.s3.us-west-2.amazonaws.com/1848/1848-RULES-FINAL.pdf

That said, now i understand the actual problem. The site links to the wrong version of the rules. I'll fix that.

**Comment by NikoC75** [comment]
Perfect.
Thanks
