### ISSUE TITLE
1822Africa - E-train not counted correctly

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#9476]
In this hotseat game, this (E) route should be counted as:
2* (30+20+40+30*2) = 300
https://gist.github.com/scottredracecar/4ebc80a244f8152652d724b0b0d0c21f

Sorry, I can't figure out what is causing it to count 270.

<img width="1183" alt="image" src="https://github.com/tobymao/18xx/assets/29106780/5a53945e-0ea3-447d-be27-a470d751e58b">

@vandamm

**Comment by scottredracecar** [comment]
Same gist, this should not be counted as an E (lacking two tokened revenue locations).
<img width="1204" alt="image" src="https://github.com/tobymao/18xx/assets/29106780/8a1f9db3-cfc4-4740-ba7b-4c153ee24fc6">

**Comment by vandamm** [comment]
* Looks like in your first example destination is not quadrupled, but only tripled.
* Second one, I'll add a restriction
