### ISSUE TITLE
1862: Cannot buy share if president's share only share to buy and only at 20% holding

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#9483]
https://18xx.games/game/130396?action=892
https://gist.github.com/ventusignis/3386f6019aac56cb8aa17a974f8716d6

It appears that in this case where the president's share of ECR is in the market, and everyone has bought the 10% shares so that nobody has more than 20%, that nobody is able to buy a third share to get the presidency

![image](https://github.com/tobymao/18xx/assets/2993555/9da49ddd-9e8f-4e88-ba12-89679e0797a6)

**Comment by ventusignis** [comment]
> To gain the director’s certificate from the Bank Pool a player needs
to hold at least three ordinary share certificates in the company.

Is this rules as written?

**Comment by roseundy** [comment]
Yes. You never buy the director's certificate directly.

**Comment by roseundy** [comment]
![1862_rule_snippet](https://github.com/tobymao/18xx/assets/8494213/56f029f8-681e-4df6-9265-31e23075a731)
