### ISSUE TITLE
[1822Africa] GameError: Cannot afford bid. Maximum possible bid is 43

### ISSUE THREAD

**Issue by rrokkam** [tobymao/18xx#9490]
```
We're sorry this game cannot be continued due to GameError: Cannot afford bid. Maximum possible bid is 43
Broken action: { "type": "bid", "entity": 3861, "entity_type": "player", "id": 312, "created_at": 1693163628, "company": "P1", "price": 50 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822Africa,%22needs%20triage%22) and include this link (https://18xx.games/game/133106?action=311)
```

**What's your Game ID?**
https://18xx.games/game/133106?action=311

**How to Reproduce the Bug?**
Not sure exactly how to reproduce - this happened while bidding in the stock round. There were some undos involved.
Sorry this isn't particularly helpful. Hopefully the error message is enough of a clue.

**Which Browser / Platform?**
Chrome 116.0.5845.96

**Comment by rrokkam** [comment]
The game is stuck in progress, too - I can't end it. I'm not sure how to forcibly end it, but if you know how (or who might know how), removing game 133106 would be great.

**Comment by vandamm** [comment]
This happened because a new 1822Africa version was deployed that made your game invalid. This happens often with titles that are in active development.
