### ISSUE TITLE
1822Africa - Don't apply loan interest after SR X.1 (1 of 2)

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#9493]
I guess I am too good of an 1822 player such that I did not run into major loan problems in my solo testing.

The current implementation is extra harsh as the loan interest is applied after each of the back-to-back SRs. I want to remove the application of loan interest after SRX.1 (1 of 2) and I adjusted the rules doc now to reflect that.

This action is right after SR5.1 and loan interest is applied. 
https://18xx.games/game/132767?action=327

**Comment by vandamm** [comment]
Yeah I saw this but thought it was intended 🦀

**Comment by scottredracecar** [comment]
50% interest per round is already pretty sharp!
