### ISSUE TITLE
[1822MX] excess tokens disappear instead of returning to Major's "Available" tokens

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#9494]
gist - https://gist.github.com/michaeljb/a4442c112337d0e95a858c7a8b10d004

* MC acquired Minors 12 and 13, so it has two tokens on L19
* MC has 1 Available token and 1 Exchange token
* MC upgrades L19 to green, joining the two cities up; one token is removed from the city
* MC still has 1 Available token and 1 Exchange token; the second token from the map is just gone

Rule 6.11.7 (emphasis mine), from page 19:

> In most cases, a company may not have more than one token in a hex. The tiles and off-board areas show the conventional grouping of slots by enclosing them in an oval. However, there are some exceptions in hexes with preprinted track on the board which start with separate unconnected token slots. The upgrade paths for these cities are a single merged city. It is possible, typically via minor company acquisition or via the NdeM privatization token auction, that a company has multiple tokens on the same hex that are not in the same grouping. This is allowed, and when these tokens merge, **extra tokens in excess of one are returned to the “Available” section of the charter for use** following the normal rules.

This will also be necessary for #9376

**Comment by scottredracecar** [comment]
This should be implemented in “base” 1822 (although it is not needed for that game) or some future base 1822 class. This is the standard practice for dealing with tokens in this kind of situation.
