### ISSUE TITLE
[1822africa] Extra Tile Lay (P7) doesn't work

### ISSUE THREAD

**Issue by otdewiljes** [tobymao/18xx#9499]
https://18xx.games/game/133199

Extra Tile Lay private action does nothing. Not before normal track lay, not in a major, not in a minor.

**Comment by scottredracecar** [comment]
Boris ended this game with this private in hand, not in a company. Must be acquired to use (common rule for all of 1822).

**Comment by otdewiljes** [comment]
Yes, we undid the move, obviously

**Comment by scottredracecar** [comment]
Can you link to the action when that happened?

**Comment by scottredracecar** [comment]
I can reproduce the problem from this action. Please submit the action along with the issue report when possible to help the person who will fix the bug. (use step backward to find the right action) Thanks.

https://18xx.games/game/133199?action=350

**Comment by WayneWWms** [comment]
Same issue in https://18xx.games/game/132981.  NAR acquired Extra Track Lay (P7):  -- 2023-09-01 --
[00:10] NAR acquires P7 (Extra tile) from WayneWilliams
[00:10] NAR passes acquire private companies
[00:10] NAR lays tile #63 with rotation 0 on E11 (Kinshasa)

But can't use the extra track lay function.

**Comment by vandamm** [comment]
@WayneWWms it's a bug and I'm working on it. Count P7 as not implemented for now.

**Comment by vandamm** [comment]
This was hard to figure out, but I've finally submitted a PR with a full fix
