### ISSUE TITLE
General enhancement: Retain finished games in "your games" until dismissed.

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#950]
Currently when a game is finished, it is banished to the "finished games" underneath your profile.

I think this is slightly clumsy and causes much of the end game discussion to vanish as people don't find the game anymore or forget to check on it.

I propose that the finished games (gray) would stay in the "YOUR GAMES" listing, but would get a "Hide" button next to the enter. Once this "Hide" button is pressed, only then it is cleared from the "Your games" listing.

**Comment by tobymao** [comment]
will solve this with rmakls

**Comment by tobymao** [comment]
emails
