### ISSUE TITLE
1822Africa - Fractional payout

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#9500]
Log shows a fractional payout here.
https://18xx.games/game/133199?action=350

**Comment by scottredracecar** [comment]
@michaeljb have you noticed this in your other 1822 work? Let me know if you want me to try to reproduce. Is this the right fix for those other games (I could do that)?

**Comment by michaeljb** [comment]
@scottredracecar Yeah it shows up in the logs for other 1822 games as well. It seems fine as a fix. It's another thing to look out for when I start my 1822Base refactoring.

**Comment by vandamm** [comment]
It's not only for 22, 1817 has it too. Basically any game that uses corporation class for minors. It reproduces always and the fix is to actually use Minor class, but that breaks everything :)

**Comment by scottredracecar** [comment]
Ah, well thanks for fixing this one anyhow.
