### ISSUE TITLE
Improvement: Do automatic discard if all trains of the same type

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#951]
Example from 1889:

The TR company owns 4 3T and someone buys a 4T. Now the game ask the TR company to choose which of the 4 3T to discard...

Instead the game could have selected one of them automatically and just logged that it had discarded it.

Now this might not be a realistic example but it happens now and then. Note, it should only be automatic if ALL games are of the same type. It is likely that the company always want to discard the lowest trains but there might be some use case for discarding a more expensive train.

**Comment by jenf** [comment]
I don't think we'll ever implement this, there's an advantage to not doing so, as it makes it clearer why a player has lost trains.
