### ISSUE TITLE
[1822africa] Game end for max stock value implemented incorrectly

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#9516]
Game ID 132776

Link: https://18xx.games/game/132776

In OR5.1 EAR hit max stock value which is supposed to trigger game end at the end of an OR (OR5.1).
Header announces that game will end at conclusion of OR5.2.

**Comment by scottredracecar** [comment]
That's correct. It's supposed to end after the OR the price is hit.
However, the other endgame triggered first (can't refill BBs).

My intention was that the stock market trigger could overrule the refill
trigger as Jimmy deduced. I now clarified this in the rules.

Jimmy, your game is over and you can undo the end of OR5.1 and manually end
it.
