### ISSUE TITLE
Email notifications, game link is a redirect

### ISSUE THREAD

**Issue by MadFedor** [tobymao/18xx#9517]
This was the first time Google showed this warning after a few dozen email notifications.

**How to Reproduce the Problem?**
Click the game link in the email.

What steps cause the unexpected behavior?
Google mail stops the link and shows a warning that it is attempting to redirect.

- Browser Version
  - On Firefox, most recent version
- Platform Notebook PC

**Comment by tobymao** [comment]
what is your suggested fix?

**Comment by outsidePasser** [comment]
Can you post the link that google was complaining about?

**Comment by tobymao** [comment]
it’s probably the email provider, forward me the email.

**Comment by tobymao** [comment]
i've disabled click tracking
