### ISSUE TITLE
[Harzbahn 1873] Acquiring another players mine is giving "undefined method corporation? for nil"

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9521]
hotseat file:
https://gist.github.com/physic/a073b0b9f5fe200fb77a4bd09556b154

console error
https://gist.github.com/physic/04bff69e8e7c4b62dfa3bf342af40fb5

Steps:
Show mines from other players.
Select a price for the 8.
Purchase.
Confirm consent of the other player.
==> console error

I am blocked from making the purchase.

**Comment by roseundy** [comment]
It helps to tell us which title. I'm guessing 1873?

**Comment by roseundy** [comment]
Wow. Finally had time to debug this. Apparently, nobody had done a cross-player mine purchase before (or at least reported the bug when they tried) :-/
