### ISSUE TITLE
[1841] Stock Round auto-action not being ignored during an Operating Round

### ISSUE THREAD

**Issue by summerjumbo** [tobymao/18xx#9522]
On a 1841 game: https://18xx.games/game/133385
a player could not proceed the sequence of operating round of SFTC.
They could not went beyond the skip trains.
**What's your Game ID?**
15422

**How to Reproduce the Bug?**
go that page and click Skip(trains)

**Which Browser / Platform?**
Opera one101.0.4843.43
and Microsoft Edge 116.0.1938.62

**Comment by roseundy** [comment]
Looks like an infinite loop.

Unfortunately, I'm leaving town in a few minutes. I'll be back on Sunday and diagnose it then.

**Comment by mahonyb** [comment]
The page freezes. No user interaction and no page updates with panning. Most other buttons seem to work, it comes back with a refresh to the press-freezes state. Just can’t proceed to next game started.

**Comment by roseundy** [comment]
I've root-caused this to a programmed auto-action to pass in a stock round erroneously being applied to a corporate financial operation during an operating round.

**Comment by mahonyb** [comment]
Initially, the problem persisted, not sure if that was what you expected.

I switched off auto and now we are on our way again.

Thanks for all your efforts, so cool to be able to revisit this classic after so many years.

**Comment by roseundy** [comment]
I still need to deploy the fix. Glad you were able to make progress.

**Comment by summerjumbo** [comment]
Thanks for fixing!
