### ISSUE TITLE
1841 previous run showing for restarted company

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9525]
https://18xx.games/game/132062?action=746

ICSF is shown with a "previous run" of 310 from its previous incarnation. It's a brand new company and the previous run should be zero (or null).

**Comment by roseundy** [comment]
I'll have to clear out it's history - which means you won't be able to see how much it ran for in the past on the spreadsheet tab.

**Comment by ChrisTheCat** [comment]
Hmm, that is awkward.
