### ISSUE TITLE
1867: Incorrect order of buying shares during merger

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#9536]
https://18xx.games/game/132411

In MR4.1, we merged TN with NO - these were owned by two different players. Formed the CPR. We got one share each (which is correct).

Then we bought shares, but it gave the first option to me (owner of TN) because I was the initiator of the merger. But the rules say "The player with the most shares is the Director, even if that player only owns one share; resolve ties in favour of the player who owned the Minor Company that operated earliest in the Merger Round." But Grinch owned the NO which operated earliest, so he should have been given first go - and therefore he would have been the director (since we both bought 2 shares).

I expect this is wrong in 1861 too.

**Comment by ianwilson156** [comment]
Further rule (to explain): "Starting with the Director .... each player with shares in the new Company is granted an opportunity to buy any number of shares..."
So, I bought some shares then Grinch bought some. (Then all the players were offered to buy one as normal).
In other words, the only bug is the initial assignment of Director .

**Comment by ianwilson156** [comment]
Note that the current implementation probably follows the 3rd edition rules, what I quoted above was from the 2nd edition.

**Comment by ollybh** [comment]
The wording in the Grand Trunk Games rules is (section 9.2c):

> Starting with the active player, exchange every Minor Certificate involved for a 10% share of the Major Company. The first player to hold two 10% shares exchanges them for the President’s certificate. Again starting with the owner of the active Minor, each player with at least one share may now purchase any number of additional shares…

The current behaviour does match this description.

@ianwilson156 Can you confirm that this description in the third edition rules is wrong, and the AAG rules should be followed?

**Comment by ianwilson156** [comment]
Confirmed. The AAG rules are the definitive ones.
