### ISSUE TITLE
[1841] Corp share actions skipped with legal (and required) actions

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9539]
Game and move: https://18xx.games/game/133019?action=554

Due to a merge, AFI owns 2 shares of its parent company CTDA. On AFI's action, it's share dealing step is skipped ("AFI has no valid actions and passes") - however, AFI can sell CTDA shares, and is in fact obligated to do so

**Comment by roseundy** [comment]
CTDA has not operated yet, so it is illegal for AFI to sell its shares.
