### ISSUE TITLE
1841 unable to dump presidency in corporate sale

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9543]
https://18xx.games/game/132062?action=951

I get this error when trying to sell the CCFC share - the SB should be able to exchange with myk and then sell one share.

<img width="546" alt="Screenshot 2023-09-03 at 08 38 38" src="https://github.com/tobymao/18xx/assets/8732435/e46833ec-80b0-4a11-a23d-907c028e60a6">

**Comment by roseundy** [comment]
I biffed the can_sell_any? method for corporation buying/selling of shares by only considering full certificate sales
