### ISSUE TITLE
1841 presidency assigned to wrong entity

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9546]
https://18xx.games/game/132062?action=915

[17:22] AFI sells 3 shares of CFCC and receives L.210
[17:22] SB becomes the president of CFCC
[17:22] CFCC's share price moves down from L.70 to L.32

Rules say "A player is always selected before a Corporation." The presidency should have been assigned to myk the player, and not SB the company.

**Comment by roseundy** [comment]
Untested code -> it has a bug

**Comment by roseundy** [comment]
I tried to account for this by overriding the game method possible_presidents by putting all the corporations after the players, but this doesn't work when wrapping around the player order.

**Comment by roseundy** [comment]
The fix will most likely kill games. Not sure how many.
