### ISSUE TITLE
Prevent cheating in 1846 draft

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#955]
Any player can open the JSON and see what private companies each player has drafted. It would be best if the JSON wasn't available to players until the draft is over. However, it looks like you've rejected that option in issue #888 . 

I, for one, am too cynical about human behavior to play a game that allows cheating with unknown/untrusted opponents. If you don't want to prevent cheating in the 1846 draft, may I offer an alternate suggestion:

Allow players to use an external tool to run the draft, and then start a game on 18xx.games and distribute the private companies manually.

**Comment by tobymao** [comment]
you can also just open up the web insector and inspect the game objects directly, how far do you want to go with anti cheat? it's a slippery slope. happy to continue this discusion in slack
