### ISSUE TITLE
Using in game chat resets share purchases and placing bids in auctions

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9563]
https://18xx.games/game/134264?action=14

As I enter my bid, if another player sends a chat message, the private company I'd selected becomes unselected, and the bid amount I'd entered is erased.

**Comment by michaeljb** [comment]
This is probably just that #9527 should have an `if` check so it doesn’t apply on Message actions

**Comment by tobymao** [comment]
i think fix 9527 was wrong, why don't we clear selected company on secection instead of in the base game recevier?

**Comment by tobymao** [comment]
@michaeljb after they make a steam boat assignment, it should just clear selected companies, can you revert 9527 and do it that way intsead?
