### ISSUE TITLE
[1830][18CZ][1822MX] Privates cannot be acquired

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#9574]
In this game: https://18xx.games/game/133692?action=116 CPR just bought the first 3T and should be able to acquire the player's private companies. Clicking them does not open the expected dialog. This also happens for the other companies and persists in the next OR.

Also happens in another 1830 https://18xx.games/game/133472 if you play to the next OR and buy a 3T.
Also happens in 18CZ: In this game: https://18xx.games/game/133678?action=337 if you withhold with OFE in order to have enough money, the privates can still not be acquired.
Also happens in 1822MX: In this game https://18xx.games/game/133688?action=201 if you play to the next OR, 13 cannot acquire any private companies.

Choosing privates as subsidies in 1817 is not affected.

**Comment by Ticketautomat1** [comment]
https://18xx.games/game/133236

1822 has the same problem
