### ISSUE TITLE
I can place an hex in B20, even if I own the right company

### ISSUE THREAD

**Issue by marcofio21** [tobymao/18xx#9576]
**Game ID - 133493**

https://18xx.games/game/133493

**Which Browser / Platform?**

**Comment by michaeljb** [comment]
This should be fixed by https://github.com/tobymao/18xx/commit/ddcfd9f78d7a954dfbf90b4cda32d45026b2ada2 which also fixed #9574. Refresh the page and see if you're still experiencing the problem.

Will need to look out for this while fixing #9563
