### ISSUE TITLE
[1841] Game stuck at Done(Trains) step

### ISSUE THREAD

**Issue by rrokkam** [tobymao/18xx#9594]
Clicking Done(Trains) on the SSFL's turn returns a 500 server error.

**What's your Game ID?**
https://18xx.games/game/134682

**How to Reproduce the Bug?**
in the above game, click the Done(Trains) step on the SSFL's turn after buying a 3-train.

<img width="1110" alt="Screen Shot 2023-09-12 at 7 59 12 PM" src="https://github.com/tobymao/18xx/assets/33299860/c01101d7-4f87-4756-8612-55f16e952840">

After this, in the console logs there's a 500 error, then the page refreshes to before the Done(Trains) step.

**Which Browser / Platform?**
Chrome 116.0.5845.179

**Comment by michaeljb** [comment]
@roseundy FYI this happened right around when I deployed #9585, I haven't done any additional debugging on this.

**Comment by gmrbluee** [comment]
Have the same problem at game ID 131307

**Comment by summerjumbo** [comment]
I had the same kind of trouble at https://18xx.games/game/133645.
When the first company RATF buys an 8 train from another company, the same message comes and automatically returns to the train buying step.

**Comment by JaySixA** [comment]
I am having a similar problem in https://18xx.games/game/131865.  However I get the error at the Skip (Trains) step.

**Comment by fsaglio** [comment]
Same error in https://18xx.games/game/134283

I get stuck at the "done trains" train, however it only happens if I have bought a train from another company.  If I buy a train from the bank I can move on.

**Comment by KlausKiermeier** [comment]
Same in https://18xx.games/game/134021

**Comment by damerell** [comment]
https://18xx.games/game/132041 has it too

**Comment by roseundy** [comment]
My fix for auto actions was broken and could only be caught on the server. I need to add a parameter to stubbed out auto_actions.

**Comment by roseundy** [comment]
Now deployed.

**Comment by summerjumbo** [comment]
Great! Thanks!
