### ISSUE TITLE
Allow players/corps to keep cash total secret

### ISSUE THREAD

**Issue by spenczar** [tobymao/18xx#9595]
**What's your idea?**

In many 18xx games, player and/or corporate cash can be kept undisclosed. For example, 1889 has's rule 3.4 Fund Disclosure says "corporation money need not be disclosed."

I would like to be able to do this. Player and corporate cash shows up on many screens. Perhaps this would be a setting for the game (like enabling autoroutes) if permitted by the rules. When disclosure is permitted (but not mandatory) players could just use the chat to communicate cash, perhaps.

While cash is always calculable from the log, that is so tedious that I don't think it would be a problem in casual play.

**Are there related ideas?**

I don't think so, based on some searching, but might have missed it.

**Comment by tobymao** [comment]
we do not support hidden trackabkw information
