### ISSUE TITLE
1856 map dissapeared

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9605]
https://18xx.games/game/131339?action=825

When I click on any brown tile, the screen jumps to the top of the page and the map disappears. I replicated it in a cloned game running locally.

**Comment by andycted** [comment]
It happened on a 1850 game, ended now, where plain russet tracks and also many other non upgradable tracks behaved like that

**Comment by H1llsman** [comment]
I have encountered a similar issue in https://18xx.games/game/132814?action=1084

When trying to upgrade a brown city tile to grey

**Comment by zedprotect** [comment]
Happened to me in 1882 and/or 1830 (I don't remember) when I clicked on an non upgradable dot tile.
