### ISSUE TITLE
Special rules for Mark Derrick Games, 18AL

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#961]
(this is a work in progress)

**All**

- [x] Private buy in is 1/2 to 1-1/2x face
- [x] All except 18MS, one train per turn until Phase 4

**18AL**

- [x] Towns don’t count against visits
- [x] Implement private companies

**18AL Tiles**

- [x] yellow 441 elyton/birmingham 10 lolipop
- [x] yellow 445 20 lumber terminal gentle curve town
- [x] yellow 451 atlanta triple lolipop 30
- [x] green 442 birmingham bird foot 2 slots 30
- [x] green 443 montgomery 5-way 2 slots 40
- [x] brown 444 birmingham montgomery 5-way, 2 slots 50
- [x] gray 446 6-way 3city 70 birmingham

See the list on https://github.com/perwestling/18xx/wiki/18AL

**Comment by scottredracecar** [comment]
If someone wants to dive into one of these games, please have at it! Otherwise, I plan to start fleshing out some of these special rules mid-July and will resume work.

Some of these games have map issues that require different tile logic to display right.

Most of these games have special city-specific tile upgrades which aren't defined yet. I listed the ones for GA and AL.

**Comment by perwestling** [comment]
I will to start look at 18AL. That, together with 18MEX, are the only Mark Derrick games I have played.
It will be my first dive into any game at 18xx.games.
After 18AL I intend to start on 18SJ which is a Swedish prototype.

**Comment by perwestling** [comment]
@scottredracecar: I looked through the tiles for 18AL in your list above, and checked what was present in the 18xx.game right now.

**Does exists in the game and look OK**
- 441 - as 441a
- 442 - as 442a
- 443 - as 443a
- 444 - as 444a
- 446

**In 18xx.games but incorrect**
- 445 - missing name and wrong revenue

**Missing in 18AL**
- 451 - not in my game. Atlanta is an off-board hex. And the one on the map matches my game.

So is only correction of 445 needed? The rest done?

I have also two other querries:
1. Coal markers, should they appear on the map?
2. Destinations, should they appear on the map? And/or the company charters?

Otherwise map looks good. Nashville and Mobile hexes can be slightly improved.
Does the game support non-pass-through off-board hexes like Nashville and Mobile?

If I do make any commit for 18AL, should I just put it up as a pull request on master branch, and notify you about it?

**Comment by perwestling** [comment]
I looked into the "All except 18MS, one train per turn until Phase 4" feature, and I do think I have something that could work. But when trying it out I encountered a bug, and the bug does remain even if I remove the implementation.

The situation is this:
- Create a hotseat 18AL with 3 players
- Buy privates
- Float 3 companies (ATN, ABC, L&N)
- Each company lays a tile, does not token, buy a 2T

When the 3rd company does this, and decline any more train buys nothing, then the view does not show anything happening. If one do click on the skip buy button the game crashes with the message "It is not ATN's turn". If checking game data one can see that L&N did buy train, but the pass operation for L&N is missing (id:33). So next operation (id:34) comes for company ATN which bugs the game. It should really have been stock round instead.

Here is the game data for this. (Have repeated this several times.)
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "TR",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "SNAR",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "BLC",
      "price": 70
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "M&C",
      "price": 100
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "NDY",
      "price": 120
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "corporation": "ATN",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "corporation": "ABC",
      "share_price": "60,2,2"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "corporation": "L&N",
      "share_price": "60,2,2"
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "shares": [
        "ATN_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "shares": [
        "ABC_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 11,
      "shares": [
        "L&N_1"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "shares": [
        "ATN_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13,
      "shares": [
        "ABC_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14,
      "shares": [
        "L&N_2"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15,
      "shares": [
        "ATN_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 16,
      "shares": [
        "ABC_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 17,
      "shares": [
        "L&N_3"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 18,
      "shares": [
        "ATN_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 19,
      "shares": [
        "ABC_4"
      ]
    },
    {
      "type": "buy_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 20,
      "shares": [
        "L&N_4"
      ]
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 21
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 23
    },
    {
      "type": "lay_tile",
      "entity": "ATN",
      "entity_type": "corporation",
      "id": 24,
      "hex": "H1",
      "tile": "9-0",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "ATN",
      "entity_type": "corporation",
      "id": 25,
      "train": "2-0",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "ATN",
      "entity_type": "corporation",
      "id": 26
    },
    {
      "type": "lay_tile",
      "entity": "ABC",
      "entity_type": "corporation",
      "id": 27,
      "hex": "G6",
      "tile": "6-0",
      "rotation": 5
    },
    {
      "type": "pass",
      "entity": "ABC",
      "entity_type": "corporation",
      "id": 28
    },
    {
      "type": "buy_train",
      "entity": "ABC",
      "entity_type": "corporation",
      "id": 29,
      "train": "2-1",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "ABC",
      "entity_type": "corporation",
      "id": 30
    },
    {
      "type": "lay_tile",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 31,
      "hex": "B3",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "buy_train",
      "entity": "L&N",
      "entity_type": "corporation",
      "id": 32,
      "train": "2-2",
      "price": 100
    },
    {
      "type": "pass",
      "entity": "ATN",
      "entity_type": "corporation",
      "id": 34
    }
  ],
  "id": "hs_lgtpirfl_1594034348",
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "18AL",
  "description": "",
  "max_players": "3",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-07-06",
  "loaded": true,
  "result": {}
}

**Comment by perwestling** [comment]
[Have now made a pull request for the commit mentioned above.](https://github.com/tobymao/18xx/pull/1010)

**Comment by scottredracecar** [comment]
> @scottredracecar: I looked through the tiles for 18AL in your list above, and checked what was present in the 18xx.game right now.
> So is only correction of 445 needed? The rest done?

Okay, I do have some concern about whether we can/should use letters for named cities since using the letters restricts the tiles that can be placed there, but that is a bigger fix. Possibly a good way is to add a letter when a hex reaches the step before it is upgradeable to the special tile and I think these "a" tiles work with that method.

> 1. Coal markers, should they appear on the map?

I think they should appear as icons.

> 2. Destinations, should they appear on the map? And/or the company charters?

I don't remember destination rules for these games. Do you mean something else? Am I misremembering? Perhaps a redevelopment by Marflow if it exists in your games?

> Otherwise map looks good. Nashville and Mobile hexes can be slightly improved.
> Does the game support non-pass-through off-board hexes like Nashville and Mobile?

I think it does not, if it is a city, the tracks connect as currently configured, but this needs to be fixed.

> Edit: I noticed that Tupelo on my map has a northern exit, so that gives it 4 exits, while the map in 18xx.games has 3 exits, missing the northern one. Is my map (Marflow) or game map correct?

I used the files here as a reference. I might still have mistakes, but Tupelo is a match. I wouldn't use Marflow maps as a reference as any differences between those and these may more likely be errors than intentional changes by the designer.
http://www.diogenes.sacramento.ca.us/18AL_18GA.html

> If I do make any commit for 18AL, should I just put it up as a pull request on master branch, and notify you about it?
You can take over from here, I can't do much more substantive work on these at this point.

**Comment by perwestling** [comment]
@scottredracecar:
"destinations" - the term in the rules are "historical objectives" in 18AL. The company receives 100$ to treasury if it puts a token in the city that is its historical objective. Each company has one, and 3 of them has Birmingham.

Checking the Marflow map from 2016 and the one in your link, the only functional difference I found was that extra exit. I will update my map...

Regarding the 18AL rules I do have the 1.7 version from September 2009, and the link gives 1.64 version.  1.7 version does not specify difference between it and previous (2004) version. Both does include the "historical objective" rule, and also the obsoleteness rule (with rust as optional, but I think it is fine to keep rust rule - that is how I play the game).

About further work I will focus on 18AL. Try to add "historical objectives" to charter, fix the tiles and so on. Private buy rule I will implement for all 4. Remaining work for 18TN/18GA/18MS will have to wait; think 18AL might be a good candidate to get into alpha.

**Comment by perwestling** [comment]
@scottredracecar I have not been able to solve how tile 445 (in 18AL) should be possible to lay (as part of private corporation) on a hex that does not allow its tile placement. As far as I can tell the tile can only be placed on a town hex, not on a non-town hex.  So how to "override" this default behavior for a tile placement? Any ideas? 
It is the same problem with 18MEX I suppose, with the Copper Valley tile.

**Comment by tobymao** [comment]
what is a private corporation? do you mean private company?

if you're wondering how to allow special tile_lays to override rules for
placement, i think that may have to wait for my rewrite

**Comment by perwestling** [comment]
OK. I will put that on hold as well. 

I always have a problem to separate between corporation and company as they do translate to the same word in my language...
