### ISSUE TITLE
1841.   Child Corp can’t EMR.  

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#9614]
https://18xx.games/game/134283

AFI needs to EMR a train, and its parent corporation, SFTC needs to contribute funds.   

The only shares that SFTC owns are shares of AFI.   

If AFI tries to buy a train, we get an error that SFTC needs to sell a share.  

If we try to have SFTC sell its share of AFI, we get an error that the share can’t be sold.   

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by roseundy** [comment]
Yep, looks like a bug. SFTC should be able to sell one share of AFI.

**Comment by roseundy** [comment]
found the bug in emr_can_sell?

**Comment by fsaglio** [comment]
Should this be fixed?  We are still stuck in the same spot.

**Comment by roseundy** [comment]
While it is fixed in our code base, it hasn't been deployed to the website. I'll deploy it this morning.

**Comment by roseundy** [comment]
The fix is now live on 18xx.games
