### ISSUE TITLE
Incorrect tile lay for Brown OO in E5 Rotterdam

### ISSUE THREAD

**Issue by ddholstad99** [tobymao/18xx#962]
E5 Rotterdam Brown OO tile allowed place a tile that moved one of the cities and should not be allowed. 
See https://www.18xx.games/game/3234

**Comment by tobymao** [comment]
https://www.18xx.games/game/3234?action=379

**Comment by tobymao** [comment]
@michaeljb

**Comment by michaeljb** [comment]
Traced the problem to https://github.com/tobymao/18xx/blob/c95af4005dd076998f73d5a440ed07f52b19e7d6/lib/engine/round/base.rb#L144-L156

In this case, `legal_rotations` should return `[1]` but is returning `[1, 3]`.

In general with the tiles in question (59 rotation 1, upgrading to tile 65), `legal_rotations` should return `[1, 5]`, but rotation 5 for tile 65 has track pointing to the top left edge; E5 in 1836Jr30 does not have a hex on its top left border.

![Screenshot from 2020-07-04 12-41-13](https://user-images.githubusercontent.com/1045173/86519014-bd5e5500-bdf3-11ea-819e-95950c29948a.png)

**Comment by jenf** [comment]
Also seen on https://www.18xx.games/game/4372?action=251

**Comment by jenf** [comment]
I believe this is the last issue between 1836jr30 being promoted to production.

**Comment by jenf** [comment]
I think there needs to be an extra check to make sure that the city is still connected to the same exits
