### ISSUE TITLE
[1847 AE] make building regions more colorblind friendly

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9625]
Please add a letter or symbol or something these are basically indistinguishable 
![13D4D79F-7593-4649-BE01-6F072212D29F](https://github.com/tobymao/18xx/assets/73144084/204f00c8-47a3-4712-8cef-256911103075)

**Comment by Galatolol** [comment]
@BellmakerSA Is this all right:

![image](https://github.com/tobymao/18xx/assets/10097748/8f871958-09b3-4ae5-b881-05fb996be5d0)

?

**Comment by BellmakerSA** [comment]
Yeah that works thanks 👍
