### ISSUE TITLE
1841 comparison of Number with NilClass failed

### ISSUE THREAD

**Issue by cwebblax** [tobymao/18xx#9626]
https://18xx.games/game/131968

Error occurs when selecting number of tokens for the SLF and/or SB (Ferdinand Secession). Can choose number of tokens for SB but doesn't work for SLF. Game will not progress as a result.

**Comment by shamblen** [comment]
Same error in https://18xx.games/game/134496 (choosing tokens for SB)

**Comment by roseundy** [comment]
New president calculation failed during asset transfer prior to "floating" a new corporation.

**Comment by shamblen** [comment]
I am still receiving the same error in https://18xx.games/game/134496, after the applied fix.

**Comment by roseundy** [comment]
I don't believe the fix is "live" yet. I'll see if I can deploy this evening.
