### ISSUE TITLE
[1841] Merger between two players gives Presidency to the wrong player

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9640]
Short summary: Trading single shares should happen after all players trade pairs of shares. So a player with 40% should receive the Presidency before an earlier player with 30% has a chance to trade up.

---------

https://18xx.games/game/133609?action=314

Based on my reading of 4.7.4.1, exchanging pairs of shares is carried out in its entirety before exchanging half shares. The text "The first shareholder with 40% of the combined old Corporations must take the Presidency." supports this.

4.7.4.1 Paraphrased:
> Follow the following steps
> - Each old Shareholder exchanges pairs of shares in order. Each player exchanges all pairs [for themselves and their Corps] before proceeding to the next player. ... *The first shareholder with 40% of the combined old Corporations must take the Presidency.*
> - Likewise, exchange half shares.

In the attached game, the Tuscan Merge occurs and Simon (LimeTurtle), exchanges shares first. Simon has 30% of old Corporations. Mark has 40% of old Corporations. Mark should receive the Presidency before shares are traded up. Instead, in the game, Simon was offered the opportunity to trade up his share to two shares and received the Presidency, while Mark's shares were still being displayed as 20% of ATFA and 20% of SSFL.

**Comment by physic** [comment]
I am reading the rules again, and I can see the interpretation now, based on the third bullet point. Perhaps the "first shareholder with 40% [when it is their turn] must take the Presidency [if it hasn't been taken yet]", but the special trade up to the Presidency comes into play before that happens.

It doesn't *feel* right to me, but I can see it now. So I am less sure now :|
The current interpretation definitely feels like it produces a less intuitive result.

These gd rules.

**Comment by physic** [comment]
Here's some more data on this. Seems that it is implemented inconsistently I made a test game to mess with this.

https://gist.github.com/physic/2b454bdd1ef57f6ca03baeb8c1d17ecd
action=353

Another player already has 40%. For some reason, the first player to trade is given the option to pre-emptively trade up to the presidency, but when they decline, pairs are exchanged and the second player is not given the option.

My guess is that it is only offering this special pre-emptive trade up to the outgoing president, when it should be offered to every player [later, after exchanging pairs]).

**Comment by roseundy** [comment]
Be aware the rules are a little vague on whether this "trade up" opportunity is given to players and corporations or just players. A strict reading suggests the latter (and is what I have implemented).

**Comment by physic** [comment]
> Well, that is not certainly the intention of my code.
> 
> All players with multiple shares of the outgoing corporations should be given the opportunity to "trade" up for a president's share before the single-share round happens.
> 
> I won't be able to investigate this until at least tonight.

All players with even a single share of the old corporations should be given the opportunity to trade up.

**Comment by roseundy** [comment]
My code is intended to allow that.

**Comment by roseundy** [comment]
Looking at your gist, I'm not sure I see the problem. Caro gets the presidency because he traded in his pair of shares first and thus had the opportunity to trade up to a pres share before Eli or Fred traded in their four shares.

Are you asking why Caro went first? If so, it's because of bullet three of section 4.6.10 (SSLF had a better share price than AFI).

**Comment by physic** [comment]
If Caro declines, Drew doesn't get the option to trade up to the Presidency. Either they should both get an option or neither of them should. (I think the latter is correct, but I can see both interpretations)

**Comment by physic** [comment]
Oh. Wait, I think I understand how you have it coded. Because D doesn't have a pair, D is skipped and E and F trade pairs before D would get the option.

**Comment by physic** [comment]
Ugh. I hate how that actually makes sense.

**Comment by physic** [comment]
Okay, So I remember why I didn't like this interpretation. What happens if there are only pairs of shares, when Caro goes to trade?

**Comment by physic** [comment]
https://gist.github.com/physic/ab59810dc4d6a98009998d65f09299c6

I see that you have handled this case. Caro trades up, and then when Bob goes to trade pairs, there are no shares left. The rules don't acknowledge this possibility or how to handle it, which I suppose is why I assumed players are guaranteed to be allowed to trade their pairs of shares.

**Comment by roseundy** [comment]
OK, but I guess I don't see where any "interpretation" is involved here (other parts of the rules, sure). The rules are pretty clear about what order players and corporations are offered a chance to exchange shares. I agree that the "trade up" rule could have been better integrated with the rest of the procedure.

**Comment by physic** [comment]
I'm not saying your interpretation is wrong. But unless there is only one reasonable conclusion, then almost by definition, any conclusion requires interpretation.

The first shareholder with 40% of the combined old Corporations must take the Presidency. First, it does not say "[When it is their turn to exchange shares] they must take the Presidency [unless it has already been claimed]" so one could argue that this line in the rules is violated when this player never takes the Presidency.
Second, given that there are multiple references to 40% being the threshold for taking the Presidency, given that the third bullet point exists, wholly or in part, in order to allow merges to go through where no one has 40%, and given that "claimed" is not clearly defined, this line could be interpreted as meaning that if someone has 40% of the old Corporation, they are under obligation to take the Presidency, and thus it has already been "claimed." That is to say, "If the new Presidency has not been claimed" is intended to mean "If no player had 40% and no player has yet traded up to the Presidency." (This notion about the intent of the third bullet point being only to allow mergers to go through, combined with sloppy or incorrect use of the terms player/shareholder elsewhere in the rules, combined with the fact that the third bullet point is the one place in the rules with $'s instead of L. and was clearly not proofread, are also why I suspect it is intended to apply to all shareholders, but I digress)

Those nuances aside, which I admit are at least somewhat tenuous, it is definitely up to interpretation that in the last edge case I provided, Bob has a pair of old shares and receives $127 and no share. There is no dispensation in the rules for a player being unable to trade in a pair of shares, or for whether or how they should be compensated.
