### ISSUE TITLE
[1841] When a player does the "special trade up" to the Presidency, the company does not receive the money

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9648]
https://gist.github.com/physic/ab59810dc4d6a98009998d65f09299c6

SFLi's consituents' treasuries before merge: L.339
Money paid to buy share: L.127
SFLi's treasury after merge: L.339

While I was responding to #9640 I realized that the SFLi was not receiving any money when the player paid to upgrade to the Presidency. The 1841 rules usually specify the recipient of a payment, even when that recipient is the bank. For this particular purchase, the recipient is not specified, but it seems the most reasonable, since all other monies from trading up shares are paid to the company treasury, and in general trading up one share in this manner will result in one less share ending up in the company's IPO. (The attached game is an outlier in this regard, since there are no shares in IPO before the merge, but that should not affect this rule)

**Comment by roseundy** [comment]
I definitely got this wrong.

The rules are a little funky here. During the exchange, if you have just a single share you can either sell it - with the money coming from the bank, or upgrade it - with the money going to the new corporation. I got the first part right.
