### ISSUE TITLE
Rolling Stock Stars hung games

### ISSUE THREAD

**Issue by charliewilsonstaindrop** [tobymao/18xx#9656]
(Some) games of Rolling Stock Stars are hung and cannot be opened by either game players or non-playing people.
https://18xx.games/game/135200 and https://18xx.games/game/135203
A previous bug report (#9642) reported this and has been closed as the problem was believed solved.  The fault is still extant.

**How to Reproduce the Bug?**

Try to enter the game and get the response "Loading game...." but nothing else happens.  Unable to force the bug as I have no idea what is causing it or what state the game is in as I can't load it!

**Which Browser / Platform?**

Multiple browser/platforms
In my case MS Edge on  laptop running Windows 10

**Comment by crericha** [comment]
The fix hasn't been deployed yet. It should be deployed in the next few days. Thanks for your patience.

**Comment by scottredracecar** [comment]
The last deployed code was on Monday so that fix isn't live yet. See last
update here:
https://18xx.games/about

**Comment by charliewilsonstaindrop** [comment]
Thank you for the update.
 
We will contain our impatience. 
 
All the best
Charlie
"From the Sea, Freedom."



 

----- Original Message -----
From: Chris Rericha ***@***.***>
Reply-To: tobymao/18xx 
***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author 
***@***.***>
Sent: 21/09/2023 17:03:34
Subject: Re: [tobymao/18xx] Rolling Stock Stars hung games (Issue #9656)



The fix hasn't been deployed yet. It should be deployed in the next few days. Thanks for your patience.

**Comment by charliewilsonstaindrop** [comment]
Thanks Scott.
"18xx.games/about" was not somewhere I would normally venture not having being 
aware what useful current info might be lurking there. 
I now know.
 
Thanks again
Charlie
"From the Sea, Freedom."



 

----- Original Message -----
From: scottredracecar ***@***.***>
Reply-To: tobymao/18xx 
***@***.***>
To: tobymao/18xx ***@***.***>
Cc: charliewilsonstaindrop ***@***.***>, Author 
***@***.***>
Sent: 21/09/2023 17:03:38
Subject: Re: [tobymao/18xx] Rolling Stock Stars hung games (Issue #9656)



The last deployed code was on Monday so that fix 
isn't live yet. See last 
update here: 
https://18xx.games/about 


On Thu, Sep 21, 2023 at 8:54 AM charliewilsonstaindrop < 
***@***.***> wrote: 

> (Some) games of Rolling Stock Stars are hung and cannot be opened by 
> either game players or non-playing people. 
> https://18xx.games/game/135200 and https://18xx.games/game/135203 
> A previous bug report (#9642 <https://github.com/tobymao/18xx/issues/9642>) 
> reported this and has been closed as the problem was believed solved. The 
> fault is still extant. 
> 
> *How to Reproduce the Bug?* 
> Try to enter the game and get the response "Loading game...." but nothing 
> else happens. Unable to force the bug as I have no idea what is causing it 
> or what state the game is in as I can't 
load it! 
> 
> *Which Browser / Platform?* 
> Multiple browser/platforms 
> 
> In my case MS Edge on laptop running Windows 10 
> 
> — 
> Reply to this email directly, view it on GitHub 
> <https://github.com/tobymao/18xx/issues/9656>, or unsubscribe 
> <https://github.com/notifications/unsubscribe-
auth/AG6CEXESWFHI3Z55UYVUZXTX3RPNHANCNFSM6AAAAAA5BY22UY> 
> . 
> You are receiving this because you are subscribed to this thread.Message 
> ID: ***@***.***> 
> 

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>
