### ISSUE TITLE
[Rolling Stock Stars] Active Game Inaccessible - Loading game... with blank screan

### ISSUE THREAD

**Issue by jbmoles** [tobymao/18xx#9661]
**How to Reproduce the Problem?**

Enter game: https://18xx.games/game/134891

What steps cause the unexpected behavior?
From main page, enter game or access via the URL listed above.

Please include screenshots (you can drag and drop or upload them into this issue)

Chrome Dev tools console log attached

[18xx.games-1695401048924.log](https://github.com/tobymao/18xx/files/12702830/18xx.games-1695401048924.log)
**Which Browser / Platform?**
- Browser Version
  - On Chrome, Version 117.0.5938.88
  - On Safari, Version 16.6 (18615.3.12.11.2)
- Platform (Andriod and Mac)

**Comment by roseundy** [comment]
dup of #9642 
Now fixed.
