### ISSUE TITLE
[Rolling Stock Stars] - Unable to bid on initial auction, interface unresponsive

### ISSUE THREAD

**Issue by nochindeluxe** [tobymao/18xx#9664]
Game id: hs_xtvpnipy_1695410257
Hotseat Game: https://gist.github.com/nochindeluxe/09c3038da2541f5fc70cdd7ee83bc8ed
Platform: Chrome version 117.0.5938.92 on Windows 10 on Desktop (also tested on Microsoft Edge and Chrome Mobile)

Steps to Reproduce:
1. Start a new hotseat game of Rolling Stock Stars with 3 players.
2. When the game starts, have the first player bid face value for any company by clicking the "Place Bid" button
3. Notice the game does not advance to the next player's turn.
4. Click the "Pass" button twice.
5. Notice the game advances to Player 2 but shows that Player 2 and Player 3 both passed on the auction, resulting in Player one purchasing the company for face value.

**Comment by roseundy** [comment]
Dup of #9642 
Now fixed.
