### ISSUE TITLE
[1877: Stockholm Tramways] Acquiring Company Exceeds Train Limit

### ISSUE THREAD

**Issue by Fellstone** [tobymao/18xx#9665]
Company RF acquires SST and gains 3 trains, taking RF to 7 trains, over the current 4 train limit.

https://18xx.games/game/134902?action=127

Not sure if allowed/intended by rules or an edge case caused by some suboptimal play on my part.

**Comment by scottredracecar** [comment]
Rules allow this, implementation is correct. Similar to 1862 in this respect.

**Comment by Fellstone** [comment]
Cheers. Thanks for the clarification.
