### ISSUE TITLE
[1861] RSR doesn't buy a train when it can

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#9666]
https://18xx.games/game/135689?action=433

RSR has no loans and exactly enough money to buy a 4, but doesn't do so.

**Comment by ollybh** [comment]
This is a bug in the check to see if the RSR could afford another train. The game was checking whether the RSR had *more* than the train's price, so if the RSR  had exactly as much cash as the train's price then it would not buy the train.
