### ISSUE TITLE
[18Chesapeake] Emergency Fund Raising Rules Inconsistency

### ISSUE THREAD

**Issue by joakley123** [tobymao/18xx#968]
When doing emergency fund raising to buy a train from another corporation, the game seems to allow you to sell more shares than necessary to purchase the train. The rules do not permit a player to sell more shares once they have enough funds to buy the train.

I believe the emergency fund raising would work better if it first asked you which train to buy (and at what price if buying from another corporation) and then allowed you to sell shares to reach the necessary funds.

**Comment by jenf** [comment]
Once you've sold more shares than needed to buy a train from another corporation then the option to buy trains from other corporations disappears.

The behavior is correct since we do not know which train the user will be purchasing, and making them undo would be painful

**Comment by joakley123** [comment]
I am confident something is not working correctly. For example, it was letting me sell 3 shares for $80 each and then buy from a train from another corporation for $1. This left money in the corporation that was purchasing the train, which is never supposed to happen (after emergency fund raising, the corporation buying the train should always have $0). 

Perhaps it is assuming that the train will be purchased from the other company at face value, but this is not required by the rules (the face value is simply the maximum that may be paid when doing emergency fund raising).

**Comment by jenf** [comment]
Do you have a game id?

**Comment by joakley123** [comment]
It was game 3063, but it may not help much since I performed an undo and manually corrected the problem. 

Basically, the cheapest train from the bank pool was $630, and I wanted to sell some shares and buy a cheaper train from another corporation (in order to provide the other corporation some additional funds). After selling the shares and choosing the train from another corporation, it was letting me choose seemingly any price (I did not check to see if it would allow me to choose more than face value).

Seems like the best approach is to choose the train and price before selling shares is permitted, or else have some requirement that the train must be purchased for some minimum value depending upon the amount from shares sold, cash on hand, and cash in treasury (and max value as face value of course).

**Comment by tobymao** [comment]
this can’t really be done because choosing a train happens when you buy it and you need the cash

**Comment by joakley123** [comment]
Maybe it would be possible to make the minimum price for purchase from another corporation go up whenever shares are sold. For example, if the buying corporation had $100, the president had $100, and 2 shares were sold for $100 each, then the minimum purchase price would be $301 (and maximum price = face value). 

I guess the formula is something like:

Min. Price = treasury cash + personal cash after selling shares - price of last share sold + 1 

(this way it was necessary to sell that last share to meet the price of the train) 

The other concern to possibly look at is if the game is permitting players to sell enough shares to buy a train (say a D train) from a corporation that is more expensive than the cheapest one in the bank (I guess a 5 or 6 in this example).
