### ISSUE TITLE
[1870] - wrong number of arguments

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#9681]
game [#132739](https://18xx.games/)

In the Stock Round, after selling a share to get under certificate limit, the error wrong number of arguments given +2 and expected +0 (or something like that) appears when clicking done, then the game reloads/refreshes.

**Comment by OedipussyRex** [comment]
Don't know if this is relevant, but the game will progress for me when cloning the game and hot-seating.

**Comment by OedipussyRex** [comment]
Game was able to continue when another player turned off auto-pass.

**Comment by OedipussyRex** [comment]
Final note: the player who had the option to price protect was the player who had auto-pass turned on, which would explain why the problem didn't show up when hot-seating.

**Comment by philcampeau** [comment]
duplicate of #9321
