### ISSUE TITLE
1841 "cannot be continued due to GameError: Blocking step Buy Trains cannot process action 789"

### ISSUE THREAD

**Issue by summerjumbo** [tobymao/18xx#9682]
[1841] it showed the message:
We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 789
Broken action: { "type": "merge", "entity": "AFI", "entity_type": "corporation", "id": 789, "created_at": 1695378361, "corporation": "ICSF" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1841,%22needs%20triage%22) and include

**What's your Game ID?**

**How to Reproduce the Bug?**

will show later

**Which Browser / Platform?**

**Comment by summerjumbo** [comment]
https://gist.github.com/summerjumbo/955cd9a15d58a2370b8f6c66507c9400

**Comment by roseundy** [comment]
Looks like this should have been archived.

**Comment by philcampeau** [comment]
@roseundy are you saying this isn't actually a bug then?

**Comment by roseundy** [comment]
I need to double-check, but at first glance it seems to be a case that I somehow missed during my last deploy of '41 fixes.

**Comment by philcampeau** [comment]
@roseundy at this point, I'll assume this should be closed?

**Comment by roseundy** [comment]
Yes
