### ISSUE TITLE
[1868 Wyoming] Northern Spike trigger did not reward $120 bonus

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9683]
https://18xx.games/game/134745

**Comment by philcampeau** [comment]
Are you sure? The corp paid out $270, but it only hit $150 worth of stops. Seems like you got the $120 revenue bonus.

**Comment by michaeljb** [comment]
Yeah everything looks correct to me at https://18xx.games/game/134745?action=525
