### ISSUE TITLE
[18TN] Calculating revenue

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#9685]
Do I miss a rule in 18TN or is this a bug?

Revenue should be 200$, instead of 150$

the applying rule is found at rulebook page 8 (4.2.3)

https://18xx.games/game/135497

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by michaeljb** [comment]
From the log right before OR3.2:

> [12:48] -- Phase 3½ (Operating Rounds: 2 | Train Limit: 4 | Available Tiles: Yellow, Green) --
> [12:48] -- Event: Civil War! --
> [12:48] IC, L&N, SR each receive a Civil War token which affects their next OR

Per 5.1 in the rulebook, one train runs for $0; the worst train here is making $50, so the total from the other two, $150, is used

![Screenshot 2023-09-27 211932](https://github.com/tobymao/18xx/assets/1045173/b202778b-47c8-43ea-8816-b5dbbd0813ed)
