### ISSUE TITLE
Add margin in game

### ISSUE THREAD

**Issue by jonmorris** [tobymao/18xx#97]
Add margin:
1. To "Available Trains" {1rem 0 .5rem 0}
2. To "Remaining Trains" {1rem 0 .5rem 0}
3. Left of Buy buttons and number input & buy buttons (not between text input & buy buttons) {0 0 .5rem 0}
4. To Train selectors {1rem 0 1rem 0}

1, 2, 3:
![image](https://user-images.githubusercontent.com/3299032/79689229-6055f880-8221-11ea-88cc-f4b0fe419dfe.png)

4:
![image](https://user-images.githubusercontent.com/3299032/79689355-42d55e80-8222-11ea-99e3-66ad2bc17969.png)

**Comment by tobymao** [comment]
done
