### ISSUE TITLE
Line wrap causes train confusion

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#972]
The line wrapping on train purchases can be quite confusing. We had a player repeatedly try to buy the 3 train from the C&A but accidentally push the buy button for the 4 train from the bank. 

<img width="325" alt="Screenshot 2020-07-02 20 27 00" src="https://user-images.githubusercontent.com/8732435/86428765-672dcc80-bca2-11ea-957a-d6dd143bbff7.png">

This, on the other hand, is much easier to parse.

<img width="286" alt="Screenshot 2020-07-02 20 18 26" src="https://user-images.githubusercontent.com/8732435/86428848-980e0180-bca2-11ea-9e7a-f1f5d0f104e5.png">

**Comment by tobymao** [comment]
fixed
