### ISSUE TITLE
[22Africa] can run to tokened out gold mine city with e-train

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9729]
https://18xx.games/game/136639?action=463

It adds A20 to the route for some reason.

**Comment by benjaminxscott** [comment]
It *looks* like NAR isn't able to run past H12 to the south, so the gold mine token seems to be working as intended, is that accurate?

![image](https://github.com/tobymao/18xx/assets/1711810/ab613475-f9ed-4f1b-b394-99fe6ddd4228)

**Comment by scottredracecar** [comment]
I agree with the issue as reported. The routing is acceptable, but the E-trains should not count the 20 (should only earn revenue from tokened cities). If the +20 was in Nairobi replacing the NAR token, Nairobi doubled would be 30*2+20.
