### ISSUE TITLE
21Moon company name/logo updates

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#9733]
There are new corporation names for 21Moon, listed on p6 of the final rules.
https://boardgamegeek.com/filepage/263361/21moon-rules

Logos:
[21Moon.zip](https://github.com/tobymao/18xx/files/12834652/21Moon.zip)

**Comment by roseundy** [comment]
Old -> New:

ME -> SWP
MA -> HMQ
DSE -> VH
SM -> ITC
MV -> SSF
IPI -> LG
LP -> KR

**Comment by roseundy** [comment]
I will be doing a migration for this
