### ISSUE TITLE
[1868 Wyoming] Double-Head selection not working

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#9737]
The game is not allowing me to select my trains to Double-Head them per rule 8.6.8.  The trains aren't listed in the selection box and the button is protected.

**What's your Game ID?**

135078 

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by michaeljb** [comment]
https://18xx.games/game/135078?action=530

Everything looks fine to me there. Can you share a screenshot, or describe more specifically what you're seeing different from my screenshots below?? Also what browser and platform are you using?

Starting state:

![Screenshot 2023-10-08 125023](https://github.com/tobymao/18xx/assets/1045173/07634091-a86a-4236-9495-6224e7e95f05)

One train selected:

![Screenshot 2023-10-08 125155](https://github.com/tobymao/18xx/assets/1045173/b31abde7-cd51-47c6-8110-69fb85ce9c59)


With both trains selected:

![Screenshot 2023-10-08 125055](https://github.com/tobymao/18xx/assets/1045173/a8a1e612-5c59-4273-b4df-613689003a21)

**Comment by Rupre** [comment]
Michael,

The screen shot of what I see is attached.

Paul Hakken

**Comment by michaeljb** [comment]
Hi Paul, it looks like GitHub can’t get the email attachment so I can’t see your screenshot. Could you post it in a comment directly at https://github.com/tobymao/18xx/issues/9737 ?

What browser and OS are you using?

**Comment by Rupre** [comment]
Windows 11 and Chrome

![Screenshot 2023-10-08 203609](https://github.com/tobymao/18xx/assets/125107695/a682b1ba-a89d-40f8-a3fc-a22dc51e106e)

**Comment by Jay-Davis** [comment]
I tried Firefox and Edge and saw the same thing. The train selection is there and works, but it seems like the train numbers and boxes are displayed in white on a white background so you can't see them. If you select the area you will see them and you can select the trains if you click in the right spot.

**Comment by Rupre** [comment]
Although the trains are appearing white on white in the list and
are, therefore, invisible, I now know where to click to select them.  So I
am working around this issue.
