### ISSUE TITLE
Switch between invite-only and public table

### ISSUE THREAD

**Issue by stateless** [tobymao/18xx#9740]
**Switch between invite-only and public table**

Would be nice to be able to switch from an invite-only to a public table. 

If you want to play with more people, but don't have enough. This allows you to organise first, then when everyone is ready open the table up to other people. 

**Are there related ideas?**

Might be good to also allow the other option. Maybe someone joins and they want a friend, but the friend is not online yet.

**Comment by tobymao** [comment]
can just use the description for this
