### ISSUE TITLE
1846 3/5 train pay out

### ISSUE THREAD

**Issue by hast18xx** [tobymao/18xx#975]
![Bildschirmfoto vom 2020-07-03 19-29-06](https://user-images.githubusercontent.com/64490299/86489112-922c2500-bd63-11ea-95a2-310a1f88dd3c.png)

40-30-50-40 for 3/5 should be 120

**Comment by tobymao** [comment]
need more detail

**Comment by scottredracecar** [comment]
Holland - Port Huron - Detroit is the max run and is 120 rather than the
110 reported.

**Comment by tobymao** [comment]
you need to hit your token so 110 is the max payout.

**Comment by scottredracecar** [comment]
I assume this is GT running with 3x trains so that would include the Port
Huron token.

**Comment by tobymao** [comment]
we always include the ends, so if you don't want winsdor, don't run it

**Comment by hast18xx** [comment]
ah, understood

**Comment by scottredracecar** [comment]
A company with the mail will get short changed from not running Windsor.

**Comment by tobymao** [comment]
yes, i'm aware of that issue, and it's a problem with always including the
ends, but it's what we were talking about
