### ISSUE TITLE
[1822PNW] Backroom Negotiations should display correct Home hex in major company display

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#9751]
When Backroom Negotiations (B.N.) is used to re-assign an associated minor, and then the major company is formed, the major company's entity display should show the updated home hex, not the 'default' one.

Example: in this game I used B.N. to assign Minor 3 to the CMPS.  However, the CMPS's 'tile' still says "Home: Spokane (F23)".
https://18xx.games/game/136346?action=856

This is (a) wrong, and (b) confusing, because there is no other visual cue available to identify the home token (now in D11) on the map.

Suggest that when B.N. is used, the company tile should display the correct (for this game) home hex instead.

**Comment by michaeljb** [comment]
[136346?action=856](https://gist.github.com/michaeljb/b6ad71f59e83f3aab31742e159f9115a)
