### ISSUE TITLE
[1847AE] Double share/presidency disappeared after changing presidency

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9752]
SAAR was dumped in the beginning of SR10 onto the double share holder.  When this happened, the presidency or the double share disappeared.  

https://18xx.games/game/137498

**Comment by Galatolol** [comment]
I'm not able to reproduce this issue. Maybe it has been solved by one of my other fixes. Let me know if this happens again.

**Comment by ollybh** [comment]
Two months since @Galatolol said they couldn't reproduce this and no reports of the bug happening again, so closing this issue.
