### ISSUE TITLE
[1844] Regionalbahn can not buy 2H in first OR

### ISSUE THREAD

**Issue by kodemaniak** [tobymao/18xx#9754]
**What's your Game ID?**

https://18xx.games/game/137539

Link to Action: https://18xx.games/game/137539?action=76

**How to Reproduce the Bug?**

- Open a Regionalbahn in first SR
- Lay track and try to buy a 2H
- An error occurs, game reloads, no train was bought.

**Which Browser / Platform?**

Seems to affect all platforms.

**Comment by EddieRakete** [comment]
in the second OP the game couldn´t continue.

forced train buy situation 
buying train - not possible 
button done trains - not possible

the game was stuck.

**Comment by crericha** [comment]
It works in hot seat mode, so it must be a server side issue.

**Comment by EddieRakete** [comment]
Yes it must, because in another game it happened again just now:

https://18xx.games/game/137596

this time the regional needed to buy a 3 train and the game was stuck again

**Comment by crericha** [comment]
The fix will be live in about 10 minutes

**Comment by crericha** [comment]
It is live now. I see that 137539 was manually ended. If you like, you can reopen the game and it will play correctly.

**Comment by kodemaniak** [comment]
We ended it in OR2, so we can just start over, since in OR1 we already skipped the RBs due to the bug.

Thanks for the fix! 🙂
