### ISSUE TITLE
[18SJ] Cant sell shares to finance train

### ISSUE THREAD

**Issue by schizimo** [tobymao/18xx#9759]
I cant sell shares to finance buying a train. 
I get error code: ' undefined method 'all abilites' for <engine::player:schizimo>

Game  Id: 134547
https://18xx.games/game/134547

**Comment by ollybh** [comment]
This error is coming from this call to `Engine::Game::abilities` when `entity` is a player object, not a corporation.
https://github.com/tobymao/18xx/blob/45a1e5ba7d937eb188df25b4f11dc2f0114c77b6/lib/engine/game/g_18_sj/step/assign_gotakanalbolaget.rb#L25
