### ISSUE TITLE
Explain route payouts.

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#976]
1) When running a 3/5 or similar train in 1846, it isn't obvious which revenue centers are actually being counted.
2) When running a route with bonuses due to privates and/or tokens, there is no announcement as to the amount.

Suggest adding the amount of revenue from each hex next to the coordinates of the hex, and adding an extra item for route-level bonuses.

**Comment by dfannius** [comment]
I think this is effectively fixed with #1717. The only request here that is not implemented is to note the revenue for each stop, which I think might be too verbose. If people still have ideas for improving the new system, let's start a new issue with reference to the current design.
