### ISSUE TITLE
[1847AE] Nationalization should disable auto actions

### ISSUE THREAD

**Issue by magnusrk-ch** [tobymao/18xx#9764]
https://18xx.games/game/135768?action=310

1. nigelsandwich has auto pass enabled.
2. I nationalize one of nigelsandwich's shares.

Expected: nigelsandwich's auto pass is disabled
Actual: auto pass continues

In this case the player didn't seem to mind for whatever reason, but in the general case nationalization is *double* shenanigans. It gives the player money / share limit, and it is implicitly a sale.

It's less clear what to do about other people's auto actions, but I suspect the implementation will be much easier if we clear everyone, and I'm sure there are at least some cases where it does matter.

**Comment by Galatolol** [comment]
I'll fix that.
