### ISSUE TITLE
[1844] Purchasing share illegal action

### ISSUE THREAD

**Issue by TrainmasterYang** [tobymao/18xx#9767]
[1844] Purchasing share illegal action

https://18xx.games/game/137724

- During stock round 3. DumpsterPacific pars VZ at 70 SFR
- On DumpsterPacific second action in stock round 3 DumpsterPacific attempts to purchase a 3rd share share of VZ to float VZ. DumpsterPacific has 71 SFR cash. After making the action error reported "Illegal action.. refreshing page"
- Other players using master mode get same error

- Browser Version
  - Chrome version: 117.0.5938.150 (Official Build) (64-bit) (cohort: Stable) 
- Platform: Desktop

**Comment by benjaminxscott** [comment]
The game was ended, on hotseat it looks like the desired action works - maybe the game was out of sync on the client side?

![image](https://github.com/tobymao/18xx/assets/1711810/f557a11e-5d6e-406f-ab6c-392d3cea40f9)

![Screenshot 2023-10-12 10 41 40 PM](https://github.com/tobymao/18xx/assets/1711810/2f1b9802-5636-43df-9fa1-f5ceb69b810a)

**Comment by crericha** [comment]
@benjaminxscott The game was developed in hot seat mode. Its likely a bug with server mode (symbol vs string).

**Comment by crericha** [comment]
Or in this case, its a rounding issue (the other common server mode thing)
