### ISSUE TITLE
[1841] Merge Not Working

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9770]
Game ID: https://18xx.games/game/136628?action=1035

Issue: RSFS and CFCC want to merge. RSFS is president of CFCC with 20%, and CTDA is president of RSFS with 20%. Merge price of new corporation will be $242, CTDA has $274 which is enough to buy up to the new presidency.

On clicking 'form' an error alert comes up: "undefined method 'empty?' for []"

I previously indicated 'current move' for the game, but another participant noted that the bank was about to break so the merge probably doesn't matter, so I undid the initial merge move and passed merge. Game state immediately prior to merge error is linked above. There's also a fair bit of commentary in the chat discussing whether it should be a bug or not

**Comment by roseundy** [comment]
Typo: error message actually was: "undefined method 'emtpy?' for []"

emtpy => empty
