### ISSUE TITLE
[1880] - Premature ending of company operation when returning from stock round

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#9771]
Not my game, reporting for players of the game.

In [game #134025 ](https://18xx.games/game/134025?action=356)the HKR bought the last 3T, leaving the company with three trains (limit 4) and $0 in it's treasury going into the stock round. In the stock round, the HKR sold to 50%, gaining the rest of it's capitalization at the end of the round. Returning from the stock round, the HKR, now flush with $500 and space for another train, was not given opportunity to purchase a 3+3. Instead, the game moved on to the next company in the operations round.

**Comment by crericha** [comment]
Fixed
