### ISSUE TITLE
1841 one less company available

### ISSUE THREAD

**Issue by summerjumbo** [tobymao/18xx#9778]
in #137121 and some previous 1841 games, i found AFI or AFTA lost in the game after the purchase of the first 4 train.

**What's your Game ID?**
#137121
https://18xx.games/game/137121

**How to Reproduce the Bug?**

I heard a player that this kind of bug occurred when there was no Tuscan merge.
**Which Browser / Platform?**

**Comment by summerjumbo** [comment]
https://gist.github.com/summerjumbo/b5a53a198ce44a332dc1d9a6490e4984

**Comment by roseundy** [comment]
Wow. Skipping the Tuscan merge removes AFI. This should be interesting to debug.

**Comment by roseundy** [comment]
Old code left over from when I had a dedicated "holding" corp instead of just choosing next available unopened corp.

Would affect play only in the most rare of occasions.

**Comment by mouseworthy** [comment]
Hi, we encountered this issue again in https://18xx.games/game/137894
The issue occurred on Sun 22/10, the game started on Sun 15/10; not sure if that means we'd be on a version without the fix?
