### ISSUE TITLE
[1880] autopass when player has P5 and company already has a D permit

### ISSUE THREAD

**Issue by Lime-Turtle** [tobymao/18xx#9791]
https://18xx.games/game/135632?action=620

During phase D, at the start of a companies operating turn it was given the option of passing or skipping track lay.
No explanation of why

It had a CD permit, and I had the D permit private: the pass was to not give the company the D permit.  Shouldn't need the option, and if the option is given then it needs to be explained.

Android

**Comment by philcampeau** [comment]
Nothing in the rules prevents a player from assigning the P5 D permit to a company that already has a permit for D. It's silly, and I don't see any reason why you _would_, but the site is correct to give players the option, as the rules are written.

**Comment by Lime-Turtle** [comment]
OK, in which case it would be nice for the UI to tell the player what it is
that they are bing invited to do or pass.
I saw no clues about it being the D permit.
S

**Comment by philcampeau** [comment]
Agreed. What will be difficult is that the programming only stops there because it recognizes there is an ability that could potentially be used. It's not a specific call for that private. I'm not sure how to fix it, though I'm sure someone will have an idea.

**Comment by benjaminxscott** [comment]
IMO it's OK to skip the assignment step in that case, since it's a no-op (and from a player's POV, less confusing)

**Comment by slapphappyjazz** [comment]
This is related to [https://github.com/tobymao/18xx/issues/9296](url) - "Jeme Tien Yow Engineer Office prompts for assign step when company already has D permit".
