### ISSUE TITLE
1844 Handling of SBB shares. ID: 137304

### ISSUE THREAD

**Issue by Lime-Turtle** [tobymao/18xx#9792]
(https://18xx.games/game/137304)

It seems that 5% shares are valued at 50% of SMP, but should be full (and 10% share should be twice SMP, but are treated as SMP).

Player portfolios do not clearly indicate share holding split (5% vs 10%)

In this game I had 2*5% and 2*10% shares.  In an SR I was given the opportunity to sell 5, 10, 20 or 30%.  But I was not allowed to sell 15% or 25%.  (I didn't intend to sell any, I was merely checking the implementation)

**Comment by philcampeau** [comment]
> It seems that 5% shares are valued at 50% of SMP, but should be full (and 10% share should be twice SMP, but are treated as SMP).

This is correct, and seems to be a mistake in the code.

> Player portfolios do not clearly indicate share holding split (5% vs 10%)

Perhaps a better approach would be to treat 5% shares as 1 cert, and the 10% shares as double certs, like the ones in 1849, 1847 AE, and a couple of others.

**Comment by crericha** [comment]
I'm open to double certs, but I don't understand how that will help if you have two of them? How will you know?

**Comment by crericha** [comment]
Partially fixed by #9807. The shares have the correct value now, but the sell share interface is still weird.
