### ISSUE TITLE
18NL - NFL cannot lay track

### ISSUE THREAD

**Issue by SharpDressedDan** [tobymao/18xx#9794]
https://18xx.games/game/137071

I was able to place a tile (#8 with rotation 2 on B13) in OR 1.1, but I have not been allowed to lay a tile since then.  I was able to upgrade the tile to green, but I cannot lay another tile.  

Running Safari 15 on iPad

**Comment by philcampeau** [comment]
This isn't a bug. The way you've laid track, you can't trace a route out of B13. 

![image](https://github.com/tobymao/18xx/assets/26125362/b2c7228e-fa84-42f8-8c6f-5b2cbe5c0b93)

This is one of the challenges of NFL, either you build to that little town and you have a run in its second OR, or you build south and develop a better route.
