### ISSUE TITLE
[18USA] Cannot proceed with game

### ISSUE THREAD

**Issue by mdeaville1** [tobymao/18xx#9798]
**What's your Game ID?**
135262

https://18xx.games/game/135262?action=368

**How to Reproduce the Bug?**
"We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 369
Broken action: { "type": "pass", "entity": "NP", "entity_type": "corporation", "id": 369, "created_at": 1697659125 }"

Cannot end my turn and proceed to the next player. Now I am unable to restart my turn either. 

**Which Browser / Platform?**

Same issue on Chrome and Android.

**Comment by DestrinStorm** [comment]
Our game (https://18xx.games/game/135262) is showing as blocked still, is there a release cycle to push this change live or is a different change needed to unstick the error?
