### ISSUE TITLE
[1844] Laying a tunnel to destinate sometimes skips token lay step.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9799]
https://18xx.games/game/138389?action=574

FNM lays a tile, then lays a tunnel, leaving it with less than 100 SF. The game skips the token lay step before giving FNM its destination funds. The FNM should receive its funds immediately and be allowed to lay a token.

**Comment by volker18xxdev** [comment]
I've asked the designer (helmut Ohley), He said: After laying a Track, all destinationsroute have to be checked and if the ckeck is true, then pay out the second half of the companymoney, which destinationroute is completed.
This has to be done before Tokenphase!
