### ISSUE TITLE
Running trains enhancements

### ISSUE THREAD

**Issue by jonmorris** [tobymao/18xx#98]
Would be great to create a little train card that displays:

Train number
Train status (has/hasn't run)
Train income (if it has run, how much did the route earn)

Optional:
Train image (just a little visual enhancement), I'd keep it to a square icon like the company icons for now.

**Comment by Tin-Whisker** [comment]
This is a good suggestion, maybe also color code the train with the color of the route.  

I would also like to see a summary after an OR of what each company ran for.   This is helpful stock purchase decisions among others.

**Comment by gchambers419** [comment]
I agree with the above suggestions, and add two more:

1.  Display the list of selected hexes the train will visit, including any flaws (e.g., too long.)
1.  In addition to graying the track not reachable from any station, once a route is started, gray track that the current route can't include (blocked by station.)
