### ISSUE TITLE
1836jr Paris and the Channel Ports should be green/brown, not yellow/brown

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#980]
Paris and the Channel Ports shouldn't have a bonus value in the yellow phase.

**Comment by jenf** [comment]
Good catch :)

**Comment by perwestling** [comment]
@ChrisTheCat: I think this has been deployed. Please check that it looks good.

**Comment by ChrisTheCat** [comment]
Looks good, I like the colors.

p.s. would still rather they had some graphic that was different from a
regular offboard.

**Comment by jenf** [comment]
that's another issue
