### ISSUE TITLE
Show share percentage in games with mixed share percentages

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9801]
The following game state is not represented in the UI:
Who owns 10% or 5% shares of the SBB. (This actually goes for all titles honestly. If I own 20% of a company, I would like to know how many certs I have of that company. Is it one share of a 5-share company? Two shares of a ten share company? A president's cert and two ordinary shares of a 20-share company?)
~~Which Bergbahn payout schedules are available and which are used.
How many Bergbahn and Tunnel private companies are available (during an OR).~~ See #9803 and #9804

**Comment by crericha** [comment]
Applies to any game with mixed cert percentages

**Comment by crericha** [comment]
@physic please spin-off the 1844 specific requests into separate issues each, so they can be closed as each is addressed.

**Comment by physic** [comment]
Done, thanks. #9803, #9804

**Comment by crericha** [comment]
Thanks!

**Comment by volker18xxdev** [comment]
A simple Solution: 2.1 notation. 
1. multiple Certificates like the 20% director-certificate or 10% SBB certificate
2. dot
3. simple certificates (10% or 5%)

i.e. CGR in 1856, the director has 8 Shares but a 10% Directorcerticate and 6 5%-Certificates. displayes as: 2.6 

the player has to add the two number, to see the total number of shares.
