### ISSUE TITLE
[1844] Manually tracing routes is abysmally slow.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9802]
https://18xx.games/game/138389?action=1140

Attempting to trace a route from Lyon to Muenchen, I had to wait 5-15 seconds in between selecting the next stop along the route. Not sure if it is getting reset by other players taking actions or chatting, or if there is just some awfully inefficient calculation happening on each stroke.

**Comment by physic** [comment]
There is an exponential time calculation happening on each stroke. The time to select a city roughly doubles with every new city I select. It still happens in a locally cloned game as well.

**Comment by crericha** [comment]
The base code for E trains is really bad. I remember doing something in 18NY to improve performance. I'll try to apply here too.
