### ISSUE TITLE
18EU Bug in Minor-Exchange Round

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#9805]
Game: https://18xx.games/game/134796
Player Ulli want's to merge the Minor 10 into the FS.
![grafik](https://github.com/tobymao/18xx/assets/80693707/4f21b5f1-f497-41bc-84b0-72ae5f932712)
after hitting the Button, an error occurs:
![grafik](https://github.com/tobymao/18xx/assets/80693707/5048b215-f860-4007-bbfc-cb6ed796182e)
there's no way to continue the game.
-->

**Comment by l33twash0r** [comment]
Game; https://18xx.games/game/137099 samething is happening to me in this game

**Comment by l33twash0r** [comment]
Hmm looks like the bug was only when I tried to exchange for market shares. Exchanging for IPO shares worked fine
