### ISSUE TITLE
Many games are 'stuck' tonight; can't reach Market screen in another game

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#9809]
Many games are being reported on the site tonight as 'stuck'.   Games hang on "Loading game...", including two of mine:
https://18xx.games/game/138543
https://18xx.games/game/137958

In addition, this game will not go to the Market screen, it just does nothing (in Hotseat (cloned) mode too?!?) : 
https://18xx.games/game/136363?action=1255

Also, perhaps related, maybe not, I've noticed lately that autorouting takes a veerrrrrry long time, even for simple routes with small trains.  Sometimes even a single train will time out.

**Comment by roseundy** [comment]
The first game listed has this error: "undefined method `info' for nil" - this is on the first action.

**Comment by waaayback** [comment]
interesting. that game was just started...  I think it's stuck on the first action

**Comment by arcanor** [comment]
https://18xx.games/game/137506
1844 game hangs after clicking Market tab.
