### ISSUE TITLE
Market Tab is not working 1880

### ISSUE THREAD

**Issue by ClosetOtaku** [tobymao/18xx#9811]
**What's your Game ID?**

This bug affects all games, both archived and current, from observation.

-->

Go to an 1880 game (past or current).  Click on the "Market" tab.  The game will not show the Market.

Multiple platforms (Mobile, Browser)

-->

**Comment by waaayback** [comment]
I also reported this as part of #9809 earlier

**Comment by arcanor** [comment]
1844 game has same problem during OR1. Click on Market tab, nothing happens, game hangs.
https://18xx.games/game/137506
