### ISSUE TITLE
1844 destination payout should precede token placement?

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#9813]
**What's your Game ID?**](https://18xx.games/game/137425)

I think that the payout from a destination completion should precede token placement. 

In this instance (https://18xx.games/game/137425?action=151) the NOB has connected to it's destination and jumped over token placement and gone straight to run trains. I was expecting to be able to token D15 before running trains using the money from destinating.

I took a look at the rules and it doesn't specify when the payment is made, but Destination Hexes are described in section 1 of the OR (page 11). This section precedes section 2 "Place a station marker" so it seems implicit the payment comes during the lay track segment.

I see someone has mention this on BGG, so perhaps this has already been raised/addresses? 

Cheers

Chris

**Comment by crericha** [comment]
Dup of #9799

**Comment by Chrisozwa** [comment]
Ah, thanks.
