### ISSUE TITLE
1825 withholding stuck the game

### ISSUE THREAD

**Issue by andycted** [tobymao/18xx#9815]
https://18xx.games/game/134033

The game got stuck and reopening it won’t work 

last thing was withhold

**Comment by roseundy** [comment]
action=529

**Comment by roseundy** [comment]
This looks like it is related to a company closing

**Comment by roseundy** [comment]
Is it possible that this is the first time anyone bankrupted a company?

**Comment by roseundy** [comment]
Need to fix `acting_for_entity` to handle an unowned corporation.

**Comment by andycted** [comment]
> Is it possible that this is the first time anyone bankrupted a company?

possibly, I didn't notice but it is a possibility - i.e. no one bankrupted before this

**Comment by roseundy** [comment]
I meant in the entirety of 1825 play on 18xx.games.

**Comment by andycted** [comment]
wo-hooo ! more seriously, really ? I thought I've probably done before, but maybe I'm mixing 1860 with 25...
