### ISSUE TITLE
[1836JR30]_Teleporting minor can't place token

### ISSUE THREAD

**Issue by rainmight** [tobymao/18xx#9818]
**What's your Game ID?** https://18xx.games/game/137779

**How to Reproduce the Bug?**
- During Operating Round 6.1 the NORD is trying to TP out of its bad position
- The TP destination of the (Charbonnage du Hainaut) is J8
- JCL just happened to have already laid the track and a token spot is open on it
- Game won't let me put the token when I push the minor button. The tile will light up and that's it.

**Which Browser / Platform?** 
Chrome [Version 118.0.5993.89)

**Comment by philcampeau** [comment]
The private ability requires the owning corp to do both the tile lay and the token, which means that if someone has already laid that tile, the ability is forfeit. Confirmed in this thread on BGG about the same ability in 1830: https://boardgamegeek.com/thread/1013512/article/12977878#12977878

If that is the case, it could be worth clarifying the text of this private and the Delaware & Hudson in 1830 to say that the corp must first lay a straight yellow city tile and then may station token.

**Comment by philcampeau** [comment]
Updated private text to clarify this issue in pull request #9820
