### ISSUE TITLE
[1844] Game cannot be continued: Cannot buy a share of SBB

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9823]
I reviewed completed game 138389 to verify the fix for #9801, and was presented with the following error. Not sure if there was an intentional breaking change, or if this is an actual issue.

We're sorry this game cannot be continued due to GameError: Cannot buy a share of SBB
Broken action: { "type": "buy_shares", "entity": 12794, "entity_type": "player", "id": 930, "created_at": 1697764796, "shares": [ "SBB_9" ], "percent": 5 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1844,%22needs%20triage%22) and include this link (https://18xx.games/game/138389?action=929)

**Comment by crericha** [comment]
The SBB share fix broke this game and it was archived. It's amazing that you caught the game in the broke state. It couldn't have been more than 2 minutes between when the new code was deployed and this game was archived.

**Comment by physic** [comment]
Not entirely coincidence. I probably saw the ticket resolved notification and immediately went to check.

**Comment by crericha** [comment]
That makes sense. I went the 1849 direction. This is what it looks like now:
![image](https://github.com/tobymao/18xx/assets/67359577/52f592c9-8d8e-4de2-b8b2-2f41675c6b28)
