### ISSUE TITLE
[1840] Dividend payout is not limited to Revenue

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#9825]
**What's your Game ID?**
https://18xx.games/game/136326

https://gist.github.com/benjaminxscott/f15deff30698e0698c92405555888e7a

**How to Reproduce the Bug?**
- During the "Company Round 2 - Pay or Withhold Dividends" a player can set the payout amount
- Interface suggests: "Select dividend to distribute to shareholders, between 0 and 100. Leftover will be withholded to corporation.", and the maximum value is pre-filled in the text form.
- The rules state that the Dividend paid must come from the Revenue pile (so maximum of 100 in that case)
- The interface allows you to fill in any number (even more than the total Treasury!)

**Comment by benjaminxscott** [comment]
Looks like we aren't restricting that value

![image](https://github.com/tobymao/18xx/assets/1711810/2bede6b9-fbd7-4dfb-a0f7-b5f84ac580e5)
