### ISSUE TITLE
1841 transcorporation train purchase by EMR(illegal action)

### ISSUE THREAD

**Issue by summerjumbo** [tobymao/18xx#9832]
[1841] SFTN could buy a train by EMR from another corporation as the "first" train of the step
while the rule 4.5 says "it must perform Emergency Money Raising[4.5.1] described below, and must buy the cheapest train available from the Bank."
In this case, SFTN had no money so that it had to buy an 8 train from the bank buy spending the presidents money(and stocks).

**What's your Game ID?**
https://18xx.games/game/137894

**How to Reproduce the Bug?**

When you copy the game, you can do the same at OR 5.1(of3)

**Which Browser / Platform?**

**Comment by roseundy** [comment]
https://18xx.games/game/137894?action=789

**Comment by roseundy** [comment]
Missed a check in process_buy_train

When this fix is deployed, your game will have to be invalidated because mouse should have bankrupted. If you "undo" before the illegal train purchase and wait for the deploy, the game could be continued.
