### ISSUE TITLE
1841 no token on city(illegal)

### ISSUE THREAD

**Issue by summerjumbo** [tobymao/18xx#9834]
While playing a clone game, I just found a corporation might lose all of its city token.
The 1841 rule 4.4 says "A Corporation's last remaining city token cannot be bought,"

**What's your Game ID?**
A clone game from https://18xx.games/game/137894
to be added below

**How to Reproduce the Bug?**

You can see the situations No tile/token actions are allowed and the corporation is free from holding a train..

**Which Browser / Platform?**

**Comment by summerjumbo** [comment]
here's gist:
https://gist.github.com/summerjumbo/124b96527e2fe9b943f71b91ebfdd4a2

**Comment by roseundy** [comment]
Forgot to exclude passes when seeing if a corp can sell it's last placed token
