### ISSUE TITLE
[1844] Error when buying first 6 train

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9835]
https://18xx.games/game/137293?action=528

Trying to buy a train results in this error:

<img width="633" alt="Screenshot 2023-10-27 at 11 27 42" src="https://github.com/tobymao/18xx/assets/8732435/0bbf62f4-8d89-48e8-804c-41cafab6c213">

**Comment by vman55** [comment]
I encountered the same message trying to buy a 6 train. I don't know what EMR in the title is supposed to mean. If it is shorthand for 'emergency fundraise', that doesn't apply in my case as the company has enough cash in the treasury to by the train.
