### ISSUE TITLE
1822Africa share price moves right when sold out

### ISSUE THREAD

**Issue by vandamm** [tobymao/18xx#9837]
Sold out corporations should not have their price move right at SR end. 

https://18xx.games/game/139207?action=460

**Comment by benjaminxscott** [comment]
Not sure why the price is moving, as the requisite flag is set to false
https://github.com/tobymao/18xx/blob/eec356acb8f41f903d84ed2da906d7ba51c50657/lib/engine/game/g_1822_africa/game.rb#L52

**Comment by vandamm** [comment]
@benjaminxscott it was moving because I did a custom `finish_round` and forgot about it
