### ISSUE TITLE
[1844] Once assigned, the EVA 5H can't be transferred to another company.

### ISSUE THREAD

**Issue by vman55** [tobymao/18xx#9845]
In game #137866 ([1844]) the player assigned EVA to MOB as a workaround to the not-completely-fixed bug regarding buying the first 6 train, intending to have JN buy it later. This is allowed according to the BBG 1844 forum, but the 18xx game doesn't make it available for purchase.

EVA is not like the permanent 5H that comes with the SBB.

**Comment by crericha** [comment]
Eva isn't marked as unbuyable, but since it isn't in the depot, it wasn't being shown in possible trains to buy.
