### ISSUE TITLE
[1848] making COM operational with tile lay = no action buttons

### ISSUE THREAD

**Issue by Sleipmaersk** [tobymao/18xx#9847]
**What's your Game ID?**
138835
https://18xx.games/game/138835

**How to Reproduce the Bug?**

https://18xx.games/game/138835?action=278
If action 279 is placing tile #8 on F11 connecting F9 and E12
Still active players turn but no action buttons
COM becomes operational with the tile lay

**Which Browser / Platform?**
- Platform
Windows 10
- Browser
Google Chrome

- Browser Version
Google Chrome	118.0.5993.118
- Platform
Desktop

**Comment by Johnnyboyb** [comment]
I have had the same issue on game ID 137730
OR4.2 company VR trying to place tile #57 on F17 (Syndney) - I tried different combinations as follows
1. #57 in F17 - no action button to skip 2nd tile lay - after any 2nd tile lay a message popped up (didnt get the exact message) said something about blocking COM and could not process action.
2. First lay tile #235 in F15, then tile#57 in F17 - this allowed tile laying step to complete, place token step was skipped (insufficiant money) then no action buttons.

I progressed the game with a different tile lay

**Comment by coranstow** [comment]
Observed again, Game 139227. 
Buttons for next actions weren't displayed.
Entering a comment causes error an error banner with "conflicting actions" and revert to the state after the tile was placed.
Errors were occurring before COM was floated.
No action completing SYD-ADL works.

**Comment by pedropp001** [comment]
Same problem when I try to connect Sydney to Adelaide laying #6 at G16
Game Id: https://18xx.games/game/139242
