### ISSUE TITLE
18ZOO new features

### ISSUE THREAD

**Issue by serpentium** [tobymao/18xx#9848]
Hi, i uploaded new manual version on bgg (vs 10) so here the new features to implement.

three FAQs to check against code
- si può upgradare in verde una traccia inserita con ANCIENT MAPS nello stesso OR
- Work in Progress says it blocks Wings, but it separately says the blocked tile can be opened by upgrading to a tile with two station spots. So if you upgrade to two spots and token the non-blocked one, is wings still blocked? no, can fly over the new tokened station
- verificare che GREEK + PASSA TURNO fa ancora rimanere il giocatore in SR

NEW FEATURES
- add brown nr47,nr44,nr39
- add green nr20,nr16
- change the number of yellows to x13 nr9, x7 nr7, x18 nr8
- change price of MIDAS and GREEK from 2$ a 1$ 
- enforce the new rule (6.2.1 Avoid the “wait-sell in order tecnique”): a non-president selling the same share in the same SR doesn't push down reputation more than the first time (just once). If the player selling it is the president, reputation goes down as usual (even more than once)

**Comment by carlorusso1984** [comment]
> si può upgradare in verde una traccia inserita con ANCIENT MAPS nello stesso OR
yes - public/fixtures/18ZOO/or_power.ancient_maps.json

> Work in Progress says it blocks Wings, but it separately says the blocked tile can be opened by upgrading to a tile with two station spots. So if you upgrade to two spots and token the non-blocked one, is wings still blocked? no, can fly over the new tokened station
yes - public/fixtures/18ZOO/or_power.work_in_progress.can_be_ignored_by_wings_if_not_unique.json

> verificare che GREEK + PASSA TURNO fa ancora rimanere il giocatore in SR
no - Greek cannot be executed without taking any action

> add brown nr47,nr44,nr39
yes - lib/engine/game/g_18_zoo/map.rb

> add green nr20,nr16
yes - lib/engine/game/g_18_zoo/map.rb

> change the number of yellows to x13 nr9, x7 nr7, x18 nr8
yes - lib/engine/game/g_18_zoo/map.rb

> change price of MIDAS and GREEK from 2$ a 1$
lib/engine/game/g_18_zoo/entities.rb

> enforce the new rule (6.2.1 Avoid the “wait-sell in order tecnique”): a non-president selling the same share in the same SR doesn't push down reputation more than the first time (just once). If the player selling it is the president, reputation goes down as usual (even more than once)
done
