### ISSUE TITLE
[1858] terrain costs are being ignored

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#9849]
https://18xx.games/game/138730

I should have paid $20 out of hand here but it was free.

**Comment by ollybh** [comment]
This is the correct behaviour. L13 is V&J's home hex, so it does not pay terrain costs when laying a tile there.

See the fifth paragraph of section 9.3 of the rules:

> A Private Company does not pay terrain costs for its home
> hexes, but its player-owner must pay for any other terrain costs
> and extra builds. A Public Company must pay for terrain costs,
> even if it owns the relevant Private Company.

**Comment by BellmakerSA** [comment]
Missed that section, my apologies
