### ISSUE TITLE
[18NY] unable to continue game

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9857]
https://18xx.games/game/138171?action=452

Clicking "Done (Trains)" results in this error:

<img width="1440" alt="Screenshot 2023-11-05 at 11 57 24" src="https://github.com/tobymao/18xx/assets/8732435/83e8a29f-d314-4e28-9b2f-49b710277ff1">

**Comment by KenBoucher** [comment]
Same issue. https://18xx.games/game/140008

**Comment by crericha** [comment]
@ChrisTheCat the wrong game is linked. Can you please update?

**Comment by ChrisTheCat** [comment]
I edited the link in the original post

**Comment by crericha** [comment]
Thanks!
