### ISSUE TITLE
[1858] Token from private railway can be placed in unreserved Madrid slot

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#9858]
https://18xx.games/game/137962

In the final closure round, the M&A folded into the A and the A took the token in Madrid - but it was the wrong slot in Madrid i.e. north rather than southeast.

**Comment by ollybh** [comment]
What's happened here is that the M&V private railway has closed without having its token slot in Madrid taken taken, leaving an unreserved slot. Later, in the private closure round, the M&A is taken over by A, and A is allowed to token its slot in Madrid.

The error occurs when the token is placed in Madrid. The code is checking that the slot chosen could be tokened by A: in this case, either M&V's reserved slot, or the unreserved slot in the north of the city. The check needs to be that it is the reserved slot.

I've had a fix for this ready for a couple of weeks (72e1ab855b9c28e8), but there's a related bug that also needs fixing. If there's an unreserved slot in Madrid and one of the other Madrid privates is used to start a major company then this can be started in the incorrect slot. This uses a different code path, so the fix needs to be made more general to cover this case as well.
