### ISSUE TITLE
[1848] - uniting Sydney/Adelaide causing the game to no longer allow further actions

### ISSUE THREAD

**Issue by jacobmnixon** [tobymao/18xx#9871]
Placing any track that unites Sydney and Adelaide in our current game (https://18xx.games/game/138496) or my hotseat copy (https://18xx.games/hotseat/hs_llkcknfi_138496) is preventing the player placing that track from proceeding further. The status shows that you are in the token laying stage but there is no option to skip laying a token and clicking a valid token location does nothing.

![image](https://github.com/tobymao/18xx/assets/150188419/7dbed828-1468-4dbb-8359-8738755003fd)

Tried on Chrome through Windows Desktop
Tried on Safari through iPhone

**Comment by jacobmnixon** [comment]
looks to be the same as https://github.com/tobymao/18xx/issues/9847

**Comment by benjaminxscott** [comment]
dupe of #9847
