### ISSUE TITLE
[18NY] Undefined method "auto_actions" for nil

### ISSUE THREAD

**Issue by gloinul** [tobymao/18xx#9875]
**What's your Game ID?**
https://18xx.games/game/137835

Game deadlocked and refuses to go forward. Tried loading this in two different browsers both reporting the error and not moving forward. 

<img width="1296" alt="Screenshot 2023-11-08 at 08 52 51" src="https://github.com/tobymao/18xx/assets/11295323/e7ef7c6b-2c8b-4116-9c8e-874e1e4ce385">

**How to Reproduce the Bug?**

Don't know. 

**Which Browser / Platform?**

Safari: Version 17.1 (19616.2.9.11.7) on MacOs
Firefox 119.1 (35574) on iOS. 
Chrome Version 119.0.6045.123 (Official Build) (arm64)

**Comment by Akado05** [comment]
This also happened in game [137698](https://18xx.games/game/137698), after a player's train buying step where they could choose to salvage 0-2 4H trains.  Regardless of the choice, when they clicked [Done (trains)], the same error was seen.

**Comment by crericha** [comment]
It's fixed, but hasn't been deployed yet.

**Comment by crericha** [comment]
dup of #9857

**Comment by gloinul** [comment]
Thanks @crericha
