### ISSUE TITLE
[1850] I sold five shares of MILW and the stock price did not decline. Game Id 132733 - Still broken!

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#9878]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by andrewzwicky** [comment]
`Current version: deployed at Wed Nov 01 2023 22:54:47`

The latest code had not been deployed yet.  You can check the about page to see if it has been updated.

https://18xx.games/about

**Comment by Rupre** [comment]
Are you saying the fix has not yet been deployed?  If so, when should I try
to sell the shares again?  In other words, when will the fix be deployed?

**Comment by andrewzwicky** [comment]
Correct, I believe it has not been deployed yet.  I don't know when the deployments happen, so you'll have to wait and check back.

**Comment by Rupre** [comment]
Ok, thanks for the update.

**Comment by benjaminxscott** [comment]
Dupe of #9659

Fwiw deployments aren't scheduled on a cadence, it's whenever a maintainer with deployment permissions has time
