### ISSUE TITLE
[1850] game broken

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#9884]
https://18xx.games/game/137789?action=416

just have a look

we can't even end the game

**Comment by andrewzwicky** [comment]
Looks like this is a consequence of https://github.com/tobymao/18xx/pull/9865.  In the old game, WLG did not close until CBQ bought a 5 train, which means KATY got one extra stock round of income from WLG, which it used to redeem shares.  When the private was updated to close at at the correct timing, KATY is missing this extra $20, so the action fails.  Not sure if the game can be pinned to the old version.

**Comment by andrewzwicky** [comment]
| New                                                           | Old                                                         |
| ------------------------------------------------------------- | ----------------------------------------------------------- |
| KATY lays tile #14 with rotation 2 on I4 (Omaha)              | KATY lays tile #14 with rotation 2 on I4 (Omaha)            |
| KATY (WLG) lays tile #9 with rotation 0 on I10                | KATY (WLG) lays tile #9 with rotation 0 on I10              |
| **Western Land Grant Company closes**                         |                                                             |
| KATY passes place a token                                     | KATY passes place a token                                   |
| ...                                                           | ...                                                         |
| -- Operating Round 6.2 (of 2) --                              | -- Operating Round 6.2 (of 2) --                            |
| UP collects $10 from Gant Brothers Construction Company       | UP collects $10 from Gant Brothers Construction Company     |
| RI collects $5 from Great River Shipping Company              | RI collects $5 from Great River Shipping Company            |
| RI collects $10 from Mississippi River Bridge Company         | RI collects $10 from Mississippi River Bridge Company       |
| NP collects $15 from Mesabi Mining Company                    | NP collects $15 from Mesabi Mining Company                  |
|                                                               | **KATY collects $20 from Western Land Grant Company**       |
| MILW collects $20 from Mississippi and Missouri Railroad      | MILW collects $20 from Mississippi and Missouri Railroad    |
| mb1898 collects $10 from Crédit Mobilier                      | mb1898 collects $10 from Crédit Mobilier                    |

**Comment by philcampeau** [comment]
That's a bummer, I put the 'pins' tag on the pull request, but maybe this game got missed. 

As far as I know, if the game is already bugged, we can't roll back to pin it.
