### ISSUE TITLE
1850 game broken by recent patch

### ISSUE THREAD

**Issue by arcanor** [tobymao/18xx#9886]
https://18xx.games/game/138564?action=562

Apparently related to https://github.com/tobymao/18xx/pull/9865

**Comment by andrewzwicky** [comment]
I think what's happening here is that in the previous game logic, WLG was closing earlier.  This means that on the original play through, the game could automatically advance to run routes after the initial track lay.  In this new logic, the WLG is still active, so the game is expecting the player to either use the WLG power or Pass (Track).  In a cloned game, I was able to Pass (Track), and then run the exact same route.  I suspect you could resolve this by undoing, passing, then recreating the same actions, but it would be pretty annoying depending on how far past that point you are.

**Comment by benjaminxscott** [comment]
Issue is the player can't undo since the state is broken, so we'd have to back out the broken action on the server-side game state

**Comment by andrewzwicky** [comment]
Ok, I'm not very familiar with recovering like this, but I saw the undo button in the game, so assumed they could undo the broken action and proceed.

**Comment by philcampeau** [comment]
Unfortunately, alpha games don't get pinned when updates are done.
