### ISSUE TITLE
[Rolling Stock Stars] dividend step throws error

### ISSUE THREAD

**Issue by dirksteiner66** [tobymao/18xx#9888]
**Game ID**
138858

https://gist.github.com/benjaminxscott/063ba50d1a4c376838f4eb794d2506f0

**Link**
https://18xx.games/game/138858

**How to Reproduce the Bug?**
Due to the behavior described in the title, I'm not in a position to contribute any further information.

During Turn 6, closing everything went well.  Currently it's my turn for dividends (T6).

**Which Browser / Platform?**

Checked on:
- Chrome Version 119.0.6045.124
- MS Edge Version 119.0.2151.44

**Comment by benjaminxscott** [comment]
fix incoming, game should be able to progress after the commit is deployed

**Comment by roseundy** [comment]
What, exactly, is the bug?
