### ISSUE TITLE
Allow users to hide intro text

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#989]
It would be nice if players had a toggle in their profile to auto hide the intro text on the home page (the paragraphs that begin "18xx.games is a website where you can play..." This would save some scrolling to get to the rest of the page.

**Comment by ChrisTheCat** [comment]
Even better, you could auto hide it for anyone who has played 5+ or 10+ games or something like that.

**Comment by benjaminxscott** [comment]
I like the idea of games being accessible w/o scrolling on mobile/desktop, could tweak the [page layout](https://github.com/tobymao/18xx/blob/master/assets/app/view/home.rb#L16) to surface active games at the top when the user is logged in

Would you be interested in making a mockup / PRs for that?

**Comment by tobymao** [comment]
i think it's simple, if the user has any games, don't show the intro

**Comment by 8bg** [comment]
Was there a regression that removed this functionality? On mobile the intro text continues to show for me. I simply hide it with uBlock Origin, but am I missing a setting? @tobymao
