### ISSUE TITLE
[1846] "Broken action" when reviewing finished game when not logged in

### ISSUE THREAD

**Issue by Drealmer** [tobymao/18xx#9894]
Multiplayer online game. Finished properly but can only be reviewed when logged in. Throws an error when not logged in.

https://18xx.games/game/137762?action=134

```
We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 133
Broken action: { "type": "buy_shares", "entity": 12711, "entity_type": "player", "id": 133, "created_at": 1697533045, "shares": [ "NYC_2" ], "percent": 10 }
```

This only seems to happen when the link to the game is opened when the player is not logged in. It works fine when logged in.

Tested with Firefox, Chrome and Safari. Same behavior on all three browsers. Only tested on desktop.

Note : something unusual happened in this game, TWO companies closed (share price down to zero). No idea if related or not.

Backup of the JSON : https://gist.github.com/Drealmer/fa9ccc44925e207613efeece111b60e6

**Comment by benjaminxscott** [comment]
Looks like the Penn was being thrown into bankruptcy, but the logic didn't close it for some reason. 

It doesn't seem to be a 'recent patch broke the logic' issue since the game successfully finished 5 hours ago @ Monday, November 13, 2023 12:20:24 PM UTC 0

**Comment by michaeljb** [comment]
Neither ERIE nor PRR take any actions on their last turn before closing, I'm pretty sure the fact two companies are closing on a single action is significant.
