### ISSUE TITLE
[18Tokaido] GameError: Blocking step Sell then Buy Shares cannot process action 120

### ISSUE THREAD

**Issue by tduchow** [tobymao/18xx#9902]
**What's your Game ID?**
https://18xx.games/game/138029

**How to Reproduce the Bug?**
https://18xx.games/game/138029?action=119
 It just says sorry this game cannot be continued. Only actions this SR4 have been buying shares.

**Which Browser / Platform?**
Chrome: 119.0.6045.124

**Comment by doubt72** [comment]
Fix for #9839 broke a bunch of games.  I'm working on a fix.
