### ISSUE TITLE
Discord Webhook Issue with Underscores

### ISSUE THREAD

**Issue by BlobfishXL** [tobymao/18xx#9904]
**How to Reproduce the Problem?**

My Discord handle is "@Miguel____" with 4 underscores. When I enter that into the Webhook User ID box on the profile settings page and send a test message, the message is addressed to "@Miguel__" with two underscores, despite still having four underscores when I check the 18xx site where I entered it. . 

Copy pasting the message I get:
"<@miguel__> This is a test notification from 18xx.games."

**Which Browser / Platform?**
WIN 11 Chrome 

<html>
<body>

Google Chrome | 119.0.6045.125 (Official Build) (64-bit) (cohort: Control)
-- | --
Revision | b9e5b8a154549bb57a57b9c822607bc3289fc5b9-refs/branch-heads/6045@{#1231}
OS | Windows 11 Version 22H2 (Build 22621.2715)
JavaScript | V8 11.9.169.6
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

</body>
</html>

**Comment by BlobfishXL** [comment]
Update: this appears to be an issue with discord. ____ returns two underscores (that are underlined) regardless of how text is entered.

**Comment by philcampeau** [comment]
This is an issue on discord's end. Discord uses surrounding underscores to mean "put this in italics", so it reads your username as miguel__ with the two underscores in italics. 

I don't think there will be a fix to be done on our end, but you can probably work around it by putting 6 underscores in the webhook id box.
