### ISSUE TITLE
1844 unoperated shares sell for wrong amount when sold in bundles

### ISSUE THREAD

**Issue by RandallNlsn** [tobymao/18xx#9916]
Game ID 141495 [1844]

At the 0931 mark, player Wyobadger sold three shares of company STB (a company not yet operated). The game correctly only dropped the stock price one row, from 100 sfr to 90sfr. However, player Wyobadger only received 210sfr after selling three shares (3 x 70) instead of 270sfr (3 x 90). 

Per rules, player should receive the amount for each share sold based on where the stock lands (in this case, 90).

Thank you!
Randall N

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
This will be implemented the next time the site is updated.
