### ISSUE TITLE
The "Join the 18xx Slack" link doesn't work.

### ISSUE THREAD

**Issue by EdPovi** [tobymao/18xx#9920]
**How to Reproduce the Problem?**
When I click on the link to 18xx Slack on the main page, I get an error message from the Slack website that says:

> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

I am looking reach out about bringing a game to 18xx.Games, Slack seems to be the location to reach out, but the link is broken. 

**Which Browser / Platform?**
- Browser: Chrome, Version 119.0.6045.160 (Official Build) (64-bit)
- Platform: Desktop)

**Comment by benjaminxscott** [comment]
https://18xxgames.slack.com/

**Comment by EdPovi** [comment]
> https://18xxgames.slack.com/

This link doesn't work.  I get the following email reply when I try to use that link:

> It looks like there isn’t an account on 18XX tied to this email address.

**Comment by EdPovi** [comment]
I found the new link to Slack in the commit.  I can confirm that I was able to join Slack using the updated link.
