### ISSUE TITLE
[1844] Dumping SBB presidency exchanges 10% presidency for 15% SBB

### ISSUE THREAD

**Issue by ZakisanGithub** [tobymao/18xx#9921]
**What's your Game ID?**

https://18xx.games/game/139599?action=816

**How to Reproduce the Bug?**

In Stock Round 9, JonasWZ sells stocks in SBB causing a presidency change. The 10% SBB presidency is exchanged for a 10% double cert and a 5% single cert. Note that Ocki previously owned 7\*5%=35% of SBB and only owns 6\*5%=30% of SBB after the sale. On the other hand, JonasWZ has a 5% certificate too much after the sale.

If JonasWZ instead sells all shares in SBB, he does not receive any shares back, but Ocki still loses a 5% too much, causing 5% of SBB to disappear completely.

**Which Browser / Platform?**

- Firefox Desktop (can look up version at home, but probably irrelevant since it is about game logic)
- Mobile: Android Opera

**Comment by DarthIA** [comment]
This may be related with what we have experience in our game https://18xx.games/game/138072 where a player bought a share from SBB market after its formation, obtaining the presidency as result and now even he should have 25% of shares, he got less dividends that the former president.

**Comment by arcanor** [comment]
Similar thing happens, breaking our game:
https://18xx.games/game/141652?action=812

old President has 35% and sells 5 single (5%) shares. should end up with 10%, but instead has 2x double shares (20%)

new president had 30% including 2x double (10%) shares and 2x single (5%) shares. ended up with president and 4 shares total (which the game counts as 20%)
