### ISSUE TITLE
[1894] Unable to upgrade Paris from Green to Brown despite having accesss, money and browns broken.

### ISSUE THREAD

**Issue by TheTagoreler** [tobymao/18xx#9926]
**What's your Game ID?**
https://18xx.games/game/141544#info
**How to Reproduce the Bug?**
What steps cause the unexpected behavior?
On current action, PLM is running.  PLM has a token in Paris and tokens outside Paris.  Unable to upgrade Paris to Brown.  Other cities are upgradable to brown as expected (Brussels already brown).  PLM has money in the treasury to pay for terrain costs.

![image](https://github.com/tobymao/18xx/assets/78515638/429a9e70-4a0c-4f3f-a255-1cebcb35b081)
![image](https://github.com/tobymao/18xx/assets/78515638/8b72999e-6e0c-47c8-b6b9-d09a9c1252a5) - working as intended

In master mode, I skipped ahead to Est (also unable to upgrade Paris) and another player who did not have a token in Paris (CFOR) and there was similar behaviour
![image](https://github.com/tobymao/18xx/assets/78515638/ed7d215c-0b64-49e3-9c9c-7be83410116b)

**Which Browser / Platform?**
Present both on iOs (Chrome) and windows 10/Firefox.

**Comment by Galatolol** [comment]
Thank you for the detailed description, I'm looking into that.
