### ISSUE TITLE
[1848] can't pass to end stock round

### ISSUE THREAD

**Issue by arcanor** [tobymao/18xx#9928]
Game keeps saying auto actions don't match and reverting my pass. I've tried master mode. I've tried enabling/disabling all kinds of auto actions. The game won't let me pass.

Notably, if I clone the game, it works just fine, so I'm guessing the auto action that doesn't match may be one of the other players' auto pass, and not mine. But there's no way for me to Master Mode and disable their auto pass actions.

https://18xx.games/game/139515

**Comment by arcanor** [comment]
guessing maybe has to do with recent patch: https://github.com/tobymao/18xx/pull/9892

**Comment by DrPooter** [comment]
Game [142482](https://18xx.games/game/142482) also having this issue.
