### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Hepworthnot** [tobymao/18xx#9947]
1822  GameError: Blocking step Bid, convert concession or buy/sell shares cannot process action 288

https://18xx.games/game/142202?action=287

**How to Reproduce the Bug?**

<!--
What steps cause the unexpected behavior?

Not sure - game just stopped with error message.

**Which Browser / Platform?**

Chrome Version 119.0.6045.160 (Official Build) (64-bit)

- Platform (Mobile, Tablet, Desktop)

Surface Pro

**Comment by dpbackes** [comment]
We had this happen as well https://18xx.games/game/136063

**Comment by michaeljb** [comment]
Fixed by #9948
