### ISSUE TITLE
Handle multiple train-rusting types

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#995]
In some 18xx (e.g. 1824, 18SJ, 1846 variants) several different train types can rust/obsolete train types.

As it is right now only one type can be specified as value to "rusts_on" or "obsoleted_on".

My suggestion is to change this to a list of strings, instead of string, or alternatively support both.

Info table should show all types that are rusted, separated by a comma.

**Comment by jaysachs** [comment]
I was just in that code ... changing the "Phases out" and "Rusts" columns on the Info page to include all variants would be straightforward. Actually changing how the variants are modeled seems like a much deeper change, and of unclear value.

Is your main request here that the Info page show all the variants in those two columns?

**Comment by tobymao** [comment]
@perwestling so in those games there are multiple train cards that trigger a rusting?

right now even though rusts_on refers to one thing, it can map to multiple variants

**Comment by perwestling** [comment]
@tobymao: Yes, there are a couple of 18xx where you can buy several new train types, which does rust the same train type. 
So e.g. 1824 the G trains can be rusted by both newer G trains and some T trains.
In 1846 both the 5 and the 4/6 will phase out the 2s and the 6 and 7/8 will phase out the 4 and 3/5.
Now I cannot see that 1846 information in the info page so I assumed that were a variant that were not shown for the base game.

I tried to put multiple values for rusts_on (both ["D", "E"] and "D,E") but in both cases None is shown in the Rusts column in the Info page.

So my main idea would be to add support for specifying multiple values in rusts_on by using comma between values. Not sure there are any need for this in obsoleted_by but that could probably be added in the same way.

As this might not be needed for current supported games at 18xx.games I guess I could try to fix this.

**Comment by tobymao** [comment]
5 and 4/6 and 6 and 7/8 are the same trains. this case is already handled.

**Comment by perwestling** [comment]
@tobymao: I could do a variant similar to 1846 to solve my need in this case, so I will close this ticket.

Not sure it would be enough for 1824, but in that case a new issue can be opened.
