### ISSUE TITLE
[1850] Able to sell only 1 share for Emergency Train Funding when >80% held

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9950]
https://18xx.games/game/140935?action=683

Rule 10.7.2
if the president is forced to sell a share in a company that he owns more than 60% of and the stock is not in the coloured portion of the stock market  (green or brown), he must sell down the the 60% limit.

If you clone the above game, Joshua6 is able to sell 1 share of the Rock Island in OR7.2 when emergency funding his train instead of being forced to sell down to 60%.

**Comment by philcampeau** [comment]
This is simple enough, the code already exists in 1870. I'll port it over here.
