### ISSUE TITLE
split auto routing as a tool for offline-players

### ISSUE THREAD

**Issue by GTMDTTKP773** [tobymao/18xx#9953]
The auto routing tools are the best 18xx calculator I have seen on internet. I wanna to be able to use it in sandbox mode, where I can freely add tracks, stations as I like. And to calculate the route under that circumstance. It will helps us a lot when we play it offline because to calculate all income manually is too complex especially in the late phase.

**Comment by crericha** [comment]
That's not something we are looking to do as part of 18xx.gamea; however the code is open source and any are welcome to make such a tool.
