### ISSUE TITLE
[1836jr56] "Wrong number of Arguments" when laying track on a minor

### ISSUE THREAD

**Issue by saxafras** [tobymao/18xx#9954]
https://18xx.games/game/142824

"Wrong number of Arguments" error when attempting to lay any track

**Comment by benjaminxscott** [comment]
Not able to repro on hotseat

**Comment by philcampeau** [comment]
"Wrong number of arguments" errors won't trigger in hotseat, since hotseat just runs the js code, which doesn't care how many arguments are given. You need to import the game and run it locally in your test environment.
