### ISSUE TITLE
1822PNW token problem

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9956]
https://18xx.games/game/137608?action=1143

CPMS does not have a token, and even if it did, it doesn't have the money to play a token.

<img width="451" alt="Screenshot 2023-11-29 at 4 43 43 PM" src="https://github.com/tobymao/18xx/assets/8732435/0f4e1584-236c-4721-ade8-94c5417d437a">

**Comment by benjaminxscott** [comment]
I suspect that the token step is treating exchange tokens as 'placeable' since they're free (Based on `5.10`), but they can only be placed during a merger so that shouldn't cause this step to block
