### ISSUE TITLE
Sometimes after viewing another user's profile, one user appears to be logged in as another

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#9959]
* cannot send messages or create games as the other user
* the `Profile (username)` link in the top right shows the other user, and that user's display settings are loaded

> 12:34:33 Martin2D: also, i dunno if you saw, but ive been randomly logged into a different user's profile twice in the past 2 days
> 12:47:38[michaeljb](https://18xx.games/profile/97)Martin2D re: different profile--hadn't heard of that, we definitely need an issue for that. Do you know which users? Having their IDs might be helpful
> 12:51:13[Martin2D](https://18xx.games/profile/207)it happened both times when i checked a random user's profile
> 12:52:02[David](https://18xx.games/profile/1753)I had the same thing happen a few days ago, but not able to reproduce.
> 12:53:21[Martin2D](https://18xx.games/profile/207)yesterday it showed RadBadsomething?'s. Today was Ken Boucher
> i couldnt do anything to their profile, but it said Profile (Ken Boucher) instead of Martin2D
> 12:54:35[michaeljb](https://18xx.games/profile/97)Couldn't do anything to their profile, but logged in as them? Could you send messages as them?
> Could you make new non-hotseat games?
> 12:56:19[Martin2D](https://18xx.games/profile/207)no, just the change in the appearance of the screen via their settings
> and the profile showing as theres in the top right
> 12:56:47[David](https://18xx.games/profile/1753)yes, that's what I experienced as well
> didn't get to test it beyond that

**Comment by tobymao** [comment]
this is due to the cache, it's simply caching the view, but you're not actually logged in
