### ISSUE TITLE
[Harzbahn 1873] Incorrect route generated by "auto-route", can't run D-train

### ISSUE THREAD

**Issue by SirYaro** [tobymao/18xx#9963]
**Desc
1) Incorrect route for blue 3Ta train
2) Can't set any correct route for D train (this may be due to our not fully understanding the rules) and can't continue without it.

**What's your Game ID?**
https://18xx.games/game/142149?action=1138

**How to Reproduce the Bug?**
ad 1) Just click Auto
ad 2) set route for diesel - getting "Concession route not run by diesel train", set no route for D - getting "must run concesion route with diesel train"

**Which Browser / Platform?**
Win/Linux
Firefox/Chrome/Edge
![Screenshot_20231203_134527_resized](https://github.com/tobymao/18xx/assets/5879723/5cdd46ce-7cb1-40ed-b134-5e2321747579)
![Screenshot_20231203_134556_resized](https://github.com/tobymao/18xx/assets/5879723/fb56d79b-e352-4c1b-87f9-9e23bf05de28)

**Comment by SirYaro** [comment]
@tobymao any word of explanation why this was closed?
The game is clearly blocked.

**Comment by tobymao** [comment]
don’t use auto routing, it’s not guaranteed to work

**Comment by SirYaro** [comment]
Fair enough @tobymao - I thought algorithm can be somewhat tweaked base on this case. But, as you said, is not a big deal.

But what about the second issue? The player is not able to run D-train to finish his turn. 
Whatever route he chooses, it's always described as "Concession route not run by diesel train". If he tries to skip D-train all together, he gets an error:
"must run concesion route with diesel train".

It's a deadlock to us...

**Comment by SirYaro** [comment]
> please file a new issue just for that as a bug thanks

#9965 opened, thank you.
