### ISSUE TITLE
[1844] Wrong certificate swap after change of presidency of SBB

### ISSUE THREAD

**Issue by dmunozdelapena** [tobymao/18xx#9971]
**What's your Game ID? 138072

https://18xx.games/game/138072

https://18xx.games/game/138072?action=635

What steps cause the unexpected behavior?

- During stock round 6

AlbertoMCS | *d 4
dmunoz | dd 4
DarthIA | d 2

- dmunoz bought a SBB share. 

AlbertoMCS | ddd 6
dmunoz | * 3
DarthIA | d 2

Wrong share swap leads to wrong share values. It should say

AlbertoMCS | dd 4
dmunoz | *d 5
DarthIA | d 2

**Comment by philcampeau** [comment]
Seems related to #9921

**Comment by crericha** [comment]
Dup of #9921
