### ISSUE TITLE
HSM allowed to token Arnhem & Nijmegen before NBDS has done so

### ISSUE THREAD

**Issue by andypymont** [tobymao/18xx#998]
In the 1836Jr30 game in the below gist, the NBDS had floated but not yet operated. The HSM is able to lay the green Arnhem & Nijmegen hex and to token, which in turn stops the NBDS from being able to do anything. (As I understand it, HSM should be able to lay the tile but not to token.)
https://gist.github.com/andypymont/50350cbe13a3dcd4d7136397cca5502f

(Possibly related to #896 ?)

**Comment by jenf** [comment]
dup of #896
