### ISSUE TITLE
[18NY] unable to sell share

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9981]
https://18xx.games/game/142142?action=533

beardbru is unable to sell a share of NYC. There are only 4 shares in the market.

**Comment by crericha** [comment]
One of the selling restrictions is 
> There may not be more shares in the Bank Pool than are held by players

Currently players hold 5 shares and the bank pool has 4 shares. If beardbru were to sell, it would violate the above restriction, so he cannot sell.
