### ISSUE TITLE
Update Rules Links

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#9982]
I uploaded new rules files to BGG (currently in GeekMod, probably will be approved/live by 12/7).

Game rules links should be updated to those files.

- 1822PNW
- 18GB
- 18NY
- 18SJ
- 18Texas
- 21Moon

**Comment by crericha** [comment]
Please update with the links when they are through moderation. Thanks!

**Comment by scottredracecar** [comment]
18Texas [boardgamegeek.com/filepage/269592](http://boardgamegeek.com/filepage/269592)
18NY [boardgamegeek.com/filepage/269593](http://boardgamegeek.com/filepage/269593)
18SJ [boardgamegeek.com/filepage/269594](http://boardgamegeek.com/filepage/269594)
18GB [boardgamegeek.com/filepage/269595](http://boardgamegeek.com/filepage/269595)
1822PNW [boardgamegeek.com/filepage/269597](http://boardgamegeek.com/filepage/269597)

**Comment by philcampeau** [comment]
Still waiting on 21Moon rules

**Comment by philcampeau** [comment]
@scottredracecar Any reason 21Moon is still listed as beta? as far as I can recall there haven't been any bugs in ages

**Comment by scottredracecar** [comment]
I don't really keep track. Okay with me, but Steve should do it.
