### ISSUE TITLE
[1850] Land Grant issue 1850 ID 143225

### ISSUE THREAD

**Issue by RandallNlsn** [tobymao/18xx#9985]
**143225**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by vandamm** [comment]
@RandallNlsn what is the issue?

**Comment by philcampeau** [comment]
I'm going to close this since the reporter hasn't replied in close to 3 months and the game was ended.
Likely, the issue was related to the fix in #10417
