### ISSUE TITLE
[18IrelandUnable to buy correct trains when Emergency Buying

### ISSUE THREAD

**Issue by Whompratt** [tobymao/18xx#9992]
**What's your Game ID?**

Game ID is: [144034](https://18xx.games/game/144034)

If you look at action [2754](https://18xx.games/game/144034?action=2754), you can see that WKR enters emergency buy, and has the option to buy either a 3H' from the bank, or a 10H from the bank. If WKR opts to buy the 3H', then...
If you look at action [2763](https://18xx.games/game/144034?action=2763), you can see that MRNCC does not have the same option, with only the 3H' available from the bank pool.

**How to Reproduce the Bug?**

In this specific instance, two public corporations were forced to emergency buy one after the other. When this happened, the first corporation in the order had the option to buy either a 3H' from the bank pool, or the last 10H. When the second corporation came to the emergency buy, even with a 10H in the bank pool, there's no option to buy it.

This _might_ be intended behaviour, but I think it's a bug, given 18Ireland specifices you can buy any train from the bank pool during e-buy, even more expensive ones.

**Which Browser / Platform?**

Chrome, stable, 119.0.6045.200

**Comment by philcampeau** [comment]
As per rule 6.10, if a corporation can afford a train in the bank pool, no Emergency Fund Raising occurs. In your case, WKR couldn't afford any trains, so it entered EMR. On the other hand MRNCC had enough to buy the 3H', so it cannot do emergency funding. 

![image](https://github.com/tobymao/18xx/assets/26125362/0eb42ec0-91e7-4b1b-8e17-142ce7b69f11)
