### ISSUE TITLE
1822PNW - Error when using Backdoor Negotiations private company to start the NP with minor #10

### ISSUE THREAD

**Issue by ScottDrone** [tobymao/18xx#9993]
Hotseat game, link to gist below.  hs_tbfiipjl_1702122331

Firefox, latest version.

(https://gist.github.com/ScottDrone/0bab3ae3e205e2e7106466efba718a96)

Player started minors 6 and 10 with Backdoor Negotiations private #20.  Brought Backdoor Negotiations into the 10 minor and selected the Northern Pacific to be the associated major.  This results in both the home and destination for the NP to be Tacoma, this doesn't appear to be explicitly forbidden by the rules.

Attempting to merge the 6 and 10 resulted in an error, undefined method 'owner' for nil

![PNW Error](https://github.com/tobymao/18xx/assets/105426708/2edfb837-f7e6-43f1-b892-7bfcbea845fb)

**Comment by ChrisTheCat** [comment]
In the rule book on page 11 in section 4.7.2 appears this note.

<img width="1016" alt="Screenshot 2024-01-26 at 7 12 51 PM" src="https://github.com/tobymao/18xx/assets/8732435/6991b2c7-7c71-421f-980a-fac89fa88ae6">
