### ISSUE TITLE
18Mag + expansion “A company cannot run routes with the engineer”

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#9996]
https://18xx.games/game/144021?action=54

https://gist.github.com/benjaminxscott/23a8340b2f92fd57415aee8a56426dd3

The program doesn’t allow company 5 to run the route with Magyar Államvastutak, that adds +1 range to 2 train.

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment]
Expansion rules indicate that each supporter can only be used once per OR 

It looks like the private has to be manually used on the 5's turn for it to apply to its train

On the 5's turn the private wasn't used

https://18xx.games/game/144021?action=54

In the case of the 11, the private was manually used so it gave the benefit

https://18xx.games/game/144021?action=81

**Comment by benjaminxscott** [comment]
reopened since it sounds like this is a bug rather than a rules clarity issue
