### ISSUE TITLE
Game: 18FL - 143924 game hung up

### ISSUE THREAD

**Issue by richpri** [tobymao/18xx#9998]
Game: 18FL - 143924 

**How to Reproduce the Bug?**
Multiplayer Game link: http://18xx.games/game/143924

[07:49] richprice: @saxafras @LeeGamer The games seems to be hung up. I believe that my turn should be over. 
What should we do?
[12:35] saxafras: i mastermoded it and NO ONE can par the Plant.

**Which Browser / Platform?**
Chrome - Version 119.0.6045.199 (Official Build) (64-bit)
Ubuntu
rich@richdesktop:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by benjaminxscott** [comment]
On hotseat, it looks like the player `richprice` must click the Plant and choose to start it as a 5 or 10 - share company, is that action possible in your game?

**Comment by saxafras** [comment]
I see.  They need to reclick on the company...Thanks so much!

    Le dimanche 10 décembre 2023 à 14:41:15 UTC−9, Benjamin Scott ***@***.***> a écrit :  
 
 


On hotseat, it looks like the player richprice must click the Plant and choose to start it as a 5 or 10 - share company, is that action possible in your game?

**Comment by benjaminxscott** [comment]
Glad to hear it worked - We could probably make that flow a bit more clear
